### ISSUE TITLE
Search/Create UI Improvment

### ISSUE THREAD

**Issue by redbassett** [wit-ai/wit#100]
When using the search/create box for an instance, the "No Items!" response when searching is confusing, as if the user doesn't realize that they are searching, it looks like all the other instances just disappeared.  Some form of visual indicator that a search is happening would be useful (or maybe the results could drop down from the search box rather than replacing the list below?).

**Comment by martinraison** [comment]
Apologies for the very late reply :) I'm not sure this is relevant anymore. Closing, but let me know if I'm wrong
