### ISSUE TITLE
bulk update keywords?

### ISSUE THREAD

**Issue by devvtms** [wit-ai/wit#1000]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
*question*

hi! its possible update keywords with array of values through api?
i use yet ` POST https://api.wit.ai/entities/$ENTITY_ID/values` but looks like that is only for single value...

**Comment by patapizza** [comment]
Hi @devvtms,

It is possible to replace all the values using [PUT /entities/$ENTITY_ID](https://wit.ai/docs/http/20170307#put--entities-:entity-id-link).

Hope this helps.
