### ISSUE TITLE
Leading 0 for wit/number entity is stripped

### ISSUE THREAD

**Issue by vdisawar** [wit-ai/wit#1003]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
This is a bug

**What is the current behavior?**
We are collecting 5-digit zip codes from users. Some zip codes have leading zeroes and wit/number entity strips out the leading 0, invalidating the valid zip code a user may have entered. We have tried to train this entity to accept leading 0's for 5 digit numbers but it still doesn't work.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Type in 05467 and have your wit app use the wit/number entity

**What is the expected behavior?**
If I enter in 05467 for my zip code, the wit entity value for number should return 05467 and not 5467.

**Comment by patapizza** [comment]
Hi @vdisawar,

The numeral value for "05467" is 5467. To capture leading zeros, you can pass the `verbose` flag to `true` and look into the `_body` key:

```json
{"_text":"living in 05467","entities":{"number":[{"confidence":1,"value":5467,"type":"value","_entity":"number","_body":"05467","_start":10,"_end":15}]}}
```

Hope this helps.
