### ISSUE TITLE
wit. ai with facebook 

### ISSUE THREAD

**Issue by ysterysys** [wit-ai/wit#1005]
Hello , 
new to this .. i'm trying out Wit.AI with facebook developer .. i had follow the tutorial in Wit.ai  created the chatbot .. When im integrating with facebook messager... it mentioned to enable NPL in FB .. however , im not able to find the call back URL ... please help

**Comment by patapizza** [comment]
Hi @ysterysys,

Here is the documentation on how to enable Built-in NLP: https://developers.facebook.com/docs/messenger-platform/built-in-nlp#enabling_nlp

Hope this helps.
