### ISSUE TITLE
Feature request: order samples by time DESC

### ISSUE THREAD

**Issue by zhanpengli** [wit-ai/wit#1009]
hi, Can the training statements of wit. Ai be shown in chronological order? just like that below
![image](https://user-images.githubusercontent.com/32571006/37631192-82444290-2c23-11e8-9ef6-d5c8bb4f2436.png)

**Comment by zhanpengli** [comment]
By the way, what is the maximum number of training sentences under value? thanks

**Comment by l5t** [comment]
Seems like a great idea. Let me see if we can do it soon

**Comment by l5t** [comment]
I don't think we have a max number of training sentences

**Comment by zhanpengli** [comment]
ok, that's great, looking forward to your good news, thank you @l5t

**Comment by zhanpengli** [comment]
@l5t  hey, I want to ask one more question here, which is the limit of the number of queries, now is 280 characters, is it possible to have more?

**Comment by zhanpengli** [comment]
if wit.ai can show the number of training statements that will be helpful :)
![image](https://user-images.githubusercontent.com/32571006/37814249-f4ea2a9e-2ea3-11e8-9146-03c378d97b6b.png)

**Comment by zhanpengli** [comment]
@patapizza  Perhaps my statement is incorrect, I mean whether you can show the number of sentences I have added on the interface, , because I need to know how many sentences I have added. thanks :)

**Comment by patapizza** [comment]
Ha got it!

**Comment by blandinw** [comment]
Thanks to @aforaleka's great work on shipping this end to end, we have a new `Samples` tab that shows your app's samples, with the newest samples first.

You can read more @ https://medium.com/wit-ai/all-your-app-samples-at-a-glance-c4d6dbefeca3
