### ISSUE TITLE
Question mark changes confidence

### ISSUE THREAD

**Issue by khwstech** [wit-ai/wit#1011]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug

**What is the current behavior?**
In WIT the confidence level it shows when adding a question mark to end changes. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Type in WIT
What does the W stand for?
and
What does the W stand for
the confidence level is quite different. Question marks shouldn't change the confidence value.

Also
What is Mobil1?
And
What is Mobil 1?
space between mobil and 1 makes the entity fail. Would like it to return same entity. Training isnt working

**What is the expected behavior?**
Question marks shouldnt make an impact on the entity

**What is the App ID where you are experiencing this issue (if applicable)?**
59945ded-a991-458b-9458-1ea934a685af

**Comment by patapizza** [comment]
Hi @khwstech,

Re confidence, I get `0.984` with the question mark and `0.993` without. That's not such a big difference.

Looking at your `intent` entity, it seems like you'd need another entity to capture things like `Mobil 1`, `synthetic oil`, `viscosity` and group all the `what is xx` type of samples under a same value `whatIs` (same for all values; try to reduce them by grouping together the ones where the sentences are similar, i.e. the user intent is the same).

Feel free to reopen once you've tried that and you'd like us to get another look.

Hope this helps!
