### ISSUE TITLE
Detecting composite entities with only space as separator

### ISSUE THREAD

**Issue by Breci** [wit-ai/wit#1014]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
A bug
**What is the current behavior?**

![Current behavior](https://i.imgur.com/4Dy7z1Y.png)
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
The app has been trained to detect "item" that can contain "wit/number"(optional) and "product"(freetext and keyword). There can only be one number and one product in one item.
The bug occurs in a specific occasion : when we have an item followed by another item with a "wit/number" as its first member. Wit group them in a single item since there is no real separator like a coma or word between them. 
If there is any separator other than a space, the items are properly detected.

**What is the expected behavior?**
![Expected behavior](https://i.imgur.com/5cABIPc.png)
Wit should split each items like this
**What is the App ID where you are experiencing this issue (if applicable)?**
5a8af317-0012-40c9-ba10-04bcb10a27f0

Issue posted after exchanging by email with Laurent from your team.

**Comment by patapizza** [comment]
Thanks for reporting @Breci!

This is a specific case of https://github.com/wit-ai/wit/issues/1007.
