### ISSUE TITLE
Import data to already created Apps.

### ISSUE THREAD

**Issue by vladikus10** [wit-ai/wit#1017]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Feature
**What is the current behavior?**
Currently you can make a back up of your app and technically remove/modify the entity files.
**What is the expected behavior?**
Some bots may share a lot of behavior (for example: small talk topics) with each other, however currently there is no way to add that behavior to an existing app. As far as I know, the only way to combine the current app with a shared behavior is to export it, manually merge the files and then create a new app from that data, which is not a very convenient way.

**Comment by hactar** [comment]
You can also use the wit API to post entities, post samples, etc into an existing app (https://wit.ai/docs/http/20170307). This may be more convenient then using the import system, especially since it isn't reliable at the moment (see #513).

**Comment by vladikus10** [comment]
@hactar Oh, I actually never thought of it.

**Comment by patapizza** [comment]
Hi @vladikus10,

We still have collaborative entities on our [roadmap](https://medium.com/wit-ai/community-update-february-2018-d6a25c93827f) (https://github.com/wit-ai/wit/issues/266). Stay tuned!

In the meantime, you can use the API as @hactar suggested.
