### ISSUE TITLE
Datetime enitie in Greek

### ISSUE THREAD

**Issue by doc1991** [wit-ai/wit#1018]
The app id is: 5a6a4543-f047-46de-919c-6ff4c50548 Suddenly happens this 
![screenshot from 2018-03-25 17-32-43](https://user-images.githubusercontent.com/15673602/37876285-cd13752e-3052-11e8-8e0a-ed51151f6aa8.png)

Thanks in advance

**Comment by patapizza** [comment]
Hi @doc1991,

Can you copy the example in all letters here? It will be easier to reproduce than from the screenshot.

**Comment by doc1991** [comment]
βάλε ξυπνητήρι στις 12:00 το βράδυ

**Comment by patapizza** [comment]
Thanks.

`wit/datetime` is powered by [Duckling](https://github.com/facebook/duckling).
The issue here is that evening is defined between 6pm and 12am exclusive the next day. As a result, "12" and "in the evening" don't intersect.

This is an edge case - I've added an internal bug for this.
