### ISSUE TITLE
Arabic prefix should not be recognized as a part of entities 

### ISSUE THREAD

**Issue by mohamed-okasha** [wit-ai/wit#1019]
I think this a Bug or Something changed in wit rule based entity extractor .

In the past, when i was training wit on sentences and select partial of words without prefixes, wit success recognize this part of word not the whole word; For Example:  
word="بالفانيلا" [prefix="ب"+"ال" so the stem of this word "فانيلا"]

When select this part of word "فانيلا" and binding with custom entity, wit recognize "بالفانيلا" as "فانيلا"

**What is the current behavior?**
When select partial of words without prefixes like this "بال" wit will not recognize this word as suggest create new entity "بالفانيلا" The whole word!

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1) Write Expression "بالفانيلا" then select last 6 characters ("فانيلا" without "بال") and create new entity this name foo, sure verify this 
2) Nothing Just rewrite sentence again wit well recognize the whole word

**What is the expected behavior?**
Wit Recognize the partial of word "فانيلا" without prefix "بال"

[Note]
If repeat this with prefix "ال" wit will recognize the partial of word as we expected :) but no with "بال"

App ID: 5904c764-29c0-4606-9361-ad580b36f344

**Comment by patapizza** [comment]
Hi @mohamed-okasha,
Thanks for the thorough report.

I can't repro this:
![](https://i.imgur.com/EKxC5rV.png)

Please reopen if you still experience the issue, more examples can help.
Thanks!

**Comment by mohamed-okasha** [comment]
Hi @patapizza 
Thank you for quick response

Can you see this 
![image](https://user-images.githubusercontent.com/6838651/37927262-e7082a28-3139-11e8-9f3b-ca75d6cf77db.png)
Today i have exported my project and import it in a new project and all things work fine.
