### ISSUE TITLE
when download the zip file find some useless sentences

### ISSUE THREAD

**Issue by zhanpengli** [wit-ai/wit#1020]
just like that below, Will it matter?
![image](https://user-images.githubusercontent.com/32571006/37896829-4d0cb7b2-3117-11e8-9546-b9cef97825bf.png)

**Comment by patapizza** [comment]
Hi @zhanpengli,

Please use the provided template. What is your app id?

**Comment by zhanpengli** [comment]
@patapizza  app id : 5aa0ad58-02eb-407c-acce-165186733b40 :)

**Comment by blandinw** [comment]
I exported your app and all expressions in `expressions.json` had both `text` and `entities`

**Comment by blandinw** [comment]
I reproduced the issue.
These samples may be used (at our discretion) to make your app smarter. They do exist in our database, so we want to show them to you. If you think the annotations are wrong, please fix them. If you think these are fine with no entities, then just ignore them. We may use the information that this text contains none of the entities you care about to make your app smarter.
