### ISSUE TITLE
I'm creating my first app and don't have the stories tab on my page (https://wit.ai/NolzMalele/MyFirstApp/entities) as illustrated in the tutorial 

### ISSUE THREAD

**Issue by NolzMalele** [wit-ai/wit#1022]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by hactar** [comment]
The tutorial you are using is outdated. The story feature has been removed (https://medium.com/wit-ai/launching-built-in-nlp-for-messenger-and-sunsetting-bot-engine-beta-46e9038869a5) . The official quick start no longer references stories (the button is still in the screen shots, so ignore that);

https://wit.ai/docs/quickstart

**Comment by patapizza** [comment]
As @hactar said.
We'll update the screenshots.
