### ISSUE TITLE
Cannot find Story tab and Action tab in wit.ai

### ISSUE THREAD

**Issue by snathju** [wit-ai/wit#1023]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by l5t** [comment]
We decided to sunset stories and action last year to focus on NLP. More info here: https://medium.com/wit-ai/launching-built-in-nlp-for-messenger-and-sunsetting-bot-engine-beta-46e9038869a5
