### ISSUE TITLE
Dutch swearwords censored out/recognized as a wrong Entity

### ISSUE THREAD

**Issue by JarneJC** [wit-ai/wit#1028]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
A question.

**What is the current behavior?**
I'm trying to get Wit to understand and react to Dutch swear words. I have created an "intent" for this, in wich I've added some keywords that I would like to detect as swearwords. So far it's been recognizing some swear words, while others are not recognized and/or censored out.  For example: "autist" or "teringleier", while other swearwords like "kut" and "tering" are censored out and recognized as a "datetime" intent. These are also not available to edit in my inbox, so making a keyword called "k**" (kut censored out) won't work either. I do however see these in my logs.

Am I doing something wrong? Forgetting something (like turning on a uncesored swearword mode)?

Any help is appreciated.

My intent:
![image](https://user-images.githubusercontent.com/11608051/38085979-f994a5e8-3352-11e8-91ee-e811d78773c5.png)

Example of a log outcome of a swear word:
![image](https://user-images.githubusercontent.com/11608051/38086037-3534a512-3353-11e8-91d6-da52d313f03d.png)

![image](https://user-images.githubusercontent.com/11608051/38086019-23e1119c-3353-11e8-85be-ea47959466c4.png)

**Comment by blandinw** [comment]
You can check for a word censored out using your own code (regex `'[a-zA-Z]\*+'`) possibly in combination with a list of keywords in Wit like you've been doing.

**Comment by JarneJC** [comment]
I'm sorry for asking, but can you explain how I should go about this? I've never worked with regex and from what I've read about it using google it's just to check a certain string for containing characters. 

The string that I'm receiving from Wit has the part that I want to check already censored out, meaning I won't be able to check if it contains a keyword I'm looking for. And since I'm not sending a string but a voice message I can't really check that either.

Am I misinterpreting something you've said? 
Or did I forget to mention I'm using voice messages to analyze?

**Comment by l5t** [comment]
Unfortunately, we won't be able to change the behavior of our speech recognition in the short term so it will sometimes return a censored word and you won't be able to actually check what was behind it. As mentioned above, you can try to detect on your side whether a censored word has been detected with a regex but you won't be able to know which one it was.
