### ISSUE TITLE
API timeout 504 by using version parameter from documentation

### ISSUE THREAD

**Issue by klemensz** [wit-ai/wit#1029]
**Bug**

**What is the current behavior?**

The API returns an error 504 (Server timeout).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

```
$ curl -XPUT 'https://api.wit.ai/entities/tournament?v=20170307' \
>   -H 'Authorization: Bearer $TOKEN' \
>   -H 'Content-Type: application/json' \
>   -d '{"values":[{"value":"some value"},{"value":"some other value"},{"value":"yet another value"},{"value":"wow, values for everyone"}],"doc":"Awesome entity."}'
```

**What is the expected behavior?**

It should return a success message and status 200.

**What is the App ID where you are experiencing this issue (if applicable)?**

5ab976ea-ea8a-49d6-bcd5-5daa91394754

Interesting fact: Trying to create a new app also times out (`PUT https://api.wit.ai/sync?verbose=true 504 (Server timeout)`.

**SOLUTION**

While writing the issue I found the solution: If I use the version parameter `v=29.03.2018` instead, it works! 🤔 But in the documentation https://wit.ai/docs/http/20170307 it's different.

**Comment by l5t** [comment]
Hey, we have had some issues today this is why your call timed out. But the correct way is what you see in the documentation... You just had luck when testing with v=29.03.2018 ;-) Sorry for the inconvenience
just tested this and it worked.

> curl -XPOST 'https://api.wit.ai/entities?v=20180329' \
>   -H "Authorization: Bearer YOUR_TOKEN" \
>   -H "Content-Type: application/json" \
>   -d '{"doc":"A city that I like",
>        "id":"favorite_city"}'

**Comment by klemensz** [comment]
OK, thanks. I tried around 20 times with the one version parameter and it failed, and with the other one it worked instantly. BTW you are showing this `v=29.03.2018` in the settings of the app as an example für the curl command.

**Comment by blandinw** [comment]
@klemensz thanks for reporting the erroneous version in the Settings page (assuming your browser is using non-US locale), we'll fix it shortly
