### ISSUE TITLE
default_intent on importing from the backup .zip

### ISSUE THREAD

**Issue by vsahith** [wit-ai/wit#1032]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
I have download the data of the app and trying to import this data while creating a new app. Now, the output for trained data is giving 'default_intent'
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- download backup
- import while creating a new app
- navigate to intent -> click on expressions -> preview API output
the new app is not detecting the intent
**What is the expected behavior?**
- to detect the intent like the old app
**What is the App ID where you are experiencing this issue (if applicable)?**
5ac2083f-20f6-4c5e-8c34-8c75c8a4499c

**Comment by blandinw** [comment]
Thank you for your feedback, we're looking into it

**Comment by stopachka** [comment]
this is actually an issue with our preview api output -- it uses an older version of our API, so the output showing the legacy "default_intent" entity. diff coming shortly. 

To confirm, this is not a bug with import/export -- you will see default_intent even in your original app if you click "preview api output"

**Comment by stopachka** [comment]
(diff to fix this should be in production ~5-6 hours
