### ISSUE TITLE
Do not receive the sample(expression) into all trait entities related while using the GET/entities/entity-id

### ISSUE THREAD

**Issue by FkLinks** [wit-ai/wit#1034]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
I would say it's a bug

**What is the current behavior?**
I have a sample that is matching more than one entity. While doing the GET/entities/entity-id for each entity that is related to it, I only get the sample(or "expression") in one of the values but not in the other ones.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
just post a sample linked to more than one entity, then try to get each entity with GET/entities/entity-id and see that only one value have the sample as expression.

**What is the expected behavior?**
I expect to have the sample as expression of all the values that are linked to this sample

**What is the App ID where you are experiencing this issue (if applicable)?**
5a958081-7b11-45f1-b16d-7ed2465bae84

**Comment by stopachka** [comment]
Hey @FkLinks I tried: 


Look for: "Why is deskew not working"

```
curl -XGET 'https://api.wit.ai/entities/operativity?v=20170307' \
  -H "Authorization: Bearer $TOKEN"
```

```
curl -XGET 'https://api.wit.ai/entities/workspace?v=20170307' \
  -H "Authorization: Bearer $TOKEN"
```

And found the expression. Could you give me an example query that you could not find?
