### ISSUE TITLE
Wit did not recognize any formats of date and return wrong values

### ISSUE THREAD

**Issue by mohamed-okasha** [wit-ai/wit#1035]
Report a *bug* about datetime builtin entity

**What is the current behavior?**
Wit did not recognize any formats of date and return wrong values. 

![screenshot-wit ai-2018 04 04-09-51-35](https://user-images.githubusercontent.com/6838651/38295777-770ae230-37ef-11e8-8b39-db1c6c3f2a92.png)

**What is the expected behavior?**
Wit should recognize common formats like 
%Y/%m/%d , %Y-%m-%d
And return year , month and day value as we expected .

**Comment by l5t** [comment]
Thanks for reaching out. wit/datetime is controlled by Duckling, our open source parser and depends on the language of your app. Feel free to open an issue there and even contribute to make it better! https://github.com/facebook/duckling
