### ISSUE TITLE
How does wit.ai handle different languages?

### ISSUE THREAD

**Issue by CombustiblePotato** [wit-ai/wit#1036]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question
**What is the current behavior?**
Currently, most major NLP frameworks support at most up to 3-8 major languages, while wit.ai supports +40 languages. While it is nothing unusual if 2 different frameworks have a couple more languages that one supports while the other doesn't, however wit.ai seems to have a HUGE leap compared to other frameworks, which makes it sort of suspicious.

How exactly does wit.ai handle so many different languages? Is there a some type of cheap method that lead to the ability to adopt so many different languages so fast?

**Comment by l5t** [comment]
Interesting question ;-) Wit supports 75 languages! How is it even possible? Wit.ai mainly relies on Machine Learning so based on the data you and other developers validated. It also relies a little bit on Duckling, our linguistic parser (that is language specific). So if you want to participate on Duckling, don't hesitate to look at the open source parser here to help with entities like date time/duration/number: https://github.com/facebookincubator/duckling
