### ISSUE TITLE
How can I add more than one user-based entity for my app? is:open label:entities

### ISSUE THREAD

**Issue by ColetheHobbyist** [wit-ai/wit#1037]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by l5t** [comment]
You can just type the name of the new entity you want to create. Note: if trait, don't highlight anything in the  sentence
![image](https://user-images.githubusercontent.com/6992759/38377697-7cf79870-38b0-11e8-8e9d-531d359b4cc9.png)
