### ISSUE TITLE
Send blank trait value through API

### ISSUE THREAD

**Issue by hsilvester** [wit-ai/wit#1039]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
I want to ask a question about posting blank trait values through the Wit API. There are some expressions we don't want our app to match and send the wrong response to the end user.

**What is the current behavior?**
Currently the API doesn't seem to pick up an intent with a blank value. We are able to validate with no entities present on the front end, but we can't replicate this through the API.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Here's an example of what we're doing in the front end, which we'd like to also do through the API:
1. Expression matches to intent
2. Remove all intents and entities from Understanding
3. Validate the expression with no entities present

**What is the expected behavior?**
It would be great if we could replicate this behavior through the API if there are expressions we don't want our app to pick up on and match to an intent.

**Comment by stopachka** [comment]
Update on samples with no entities

- Currently, providing these samples will **not** actually train the model the way you would like (it does not have any effect)
  - We are working on this solution in the next version of model management

In the meantime, the best solution would to create a blacklist entity, to detect the sentences that you do not want to match

**Comment by patapizza** [comment]
Hi @hsilvester, training an expression without entities should not affect the model at this point. Negative samples are something we'd like to support in the near future.

**Comment by aforaleka** [comment]
Hi @hsilvester! Regarding training an expression with no entities through the API, we now support doing that in POST /samples. We're also working on making it easier to manage datasets, so thank you for requesting this feature! :)
