### ISSUE TITLE
Could not validate expression

### ISSUE THREAD

**Issue by NourShalabi** [wit-ai/wit#1040]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
"Could not validate expression" Appears while training trait expressions

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Create a new Wit.ai app, start training new expressions, after a while message appears.
![image](https://user-images.githubusercontent.com/25252530/38409778-642ec1d4-398b-11e8-937a-42409d36920c.png)

**What is the expected behavior?**
Training without errors

**What is the App ID where you are experiencing this issue (if applicable)?**
5ac72794-9985-4258-a6e2-7af1b295edeb

**Comment by hsilvester** [comment]
I've experienced this behavior on several occasions. It happens both when the app has both a Clean and Ongoing training status. Most of the time I just wait a short time before I begin training again. It would be great if this can be improved so training will be much more efficient.

**Comment by NourShalabi** [comment]
I also have a question regarding this behavior, is this returned as an error message if the training was posted through the API?

**Comment by hsilvester** [comment]
I'd be interested to know if it also returns the error message when posting through the API.

I've been experiencing this issue several times today through the front end. Normally it only happens once or twice a day when we're spending a lot of time training, but it continues to happen today in all of the apps I'm training.

**Comment by hsilvester** [comment]
@stopachka Thank you for the update! Are there more intermittent issues today? I haven't been able to successfully train any of the apps I'm working on today. I continue to receive the "Could not validate" error message every so often.

**Comment by patapizza** [comment]
@hsilvester Yes we're experiencing some issues and are working on them.

**Comment by patapizza** [comment]
We should be better now.

**Comment by l5t** [comment]
Closing, please reopen if you still experience this
