### ISSUE TITLE
Unable to create synonyms - update the UI to prevent synonym creation for free-text only entity

### ISSUE THREAD

**Issue by pjoimedia** [wit-ai/wit#1041]
Reporting a bug.

Unable to create synonyms for a keyword in a free-text entity in Chrome Version 65.0.3325.181. I enter a word in the "Add synonym" input, click enter, but nothing happens. It does not add synonyms to the Synonyms column.

**Comment by l5t** [comment]
Just tested on Google Chrome 65.0.3325.181 also and it works for me 
![keyword](https://user-images.githubusercontent.com/6992759/38430988-b8869c70-3977-11e8-83ea-aecbe919bd38.gif)

**Comment by pjoimedia** [comment]
Thanks for looking into this @l5t.

If you change lookup strategies from free-text & keywords to free-text you should be able to replicate the issue.

**Comment by stopachka** [comment]
Hey @pjoimedia -- if you change to free-text only, then there is no concept of synonym anymore. 

free-text means: it must is located somewhere in the sentence, so "start" and "end" values are required

**Comment by pjoimedia** [comment]
Thanks @stopachka.

1. If that's the case the feature should not be available and confuse people because there is currently no information what are you talking about on the page so if there is an input field to put synonyms I would expect them to work or not be there is they shouldn't be there.

2. Also, I still see an application for synonyms even for free text.

**Comment by l5t** [comment]
1. Indeed we should do a better job in the UI
2. if this is the case you can have both a free-text & keyword strategy for your entity
