### ISSUE TITLE
Cannot create/destroy app (504 Server timeout)

### ISSUE THREAD

**Issue by klemensz** [wit-ai/wit#1043]
**Bug**

**What is the current behavior?**

When trying to create an app, nothing happens. In the Chrome dev tools I can see an error:

Request URL: https://api.wit.ai/sync?verbose=true
Request Method: PUT
Status Code: 504 Server timeout

And it returns an HTML page with the following content (among other):

```
      <h1 id="sorry">Sorry, something went wrong.</h1>
      <p id="promise">
        We're working on it and we'll get it fixed as soon as we can.
      </p>
```

Actually, the same problem exists when trying to delete an app (5acb4296-44b7-4cd4-accd-1d93ed2fc7da). And I'm also experiencing the timeout issue when uploading entity values over the API. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Go to https://wit.ai/apps/new and try to create a new app

**What is the expected behavior?**

It should create a new app.

**What is the App ID where you are experiencing this issue (if applicable)?**

It's a new app

**Comment by anurag-arora** [comment]
only GET requests are working, all others are showing the same response

> <h3 id="sorry">Sorry, something went wrong.</h3>
      <p id="promise">
        We're working on it and we'll get it fixed as soon as we can.
      </p>

**Comment by l5t** [comment]
I just tested and it worked for me. Can you try again and report whether this was a transient issue?

**Comment by klemensz** [comment]
* Creating a new app: now works again
* Deleting existing app: now gives me an error ("You cannot do that.") IDs: 5acb489d-6b8b-421f-a870-658a61a942f9 and 5acb489d-6b8b-421f-a870-658a61a942f9
* Updating entity values via API: gives me `{ error: 'Something went wrong. We\\'ve been notified.',\n  code: 'wit' }` for one of the tree entities, for the other two it works

**Comment by klemensz** [comment]
The issue re-appeard, creating an app times out after exactly 2 minutes with 
```
      <h1 id="sorry">Sorry, something went wrong.</h1>
      <p id="promise">
        We're working on it and we'll get it fixed as soon as we can.
      </p>
```

From Chrome dev tools:
```
curl 'https://api.wit.ai/sync?verbose=true' -X PUT -H 'Accept: application/vnd.wit.20150405+json' -H 'Referer: https://wit.ai/' -H 'Origin: https://wit.ai' -H 'Authorization: Bearer MYTOKEN' -H 'Content-Type: application/json' --data-binary '[{"data":{"name":"Some_random_name_for_my_app","desc":"","lang":"en","private":true},"type":"created-instance"}]' --compressed
```

**Comment by klemensz** [comment]
Actually I tested with uploading about a couple of thousand entity values, around 50% of them get a code 200 response,  the other 50% fail with an error 500. There is no clear pattern why some fail and some succeed.

**Comment by patapizza** [comment]
@klemensz Importing external databases to `keywords` entities is an anti-pattern. As an example, for `player` can you try using a `free-text` instead and filtering out in your client based on the database? Thanks.

**Comment by mubiesam** [comment]
still happening...can not create new app / access existing app
Failed to load resource: the server responded with a status of 400 (Bad Request)
Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by blandinw** [comment]
Thank you all for your feedback!

@klemensz We did implement several stability and performance fixes in the past week. However, as @patapizza said, you should not be uploading large databases as keywords at the moment, and use `free-text` instead. If you do need to upload a large database that could also benefit the rest of the community, feel free to contact us and we may create a new built-in entity for it. We also have plans to allow upload of large amounts of data, but this is still being discussed internally.

@mubiesam You'll need to provide more info, maybe by opening a new issue and filling out the template, thank you.

Will close this for now as it is getting a bit noisy, feel free to reopen more issues. Thank you very much once again for your feedback!
