### ISSUE TITLE
"Go down the rabit hole" button not working.

### ISSUE THREAD

**Issue by feralheart** [wit-ai/wit#1044]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
When I want to submit the form, the button not working.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Log in to Git Hub
2. Fill the form
3. Click on the green button

**What is the expected behavior?**
"We accepted your registration. Have a nice day."

**What is the App ID where you are experiencing this issue (if applicable)?**
It's the [main page](wit.ai)

**Comment by l5t** [comment]
Seems related to #1043
