### ISSUE TITLE
Not able to update or delete wit's entites through API

### ISSUE THREAD

**Issue by anurag-arora** [wit-ai/wit#1045]
As soon as I am requesting to update or delete this entity, I am getting this message. 

{
    "error": "Entity 'wit$greetings' not found",
    "code": "not-found"
}

**Comment by klemensz** [comment]
Usually the `wit$` prefix is used for built-in entities.

**Comment by anurag-arora** [comment]
so you mean to say we cannot request for delete built-in entities and update built-in entity values?
https://wit.ai/docs/http/20170307#put--entities-:entity-id-link

**Comment by patapizza** [comment]
@anurag-arora Users are not allowed to update/delete built-in entities.
