### ISSUE TITLE
Keywords not operating as expected 

### ISSUE THREAD

**Issue by adabritt** [wit-ai/wit#1047]
We have a list of activities created as keywords with the lookup strategy keywords selected. 

Several of our key words are similar in nature. For example we have skiing, and sand_skiing with an alias for sand skiing. There is also surfing, and sand_surfing that has sand surfing listed as an alias. 

Any time the word "and" is entered, any activity that also has a sand version is what is being verified. So the phrase "biking, skiing, and surfing" is validating as biking, skiing, sand surfing. 
When entering "biking and skiing", it validates as biking, sand skiing. 
![screen shot 2018-04-11 at 4 48 44 pm](https://user-images.githubusercontent.com/30119297/38642589-7e23643e-3da8-11e8-84e1-af1652d59b4b.png)

Because we are using keywords for the look up strategy, we would not expect validation to assume that we meant sand when typing and. The same issue does not happen if there are multiple other entities used.
![screen shot 2018-04-11 at 4 48 32 pm](https://user-images.githubusercontent.com/30119297/38642576-76c3c81e-3da8-11e8-9963-3acf222e9c0d.png)

App ID 583273ad-575f-4ad3-a801-fe95d236ce57

**Comment by patapizza** [comment]
Hi @adabritt, thanks for reporting.
This is an edge case - for `keywords` we're trying to be robust to typos and here `sand skiing` is very close to `and skiing`, hence it's being picked up.
Not sure what the workaround could be - will bring up to the team and report back.
