### ISSUE TITLE
Can't train "Goodbye" text

### ISSUE THREAD

**Issue by Pendejooo** [wit-ai/wit#1050]
Hi wit.ai team,

we're using your NLP and it seems that we aren't able to associate an intent to the keyword "goodbye" because it seems to be recognized as a smalltalk.

applicationId : 
5a255ade-906a-4b80-b7f9-777953611e24

Even if we remove smalltalk (goodbye) and associate it manually to our own intent when we try to type it and to give it to your api the intent is null on result.

I add some screenshots.
Feel free to contact me if needed.

Thanks a lot,
![intents](https://user-images.githubusercontent.com/14124074/38723063-3c4b192c-3f00-11e8-9cb0-cbd9ec829d34.PNG)
![test](https://user-images.githubusercontent.com/14124074/38723064-3c716bcc-3f00-11e8-9276-7fdac0f8ca51.PNG)

Tiago.

**Comment by patapizza** [comment]
Hi @Pendejooo, thanks for reporting. Indeed this is unexpected, `good bye` (with a space) works as expected. Can you try adding more expressions with `goodbye`?

**Comment by mannerav** [comment]
Openfile
