### ISSUE TITLE
Feature request: Accept audio in ogg/opus formats, accept audio download links

### ISSUE THREAD

**Issue by mborus** [wit-ai/wit#1052]
*feature* request

Hi, can you consider accepting audio in ogg/opus formats?

These are very small, high quality files and used by chat application voice messages,
like Telegram (which uses 16bit, 48000kHz mono files). They also play in the web 
browser and are licence free.

Currently I convert my ".ogg" files I receive from Telegram to ".mp3", before uploading, This not only takes time for conversion, but also increases file size by factor 3. 

Also, it would be great if I could send you a download link to a audio file instead of the file itself. Again, this is for messenger communication, where now I need to download the file myself to upload it to you again. Passing on the direct download link could speed up the audio to text conversion a lot.

**Comment by patapizza** [comment]
Hi @mborus,

Thanks for reaching out. Speech is not a high priority for us at this time. I'll track this internally.

**Comment by stefan-reich** [comment]
To be clear, ogg/vorbis isn't supported directly either, is it? For wit.ai, I'm converting my Telegram .oggs to mp3 too.

**Comment by jtliao** [comment]
hey @stefan-reich, it's not currently supported

**Comment by stefan-reich** [comment]
Thanks :) @jtliao

**Comment by HaiCheViet** [comment]
So i have a question that how many languages are supported in speech to text?
Tks in advance

**Comment by jtliao** [comment]
We only officially support English, the rest of the languages are experimental.
