### ISSUE TITLE
In Arabic, wit/contact doesn't identify more than one word in any name

### ISSUE THREAD

**Issue by rudyzeinoun** [wit-ai/wit#1053]
Using the Arabic language, the built-in entity wit/contact does not recognize names that consist of more than one word, even if you train it for so. Using a similar configuration in English, it works flawlessly. It is probably aided in English by the use of capitalization.

**What is the current behavior?**
Train with: ماذا كتب صالح محمود
 ؟
ماذا كتب => new intent, get_news
صالح محمود => wit/contact
Validate.

Try it again and you'll see only محمود recognized as contact.

Repeating this in English will properly take both words "John Smith" as a contact.

App ID: 5ad35c2f-2996-46c9-9d01-044ac0975c17

![p1](https://user-images.githubusercontent.com/393106/38779865-14897900-40d7-11e8-9b5f-fcfebe09f946.JPG)

![p2](https://user-images.githubusercontent.com/393106/38779868-1d5f46c2-40d7-11e8-817e-6c5954f4c482.JPG)

**Comment by patapizza** [comment]
Thanks for reporting @rudyzeinoun. We'll need to take a look into the model.
In the meantime, please keep validating more examples.

**Comment by jtliao** [comment]
Merging with #1615 for tracking
