### ISSUE TITLE
Training of Composite Entities through the Samples API doesn't work

### ISSUE THREAD

**Issue by NourShalabi** [wit-ai/wit#1055]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
Training of composite entities through the Samples API doesn't work
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Request:
[
  {
    "text": "live testing of sub entities",
    "entities": [

      {
        "entity": "sub2",
        "value": "free text with sub entity",
        "start": 0,
        "end": 28,
        "role": null,
        "subentities": [
          {
            "entity": "sub_ent",
            "value": "sub2",
            "start": 0,
            "end": 4,
            "role": null
          }
        ]
      }
    ]
  }
]

Response:

{
    "sent": true,
    "n": 1
}

When I checked the interface I found that the expression was trained correctly.
![image](https://user-images.githubusercontent.com/25252530/38829060-a451325a-41c0-11e8-8530-e2c42d152643.png)

However, when I try the same expression in Understanding, the result doesn't show the main entity
![image](https://user-images.githubusercontent.com/25252530/38829148-e366dfd0-41c0-11e8-95a2-8e3d0ed21f82.png)

I detected this behavior when training subentities through the API if the main entity is of Keyword look up strategy. However, there isn't a clear documentation on how to change look up strategies from [Keywords] to [free-text] or [free-text & keywords]

**What is the expected behavior?**
To be able to train composite entities, if there is a way to change look up strategies to free-text or free-text & keywords please let me know, as this could potentially solve the problem.
Otherwise, please advise a clear way to train composite entities through the samples endpoint.

**What is the App ID where you are experiencing this issue (if applicable)?**
5ac72794-9985-4258-a6e2-7af1b295edeb

**Comment by stopachka** [comment]
Hey @NourShalabi 

Could you go over the API requests you sent, to get to this state? It's surprising that "keywords" is set as the default -- it should be free-text & keywords if it's going strictly through POST /samples

**Comment by s-nour** [comment]
@stopachka I will go over them and let you know how it goes, but can you please clarify how exactly the lookup strategy is set for entities created through the API if we don't choose a specific type?

**Comment by l5t** [comment]
Basically, if you validate sample with span (aka start and end), Wit will know that this is freetext&keyword as opposed to if you validate sample without span, Wit will know that this is a trait.
BTW, we just released an improvement to the PUT /entities/entity-id API: you can now set the lookups to free-text, keywords, or free-text & keywords through the API: https://wit.ai/docs/http/20170307#put--entities-:entity-id-link
