### ISSUE TITLE
[bug] cannot see access token when user own too many apps

### ISSUE THREAD

**Issue by s-nour** [wit-ai/wit#1057]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
I'm unable to obtain access toke, the fields are empty and when I click refresh nothing happens. 

Also, training through the API has stopped working for this app

This is happening on multiple apps now. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

![image](https://user-images.githubusercontent.com/19264187/38936771-3a5c945a-432a-11e8-8c83-bb36ff75df9e.png)

**What is the expected behavior?**
To be able to obtain the access token

**What is the App ID where you are experiencing this issue (if applicable)?**
5acb6a6f-8ca1-4c53-a5d6-a403ca473fdb

**Comment by blandinw** [comment]
You have too many apps :-) 
If you create the apps using the `POST /apps` API, the response will contain the corresponding access token. I created a low priority internal ticket to paginate apps in the UI when there's too many of them.
