### ISSUE TITLE
Adding wit/datetime through API

### ISSUE THREAD

**Issue by sanjayraja** [wit-ai/wit#1058]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug
**What is the current behavior?**
On calling the below API - expected result is that the wit$datetime is added to the App entities.
https://api.wit.ai/samples?v=20170307
[{
        "text": "Do I have an appointment tomorrow ?",
        "entities": [
          {
            "entity": "wit$datetime",
            "value": "tomorrow",
            "start": 25,
            "end": 32
          }
        ]
      }]

However get the following response when querying via 
https://api.wit.ai/message?v=20170307%0A&q=Do%20I%20have%20an%20appointment%20tomorrow%20%3F

{"_text":"Do I have an appointment tomorrow ?","entities":{},"msg_id":"0D2cb1mjGw8sM8wzI"}

wit/datetime entity is not been identified.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Replicable through the above steps
**What is the expected behavior?**
wit/datetime entity should be added to the App
**What is the App ID where you are experiencing this issue (if applicable)?**
NA - happening on all Apps

**Comment by sanjayraja** [comment]
This issue is now fixed

**Comment by philippe-tseyen** [comment]
Having the same issue. Since today.
