### ISSUE TITLE
SSLError, max retries exceeded

### ISSUE THREAD

**Issue by ZenyoXos** [wit-ai/wit#1061]
There's a bug for me, tough wit.ai was *unlimited* call

It worked for the half of a day, but now this happen :

Max retries exceeded with url: /speech?v=20150101 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

app id : 5ad5bad8-1900-4ca7-9278-764e7de3ca59

**Comment by l5t** [comment]
Closing, please reopen if you still experience this with more info
