### ISSUE TITLE
Train Status API

### ISSUE THREAD

**Issue by kazimanzurrashid** [wit-ai/wit#1062]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Feature

Currently there is no way to know whether the train is completed, can you expose some endpoint 
which returns the status of the train.

**What is the current behavior?**
none

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
n/a

**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by l5t** [comment]
You're spot on... and this is on our roadmap 
#620
