### ISSUE TITLE
Api incomplete: cannot get training data with breakdown into entities & roles

### ISSUE THREAD

**Issue by gorenbox** [wit-ai/wit#1063]
Hi, 

we would like to get via api our training data, today we can get the whole expressions used for training, but not a breakdown into entities and roles.

Thx

**Comment by l5t** [comment]
Can you share a concrete example?
As an alternative, have you tried the export? https://wit.ai/docs/recipes#copyexportversion-my-app

**Comment by gorenbox** [comment]
Hi, sorry for delayed response.
We would like to manage our models completely automatically via api automated training).
I order to do so, we need a more full api, where we can retrieve the model information (intents, entities, roles, expressions....).
Today we dont have that, so there are 2 options, one is export and analyze files, this is not really robust and comfortable for automated processes. The other option (what we try to do today), is store a mirror copy of the model locally. This is prone to problems, and also creates sync issues if for example, the  model was updated manually in the wit UI.
It would be really great to expand the api to contain the full model data (must) and also to provide meta data, like agent settings (language, timezone, name...).

**Comment by patapizza** [comment]
Hi @gorenbox,

As @l5t mentioned, the export feature should help with that. The full dataset is available in `expressions.json` and all entity data (including role) in each `entities/name.json` file.
The app language and name are available in the `app.json` file. It seems like the timezone is indeed missing.

Is anything else missing?

**Comment by gorenbox** [comment]
except for an api so i dont have to do get / set through files :-( ...
seems rest is covered.

**Comment by gorenbox** [comment]
@l5t @patapizza there is no api for export and import. How did you intent for us to get the information.
Our system will be automated, so the import and export cannot be done manually.
Is there a possibility to supply an api for
1) import / export model
2) getting full training data 
3) getting / setting agent data
Is this possible, is it in the roadmap?

**Comment by l5t** [comment]
1. We are working on an export api not sure about the status of the import one  cc @stopachka 
2. Will be addressed by 1
3. https://wit.ai/docs/http/20170307#get--apps-link are you thinking about something else?

**Comment by gorenbox** [comment]
Thanks @l5t for the feedback
1) if there will be an api for export and import that would be AMAZING. is there any schedule you could share? this is a critical feature for us.
3) That is PERFECT, thanks for referring me...somehow missed it.

About 2) 1 addresses it but, not in the best way. 2 systems communicating via file transfers is not the best option. I know u have your priorities and a lot of things on your plate, but would consider adding it to your roadmap somewhere.

**Comment by blandinw** [comment]
1) There will be an API for import and export, but you'll still be dealing with .zip files. @stopachka will share the timeline
2) We will consider other APIs, thank you for your input

**Comment by gorenbox** [comment]
@stopachka any news about the apis when they will be ready (export / import, set lookup strategy)

**Comment by jtliao** [comment]
hey @gorenbox, we are currently working on the API to set lookup strategy, which will be available in the coming weeks. As for import/export and the training API, they are currently in the pipeline and we will provide updates as they get closer.

**Comment by gorenbox** [comment]
Thanks @jtliaofor the update regarding lookup strategy ... anxiously waiting for the import / export api...

**Comment by stopachka** [comment]
closing, as this will be fixed with: 

https://github.com/wit-ai/wit/issues/706 Export API

and 

https://github.com/wit-ai/wit/issues/655 Samples CRUD

**Comment by stopachka** [comment]
To give context on the timeline: 

The current stage of the pipeline is: Training API, GET /samples, GET /export. All of these should be published and available in the coming 1-2 months

**Comment by gorenbox** [comment]
@stopachka and whole wit team! thanks for sharing this information and being so transparent and helpful.
you are great!!
stupid question - what is the training api?
Is there a plan for an import api, so you can append to an existing model in bulk through api.

**Comment by stopachka** [comment]
Cheers @gorenbox!

cc https://github.com/wit-ai/wit/issues/876 for Training API

The idea is: currently if you send new data, it's hard to know: when has wit taken that data into account? The Training API will show a transparent to see: what data has been taken into account and trained

There is indeed a plan for an import API, but it's a bit behind the backlog of those three. We will get to this soon as well. In the meantime, if you have ideas for how it should work, you can comment on https://github.com/wit-ai/wit/issues/658

**Comment by gorenbox** [comment]
wow, what an exciting roadmap!
