### ISSUE TITLE
story,actions pages are not show

### ISSUE THREAD

**Issue by chamilab** [wit-ai/wit#1064]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question wit.ai

**What is the current behavior?**
Only show understanding,inbox,logs and settings only

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
n/a
**What is the expected behavior?**
see my project story, actions
**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by s-nour** [comment]
These features were removed.

**Comment by l5t** [comment]
https://wit.ai/blog/2017/07/27/sunsetting-stories
