### ISSUE TITLE
Misc Console Issues

### ISSUE THREAD

**Issue by jcdenny** [wit-ai/wit#1065]
I'm currently having a few issues. Login seems to be failing most of the time. I've tried both Github and Facebook. After a few attempts it will finally login, however some things don't show up such as expression values. It seems very much like performance issues with the site.

**Comment by jcdenny** [comment]
It looks like it may be working now.

**Comment by magnusburton** [comment]
Having ahard time logging in as well. I'm receiving the following error in my console. I've tried logging in via incognito etc.

> Refused to load the script 'chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/localLib/jquery/jquery-2.1.4.min.js.local' because it violates the following Content Security Policy directive: "script-src *.facebook.com *.fbcdn.net *.facebook.net *.google-analytics.com *.virtualearth.net *.google.com 127.0.0.1:* *.spotilocal.com:* 'unsafe-inline' 'unsafe-eval' fbstatic-a.akamaihd.net fbcdn-static-b-a.akamaihd.net *.atlassolutions.com blob: data: 'self' *.cloudflare.com platform.twitter.com cdn.syndication.twimg.com *.wit.ai *.intercomcdn.com *.intercom.io *.facebook.com:8443".

> Bootstrap's JavaScript requires jQuery

**Comment by patapizza** [comment]
Hi @jcdenny @magnusburton - are you guys still experiencing this?

**Comment by magnusburton** [comment]
@patapizza Hi Julien. I'm still experiencing this issue. See below for the complete console data.

> Refused to load the script 'chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/localLib/jquery/jquery-2.1.4.min.js.local' because it violates the following Content Security Policy directive: "script-src *.facebook.com *.fbcdn.net *.facebook.net *.google-analytics.com *.virtualearth.net *.google.com 127.0.0.1:* *.spotilocal.com:* 'unsafe-inline' 'unsafe-eval' fbstatic-a.akamaihd.net fbcdn-static-b-a.akamaihd.net *.atlassolutions.com blob: data: 'self' *.cloudflare.com platform.twitter.com cdn.syndication.twimg.com *.wit.ai *.intercomcdn.com *.intercom.io *.facebook.com:8443".

> bootstrap.min.js:6 Uncaught Error: Bootstrap's JavaScript requires jQuery
>     at bootstrap.min.js:6

> ry8GJmx5pzn.js:57 ErrorUtils caught an error: "<![EX[["Tried to get element with id of \"%s\" but it is not present on the p...". Subsequent errors won't be logged; see https://fburl.com/debugjs.

**Comment by stopachka** [comment]
Hey @magnusburton 

This seems to be an error from an extension that is trying to work on top of Wit. 

For security reasons, we don't allow external scripts to loaded onto wit.ai, this could expose you to security vulnerabilities. I'd suggest disabling / blacklisting wit.ai from this extension

**Comment by l5t** [comment]
Closing, please reopen if @stopachka's answer didn't solve this
