### ISSUE TITLE
My speech input are not recognized correctly

### ISSUE THREAD

**Issue by earthat** [wit-ai/wit#1068]
I am building a voice recognition app, based on the intent value of speech, certain action will be decided. But the wit app is not giving the desired intent. Here is my app ID: 5a8a8bc5-b483-417d-8c3b-94adba82d38f

I need to suggestions to improve this app. Python API for it is being used.

**Comment by patapizza** [comment]
@earthat Can you share a few examples that don't work for you?

**Comment by earthat** [comment]
Thanks for the response,  I would like to share my witai app with you so that you can listen to speech input in logs. May I know your wit username or email.

**Comment by earthat** [comment]
I have trained for 'invoice' intent value and giving speech commands like, 'open an invoice' or 'make an invoice'. This is giving back such kind of responses:

-open and in what is
-may i was
-make noise and
-make invoice
-open and invoice
-may an invoice
-will everyone's
-open and in what

However when I give the text input, it recognizes it correctly.

**Comment by earthat** [comment]
@patapizza your help will be appreciated. Please take out few minutes to look into it.

**Comment by patapizza** [comment]
@earthat It seems like the speech engine has having issues with the accent.

Speech is not a priority for us at the moment. We do keep this in mind but can't provide an ETA on when things will improve. In the meantime, if the current state doesn't work well enough for you, we encourage you to try other solutions (e.g. iOS/Android native speech).

**Comment by earthat** [comment]
Thanks for it.
