### ISSUE TITLE
Is there a way to convert the value of an intent to lowercase always?

### ISSUE THREAD

**Issue by samt07** [wit-ai/wit#1069]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?** Yes, I am looking for a feature. It may be new or already existing. I am not sure about that.

**What is the current behavior?** It takes the value as is. I want to force convert the values for a user defined intent to all lowercase.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?** Force convert the values of an intent to lowercase.

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by patapizza** [comment]
@samt07 Thanks for the suggestion, let me see with the team if this is something we want to support.

**Comment by patapizza** [comment]
Hi @samt07, we don't silently convert the values to lowercase as this would be trigger unexpected behavior. However we are robust to case sensitivity and use the first provided value as source of truth.

Hope this helps.

**Comment by samt07** [comment]
Ok thanks @patapizza. I was hoping if there is an option to choose "wit/lowercase" while creating an entity. I can still convert it in my code after I get it from wit. Not a big deal. Thanks for giving it a thought and following it up with your team.
