### ISSUE TITLE
Conditionally apply entities

### ISSUE THREAD

**Issue by renet** [wit-ai/wit#1070]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question (maybe a feature request)

**What is the current behavior?**
I've added the entity `wit/message_subject` to my project, to identify the target language, when a user says something like `What's "apologize" in German?`. I trained my app to identify sentences like this as an intent with the value `do_translate`. I did this, so I don't have to add every possible language to an enum. However, since then the message_subject entity is being applied to almost every message of a user.

**What is the expected behavior?**
I'd like to add a condition to the the `wit/message_subject` entity, so that it only applies if the intent has the value `do_translate` (and maybe more values in the future). Is that possible at the moment? If not, is there a better way to handle cases like this? Otherwise this would be my feature request.

**What is the App ID where you are experiencing this issue (if applicable)?**
5ae0f4de-5053-445b-8496-344471381358

**Comment by patapizza** [comment]
Hi @renet,

Thanks for the suggestion. We used to have this, and we do have this in mind.
In the meantime, it seems like in your code, you can decide to ignore `wit/message_subject` when `intent` is not `do_translate`.

Hope this helps.

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
