### ISSUE TITLE
Cannot set `free-text & keywords` lookup strategy via HTTP API.

### ISSUE THREAD

**Issue by vladikus10** [wit-ai/wit#1072]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question
**What is the current behavior?**
Currently you can set the entity to "free-text & keywords" via the GUI, however you can't do the same with HTTP API, getting response  `"error": "Unsupported lookups"`. Why is it like that?
Tested with version **20180507**
**What is the expected behavior?**
You would expect it to accept both `free-text` and `keywords` as look ups and then combine them into `free-text & keywords`, especially since the look up field is an array.

P.S. I'm actually working on a node script which would train apps using the exported data from different wit.ai apps, so I'm not sure if it is possible now. Example: say if you have 2 wit.ai apps, one trained to recognize weather requests, the other one trained to take food orders, you would export them both and use the script to train a third app to understand both weather and food requests, also update in the future, kinda like dialogflows modules.

**Comment by vladikus10** [comment]
Huh, never really seen that warning, how can it be misused?

**Comment by l5t** [comment]
![image](https://user-images.githubusercontent.com/6992759/39710569-017091a8-51d2-11e8-9d23-15445ab678c1.png)
This is the warning I was talking about. As for misusing it, it was more about developers setting it the wrong entity type (like keyword for intent like entity) and then not understanding why Wit was behaving in a certain way

**Comment by vladikus10** [comment]
Mhm that's a bummer, I guess using only either `keywords` or `free-text` should work for now for the trainer.

**Comment by vladikus10** [comment]
Hand on, I just checked and even `free-text` alone is not supported. Did people even misuse that through the api?

**Comment by stopachka** [comment]
Hey @vladikus10 

We disabled changing lookups in the API, as they alter fundamentally the kind of samples that are needed (i.e not possible to go from free-text -> trait without introducing potentially bad data)

What you can do though is:
1. Create the entity
2. Send a POST /sample request with an example expression
  - This, if it has a start and end, will automatically set "free-text & keywords" 

If I understand correctly, the 2 steps above should solve your problem. 

However, indeed we still need to think of an ergonomic API for changing lookups. This is on the roadmap

**Comment by gorenbox** [comment]
Hi, 
You could still enable setting the lookup for a new entity. the ability to change is less important. but the ability to create an entity and set the lookup strategy is important, and if u disabled it, maybe easy to bring back.

**Comment by blandinw** [comment]
Given the feedback we received, we will be bringing back this feature soon.
We'll update this issue once this is done.

**Comment by gorenbox** [comment]
hi @blandinw , any update when this will be ready?
any light you can shed on this would be very very helpful

**Comment by patapizza** [comment]
@gorenbox We're actively working on it, it should be released soon.

**Comment by jtliao** [comment]
You can now set the lookups to free-text, keywords, or free-text & keywords through the API. 

Something like this would work for your use case

`curl -XPUT 'https://api.wit.ai/entities/$ENTITY_ID?v=20170307' -H 'Authorization: Bearer $TOKEN' -H 'Content-Type: application/json' -d '{"lookups":["free-text", "keywords"]}'`

See the docs for details: https://wit.ai/docs/http/20170307#put--entities-:entity-id-link
