### ISSUE TITLE
Wit.ai api seems to be down

### ISSUE THREAD

**Issue by alexandruf** [wit-ai/wit#1073]
**What is the current behavior?**

GET https://api.wit.ai/message?v=version&q=message

---------------------------
Response Error
---------------------------
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote server returned an error: (503) Server Unavailable.

   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)

   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)

   --- End of inner exception stack trace ---
---------------------------
OK   
---------------------------

**Comment by patapizza** [comment]
@alexandruf I can't repro this. Is the issue consistent?

**Comment by alexandruf** [comment]
Hey, now works fine. :)

**Comment by alexandruf** [comment]
Evan the site didn't work properly at that time. When tried to login with github, it didn't work
