### ISSUE TITLE
500 on DELETE /entities/:name/values/:name/expressions/:exp

### ISSUE THREAD

**Issue by mehfuzh** [wit-ai/wit#1077]
I am getting the following exception while deleting an expression.

```
curl -XDELETE 'https://api.wit.ai/entities/intent/values/start/expressions/hi?v=20170307' \
-H "Authorization: Bearer $TOKEN"
```

```
{
  "error" : "Something went wrong. We've been notified.",
  "code" : "wit"
}

```

**Comment by blandinw** [comment]
@mehfuzh Please do not post your access token publicly and provide your appid.

**Comment by mehfuzh** [comment]
It could be an issue with that particular app and its a test app anyway.

**Comment by mehfuzh** [comment]
ahh, good point. Here is the app Id : 5af612d2-6986-422d-b95a-4a833e4727e9

**Comment by blandinw** [comment]
@mehfuzh Thank you for your feedback, a fix is being pushed out right now

**Comment by mehfuzh** [comment]
Yep works like a charm!
