### ISSUE TITLE
Incorrect intent for word with accent mark (Spanish)

### ISSUE THREAD

**Issue by andresespinosapc** [wit-ai/wit#1078]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug

**What is the current behavior?**
Wit recognizes words with accent marks as different characters. With this behaviour, I would need to give much more training examples to wit to handle these words, I don't even know if it is possible.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
![image](https://user-images.githubusercontent.com/8888934/39951935-40d0d060-5565-11e8-8b96-2d804e4022ec.png)
![image](https://user-images.githubusercontent.com/8888934/39951938-4aac1dce-5565-11e8-89f2-0bd9866cb72d.png)
With this simple example you can see that wit takes "ó" as a different character than "o", so I would need to add the examples twice to handle it for people that write with or without accent marks.

**What is the expected behavior?**
Just handle letters with accent marks as if they were the same letter without it, or give an option to change this behaviour. I live in Chile and most people don't use accent marks when writing on Messenger, but sometimes they do, mostly because of the smartphone spelling checker.

**What is the App ID where you are experiencing this issue (if applicable)?**
58d9df09-dafa-434d-8d7c-a58b5a08e684

**Comment by blandinw** [comment]
@andresespinosapc Thank you for your feedback.
You're right that accents should not play a major role in understanding intent.
We'll start working on a fix and update this issue once it is deployed.

**Comment by asfyra** [comment]
The same thing also happens with the Greek language. 
Καλημέρα / Καλημερα

**Comment by John000708** [comment]
Can confirm that this is an issue with Greek as well. 

Taking wit/ordinal as an example:

Δεύτερος is recognized correctly and shows me as a value 2.
Δευτερος is not recognized at all. It also seems like trying to train it without the accents doesn't do anything.

However with other ordinals like 43th the behavior is different. Example:
"τεσσαρακοστός τρίτος" shows the value of 43 which as expected is correct.
"τεσσαρακοστος τρίτος" weirdly also shows the correct value of 43.
"τεσσαρακοστος τριτος" however only recognizes the first word, 40 in this case.

It seems to me like it only understands long words without accents with a high confidence (>0.9) while small words without accents aren't understood correctly. Generally the confidence with small words seems to fluctuate between 1 and 0.7.

I hope my report was helpful and I'm looking forward to it being resolved.

**Comment by maxing89** [comment]
Any updates about this issue? Thanks!

**Comment by blandinw** [comment]
No update for now. We are working on a larger update to our machine learning pipeline and this will be included in it.
In the meantime, a possible workaround is to normalize accent marks away on your side, or generate the necessary samples and upload them using the `POST /samples` endpoints.

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
