### ISSUE TITLE
wit app couldn't be found!

### ISSUE THREAD

**Issue by azarezade** [wit-ai/wit#1079]
After working for a while with wit.ai, today suddenly I encountered this error:

<img width="1261" alt="screen shot 1397-02-24 at 08 38 10" src="https://user-images.githubusercontent.com/11195749/39977913-4967203c-5752-11e8-8a19-c61ff2930468.png">

while trying to I connect to one of my apps (**VPA-dev**).

**Comment by azarezade** [comment]
I think there are some errors there:
<img width="1280" alt="screen shot 1397-02-24 at 10 32 57" src="https://user-images.githubusercontent.com/11195749/39980668-45abae9e-5762-11e8-87ed-5937767739ef.png">

**Comment by giorgiomarzianidepaolis-was** [comment]
same here, the issue is the browser

**Comment by hactar** [comment]
Ditto here with safari. chrome works.

**Comment by blandinw** [comment]
Thank you for your reports, can you all try to log in again and report back?

**Comment by hactar** [comment]
Safari works for me now.

**Comment by azarezade** [comment]
Great! 
Thanks it works now.
