### ISSUE TITLE
Adding Arabic values to an entity via curl 

### ISSUE THREAD

**Issue by mennafateen** [wit-ai/wit#1081]
Using this command:

curl -XPUT 'https://api.wit.ai/entities/location_3?v=20180514' \
  -H 'Authorization: Bearer $mytokenhere' \
  -H 'Content-Type: application/json; charset: utf-8' \
  -d '{
       "values":[
 {
   "value": "البنفسج"
 },
 {
   "value": "اللوتس"
 },
{
   "value": "المستثمرين الشمالية"
 },
 {
   "value": "المستثمرين الجنوبية"
 }
 ]}'

All I get on wit.ai are question marks.
![image](https://user-images.githubusercontent.com/11869772/39995696-50f17066-577d-11e8-86ae-6c52fd9ab26c.png)

What is causing this problem?

**Comment by blandinw** [comment]
We are looking into it, thank you for your feedback

**Comment by jtliao** [comment]
Hey @mennafateen, 

Tried the curl you provided, but I do see the Arabic values as inputted (tested on Chrome, Firefox, Edge, Internet Explorer, Safari). 

![screen shot 2018-05-15 at 2 37 30 pm](https://user-images.githubusercontent.com/13305586/40085070-2859b664-584e-11e8-8431-e011623a5834.png)


May I ask what browser you're using to view these values?

**Comment by mennafateen** [comment]
Hey @jtliao,
I'm using Google Chrome but I'm still receiving those question marks.  
![image](https://user-images.githubusercontent.com/11869772/40102921-0b1cf194-58ec-11e8-81af-18cfbc5b068e.png)
Is there something I'm missing?

**Comment by jtliao** [comment]
hey @mennafateen,

Can you provide your App ID? In the meantime, can you try loading the app on Chrome Incognito mode or a different browser?

**Comment by mennafateen** [comment]
Hey @jtliao,

I actually just found a workaround. I figured the problem might have been with the terminal since the Arabic characters seemed a bit weird so I tried sending the request from another terminal and it worked.
I apologize for wasting your time and thank you for your help!

**Comment by jtliao** [comment]
No worries :)

**Comment by mrghofrani** [comment]
> Hey @jtliao,
> 
> I actually just found a workaround. I figured the problem might have been with the terminal since the Arabic characters seemed a bit weird so I tried sending the request from another terminal and it worked.
> I apologize for wasting your time and thank you for your help!

I have encountered the same issue, I have tried cmd, cmder and Windows Terminal, but no luck. Which terminal you have used?
