### ISSUE TITLE
Witai doesn't recognize datetime (Polish & French)

### ISSUE THREAD

**Issue by woprzech** [wit-ai/wit#1083]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug

**What is the current behavior?**
Witai doesn't recognize datetime entity in polish language. It was working correctly till today.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1) create project for polish language
2) add datetime entity
3) type `wtorek` word (Tuesday)

**What is the expected behavior?**
datetime entity should be recognized

**What is the App ID where you are experiencing this issue (if applicable)?**
5a8d7b88-c639-4500-97da-aacc458374d8

**Comment by LokoSama** [comment]
We have exactly the same issue in French language, may be a generalized issue.
Our App ID : 59d5db09-8c74-4352-b3e7-aff7601d32dc 
Looking forward for a fix or news about this

**Comment by flogaribal** [comment]
Exactly the same issue as @LokoSama in French
We tried in english too and it is not working neither

**Comment by vnheros** [comment]
I have same issue in Vietnamese. For example: _ngày 19/5_
But it works for: _ngày 19/5/2018_
Looking for a fix. Many thanks!

**Comment by mminchev** [comment]
I have the same issue, "1st of May" is not recognized as a date in English.

**Comment by monika1800** [comment]
I have the same issue, Suddenly dates are not getting recognised as datetime in English by wit. @l5t Is there any changes happening at your side?

**Comment by l5t** [comment]
Thanks for reporting all. We are investigating and will update as soon as we have a fix. Sorry for the inconvenience

**Comment by patapizza** [comment]
Thanks for reporting, I'm on it.

**Comment by patapizza** [comment]
We found where the issue comes from and are pushing a fix to production. Unfortunately, it may take up to 3 hours to propagate worldwide.
We sincerely apologize for the inconvenience.

**Comment by hsilvester** [comment]
We are experiencing the same issue in English. Thank you for the update @patapizza

**Comment by andresespinosapc** [comment]
Could you let us select which release version we want to use? This is the second time in 3 weeks that you have a heavy problem. These issues don't let my users use my application, so maybe I should develop my own NLP model to avoid the issues you have sometimes. Please deploy the application through releases.

**Comment by philippe-tseyen** [comment]
Same issue over here :(

**Comment by patapizza** [comment]
This is now fixed, sorry for the delay. We'll review what went wrong exactly to learn from it and improve our process.
