### ISSUE TITLE
Cannot add synonyms to entities

### ISSUE THREAD

**Issue by hactar** [wit-ai/wit#1087]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
When I try to add entities to https://wit.ai/hactar/NewWaveV4/entities/vienna_location by clicking "add synonym", adding something like "Kindergärten", nothing happens, and the java console shows a 500 error. The screenshot shows the java error log (I tried multiple times before noticing, which is why multiple 500 errors can be found)

<img width="1497" alt="wit-error" src="https://user-images.githubusercontent.com/645674/40347629-3d1e1e8e-5da1-11e8-83bf-8d8a6987bf11.png">

**What is the App ID where you are experiencing this issue (if applicable)?**
https://wit.ai/hactar/NewWaveV4/entities/vienna_location
5a2934a4-a921-48f2-8439-960637f89aba

**Comment by patapizza** [comment]
Thanks for reporting @hactar, we're on it.

**Comment by patapizza** [comment]
Related to #1086.
