### ISSUE TITLE
New App Creation and Wit Expressions are not validating, giving 500 internal server error

### ISSUE THREAD

**Issue by anurag-arora** [wit-ai/wit#1088]
Training is not working, Inbox training has been stopped too
https://api.wit.ai/sync?verbose=true
I have checked in the console of wit website and found that this PUT request is resulting in 500 Internal server error.
{
  "error" : "Something went wrong. We've been notified.",
  "code" : "wit"
}

**Comment by patapizza** [comment]
Thanks for reporting @anurag-arora, I'm on it.

**Comment by patapizza** [comment]
Related to #1086.
