### ISSUE TITLE
Unable to login via Facebook

### ISSUE THREAD

**Issue by Abhishek-Choudharyy** [wit-ai/wit#1089]
Hii, Anyone having the issue with wit.ai login via facebook.
In Console, it is showing POST https://api.wit.ai/me/facebook_signin 500 (Internal Server Error)

**Comment by hiephm** [comment]
Cannot login using Github either. Has wit.ai been abandoned by FB?

**Comment by woprzech** [comment]
Probably it is duplicate:
https://github.com/wit-ai/wit/issues/1086

**Comment by patapizza** [comment]
Thanks for reporting.
Closing in favor of #1086.
