### ISSUE TITLE
github login via www.wit.ai doesn't work

### ISSUE THREAD

**Issue by hactar** [wit-ai/wit#109]
If you visit http://www.wit.ai (instead of http://wit.ai) and hit log in, the github authentication screen is presented. When you submit the authentication data the window closes again, but you are not moved into the console, the page remains on http://www.wit.ai .

I suggest either fixing this, or redirecting users from http://www.wit.ai to http://wit.ai.

**Comment by Sisekelo** [comment]
Hi there Blandinw. I am having the same issue

**Comment by joyabbhi** [comment]
Hi, having the same issue. Unable to login with GitHub or FaceBook account in Mac. I tried Browser, Safari and Chrome.

**Comment by blandinw** [comment]
Hi @joyabbhi, could you be more specific? Do you see any error message?

**Comment by visyon360** [comment]
Same issue here. The github login intent pop up opens up, then closes (I guess it is a successful login), and then redirects to https://wit.ai/home
The page shows up the following message: `"Uh oh... You cannot access this page. You'll need to sign in to view this page! Sorry about that!"`. Then you try to log in again with GitHub and redirects again to that page.

![Screenshot attached](https://imgur.com/P7kf4nTl.png)

**Comment by BabuWitCh** [comment]
Hi,
Looks like the issue is not resolved yet! After clicking on 'Log in with GitHub', it takes me to a pop up and i could successfully logged in. But immediately the page closes itself and i back to wit.ai home page.

Any solution for this?

**Comment by joyabbhi** [comment]
Hi, could you try switching the network?..it worked for me when I changed
my WiFi network..thanks.

**Comment by GanadiniAkshay** [comment]
Facing the same issue.

@joyabbhi changing the network doesn't help

**Comment by blandinw** [comment]
@GanadiniAkshay @BabuWitCh @visyon360 are you still facing the same issue?

**Comment by GanadiniAkshay** [comment]
@blandinw Its resolved for me

**Comment by mohbasheer** [comment]
Hi @blandinw 

I'm getting the same error. I tried login with github and facebook after authentication it's going to https://wit.ai/home  and it's again asking me to authenticate.  this issue is not resolved please look into it.

**Comment by mohbasheer** [comment]
I cleared the cache now it's working. but still it's an issue.

**Comment by stopachka** [comment]
we had an intermittent outage, apologies for the inconvenience everyone. We're working on making these quickly visible for our users

**Comment by gomgo-github** [comment]
I'm having again problems with the github login, i dont want a facebook accont, i respect my privacy but i need a token for my Discord Bot
