### ISSUE TITLE
Not able to login with either github or facebook

### ISSUE THREAD

**Issue by bharathgrk** [wit-ai/wit#1090]
@blandinw I am facing the issue of not being able to login with my github account.
I have attached a screenshot of the wit.ai/home page that shows the error as well as the console error, if it will be of any help.

![screen shot 2018-05-22 at 12 37 29](https://user-images.githubusercontent.com/9738122/40347284-55db9fb6-5dbd-11e8-95c3-a0c705ca403f.png)

Edit: had the same problem when i tried to login with my facebook account also..

![screen shot 2018-05-22 at 17 40 37](https://user-images.githubusercontent.com/9738122/40361533-4c6f94c6-5de7-11e8-967b-b606180a33f3.png)

**Comment by patapizza** [comment]
Thanks for reporting @bharathgrk, I'm on it.

**Comment by patapizza** [comment]
Closing in favor of #1086.
