### ISSUE TITLE
App has been stuck in training for last couple of hours

### ISSUE THREAD

**Issue by liamMwalls** [wit-ai/wit#1093]
Do you want to request a feature, report a bug, or ask a question about wit?
question

What is the current behavior?
App is stuck in training.  

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Inserted a lot of values into an entity (~10k). App has been in ongoing training since then.

What is the expected behavior?
Training should've finished by now.

What is the App ID where you are experiencing this issue (if applicable)?
5af55db6-a9c2-44ad-8188-64168d7105845af55d

**Comment by patapizza** [comment]
Hi @liamMwalls, I just fixed the training of your app `5af55db6-a9c2-44ad-8188-64168d710584`.
