### ISSUE TITLE
keywords not helping to identify trait

### ISSUE THREAD

**Issue by bpleao** [wit-ai/wit#1094]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question/bug

**What is the current behavior?**
Associating keywords to a certain trait doesn't help in trait recognition.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I've created a simple bot to illustrate what I mean. (app id below). I have two intents: `hungry` and `thirsty`. I have created two keywork entities: `drink `and `food`, and added 4 examples of each one. Then I've created 2 exemples for each intent, associating one keyword of the corresponding type to each one (`food` to `hungry` and `drink` to `thirsty`). I was expecting that when I used the other examples for the keywords this would take me to the correct intent, but this is not what happens. For instance, if I try "I want wrap", having "wrap" as a term in `food` it identifies the intent as `thirsty`. 

**What is the expected behavior?**
If some keywords are associated to specific intents, examples that include keywords of a certain type should lead to the corresponding intent.

**What is the App ID where you are experiencing this issue (if applicable)?**
5b0b484a-f0b9-427f-87a4-f69a13badea8

**Comment by patapizza** [comment]
Hi @bpleao,

Traits take sentence-level features. In your app, all samples are of the form "I want <x>". The intent is the same for all sentences: `want`. In this case, depending if there is a `drink` or/and a `food`, you can handle the message appropriately. Another intent would be `dislike` for "I don't like <x>", or `order` for "I want to order <x>".

Hope this helps.

**Comment by bpleao** [comment]
Hi @patapizza,

Well, I think an intent is a very abstract concept: If the intent for all samples starting with "I want" is the same than the intent for "I want to know the weather" and "I want to book a trip" are also the same which is clearly not the case... And I believe the type of keyword entities that exist in a sample are very relevant sentence-level features that should be used to help identify traits.

But anyway, do you have any advice on how I could leverage lists of related terms (like the keyword entities I've used) to help wit identify traits? I have a real situation, much more complex than the one in the example, where I would like to do that.

Thanks,

Bruno

**Comment by patapizza** [comment]
Hi Bruno,

In your app, all examples are of the form "I want <x>". Obviously "I want to know the weather" is a different intent, but that's not an example from your app. In your app, the validated examples for "hungry" and "thirsty" are the same.

I would provide multiple sentence examples with the same keywords entities (e.g. "I would like rice", "I want to eat rice", "I'm craving for rice"). Again in your current app setup, "thirsty" or "hungry" are actually the same intent.

**Comment by bpleao** [comment]
Thanks @patapizza. I understand that I can differentiate the intents by using different phrases, but the whole point of my question is whether or not I can make wit differentiate intents based on the fact that they are associated to different keyword entities. For reference, if I've built exactly the same bot in [dialogflow](https://dialogflow.com/) and it works perfectly as expected, differentiating hungry from thirsty based only on the keywords. I've made available an export of the dialogflow bot [here](https://sites.google.com/site/brunoleao/test.zip?attredirects=0&d=1) that you can use in case you want to test it. I would prefer not to switch to dialogflow because I already have a bot in production in wit, which is working great since last year and I am familiar with the API.

Regards,

Bruno

**Comment by patapizza** [comment]
It would be helpful to get a bit more context on what you are trying to do, as this doesn't seem like a good approach. I'm happy to help with the modeling involved in translating your business needs into your Wit app.

**Comment by bpleao** [comment]
Great! I’m trying to build a Q&A app with more over 1k different Q&A pairs. I’m planning to use one intent for each Q&A pair, as I’ve already done successfully in the past. I have a big list of relevant terms with their synonyms that I’d like to leverage and I was expecting that adding each of this terms with its synonyms as a keyword entity could do the trick.

**Comment by patapizza** [comment]
@bpleao This sounds about right, provided that each Q&A pair is different enough than another.
