### ISSUE TITLE
[question] How to correctly use the Inbox

### ISSUE THREAD

**Issue by tomzmtl** [wit-ai/wit#1095]
Hi, I recently created an app which is in its learning phase.
I'm basically reading from a chat thread and use the inbox to train the bot.

It's not clear though how to handle messages with custom intent.
How do I tell the AI that it was wrong in finding a specific intent? Should I click the "X" on the left of the intent found and then click "Validate", or simply trash the message?

Is there a difference between the two? The docs are not really explaining how that works (except maybe the obvious click "validate" to tell the AI it was right).

Thank you.

**Comment by patapizza** [comment]
Hi @tomzmtl,

Indeed, we need to clarify. You can validate without the "intent" entity to show that this is an example not matching any intents.

**Comment by tomzmtl** [comment]
@patapizza Thanks for the reply.

Is there a way to add new matches on entries that were already processed?

Let's say I add a new intent value in the future and want to indicate matches on past inbox entries.
Would that be possible?

**Comment by l5t** [comment]
Very good question also... Currently we don't support this so you will have to go manually on your past inbox entries (the ones you validated already) and add the new intent. We are thinking about making it easier for developers to do this in the future but this is not yet prioritized on our side
