### ISSUE TITLE
[HTTP API] Update entity's id/doc causes removal of all its value & expression

### ISSUE THREAD

**Issue by bcphung** [wit-ai/wit#1096]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a *bug*.

**What is the current behavior?**
When calling `PUT /entities/:entity-id` which only updates for `id` or `doc` field, it also removes all associated values & expressions have been created before.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Create entity
```bash
$ curl -XPOST 'https://api.wit.ai/entities?v=20170307' \
  -H "Authorization: Bearer $TOKEN" \
  -H "Content-Type: application/json" \
  -d '{"doc":"A city that I like",
       "id":"favorite_city"}'
```

2. Create sample
```bash
$ curl -XPOST 'https://api.wit.ai/samples?v=20170307' \
  -H "Authorization: Bearer $TOKEN" \
  -H "Content-Type: application/json" \
  -d '[{
        "text": "I want to live in Danang",
        "entities": [
          {
            "entity": "favorite_city",
            "value": "live"
          }
        ]
      }]'
```

3. Update entity
```bash
$ curl -XPUT 'https://api.wit.ai/entities/favorite_city?v=20170307' \
  -H 'Authorization: Bearer $TOKEN' \
  -H 'Content-Type: application/json' \
  -d '{"doc":"These are cities worth going to"}'
```

**What is the expected behavior?**
Calling `PUT /entities/:entity-id` should update only present fields in request body.

**What is the App ID where you are experiencing this issue (if applicable)?**
All of my apps, I'm afraid.

**Comment by jtliao** [comment]
hi @bcphung , I just gave it a shot and am not experiencing the bug anymore, can you confirm?

**Comment by jtliao** [comment]
I see why I couldn't produce it, seems that the problem occurs only for "trait" entities, and not "keywords" and "free-text". We will look into the problem, thanks for the detailed reproduction steps.

**Comment by jtliao** [comment]
Hey @bcphung, this should be fixed now. Let me know if you are still an issue with this!

What I tested:
`curl -XPUT 'https://api.wit.ai/entities/favorite_city?v=20170307' -H 'Authorization: Bearer $TOKEN' -H 'Content-Type: application/json' -d '{"doc":"These are cities worth going to"}'`

`{
  "builtin" : false,
  "doc" : "These are cities worth going to",
  "exotic" : false,
  "id" : id,
  "lang" : "ar",
  "lookups" : [ "trait" ],
  "name" : "favorite_city"
}`

`curl -XGET 'https://api.wit.ai/entities/favorite_city?v=20170307' -H "Authorization: Bearer $TOKEN"`

`{
  "builtin" : false,
  "doc" : "These are cities worth going to",
  "exotic" : false,
  "id" : id,
  "lang" : "ar",
  "lookups" : [ "trait" ],
  "name" : "favorite_city",
  "values" : [ {
    "value" : "live",
    "expressions" : [ "I want to live in Danang" ]
  } ]
}`

No longer deleted!
