### ISSUE TITLE
wit.ai C++ sdk

### ISSUE THREAD

**Issue by brightening-eyes** [wit-ai/wit#1101]
hi,
i've developed a sdk for wit.ai in C++.
although it is incomplete yet, [here it is](https://github.com/brightening-eyes/witpp)
thanks

**Comment by aforaleka** [comment]
Hi @brightening-eyes, thanks for contributing!! Please share this in the [Wit.ai Hackers FB group](https://www.facebook.com/groups/withackers/) so more developers can see this. :)

**Comment by brightening-eyes** [comment]
hi @aforaleka,
unfortunately, i dont have access to facebook (due to limitations in my country)
i'm glad if someone can share it with others.
thanks

**Comment by lara101aneke** [comment]
Hey @brightening-eyes i am super new to programming and i saw your sdk for wit.ai. i am trying to so simple speech recognition from the built in microphone, i was wondering if you have managed to send live/raw audio to wit.ai rather than pre-recorded files? it is even possible? 

Thanks

**Comment by brightening-eyes** [comment]
hi,
you can record with microphone and send the data with whatever you prefer.
maybe if you areon windows, winmm can help you or rtaudio or portaudio
check them out.

۱۳۹۹-۰۲-۰۴ ۲۲:۰۹ ‎+۰۴:۳۰ گرینویچ, lara101aneke <notifications@github.com>:
