### ISSUE TITLE
How to train composite entities through Wit.ai HTTP API?

### ISSUE THREAD

**Issue by vladikus10** [wit-ai/wit#1104]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question
**What is the current behavior?**
Currently the API docs only describe how to train basic free-text and keyword entities, however it does not explain how to train composite entities, is it even possible?

**Comment by l5t** [comment]
You're right, we don't have this in our docs but this is possible. We will update the docs soon but here is how to format the POST /samples code. Note that you need to create entities first (here car, color and model)


 ```
curl -XPOST 'https://api.wit.ai/samples?v=20170307' \
  -H "Authorization: Bearer TOKEN" \
  -H "Content-Type: application/json" \
  -d '[{
        "text": "I want a blue toyota",
        "entities": [
          {
            "entity": "car",
	        "value": "blue toyota",
	        "start": 9,
        	"end": 20,
        	"subentities": [
				{
	              "entity":"color",
	              "value": "blue",
	              "start": 0,
	              "end": 4
            	},
            	{
	              "entity":"model",
	              "value": "toyota",
	              "start": 5,
	              "end": 11
	            }
        	]
          }
        ]
      }]'
```
