### ISSUE TITLE
Composite entities are not always extracted correctly 

### ISSUE THREAD

**Issue by NourShalabi** [wit-ai/wit#1105]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
Hello, I noticed a problem in training composite entities, they don't seem to be always extracted correctly all the time. 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I defined an expression "i want a table at cinco" with a composite entity as follows:

![image](https://user-images.githubusercontent.com/25252530/40972915-fe571946-68ca-11e8-84f5-68092133b7e9.png)

This expression has been trained a long time ago. In the understanding section the sub-entity doesn't show
![image](https://user-images.githubusercontent.com/25252530/40972984-42e65be4-68cb-11e8-94d0-7a8c5865b239.png)

This happens on an off, and it's not clear why the sub-entity was not extracted.

**What is the expected behavior?**
Sub-entities to be extracted correctly from trained expressions. 

**What is the App ID where you are experiencing this issue (if applicable)?**
5acb6a6f-8ca1-4c53-a5d6-a403ca473fdb

**Comment by vladikus10** [comment]
I'm kinda dealing with similar issue, where composite entities are not extracted correctly. However, shouldn't composite entities be made out of several entities? I think in your situation, assigning a role would probably be better.

**Comment by stopachka** [comment]
Hey @NourShalabi, I took a look and it seems that example is now working: 

![image](https://user-images.githubusercontent.com/984574/41247648-7185b3cc-6d63-11e8-97c6-780baa8a41b3.png)

--- 

Did something change by the time you posted and now? We are getting very close to building the training API, which should make this much easier to debug :)
