### ISSUE TITLE
wit.ai API service and wit.ai site itself went down about 20 minutes ago

### ISSUE THREAD

**Issue by joechoi-git** [wit-ai/wit#1106]
wit.ai API service and wit.ai site itself went down about 20 minutes ago.
This is impacting our business.

Can you please restore it ASAP?

Thank you.

**Comment by hactar** [comment]
Confirmed.

wit.ai site works for me, but the API doesnt:

Server responds with a 503 error and:

"Sorry, something went wrong.

We're working on it and we'll get it fixed as soon as we can."

**Comment by joechoi-git** [comment]
It just came back up about 5 minutes ago.
Service is restored now.

But, can you please elaborate on why this outage happened today? 
Can we reliably trust that wit.ai service will be operational 24/7?

Thank you.

**Comment by hactar** [comment]
API Service now working for me too again.

**Comment by mvdt** [comment]
I'm still getting 503 at my local dev-env, but an other remote app using the same service is working fine

**Comment by blandinw** [comment]
Thanks, we're aware of the issue. We'll update this issue soon.

**Comment by blandinw** [comment]
Things should be working now.

The issue was region-specific caused by a misconfiguration of our load balancers, failing to properly handle a regional failover exercise (simulation of a datacenter going down).

We're working to prevent the issue going forward.
We'll publish some reliability metrics for the last month as well.

**Comment by blandinw** [comment]
Here are some reliability numbers. Note that:
- these include _ALL_ API endpoints, even the less reliable ones like POST /samples, GET /export, etc.
- we're still working on making the service more stable and reduce latency regardless of the region of the world
- we are still in the process of migrating the rest of our API endpoints to the new infrastructure (our main endpoint GET /message is already migrated)
- "500 ok" means the number does not count 500 errors as reliability failures (i.e. it is counting them as user misusing the API), which, in practice, should be close to reality for production apps.

**Last 30 days (taking into account this outage)**
Reliability new infrastructure only: 99.9229%
Reliability new infrastructure only 500 ok: 99.9366%
Reliability overall: 99.8285%
Reliability overall 500 ok: 99.9646%

**The month before**
Reliability new infrastructure only: 99.9827%
Reliability new infrastructure only 500 ok: 99.9992%
Reliability overall: 99.9679%
Reliability overall 500 ok: 99.9845%

**Comment by hactar** [comment]
@blandinw Thanks for all the work you guys are doing, being a long time user it's great to witness the strides you've made over the years - wit has become noticeably faster and more reliable.
