### ISSUE TITLE
Export API

### ISSUE THREAD

**Issue by alexandruf** [wit-ai/wit#1107]
Hello, 

Is it possible to export your project data automatically from wit.ai API?
When you open a project and go to Settings tab, you can export your data and the link is something like:

> https://api.wit.ai/export/[generatedKey]

Why is this important?
Every time Wit.ai return no intent, that utterance goes to our "trainer" and he manually qualifies with the correct intent. Using your API, we train the model bulk with new proposed utterances.

I would like to backup before every bulk training, in order to assure the quality of the bot and to rollback if problems.

BR,
Alex

**Comment by stopachka** [comment]
Hey @alexandruf -- This is on the pipeline, within the next few months we will release a new export api, that should handle your need. Will keep this task open to track it

**Comment by jtliao** [comment]
This is now available, see docs https://wit.ai/docs/http/20170307#get__export_link
