### ISSUE TITLE
[question] train new value for "wit/location" 

### ISSUE THREAD

**Issue by Bandesz99** [wit-ai/wit#1108]
Hi all, I am using Hungarien language (i know it is in beta) and i try to train to recognise locations (use Understanding section and Validate) but it looks no effect. E.g. my sentence is: what is the weather in Sopron (in hungarien of course), i select Sopron, set wit/location entity, click on validate, i write this sentence again and wit/location entity not found at all. Anybody has an idea what's wrong? Many thanks!

**Comment by patapizza** [comment]
HI @Bandesz99, what is your app id? Can you share the Hungarian text?

Thanks.
