### ISSUE TITLE
Migrate to GitLab

### ISSUE THREAD

**Issue by feralheart** [wit-ai/wit#1109]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question and Bug
**What is the current behavior?**
The project is on GitHub
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Microsoft bought github.
**What is the expected behavior?**
Port it to GitLab
**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by RethoughtSolutions** [comment]
I'm not sure if you are just trolling or mean it seriously, but with the amount of information you gave and the way you wrote it I will assume it's a "joke".

If you are serious however I have two things to say. First of all, you don't know the implications of Microsoft buying GitHub just yet and are just following an outcry without informing yourself first. Of course it sounds scary if such a platform is bought by a big company like Microsoft and sure enough Microsoft doesn't have the best reputation - but it won't just ruin GitHub for you just now. Recent Open Software projects (also hosted on GitHub!) by Microsoft have been great and they would sincerely harm themselves if they did anything too crazy with GitHub.
The second thing is that I personally believe this is not the right place for such "jokes" or "trolls", especially if there is no effort put into it. Not that I'm trying to be unfunny, but this looks more like spam than being entertaining.

**Comment by stopachka** [comment]
The strategy we will take is to see how it goes -- so far Github is great, but we will stay on top of it. Also, being a company acquired by FB, we believe it's possible to be acquired and still provide a great product :)
