### ISSUE TITLE
XMLHttpRequest cannot load https://api.wit.ai/sync : Log in with Github, 'You cannot access this page'

### ISSUE THREAD

**Issue by stopachka** [wit-ai/wit#111]
Hiya Wit team, excited to check out what's rocking behind the angular.js app.

Right now, If I log in with github on the home page,
     I get the error -- Uh oh... You cannot access this page
![image](https://cloud.githubusercontent.com/assets/984574/3085635/b2b803c4-e516-11e3-9246-2ca088edc433.png)

When opening inspect element, I see 
![image](https://cloud.githubusercontent.com/assets/984574/3085642/dd25e8c4-e516-11e3-85d2-8e02c512d130.png)

This might have to do with CORS, http://stackoverflow.com/questions/21709790/no-access-control-allow-origin-header-is-present-on-the-requested-resource

**Comment by rojinva** [comment]
I am also facing the same issue. I cannot login to your site with Github.
