### ISSUE TITLE
Intent is not getting recognised when input is very long.

### ISSUE THREAD

**Issue by vsahith** [wit-ai/wit#1110]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
Intent is not getting classified for long sentences. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
give feedback -> intent:feedback
give feedback give feedback give feedback give feedback give feedback give feedback -> intent:feedback
give feedback give feedback give feedback give feedback give feedback give feedback give feedback give feedback give feedback give feedback give feedback give feedback give feedback give feedback give feedback give feedback give feedback give feedback give feedback give feedback give feedback give feedback give feedback give feedback give feedback give feedback give feedback give feedback give feedback give feedback -> no intent

**What is the expected behavior?**
should return the intent

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by stopachka** [comment]
Hey @vsahith, as this is a trait entity, it takes the whole sentence into account when deciding what the value is. You would need to give it examples of large sentences to start to detect those as well, for they are not inherently the same as the smaller ones. Please reopen with a repro if this continues, and we'd be happy to take a look :)
