### ISSUE TITLE
Trait Entities

### ISSUE THREAD

**Issue by 91ns** [wit-ai/wit#1112]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question

I would like to know if there's a limit to the number of trait entities that can be assigned to one expression. 

We've experimented with 3 traits per expression, but the understanding didn't go very well, I also want to know if there's a certain approach to follow in training trait expressions. 

This is the approach we experimented with:

expression : entrance fees to petra

trait entities: 
- intent : General Info
- Inquiry_Type : Attractions
- details : Entrance Fees

Most of the type it's not extracting all of the trait entities.

**Comment by patapizza** [comment]
Hi @NourShalabi,

Please use the provided template - what is your app id?

There is no limit for trait entities - each trait entity is trained separately, so if one particular trait doesn't show up, its dataset might not be large enough.
At first glance, it seems like `details` could be a `keywords` entity. I'll have a better idea on how to design your use case after looking at your app.

**Comment by NourShalabi** [comment]
app-id : 59e8add5-117d-469c-80e7-cd7f6c21798a

The training my have changed a bit since I posted the question. But, my main concern is if this is a valid approach or not. 
Also, I couldn't find clear documentation on use cases of trait entities, if you guys can provide that it will be great. 

Thanks :)

**Comment by patapizza** [comment]
@NourShalabi It seems like it's picking the right entities, and the approach seems fine to me. Do you have a few samples that don't work?

**Comment by stopachka** [comment]
Assuming this is stale and closing -- let us know the samples if we can help
