### ISSUE TITLE
3 entities, same key word.  How to detect all entities?

### ISSUE THREAD

**Issue by jordotech** [wit-ai/wit#1113]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question: How can I have the same keywords belong to multiple entities?  
I'm using keyword lookup strategy for `blue cheese`.  It can be a topping, dressing or a sauce but wit only seems to be able to return one of those at a time and how it chooses which one is a mystery.  

**What is the current behavior?**
Even though `blue cheese` belongs to 3 identically trained entities, `food_topping` is currently always winning

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
![screen shot 2018-06-12 at 8 03 13 am](https://user-images.githubusercontent.com/485972/41292304-c91f9eea-6e17-11e8-9d67-1d136bf54878.png)

**What is the expected behavior?**
Should return all 3 entities, `food_topping`, `food_sauce`, `food_dressing`

**What is the App ID where you are experiencing this issue (if applicable)?**
5b1fc11e-b59c-4845-bfbf-1fa8bf99d93b

**Comment by jordotech** [comment]
I came up with a workaround, maybe this will help others with the same issue.

I ended up putting in a JSON object into the entity value's metadata:

`{"entities": ["food_topping", "food_dressing", "food_sauce"]}`

Now when I receive the wit response I check the returned entity values and alter the response dictionary so my app knows it also belongs to those other entities.

![screen shot 2018-06-12 at 12 01 59 pm](https://user-images.githubusercontent.com/485972/41305471-9e07579a-6e38-11e8-8510-968ebeb0ad8e.png)

**Comment by patapizza** [comment]
Hi @jordotech, we currently allow only one entity per text span (besides composite entities).

In your app, although you have the same keyword for all three entities, there's only one sample, validated with `blue cheese` for `food_topping`, which is why it's the winning one.

The metadata trick seems to be a good idea, for the few values that work for multiple entities.
