### ISSUE TITLE
My trained apps not identifying any entities since today morning?

### ISSUE THREAD

**Issue by buchikey** [wit-ai/wit#1114]
Previously My apps are working but from today morning wit is not identifying single entity from message

**Comment by asfyra** [comment]
The same thing happens to all my apps too since today !

**Comment by asfyra** [comment]
The inbox page on wit.ai website is returning empty. And the "Understanding" operation does not seem to work at all

**Comment by buchikey** [comment]
Api is working but return format is changed. I am using Node js they directly return 'entities' object but this time wit is returning data['data'][0]["__wit__legacy_response"]['entities']

**Comment by nicopetremann** [comment]
Same

**Comment by NourShalabi** [comment]
Same

**Comment by ensargunesdogdu** [comment]
same

**Comment by stopachka** [comment]
Apologies all, more info here -- https://github.com/wit-ai/wit/issues/1117. Fix on the way and we will update there
