### ISSUE TITLE
I just observed, your api (https://api.wit.ai/message?v=20180620&q=) response format change. Is that format fixed??

### ISSUE THREAD

**Issue by tarak085** [wit-ai/wit#1115]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by stopachka** [comment]
More info here. Fix is coming asap. Apologies :( 

https://github.com/wit-ai/wit/issues/1117
