### ISSUE TITLE
App Language Drop-down is Empty

### ISSUE THREAD

**Issue by NourShalabi** [wit-ai/wit#1116]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
Can't select/change App Language because the drop-down is empty
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
![image](https://user-images.githubusercontent.com/25252530/41640833-d2f333dc-746b-11e8-97db-830815f9a798.png)

**What is the expected behavior?**
Choose App Language
**What is the App ID where you are experiencing this issue (if applicable)?**
5a6cc78e-b0b4-4947-b2ec-cc23292be8f1

**Comment by nicopetremann** [comment]
Same

**Comment by serdalbayram** [comment]
same
