### ISSUE TITLE
App Stuck in Training Mode 

### ISSUE THREAD

**Issue by NourShalabi** [wit-ai/wit#1118]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
I have an app that seems to be stuck in training mode for hours now, can we please have it restarted.
 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**
5b1f8b7e-fb79-4cb0-ab6d-98b960e403eb

**Comment by mminchev** [comment]
I am facing the same issue. All wit.ai apps that I trained in the last 24h are stuck in "Training status: ongoing".

App ID: 5b295ca1-192e-4b3f-9077-5a21398ef46e

**Comment by blandinw** [comment]
Looking into it. Closing in favor of #1119

**Comment by sankarGkrish** [comment]
my app also Stuck on Scheduled: app id : 
2232278810168545

**Comment by patapizza** [comment]
Hi @sankarGkrish, it seems like your app is done training. Please open up a new or comment on an open recent issue, it's easier to track. Thanks!
