### ISSUE TITLE
Unable to create intent

### ISSUE THREAD

**Issue by kazimanzurrashid** [wit-ai/wit#1120]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
Throws http status code 400

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
making http post on https://api.wit.ai/entities/intent/values?v=20170307 with body { "value": "start" }
throws http 400 with error message "Unknown path components: /value"

**What is the expected behavior?**
it should create the intent like before.

**What is the App ID where you are experiencing this issue (if applicable)?**
5b2c3800-bc95-4cb9-9204-d052e9d8e4cf

**Comment by blandinw** [comment]
We identified the issue and are working on solving it, ETA < 1 hour
This has not been a good week :-)

**Comment by blandinw** [comment]
Fix is deployed and things are working

**Comment by shinmar** [comment]
Goood Job Guys!
