### ISSUE TITLE
PUT and POST on /entities/:entitiy-id seems to not work anymore

### ISSUE THREAD

**Issue by josephlingzb** [wit-ai/wit#1121]
Hi, as of 2 hours ago, it seems like the PUT and POST routes on /entities/:entitiy-id have stopped working. Any valid request to these routes end up with the following response:

{
    "error": "Unsupported put request",
    "code": "bad-request"
}

This is happening on all my wit.ai apps.

**Comment by blandinw** [comment]
duplicates #1120
