### ISSUE TITLE
Entity values are not recognized (sometimes)

### ISSUE THREAD

**Issue by klemensz** [wit-ai/wit#1124]
**Bug**

**What is the current behavior?**

Starting maybe 3 days ago I'm experiencing strange results for different values of the same entity. See the examples. These are all values of the same entity, sometimes they are recognized, sometimes not.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

See screenshot

**What is the expected behavior?**

It should always recognize the entities. As I already wrote, this has worked without a  problem until 3 days ago. 

**What is the App ID where you are experiencing this issue (if applicable)?**

5902737c-e922-4695-bed3-874f70abb502

![bildschirmfoto 2018-06-23 um 14 02 19](https://user-images.githubusercontent.com/1116517/41809480-7f7d36d2-76ee-11e8-84c5-38b88bd4199e.png)
![bildschirmfoto 2018-06-23 um 14 02 09](https://user-images.githubusercontent.com/1116517/41809481-7f9579fe-76ee-11e8-8b9c-22bbc6f18eb9.png)
![bildschirmfoto 2018-06-23 um 14 01 33](https://user-images.githubusercontent.com/1116517/41809482-7fb1a638-76ee-11e8-8965-430102867a2f.png)
![bildschirmfoto 2018-06-23 um 14 01 17](https://user-images.githubusercontent.com/1116517/41809483-7fca7ae6-76ee-11e8-8755-033913367494.png)
![bildschirmfoto 2018-06-23 um 14 06 03](https://user-images.githubusercontent.com/1116517/41809487-9b624a22-76ee-11e8-814c-660152c8d1fc.png)

**Comment by stopachka** [comment]
Thanks for the detailed examples @klemensz -- we will look into this and update you

**Comment by patapizza** [comment]
Apologies for the delay, looking into this.

**Comment by patapizza** [comment]
Thanks for your patience, fix upcoming.

**Comment by patapizza** [comment]
This is now fixed.

<img width="999" alt="screen shot 2018-07-06 at 3 19 28 pm" src="https://user-images.githubusercontent.com/1015208/42402495-06f9b0ea-8130-11e8-8166-9797babe6e6d.png">

**Comment by klemensz** [comment]
Thanks!
