### ISSUE TITLE
App still stuck in training, even after #1119 was closed.

### ISSUE THREAD

**Issue by liamMwalls** [wit-ai/wit#1125]
I raised #1119 4 days ago which got set to closed . My app is still in training, 3 days after the ticket was closed. 

App ID:  5af55db6-a9c2-44ad-8188-64168d7105845af55d

**Comment by l5t** [comment]
I should be trained now. Sorry for the wait.

**Comment by mminchev** [comment]
I am experiencing the "stuck in training" issue described in #1119 again. APP ID: 5b295ca1-192e-4b3f-9077-5a21398ef46e
