### ISSUE TITLE
what is the response time for wit.ai Api?

### ISSUE THREAD

**Issue by tarak085** [wit-ai/wit#1126]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by l5t** [comment]
Thanks for reaching out. For GET /message our P90 is 480ms. Also, if you build for Messenger, you can get the NLP directly in the Send/Receive API so you don't even have to make a call to the Wit.ai server: https://developers.facebook.com/docs/messenger-platform/built-in-nlp
