### ISSUE TITLE
Authorization token handled differently for POST & GET

### ISSUE THREAD

**Issue by botstar-hung** [wit-ai/wit#1128]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a *bug*

**What is the current behavior?**
When token has space in front of it, the request
- Success for GET
- Failed for POST

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
```bash
$ curl -XGET 'https://api.wit.ai/apps?offset=1&limit=2' \
  -H "Authorization: Bearer  $TOKEN" \
                            ^ (has space)
  -H "Content-Type: application/json"
```

```bash
$ curl -XPOST 'https://api.wit.ai/apps?v=20170307' \
  -H "Authorization: Bearer  $TOKEN" \
                            ^ (has space)
  -H "Content-Type: application/json" \
  -d '{"name":"My_New_App",
       "lang":"en",
       "private":"false"}'
```

**What is the expected behavior?**
Handle them correctly

**What is the App ID where you are experiencing this issue (if applicable)?**
All of my App.

**Comment by patapizza** [comment]
Thanks for reporting. This will get fixed eventually, not high-pri. In the meantime, use a single space.
