### ISSUE TITLE
Enhancement : labels/directories for intents

### ISSUE THREAD

**Issue by Seraf** [wit-ai/wit#113]
Hello,

It will be usefull to have tags/virtual directories for intents.

For example, in my software, I have plugins and they come with a list of intents.
In the case where I have 10 intents per plugins and 20 plugins installed, there's 200 intents.
Is it possible to sort them into virtual folder like Google Drive done for documents ?
Or adding tags on them, etc etc ...

What do you think about it ?

Thanks

**Comment by stopachka** [comment]
Hey Seraf, apologies for the late response here. 

Wit v2 no longer has intents. You can learn more about it here -> https://wit.ai/blog/2016/04/12/bot-engine
