### ISSUE TITLE
Ability to extract multiple entities from the same keyword

### ISSUE THREAD

**Issue by 91ns** [wit-ai/wit#1130]
If one keyword is trained in multiple entities, is it possible to extract multiple entities for that keyword?

**Comment by patapizza** [comment]
This is currently not supported. Can you share concrete examples/more context for this?

Thanks

**Comment by NourShalabi** [comment]
For example, Gold is a type of metal, it is also a color. 
Sometimes, I need to have both entities in the response and decide which one to use based on the context or intent. 

But right now, if I was to train Gold as "material_type" and "color", the response will return only one of them.

**Comment by blandinw** [comment]
Hi @91ns :-)
We used to return only entities that have been validated with a certain `intent`. We are bringing back this behavior for some beta users, before deploying to more people. Would that fix your issue or do you need something more elaborate?

**Comment by 91ns** [comment]
@blandinw this will be great actually, thanks a lot.

**Comment by blandinw** [comment]
@91ns please provide the app ids you would like me to follow this behavior and I'll make the change :-)

**Comment by blandinw** [comment]
@91ns I looked more closely at your app, and in this case the "soft intent slots" behavior I described above would not work since the conflicting entities "color" and "material_type" are validated with the same intent "lost" in your dataset. Is this intended?

**Comment by fkerasar** [comment]
Hi,

I have a similar issue and I would also need to get back all the entities that a value belongs to.

Example :

Let's say I have two keyword entities, the countries of EU (countries_EU) and the countries of NATO (countries_NATO) and they both have "Greece" as a value.

Chatobot : Where do you live?
User : In Greece.

This could be a form filling chatbot. In that case I would need to get back both entities recognized. I think this is an important feature. Would you consider it for implementation?

**Comment by blandinw** [comment]
@fkerasar thank you for your feedback, it definitely helps us gauge the need for such a feature :)

This difficulty is to know which entities are allowed to be returned together.
A contrived example is "Let's meet at [Noon]", here Noon could be a datetime or a location, but it would probably be incorrect to say it's both simultaneously, so we cannot allow this behavior in a generic fashion.

Ultimately, there may be a perception issue as to what data you should be storing in Wit. Wit tells you that a piece of text is describing the country known as "Greece". The fact that Greece can be a country in Europe, NATO, EU, Schengen, etc. should probably be saved in your business logic, and not in Wit itself. Wit is only concerned with extracting entities from text, and the "data schema" (or ontology) you have in Wit should only cater to this. There is a subtle difference between the two types of data that is negligible in a small app, but starts to show when you're trying to do something more complex.

Note that we do allow each entity value to have metadata attached to it where you can store e.g. a normalized ID to link it to your own database/business logic.

I will close this issue for now, but please feel free to comment back, or if you need the "soft intent slots" behavior described earlier in the thread.

**Comment by chatbotalex** [comment]
Hi @blandinw , is it possible to switch my test app to multiple intents also? appid: 2524273854283544

**Comment by rlakhotiya** [comment]
Hello @blandinw is it possible to switch my test app to multiple entities also APP ID: 516447745943988

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
