### ISSUE TITLE
Ann

### ISSUE THREAD

**Issue by annaloveDima** [wit-ai/wit#1132]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by patapizza** [comment]
Feel free to open a new ticket with provided info. :)
