### ISSUE TITLE
After posting, intent's values don't get updated when making get request.

### ISSUE THREAD

**Issue by fderen** [wit-ai/wit#1134]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

Bug.

**What is the current behavior?**

When posting via http api new values for intent, application in web app updates but when I request intent by get, values are unchanged.
When I change something in web app e.g. open metadata edit and close, values are updated.
Problem lasts until I change something in web app.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

{'error': False,
 'request': {'method': 'GET', 'path': '/entities/intent'},
 'request_timestamp': 1531222688.449999,
 'request_type': <WitaiRequestType.GET_ENTITY: 1>,
 'response': {'builtin': False, 'doc': 'User-defined entity', 'id': '5b449a15-99af-4312-af19-985190cd53c2', 'lang': 'pl', 'lookups': ['trait'], 'name': 'intent', 'values': []},
 'response_timestamp': 1531222689.385279}

{'error': False,
 'request': {'method': 'POST', 'params': '{"value": "po\\u0142\\u0105cz", "metadata": "POLACZ", "expressions": ["po\\u0142\\u0105cz", "zadzwo\\u0144"]}', 'path': '/entities/intent/values'},
 'request_timestamp': 1531222801.658321,
 'request_type': <WitaiRequestType.POST_VALUE: 5>,
 'response': {'builtin': False,
              'doc': 'User-defined entity',
              'exotic': False,
              'id': '5b449a15-99af-4312-af19-985190cd53c2',
              'lang': 'pl',
              'lookups': ['trait'],
              'name': 'intent',
              'values': [{'expressions': None, 'metadata': 'POLACZ', 'value': 'połącz'}]},
 'response_timestamp': 1531222803.127745}

{'error': False,
 'request': {'method': 'GET', 'path': '/entities/intent'},
 'request_timestamp': 1531222857.482475,
 'request_type': <WitaiRequestType.GET_ENTITY: 1>,
 'response': {'builtin': False, 'doc': 'User-defined entity', 'id': '5b449a15-99af-4312-af19-985190cd53c2', 'lang': 'pl', 'lookups': ['trait'], 'name': 'intent', 'values': []},
 'response_timestamp': 1531222861.376352}

**What is the expected behavior?**

Updated values of trait via get after posting.

**What is the App ID where you are experiencing this issue (if applicable)?**

All apps.

**Comment by jtliao** [comment]
Hi @fderen, we are investigating now, thanks for raising this.

**Comment by jtliao** [comment]
This this should be fixed now, i.e. after posting new values for intent, they will show up using GET /entities/:id. Closing for now, feel free to re-open if you are still experiencing the issue.
