### ISSUE TITLE
Wit.ai disabled button "Validate" and I can´t continue training the bot

### ISSUE THREAD

**Issue by carlostule** [wit-ai/wit#1135]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
I want to report a bug 
**What is the current behavior?**
Button "Validate" was disabled and I can´t continue training my bot.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I don´t know how to reproduce exactly the bug. I was just training my bot and suddenly the button was disabled by wit.ai
![bug](https://user-images.githubusercontent.com/17634225/42525909-00d484e4-843a-11e8-9f99-fdbc29ca82a3.PNG)
**What is the expected behavior?**
Validate new expressions pressing the button
**What is the App ID where you are experiencing this issue (if applicable)?**
5b0f0537-e697-4247-adb9-bb2d1a17c28b

**Comment by patapizza** [comment]
Thanks for reporting @carlostule, we're looking into this.

**Comment by aforaleka** [comment]
Hi @carlostule, thanks for reporting this bug, are you still experiencing it currently? I'm unable to repro it right now but feel free to reopen the issue!
