### ISSUE TITLE
[App accessing] Some thing went wrongs

### ISSUE THREAD

**Issue by minhnguyenit14** [wit-ai/wit#1137]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
Suddenly, i cant access to my app??? detail below here
![image](https://user-images.githubusercontent.com/38130019/42677399-cd0e4226-86a5-11e8-8af0-b5273bc62a62.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
i want to access to my app normally again :(
**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by minhnguyenit14** [comment]
when i f12, i found this...?
![image](https://user-images.githubusercontent.com/38130019/42678742-0294af8a-86aa-11e8-8f20-1ab8f57e1ee4.png)

**Comment by stopachka** [comment]
Hey @minhnguyenit14 is your app now called? MedicalChatBot? 

I can see it now loads, this could have been due to an intermittent failure we had last week. Let me know if you still cannot access this
