### ISSUE TITLE
Could not create entity "dinasour"

### ISSUE THREAD

**Issue by stopachka** [wit-ai/wit#1138]
app-id: 5b2775b1-fc6a-4a2f-9e0c-63e87a8e4c1c

Try to create an entity called "dinasour" 
See it says the entity is already created
However, it does not seem to exist

**Comment by kaydanial** [comment]
Had same issue , almost any entity cant be created

app-id : 59bbe086-feab-4b4b-9b54-cab99a996261

the entity exist when we get it from http-api , but it doesnt display on the dashboard

**Comment by varunish** [comment]
app-id: 5b29edbb-bacd-4d8f-95a3-5db8772ef6f1

Same problem with creating new entities, says entity created but can't see it anywhere and can't add any preexisting entities for that whole sentence, just says create a new entity. Also it's stuck at on-going training. Is this a problem with your server?

**Comment by nyotahealth** [comment]
Same problem here app-id: 5b40e21f-b401-4bd5-b357-0511c1e12bf2

I checked the backup zip and the new entity doesn't appear in it either

**Comment by asafnevo** [comment]
Same here
![screen shot 2018-07-13 at 15 59 41](https://user-images.githubusercontent.com/15774025/42693030-61ed58e0-86b6-11e8-8208-7413f6fca34b.png)

**Comment by platech** [comment]
Same here, app-id:  5ab80591-14be-4e2d-bc2a-0cbb3f516b0b

**Comment by stopachka** [comment]
Hey all, shipped the fix to this bug. Apologies for the UI bugs last week. We are working on a complete fix this week
