### ISSUE TITLE
Wit.ai Dashboard Bug

### ISSUE THREAD

**Issue by jainaayush05** [wit-ai/wit#1139]
**BUG**

I am not able to access one of my apps - https://wit.ai/yash-greendeck/octopus-category-2 on wit.ai dashboard. I can open all other apps.

Upon network inspection - I can see that wit.ai is giving a 500 error.

Can you please look into this urgently

**Comment by l5t** [comment]
Will investigate tomorrow, thanks for your patience

**Comment by l5t** [comment]
closing and will follow on the #1140
