### ISSUE TITLE
App not loading in web interface

### ISSUE THREAD

**Issue by klemensz** [wit-ai/wit#1140]
**Bug**

**What is the current behavior?**

I cannot access two of my apps in the web interface any more. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

From https://wit.ai/{username}, klicking on one app.

In Firefox and Firefox: Infinite loading, showing a 500 error in the console "Something went wrong. We've been notified." GET (https://api.wit.ai/inst/{username}/{app_name}

**What is the expected behavior?**

The app should open.

**What is the App ID where you are experiencing this issue (if applicable)?**

590c3891-b23b-4cb4-b5a2-c3cd0ef17397 and 5902737c-e922-4695-bed3-874f70abb502

**Comment by l5t** [comment]
#1139

**Comment by l5t** [comment]
Will investigate tomorrow, thanks for your patience

**Comment by stopachka** [comment]
Thank you for the patience @klemensz -- we recently landed an infrastructure change that could have caused this. I'm on this asap, and will update. 

Aim for this week for the team will be to get the system ironed out and to a robust state

**Comment by stopachka** [comment]
Hey @klemensz your pages should be back online within 15 minutes or so. Will be making long-term fixes this week. Thank you for the quick message and patience. Let us know if you have any issues

**Comment by klemensz** [comment]
Thanks, they are back again.
