### ISSUE TITLE
Bug: Expressions are not present on uploading one app zip to new app.

### ISSUE THREAD

**Issue by anurag-arora** [wit-ai/wit#1141]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
On uploading zip of one app on creation of another new app, expressions are not present.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Train one app with simple expressions and upload the zip of that app on creation of new app. Then those expressions are not present.
**What is the expected behavior?**
Those expressions must also be present when viewing specific intent or entity.

**Comment by stopachka** [comment]
Hey anurag, can you:
- say the app-id of the app you are exporting
- say the app-id of the app you imported, but which has no expressions

**Comment by anurag-arora** [comment]
My App id I am exporting- 5a9e87c8-c936-4d04-b305-33624d7f5861
Imported App Id 5b4c9f4e-1537-406b-8bd0-8460c8e51eef

**Comment by anurag-arora** [comment]
but now I am getting all the expressions, is it take some time to populate?
Anyways thanks I am closing this now.
