### ISSUE TITLE
Writes failing intermittently

### ISSUE THREAD

**Issue by platech** [wit-ai/wit#1142]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

Bug

**What is the current behavior?**

Can't add new synonyms and keywords.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Go to entities list
2. Select any entity
3. Type in new keyword/synonym
4. Press enter and wait for keyword/synonym to disappear from textbox

**What is the expected behavior?**

Synonyms and keywords should add and be visible in the entity details

**What is the App ID where you are experiencing this issue (if applicable)?**

5ab80591-14be-4e2d-bc2a-0cbb3f516b0b

**Comment by shasha79** [comment]
Same here. App ID:
58741228-a551-45b4-a33e-1a79c5fc04c3

**Comment by stopachka** [comment]
hey team, i am not able to repro this on either of your apps. 

could you: 
1. give me an example entity to click into
2. an example synonym

Apologies for the thrash, looking forward to finding and fixing this bug

**Comment by stopachka** [comment]
Most likely this was related to our database issues. Closing this, as it should not longer be the case. Let me know if we come across this issue once more
