### ISSUE TITLE
Large apps with roles fail to load

### ISSUE THREAD

**Issue by hactar** [wit-ai/wit#1147]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug.
**What is the current behavior?**
When i visit https://wit.ai/hactar/NewWaveV4, the page doesn't load, instead I get an 500 internal server error.

<img width="1325" alt="screen shot 2018-07-19 at 12 45 38" src="https://user-images.githubusercontent.com/645674/42939384-bd0a81dc-8b55-11e8-9324-45bb603dcd05.png">

**What is the App ID where you are experiencing this issue (if applicable)?**

Can't tell you the app id as I cant get to the settings, but its https://wit.ai/hactar/NewWaveV4

**Comment by palingsusah** [comment]
i have the same problem, my application wont open, 
since i also cant access the application setting menu, 
here is my application url : https://wit.ai/theochandra/VIRA_DEV

**Comment by stopachka** [comment]
Hey all, this is being caused by a UI bug affecting large apps. temporarily patched things to fix this for you two -- making a full fix now
