### ISSUE TITLE
The bot show "scheduled" label and gets stuck in training

### ISSUE THREAD

**Issue by carlostule** [wit-ai/wit#1148]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
When I try to train my bot, wit.ai show me "scheduled" label and I can´t continue the training.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
![train](https://user-images.githubusercontent.com/17634225/42964499-da9f8c9a-8b5c-11e8-80f5-cc9ddb5c4548.PNG)
**What is the expected behavior?**
To continue training the chatbot.
**What is the App ID where you are experiencing this issue (if applicable)?**
App ID: 5b0f0537-e697-4247-adb9-bb2d1a17c28b

**Comment by stopachka** [comment]
Hey @carlostule -- this could have been related to https://github.com/wit-ai/wit/issues/1119 -- This has been fixed recently, feel free to comment in there if you are still experiencing issues

**Comment by sankarGkrish** [comment]
my app Stuck on Scheduled. my app id :
2232278810168545. please do the needful ?

one more question is each time we can do it here whenever app Stuck on Scheduled message shows ?

**Comment by patapizza** [comment]
Hi @sankarGkrish, it seems like your app is done training. Please open up a new or comment on an open recent issue, it's easier to track. Thanks!

**Comment by arghya052** [comment]
Hi,

I am facing the same issue as mentioned in the initial post. Is there any permanent fix for this yet?

**Comment by OfYing** [comment]
Hi,

I'm facing the same problem, please take a look at my app.

App ID: 2206761902739252
