### ISSUE TITLE
My Wit project keep loading and won't show anything

### ISSUE THREAD

**Issue by wilsontimothyk** [wit-ai/wit#1149]
![wit](https://user-images.githubusercontent.com/31413629/42999068-9453c2f2-8c46-11e8-8a37-2a13b30cb662.PNG)

I have issue about my project, I need to access my project but then it won't load. Please tell me what should I do to fix it as I need to access my project ASAP.

Here is my project link, as I couldn't get the project ID:
https://wit.ai/theochandra/VIRA_DEV

Any help would be very appreciated.

Big thanks.

**Comment by stopachka** [comment]
(dealing with this in https://github.com/wit-ai/wit/issues/1147)
