### ISSUE TITLE
Issue with Bot Training

### ISSUE THREAD

**Issue by tarakdesai1983** [wit-ai/wit#1150]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
Continuously showing bot training is on after 30 mins as well.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
change something on bot and it will get started in training phase automatically.

**What is the expected behavior?**
It should build as soon as possible as we are in the learning phase and if it gets stuck then we have to sit till it gets solved.

**What is the App ID where you are experiencing this issue (if applicable)?**
5b3f143e-65fd-449d-92b0-be742863dfaf

5b51c011-ad55-4cfb-84f8-3b45740f3b2d

**Comment by stopachka** [comment]
merging into #1150
