### ISSUE TITLE
[consistency] entities not found in GET /entities/:id

### ISSUE THREAD

**Issue by MathieuDuboy** [wit-ai/wit#1151]
Hi,
it's impossible to execute this line : <br />

````
curl      -H 'Authorization: Bearer XXXXXXXXXXMyTokenXXX'      'https://api.wit.ai/entities/Dire_Bonjour?v=20191212'
````
It returns <br />
````
{
  "error" : "Not Found",
  "code" : "not-found"
}
````

But this command works well : 
````
curl \
     -H 'Authorization: Bearer XXXXXXXXXXMyTokenXXX' \
     'https://api.wit.ai/entities?v=20191212'
````

**Comment by semsimsom** [comment]
I have the same issue (in one of my projects) as well.
https://api.wit.ai/entities works
but https://api.wit.ai/entities/{entityName} does not work["error" : "Not Found"].
but in other projects it works well.

**Comment by stopachka** [comment]
Hey team, please provide
- Your app-id
- Optionally, information about how you created our entity 

To confirm, in /entities you see {enityName} in the response, but not in /entities/{entityName]

**Comment by stopachka** [comment]
This should be fixed -- let us know if you see any issues
