### ISSUE TITLE
Clean up "inbox" quickly

### ISSUE THREAD

**Issue by nicopetremann** [wit-ai/wit#1152]
Would be great to be able to clean up the inbox with just one click. My bot have been spammed and I received thousands of stupid messages that I do not want to treat and I have to manually click on the trash button.

**Comment by aforaleka** [comment]
Thanks for suggesting this @nicopetremann! It's on our roadmap to provide a smarter inbox experience as well as better dataset management. The temporary workaround is to duplicate your app (export/import), but we'll definitely consider your suggestion as an enhancement :)

**Comment by jtliao** [comment]
merging with #799
