### ISSUE TITLE
Allow import from a zip where files have been zipped in any order

### ISSUE THREAD

**Issue by tchapi** [wit-ai/wit#1153]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

Kind of a bug in the import system (more of a bizzare feature)

**What is the current behavior?**

If the order of the files in the zip archive is not respected, the import fails with "Failed to validate sample at index 0" which is a bit unsettling.

The correct order (written in app.json): 
  - First,`app.json`
  - Then, all entities in `/entities/*.json`
  - And then, the `expressions.json` file

I think this should be corrected so that the import system is a bit more robust. Or at least have a nice error message

See https://github.com/wit-ai/wit/issues/513#issuecomment-406896052

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Export a backup from a working app, and rezip the files in a different order, then Reimport

**What is the expected behavior?**

The order of files in the Zip should not interfere with the import

**Comment by stopachka** [comment]
Hey @tchapi -- this currently happens for an optimization -- as soon as the zip is streamed into /import, we start processing it. For this to work, things must come in the correct order. 

This may be an unnecessary optimization though -- we'll keep track of this here for a potential enhancement

**Comment by tchapi** [comment]
Oh ok, I understand.
As far as I know, this could potentially lead to problems too, since the central directory of a zip file is at the end of the file (_thus unzipping a file on the fly being somewhat dangerous_). This is well described [here](https://github.com/thejoshwolfe/yauzl#no-streaming-unzip-api).

I would be in favor of removing this optimization in the future.

Thanks for your great work on Wit anyway !

**Comment by FengyangZhang** [comment]
the order of files should no longer interfere with import, closing this issue.
