### ISSUE TITLE
PUT /entities/:id has surprising results if value name is not in expressions

### ISSUE THREAD

**Issue by shabinGravitum** [wit-ai/wit#1154]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
Keyword entity training disappears after a while

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
We have trained a sentence for a trait entity and a word in it for keyword entity, via HTTP api
Eg : Show me Sunny
[{
	"text": "show me sunny",
	"entities": [{
		"entity": "cars_en",
		"value": "sunny",
		"start": 8,
		"end": 13
	}, {
		"entity": "documents_en",
		"value": "Sunny Main - En"
	}]
}]
Documents_en is the trait entity, cars_en is the keyword entity
Problem : After some time, while typing in the same text in understanding, wit returns only the trait entity.
Wit response can be seen here : https://imgur.com/iRvKVGA

**What is the expected behavior?**
Both trait entity and keyword entity should be returned for the text

**What is the App ID where you are experiencing this issue (if applicable)?**
5af953ef-1dd6-4bcc-9817-e85776726fc3

**Comment by stopachka** [comment]
Hey @shabinGravitum -- this seems like a bug on our end, I am looking into it. In the meantime, if you could share:
 - How did you set the lookups to "keywords"
 - How did you set the synonyms for this entity "sunnie, sonny" 

This will help speed up the investigation

**Comment by shabinGravitum** [comment]
Hi @stopachka 

The lookup strategy for entity "cars_en" is keyword
The synonyms were setup using the HTTP API 
PUT /entities/:entity_id

**Comment by stopachka** [comment]
Great to know @shabinGravitum! 

Could you give a few more examples of sentences which worked previously, that now no longer work? the sunny example in your app is currently working

**Comment by shabinGravitum** [comment]
@stopachka 

You could try
- "show me sunny",
- "show me altima"
- "give me altima"

None of these return a cars_en entity, how ever
if i use a synonym of these cars_en entity, like "show me ultima", then it works fine.

**Comment by stopachka** [comment]
Hey @shabinGravitum -- Okay, bug has been found! 

For a short-term fix, when you use the api  (PUT /entities/:id), make sure to include the value name in the `expressions`

i.e instead of: 

`{value: "sunny", expressions: ["sonnie", "sunnie"]},` 

Do 

`{value: "sunny", expressions: ["sunny", "sonnie", "sunnie"]},` 

A full fix (which could involve making this more explicit in the UI) will be coming soon

**Comment by jtliao** [comment]
This should be fixed now, PUT /entities/:id will now automatically include the value itself in the expressions, we've also clarified this in the UI by showing exactly the expressions for the value, which may or may not include the value itself.
