### ISSUE TITLE
Values not being created under an Entity when posting to /samples

### ISSUE THREAD

**Issue by RobertsG** [wit-ai/wit#1155]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
BUG
**What is the current behavior?**
Samples to not get added to entities.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
All using HTTP API:
1. Created a new entity
2. Sent some values to /sample
`array:13 [
  0 => array:2 [
    "text" => "hello!"
    "entities" => array:1 [
      0 => array:2 [
        "entity" => "st_5b4600e72d6186005225cdde"
        "value" => "5b4600e72d6186005225cdde"
      ]
    ]
  ]
  1 => array:2 [
    "text" => "hello"
    "entities" => array:1 [
      0 => array:2 [
        "entity" => "st_5b4600e72d6186005225cdde"
        "value" => "5b4600e72d6186005225cdde"
      ]
    ]
  ]
  2 => array:2 [
    "text" => "hi"
    "entities" => array:1 [
      0 => array:2 [
        "entity" => "st_5b4600e72d6186005225cdde"
        "value" => "5b4600e72d6186005225cdde"
      ]
    ]
  ]
  3 => array:2 [
    "text" => "hi!"
    "entities" => array:1 [
      0 => array:2 [
        "entity" => "st_5b4600e72d6186005225cdde"
        "value" => "5b4600e72d6186005225cdde"
      ]
    ]
  ]
  4 => array:2 [
    "text" => "hi there"
    "entities" => array:1 [
      0 => array:2 [
        "entity" => "st_5b4600e72d6186005225cdde"
        "value" => "5b4600e72d6186005225cdde"
      ]
    ]
  ]
  5 => array:2 [
    "text" => "good day"
    "entities" => array:1 [
      0 => array:2 [
        "entity" => "st_5b4600e72d6186005225cdde"
        "value" => "5b4600e72d6186005225cdde"
      ]
    ]
  ]
  6 => array:2 [
    "text" => "ciao"
    "entities" => array:1 [
      0 => array:2 [
        "entity" => "st_5b4600e72d6186005225cdde"
        "value" => "5b4600e72d6186005225cdde"
      ]
    ]
  ]
  7 => array:2 [
    "text" => "hola"
    "entities" => array:1 [
      0 => array:2 [
        "entity" => "st_5b4600e72d6186005225cdde"
        "value" => "5b4600e72d6186005225cdde"
      ]
    ]
  ]
  8 => array:2 [
    "text" => "aloha"
    "entities" => array:1 [
      0 => array:2 [
        "entity" => "st_5b4600e72d6186005225cdde"
        "value" => "5b4600e72d6186005225cdde"
      ]
    ]
  ]
  9 => array:2 [
    "text" => "hello there!"
    "entities" => array:1 [
      0 => array:2 [
        "entity" => "st_5b4600e72d6186005225cdde"
        "value" => "5b4600e72d6186005225cdde"
      ]
    ]
  ]
  10 => array:2 [
    "text" => "greetings"
    "entities" => array:1 [
      0 => array:2 [
        "entity" => "st_5b4600e72d6186005225cdde"
        "value" => "5b4600e72d6186005225cdde"
      ]
    ]
  ]
  11 => array:2 [
    "text" => "hey"
    "entities" => array:1 [
      0 => array:2 [
        "entity" => "st_5b4600e72d6186005225cdde"
        "value" => "5b4600e72d6186005225cdde"
      ]
    ]
  ]
  12 => array:2 [
    "text" => "heeey"
    "entities" => array:1 [
      0 => array:2 [
        "entity" => "st_5b4600e72d6186005225cdde"
        "value" => "5b4600e72d6186005225cdde"
      ]
    ]
  ]
]`

Get a response:
`object(stdClass)#863 (2) {
  ["sent"]=>
  bool(true)
  ["n"]=>
  int(13)
}`

But the values do not apply to the entity, it stays empty, sometimes it works sometimes it doesn't I retry the request until I can finally see the values on the entity.

If I attempt to send a batch of values, sometimes only part of the batch will get inserted/trained, if I keep retrying on rare ocasions duplicates of values will get created.

**What is the expected behavior?**
Values should appear on the entity.
**What is the App ID where you are experiencing this issue (if applicable)?**
5b3256c2-98a8-45d9-b5dd-83fb4e8c6d8c

**Comment by stopachka** [comment]
Hey @RobertsG -- this may relate specifically to your app. I'll respond to it over email, but values should in about 10 minutes be okay to be inserted again
