### ISSUE TITLE
Taking time to reflect in UI (console)

### ISSUE THREAD

**Issue by tarakdesai1983** [wit-ai/wit#1156]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
When i create new intent from post man . it is taking time to reflect on console.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Have call API from postman.

URL : https://api.wit.ai/samples?v=20170307
Header
[{"key":"Content-Type","value":"application/json","description":""},{"key":"Authorization","value":"Bearer XMTVKEVNFDYBQI4PB7O2LXUBDPI7HRET","description":""}]
Data
[{
        "text": "I want an appointment for tomorrow please",
        "entities": [
          {
            "entity": "intent",
            "value": "appt_make"
          },
          {
            "entity": "wit$datetime",
            "value": "tomorrow",
            "start": 26,
            "end": 34
          }
        ]
      }]
**What is the expected behavior?**
It should reflect as soon as possible.
**What is the App ID where you are experiencing this issue (if applicable)?**
5b559e4c-c2ca-4d85-b750-1a9fcab85234

**Comment by stopachka** [comment]
Hey @tarakdesai1983 

This is because, when you send a request to POST /samples, it ends up in a queue.

We will be making an api soon to be able to know whether your sample sentences have been taken into account

**Comment by tarakdesai1983** [comment]
Hi Stephen,

Currently we are in development phase but soon we in next 10 days we are
planning to use it in production.
Pls let me know how we can avoid such delays or are we doing something
wrong.
Please suggest so we can confident of deploying in production.

**Comment by blandinw** [comment]
Even when puts in a queue, it should be pretty fast. We'll make an announcement when this feature is available

**Comment by tarakdesai1983** [comment]
Hi Willy,
Thanks for response.
But some times it makes more than 1 hour.
Any suggestions for date when we will receive it?So based on that we can
delay our production plan.
