### ISSUE TITLE
Project training stopped last Friday

### ISSUE THREAD

**Issue by asfyra** [wit-ai/wit#1157]
I believe i encountered a bug.

Although i continue to feed my project with new traits, the training process has stopped to last Friday according to projects training info: 
"All your changes have been taken into account. Your app last trained at 7/20/2018 9:02:29 AM"

The project appid is:
5b1e505b-0e5f-484a-9e44-20d7c4ee12d1

Can you please help me with this?
Thanks in advance

**Comment by asfyra** [comment]
Is there any other way we could get some help with this? It's since the 20th of July  that the app stopped training. This is very strange.

Thank you

**Comment by stopachka** [comment]
Hey @asfyra, apologies for the late response. We will investigate and update you as soon as possible

**Comment by blandinw** [comment]
@asfyra We landed a few fixes in our training logic, your app got in a weird state before then.
I trained your app successfully, and it should train automatically again, you are good to go.

**Comment by asfyra** [comment]
Thank you very much, it looks ok now. 
Thank you 👍
