### ISSUE TITLE
Can not use api anymore

### ISSUE THREAD

**Issue by maxcogay** [wit-ai/wit#1158]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question
**What is the current behavior?**
I can not communicate with the bot anymore, but I can communicate the day before, but today it only returns bad requests
Is my APP locked?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**Have call API from 'https://api.wit.ai/speech?

```
wit_access_token = 'SFGCBHUVEZDJ27CLFFP5ENQO2NOSEG2L';
        headers = {'authorization': 'Bearer ' + wit_access_token,'Content-Type': 'audio/wav'};
    	Mic.Record(1024,pyaudio.paInt16,1,8000,3,"/home/l/PROJECT/Audio/WITAI.wav").profile();
with open("/home/l/PROJECT/Audio/WITAI.wav", "rb") as binary_file:
            data = binary_file.read();
    	try:
            r = requests.post('https://api.wit.ai/speech?v=20180725',data=data,headers=headers);
            data = json.loads(r.content);
            TEXTWIT = format(data['_text']);
```

**What is the expected behavior?**

please tell me the result
**What is the App ID where you are experiencing this issue (if applicable)?**
5b16ab19-c610-47f8-881c-5a94ff08caf8

**Comment by stopachka** [comment]
hey @maxcogay -- This may be related to the audio being sent. Can inspect it, to make sure there is actual text being said in the audio? If yes, please email me the wav file and I can try to repro (stopachka [at] fb [dat] com)

**Comment by maxcogay** [comment]
hey @stopachka , I have checked the audio file very well in advance, I can use the current is not

**Comment by stopachka** [comment]
Hey @maxcogay -- I am not sure what you mean by that sentence x} -- do you mind rephrasing?

**Comment by stopachka** [comment]
Hey team, apologies for the inconvenience, we ended up with an unexpected bug that lay quietly in our speech api, which affected your usage. We've went ahead patched the service, so things should be working once more, with a long-term fix on the way.

**Comment by JulianoPensador** [comment]
Yeah,that fixed it,Thank you guys
