### ISSUE TITLE
*question* wit is finding wrong intent for me

### ISSUE THREAD

**Issue by mamehedihasan** [wit-ai/wit#1159]
Hi,

I am developing a chatbot for replying user our service price. It is in development phase. I have created a trait "What is your service price" and assigned "cleaning_price" as intent. My issue is when I am asking "What is your service price" it replies correct intent "cleaning_price" with 0.83159448987398 confidence. If I ask "What is your name?" it replies intent "cleaning_price" with 0.76480740956394 confidence. Even If I ask "What is your country?" it replies intent "cleaning_price". 

![trait](https://user-images.githubusercontent.com/25205225/43262134-e50f03d2-9100-11e8-92e3-a7d3cc9f7657.gif)

How can I better train my bot so that it will only show "cleaning_price" as intent when price related question is asked?

My App id is 5b3cb964-a679-40ce-8fef-1862ce80104c.

**Comment by stopachka** [comment]
Hey @mamehedihasan -- I would train what is your name and what is your country as an alternate intent, to give negative samples to service location. 

for example "What is your name?" can be "chitchat".

**Comment by stopachka** [comment]
(closing, please ping once more if still facing issues)
