### ISSUE TITLE
wit/datetime failing

### ISSUE THREAD

**Issue by hactar** [wit-ai/wit#1160]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug.
**What is the current behavior?**
datetime appears to be failing in my app. Neither training nor the api returns datetime values. Pure duckling correctly recognizes the time (as did wit in the past).
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Try to train or send "wie komme ich zum 16 uhr zur bartensteingasse 13" to my app. The result is this:

<img width="1001" alt="screen shot 2018-07-26 at 14 21 09" src="https://user-images.githubusercontent.com/645674/43262156-6d690146-90df-11e8-90d2-b2094f87520c.png">

Duckling correctly finds this time though:

```
 curl -XPOST http://0.0.0.0:8000/parse --data 'locale=de_AT&text=wie komme ich um 16 Uhr zur Bartensteingasse 13'
[{"body":"um 16 Uhr","start":14,"value":{"values":[{"value":"2018-07-26T16:00:00.000-07:00","grain":"hour","type":"value"},{"value":"2018-07-27T16:00:00.000-07:00","grain":"hour","type":"value"},{"value":"2018-07-28T16:00:00.000-07:00","grain":"hour","type":"value"}],"value":"2018-07-26T16:00:00.000-07:00","grain":"hour","type":"value"},"end":23,"dim":"time","latent":false},{"body":"13","start":45,"value":{"value":13,"type":"value"},"end":47,"dim":"number","latent":false}]%
```

**What is the App ID where you are experiencing this issue (if applicable)?**
5a2934a4-a921-48f2-8439-960637f89aba

**Comment by stopachka** [comment]
Hey @hactar looking into this, will update asap

**Comment by stopachka** [comment]
Hey @hactar -- looks like there was a bug on your app. I patched it, and am investigating the root cause. Can you confirm if you changed the roles for datetime recently?

**Comment by hactar** [comment]
Thanks! Not quite sure what you'd be referring to - we haven't added or removed any roles recently, or at least not on purpose (we have multiple people training the model, so I can't guarantee that someone may have mis-trained something)

**Comment by stopachka** [comment]
Cheers! Indeed, I looked back at the logs and was not able to find a recent change. Do you know when the datetime stopped working for that app?

**Comment by hactar** [comment]
It is not a frequently used feature of the app (though it will be after the next update) - so it might not have worked for months, I only noticed it after a bug report today.

**Comment by stopachka** [comment]
Cheers @hactar -- will keep an eye out for this bug then. Thanks for the comprehensive report, and let us know if you see anything suspicious!

**Comment by blandinw** [comment]
Hi @hactar, the fix we made last time was not optimal, so I took it upon myself to reverse it since you're saying you'll rely on this feature more later. I'm looking as to what the root cause is so that we can implement a robust and long term solution. Looking now, thanks for bearing with us.

**Comment by blandinw** [comment]
@hactar we were able to find the root cause. In summary, roles are a bit harder to find than just datetimes since several models have to agree with Duckling. We're deploying a fix in our "consensus logic" to be more lenient in this case.

Thank you for the feedback, and let us know if you encounter other issues, or if we can help further.

**Comment by blandinw** [comment]
We're live, let us know if we can further

**Comment by hactar** [comment]
@blandinw Thanks, works like a charm, your help is greatly appreciated!
