### ISSUE TITLE
How to synch Wit apps?

### ISSUE THREAD

**Issue by shabinGravitum** [wit-ai/wit#1162]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Ask a *question*

**Question**
We have a dev and a prod instance for our application. We need some way to synch the wit apps used by the prod instance with the training done on dev apps. Currently, the dashboard supports only creation of new apps from exports, not uploading exports to existing apps.

Is there a work around for this? If not, please consider this a feature request.

**Comment by jtliao** [comment]
hi @shabinGravitum , currently there isn't a way to upload to an existing app. What you can do instead is use the export file from one app and programmatically use our API to post the entities/samples you want to the other app.
