### ISSUE TITLE
Problems with Composite Entities 

### ISSUE THREAD

**Issue by 91ns** [wit-ai/wit#1163]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
Training of composite entities, doesn't always work, I tried creating a new app and validated these simple expressions multiple times. But it still wont work 

![image](https://user-images.githubusercontent.com/25252530/43364954-468470ec-932d-11e8-9d8b-d29172e1d0d1.png)

![image](https://user-images.githubusercontent.com/25252530/43365011-16610bf4-932e-11e8-89fa-70c3d6f62526.png)

Also, sometimes when built-in entities are used as sub-entities, the main entities doesn't get detected at all. 
For the most part, a while after training some of the composite entities stop working altogether. this makes it unreliable to use. 
Is there a certain way that composite entities have to be trained to ensure they work correctly?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Composite entities to not change after training.

**What is the App ID where you are experiencing this issue (if applicable)?**
5b5d839c-6b60-4ccb-ace5-9c82ae1b2b40

**Comment by 91ns** [comment]
Any updates on this? I'm having to validate the same expressions many times but it's still not working. 
I'm having the same issue with this app-id 2079802055419996

**Comment by jtliao** [comment]
hi @91ns , sorry for the delay- we recently put in a fix that should address this (cc #1183 ) and I went ahead and fixed it in the first app you linked. For app-id 2079802055419996, I didn't see any composite entities that exist, let me know if there's something I'm missing for that app.

**Comment by jtliao** [comment]
Just tested creating a new app and trained "black dell laptop" as above along with some samples like "black laptop" and "laptop", then checked to see if entities are detected correctly in "black dell laptop" below:

![screen shot 2018-08-17 at 9 14 50 am](https://user-images.githubusercontent.com/13305586/44276956-073cf280-a1fe-11e8-8f1d-e5ad32a295cd.png)
