### ISSUE TITLE
Exact match not working on a phrase

### ISSUE THREAD

**Issue by RobertsG** [wit-ai/wit#1164]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
I’m currently having issues with phrases not matching as expected. I have an entity called "Small Talk" in which I have several phrases with target values, I have also attempted to enter each of the question and its variations in separate entities to see if that helps, but the results are the same.

When I try to test the matching by entering “i like you” (which is an exact match) into the testing field, I get no matches:

{
  "_text": "i like you",
  "entities": {},
  "msg_id": "0XZUBBdaUzCalqpX7"
}
Even if I go to the entity and open the phrase it shows nothing in entities:
https://www.dropbox.com/s/z85yz2mmq42k3ji/Screenshot%202018-07-30%2010.18.10.png?dl=0

I have currently removed the one with the “." for a test, but it has not changed anything yet.
I’d love to know what the issue could be and how I can fix it.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I just created an entity and trained it with several samples that should return different values.

**What is the expected behavior?**
The phrase matches if its an exact match.

**What is the App ID where you are experiencing this issue (if applicable)?**
5b3256c2-98a8-45d9-b5dd-83fb4e8c6d8c

**Comment by RobertsG** [comment]
Same applies to AppID: 5b3256ab-86a1-4818-8bb2-5cd301e3e8dc
where I have trained the questions as seperate entities.

**Comment by blandinw** [comment]
The issue with `5b3256c2-98a8-45d9-b5dd-83fb4e8c6d8c` is that even though you validated 2 samples with the right annotations ("i like you" and "i like you."), you also validated 2 counter examples (with no annotations): "I like you" and "I like you."

We are working on giving you more visibility on the data used for training for each entity. In the meantime, you can list the counter examples (aka. negative samples) for a given entity with the following cURL query:
```
curl -XGET 'https://graph.willy.sb.wit.ai/samples?access_token='$WIT_TOKEN'&limit=10000&entity_ids\[\]=small-talk&negative=true' | jq . | vi -
```

**Comment by RobertsG** [comment]
@blandinw, unfortunately, I can't get anything from that domain as it's not reachable.
`curl: (6) Could not resolve host: graph.willy.sb.wit.ai`

**Comment by l5t** [comment]
You can try this instead:
```
curl \
 -H 'Authorization: Bearer YOUR_TOKEN' \
 'https://api.wit.ai/samples?v=20180801&negative=true&limit=10000&entity_ids\[\]=intent'

```
