### ISSUE TITLE
App is stucking in ONGOING

### ISSUE THREAD

**Issue by tarakdesai1983** [wit-ai/wit#1165]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
after making changes app gets stuck in Ongoing status.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Tried to add some entities and intent from API and then when it tries to build it gets stuck.

**What is the expected behavior?**
It should get stuck and if there is any bug from our side then let us know.

**What is the App ID where you are experiencing this issue (if applicable)?**
5b5f1251-24e4-4728-8b63-1ad4b4e843fa

We are in development phase and due to an issue from our side it is getting stuck then please let us know where we are doing the mistake.
Thanks

**Comment by henninghalv** [comment]
I have had the same problem twice now. But I have a hacky solution if your app is not in production.

In our project we are currently just training the bot to reach a certain level of understanding. After that it will not be trained once deployed (at least not very often).

What you can do is to export all your data from your bot, then create a new bot where you import all that data, and then just delete the old one.

This solved the issue for me, as the new bot now says "Done".

As I said, this can only be done if the bot is not live or being used.

Hope this helps!

**Comment by blandinw** [comment]
@henninghalv we apologize for the inconvenience, please report your app id when that happens

**Comment by blandinw** [comment]
More reports
58aecb8b-e2a7-46ff-8f5d-3a04e81575ac
5b3c93e4-a6b3-45bd-af1e-e0c8ffbae98b

**Comment by henninghalv** [comment]
Here is mine which is stuck: 
5b5982b7-ed75-4051-b9a9-ae77da98a9b6

But as I said, I have a working duplicate.
I will report again if this one freezes as well.

**Comment by blandinw** [comment]
We implemented a last wave of fixes to our training stack end of last week. That should do it for the recurrent issues we've been seeing. I'll close this one up folks, please comment here or open a new issue if something goes haywire.

**Comment by matsjs** [comment]
Hi, my app is also stuck in ongoing.

When I do get a response some of the entities that my app used to get are not returned or blank. I've been training these entities - could that cause no response until retrain?

Also, I've been getting 500 errors quite often. Are there server issues today?

App-ID: 
5b616a37-0016-4e9d-a723-5cd2fe35d2f55b616a

Best Regards

**Comment by blandinw** [comment]
@matsjs thank you for your feedback!

1) Did you mean id "5b616a37-0016-4e9d-a723-5cd2fe35d2f5"? If so, is it just a typo, or are we showing you the wrong ID?
2) What makes you think your app is stuck? It is scheduled to be trained, as you should be able to see in the UI. Let us know how we can make it more transparent!

**Comment by kvvojciechowski** [comment]
Also, '5b6b0a95-f453-431b-b218-493fe5cec1b6' is stuck too.
