### ISSUE TITLE
PUT /entities/:entity-id inconsistency between UI and API

### ISSUE THREAD

**Issue by didjoman** [wit-ai/wit#1166]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
BUG

**What is the current behavior?**

After a PUT on the API, the UI contains the new list of values given in the put (as expected) whereas the API contains the old list PLUS the new values given in the list.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1 - I use the API to create the entity : 

```
 {
  "id":"toto",
  "values":[
      {"value":"value1"}
   ]
 }
```
After that both the UI and the API have an entity toto with a value "value1".

2 - Then I update my entity (with the API) : 
```
 {
  "id":"toto",
  "values":[
      {"value":"value2"}
   ]
 }
```

And after the update, the API and the UI have 2 different entities:
On the API I have :
```
 {
  "id":"toto",
  "values":[
      {"value":"value1"},
      {"value":"value2"}
   ]
 }
```
And in the UI, I have : 
Toto with only the value 2 

**What is the expected behavior?**

I expected the UI and the API to give the same result (the entity retrieved after a GET should contain the exact same list as the one given in the PUT).

**What is the App ID where you are experiencing this issue (if applicable)?**
5b601f6d-27b7-4bcc-b41f-319fd7ff62f5

**Comment by stopachka** [comment]
Great catch @didjoman -- Looking into this now

**Comment by stopachka** [comment]
this has since been fixed. Let us know if you see any issues!
