### ISSUE TITLE
App training state is stuck in ONGOING

### ISSUE THREAD

**Issue by bmcclenahan** [wit-ai/wit#1167]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
My App has been training for a few days

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Training should complete

**What is the App ID where you are experiencing this issue (if applicable)?**
58aecb8b-e2a7-46ff-8f5d-3a04e81575ac

**Comment by mallik1055** [comment]
+1 mine since 3 hrs.
5b3c93e4-a6b3-45bd-af1e-e0c8ffbae98b

**Comment by blandinw** [comment]
duplicates  #1165
