### ISSUE TITLE
Feature request: PUT /entities/:entity-id/values/:value + more values, more synonyms per value

### ISSUE THREAD

**Issue by Chaosfirebolt** [wit-ai/wit#1168]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Ask questions

My app has few entities which might potentially exceed 1000 keywords, and some of the keywords will exceed 50 synonyms. Keywords, metadata and synonyms will be handled by the client and since there is a lot of keywords and metadata is in json format using UI for updates will not be possible.

So the questions are:
1. Is there a way to update metadata for a single keyword? Currently i need to retrieve every keyword in my entity to find the one i need and then update metadata with update entity put request.
2. Is it possible to get every synonym of a keyword(currently it's limited to the first 50)? Workaround using limit and offset params in url would be good enough for me.

If it's not possible, please consider those feature requests :)

**Comment by blandinw** [comment]
Hi @Chaosfirebolt, thank you for your feedback!

- How many potential values and synonyms per value do you think you may have?
- At the very least, I'll keep this one open as a feature request to support
  - updating one value (maybe PUT /entities/:entity-id/values/:value
  - more values and synonyms

**Comment by Chaosfirebolt** [comment]
Thanks for reply @blandinw 

I am expecting few hundred keywords each with 2, maybe 3 synonyms, at the beginning, and then the numbers to gradually increase to few thousand keywords, some of those with few tens of synonyms, as the client trains the bot according to his needs (that's just a rough estimate, i won't be the one training the bot after it goes live, so i can't be sure things will go that way). My main concern is that some synonyms might get removed from the list, if i can't retrieve all of them, since i am updating the entire entity.

Actually I just noticed that i could not add more than 50 synonyms. Can i safely assume this is the expected behaviour and currently we can't have more than 50 synonyms per keyword? If so, that would actually make my concerns non-existent.

**Comment by blandinw** [comment]
You're right that we do not support at the moment more than:
- 1000 keyword values
- 50 synonyms per keyword value

We are making improvements that would let us allow up to 10k values and later more than 50 synonyms per value. If you'd like an early access to have up to 10k values, you can provide me with your appid and I'll allow that behavior.

Keeping this issue open to track the need

**Comment by Chaosfirebolt** [comment]
Thanks for the help 👍 . I'd like to have early access, but we are still testing stuff, so I'll provide you an app id later on, when we are ready for deployment.

**Comment by stopachka** [comment]
Cheers @Chaosfirebolt -- closing issue for now
