### ISSUE TITLE
Bad request error using the speech() sample code 

### ISSUE THREAD

**Issue by TalitaAnthonio** [wit-ai/wit#1169]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug 

**What is the current behavior?**
I use the example code that is provided on the github page to conduct audio-to-text recognition. 

```
client = Wit(access_token)

resp = None
with open('path-to-file', 'rb') as f:
  resp = client.speech(f, None, {'Content-Type': 'audio/wav'})
print('Yay, got Wit.ai response: ' + str(resp))
```

I tried it with different files and get the following error: 

Traceback (most recent call last):
  File "wit-test.py", line 9, in <module>
    resp = client.speech(f, None, {'Content-Type': 'audio/wav'})
  File "/Users/TalitaAnthonio/Documents/Studie/stage/scripts/UMCG-stage/venv/lib/python3.6/site-packages/wit/wit.py", line 88, in speech
    data=audio_file, headers=headers)
  File "/Users/TalitaAnthonio/Documents/Studie/stage/scripts/UMCG-stage/venv/lib/python3.6/site-packages/wit/wit.py", line 41, in req
    ' (' + rsp.reason + ')')
wit.wit.WitError: Wit responded with status: 400 (Bad Request) 

I am working with Python 3.6.0

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

```
client = Wit(access_token)

resp = None
with open('path-to-file', 'rb') as f:
  resp = client.speech(f, None, {'Content-Type': 'audio/wav'})
print('Yay, got Wit.ai response: ' + str(resp))
```

**What is the expected behavior?**
Audio-to-text recognition 

**What is the App ID where you are experiencing this issue (if applicable)?**
5b5229c9-3886-48d6-872c-0198b1c4d46b

**Comment by blandinw** [comment]
Works for me®
Please provide a link to the audio file you're using, is it proper audio/wav?

If not you'll have to change the content-type to match the encoding, see our HTTP docs for the supported content types: https://wit.ai/docs/http/20170307#post--speech-link

**Comment by TalitaAnthonio** [comment]
Thanks for your reply. I think the file is in wav, could it be that there is something else wrong with it? I did expeirment with a similar file though and it did not work either. 

[t1_HerwinJulia_ch2-kort_01.wav.zip](https://github.com/wit-ai/wit/files/2262082/t1_HerwinJulia_ch2-kort_01.wav.zip)

**Comment by blandinw** [comment]
The file seems to be a valid .wav and the snippet above works for me on both Python 2.7.10 and Python 3.6.5 on the latest macOS.

Are you positive you're using the right token?
What operating system are you using?

**Comment by TalitaAnthonio** [comment]
I am using Python 3.6.0 and my mac OS version is 10.13.6.  

I see now that the error only occurs for specific wav files (see Zip files with working and non working files)> Are there certain requirements? Such as that the file should not be longer than 3 minutes or not bigger than a certain amount of MB? In case that it matters, I am trying to do Dutch speech recognition.

**Comment by blandinw** [comment]
@TalitaAnthonio there is a softly enforced ~20 seconds timeout, to avoid abuse. There should be no limit on file size, but if your audio file is in the MBs, then it's probably too long as well.
What .zip files are you referring to? The previous zip only contains one .wav

**Comment by blandinw** [comment]
Closing, feel free to comment with more information
