### ISSUE TITLE
POST /speech -> 400 Bad request

### ISSUE THREAD

**Issue by geo-matheou** [wit-ai/wit#1170]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
* Bug

**What is the current behavior?**
* I am receiving the following error: `Could not request results from Wit.ai service; recognition request failed: Bad Request`.  I would like to ask what this message means. Also, are any requirements for the wav files?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
* I am using Wit.ai through this library: https://pypi.org/project/SpeechRecognition/
* I have stereo wav files (2 channels, 8KHz) and I am converting them to two different mono wav files with 16KHz.

**Comment by blandinw** [comment]
Could you share your app id and upload a sample .wav file?

**Comment by geo-matheou** [comment]
Hello. Unfortunately, I can't upload wav files due to confidentiality issues. Thank you very much for your reply.

**Comment by blandinw** [comment]
Sounds good, let us know if you manage to reproduce the issue with a file that you can share.

**Comment by geo-matheou** [comment]
OK Willy. Thank you very much!
