### ISSUE TITLE
Whenever I make a new app, Its tokens just disappears from the witai after some time. 

### ISSUE THREAD

**Issue by himanshuteotia** [wit-ai/wit#1172]
![wit ai amway_tewam_assignment](https://user-images.githubusercontent.com/10083136/43884896-eeb0e966-9be9-11e8-918a-4430a7ffbe72.png)
![wit ai amway_team_assignment](https://user-images.githubusercontent.com/10083136/43884897-eef6d8a4-9be9-11e8-856d-99ff95719cdd.png)

**Comment by asfyra** [comment]
The same thing happens to me also 
![image](https://user-images.githubusercontent.com/6898230/43902186-1a68bb58-9bf2-11e8-9036-573681d316c7.png)

I recreate the token, the app id changes to some GUID a new token is shown and after a while it disappears and the appid is becoming number.

Thank you

**Comment by Joinfield** [comment]
some issue here. english language, newly created app. other apps running smoothly.

**Comment by Joinfield** [comment]
@asfyra  @himanshuteotia  got a workeround: press the renew token button on the right beside the inout field and you get a new token. copy this directly into you code. it will disappear after page reload. for me this work for now ...

**Comment by stopachka** [comment]
Hey team, we are aware of this bug, and have found a fix. Will update here when it has landed

**Comment by stopachka** [comment]
Landed!
