### ISSUE TITLE
App status stuck in ONGOING

### ISSUE THREAD

**Issue by kvvojciechowski** [wit-ai/wit#1174]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug.

**What is the current behavior?**
App's status stuck in "ONGOING"

**What is the expected behavior?**
App's status should change

**What is the App ID where you are experiencing this issue (if applicable)?**
5b6b0a95-f453-431b-b218-493fe5cec1b6

**Comment by kvvojciechowski** [comment]
Ok, now it has SCHEDULED.

**Comment by blandinw** [comment]
@kvvojciechowski thank you for your feedback! This still took way too long than it should and should be considered as a bug.

I've implemented a priority queue for small apps like yours to be trained quickly, regardless of how many big apps we're trying to train at the same time, hopefully things are smoother from now on.
