### ISSUE TITLE
I am unable to fork open wit apps

### ISSUE THREAD

**Issue by BenBergman** [wit-ai/wit#1176]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Many sources talk about forking open apps in wit.ai but I am unable to find the fork option. In particular I am trying to test out the examples from the `node-wit` library.

**What is the current behavior?**
Currently there seems to be no way to replicate an open app with a fork button or otherwise.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Look at an open project and there is no fork button.

**What is the expected behavior?**
There should be a fork button.

**What is the App ID where you are experiencing this issue (if applicable)?**
https://wit.ai/aforaleka/wit-example-joke-bot

**Comment by stopachka** [comment]
Hey @BenBergman -- we have deprecated the forking option, but I will look into was to solve the core issue, of being able to replicate open projects

**Comment by BenBergman** [comment]
Great, thanks.

I see an import option is still present. I imagine a way to export open
projects would be okay.

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
