### ISSUE TITLE
Training added by POST /samples are ignored

### ISSUE THREAD

**Issue by shabinGravitum** [wit-ai/wit#1177]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
Training added by POST /samples api not being saved, not returned by GET /samples

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Step 1 : Try to train the app with POST /samples
Eg body : [{
    "text": "Show me all dealers",
    "entities": [
    	{
	        "entity": "documents_en",
        	"value": "Dealer Main - En"
    	}
    ]
}]
Wit responds with 200OK 
Response body : {
    "sent": true,
    "n": 1
}

Step 2 : Try to retrieve the trainings GET /samples?v=20170307&entity_ids=documents_en&entity_values=Dealer Main - En&limit=100

The returned array does not contain the string send in the previous step

**What is the expected behavior?**
The returned array should contain the newly trained string

**What is the App ID where you are experiencing this issue (if applicable)?**
5af953ef-1dd6-4bcc-9817-e85776726fc3

**Comment by dibyendu** [comment]
I have been experiencing the same since past 3/4 days.

**Comment by stopachka** [comment]
Hey all, this should be cleared now. If you are still experiencing this, comment with your app-id

**Comment by TobyColeman** [comment]
Experiencing the same problem above, have tried a few times with a completely fresh app too. 

**App ID:** 2014989421866256

**Comment by lpiacquadio** [comment]
+1

App id: 1883173705093393

**Comment by jtliao** [comment]
Our systems were overloaded by some apps that posted way too many samples-- the samples will slowly get trained, sorry for the inconvenience.

**Comment by Emb1ter** [comment]
Experiencing the same with all of the apps, which I have.

1823291164372822182329
1071472866310970
