### ISSUE TITLE
Datetime entity not working!

### ISSUE THREAD

**Issue by OmarJabri7** [wit-ai/wit#1179]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
My app is not parsing datetime, because the attribute disappeared from the entities in wit. I see that there is an entity named wdatetime, but it is for experimental purposes and not for use.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Datetime entity disappeared, so whenever a representation of a date is sent, i.e. tomorrow, after 3 hours, in 2mins, etc.. The app crashes
**What is the expected behavior?**
To parse datetime, send me the right date in 'Y-m-dTH:i:s' format so my app parses it successfully
**What is the App ID where you are experiencing this issue (if applicable)?**
5b48b61b-a3ce-48e7-856c-2d93d794aa57

**Comment by jackneil** [comment]
+1. :+1: 

This breaks my bot completely :/

**Comment by stopachka** [comment]
Hey all, apologies for this. We are  looking into it, and will update here asap

**Comment by stopachka** [comment]
Oky doke, mitigated the issue. You should now be able to use the UI. Looking deeper into the root cause

**Comment by stopachka** [comment]
cc @jackneil -- when you say it broke your bot completely, do you mean it broke your API usage? (i.e GET /message) -- this should not have been the case, so if it did please give us more info

**Comment by jackneil** [comment]
hi @stopachka. Good point. It didn't literally 'break the bot' but with many elements depending on datetimes being sent along with the data (we are using it for healthcare provider documentations) it made it effectively broken. 

I'll be more clear next time :) And thanks for mitigating the issue so quickly. A+ effort and we love wit

**Comment by stopachka** [comment]
Cheers @jackneil!
