### ISSUE TITLE
destroy app is not working

### ISSUE THREAD

**Issue by jackneil** [wit-ai/wit#1180]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
after clicking 'destroy app' and confirming on the popup (web UI - settings page), a yellow message box appears in the upper right of the screen appears that states 'Could not find app.' ... and the app is not destroyed. There doesn't seem to be a functioning method by which to remove an app currently

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
see above

**What is the expected behavior?**
destroy app should delete the app after confirmation

**What is the App ID where you are experiencing this issue (if applicable)?**
1835081906568725 ... but this may be the problem. I exported my functioning app, then tried importing it a few times to create a cloned app to tinker with. It appears many of the apps created during the import process have this same ID. I do not wish to remove all the apps (as my main, functioning app shares this same ID), just some of the cloned ones. Seems the import process may have imported the actual AppID which may be confusing the destroy app process.

UPDATE: that last paragraph may be incorrect. It appears the way the webUI loads the AppID it doesn't always refresh the AppID field when switching between apps (I'm using Chrome). A full page-refresh after loading the Apps settings does show unique AppIDs for each app. However, even after doing the page refresh and getting what appears to be the correct, unique ID, 'destroy app' still does not function. :/

**Comment by jtliao** [comment]
Hi @jackneil, we're looking into this-- thanks for bringing it up!

**Comment by blandinw** [comment]
Should be fixed now, thank you for your feedback!

**Comment by jackneil** [comment]
OK. So major issue here!

It appeared that the destroy-app had been corrected, so I began deleting the junk apps in my account. I deleted 3 and was VERY careful to not delete my main, functioning app. However, my main functioning app was deleted! The destroy-app function has a SERIOUS BUG and I would recommend disabling it until this is fixed.  If there is not a copy of my main functioning app I will have lost ~100 hours of work (since the import/export features do not work effectively). 

Please help! And please re-open this issue.

**Comment by stopachka** [comment]
Hey @jackneil -- indeed, this is pri 0. Investigating now. Thank you for your patience, I'll update asap as we get more info

**Comment by jtliao** [comment]
Hey @jackneil- Your app should be restored now, let us know if you don't see it still. We've temporarily disabled app deletion while we fix the underlying issue. Apologies again for the inconvenience

**Comment by jtliao** [comment]
Delete app is now re-enabled as the app id issue was fixed

**Comment by jackneil** [comment]
OK thanks for your quick response and a HUGE thanks for being able to recover my app!! I was sweating :)
