### ISSUE TITLE
problem with composite entity identifying subentities

### ISSUE THREAD

**Issue by jackneil** [wit-ai/wit#1183]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
I have a composite entity called 'drugObject'. The model has been trained with subentities (some keywords, some keywords + freetext, some numbers) to identify the components of a drug-dose. An example is: 20ml bupivacaine 2% IV. Despite a large number of trained utterances labeled according to the 'expected behavior' findings below, the following always occurs:
20ml bupivacaine 2% IV = drugObject (correct)
bupivacaine = drugName (correct)
ml = drugUnit (correct)
20 = number (wrong. should have role number:drugDose assigned)
2 = number (wrong. should have keyword role drugConcentration = 2%)
IV = never assigned to an entity. The drugRoute entity is never assigned within drugObject. ever. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Given the example above, the following should be labeled.
20ml bupivacaine 2% IV = drugObject (composite entity - freetext/keyword)
20 = number:drugDose
ml = drugUnit (keyword entity)
bupivacaine = drugName (keyword entity)
2% = drugConcentration (keyword entity)
IV = drugRoute (keyword entity)

Interestingly, the drugConcentration, number:drugDose, and drugRoute (which are the entities not being assigned correctly when a drugObject is identified) do get correctly assigned if wit does not identify drugObject in the sample. I.e. when the entities listed above are not wrapped inside a drugObject entity, wit finds them correctly. 

I know this seems to be a complex and unique bug, but I feel this may replicate within other projects when there are subentities ... as there don't seem to be issues if I do not attempt to use a master drugObject entity.

**What is the App ID where you are experiencing this issue (if applicable)?** 
1903459246359284

Hopefully I didn't lose you in that explanation. Thanks for reading this far and hopefully helping to figure this out. I've trained a model for this use case using luis.ai and it works quite well. But the intelligence of the wit.ai NLP engine is far superior to luis' at inferring entities from samples rather than having to predefine every possible entity example ahead of time. Hopefully y'all are able to figure this one out as I'd strongly prefer to use wit as out main engine. The only other hinderance to this (which is already identified in another older ticket) is that the export and import functions of wit do not work properly. 

Thanks!
-jack

**Comment by jtliao** [comment]
Thanks for raising, looking into it now!

**Comment by jtliao** [comment]
Looks like there was a bug with composite entities, the fix might help your situation-- can you let me know if it's better now?

**Comment by jackneil** [comment]
I'm ok with closing this, but any idea about why the wit entities with roles are not being assigned inside of composite entities? the wit\entity is being assigned, but never a wit\entity:role
