### ISSUE TITLE
Missing Tabs (Inbox, Logs) in Bot UI

### ISSUE THREAD

**Issue by serdalbayram** [wit-ai/wit#1186]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
**Bug**

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/25345380/44202053-99d48780-a153-11e8-83b4-42d4692fe6bb.png)

For my bot (app id: 1622020321212473), only understanding tab is active but other tabs (Inbox, Logs etc.) are not visible to me.  

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open the bot

**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**
1622020321212473

**Comment by jtliao** [comment]
merging this into #1187 , which also deals with non-creators being unable to edit

**Comment by serdalbayram** [comment]
thanks
