### ISSUE TITLE
Impossible to edit 

### ISSUE THREAD

**Issue by vcnsiqueira** [wit-ai/wit#1187]
This problem had been solved, but it returned.

I created an app and shared with some colleagues. Unfortunately they cannot edit or create other entities. These are the problems:

1. They only have access to the Uderstanding tab, no access to settings, inbox or logs tabs.
2. They can't delete or edit entities.
3. The input field in the UI, where you train your bot is inactive for them, it is active for me, the app owner.
4. Non of the samples were transfered to the new app. There are no samples in the UI, get samples request from HTTP API also returns an empty array.
5. No one can download the zip file of the app.

App number: 1808172539205079

**Comment by jtliao** [comment]
We are looking into this, thanks for raising

**Comment by jtliao** [comment]
@vcnsiqueira just to make sure, are you still seeing this issue? We put out some fixes in the past day that may have addressed this issue, but want to confirm first.

**Comment by vcnsiqueira** [comment]
Now it's working. This problem had been solved and returned. At this moment the only problem I've been facing is that I can't download de .zip of my data.

**Comment by vcnsiqueira** [comment]
Every time I try, it appear this message:
![image](https://user-images.githubusercontent.com/35041704/44284331-a9c59780-a237-11e8-9b93-9d98504e0c3a.png)

**Comment by jtliao** [comment]
That's related to another issue that we're working on fixing cc #1173 , closing this task
