### ISSUE TITLE
Server Access and Client Tokens missing from Settings tab

### ISSUE THREAD

**Issue by paulopadopalos** [wit-ai/wit#1188]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
This is a bug.

**What is the current behavior?**
When I log into the Wit.ai dashboard and click on the "Settings" tab, the boxes for "Server Access Token" and "Client Access Token" are empty, even though I have valid tokens currently in use. Also, when I use the box at the top of the screen to try out cURL, the generated curl command is missing an authorisation token.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Log into Wit.ai, choose an app and click on Settings.

**What is the expected behavior?**
Previously the tokens were visible in the user interface, and curl commands generated at the top of the page included an authorisation token.

**What is the App ID where you are experiencing this issue (if applicable)?**
I'm seeing this affect both my Wit.ai apps:
- 1725778067474595
- 1725778067474595

**Comment by jackneil** [comment]
Link to https://github.com/wit-ai/wit/issues/1172

**Comment by jtliao** [comment]
Looking into this, thanks for raising

**Comment by mikesusi** [comment]
also having this problem...please let us know when resolved

**Comment by jtliao** [comment]
This should be resolved now- if you can't see the tokens, refreshing the page should fix it. We're in the process of putting out a larger fix regarding the app id not displaying and not needing to refresh, thanks for your patience.

**Comment by paulopadopalos** [comment]
Confirmed – this is working for me now. Many thanks @jtliao!
