### ISSUE TITLE
Wit.ai doesn't find intent of sentence

### ISSUE THREAD

**Issue by Teelte** [wit-ai/wit#1190]
I don't know if it's a bug or just me but when I first use my app and trained with only 3 examples it was working great and finding the right intent, but now it doesn't find it anymore. 
![image](https://user-images.githubusercontent.com/40150094/44219778-26e00680-a17d-11e8-8058-31a55d135b42.png)

It is supposed to recognize the "translate_get" intent but it doesn't, same for the API, it doesn't output the intent.

Here is my app id: 2107168016024526

**Comment by jtliao** [comment]
We're looking into the issue, thanks for raising.

**Comment by jtliao** [comment]
Hi @Teelte , I went ahead and retrained your app, and it seems to be working as intended now (see screenshot below). Thanks for your patience!

![image](https://user-images.githubusercontent.com/13305586/44264881-18273d00-a1d9-11e8-87b4-f8f7437e27e0.png)
