### ISSUE TITLE
Insight dosen't work

### ISSUE THREAD

**Issue by Ramios95** [wit-ai/wit#1192]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug 
**What is the current behavior?**
Insight shows "Validate more expressions to get insights for this entity 😊" even after validating more than 50 expressions
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I submited 100 expression to the app with the same value in the same entity, but still Insight is empty.
I did the same before and the insights show two lines of values equal to 1
**What is the expected behavior?**
A graph showing precision and recall on the insight field
**What is the App ID where you are experiencing this issue (if applicable)?**
App ID : 1836820343077021183682

**Comment by patapizza** [comment]
Hi @Ramios95, thanks for reporting. You sent way more than 100 expressions, we had to block your app from using `POST /samples`, to prevent impacting other users. I'll look into why you don't get Insights.

**Comment by Ramios95** [comment]
I m sending way more because i though it wasn't working at all when the insight don't show a thing. 
If you can activate the insights for this app , ID = 1820266764706804. I m training it by a backup file but nothing is displayed on the insights field.

**Comment by ben94lim** [comment]
Hi I am having the same issue where I am adding/removing entities and samples using the HTTP API and my entities are going through but not my samples. I am also using POST /samples but I'm only sending around 5 at a time and the WIT UI shows that the entities were updated but none of the samples got through.

App ID: 5b6125b9-1697-48db-a71b-3e1fdad24900

**Comment by patapizza** [comment]
Thanks for your patience, fix upcoming.

**Comment by patapizza** [comment]
@Ramios95 This is now fixed.

**Comment by sudoStatus200** [comment]
@patapizza 
I cannot see insight section on this page "https://wit.ai/kshitijpurwar/BreeZo/entities"
I cheked everywhere I could not found insight section
