### ISSUE TITLE
App Train is not working

### ISSUE THREAD

**Issue by tarakdesai1983** [wit-ai/wit#1193]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
When we call POST https://api.wit.ai/samples API it return true but intent is not getting created in UI.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Created new app and called this API to create new intent.
**What is the expected behavior?**
Intent should be created.
**What is the App ID where you are experiencing this issue (if applicable)?**
1873273056050029

**Comment by lpiacquadio** [comment]
+1

**App ID:** 1883173705093393

**Comment by jtliao** [comment]
Hi, we were experiencing a large number of POST /sample requests in our queue, they have been cleared now (checked both of your apps, they seem to be retrained now).

**Comment by tarakdesai1983** [comment]
thanks. sure let me check
