### ISSUE TITLE
Contact entity not getting identified on changing the sentence structure

### ISSUE THREAD

**Issue by monika1800** [wit-ai/wit#1194]
**report a *bug***

**the current behavior**
Doesn't recognises "contact"entity on changing the sentence structure.
Example:
Works using "I want to pay john 8000"
Doesnt works for "remind me to pay john 8000 "

**expected behavior**
Should recognise the entity not solely based on structure.

**Comment by jtliao** [comment]
hi @monika1800 , can you post your app id please?

**Comment by jtliao** [comment]
Closing as it's been a month, feel free to re-open with more details
