### ISSUE TITLE
Bug: German language app detecting english instead of german

### ISSUE THREAD

**Issue by marcelgoya** [wit-ai/wit#1195]
My german app started to detect english sentences instead of german for no apparent reason. German words are not being detected anymore.

My app id is:

578d1094-55a1-4088-99df-c3f6789b008b

**Comment by jtliao** [comment]
Hi @marcelgoya , when looking at your app, I don't see any samples or entities, can you clarify?

**Comment by marcelgoya** [comment]
Hi @jtliao,

sorry about my late reply. You're right, it's just a test account at the moment and I wanted to check how the recognition quality for german is. Like I said, it's only recognising english. Is it supposed to make a difference when I add entities?

Thanks,
Marcel

**Comment by marcelgoya** [comment]
Sorry, I forgot to mention that I'm using the node websocket api and I'm not sending it via http

**Comment by jtliao** [comment]
The microphone example is mainly deprecated, I'd go through the HTTP API if possible

**Comment by marcelgoya** [comment]
ok, thanks.
