### ISSUE TITLE
Feature Request: GET samples randomize return

### ISSUE THREAD

**Issue by jackneil** [wit-ai/wit#1198]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
feature

**What is the current behavior?**
GET samples returns the same samples every time

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Please offer the ability to randomize the samples returned via the GET /samples api call so that we don't get the same set on every call (or make randomization the default action). Currently I'm having to return a large number of samples and then randomly select from them on my end ... which is inefficient for your bandwidth and my processing :)

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by jtliao** [comment]
hey @jackneil , can you let us know more about your use case that requires random samples?

**Comment by jtliao** [comment]
This is low priority on our roadmap, as it would require a non-trivial change to how we fetch samples from our database. If more people show interest in the feature, we can reconsider!

**Comment by jackneil** [comment]
Thanks for the response. I agree lowpri is fine. I was able to accomplish it via a different mechanism.
