### ISSUE TITLE
Major outage - 500 errors

### ISSUE THREAD

**Issue by blandinw** [wit-ai/wit#1200]
All API endpoints return 500 errors at the moment

**Comment by kumangxxx** [comment]
same here

**Comment by CardosoGit** [comment]
Same here

**Comment by blandinw** [comment]
We are working on a fix, unfortunately, this will take a couple hours to be fixed...

**Comment by sprasad09** [comment]
any update?

**Comment by l5t** [comment]
https://wit.ai/status

**Comment by blandinw** [comment]
Update: fix is propagating worldwide and should be out in less than an hour, it is hard to estimate exactly. Will close this issue once done.

**Comment by paixlukee** [comment]
Thank god. My bot has been freaking out lol.

**Comment by monika1800** [comment]
@l5t @blandinw 

Any update? How much more time will it take?

**Comment by paixlukee** [comment]
It started working, and then it just went down again

**Comment by blandinw** [comment]
The fix is now widely spread. We will review the incident internally to make sure this does not happen again in the future. Thank you all for your patience.

**Comment by blandinw** [comment]
@alexandruf I'll bring your feature request for a API status/healthiness endpoint to the team!
Can you comment a little more as to how you'd use such an API? Would a circuit breaker pattern work better (i.e. if the API returns too many 500s, just back off for a bit)?
