### ISSUE TITLE
Wit.ai down?

### ISSUE THREAD

**Issue by josephlingzb** [wit-ai/wit#1201]
Hi,

Is wit.ai down? All requests sent to https://api.wit.ai/entities is getting the following response:

{
    "error": "Something went wrong. We've been notified.",
    "code": "wit"
}

**Comment by kumangxxx** [comment]
same here

**Comment by sebamenabar** [comment]
+1

**Comment by CardosoGit** [comment]
same

**Comment by l5t** [comment]
#1200
