### ISSUE TITLE
Add official Go SDK to wit GitHub org

### ISSUE THREAD

**Issue by plutov** [wit-ai/wit#1202]
Currently there are a lot of wit Go clients, but they're all outdated and not supported:
https://github.com/kurrik/witgo
https://github.com/jsgoecke/go-wit
https://github.com/meinside/wit.ai-go
https://github.com/eternnoir/go-wit-ai

To have it fixed I started to make my own Wit.ai Go Client with unit tests, integration tests and all endpoints.

https://github.com/plutov/wit.ai

Can I have a review from Wit devs and add it to Wit GitHub org?

**Comment by blandinw** [comment]
Hi @plutov, thank you for your contribution!
I looked at the code and it looks pretty solid + good docs and tests, nicely done :)

However, making a client official means committing to maintaining it, answering support tickets, etc.
This creates more work for the Wit engineering team and distracts us from improving Wit through bug fixes, performance improvements and new features.
As a result, we currently do not want to add more official clients to our list, in order to focus on work that only us can perform on the Wit internals.

Thanks again!

**Comment by plutov** [comment]
Hi @blandinw I am raising my hand to help you with client maintenance and support for Go.

**Comment by blandinw** [comment]
Thanks @plutov, I'll discuss with the team and Facebook open source team to see if we can reach a middle ground where the repo is part of the wit-ai org, but we clearly communicate that it is community-maintained. Will update this issue with progress

**Comment by blandinw** [comment]
@plutov ok we worked it out :)
If you can transfer the repo to @caabernathy, we'll then transfer it to the [wit-ai](https://github.com/wit-ai) org and make you a contributor with repo write access

**Comment by plutov** [comment]
Hi @blandinw, I am not sure if I can transfer erpo in GH to another user without they permission. Also why not to transfer to wit-ai directly?

**Comment by caabernathy** [comment]
@plutov see this [GitHub help page](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/), the wit-ai org doesn't allow members to create repos so you can't transfer it there. I'm one of the org owners, so I can transfer it into that org once you transfer the repo to me. When you initiate the transfer, I'll receive an email notification and complete the transfer into my personal account. Next, I'll transfer it to the org.

A little convoluted I know, but that's how we do it based on the security we've put around our orgs.

**Comment by plutov** [comment]
Thank you @caabernathy, I just sent a transfer request:
```Repository transfer to caabernathy requested```

In repository code there are some imports which includes my username `plutov`, it need to be changed to the org name we will have later. I will help you with that after transfer.

**Comment by caabernathy** [comment]
@plutov I didn't check my mail over the weekend and the transfer request expired (it only lasts a day). Could you resend? Thanks!

**Comment by plutov** [comment]
Got it, I resent the transfer request.

**Comment by blandinw** [comment]
@plutov the repo now lives at https://github.com/wit-ai/wit-go.

This process is new for us, and there's apparently one final step: sign our standard FB CLA at https://code.facebook.com/cla. Apologies for not making this clear from the beginning.
Once that's done, I'll add you as a contributor and we're all set :)

**Comment by plutov** [comment]
Hi @blandinw I just signed the FB CLA.

**Comment by blandinw** [comment]
You should now have push access to the repo. I'll add a disclaimer to the repo like for `wit-ios` explaining that it is maintained by the community.

Thanks for building a clean Go client 🤩

**Comment by plutov** [comment]
Thanks, I will make some changes in the new repo to make it work with new path.
