### ISSUE TITLE
Something went wrong when export data.

### ISSUE THREAD

**Issue by palingsusah** [wit-ai/wit#1204]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
i would like to ask about export data from wit.ai, i know your team currently working for this problem, but do you have estimated time for this?

**What is the current behavior?**
whenever i tried to export data :

{
  "error" : "Something went wrong. We've been notified.",
  "code" : "wit"
}

**What is the App ID where you are experiencing this issue (if applicable)?**
58327310-69b2-4e44-850c-6e9a969b4dad

**Comment by jtliao** [comment]
Hi @palingsusah , the issue for your app should be fixed now, I was able to export successfully.
