### ISSUE TITLE
UTC not properly formatted

### ISSUE THREAD

**Issue by OmarJabri7** [wit-ai/wit#1205]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Issue a behavior about UTC timezone in settings
**What is the current behavior?**
When i send a date to wit, say 10 pm, where in the settings, time is set to UTC, I still get 10 pm in the wit response. It should send me &pm UTC where 10pm is 7 + 3 UTC
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
It may not seem as a bug, it can be a suggestion
**What is the expected behavior?**
The expected behavior is to recieve a time in utc hence, 7pm instead of 10pm , because in my country, UTC+3, i should recieve 10 - 3 = 7 pm.
**What is the App ID where you are experiencing this issue (if applicable)?**
5b48a903-ba7d-4c9f-a314-ac1db0268bee

**Comment by blandinw** [comment]
Wit does not know in what country you are, this is why there is a timezone option in the Settings. Given your app settings, Wit thinks you are in the UTC timezone (not UTC +3, how would it know that?). You can set a timezone per request too using the `context` parameter, when you know the timezone of the user, cf. https://wit.ai/docs/http/20170307#context_link

Closing this, but feel free to comment back if something does not make sense.
