### ISSUE TITLE
Difference between wit/agenda_entry and wit/reminder

### ISSUE THREAD

**Issue by timaschew** [wit-ai/wit#1206]
First of all, thank you for this awesome project! It's amazing! 🙏🤘
 
**Question about wit?**

Somehow I don't get the difference between `wit/agenda_entry` and `wit/reminder`.
The description in the docs is quite minimal, you could you please elaborate on that?

Also another question which I just realized. Do I need to assign to each sample an intent?
I'm not talking about negative samples or about no intents, it's more that a sentence with a `agenda_entry`has the intent of an agenda for some cases?

**What is the current behavior?**

I would like to use wit to create events to my google calendar for instance.
That's one sample to do it:

> meet Anna at 3 o clock for dinner

Here is the result (almost untrained app, only `event` intent was created and `Anna` as a contact)
<img width="929" alt="screen shot 2018-08-24 at 13 58 06" src="https://user-images.githubusercontent.com/110870/44583505-ea786000-a7a5-11e8-94fa-4e3d0fc7dfa9.png">

What is also a bit confusing to me that `agendy_entity` was recognized twice for `meet` and `dinner`.
Is that okay or should I create a role for `dinner` so it would be `wit/agenda_entry:type`?

Would be nice if we can bring this type of sample to the official docs, what do you think?

BTW: How can I access (readonly of course) some public apps on wait.ai console or HTTP API without that someone shared it with me?
Actually I would expect to see some public apps on `https://wit.ai/home` already but somehow I'm getting redirected to my user page `https://wit.ai/timaschew`

**What is the App ID where you are experiencing this issue (if applicable)?**
1813071692123203

**Comment by l5t** [comment]
Thanks for the kind words. You're right to say that wit/agenda_entry and wit/reminder are pretty similar: the first one is more for your type of example ("Meet Anna"), the later for examples like "reminder me to do something tomorrow". That being said, these built-in entities have been trained across thousands of Wit apps and the Wit community may have trained them with different use cases in mind, this is probably why Wit capture both Meet and Dinner as agenda_entry. Role may help so I would try but probably the easiest would be to create your own custom entities to detect event_type and event_object (for Meet for example)

We don't have yet a repo where you can browse public apps. While we have been thinking about it for a while, we haven't had yet the time to implement it.

**Comment by blandinw** [comment]
Will close that if there's no further discussion, we may merge these two entities at some point, since they are so similar and we have enough data to learn both kind of sentence pattern/construction

**Comment by timaschew** [comment]
Thanks!

Just a last questions related to this:

> but probably the easiest would be to create your own custom entities to detect event_type and event_object (for Meet for example)

Why it would make (more) sense in this case and in general to use own entities over the existing ones if the seems to be similar?

**Comment by l5t** [comment]
because with your own custom entity, you better control the behavior since you and only you validate the examples to train your entity (as opposed to a built-in entity that has been trained across thousands of wit apps)
