### ISSUE TITLE
Not recognizing notable_person when sent message through FB messenger

### ISSUE THREAD

**Issue by jaisrael1** [wit-ai/wit#1209]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug

**What is the current behavior?**
When I type in the name of a notable person e.g. 'Mark Zuckerberg' Wit recognizes fine it in the console. If I send it to a FB page linked to the same Wit app, it does not appear in 'message.npl.entities' that facebook sends to my webhook. In the logs for the app however, it correctly identifies that same message as the notable_person entity with high confidence.

**What is the expected behavior?**
The notable_person entity should appear in 'message.nlp.entities' that is sent to my webhook if it is also recognized in the wit logs.

**Comment by patapizza** [comment]
Hi @jaisrael1,

Thanks for reporting. What is your app id?

**Comment by jaisrael1** [comment]
5a39605f-b5e7-4492-82e7-7fd3bcf2514f

**Comment by patapizza** [comment]
Thanks for your patience, fix upcoming.

**Comment by patapizza** [comment]
This should now be fixed.
