### ISSUE TITLE
Post samples returns with "bad-json" code 

### ISSUE THREAD

**Issue by globiqGlobema** [wit-ai/wit#1210]
I would like to report a bug or ask about clarification

Current behavior: 

I have small application to train my Wit.Ai app with some samples - so far I used to received proper responses for my requests. Today when I tried to trained my application I get an error from the server: 

curl -XPOST "https://api.wit.ai/samples?v=20180830" -H "Authorization:Bearer XXXXXXX" -H "Content-Type: application/json" -d "[{'text':'akceptuj','entities':[{'entity':'intent','value':'status'},{'entity':'Statusy_Geotask','value':'akceptuj','start':0,'end':8}]}]"

{
  "error" : "Unable to parse json",
  "code" : "bad-json"
}

Could I please get some clarification If it is my simple mistake which somehow I cannot see or there is some problem with  post /samples end point. 

My App ID: 2073614389349886

**Comment by patapizza** [comment]
Hi @globiqGlobema,

Can you try to use double quotes inside the JSON and single quotes outside (or escaped double quotes)?

**Comment by globiqGlobema** [comment]
Tried it at the very beginning - it did not help

**Comment by patapizza** [comment]
@globiqGlobema Just tried that and it worked:

```
$ curl -XPOST "https://api.wit.ai/samples?v=20180830" -H "Authorization:Bearer xx" -H "Content-Type: application/json" -d '[{"text":"akceptuj","entities":[{"entity":"intent","value":"status"},{"entity":"Statusy_Geotask","value":"akceptuj","start":0,"end":8}]}]'
{
  "sent" : true,
  "n" : 1
}
```

Single-quotes didn't work:

```
 $ curl -XPOST "https://api.wit.ai/samples?v=20180830" -H "Authorization:Bearer xx" -H "Content-Type: application/json" -d "[{'text':'akceptuj','entities':[{'entity':'intent','value':'status'},{'entity':'Statusy_Geotask','value':'akceptuj','start':0,'end':8}]}]"
{
  "error" : "Unable to parse json",
  "code" : "bad-json"
}
```

**Comment by globiqGlobema** [comment]
On Windows system it has to be set double quotes and rest in json \" instead of ". Thank you for your kind help.

**Comment by patapizza** [comment]
Happy to help!
