### ISSUE TITLE
GET Samples: Allow getting samples that were validated in the UI

### ISSUE THREAD

**Issue by ouamer-dahmani** [wit-ai/wit#1211]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
*feature*

**What is the current behavior?**
At the moment a GET on the samples API seems to return all the samples in order of training starting at *offset* up to *limit* results.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
I would like to be able to get a list of recent samples that were manually validated on the dashboard. This will allow me to replicate these samples to an offline training set I have that can be used to retrain a bot from scratch.

I guess that being able to search within a time window and based on a metadata flag that indicates whether the samples were manually approved would be sufficient.

For the time window it is still necessary to determine whether using the time at which the sample came in or the time at which it was validated (updated) would be more useful. An update time would allow us to keep data on our end that would allow us to perform incremental updates by forming a query such as "Get me all the manually validated samples since today 12:00AMUTC".

Time format can be simple epoch ms timestamps.

Alternatively if samples are returned with their ID (offset) we could use that instead.

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by patapizza** [comment]
Hi @ouamer-dahmani,

It seems like using the `limit` and the `offset`, you should be able to query for new samples: once you get the whole dataset, you can use the dataset size as the new offset to get new samples. Regarding manually approved samples, `GET /samples` only returns validated samples.

Let me know if that works.

**Comment by ouamer-dahmani** [comment]
Hi @patapizza ,

Thanks for the answer. Let us say that I retrain the AI with the same dataset regularly from scratch but in a possibly different order, would they retain the same offset they already have or would these change?

Thanks!

**Comment by patapizza** [comment]
If by 'from scratch' you mean that you re-train all the samples for the same app, then yes the ordering will remain unchanged.
On the other hand if you mean to start a new app from scratch, then the ordering will be different.

**Comment by ouamer-dahmani** [comment]
Perfect! That answers my question.
Thanks!
