### ISSUE TITLE
Question: Do repeated samples bias learning or are they ignored?

### ISSUE THREAD

**Issue by ouamer-dahmani** [wit-ai/wit#1212]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
*question*
Let us say that we train the application through the API by feeding it data from a dataset.

We then find some new sentences we wish to train the application with. If we resend training calls with the entirety of the dataset we will be sending repeated samples for everything except for the new sentences. Will these repeated sentences bias the engine in any way?

If repeated sentences are ignored then it is simpler for us as we can always edit our existing datasets and resend everything. Otherwise we have to make sure we send only the new data which makes automation more complicated.

Can you provide me with some insight?

**What is the current behavior?**
----
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
-----
**What is the expected behavior?**
----
**What is the App ID where you are experiencing this issue (if applicable)?**
-----

**Comment by patapizza** [comment]
Hi @ouamer-dahmani,

For a Wit app, we consider that there is only one single correct semantic for a given sentence. So if you revalidate previously validated samples, you will effectively update the semantic, as opposed to adding a new sample to the dataset.
