### ISSUE TITLE
Searching bugs

### ISSUE THREAD

**Issue by robinsinghkhalsa** [wit-ai/wit#1214]
**Search is not performed properly**

1.	As I find this link https://wit.ai/docs not helpful because the relevant description is missing and  as I found problem in searching that I have two entities in my APP and having same keywords and values but when I perform search then it returns only single entity.

2.	And one more problem which I found in the searching is when I save the entities with lookup “free-text & keywords”  then the search operation is working but with other lookups values its stops searching.

**Comment by patapizza** [comment]
Hi @robinsinghkhalsa,

Please use the provided template - what is your app id?

What do you mean by "Search"?
Regarding (2), what entities and what lookup values are you referring to?

Thank you.

**Comment by robinsinghkhalsa** [comment]
Hi @patapizza ,

my App id is 1675000069288667

1. With term search I mean that querying with the keyword
for example I created the entities on the name of three movies and three entities has the keyword inspirational but when I make a search with get message https://wit.ai/docs/http/20170307#get__message_link with keyword inspirational then it returns only one entity.

2. With second point I mean when I saved any entity keywords with lookup free-text&keywords and when I searching is working well but not with the another lookups.You can take above example.
try to make search with keyword "inspirational".

**Comment by patapizza** [comment]
Hi @robinsinghkhalsa,

I don't see any validated samples in your app, and `movie_list` doesn't have any strategies set. For more information on what lookup strategy to use, look into https://wit.ai/docs/recipes#which-entity-should-i-use. This could help understanding why a certain entity works properly with `free-text & keywords`, but not with other strategies.

Hope this helps.

**Comment by aforaleka** [comment]
Hey @robinsinghkhalsa, we don't currently support returning multiple entities from the same keyword. Looking at your app, you might want to store "inspirational" as a separate entity, and add your own logic on top of Wit to return certain movies if the entity "inspirational" exists in the message.

You can also take a look at https://github.com/wit-ai/wit/issues/1130 for more details.
