### ISSUE TITLE
Dual (auto-detecting) language support for speech recognition

### ISSUE THREAD

**Issue by stefan-reich** [wit-ai/wit#1215]
I get voice samples from Telegram users. Is it possible to run this through the speech recognition in a way that tells me whether German or English was probably spoken?

Right now wit.ai doesn't return confidence values AFAICS, so I can't compare on the basis of those.

I realize trying to auto-detect the language may lower recognition quality, but it's kind of annoying for users to specify which language they will speak in first.

Thanks for a great product.

**Comment by patapizza** [comment]
Thanks for the thought! To set expectations, we don't have the bandwidth to currently tackle this, but I'll definitely add this to the features list to discuss internally.

**Comment by stefan-reich** [comment]
Actually, my tests indicate that the German setting automatically detects English too! Even with complex input (saying "Does this work with any sentence?" comes out just fine in the German module).

**Comment by jtliao** [comment]
Closing, as this won't be something we'll be able to reasonably support.

**Comment by stefan-reich** [comment]
Too bad, but I understand it requires additional resources. Thanks
