### ISSUE TITLE
Wit not recognizing explicitly trained sample

### ISSUE THREAD

**Issue by jaisrael1** [wit-ai/wit#1216]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

Bug

**What is the current behavior?**

The app recognizes 'I love you kygo!' with high confidence, but doesn't recognize 'I love you kygo' with > 50% confidence. Both samples have been explicitly trained with the same value.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Check the above text samples. 

**What is the expected behavior?**

That both samples are recognized to have s-intent value 'love' with high confidence

**What is the App ID where you are experiencing this issue (if applicable)?**

5a42b41d-f23a-41c2-a63f-dc481e6a103a

**Comment by aforaleka** [comment]
Hi @jaisrael1, thanks for reporting your issue. I took a look at your app samples and it seems like the sentence "I love you kygo" (without the '!') has been validated without the s-intent "love". If you revalidate the sentence with the s-intent, the app should work properly. Let me know if that fixes it! :)

**Comment by jaisrael1** [comment]
That fixed it! Thanks!
