### ISSUE TITLE
Wit.Ai is not able to detect intents for many

### ISSUE THREAD

**Issue by nitikeshd** [wit-ai/wit#1217]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by aforaleka** [comment]
Hi @nitikeshd -- can you provide us with more information about the issue you're experiencing?

**Comment by aforaleka** [comment]
closing the issue -- feel free to reopen to provide us more info!
