### ISSUE TITLE
Speech recognition wrong language

### ISSUE THREAD

**Issue by Andy1210** [wit-ai/wit#1218]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
I have an app which configured to Hungarian language in the settings.
I am using /speech_ws endpoint through websocket with this one: https://github.com/wit-ai/microphone
Wit.ai tries to recognize my speech as english instead of hungarian. It was working earlier.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. have an app configured to different language than english
2. use https://github.com/wit-ai/microphone from web browser and inspect the network/ws frames

**What is the expected behavior?**
Speech should be recognized as the configured app language.

**What is the App ID where you are experiencing this issue (if applicable)?**
5a6dbc53-da51-4ed8-aec4-7bb5e153b9fc

**Comment by aforaleka** [comment]
Hi @Andy1210, thanks for reporting! 

Our microphone example is mainly deprecated, and your bug is probably caused by the /speech_ws endpoint having an English locale. While we plan to get that working again in the near future, I suggest sending the speech audio via the HTTP API. Let us know if that works :)

**Comment by Andy1210** [comment]
Thank you for your answer. I thought that the endpoint will be the problem so I wrote a mic.js using the Recorder.js and I'm sending the audio as wav. It's working perfectly. Thank you :)
