### ISSUE TITLE
Not allowed to create new wit apps

### ISSUE THREAD

**Issue by danielfto** [wit-ai/wit#1219]
Since a few days ago we are trying to create a new app under our user name, but Wit shows us a message:  
Something went wrong. We've been notified.  
  
Is there any problem going on?  
  
It is a private app and I am importing a previus backup file.  
  
Thank you.

**Comment by aforaleka** [comment]
Hey @danielfto, thanks for reporting! Can you give us your login username so we can take a look? And does this error happen only when importing that backup zip file, or creating new apps from scratch in general?

**Comment by danielfto** [comment]
Hi, @aforaleka !
My username is "daniel.fto"
I am able to create new apps not using backup file. I just did it for testing and it was ok.
[BotnicksGenesis.zip](https://github.com/wit-ai/wit/files/2384821/BotnicksGenesis.zip)
This is the backup file I am trying to upload while creating the new app.
Thank you for you support!

**Comment by aforaleka** [comment]
Thanks for the info @danielfto! We'll look into it early next week. Did you happen to have manually modified the zip by any chance?

**Comment by danielfto** [comment]
@aforaleka I just exported the same project again, and then imported this new file in a new project and it worked!
Surely these old file I sent you has some conflict. I haven't modified these file. I always use it for my new apps, as a primary database, but this time I had problems.
The new file that worked is:
[BotnicksGenesis_new.zip](https://github.com/wit-ai/wit/files/2385227/BotnicksGenesis_new.zip)
Just in case you need to investigate it.
Thank you for you support, it was essencial to make this new app work =)

**Comment by aforaleka** [comment]
Glad that worked! Thanks for providing us the info, we will be improving our import / export soon. :)
