### ISSUE TITLE
How to train samples in bulk?

### ISSUE THREAD

**Issue by 91ns** [wit-ai/wit#1220]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question
**What is the current behavior?**
What's the correct way to send training samples in bulk? I tried to send a large number of samples in one API call "97183" samples, and the app showed "training" status a few times but then nothing happened. 

I understand the number might be too large, but can you fill me in on how I can train such quantities of data?

**What is the App ID where you are experiencing this issue (if applicable)?**
2098656580186676

**Comment by jtliao** [comment]
Hey @91ns , apologies for the delay on this-- the reason nothing happened is the large amount of samples sent unfortunately caused our systems to go down for a while. 

We set a rate limit of 200 samples per minute, so it will work if you split the large call into smaller pieces. If you have a specific use case that requires exceeding the limit, I'd recommend reaching out directly (help@wit.ai) so we can discuss the details. Thanks for your patience!
