### ISSUE TITLE
POST /samples bug

### ISSUE THREAD

**Issue by Emb1ter** [wit-ai/wit#1221]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
report bug
**What is the current behavior?**
The  POST /samples endpoint responds with 
{
  "sent" : true,
  "n" : 1
}
but, the samples are not added in the app
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Create a new app
POST /entities - create entity
POST /samples - add samples and automatically switch to trait type
**What is the expected behavior?**
The samples are visible in UI and actually added
**What is the App ID where you are experiencing this issue (if applicable)?**
1809423705773757

**Comment by gagan-bansal** [comment]
Yes me too facing same issue, last week it was working fine.
I am able to post entities but not samples though the API `/samples` responded with `{"sent" : true, "n": 1}` as @Emb1ter said.  
My app id: 1108458275945365

**Comment by aforaleka** [comment]
POST /samples should be working now, sorry for the inconvenience!

**Comment by gagan-bansal** [comment]
Great! Its working now.
Thanks
