### ISSUE TITLE
Very slow response after app inactivity

### ISSUE THREAD

**Issue by asfyra** [wit-ai/wit#1224]
I would like to ask if it's normal to have a 15sec long delay every time our application stays inactive for approximately 15 to 20 minutes.

If we just leave the application inactive for sometime, the first message after that takes around 15 secs for the reply

We would expect the application to respond as fast as it does when the user makes frequent requests

Our app id is: 5b1e505b-0e5f-484a-9e44-20d7c4ee12d1

Thanks in advance for any help on this. It is important for us to solve this issue as the client gets timeouts and our users see an error everytime this happens

Alex

**Comment by jtliao** [comment]
Hey @asfyra , I tried a couple GET /message requests to your app and can't seem to repro this, the first request seemed about the same in time as the later ones (and definitely <<15 sec). 

Are you sure that it's the Wit piece in your application that is causing the delay, and not something else?

If so, I'd like to know more about this-- does this happen _every_ time your app has been inactive, or only sometimes?

Thanks for your patience.

**Comment by asfyra** [comment]
Thank you for your patience @jtliao !
Our servers are having some hard time with external communication.

Thanks a lot for your time
Alex

**Comment by asfyra** [comment]
Well i decided to reopen this issue as i found a pattern to reproduce it.
After aprox 1 hour of inactivity the first GET /message takes around 15seconds to respond and it never returns a result. It returns the "default_intent".
The second try with the same data returns the correct entity.
I tried to send "Hello". The  response of the first call after an hour of inactivity returned "default_intent", the next try returned the correct result with 0.9915.... confidence !!!

1st Call
`[{
		"entities" :
		[
		]
		"confidence" :
		null
		"_text" :
		"Hello"
		"intent" :
		"default_intent"
		"intent_id" :
		"default_intent_id"
	}
]
`

2nd Call
`[{
		"entities" : {
			"intent_general" :
			[{
					"confidence" :
					0.99157275897229
					"value" : {
						"value" :
						"GREETING"
					}
					"entity" :
					"intent_general"
				}
			]
		}
		"confidence" :
		null
		"_text" :
		"Hello"
		"intent" :
		"default_intent"
		"intent_id" :
		"default_intent_id"
	}
]`

If there is access to the logs please refer for exaple to the "hello" message calls at around 2018-10-04T14:44 UTC

Thank you
Alex

**Comment by asfyra** [comment]
Hi @jtliao, i was wondering if you have any (good) news on this issue?

Thanks in advance
Alex

**Comment by jtliao** [comment]
Hey @asfyra , I still haven't been able to find a way to reproduce this, so having a hard time debugging. I imagine it is related to a cache issue. I'll keep looking into the root cause, but temporarily, pinging the app with "hello" would likely ensure you get the correct response consistently.

**Comment by asfyra** [comment]
@jtliao i 've made a copy of my project with appid 2424468930899829, which has no traffic at all, so you that you can reproduce the issue whenever you want.
Your suggestion on pinging is what i will end up doing until the issue is resolved. The only downside with this, is that i will "pollute" the logs with hellos. Is there any way to exclude specific calls from logging ?

Thanks again for your effort @jtliao, I hope that a solution to the problem will be found soon.

Alex

**Comment by jtliao** [comment]
hey @asfyra, did some digging, and as you correctly mentioned earlier, this is a cache issue. The "intent_faq" entity has 3400 values for a trait entity, which leads to a very long time to warm up the cache. I'd recommend splitting this into different entities if possible, or continuing to do the "ping" method to keep the cache warm.

**Comment by asfyra** [comment]
Thank you @jtliao we will follow your instructions. I didn't know multiple intents is better. 

Thank you
