### ISSUE TITLE
Receiving only single keyword

### ISSUE THREAD

**Issue by SI-santosh192** [wit-ai/wit#1225]
Hi @jtliao ,

Please help with the below scenario,

I am using multiple Synonyms across multiple keywords.

eg.
Keyword 1 - Deepak Kumar Dahiya
Synonyms - Deepak, Deepak Dahia, Deepak Dahiya, Deepak Kumar, Deepak Kumar Dahia, Deepak Kumar Dahiya, Dipak Kumar, Dipak Kumar Dahia, Dipak Kumar Dahiya

Keyword 2 - Deepak
Synonyms - Deepak, Dipak

o/p -
{
"_text": "dipak",
"entities": {
"players": [
{
"metadata": "220",
"confidence": 1,
"value": "Deepak",
"type": "value"
}
]
},
"msg_id": "1v01Cyzsp62DweMu7"
}

Problem - Only one keyword is detected. However, the expectation to receive both the keywords as o/p.

Please help as it is slightly urgent.

AppId:2018290648222034

**Comment by jtliao** [comment]
In your query you have "dipak", which is only a synonym for keyword 2. Keep in mind keyword entities will only extract exact text matches, so only keyword 2 is returned here.

**Comment by SI-santosh192** [comment]
Hi @jtliao ,

Sorry for it was my fault.

I have added dipak in both the keywords mentioned above. Still not getting both the entities.

Please help

**Comment by blandinw** [comment]
It is very unclear what result you're expecting. Please make it very clear:
1) what is the expected result
2) what is the actual result

As of today, we do not support two values sharing the same synonym. Only one value will be returned arbitrarily.
