### ISSUE TITLE
unable to parse (receive) the basic available entities like wit/quantity or wit/distance inspite by training and validating many examples..........

### ISSUE THREAD

**Issue by girrajmal** [wit-ai/wit#1226]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by girrajmal** [comment]
My APP ID :- 
5b4a9e75-5e0f-4f40-afca-de6046bde418

i have defined many custom entities and intents and the wit.ai responds perfectly most of the time with json containing the entities and intent, even i received the entity for wit$datetime , but could never get any value for wit$distance or wit$quantity though i trained the app with many many samples, please help me, i need these two entities too...

**Comment by blandinw** [comment]
`wit/quantity` matches things like "1 pound of sugar".
`wit/distance` matches things like "1 km".

These 2 entities are implemented using Duckling, so providing more examples won't directly help and should not be necessary.

They are working correctly from my testing. Can you give an example of a sentence you would like Wit to understand?

**Comment by patapizza** [comment]
I'm able to get `wit/distance` and `wit/amount_of_money`:

<img width="986" alt="screen shot 2018-12-17 at 1 17 32 pm" src="https://user-images.githubusercontent.com/1015208/50116155-3db36a00-01fe-11e9-88d0-ba5c1ee63122.png">

Feel free to reopen with specific examples that don't work.
