### ISSUE TITLE
Incorrect Data from Get Request

### ISSUE THREAD

**Issue by Mikesteinberg** [wit-ai/wit#1227]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

question about get Request

**What is the current behavior?**
When I use OnlineCurl to make a request, The data is correctly returned. However, using postman, the entities are returned as {}, and the the text is returned as follows: "'"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Enter a get request into Postman to get a message.

**What is the expected behavior?**
Data correctly returned

**What is the App ID where you are experiencing this issue (if applicable)?**
1813383875382399

**Comment by blandinw** [comment]
It sounds like you're getting the correct results using OnlineCurl (whatever this is), but not with Postman. This sounds more like a Postman issue than a Wit issue.

I'll close this issue, please comment back with the sentence you're trying to match if you still need help.
