### ISSUE TITLE
How To Call My Bot From Google App Script

### ISSUE THREAD

**Issue by eyalgi11** [wit-ai/wit#1228]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Ask A Question
**What is the current behavior?**
I Can't Undestand How To Call And Send Text To My Bot And Get Answer On Google Script
**What is the expected behavior?**
Code To Write In Google Script That Work WIth Wit.ai
**What is the App ID where you are experiencing this issue (if applicable)?**
App ID: 1763784243733845
In The Google Script Editor

How I Explain Well
Please Answer

**Comment by blandinw** [comment]
Please contact whoever works on Googe App Script. Any HTTP client should be able to use Wit. Closing.

**Comment by eyalgi11** [comment]
I'm working on the google app script, and i not professional so i don't know how to set that (what practically to write)
and the docs don't help me
i know it's possible with http request but don't know how

**Comment by blandinw** [comment]
As explained in #1230, we cannot help you with Google Script. Wit provides a standard HTTP API, we cannot help you with the specifics of your HTTP client.
