### ISSUE TITLE
Support analytics for logs

### ISSUE THREAD

**Issue by benjaminroe** [wit-ai/wit#1229]
We need a way to see analytics on our intents/entities, how many times something has been answered, what confidence thresholds they've been answered with etc. This could be done through the logs tab. If this isn't possible, we at least need a way to download logs so that we could produce these analytics ourselves.

**Comment by stopachka** [comment]
Hey @benjaminroe -- I'll involve this in the roadmap discussions. 

In the meantime, a solution could be to start logging on your end -- either after wit responds, or after you use wit's response to do something. This way, you can have analytics not only on wit data, but any enhanced data as well (the response messages ent, etc)

If you need to backfill previous data, we could send you a zip of all your previous logs. Email me at stopachka [-a-t] fb.com with your app-id, and I'd be happy to send that to you

**Comment by flogaribal** [comment]
Hey @stopachka 
I am currently in the exact same situation as @benjaminroe, I would like to retrieve all my logs to see analytics our intents/entities.
Thereby I would like to know if you can send them to me by email. I already sent you a mail :) 
Thanks a lot in advance it would be very helpful!

**Comment by flogaribal** [comment]
Hey @stopachka, do you have any update on this ? 
I am really sorry to insist but we are facing some weird things about our chatbot understanding that is why we would like to know where it come from and do some statistics on our logs.

**Comment by patapizza** [comment]
Hi @benjaminroe @flogaribal, sorry for the latency. Providing a way to download the logs would be the way to go. Let's keep track of this here: https://github.com/wit-ai/wit/issues/431
