### ISSUE TITLE
How To Use Http request In Google Script To Call My Bot

### ISSUE THREAD

**Issue by eyalgi11** [wit-ai/wit#1230]
_Originally posted by @eyalgi11 in https://github.com/wit-ai/wit/issues/1228#issuecomment-426224733_

Hi I'm Opened An Issue. unfortunately It's Closed when I Still needed help

i'm Using google app script to make http request to wit.ai for communicate with my bot
but because i not a professional in javascript (The language 'app script' based on)
 i need help to know what to write

in The Original Issue i told that any http client will work
but i still don't know how to create it in my script

thanks very much to helpers
:)

**Comment by blandinw** [comment]
Wit uses a standard protocol (HTTP, see our docs at https://wit.ai/docs/http/20170307) so any client implementing this protocol should work. We do not know Google Script, the best way for you to get an answer is to ask on a Google Script support group.
