### ISSUE TITLE
How do I handle multilingual expressions

### ISSUE THREAD

**Issue by biancatarun** [wit-ai/wit#1231]
For example the phrases are "I want to find a school" and "Gusto ko pong maghanap ng school". I want my chatbot to respond in english if the expression entered was in english and respond in filipino if the expression entered was in filipino. How do I do that?

**Comment by l5t** [comment]
Unfortunately we don't support this yet. This may help though https://github.com/wit-ai/wit/issues/850

**Comment by jtliao** [comment]
Closing for now, feel free to comment in the linked thread above to unify our multilingual discussion
