### ISSUE TITLE
"cheers" is being recognised as a greeting instead of a thanks

### ISSUE THREAD

**Issue by benjaminroe** [wit-ai/wit#1232]
This is a bug where variations of the word "cheers" result in being recognised as a greeting instead of a thanks. For example, "cheers" has a confidence of 0.908 for wit/greetings and a confidence of 0.712 for wit/thanks.

**Comment by stopachka** [comment]
Thanks for the feedback @benjaminroe! We'll look into this.

**Comment by jtliao** [comment]
Merging with #1615 for tracking
