### ISSUE TITLE
App is stuck in SCHEDULED mode

### ISSUE THREAD

**Issue by mminchev** [wit-ai/wit#1235]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
I am reporting a bug.

**What is the current behavior?**
My app is stuck in SCHEDULED mode for almost 1 day.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
The ID of my app is 2147293685303684. I have noticed that this issue occurs for all of my apps in Bulgarian and it does not occur for apps in English.

**What is the expected behavior?**
The training should be scheduled and then it should be performed within some reasonable time frame. 

**What is the App ID where you are experiencing this issue (if applicable)?**
The app ID is 2147293685303684.

**Comment by patapizza** [comment]
Seems like your app is trained properly:

<img width="282" alt="screen shot 2018-10-09 at 6 36 27 pm" src="https://user-images.githubusercontent.com/1015208/46708200-51d15e80-cbf2-11e8-8a3d-b7c497fee26e.png">
