### ISSUE TITLE
Something went wrong. We've been notified. - for facebook messenger built-in nlp

### ISSUE THREAD

**Issue by danqing** [wit-ai/wit#1236]
We are seeing the following for our chatbot using built-in NLP. The bot can be found at m.me/getahug.

```py
[{'time': 1538812421460, 'id': '999790083446832', 'messaging': [{'sender': {'id': '***'}, 'recipient': {'id': '999790083446832'}, 'message': {'mid': '6j3qp-lzCoQSOtmbjB3SPdDOPE4vZ1isWUVS9-ECNhWAhvTgPVG70KlyWUMUOK6CoaDKUE-YtpbVTTvnQbkPaw', 'nlp': {'errors': [{'code': 'unknown', 'message': "Something went wrong. We've been notified"}]}, 'seq': 1251186, 'text': 'October 1, 2018'}, 'timestamp': 1538812420980}]}]
```

**Comment by jtliao** [comment]
Hi @danqing , are you still experiencing this issue? I think it's related to #1239, which should be resolved now.

**Comment by akrishi** [comment]
@jtliao I am still experiencing this issue
On printing out the incoming message, ,I get the following in the payload for "nlp" :
'nlp': {'errors': [{'code': 'unknown', 'message': "Something went wrong. We've been notified"}]}}}] .

**Comment by jtliao** [comment]
hey @akrishi , can you give it another try now? it might have taken a few minutes for the fixes to propagate to everyone. If it is still broken now, please post the relevant app id/reproduction details

**Comment by danqing** [comment]
Seems to be working for us. Thanks!
