### ISSUE TITLE
Intent entity not generating a detection of an utterance it is trained on

### ISSUE THREAD

**Issue by falmusha** [wit-ai/wit#1240]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
Intent entity not generating a detection of a sample it is trained on if the sample is a long sentence

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I can't without exposing private training data. 

**What is the expected behavior?**
The entity generated detection on exact samples that it is already trained on

**What is the App ID where you are experiencing this issue (if applicable)?**
2029938310397968

I don't know if it related but I'm using entities with many trait values (14+ values). Is that a problem?

**Comment by patapizza** [comment]
Hi @falmusha, I didn't find an `intent` entity, but tried a few examples from the other trait entities and it seemed to work properly. Feel free to shoot us an email through the `Help` link on the top right with specific training samples that don't work.
