### ISSUE TITLE
Wit greetings not working

### ISSUE THREAD

**Issue by S-Dutta1** [wit-ai/wit#1241]
The app does not recognize greetings(Hi, hello), bye, and contact (Paul, the dentist etc). 
eg. 
curl  -H 'Authorization: Bearer $TOKEN'  'https://api.wit.ai/message?v=20181011&q=Hi' 
App id: 5b5ff0ce-4bf0-4926-8440-8b29e9b6b462

Are we doing something wrong ?

**Comment by jtliao** [comment]
Hi @S-Dutta1, you need to add the builtin entity wit/greetings to your app before the entity will be detected. 

Also, avoid sharing your app token publicly, and in these cases share your app id instead :)

**Comment by patapizza** [comment]
@S-Dutta1 As @jtliao, make sure to add the entity, and you probably want to reset your server token. Feel free to reopen if you still experience the issue after adding the entity to your app.

**Comment by bewithdhanu** [comment]
Hi
while I am trying greeting words it is showing like this
![image](https://user-images.githubusercontent.com/19368533/68178482-3336c600-ffb2-11e9-8436-41f119dc64b3.png)
even I select wit/greetings it not showing true/false option as I have seen in demos like this
![image](https://user-images.githubusercontent.com/19368533/68178548-6da06300-ffb2-11e9-8f0b-b54dd9d797a0.png)
How can I use greetings and bye
