### ISSUE TITLE
Two DateTime Detected Instead Of One

### ISSUE THREAD

**Issue by eyalgi11** [wit-ai/wit#1243]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question
**What is the current behavior?**
I am want to create "task" Intent
and when i say for example "on friday i am get up in the morning at 9 o'clock"
it will recognize that "get up" is action for task intent and "friday on the morning at 9 o'clock" is time date
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
the problem when i typed "on friday i am get up in the morning at 9 o'clock"
it's recognize friday and 9 o'clock as two datetime (see photo 1)
![1](https://user-images.githubusercontent.com/2491520/46953133-9c8d2380-d095-11e8-87a5-cc025936e28f.PNG)
i've tried to do first example for the system with friday and the time not seperete and it's worked (see picture 2)
![2](https://user-images.githubusercontent.com/2491520/46953210-e5dd7300-d095-11e8-8b99-2aa9195425bd.PNG)
but when the bot was trained it's not helped to the first one to get recognize
i tried to edit the hour on the first image but there is no button to do that
my real project is on hebrew but i succeed to reproduce the problem on the photos above
thanks
**What is the App ID where you are experiencing this issue (if applicable)?**
1836882386347473

**Comment by lamkent00** [comment]
face to same issuse :|
@eyalgi11 : do you have temp solution to pass this problem?

**Comment by eyalgi11** [comment]
> face to same issuse :|
> @eyalgi11 : do you have temp solution to pass this problem?

If You Asked Me If I Found A Solution. No sorry

**Comment by eyalgi11** [comment]
> face to same issuse :|
> @eyalgi11 : do you have temp solution to pass this problem?

I'm Sorry I Forgotten I Do Came With A Solution
I Created An Entitie And Mark WIth HIm The Necessary Field
Just Don't Use The Build-in Entitie
Text Me IF I Helped :)
