### ISSUE TITLE
[bug]Can't download bot's data

### ISSUE THREAD

**Issue by melaniab** [wit-ai/wit#1245]
In the last few month I've been working on a chatbot using Wit.ai As I make weekly changes in the entities or the training, I would like to keep track of my work and weekly download the current state of the bot in case there is some mistake made. Unfortunately, for few weeks I haven't been able to download a .zip of it's data. When I click the button "Download .zip with your data" I keep receiving the same error message over and over again:
```
error "Something went wrong. We've been notified."
 code "wit"
```
I asked the other developer working on the same bot but he receives the same error as well.
Can you take a look into why this error occurs? Here is the bot I'm talking about: https://wit.ai/bbhsciant/resbot_de/

Thank you in advance,
Melania

**Comment by jtliao** [comment]
hi @melaniab, this should be resolved now (I was able to successfully download a .zip), thanks for your patience. Feel free to re-open if you are still experiencing the issue.
