### ISSUE TITLE
Where I can find some "sample/base/basic data" for "app"

### ISSUE THREAD

**Issue by anhhtz** [wit-ai/wit#1247]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Ask question

**What is the current behavior?**
Where I can find some `sample/base/basic data` for `app` on `wit.ai` ? Ex: `greeting`, `weather`, `location` data. Somewhere like as `public` or `open` data for importing to `app`.

The task that build (train) basic data for app wasted a lot of develoepr 's time.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by jtliao** [comment]
Unfortunately, exporting from open apps is not supported yet, issue #1176 is open for that. 

However, we do have many pre-trained builtin entities that handle standard use cases like wit/location, wit/greetings, and many more.
