### ISSUE TITLE
Application training stuck (again) in ONGOING

### ISSUE THREAD

**Issue by asfyra** [wit-ai/wit#1248]
Hello,
our application is stuck in ONGOING traninig for the last few hours. 
The usual training time it takes, is about 10 minutes. If i hover over the ongoing message the label that pops up shows that the last training took around 8mins.

Our AppId is: 5b1e505b-0e5f-484a-9e44-20d7c4ee12d1

Could you please have a look at this.

Thank you
Alex

**Comment by aforaleka** [comment]
Hi @asfyra, the problem should be fixed now. Let me know if that works! :)

**Comment by asfyra** [comment]
Yes thank you very very much @aforaleka 
It's working fine :)

**Comment by asfyra** [comment]
I will have to reopen the issue, as our application stuck again in Ongoing state.
Could you please do your magic, or is it some kind of a bug that would need to be resolved ?

Thanks in advance
Alex

**Comment by asfyra** [comment]
I don't know if some one did something, but since this morning the app returned back to normal training cycles.

I have to close the issue

**Comment by asfyra** [comment]
I am afraid i will have to reopen this issue because our application is stuck again.
AppId: 5b1e505b-0e5f-484a-9e44-20d7c4ee12d1

Please be so kind to fix it one more time.
I am glad that [this issue](https://github.com/wit-ai/wit/issues/1402) reports that a permanent solution is on the way.

Thanks in advance
Alex

**Comment by aforaleka** [comment]
Hi @asfyra, I've restarted your app's training and it is scheduled to train tonight.

**Comment by asfyra** [comment]
Thank you very much @aforaleka

**Comment by asfyra** [comment]
@aforaleka although you reset the application, it stack again during training and it never finished.
Is there something you can do to help? We really need the application to complete training.

Thanks in advance
Alex

**Comment by sophiexr** [comment]
Hi,

Any news on that issue?? Our app hasn't trainned since 09/04....

thanks

**Comment by aforaleka** [comment]
HI @sophiexr and @asfyra, your app is pretty big and we are working on a solution for handling large apps like yours (similar to https://github.com/wit-ai/wit/issues/1338#issuecomment-461556181). We suggest downsizing your app for now.

**Comment by asfyra** [comment]
Our app (5b1e505b-0e5f-484a-9e44-20d7c4ee12d1) is stuck again since 4th of June. Could you please restart the app for us.
Is there any progress on this issue?

Thank you.

**Comment by patapizza** [comment]
@asfyra As @aforaleka mentioned, we're actively working on improving our infra for large apps like yours. This is in our radar. Thank you for your patience.
