### ISSUE TITLE
Increase text character limit to 512 across the board please

### ISSUE THREAD

**Issue by HarshEvilGeek** [wit-ai/wit#1250]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Request a feature

**What is the current behavior?**
Limit to input text length is 256 characters

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
I'm using sentence segmentation (and in some cases comma segmentation), but 256 characters seems really short nowadays. The applications of wit extend far beyond ordinary conversation comprehension to applications that frequently have long sentences (analysis of key phrases in legal documents for example). Increasing 256-512 would make a huge difference to me (and a few other organizations I can think of).

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by aforaleka** [comment]
Hi @HarshEvilGeek! Thank you for supporting Wit, I'll discuss with the team and let you know.

**Comment by aforaleka** [comment]
Hey @HarshEvilGeek -- brought this up with the team and we decided that Wit's use case should still be focused on shorter conversations. Therefore for your use case, sentence segmentation will be the way to go.
