### ISSUE TITLE
Wit.ai not matching phrases when a symbol is added to the phrase.

### ISSUE THREAD

**Issue by RobertsG** [wit-ai/wit#1251]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question
**What is the current behavior?**
I have trained the phrase "Hi", but when I enter "hi," or "hi." or "hi?" they do not match, I attempt to train the "hi," for example and that works now, but I still have the issue with other symbols as "hi?" and so on. What can I do to improve the matching without having to train all the possible symbols attached to my sentence?
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
I would expect the application, to recognise "hi?", "hi,", "hi." when the phrase "hi" is trained.
**What is the App ID where you are experiencing this issue (if applicable)?**
1849054828509044

**Comment by blandinw** [comment]
@RobertsG sorry for the late reply and thanks for your feedback.
I could not guess the entity/value pair you expect.
Can you provide the following information?
- example query
- expected entity name and value name, as they appear in your app (they seem to be some kind of IDs)

**Comment by RobertsG** [comment]
@blandinw Hi there, no worries:

Example query that works as expected: "hi" -> https://api.wit.ai/message?q=hi
Example queries that do now work: "hi," -> https://api.wit.ai/message?q=hi%2C
"hi?" -> https://api.wit.ai/message?q=hi%3F
"hi!" -> https://api.wit.ai/message?q=hi!
"hi." -> https://api.wit.ai/message?q=hi.

Expected response would be:

`"entities": {
            "small_talk": [
               {
                  "confidence": {SOME_CONFIDENCE},
                  "value": "5bd0796b0a528c590426114e",
                  "_entity": "small-talk"
               }
            ]
         }`

**Comment by stopachka** [comment]
Hey @RobertsG -- This is mainly because the word "hi" is two characters. We usually run fuzzy matches (i.e "hello" and "helo" are considered the same). For two characters it gets more complex, because there's many ways to misunderstand it -- i.e "hit" is similar to "hi!". 

I'll bring this up with the team, to see if we can update our logic to handle these cases

**Comment by RobertsG** [comment]
Thanks for the answer, that's what I suspected, just seemed weird that it would work in such a way for those type of characters, kind of imagined that it would handle letters and characters like ,.!'" differently.
