### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by stefan-reich** [wit-ai/wit#1253]
Hi!

I'm not clear on licensing of wit.ai speech recognition (which is a very good service).

In fact I am considering switching from Google to wit.ai.

The question is how this would be licensed.

I distribute an open source OS ("Stefan's OS") [here](https://www.botcompany.de:8443/1013826/raw). Can I ship the two wit.ai tokens (for English + German) with this product?

**Comment by blandinw** [comment]
@stefan-reich you are free to use Wit in any of your projects, commercial or otherwise.
Be sure to generate and use _**client tokens**_, that have more restricted permissions, since users o your projects will technically have access to them.

Good luck with your project 😊

**Comment by stefan-reich** [comment]
Thanks for the info and the good wishes! :)

So I can send one client token to mulitple people? Will they run into usage limits quicker that way?

**Comment by blandinw** [comment]
We have a soft rate limit per app, so you're right that they would share this limit.
To work around this, you would need to create several apps, but then you'd have to keep them in sync, which can get awkward fast.
I would advise you start with one token for multiple people and later, we can figure out something when your app becomes so successful that you hit our limits (lift the limit for your app, etc.).
