### ISSUE TITLE
Feature request: language detection

### ISSUE THREAD

**Issue by mcspenzer** [wit-ai/wit#1254]
Hi, I would like to request a new feature to further improve Wit AI.

Currently, I am working on my capstone project that involves using NLU, and I am using Wit as my platform for processing sentences.

The current platform lacks a built-in entity for detecting the language of the sentence. But I tried training the bot to detect the language of a given sentence as a temporary workaround, but It would be nice to have the mentioned entity as a new feature in Wit.

Thank you so much, and I look forward to making Wit grow!

**Comment by blandinw** [comment]
@mcspenzer thank you for your feedback, this is a feature we have been considering for a while, as it would also allow us to enable multilingual apps. I'll keep this open as the canonical feature request, but it is low priority for us at the moment.

**Comment by mcspenzer** [comment]
> @mcspenzer thank you for your feedback, this is a feature we have been considering for a while, as it would also allow us to enable multilingual apps. I'll keep this open as the canonical feature request, but it is low priority for us at the moment.

I understand. Still, always looking forward to making this feature happen. Thanks!

**Comment by patapizza** [comment]
@mcspenzer We've now implemented [language identification](https://medium.com/wit-ai/introducing-language-identification-38d714f86ffc). :)

**Comment by dessant** [comment]
Hi @patapizza! Are there any plans for implementing language detection for audio? I'm aware only of Google Cloud to offer such feature: https://cloud.google.com/speech-to-text/docs/multiple-languages

**Comment by patapizza** [comment]
Hi @dessant, no plans yet, https://github.com/wit-ai/wit/issues/1215 for tracking.
