### ISSUE TITLE
Feature request: better UI to manage keyword value synonyms

### ISSUE THREAD

**Issue by mcspenzer** [wit-ai/wit#1255]
Hi, I would like to suggest a possible feature for Wit AI

In the current version of Wit, adding synonyms for keywords are a bit hassle since you need to manually input the synonyms one by one. And when you do, The table sort of breaks the layout and arrangement of keywords for a bit that results in a poor user experience. I also find this issue problematic because when I click the screen while the layout break happens, I am accidentally removing synonyms for other keywords. I suggest changing the process of adding synonyms, UI wise.

I would also like to suggest adding multiple synonyms in one go to make the process more bearable.

Thank for considering!

**Comment by blandinw** [comment]
Thank you for your feedback, I will keep this open as a feature request and bring that to the team to prioritize.
For batch editing, I recommend using the HTTP API: https://wit.ai/docs/http.

**Comment by mcspenzer** [comment]
> Thank you for your feedback, I will keep this open as a feature request and bring that to the team to prioritize.
> For batch editing, I recommend using the HTTP API: https://wit.ai/docs/http.

Thanks you so much!
