### ISSUE TITLE
Arabic Support

### ISSUE THREAD

**Issue by Nada-Abdelkader** [wit-ai/wit#1262]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Ask a question

**What is the current behavior?**
There is no built in entities for Arabic language. Is the Arabic language support stable or not?
Also If i need multiple languages, do i have to create an application for every language?

**What is the expected behavior?**
As an example when i write "درجة الحرارة", wit doesn't consider it under wit/temperature entity and so on.

**Comment by patapizza** [comment]
Hi @Nada-Abdelkader,

There are many built-in entities for Arabic. Which ones are you looking for?
Yes you'd need a specific app for each language in the current state of things.

`wit/temperature` is powered by [Duckling](https://github.com/facebook/duckling). Feel free to improve it by submitting a pull request!

**Comment by 91ns** [comment]
There are many built-in entities with Arabic support like @patapizza mentioned. 

The temperature entity is not meant for keywords like درجة الحرارة . It is used to identify the part of a phrase that refers to a temperature.

Try this example:

![image](https://user-images.githubusercontent.com/25252530/48276590-0b6d5a80-e451-11e8-87f0-d860ac381f4f.png)

**Comment by patapizza** [comment]
@Nada-Abdelkader Closing this now, feel free to re-open should you have more questions.
Thanks for chiming in @91ns!
