### ISSUE TITLE
[question] Recognising word/number combination without adding values manually

### ISSUE THREAD

**Issue by Coayer** [wit-ai/wit#1265]
I have a question regarding how I can recognise a combination of letters and numbers (an aircraft callsign).

Currently, when I enter a new callsign (eg. "Charlie 31", "Echo 64" etc...) it only recognises it as a callsign if I have already added it as a value of the 'callsign' entity.

I would like the app to recognise callsigns of the format  WORD  DIGIT DIGIT  ( eg. "Mike 29", "Zulu 12") without me entering each combination of word and number from 00-99. I'm using free-text & keywords as the lookup strategy as I thought it suited my situation.

Thank you :)

**Comment by stopachka** [comment]
Hey @Coayer -- if the data is clean enough, could a regex take care of this? If so, it may be better to 
"enhance" your wit results, with a custom regex

**Comment by Coayer** [comment]
Yeah, I switched to regex as it makes way more sense for my usage. I appreciate your response though, thank you! :+1:
