### ISSUE TITLE
App displays "scheduled" at all times, logs are empty

### ISSUE THREAD

**Issue by meganthorsen** [wit-ai/wit#1267]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
1. The app has said "scheduled" for hours now, even though I have sent several more requests since that time and they have all been executed within minutes.  I am not sure if a request got lost in the process and still awaits scheduling, but new ones are not blocked.

2. Additionally and relatedly, when I view "logs" it says there have been no API requests, so I have no hint about which requests may or may not have run.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Just open the app page and view the status. It says "Scheduled".

2. Just open the logs page.

**What is the expected behavior?**
1. The status should progress through "ongoing" to "done" when the requests are run and completed.

2. We have run several dozens of API requests.  The "logs" should at least indicate that we have made API requests, if not provide information about their success, failure, or other status.

**What is the App ID where you are experiencing this issue (if applicable)?**
2145710502127902

**Comment by stopachka** [comment]
Hey @meganthorsen 
In wit, when you see the "scheduled" state, that refers to your model training
- What this means is, any time you validate some sentence, we schedule a job to "train" your app, so it can handle that sentence

When you send requests, this state does not affect them -- those requests will always run. 

It is curious that requests don't show up in logs though -- could you give an example of a request you are running?

**Comment by mthorsen** [comment]
I was mostly concerned that it was stuck on "scheduled" for my entire workday when it always previously resolved in <10 minutes on similar datasets.

Every time we train we delete the old model, so it's GET, DELETE, and POST on the samples endpoint, running one request every 30 seconds on SAMPLE_LIMIT=100 samples at a time to comply with the rate limit.  With our current test dataset there are between 400 and 500 samples, so 5 requests of each type every time we train.  Here are the Python excerpts if you need them.  Let me know if you would prefer an edited version of the actual requests.

```
    old_samples = http.request(
        'GET',
        'https://api.wit.ai/samples?limit=%s' % SAMPLE_LIMIT,
        headers={'Authorization': 'Bearer %s' % WIT_TOKEN})

    r = http.request(
        'DELETE',
        'https://api.wit.ai/samples?v=20170307',
        body=old_samples.data,
        headers={'Authorization': 'Bearer %s' % WIT_TOKEN,
                 'Content-Type': 'application/json'})

    r = http.request(
        'POST',
        'https://api.wit.ai/samples?v=20170307',
        body=working_data.encode("utf-8"),
        headers={'Authorization': 'Bearer %s' % WIT_TOKEN,
                 'Content-Type': 'application/json'})
```

**Comment by stopachka** [comment]
Gotcha, I see that it may have been intermittent based on #1268  -- let us know if not and will look deeper

**Comment by mthorsen** [comment]
Actually, I've never seen any logs there.  It's been empty every time I looked.

**Comment by patapizza** [comment]
Hi @mthorsen, to clarify, the Logs only show the requests to `GET /message` or `POST /speech`.

**Comment by mthorsen** [comment]
Ah.  Thanks for the clarification.
