### ISSUE TITLE
App guesses deleted intent

### ISSUE THREAD

**Issue by meganthorsen** [wit-ai/wit#1268]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question

**What is the current behavior?**
I recently deleted all the training data, removed an intent from the app and the training set, and then retrained the model.  During validation it asks if I want to create a new intent with the deleted intent's name, with a confidence level very similar to what it provided before it was deleted.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Enter "Hvordan er ordningen for Statoil-ansatte i år, har vi rabatt på billetter?" and it will suggest creating intent "quirky_request" with confidence .996.

**What is the expected behavior?**
I had hoped that deleting all training data as well as the intent "quirky_request" would eliminate the memory of that intent from the model and retrain on the new data.  What else do I need to do to reset the model?  It's crucial to start over from scratch, as we were just exploring an unlikely-to-work design by adding that intent in the first place.

**What is the App ID where you are experiencing this issue (if applicable)?**
2145710502127902

**Comment by stopachka** [comment]
Hey @meganthorsen -- 

Was the dot at the top left showing something like "scheduled" or "training"? The reason this happened, is perhaps because the app was still "training" on the changes. It can lag behind a bit.

This could lead to an interesting update the UI -- perhaps we could be more comprehensive about what data your current model is using.

**Comment by mthorsen** [comment]
Yes, it was stuck on "scheduled" for at least my entire workday.  Very helpful to know, thanks!

**Comment by patapizza** [comment]
@meganthorsen @mthorsen Do you still experience the issue?

**Comment by mthorsen** [comment]
No, it was just hung up for many hours, but seems to have resolved itself.  We're back to the normal <10 minute model builds now.
