### ISSUE TITLE
Bug report: Accents messes up keywords and synonyms

### ISSUE THREAD

**Issue by ouamer-dahmani** [wit-ai/wit#1269]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
BUG

**What is the current behavior?**
Adding a sample text that has accents messes up the reported synonyms by cutting off as many characters from the end as there are accents. This is compounded by subsequent accents.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

In wit.ai create the following entities:
- product_brand: keyword+free text
- product_category: keyword+free text
- product_color: keyword+free text

Run the following curl:
curl -X POST  https://api.wit.ai/samples  -H 'Content-Type: application/json'  -H 'cache-control: no-cache'   -d '[{ \"text\": \"hello je cherche un bibliothèèèques de marque G Digio colore rouge\", \"entities\": [ { \"entity\": \"product_category\", \"value\": \"bibliothèques\", \"start\": 20, \"end\": 35 }, { \"entity\": \"product_brand\", \"value\": \"G Digio\", \"start\": 46, \"end\": 53 }, { \"entity\": \"product_color\", \"value\": \"rouge\", \"start\": 61, \"end\": 66 }, { \"entity\": \"intent\", \"value\": \"product_search\" } ] }]'

In Wit, go look at the product_category and see the following:
![image](https://user-images.githubusercontent.com/5343121/48351306-db43d880-e657-11e8-986e-5f17a7dc7c49.png)

**What is the expected behavior?**
I would expect that the synonym would be the complete word bibliothèèèques

**What is the App ID where you are experiencing this issue (if applicable)?**
1801648746627495

**Comment by stopachka** [comment]
Hey @ouamer-dahmani  -- thanks for the report -- we will look into this and update here.

**Comment by jtliao** [comment]
hi @ouamer-dahmani, this should be resolved now, let me know if you are still experiencing issues here

**Comment by ouamer-dahmani** [comment]
Hi!
I did a test training pass with a few thousand samples and it looks like it is fixed.

Thanks!
