### ISSUE TITLE
New intents are not registering properly

### ISSUE THREAD

**Issue by SL0TR** [wit-ai/wit#1270]
I have created a new intent called 'portfolio' and gave some examples string and validated. But even after the training update being green, the strings doesn't return the appropriate intents which it was registered with. One time it did work and next time it didn't. Now, next scheduled training update is after 5 hours.

Thanks in advance.
App ID: 5b4b497b-a223-49c9-8b86-926ce143c8bc

**Comment by patapizza** [comment]
Hi @SL0TR, it seems like `portfolio` has now a single sample. It's now working properly:

<img width="977" alt="screen shot 2018-11-14 at 9 28 46 am" src="https://user-images.githubusercontent.com/1015208/48500502-dca80900-e7ef-11e8-9860-c7f36b9353d1.png">

Feel free to reopen if you get the issue again.
