### ISSUE TITLE
Unable to validate expressions in app Inbox

### ISSUE THREAD

**Issue by asfyra** [wit-ai/wit#1271]
Hello,
We have an issue with the inbox functionality.
When we try to validate an expression from the list, the entry disappears for a while, as it should and after a sec is coming back again.

We noticed that the problem occurs only on expressions with multiple entities.

The expected behavior would have been to remove the validated expression from the list.

The appid is: 5b1e505b-0e5f-484a-9e44-20d7c4ee12d1

Thanks 
Alex

**Comment by asfyra** [comment]
Right now i tried and it looks ok. 
When we had the problem i looked at the browser developer tools and i saw that the response wan an error mentioning that you will be informed for the error.
I believe it's fixed now, so i' ll close the this issue and i will inform you if we have the same behavior again.
Thanks a lot for your effort
Alex

**Comment by patapizza** [comment]
Thank you for reporting!
