### ISSUE TITLE
 WIT.AI  for translate language/speech

### ISSUE THREAD

**Issue by santtlorenzo** [wit-ai/wit#1274]
Hello :
I would like to know if it is possible to use WIT.AI to translate a text string or a WAV file
For example "Hello world" English-Spanish and that the response of the API is "Hola Mundo" Is it possible?
You have some link or documentation
Best regards

**Comment by jtliao** [comment]
hey @santtlorenzo, unfortunately, we do not support language translation.

**Comment by santtlorenzo** [comment]
Ok Many Thanks :)
