### ISSUE TITLE
'Exercise' interpreted as 'exercised'

### ISSUE THREAD

**Issue by GauravDobhal** [wit-ai/wit#1275]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**

When I am training my bot on the sentence 'Yes I do exercise' and its other variations, wit  interprets the value of 'exercise' as 'exercised', adding a 'd' in the end. It was working properly earlier but seems to be a issue since the past few weeks. I have tried training it a lot, but it does not seem to correct the mistake.

**Comment by patapizza** [comment]
Hi @GauravDobhal, what is your app id?

**Comment by GauravDobhal** [comment]
5a3370ee-861c-4cd8-b0e1-134f3acb25a0

**Comment by patapizza** [comment]
It seems that some validated samples have the value `exercised` for the text `exercise` - can you fix your dataset to see if that helps?

<img width="685" alt="screen shot 2018-11-17 at 1 49 18 am" src="https://user-images.githubusercontent.com/1015208/48659786-21f45280-ea0b-11e8-9630-ef7200231a46.png">


Feel free to re-open if you still experience the issue after that.

**Comment by patapizza** [comment]
For that specific case, you could hack it by checking the body of the `verb` entity (using `verbose=true` in the API request).

**Comment by patapizza** [comment]
Hi @GauravDobhal, this is now fixed.
However you've added a new value, `exericse` with `exercise` as synonym, which needs to be fixed on your end.

**Comment by GauravDobhal** [comment]
Hello Julien,

So this started working fine but now has again started giving exercise as
exercised.

Gaurav

**Comment by patapizza** [comment]
Let me look into it.

**Comment by GauravDobhal** [comment]
Any luck with this? I am facing another challenge, on entering *"**Chittoo
doesnt like milk", *it gives 'likes' instead of 'like' even though I have
checked my dataset and made corrections.

**Comment by patapizza** [comment]
Hi @GauravDobhal, this is still in my list. Sorry for the latency.
