### ISSUE TITLE
Cannot export data and put request is not working as expected.

### ISSUE THREAD

**Issue by davidtw23** [wit-ai/wit#1276]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug
**What is the current behavior?**
1. Always pop up "Something went wrong while exporting your app 😣. Please try again, or contact us."
when clicking "export .zip with your data" in settings.

2. I have made a list of dictionary which consist of ~6000 keyword values, used put request to update keywords entity, however I have downloaded the json data afterwards(export data function still worked at that time) , it is observed that only ~2300 keywords values have been updated.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
1. It is able to download the whole zip file.

2. Should be 6300 keywords value in the entity instead of only ~2300

**minimal demo**
2.  I have done something like:

```
import requests
headers = {
	'Authorization': 'Bearer {}'.format(test_token),
	'Content-Type':'application/json',
}
query = {"values":[]}
# len(name_list) >6000 
for i in name_list:
	query['values'].append({"value" : i, "expressions" : [i]})
resp = requests.put(API_ENDPOINT,headers=headers, json=query)
data = resp.json()
print(data)

```
The response is:
{
error: "Something went wrong. We've been notified.",
code: "wit"
}
**What is the App ID where you are experiencing this issue (if applicable)?**
APP ID: 1967774586633462

**Comment by patapizza** [comment]
Thanks for reporting, we'll look into it.

What is the value of `API_ENDPOINT`?

**Comment by davidtw23** [comment]
`API_ENDPOINT = 'https://api.wit.ai/entities/instructors'`

**Comment by jtliao** [comment]
hi @davidtw23, unfortunately your app was in a bad state which broke things like export-- the entity "instructors" was corrupted and many values are missing, and unfortunately they have to be added back. 

As for the issue with PUT entities, can you try it again and let me know if it's still broken?

**Comment by davidtw23** [comment]
Hi
After removing the instructors entity and re-create a new one.
Exporting function work again. Thank you!
However, PUT entities is still not working as expected.
All the duplicated values have been screened out from the dictionary before I send put request
After I exported the json file,
I observed that some values has been placed repeated twice or even 3 times.

**Comment by jtliao** [comment]
I'll look into this-- can you give me an example of what you have in the PUT entities request? Maybe not the whole payload, but just a couple examples of the values

**Comment by davidtw23** [comment]
I sent one request with all the values.

**Comment by jtliao** [comment]
I looked into this and it shouldn't be possible other than duplicates in the request (which is now also fixed), can you try it again?

**Comment by davidtw23** [comment]
Yeah, no more duplicates, thanks a lot!
But there is another issue: some values is missing.
After I made put request, the following response is given
`{'code': 'wit', 'error': "Something went wrong. We've been notified."}
`

I wrote a few lines of code, and found out that:
number of values from wit.ai: 1286
number of values from my_data is 6005
I pretty sure that there is no empty string or duplicates values in my data set
what would be the possible causes lead to such situation??

**Comment by davidtw23** [comment]
Thank you very much!
But I think PUT request would overwrite the previous values in the entity, so dividing the data and send multiple PUT request with different portions may not work for me.

**Comment by jtliao** [comment]
Sorry you're right-- hoping to have a fix out on the next work day.

**Comment by jtliao** [comment]
Can you give it a shot now? Note that the values may not be updated immediately if you send a large amount.
