### ISSUE TITLE
Error on validating expression.

### ISSUE THREAD

**Issue by thipinho98** [wit-ai/wit#1278]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
report a bug

**What is the current behavior?**
im having a problem as i try to validate an expression, it takes a while on loading and later return a error. 
![image](https://user-images.githubusercontent.com/26885706/48797954-ad5f3380-ecea-11e8-8863-fbcfdfa50edb.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Try to validate a expression and wait

**What is the expected behavior?**
Just validate it.

**What is the App ID where you are experiencing this issue (if applicable)?**
1810511089074923

**Comment by aforaleka** [comment]
Hi @thipinho98! Thanks for reporting the issue. This is probably caused by the sporadic outages we're currently experiencing, you can follow https://github.com/wit-ai/wit/issues/1277 or https://wit.ai/status for updates. Sorry for the inconvenience!!

**Comment by jtliao** [comment]
this should be resolved now
