### ISSUE TITLE
I'm creating my first wit.ai app. I don't have the option to enble NLP on my main facebook page, as illustrated in the tutorial.

### ISSUE THREAD

**Issue by JoelStolarski** [wit-ai/wit#1281]
I'm creating my first wit.ai app. I don't have the option to enble NLP on my main facebook page, as illustrated in the tutorial.

**Comment by aforaleka** [comment]
hey @JoelStolarski, can you tell us which tutorial you're looking at? (or a screenshot will be helpful)

**Comment by aforaleka** [comment]
You can take a look at https://developers.facebook.com/docs/messenger-platform/built-in-nlp#customizing_nlp if you want to link your app to your facebook page

**Comment by JoelStolarski** [comment]
I might have to actually get the wit.ai bot done, and then approved. It's possible the settings won't show up until it's approved. I'll see if I can find the page with the instructions to enable nlp. I just looked for the page that showed how to enable nlp, but couldn't find it.

**Comment by aforaleka** [comment]
ah yes, the app review process might take some time. hope it'll work soon for you! closing the issue for now.

**Comment by JoelStolarski** [comment]
thank you aforaleka
