### ISSUE TITLE
Sometimes empty entities returned

### ISSUE THREAD

**Issue by shasha79** [wit-ai/wit#1284]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
In the last 3 days, sometimes Wit returns empty entities for the same text (difficult to reproduce, but happens only with intent "affirm" in my app)
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
This is wrong output:
{'msg_id': '1oRrH8WgWGTvzJF94', 'entities': {}, '_text': 'מעולה'}
**What is the expected behavior?**
{'entities': {'intent': [{'confidence': 0.97756673916601, '_entity': 'intent', 'value': 'affirm'}]}, '_text': 'מעולה', 'msg_id': '1wMNnhOFFZ09zINAS'}
**What is the App ID where you are experiencing this issue (if applicable)?**
58741228-a551-45b4-a33e-1a79c5fc04c3

**Comment by aforaleka** [comment]
hey @shasha79, thanks for reporting. We will look into this, sorry for the inconvenience!

**Comment by patapizza** [comment]
HI @shasha79, we've deployed a fix yesterday which should fix the issue. Feel free to reopen should it arises again.
