### ISSUE TITLE
App is stucking in ongoing status

### ISSUE THREAD

**Issue by tarakdesai1983** [wit-ai/wit#1286]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
App is getting stuck in ongoing status
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Whenever we create App or create intent via api it is getting sutck in to Ongoing status.
**What is the expected behavior?**
It should get trained and give expexted result.
**What is the App ID where you are experiencing this issue (if applicable)?**
1681257678647396

**Comment by aforaleka** [comment]
Hey @tarakdesai1983, thanks for reporting! We noticed that your app's training took longer than usual, it should be done now but we'll look into this.

**Comment by notiles** [comment]
Hello it's stuck again
<img width="355" alt="capture d ecran 2018-11-28 a 14 53 59" src="https://user-images.githubusercontent.com/2833559/49156390-92f60d00-f31d-11e8-9809-3dec096abb50.png">

**Comment by jtliao** [comment]
The training time will normalize over time, if you experience an issue in the meantime feel free to post your app ID here.

**Comment by yodamerlin** [comment]
We have had a similar problem with having the schedule set for 6 hours in to the future.
![image](https://user-images.githubusercontent.com/8143879/50058875-a8b95e00-0176-11e9-90e9-37470a748736.png)

The app id is: 2308047179206845

Thanks for an help you can provide.

**Comment by NicolasLF** [comment]
I have a same problem, My app is getting stuck in Scheduled Status...
App id : 2099206013468936

Thanks for your help 🙏

**Comment by patapizza** [comment]
Hi @NicolasLF, it seems like your app is trained.

**Comment by patapizza** [comment]
Hi @lisaMartini, 

It seems like your app is trained:
<img width="328" alt="screen shot 2019-01-28 at 9 43 04 am" src="https://user-images.githubusercontent.com/1015208/51855091-385b3c00-22e1-11e9-9769-6290024e8c07.png">

The main issue here was the training being stuck in "ongoing" status, which should be resolved by now.
If the app is "scheduled" but later in the day, that's a separate issue. Does it consistently get schedule at the end of the day?

**Comment by nitikeshd** [comment]
![image](https://user-images.githubusercontent.com/32154791/61724674-086e8c00-ad8c-11e9-93f0-94c8343ae724.png)
I have been getting this issue very often now. I am planning to use it for enterprise purpose. But wit looks like is not reliable interms of training of keyword. Could any one from the team can help me out in this issue asap?
