### ISSUE TITLE
Explicit train API

### ISSUE THREAD

**Issue by gagan-bansal** [wit-ai/wit#1287]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Feature/Question
**What is the current behavior?**
Does every post of the samples initiate training of model. 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Training can be in two parts:
1) Post all the samples with rate limit or all
2) Explicit `train` api that initiate the training and the response contains status `started`, `processing` or `scheduled`

This may decrease unnecessary starting of training, and hence will decrease the load server.  
For the client side availability would be known. So appropriate action can be taken at client side. 

**What is the App ID where you are experiencing this issue (if applicable)?**
2343914732347451

**Comment by jtliao** [comment]
This is an interesting idea, I think in most cases it would add more complexity for developers, but I'll bring it up with the team.

**Comment by gagan-bansal** [comment]
Yes who have already developed the client app it will be an extra work. Also where sample data set is very less there would be additional steps, but applications with large data set this is certainly a required feature.

**Comment by patapizza** [comment]
Hi @gagan-bansal,

This is an interesting idea that has been suggested in the past - tl;dr we'd like our system to be smart enough to remove this burden from the developer: https://github.com/wit-ai/wit/issues/1119.
