### ISSUE TITLE
wit/phone_number

### ISSUE THREAD

**Issue by jacques0191** [wit-ai/wit#1288]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
report a bug
**What is the current behavior?**
Throws away first brace in phone number but keep the second brace if only number is entered. Therefore breaks the number formatting.

Entity: wit/phone_number

**Invalid case:**
Wit response example:
`
{
  "_text": "(000)5040299",
  "entities": {
    "phone_number": [
      {
        "confidence": 0.96311,
        "value": "000)5040299"
      }
    ]
  },
  "msg_id": "1QH69UOjLc70MbTtY"
}
`
When text is mixed with phone number behavior is correct.
**Valid case:**
`
{
  "_text": "my number is (000)5040299",
  "entities": {
    "phone_number": [
      {
        "confidence": 1,
        "value": "(000)5040299"
      }
    ],
    "intent": [
      {
        "confidence": 0.81178077279575,
        "value": "has_mobile"
      }
    ]
  },
  "msg_id": "1oZwk7tM5geQ18nz1"
}
`
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**Test case:**
1. Using wit built-in entity wit/phone_number.
2. Enter any number in the format (xxx)xxxxxxx.

**Result:**
1. Wit returns "xxx)xxxxxxx".

**What is the expected behavior?**
1. Wit should return number as "(xxx)xxxxxxx" not "xxx)xxxxxxx".

**What is the App ID where you are experiencing this issue (if applicable)?**
5a0b418b-a1e6-47bc-b525-174ca13c50ea

**Comment by jtliao** [comment]
Hi @jacques0191, wit/phone_number is powered by Duckling, and this seems like a parsing issue. Can you open an issue here? https://github.com/facebook/duckling/issues
