### ISSUE TITLE
Training never start / App stuck in training

### ISSUE THREAD

**Issue by notiles** [wit-ai/wit#1289]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
training schedule to 11pm, wit don't train new intents
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Go to 'understanding'
fill the form with a new sentence
select intent, create a new intent
training will never start...
**What is the expected behavior?**
training have to start when I create or update a new intent
**What is the App ID where you are experiencing this issue (if applicable)?**
1596633837104787

<img width="331" alt="capture d ecran 2018-11-27 a 17 00 17" src="https://user-images.githubusercontent.com/2833559/49094195-fc1a4980-f265-11e8-87dd-8d4efdc6152a.png">

Could you unlock training on my app ?

**Comment by notiles** [comment]
Could you unlock training on my app ?

**Comment by jtliao** [comment]
I went ahead and retrained your app for now. We're looking into the root cause of the training delay, let's keep the conversaion in #1286.
