### ISSUE TITLE
Matching specific text

### ISSUE THREAD

**Issue by micheleselea** [wit-ai/wit#1290]
Hi all, I would know it's possible to teach wit.ai for matching text that has specific syntax but you don't know values, for example fiscal code or carplates so you have CRFTHG88R32X334E or AA000BB. Is there a way or you think I should do it at application level?

**Comment by Shubham132** [comment]
How do I start using a regular expression in Wit.ai, I couldn't find any options to do so.

**Comment by kingseaeast** [comment]
@Shubham132 There is no regex in Wit.ai. The easiest way is to implement it in your code using the whatever the regex library provided by the language of your choice
