### ISSUE TITLE
Stuck on SCHEDULED very often

### ISSUE THREAD

**Issue by sebastianarena** [wit-ai/wit#1291]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
BUG

**What is the current behavior?**
Training is stuck on SCHEDULED

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I have many apps. And often I spend days without training a new set on an app. Often, after I train something new, I'm left with 10+ hours waiting for the new set to be trained, instead of triggering something sooner.

**What is the expected behavior?**
I would expect that WIT trains my set faster when I update it

**What is the App ID where you are experiencing this issue (if applicable)?**
Right now I have one waiting for 6+ hours: 2196522063691368

**Comment by jtliao** [comment]
I went ahead and retrained your app for now. We're looking into the root cause of the training delay, let's keep the conversation in #1286.

**Comment by sebastianarena** [comment]
GENIUS! THANKS! Will keep the conversation in the other issue!
