### ISSUE TITLE
Something gone wrong error when Intent is created

### ISSUE THREAD

**Issue by sanskarbiswal** [wit-ai/wit#1292]
Each time I try to create a custom intent in wit, the web page gives the following error, "Something gone wrong 😔 Please refresh or create a Github issue here".
I am facing this issue only when I create a new custom intent. I am working in the Understanding section on chrome Interface.
Any solutions??

**Comment by jtliao** [comment]
Hi @sanskarbiswal, I can't seem to reproduce this one-- can you provide your app ID?

**Comment by sanskarbiswal** [comment]
@jtliao I have been working this the last hour and it appears that the issue is at random. Not exctly able to reproduce it everytime. It happens every once in a day or two. The fix I got as of now is I use a VPN and load the webpage from a different IP. That resolves the problem.
Here is the app Id : 1947655731978617
