### ISSUE TITLE
Datetime year issue

### ISSUE THREAD

**Issue by nomercy89** [wit-ai/wit#1293]
I can't understand why the wit/datetime component gives me back two different years with two different ranges of months.

Look here: [link1](https://ibb.co/VqVZY2v) - [link2](https://ibb.co/QKcJFRF)

Is it a bug?
Is there a way to return the current year if it is not specified? (As in link1)

Thanks

**Comment by jtliao** [comment]
Hi @nomercy89, wit/datetime is powered by Duckling, can you open an issue at the following link, the maintainers will be more fit to help: https://github.com/facebook/duckling/issues
