### ISSUE TITLE
when I receive data from wit my voice command bot slows down the voice channel connection speed

### ISSUE THREAD

**Issue by maxymoo22** [wit-ai/wit#1297]
Hi my problem is that my app, which is a discord bot that stays in a voice channel, listens to users speaking, and sends the audio data to wit.ai, makes the ping in the voice channel go way up to like 400ms when it gets the text back from wit. So I was wondering if that was my codes' fault or something at wit.ais end. I'm using the `request` module from npm to stream the audio to wit. I can post my code if needed. Thanks in advance.

**Comment by jtliao** [comment]
I'm not quite sure what you're asking, do you mean that it takes a long time to get the speech response? If so, has this only started recently? It may be related to #1296

**Comment by jtliao** [comment]
Latency issue should be resolved, feel free to re-open if still facing issues

**Comment by maxymoo22** [comment]
It still creates lots of ping when I stream sentences longer than 3 words to wit
