### ISSUE TITLE
Last week returning 2 weeks ago date

### ISSUE THREAD

**Issue by 91ns** [wit-ai/wit#1300]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
Last week returning the following value 

 "value": "2018-11-26T00:00:00.000+04:00",
        "grain": "week",
        "type": "value"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
 "value": "2018-12-03T00:00:00.000+04:00",
        "grain": "week",
        "type": "value"
**What is the App ID where you are experiencing this issue (if applicable)?**

1888793904536889

**Comment by patapizza** [comment]
Yesterday it was Sunday. Duckling assumes a week to be from Monday to Sunday. "Last" is the one before the current one, so in the case of yesterday, it was indeed starting on 11/26.

To prevent breaking existing users, this won't be resolved before [overriding assumptions](https://github.com/facebook/duckling/issues/29).
Somewhat related is the discussion around [next week](https://github.com/facebook/duckling/issues/44).
