### ISSUE TITLE
wit.ai doesn't recognize its own name

### ISSUE THREAD

**Issue by stefan-reich** [wit-ai/wit#1301]
OK this one is just a tiny funny thing... my attempts to say "wit A I" in wit.ai's speech recognition have been utterly futile so far... it hears "Whitney I" or "Which AR" or a myriad other things.

Just thought I'd tell you. Please don't take this too seriously :smiley: 

In other news, everything is working great. Thanks a lot, recognition (except for this funny mini-bug) is really awesome.

**Comment by jtliao** [comment]
great to hear!
