### ISSUE TITLE
Unable to restore from ZIP

### ISSUE THREAD

**Issue by erudyk** [wit-ai/wit#1302]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
Hitting create the App after some processing time says it's unable to load the zip file. Only one entity from ~10 is created.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Download the ZIP. Create new app and provide the ZIP as parameter.
**What is the expected behavior?**
App created successfully.
**What is the App ID where you are experiencing this issue (if applicable)?**
2195640480455891

**Comment by jtliao** [comment]
hi @erudyk, I can't seem to reproduce this, I tried to export/import it and it worked fine. Can you try it again?

**Comment by jtliao** [comment]
looking into it

**Comment by jtliao** [comment]
This should be working now, I was able to import your app successfully (with all 16 entities)

**Comment by erudyk** [comment]
Works like a charm. Thank you very much!
