### ISSUE TITLE
Speech recogrecognition API timeout

### ISSUE THREAD

**Issue by xFilosofx** [wit-ai/wit#1303]
Hello,
i have some issue with APeech API. It work correct on Novemder, not work on last week. When i send POST to HTTP 'https://api.wit.ai/speech it return timeout error.
In console:
```
[root@dc1pbx test]# python3 test.py
{'error': 'Timeout, please try again later', 'code': 'timeout'}
```
Test Code on python:
```
import requests
import json

def read_audio(WAVE_FILENAME):
    # function to read audio(wav) file
    with open(WAVE_FILENAME, 'rb') as f:
        audio = f.read()
    return audio

API_ENDPOINT = 'https://api.wit.ai/speech'
ACCESS_TOKEN = 'XXXXXXXXXXXXXXXXXXXXXXXXXX'

# get a sample of the audio that we recorded before.
audio = read_audio("speech.wav")

# defining headers for HTTP request
headers = {'authorization': 'Bearer ' + ACCESS_TOKEN,
           'Content-Type': 'audio/wav'}

#Send the request as post request and the audio as data
resp = requests.post(API_ENDPOINT, headers = headers,
                         data = audio)

#Get the text
data = json.loads(resp.content.decode('utf-8-sig'))
print(data)
```
Wav file -3,4MB. I trying change IP, workspace and servers, python version, tokens. But nothing help.
Anybody can help me?

**Comment by jtliao** [comment]
How long is the wave you're sending? Also, can you provide your app id?

**Comment by xFilosofx** [comment]
4 mins, APP ID 1972483139454141.

**Comment by jtliao** [comment]
There haven't been any changes on our end, but sending a 4 minute long audio could definitely cause timeouts. I'd recommend sending smaller pieces, and the speech recognition would not perform well on long waves anyways.

**Comment by Dmitry1972** [comment]
I had the same problem. Files from 29 seconds long up to 59 seconds.

**Comment by jtliao** [comment]
we'll look into this

**Comment by xFilosofx** [comment]
Do you have any information on our the problem? Maybe something wrong with Russian speech engine?

**Comment by xFilosofx** [comment]
I tried speech recognition with mp3 and curl. Tested with one 45s file and one 6 min file.
Console log:
```
HTTP/1.1 100 Continue
Server: proxygen
Date: Tue, 25 Dec 2018 09:09:49 GMT

HTTP/1.1 408 Request Timeout
Content-Type: application/json
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
X-Content-Type-Options: nosniff
Date: Tue, 25 Dec 2018 09:10:18 GMT
Server: proxygen
Connection: keep-alive
Content-Length: 71

{
  "error" : "Timeout, please try again later",
  "code" : "timeout"
```

**Comment by jtliao** [comment]
This means that the audio files that you sent are too long, and our system times out. We'll work on having some better error messaging since "Timeout, please try again later" isn't very clear, but in the meantime you'll have to split the audio into smaller files for recognition (speech recognition doesn't work very well for audio files that large anyways).

**Comment by Bio-Leisure** [comment]
I have the same problem, and I noticed that each audio file can't be longer than 20 seconds. Split the audio to several small files can fix it.
