### ISSUE TITLE
400 ERROR in post samples when text is too long

### ISSUE THREAD

**Issue by mmdaz** [wit-ai/wit#1304]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question
**What is the current behavior?**
I am trying to post sample with https://api.wit.ai/samples  but when my samples are too long I get 400.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
200 status code.
**What is the App ID where you are experiencing this issue (if applicable)?**
2063475790341251

**Comment by jtliao** [comment]
This is expected, we enforce a max length of 280 characters, as longer texts do not work well for Wit's use case.
