### ISSUE TITLE
Stuck on Scheduled

### ISSUE THREAD

**Issue by tarpitgrover** [wit-ai/wit#1305]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug.

**What is the current behavior?**
App is stuck on Scheduled for ages. 

**What is the expected behavior?**
Usually the app trains every so often. Its the first time its been stuck for hours and hours now.

**What is the App ID where you are experiencing this issue (if applicable)?**
1879082498812979
![screenshot 2018-12-13 at 10 53 57](https://user-images.githubusercontent.com/5577200/49934120-69181b00-fec5-11e8-8bf8-7f9935f050ca.png)

**Comment by jtliao** [comment]
Seems like it trained about 6 hours ago-- this shouldn't happen again in the future, feel free to re-open if so.
