### ISSUE TITLE
I  don't receive any entity when I use /message request . 

### ISSUE THREAD

**Issue by mmdaz** [wit-ai/wit#1307]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
ask a question
**What is the current behavior?**
{'_text': 'my sample sentence', 'entities': {}, 'msg_id': '12xot1PqdaI93eFpw'}
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
getting entities that related to my sentence that I am sending with message method of pywit library in python .
**What is the App ID where you are experiencing this issue (if applicable)?**
2063475790341251

**Comment by jtliao** [comment]
After looking at your app, I'm not sure what you're expecting back, as none of your samples seem to be in English, so sending a sample text in English would return no entities back. Additionally, you should definitely not have that many entities in your app, it leads to poor performance. It's recommended to have fewer entities with more values if possible.

**Comment by mmdaz** [comment]
Yes , my entities are persian and also I am not sending English sample and I am sending persian samples.
About amount of entities I can say that these data are just what I have and they are different one by one.

**Comment by jtliao** [comment]
Your example above is English though, so am a bit confused about what is expected. Regardless, having 1600 trait entities with one sample each will almost certainly lead to very poor performance.

**Comment by mmdaz** [comment]
Is it common that my entity has for example 2000 values ?
and also how do I get my intended question( that is a value now ) from one entitiy ?

**Comment by jtliao** [comment]
It's much more common for 1 entity to have 2000 values than 2000 entities. Still, the performance won't be great since you only have one sample per value and it's a trait entity. 

This is what the response looks like,` {"_text":"some text","entities":{"entity_name":[{"confidence":0.99712834173823,"value":"some_value"}]},"msg_id":"1duIcUldUZjPdLTL6"}`, you can get the value name from the "value" field in the entity "entity_name"

**Comment by mmdaz** [comment]
Yes , I khow but I have to hadle this with these data.
I think I undrestand what you say.
You say I have one entitiy for example question and add all my questions in the values of this entitiy then if I send a similar sample I receive a response like that one you sent.
Is it correct ?

**Comment by jtliao** [comment]
Yes!

**Comment by mmdaz** [comment]
Thanks so much :)
