### ISSUE TITLE
decrease confidence threshold in wit

### ISSUE THREAD

**Issue by mmdaz** [wit-ai/wit#1308]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question
**What is the current behavior?**
I am receiving only high level confidence entities for example : 0.95  
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
I want to get a bit low level confidence entities for example : 0.70
because I want to get more entities from wit and show them as a suggestion to my users that they choose one of them if it is correct. 
**What is the App ID where you are experiencing this issue (if applicable)?**
2063475790341251

**Comment by jtliao** [comment]
Note that it's not possible to change the default confidence for your app, but in most cases we should return all entities with confidence greater than 0.5.
