### ISSUE TITLE
*Bug* Missing entities after training with POST /samples

### ISSUE THREAD

**Issue by ouamer-dahmani** [wit-ai/wit#1309]
Hi,

This might be related to [#876](https://github.com/wit-ai/wit/issues/876) but since I am not sure I will let you guys decide and reclassify if necessary.

Thanks!

**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
I use POST /samples to train some new intents with a few hundred samples. I upload them respecting the api limit and then wait for my app to get trained.

The problem I see is that some of the new intents never make it into the "intent" entities. To make sure I did a GET /samples to see if it had received them and they are indeed there so it looks more like incomplete training.

From what I remember, new intents would be created from the samples without me having to create them manually. Is that still true?

An example sample that exhibits the issue:
```
{
        "text": "avez-vous des programmes pour les designers?",
        "entities": [
            {
                "entity": "intent",
                "value": "service_designers"
            }
        ]
}
```

I can get it with GET /samples but the "service_designers" intent never appears to exist when I perform a GET /entities/intent.

Other intents from the same training session did appear such as:
```
{
        "text": "est-ce que vous faites des meubles custom?",
        "entities": [
            {
                "entity": "intent",
                "value": "product_custom"
            }
        ]
}
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I am not sure of a generalized repro but I am able to reproduce this fairly easily with mass training, even on a new application.

I just create my entities. Then post my samples and after training some intents are missing.

**What is the expected behavior?**
I would expect all intents in the samples to be trained.

**What is the App ID where you are experiencing this issue (if applicable)?**
2937650459594344
2219595151384316 (english app with similar issues)

**Comment by ouamer-dahmani** [comment]
Hello,

since this project was time-sensitive I ended up going through the samples in the web UI and noticed that it would propose creating the new intent, to which I agreed to:

![image](https://user-images.githubusercontent.com/5343121/50091307-01b9de00-01d9-11e9-9546-3d97ebcf2fa2.png)

Is it normal for those intents to not have been created when I uploaded the samples? Why were some created and others not?

Corollary question: Should I redownload all the samples and POST them anew to make sure that the intent is properly picked up?

**Comment by jtliao** [comment]
This is indeed not expected-- thanks for raising the issue, we'll look into why it's happening.

**Comment by ouamer-dahmani** [comment]
Any update concerning this?

Every time I upload some sample (which can be numerous) I end up missing intents or keywords. It kinda makes training unreliable and causes issues with customers.

Thanks!

**Comment by jtliao** [comment]
We found the issue, will look to have a fix out in the next day or so.

**Comment by jtliao** [comment]
hi @ouamer-dahmani, can you try this again? should be fixed now

**Comment by ouamer-dahmani** [comment]
Hi!

Sorry for not getting back to you sooner but I was pretty busy on another project.

I did not directly verify with the same dataset but I was in the middle of training another app and did not encounter the problem. It used to be very easy to reproduce so I assume it is indeed fixed.

Happy holidays!

-Ouamer
