### ISSUE TITLE
affinity between intent and other entities

### ISSUE THREAD

**Issue by bmcclenahan** [wit-ai/wit#1310]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question

**What is the current behavior?**
some entities get recognized with confidence 1 and returned with intent entities that they have never been trained for when they are not expected or wanted

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
dialogflow has an explicit affinity between intent/action and other entities, so you can say I'd like to see these entities with this intent, but not others. with wit it's more implicit and that's generally good, but often obscure entities are identified based on a word match that have a completely different purpose in the intent. the intent is identified with high confidence, and I'd expect that to reduce the confidence of entities that have never been trained for that intent. is there a way to train this strong affinity out of the model ? currently I have to process them out manually in code.

**What is the App ID where you are experiencing this issue (if applicable)?**
58aecb8b-e2a7-46ff-8f5d-3a04e81575ac

**Comment by jtliao** [comment]
We do take "negative samples" (i.e. samples that do NOT have an entity) into account in training, so generally adding more training data would help. However, processing it on your side would still give you more assurance of this.

**Comment by bmcclenahan** [comment]
Thanks for following up. I've got around 100 samples for the intent, 100% of which do NOT have the entity identified, and still it is included with confidence 1.0. I'm suggesting that the negative affinity isn't working for me. How many samples that don't have it tagged would I need to see a change ?

**Comment by jtliao** [comment]
I see, can you let me know which entities in particular you're referring to that should not be showing up?
