### ISSUE TITLE
post_samples with wit$ system entities cannot insert samples into repo nor recognize such entities for the app

### ISSUE THREAD

**Issue by wr200m** [wit-ai/wit#1311]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
https://wit.ai/docs/http/20170307#post__samples_link
Posting sample with wit$ system entity sometimes does not automatically validate such an entity.  In fact, the sample might not even have made it into the repository of samples. When this happens, there are two symptoms: 1. the 'samples' tab is empty and displays "loading" for ever. 2. manual validation is required as when I re-enter the same sample sentence on the 'understanding' tab, the system suggests the wit/ system entity ("other entities you might like" ) and requires manual validation for wit to fully recognize sample's entities

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Create a new app on wit (in my space, this app is called test3)

2. Run the following curl that has two samples (first one has a wit$datetime entity marked)

curl -XPOST 'https://api.wit.ai/samples?v=20170307' \
  -H "Authorization: Bearer MY_TOKEN" \
  -H "Content-Type: application/json" \
  -d '[{"text":"wake me up at 7am tomorrow","entities":[{"entity":"intent","value":"set"},{"entity":"wit$datetime","value":"7am tomorrow","start":14,"end":26}]},{"text":"cancel the alarm","entities":[{"entity":"intent","value":"cancel"}]}]'

3. go to wit.ai app page, click on 'samples' tab, which will continuously display "loading" without showing any samples

4. click on 'understanding' tab and enter the same sentence "wake me up at 7am tomorrow". It then shows me "Other entities you might like" with a grey check mark right next to wit/datetime waiting for me to check and validate.

**What is the expected behavior?**
The samples should go into the sample repo, and the understanding tab should show the datetime entity inside the list of "Other entities you might like". If I tried two samples with no system wit$ entities, then the samples would seem to  get in without a problem.

**What is the App ID where you are experiencing this issue (if applicable)?**
2082680081796964

**Comment by jtliao** [comment]
Looking into it

**Comment by jtliao** [comment]
hi @wr200m, can you try this again? should be fixed now
