### ISSUE TITLE
Cannot Enter To The Website "WIt.ai". Like Nothing There

### ISSUE THREAD

**Issue by eyalgi11** [wit-ai/wit#1312]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
I Just Enter to Wit.ai site and like there is nothing there
(Photo Below Looks The Same WIth Chrome And Edge)
<img width="960" alt="default" src="https://user-images.githubusercontent.com/2491520/50165020-b2fd6880-02ec-11e9-8ac6-f103403f0af0.PNG">
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I Enter Google, Write "WIt.ai", Enter The Site, Can't DO Anything
**What is the expected behavior?**
That The SIte WIll Be What He Was When I Last Opened Him
**What is the App ID where you are experiencing this issue (if applicable)?**
I Can't Access The ID

Thanks

**Comment by eyalgi11** [comment]
It's Like All The CSS Is Cancelled
<img width="960" alt="default" src="https://user-images.githubusercontent.com/2491520/50295244-52069980-0480-11e9-881c-064ce1175452.PNG">
(The Getting Started Page I Access Through Google)
And That's In Edge The Same So The Chrome Is Not The Problem

**Comment by aforaleka** [comment]
Have you tried clearing your cache? It might be something to do with your network if it isn't the browser. Closing the issue since we can't repro this.

**Comment by eyalgi11** [comment]
A Network Problem Probably
I Was Connected To A Free Wifi That Maked Limitations To Some Website
(I Not Consider it Because It's Opened the site)
Now With Normal WIfi It's Working'
Thanks All Of You
