### ISSUE TITLE
Question: Training with Complex Tokens

### ISSUE THREAD

**Issue by jcuenod** [wit-ai/wit#1314]
**Question**
I am trying to use wit to build a natural language query builder for an app I am working on. An example would be `find plural verbs with singular nouns` which tags as follows:

```
"find" = "intent"
"plural" = "my_number:term-1"
"verbs" = "part_of_speech:term-1"
"singular" = "my_number:term-2"
"nouns" = "part_of_speech:term-2"
```

Note: those fields are `keyword`s

But sometimes instead of writing `first person plural nouns` people write `1pl nouns`.

**What is the current behavior?**

Wit is correctly getting that `1` is `person:term-1` but it seems wit is struggling to tag `pl` in `1pl` with `my_number:term-1`.

**What is the expected behavior?**

Obviously, I'm hoping to get those sequences to be better registered:

```
"1" = "person:term-1"
"pl" = "my_number:term-1"
"nouns" = "my_number:term-1"
```

**What is the App ID where you are experiencing this issue (if applicable)?**

`2673380186007281`

I should add that Wit is also not reliably assigning the role `term-1` to `person` (and I think the reason it's effectively identifying the person is that person is the only tag that uses a number). So the problem simply stated is that I can't get Wit to reliably identify `1pl` as two entities.

The above is a slightly simplified version of the problem. I'm working with Hebrew data and the format is `<person><gender><number>` like `3ms` [for 3rd masculine singular] so it is both `gender` and `number` that Wit never identifies and `person` is never assigned a role)

**Comment by jcuenod** [comment]
I should add that Wit is also not reliably assigning the role `term-1` to `person` (and I think the reason it's effectively identifying the person is that person is the only tag that uses a number).

**Comment by patapizza** [comment]
It seems like it's working:
<img width="990" alt="screen shot 2018-12-20 at 2 06 16 pm" src="https://user-images.githubusercontent.com/1015208/50313522-79e60500-0460-11e9-9834-381e8e50a385.png">
<img width="973" alt="screen shot 2018-12-20 at 2 06 27 pm" src="https://user-images.githubusercontent.com/1015208/50313524-79e60500-0460-11e9-8dd9-9145accfd7e8.png">

For the roles `term-1` and `term-2`, it seems like using a composite entity "term" would be best.

Feel free to reopen and comment back if that doesn't work. Thanks.

**Comment by jcuenod** [comment]
The problem is that I'm trying to catch multiple search terms. That is, in "1pl verbs and 2ms imperatives", I need to distinguish between 2 search terms: (term-1) "first person plural verbs" and (term-2) "second person masculine singular imperatives".

In the example you show, I need to know that `person` is connected to the same search term as `nu`. And in the first example it's working fine but those are not complex tokens (which I'm using to refer to a single "word" in the string that denotes multiple [though non-overlapping] entities).

I have resolved this by retraining with a new "composite person, number, gender" entity and it's working pretty well.
