### ISSUE TITLE
How to train wit/datetime built-in entity in Arabic Language?

### ISSUE THREAD

**Issue by 91ns** [wit-ai/wit#1316]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question
**What is the current behavior?**
I'm trying to train an app with built-in datetime through the API, it worked for "last week" and "last month" but not for a "a week ago". 

I wanted to know if this is supported or not for Arabic language, and if yes what's the correct way to train it for dates like "a week ago" or "a month ago"?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by patapizza** [comment]
Hi @91ns,

`wit/datetime` is powered by [Duckling](https://github.com/facebook/duckling). Feel free to submit a pull request to improve it!
