### ISSUE TITLE
The entities returned by my NER model has changed in the last couple of days

### ISSUE THREAD

**Issue by eliasjonsson-ross** [wit-ai/wit#1317]
I have a pre-trained NER model that detects locations, previously it was able to detect *New York*, *Texas* and *U.S.* from the sentence *New York and Texas are states in the U.S.*. However, now it's only able to detect *U.S.*. I'm using the same model as before and I haven't re-trained it. It was definitely working 2-3 days ago. Do you know what might be happening?

**Comment by aforaleka** [comment]
Hey @eliasjonsson-ross, can you let us know your app-id and the entity with this problem?

**Comment by ross-development** [comment]
Hey @aforaleka, the app-id is 594bfa3f-42d2-4d9d-9ec6-f6a41f60bfdc and the entity with this problem is jurisdiction.

**Comment by eliasjonsson-ross** [comment]
Hey @aforaleka, the app-id is 594bfa3f-42d2-4d9d-9ec6-f6a41f60bfdc and the entity with this problem is jurisdiction

**Comment by aforaleka** [comment]
Seems like the model was last trained on 12/11. I recommend adding validating more samples like "New York and Texas are states in the U.S." with the two states added, so the model can be more confident detecting the states in the sentences. Let us know if that works :)
