### ISSUE TITLE
app is stuck on scheduled

### ISSUE THREAD

**Issue by Nileshlundwani** [wit-ai/wit#1318]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by Nileshlundwani** [comment]
appid is 2173221039389713

**Comment by aforaleka** [comment]
Sorry for not getting to you earlier, seems like your app's training is unstuck and finished on 1/8. Let me know if you encounter this issue again!
