### ISSUE TITLE
Is it possible to create a role for custom entity? 

### ISSUE THREAD

**Issue by globiqGlobema** [wit-ai/wit#1319]
I would like to ask a *question* about wit.

Is it possible to create a role for custom entity? 

I try to train my app (id 2379196575485136) to set a role for my custom entity ocena_stanu. Entity is recognizing properly but role is not set even if I trained for exacly the same example several times.

**Comment by aforaleka** [comment]
Hi @globiqGlobema, thanks for reporting this. You can definitely set roles for custom entities. I took a look at your entity ocena_stanu, can you give me a specific example when it's not recognized?

**Comment by globiqGlobema** [comment]
Now, when I try the same samples I tried a few days ago, it works great. Maybe some time has to be passed after creating a custom entity (in my case, assessment of_state), to teach a role for him? I taught this role right after the creating of the entity.

Thank you in advance for your kind support.

**Comment by aforaleka** [comment]
Awesome! And yes, it does takes a little time for your app to train so it can reflect the new roles added to your entity. You can check the training status to see if your app has finished training :)
