### ISSUE TITLE
REST API /message not returning some (intent) entities?

### ISSUE THREAD

**Issue by psquared2** [wit-ai/wit#1320]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

- Reporting a possible bug?

**What is the current behavior?**

- The API output via REST API is missing some entities.
- The desired entities can be seen from "Samples" tab >> Preview API Output

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Send a query through /message (REST API) - e.g. "i need to drop a course online"
2. Intent entity (labelled "intent") is missing from the output
3. From Wit.ai console, "Samples" tab >> use same query >> Preview API Output
4. Intent entity (labelled "intent") is present

**What is the expected behavior?**

- Preview API Output contains intent entity, which is desired

**What is the App ID where you are experiencing this issue (if applicable)?**

- APP ID 5a5f65cf-78ea-4382-b2a9-ea0a85c456d0

**Comment by psquared2** [comment]
Downgrading this ticket to "**QUESTIONS**": the desired behaviour is seen in some queries

I see intent entity with _some_ queries (e.g. "livrary [sic] catalogue") - what is the criteria for displaying the intent entity?

**Comment by patapizza** [comment]
Hi @psquared2,

I can see the `intent` entity for both queries:

<img width="971" alt="screen shot 2019-01-14 at 9 44 12 am" src="https://user-images.githubusercontent.com/1015208/51130121-193cb480-17e1-11e9-9cac-9b22eeeee891.png">
<img width="974" alt="screen shot 2019-01-14 at 9 44 32 am" src="https://user-images.githubusercontent.com/1015208/51130122-19d54b00-17e1-11e9-9217-36c83b065385.png">

Trait entities show up in the API when the confidence level is above 0.5. To get them for lower confidence, set the `n` parameters to get a list of trait values sorted by decreasing confidence.
