### ISSUE TITLE
'number' and 'amount_of_money' built in entities not been recognised in specific sentence structures. Didn't use to happen earlier.

### ISSUE THREAD

**Issue by monika1800** [wit-ai/wit#1321]
example: 'show all my spends above 9800'
'9800' is not been identified as a 'number'

Similarly, for

example: 'show all my spends above 9800 INR'
'9800 INR' is not been recognised as 'amount_of_money'

**Comment by patapizza** [comment]
Hi @monika1800,

Please use the provided template. What is your app id?

I can't repro:

<img width="967" alt="screen shot 2019-01-11 at 10 17 59 am" src="https://user-images.githubusercontent.com/1015208/51051998-47748700-158a-11e9-9184-7b533ad28897.png">
<img width="984" alt="screen shot 2019-01-11 at 10 18 23 am" src="https://user-images.githubusercontent.com/1015208/51052000-48a5b400-158a-11e9-971e-d25dd215df7d.png">

**Comment by monika1800** [comment]
Hi @patapizza, its working fine now.
