### ISSUE TITLE
Validate Samples From My App

### ISSUE THREAD

**Issue by eyalgi11** [wit-ai/wit#1323]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question
**What is the current behavior?**
I'm Want To Be Able To Validate The Samples From My App
So If I Send A Message To My Bot, And He Returns JSON
I Could Validate And Fix, Send The Same Message And Get Seemingly "Correct" Response
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
I Need To Know How To DO That From Google App Script (Because That's Where I Working On The App)
I Already Read Parts Of The Docs
But They Don't Give Example That Works In Google Script Or That I Just Don't Undestand
I'm Still Very Nooby For Programming
**What is the App ID where you are experiencing this issue (if applicable)?**
2211307315600722

**Comment by stopachka** [comment]
Hey @eyalgi11!  

We don't help at the programming level on support tickets, buut -- 

1) Congrats on getting into your journey of programming! 

2) Would start by google searching "How to make a POST request in {language of your choice}

3) You will want to make a request called POST /samples -- you can find this in https://wit.ai/docs/http
