### ISSUE TITLE
Some questions regarding throttling and migration

### ISSUE THREAD

**Issue by RobertsG** [wit-ai/wit#1324]
Hi there,

We’re planning on migrating some training phrases between several apps, so we wanted to know of some limitations that your platform has.

1. Is there a limit of how many samples can be sent to WIT AI per minute/hour.

1.1. Is it better to send the samples batched or individually, if batched, how does this count against the limit/throttle.

2. We’ve noticed that an Apps scheduled training delays significantly once several samples are sent to it in a row, could you please tell us what affects it, how does it increase/increment, and what would your suggestions be to reduce its growth.

**Comment by stopachka** [comment]
Hey @RobertsG

Currently, the rate limit for POST /samples is 200 / minute
- It will not make a difference between sending individually or batched, but if we suggest sending batched (just makes it simpler to debug down the road, if there are any issues)

Re: training delays -- the training algorithm simply re-schedules a bit farther in advance, but it should not affect it too badly. Could you go into what kind of delays you see?
