### ISSUE TITLE
wit/contact fails on phrases in portugese

### ISSUE THREAD

**Issue by LuizLeite** [wit-ai/wit#1325]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
REPORT A BUG

**What is the current behavior?**
Dont response OK for protuguese phrases

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Meu nome é João - dont return wit/contact - only intent
My name is João - return OK (intent and wit/contact)

**What is the expected behavior?**
Response intent and wit/contact for portuguese phrases

**What is the App ID where you are experiencing this issue (if applicable)?**
2269303183120447

**Comment by aforaleka** [comment]
Thanks for reporting @LuizLeite, we'll look into it! In the meantime, you can try training your own entity for name.

**Comment by LuizLeite** [comment]
Hi again.

Another test. Try this: 

Meu nome **is** Luiz

Its works fine too.

The verb "is" into portuguese phrase working fine.

Tanks

**Comment by stopachka** [comment]
Thanks for the info @LuizLeite -- we will look into this

In the meantime, we suggest you train a custom entity, something like "custom_contact" -- that works with your phrasing. 

We may need to retrain the wit/contact model for portugese

**Comment by jtliao** [comment]
Merging with #1615 for tracking
