### ISSUE TITLE
Apps missing on dashboard

### ISSUE THREAD

**Issue by yash6992** [wit-ai/wit#1327]
I see that 4 out of the 6 apps I had for my wit.ai account are missing from the dashboard at https://wit.ai/yash-greendeck

Is there something I am missing here?

**Comment by patapizza** [comment]
Hi @yash6992,

I can see 6 apps on your page. Feel free to reopen if you still experience the issue.

**Comment by yash6992** [comment]
I see.
I tried re-logging in again via incognito and it worked.
The issue is that I am using two separate github accounts in wit. The UI and the url displayed one and the apps were being displayed for the other.
The other account is at https://wit.ai/yash6992
![screenshot 2019-01-29 at 10 41 10](https://user-images.githubusercontent.com/1450837/51885843-585b3000-23b3-11e9-8d8d-ad121c1fa30e.png)

**Comment by aforaleka** [comment]
I don't see any apps associated with your other account yash6992; but there should be 6 apps for yash-greendeck.
