### ISSUE TITLE
Creating A copy of an existing app

### ISSUE THREAD

**Issue by 91ns** [wit-ai/wit#1328]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
I'm trying to create a copy of one of my apps but it fails to import into a new app with the error "Built in entity already exists"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Export existing app then import it into a new app.

**What is the expected behavior?**
I need to be able to create copies of existing apps. Also, is there a way to perform this through the API?

**What is the App ID where you are experiencing this issue (if applicable)?**
5b3e0844-14de-4253-a897-2670ca50aef6 <= the app I would like to copy

**Comment by aforaleka** [comment]
Hi @91ns! Sorry for the inconvenience, we noticed that in your app there are two "location" entities, one user-defined and one built-in, which caused the bug in importing. We'll look into why that went through in the first place, but the quick fix for you is to either rename the custom one to some name other than "location", or remove it if it's not being used. Hope that helps!
