### ISSUE TITLE
[Request] - Does WIT.AI have plans to implement text to mp3?

### ISSUE THREAD

**Issue by LuizLeite** [wit-ai/wit#1329]
Hi.
I am initiating the development of a Virtual Attendant (text and voice) for the messenger and whatsapp platforms. This virtual attendant aims to assist a Call Center in order to minimize repetitive tasks.

Is there any intention of making text to voice (mp3) available?

If so, is there any forecast?

And this application would have 2 languages, Brazilian Portuguese and English.

Thankful

**Comment by patapizza** [comment]
Hi @LuizLeite,

There is no immediate plans for text-to-speech.
I'll surface it with the team.

Thanks,
Julien

**Comment by Barbog** [comment]
Feature has been implemented. Closing.
