### ISSUE TITLE
Custom models, 256 char limit

### ISSUE THREAD

**Issue by sebastianarena** [wit-ai/wit#1330]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Feature

**What is the current behavior?**
Queries are only allowed up to 256 characters long for training

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
-

**What is the expected behavior?**
I know it has been asked before, and I have more than a dozen apps which work flawlessly with the 256 chars limit. However, there are times were the bots we are training leave input fields for users to submit an inquiry. They normally write quite a bit of text. Never exceeding 1000 characters. Breaking up those sentences is almost imposible, because they mostly contain an explanation of the problem, maybe something they tried fixing with it, and usually (ha!) a kind thank you.
Maybe what I'm saying is that the limit increase could be handled more of a "per request" situation, that you could approve. Much like AWS policy of imposing limits, that you can sometimes ask to be increased.
Would benefit a lot from not having the limit in SOME apps, not all.

THANKS! WE LOVE WIT!

**What is the App ID where you are experiencing this issue (if applicable)?**
-

**Comment by patapizza** [comment]
Hi @sebastianarena,

Thank you for your kind words.

We've optimized our models and infra for that 256 char limit. I understand the ask, and I'll surface it in our meeting.

Thanks,
Julien

**Comment by dfischer** [comment]
What's the status of this @patapizza ?

**Comment by aforaleka** [comment]
Hi @dfischer, we're not prioritizing this at the moment. But we do see the value of having a per request limit increase, and will revisit in the future.

**Comment by sebastianarena** [comment]
🙏
Per request sounds about right... it's not the average, it's the exceptions to the rule that we would love to be able to handle

**Comment by dfischer** [comment]
Got it. Thanks. I do have use cases that don't require it for every request but for specific use cases with our product. Would love to open a dialog on opt-in to this if possible.

Thanks
