### ISSUE TITLE
Question: Counting groups without using roles

### ISSUE THREAD

**Issue by jcuenod** [wit-ai/wit#1332]
I understand why using roles like `grocery_item:first` is not scalable.

I want to allow users to build multiple search terms that have various attributes like "find stores with red vegetables and yellow fruit". The way I see this is:

```
search_context = store
colour:term-1 = red
product:term-1 = vegetable
colour:term-2 = yellow
product:term-2 = fruit
```

How should I be training the model? I'm guessing it's using nesting. If that's the case, is there a good way to convert my data rather than starting from scratch?

**Comment by patapizza** [comment]
Hi @jcuenod,

Have you tried using composite entities?

**Comment by jcuenod** [comment]
Does that mean labeling like:

```
item = red vegetable
color = red
product = vegetable
item = yellow fruit
color = yellow
product = fruit
```

If so, no, but that’s what I meant by “nesting”. If that’s what composite entities are, is there a good way of converting my data to that format?

**Comment by aforaleka** [comment]
Nesting does seems to fit your use case! We currently don't provide a way to convert your data like so, but the model should work well after you've annotated a few examples with the composite entities.
