### ISSUE TITLE
App is not trained after PUT /entities/intent request

### ISSUE THREAD

**Issue by PitichatS** [wit-ai/wit#1335]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug.

**What is the current behavior?**
App is not trained after PUT /entities/intent request.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
URL Endpoint: https://api.wit.ai/entities/intent?v=20170307
Request content:
{"doc":"Intention List","values":[{"value":"end_conversation","expressions":["\u0e1a\u0e32\u0e22","\u0e08\u0e1a\u0e01\u0e32\u0e23\u0e2a\u0e19\u0e17\u0e19\u0e32","\u0e08\u0e1a\u0e40\u0e2b\u0e2d\u0e30","\u0e44\u0e21\u0e48\u0e04\u0e38\u0e22\u0e41\u0e25\u0e49\u0e27","\u0e44\u0e21\u0e48\u0e04\u0e38\u0e22","\u0e40\u0e25\u0e34\u0e01\u0e04\u0e38\u0e22","\u0e40\u0e25\u0e34\u0e01\u0e46","\u0e41\u0e25\u0e49\u0e27\u0e04\u0e38\u0e22\u0e01\u0e31\u0e19\u0e43\u0e2b\u0e21\u0e48","\u0e44\u0e1b\u0e01\u0e48\u0e2d\u0e19\u0e25\u0e48\u0e30"]},{"value":"greeting","expressions":["\u0e17\u0e31\u0e01\u0e08\u0e23\u0e49\u0e32","\u0e17\u0e31\u0e01\u0e08\u0e49\u0e32","\u0e17\u0e31\u0e01","\u0e14\u0e35\u0e08\u0e23\u0e49\u0e32","\u0e14\u0e35\u0e08\u0e49\u0e32","hello","\u0e14\u0e35","\u0e14\u0e35\u0e04\u0e23\u0e31\u0e1a","\u0e14\u0e35\u0e04\u0e31\u0e1a","\u0e14\u0e35\u0e04\u0e48\u0e30","\u0e14\u0e35\u0e04\u0e48\u0e32","\u0e14\u0e35\u0e2e\u0e31\u0e1a","\u0e2e\u0e31\u0e25\u0e42\u0e2b\u0e25","\u0e42\u0e2b\u0e25","\u0e14\u0e35\u0e46","\u0e2b\u0e27\u0e31\u0e14\u0e14\u0e35","\u0e2b\u0e27\u0e31\u0e14\u0e14\u0e35\u0e04\u0e23\u0e31\u0e1a","\u0e2b\u0e27\u0e31\u0e14\u0e14\u0e35\u0e04\u0e48\u0e30","\u0e2a\u0e27\u0e31\u0e2a\u0e14\u0e35","\u0e2b\u0e27\u0e32\u0e14\u0e14\u0e35","\u0e2b\u0e27\u0e32\u0e14\u0e40\u0e14","\u0e2b\u0e27\u0e31\u0e14\u0e40\u0e14","\u0e15\u0e31\u0e27\u0e40\u0e18\u0e2d","\u0e2e\u0e32\u0e22","\u0e14\u0e35\u0e08\u0e48\u0e30","\u0e42\u0e2b\u0e25\u0e46\u0e46\u0e46","\u0e2d\u0e31\u0e19\u0e22\u0e2d\u0e07","\u0e2a\u0e30\u0e1a\u0e32\u0e22\u0e14\u0e35","\u0e40\u0e2e\u0e42\u0e2b\u0e25","\u0e40\u0e2e\u0e25\u0e42\u0e2b\u0e25","\u0e42\u0e22\u0e48\u0e27","hihi","hi","\u0e17\u0e31\u0e01\u0e17\u0e32\u0e22","\u0e17\u0e31\u0e01\u0e46","\u0e27\u0e48\u0e32\u0e44\u0e07","\u0e01\u0e4a\u0e2d\u0e01\u0e46","\u0e42\u0e2b\u0e25\u0e46","\u0e40\u0e2e\u0e49","\u0e40\u0e2e\u0e25\u0e42\u0e2b\u0e25\u0e27","\u0e2e\u0e32\u0e42\u0e2b\u0e25","\u0e2e\u0e32\u0e42\u0e2b\u0e22","\u0e44\u0e2e","\u0e44\u0e2e\u0e49","\u0e42\u0e2b\u0e22\u0e46","\u0e27\u0e48\u0e32\u0e07\u0e32\u0e22","\u0e27\u0e48\u0e32\u0e44\u0e07\u0e40\u0e2d\u0e48\u0e22","\u0e40\u0e2b\u0e27\u0e22","\u0e19\u0e35\u0e48\u0e46"]},{"value":"thankyou","expressions":["\u0e02\u0e2d\u0e1a\u0e04\u0e38\u0e13","\u0e02\u0e2d\u0e1a\u0e04\u0e38\u0e13\u0e21\u0e32\u0e01","\u0e02\u0e2d\u0e1a\u0e04\u0e38\u0e13\u0e2b\u0e25\u0e32\u0e22","\u0e02\u0e2d\u0e1a\u0e1e\u0e23\u0e30\u0e04\u0e38\u0e13","\u0e02\u0e2d\u0e1a\u0e43\u0e08","\u0e02\u0e2d\u0e1a\u0e43\u0e08\u0e08\u0e23\u0e34\u0e07\u0e46","\u0e02\u0e2d\u0e1a\u0e43\u0e08\u0e19\u0e30","\u0e02\u0e2d\u0e1a\u0e43\u0e08\u0e21\u0e32\u0e01","\u0e0a\u0e48\u0e27\u0e22\u0e44\u0e14\u0e49\u0e40\u0e22\u0e2d\u0e30\u0e40\u0e25\u0e22\u0e02\u0e2d\u0e1a\u0e04\u0e38\u0e13\u0e21\u0e32\u0e01","\u0e42\u0e2d\u0e49\u0e02\u0e2d\u0e1a\u0e04\u0e38\u0e13"]}]}
Response:
{
  "builtin" : false,
  "name" : "intent",
  "doc" : "Intention List",
  "id" : "859a358c-959b-fe4c-d45d-336d84074231",
  "lang" : "th",
  "lookups" : [ "trait" ]
}

Time: 2019-01-28 23:39:14 (UTC+07)

**What is the expected behavior?**
All expressions should appear in app and then it will be scheduled to train after that.

**What is the App ID where you are experiencing this issue (if applicable)?**
f14ad5c8-5d12-180e-5360-9263d53a2bd3

**Comment by aforaleka** [comment]
Hi @PitichatS, since the `intent` entity is a trait entity, we don't take `values` and `expressions` of your request content into account; those are only considered when the entity has the keyword lookup. For adding samples for a certain intent (e.g. greeting), you can use the POST /samples endpoint (https://wit.ai/docs/http/20170307#post__samples_link)

**Comment by PitichatS** [comment]
> 
> 
> Hi @PitichatS, since the `intent` entity is a trait entity, we don't take `values` and `expressions` of your request content into account; those are only considered when the entity has the keyword lookup. For adding samples for a certain intent (e.g. greeting), you can use the POST /samples endpoint (https://wit.ai/docs/http/20170307#post__samples_link)

Thank you so much for the explanation. I'll try POST /samples endpoint as you mention.
