### ISSUE TITLE
[bug] Cannot log into my old wit.ai account on dashboard

### ISSUE THREAD

**Issue by edwardselig** [wit-ai/wit#1336]
I Cannot log into my old account wit.ai on dashboard.  I tried messaging help@wit.ai about it and I just got a response from Himanshu telling me to post on github for traceability.  I signed up for wit.ai over a year ago and the nlp on my facebook app still works using my setting from wit but I am unable to log into my old account to modify my wit settings.

**Comment by aforaleka** [comment]
Hey @edwardselig, can you log into your account via Facebook or Github? Those have been the two ways for signing up for Wit.ai. The email you provided is used for communication purposes and not for logging in.
