### ISSUE TITLE
App in training mode for hours 

### ISSUE THREAD

**Issue by 91ns** [wit-ai/wit#1337]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
The App has been in training mode for hours 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**
1920697761332727

**Comment by aforaleka** [comment]
Hi @91ns, I've restarted the training and your app should be trained now. Thanks for reporting the issue!
