### ISSUE TITLE
App stuck in Ongoing status

### ISSUE THREAD

**Issue by hsilvester** [wit-ai/wit#1338]
Reporting a bug:

Current behavior - My app has been stuck in the Ongoing status for several days now. The first time I noticed this was on 1/27/19 at approximately 3:00 PM MST. I confirmed this morning that it is still in Ongoing status.

I've reported this through help@wit.ai as I don't usually post app data here.

**Comment by 91ns** [comment]
Can we have more clarification as to why apps get stuck in on going status? It happens more often in some of our apps. Is this something related to the content used for training?

**Comment by aforaleka** [comment]
Hi @hsilvester, since your app is pretty big it won't train instantly , but I've restarted it and your app is scheduled to train tonight. Hope that helps!

**Comment by hsilvester** [comment]
@aforaleka Thank you for restarting it! I'll keep an eye on it to see if it finishes training tomorrow.

**Comment by hsilvester** [comment]
@aforaleka Previously, the app showed how long it would take to train compared to the last time. After restarting it and it began training, it's just always in the Ongoing status. I realize the app has a lot of trained data, however, do you know if it would ever finish training and move to Done?

**Comment by LHommeDeBat** [comment]
> 
> 
> Hi @hsilvester, since your app is pretty big it won't train instantly , but I've restarted it and your app is scheduled to train tonight. Hope that helps!

My app seems to be stuck too. Last training lasted for 8 seconds. Now it's ongoing for hours. My App-ID is: 2006122659443708

Could you restart mine too?

**Comment by aforaleka** [comment]
Hi @hsilvester, sorry for the delayed response. We looked into your app and saw that the number of intent values your app has is quite large, and the current training we provide won't do well for that size. We are working on a solution for you in the next month or so, but in the meantime, I suggest downsizing and splitting your app. Feel free to reach out in intercom if you want to discuss more and we will update you with our solution.

**Comment by LHommeDeBat** [comment]
@aforaleka Thank you! The status of my app is now "DONE".

**Comment by patapizza** [comment]
@hsilvester We're monitoring your app closely. Thanks for your patience.

**Comment by jaisrael1** [comment]
I am having a similar problem, I added one sample to App-ID 2304317796287134 and it has been stuck at ongoing with "Last time it took your app 8 s to train." for a while.

**Comment by patapizza** [comment]
@jaisrael1 It seems like your app is now up-to-date:
<img width="330" alt="screen shot 2019-02-15 at 5 18 33 pm" src="https://user-images.githubusercontent.com/1015208/52892270-c474bc80-3145-11e9-8872-c6b3eb121463.png">

**Comment by patapizza** [comment]
This should now be fixed. Thank you for your patience.
