### ISSUE TITLE
App created from zip file has no samples

### ISSUE THREAD

**Issue by jaisrael1** [wit-ai/wit#1339]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
When I try to create an app from another app's data zip file, it loads all the entities and values, but none of the expressions.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Create app from zip

**What is the expected behavior?**
The new app will have all of the training samples that were in the source app

**What is the App ID where you are experiencing this issue (if applicable)?**
2231751310219810

**Comment by aforaleka** [comment]
Closing because can't repro. Feel free to reopen if that's still happening.
