### ISSUE TITLE
Expressions confusion

### ISSUE THREAD

**Issue by Aydino** [wit-ai/wit#1341]
App Id : 5a663033-82f2-44ed-ad06-99d2b2b47942

We have faced a different situation in our application. These two endpoints that have different expression values. For example, when we are receiving GET /entities/:entity-id, there are expressions which are not shown in wit.ai console. On the other hand, when we use GET /samples endpoint, we are receiving the last trained expressions.

We can't see our expressions which are trained before so our chatbot works fine but the panel we have developed, can not train or show correct expressions.

**Comment by aforaleka** [comment]
Hi @Aydino, can you give us an example of what you mean by "expressions which are not shown in wit.ai console" and "last trained expressions"?

**Comment by grkn** [comment]
Let me explain myself 👍 
For example:
when we get expressions from entity object we can not see expressions which are trained before.
when we train(POST /samples) we can not see in entity object but we can get from GET /samples

**Comment by jtliao** [comment]
Can you give an example workflow with what curls you sent (i.e. example POST /samples request, example GET /entities/:id request) and what you expect to see v.s. what you currently see?

**Comment by aforaleka** [comment]
Closing the issue until more info is given
