### ISSUE TITLE
Will it be possible to get the corresponding phrase of the sentence which determines 'datetime' entity

### ISSUE THREAD

**Issue by monika1800** [wit-ai/wit#1342]
e.g: What is the date today?

Required Feature:
Adding 'text' as a field in datetime array. 
e.g: "text": "today"

Payload without 'text' field:
 "datetime": [
      {
        "confidence": 0.957305,
        "values": [
          {
            "value": "2019-02-04T00:00:00.000+05:30",
            "grain": "day",
            "type": "value"
          }
        ],
        "value": "2019-02-04T00:00:00.000+05:30",
        "grain": "day",
        "type": "value"
      }
    ]

Payload with 'text' field:
 "datetime": [
      {
        "confidence": 0.957305,
        "values": [
          {
            "text": "today"
            "value": "2019-02-04T00:00:00.000+05:30",
            "grain": "day",
            "type": "value"
          }
        ],
        "text": "today",
        "value": "2019-02-04T00:00:00.000+05:30",
        "grain": "day",
        "type": "value"
      }
    ]

**Comment by aforaleka** [comment]
Hi @monika1800, you can set the `verbose` flag to true in GET /message, and get the "text" using the "_body" field.

For example, when `verbose` is set to true, you will see this information for wit/datetime:
```
"datetime" : [
         {
            "grain" : "day",
            "confidence" : 0.955135,
            "value" : "2019-02-04T00:00:00.000-08:00",
            "_end" : 22,
            "values" : [
               {
                  "value" : "2019-02-04T00:00:00.000-08:00",
                  "type" : "value",
                  "grain" : "day"
               }
            ],
            "_entity" : "datetime",
            "type" : "value",
            "_body" : "today",
            "_start" : 17
         }
      ]
```
