### ISSUE TITLE
Spaces before the final punctuation mark affect detection

### ISSUE THREAD

**Issue by ouamer-dahmani** [wit-ai/wit#1345]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
**BUG**

**What is the current behavior?**
Adding spaces before the final punctuation mark affects the detected intent (if it detects one). I have not pushed my tests to see if this an issue generalized to all types of punctuation.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
See the attached images.
![wit ai_punctuation_bug](https://user-images.githubusercontent.com/5343121/52416284-449c8180-2ab7-11e9-957f-15c1b473d237.png)
![wit ai_punctuation_bug_2](https://user-images.githubusercontent.com/5343121/52416285-449c8180-2ab7-11e9-906f-1c0c2b6a9577.png)

**What is the expected behavior?**
The amount of spaces before the final punctuation mark should not matter.

**What is the App ID where you are experiencing this issue (if applicable)?**
1875945119167092

**Comment by jtliao** [comment]
we'll look into what is causing this
