### ISSUE TITLE
Wit not recognizing multiple locations with durations

### ISSUE THREAD

**Issue by jaisrael1** [wit-ai/wit#1346]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug

**What is the current behavior?**
App fails to recognise the location entity 'Malaysia' in this sentence:
  "australia for 2 days and malaysia for a week"

It recognizes it just fine in this sentence:
"australia for 2 days and malaysia for 7 days"

Note that it also fails to recognize 'Australia' here:
"malaysia for a week and australia for 2 days"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Create a brand new app, enable the wit/location and wit/duration entities, and enter the above three sentences. 

**What is the expected behavior?**
It should recognise the location entity 'Malaysia' in the first 2 sentences and 'Australia' in the third. 

**What is the App ID where you are experiencing this issue (if applicable)?**
2662646560419471

**Comment by jtliao** [comment]
hey @jaisrael1, we will look into this

**Comment by jaisrael1** [comment]
Thanks!

**Comment by jaisrael1** [comment]
Any update on this? It is critical for a time-sensitive project.

**Comment by jtliao** [comment]
@jaisrael1 still looking into it. for whatever reason, if you capitalize Malaysia, it will resolve. trying to figure out why the lowercase is not working

**Comment by jtliao** [comment]
Merging with #1615 for tracking
