### ISSUE TITLE
Best practices for implementing comparisons

### ISSUE THREAD

**Issue by 91ns** [wit-ai/wit#1347]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question

What's the best practice to train an app to understand comparisons between 2 or 3 items? 

For example : 
How many employees are in x compared to y?

What are the differences in sales between x and y?

One approach would be to train each expression with an intent, such as "employee_comparison" and "sales_comparison"

Another approach would be to have one intent called "comparison" and another trait entity called "comparison_type" having "sales" and "employees" as values.

**Comment by jtliao** [comment]
This is an interesting case, off the top of my head it may be worth trying a trait entity "comparison" as you mentioned, with "sales" and "employees" as values, then trying a free-text/keywords entity with roles to capture "x" and "y"
