### ISSUE TITLE
Unable to create intent

### ISSUE THREAD

**Issue by capusta** [wit-ai/wit#135]
Hopefully this is temporary or an easy fix.  

When creating an intent titled "24iaOm8WPhQ" (no quotes), the system renames it to _4iaOm8WPhQ.  When attempting to rename the intent - get an error message - saying the intent already exists.

_24iaOm8WPhQ_ or any combination of "24iaOm8WPhQ" or '24iaOm8WPhQ' is considered legitimate (using double and single quotes).

Edit: Seems like intents cannot start with numbers ...

**Comment by stopachka** [comment]
Hi @capusta! Apologies for the late response here. intents are now deprecated. You can learn more about the changes here -> https://wit.ai/blog/2016/04/12/bot-engine
