### ISSUE TITLE
location not getting resolved and "Christmas Island" getting resolved to Wit/date

### ISSUE THREAD

**Issue by frooty1234** [wit-ai/wit#1351]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behaviour?**
I am trying out the following locations but these are not getting resolved to proper location : 
Proserpine, Paraburdoo, Kununurra,  Rarotonga, Cocos Islands, Learmonth, Esperance,Denpasar Bali, Newman, Coolangatta, Nadi,  Windarling.

There is a location named " Christmas Island" , this is classified under Wit/date . 

Also Wit/location is bit greedy , if any random word say "xyz" is classified under Wit/location. Is there any way I can avoid this greediness to some extent?

**If the current behaviour is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Trying out  following locations : 
Proserpine, Paraburdoo, Kununurra,  Rarotonga, Cocos Islands, Learmonth, Esperance,Denpasar Bali, Newman, Coolangatta, Nadi,  Windarling.

Try out  location named " Christmas Island" , this is classified under Wit/date . 

Try out random word say "xyz" is classified under Wit/location.

**What is the expected behaviour?**
These locations (Proserpine, Paraburdoo, Kununurra,  Rarotonga, Cocos Islands, Learmonth, Esperance,Denpasar Bali, Newman, Coolangatta, Nadi,  Windarling.) should get resolved under Wit/location.

" Christmas Island" should be resolved as location not Wit/date

Any random word should not be classified as Wit/location

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by patapizza** [comment]
Hi @frooty1234, what is your app id?

**Comment by frooty1234** [comment]
@patapizza My App id is  2414220128618601

**Comment by patapizza** [comment]
Hi @frooty1234,

Thank you for the feedback. We'll work on getting proper resolution for the provided locations.

For random words like `xyz` it's a tough call as there exist locations such as `krk` (which should also get resolved). The proper way to go around model greediness is to match against a resolution service (either local database or the resolved value).

**Comment by jtliao** [comment]
Merging with #1615 for tracking
