### ISSUE TITLE
Which trait to use for synonym phrase with a difference of verb

### ISSUE THREAD

**Issue by MagSag** [wit-ai/wit#1352]
I have a trait entity(intent) that I have trained but it is not decteting the intent : 

I trained it with : **I need to sue someone** //_PROVIDER_ADVOCATE (Trait entity)_
I tested with : **I want to sue someone** 
I tested after 3 days but still it didn't show the trait, as you can observe the only word I changed was the verb need with want... and in my app I have a lot of such case where the same thing can be said : **help me sue** 
My Questions : 
1) I am wondering which strategy is the best to use so that Wit can understand the similarity between these sentences.
2) Wit is not recognizing this trained text too.

My app id is : 1460880240681105

**Comment by aforaleka** [comment]
Hi @MagSag, adding more training samples for the entity should fix the problem. We also suggest using the `intent` entity with value = PROVIDER_ADVOCATE instead of a separate trait entity if you expect each sentence to have one intent. (https://wit.ai/docs/recipes#categorize-the-user-intent) Hope that helps!

**Comment by MagSag** [comment]
Ok, some how it just we have added a lot of samples for some intent but still WIT is poorly detecting when you bring a slight difference with words. I chose to go with trait entities for each intent because of what was explained here :  [https://github.com/wit-ai/wit/issues/18](https://github.com/wit-ai/wit/issues/18)  (Usage of the binary seems to be the solution to my use case).

**Comment by aforaleka** [comment]
Gotcha -- adding more samples will improve the recall for your trait entities. If you look at the "insights" for your PROVIDER_advocate entity, you'll notice the "recall" score is still pretty low. Adding more samples (we suggest 50) should improve that. This may be helpful: https://wit.ai/docs/recipes#which-confidence-threshold-should-i-use
