### ISSUE TITLE
Wit does not recognize the entities

### ISSUE THREAD

**Issue by MagSag** [wit-ai/wit#1353]
I have trained my wit engine and have noticed that it is not detecting my trait entities for even the phrase I trained it with.

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by MagSag** [comment]
My app id is : 1460880240681105

**Comment by patapizza** [comment]
Hi, please use the provided template. What examples don't work, what is expected and what is the response instead?

Random sample seems like it works:
<img width="973" alt="screen shot 2019-02-20 at 2 41 21 pm" src="https://user-images.githubusercontent.com/1015208/53129905-aaf4bb80-351d-11e9-8e32-a320185a5059.png">

Feel free to reopen with more details if you still have the issue.
