### ISSUE TITLE
wit/datetime is not working properly 

### ISSUE THREAD

**Issue by 91ns** [wit-ai/wit#1354]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
In the understanding section, I'm trying to train expressions having datetime values but it's not being detected by wit 

![image](https://user-images.githubusercontent.com/25252530/53077176-217fc200-34fa-11e9-8aa9-ca9c3055d392.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**
2035049146549177

**Comment by patapizza** [comment]
Thanks for reporting, we're looking into this.

**Comment by jtliao** [comment]
hey @91ns, this should be working now, I just tested with your app
<img width="673" alt="screen shot 2019-02-20 at 9 25 45 pm" src="https://user-images.githubusercontent.com/13305586/53145725-21adab00-3556-11e9-8e8f-d64f324b735b.png">
