### ISSUE TITLE
App Stuck on Scheduled

### ISSUE THREAD

**Issue by tarpitgrover** [wit-ai/wit#1355]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
App is stuck on scheduled.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**
1879082498812979

**Comment by patapizza** [comment]
Hi @tarpitgrover,

It seems like your app is trained:
<img width="332" alt="screen shot 2019-02-22 at 10 15 28 am" src="https://user-images.githubusercontent.com/1015208/53262224-e52f9b80-368a-11e9-9893-717adf6c0c2c.png">


If many apps are active, it might take sometime to get scheduled
