### ISSUE TITLE
Unsupported get request. Object with ID 'speech' does not exist, cannot be loaded due to missing permissions, or does not support this operation

### ISSUE THREAD

**Issue by isnaasharimam** [wit-ai/wit#1356]
my app id: 1657374664366385

`POST /speech` api has been working correctly but now I'm getting this error
```
{
    "error": "Unsupported get request. Object with ID 'speech' does not exist, cannot be loaded due to missing permissions, or does not support this operation",
    "code": "bad-request"
}
```
What's problem and how to solve it?

**Comment by jtliao** [comment]
hi @isnaasharimam, it looks like you're going GET /speech instead of POST /speech. I just tried reproducing, and got that exact error doing GET /speech.
