### ISSUE TITLE
Content-type for audio stream

### ISSUE THREAD

**Issue by srishti77** [wit-ai/wit#1357]
I am building an android app, where I want to send audio in byte array form and get the intention of the user. Following is the code that I have written to communicate with Wit.ai speech API

`  
   fun getIntention(byteArray: ByteArray) {

        val url = "https://api.wit.ai/speech"
        val key = "my key"

        val param1 = "20190222"
        val charset = "UTF-8"

        try {

            val query = String.format(
                "v=%s", URLEncoder.encode(param1, charset))

            Log.d("Here", "$url?$query")
            val connection: HttpURLConnection =
                URL("$url?$query").openConnection() as HttpURLConnection

            connection.setRequestProperty("Authorization", "Bearer $key")

            connection.setRequestProperty("Content-Type",
                "audio/raw;encoding=signed-integer;bits=16;rate=44000;endian=big")

            connection.setRequestProperty("Transfer-Encoding", "chuncked")
            connection.setRequestProperty("Accept", "json")
           connection.doOutput = true
            connection.doInput = true
            val outputStream: OutputStream = connection.outputStream
            outputStream.write(byteArray)
            outputStream.close()
            connection.connect()

            Log.d("Response code", "${connection.responseCode}")
            Log.d("Response Message", "${connection.responseMessage}")

            val responseCode = connection.responseCode
            var response: BufferedReader? = null
           
            if(responseCode >=400){
                response = BufferedReader(InputStreamReader(connection.errorStream))
            }
            else{
                 response = BufferedReader(InputStreamReader(connection.inputStream))
            }

            while (true) {

                val line = response.readLine() ?: break
                Log.d("line: ", "$line")
            }

        } catch (e: Exception) {

            e.printStackTrace()
        }`

I have a feeling that the problem lies in the Content-type property. 
**My Audio data format: PCM 16 bit per sample**. I have checked the https://github.com/wit-ai/wit/issues/935 issue and the solution given does not help in my case. Any help would be highly appreciated.

**Comment by aforaleka** [comment]
Hi @srishti77, what is the error you're getting? There seems to be a typo in "connection.setRequestProperty("Transfer-Encoding", "**chuncked**")", does fixing it help?

**Comment by srishti77** [comment]
Thank you very much for the response. I have corrected the typo and still I have the same problem. 
The response code is 400. Is there a limit on the byte Array size? My byte array size is 724776.

`java.io.FileNotFoundException: https://api.wit.ai/speech?v=20190222
 System.err:    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:251)
System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(Unknown Source:0)
System.err:     at com.example.simvelop.speechrecognization.SpeechRecognizationUsingWit.getIntention(SpeechRecognizationUsingWit.kt:67)
System.err:     at com.example.simvelop.speechrecognization.SpeechRecognizationUsingWit.doInBackground(SpeechRecognizationUsingWit.kt:26)
System.err:     at com.example.simvelop.speechrecognization.SpeechRecognizationUsingWit.doInBackground(SpeechRecognizationUsingWit.kt:16)
System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:333)
System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
System.err:     at java.lang.Thread.run(Thread.java:764)
`

**Comment by jtliao** [comment]
That byte size should be fine. Can you try calling the POST /speech API directly with the audio, to make sure it's not an issue with the code itself?

**Comment by srishti77** [comment]
Thank you for your response. The issue is resolved. I made some changes in the connection property.
Following is my code:

` 
              
           val query = String.format("v=%s", URLEncoder.encode(param1, charset))
            connection = URL("$url?$query").openConnection() as HttpsURLConnection
            connection?.doOutput = true
            connection?.requestMethod = "POST"
            connection?.setRequestProperty(
                "Content-Type",
                "audio/raw;encoding=signed-integer;bits=16;rate=44000"
            )
            connection?.setRequestProperty("Authorization", "Bearer $key")
            val outputStream: OutputStream = connection?.outputStream!!
            outputStream.write(byteArray)
            connection?.connect()
            val responseCode = connection?.responseCode
            if (responseCode == HttpsURLConnection.HTTP_OK) {
                  response = BufferedReader(InputStreamReader(connection?.inputStream))
                 //do your work
            }
`

**Comment by aforaleka** [comment]
Glad it's working!
