### ISSUE TITLE
BUG: Continuous Retraining

### ISSUE THREAD

**Issue by jcuenod** [wit-ai/wit#1358]
**What is the current behavior?**

Wit is continuously training without any changes to the data. I do see `done` every now and then but within a few minutes it will have changed to either `scheduled` or `ongoing`.

To be honest, the quality of my results has seemed to be decreasing which is why this concerns me enough to post an issue - perhaps I've mangled my own data in some way or something.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Right now I can just be watching my dashboard and my models continually retrain without any change to the data (I am the only one editing the data). So steps to reproduce are just, watch my models...

**What is the expected behavior?**

After tagging a sample, I am used to wit changing from `done` to `ongoing`/`scheduled`. If the models and samples don't change I expect training not to be happening.

**What is the App ID where you are experiencing this issue (if applicable)?**

2487005358039904

**Comment by aforaleka** [comment]
Hi @jcuenod, thank you for reporting and sorry that this is happening. We have stopped your app's training for now and will look into it.

**Comment by jcuenod** [comment]
Thanks

**Comment by jcuenod** [comment]
Just to update - it now appears to have been training for a few hours...

**Comment by jcuenod** [comment]
And to follow up further, it's still going.

**Comment by patapizza** [comment]
Hi @jcuenod, your training is fixed -- you're right: your app took 21s to train.

**Comment by jcuenod** [comment]
Thanks! Can you tell me what the problem was?

**Comment by patapizza** [comment]
A scheduling issue, manually retraining the app fixed it.
