### ISSUE TITLE
stuck on scheduler 

### ISSUE THREAD

**Issue by jordihasianta** [wit-ai/wit#1359]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
Stuck on schedule
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
it should be proceed to the training process. Or can you tell me why wit.ai sometimes choose the training schedule too far? thanks
**What is the App ID where you are experiencing this issue (if applicable)?**
1965681066892470

**Comment by Ayush-Rajniwal** [comment]
Same Problem Training process is scheduled a day ahead. Without training wrong intent and entities are being return.

**Comment by patapizza** [comment]
Hi @jordihasianta, the training status was done and I manually retrained it to ensure it trains properly.
