### ISSUE TITLE
Support for russian language

### ISSUE THREAD

**Issue by efa2000** [wit-ai/wit#136]
Hi,

Is there any plans to support russian language?

Thanks,
Maksim

**Comment by virt87** [comment]
Anything new on russian?

**Comment by l5t** [comment]
We do support russian. We don't have yet built-in entities though so feel free to contribute here: duckling.wit.ai
![image](https://cloud.githubusercontent.com/assets/6992759/13511818/c9c7a35c-e14b-11e5-8c95-6d4ec187e0b5.png)

**Comment by Vaanres** [comment]
Could you please support Vietnamese :(, i would love to develop a customer service chat bot, but i need vietnamese, thanks you so much

**Comment by vnthanh** [comment]
Wit does support Vietnamese, but we need to provide our own intents, not built-in entities. Numbers of wit app  for Vietnamese is tiny, so keep making app for Vietnamese will make wit deal better with it.

**Comment by maxaliev** [comment]
............................................................................................................................................................................

**Comment by maxaliev** [comment]
...............................................................
