### ISSUE TITLE
Problems with the expressions 

### ISSUE THREAD

**Issue by luciabra** [wit-ai/wit#1360]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
report a *bug*

**What is the current behavior?**
 Most of the expressions we have loaded do not appear in the intentions

**What is the expected behavior?**
Before all the expressions that we had loaded appeared here https://wit.ai/fsilvera/monibot/entities/intent

**What is the App ID where you are experiencing this issue (if applicable)?**
592c7140-faa6-41c7-acbd-470b510dc933

**Comment by patapizza** [comment]
Hi @luciabra,

At a quick glance, this seems to be working fine:

<img width="985" alt="screen shot 2019-03-01 at 11 47 30 am" src="https://user-images.githubusercontent.com/1015208/53662482-d8292400-3c17-11e9-8460-19137bc5f781.png">

Can you give an example of expressions that doesn't work?
