### ISSUE TITLE
Keyword synonyms are not recognized

### ISSUE THREAD

**Issue by 91ns** [wit-ai/wit#1361]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
Synonyms of entity keyword value are not being recognized, even though it's basically the same word but in lower case 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
![image](https://user-images.githubusercontent.com/25252530/53563388-8c657480-3b5c-11e9-9c06-e43a77ce8005.png)

![image](https://user-images.githubusercontent.com/25252530/53563418-9dae8100-3b5c-11e9-96da-32b3d6072346.png)

**What is the expected behavior?**
Keyword synonyms should be understood

**What is the App ID where you are experiencing this issue (if applicable)?**
2035049146549177

**Comment by aforaleka** [comment]
Merging with #1371
