### ISSUE TITLE
speech api is not working

### ISSUE THREAD

**Issue by beqabeqa473** [wit-ai/wit#1362]
hello. i am using your speech api and it worked in the past.
today it stopped working.

in response it says timeout please try again.

what is the problem?

**Comment by solyarisoftware** [comment]
the same here :(

```
HTTP/1.1 100 Continue
Server: proxygen
Date: Thu, 28 Feb 2019 13:31:21 GMT

HTTP/1.1 408 Request Timeout
Content-Type: application/json
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
X-Content-Type-Options: nosniff
Date: Thu, 28 Feb 2019 13:31:51 GMT
Server: proxygen
Connection: keep-alive
Content-Length: 71

{
  "error" : "Timeout, please try again later",
  "code" : "timeout"
}# 

```

**Comment by solyarisoftware** [comment]
service is now up & running again :)

**Comment by beqabeqa473** [comment]
confirmed

**Comment by dadaloop82** [comment]
me too, same problem unfortunately ...

**Comment by backmeupplz** [comment]
Same here, still receivng timeouts. Status page isn't loading.

**Comment by patapizza** [comment]
Thanks for reporting, investigating.

**Comment by patapizza** [comment]
The service should be back to normal. Sorry for the inconvenience.

**Comment by Sergey047** [comment]
Hello, can I find out why the service did not work? What is the reason? And what is the probability of repeated failures?

**Comment by patapizza** [comment]
Hi, we got an unexpected sudden load increase. We're working on improving our infra to reduce the likelihood of such events happening again.

**Comment by Sergey047** [comment]
Now 
{
  "error" : "Timeout, please try again later",
  "code" : "timeout"
}

**Comment by beqabeqa473** [comment]
issue still persists

**Comment by solyarisoftware** [comment]
issue still persists :(

**Comment by backmeupplz** [comment]
@patapizza it's happening again :(

**Comment by patapizza** [comment]
Fixed again, thank you on your patience while we're working on a viable solution.

**Comment by backmeupplz** [comment]
@patapizza hmmm, doesn't seem to be fixed, still processing only 10% of the requests

**Comment by patapizza** [comment]
@backmeupplz Give a few minutes for the infra to recover - should be better now. Apologies again.

**Comment by backmeupplz** [comment]
seems resolved for now :)

**Comment by catvlad** [comment]
I'm seeing the problem again. TImeout error

**Comment by dadaloop82** [comment]
408 error ... does not work ...

**Comment by backmeupplz** [comment]
Confirmed, not working again :(

**Comment by backmeupplz** [comment]
Summoning @patapizza

**Comment by Meugenn** [comment]
![photo_2019-03-04_20-18-51](https://user-images.githubusercontent.com/40069502/53753777-bc917800-3eba-11e9-8233-7327ab55e175.jpg)

**Comment by backmeupplz** [comment]
![photo_2019-03-04_10-19-53](https://user-images.githubusercontent.com/3192028/53753840-15372580-3e67-11e9-8194-97a219120366.jpg)

**Comment by tipoc123** [comment]
![photo_2019-03-04_21-20-01](https://user-images.githubusercontent.com/15922591/53753842-4ba28e00-3ec3-11e9-860c-908a5d794780.jpg)

**Comment by adree67** [comment]
![image](https://user-images.githubusercontent.com/40829881/53753900-78ef3c00-3ec3-11e9-9407-3b0bb8a68f82.png)

**Comment by Kalinkin92** [comment]
https://user-images.githubusercontent.com/40829881/53753900-78ef3c00-3ec3-11e9-9407-3b0bb8a68f82.png

**Comment by Kiku-git** [comment]
![image](https://user-images.githubusercontent.com/25382531/53754709-6bcf4e80-3ebd-11e9-8739-b4a96f4d5c46.png)

**Comment by Sxela** [comment]
![photo_2019-03-04_21-17-49](https://user-images.githubusercontent.com/11751592/53755384-7b539500-3ec7-11e9-8c3e-253f8cf4604d.jpg)

**Comment by backmeupplz** [comment]
Some of the voice messages get recognized again :) around 30% of them, the rest give timeout at the moment

**Comment by Sergey047** [comment]
It's not working!!!

**Comment by backmeupplz** [comment]
Hmm, still ~10% of requests return timeout :(

**Comment by jtliao** [comment]
Apologies for the lapse in service, we were working on improving our infra to support spikes in requests. Things should be back to normal now.

**Comment by vladviolenty** [comment]
API not work Again

**Comment by Sergey047** [comment]
It's not working

**Comment by jtliao** [comment]
Reopening until we fully address this. Sincere apologies about this, we're working to address this.
