### ISSUE TITLE
BUG: Keyword Training

### ISSUE THREAD

**Issue by jcuenod** [wit-ai/wit#1363]
**What is the current behavior?**

While I have only a handful of examples in other areas, my "gender" keyword is not training successfully. I am trying to detect a list of morphological features describing linguistic data (like "feminine plural past tense verb" where gender, number, tense, and part of speech are represented).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

I have added a number of samples but in spite of the fact that all my other attributes are being detected well, I never seem to get results on gender.

**What is the App ID where you are experiencing this issue (if applicable)?**

2487005358039904

**Comment by patapizza** [comment]
Thanks for reporting, we'll look into this.

**Comment by jcuenod** [comment]
Hmm, I notice that the "Insights" section (which normally has a graph) is greyed out and says

> Validate more expressions to get insights for this entity 😁

But to be clear, there are a number of samples validated.

**Comment by patapizza** [comment]
This is now fixed:

<img width="979" alt="screen shot 2019-03-06 at 2 30 31 pm" src="https://user-images.githubusercontent.com/1015208/53918662-6fc5b280-401c-11e9-8bad-05eff50628a4.png">

The insights is another issue. I see the insights for your `intent` entity. You need at least 50 validated samples having the entity, make sure the entity you are looking for has a large enough dataset.

**Comment by jcuenod** [comment]
Thanks very much, I noticed after my previous message that I was missing insights on other entities. Can you explain more about what was wrong?

Thanks.

**Comment by patapizza** [comment]
As mentioned in my previous message and in [this recipe](https://wit.ai/docs/recipes#which-confidence-threshold-should-i-use), you need at least 50 validated samples to get insights.

**Comment by jcuenod** [comment]
Okay so to get the graph I understand I need more samples. What I mean is why was the `gender` entity not training?

**Comment by jtliao** [comment]
Can you clarify what you mean by `gender` is not training?

**Comment by jcuenod** [comment]
@jtliao the problem is fixed. I'm just trying to understand how @patapizza fixed it.

**Comment by jtliao** [comment]
gotcha, there was a bug with subentities in your app, where `gender` was not being detected under `search_term`

**Comment by jcuenod** [comment]
Ahh, thanks! Anything that I could have done differently?

**Comment by patapizza** [comment]
As @jtliao mentioned, it was a bug, nothing wrong on your end. :)
