### ISSUE TITLE
load more questions in inbox

### ISSUE THREAD

**Issue by sophiexr** [wit-ai/wit#1364]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by sophiexr** [comment]
Hi, 

We are working on the project WinFAQV2_gr and we have a lot of questions to validate each day (over a 1000). Is there any way to load more than 10 per page, or to add page numbers so it will be easier for more users to work on validation?

Also,  is there any way to see the remaining number of questions to validate?

thanks

**Comment by sophiexr** [comment]
Hi,

We are working on the project WinFAQV2_gr and we have a lot of questions to validate each day (over a 1000). Is there any way to load more than 10 per page, or to add page numbers so it will be easier for more users to work on validation?

Also, is there any way to see the remaining number of questions to validate?

thanks

**Comment by patapizza** [comment]
Hi @sophiexr,

We have longer term plans to help improving the developer productivity on the Inbox. In the current state of things we aren't able to prioritize this at the moment.
