### ISSUE TITLE
BUG: App Locked on "ongoing" status

### ISSUE THREAD

**Issue by etienne-lelouet** [wit-ai/wit#1365]
Hello,

Our app, "smalltalk" (id: 586ce81f-853b-4af4-931c-0b3cd4e15781, url: https://wit.ai/AlexandreRgx/smalltalk) has been stuck on "ongoing" status for about a week now. It had a history of taking a long time to train, but it is the first time it has taken this long.

Thanks in advance for your help

**Comment by patapizza** [comment]
Hi @etienne-lelouet, I just retrained your app.
