### ISSUE TITLE
BUG: can't export data

### ISSUE THREAD

**Issue by etienne-lelouet** [wit-ai/wit#1366]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
I can't export the app data as zip, it works fine on our other apps, only this one has this issue.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Just click the download button on the settings page, an error message appears saying "Something went wrong while exporting your app 😣. Please try again, or contact us."

**What is the expected behavior?**
Launch the download of a zip file containing the bot data.

**What is the App ID where you are experiencing this issue (if applicable)?**
599b00ae-da68-40d9-b255-43787cf1cd64

**Comment by patapizza** [comment]
Thanks for reporting, we'll look into this.

**Comment by jtliao** [comment]
This should be fixed now, I was able to successfully export your app.

**Comment by eurocharts** [comment]
Hi, 
Cannot export data (same on settings and API)

"Something went wrong while exporting your app"

APP id: 2184728738274083
