### ISSUE TITLE
speech to text

### ISSUE THREAD

**Issue by sandroormeno** [wit-ai/wit#1367]
I'm receiving the follow answer:

{u'code': u'timeout', u'error': u'Timeout, please try again later'}

Sometimes my script is fine but some time is wrong

this is my code:

import requests

import json

def read_audio(WAVE_FILENAME):

with open(WAVE_FILENAME, 'rb') as f:

audio = f.read()

return audio

API_ENDPOINT = 'https://api.wit.ai/speech'

ACCESS_TOKEN = ""

audio = read_audio("test.wav")

headers = {'authorization': 'Bearer ' + ACCESS_TOKEN,

'Content-Type': 'audio/wav'}

resp = requests.post(API_ENDPOINT, headers = headers,
data = audio)

data = json.loads(resp.content)
print(data)

**Comment by Mihonarium** [comment]
Same. It started a few days ago.

**Comment by carloalbertobarbano** [comment]
Same here. Only english seems to work..

**Comment by aforaleka** [comment]
Merging with #1362 to keep track of speech issues
