### ISSUE TITLE
Ongoing status for a couple of week

### ISSUE THREAD

**Issue by iamkenken** [wit-ai/wit#1368]
Here is my app id: 5aa264dd-5d3f-4c46-af80-1a4f94db43f4

**Comment by aforaleka** [comment]
Hi @iamkenken, we noticed that your intent entity has a lot of trait values which we currently don't support well. We are working on a solution that better supports apps like yours, but in the meantime I suggest downsizing your app.

**Comment by 51100807** [comment]
Hi @aforaleka , mine is also constantly training. Can you check it as well? That's my app id: 5add9b65-6776-487f-aec9-cd1c45a2d70e

**Comment by jtliao** [comment]
hi @51100807, sorry about that, your app was stuck-- just triggered a training now, should be done soon
