### ISSUE TITLE
Time Out speech recognition spanish

### ISSUE THREAD

**Issue by RodneyLafaurie** [wit-ai/wit#1369]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by sandroormeno** [comment]
In my case, Today at 10am (lima-peru time) , it don't work( Timeout, please try again later). but today at 1 am it worked fine.

**Comment by aforaleka** [comment]
Merging with #1362 to keep track of speech issues
