### ISSUE TITLE
Seriously? Max audio length is 20 seconds?

### ISSUE THREAD

**Issue by backmeupplz** [wit-ai/wit#1370]
Not cool.

**Comment by backmeupplz** [comment]
Give us at least 50 seconds, as before :3

**Comment by aforaleka** [comment]
Hi @backmeupplz, we have observed that the speech recognition quality declines significantly after 20s. As our top priority is to ensure the service is stable, we are adding the cap until we find other solutions. Thank you for your understanding.

**Comment by backmeupplz** [comment]
Thank you for the response

**Comment by DevanshuGoyal8** [comment]
> Hi @backmeupplz, we have observed that the speech recognition quality declines significantly after 20s. As our top priority is to ensure the service is stable, we are adding the cap until we find other solutions. Thank you for your understanding.

Is there any update on this? or is it still capped to 20s only?

**Comment by kingseaeast** [comment]
Hi @DevanshuGoyal8, it is still the same cap due to above reason.
