### ISSUE TITLE
Upper case keywords not recognized 

### ISSUE THREAD

**Issue by 91ns** [wit-ai/wit#1371]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
Keywords written in upper case are not being recognized.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

![image](https://user-images.githubusercontent.com/25252530/53911050-12525580-405e-11e9-8a47-b7cacb718123.png)

![image](https://user-images.githubusercontent.com/25252530/53911072-1f6f4480-405e-11e9-9d8f-fe0258ebd562.png)

**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**
2035049146549177

**Comment by aforaleka** [comment]
Thanks for reporting @91ns, that is unexpected and we'll look into it. A quick fix for now is to remove one of the synonyms with the same body and different casing-- e.g. for ngl, only keep one of "ngl" or "NGL" and that should work.

**Comment by aforaleka** [comment]
hi @91ns, going forward all keyword synonyms will be lowercased. The specific product_name2 keyword entity should now have all unique lowercase synonyms. If you still experience the issue in other entities, please update them. Thanks!
