### ISSUE TITLE
How to train for negated keywords?

### ISSUE THREAD

**Issue by PAK90** [wit-ai/wit#1373]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question

I'm attempting to train Wit to understand some search queries, e.g. to find books. I have a list of keywords (e.g. author names) which are fine, but some might be negated. For example, `books from 1995 that aren't hardcover`. I can point at `aren't`, give it a `negation` entity, and have `1995` and `hardcover` as their own keywords/entities too. However, the info I really need is that `hardcover` has been negated, and not, say, `1995`. How do I train Wit to recognise this? Or can I extract a syntax tree which will let me see that the `negation` entity is related to `hardcover` and not `1995`?

edit: I found the Role functionality, and I started trying to attach a `neg` role to entities that were negated. It seems to be doing alright, is this the intended way to do it?

**Comment by aforaleka** [comment]
Hi @PAK90! You can post on our Facebook community group to see what other Wit developers are doing in this scenario, but leveraging roles does sound like it'll work in your use case.

**Comment by jcuenod** [comment]
@PAK90 I'm wanting to do something similar to this (something like "turn everything on except x"). Can you point me to the discussion (and, ironically I suppose, I'm not on Facebook).

**Comment by PAK90** [comment]
@jcuenod I didn't actually start a discussion on Facebook, since the Wit AI group seems to be devoid of anyone else asking for help there; the latest post seems to be from 2016. I've been using the role tags for now, tagging entities but adding `:neg` or `:only` depending on context. It seems to be doing alright so far, but I've not done many training phrases yet.

**Comment by patapizza** [comment]
Hi @PAK90,

The Wit.ai group @aforaleka was referring to is https://www.facebook.com/groups/withackers/.
We're happy to help here. It seems like roles are working fine. If you need more help in the future, please use the provided template including your app ID so we can look into it.

Thanks and happy hacking!
