### ISSUE TITLE
App is scheduled to train in 12 hours

### ISSUE THREAD

**Issue by klemensz** [wit-ai/wit#1375]
**Bug / Question**

**What is the current behavior?**

Yesterday our app was trained usually within one minute. Today (= Monday) morning, around 9:45 CET, I made a change and now the “app is scheduled to train at 11.3.2019 21:46:04”. So that's 12 hours from when I made the change.

![Bildschirmfoto 2019-03-11 um 13 44 36](https://user-images.githubusercontent.com/1116517/54124910-eb9c7200-4403-11e9-9e05-f6409c31b6b9.png)

**What is the expected behavior?**

I would expect the training to happen earlier. We have project to finish tomorrow and go live on Wednesday, but we cannot test any changes/fixes today. 

We actually have another app (same feature set but in another language) where the training happens nearly instantly.

**What is the App ID where you are experiencing this issue (if applicable)?**

5902737c-e922-4695-bed3-874f70abb502

**Comment by patapizza** [comment]
Hi @klemensz, I just retrained your app.

**Comment by klemensz** [comment]
Thanks! Is there some rule that defines how often/when an app is trained?

**Comment by jtliao** [comment]
Apps should be retrained as soon as a change is made that requires training, but we've recently been experiencing some problems with our training that is causing this issue.

**Comment by klemensz** [comment]
OK thanks. Getting this now:

![Bildschirmfoto 2019-03-13 um 18 57 06](https://user-images.githubusercontent.com/1116517/54302876-04eb1d00-45c2-11e9-9a4a-3fc9d3b67cdc.png)

**Comment by jtliao** [comment]
Sorry about that, this was related to #1379
