### ISSUE TITLE
Spanish speech recognition not working

### ISSUE THREAD

**Issue by tobeorla** [wit-ai/wit#1376]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?** bug

**What is the current behavior?**

Using an app that has spanish set as language doesn't work for speech to text feature, returns random english phrases.

**What is the expected behavior?**

Support for spanish speech recognition or update https://wit.ai/faq to properly show the supported features of each language.

**What is the App ID where you are experiencing this issue (if applicable)?**
2231384743607802

**Comment by patapizza** [comment]
Thanks for reporting, we're looking into it.

**Comment by aforaleka** [comment]
Hi @tobeorla, are you sending the audio via the HTTP API?

**Comment by tobeorla** [comment]
I'm using the microphone sdk provided in https://github.com/wit-ai/microphone/blob/master/quickstart.md (with token properly set ofc)

**Comment by jtliao** [comment]
We found the bug, will have a fix out soon

**Comment by jtliao** [comment]
This should be fixed now, thanks for raising and your patience here.
