### ISSUE TITLE
Multilayer entities not consistent

### ISSUE THREAD

**Issue by khwstech** [wit-ai/wit#1377]
Bug

So I have two strings which are quite similar but one returns as expected and one does not:
1st: i would like a recommendation for my ford fiesta 3.0 (returns expected response)
{
  "_text": "i would like a recommendation for my ford fiesta 3.0",
  "entities": {
    "vehicle": [
      {
        "confidence": 1,
        "value": "ford",
        "type": "value"
      },
      {
        "confidence": 1,
        "value": "fiesta",
        "type": "value"
      }
    ],
    "number": [
      {
        "confidence": 1,
        "value": 3,
        "type": "value"
      }
    ],
    "intent": [
      {
        "confidence": 0.76252862772482,
        "value": "whichOil"
      }
    ]
  },
  "msg_id": "1ugceEuCQTyMBZy3q"
}

2nd: i would like a recommendation for my ford fiesta 2017 (Returns incorrect)
{
  "_text": "i would like a recommendation for my ford fiesta 2017",
  "entities": {
    "vehicle": [
      {
        "confidence": 1,
        "value": "ford",
        "type": "value"
      },
      {
        "confidence": 1,
        "value": "fiesta",
        "type": "value"
      }
    ],
    "number": [
      {
        "confidence": 1,
        "value": 2017,
        "type": "value"
      }
    ]
  },
  "msg_id": "113kTbXepK9yd0Kg1"
}

The second response is missing:
    "intent": [
      {
        "confidence": 0.76252862772482,
        "value": "whichOil"
      }
    ]

Also:
"i would like a recommendation for my ford fiesta" works as expected. Has all the required properties except for wit/number which is what i expect

App Id:
59945ded-a991-458b-9458-1ea934a685af

**Comment by jtliao** [comment]
sorry for the delay, is this still an issue? i just tried "i would like a recommendation for my ford fiesta 2017" and see the `whichOil` intent showing up

**Comment by khwstech** [comment]
Hi there,
Yes its  now working. THanks for that

**Comment by aforaleka** [comment]
Awesome -- closing the issue
