### ISSUE TITLE
Can't access

### ISSUE THREAD

**Issue by erudyk** [wit-ai/wit#1378]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
BUG
**What is the current behavior?**
Can't enter to any agent on my account - the agent page doesn't load. All API requests get error.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
I want everything to work as before.
**What is the App ID where you are experiencing this issue (if applicable)?**
Any APP in my account.

**Comment by hsilvester** [comment]
I'm having similar issues logging into the system. Neither my Facebook nor Github logins are working, so I can't access any apps.

Another user also reported issues validating expressions earlier today in one of our shared apps. Just thought I'd mention that if it's tied to this particular issue.

**Comment by ajlohr** [comment]
I cannot login via Github either. I see the following errors after I attempt to login

```
POST https://api.wit.ai/me/github_signin 500 (Internal Server Error)
 [login] Failed to connect to Github undefined
```

with response
```
{
  "error" : "Something went wrong. We've been notified.",
  "code" : "wit"
}
```

**Comment by erudyk** [comment]
Partially resolved here. I can access my agents, but some requests get incorrect answers. Things that was classified correctly before now get wrong answers...

**Comment by thedeadkoiclub** [comment]
Having trouble accessing existing projects and cannot create new projects. Server responds with 500 at https://api.wit.ai/sync?verbose=true.

**Comment by jtliao** [comment]
tracking in #1379
