### ISSUE TITLE
I Need To Create Intent Programmatically

### ISSUE THREAD

**Issue by eyalgi11** [wit-ai/wit#1380]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Ask a Question
**What is the current behavior?**
It's Possible To Create Intent In The Web Console
**What is the expected behavior?**
I Want Programmatically Make Intent
I Have Searched The HTTP API Reference But Not Found
**What is the App ID where you are experiencing this issue (if applicable)?**
2654140397992492

**Comment by jtliao** [comment]
Hi, see our documentation on [POST /entities](https://wit.ai/docs/http/20170307#post__entities_link) to create intents (just a "trait" entity). Below is an example query:

```
curl -XPOST 'https://api.wit.ai/entities' \
  -H "Authorization: Bearer $TOKEN" \
  -H "Content-Type: application/json" \
  -d '{"id":"entity_name", "lookups":["trait"]}'
```
