### ISSUE TITLE
Wit doesn't identify specific word and splitting the word - BUG

### ISSUE THREAD

**Issue by umasudheesh** [wit-ai/wit#1382]
![](https://lh3.googleusercontent.com/-lM1NS84dPUs/XIuRNT-wKCI/AAAAAAAAATI/ijeT9LSN6ggPPog0zF8HW3GKIS4LiHAtgCK8BGAs/s0/2019-03-15.png)

The above example is for you reference.

Wit doesn't identify **don't** term. It reads the term "**don't**" to "**do**" and accepts it as a positive reply entity. 
But **don't** word is actually mapped in negative reply entity

My question is - 
**Why is it splitting the word?**

**Comment by jtliao** [comment]
this is definitely not expected. thanks for raising, we'll look into this
