### ISSUE TITLE
[Portuguese Wit Understanding] Error on Datetime understanding

### ISSUE THREAD

**Issue by rada-a-gast** [wit-ai/wit#1385]
So, when you type "day 10 at 18:00 hours" in portuguese ("dia 10 às 18:00 horas"), the output for "wit/datetime" just ignore the day and set only the hours. But if you type "at day 10 at 18:00 hours" in portuguese ("no dia 10 às 18:00 horas") he just send the right output for "wit/datetime".

**Comment by jtliao** [comment]
hey @rada-a-gast, wit/datetime is powered by Duckling-- can you open a Github issue [here instead](https://github.com/facebook/duckling/issues), so we can get the right person to help you out?
