### ISSUE TITLE
Unable to login (facebook account disabled)

### ISSUE THREAD

**Issue by sharma-hitesh** [wit-ai/wit#1386]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Ask a question (Actually need help)
**What is the current behavior?**
I am not able to login via facebook
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
No It's not a bug. The facebook account I used to sign-up with wit, has been disabled, so I am not able to login to facebook and hence not able to login to wit
**What is the expected behavior?**
I am expecting, if I tell me email ID ( that I used to signup via facebook), then wit.ai can help me log-in to wit console with needing do a fb-connect
**What is the App ID where you are experiencing this issue (if applicable)?**
Since I am not able to login to wit console I don't know the App-id that I am accessing with API
(The API s working fine though, using the access token)

**Comment by jtliao** [comment]
We do require a connection to either FB or Github to log in, so you'll need to pick an account you want to attach your Wit.ai account to. After deciding, can you e-mail us at help@wit.ai so we can help you privately?

**Comment by sharma-hitesh** [comment]
Hi
I have reached out on help@wit.ai. 
Waiting for response ...

**Comment by jtliao** [comment]
Sorry about that, responded.
