### ISSUE TITLE
None of the trained phrases is recognized

### ISSUE THREAD

**Issue by rusell** [wit-ai/wit#1387]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug

**What is the current behavior?**
Once new training occurs, NLP does not recognize any of the trained phrases. A problem started aprox. at 17:00 18/03/2019 CET.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Just ad a new expression, wait for training to happen and then none of the previously trained phrases is recognized.

**What is the expected behavior?**
Phrases are trained and added to the previous data set. Once posted to wit.ai, assigned value (intent) is returned.

**What is the App ID where you are experiencing this issue (if applicable)?**
Few of them at the moment, here is one - 5c5370fef168560f6267f2c4

**Comment by 91ns** [comment]
Same here 
app id : 2084463711607674

**Comment by ssitbiz** [comment]
yup Having the same issue
app id: 1927013864087802

**Comment by vnalex** [comment]
Same here.. need help.
app id: 2096249480457187

**Comment by mjain1990** [comment]
We are also experiencing the same problem past few hours.

**Comment by b-tix** [comment]
app id: 2115985458480186
Since yesterday we realize a different response behavior. Some phrases that have been trained before are not recognized anymore. e. g. "finanzierung" should bring up ..._vgv and ..._risiko.

**Comment by MutatedBread** [comment]
app id: 2108187609262747
Just added a new phase to an entity. What was previously recognized is no longer now.

**Comment by serdalbayram** [comment]
the same problem in my apps

**Comment by bartklin** [comment]
same here, app id: 2462683460472465

**Comment by asfyra** [comment]
same here app id: 5b1e505b-0e5f-484a-9e44-20d7c4ee12d1

**Comment by GaganTM** [comment]
Same problem in my app 
app id  : 2341059599251771

**Comment by lynnfachetaet** [comment]
Having the same problem too. App ID's 
5b2c4f04-eb80-46c2-8ed9-b693736bbcad
5b350cc2-f26d-4c7b-8f7b-706090b17c9c

**Comment by jlariza** [comment]
Same here:

 App ID: 1813892522042357

We have been working with the model for several months now and it was working fine; and suddenly it stopped working yesterday; it does not recognize the phrases and the intents are not identified.

Ty

**Comment by serdalbayram** [comment]
Any progress or feedback about this issue ?

**Comment by ChrisMacAET** [comment]
Also experiencing this issue:
App ID: 2056647174448351.

**Comment by RobSederAET** [comment]
Same issue for this one too:

> App ID: 2439958889411567

Has anyone heard back? We've been down since yesterday!

**Comment by timgreynolds** [comment]
I am seeing the same issue.

AppId: 5b6073ae-6bc1-4dea-bff4-c64790ea1141

**Comment by ram-botworxai** [comment]
I have a bunch of wit apps -> they all seem to be unable to recognize non-builtins and if I try to train they get stuck in training. I guess you are well aware of this based on the stream of 'same here's above.

**Comment by jennygrahamjones** [comment]
App ID: 2037325916356319

None of my 'intent' values are returning. I can see them tagged to historical samples and inputs, but new inputs don't register the 'intent' that they previously would have.

**Comment by femioladeji** [comment]
Experiencing the same issue here, appid is **2050679248326545**

**Comment by patapizza** [comment]
Thanks for reporting, looking into it.

**Comment by redoyh7** [comment]
Sending an audio sample from unity but nothing showing inside the expression or inbox tab. Clicking "train some more" also not working. This is happening to me right now. I send audio from Unity but in "Validate Audio" never appears. What should I do? Please help...

**Comment by patapizza** [comment]
This is now working. I'm manually retraining all app ids above. Sorry for the inconvenience, we'll make sure this won't happen again.

**Comment by patapizza** [comment]
For the remaining apps, please validate one sample to kick start a new training. Thanks.

**Comment by jennygrahamjones** [comment]
Thanks for the quick fix @patapizza :)

**Comment by lynnfachetaet** [comment]
Thank you very much for your help @patapizza !

**Comment by GaganTM** [comment]
Thanks for the fixing issue @patapizza :)

**Comment by asfyra** [comment]
Thank you @patapizza

**Comment by vnalex** [comment]
Thankss @patapizza
