### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by w-ali-amer** [wit-ai/wit#1388]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
possibly a bug, definitely a question
**What is the current behavior?**
my program was working just fine till it started giving me a 400 error.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
my code is a little messy, but earlier iterations didn't have a problem. The post request possibly exceeds 256 characters, but it did earlier too when the program worked just fine. I think it's possible it could be a server side error.
**What is the expected behavior?**
the expected behaviour was to post messages to messenger and get messages from there.
**What is the App ID where you are experiencing this issue (if applicable)?**
1863342383771407

**Comment by tobeorla** [comment]
https://github.com/wit-ai/wit/issues/1362 may be related

**Comment by w-ali-amer** [comment]
I don’t think so because I’m not using the speech api. I’m trying to set up a bot using messenger and i get a wit.error. I’m using code that was given as an example for a messenger bot using python, except i changed the framework to flask
