### ISSUE TITLE
Add range to wit/number

### ISSUE THREAD

**Issue by PAK90** [wit-ai/wit#1389]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Feature

**What is the current behavior?**
Numbers can't have ranges.

**What is the expected behavior?**
Numbers should have ranges, like `wit/amount_of_money`

I want to have a number entity, for example from the sentence `more than 90 seconds`. This currently just picks out 90 as a number, for which I can't declare a range. It'd be good to have it behave like `wit/amount_of_money` does, where you can do `less than $5` and it picks up the range and currency.

**Comment by patapizza** [comment]
Hi @PAK90, thanks for the suggestion.
As `wit/number` is powered by Duckling, I opened https://github.com/facebook/duckling/issues/352 to track changes there.
