### ISSUE TITLE
Automatic validation

### ISSUE THREAD

**Issue by VirutalAgent** [wit-ai/wit#139]
Is it possible to train Wit.ai with a batch file containing intent examples that we know are valid so we don't have to validate manually?

**Comment by mikekhristo** [comment]
Checking in on this - thanks!

**Comment by martinraison** [comment]
Hi, apologies for the lack of updates. We haven't had a chance to work on this recently but the validation API is still on our roadmap. We don't have a time estimate yet, though, but we'll keep you updated.

**Comment by l5t** [comment]
You can do this now via the API. Example here: https://github.com/wit-ai/wit-api-only-tutorial#train-with-existing-data
