### ISSUE TITLE
Wit.ai cant identify intent created inside entity  

### ISSUE THREAD

**Issue by GaganTM** [wit-ai/wit#1390]
We have created some intent inside entity but  when we test sample text with wit.ai is not able to recognize it

**Comment by hsilvester** [comment]
I believe I'm experiencing a similar problem with one of my apps. One of the apps I built has stopped picking up an intent altogether. It's still picking up entities I created for keyword recognition, but the intent isn't matching at all.

**Comment by jtliao** [comment]
it was related to #1387, apologies
