### ISSUE TITLE
Are Wit.ai Apps deleting by itself?

### ISSUE THREAD

**Issue by supergianlu** [wit-ai/wit#1391]
Hi, I use wit.ai in a application for speech recognition with about ten apps (one per language). For a few days when I try to create an app, it changes language by itlsef or it erases itself.  I tried to create another account but I have the same problem.
Have someone else got this problem? How can I solve it? What is it caused by?
Thanks.

**Comment by patapizza** [comment]
Hi @supergianlu,

Can you share the app ids of the ones whose language changed? And which ones are missing?

Thanks

**Comment by supergianlu** [comment]
Sure, this app id (UDTKKJCP7XTHKWHZYAJWBHE3S5U466WZ) changes continuously
language. Now this account has only that app. Old app ids deleted by
themself are: R24SXYNNKIJVHBBGURVULXFM5QQOY4KO,
VXDG3NZ2A446YVFSYBSTY74AY2RB7POV,
MEU5XMZ5FCV2G56BWSX5WTSVI4VQ3HAP, ZORB3QF6MGSDO34QMXV3VIHBT2D5XAB3, etc...
I think that a wit account must have at least one app, so this is why I
have only one app otherwise it would also be canceled.
This happens for all accounts I try to use. I removed the application that
used wit from play store, it's old id was
com.supergianlu.audiototextforwhatsapp.
I thought was a hacker that that got to the apps ids by reverse engineering
but I'm sure it's not like that: I've created one app id that I didn't add
in the application but that too was deleted.
Thank you.

Il giorno lun 25 mar 2019 alle ore 18:49 Julien Odent <
notifications@github.com> ha scritto:

**Comment by aforaleka** [comment]
Hi @supergianlu, sorry that's happening. That's unexpected and we will look into it. To help with our investigation, can you give us your username for the other account you've created which still experiences the issue?

**Comment by supergianlu** [comment]
Sure, grossigianluca22 and suuuuuuuper (the last one created exclusively
for testing).

Il mar 26 mar 2019, 22:24 Aleka C <notifications@github.com> ha scritto:

**Comment by jtliao** [comment]
hey @supergianlu, we did some investigating, and see logs of the PUT /apps/:id and DELETE /apps/:id API endpoints being hit by your users. If this isn't you, I'd recommend resetting your tokens/password to address this.
