### ISSUE TITLE
Ability to increase the /sample 200/minute limit

### ISSUE THREAD

**Issue by sebastianarena** [wit-ai/wit#1392]
Would it be possible, through some sort of approval process, to be able to increase the 200/minute limit to call /samples? Same thing that AWS does when you reach a limit that you are using fairly but need some more?

We basically have a lot of accounts to handle, and most of them are now bulk importing information to us to train better. We have a queue in process to send the samples respecting the limit, however that limits us a lot on how much we can train in a given hour.

Would you guys also consider a bulk import of some sort that we can send to you zipped?

Thanks very much!

**Comment by patapizza** [comment]
Hi @sebastianarena,

Let's chat through intercom on how to better support your use case.

Thanks!

**Comment by aforaleka** [comment]
Seems like there's a conversation going on intercom already, our dev will review your use case and talk there

**Comment by sebastianarena** [comment]
@aforaleka no one has contacted me about this... and still don't know to which conversation you are referring to on intercom. Would love it if I could talk to someone over email at least. This is a pressing issue on our side.

**Comment by jtliao** [comment]
Hi @sebastianarena, apologies about this, there was some confusion on our side. Please e-mail us at `help@wit.ai` about your use case and we can discuss it.

**Comment by sebastianarena** [comment]
@jtliao thank you! just did
