### ISSUE TITLE
while converting audio/video getting FileNotFoundException

### ISSUE THREAD

**Issue by Ahsan721** [wit-ai/wit#1395]
****Do** you want to request a *feature*, report a *bug*, or ask a *question* about wit?*
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by jtliao** [comment]
think this is the wrong place :)

**Comment by Ahsan721** [comment]
not understanding your point.. is this library issue?

**Comment by Ahsan721** [comment]
please explain

**Comment by patapizza** [comment]
Hi @Ahsan721, are you using a specific client SDK? This repo is for the wit.ai service.
