### ISSUE TITLE
Specifying conditions for entities in specific Intents

### ISSUE THREAD

**Issue by praharshbhatt** [wit-ai/wit#1396]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
feature

**What is the current behavior?**
The only issue I faced with Wit from the start is that all the pre-defined entities i've used in my app have caused an issue, this is how:
I have wit/reminder, wit/searchquery and others like wit/contacts
Now for queries like "Call my wife" or "Call xyz" or "Send a text to xyz", Wit gets the intents correct, the only issue is "wit/reminder" or "wit/searchquery" gets assigned to the whole phrase, even after training numerous times, to the exact same query.

**What is the expected behavior?**
I propose that if Wit team rolls out a feature where developers can assign a condition to all the intents, the problem will be solved.
For example in the above case, I would like to specify that the "Call" and "Text" intents, could not have entities "Wit/reminder" and "Wit/searchquery".

So all the queries in "Call" and "Text" will be limited to specific entities, which will make the accuracy higher, since the entities that don't belong to the specific intent will never be checked for.

**What is the App ID where you are experiencing this issue (if applicable)?**
5af134f9-929b-4f9c-b496-1eed315571e2

I would love to get more opinions if this can be possible.

**Comment by patapizza** [comment]
Hi @praharshbhatt,

This is a great idea. We're already tracking this as https://github.com/wit-ai/wit/issues/1070. We've implemented a working prototype for this in the past, but we still need to prioritize the project to productionize it.
In the meantime, you can try to add a role to `wit/contact` to see if it helps prioritizing it for calling/messaging intents.
