### ISSUE TITLE
Repeated messages breaking my app.

### ISSUE THREAD

**Issue by gazehyena** [wit-ai/wit#1397]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
My Wit.ai app only recognizes Wit.ai's own entities after accidentally sending a huge amount of repeated messages from my javascript app using HTTP requests. Now my app refuses to recognize any of my own intents. I exported the data from the broken app and imported it into a new app, and it seems to work just fine with the same data.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I have a pretty simple HTML + javascript web application with a text box for user defined text and a button to send the text to Wit. I had a bug in my javascript that caused my javascript app to repeatedly sent the message back to Wit.ai each time Wit.ai replied. 

This happened several times while I was troubleshooting the bug on my side. After fixing the bug Wit.ai no longer recognizes intents definded before or after the bug appeared. I even tried to remove all the messages from Wit.ai inbox sent by the bug on my javascript, and I cleared even the proper samples from my app, but my Wit.ai app is still broken.

**What is the expected behavior?**
Repeated messages should not stop the app from recognizing my intents.

**What is the App ID where you are experiencing this issue (if applicable)?**
My App ID for the broken app: 
2511933215514781

**Comment by jtliao** [comment]
Sorry about that, there were issues with intents (#1387). This should be fixed now.
