### ISSUE TITLE
PUT /entities/intent behaviour between small number of expressions and large number of expressions

### ISSUE THREAD

**Issue by kumangxxx** [wit-ai/wit#1398]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question

**What is the current behavior?**
```PUT /entities/intent``` sometimes train the app sometimes not. If i call this api using small number of expression, the app will be trained, and expressions will be updated. but if call this using large number of expressions, its not, and no expressions is saved. 

```GET /entities/intent``` will return

```
{ "value": "first intent", "expressions": [] }
```

eventho i call the api using ```PUT /entities/intent``` with this payload:

```
{ "value": "first intent", "expressions": [ "long expression 1", "expression 2", "etc " ] }
```

**What is the expected behavior?**
consistency, 
updating using small number of expression, will save the expressions and will train the app.
updating using large number of expressions, will not save the expressions and will not train the app

can you confirm this ?

from another thread, i get that i need to use ```/samples``` to update expression since ```intent``` has ```trait``` lookup, yes ?

but its limited to 200 expressions / minute. sometimes we import a large amount of expressions, how do i reach u guys to talk about extending the limit ? 

**What is the App ID where you are experiencing this issue (if applicable)?**
-

**Comment by patapizza** [comment]
Hi @kumangxxx,

From the [docs](https://wit.ai/docs/http):
> You can update values for keyword entities. For traits or free-text entities, use POST /samples

Note that `PUT /entities/:id` resets the values, and doesn't add new ones.
Let's chat more about your use case through intercom.
