### ISSUE TITLE
Inbox does not load all past messages.

### ISSUE THREAD

**Issue by mcspenzer** [wit-ai/wit#1399]
I would like to report a bug regarding the Inbox module of Wit

Currently, the inbox does not display all past messages. I discovered it as I was trying to clear my inbox of past messages. I repeatedly validated correct entity recognitions and trashed the incorrect ones. As I was done, or so I thought, I clicked the refresh button out of impulse and my inbox became immediately flooded with the past messages that I still recognize.

And i suspect that there's a 10 messages limit that is imposed on the inbox as I can only count 10 when I click refresh after cleaning the displayed messages

App IDs:
2828889323803130
2279326185474103
1822435484550997

**Comment by patapizza** [comment]
Hi @mcspenzer, indeed the inbox currently loads 10 samples at a time.
Tracked @ https://github.com/wit-ai/wit/issues/1364
