### ISSUE TITLE
Running on a local server/machine/embedding.

### ISSUE THREAD

**Issue by vantreeseba** [wit-ai/wit#14]
I'm not sure about your plans for this, but it would be nice if you could do this with a community license (i.e. to make the queries faster) by somehow running a local copy that only "caches" the results, and still shared the actual expressions and intents back to the live server. 

So pretty much a local "server" but it passes through all data so that it is shared.

This would be really great for embedding into something like a voice control mechanism for xbmc.

**Comment by steffensenthomas** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by darkhexagon** [comment]
https://camo.githubusercontent.com/a2840914d539225aaf8d395397d8dbc488a0740d/68747470733a2f2f6173736574732d63646e2e6769746875622e636f6d2f696d616765732f69636f6e732f656d6f6a692f756e69636f64652f31663434642e706e67

**Comment by darkhexagon** [comment]
![68747470733a2f2f6173736574732d63646e2e6769746875622e636f6d2f696d616765732f69636f6e732f656d6f6a692f756e69636f64652f31663434642e706e67](https://cloud.githubusercontent.com/assets/6187115/5693149/beebd64e-9910-11e4-8436-128fc6254903.png)

**Comment by Zetaphor** [comment]
:+1:

**Comment by 0xakhil** [comment]
any updates?

**Comment by sigmar** [comment]
![1f44d](https://cloud.githubusercontent.com/assets/4113117/6072201/42707248-ad9f-11e4-800c-f82a5a013c28.png)

**Comment by aripatrick** [comment]
Would it be possible to get an update on this? While the team may not have the functionality completed, it would be nice to have a better understanding of what the solution may look like.

**Comment by Glavin001** [comment]
I'd love to be able to have an offline / local copy of Wit API Server! That would be very valuable when making outgoing Internet requests is not an option. Thank you!

**Comment by tedstriker** [comment]
My guess is, there won't be an offline version since facebook bought the company. A friendly, "we're still on it" or "nope, we're not going to release it anymore" would have been kind.
I think wit could have become a key part in many IoTish solutions, but... money.

**Comment by Glavin001** [comment]
I really hope more of the core features of Wit could be made 1) open source and 2) offline / installed locally. I would love to contribute to the production of Wit. 
Hopefully this is not the case, @tedstriker.

**Comment by ar7hur** [comment]
Hey @tedstriker @Glavin001 sorry for the long silence on this topic. We are currently focusing on dialog management, and **we don't have offline on our roadmap at the moment**. As you may know we are 100% Clojure, which enables us to iterate very quickly in our research toward dialog. But Clojure/JVM + the many services we use in the backend make it harder to release an embeddable runtime.

I know you'll be disappointed but it would be hard to focus on these two things at once. Also, we are not ready to open source everything yet, but that's an open option for the future. I apologize for the lack of precise commitments here, but we are really still evaluating all these options.

**Comment by Glavin001** [comment]
Thank you for your reply and keeping us in the loop of Wit's progress, @ar7hur.
I look forward to a more open-source / portable Wit in the possible future, however understand it will take time to get there.

---

Is there currently a place where we can observe ongoing roadmap for Wit?

**Comment by ar7hur** [comment]
@Glavin001 not yet but that's a good suggestion! At very high level, that's mostly about Github-like collaboration (forking intents, merging, etc.) and dialog (vs. simple intent extraction as Wit does today). Stay tuned we'll announce more shortly!

**Comment by tedstriker** [comment]
Hey @ar7hur, thank's for quick response! I'm curious about the things to come.
Good luck & kudos for what you have achieved so far.

**Comment by ar7hur** [comment]
@tedstriker thanks!

**Comment by harveyslash** [comment]
so is it any good to wait for a WIT version thats offline?  I am working on a project where internet connection is very slow. Is it any point to wait for an offline Wit by the end of 2015 since facebook has acquired Wit?

**Comment by zitkkyz** [comment]
I love the idea of having it as a personal server too. Let it be just to shoot confidential information, Open-source would be amazing but even if it's a closed source server, i'd be more than happy!

**Comment by kundusandeepan** [comment]
Loved the idea.. and this is what I need :+1: :)

**Comment by typeofgraphic** [comment]
any updates on running an offline version of WIT?

**Comment by blandinw** [comment]
So sorry for the late reply and lack of updates. 😔
Our priorities have changed since the move to FB and the release of Bot Engine.
Also, we're now using AI techniques that cannot realistically work in an embedded fashion.
This is no longer on the roadmap unfortunately.
We have other cool things in the pipe though, stay tuned. 🙃

Closing now.
