### ISSUE TITLE
[Feature request] Speech-to-text: Timestamp for each word

### ISSUE THREAD

**Issue by isaiash** [wit-ai/wit#1400]
Hi guys,

I'm trying to generate subtitles for a video using your API. To simulate google behavior I need to know the time(ms) when the word is "heard". In the docs I have not seen this possible. It would be a nice feature to add.

**Comment by patapizza** [comment]
Thanks for the suggestion @isaiash, I'll bring it up to the team.

**Comment by jtliao** [comment]
We won't be able to support this feature, apologies for the inconvenience.
