### ISSUE TITLE
Long text phrases are being classified wrongly 

### ISSUE THREAD

**Issue by 91ns** [wit-ai/wit#1401]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
Long phrases analyzed through the API endpoint are classified wrongly. On wit UI they are not processed though, this makes it difficult to detect the problem. 

The expressions being referred to are not meant to be processed because they are long and are in json format, but because they are returning wrong classification I had to train them as intent with value null.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Please check the samples under entity : intent, value : null as these expressions contain personal data.
**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**
2035049146549177

**Comment by patapizza** [comment]
Hi @91ns,

Thanks for the feedback. Providing an specific value for out-of-scope examples to ignore is the way to go. You can actually validate these samples without the `intent` entity and the classifier will take them as negative samples. More info: https://wit.ai/docs/recipes#manage-negative-samples
