### ISSUE TITLE
Download training data

### ISSUE THREAD

**Issue by shoumikgoswami** [wit-ai/wit#1403]
Currently I am using Wit API for my chatbot. I have created a number of entities and trained the bot online. Is it possible to get a dump of the training data which I have used since inception to train the app online? I want a dump of the training samples and corresponding intent classes.

**Comment by jennygrahamjones** [comment]
Not sure if this is what you're after, but using the HTTP API you can

- can get up to 10,000 of the samples you've input, along with the corresponding intents and entities the bot assigned to them: https://wit.ai/docs/http/20170307#get__samples_link
- download all of your app data: https://wit.ai/docs/http/20170307#get__export_link

**Comment by patapizza** [comment]
Thanks @jennygrahamjones for providing the right pointers!
