### ISSUE TITLE
I dont want to see my messages in Inbox for already trained mature bot

### ISSUE THREAD

**Issue by serdalbayram** [wit-ai/wit#1406]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
questian
**What is the current behavior?**
All messages sent to Inbox
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
For some bots (trained for a long time ) I dont want to see all user messages in the inbox.
Is there any flag during API call, not sent to Inbox? 
**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by aforaleka** [comment]
Hi @serdalbayram, if you don't want the message logged or sent to inbox, you can set the junk flag to true. However, **the message will also not appear in Logs**, which may not be desirable.

For example:
```
curl \
 -H 'Authorization: Bearer $TOKEN' \
 'https://api.wit.ai/message?v=20190326&junk=true&q=dont%20send%20to%20inbox'
```

Hope that helps!

**Comment by serdalbayram** [comment]
Thanks
