### ISSUE TITLE
[API] Speech recognition : high latency

### ISSUE THREAD

**Issue by ImForgi** [wit-ai/wit#1408]
Hi everyone,

First I am new with this API, therefore I do not really know what I should expect from the service.
I opened this issue because when trying the service for my app, I faces high latency when requesting speech recognition from the API (/speech).

The delay for the API to respond is around 5000 ms when launching my app on my localhost and around 2500 ms when launching from production server (an OVH vm). This first point is strange because I personnally have a good connection, but whatever the only thing I care is the latency from production server which seems to me really high for my needs.

I send to the API a ~90ko wav file, which is sent pretty fast. The huge latency is obviously on API's side.

I would like to know if it is expected latency or not ? (since it is a free service, I do not really know what I should expect)

Thanks for your help, have a nice day. 

**What is the App ID where you are experiencing this issue (if applicable)?**
2546640725363591

**Comment by aforaleka** [comment]
Hi @ImForgi, we apologize for the higher latency this past week. We are shipping a bunch of improvements in this coming month and the service should be much more stable then.
