### ISSUE TITLE
phone number transcription vs wit/phone_number

### ISSUE THREAD

**Issue by abv** [wit-ai/wit#1409]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

bug / question

**What is the current behavior?**

when wit.ai transcribes a spoken phone number string, it returns the phone number as a text string. for example the transcription might look like: "please call me back at seven one eight five five five one two one two". this, in and of itself, is not a problem. however, the wit/phone_number entity does not recognize this as a phone number. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

post audio to the speech endpoint that contains a phone number

**What is the expected behavior?**

i would either expect phone numbers to be transcribed like "718-555-1212" *OR* wit/phone_number entity to recognize phone numbers formatted like "please call me back at seven one eight five five five one two one two".

for the time being i'm using https://www.npmjs.com/package/words-to-numbers to take the transcribed text, reformat it, and re-post the number-ified transcription back into wit. this works, but means i'm querying wit twice, and feels like something wit should handle natively.

**Comment by aforaleka** [comment]
Hi @abv, thanks for reporting this! I'll discuss your suggestions with the team.

**Comment by aforaleka** [comment]
I've forwarded the issue to the Duckling repo, let's keep track of the request there @abv :)

**Comment by abv** [comment]
Running into similar issues w/ a date of birth voice prompt as well. Seems to handle day and month ok, but not year.

```
{
	"_text": "august twenty third nineteen eighty",
	"entities": {
		"datetime": [{
			"confidence": 1,
			"values": [{
				"value": "2019-08-23T00:00:00.000-04:00",
				"grain": "day",
				"type": "value"
			}, {
				"value": "2020-08-23T00:00:00.000-04:00",
				"grain": "day",
				"type": "value"
			}, {
				"value": "2021-08-23T00:00:00.000-04:00",
				"grain": "day",
				"type": "value"
			}],
			"value": "2019-08-23T00:00:00.000-04:00",
			"grain": "day",
			"type": "value"
		}]
	},
	"msg_id": "1LqImkjGlBD7V7rXO"
}
```

**Comment by chessai** [comment]
Re-opening as the appropriate spot for this issue

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
