### ISSUE TITLE
POST /speech return 408 Timeout

### ISSUE THREAD

**Issue by yab0b1k** [wit-ai/wit#1410]
Hello, I sending small (3-15 sec) audio files to /speech and receiving 408 timeout. But if I increase request timeout to 90 sec (30 sec is default), I has 408 error again.
After stop sending with some pause (30 minutes or bigger), I receiving correct response some time (30 minutes or less) and receive error again
Audio is a mono channel wav file with russian voice.
What is problem with recognize service?

**Comment by jtliao** [comment]
Merging with #1412
