### ISSUE TITLE
Response Time Issue From South East Asia

### ISSUE THREAD

**Issue by pamenta** [wit-ai/wit#1411]
Hi There.. 

I have a problem with response Issue from api.wit.ai server from our server in Singapore. it takes time about 8-10 Second to wit ai api response the request. when we move our server to US, the response time was increasing a lot, but it also impact to our users accessing our platform will be slow if we move the server to US because our users 100% from Indonesia.

I tested ping wit ai ip from our server it takes around 250ms, I guess that is the reasons why the response time from api.wit.ai takes time to response. 

is there anyway that I can solve the response time Issue.?? with server in Singapore.?? 
Thank you so much..

**Comment by limxuanhui** [comment]
Hi, I'm so glad to find someone facing response time issue in Singapore as well. I followed the basic example of initialization:
>>>from wit import Wit
>>>client = Wit(access_token='myserveraccesstoken') #my app is private
>>>client.message('mymessage')

And I got connectionError. Do you know how to resolve this?

**Comment by jtliao** [comment]
@pamenta can you give an example of how you are querying Wit.ai?

**Comment by pamenta** [comment]
@jtliao Thank you.. 

so here are the responses time we got from different server location.
I tested in both server one in  US located in New York, and one in Singapore that we are use right now.

Result : 

US Server :
![us server](https://user-images.githubusercontent.com/9650622/55600176-1f5d8400-5785-11e9-8ef4-105037c6114d.png)
its < 1

Singapore Server :
![singapore server](https://user-images.githubusercontent.com/9650622/55600241-6481b600-5785-11e9-84f3-6c1ff9b6edfe.png)
its unstable and fluctuates. 

here is the code : 
`
# -*- coding: utf-8 -*-

import requests
import unittest
import json
import uuid
import time
import datetime
import wave
import sys

def makeRequest(wav_path):
    f = wave.open(wav_path, 'rb')
    data = f.readframes(64000)
    f.close()
    return data

def main():

    if len(sys.argv)==2:
        wav_path = sys.argv[1]
    else:
        wav_path = 'test.wav'


    session = requests.Session()
    _url = 'https://api.wit.ai/speech?v=20160516'
    _headers = {}
    _headers['Content-Type'] = 'audio/raw; encoding=signed-integer;bits=16;rate=16000;endian=little' 
    _headers['Authorization'] = 'Bearer <MY ACCESS TOKEN>'
  
    
    _post_data = makeRequest(wav_path) 
    t0 = time.time()

    response = session.post(_url, headers=_headers, data=_post_data, timeout=32, proxies=None, verify=True)
    t1 = time.time()
    print ('Delta T:', t1-t0)
    
    if response.status_code == 200:
        print ("200 OK")
        json = response.json()
        print ("json: ", json)

        pass

    print ("status code: ", response.status_code)

    
if __name__ == "__main__":
    main()

`

as I mentioned that our customer will be in Indonesia, so we will use Singapore server to get a best connection to our end customer to our main server. how can I solve this Issue..??

**Comment by pamenta** [comment]
when I ping from New York server to api.wit.ai time is around 6ms, and when I ping api.wit.ai from Singapore server its around 230ms

**Comment by jtliao** [comment]
thanks for the info. we'll look into what is going wrong

**Comment by jtliao** [comment]
hi @pamenta, apologies for the delay, but after doing some more investigating I don't think we'll able to address this issue, as it's simply an issue of distance to server
