### ISSUE TITLE
Speech Recognition API: Long reponse times & Timeouts still persist

### ISSUE THREAD

**Issue by solyarisoftware** [wit-ai/wit#1412]
Hi there, 
I'm a ITD-CNR researcher and I'm user of Wit.ai speech recognition API, that we are using as backend for an experimental chatbot in education realms to support Italian language learning by foreigners/immigrants. I'm very happy regarding recognition rates, but I'm worried for long response times.

The related issue: https://github.com/wit-ai/wit/issues/1362 have been opened and closed a lot of times.

I decided to open this new issue now, because the timeout percentage yesterday (1st April in the afternoon/night) have been not-insignificant for many hours. The problem is contained now, nevertheless I noticed in general a big variance in response times last days, from a minimum of 1300 msecs (my test is the single word "gatto" wav) to also more than 10 seconds. 

I share here my simple bash script test, 
Trying 10 GET requests I got these response times: 

`Elapsed times (msec)      : 33734 1333 1278 1301 1341 1317 1348 1322 1353 1316`

The first request taked ~34 seconds! (btw weird: without timeout)
and in general I got ~1300 msec

My questions:
1) There any Wit.ai plans to solve definitively the timeout/too long response times issue?
If the issue is due to peak requests, do you considered to insert a token-related "requests limiter" ?

2) Generally speaking the response time of  ~1300 msec for a single word, is what you foresee OK your side? My side, using the speech recognition inside a chatbot,  a response time ~< 2000 msec is still acceptable but  I have problems with many seconds response times. 

Thanks a lot for your help and support!
giorgio

--- 

```
$ cat com/witaitest 
#!/bin/bash

token=GB*******************************************XA2
sample=/*****/cpiabot/*********/sample.wav

echo
echo "send recording to WIT.ai speech recognition API service"
echo

function submit_speech() {
  start_time=`echo $(($(date +%s%N)/1000000))`

  curl -XPOST 'https://api.wit.ai/speech?v=20170307&context=%7B%22timezone%22%3A%22Europe%2FRome%22%2C%22locale%22%3A%22it_IT%22%7D' \
       -i -L \
       -H "Authorization: Bearer $token" \
       -H "Content-Type: audio/wav" \
       --data-binary "@$sample"

  end_time=`echo $(($(date +%s%N)/1000000))`
  elapsed_time=$(($end_time - $start_time))

  echo
  echo
  echo "API elapsed (msec): $elapsed_time"
  echo

  elapsed_array+=($elapsed_time)
}

#initialize array
elapsed_array=()

# set pause time to 2 seconds
pause_time=2

# for 10 times
for ((n=0;n<10;n++)) 
do 
  # push inthe array the elapsed time (msec)
  submit_speech

  # pause 
  sleep $pause_time
done

# print elapsed times
echo
echo "Elapsed times (msec)      : ${elapsed_array[@]}"
echo

len=${#elapsed_array[@]} #Number of elements in the array

total=0
for i in "${elapsed_array[@]}"
do
  total=$(($total + $i)) 
done

mean=`expr $total / $len`
echo "Medium Elapsed Time (msec): $mean"
```

```
$ com/witaitest 

send recording to WIT.ai speech recognition API service

HTTP/1.1 100 Continue
Server: proxygen
Date: Tue, 02 Apr 2019 09:25:39 GMT

HTTP/1.1 200 OK
Content-Type: application/json
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
X-Content-Type-Options: nosniff
Date: Tue, 02 Apr 2019 09:25:39 GMT
Server: proxygen
Connection: keep-alive
Content-Length: 77

{
  "_text" : "gatto",
  "entities" : { },
  "msg_id" : "1krxcxCSUUoTDRGYv"
}

API elapsed (msec): 33734

...
...

Elapsed times (msec)      : 33734 1333 1278 1301 1341 1317 1348 1322 1353 1316
Medium Elapsed Time (msec): 4564
```

**Comment by jtliao** [comment]
Apologies, we have been experiencing sporadic issues; we thought we had a fix but it turns out we were wrong. We're on top of this and are looking to fix the issues ASAP.

**Comment by jtliao** [comment]
closing as things have stabilized for a few days now, will re-open if issues come up again
