### ISSUE TITLE
thread_id and context.state not honored for /speech endpoint

### ISSUE THREAD

**Issue by abv** [wit-ai/wit#1413]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

SPEECH BUG 🎤🐛

**What is the current behavior?**

The docs state that `/speech` accepts an optional thread_id argument (https://wit.ai/docs/http/20170307#post__speech_link) however, it does not appear that this argument is being used or honored. 

Additionally, the docs state that I can pass the context.state argument to `/speech`. This argument isn't being honored by `/speech` either.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

To recreate this, post to `/speech` with a thread_id and options that include a state, like: `{"state":["yes_no"]}`

**What is the expected behavior?**

When I pass thread_id to `/message`, I see my messages grouped together in the logs, and I notice that thread_id is passed back in the API response. I would expect `/speech` to work like `/message`.

However when I pass thread_id to /speech, this is not the case -- the speech messages are not grouped together in the logs & I do not see the thread_id returned in the API. _FWIW, I _do_ see that msg_id works with /speech._

Additionally, the context.state doesn't show up for speech posts, and its not cleared to me that the states are being used. 

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by jtliao** [comment]
hey @abv, thanks for raising-- regarding thread_id, thanks for catching this, we'll have a fix out soon. For context.state, as stated in the docs, this is a legacy context field and probably shouldn't be used, the other context fields are working as expected.

**Comment by abv** [comment]
@jtliao Thanks for fixing that and clarifying what's going on with `context.state`. In lieu of the state argument, is there a way to provide wit with a hint about what type of entity value, I'm expecting?

**Comment by jtliao** [comment]
The original thread_id issue should be fixed now. As for the state, currently there isn't a way to do this, we deprecated this in favor of a more general model.

**Comment by abv** [comment]
It looks like a percentage of speech posts are now being logged with the thread_id, but not all of them. All of my speech audio is getting posted the same way.

**Comment by jtliao** [comment]
Can you provide your app id please?

**Comment by abv** [comment]
2793789567327769

**Comment by jtliao** [comment]
i can't seem to reproduce this, can you give some examples of instances where you sent the thread_id, but it wasn't logged?
