### ISSUE TITLE
can't login with facebook or github, i clicked on log in with both, and nothing happens.. 

### ISSUE THREAD

**Issue by yonitimes** [wit-ai/wit#1414]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by yangjinfeng** [comment]
I am the first time to try the wit, I cannot login with github or facebook account. I was always redirected to the login page again . My github account is yangjinfeng2010@gmail.com. Thanks

**Comment by agostonbonomi** [comment]
Same thing is happening to my colleagues. I can log out and log in again, so it seems like existing authorisations are working fine with Github, yet new ones are broken. Can it be a Github issue?

Facebook redirects me back to homescreen too without anything happening.

**Comment by jtliao** [comment]
Apologies for the inconvenience, this has been fixed.

**Comment by agostonbonomi** [comment]
hey @jtliao , thanks for sorting it out!!!
