### ISSUE TITLE
My app ID is set to train in 5hs from now

### ISSUE THREAD

**Issue by sebastianarena** [wit-ai/wit#1416]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
I've made several changes to entity names, and now it says its going to re-train in 5hs

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
I expect to have it re-train sooner. I understand I made more than the normal set of changes, but 5hs is a very long time, I really need to test this ASAP!

**What is the App ID where you are experiencing this issue (if applicable)?**
2121652087916253

**Comment by jtliao** [comment]
Thanks for raising. I went ahead and re-scheduled the training; as for the larger scheduling issue, we're aware of it but have not been able to prioritize it yet.
