### ISSUE TITLE
Creating custom quantities possible?

### ISSUE THREAD

**Issue by PAK90** [wit-ai/wit#1418]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Feature

**What is the current behavior?**
Quantity entity is fixed to specific things

**What is the App ID where you are experiencing this issue (if applicable)?**
2208311585881028

I have need of custom quantities (e.g. `forest with 30 trees` (30 trees) or `book with less than 300 pages` (less than 300 pages)), since quantities apparently have support for intervals. I have a predefined list of quantities I wish to support, but I can't seem to define those anywhere in the wit interface. Is this possible?

**Comment by patapizza** [comment]
Hi @PAK90,

`wit/quantity` is powered by [Duckling](https://github.com/facebook/duckling). To support your own quantities, I suggest to use a composite entity `my_quantity`, using `wit/number` (e.g. to catch both `30` and `thirty`) and `my_product` as a keyword entity (e.g. `trees`, `pages`) under it.

Hope this helps.
