### ISSUE TITLE
Training is stuck on SCHEDULED

### ISSUE THREAD

**Issue by shukriwinapp** [wit-ai/wit#1419]
Do you want to request a feature, report a bug, or ask a question about wit?
BUG

What is the current behavior?
Training is stuck on SCHEDULED

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
I have many apps. And often I spend days without training a new set on an app. Often, after I train something new, I'm left with 10+ hours waiting for the new set to be trained, instead of triggering something sooner.

What is the expected behavior?
I would expect that WIT trains my set faster when I update it

What is the App ID where you are experiencing this issue (if applicable)?
Right now I have one waiting for 6+ hours: 59bbe086-feab-4b4b-9b54-cab99a996261

**Comment by aforaleka** [comment]
Hi @shukriwinapp, your app is currently training. It last took around 6 hours to train that's why it was scheduled and didn't train instantly.

**Comment by shukriwinapp** [comment]
may I know the reason why it takes so long ? sorry im new in this.

**Comment by shukriwinapp** [comment]
> Hi @shukriwinapp, your app is currently training. It last took around 6 hours to train that's why it was scheduled and didn't train instantly.

may I know the reason why it takes so long ? sorry im new in this.

**Comment by aforaleka** [comment]
Ah on a second look, it might be because it got stuck in training one time and so we scheduled it 6 hours in advance because that was how long it took to train. But seems like it only took 6 minutes to train last time it has reset and won't be scheduled that far in advance going forward. Thanks for your understanding.
