### ISSUE TITLE
SIP Integration

### ISSUE THREAD

**Issue by jwasinski** [wit-ai/wit#142]
I have been trying to integrate twilio with wit.ai I have had some progress along the lines of using the Twilio record function and then sending that audio file to wit for processing. But it would be much more fluid if this could be streamed. 

Currently the only way twilio will allow live audio to be streamed is over SIP protocol, but the format does work on wit. It would be amazing if I could simply enter the SIP username/password and server details of wit on twilio and have wit parse out information as it is being spoken. 

Twilio Record Docs: https://www.twilio.com/docs/api/twiml/record

Twilio SIP Docs: https://www.twilio.com/docs/api/twiml/sip

Wit.AI Voice Docs: https://wit.ai/docs/http/20141022#get-intent-via-speech-link

**Comment by stopachka** [comment]
Hey @jswasinski, apologies for the late response here, this is not currently on the roadmap, but should be possible to develop this yourself. Feel free to ping us if you have any questions.
