### ISSUE TITLE
App has been training for a week

### ISSUE THREAD

**Issue by HarshEvilGeek** [wit-ai/wit#1420]
Do you want to request a feature, report a bug, or ask a question about wit?
Bug

What is the current behavior?
Will not stop training (been well over a week).

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

What is the expected behavior?
would like training to end in a few days/a week

What is the App ID where you are experiencing this issue (if applicable)?
2026352357478778

Saw this issue reported before, but I think my app needs to be restarted as well.

**Comment by HarshEvilGeek** [comment]
Just saw that the training has done. Can you let me know if you stopped it (meaning it hasn't trained) or this is just a coincidence?

**Comment by aforaleka** [comment]
Hi @HarshEvilGeek, I've restarted your training but it seems like it's taking longer than usual. We'll look into it.

**Comment by aforaleka** [comment]
This is most likely due to your bigger app size and we're currently working on a solution to better support apps like yours. We suggest downsizing your app for now to ensure training finishes.

**Comment by HarshEvilGeek** [comment]
How would I go about downsizing an app? Delete sample sentences?

**Comment by jtliao** [comment]
Yes, this would help
