### ISSUE TITLE
Stucked ONGOING

### ISSUE THREAD

**Issue by lezsakg** [wit-ai/wit#1421]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
It has been training longer than it should. I had an app before which had been stucked ongoing status, so I made a new app and put the training in again. This new app has been working good for some weeks until now, but now it has been stucked ongoing. I can't make a new app because there are too much training samples, it would be hard to put all of them in again. Can U restart my app training?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I don't know what caused this.

**What is the expected behavior?**
It should be done in some seconds (or at least an hour).

**What is the App ID where you are experiencing this issue (if applicable)?**
2298324296880684

Thank you very much for your help!

**Comment by aforaleka** [comment]
restarted the training, it should be done now. Thanks for the patience!

**Comment by lezsakg** [comment]
Thank you very much!
