### ISSUE TITLE
Stuck in scheduled?

### ISSUE THREAD

**Issue by dfischer** [wit-ai/wit#1422]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

question / bug

**What is the current behavior?**

scheduled longer than expected 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

usually it would just update right away and not much data has changed

**What is the expected behavior?**

scheduled to training within 5 min usually.... 

**What is the App ID where you are experiencing this issue (if applicable)?**
2326375457435428

**Comment by jtliao** [comment]
hi @dfischer, I went ahead and retrained your app

**Comment by dfischer** [comment]
@jtliao was it me just being impatient / is there a quota / bug? Trying to manage my own expectations so I don't bug you guys.

**Comment by aforaleka** [comment]
Hi @dfischer, I think in your case there was a bug. We're working on improving our ML infra and making it more stable, thanks for your patience!

**Comment by dfischer** [comment]
ML Prod pipelines are hard. Thanks for the solid work. @aforaleka

**Comment by dfischer** [comment]
Seems stuck again @aforaleka ?
