### ISSUE TITLE
Change email

### ISSUE THREAD

**Issue by gezquinndesign** [wit-ai/wit#1423]
Hello,

Would it be possible to change any instances of my email being 'gezzius@gmail.com' to 'holla@gezquinn.design' please? I changed it on GitHub but your systems still have my old address.

Thanks

Gez

**Comment by aforaleka** [comment]
Hey @gezquinndesign, do you still have access to your old email? Can you send a request from your gezzius@gmail.com account to help@wit.ai to verify?

**Comment by gezquinndesign** [comment]
Yes, no problem  I've sent an email entitled 'Confirmation Email' to help@wit.ai.

**Comment by aforaleka** [comment]
cool, we've changed your email to holla@gezquinn.design

**Comment by gezquinndesign** [comment]
Thanks.On 22 Apr 2019 07:52, Aleka C <notifications@github.com> wrote:cool, we've changed your email to holla@gezquinn.design

**Comment by gezquinndesign** [comment]
The latest marketing email about the GET/language went to my old address again. There's somewhere in your system that still has my old email address...

**Comment by jtliao** [comment]
Sorry about that, we'll go ahead and change it in the right place.

**Comment by gezquinndesign** [comment]
Thanks.
