### ISSUE TITLE
Recognition of the Ukrainian language

### ISSUE THREAD

**Issue by Dmitry1972** [wit-ai/wit#1424]
Previously worked recognition of the Ukrainian language. Now, error - { "error" : "Speech recognition is not supported for language: Ukrainian", "code" : "bad-request" } Api id 2446121478791400 

How to start again? Thank's.

**Comment by aforaleka** [comment]
Hey @Dmitry1972, we're in the process of improving our speech infra and we limited support for certain languages. But we whitelisted you and it should be working again. Thanks for supporting Wit!

**Comment by nimaasadi29** [comment]
does persian is one of those languages too?

**Comment by jtliao** [comment]
yes

**Comment by nimaasadi29** [comment]
does it come back? or you don't support again?

**Comment by jtliao** [comment]
yes, please provided your app id

**Comment by nimaasadi29** [comment]
thanks for your response. this is my app id: 2384486384935650

**Comment by 0cteract** [comment]
Same issue with the Ukrainian
app id: 2134453553259091

**Comment by dozham** [comment]
I get the same error when trying to recognize farsi (persian) text:
`Speech recognition is not supported for language: fa`
My app ID is: **2630958363692111**

**Comment by aforaleka** [comment]
Hi @dozham, unfortunately we have deprecated speech recognition for farsi until further notice.

**Comment by Valixon** [comment]
Speech recognition is not supported for language: uz.

**Comment by 0cteract** [comment]
Ukrainian recognition does not work again
wit.wit.WitError: Wit responded with an error: Speech recognition is not supported for language: uk
app id: 2134453553259091

**Comment by jtliao** [comment]
hi @0cteract, unfortunately we no longer have the capability to support speech recognition for Ukrainian. We hope to bring it back at some point later in the year, in the meantime please refer to https://wit.ai/faq for the speech languages we support.

**Comment by Valixon** [comment]
> Speech recognition is not supported for language: uz.
> I have the same problem. How can I use it if possible? My app ID is: 2584527051675979

Uzbek please
