### ISSUE TITLE
Training not working, 1.000 confidence on everything

### ISSUE THREAD

**Issue by lezsakg** [wit-ai/wit#1425]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
- In Inbox I can't click on Validate (happens nothing)
- There is written 1.000 confidence on everything
- When I put a new sample in Understanding it does not show up in Samples
- The training status remains "Done" forever

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I can see this behaviour on all my wit.ai apps (karora_centrum is my most important app).

**What is the expected behavior?**
It should working

**What is the App ID where you are experiencing this issue (if applicable)?**
2298324296880684

**Comment by anthonymfowler15** [comment]
I am having a similar issue here. Manually training (via the "Validate" button) does not add values to the expressions of my entities. Attempted to do the same via API and no expressions are being added.

App ID:
2303780949737600

**Comment by jtliao** [comment]
hi, we found the issue and will have a fix out soon

**Comment by lezsakg** [comment]
Here is working now :)
Thank you very much!

**Comment by jtliao** [comment]
fixed
