### ISSUE TITLE
Confusion about Entities Context

### ISSUE THREAD

**Issue by anthonymfowler15** [wit-ai/wit#1426]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question

What is the `entities` context (https://wit.ai/docs/http/20170307#context_link) used for? I am not seeing anything different in the API when passing in this context. 

I am hoping that it would filter the `/message` endpoint so that only specified entities are considered/returned by the endpoint. If this is not the case, is there another solution.

Also as a side note, the example in the docs shows:
```
curl -XGET 'https://api.wit.ai/message?v=20180601&q=chicago&context%3D%7B%22timezone%22%3A%22America%2FLos_Angeles%22%2C%22locale%22%3A%22en_CA%22%2C%22coords%22%3A%7B%22lat%22%3A37.47104%2C%22long%22%3A-122.14703%7D%7D' \
    -H "Authorization: Bearer $TOKEN"
```
as an example request (in https://wit.ai/docs/http/20170307#context_link). The `=` is url encoded into `%3D` (after the `context` query param). Is this correct?

**Comment by jtliao** [comment]
sorry about that, those features have been deprecated, we should remove that from the docs. there isn't currently a way to do entity filtering, it would have to be done on your end after receiving the entities. 

you're right about the example, it is wrong... it should be `=` and not `%3D`

we'll update the docs, thanks so much for raising the issue!
