### ISSUE TITLE
getting error" : "Speech recognition is not supported for language: Persian"

### ISSUE THREAD

**Issue by meysamg7** [wit-ai/wit#1427]
hello
im getting this message:
error" : "Speech recognition is not supported for language: Persian"
why? Previously worked recognition of the persian

and my app id is:
5ad5e77a-4061-456b-b070-840240c6b378

thanks

**Comment by jtliao** [comment]
this should be fixed now

**Comment by meysamg7** [comment]
thank you for your response,
in wit Q/A, it comes "Is there any rate limit?", What shall i do for haven't limitation? i plan use stream usage for my app, is it possible?

**Comment by jtliao** [comment]
hi @meysamg7, i'm having some trouble understanding what you mean, can you clarify?

**Comment by meysamg7** [comment]
> hi @meysamg7, i'm having some trouble understanding what you mean, can you clarify?

sorry my english not good

**Comment by jtliao** [comment]
Please reach out to `help@wit.ai` with more info about your specific use case.

**Comment by galubap** [comment]
I still have error that "Speech recognition is not supported for language". In my app settings language is set to polish

**Comment by jtliao** [comment]
Sorry, we do not have the ability to support speech recognition for all languages.
