### ISSUE TITLE
*Bug* Training generates a ton of duplicate intents with the same samples

### ISSUE THREAD

**Issue by ouamer-dahmani** [wit-ai/wit#1429]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
*Bug*

**What is the current behavior?**
We are training our application through the HTTP api.
Starting sometime this week, we started seeing duplicate intent values in multiple projects.

![image](https://user-images.githubusercontent.com/5343121/56824585-e0bb6680-6824-11e9-8dd2-e4cf696e8d47.png)

This does not seem to be a purely UI issue: if I fetch intents using the HTTP API I see the same results:

![image](https://user-images.githubusercontent.com/5343121/56824651-17917c80-6825-11e9-9abf-f9b6a18877f1.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Here is a sample of the messages we used to train the app.
```
[  
  {
    "_text": "Hi! Can I make Recipes for Overnight oats? Gracias.",
    "_nlp": {
      "version": 1,
      "intent": [
        {
          "name": "recipe_search",
          "confidence": -1
        }
      ],
      "sentiment": [],
      "entities": [
        {
          "end": 41,
          "entity": "recipe_category",
          "start": 27,
          "text": "breakfast"
        }
      ]
    }
  },
  {
    "_text": "Hey? I'd like Recipes for Shrimp kabobs. tchao.",
    "_nlp": {
      "version": 1,
      "intent": [
        {
          "name": "recipe_search",
          "confidence": -1
        }
      ],
      "sentiment": [],
      "entities": [
        {
          "end": 39,
          "entity": "recipe_category",
          "start": 26,
          "text": "fish_and_seafood"
        }
      ]
    }
  }
]
```

**What is the expected behavior?**
I should have only one of each intent.

**What is the App ID where you are experiencing this issue (if applicable)?**
2458421787509840

**Comment by jtliao** [comment]
Thanks for raising, this is definitely unexpected. We'll look into what is wrong.

**Comment by lezsakdomi** [comment]
Experienced on 2235996579827349 too.

Generated by unintentionally letting running this script (or at least the 200 messages of it) about six times:
```
for i in {1..$(curl -XGET "https://api.wit.ai/samples?limit=10000" -H "Authorization: Bearer $SOURCE_KEY" | jq length)..200}; do
  curl -XGET "https://api.wit.ai/samples?limit=200&offset=$((i-1))" -H "Authorization: Bearer $SOURCE_KEY" \
    | curl -XPOST -d '@-' "https://api.wit.ai/samples" -H 'Content-Type: application/json' -H "Authorization: Bearer $DESTINATION_KEY"
  sleep 70
done
```

`$SOURCE_KEY` corresponds to the server key of 2298324296880684, `$DESTINATION_KEY` to 2235996579827349.

**Comment by lezsakdomi** [comment]
Is there a way to fix the issue by hand?

**Comment by jtliao** [comment]
We've identified an issue, and hope to have a fix out in the next week. You can fix the issue by hand by just deleting the redundant values.

**Comment by ouamer-dahmani** [comment]
Hello! Any update on this? This is basically doing it on all our apps when we do some incremental training per API.

**Comment by jtliao** [comment]
apologies for the delay, this should be addressed now
