### ISSUE TITLE
Cannot export app data

### ISSUE THREAD

**Issue by headless-ltd** [wit-ai/wit#1430]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
I can't export the app data as zip, it works fine on our other apps, only this one has this issue.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Just click the download button on the settings page, an error message appears saying "Something went wrong while exporting your app persevere. Please try again, or contact us."

**What is the expected behavior?**
Launch the download of a zip file containing the bot data.

**What is the App ID where you are experiencing this issue (if applicable)?**
2108266852622141

**Comment by jtliao** [comment]
this should be resolved now
