### ISSUE TITLE
"Speech recognition is not supported for language: Dutch

### ISSUE THREAD

**Issue by isnaasharimam** [wit-ai/wit#1432]
I'm getting this error "Speech recognition is not supported for language: Dutch", while you said in faq that dutch is supported.
app_id: 2654463707902632

Please fix problem.

**Comment by jtliao** [comment]
Unfortunately we do not have the ability to support speech recognition for all languages at the moment. We are actively working on expanding the ones we support, but do not currently have a timeline for Dutch.
