### ISSUE TITLE
Problems with Finnish Speech Recognition

### ISSUE THREAD

**Issue by Kaappihullu** [wit-ai/wit#1434]
We ran into a problem with speech recognition with our product that we
were developing using wit.ai. This used to work perfectly for our needs
atleast. But after some digging we found this error message send by your
server.

{
      "error" : "Speech recognition is not supported for language: Finnish",
      "code" : "bad-request"
}

Again this feature used to work perfectly for the needs of our product.
Is this a bug or did you disable this? If so when can we expect it to be
functional again?

**Comment by jtliao** [comment]
What is your app id?

**Comment by jtliao** [comment]
this should be addressed now
