### ISSUE TITLE
Cannot export app data

### ISSUE THREAD

**Issue by jmar1103** [wit-ai/wit#1435]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
App Data error exporting

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Settings -> Export app data

**What is the expected behavior?**
Export app data as zip file download

**What is the App ID where you are experiencing this issue (if applicable)?**
5a09cc53-45df-4778-b58a-126cd745660a

**Comment by jtliao** [comment]
Thanks for raising, this should be fixed now
