### ISSUE TITLE
App is stuck on training

### ISSUE THREAD

**Issue by malabananharold** [wit-ai/wit#1436]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
--Report a bug.

**What is the current behavior?**
--App is stuck on ON-GOING status after trying to add a new user defined entity and trying o add new samples for the new entity. 

**What is the expected behavior?**
--App should be done already.

**What is the App ID where you are experiencing this issue (if applicable)?**
-- 2192891107473665

**Comment by jtliao** [comment]
I went and retrained your app, it should be done now.
