### ISSUE TITLE
Wit classifies X4 as a greeting

### ISSUE THREAD

**Issue by lmessinger** [wit-ai/wit#1437]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
Wit classifies X4 as a greeting *this happens with many other words, like X4, Bmw and many, many others entities we are using as keywords or freetext. The problem is that you cannot get rid of the greeting. deleting it (by clicking the x) won't do a thing*
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
not to
**What is the App ID where you are experiencing this issue (if applicable)?**
![Capture](https://user-images.githubusercontent.com/1693213/57023033-afce9d80-6c39-11e9-9b3b-301f4597e0d5.PNG)

**Comment by patapizza** [comment]
Thanks for reporting @lmessinger!

**Comment by jtliao** [comment]
Merging with #1615 for tracking
