### ISSUE TITLE
wit/bye and wit/greetings not available in spanish

### ISSUE THREAD

**Issue by kr05** [wit-ai/wit#1438]
First, I would to like to extend my thanks to the amazing team behind wit. Coming from DialogFlow, I can confidently that the level of community outreach and support is second to none and is one of the reasons why I'm thoroughly enjoying my first few days of using wit.

As for my issue, do you have guys have a timeline for extending wit/bye and wit/greetings to more languages? I understand it's in beta so it might take a while, but it would be nice to have a general timeline. I personally have a need for the Spanish version, but I'm sure other people would appreciate this feature in a language other than Spanish. On a related note, is there anything the community can do to speed up or help with the implementation of these intents to more languages? Thanks!

**Comment by patapizza** [comment]
Hi Kevin, thank you for the kind words.

We don't have a clear timeline yet for extending these entities to other languages unfortunately. I'll surface the need for Spanish to the team today.
In the meantime, it'd be helpful to build your own trait entities for `bye`, `greetings` and `thanks` and share your app ID here so we can explore that to bootstrap the Spanish built-in.

Thanks!

**Comment by kr05** [comment]
Thanks for the response! Sounds good, as soon as I have a half-decent entity I'll share my app ID. I just wanted to see if it was better to wait while the team released the Spanish version or attempt it myself. Keep up the great work!

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
