### ISSUE TITLE
Intent name is converted to all lower case letters

### ISSUE THREAD

**Issue by Enceradeira** [wit-ai/wit#144]
When I create a new intent through the Inbox/Expressions->Dropdown->search/create (https://wit.ai/Enceradeira/FoodHero/inbox) I mange to name an intent as e.g "setSuggestionFeedback_Dislike".

When I create a new intent through the Intent-Tab (https://wit.ai/Enceradeira/FoodHero/intents) by directly entering its name in the text-field (e.g typing "setSuggestionFeedback_Dislike") the intent is created as "setsuggestionfeedback_dislike" (all lowercase)

I believe this is a bug and the name should not be automatically converted to all lower case. I want to be able to add intents with both upper- and lowercase characters.

**Comment by blandinw** [comment]
So sorry for the late reply 😔
This has been fixed a long time ago. Closing now.
