### ISSUE TITLE
error: Speech recognition is not supported for language: Polish

### ISSUE THREAD

**Issue by ihavenoclueastowhatputinhere** [wit-ai/wit#1440]
I'm using HTTP POST requests to wit.ai Speech API. It was working before but now in response I only get:
{'error': 'Speech recognition is not supported for language: Polish', 'code': 'bad-request'}

**I know this issue was brought up by other people** but speech recognition for Polish is still not working. I'm sure it was perfectly functional only few months ago. I'd like to know if it's only temporally not available or you are dropping support for Polish altogether?

**Comment by safarisadegh** [comment]
I have same issue for Persian language

**Comment by jtliao** [comment]
please provide your app id

**Comment by ihavenoclueastowhatputinhere** [comment]
id: 1937479636305752
Sorry, I forgot to put it in the main post.

**Comment by jtliao** [comment]
addressed

**Comment by safarisadegh** [comment]
my id is: 2629917927080122
('error': 'Speech recognition is not supported for language: Persian', 'code': 'bad-request')

**Comment by aforaleka** [comment]
it should work now @safarisadegh

**Comment by JUtupe** [comment]
Same issue here, my app id: 1828868047239558
