### ISSUE TITLE
wit/contact: emoji breaks entity value

### ISSUE THREAD

**Issue by jacques0191** [wit-ai/wit#1443]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
report bug
**What is the current behavior?**
wit/contact skips the first character of an entity when emoji is used but only when emoji is placed in the sentence before the entity.
Example:
🙂 My name is John. 
Entity = ohn
vs
My name is John 🙂
Entity = John
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
![Screenshot from 2019-05-06 10-07-52](https://user-images.githubusercontent.com/29854958/57213374-e95f2a00-6fe6-11e9-9984-ef2ef72e3cde.png)
![Screenshot from 2019-05-06 10-07-42](https://user-images.githubusercontent.com/29854958/57213375-e95f2a00-6fe6-11e9-92f6-bc9ddaef3b99.png)
![Screenshot from 2019-05-06 10-00-17](https://user-images.githubusercontent.com/29854958/57213376-e95f2a00-6fe6-11e9-9a87-93364a481d28.png)
![Screenshot from 2019-05-06 10-00-11](https://user-images.githubusercontent.com/29854958/57213377-e9f7c080-6fe6-11e9-8c43-51a36610a0ad.png)

**What is the expected behavior?**
To catch the correct entity without removing the first character.
**What is the App ID where you are experiencing this issue (if applicable)?**
59c64719-2eb7-4073-8981-cb40a76f2749

**Comment by patapizza** [comment]
Thanks for reporting. We'll look into this.

**Comment by jtliao** [comment]
Merging with #1615 for tracking
