### ISSUE TITLE
"qua" is being parsed wrongly in Vietnamese 

### ISSUE THREAD

**Issue by 51100807** [wit-ai/wit#1444]
Do you want to request a feature, report a bug, or ask a question about wit?
report bug

What is the current behavior?
"qua" has 2 meanings in Vietnamese: yesterday and through/by/pass. Wit always parse "qua" as yesterday, which cause misunderstanding 

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
User says: mình cần xác nhận qua điện thoại (which means "I want to confirm by phone") but wit parse "qua" as wit/datetime 5/6/2019, 12:00:00 AM

What is the expected behavior?
Don't parse "qua" because it has many meanings 

What is the App ID where you are experiencing this issue (if applicable)?
1778316165603240

**Comment by aforaleka** [comment]
Hi @51100807, thanks for reporting! Since the datetime built-in entity is powered by Duckling, please open an issue [here](https://github.com/facebook/duckling/issues) instead.
