### ISSUE TITLE
No response for high sample rates(like 44100 samples per sec)

### ISSUE THREAD

**Issue by prabalbansal** [wit-ai/wit#1446]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
Working only for 8000Hz samples rate audios.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1) Have a file of sample rate 44100 or 16000 Hz. Try to get the response. 

**What is the expected behavior?**
Should transcribe the 44100 or 16000 Hz file also.
**What is the App ID where you are experiencing this issue (if applicable)?**
2324515704254613

**Comment by aforaleka** [comment]
Hi @prabalbansal, unfortunately I cannot repro. Are you using our POST /speech API directly with the audio?

**Comment by aforaleka** [comment]
We actually experienced some issues with our speech endpoint earlier that might have affected you, can you try again and see if you still experience it?

**Comment by prabalbansal** [comment]
Hi @aforaleka , We are using API for converting audio transcriptions and when we give a 44100Hz file it gives us.
{'error': "Something went wrong. We've been notified.", 'code': 'wit'}.
It only works for 8000Hz file.
You can have a sample file from here: https://drive.google.com/open?id=1Jw5wOdKo2ZPyEj5JiihxqEudX3W_CC46
When we convert the same file to 8000Hz, it works fine.

And also one more thing, it took around 14 sec to transcribe a 20 sec audio. Can we decrease this 14 sec time?

**Comment by aforaleka** [comment]
Hi @prabalbansal, it seems like the sample file is stereo which we don't process, you'll have to convert it to a mono file. Let me know if that works!

**Comment by prabalbansal** [comment]
Yes it works really good.
And time issue is also solved(internet speed problem on our side)

And Thanks a lot for quick support.

**Comment by aforaleka** [comment]
awesome, glad that works!
