### ISSUE TITLE
Why not supported Ukrainian language.

### ISSUE THREAD

**Issue by dentok** [wit-ai/wit#1447]
I use your service, but when send request I get error:
{
"error": "Speech recognition is not supported for language: Ukrainian",
"code": "bad-request"
}

Why?

My email is us_81@ukr.net.

Please, add me to white list for use speech on Ukrainian language.
Thank you!

**Comment by aforaleka** [comment]
hey @dentok, unfortunately we don't have the ability to support speech recognition for all languages at the moment.
