### ISSUE TITLE
speech to text/speech recognitio doesn't work with Catalan

### ISSUE THREAD

**Issue by fgadea** [wit-ai/wit#1448]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question or bug
**What is the current behavior?**
Time ago, the speech recognition in the language: Catalan, worked, but now it doesn't work.
Is it a bug or did you remove the service?

**What is the expected behavior?**
That the speech recognition works.

**What is the App ID where you are experiencing this issue (if applicable)?**
2292631217470925

**Comment by jtliao** [comment]
Sorry, we no longer have the ability to support speech recognition for Catalan
