### ISSUE TITLE
After training the App, App stuck in ongoing for few hours 

### ISSUE THREAD

**Issue by GaganTM** [wit-ai/wit#1449]
Hi 

From few days after training  our application is stuck in ONGOING for the last few hours.

And this issue is occurring in all our applications   

For reference please find the App ID below
App ID: 2036569073137519

Could you please have a look at this.

**Comment by arivitto** [comment]
Same problem with app 2187697417965796...

**Comment by aforaleka** [comment]
hey @GaganTM and @arivitto, the training should be done now. Thanks for your patience!
