### ISSUE TITLE
Unable to record transcript of my message

### ISSUE THREAD

**Issue by jkbrooks** [wit-ai/wit#145]
I want to record a transcript of myself, using Instance 7b0e-4c0.  When I try this at www.labs.wit.ai, I get a totally empty `msg_body`  

    {
      "WARNING": "DEPRECATED",
      "msg_body": "",
      "outcome": {
        "entities": {}
      },
      "msg_id": "519eb1d0-99d2-4414-aad3-aa4384509b40"
    }

I have used this before with another intent on that instance and the recording was correct.  What's happened here?

**Comment by jkbrooks** [comment]
As an update, this was a problem only in Chrome.  In Firefox, the web app works correctly

**Comment by jkbrooks** [comment]
Updating the Chrome browser fixed this issue.

**Comment by james20718** [comment]
Excuse me, your chrome version?
My version 40.0.2214.115 m (64-bit)
Just like you?

**Comment by jkbrooks** [comment]
My Chrome version is 40.0.2214.115 (64-bit)

**Comment by james20718** [comment]
I still have a problem,there are other methods?

**Comment by jkbrooks** [comment]
You should open a new ticket and someone from Wit will help you.
