### ISSUE TITLE
Training Stuck at "Ongoing"

### ISSUE THREAD

**Issue by edskeizer** [wit-ai/wit#1450]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug 

**What is the current behavior?**
Training is stuck in 'Ongoing'

**What is the App ID where you are experiencing this issue (if applicable)?**
2661968487209858

**Comment by dalo2903** [comment]
My app is stuck at "Ongoing" too,
My App ID: 2201933053209591

**Comment by jtliao** [comment]
Hi, we were facing some training issues last night. Both are now trained.

**Comment by edskeizer** [comment]
Again, the training is stuck. Can you fix this please? @jtliao
