### ISSUE TITLE
Unable to login anymore

### ISSUE THREAD

**Issue by b-tix** [wit-ai/wit#1451]
Today I logged out and cannot login anymore with my github account: Uh oh... You cannot access this page. You'll need to sign in to view this page! Sorry about that!

**Comment by jtliao** [comment]
hi @b-tix, is this still happening for you? i can't seem to reproduce

**Comment by b-tix** [comment]
Still not able to login, sorry :-( I use Chrome, but have also probems with Firefox. My App ID e. g. 2371065689592980

**Comment by hsilvester** [comment]
I'm also having trouble logging in with both Facebook and GitHub. I am just being redirected to the "Uh oh... You cannot access this page" no matter which service I try to log in with.

**Comment by silsolinas** [comment]
I have the same problem too...

**Comment by jtliao** [comment]
Found the issue, will have a fix soon

**Comment by jtliao** [comment]
Should be fixed now, apologies for the inconvenience.
