### ISSUE TITLE
App SCHEDULED time is more 

### ISSUE THREAD

**Issue by GaganTM** [wit-ai/wit#1452]
When we are adding new training data into the application. Either it may take more time like half day/ one whole day to schedule or its will be in the ongoing status. This is happening when we training 2 or 3 training data.

For reference please find the below App ID. 
App ID:  2036569073137519

Please suggest a permanent solution for this issue as we are facing it again & again.

**Comment by patapizza** [comment]
Hi @GaganTM, thanks for reporting. We're actively looking into our training service.

**Comment by jtliao** [comment]
Your app is now trained, we're hoping to address the larger issue soon

**Comment by GaganTM** [comment]
If we train single sentence to the application 
the app scheduler is show 12 hours for training.

For reference please find the below App ID.
App ID: 2036569073137519
