### ISSUE TITLE
BUG: internal entities override keywords, and no training changes that

### ISSUE THREAD

**Issue by lmessinger** [wit-ai/wit#1454]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
**bug**
**What is the current behavior?**
train 500L  as keyword/free text. but it is recognized as wit/volume
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
500L 
**What is the expected behavior?**
car model entity
**What is the App ID where you are experiencing this issue (if applicable)?**
2200479686655080
related to:
#1445

**Comment by kingseaeast** [comment]
Thanks for reporting! We will look into it.

**Comment by Barbog** [comment]
Closing this issue due to there being no movement in some time. Please re-open or file a new issue should the issue persist today.
