### ISSUE TITLE
Training scheduled for too long!

### ISSUE THREAD

**Issue by marinakhomutova** [wit-ai/wit#1456]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by marinakhomutova** [comment]
We are having a very important event now and need to demo our bot. It is highly important to train a bot for a new sentence to demo. The problem that the demo is in 5 hours, but the training is scheduled to be done in 10 hours. Could you do something to speed up the training? 
User: Travelaer 
Name: bot-taer-en

**Comment by jennygrahamjones** [comment]
@marinakhomutova You may want to provide the App ID for the application (found in Settings section of your application) as the wit team typically need it to look into any issues that are specific to your application.

**Comment by patapizza** [comment]
Hi @marinakhomutova, I've retrained your app. You're good to go.
