### ISSUE TITLE
App stuck in training

### ISSUE THREAD

**Issue by iamgoodbytes** [wit-ai/wit#1457]
Hi friends, 

my app with id "2069953043117511" has been stuck in trainingland for the past couple of hours. My guess is that it somehow froze because usually training is pretty instant.

Could you look into this please?

thanks a lot, I'm having lots of fun with wit.ai

**Comment by patapizza** [comment]
Thanks for the kind words @iamgoodbytes. Your app is done training.

**Comment by iamgoodbytes** [comment]
@patapizza thanks a lot, was it an issue on my side or should I contact you here if this happens again? Curious about what's causing this.

**Comment by patapizza** [comment]
@iamgoodbytes We had some issues with our training service, which should be resolved by now.

**Comment by iamgoodbytes** [comment]
Hi @patapizza thanks for solving this issue last time. It looks like my app is hanging in "scheduled" now, could you please take a look for me?

![Screen Shot 2019-05-26 at 20 11 28](https://user-images.githubusercontent.com/3899360/58385588-db536680-7ff2-11e9-8298-5525d33ccf9f.png)
