### ISSUE TITLE
Cannot use newly created app id and token.

### ISSUE THREAD

**Issue by wr200m** [wit-ai/wit#1458]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
1. I have an existing wit.ai app, of which the server access token is XXXXXXXXXXXXXXX.
2. I use the following API to create a new app and receive app_id: an alphanumeric UUID yyyy-yyyy-yyyy and access_token: ZZZZZZZZZZZZZZZZZZ
3. I then use the new access token ZZZZZZZZZZZZZZZZZZ to query the new app yyyy-yyyy-yyyy. But I receive no-auth error.

curl -XPOST 'https://api.wit.ai/apps?v=20170307' \
  -H "Authorization: Bearer XXXXXXXXXXXXXXX" \
  -H "Content-Type: application/json" \
  -d '{"name":"My_New_App_Test2",
       "lang":"en",
       "private":"false"}'
	   
{"app_id":"yyyy-yyyy-yyyy","access_token":"ZZZZZZZZZZZZZZZZZZ"}

curl -XGET 'https://api.wit.ai/apps/yyyy-yyyy-yyyy?v=20170307' \
  -H "Authorization: Bearer ZZZZZZZZZZZZZZZZZZ" \
  -H "Content-Type: application/json"
  
 {"error":"Access token does not match","code":"no-auth"}

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Run the curl for two API calls, as shown above.

**What is the expected behavior?**
I expect to receive something similar to the following after the second curl:
{
	"name": "My_New_App_Test2",
	"id": "a numeric UUID",
	"description": "",
	"lang": "en",
	"private": false,
	"created_at": "timestamp",
	"last_training_duration_secs": 0,
	"will_train_at": "timestamp before 1970",
	"last_trained_at": "timestamp before 1970",
	"training_status": "done"
}

**What is the App ID where you are experiencing this issue (if applicable)?**
Existing app id is: all numeric UUID  1805556799554901
Newly created app id returned from app creation call: an alpha-numeric 5e2b2160-bbe8-84e2-6c3a-26a9bfa82844

**Comment by patapizza** [comment]
Thanks for reporting @wr200m, looking into it.

**Comment by patapizza** [comment]
Fix ready, this should be fixed in a few hours. Thanks for your patience.
