### ISSUE TITLE
Persian is not supported

### ISSUE THREAD

**Issue by Misaghlb** [wit-ai/wit#1459]
**when I send this request for the Persian language:**

curl -XPOST 'https://api.wit.ai/speech?v=2238056099623458' \
   -i -L \
   -H "Authorization: Bearer <MY_TOKEN>" \
   -H "Content-Type: audio/wav" \
   --data-binary "@Speak.wav"

**returned response is:**
{
  "error" : "Speech recognition is not supported for language: Persian",
  "code" : "bad-request"
}

**Comment by patapizza** [comment]
Sorry @Misaghlb we don't support speech recognition for Persian at this time.
