### ISSUE TITLE
Catalan support

### ISSUE THREAD

**Issue by JuanIzquierdoDomenech** [wit-ai/wit#1461]
Why is Catalan language not supported anymore?
It worked pretty well.

If there are no plans to support it anymore, are there any other alternatives to use it?

**Comment by patapizza** [comment]
Hi @JuanIzquierdoDomenech, what is your app ID? We're improving our infra and models and are preventing new use cases in the meantime to ease the transition.

**Comment by JuanIzquierdoDomenech** [comment]
My app id is 2292631217470925

**Comment by jtliao** [comment]
apologies for the delay, this should be addressed
