### ISSUE TITLE
Entity Keyword limits

### ISSUE THREAD

**Issue by 91ns** [wit-ai/wit#1463]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question

This was probably asked before, but I would like to know if there's a definite answer on the possibility of adding a large number of keywords to one entity. The number would be around 9000.

Thanks,

**Comment by aforaleka** [comment]
Hey @91ns! Yes it is possible, although our UI might not not handle the volume well. We also suggest using free-text if that list of enums will be growing. Thanks for supporting Wit!
