### ISSUE TITLE
Not getting output for raw_data

### ISSUE THREAD

**Issue by prabalbansal** [wit-ai/wit#1464]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
Passing the 20 sec raw data but getting {'error': 'Max audio length is 20 seconds.', 'code': 'timeout'}
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
API_ENDPOINT = 'https://api.wit.ai/speech'
headers = {'authorization': 'Bearer ' + ACCESS_TOKEN,'Content-Type': 'audio/raw;encoding=unsigned-integer;bits=16;rate=8000;endian=little'}
segment = song[0:20000]    
resp = requests.post(API_ENDPOINT, headers = headers,data =segment.raw_data)
text = json.loads(resp.content)
print(text)

**What is the expected behavior?**
Should transcribe the audio.
**What is the App ID where you are experiencing this issue (if applicable)?**
1965866446858539

**Comment by aforaleka** [comment]
hey @prabalbansal, what's the format of `song`? Can you check whether `song[0:20000]` actually takes the first 20 seconds of your audio sample?

**Comment by prabalbansal** [comment]
hi @aforaleka , the song is mp3 type. Yes it takes the first 20 seconds of the sample.

**Comment by aforaleka** [comment]
Sorry that's happening, unfortunately I can't repro. Does it work if you decrease it to say, 19 seconds? Or can you send me the segmented song file (through email if you want to) so I can try to repro?

**Comment by prabalbansal** [comment]
Hi I create a shareable link.
https://drive.google.com/drive/folders/1aynM2G1s_Xhh2vyAk2LdpL8u66M42D5N?usp=sharing

**Comment by prabalbansal** [comment]
> Sorry that's happening, unfortunately I can't repro. Does it work if you decrease it to say, 19 seconds? Or can you send me the segmented song file (through email if you want to) so I can try to repro?

It is not working for 19 seconds also.

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
