### ISSUE TITLE
not working on firefox

### ISSUE THREAD

**Issue by fvildoso** [wit-ai/wit#1467]
Hi guys,

Wit is not working on Firefox. The browser console says 
`ReferenceError: requireLazy is not definedwit.ai:20:1
    <anónima> https://wit.ai/:20` 

Regards.

**Comment by aforaleka** [comment]
hey @fvildoso! sorry that's happening, can you try clearing your cookies/cache and see if you're still experiencing the issue?

**Comment by fvildoso** [comment]
Hi @aforaleka 

I clean everything and nothing change.

![Screenshot_2019-06-04 Wit ai](https://user-images.githubusercontent.com/9140883/58914794-64525800-86ed-11e9-801b-0dc3569d3ca2.png)

**Comment by jtliao** [comment]
hey @fvildoso, apologies, but we can't seem to reproduce this on our side

**Comment by fvildoso** [comment]
Hi guys,

The [Facebook Container](https://addons.mozilla.org/en-US/firefox/addon/facebook-container/) addon is the responsible for crashing, so I will open an issue there.

Thanks!

**Comment by edje123** [comment]
I am having this issue as well. I get the same page as fvildoso. It was working previously.

**Comment by cschultzzz** [comment]
A quick fix for Firefox: Open https://wit.ai in a PRIVATE MODE tab and you can see it. The Facebook Blocker is deactive in private mode.
