### ISSUE TITLE
Not able to assign intent

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#1469]
'Hi' is not identifyingg'greetings' intent even after validating.
It returns only the inbuilt entity 'greetings'.
Is there any issues if we have same name for buitin entity and intent.

**Comment by jtliao** [comment]
please provide your app id, we can't help otherwise.

**Comment by anjaly** [comment]
Our appid is 2159428820836844

**Comment by jtliao** [comment]
if you don't want the builtin greetings to resolve, you should remove it from your app or validate more samples for your own `intent` entity
