### ISSUE TITLE
WIT.ai Speech API: "wrong" speech to text translation (Italian word: "professoressa")

### ISSUE THREAD

**Issue by solyarisoftware** [wit-ai/wit#1471]
Hi,
Wit.ai Speech APIs, that I'm successfully using for Italian locale, are great 99.9% of cases, but there are some words that are translated wrongly.

```
{
"timezone":
"Europe/Rome"
"locale":
"it_IT"
"coords":
{
"lat":
44.414165
"long":
8.942184
}
}
```

One of word that seems almost always bad interpreted is 

**PROFESSORESSA** (singular female of PROFESSORE).

The Wit.ai interpretation of **PROFESSORESSA** is often:

**PROFESSORE SSA**
     
the space is wrong and **SSA** is not an Italian word .

I tryied with many different input voices so I think that's systematic. 
Maybe that's a ML "bug". There is a away to improve the training set/ fix the issue? 

---

I don't know if this is the correct place to submit the problem; maybe i have to write at help@wit.ai ?

Thanks
giorgio

**Comment by jtliao** [comment]
hi, unfortunately we don't have the ability to manually update the Italian model; apologies for the inconvenience
