### ISSUE TITLE
Wit.ai Speech API: what's the suggested audio format (using ffmpeg) ? 

### ISSUE THREAD

**Issue by solyarisoftware** [wit-ai/wit#1472]
Hi,
just an info request:

I submit a voice recording audio file (mono), to Wit.ai speech API (https://wit.ai/docs/http/20170307#post__speech_link). 
The source file is an OGG file,  and the file to submit is a WAV file.

What's the suggested (wav) audio format for a **BEST Speech Recognition** results?

There is any specific requirement about VOLUME / loudness for better results?
By example: are the `ffmpeg` conversion flags here below optimals?

```
ffmpeg -loglevel panic -i /path/to/source_file.oga \
    -af loudnorm=I=-19:dual_mono=true:TP=-1.5:LRA=11 \
    -ac 1 -ar 16000 
    /path/to/file_for_witai.wav -y
```

thanks for your patience and help
giorgio

**Comment by jtliao** [comment]
I don't think there are any requirements on volume, but of course clearer is better. Those settings seem fine to me.
