### ISSUE TITLE
Metadata missing in exported data

### ISSUE THREAD

**Issue by lanarimarco** [wit-ai/wit#1473]
Hi,
I've notice that the exported data (button "download .zip with your data" in the settings form) doesn't contain entities metadata.
Same behavior through api /export.
My appid is 2290632434290691.
Is in your roadmap to add this features?

Best regards.

Marco

**Comment by jtliao** [comment]
hi @lanarimarco, thanks for the feedback, i'll raise this with the team

**Comment by jtliao** [comment]
This should be addressed now

**Comment by lanarimarco** [comment]
I did some testing but the metadata is not yet exported
