### ISSUE TITLE
Ukrainian speech recognition

### ISSUE THREAD

**Issue by 0cteract** [wit-ai/wit#1475]
I am trying to test speech recognition, yet have some struggles. 
I use Python, and everything works really well when I am using russian. But when I switch to ukrainian, error says that Speech recognition is not supported for language: ukrainian.
It looks self-explanatory, yet as far as I know some other apps can preform speech recognition in ukrainian via Wit.ai
Am I doing something wrong, or ukrainian speech recognition is in some form of closed beta?

saw similar issue here: https://github.com/wit-ai/wit/issues/1424 

app id: 2134453553259091

thanks

**Comment by jtliao** [comment]
this should be addressed now

**Comment by matroskin777** [comment]
Same problem, app ID: 2863680990371336

**Comment by prostosergey** [comment]
Same problem, app ID:  3989175811108371
