### ISSUE TITLE
Decimal number not getting handled in datetime entity

### ISSUE THREAD

**Issue by monika1800** [wit-ai/wit#1476]
*Current Behaviour*
Datetime entity is only identifying an int number properly. In case of '3.5 years ago' it is not picking 3.5 years ago rather picks '.5 years ago'.

Ex: In case of ' in last 3.5 years'
It is not even identifying this as a datetime entity, rather ignores '3.' and just takes duration entity as '5 years'.

*Expected Behaviour*
Ex: In case of 'in last 3.5 years'
It should first identify ' in last 3.5 years' as a datetime entity and with the value 'from01/01/2016, 00:00:00 to 01/01/2019, 00:00:00'

**Comment by aforaleka** [comment]
Hi @monika1800, thanks for reporting this! Since this is related to our Duckling datetime parser, please open an issue [there](https://github.com/facebook/duckling/issues) instead and our Duckling engineers will work on a fix.
