### ISSUE TITLE
Confidence Calculation

### ISSUE THREAD

**Issue by davislf2** [wit-ai/wit#1478]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question

**What is the current behavior?**
Hi, I am quite interested in how wit calculates confidence scores. However, I couldn't find how you define the confidence score from your documentation. Could anyone append any documentation or papers wit refers to calculate the confidence scores? That would be a great help for me. Thanks.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
A formula of how wit.ai calculate the confidence score.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2750067838340707

**Comment by jtliao** [comment]
hi @davislf2, thanks for your interest in Wit! however, we cannot disclose this information about Wit specifically. you can find general information online by looking into document classification and named entity necognition
