### ISSUE TITLE
Inconsistent /message api outcomes

### ISSUE THREAD

**Issue by gaurav-huminos** [wit-ai/wit#1479]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
report a *bug*

**What is the current behavior?**
It happens sometimes that get intent API, (/message) returns intents sometimes and sometimes it does not. This has happened a few times, latest incident I am reporting in detail here.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I am posting here the response from the API at 2 different times, separated by 2 minutes

```
{
    "_text": "*MASKED VALUE*",
    "entities": {
        "location": [
            {
                "suggested": true,
                "confidence": 0.882805,
                "value": "*MASKED VALUE*",
                "type": "value"
            }
        ]
    },
    "msg_id": "1B7wwzunvJLtxIEIo"
}
```

```
{
    "_text": "*MASKED_VALUE*",
    "entities": {
        "location": [
            {
                "suggested": true,
                "confidence": 0.882805,
                "value": "*MASKED_VALUE*",
                "type": "value"
            }
        ],
        "intent": [
            {
                "confidence": 0.95016976664091,
                "value": "*MASKED_VALUE*"
            },
            {
                "confidence": 0.011200571929716,
                "value": "*MASKED_VALUE*"
            },
            {
                "confidence": 0.00068909498353888,
                "value": "*MASKED_VALUE*"
            }
        ]
    },
    "msg_id": "14IcWPcVMB5Ku7XbG"
}
```

**What is the expected behavior?**
The responses should be same at each API call if no changes/training has occurred in between.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2309851599065590

**Comment by aforaleka** [comment]
Hi @gaurav-huminos, can you let us know the text of the message so we can try to repro?

**Comment by gaurav-huminos** [comment]
@aforaleka The message was "standing desk". I tried the same API several times but not able to reproduce this behaviour. This happens once in a while and has happened with other texts for different intents as well. I've mentioned the message-id for both requests, so you can compare the results.

**Comment by aforaleka** [comment]
we'll look into it, but so far we can not repro the problem; we also don't store the msg_id so we can't use it to compare the results.

**Comment by mfakhryIntdv** [comment]
Same issue here
![try1](https://user-images.githubusercontent.com/51078124/60664058-39306500-9e61-11e9-83ab-01b790dab124.png)

![try2](https://user-images.githubusercontent.com/51078124/60664067-3f264600-9e61-11e9-8f22-15e60b0c7df9.png)

Two different results for the same query with time differance about 30 seconds.
