### ISSUE TITLE
UI Issue 2: Inbox is difficult to use

### ISSUE THREAD

**Issue by brightonBreezy** [wit-ai/wit#148]
After a bout of testing my inbox will have lots of expressions to validate, several all the same or similar, but it only shows a limited number at a time.

After validating one of the entries I should be able to re-evaluate certain of the rest of the inbox items so that Wit can apply what it has learned.

Also, sometimes, I have a need to validate a specific expression which will mean validating/cancelling all outstanding inbox items until the one I need appears in the list.

**Comment by l5t** [comment]
Sorry for the super late reply. Following the new Bot Engine Launch, we will be revamping soon the Inbox.

**Comment by l5t** [comment]
Closing as this issue is hold. Please reopen or create a new one if you still experience the issue. If you want to force the “re-evaluation” of your inbox before you've validated the 10 entries, a refresh should make it
