### ISSUE TITLE
Wit/location returns the misspelt location name

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#1480]
Hi team,
     If I input ""Time in duabi", wit returns the below data.

 {"_text":"time in duabi","entities":{"location":[{"suggested":true,"confidence":0.93188,"value":"duabi","type":"value"}],"intent":[{"confidence":0.94573255405996,"value":"get_time_info"}]},"msg_id":"1NZxu7deXWrnpVR6z"}

The location value is the misspell word "duabi"  instead of the correct location name "dubai".
Can I get the correct name.

Thanks in advance

**Comment by aforaleka** [comment]
Hi @anjaly, unfortunately our built-in wit/location only resolves location with their exact name. We'll consider this as a feature request but currently won't prioritize it. We suggest handling such unresolved locations in your application.
