### ISSUE TITLE
Training App Problem 

### ISSUE THREAD

**Issue by alorbach** [wit-ai/wit#1481]
App ID is 586bc070-b8e2-4f01-9d72-36a3f5d2402d

I have a problem training my app with sample data like: 
"show inventory" "American Motors" "Alliance" "DL" "2dr Sedan" "

The Keyword Alliance is detected as Model which is correct. And it is already added as Model however it always shows "Create new value..." which is wrong. I cannot add it as it is already added and I cannot remove it from the values as there is a display limit of 1000.

**Comment by aforaleka** [comment]
Hi @alorbach, we're sorry this is happening. Wit still recognizes alliance as model and has the value saved already, but because of the UI bug (mentioned in #226) it is shown as "Create new value". Will keep track of the issue there.
