### ISSUE TITLE
does wit support messenger audio for /speech endpoint ?

### ISSUE THREAD

**Issue by senateurritchie** [wit-ai/wit#1484]
Hi.
When I send text from Messenger Wit.ai brings the entities correctly,
however when an audio is received it does not bring the entities.
I need to make a new POST Speech API call for this.
Would not it be more convenient to bring the entities on the first call?

A doubt. How to send an audio directly from https://cdn.fbsbx.com, because the messenger audio is stored there. Or do I have to download the audio and then send it?

Thankfull.

**Comment by JoabMendes** [comment]
You have to download the facebook audio file, convert it from `mp4` to one of the accepted WIT audio formats (PCM (WAV), mp3, ulaw, and raw) and then, call the speech API sending that converted file.
