### ISSUE TITLE
Weird behavior when training is scheduled  

### ISSUE THREAD

**Issue by 91ns** [wit-ai/wit#1489]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
Wrong trait value is returned while the app is in scheduled mode. What's weird is that the wrong trait value is returned with a very high confidence level. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

This is how it shows in the understanding section 
![image](https://user-images.githubusercontent.com/25252530/59789559-d4103780-92d6-11e9-93d3-d5dd178edcb0.png)

This is how the expression is actually trained 
![image](https://user-images.githubusercontent.com/25252530/59789625-f2763300-92d6-11e9-9fad-f38a5f3a00e0.png)

Also, this expression was not previously associated with the wrong value.

**What is the expected behavior?**
To at least not return a random wrong value with high confidence. 

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2337938019605260

**Comment by patapizza** [comment]
Hi Nour,

Seems like the issue resolved itself:

<img width="967" alt="Screen Shot 2019-06-20 at 10 57 31 AM" src="https://user-images.githubusercontent.com/1015208/59859223-5ab22c80-934a-11e9-8d73-2a1872afaae8.png">


Please let us know if this happens again.
