### ISSUE TITLE
Application training stuck

### ISSUE THREAD

**Issue by asfyra** [wit-ai/wit#1490]
I first want to apologize for opening a new  task for the same issue again, but i could not reopen the [previous one](https://github.com/wit-ai/wit/issues/1248), although i tried to use that to get help, but probably due to it's closed state it was ignored.

Well our  app (5b1e505b-0e5f-484a-9e44-20d7c4ee12d1) is stuck again since 4th of June.
I can assure you that it was working just fine and we did not add any new intents since.
Could you please restart the app for us.

I also want to ask you if there is any progress with [App status stuck in ONGOING]( https://github.com/wit-ai/wit/issues/1402). 

We rely on wit for our company virtual assistant and we are looking fwd to extend our bot as much as possible. We put a lot of effort and resources on this and we need your support.

Thank you
Alex

**Comment by patapizza** [comment]
Hi Alex, commented on previous issue - we're still working on it, and the training will stay stuck until then. Thanks for your patience.
