### ISSUE TITLE
Partial importing from backup

### ISSUE THREAD

**Issue by cambrian-dk** [wit-ai/wit#1491]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug regarding importing
**What is the current behavior?**
When I imported from a zip file, only about 10% of the expressions were imported into the new app.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
The app was cloned from another app I have (ID 2213424035442845)
**What is the expected behavior?**
I didn't edit any of the zipped files, so by right all the expressions should be imported correctly.
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2476018955782055

**Comment by chatbotalex** [comment]
Hello,

I am having the same problem. I have made a back-up after my current app, but when I create a new app, after the back-up, only a part of my expressions are imported. The initial downloaded back-up is 73KB, but after I upload the new one, and let it train a while, the new download is only 39KB. Some of the trained utterances are gone.

The ID of the App I am backing-up: 2338349596222319
The ID of the new App after the import: 2273110556069074

Thank you!

**Comment by yukiplus** [comment]
Hello,

I have the problem, when I back up an app, it drops everything normal, but when I create a new app with this backup, the samples are not imported and the size of the backup also changes, in the current 361kb app in the new app stands with 31kb.

The ID of the App I am backing-up: 2214734048594857
The ID of the new App after the import: 2482912691770821

Thank you!

**Comment by FengyangZhang** [comment]
Can you verify that the expressions never get fully imported(after a fair amount of time)? Asking because the expressions importing might take long if you have many expressions.

**Comment by cambrian-dk** [comment]
Yep, I've just checked and most of the expressions are not in the clone.

**Comment by chatbotalex** [comment]
Hi,

I can also confirm this, after more than 24 hours there are less Samples in the back-up app than in my main app.
For example, on the intent 'invoice-details' i have 106 expressions in the backed-up app, as to 124 in the main app.

Thank you!

**Comment by jaisrael1** [comment]
I am having this same problem
source appId: 2071057342962927
clone appId: 2584749414889785

**Comment by FengyangZhang** [comment]
Thanks for reporting, we will be working on a solution.

**Comment by chatbotalex** [comment]
Any news?

**Comment by FengyangZhang** [comment]
the problem should be fixed now, can you try importing your apps again?
