### ISSUE TITLE
Why my app training is getting scheduled?

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#1492]
Hi team,
Can anyone please clarify why my app's ( with app id "2463006727052618") training is getting scheduled always.

Because of this we are not able to make any urgent changes or bug fixes. 
Can someone please help use to resolve this because if the training is getting scheduled it will not be feasible for us to use this service for our AI. 
Waiting for a reply soon.

Thanks in advance
Anjaly

**Comment by edskeizer** [comment]
Same here with app ID 2661968487209858

**Comment by anjaly** [comment]
Can some one please let us know why this is happening.

**Comment by brianebeling** [comment]
Same issue here, hovering over it shows that the scheduled training is supposed to be sometime this afternoon. That'd be in like 6-8 hours for me.

**Comment by arghya052** [comment]
Same issue with my BOT as well. 

APP ID: 2460764473976354

**Comment by jtliao** [comment]
apologies, your apps should be trained now
