### ISSUE TITLE
cannot export a .zip file with the data of the app

### ISSUE THREAD

**Issue by EssamEid614** [wit-ai/wit#1494]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
report a bug
**What is the current behavior?**
trying to export the app since yesterday and on clicking export the app the following message is returned
"Something went wrong while exporting your app 😔. Please try again, or contact us."
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
going to the app and trying to export it through settings .
**What is the expected behavior?**
exports a .zip file with all data to be imported in another app
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2208639952577836

**Comment by jtliao** [comment]
should be fixed now
