### ISSUE TITLE
API end point to generate Client Access Token 

### ISSUE THREAD

**Issue by mfakhryIntdv** [wit-ai/wit#1495]
**Feature request**

**What is the current behavior?**

Currently I can not generate Client Access Token through the API.

**What is the expected behavior?**

An API endpoint to generate or refresh the Client Access Token and returned also with app details.

**Comment by jtliao** [comment]
will bring this up with the team

edit: we don't plan on supporting this, I'd recommend using the UI for this.

**Comment by intdv** [comment]
hi i have the same problem
