### ISSUE TITLE
App Training scheduled after 12 hours

### ISSUE THREAD

**Issue by Sidhant-Chatterjee** [wit-ai/wit#1496]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
A feature to atleast set a training time and training button
**What is the current behavior?**
App says it would start training after 12 hours from now
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Should train within a short span of time
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2656236621118336

**Comment by Sidhant-Chatterjee** [comment]
Your app is scheduled to train at 6/27/2019 11:35:58 PM

**Comment by dupengling** [comment]
Thanks for reporting the issue. For some reason, your training is delayed and did not started immediately. We have manually started the scheduled training and it was completed after 8s.
