### ISSUE TITLE
Can't export data

### ISSUE THREAD

**Issue by gabriel-soga-movile** [wit-ai/wit#1498]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
A bug

**What is the current behavior?**
I cant export the data of my app

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- Settings page
- Export data
- Show pop-up `Something went wrong while exporting your app ☹️. Please try again, or contact us.`

**What is the expected behavior?**
Download the export

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2301314626643310

**Comment by jtliao** [comment]
Apologies, this should be fixed now.

**Comment by ladislauek** [comment]
I have this problem too. App ID 2387433377997084.

**Comment by iamkenken** [comment]
same problem. APP ID: 1117875451674104
