### ISSUE TITLE
Math-related entities return broken text under some conditions.

### ISSUE THREAD

**Issue by virtadpt** [wit-ai/wit#1499]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug.

**What is the current behavior?**
I've run into an interesting anomaly when training an intent to identify math problems.  I've defined an entity that recognizes simple math problems (2 + 2, absolute value of -7, 15 mod 2, and so forth). When testing it seems to do the right thing, but addition problems in particular have some characters missing.  For example `2 + 2` is returned as `2   2`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Text sent to wit.ai: `Switchboard, what is 6 + 3?`

Text is sent to intent: https://wit.ai/virtadpt/Exocortex/intents/calculator

Response sent back from API:

```
{
    "outcomes": [{
        "confidence": 0.499,
        "intent": "calculator",
        "_text": "Switchboard, what is 6   3?",
        "entities": {
            "math_problem": [{
                "suggested": true,
                "confidence": 0.92908970379192,
                "value": "6 3",
                "type": "value"
            }]
        }
    }]
}
```

The intent correctly identified the request (math problem), but the line `"_text": "Switchboard, what is 6   3?"` is not correct.

**What is the expected behavior?**
The response should look something like this:

```
{
    "outcomes": [{
        "confidence": 0.499,
        "intent": "calculator",
        "_text": "Switchboard, what is 6 + 3?",
        "entities": {
            "math_problem": [{
                "suggested": true,
                "confidence": 0.92908970379192,
                "value": "6 3",
                "type": "value"
            }]
        }
    }]
}
```

If I do an API test, the correct value for the string $.outcomes.[0].value is there:

```
{
    "_text": "Switchboard, what is 6 + 3?",
    "outcomes": [{
        "confidence": 0.499,
        "intent": "calculator",
        "_text": "Switchboard, what is 6 + 3?",
        "entities": {
            "math_problem": [{
                "suggested": true,
                "confidence": 0.92128793691079,
                "value": "6 + 3",
                "type": "value"
            }]
        }
    }],
    "WARNING": "DEPRECATED",
    "msg_id": "18dUgZItPa2JgpFQ5"
}
```

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
5546689f-0c17-4892-8fe7-c82519566369

**Comment by virtadpt** [comment]
Anybody?

**Comment by jtliao** [comment]
hi @virtadpt, apologies for the delay. I can't seem to repro this one, I sent the exact text that you did, but get this as the output:

`{"_text":"Switchboard, what is 6 + 3?","outcomes":[{"confidence":0.499,"intent":"calculator","_text":"Switchboard, what is 6 + 3?","entities":{"math_problem":[{"suggested":true,"confidence":0.95192007457122,"value":"6 + 3","type":"value"}]}}]}`

maybe something going wrong in the encoding after receiving a response?

**Comment by sfbalg** [comment]
How did you send it?  I've tried with both my code over here, and cURL from the command line.

What are the headers you sent with the request?  Character encoding is a distinct possibility.

**Comment by virtadpt** [comment]
How did you send the request? I've tried with both my code over here, and cURL from the command line.

Character encoding is a distinct possibility - what are the headers you sent with the request?

**Comment by jtliao** [comment]
nothing too special on my end, generated the cURL from the Settings page of an app to URL encode "Switchboard, what is 6 + 3?"

`curl -H 'Authorization: Bearer $TOKEN' 'https://api.wit.ai/message?q=Switchboard%2C%20what%20is%206%20%2B%203%3F'`
