### ISSUE TITLE
Issue with trained inputs

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#1500]
Hi team,
We have an app with app id 2305526219502316.
We are facing issues with some trained inputs today. the inputs that returned the data correctly is returning wrong responses now and also it is not constant. Sometimes in wit ui it shows correctly and in api it shows wrong and some other time reversely also.

Also the api is taking too long to return the response.

Can some one please help as it is gone live and, most commands are not working now.
Please consder it as high priority.

Thanks in Advance
Anjaly

**Comment by asfyra** [comment]
We are also getting wrong responses the last few hours appId: 5b1e505b-0e5f-484a-9e44-20d7c4ee12d1

Thank you

**Comment by arghya052** [comment]
Same issue here.. The response is taking a lot of time and we are receiving incorrect responses from Wit. The inputs which were properly trained are not working since today morning. 

Please look into the issue and revert since it is impacting the end users.

Thank you

**Comment by jtliao** [comment]
Can you please provide some examples with expected/actual outcomes so I can take a look?

**Comment by asfyra** [comment]
Hi @jtliao, I can provide some examples from our app with id 
5b1e505b-0e5f-484a-9e44-20d7c4ee12d1

Intent_faq/password_lock
Έβαλα λάθος κωδικούς, τι κάνω?
θελω να αλλαξω κωδικο

Intent_general/greeting
Hello
Hi
Καλημέρα
καλημέρα και καλό μήνα

Intent_general/time
μήπως ξέρεις τι ώρα είναι?
παρακαλώ πείτε μου την ώρα


Thank you
Alex

**Comment by serdalbayram** [comment]
same here 5ab2407f-561a-45df-ab6c-139009d7b2b6

**Comment by chatbotalex** [comment]
Same here. Apart from the train taking a long time, being scheduled hours later, the successfully trained utterances don't work, and today even some old utterances, trained long ago, stopped working, or need to be imputed 3 or 4 time to be recognized. (APP id: 2338349596222319).

Thank you!

**Comment by ozbusraa** [comment]
We have exactly the same problem for app: 2060769614041304

I think this is a general performance problem for all bots

**Comment by jtliao** [comment]
again, please provide an example expected/actual outcome if possible; i'm not familiar with the different languages, making it difficult to debug/give a test query. if you are no longer seeing the issue, please react to this with a thumbs up

@asfyra unfortunately your app is very large and experiencing problems with training


sincere apologies about the inconveniences for everyone, we are working to fix this ASAP

**Comment by arghya052** [comment]
> 
> 
> Can you please provide some examples with expected/actual outcomes so I can take a look?

App ID : 2460764473976354

Text : Show anomaly trends
Expected Intent : Get_Anomaly_Count_By_Circle

But it is not giving the correct response and when trying from Rest Client the request is taking more than 100 secs and getting timed out. 

Please have a look at it and advise.

Regards,
Arghya

**Comment by jtliao** [comment]
@arghya052 i can't seem to reproduce, when i try that i get the correct response pretty much instantly

**Comment by 91ns** [comment]
We're having the same issue with multiple apps. it's not constant, at certain times the response becomes very slow, over 10 seconds to respond.

**Comment by jtliao** [comment]
update: things look back to normal for the past hour or so

**Comment by asfyra** [comment]
@jtliao I can confirm the app is responding and it's responding fast again. 

Thank you @jtliao and the wit.ai team for your efforts

Alex

**Comment by anjaly** [comment]
Thank you team. wit.ai is back for us also.
Thank you all for your effort.
