### ISSUE TITLE
Date Range is not working

### ISSUE THREAD

**Issue by landman** [wit-ai/wit#1501]
Hi, i m working on a booking site in german and the user should also search with free text. 
For example: "Suche Flug vom 12. bis 18. August von Berlin nach New York" but wit did not understand the first Number in a Date Range. For example:

![image](https://user-images.githubusercontent.com/5006372/60641569-a249b580-9e2c-11e9-8eed-a10ce6e2f870.png)

I tried different dates but its not working. How can i train it? 

One date is working. For example: ""Suche Hotel am 12. August in Berlin".

Thanks and Best from Berlin, Dennis

**Comment by pengtxiafb** [comment]
Hi, What language is this? and What is your expected outcome, looks like Wit may not understand your language.

**Comment by patapizza** [comment]
Hi @landman,

Thanks fo reporting. `wit/datetime` is powered by [Duckling](https://github.com/facebook/duckling). Please report the issue there, with what is expected and what is the current result. Even better, feel free to improve the [German rules for Time](https://github.com/facebook/duckling/blob/master/Duckling/Time/DE/Rules.hs) and add [tests](https://github.com/facebook/duckling/blob/master/Duckling/Time/DE/Corpus.hs) to reflect the changes.

Thanks!

**Comment by landman** [comment]
> Hi, What language is this? and What is your expected outcome, looks like Wit may not understand your language.

Its german. The result should be 12.08. and 18.08.

**Comment by landman** [comment]
> Hi @landman,
> 
> Thanks fo reporting. `wit/datetime` is powered by [Duckling](https://github.com/facebook/duckling). Please report the issue there, with what is expected and what is the current result. Even better, feel free to improve the [German rules for Time](https://github.com/facebook/duckling/blob/master/Duckling/Time/DE/Rules.hs) and add [tests](https://github.com/facebook/duckling/blob/master/Duckling/Time/DE/Corpus.hs) to reflect the changes.
> 
> Thanks!

The tests dont have a simple Date Range. The first Date is always wrong.
