### ISSUE TITLE
Get error "Something went wrong. We've been notified" on Facebook API

### ISSUE THREAD

**Issue by offengenden** [wit-ai/wit#1502]
I want to report a bug

My wit account connected to Facebook messenger platform. 
Everything works fine util yesterday when I suddenly started to get error message in NLP section.

Here is the JSON I get:
{
  "object": "page",
  "entry": [
    {
      "id": "hidden",
      "time": 1562219547913,
      "messaging": [
        {
          "sender": {
            "id": "hidden"
          },
          "recipient": {
            "id": "hidden"
          },
          "timestamp": 1562219542236,
          "message": {
            "mid": "NOi39paFjNrQIRirf9Szn2SK18IyjU-_rIMKn3VhXtBwc19qI3zfoBF998wzaPR1BHTu6p5yTq6ELGqI6md8DQ",
            "seq": 0,
            "text": "Some text",
            "nlp": {
              "errors": [
                {
                  "code": "unknown",
                  "message": "Something went wrong. We've been notified"
                }
              ]
            }
          }
        }
      ]
    }
  ]
}

App ID: 2167709739965060

**Comment by jtliao** [comment]
hi, I tried to reproduce and couldn't, is this still happening?

**Comment by jtliao** [comment]
never mind, the issue is found. merging with #1500
