### ISSUE TITLE
Some Apps have slow response times

### ISSUE THREAD

**Issue by idanadut** [wit-ai/wit#1504]
**report a *bug*, or ask a *question* about wit?**
BUG/Issue

**What is the current behavior?**
some of my apps have very slow response time (api & wit.ai web client), at least 7-8 seconds. Only in the past 3-4 days. Have I reached some limit?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
for example app ID: 5abbadbf-0e11-4e85-9090-d8afae916db4
send a request with this hebrew query: "אפשר לטוס רק לכיוון אחד"  -> response time is very long.

go to the wit.ai web client of my app, or call an api call, see the long response time.

**What is the expected behavior?**
1-3 seconds response time like I always experienced.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
All of these apps:
1990367351029043
2699917330080017
5b4cb074-8560-4fa9-9cd1-7f95bccb623d
2498067833556402
5abbadbf-0e11-4e85-9090-d8afae916db4

**Comment by serdalbayram** [comment]
the same problem in issue #1500

**Comment by jtliao** [comment]
merging with #1500
