### ISSUE TITLE
Can not compile libwit

### ISSUE THREAD

**Issue by dingfs** [wit-ai/wit#151]
Hi, I am trying to build a simple rust project. However, I can not compile libwit, seems like there are syntax errors? Can anyone help me? Thx.

**Comment by martinraison** [comment]
Hi, apologies for the very late reply. We haven't had time to work on libwit recently and it is now community maintained. Your best bet for using Wit.ai is probably to call the HTTP API directly (there are now some good clients for Rust). See https://wit.ai/docs/http/latest for details.
