### ISSUE TITLE
Create an entity that works as a slot value

### ISSUE THREAD

**Issue by cchrism0426** [wit-ai/wit#1511]
I'm trying to create something that can add shopping products to a list. So far example, when you type to the bot "I want to add crocs", the bot will recognize crocs is what you want to add, and mark it as a value of an entity. How would I go about doing this? Am I using free-text or keywords? I've tried using free-text and keywords and it's having a hard time recognizing words that aren't in my keywords.

**Comment by lycai-fb** [comment]
Hi cchrism0426, and welcome to wit.ai!
Try setting it to free-text only, and annotating some more phrases.
For instance, if you annotate "I want to add crocs", "I want to add loafers", "I want to add high heels", etc. the bot should be able to pick up on the general structure pretty quickly.
![Example Screenshot](https://user-images.githubusercontent.com/52939420/61421330-7feb7980-a8bb-11e9-89b2-9f0075dc1c18.png)

**Comment by cchrism0426** [comment]
What if I want to be able to tell the bot to add crocs with multiple phrases, like "Please add crocs" or "Add crocs for me". Would I have to type this for all the different types of products I want to add? Like "Please add loafers", "Add loafers for me", and so forth. Also, I'm trying to get it to recognize a really diverse range of products, like also groceries, electronics, books, etc. Is this possible through training it this way? Or would I have to include training data from each type of product I want it to recognize. Thanks!
