### ISSUE TITLE
handling text emoji's

### ISSUE THREAD

**Issue by bmcclenahan** [wit-ai/wit#1513]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question
**What is the current behavior?**
text emoji's are treated as normal text and assigned to a custom entity

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
when :-) is entered as text it is assigned to an entity that's not appropriate

**What is the expected behavior?**
is there an inbuilt entity to recognize and collect text emoji's ? if not could there be one ? eg
wit/emoji ... could be used in conjunction with /sentiment
if this isn't possible, what would be good practice for catching text emoji input and not having the text assigned to an entity?

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by RongrongQiu-fb** [comment]
Thanks for report this problem! We currently don't support text emoji now, but we will raise it with the team! #

**Comment by bmcclenahan** [comment]
what would be good practice for catching text emoji input and not having the text assigned to an inappropriate entity?

**Comment by aforaleka** [comment]
I suggest creating your own custom entity with keyword (maybe + free-text lookup) that catches text emoji input. This recipe can help to decide which lookup strategies you want: https://wit.ai/docs/recipes#which-entity-should-i-use

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
