### ISSUE TITLE
Cannot export data

### ISSUE THREAD

**Issue by gregor10** [wit-ai/wit#1514]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug

**What is the current behavior?**
I cannot export zip data of the app

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
There is an error message when trying to export app data from UI.
The error message is: "Something went wrong while exporting your app ☹️. Please try again, or contact us."
The api call to "/export" service returns 500 status code and "unknown" error code in the body.

**What is the expected behavior?**
ZIP data of the application

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2324613967589734

**Comment by jtliao** [comment]
fixed
