### ISSUE TITLE
Speech recognition is not supported for language: Hebrew

### ISSUE THREAD

**Issue by ZombieAlla** [wit-ai/wit#1516]
Hello, I would like to report a bug

I am sending a CURL request with a wav file for speech-to-text recognition. If I Choose in App Details: English, everything works, but when I switch to Hebrew it doesn't. I get the following error:
 { "error" : "Speech recognition is not supported for language: Hebrew",
  "code" : "bad-request" }

My AppID is 2027695534000947

Thank you,
Alla

**Comment by RongrongQiu-fb** [comment]
> Hello, I would like to report a bug
> 
> I am sending a CURL request with a wav file for speech-to-text recognition. If I Choose in App Details: English, everything works, but when I switch to Hebrew it doesn't. I get the following error:
> { "error" : "Speech recognition is not supported for language: Hebrew",
> "code" : "bad-request" }
> 
> My AppID is 2027695534000947
> 
> Thank you,
> Alla

Hi Zombie,
Thank you for report the problem! Unfortunately we don't support Hebrew currently.
Thanks,
Rongrong

**Comment by ZombieAlla** [comment]
Thank you for the answer.
I know for a fact that some applications use WIT's speech to text with Hebrew. For instance: Voicy (https://voicybot.com/). I'm adding the following code snippet from their open source code:

`async function recognizePath(path, token) {
  return new Promise((resolve, reject) => {
    const options = {
      method: 'POST',
      hostname: 'api.wit.ai',
      port: null,
      path: '/speech?v=20170307',
      headers: {
        authorization: `Bearer ${token}`,
        'content-type':
          'audio/raw;encoding=signed-integer;bits=16;rate=16000;endian=little',
        'cache-control': 'no-cache',
      },
      timeout: 120 * 1000,
    }
    const req = https.request(options, res => {`

How can it be that they can send you Hebrew speech to text audio files, while I cannot?
Maybe there is some special/paid service I can join to?
Thanks, Alla

**Comment by jtliao** [comment]
Hey @ZombieAlla, we're currently doing some work on the speech engines we provide, and thus have been limiting usage to existing users. I've provided you access though.

**Comment by romul** [comment]
@jtliao I also faced into this issue. Could you enable access for AppID 2346421265441191? 
Thank you in advance.

**Comment by patapizza** [comment]
@romul done

**Comment by romul** [comment]
@patapizza Thank you very much ❤️

**Comment by idanadut** [comment]
Hi @jtliao, I also ran into this issue this week trying to develop Hebrew speech app. Can you enable access to my account or to app ID: 4084030051614516 ?

Thanks!

**Comment by jtliao** [comment]
hi @idanadut, unfortunately we no longer have the capability to support speech recognition for Hebrew. We hope to bring it back at some point later in the year, in the meantime please refer to https://wit.ai/faq for the speech languages we support.

**Comment by simcha1** [comment]
Hey, it's been 3 years
Please return your support for the Hebrew language
I really need this
Thank you so much!
My app ID is 255179775557238
