### ISSUE TITLE
My app ID is set to train many hours into the future

### ISSUE THREAD

**Issue by sebastianarena** [wit-ai/wit#1517]
- Do you want to request a feature, report a bug, or ask a question about wit?
Bug

- What is the current behavior?
I've made a single change to train a new intention, and now it says its going to re-train in 5hs

- What is the expected behavior?
I expect to have it re-train sooner. I understand I made more than the normal set of changes, but 5hs is a very long time, I really need to test this ASAP!

What is the App ID where you are experiencing this issue (if applicable)?
2018922608213854

**Comment by jtliao** [comment]
apologies, i went ahead and re-trained your app for now, we're working on fixing the training scheduling logic in the near future

**Comment by lpiacquadio** [comment]
@jtliao I have the same issue, my App ID is: 2340144709385611

**Comment by RongrongQiu-fb** [comment]
> @jtliao I have the same issue, my App ID is: 2340144709385611

Retrained.
