### ISSUE TITLE
Long delay for training

### ISSUE THREAD

**Issue by TimNZ** [wit-ai/wit#1518]
long delay in training ("scheduled")

Estimate is for 8 hrs

App id = 2891044107634916

**Comment by TimNZ** [comment]
I exported the app and created a new one from zip and that is now training realtime-ish.
2968181659890174

**Comment by TimNZ** [comment]
Now I have to wait 6 hours for 2968181659890174 to train.

Can you please publicly publish guidelines on delays to training if this is designed behaviour

**Comment by jtliao** [comment]
merging #1517
