### ISSUE TITLE
App stuck in training

### ISSUE THREAD

**Issue by klemensz** [wit-ai/wit#1519]
The following app is stuck in "training ongoing": 5902737c-e922-4695-bed3-874f70abb502 ("Your app is currently training. Last time it took your app 26 s to train.")

Can you please reset it?

Thanks!

**Comment by RongrongQiu-fb** [comment]
last trained 07/30 08:36:43 AM, last duration(s) [26s, 1393s, 39s, 162s, 26s], 0 intents, 3 traits, 6 ners, 1756 samples
Please reopen if issue back
