### ISSUE TITLE
Wrong/Broken link to get  "witd-arm executable"  for Raspberry Pi

### ISSUE THREAD

**Issue by szv** [wit-ai/wit#152]
Hi, everyone,
I want to get wit running on Raspberry Pi.
But the link to get the 'ARMv6 executable' in the documentation seems to be broken (https://github.com/wit-ai/witd/blob/master/witd-arm?raw=true).
So what shall I do?

**Comment by martinraison** [comment]
Thanks for reporting! You can find the executable here: https://github.com/wit-ai/witd/releases

**Comment by szv** [comment]
Thank you!
:-D

**Comment by raminia** [comment]
The link is broken again.

**Comment by pagalengineer** [comment]
not able to run with execuatable arm getting errors 
root@raspberrypi:/pagal/gmail/microsoft# ./witd-arm &> witd.log &
[1] 2442
root@raspberrypi:/pagal/gmail/microsoft# cat witd.log
-bash: ./witd-arm: No such file or directory
[1]+  Exit 127                ./witd-arm &>witd.log
root@raspberrypi:/pagal/gmail/microsoft#


any help out there ?
