### ISSUE TITLE
questions about customizing the speech recognition

### ISSUE THREAD

**Issue by lenyturmel** [wit-ai/wit#1520]
question

Hi,
I am new to Wit.AI.
Regarding the speech recognition capabilities, I have tow questions:

1. is it possible to add custom vocabularies like medicine, sciences, manufacturing vacabularies? 
2. is it possible to train the model with audio/transcription in order to adapt the speech recognition to a specific noisy environment or to specific regional accents?

Thank you for your help

**Comment by wangsnowyin11** [comment]
Hi,
For your questions, 
1. Could you elaborate more on where do you want to add those vocabularies to? If you are referring to the entity list, that's yes. You could type in your sentence, and select the word or the phrase that you need to create a new entity besides the ones in the list. In UI, entity creation option would be shown to you.
 
2. Currently no. Wit doesn't support training model on audio/transcript, only text utterances are supported. We do have plan on it though. 

Hopefully my answer helps. Thanks for using our product!

**Comment by lenyturmel** [comment]
Hi
Thank you for your quick answer.
For the vocabulary, I would like to know if it is possible to add jargon, proper nouns (names, products, companies, work tools, etc.), acronyms or any other words specifics to an industrial domain which may be wrong recognized by the speech recognition.

Good news to know you plan to support additionnal trainings on custom audio/transcript data  .
thanks

**Comment by wangsnowyin11** [comment]
Hi,
I sees your question. Sorry that we currently just have one speech model. That's really reasonable feature request. We would definitely put it into schedule to provide customizable speech models.

Hope it helps. Thanks!
