### ISSUE TITLE
App is scheduled to train for long time, and after the status turns to Done, it is not giving expected result.

### ISSUE THREAD

**Issue by mohanstriker03** [wit-ai/wit#1521]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by mohanstriker03** [comment]
This is my app id: 3282981305053238
I am setting the role for wit number entity, then app is scheduled to train at post 8 hours of training.
After status changes to Done, It is not giving the expected result as I have trained

**Comment by wangsnowyin11** [comment]
Hi,
I just re-train the model for you, can you check whether now it works as expected?

Hope it helps, thanks for using our products!
