### ISSUE TITLE
App is stuck in On Going 

### ISSUE THREAD

**Issue by 91ns** [wit-ai/wit#1522]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
App stuck in training
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2393305450751956

**Comment by wangsnowyin11** [comment]
Hi 

I just helped you to schedule the retraining for the app, and now it's done.

Hope it helps. Thanks for using our product! Let me know if there are any other issues.
