### ISSUE TITLE
Cannot export app data

### ISSUE THREAD

**Issue by neoighodaro** [wit-ai/wit#1523]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?** 
Bug

**What is the current behavior?** 
I can't export the app data as zip

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.** 
Clicking the export button I get "Something went wrong while exporting your app 😔. Please try again, or contact us."

**What is the expected behavior?** 
The application data is downloaded as a zip file

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.** 
3469212549771826 and 3036856932992893

**Comment by FengyangZhang** [comment]
Hi there, you should be able to export your apps now!
