### ISSUE TITLE
Cannot export app data - Keeps failing

### ISSUE THREAD

**Issue by timothyapplewhite** [wit-ai/wit#1524]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
The data of my application cannot be exported as a zip file

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Clicking the button "Download .zip with your data" results in "Something went wrong while exporting your app 😔. Please try again, or contact us."

**What is the expected behavior?**
The application data is downloaded as a zip file

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2251783211564721

**Comment by timothyapplewhite** [comment]
Could someone please assist here? This issue is getting rather urgent.
Thanks & Best regards

**Comment by FengyangZhang** [comment]
Sorry about that, the problem should have been fixed.
If anyone else has similar problem please leave a comment here, thanks!
