### ISSUE TITLE
Stuck in 'ongoing'

### ISSUE THREAD

**Issue by TimNZ** [wit-ai/wit#1525]
App id: 2968181659890174
About 9 hours now.

As per the other issues reporting the same.

**Comment by LemonAndroid** [comment]
thhis way . it . willg et really . smart

just . wait

**Comment by moraitis55** [comment]
My app is stucked in ongoing for days now. 
**App id:**  2702444876450736

**Comment by kingseaeast** [comment]
They should both be fixed now. thanks!
