### ISSUE TITLE
wit.ai does not deliver Payload when user Facebook language is not en_EN

### ISSUE THREAD

**Issue by asierraserna** [wit-ai/wit#1526]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

Hello!

I need some help, I don't know where else to check. I am getting several 503 errors when using the messenger bot, but when I test with my user, and some other users test too, it works really fine, even via messenger plugin in my webstie www.partidito.com.

It looks as attached. Just sometimes the platform is not sending anything to my server and is logging the 503 errors. Seems to fail when the Facebook User Language is different than en_EN

I am checking with the Infra guys of the webhosting, but they cannot see anything wrong from their side, and the code seems to be fine.

**What is the current behavior?**

The bot works fine if the Facebook language of the user is en_EN, but if is es_XX or pl_PL the bot is not sending the payload to my server to process.

![image](https://user-images.githubusercontent.com/19590141/62656644-f59bb000-b964-11e9-9f03-07f791d3978b.png)

![image](https://user-images.githubusercontent.com/19590141/62656700-149a4200-b965-11e9-93c5-0ed8f40f381e.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

some extra information I just noticed. In wit.ai I see the log, and the difference between the ones that work, and the ones that fail might be the Locale: es_XX and pl_PL are failing, while en_XX seems to work just fine. 

![image](https://user-images.githubusercontent.com/19590141/62656720-24b22180-b965-11e9-9864-2a51eebfb299.png)

Yesterday morning a user with locale pl_PL received many messages from the platform. That user was testing the bot the day before around 1 PM, but didn't receive any messages at that moment. Then suddenly many messages arrived automatically yesterday at 8AM, and I was not changing anything in my server. That was really strange. It can be seen in the screenshot.

![image](https://user-images.githubusercontent.com/19590141/62656742-30054d00-b965-11e9-891e-44f21750f66c.png)

After that, the server received a lot of messeges and answered many times, like if a queue from facebook messenger was released suddenly.

![image](https://user-images.githubusercontent.com/19590141/62656776-3dbad280-b965-11e9-8703-f0263104dfb8.png)

Definitively the problem is the language of the user in Facebook. It always work if is in English, it sometimes work if is in Spanish and doesn't work if is Polish. I believe the problem is in Wit.AI.

The test is simple, change you Facebook language to Polish and try my bot (it is in Patidito.com). Then change it to english and try again.

If in English, the bot will answer automatically right away, if the language of the User is in Polish, there will be no answer because the messages are not arriving to my server.

**What is the expected behavior?**

The bot should always anser, not matter what lnguage has the user in their Facebook Account

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

https://wit.ai/alejandrosierra/Partidito.com
App ID 5aa9a49c-6ab7-47fe-b6b8-2650ec54b46a

**Comment by LemonAndroid** [comment]
could b e everything

**Comment by LemonAndroid** [comment]
just wait a bit and believe in god pls

**Comment by LemonAndroid** [comment]
soon you'll see the model . schedulled for . a time in a . few . hours . etc

**Comment by LemonAndroid** [comment]
https://satin-dew-1.glitch.me

**Comment by asierraserna** [comment]
hello LemonAndroid, I do not understand well what you mean, but ok. The messages arrived randomly yesterday at 5Pm CET after about one day. I can see the log is receiving those messages at about that time. I dont have queue system in my server, is all Syncronous, so definitively was that wit.ai or facebook messenger platform took about a day to send the messages to my server.

wit.ai community, is there any log of receiving and sending payloads in wit.ai that could be checked?

cheers!

**Comment by kingseaeast** [comment]
Hi @asierraserna,

Thanks for reporting this. We're looking into this issue.

**Comment by asierraserna** [comment]
Hello guys, the problem might be in Facebook messenger. I tested today disabling wit.ai, and the situation is the same. If the user has facebook in english, the bot works fine, but in polish or spanish it doesn't.

I hope this helps.

Alejandro

**Comment by patapizza** [comment]
Hi Alejandro,

Are you calling wit.ai directly or using [Built-in NLP](https://developers.facebook.com/docs/messenger-platform/built-in-nlp)? As a side note, you might want to build a wit.ai app for each of the languages you support (English, Spanish, Portuguese) and map them using [language identification](https://medium.com/wit-ai/introducing-language-identification-38d714f86ffc) through Built-in NLP.

**Comment by asierraserna** [comment]
Hello @patapizza, I am using the built-in NLP as shown in the page:

![image](https://user-images.githubusercontent.com/19590141/63262822-42498a00-c287-11e9-905b-1a000e27a829.png)

Regarding adding the additional languages, I tried that about a week ago, but I was receiving some errors when registering the custom token language. Now I just tried it again, and the system allow me to enter them! 👍 

I see the team has been fixing stuff! 🥇 

I will test this with users with different User Language to see how it goes, and will update you guys.

Thanks!

**Comment by patapizza** [comment]
Awesome, closing this for now. Looking forward to your update!

**Comment by asierraserna** [comment]
Hello @patapizza! Sadly the problem still exists. I have a user which has facebook in Polish, and another one in English. The bot works with the one in english, but doesnt for the polish one. 

Is not about the language the user is using to send messages since for both I am testing in english.

Simple, the Locale pl_xx is not processing to deliver the payload to my server.

I think the problem is in the messenger platform since with wit.ai deactivated the same problem persists

:(

**Comment by asierraserna** [comment]
Can this bug be reopen? Or should I create a new bug but for facebook messenger?
