### ISSUE TITLE
Login problem, unable to login

### ISSUE THREAD

**Issue by josevahljr** [wit-ai/wit#1529]
Hi, anyone having the issue with wit.ai login via facebook or Giyhub.
In Console, it is showing POST https://api.wit.ai/me/facebook_signin 500 (Internal Server Error)

**Comment by nopain2110** [comment]
i have the same problem

**Comment by nopain2110** [comment]
I have the same problem

**Comment by GeorgeParadise** [comment]
Hi, same here.

**Comment by jtliao** [comment]
working on a fix

**Comment by jtliao** [comment]
should be back to normal, sorry about that
