### ISSUE TITLE
errors while rebuilding Android demo project

### ISSUE THREAD

**Issue by vanderleisp** [wit-ai/wit#153]
while rebuilding the project Android Studio shows these errors, but first one (declare public for a class) is already there, so whats wrong ?

\projects\wit\demoAndroid\Wit_Eval\app\src\main\java\ai\wit\eval\wit_eval\MainActivity.java
Error:(25, 8) error: class MyActivity is public, should be declared in a file named MyActivity.java
Error:(32, 32) error: cannot find symbol variable activity_my
Error:(35, 13) error: cannot find symbol method enableContextLocation(Context)
Error:(43, 41) error: cannot find symbol variable my

And java is like:

public class MyActivity extends ActionBarActivity implements IWitListener {

    Wit _wit;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_my);
        String accessToken = "";
        _wit = new Wit(accessToken, this);
        _wit.enableContextLocation(getApplicationContext());

    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.my, menu);
        return true;
    }

So, any help ?

thanks,
Vanderlei

**Comment by patapizza** [comment]
Hi @vanderleisp,

1. Be sure that your file name is the same as the class name: `MyActivity.java` with top class `MyActivity`, and/or `MainActivity.java` with top class `MainActivity`.
2. Did you create the file `activity_my.xml` under `app/res/layout`? (see [step 1](https://wit.ai/docs/android/3.1.0/quickstart))
3. Do you have a file named `my.xml` under `app/res/menu`? You can copy `menu_main.xml` and replace `MainActivity` by `MyActivity` in the file.

Let me know if that helps.

Thanks
