### ISSUE TITLE
Training samples are being dropped when the app is in "Scheduled" state

### ISSUE THREAD

**Issue by 91ns** [wit-ai/wit#1530]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
When the app is in "Scheduled" state and new samples are sent, the API returns a true response, but the new samples are not considered. 
We have to wait till previously scheduled training is finished then send new samples. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2101186346677141

**Comment by patapizza** [comment]
Hi @91ns, this is expected: when the state is "Scheduled", the latest samples aren't being considered until the new training is complete ("Done"). When new samples are sent during a training ("Ongoing"), the training gets automatically rescheduled right at the end of the ongoing training to account for the latest samples.
