### ISSUE TITLE
Unable to import agent (after backup) containing entities with a lots of values (>500)

### ISSUE THREAD

**Issue by erudyk** [wit-ai/wit#1533]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
For big entities containing a lot of values, entry is created empty :(
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Build an entry with a lots of values inside (>500). Download as ZIP file. Restore agent from ZIP. Long entry created empty. Download that agent and you end up with much smaller file -> agent data lost.
**What is the expected behavior?**
Restore works and able to restore it's own backups.
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
Original App - 2853392304677134, restored App - 3202596139758175

**Comment by yukiplus** [comment]
Hello, I have a similar problem in an app
To download an app backup, one of the entities has more than 500 values, when I created a new app with this backup, it was created but:
- some values didn't go up
- There was another "BUG" where some values with expressions were doubled, tripled, has a value that is appearing 15 times
the entity in question is "object"
The app ID: 3075748502467413

**Comment by FengyangZhang** [comment]
Sorry for the delay, we've made import more reliable, you should be able to get all values fully imported now. In the meantime, if you are using the import/export to version your app, we recently released a 'real' versioning feature and you can find out more in the docs: https://wit.ai/docs/recipes#version-your-app
