### ISSUE TITLE
Stuck on Schedule more than 15 hours

### ISSUE THREAD

**Issue by newint33h** [wit-ai/wit#1535]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question

**What is the current behavior?**
Suddenly my app shows "Your app is scheduled to train at 28/8/2019 23:19:45" since today morning, thats more than 15 hours. Is that long period of time normal? Should I expected to have longer periods of training from now on?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Usually the training starts each time I change something.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2405638432816671

**Comment by jtliao** [comment]
apologies for the inconvenience, i went ahead and re-trained your app
