### ISSUE TITLE
And it's stuck in 'ONGOING' for me as well

### ISSUE THREAD

**Issue by danielkhan** [wit-ai/wit#1536]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
App is stuck in ONGOING for 20 minutes now

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Add training phrases

**What is the expected behavior?**
Reliability that the training does not get stuck

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2816517318361716

I am currently preparing an online course and I'm seeing this behavior constantly.
Sometimes it works after some time, sometimes I just have to start over.
This is very frustrating and your replies on previous tickets with the same problem are frustrating as well.
You keep mentioning that the training did last 13s or similar figures but the metrics that show up for the training duration are wrong. Maybe the training itself takes 13s but it may sit in your queue for an hour before.

This is a pretty hard sell for an online course that would feature your product and I think you should try to fix it. You are facebook. You have the resources to do that better.

Reference: https://github.com/wit-ai/wit/issues?utf8=%E2%9C%93&q=ONGOING

**Comment by jtliao** [comment]
hey @danielkhan, thanks for the candid feedback. you're right that we should be doing better, and frankly it's not acceptable that this is not working consistently. we really do have work in the pipeline to improve our training infrastructure

as for your specific app, it seems like it's been trained so i won't take any action there, but please don't hesitate to reach out with any further questions.

**Comment by nimaftf** [comment]
https://github.com/wit-ai/wit/issues/1537

‫‪Jason Liao‬‏ <‪notifications@github.com‬‏> در تاریخ سه‌شنبه ۳ سپتامبر
۲۰۱۹ ساعت ۱:۲۸ نوشت:‬
