### ISSUE TITLE
persian speech recognition

### ISSUE THREAD

**Issue by hosseinmh** [wit-ai/wit#1539]

**Comment by hosseinmh** [comment]
hi 
when is send post request for speech endpoint for persian voice ,
api send error 
{
  "error" : "Speech recognition is not supported for language: Persian",
  "code" : "bad-request"
}
thanks for your time

**Comment by robustcoffee** [comment]
Could you provide the app id?

**Comment by hosseinmh** [comment]
hi 
app id is  2289574471165770

**Comment by hosseinmh** [comment]
and I have another problem in using speech api 
when I use curl command api response send error about file audio 
my request is :
curl -XPOST 'https://api.wit.ai/speech?v=20170307' \
   -i -L \      
   -H "Authorization: Bearer $my_token" \
   -H "Content-Type: audio/wav" \
   --data-binary "@as.wav"
[sound.zip](https://github.com/wit-ai/wit/files/3603823/sound.zip)

and sound is attach

**Comment by hosseinmh** [comment]
error response
![Screenshot from 2019-09-12 09-59-03](https://user-images.githubusercontent.com/12621753/64756384-003cfc80-d544-11e9-8103-7d0a093b113b.png)

**Comment by hosseinmh** [comment]
hi 
thanks for response 
is my app id is open for perisan language ?

**Comment by jtliao** [comment]
We no longer have the capability of supporting Persian speech recognition.
