### ISSUE TITLE
Support for vietnamese

### ISSUE THREAD

**Issue by manhtuhtk** [wit-ai/wit#154]
Hi wit team,

Do u have any plans to support vietnamese language?

Thanks

**Comment by blandinw** [comment]
We don't have specific plans for Vietnamese for the moment.
Part of adding a language to Wit is to provide a way for Wit to understand dates, etc.
We have open-sourced our parser [here](http://duckling-lib.org/) if you would like to contribute some Vietnamese content to the project.
