### ISSUE TITLE
Count total samples submitted and inbox samples

### ISSUE THREAD

**Issue by qfavor** [wit-ai/wit#1541]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Feature

**What is the current behavior?**
The 'Samples' data page doesn't display the number of total samples sent.

**What is the expected behavior?**
It would be nice if there was a count on the webpage with the amount of samples I have submitted so far. :)

**Comment by robustcoffee** [comment]
Thank you. Mark it as feature request.

**Comment by rahadianahmad** [comment]
would be great if theres a REST api support as well, something like `/samples/count`

**Comment by jtliao** [comment]
This is now displayed in the refreshed Wit UI.
