### ISSUE TITLE
Receiving empty entities object for some requests - /sentiment

### ISSUE THREAD

**Issue by qfavor** [wit-ai/wit#1545]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug/Question

**What is the current behavior?**
The response sometimes comes with "entities":{} - empty entities, even though the application has one entity. 

**What is the expected behavior?**
Is this because of a lack of sample data? I have added sample data and I keep adding it as it keeps popping up in my Inbox, but some messages seem to always come back with an empty entities object.

**Comment by jtliao** [comment]
Hey @qfavor, apologies for the delay-- there's a filter on confidence, so if the entity detected doesn't exceed the threshold, it won't be returned.
