### ISSUE TITLE
How to add "by the start of next week" to wit.ai wit/datetime?

### ISSUE THREAD

**Issue by commandos1985** [wit-ai/wit#1546]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
feature
**What is the current behavior?**
the phrase "by the start of next week" is not recognized by wit/datetime entity

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
processed the same way the other similary phrases are processed. Like "by the end of next week"
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID: 2695345620489080

**Comment by jtliao** [comment]
hi @commandos1985, apologies for the delay-- `wit/datetime` is supported by Duckling (https://github.com/facebook/duckling), it's open-sourced and you're welcome to support a pull request, thanks!
