### ISSUE TITLE
App stuck in training

### ISSUE THREAD

**Issue by kumangxxx** [wit-ai/wit#1547]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
my app stuck in training

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Usually it takes minutes for training, now it takes long time

**What is the expected behavior?**
Normal training speed

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
APP ID: 3210381992313056

**Comment by kumangxxx** [comment]
anyone ?

**Comment by robustcoffee** [comment]
Thank you for filing the issue. It looks your app's training has been completed in 9/12. Can you confirm?

**Comment by kumangxxx** [comment]
yes, its completed. may i know whats the cause ? i read from other issue, that it could be the app is too big, how big is too big ?
