### ISSUE TITLE
Questions about /sentiment samples

### ISSUE THREAD

**Issue by qfavor** [wit-ai/wit#1548]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question

**What is the current behavior?**
I have an app that uses /sentiment (English). I have been constantly receiving samples in my inbox that I have been processing so that the model gets better (for my specific use-case) and I have a few questions.
1. Are the samples that I am submitting helping the entire /sentiment endpoint - for everyone or are those used to improve my app only?
2. As far as I can see, there's a review process for each submitted sample. Can you please give some more details around it? Is someone manually going through my samples and reviewing them? How long does this review process take?
3. How can I know when my samples have been reviewed?
4. Is it probable that after my samples have been reviewed the accuracy for the type of messages I usually send improves?

Thank you!

**Comment by patapizza** [comment]
Hi @qfavor,

As `wit/sentiment` is a built-in entity, the underlying model is shared across all apps. The accuracy of built-in entities should improve over time as more samples are added to the training dataset. Re-training is done periodically without manual review of the samples. We haven't had the chance to implement the continuous learning loop for `wit/sentiment` yet. Once we do, the samples you've annotated in Inbox and in Understanding will be included in the training dataset, thus improving the machine learning model.

**Comment by jtliao** [comment]
Merging with #1615
