### ISSUE TITLE
Error after saving app

### ISSUE THREAD

**Issue by dracero** [wit-ai/wit#1549]
After saving the app I couldn't see the saving panel anymore and received the following error:

Something went wrong 😔 Please refresh or create a Github issue here.

**Comment by FengyangZhang** [comment]
Hi @dracero, can you explain what do you mean by "saving the app"? Is it the "save the current version" or something else? And can you share your app ID?

**Comment by dracero** [comment]
The problem began after I pressed the "Save Current Version" button, but It
is working now. Could be a problem due to the operative system?

My app id is 2310062225788838.

Thank you very much for your help

**Comment by FengyangZhang** [comment]
I don't see an error in our logs, so will close this issue for now, let us know if the error comes up again.
