### ISSUE TITLE
issue running Android Quickstart

### ISSUE THREAD

**Issue by cyrille314159265** [wit-ai/wit#155]
Hi,

I'm getting the error below when attempting to speak to the app built with the Android Quickstart instructions. I'm running Android Studio 0.9.9 and my target is a nexus 5.

can you help?
regards

01-09 09:52:39.412    6279-6318/ai.wit.eval.wit_eval D/OpenGLRenderer﹕ Render dirty regions requested: true
01-09 09:52:39.423    6279-6279/ai.wit.eval.wit_eval D/Atlas﹕ Validating map...
01-09 09:52:39.478    6279-6318/ai.wit.eval.wit_eval I/Adreno-EGL﹕ <qeglDrvAPI_eglInitialize:410>: QUALCOMM Build: 10/24/14, 167c270, I68fa98814b
01-09 09:52:39.481    6279-6318/ai.wit.eval.wit_eval I/OpenGLRenderer﹕ Initialized EGL, version 1.4
01-09 09:52:39.508    6279-6318/ai.wit.eval.wit_eval D/OpenGLRenderer﹕ Enabling debug mode 0
01-09 09:52:47.212    6279-6279/ai.wit.eval.wit_eval D/ai.wit.sdk.Wit﹕ streamRawAudio started.
01-09 09:52:47.222    6279-6638/ai.wit.eval.wit_eval D/Wit﹕ Requesting SPEECH ....audio/raw;encoding=signed-integer;bits=16;rate=16000;endian=little
01-09 09:52:47.222    6279-6638/ai.wit.eval.wit_eval D/Wit﹕ Posting speech to https://api.wit.ai/speech?v=20140923
01-09 09:52:48.116    6279-6638/ai.wit.eval.wit_eval D/Wit﹕ An error occurred during the request: Write error: ssl=0xaf937e00: I/O error during system call, Broken pipe
01-09 09:52:48.117    6279-6279/ai.wit.eval.wit_eval D/Wit﹕ Wit : Response null
01-09 09:52:48.137    6279-6279/ai.wit.eval.wit_eval D/Wit﹕ Gson : Response null
01-09 09:52:48.907    6279-6637/ai.wit.eval.wit_eval D/WitVAD﹕ Speak start
01-09 09:52:51.707    6279-6637/ai.wit.eval.wit_eval D/WitVAD﹕ Speak end
01-09 09:52:51.770    6279-6637/ai.wit.eval.wit_eval E/AudioRecord-JNI﹕ Unable to retrieve AudioRecord object, can't record

**Comment by cyrille314159265** [comment]
was anyone else able to run the Android Quickstart successfully?

**Comment by ellienene** [comment]
I cannot run Android Quickstart either, but with different error mesg: Response Bad auth, check token/params

Check below:
02-01 23:01:33.777    3379-3379/ai.wit.eval.witeval D/ai.wit.sdk.Wit﹕ streamRawAudio started.
02-01 23:01:33.787    3379-3436/ai.wit.eval.witeval D/Wit﹕ Requesting SPEECH ....audio/raw;encoding=signed-integer;bits=16;rate=16000;endian=little
02-01 23:01:33.827    3379-3436/ai.wit.eval.witeval D/Wit﹕ Posting speech to https://api.wit.ai/speech?v=20141022&context=%7B%22reference_time%22%3A%222015-02-01T23%3A01Z%22%7D
02-01 23:01:39.777    3379-3435/ai.wit.eval.witeval D/WitVAD﹕ Speak start
02-01 23:01:40.977    3379-3435/ai.wit.eval.witeval D/WitVAD﹕ Speak end
02-01 23:01:41.057    3379-3436/ai.wit.eval.witeval D/Wit﹕ Done sending data
02-01 23:01:41.107    3379-3379/ai.wit.eval.witeval D/Wit﹕ Wit : Response Bad auth, check token/params
02-01 23:01:41.177    3379-3379/ai.wit.eval.witeval E/Wit﹕ Wit : Error java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1

**Comment by ellienene** [comment]
after put on my server access token, bad auth issue fixed and Android Quickstart can run now

**Comment by cyrille314159265** [comment]
nice, what is the expected behavior? can you attach a screen-shot?

**Comment by michaelmctear** [comment]
I also had a problem with the Android app. It looks like it is a thread error. Here's the logcat:
11-09 18:29:48.014 30027-30027/? I/art: Late-enabling -Xcheck:jni
11-09 18:29:48.046 30027-30034/? I/art: Debugger is no longer active
11-09 18:29:48.119 30027-30041/? D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
11-09 18:29:48.159 30027-30041/? I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 09/02/15, 76f806e, Ibddc658e36
11-09 18:29:48.160 30027-30041/? I/OpenGLRenderer: Initialized EGL, version 1.4
11-09 18:29:55.246 30027-30027/ai.wit.eval.wit_eval W/art: Before Android 4.1, method int android.support.v7.internal.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
11-09 18:29:57.967 30027-30041/ai.wit.eval.wit_eval E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb43fa4e0
11-09 18:29:59.883 30027-30027/ai.wit.eval.wit_eval D/ai.wit.sdk.Wit: streamRawAudio started.
11-09 18:29:59.885 30027-30296/ai.wit.eval.wit_eval D/Wit: Requesting SPEECH ....audio/raw;encoding=signed-integer;bits=16;rate=16000;endian=little
11-09 18:29:59.898 30027-30296/ai.wit.eval.wit_eval D/Wit: Posting speech to https://api.wit.ai/speech?v=20141022&context=%7B%22reference_time%22%3A%222015-11-09T18%3A29Z%22%2C%22location%22%3A%7B%22latitude%22%3A54.5945945945946%2C%22longitude%22%3A-5.877894134766462%7D%7D
11-09 18:30:00.777 30027-30295/ai.wit.eval.wit_eval E/AndroidRuntime: FATAL EXCEPTION: Thread-120486
11-09 18:30:00.777 30027-30295/ai.wit.eval.wit_eval E/AndroidRuntime: Process: ai.wit.eval.wit_eval, PID: 30027
11-09 18:30:00.777 30027-30295/ai.wit.eval.wit_eval E/AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=12800; index=12800
11-09 18:30:00.777 30027-30295/ai.wit.eval.wit_eval E/AndroidRuntime:     at ai.wit.sdk.WitMic$SamplesReaderThread.short2byte(WitMic.java:227)
11-09 18:30:00.777 30027-30295/ai.wit.eval.wit_eval E/AndroidRuntime:     at ai.wit.sdk.WitMic$SamplesReaderThread.run(WitMic.java:207)
11-09 18:30:00.971 30027-30041/ai.wit.eval.wit_eval E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb43fa030
11-09 18:30:05.327 30027-30295/ai.wit.eval.wit_eval I/Process: Sending signal. PID: 30027 SIG: 9

**Comment by l5t** [comment]
So sorry for the lack of reply and support here. We have been focusing on the API and haven't had the time to maintain and support our mobile SDKs. For this exact reason, we decided to open source our SDK hoping that the community can help and contribute: https://github.com/wit-ai/wit-android-sdk
