### ISSUE TITLE
500 all morning on speech recognition

### ISSUE THREAD

**Issue by backmeupplz** [wit-ai/wit#1550]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
It's a bug probably.

**What is the current behavior?**
Speech recognition API returns a lot of 500.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Well, I keep receiving `Message: Something went wrong. We've been notified.`

**What is the expected behavior?**
To get the recognized text.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
Maybe `5b59546f-9bcc-4eb4-aa16-f34cc88cee29`?

**Comment by patapizza** [comment]
Thanks for reporting, we're looking into this.

**Comment by patapizza** [comment]
Things are back to normal for the last 50'. We'll continue investigating to improve our infra.
