### ISSUE TITLE
App Training scheduled after 12 hours

### ISSUE THREAD

**Issue by altsalih** [wit-ai/wit#1552]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question 
**What is the current behavior?**
App says it would start training after 12 hours from now

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Should train within a short span of time

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
5af953ef-1dd6-4bcc-9817-e85776726fc3

**Comment by pengtxiafb** [comment]
we have manually triggered this app to train, and it is done now, let us know if you still face issues.
