### ISSUE TITLE
Style.2020

### ISSUE THREAD

**Issue by linkswiko** [wit-ai/wit#1553]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by pengtxiafb** [comment]
There is not enough information here, so I will close it
