### ISSUE TITLE
BUG: Duplicate Entity Name

### ISSUE THREAD

**Issue by doriclaudino** [wit-ai/wit#1554]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
duplicate entities names

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I create a new app, the same happens

**What is the expected behavior?**
Appear only one label per entity

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2478114785588327
All my apps, seems general bug after some update, this bug start after 4:00pm -5 UTC

![image](https://user-images.githubusercontent.com/3863501/65549194-0db29900-deeb-11e9-833d-e3fc1d912777.png)

On filters it get even worst:
![image](https://user-images.githubusercontent.com/3863501/65549413-7a2d9800-deeb-11e9-9914-f58fad0bd8ba.png)

**Comment by FengyangZhang** [comment]
Hi @doriclaudino, sorry for the inconvenience, the bug should've been fixed now. Please let use know if similar problems happen again!

**Comment by doriclaudino** [comment]
@FengyangZhang yes, is fixed! thanks
