### ISSUE TITLE
Count total messages in inbox

### ISSUE THREAD

**Issue by qfavor** [wit-ai/wit#1555]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Feature

**What is the expected behavior?**
It would be useful if we knew how many samples that need training we have in the inbox from within the web interface. This number could be displayed next to the red dot that appears when you have something in your Inbox.

Thank you!
PS: If there's another way through which I could submit this type of feedback and I'm doing it wrong, let me know!

**Comment by jtliao** [comment]
merging with and updating #1541, since we'll probably get around to both at the same time :)
