### ISSUE TITLE
Ongoing training

### ISSUE THREAD

**Issue by chatbotalex** [wit-ai/wit#1556]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
My apps training is stuck on Ongoing for quite some time.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Backed-up an app and its training is Ongoing.

**What is the expected behavior?**
To finish the training

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
3052593201434267

**Comment by pengtxiafb** [comment]
We have force the retrain the model, and training is finished now, let us know if you still have issue on the training.

**Comment by danielkhan** [comment]
This is not how you should solve these ongoing problems. Could you **please** solve this bug once and for all?
