### ISSUE TITLE
[BUG] Github OAuth does not work

### ISSUE THREAD

**Issue by danielgatis** [wit-ai/wit#1557]
I can't log in with my github account. I always get this error on chrome devtools console:

```
authorize:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://github.githubassets.com/assets/github-bootstrap-e79d5d49.js' with computed SHA-256 integrity 'Uad6+Pod5KgEVapUNGjQaIT1Hl1dUleW1CNJWkOxs6Y='. The resource has been blocked.
```

**Comment by jtliao** [comment]
hey @danielgatis, can you share a quick repro video? i can't seem to be able to reproduce this, Github login works fine for me

**Comment by danielgatis** [comment]
@jtliao nevermind, it's working! my bad.
