### ISSUE TITLE
wit/datetime not listing

### ISSUE THREAD

**Issue by amtdevops** [wit-ai/wit#1558]
Hi,
For my app also wit/datetime not showing in the entity list. Any issues?

**Comment by jtliao** [comment]
Please provide your app ID, or we can't help

**Comment by amtdevops** [comment]
My app ID is 2469727699777042

**Comment by FengyangZhang** [comment]
Hi @amtdevops, I checked your app and was able to find wit/datetime in the entity list, can you double check if you still can't see it?

**Comment by amtdevops** [comment]
![image](https://user-images.githubusercontent.com/35335761/65841519-cbe97e80-e340-11e9-9952-5d8c0d636bb2.png)

Only the above listed entities comes when I search. Where can I find wit/datetime?

**Comment by amtdevops** [comment]
<img width="742" alt="Untitled" src="https://user-images.githubusercontent.com/35335761/65841544-12d77400-e341-11e9-99e7-929e797b2118.png">

Only the above listed entities comes when I search. Where can I find wit/datetime?

**Comment by FengyangZhang** [comment]
I see, can you search for datetime instead?

**Comment by amtdevops** [comment]
Thank you it worked. Got it when I searched datetime :)
