### ISSUE TITLE
Merging 2 entities

### ISSUE THREAD

**Issue by l5t** [wit-ai/wit#156]
Is it possible too merge 2 or more entities together to maintain all tagging learnt so far( if not may be a nice feature to add! )

**Comment by AlexanderEwart** [comment]
As a developer, thinking ahead even further (tho I currently do not have a need to do this) perhaps an  extension of #156 would be the division of 2 entities that were currently merged as one.

Anyway thanks for the consideration of our problem and your fast response, Alex.

**Comment by RobQuistNL** [comment]
This would be genious. It would allow me to say things like "Enable the tv and the lights" and both come up. The API's JSON output looks like it can handle multiple entities / intents, but the dashboard seems to lack this functionality.

**Comment by l5t** [comment]
So sorry for the late reply. The concept of intents is less prominent in new Bot Engine and actually like a entity. Please see https://wit.ai/docs for further info. You can now define 2 intent entities and Wit will be able to extract both.

**Comment by RobQuistNL** [comment]
Awesome @l5t ! This API keeps getting better and better.
