### ISSUE TITLE
Empty entity lists are returned as a json array, should be object

### ISSUE THREAD

**Issue by mrkhingston** [wit-ai/wit#1560]
**report a *bug***

**What is the current behavior?**

Empty entity lists are returned as a json array when other entity lists are a json object.

This is what I currently get when there are no entities found:

{"_text":"No thanks","entities":[],"msg_id":"1Eg6GQGEUBsV10jtM"}

when there ARE entities found, it would look like:

{"_text":"No thanks","entities":{....},"msg_id":"1Eg6GQGEUBsV10jtM"}

No notification was given of an api format change and the inconsistency makes me think this is a bug more than it is an intentional change.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Send something that produces no entity results to a classifier that uses the wit/datetime entity

**What is the expected behavior?**

Should receive this:

{"_text":"No thanks","entities":{},"msg_id":"1Eg6GQGEUBsV10jtM"}

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

59ae4c4b-7140-4c6d-b8bb-41ac75f93151

**Comment by serdalbayram** [comment]
Same for me :(

**Comment by jtliao** [comment]
Not sure what happened, no changes were made around here. We're looking into it

**Comment by jtliao** [comment]
This should be back to normal again, apologies for the inconvenience. We'll add more checks to make sure this doesn't happen again
