### ISSUE TITLE
The train bot UI is missing the entity/intent editor.

### ISSUE THREAD

**Issue by tarpitgrover** [wit-ai/wit#1561]
Report a Bug.

**What is the current behavior?**
When I enter a sentence in the train bot UI (Understanding Tab), I no longer see the entity/intent editor.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Here's a screenshot: https://ibb.co/6BHbvPH

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID: 1879082498812979

**Comment by anxodio** [comment]
Same here!

**Comment by harreefai** [comment]
Same here!

**Comment by FengyangZhang** [comment]
Thanks for reporting! This should've been fixed now.
