### ISSUE TITLE
Working with wit/datetime

### ISSUE THREAD

**Issue by amtdevops** [wit-ai/wit#1563]
Hi,
I have an input which asks for date and time. we are getting the datetime value in wit/datetime.
If user dosen't input date and only provided time, then we should ask to input date. But even if I didn't input date and only provided time, the wit/datetime entity shows today's date by default. same for time also, 12am is showing as default time. 
How shall I ask prompt for date and time with wit/datetime?

**Comment by FengyangZhang** [comment]
Hi @amtdevops, in that case you can probably define two parsers - date and time instead of using builtin datetime

**Comment by amtdevops** [comment]
@FengyangZhang Can  u please help me in adding paser for date and time in wit.ai.
How can we add the parser for date and time in our wit app?

**Comment by amtdevops** [comment]
Any updates. Please help.

**Comment by lycai-fb** [comment]
Hey @amtdevops I think the easiest solution is to prompt for the date or time if the parser returns the default value. You will have the side effect of possibly prompting twice if the user explicitly states today or 12:00, but there isn't an easy way around it.

I believe what @FengyangZhang was referring to is to have two wit/datetime parsers and try to train one to only accept date and the other to only accept time but it might be difficult to get the accuracy you'd like from that approach.

**Comment by patapizza** [comment]
You can use the `grain` information to see whether it's a time or a date (https://github.com/wit-ai/wit/issues/1098).

**Comment by amtdevops** [comment]
> You can use the `grain` information to see whether it's a time or a date (#1098).

@patapizza thanks for the reply, but one clarification if I give '6am' I'm getting the below response

{
  "_text": "6am",
  "entities": {
    "datetime": [
      {
        "confidence": 0.955325,
        "values": [
          {
            "value": "2019-10-15T06:00:00.000-07:00",
            "grain": "hour",
            "type": "value"
          },
          {
            "value": "2019-10-16T06:00:00.000-07:00",
            "grain": "hour",
            "type": "value"
          },
          {
            "value": "2019-10-17T06:00:00.000-07:00",
            "grain": "hour",
            "type": "value"
          }
        ],
        "value": "2019-10-15T06:00:00.000-07:00",
        "grain": "hour",
        "type": "value"
      }
    ]
  },
  "msg_id": "1xKAJKHbGIqKhw0Uh"
}



and if I give 'today at 6am' it gives the following response

{
  "_text": "today at 6am",
  "entities": {
    "datetime": [
      {
        "confidence": 0.96359333333333,
        "values": [
          {
            "value": "2019-10-14T06:00:00.000-07:00",
            "grain": "hour",
            "type": "value"
          }
        ],
        "value": "2019-10-14T06:00:00.000-07:00",
        "grain": "hour",
        "type": "value"
      }
    ]
  },
  "msg_id": "1uXShfcYCm85H76pG"
}


In both cases th e'grain' have value 'hour'. The how can I check if the user has provided date or not.
