### ISSUE TITLE
Easy doc typo to fix

### ISSUE THREAD

**Issue by fozcodes** [wit-ai/wit#1564]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

I suppose it's _technically_ a "bug", but really just a typo in your docs. I would have made a PR myself, but wasn't sure if those were accepted or where. 🤷‍♂ 

**What is the current behavior?**

Your example for [API Versioning](https://wit.ai/docs/http/20170307#api_versioning_link) is for `v=20170307`, but the explanation text below says the incorrect date:

> This request gives you the guarantee that any changes that may have occurred after April 1st, 2014 won’t impact you...

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

- Go to the link: https://wit.ai/docs/http/20170307#api_versioning_link
- Read the text
- Profit 😄 

**What is the expected behavior?**

Either change the example request code, or the explanation text so that the dates match. I would say the latter to make the date less common for a good example.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by FengyangZhang** [comment]
thanks for reporting, this should be fixed soon
