### ISSUE TITLE
Duplicate speech recognition

### ISSUE THREAD

**Issue by backmeupplz** [wit-ai/wit#1565]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
It's probably a bug

**What is the current behavior?**
When using the speech recognition API, resulting text is returned twice in the same string

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Use Russian language speech recognition

**What is the expected behavior?**
Server should respond with the recognized text written once in the resulting string.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
`5b59546f-9bcc-4eb4-aa16-f34cc88cee29`

**Comment by jtliao** [comment]
looking into it..
