### ISSUE TITLE
Duplicate Trait values for intent

### ISSUE THREAD

**Issue by titoportas** [wit-ai/wit#1566]
**Do you want to request a feature, report a bug, or ask a question about wit?**
Bug
**What is the current behavior?**
I see 3 trait value items with the same value "Envío de Poliza", "como estas?", etc.

**What is the expected behavior?**
There should only be 1 value of each trait value.

**What is the App ID where you are experiencing this issue (if applicable)?**
2970319799651450

The trait values were created by the `POST https://api.wit.ai/samples` API. I found the same issue 2 years ago. #743

**Comment by Vickylatruite** [comment]
I have exactly the same issue using the same API (v=20191211).
I see from 2 to 6 duplicates in my case.
The worse is that if you try to remove one redondant value, it removes all of them.

**App ID:** 2404573142974955
