### ISSUE TITLE
App Stuck in On-Going

### ISSUE THREAD

**Issue by 91ns** [wit-ai/wit#1567]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
App is stuck in training mode 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2581175611920920

**Comment by 91ns** [comment]
We are also having the same issue with App ID 2101186346677141

**Comment by patapizza** [comment]
Retrained the second one, the first one was already trained.
