### ISSUE TITLE
is there any limits on the number of keywords allowed?

### ISSUE THREAD

**Issue by boynet** [wit-ai/wit#1568]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question

I need to identify street names, I have a list with 50k names, is it ok to upload that much into entity keywords? 

I tried to enter a few names, make the entity free-text & keywords and train it but it never catch streets that not in the list(non English bot)

**Comment by jtliao** [comment]
hi @boynet, the max is 10k values.
