### ISSUE TITLE
Not recognize Russian digits 13

### ISSUE THREAD

**Issue by Phoenix1833** [wit-ai/wit#1569]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
Does not recognize the Russian digit "тринадцать" as a number.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Example: "шестьсот три тринадцать шестьсот три"
**What is the expected behavior?**
return json wit/number 603 13 603
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2250282511767645

**Comment by wangsnowyin11** [comment]
We use Duckling to parse numbers. You could contribute it to the library. Make a pull request to the open source, https://github.com/facebook/duckling
