### ISSUE TITLE
Wit's weird behaviour in detecting entities

### ISSUE THREAD

**Issue by shzamani** [wit-ai/wit#1570]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
*bug*

**What is the current behavior?**
Instead of finding entity(ies) inside the detected intent, it detects the entity(ies) from other intents.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Please see the screenshot.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
Here is the App ID: 2563137910464119

In the screenshot, the _apikg_Yelp_location_ is an entity from **businesses_search** intent, and _apikg_OpenWeatherMap_q_ is an entity from **GetWeather** intent.

![Screen Shot 2019-10-21 at 6 11 21 pm](https://user-images.githubusercontent.com/6498095/67184012-7a5b7d80-f42e-11e9-8759-3c0e8913f52d.png)

**Comment by patapizza** [comment]
Hi @shzamani,

In the current business model, `intent` is an entity just like any others; working standalone.
To track conditionally applied entities, please follow https://github.com/wit-ai/wit/issues/1070.

Thanks
