### ISSUE TITLE
Is not identifying wit/location entity

### ISSUE THREAD

**Issue by viveksachidananda** [wit-ai/wit#1572]
**_Do you want to request a feature, report a bug, or ask a question about wit?_**
Report bug

**_What is the current behavior?_**
Does not identify the location entity.

**_If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem._**
It looks a regression, was working fine yesterday seems to be broken today! Just try with string
**"Get me surfing retreats in spain under 100 euros"**

**_What is the expected behavior?_**
Country Spain to be identified under wit/location entity

**_If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help_**.
3151918951545304

**_Logs:_**
{
  "_text":
  "Get me surfing retreats in spain under 100 euros"
  "confidence":
  null
  "intent-id":
  "default_intent_id"
  "intent":
  "default_intent"
  "entities":
  {
    "intent":
      [{"value":{ "value": "surf"}
      "confidence": 0.99630867568465
      "entity":"intent"}]
  }
}

**Comment by viveksachidananda** [comment]
App ID: 3151918951545304

Steps to reproduce: "Get me surfing retreats in spain under 100 euros"

Expected behavior: Spain to be identified as location

Logs:
[
{
"_text":
"Get me surfing retreats in spain under 100 euros"
"confidence":
null
"intent-id":
"default_intent_id"
"intent":
"default_intent"
"entities":
{
"intent":
[
{
"value":
{
"value":
"surf"
}
"confidence":
0.99630867568465
"entity":
"intent"
}
]
}
}
]

**Comment by kingseaeast** [comment]
thanks for reporting @viveksachidananda! We'll look into it today,

**Comment by kingseaeast** [comment]
@viveksachidananda We'll continue to improve the quality of our builtin entities like wit/location. Before that, I'd recommend creating your own entities and add samples to improve the quality that way.
