### ISSUE TITLE
Entity with keywords and free-text

### ISSUE THREAD

**Issue by sebamenabar** [wit-ai/wit#1573]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

I have a question/bug; I'm trying to train and entity to match with both free text and keywords, for example, I want to match kwown locations with keywords in my database/wit, but also, based on the structure of the text it can be recognized that certain part of the string corresponds to also a location.

**What is the current behavior?**

Every thing works good with keywords, but when I try to add/train an example with free text identification, when I choose the entitiy, the dropdown shows: Create new value "name of the place", and when I click validate, a new keyword for the entity is created.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

I'm trying to upload screenshots but it's failing

**What is the expected behavior?**

Those free text matches should not be created as new keywords, because I want manny different (unknown) strings to be identified.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

58d9df09-dafa-434d-8d7c-a58b5a08e684

**Comment by kingseaeast** [comment]
Thanks for reporting @sebamenabar! I'll look into it today.

**Comment by kingseaeast** [comment]
@sebamenabar do you have an example of the actual and expected behaviors? I'm not sure if I understand your case fully. My gut feeling is that you'll want to label the span with the type of the entity, not the actual name of the entity.

**Comment by sebamenabar** [comment]
I'll try, thank you for your help.

In my first picture, `copec` is a meetpoint that is currently not supported by my application, but because of the sentence (I want a ride to `copec`) it can be recognized as a meetpoint, and I want it to be recognized as a meetpoint to perform some additional actions on my backend.

The problem is that if I train wit to recognize `copec` as a meetpoint, it creates a new keyword for that word (second pic), but  I want it to behave as free text, because there will be other meetpoints (not in my database nor in wit keywords), and I still want to infer if they are meetpoints based on the sentence structure, if possible.

So, I'll try to say it in few words; I want to be able to train the same entity with free-text (that is not added as a new keyword) and keyword examples (I have the keywords & free-text setting of the entity enabled, but it does not allow me to do this).

I hope this helps, any further doubt or any way in which I can help please let me know.
Thanks again

![Captura de pantalla 2019-10-22 a la(s) 16 59 26](https://user-images.githubusercontent.com/13748963/67446898-7a06e200-f5e8-11e9-86d9-3e36b0a2bb11.png)
![Captura de pantalla 2019-10-22 a la(s) 17 00 10](https://user-images.githubusercontent.com/13748963/67446914-85f2a400-f5e8-11e9-8854-104a8240d07b.png)

**Comment by kingseaeast** [comment]
If you try another sample for meetpoints not in your database or in wit keywords, will that work? The fact that "copec" was created as keyword shouldn't be a problem, because you selected "free text & keywords" lookup strategy.

**Comment by sebamenabar** [comment]
Nope, my expected (wanted) behaviour would be to recognize `los palafitos` as a meetpoint since it's after `desde` (from). (I'm not totally sure if this is what you asked though)

![Captura de pantalla 2019-10-28 a la(s) 12 21 09](https://user-images.githubusercontent.com/13748963/67691495-758e5080-f97d-11e9-9b32-a6d589f71ff3.png)

**Comment by patapizza** [comment]
Hi @sebamenabar,

Thanks for the thorough explanation. When setting an entity as `free-text & keyword`, it's using both parsing strategies. So any validated samples will be recorded both as a keyword and as a free-text, so that it'll work really well on validated samples (because of the keyword strategy), but will also generalize to unseen text in similar sentence contexts (because of the free-text strategy). If it doesn't work for unseen texts yet, I recommended validated more samples showing similar sentence contexts (e.g. with `desde` as previous word).
If you really want an exclusive behavior between parsing strategies, you could split the entity into one keyword, and one free-text, and merge them on your end.

Hope this helps.
