### ISSUE TITLE
App is stuck  in Ongoing (since June)

### ISSUE THREAD

**Issue by sophiexr** [wit-ai/wit#1575]
Hi,

Our application (5b1e505b-0e5f-484a-9e44-20d7c4ee12d1 ) is stuck in ONGOING since June. 
Last time it trained was June 30th

We deleted many samples but it hasn't changed status. We created a copy of the app, but lost most of it's training. 

Can you please look into it? 

Thanks
Sophie

**Comment by kingseaeast** [comment]
I have kicked off a retrain on the app, but the training sample size is a littler larger than wha we can reliably handle, which contributed to the training got stuck. If the training is still stuck after some time, reducing the size of the training data should help.
