### ISSUE TITLE
The following locations are not being picked by with/location 1. Jackson (only picks Mississippi, Wyoming, Tennessee but not Ohio) 2. Fort Wayne IN or Fort Wayne, IN gets picked up as the location 'Wayne' in Michigan and Pennsylvania.

### ISSUE THREAD

**Issue by ElizabethRebello** [wit-ai/wit#1577]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by kingseaeast** [comment]
@ElizabethRebello Thanks for reporting! We will work on improving our built-in models, but there currently no ETA to fix the above issues. I recommend you train them with your custom entities.
