### ISSUE TITLE
Problem speech recognize russian language

### ISSUE THREAD

**Issue by Phoenix1833** [wit-ai/wit#1579]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
BUG
**What is the current behavior?**
Periodically does not fully recognize the sound file
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
For example files in wit.ai Voice inbox:
73192912_440235979958766_7183045883405183454_n.wav
73265586_203232810677394_6600335754472042894_n.wav
73268054_169106940814840_8008614382405949483_n.wav
73365315_175218226985838_3691524655776801399_n.wav
73375304_1472362699598090_4709505374623392629_n.wav
73402341_142328900460659_6526625234833944895_n.wav
73458217_429735151077568_8478952264847731016_n.wav
73458377_545735589494013_4132508073277555117_n.wav
74139736_164765124640295_2899042568896734439_n.wav
74263590_2494106777331713_49478802241545797_n.wav
74404966_2405099359526216_2198415702419814957_n.wav
74410236_1210923302429158_5832678964085607761_n.wav
74422272_525062728329602_5537205642338764501_n.wav
74480343_653835835145594_2257107944864895783_n.wav
74517448_1021634554849321_8088146394313434282_n.wav
74678065_2789194524437553_2128432932648317717_n.wav
74979287_142683277002783_7329711433969971195_n.wav
75180212_421558775230491_6917365616542778627_n.wav
If necessary, I am ready to send them for recognition or provide the files themselves.
**What is the expected behavior?**
Full recognize
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2250282511767645

**Comment by kingseaeast** [comment]
Thanks for reporting @Phoenix1833 ! We'll look into it.

**Comment by patapizza** [comment]
You can help improve the speech engine by correcting the transcript in the Voice Inbox. Thanks.

**Comment by Phoenix1833** [comment]
The problem of recognizing the whole phrase. Re-said recognizes normally. Take a look at "msg_id": "1u4BSB1phIbQXZQG0". The phrase is much longer than it was recognized.

**Comment by Phoenix1833** [comment]
I found! This is due to pauses in speech between words for more than 1 second.

**Comment by patapizza** [comment]
Interesting. Are you able to preprocess the audio on your end then?

**Comment by Phoenix1833** [comment]
Yes. I record the sound with the help of IP PBX Asterisk, remove the pauses with the help of sox and send it to wit. I noticed yesterday that in the case of normal recordings with normal pauses, this only interferes with recognition. 
Therefore, I am forced to send processed and unprocessed audio for recognition and choose according to the size of the response which is better recognized. While such a crutch.
