### ISSUE TITLE
Support for Indian English accent?

### ISSUE THREAD

**Issue by akhilpo** [wit-ai/wit#158]
Hi, is there any support for Indian english accent? Currently the Voice-to-text part of wit gets confused totally with my accent. I have tried a lot train it with my voice. But it gets me wrong even with the same sentence which I used to train it. Is there any way to fix this?

**Comment by l5t** [comment]
So sorry for the super late reply. Unfortunately it is not yet possible to add new word or to improve the speech rec. We plan to be able to customize the speech layer to allow you to do exactly that and this is why we implemented the Voice Inbox. However we won't be ready anytime soon... In the meantime, you can look at open source speech engine like Kaldi or Sphinx.

**Comment by devmrfitz** [comment]
Is there an update on this?
