### ISSUE TITLE
[Question] Legacy app updates deprecation

### ISSUE THREAD

**Issue by chrispanag** [wit-ai/wit#1580]
Hello, I have an app that is working since before March 2016. It is considered "Legacy". Now, I started getting some warnings that "legacy app updates will be deprecated", but I can't find any migration information. 

What steps should I take to ensure the stability of my app? 

Thank you in advance!

**Comment by jtliao** [comment]
also, in case it wasn't clear, legacy apps will still be able to support runtime queries (`GET /message`, `POST /speech`, etc.), just not updates

**Comment by chrispanag** [comment]
@jtliao I've already sent you an email :)
