### ISSUE TITLE
Is anything wrong with the speech recognition?

### ISSUE THREAD

**Issue by backmeupplz** [wit-ai/wit#1581]
Sorry for not following the template or not providing the app id. I just wanted to point to your attention that I started to receive an excessive amount of 500 errors again.

Just check if speech recognition still works well. If so, please, disregard this issue.

**Comment by toofan0909** [comment]
Hello Guys, 

I am getting server time out errors, I hope this getting sorted out soon :)

**Comment by jtliao** [comment]
The 500 error rate should be improved now.
