### ISSUE TITLE
Slow and incorrect parsing

### ISSUE THREAD

**Issue by AlexandreRgx** [wit-ai/wit#1582]
**Do you want to request a feature, report a bug, or ask a question about wit?**
BUG

**What is the current behavior?**

It's very slow to get an answer from the API for all my applications. Furthermore, the results are not always correct anymore - compared to yesterday behavior - without any modifications from my side.

**Comment by serdalbayram** [comment]
the same for me

**Comment by UtkuErem** [comment]
+1 same problem

**Comment by idanadut** [comment]
+1 same here - very slow to get answer from API (related to outage?). any ETA to fix?
thanks

**Comment by patapizza** [comment]
Thanks for reporting, and sorry for the inconvenience. There were infra issues yesterday that should be resolved by now.
