### ISSUE TITLE
Problem russian speech recognize

### ISSUE THREAD

**Issue by Phoenix1833** [wit-ai/wit#1583]
I found! This is due to pauses in speech between words for more than 1 second.
When I processed the file using sox:
sox in.wav out.wav silence -l 1 0.1 1% -1 2.0 1%
the problem is gone

_Originally posted by @Phoenix1833 in https://github.com/wit-ai/wit/issues/1579#issuecomment-549071793_

**Comment by patapizza** [comment]
Duplicate of https://github.com/wit-ai/wit/issues/1579.
