### ISSUE TITLE
registering with github shows wrong github username

### ISSUE THREAD

**Issue by solrevdev** [wit-ai/wit#1584]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

Bug

**What is the current behavior?**

When i register it links to and calls me solrevdev_NE2I2HA but I am solrevdev

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

register

**What is the expected behavior?**

my github link and account name should be solrevdev 

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by lintaocui** [comment]
this is by design, we add random string to the suffix of user name
