### ISSUE TITLE
App stuck in ongoing for a long time

### ISSUE THREAD

**Issue by sophiexr** [wit-ai/wit#1585]
Hi,

Regarding the issue with our application (5b1e505b-0e5f-484a-9e44-20d7c4ee12d1 ) which is stuck in ONGOING since June, the retraining you forced last week didn't work.

Will it help if you divide our project in many entities? 

Any other suggestions ? 

thanks

**Comment by lintaocui** [comment]
this is currently by design, we add random string suffix to the user name

**Comment by lintaocui** [comment]
hi @sophiexr , thanks for the feedback. Unfortunately,  there are too many samples in your app, and we can't support that load at the moment. The good news is we are working on our training infra to support app with large number of samples. Please stay tuned.
