### ISSUE TITLE
Danish Speech Recognition - Not Working

### ISSUE THREAD

**Issue by TheRealKANi** [wit-ai/wit#1587]
Hi Wit
Long time happy user here.. 😉
App Id: 58b5dbe6-eaf0-48a3-b987-aafae8c39176

If i make the usual request to your service the following issue arises.:

![Skærmbillede 2019-11-06 kl  22 45 24](https://user-images.githubusercontent.com/1286819/68340820-6fb80e00-00e7-11ea-9c59-2bb3f11c8a2e.png)

I can see in the issue tracker that this is not the first language 
to be affected by this 'bug', hope it can be fixed very soon.

Thanks in advance
Kenneth

**Comment by lintaocui** [comment]
Thanks @TheRealKANi  for the feedback, Danish is not a language Wit supports for now.

**Comment by TheRealKANi** [comment]
That does not make any sense.. I have been using Wit.ai with the danish language for more than 2 years without a problem.. Time restraints on my side had paused the project for the last ca year. But before that everything was working perfectly. It is stated as well on the FAQ of wit.ai.
![Skærmbillede 2020-01-07 kl  09 47 20](https://user-images.githubusercontent.com/1286819/71881564-d4690680-3132-11ea-8cee-206c2aec252b.png)
