### ISSUE TITLE
Is is possible to only detect entities (free-text, keywords) ?

### ISSUE THREAD

**Issue by jonathanrico** [wit-ai/wit#1588]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

Question

**What is the current behavior?**

Current behavior appears to be to always detect an intent and entities configured under the intent.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Not a bug

**What is the expected behavior?**

Let's say I want to create a "book a flight" intent (trait). I can train a a book_flight intent that contains Airport entities (free-text, keywords) with several phrases. For example, I want to book a flight, I want to fly from [SFO] to [JFK], I want to fly from [CDG], etc. But let's say a user just says "I want to book a flight", then I would like to ask : "From where are you flying from". If user just responds : "SFO" and pass the response to the message endpoint then no entity is detected.

My question is the following. Is there a way to call the message api but just look for entities or a recommended way to detect entities for this type of scenarios?

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by KartikChugh** [comment]
Yeah it can work if you just add the entities in the Management > Entities tab
