### ISSUE TITLE
How to sync my project?

### ISSUE THREAD

**Issue by kongqw** [wit-ai/wit#159]
My project used Eclipse.so, how to sync my project?
thanks very very much!

02-03 14:54:56.922: E/AudioRecord-JNI(31469): Unable to retrieve AudioRecord object, can't record
02-03 14:55:03.309: E/AndroidRuntime(31469): FATAL EXCEPTION: AsyncTask #1
02-03 14:55:03.309: E/AndroidRuntime(31469): Process: com.kongqw.witai, PID: 31469
02-03 14:55:03.309: E/AndroidRuntime(31469): java.lang.RuntimeException: An error occured while executing doInBackground()
02-03 14:55:03.309: E/AndroidRuntime(31469): 	at android.os.AsyncTask$3.done(AsyncTask.java:300)
02-03 14:55:03.309: E/AndroidRuntime(31469): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
02-03 14:55:03.309: E/AndroidRuntime(31469): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
02-03 14:55:03.309: E/AndroidRuntime(31469): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
02-03 14:55:03.309: E/AndroidRuntime(31469): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
02-03 14:55:03.309: E/AndroidRuntime(31469): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-03 14:55:03.309: E/AndroidRuntime(31469): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-03 14:55:03.309: E/AndroidRuntime(31469): 	at java.lang.Thread.run(Thread.java:841)
02-03 14:55:03.309: E/AndroidRuntime(31469): Caused by: java.lang.NoClassDefFoundError: org.apache.commons.io.IOUtils
02-03 14:55:03.309: E/AndroidRuntime(31469): 	at ai.wit.sdk.WitSpeechRequestTask.doInBackground(WitSpeechRequestTask.java:84)
02-03 14:55:03.309: E/AndroidRuntime(31469): 	at ai.wit.sdk.WitSpeechRequestTask.doInBackground(WitSpeechRequestTask.java:26)
02-03 14:55:03.309: E/AndroidRuntime(31469): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
02-03 14:55:03.309: E/AndroidRuntime(31469): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-03 14:55:03.309: E/AndroidRuntime(31469): 	... 4 more

**Comment by patapizza** [comment]
Hi kongqw,

Did you add the Apache Commons IO dependency in your `app/build.gradle` file?
```
compile('org.apache.directory.studio:org.apache.commons.io:2.4')
```

Please note that we recommend using Android Studios for Android development.

Let me know how it goes.

Thanks,
Julien

**Comment by kongqw** [comment]
Hi,Julien
I'm not.
I can't used Android Studio,so,I don't know what the "app/build.gradle file".
In my team,we are used eclipse,
what should i do by Eclipse?

thanks!
happy new years!

kongqw

**Comment by kongqw** [comment]
Hi,Julien
I'm not.
I can't used Android Studio,so,I don't know what the "app/build.gradle file".
In my team,we are used eclipse,
what should i do by Eclipse?

thank you!
happy new years!

kongqw

**Comment by stopachka** [comment]
@kongqw, apologies for the lack of updates here. Please ping is if you still experience issues
