### ISSUE TITLE
Speech Recognition always returning blank

### ISSUE THREAD

**Issue by morgan-evans** [wit-ai/wit#1590]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug
**What is the current behavior?**
No matter what I do, it always returns blank for the text output. I changed nothing in my code since it worked yesterday, and no longer works. (sometimes detects the words "what" and "okay"
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Just send a request with an audio stream to /speech and it'll return a value with nothing in it
**What is the expected behavior?**
The audio gets converted to text
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2861174207226599

**Comment by gondiss** [comment]
Hi Morgan,
We have recently made some updates. Can you try using speech API now and let us know if you  are still having the specific issue.
Thanks
