### ISSUE TITLE
Chinese input always returns wit/greetings

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#1591]
Hi,
We have a wit.ai app which in is English language. We expect out AI to return no intents if we input in any other language.
But in our wit.ai app, any input in Chinese language returns wit/greetings.
How can we fix this.

Thanks and Regards
Anjaly

**Comment by anjaly** [comment]
Hi,
Can some one please help in fixing this.

Thanks and Regards
Anjaly

**Comment by FengyangZhang** [comment]
Hi there, can you provide the app ID?

**Comment by anjaly** [comment]
Hi,
Our app ID is 2249860545110846

**Comment by FengyangZhang** [comment]
Seems wit/greetings is working good, though it is returning true for Chinese inputs, maybe because of bad data used for training. We are looking to improve the quality of builtin models very soon.
