### ISSUE TITLE
Failed parsing entities/ wit MAGICMIRROR AI

### ISSUE THREAD

**Issue by areeb95** [wit-ai/wit#1592]
When uploading "wit_training_data.zip" to create an app, It throw an error "Failed parsing entities/" and app created but it only creates "Status-Type" and "Map-Type" entity.
Please help ASAP...

**Comment by FengyangZhang** [comment]
Hi, can you provide the app id?

**Comment by areeb95** [comment]
> Hi, can you provide the app id?

Here is the App id:
1972155939553397

**Comment by FengyangZhang** [comment]
Seems this is the imported app. Can you provide the original app you exported?

**Comment by areeb95** [comment]
> Seems this is the imported app. Can you provide the original app you exported?

Please help me!!

**Comment by FengyangZhang** [comment]
Hi, seems the zip file you provided is edited and zipped. You should not manually change the content in the zip file you exported from wit, is there a reason you want to do so?

**Comment by jtliao** [comment]
ZIPs should not be edited. if you need to alter training samples, utilize `POST /samples`
