### ISSUE TITLE
App Stuck in On Going

### ISSUE THREAD

**Issue by 91ns** [wit-ai/wit#1593]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
App is Stuck in On Going
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
5a0d7814-78cf-4a6f-b28a-7e0287bc3794

**Comment by MMaggieZhou** [comment]
We have retrained your app and it has finished on 11/21. Please let us know if you are unblocked.
