### ISSUE TITLE
App Stuck on on-going

### ISSUE THREAD

**Issue by Malakaburizk** [wit-ai/wit#1595]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
Stuck on on-going
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
It's stuck can't really reproduce it

**What is the expected behavior?**
Finish training

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
5a0d7814-78cf-4a6f-b28a-7e0287bc3794

**Comment by ankit-27** [comment]
Hi, my app status is Ongoing for 2 days now, can you take a look?
App id: 2536731159742728

**Comment by MMaggieZhou** [comment]
We checked your App and it seems that the training has completed. Can you verified if it's unblocked?
