### ISSUE TITLE
App struck in ongoing

### ISSUE THREAD

**Issue by ankit-27** [wit-ai/wit#1596]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
Status Ongoing
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Status Finished
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID: 2536731159742728

**Comment by MMaggieZhou** [comment]
We have manually retrained for your app and it has finished. Let us know if you are unblocked.

**Comment by ankit-27** [comment]
Yes, the app got trained now. Thanks,
