### ISSUE TITLE
Downloading the app data

### ISSUE THREAD

**Issue by mohanstriker03** [wit-ai/wit#1597]
App Id: 2995192457162499
I am not able to download the trained app data from the app.
It is displaying a notification with the below message
**Something went wrong while exporting your app ☹️. Please try again, or contact us.**

**Comment by MMaggieZhou** [comment]
We have fixed the export issue on your end. Please let me know if you are unblocked.

**Comment by mohanstriker03** [comment]
Hi @MMaggieZhou, Still I am not able to export the data.
![Issue_not_resolved](https://user-images.githubusercontent.com/53551269/69600763-d4f08680-1037-11ea-88f3-76024ba60ceb.png)

**Comment by jiayexie** [comment]
Hi @mohanstriker03, we have fixed a few more issues; could you please try exporting again?
