### ISSUE TITLE
Blank Problems

### ISSUE THREAD

**Issue by landman** [wit-ai/wit#1599]
I have a "location" Problem.

"From Berlin to Shanghai" is working but "Berlin Shanghai" gives me "berlin shanghai" as one location. Not seperated.

**Comment by jiayexie** [comment]
Hi @landman, thanks for reporting the issue; I can repro. Unfortunately, this is a prediction output of our machine learning model that cannot be quickly and properly fixed. I think it mostly likely never saw any training example with two city names consecutively show up like this. If this is indeed your use case, we recommend creating your own custom entity type and train that type with your own samples.
