### ISSUE TITLE
Having trouble adding new expressions

### ISSUE THREAD

**Issue by vinay-singla** [wit-ai/wit#1600]
When I try to add a new expresssion and intent and hit validate, I get the below message:

Wit had an issue validating this expression. Please try again and contact us if this does not resolve

**Comment by jtliao** [comment]
Hi @vinay-singla, can you please provide your app ID? I can't reproduce this on my app.

**Comment by vinay-singla** [comment]
APP ID: 2523687551045814
APP Name: MyFirstApp

**Comment by vinay-singla** [comment]
Were you able to look into the issue? Thanks!

**Comment by vinay-singla** [comment]
I closed my browser and then reopened, it's working now!
