### ISSUE TITLE
Built in entity for stock symbok

### ISSUE THREAD

**Issue by vinay-singla** [wit-ai/wit#1601]
I would like a built-in entity for stock symbol of a public company.

**Comment by MMaggieZhou** [comment]
Thanks for asking. I will bring up this feature within the team and let you know next week.

**Comment by MMaggieZhou** [comment]
Hi, we have fixed the export issue for your on our end. Let us know if you have unblocked.

**Comment by jtliao** [comment]
Hi, unfortunately this is not something we can support anytime soon. I'd recommend doing the parsing on your end, it should be simple to pull the list of symbols and use Regex to parse it.
