### ISSUE TITLE
Number entities is not working

### ISSUE THREAD

**Issue by eduardovoll** [wit-ai/wit#1602]
report a *bug*

**What is the current behavior?**
Does not recognize numbers by entities

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
In the console itself enter the text "number 1", it does not recognize the number in the text

**What is the expected behavior?**
Understand the text and recognize that it is a number within the text

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
APP ID: 3140859945930357

**Comment by eduardovoll** [comment]
> report a _bug_
> 
> **What is the current behavior?**
> Does not recognize numbers by entities
> 
> **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
> In the console itself enter the text "number 1", it does not recognize the number in the text
> 
> **What is the expected behavior?**
> Understand the text and recognize that it is a number within the text
> 
> **If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
> APP ID: 3140859945930357

Done

**Comment by jtliao** [comment]
Hi @eduardovoll, you need to add the `number` entity to your app first.

**Comment by eduardovoll** [comment]
Hi, Liao

How can I ser number entity in my app?

Regards.
Eduardo

Em sáb, 23 de nov de 2019 15:41, Jason Liao <notifications@github.com>
escreveu:
