### ISSUE TITLE
Training sticked in on-going status

### ISSUE THREAD

**Issue by serdalbayram** [wit-ai/wit#1603]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
Training is still on-going status for very long time 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2677939075591789

**Comment by MMaggieZhou** [comment]
We have retrained your app and it has finished. Please let us know if you are unblocked.

**Comment by serdalbayram** [comment]
Thank you it is working now
