### ISSUE TITLE
Issue with validating the expression

### ISSUE THREAD

**Issue by web-pda** [wit-ai/wit#1605]
I have a problem about validation. When I click "validate", It gives an error which is below.

![wit_problem](https://user-images.githubusercontent.com/48081365/69616182-35d38b00-1047-11ea-97bc-a647d1946ad5.png)

![image](https://user-images.githubusercontent.com/48081365/69616684-1426d380-1048-11ea-9e36-a19ec27e9681.png)

My app ID is 2995832480432509

Please inform me as soon as possible.

**Comment by jtliao** [comment]
Can you try refreshing your page? Seems similar to #1600

**Comment by web-pda** [comment]
I try it and it still gives the same error.

**Comment by web-pda** [comment]
This problem started 3 days ago we closed and opened the page many times but it still gives error. Refreshing did not solve :(

**Comment by jiayexie** [comment]
Hi @web-pda, we have identified the issue and are working on fixing it. Will update this thread once we have the fix in place.

**Comment by jiayexie** [comment]
@web-pda, could you please try again? We've fixed the issues on our end and it should be working for you.
