### ISSUE TITLE
Train via HTTP API not working

### ISSUE THREAD

**Issue by serdalbayram** [wit-ai/wit#1607]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
Training via API (to add samples via HTTP API service) not working.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Adding samples via "post https://api.wit.ai/samples?v=20170307" not working 
[{
        "text": "our products",
        "entities": [
          {
          	 
            "entity": "intent",
            "value": "31299_ürünlerimiz nelerdir"
          
          }
        ]
      }
 ]

Although response is 

{
    "sent": true,
    "n": 1
}

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
All Apps have the same error (e.g 3064271876980515)

**Comment by jiayexie** [comment]
Hi @serdalbayram, what do you mean by "not working"? For the app id you provided, I see that all the samples post APIs went through correctly and there have been 12 samples trained for this app.

**Comment by serdalbayram** [comment]
But since yesterday, this is not working.

**Comment by jiayexie** [comment]
Could you please elaborate on "not working"? Please answer the question "What is the expected behavior?" in the template in order for us to help you.

**Comment by serdalbayram** [comment]
After API call (https://api.wit.ai/samples?v=20170307), new text sample is not added to the App since yesterday.

**Comment by serdalbayram** [comment]
Start working again
