### ISSUE TITLE
Wit/number:role_name missing in the API Output

### ISSUE THREAD

**Issue by kidstell** [wit-ai/wit#1608]
**I have a question about creating entities in Wit**

![image](https://user-images.githubusercontent.com/19243382/69893686-75cf9200-1315-11ea-8372-2a4c08566cdd.png)

**Current Behavior**
From the screen shot above, Wit seems to identify my entities correctly but when i preview the API Output, the size entity is missing even after I have trained it with a few examples. see below for the API Output. 
```{
  "_text": "1gb to ade",
  "entities": {
    "unit": [
      {
        "confidence": 0.9696087683501,
        "value": "gb",
        "type": "value"
      }
    ],
    "recipient": [
      {
        "suggested": true,
        "confidence": 0.9017481921548,
        "value": "ade",
        "type": "value"
      }
    ],
    "intent": [
      {
        "confidence": 1,
        "value": "data_sub"
      }
    ]
  },
  "msg_id": "1SwfhQoljgbYT9voE"
}
```

**Is this a Bug?**
I am not sure if this is a bug, even when i train wit with the same string repeatedly, the Output still won't contain the Wit/number:size.
could there be a better way of achieving this. My goal is to allocate disk space to contacts or phone identifiers on a server.

**What is the expected behavior?**
I expect that the Wit/number:size entity should be a part of the API Output, and this is currently missing.

**App ID: 2450667728393314**

**Comment by jiayexie** [comment]
Hi @kidstell, thanks for reporting; I can confirm. Could you please try removing the "size" role on the slot and see if it works?

**Comment by kidstell** [comment]
> Hi @kidstell, thanks for reporting; I can confirm. Could you please try removing the "size" role on the slot and see if it works?

Thanks, I removed the role and it seems to work fine. for my current use cases, this will be fine. perhaps it failed to work since there was just one role to choose 

```
{
  "_text": "2mb to 08054545454",
  "entities": {
    "number": [
      {
        "confidence": 1,
        "value": 2,
        "type": "value"
      }
    ],
    "unit": [
      {
        "confidence": 0.97768005375547,
        "value": "mb",
        "type": "value"
      }
    ],
    "recipient": [
      {
        "confidence": 0.95496814009464,
        "value": "08054545454"
      }
    ],
    "intent": [
      {
        "confidence": 1,
        "value": "data_sub"
      }
    ]
  },
  "msg_id": "1onZlcCCYWFhPtmhx"
}
```

**Comment by jiayexie** [comment]
Thank you for confirming! It is a bug on our side that wit/number doesn't work with roles. We will work on a fix and let you know when it's ok to add the role back.

**Comment by jiayexie** [comment]
@kidstell, I made a fix so the role should be working now. Would you please add the role back and check if it works?

**Comment by kidstell** [comment]
@jiayexie sorry for the late response. i created a different app where i used a custom entity. so i stopped adding role to the wit/integer. I will be glad to use this feature asap. thanks for your sound and prompt feedback. I also hope to contribute more and improve the community.
