### ISSUE TITLE
Looking for a streaming (vanilla JS) example

### ISSUE THREAD

**Issue by rvegele** [wit-ai/wit#1609]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question / reques

**What is the current behavior?**
I'd love to see an example of streaming microphone audio with webRTC alone, meaning no websockets. The microphone example uses websockets and a coffeescript? under the hood and the actual 'send data stream' behaviour is masked there. Something that's vanilla JS and doesn't require add-on's / frameworks on top would be really appreciated. 

I can currently construct the connection to the mic (I know it's very browser/platform dependent) and build data-packets, but am not sure of the best way to actually transmit those to wit.

The microphone example uses "@conn.send(int16s)" which is basically delegating the sending to WS but unfortunately that's a black box to me at the moment. So again, something that's more basic and raw code would be really helpful to explain for a beginner. 

Thanks! 

This is how my code looks thus far. It works OK up till this end. 

`

        const handleSuccess = function(stream) {
	self.stream = stream;
	self.context = new AudioContext();
	self.source = self.context.createMediaStreamSource(self.stream);
	self.processor = self.context.createScriptProcessor(4096, 1, 1);
		    
	self.source.connect(self.processor);
	self.processor.connect(self.context.destination);
		    
	self.processor.onaudioprocess = function(e) {
		let buffer = e.inputBuffer;
		let float32s = buffer.getChannelData(0);
		let n_samples = float32s.length;
		let int16s = new Int16Array(n_samples);

		for (i = 0; i<n_samples; i++) {
			x = float32s[i];
			if (x < 0) {
				y = x * 0x8000;
			} else {
				y =  x * 0x7fff;
			}
			int16s[i] = y;
		}

		// @conn.send(int16s) from microphone example
		// WHAT DO I DO HERE???
	};
};

navigator.mediaDevices.getUserMedia({ audio: true, video: false }).then(handleSuccess);

`

**Comment by jtliao** [comment]
Hi @rvegele, we currently don't have support for streaming outside of Websockets. 

As for the question about sending the data stream, it's not necessarily masked, but after the `auth` and `start` messages, we begin accepting raw audio, which is being done by `@conn.send(int16s)`.
