### ISSUE TITLE
Transfering ownership isn't working

### ISSUE THREAD

**Issue by sebastianarena** [wit-ai/wit#1611]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
BUG

**What is the current behavior?**
When I get invited to share an app, it works as expected
I don't get an email, but I do see the app on Shared Apps
However, if people want to transfer ownership of the App.. it says I've been notified, but I haven't, and this cannot transfer the app

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Create an app with User A
2. Share app with User B (no email is sent, but app is shared)
3. Transfer app to User B (no email is sent, and thus can't confirm transfer)

**What is the expected behavior?**
Be able to receive an email and transfer an app

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
All of the following apps should be transfered to user chat-tonic, which is already shared as user
2428463013855806
2336462376477209
2089037864529260
2732654683419558
2321204498005044

**Comment by kitchWWW** [comment]
Hello! thank you for reaching out: I tried to reproduce the email / transfer failure, but was unable to with the steps provided. However, I'm more than happy however to transfer the apps to the user `chat-tonic`. If you please confirm this as your intention, I'll go ahead and transfer ownership of the apps.

**Comment by sebastianarena** [comment]
Yes please!

Just for reference, I get no email when a user shares an app with me either. I don’t know if a Facebook setting might be affecting this, as I am logged in through that. Hope it helps!

**Comment by kitchWWW** [comment]
Alright, thanks for being patient! the five app ids you listed should now be owned by user `chat-tonic`. We are looking into the email issue, and will reach out if we need any more additional information. Thanks again, and please let us know if you have any other issues!
