### ISSUE TITLE
Persian is not supported

### ISSUE THREAD

**Issue by shahinesi** [wit-ai/wit#1612]
**when I send this request for the Persian language:**

```
# Wit speech API endpoint
API_ENDPOINT = 'https://api.wit.ai/speech?v=20191206'

# Wit.ai api access token
wit_access_token = 'HSZNEZQYLWDPSKCHLCVT5IYJCFHXUZSH'

def RecognizeSpeech(AUDIO_FILENAME, num_seconds = 5):
        
    # reading audio
    audio = read_audio(AUDIO_FILENAME)
    
    # defining headers for HTTP request
    headers = {'authorization': 'Bearer ' + wit_access_token,
               'Content-Type': 'audio/raw;encoding=signed-integer;bits=16;rate=16000;endian=little'}

    # making an HTTP post request
    resp = requests.post(API_ENDPOINT, headers = headers,
                         data = audio)
    
    # converting response content to JSON format
    data = json.loads(resp.content)
    
    # get text from data
    #text = data['_text']
    
    # return the text
    return data
```

> You said: {'code': 'bad-request', 'error': 'Speech recognition is not supported for language: fa'}

App ID : 2521821944599924

**Comment by kitchWWW** [comment]
Hello! Thank you for reaching out: Unfortunately, Persian is not on our list of supported languages at this time. Please let us know if you have any additional concerns.

**Comment by shahinesi** [comment]
> Hello! Thank you for reaching out: Unfortunately, Persian is not on our list of supported languages at this time. Please let us know if you have any additional concerns.

How Use @voicy bot telegram from Persian ?
