### ISSUE TITLE
Can not export app data

### ISSUE THREAD

**Issue by longlvt** [wit-ai/wit#1613]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
Can not export app data

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
download app data as .zip file

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
597011f5-73bf-4e1c-bc8a-7ec4a868213f

**Comment by jtliao** [comment]
apologies for the delay, this should be addressed now

**Comment by longlvt** [comment]
Thanks @jtliao.
