### ISSUE TITLE
App is currently training (7 days)

### ISSUE THREAD

**Issue by eurocharts** [wit-ai/wit#1616]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
App is currently training. Last 7 days this status. All this time app understands a sentences with a mistakes. Sometimes 1 or 2 letters it counts as an random entity with 0.504 value

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2184728738274083

**Comment by aforaleka** [comment]
Hi @eurocharts, the number of entities in your app is larger than what our training can handle at the moment. We're actively working on improving our machine learning infra and supporting apps like yours. Thank you for your patience while we work on the issue!
