### ISSUE TITLE
Server doesn't support requests with Content-type with spaces(like "audio/raw; param1=value1; param2=value2")

### ISSUE THREAD

**Issue by HavenDV** [wit-ai/wit#1617]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
*bug*

**What is the current behavior?**
I am having problems using your API and am getting the following error:
{
   "code": "unsupported-content-type",
   "error": "Unsupported content-type: 'audio/raw; encoding=unsigned-integer; bits=16; rate=8000; endian=little'"
}
Request has been sent to "https://api.wit.ai/speech?v=20200103" with 
Authorization and Content-Type headers

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
```csharp
using System.Net.Http;

var client = new HttpClient();
var request = new HttpRequestMessage(HttpMethod.Post, "https://api.wit.ai/speech?v=20200103")
{
    Headers =
    {
        { "Authorization", "Bearer KATWBG4RQCFNBLQTY6QQUKB2SH6EIELG" },
    },
    Content = new ByteArrayContent(Array.Empty<byte>())
    {
        Headers =
        {
            { "Content-Type", "audio/raw;encoding=unsigned-integer;bits=16;rate=8000;endian=little" },
        }
    },
};
//[Method: POST, RequestUri: 'https://api.wit.ai/speech?v=20200103', Version: 1.1, Content: System.Net.Http.ByteArrayContent, Headers:
//{
//  Authorization: Bearer KATWBG4RQCFNBLQTY6QQUKB2SH6EIELG
//  Content-Type: audio/raw; encoding=unsigned-integer; bits=16; rate=8000; endian=little
//}]

var response = await client.SendAsync(request);
//[StatusCode: 400, ReasonPhrase: 'Bad Request', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
//{
//  Connection: keep-alive
//  Date: Thu, 02 Jan 2020 19:33:21 GMT
//  Content-Length: 154
//  Content-Type: application/json
//}]

await response.Content.ReadAsStringAsync()
//"{\n  \"code\": \"unsupported-content-type\",\n  \"error\": \"Unsupported content-type: 'audio/raw; encoding=unsigned-integer; bits=16; rate=8000; endian=little'\"\n}"
```

**What is the expected behavior?**
According to the documentation, this Content-Type is supported (examples of using this Content-Type are also given) -> https://wit.ai/docs/http/20170307#post__speech_link

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2876958245650136

**Comment by aforaleka** [comment]
hi @HavenDV, can you try using the API directly with curl and see if you get the same error? And if you can provide an example audio file, that might be helpful for us to debug.

**Comment by HavenDV** [comment]
I researched the question and found the problem:
This works correctly and returns "No request body provided":
```
curl -XPOST "https://api.wit.ai/speech?v=20170307" -i -L -H "Authorization: Bearer KATWBG4RQCFNBLQTY6QQUKB2SH6EIELG" -H "Content-Type: audio/raw;encoding=unsigned-integer;bits=16;rate=8000;endian=big"
```
This does not work and returns "Unsupported content-type: 'audio/raw; encoding=unsigned-integer; bits=16; rate=8000; endian=big'":
```
curl -XPOST "https://api.wit.ai/speech?v=20170307" -i -L -H "Authorization: Bearer KATWBG4RQCFNBLQTY6QQUKB2SH6EIELG" -H "Content-Type: audio/raw; encoding=unsigned-integer; bits=16; rate=8000; endian=big"
```
The problem is that you do not support spaces after ';' which are allowed according to the specification - https://tools.ietf.org/html/rfc7231#section-3.1.1.5, and which are automatically added when using HttpClient in C#

**Comment by HavenDV** [comment]
It is also a C# problem that there is no way to easily bypass header normalization - https://github.com/dotnet/corefx/issues/18449

**Comment by lycai-fb** [comment]
Thanks for surfacing this issue @HavenDV 
The fix should be out soon. Please reopen this task if you're still having issues in a couple of days.

**Comment by showment** [comment]
Still experiencing this issue, I'm also using C#.

**Comment by showment** [comment]
Actually my mistake, it seems like the library was adding another parameter, which was causing the error.
