### ISSUE TITLE
handle accents strings

### ISSUE THREAD

**Issue by doriclaudino** [wit-ai/wit#1619]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
bug 1: UI don't show accents
bug 2: Those messages with "accents bug strings" I can't validade or delete from my list.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

request /message endpoint
use some accents on the message
I realize this bug start 2-3 days ago.

**What is the expected behavior?**
![image](https://user-images.githubusercontent.com/3863501/71769982-b4b1c280-2f27-11ea-8595-4f63b6c4c9e9.png)

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
3385537998125206

**Comment by aforaleka** [comment]
Merging with #1618 to keep track.
