### ISSUE TITLE
Link broken in docs (Raspberry Pi Quickstart)

### ISSUE THREAD

**Issue by patapizza** [wit-ai/wit#162]
In the [Raspberry Pi Quickstart](https://wit.ai/docs/raspberry-pi/quickstart) docs, the link to the "direct HTTP API" is broken, "docs" is missing.

Expected: https://wit.ai/docs/http/
Actual:  https://wit.ai/http/index.html

**Comment by blandinw** [comment]
Nothing is someone else's problem!

**Comment by blandinw** [comment]
http://dictionary.reference.com/browse/kaizen

**Comment by patapizza** [comment]
It should be fixed by now!
