### ISSUE TITLE
export : Something went wrong.

### ISSUE THREAD

**Issue by doriclaudino** [wit-ai/wit#1620]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
error: "Something went wrong. We've been notified", code: "unknown"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
GET https://api.wit.ai/export

**What is the expected behavior?**
receive a .zip link to download

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2818791271466506

**Comment by aforaleka** [comment]
hey @doriclaudino, can you try again? The issue should be fixed.

**Comment by doriclaudino** [comment]
@jtliao yes, works, thanks
