### ISSUE TITLE
Arabic language app are not working properly 

### ISSUE THREAD

**Issue by 91ns** [wit-ai/wit#1621]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
When training expressions in Arabic language they appear as question marks 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
![image](https://user-images.githubusercontent.com/25252530/71778517-93001c00-2fb7-11ea-944b-1437dbe21258.png)

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
   2256792411082295

**Comment by jtliao** [comment]
merging with #1618

**Comment by hno1993** [comment]
this problem also appears with me just a few days ago, I think i closed by new update ...
please, developers fix it
