### ISSUE TITLE
Settings page forwards me to the "something went wrong page".

### ISSUE THREAD

**Issue by nateac1** [wit-ai/wit#1622]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
I'd like to report a bug.
**What is the current behavior?**
After setting the first version of the app, the settings page will load for a fraction of a second before showing me the "Something went wrong" page. Intermittently, on the entities webpage, the entities will be greyed out or empty squares when I type a sentence. I'll edit this post with a picture if it happens again. 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I've tried analyzing the GET requests in BurpSuite, however, my browser stops the connection since it strips the SSL layer from the traffic and won't allow me to make an exception. To initiate an issue, start versioning the application and go back to work on the entities page. Add new sentences and/or entities, then attempt to go back to the settings page to save any changes. The settings page should load for a second, then redirect you to the "Something went wrong" page, with the correct URL still in the address bar. The settings page is available on my mobile phone, however, the error persists on the laptop regardless of clearing the cookies and cache. I've changed the user agent on the laptop just in case, but it didn't fix the issue.
**What is the expected behavior?**
The expected behavior is to load the settings page for the application, and not redirect to an error page.
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
The application number is 2692921914095858

![beforeerror](https://user-images.githubusercontent.com/16395893/71787222-dddf5b00-2fda-11ea-9693-18f726f58989.png)
![error](https://user-images.githubusercontent.com/16395893/71787224-e041b500-2fda-11ea-8548-cd54224f2936.png)

**Comment by FengyangZhang** [comment]
Hi @nateac1, we are not able to find any error logs associated and seems the version '0.1.0' is created successfully. Do you see the "something went wrong" page when saving a second version?

**Comment by nateac1** [comment]
> Hi @nateac1, we are not able to find any error logs associated and seems the version '0.1.0' is created successfully. Do you see the "something went wrong" page when saving a second version?

I'll try to save another version and let you know how it turns out.
