### ISSUE TITLE
Speech recognition stopped working for Greek lnaguage

### ISSUE THREAD

**Issue by asfyra** [wit-ai/wit#1623]
Hello, 
we used to use speech api with our application which is in the Greek language and everything was working fine. The speech recognition was performing very well.

Since last month we get an error saying that 
`{
  "code": "bad-request",
  "error": "Speech recognition is not supported for language: el"
}`

Why is this happening, since the Greek language was supported very well?

Is it something in our application that causes the problem? Our application id is 2338373192925238

Happy new year

Alex

**Comment by lycai-fb** [comment]
Hi Alex,
Unfortunately we can no longer support Greek for speech recognition.
You can take a look at the [https://wit.ai/faq](FAQ) to see the list of languages that we do support.
