### ISSUE TITLE
inbox expression problem with the Arabic language

### ISSUE THREAD

**Issue by hno1993** [wit-ai/wit#1624]
a few days ago the application was running perfectly..
but now if I try to send "اريد حجز 4 تذاكر طيران إلى الكويت" 
`witClient.message("اريد حجز 4 تذاكر طيران إلى الكويت")`

my wit.ai app understand it correctly and return:
`{'_text': 'اريد حجز 4 تذاكر طيران إلى الكويت', 'entities': {'flightBooking': [{'confidence': 1, 'value': 'أحجز', 'type': 'value'}], 'TicketsNo': [{'confidence': 0.99383004668764, 'value': 4, 'type': 'value'}], 'ticketQuantity': [{'confidence': 1, 'value': 'جمع', 'type': 'value'}], 'To': [{'suggested': True, 'confidence': 0.99058321385597, 'value': 'الكويت', 'type': 'value'}], 'booking_intent': [{'confidence': 0.99998576015414, 'value': 'BookFlight'}]}, 'msg_id': '1BATvcRTVizDOVuzm'}`

but when I tried to validate this sentence in the inbox I keep getting question marks
![image](https://user-images.githubusercontent.com/44380685/71890605-b660cd80-3155-11ea-88c9-8bc634b35a6b.png)
and when I try to delete it or press validate it keep appear in contrast if the whole sentence were in English language 

note: I try different wit.ai app token and the problem still exists. i am using python 3.7
my application ID : 3179188082152056

**Comment by lycai-fb** [comment]
Looks like same bug as #1618; merging.
You can check there for updates
