### ISSUE TITLE
Duckling + Wit in Hebrew & Other Non-US countries - Dates & Amounts

### ISSUE THREAD

**Issue by idanadut** [wit-ai/wit#1626]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Questions (& possible feature request)

Hi,

A few questions - would really appreciate your help:
1) **Typos** - if there is a typo like "last **Decmber**" (both in English & Hebrew) it will not understand it, and I see no way of controlling it or adding keywords. what do you think?

2) **Reverse US English format vs. Hebrew & other countries**
(i) In Hebrew (Also in all of Europe and most of the world) when one writes 7.1 - he means 7th of January not 1st of July.
(ii) In Hebrew, when one writes ("August 19" - in Hebrew ״אוגוסט 19״) - he means august in the year of 2019 and not 19th of august
My question on this - (a) How can I control these? (b) If I can't, how can I contribute or make a request to you to handle this? (c) If I will contribute, how much time do you estimate changes will be approved an in production?

3) **Hebrew Examples/Phrases Training** - 
(a) How can I add more examples or rules for you to approve (such as "מחרתיים" ,which mean "the day after tomorrow")? I suppose to be added to these files:
https://github.com/facebook/duckling/blob/master/Duckling/Time/HE/Corpus.hs 
https://github.com/facebook/duckling/blob/master/Duckling/Time/HE/Rules.hs
(b) In the Hebrew Corpus file (link above), there are a lot of commented phrases -which are actually really good but are not working since they are commented.
I guess there is some reason for that - Why is that? When could these examples be available? *Phrases such as "ב15 לחודש" (which mean "on the 15th of this month"), "שנה שעברה" (which means "last year"), "לפני שלושה חודשים" (which means "three months ago").

4) **Date is always in the future** - It assumes a for example in "my orders in December" that the user means 01/12/2020 and not 01/12/2019) - is there a way to control it?

**General Questions (not related to duckling)**
1) **Keyword as substring problem** - When we have a 2 letter keyword or keyword that is popular as a substring (in other words) it classifies it also as a substring, not only as a real word. (i.e. -  lets say I have a keyword "app". If a message contains the word "appear" like "suddenly it appeared". This message has no relation to the keyword "app", yet almost always wit will classify it). How can I control that so that only real words (separated by space) will be classified, and not substrings. I saw some questions on the issue but didn't understand if there is a solution in wit.
2) **Addition to API** - Is there a possibility to receive the original word of message that was classified from the API? (i.e. - "schedule a meeting on August 19". API will return "DATE=08/19/2020". Is there a possibility to also receive the actual phrase it classified, so the response would be something like "DATE={ date = 08/19/2020, phrase = "August 19"}")? It could be very useful to better understand the text after wit analyzes it - for example, it could solve problem (2) above.

Thank you!
Idan

**Comment by jtliao** [comment]
Duckling
1. Typos are not handled, since Duckling is doing exact rule matching
2/3a. The time rules are here (https://github.com/facebook/duckling/blob/master/Duckling/Time/HE/Rules.hs), feel free to submit a pull request
3b. I think it's because the rules don't exist yet to handle those test cases, so they are commented out. If the rules are added to support them, they can be uncommented. 

General
1. Can you give an example in your app (with an app ID)? In general, there should not be keyword extraction for substrings. 
2. if you input `verbose=true` as a query parameter to `GET /message`, you'll get back the `_start` and `_end` values for the entity, which you can use to construct the original text.

**Comment by idanadut** [comment]
Hi Jason, Thanks so much for the quick & detailed answer, very helpful!
My Comments:

Duckling

1. Got it. Usually, if I define my own entity with keywords I would put in the synonyms common typos so that Wit will still understand the message with typos. However, in the built-in entities (like datetime) I cannot, so in the case of "last Decembr" I will not understand anything. Making this a broader "Wit" (not duckling) issue, do you have a suggestion on how to handle these cases?
2. If I submit a pull request of this kind, do you have an estimation on approval and update times? I'm asking since its Hebrew rules - how do you validate it and how long does it take?
3. I thought maybe someone thought of these useful examples but put in comments with no supporting rules for some special reason. Anyways, I'll check it out and contribute.


General

1. App Id: 2646309675417270
Put in this message: "תאגודה". You will receive a keyword AGODA form the substring "אגודה".
I will mention before you think about this bug a theory why it happens but it's just a guess - that in Hebrew (unlike in English), connector words like "a", "in", "to" will be a prefix of one letter to the actual word. for example "חדר" means "room", and to say "in room" it would be "בחדר". So, if that's the case it actually is good, but obviously its often not the case and then this substring extraction is not good.

**Comment by jtliao** [comment]
Duckling
1. Unfortunately there isn't a solution for resolving built-in entities like this. One hack I can think of is having a custom keyword entity that handles these cases (like "December", which will also extract "Decembr"), then resending that keyword to get the relevant `datetime` value
2. I'm not sure, since Duckling is another project-- we'll try to get it approved as soon as possible though.

General
1. I think this is because keywords are intended to be robust to small typos (like "Decembr" in the previous example), which would explain why this is resolving

**Comment by idanadut** [comment]
Hi @jtliao !

So I just made the enhancements in Hebrew we discussed here and made a pull request to duckling project (Enhancement + Fixes for Hebrew Language - Duration+TimeGrain+Time+Amount #448).
-Will it be automatically available in wit.ai apps when you/they approve and push? 
-Do you think it's realistic it could happen this week?

Thanks,
Idan


**What's included**:
Mostly these enhancements are about new Hebrew grammer options to write time intervals, catch simple times correctly, and handle more complex forms like Hebrew plural forms.
**Examples**:
Phrases such as "ב15 לחודש" (which mean "on the 15th of this month"), "שנה שעברה" (which means "last year"), "לפני שלושה חודשים" (which means "three months ago"), "חצי שנה אחרונה" ("past half a year"), "בין 15 לנובמבר לבין 18 לדצמבר" ("between 15th of November to 18th of December")  - will now work correctly!
