### ISSUE TITLE
Can't login with Github. "Something went wrong 😣 Please refresh or create a Github issue here."

### ISSUE THREAD

**Issue by nickcbarone** [wit-ai/wit#1627]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

*Bug*

**What is the current behavior?**

"Something went wrong 😣 Please refresh or create a Github issue here."

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Try signing in using your GitHub credentials.

**What is the expected behavior?**

To sign in successfully.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by nateac1** [comment]
Hey this is happening to me as well. It might be server maintenance or something. I'll try it again in a few hours and let you know if it starts working for me.

**Comment by lycai-fb** [comment]
Hi all,
The website is currently down due to some unexpected issues with a backend upgrade.
The team is working hard right now to fix it.
Thanks.

**Comment by Bakersbakebread** [comment]
Still down, querying over HTTP seems to be working smoothly though.

**Comment by lycai-fb** [comment]
To clarify on the issue: the main Wit.ai website currently has some Javascript errors and cannot be accessed. **The API endpoints are not affected.**

A fix has been found and (if all goes well) the website should be up again in a few hours.
Thanks for your patience. :)

**Comment by yra-wtag** [comment]
Still having the issue

**Comment by Pal-Pooja** [comment]
I am getting error while signing up into the github
