### ISSUE TITLE
Error with Vietnamese language

### ISSUE THREAD

**Issue by vietdang7** [wit-ai/wit#1629]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug
**What is the current behavior?**
I am trying to train the bot with Vietnamese sample, it worked well before but at the moment all the current sample inputs were converted wrongly 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
For example: the correct sample input is "có giặt được không em" is converted to  "c? gi?t ???c kh?ng em"  after validation
**What is the expected behavior?**
"có giặt được không em" after validation should be "có giặt được không em"
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2448057181984089

**Comment by jtliao** [comment]
Merging with #1618, we are still investigating the issue
