### ISSUE TITLE
mon - thu returns wit/datetime for monday to friday

### ISSUE THREAD

**Issue by damianskobel** [wit-ai/wit#1630]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
report a *bug*  

**What is the current behavior?**
days range: mon - thu
results with: wit/datetime from13.01.2020, 00:00:00 to 17.01.2020, 00:00:00
where 17.01.2020 is friday

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
curl --request GET \
  --url 'https://api.wit.ai/message?v=20160526&q=mon%20-%20thu' \
  --header 'authorization: Bearer $TOKEN'

**What is the expected behavior?**
wit/datetime from13.01.2020, 00:00:00 to 16.01.2020, 00:00:00

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by lycai-fb** [comment]
Hi Damian,
The date range returned is from midnight the start of Monday to midnight the end of Thursday and is expected behavior.
Thanks.

**Comment by damianskobel** [comment]
I'm sorry but that doesn't make sense, friday is friday not thursday
