### ISSUE TITLE
everything in Greek language appears as gibberish

### ISSUE THREAD

**Issue by sophiexr** [wit-ai/wit#1632]
hi,

In our app 5b28e553-b6b4-42fe-8fe8-5b8f3e6b32ae, everything that should be in Greek language, appears suddenly as gibberish.

![image](https://user-images.githubusercontent.com/48153186/72322292-b1000780-36ae-11ea-9d4d-ab7bc3a50926.png)

thanks

**Comment by sophiexr** [comment]
also delete doesn't work (in Inbox or in Samples)

![image](https://user-images.githubusercontent.com/48153186/72340070-2f20d600-36d0-11ea-902c-0b79ea79d09f.png)

**Comment by jtliao** [comment]
This should be addressed now, if not please forward discussion to #1618
