### ISSUE TITLE
Why speech recognition for Persian language is not supported any more?

### ISSUE THREAD

**Issue by BabakMahmoudi** [wit-ai/wit#1633]
I have been using speech recognition for Persian language. Then i began to receive the 'Unsupported language' error, and it's strange that some other applications namely 'voicybot' are still using this feature. I believe i am using the api exactly the same way and still get the error. Is there an workaround?

**Comment by jtliao** [comment]
Hi @BabakMahmoudi, unfortunately we are no longer able to support Persian speech recognition. That language will be deprecated on March 1, 2020. We've allowed existing users to continue until then, but not new clients since it will be gone soon.

**Comment by BabakMahmoudi** [comment]
Hi @jtliao , thanks for this information. Is there any chance that the engine can be continued by a community of users?
