### ISSUE TITLE
Exporting not showing all data 

### ISSUE THREAD

**Issue by jurneek** [wit-ai/wit#1634]
Export files aren't returning all of our expressions. Are export files being limited on the data they provide?

**Comment by dupengling** [comment]
Hey @jurneek, occasionally inconsistencies within an app can cause export issues. Can you let me know your App ID so that I can debug?

**Comment by jurneek** [comment]
@dupengling sorry do you work for Wit?

**Comment by dupengling** [comment]
@jurneek yes, I work for Wit.

**Comment by jurneek** [comment]
@dupengling can I get your WIT email I'd prefer to share the app ID over email?

**Comment by jtliao** [comment]
Sharing your app ID does not risk your app, and it make it easier to collaborate to solve the issue. However if you really are uncomfortable sharing it, please e-mail it to jtliao@fb.com
