### ISSUE TITLE
Dealayed Response - Increased latency - Response time is between 1100-2500 ms

### ISSUE THREAD

**Issue by monika1800** [wit-ai/wit#1635]
Hi,
Help Needed. Observing sudden increase in response time.

App ID: 5a4de8e6-902a-4090-85da-030bea2df754

**Comment by jtliao** [comment]
Hi @monika1800, how are you measuring latency on your side? Looking at the logs from our side, the average latency is 150ms, with a maximum of about 400ms, so nothing near 1100-2500ms.

**Comment by monika1800** [comment]
Hi @jtliao I am testing it through 
resp = client.message(raw_query, verbose=True)
The response time is still around 1200-1500ms

**Comment by monika1800** [comment]
Checked time through curl aslo. It is still showing between 0.9-1.2 seconds

**Comment by jtliao** [comment]
Could it be the network connection from your end? No logic/latency has changed from our side.
