### ISSUE TITLE
Export generate nulls

### ISSUE THREAD

**Issue by doriclaudino** [wit-ai/wit#1636]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
274 samples get property text = null 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
click on export
**What is the expected behavior?**
export correct data
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App_id: 3385537998125206

example_bug_message_id: '1JIyEN39UCT8epZpx'

I'm trying for 20 days export 2 projects without success, probably is related with [bug](https://github.com/wit-ai/wit/issues/1618)

There's any chance to receive my two projects exported **correctly** by e-mail?

**Comment by FengyangZhang** [comment]
Should be related to the bug. The samples are not totally fixed yet, let me fix yours first.

**Comment by idanadut** [comment]
Hi @FengyangZhang
Is it possible to also somehow receive them correctly by e-mail or something? I'm also waiting for this to be fixed for a few weeks.
App Id: 2646309675417270. Language: Hebrew
Thanks

**Comment by doriclaudino** [comment]
Any update? I'm still waiting for this bug and as well for https://github.com/wit-ai/wit/issues/1618 (on month tomorrow)

It's not an technology issue that we can workaround, someone mess our data with an update on code/infra/db. Still getting 270+ texts as nulls

**Comment by FengyangZhang** [comment]
We've completed a scan and fix on all data. If the export still shows nulls, please delete the incorrect samples, thanks!
