### ISSUE TITLE
Several intents matched in Inbox->Expressions

### ISSUE THREAD

**Issue by asfyra** [wit-ai/wit#1637]
Hello i would like to ask a question for the application with id: 
5b1e505b-0e5f-484a-9e44-20d7c4ee12d1

We noticed recently that the expressions functionality of the inbox page inside wit, displays more than one matching intents in it's results.
This did not happen in the past. Why is this happening now and how could this be fixed ?

![image](https://user-images.githubusercontent.com/6898230/73243548-8767d580-41b0-11ea-8845-50d0cc4b654c.png)

Thank you
Alex

**Comment by timmyRS** [comment]
These are two seperate traits so they are individual matches, it is up to your code to interpret the result.

**Comment by asfyra** [comment]
@timmyRS i realize that and that's what we already do. The point is that up until now the expressions page returned only one trait. Why is it returning more traits now? Has something changed ?

**Comment by wangsnowyin11** [comment]
This is expected to have multiple intents predicted. Since there could be multi traits created

**Comment by asfyra** [comment]
@wangsnowyin11, @timmyRS
 
Thank you for your responses.
