### ISSUE TITLE
New Hebrew Enhancements

### ISSUE THREAD

**Issue by idanadut** [wit-ai/wit#1638]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question - about Contribute enhancement for duckling for wit

Hi @jtliao !
Just noticed our Issue was closed, so opening this one.

I just made the enhancements in Hebrew we discussed here and made a pull request to duckling project (Enhancement + Fixes for Hebrew Language - Duration+TimeGrain+Time+Amount #448).

-Will it be automatically available in wit.ai apps when you/they approve and push?
-Do you think it's realistic it could happen this week?

Thanks,
Idan

What's included:
Mostly these enhancements are about new Hebrew grammer options to write time intervals, catch simple times correctly, and handle more complex forms like Hebrew plural forms.
Examples:
Phrases such as "ב15 לחודש" (which mean "on the 15th of this month"), "שנה שעברה" (which means "last year"), "לפני שלושה חודשים" (which means "three months ago"), "חצי שנה אחרונה" ("past half a year"), "בין 15 לנובמבר לבין 18 לדצמבר" ("between 15th of November to 18th of December") - will now work correctly!

**Comment by jtliao** [comment]
Hey @idanadut, thanks for making the pull request! Unfortunately, Duckling is separate project, so I'm not quite sure how long it would take. Once it is pushed though, it will be available in Wit.ai automatically after a short delay.
