### ISSUE TITLE
speech recognition weak => can't train bc no playback in logs/game

### ISSUE THREAD

**Issue by adrifcastr** [wit-ai/wit#1639]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug
**What is the current behavior?**
Neither the logs nor the training can playback audio
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
sent audiostream via api => click play in logs/start training game thingy
**What is the expected behavior?**
audio playback?
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2723297194406632

**Comment by jtliao** [comment]
Thanks for raising this, we'll look into it.

**Comment by adrifcastr** [comment]
Thank you. Because I really do need to check the audio because it does not
at all detect what I am saying, and I can't check the audio, I can't check
where the issue lies.

**Comment by jtliao** [comment]
Can you give some more info about how you are making the request (the whole request you're sending would also be helpful, without the token), like the audio content type? I can't reproduce this for my own app/audio files. Also, if possible, attaching an example audio file that fails for you would be helpful.

**Comment by adrifcastr** [comment]
> Can you give some more info about how you are making the request (the whole request you're sending would also be helpful, without the token), like the audio content type? I can't reproduce this for my own app/audio files. Also, if possible, attaching an example audio file that fails for you would be helpful.

This is what I am doing: https://github.com/adrifcastr/Gideon/blob/master/cmds/voice.js#L30-#L77

**Comment by jtliao** [comment]
I see. The only thing I can think of is that the content type is mismatched, maybe try tweaking the content type to see if anything else works better?

**Comment by adrifcastr** [comment]
do you have any example options? From what I know is that discord creates a
16 bit signed little endian PCM stream.

**Comment by adrifcastr** [comment]
from what I see, this user had used the same content type https://github.com/wit-ai/wit/issues/822

**Comment by adrifcastr** [comment]
I fixed the issue, discord creates a **stereo** stream, I mixed it down to mono, and now it works as intended, sorry for the trouble.
