### ISSUE TITLE
Missing Wit/ entities in some languages?

### ISSUE THREAD

**Issue by vaxjool** [wit-ai/wit#164]
Hi, I'm currently exploring Wit.ai, but it seem that for example Wit/datetime is missing when using Swedish language settings. Is there a way to either get the same built in entities in Swedish as in English, or can you add an entity with specific formats (like date, time) and ranges?

**Comment by ar7hur** [comment]
Hi,

Language-dependent entities like wit/datetime are implemented in the open source project Duckling (https://github.com/wit-ai/duckling). Feel free to have a look and contribute if you can (we're here to help!).
