### ISSUE TITLE
Can't process /sentiment inbox

### ISSUE THREAD

**Issue by qfavor** [wit-ai/wit#1640]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug/Question
**What is the current behavior?**
I am sending /sentiment messages and when processing those that pop up in my inbox, after I click Validate, the message reappears instantly in the page just as if I didn't validate it.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
E.g.: I click on Inbox - > Expressions -> Change the /sentiment to 'neutral' and then click 'Validate'.  The row disappears for half-a-second and then reappears in the page.
**What is the expected behavior?**
The messages used to get validated and then it would become available in /samples.
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2599960866722323

**Comment by FengyangZhang** [comment]
Should have been fixed now, please try again.

**Comment by qfavor** [comment]
It works now, thank you!
