### ISSUE TITLE
Android github login callback broken/wav playback in web dashboard broken on desktop

### ISSUE THREAD

**Issue by adrifcastr** [wit-ai/wit#1641]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Multiple bugs
**What is the current behavior?**
->Trying to login via GitHub on Android returns in the callback URL providing an error on every attempt.
->Trying to playback any audio on the website does not work in any desktop browser.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
->try to log-in via github on an android device
->try to playback logged audio files/do the learning game
**What is the expected behavior?**
->successfull login via github oauth
->successfull audio playback in logs/training game
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2723297194406632

**Comment by wangsnowyin11** [comment]
Hey 
1. I am not sure login to github failure is related to our product. Could you provide error message?
2. Could you provide more info, such as does it work before, did you just send audiostream via api, then playback?

**Comment by adrifcastr** [comment]
> Hey
> 
> 1. I am not sure login to github failure is related to our product. Could you provide error message?
> 2. Could you provide more info, such as does it work before, did you just send audiostream via api, then playback?

When logging in I get this redirect and the error shown on the screenshot:
https://wit.ai/github_callback/?code=1e7db623f2be36f3867b&state=b7f47a3b-4231-4961-b42c-02b07edc52f4be9a1719-02bc-413f-bc54-47dbfc27ed0d
![Screenshot_20200203-195643_Chrome](https://user-images.githubusercontent.com/22133246/73681763-55c6a100-46bf-11ea-9c54-1a1be712cdc5.jpg)
And no since signing up I have been unable to playback any and all audio, no matter on which area of the web dashboard.
Neither the logs not the training game thingy provide any playback on any Web-Browser that I have tried.

**Comment by wangsnowyin11** [comment]
We are actively investigating the issue, thanks for your patience. Will get back to you once we figured it out

**Comment by adrifcastr** [comment]
gotcha

**Comment by wangsnowyin11** [comment]
Hey in our end we couldn't repro the login issue on neither web nor android. Could you retry on wifi/4G etc, and if any other people is experiencing the same? 

As for audio playback, you have to make post to the speech, so that your inbox can receive it then you can retrieve it back. Check docs https://wit.ai/docs/http/20170307#post__speech_link
If you did that, and still can't playback, please give us the info how the post call you made

**Comment by wangsnowyin11** [comment]
Give you an example how to do this:
make cURL request with
```
curl -XPOST 'https://api.wit.ai/speech?v=20200204' \
   -i -L \
   -H "Authorization: Bearer $TOKEN" \
   -H "Content-Type: audio/mpeg3" \
   --data-binary "@$FILENAME.mp3"
```

You should be able to get back result like this if successful
```
HTTP/1.1 200 OK
Content-Type: application/json
Date: Tue, 04 Feb 2020 21:55:43 GMT
Date: Tue, 04 Feb 2020 21:55:43 GMT
Connection: keep-alive
Content-Length: 182

{
  "_text": "hello",
  "entities": {
    "intent": [
      {
        "confidence": 0.96054483227547,
        "value": "wakeword"
      }
    ]
  },
  "msg_id": "1Pl4jiVTXV9pUYzhG"
}
```

Then you can see the speech you posted in your inbox, and you can play it back

I backed up your app and tried with it, things are working fine

**Comment by adrifcastr** [comment]
This is what I am doing
https://github.com/adrifcastr/Gideon/blob/master/Util.js#L448-#L499
The issue is not on my end, your service seems to have critical issues with
playing back raw PCM streams.

**Comment by wangsnowyin11** [comment]
For now Wit.ai is only able to process mono so you must make sure to send mono and not stereo to the API. Can you check what you post is mono or stereo?

**Comment by adrifcastr** [comment]
as you can clearly see in my code the buffer is converted to a 1 channel
stream. so once again, the issue does not lie with me

**Comment by adrifcastr** [comment]
otherwise the STT would fail, which it doesn't I get the results I want, I
just can't train the app via this game thing or listen to the logs

**Comment by adrifcastr** [comment]
the TTS works just fine, I just can't playback anything via the web interface and thus the logs and that game thingy are useless, otherwise your service does exactly what it says it does.

**Comment by gondiss** [comment]
Hi, we are actively working on finding a solution for this issue. Meantime, can you use wav audio as input instead of raw pcm? you could use open source sox tool for converting raw to wav format.

**Comment by adrifcastr** [comment]
Well I'm receiving the audio via Discord, and the library I use only
supports RAW PCM, converting it on the fly would induce an unnecessary
delay in executing the response, I can wait until the issue is resolved
before I keep training the app.

**Comment by gondiss** [comment]
Can you check now whether playback works for your audio samples? If it works for you, please close the issue.

**Comment by adrifcastr** [comment]
> Can you check now whether playback works for your audio samples? If it works for you, please close the issue.

I have identified the issue, the blayback works on the files that have been sent since I added 1 channel (mono) conversion, so the playback in the logs works as intended, I would ask you to please clear the training game of all current samples, as 90% of them are from before doing the one-channel conversion and due to that they won't play
