### ISSUE TITLE
Cannot login with Github account

### ISSUE THREAD

**Issue by tolui** [wit-ai/wit#1643]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
cannot login with my github to old wit account (old wit account not logged in since about 2 or 3 years ago)
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
clicked on login with Github button and it says 
"Uh oh... You cannot access this page
You'll need to sign in to view this page! Sorry about that!"
![image](https://user-images.githubusercontent.com/10773668/73944116-fec60380-492c-11ea-903d-0b53eaf53571.png)
**What is the expected behavior?**
successful login
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by jtliao** [comment]
Hey @tolui, sorry for the inconvenience-- to help debug, can you let me know if you see any Network errors in the Inspect tool of your browser?

The faster alternative would be to sign up with a new account through Facebook :)

**Comment by tolui** [comment]
@jtliao  Hello. here is the screenshot
![image](https://user-images.githubusercontent.com/10773668/74086912-79745780-4ac2-11ea-8e4d-4db9ef1e6273.png)
I need my old account. please help me

**Comment by jtliao** [comment]
@tolui can you give it a try again?

**Comment by tolui** [comment]
@jtliao yes now I can login, Thank you very much
