### ISSUE TITLE
Background noise misrecognized as "hallo"

### ISSUE THREAD

**Issue by stefan-reich** [wit-ai/wit#1644]
Hi,

when I send [this file](https://botcompany.de/files/1400341/20200207-230851.live.mp3) to the German recognizer (which works very well otherwise)... it hears "hallo". It does this a lot lately which is a really funny effect... but definitely not desirable.

(It's always with files consisting of only noise, and it's always recognized as the single word "hallo". So strange!)

**Comment by kingseaeast** [comment]
Thanks for reporting!  We will take a look.

Do you know if this is a new issue?
