### ISSUE TITLE
STACK IN SCHEDULED

### ISSUE THREAD

**Issue by dv-kchahid** [wit-ai/wit#1645]
Hi please my app stuck in scheduled status how can i solve it ?

**Comment by fluffyx** [comment]
My app is having the same issue! Thank you for reporting =)

**Comment by fluffyx** [comment]
More info:

My will_train_at time keeps getting pushed back.
"will_train_at":"2020-02-09T12:03:44-0800",
"last_trained_at":"2020-02-08T08:27:57-0800"

Now it's
"will_train_at":"2020-02-09T12:03:44-0800",
"last_trained_at":"2020-02-09T12:06:05-0800"

**Comment by jtliao** [comment]
@fluffyx your app should be trained now. 

@dv-kchahid, please provide your app ID

**Comment by dv-kchahid** [comment]
@jtliao Thank you but now is solved

**Comment by dv-kchahid** [comment]
@jtliao can i ask u ?
