### ISSUE TITLE
issue with user says textbox bug

### ISSUE THREAD

**Issue by DaxJain** [wit-ai/wit#1647]
There is an issue with the user says textbox, whenever we start typing only some of the text is typed and then the cursor goes back to the starting point without completing the whole line and then backspace is also not applied.

Please solve this problem as soon as possible.

App link - (https://wit.ai/DaxJain)

**Comment by kingseaeast** [comment]
Thanks for reporting! I haven't been able to repro this issue on my end. Can you provide more details:
- Your browser version
- Your app name/id (what you have is the link to your account
- Does it repro consistently for every string you type in the text box?
- Does it repro with anyone else that you know?

**Comment by DaxJain** [comment]
- Your browser version - Firefox 72.0.2 (64-bit)
   - Your app name/id (what you have is the link to your account -
   https://wit.ai/DaxJain/Shop/entities
   - Does it repro consistently for every string you type in the text box?
   - No, sometimes only
   - Does it repro with anyone else that you know? - Yes with my colleague

**Comment by patapizza** [comment]
Hi @DaxJain,

Can you provide a screencast to show the behavior?

Thanks!
