### ISSUE TITLE
Uzbek language not supported 

### ISSUE THREAD

**Issue by Valixon** [wit-ai/wit#1648]
Speech recognition is not supported for language: uz.
I have the same problem. How can I use it if possible? My app ID is: 2584527051675979

**Comment by jtliao** [comment]
hi @Valixon, unfortunately we no longer have the capability to support speech recognition for Uzbek. We hope to bring it back at some point later in the year, in the meantime please refer to https://wit.ai/faq for the official speech languages we support.
