### ISSUE TITLE
Wit refuses to accept new samples

### ISSUE THREAD

**Issue by fluffyx** [wit-ai/wit#1649]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
BUG

**What is the current behavior?**
POSTing to /samples succeeds
    {"sent":true,"n":1}
However, the sample doesn't show up in the Wit dashboard or in GET /samples
Issue persists with all new samples we try to submit.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
3743960025629293

**Comment by fluffyx** [comment]
I'm pretty sure I should be able to add new samples using the Understanding tab in the web interface, but that isn't working either!

**Comment by fluffyx** [comment]
This issue has resolved but now our query results are absolutely useless. Is there a way to reset and rebuild the AI database?

**Comment by FengyangZhang** [comment]
Happy to hear it's resolved. To your question, it depends on the sample size, if it's just a few it should be in seconds, if it's in hundreds in might take a few minutes.
