### ISSUE TITLE
ios Swift QuickStart

### ISSUE THREAD

**Issue by jimhamilton** [wit-ai/wit#165]
I'm new to wit.ai and am learning iOS Swift.

Are you able to provide me with a Swift version of the iOS QuickStart in Objective C?

Many thanks in advance.

Jim

**Comment by pleonard** [comment]
If it's helpful I'd be happy to post the code that I have for the HTTP GET in swift. not sure the best place to post it.

**Comment by jimhamilton** [comment]
Could you enter it under this thread as a start so others show search for swift help on the forum will be able to see it? A comment in the main documentation could then link to here.

Thanks for your trouble.

**Comment by adapala** [comment]
I'm also new to iOS and learning SWIFT, would appreciate SWIFT quick start version for wit.ai.  Thanks

**Comment by pleonard** [comment]
really sorry, I thought I'd be able to finish this but too much going on at
work. if i can get a few spare minutes I'll try to post the code.

On Tue, Apr 21, 2015 at 8:41 PM, adapala <notifications@github.com> wrote:

> I'm also new to iOS and learning SWIFT, would appreciate SWIFT quick start
> version for wit.ai. Thanks
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/wit-ai/wit/issues/165#issuecomment-95004823>.
>



-- 

Patrick Leonard
CTO
iTriage / Aetna Consumer Digital & Innovation
@patrickjleonard <https://twitter.com/#!/patrickjleonard>

Download iTriage for free at http://www.itriagehealth.com/get-mobile
We're Hiring! Join The iTriage Team <http://about.itriagehealth.com/jobs/>"
