### ISSUE TITLE
TRAIN YOUR APP SHUTDOWN

### ISSUE THREAD

**Issue by dv-kchahid** [wit-ai/wit#1650]
I'm trying to train my bot with cURL
return: {"sent":true,"n":1}
but nothing change 
and now bloqued in SCHEDULED mode
ID:2242841785819286

**Comment by patapizza** [comment]
Hi @dv-kchahid,

The training isn't immediate. If the status is `SCHEDULED`, your app will be trained at the time shown on hovering (see screenshot below). The scheduling algorithm is necessary to support the scale of our community.

<img width="329" alt="Screen Shot 2020-02-12 at 9 58 27 AM" src="https://user-images.githubusercontent.com/1015208/74362819-3940fd80-4d7e-11ea-8f6e-033124b8a8c4.png">
