### ISSUE TITLE
Logs tab display nothing.

### ISSUE THREAD

**Issue by serdalbayram** [wit-ai/wit#1651]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
When you click the "Logs" tab, it is empy. One week ago, all logs were displayed here.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Login wit.ai, select App, and then click "Logs" icon

**What is the expected behavior?**
Logs were displayed here 
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
5ab2407f-561a-45df-ab6c-139009d7b2b6 
![Logs](https://user-images.githubusercontent.com/25345380/74658801-1494bd80-51a4-11ea-8665-fa0c8c986e0f.png)

**Comment by patapizza** [comment]
Thanks for reporting, we're looking into it.

**Comment by patapizza** [comment]
@serdalbayram This should be fixed, let me know if you still experience issues.

**Comment by serdalbayram** [comment]
Issue is not resolved :( . Facing the same empty screen

**Comment by serdalbayram** [comment]
> @serdalbayram This should be fixed, let me know if you still experience issues.

No it is not fixed :(

**Comment by patapizza** [comment]
Can you refresh? I do see the logs on your app.

**Comment by serdalbayram** [comment]
yes I refreshed it but still the same error occured.


![image](https://user-images.githubusercontent.com/25345380/74860661-11dbc900-535a-11ea-84ea-a0a2ed6714d4.png)

**Comment by patapizza** [comment]
When you go to Logs, is https://wit.ai/serdalbayram/maestroBotGeneral/logs/-1 the URL you get redirected to?

**Comment by serdalbayram** [comment]
> When you go to Logs, is https://wit.ai/serdalbayram/maestroBotGeneral/logs/-1 the URL you get redirected to?

Yes, it is the same link
