### ISSUE TITLE
LOGS tab showing 500 error

### ISSUE THREAD

**Issue by sabinchacko007** [wit-ai/wit#1654]
BUG

What is the current behaviour?
logs tab showing 500 error

![Screen Shot 2020-02-27 at 9 24 40 AM](https://user-images.githubusercontent.com/36190477/75410964-a1c5d800-5943-11ea-9353-fc884fd003b2.png)

App id 200131591049011 And 2788662337869759

**Comment by gondiss** [comment]
Hi, we can't reproduce this issue. Is this happening consistently with the specific apps?

**Comment by sabinchacko007** [comment]
all my apps having the same issue.

**Comment by patapizza** [comment]
Seems like https://github.com/wit-ai/wit/issues/1651 isn't fully resolved. Sorry about that, we're looking into it.

**Comment by patapizza** [comment]
@serdalbayram @sabinchacko007 Can one of you confirm it's working now?

**Comment by sabinchacko007** [comment]
@patapizza still having the issue.

**Comment by patapizza** [comment]
What about now, after hard page refresh?

**Comment by sabinchacko007** [comment]
@patapizza ya the issue is fixed now . Thank you

**Comment by serdalbayram** [comment]
> @serdalbayram @sabinchacko007 Can one of you confirm it's working now?

it is also fixed for me thank you :)
