### ISSUE TITLE
"Train my voice" under Inbox/Voice tab not returning improved results after correcting transcriptions

### ISSUE THREAD

**Issue by rishabh-patch** [wit-ai/wit#1655]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question
**What is the current behavior?**
Same transcriptions are printed even after corrections in "Train my voice" under Inbox/Voice tab
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Improved transcriptions
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
3004841362882553

**Comment by gondiss** [comment]
Hi, thanks for reporting the issue. we try to tune and balance the speech recognition for all types of apps. so, sometimes, your app's speech may not transcribe exactly to what was expected. That being said, we are constantly improving our backend to enhance the performance of speech recognition. you can expect better performance in near future.

**Comment by rishabh-patch** [comment]
Thanks @gondiss

**Comment by rishabh-patch** [comment]
Could you please help with the following issues as well?
How does wit handle noise, frame rate and volume of an audio while processing it for transcription?
Also, is there a provision for special use case transcription? For instance, a call recorded on a mono channel having multiple speakers (and hence noise from sides of all speakers).

**Comment by Barbog** [comment]
Closing this issue due to there being no movement in some time. Please re-open or file a new issue should the issue persist today.
