### ISSUE TITLE
axios don't work with speech

### ISSUE THREAD

**Issue by el9in** [wit-ai/wit#1657]
const response = await axios({
		  method: 'post',
		  url: 'https://api.wit.ai/speech?v=20170307',
		  data: audio,
		  headers: {
			Authorization: 'Bearer (TOKEN HERE)',
			'Content-Type': 'audio/ogg'
		  }
		})

appid: 44D5TIXCKRXHAQOMLUZGQVSSHUATSMRL
audio: url ogg

**Comment by gondiss** [comment]
Hi, can you be more specific about what is not working with speech API? Please use the template to raise any issues. You can look at https://github.com/wit-ai/wit/issues/1590 as reference. Here is speech API documentation for your reference - https://wit.ai/docs/http/20170307#post__speech_link.

**Comment by el9in** [comment]
data: audio,
audio = 'http://translate.google.com/translate_tts?ie=UTF-8&tl=ru-RU&client=tw-ob&q=Test'
I don’t really understand what should be in the body

**Comment by gondiss** [comment]
The body should contain the binary audio data. Following is the example of using speech API with curl.

Definition
  POST https://api.wit.ai/speech
Example request
  $ curl -XPOST 'https://api.wit.ai/speech?v=20170307' \
   -i -L \
   -H "Authorization: Bearer $TOKEN" \
   -H "Content-Type: audio/wav" \
   --data-binary "@sample.wav"
The response format is the same as in GET /message

**Comment by el9in** [comment]
How I can use 'stream' audio?

**Comment by gondiss** [comment]
Hi, currently we don't support continuous streaming of audio. You could set Transfer-encoding header to chunked to send multipart payload through speech API. We do have a maximum audio limit of 10 secs per API request. You can somehow buffer the streaming audio you are receiving  and call speech API on segment by segment basis. https://wit.ai/docs/http/20170307#streaming-audio.
