### ISSUE TITLE
Wrong intent

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#1659]
Hi team,

We are using wit.ai for our chatbot.
Our appId is 2327071384087629

Our issue is that "what's the special offer today" is identifying greeting intent where as "what's the special offer" identifies no intent.
Also "what's the temperature of my room" returns "get_temperature" but "what's the temperature of my" doesn't.
Actually we don't expect any intent for "what's the special offer today".
Can you please help us in identifying if there is any issue in the process that we are training inputs.
Also please let us know why it behave in different ways even though it don't have any words trained in that intent.

Thanks,
Anjaly

**Comment by amtdevops** [comment]
Hi,
Any updates pls.

**Comment by jtliao** [comment]
1. Both "what's the special offer today" and "what's the special offer" don't return an intent when I test this, what is the issue?
2. For the temperature issue, I'd recommend validating for samples. It seems like many of the samples involve "room", so it's possible that examples without the word "room" won't have as high of a confidence.

**Comment by anjaly** [comment]
> 1. Both "what's the special offer today" and "what's the special offer" don't return an intent when I test this, what is the issue?
> 2. For the temperature issue, I'd recommend validating for samples. It seems like many of the samples involve "room", so it's possible that examples without the word "room" won't have as high of a confidence.



> 1. Both "what's the special offer today" and "what's the special offer" don't return an intent when I test this, what is the issue?

1. We retrained it yesterday.
