### ISSUE TITLE
AI not training when adding/updating intents and entities

### ISSUE THREAD

**Issue by benji2512** [wit-ai/wit#1660]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
App is not training at all for new intents and entities added also not retraining for editing existing intents and entities

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
create a new intent with a single message_body entity, let the ai train then navigate to samples tab and click new sample just trained then click "Preview API Output" and observe the incorrect output.
Same also applies to Understanding tab when testing newly added sample.

**What is the expected behavior?**
API Output is what was specified when adding new intent and entity

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
3306614322746421

_P.S. This bug has only appeared in the last couple of weeks._

**Comment by gondiss** [comment]
Hi, training for 3306614322746421 has completed. Let us know if you are still facing the issues.

**Comment by benji2512** [comment]
Hi, I have tested things on my end and find that while the training is now completing, the changes I make do not take effect at all. If the ai comes back with an incorrect understanding of the sentence, i then fix the issue, train the ai and when I test the newly trained ai still has an incorrect meaning! This used to work perfectly

**Comment by 91ns** [comment]
Same issue here we're not able to train through wit APIs.

**Comment by benji2512** [comment]
@gondiss is there any update on a resolution for this?

**Comment by gondiss** [comment]
Hey folks, we are actively working on fixing these issues. Could you provide the sample of sentences for which understanding is incorrect?
