### ISSUE TITLE
AI not training when sending samples from API

### ISSUE THREAD

**Issue by mintunitish** [wit-ai/wit#1661]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
App is not training for samples sent through API.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Send training samples through the API, even after a day yet the samples are not reflecting.

**What is the expected behavior?**
AI should train and reflect the new intents.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
492510541424995

**Comment by schecter22107** [comment]
We are having the same issue right now also. We are not being able to train using the api.

**Comment by patapizza** [comment]
Hi @mintunitish, please provide examples of samples that don't work, with expected results. "I want to know about air" seems working for your app. Thanks!

@schecter22107 Please provide your own app ID as well as above. Thanks!

**Comment by mintunitish** [comment]
@patapizza I have just submitted 199 records again still no luck. The app is mine. I transferred ownership to other account to see if that will work, still no luck!

Samples are like:
- why choose payworld
- services list
- how can i become retailer
- i have a business

**Comment by schecter22107** [comment]
@patapizza  612363492944732 thank you

**Comment by Xueying-Wang** [comment]
@mintunitish @schecter22107 Thank you for reporting the issue! Can you try sending the training samples again and see if it works?

**Comment by schecter22107** [comment]
It still does not work

**Comment by Xueying-Wang** [comment]
Great :P
