### ISSUE TITLE
cannot export data .zip from dashboard

### ISSUE THREAD

**Issue by altsalih** [wit-ai/wit#1664]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
Something went wrong while exporting your app ☹️. Please try again, or contact us.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Settings>Export your data > Download .zip with your data
**What is the expected behavior?**
Download A Zip
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
Appid : 5af9541a-7f6c-4fa4-b09a-d2e28413a66e

**Comment by altsalih** [comment]
Hello, 

Any update?

**Comment by Xueying-Wang** [comment]
Sorry for the delay. We have been fixing the export issue for your app. Can you try export again and let us know if it successfully generates the zip file?

**Comment by altsalih** [comment]
Thank you
