### ISSUE TITLE
App is stucking in ongoing status

### ISSUE THREAD

**Issue by beshoo** [wit-ai/wit#1665]
Update on https://github.com/wit-ai/wit/issues/1286
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
each time I add a training data I stuck with "Your app is scheduled to train at XX/XX/XXX"
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I understand that you are trying to serve all community and load-balance but that's is delay our works.  

**What is the expected behavior?**
It should get trained and give expected results. well I can wait like 3 min and get DON messages 
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
216884519426502, i don't want you to speed this up for me just one time, I am asking for a general fix for this problem, come on you are Facebook!

**Comment by jtliao** [comment]
Our training stability has been far better as of late, and we are actively measuring it. Closing
