### ISSUE TITLE
Tag Items Description (Hebrew+English)

### ISSUE THREAD

**Issue by tzufstokelman** [wit-ai/wit#1666]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question - What is the best way to tag numbers who describe the item.
Regrading E-Commerce products description, For instance, 
"ACER Aspire C27-865 27" All-in-One PC Intel® Core™ i5, 1 TB HDD & 256 GB SSD" .This is the product description and I want to tag everything to entities.

I want to Tag and understand a number that describes an attribute of a product along with its unit. 
So if I have “smartphone Galaxy S10 256GB 3 grams”
I want to understand the following 
Product - Smartphone
Product type - galaxy
Model - S10
This is where my problem begins:
256 storage with unit GB
3 weight with unit grams

And I have lots if possible attributes and units so I cant open an Entity for each product attribute

**What is the current behavior?**

I am currently thinking about three different ways to solve my problem.

1) using the built-in wit/number with given roles to each number (for instance- "Apple iPhone 11 32 GB", so the "11" will be wit/number Role "model", while the "32" will be wit/number Role "storage").

2) Tag entities "inside" other entities. For instance query  ("SAMSUNG UE50RU7470UXXU 50" Smart 4K Ultra HD") so I can tag everything (let's call it "Product") and then tag inside the "Product" fractions of the sentence (it can be number like "50", it can be numbers and Chars like "UE50RU7470UXXU ") but it caused me some problems when I tried that a few months ago.

3) Tag all the numbers as "Nums" (my entity, not the built-in), while tagging all the the "GB" and stuff like this (distance, volume, weight etc) as "Units" (again, my entity). 
For instance "BEKO WTB720E1W 7 kg 1200 Spin" ("1200" and "7" are "Nums", "kg" and "spin" are "Units".

My app works with English and *Hebrew*(!) that's why I need a "correct" generic answer and not only for one certain language. 
Also, I cannot use most of the built-in entities because there is no support in the Hebrew language.
Do you guys think any of the 3 solutions that I described is good enough? If you have any 
better solution please tell me.

Best Regards,
Tzuf.

**Comment by patapizza** [comment]
Hi Tzuf,

Great question!

This is the type of inputs that would work better with rule-based systems (e.g. regexes). To that end, you might want to try to build a custom dimension in [Duckling](https://github.com/facebook/duckling). You'd need to run Duckling as a service on your end for custom dimensions at this time. This would be the best if that's all you need. If you need NLU for other types of inputs, you could complement the Wit.ai response with your own set of regexes / local Duckling.

Now, if we try to tackle the problem on wit.ai only, you could indeed use composite entities: one overarching entity for the overall product, and subentities for each individual piece. `wit/quantity` should work well for e.g. `3 grams`. This is powered by Duckling, and you could provide support for the Hebrew version by submitting a pull request.

Hope this helps!

**Comment by tzufstokelman** [comment]
Hi Julien!
Thanks for the quick and detailed response.
I will probably use Duckling, but before that, If I am using Wit only, Is the solution with composite entities is the best solution? or my first (option 1) solution? or should I go with my third solution (option 3)?
Best Regards,
Tzuf.

**Comment by tzufstokelman** [comment]
#@patapizza
Hi Julien!
Thanks for the quick and detailed response.
I will not use Duckling, for now, So if I am using only Wit, Is the solution with composite entities is the best solution, Using composite entities only for the number's units(only for the quantitative attribute of the product, like tagging the whole 8 kg, and then inside 8 and kg) ? or my first (option 1) solution with the Roles? or should I go with my third solution (option 3),
The regular tagging?
And should I go with the built-in " wit/number" entity or with my "Nums" entity ?
Best Regards,
Tzuf.

**Comment by patapizza** [comment]
Hey,

I'd tag `smartphone Galaxy S10 256GB 3 grams` as `item`, `smartphone` as `product`, `galaxy` as `product_type`, `S10` as `model`, `256GB` as storage (this could be a good candidate for a new Duckling dimension), `3 grams` as `wit/quantity` (the built-in entity leveraging Duckling's `Quantity`).
Tagging your item as a whole allows you to get the relevant part in e.g. "hey I have a smartphone galaxy S10", to better teach the composite entities, and to run custom regexes to complete your entities (e.g. split up `256GB` into value and unit).

Hope this helps.

**Comment by idanadut** [comment]
Hi Everyone,
@patapizza - what if I have tens or potentially hundreds of different product attributes like in real-life e-commerce (i.e. storage, weight, size, length, depth, RPM, RAM, width, horsepower, Ghz, Resolution, MP, watt - and many more **quantitative product attributes**..)? How would you go about that to get the best results on wit for now?

I thought instead of having hundreds of entities or hundreds of regex rules/duckling entities (for each type of quantitative attributes like storage) I would have one entity called "AttributeQuantity" to tag the numbers (e.g _256_) and one entity called "Unit" to tag the unit type (e.g tag _"GB"/"MB"_ as  "Storage" keyword in "Unit" Entity , or tag _"Kilos"/"KG"/"grams"_ as "Weight" keyword in "Unit" Entity). What do you think? 
_*There's also the possibility to add on top of that a "father" composite entity over both "AttributeQuantity" & "Unit" so I could match them together (hope you can address this suggestion as well)_

Thanks!
