### ISSUE TITLE
Duplicate entity values created

### ISSUE THREAD

**Issue by sabinchacko007** [wit-ai/wit#1667]
BUG

Duplicate **entity** **values** are created (having same entity value.)

appid : 2788662337869759

![Screen Shot 2020-03-13 at 10 17 30 AM](https://user-images.githubusercontent.com/36190477/76590730-1be58780-6514-11ea-86b1-608be591668d.png)

**Comment by jtliao** [comment]
Deleted it, we'll work on enforcing this better.
