### ISSUE TITLE
Cannot use API /smaples offset more than 3 and limit more than 10

### ISSUE THREAD

**Issue by convolab** [wit-ai/wit#1668]
**Sorry For My English**
I use API "https://api.wit.ai/samples" to get expressions in entity and add parameter offset value more than 3 or limit limit more than 10, then api response error to me.
![image](https://user-images.githubusercontent.com/30592933/76615018-bfa25800-6553-11ea-9b85-01eb9e011c72.png)

check for this case, please.

APP ID : 891285304663061

**Comment by jtliao** [comment]
Should be fixed now, looks like there was something wrong with your app, not the offset/limit.
