### ISSUE TITLE
emojis are returning a 500 error

### ISSUE THREAD

**Issue by asierraserna** [wit-ai/wit#1669]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

bug

**What is the current behavior?**

it breaks when the user sends an emoji

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

send an emoji to a bot.

more info here

https://developers.facebook.com/support/bugs/193903275368689/

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

5aa9a49c-6ab7-47fe-b6b8-2650ec54b46a

**Comment by asierraserna** [comment]
https://wit.ai/alejandrosierra/Partidito.com/logs/-1

**Comment by jtliao** [comment]
what happens when you send a request to `GET message` directly with an emoji? i can't reproduce this

**Comment by asierraserna** [comment]
I think I just a response from the system from a test @jtliao
![image](https://user-images.githubusercontent.com/19590141/76681565-a0a7d280-65f4-11ea-820b-f4099954713e.png).

in Messenger is this:
![Capture1](https://user-images.githubusercontent.com/19590141/76681603-fa100180-65f4-11ea-8ed8-35d416a8313b.JPG)

Not sure how to test sending a request to GET message directly with emoji. shouldn't be always in the payload?

Thank you for checking this!

**Comment by asierraserna** [comment]
From what I see in the log of the project, it seems lke wit.ai enters into a loop with the emojis:

![image](https://user-images.githubusercontent.com/19590141/76681690-eb761a00-65f5-11ea-8915-0026882516a9.png)

**Comment by jtliao** [comment]
I mean if you send a request to Wit.ai directly through the `GET /message` API (documented here https://wit.ai/docs/http/20170307#get__message_link), rather than through Messenger. I'm trying to figure out if the issue is with Messenger + Wit, or Wit alone.
