### ISSUE TITLE
Merge a forked  or export/import

### ISSUE THREAD

**Issue by aegeous** [wit-ai/wit#167]
Hi, nice to see things moving along. I am really eager to see the 'community' sharing features implemented. For two reasons, one to avoid reinventing the wheel and two to have my work be propel others further. I am reluctant to begin going to task on creating intents until they can be shared for both reasons, economy of time invested. One easy way to implement community sharing could be to utilize the exiting GitHub tools to merge forks of a project with someone else's (is this possible now?). Alternatively, an export function with import (perhaps in xml to edit out selections) could be another quick implementation. Great to see new features are to arrive "in the near future" in the Docs page, maybe some of them easy than others, and be able to share intents would in my opinion have a multiplier effect on the speed of their development! Thanks!

**Comment by aegeous** [comment]
Hi, glad I posted this because I now following development with notifications. I thought I should maybe summarize my request a little better. 

A simple import/export feature or a merge feature for the wit projects would go a long way toward being able to share with the community.

For example, I have an Android device and if I listed every intent available on my specific OS version, probably %80 of them could carry over to newer versions like Lollipop. Likewise, if someone listed all of their intents on Lollipop, I could possibly import them to a project for my version.

**Comment by leonardoobaptistaa** [comment]
+1 for the import / export tool
mainly if supports import / export per intent

**Comment by l5t** [comment]
Sorry for the lack of reply on this topic... With the new release of Bot Engine Beta, we removed the community feature. We will bring it back when we exit the Beta and will work on making it easier to import/export part of your app.

**Comment by fczuardi** [comment]
LUIS has an export button that creates a very useful JSON file, including entities positions on a statement. It would be nice to be able to export that information when this feature gets implemented.

**Comment by oplatek** [comment]
Any update? I still cannot find the feature, but it is mentioned here: https://wit.ai/blog/2016/06/28/bot-engine-v1

**Comment by l5t** [comment]
Sorry for the glitch, this feature was gated to certain users but we will open this morning. Thanks for your patience

**Comment by sanster23** [comment]
The feature does not work properly.
Importing a zip -> creating an instance taking hours and not creating in the end.

**Comment by oplatek** [comment]
@sanster23 may I ask you:
a) How you managed to export the conversations?
b) How you import them?

I still cannot see the feature

**Comment by sanster23** [comment]
The feature was shown randomly after like few refreshes on the UI.
A .zip file(containing JSON format files of the actions and the entities etc.) can be exported or imported.

Export is good but import feature didn't work.

**Comment by ar7hur** [comment]
@oplatek it's on your app settings page /settings
![image](https://cloud.githubusercontent.com/assets/993739/16487163/5995332a-3ec9-11e6-9b34-941e65708ed5.png)
If you don't see it, try to hard-refresh (Cmd-Shift-R)
If you still don't see it: when did you create this app?

**Comment by oplatek** [comment]
@ar7hur thanks a lot! Successfully downloaded the app settings.

**Comment by oplatek** [comment]
@sanster23  Actually, I was able to create a "new" app from the backed-up zip file.

**Comment by sanster23** [comment]
@oplatek Cool I'll try again then. 
Thanks for the update.

**Comment by mikob** [comment]
I'm not able to import. When I try to create a new project from a backup file it get's stuck on "We are creating your instance. Please do not refresh" After a few minutes, the request times out with a 504. https://api.wit.ai/import?name=KlassBot1.1&desc=klassbot1.1&private=false&lang=en&login=mikob

**Comment by ar7hur** [comment]
Probably un bug on our side, we'll look into it cc @martinraison  @blandinw

**Comment by androidlab** [comment]
@ar7hur Hi, I created the app some time back. So, i dont see the export function in my app. Is there any way I can export the data to a new account? Or can I transfer the app to a new user completely?

**Comment by pasalino** [comment]
Hi, 
I tried to create a new app from an existent zip file. 
If i change anything in file and upload it, i receive a blank yellow alert message and not create that.
If i download a zip file and try to upload it in new application, everytimes the creation process remain in stuck on "We are creating your instance. Please do not refresh". 
if i look in other tab, the list of App, 1 of 4 time the new application is created correctly but the tab that contains  "We are creating your instance. Please do not refresh" reamain in stuck.

**Comment by arpitgoyalhtmedia** [comment]
I am also having problems importing the app. I browsed the zip file while creating the new app and as pointed out by @pasalino I received a blank yellow dialog box (probably some error). I went into my apps and can see the new app with entities and their values imported but I found out that there was no expressions attached to them. There seems to be a bug please help me out with this one.

**Comment by blandinw** [comment]
Closing this as the conversation became too noisy. We have other issues open regarding the import functionality.

**Comment by auwsom** [comment]
@blandinw Could you link to the most relevant? Pls, thx

**Comment by blandinw** [comment]
https://github.com/wit-ai/wit/issues?q=is%3Aopen+is%3Aissue+label%3Aimport
