### ISSUE TITLE
GET /message doesn't include metadata

### ISSUE THREAD

**Issue by kenkunz** [wit-ai/wit#1670]
This is a bug report. GET requests to `/message` are not including `metadata` (it was included in the past – I believe it stopped working w/in the past week or so). This looks similar to closed issues #177, #553, #561.

app id: 2983709474984199

Example request:
`GET /message?v=20200313&q=i%20forgot%20my%20password`

response:
```
{
  "_text": "i forgot my password",
  "entities": {
    "intent": [
      {
        "confidence": 0.99960770082441,
        "value": "topic/BPME3"
      }
    ]
  },
  "msg_id": "1TwtY0zjvoIwuj3P1"
}
```

**Comment by jtliao** [comment]
Hey @kenkunz, thanks for raising, we're looking into the issue.

**Comment by FengyangZhang** [comment]
Hi @kenkunz, the issue should've been resolved, thanks for  the patience.

**Comment by kenkunz** [comment]
Verified – it is working correctly now.

I am somewhat reticent to rely on this feature given that it has been a recurring issue. I could rework my code and overload the intent value, but that is not ideal either. How likely is this issue to crop up in the future?

Thank you,
Ken

**Comment by FengyangZhang** [comment]
@kenkunz Sorry about the instability you experienced about this feature. Because this is caused by a bug introduced in our code Wednesday this week, I don't think the exact same thing has happened before, and it's highly unlikely to happen again.

**Comment by kenkunz** [comment]
@FengyangZhang thank you for clarifying, and for your quick attention to this!

Regards and be safe!
-Ken

**Comment by eduardovoll** [comment]
It seems that metadata did not appear in the response again. Below the comparison of the old deprecated version and the new version.

![image](https://user-images.githubusercontent.com/27147492/88831668-0cef3100-d1a6-11ea-8b78-e1e9b64491fe.png)
![image](https://user-images.githubusercontent.com/27147492/88831694-15e00280-d1a6-11ea-9148-82d593bfdd8d.png)
