### ISSUE TITLE
Add expressions amount 1563 sentences in 1 values but API /samples show result amount expression more than 1563 sentences

### ISSUE THREAD

**Issue by thanaphat-convolab** [wit-ai/wit#1671]
*Sorry For My English*
I added expressions amount 1563 sentences in 1 values but I try to get all expressions by api /samples with this URL "https://api.wit.ai/samples?&limit=2000&offset=0" and response show result of sentences more than 1563 sentences

Previously, I never add sentences. I add first time and I add by api /entities with this URL "https://api.wit.ai/entities/intent/values?v=20170307" with BODY 1 values and some sentences don't have entity name and value name in sentence 
Ex.
![image](https://user-images.githubusercontent.com/48672150/76747457-bf9c9500-67ab-11ea-9095-2c4f42c35ab3.png)

App ID : 891285304663061

**Comment by jtliao** [comment]
For the examples in the screenshot that don't have entities, can you send the payload you used to upload the samples, so we can see the expected value? Also, can you send the raw text so I can copy/paste the text? I'm not sure how to write that text otherwise :)

**Comment by thanaphat-convolab** [comment]
[example_expressions.zip](https://github.com/wit-ai/wit/files/4341809/example_expressions.zip)

This is the payload I used to upload the samples but this data is confidential, so I set password of this file.
Can you give me your email ? I will send password to unlock this file.

**Comment by jtliao** [comment]
we'll look into this. in the meantime, can you try adding the samples through the `POST /samples` API instead? you should be able to accomplish what you're trying to do there

**Comment by thanaphat-convolab** [comment]
@jtliao I used to try add the samples through api POST /samples but I founded duplicate trait values problem (same this issue https://github.com/wit-ai/wit/issues/1566) so I have to add the samples through api POST /entities/intent/values?v=20170307

**Comment by patapizza** [comment]
We've made some improvements and deprecated `POST /samples` in favor of [`POST /utterances`](https://wit.ai/docs/http/20200513#post__utterances_link). We've introduced [`POST /intents`](https://wit.ai/docs/http/20200513#post__intents_link) as well.
