### ISSUE TITLE
Samples api returning 500

### ISSUE THREAD

**Issue by swys** [wit-ai/wit#1673]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
samples api returns 500. I am using same example as stated in the docs : https://wit.ai/docs/http/20170307#get__samples_link

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I ran below get request and got below response : 
```
GET https://api.wit.ai/samples?limit=10 HTTP/1.1

HTTP/1.1 500 Internal Server Error
WWW-Authenticate: OAuth "Facebook Platform" "invalid_request" ""
Content-Type: application/json; charset=UTF-8
wit-api-version: v1.0
Strict-Transport-Security: max-age=31536000; preload; includeSubDomains
Pragma: no-cache
x-fb-rev: 1001853738
Access-Control-Allow-Origin: *
Cache-Control: no-store
x-fb-trace-id: AMhZFvLH1lu
x-fb-request-id: AlCq4dPZUHU2orF5AsdMHPI
Expires: Sat, 01 Jan 2000 00:00:00 GMT
X-FB-Debug: 2a9eooqzXnu6PiTgaG9vRBsmcYgh7CfHOXD2QOpWtW4GLzqi7mhLOC3LKaiJ7M9qD/qZgSHS2IMztTHKi+cLkA==
Date: Wed, 18 Mar 2020 02:00:03 GMT
Connection: close
Content-Length: 70

{
  "error": "Something went wrong. We've been notified",
  "code": "unknown"
}
```

**What is the expected behavior?**
return 200 along with array of samples

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
3030437770345565

**Comment by swys** [comment]
just realized I put the wrong app id, I've updated the original post to reflect the correct app id now. It appears to be specific to this app because the other app I posted (incorrectly) is getting a 200 response to the same request.

**Comment by jiayexie** [comment]
Hi @swys, it looks like your app was in a bad state where an entity was deleted after it was annotated, so the sample was storing a bad pointer. I've removed that bad pointer and tested the samples API for your app; it seems to be working. Please verify.

**Comment by swys** [comment]
@jiayexie thanks! I was able to verify that its working now.
