### ISSUE TITLE
Link users messages

### ISSUE THREAD

**Issue by andersonmgomes** [wit-ai/wit#1674]
Hello people

How can I link two messages from the same user on wit.ai? I ask why I need to continue an action from the previous answer. For example,

Bot msg01: "enter your name to register ..."

User msg01: "Paul"

Bot msg02: "Register Paul ...? (Answer yes or no)"

User msg02: "Yes"

Bot msg03: "Registration was successful. Thank you."

My question is whether there is any feature of wit.ai that facilitates the implementation logic that allows linking "User msg02" with "User msg01". What is the most appropriate way to do this?

Thank you very much in advance.

**Comment by jiayexie** [comment]
Hi @andersonmgomes, wit.ai does not support multi-turn dialogs; our goal is help you parse user input into structured entities, and you can build the dialog logic on top of it.

For example:
- Your app says: "enter your name to register ..."
- User says: "My name is Paul."
- (wit helps you extract "Paul" as user name)
- Your app generates another message based on wit result: "Register Paul?"
- User says: "yes"
- (wit helps you extract the trait "true")
- Your app does whatever it needs and says "Registration was successful. Thank you."

**Comment by patapizza** [comment]
Hi @andersonmgomes,

To add on what @jiayexie said, we believe it's doable to manage the conversation state in your code, closer to your business logic.
From the rationale behind [sunsetting Bot Engine](https://medium.com/wit-ai/launching-built-in-nlp-for-messenger-and-sunsetting-bot-engine-beta-46e9038869a5) in 2017:
> The recommended migration is to use /message and code on your side to manage the conversation and link to the answers that would be stored in your database.
