### ISSUE TITLE
App-status (training) is still ongoing after 3-4 days. 

### ISSUE THREAD

**Issue by serdalbayram** [wit-ai/wit#1677]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
App  is stucked in ongoing status.  It took 3-4 days. 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2348639601920387

**Comment by jiayexie** [comment]
Hi, we apologize for the inconvenience. I have manually retrained your app; it is now done.

**Comment by serdalbayram** [comment]
Thank you
