### ISSUE TITLE
Get the Most Significant words affecting polarity in wit/sentiment

### ISSUE THREAD

**Issue by Raamyy** [wit-ai/wit#1681]
Hello,

I am currently using wit to determine the **polarity** of text whether it is positive, negative or neutral. 

But also i need to know the **most significant** words that affected the bot to choose the polarity.
For example:
>  The weather is very **awesome**.
>  What a **bad** day.
>  I **don't like** the food.

I need to get the bold words. Is this possible?

Thanks

**Comment by nausicaasnow** [comment]
Thanks for your question, currently the built-in wit/sentiment only support returning value (positive, negative, neutral), but not the words affecting the model.
