### ISSUE TITLE
#@patapizza

### ISSUE THREAD

**Issue by tzufstokelman** [wit-ai/wit#1682]
#@patapizza 
Hi Julien!
Thanks for the quick and detailed response.
I will not use Duckling, for now, So if I am using **only** Wit, Is the solution with composite entities is the best solution, Using composite entities only for the number's units(only for the quantitative attribute of the product, like tagging the whole 8 kg, and then inside 8 and kg) ? or my first (option 1) solution with the Roles? or should I go with my third solution (option 3), 
The regular tagging?
And should I go with the built-in " wit/number" entity or with my "Nums" entity ?
Best Regards,
Tzuf.

_Originally posted by @tzufstokelman in https://github.com/wit-ai/wit/issues/1666#issuecomment-600476243_

**Comment by patapizza** [comment]
Hey, will reply in thread.
