### ISSUE TITLE
Trying to tag Below zero WIT/Amount of money

### ISSUE THREAD

**Issue by tzufstokelman** [wit-ai/wit#1683]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
*Bug*.

**What is the current behavior?**

When I am trying to tag ("עיסקה מתחת ל 0- אירו ") the GUI crashes. The meaning of this sentence and more similar sentences that I tried, Is somthing like " Less than 0 Euro/Dollar/GBP".

![image](https://user-images.githubusercontent.com/20947978/77650659-7a7b1e80-6f74-11ea-8f0e-27cd81908866.png)

And immediaetly:

![image](https://user-images.githubusercontent.com/20947978/77650242-d72a0980-6f73-11ea-8777-03b053ab5458.png)
  
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Not to crush.
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID-2646309675417270

**Comment by nausicaasnow** [comment]
Thanks for your feedback! It looks like a bug in our UX, we will look into it.

**Comment by jtliao** [comment]
should be fixed
