### ISSUE TITLE
Duplicate entity values are created (having same entity value.)  

### ISSUE THREAD

**Issue by mariaspm** [wit-ai/wit#1684]
appid : 2788662337869759
entity value: Have Tea and Coffee making Facilties in room?

**Comment by kitchWWW** [comment]
Hello! Thanks for reaching out to us with this issue. Could you provide more details on how you were able to encounter this issue? I'm having trouble reproducing this.

**Comment by mariaspm** [comment]
Hi @kitchWWW 
The issue was observed a couple of times but I was not able to reproduce it by a defined set of steps. This was pretty much a random behavior, will try to work on reproducing it somehow. Meanwhile, it would be helpful if you could provide me with a workaround for this.

Thanks in advance.

**Comment by mariaspm** [comment]
Hi @kitchWWW 
Still, having the issue, any updates?

**Comment by jtliao** [comment]
sorry for the delay here -- i can manually merge the values for now, while we work on a fix

**Comment by mariaspm** [comment]
Hi @jtliao 
Currently, we deleted the duplicate entities manually and added them again. 
Thanks.

**Comment by kingseaeast** [comment]
@mariaspm Thanks for getting back! will close the issue.
