### ISSUE TITLE
'Expressions' are not loading when filtered with entity name

### ISSUE THREAD

**Issue by mariaspm** [wit-ai/wit#1685]
APP ID: 2788662337869759

Thanks!

**Comment by kitchWWW** [comment]
Hello! Thanks for bringing this to our attention. We are working through this issue and will let you know when we come to a resolution on it.

**Comment by kitchWWW** [comment]
Hello mariaspm!

Wanted to let you know that we have identified the issue and published a fix for the problem. It should be operating as normal now. Please reach out or file a new bug if you need any other assistance! Thanks again for bringing this to our attention and helping us improve the quality of our ai offerings.
