### ISSUE TITLE
Speech to text doesn`t work correct

### ISSUE THREAD

**Issue by dirkar** [wit-ai/wit#1686]
HI
Yesterday when i sent .wav file to extract text from it i received  error code 500. Now i send same file and  receive code 200, but text is empty.  length of file is 14 sec, mono, language russian

Server response:
HTTP/1.1 200 OK
Content-Type: application/json
Date: Fri, 03 Apr 2020 13:08:03 GMT
Date: Fri, 03 Apr 2020 13:08:03 GMT
Connection: keep-alive
Content-Length: 35

{
  "_text": "",
  "entities": {}
}

[msg0005.zip](https://github.com/wit-ai/wit/files/4427355/msg0005.zip)

Can you check why this file cannot be recognized in text?

**Comment by jtliao** [comment]
this is what I see when I use that wav file:
```
{
  "_text": "лицевой счёт одиннадцать шестьдесят два семьдесят шесть показания счётчика шестнадцать двести восемьдесят",
  "entities": {},
  "msg_id": "17fGX5Eo7CLTKYes1"
}
```

Can you please provide your app ID?

**Comment by dirkar** [comment]
> this is what I see when I use that wav file:
> 
> ```
> {
>   "_text": "лицевой счёт одиннадцать шестьдесят два семьдесят шесть показания счётчика шестнадцать двести восемьдесят",
>   "entities": {},
>   "msg_id": "17fGX5Eo7CLTKYes1"
> }
> ```
> 
> Can you please provide your app ID?

App ID 2413142362085950
curl.exe -XPOST https://api.wit.ai/speech?v=20200303 -i -L 
-H "Authorization: Bearer <token>" 
-H "Content-Type: audio/wav" 
--data-binary "@msg0005.WAV"

**Comment by jtliao** [comment]
Am able to reproduce now, looking into the issue. Merging with #1687 to consolidate updates
