### ISSUE TITLE
I get the following when trying access my instance

### ISSUE THREAD

**Issue by kinjalpadalikar** [wit-ai/wit#169]
"Uh oh... You cannot access this page

You'll need to sign in to view this page! Sorry about that!"

I can log in fine using my github credentials, but I can't get past that page.  I've noticed that my application that attempts to connect to my instance doesn't work either, but if I use a different instance from another account, it works fine.

**Comment by l5t** [comment]
Hello,
It seems that you were pinging our API quite heavily. We had to block you to be respectful for our community. Please contact us at help@wit.ai and we will figure it out.
Laurent
