### ISSUE TITLE
Keywork not working

### ISSUE THREAD

**Issue by dvpthien** [wit-ai/wit#1690]
App id: 1088016214918281
After training unicode character, the system does not work with that keywords. Please check my photos

![image](https://user-images.githubusercontent.com/10919157/78534710-14648600-7815-11ea-8bdc-551903f47b06.png)
![image](https://user-images.githubusercontent.com/10919157/78534767-2c3c0a00-7815-11ea-9c54-72a9754f3d77.png)

**Comment by kitchWWW** [comment]
Hello! dvpthien!

Thank you for bringing this to our attention. We are investigating the issue and will post here if we have follow up questions or resolution.

**Comment by dvpthien** [comment]
Do you have any updates?

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
