### ISSUE TITLE
App is stuck in ongoing status and Samples tab is stuck in "Loading.."

### ISSUE THREAD

**Issue by zaher-h** [wit-ai/wit#1691]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
I just added one example or so to the training and then the training is stuck in on going status for a day now although the total dataset is too small (like less than 100 examples in total)..
Also, the Samples tab in the console is also stuck in "Loading.." and samples are not listed..

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Feel free to have a look at my app to see what's producing this bug as I'm not really sure how to reproduce it..

**What is the expected behavior?**
The expected behaviour is to get trained in like 12 seconds similar to the last training time. And for the Samples tab to return the training examples..

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID:
736317986905097
<img width="1039" alt="Screenshot 2020-04-11 at 18 15 04" src="https://user-images.githubusercontent.com/1856282/79050351-5c264b80-7c21-11ea-8073-06fd9f3e49d5.png">

Please note that this is app is now live and bing used so if you can please just minimise any down time if possible while you are checking the issue..
Many thanks

**Comment by jtliao** [comment]
Should be fixed now, apologies for the inconvenience
