### ISSUE TITLE
Wit.ai - Issue validating expression

### ISSUE THREAD

**Issue by Jay-ArBrouillard** [wit-ai/wit#1692]
Bug: I've been trying to train my Wit.ai bot but I keep getting "Wit had an issue validating this expression. Please try again and contact us if this does not resolve". 

I've tried refreshing the page, clearing my browser cache, logging in and out, restarting browser, and restarting computer but it doesn't change the outcome. Same thing happens on the inbox tab aswell.

![image](https://user-images.githubusercontent.com/44123272/79051914-7dbf0d00-7bf8-11ea-9fe0-3425db3b8757.png)

App id:830478657473066

**Comment by yestouscool** [comment]
I have the same issue with my app

**Comment by FengyangZhang** [comment]
The issue should have been addressed. Please let us know if you're still seeing issues.

**Comment by Jay-ArBrouillard** [comment]
Yes, looks like it's working again
