### ISSUE TITLE
Wit.ai Magic Mirror  Failed parsing entities/

### ISSUE THREAD

**Issue by Mahieedaboss** [wit-ai/wit#1694]
So I am following the steps on Hacker Shacks' repo and when trying to receive token by creating app,I  get this 
Failed parsing entities/
I had to edit app.json as there was a parsing error but what do I edit in entities/
entities is a folder so please be specific

If you need more info then will give

**Comment by aforaleka** [comment]
Hi @Mahieedaboss, what is the link to the repo and the instructions you're following?

**Comment by Mahieedaboss** [comment]
https://github.com/HackerShackOfficial/AI-Smart-Mirror

**Comment by aforaleka** [comment]
We'll need to get access to the app that exported the training data in order to investigate. Can you create a Github issue there and check with the owner whether he can provide us the app ID?

**Comment by Mahieedaboss** [comment]
New issue there

**Comment by Mahieedaboss** [comment]
https://github.com/HackerShackOfficial/AI-Smart-Mirror/issues/102

**Comment by Mahieedaboss** [comment]
any help?

**Comment by aforaleka** [comment]
Hi @Mahieedaboss, we'll need the owner of the app to tell us their app ID and let us re-export the app.
