### ISSUE TITLE
[500] Internal Server error on message and speech endpoints

### ISSUE THREAD

**Issue by BL19** [wit-ai/wit#1695]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
500 errors on requests. So possibly a bug.

**What is the current behavior?**
Cannot search for a message or use speech endpoint. 
[Chrome dev tools](https://i.imgur.com/9HnzfEb.png)
And my error from the speech endpoint: 
`{
  "code": "wit",
  "error": "Something went wrong. We've been notified."
}`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
I get a normal response. And working endpoints.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1455384507976871

**Comment by jtliao** [comment]
Hi @BL19, we're having some problems with our built-in entities. As a workaround, you can try removing the `wit/datetime` entity temporarily, we'll let you know when it's working again.

**Comment by sebastianarena** [comment]
Hello, I'm just chiming in to let you know the recent 2 apps that I created cannot be accessed through the /entities API. The old apps work just fine. None of them have a built-in entity enabled.

**Comment by jtliao** [comment]
should be fixed
