### ISSUE TITLE
WIT not recognizing child's voice

### ISSUE THREAD

**Issue by henrikingo** [wit-ai/wit#1696]
Hi

Thanks for WIT. We are having a lot of fun with it. AFAIK this is the only speech recognition service that also supports Finnish!

It seems the voice recognition doesn't really handle high frequency children's voices at all. When my daughter speaks, it always comes back as empty _text or "hi" or other single word. I wanted to file this issue in case this is something in your pre-processing that we cannot learn away.

App id is 1321115178088510. I have gone through the inbox and provided correct sentences.

Maybe a related feature request: Now I use the wit/contact entity, and it gives me a confidence how well it believes it extracted the entity from the text string. But it would also be nice to have a confidence score for the voice-to-text conversion. The way it is now, the _text is completely wrong, but the confidence for the entity is high.

**Comment by aforaleka** [comment]
Hi @henrikingo! We're glad to hear that you're finding Wit useful and fun :) We currently tune our speech recognition service to all kinds of apps, so it's expected that it might not transcribe your speech exactly. However, we are taking your feedback seriously and many improvements are coming in the near future!

**Comment by henrikingo** [comment]
I know how machine learning works. The issue here is not that it doesn't work exactly, rather it doesn't seem to recognize the child's voice at all. The output is the same as if nobody talks anything. (Usually empty _text field.)

**Comment by gondiss** [comment]
Hi henrikingo, thanks for the specific feedback. appreciate it. we will look closely at your app and investigate why the service is not transcribing child's voice.

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
