### ISSUE TITLE
/samples API returns 500

### ISSUE THREAD

**Issue by rahadianahmad** [wit-ai/wit#1697]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
`/samples` api returns 500 with this JSON:

```
{
    "error": "Something went wrong. We've been notified",
    "code": "unknown"
}
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

```
curl --location --request GET 'https://api.wit.ai/samples?limit=10' \
--header 'Authorization: Bearer xxxxx'
```

**What is the expected behavior?**
it returns 200 with list of samples

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
`218555539575429`
`543948353207191`

**Comment by jtliao** [comment]
Your apps have been fixed temporarily, we found an issue with `PUT entities` -- we'll work on a fix soon.

**Comment by kras95** [comment]
Hello, I'm having the same issue right now while in my "/entities/greetings" section.

I added a few greetings and it stopped working.

App ID: 860002774487618

**Comment by rahadianahmad** [comment]
> Your apps have been fixed temporarily, we found an issue with `PUT entities` -- we'll work on a fix soon.

Hi jtliao, do we have the fix already ?

We have similar issue with 2 others apps as well

```
2265841803520104
2696660233750180
```

these are our production apps, can advise what we can do to prevent this ?

thanks

**Comment by jtliao** [comment]
sorry for the delay -- but neither of the above apps seem to throw 500s when I send a `GET /samples` request

**Comment by rahadianahmad** [comment]
hi, i will close this ticket as initial issue is solved.
altho we are facing several issues with our apps right now, will open tickets once we understand them better.

thanks!
