### ISSUE TITLE
'Fuzzy' time concepts entity

### ISSUE THREAD

**Issue by huanga** [wit-ai/wit#170]
For example; 'tomorrow' currently gets converted as "2/25/2015, 12:00:00 AM", and 'next week' gets converted as "3/2/2015, 12:00:00 AM". Both of these are very concrete, and are useful in some context. In other context, 'tomorrow' would mean between "2/25/2015, 12:00:00 AM" and "2/25/2015, 11:59:59 PM", and next week could mean the equivalent of next calendar week.

Is there a way to make `wit/datetime` 'fuzzy' such that the system provides a timerange?

I've seen #118 and tried marking 'next week' and 'tomorrow' as `wit/duration` but it doesn't seem to be able to identify them as valid duration at all (e.g.:  `curl   -H 'Authorization: Bearer TOKEN GOES HERE'   'https://api.wit.ai/message?v=2015224&q=Setup%20a%20meeting%20tomorrow%20with%20John%20to%20discuss%20top%20secret%20project'` does not return a `wit/duration` block).

**Comment by jeffklassen** [comment]
What interface are you using to retrieve the datetime? When using the http or NodeJS clients a 'grain' value is returned along with the date time:

```javascript
 [{
   "_text": "remember to call Ryan next week",
   "intent": "add_reminder",
   "entities": {
    "datetime": [{
      "grain": "week",
      "type": "value",
      "value": "2015-03-09T00:00:00.000+01:00"
     }],
    "contact": [
     {
      "value": "Ryan"
     }]},
   "confidence": 1}]
```

Other values for grain I've seen have been: minute, hour, day, month. I'm sure there are more. 

@huanga, I hope this helps you.

It would be nice to see the values for 'grain' listed somewhere.

**Comment by huanga** [comment]
I was using raw curl. I must've been blind and missed it! :)  This is great, thanks @jeffklassen !
