### ISSUE TITLE
Invaild Intent Showing 

### ISSUE THREAD

**Issue by jurneek** [wit-ai/wit#1700]
Our database is showing and intent of just numbers being matched we recently deleted an intent but on wit's end, it isn't deleting properly. Can someone from Wit please help us look into this?

**Comment by lycai-fb** [comment]
Hi @jurneek 

Please take a look at the [issue template](https://github.com/wit-ai/wit/blob/master/ISSUE_TEMPLATE.md). In particular, I will need the App ID where you're having the issue.

**Comment by jurneek** [comment]
58c80d0b-dc8a-443a-9570-013e22a1bf8c @lycai-fb

**Comment by lycai-fb** [comment]
Thanks for the update, but I'm going to need some additional info:
- What intent are you trying to delete?
- What steps are you performing to do this?
Thanks.

**Comment by jurneek** [comment]
@lycai-fb the intent was deleted and no longer showing but in our database, the intent has changed named.  Can I have your email to send images better explaining

**Comment by patapizza** [comment]
Hi @jurneek, please sent your images to help@wit.ai.

Thanks!
