### ISSUE TITLE
get entity not found

### ISSUE THREAD

**Issue by WerAndres** [wit-ai/wit#1702]
Hello, 

When I create an entity:

ENDPOINT: https://api.wit.ai/entities?v=20200424
METHOD: POST
Body:{  "id":"si_533ac084" }
Response: {
    "doc": "User-defined entity",
    "id": "665abc47-2edd-4d6c-961d-5970996b626d",
    "lang": "en",
    "name": "si_533ac084",
    "lookups": [],
    "builtin": false
}

the result is successful, but when I consult the entity created the result:

ENDPOINT: https://api.wit.ai/entities/si_533ac084?v=20200424
METHOD: GET
Response: {
    "error": "Entity 'si_533ac084' not found",
    "code": "not-found"
}

but, in the list of entities appears:

ENDPOINT: https://api.wit.ai/entities?v=20200424
METHOD: GET
[
    "intent",   
    "si_533ac084",  
    "wit$age_of_person",
    "wit$agenda_entry",
    "wit$amount_of_money",
    "wit$contact",
    "wit$datetime",
    "wit$distance",
    "wit$duration",
    "wit$email",
    "wit$local_search_query",
    "wit$location",
    "wit$math_expression",
    "wit$message_body",
    "wit$message_subject",
    "wit$number",
    "wit$on_off",
    "wit$ordinal",
    "wit$phone_number",
    "wit$phrase_to_translate",
    "wit$reminder",
    "wit$search_query",
    "wit$temperature",
    "wit$url",
    "wit$volume",
    "wit$wdatetime",
    "wit$wikipedia_search_query",
    "wit$wolfram_search_query"
]

Why is this happening?

thank you for your attention

**Comment by jtliao** [comment]
Fixed, sorry for the inconvenience.
