### ISSUE TITLE
Empty responses for certain phrases/words

### ISSUE THREAD

**Issue by sug-do** [wit-ai/wit#1703]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
issue/question
**What is the current behavior?**
I am getting empty responses for some phrases/words
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
check logs and see that certain phrases are giving empty responses. this happens in API or in the web UI with the same phrase. two examples "Snoozing an alarm is disagreeing with your past self" and "It's simple to live a difficult life. It's difficult to live a simple life." 
from the logs:
```
"_text":
"Snoozing an alarm is disagreeing with your past self"
"confidence":
null
"intent-id":
"default_intent_id"
"intent":
"default_intent"
"entities":
```
```
"_text":
"It's simple to live a difficult life. It's difficult to live a simple life."
"confidence":
null
"intent-id":
"default_intent_id"
"intent":
"default_intent"
"entities":
```
**What is the expected behavior?**
expected behavior is a response with sentiment values
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2667070580228797
~~**Additional notes**
I do see that the wit.ai app is showing in ONGOING status for a long time now. and, when hovering over it a popup shows "Your app is currently training". not sure if 2 different things are going on here, or one thing is the root cause. I realize I uploaded a pretty large data set. how long should it take to train? if anyone could check on the ONGOING status and provide an update that it hasn't actually stalled in the background would be appreciated.~~

**Comment by lycai-fb** [comment]
Hi @sug-do 

It looks like you're using the built-in sentiment model. This model will not return a response if it has very low confidence.
Also since it is built-in, your validated samples may not affect the global model.

Hope this sheds some light into your situation. :)

**Comment by sug-do** [comment]
That makes much more sense. I overlooked that bit in the documentation @lycai-fb
