### ISSUE TITLE
app is unresponsive

### ISSUE THREAD

**Issue by bmcclenahan** [wit-ai/wit#1704]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
no response from https://wit.ai/brucemcclenahan/churchbot
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
needs a reset
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by jtliao** [comment]
working on a fix
