### ISSUE TITLE
Training scheduler not updating

### ISSUE THREAD

**Issue by asfyra** [wit-ai/wit#1707]
We encounter an issue with the training scheduler for application Id: 2841817995840539
Application training stopped being triggered since April 24.
Although we validate samples, training does not schedule to run.
Could you please check what's wrong with this?

Thank you

**Comment by asfyra** [comment]
It looks like someone forced the app to train, but it has now stack on ONGOING state for days.
Could you please check if the app is in need of a little push?

Thank you

**Comment by jtliao** [comment]
should be ok now, there were some issues with the scheduler
