### ISSUE TITLE
Web site: App details does not work

### ISSUE THREAD

**Issue by cesarve77** [wit-ai/wit#1709]
Reporting a bug

**What is the current behavior?**

I try to enter to my app details and get stuck
e.g. https://wit.ai/cesarve77/3333/
![image](https://user-images.githubusercontent.com/3970983/80652770-01636f80-8abc-11ea-9aa3-c8d136f00349.png)
always empty

**steps to reproduce.**

login to my accounts
go to https://wit.ai/cesarve77/3333/

**What is the expected behavior?**

Show my app details

**Other**
```
No working: https://wit.ai/cesarve77/11111 
No working: https://wit.ai/cesarve77/2222 
No working: https://wit.ai/cesarve77/3333 

Working: https://wit.ai/cesarve77/2020es/entities
```
*In the console I can see:*
![image](https://user-images.githubusercontent.com/3970983/80652375-1be91900-8abb-11ea-9314-080f5a209a01.png)

![image](https://user-images.githubusercontent.com/3970983/80652730-eb55af00-8abb-11ea-8f80-1b5dbe41b942.png)

*This request:*
`https://api.wit.ai/inst/cesarve77/2222`
*is returning: *
```
{
   "error": "Something went wrong. We've been notified",
   "code": "unknown"
}


likely related to:
https://github.com/wit-ai/wit/issues/1697


```

**Comment by jtliao** [comment]
Fixed

**Comment by cesarve77** [comment]
Thanks for your quick response.

I have some others app which are not working.
like:
No working: https://wit.ai/cesarve77/11111 
No working: https://wit.ai/cesarve77/2222 
No working: https://wit.ai/cesarve77/3333
