### ISSUE TITLE
Highlighting for spanned entities

### ISSUE THREAD

**Issue by jeffklassen** [wit-ai/wit#171]
It would be great to include a 'highlighting' mechanism for spanned entities. This would allow us to have our users be able to validate returned outcomes. 

Rather than a returned entity object simply containing the extracted entity, an entity object could contain a pointer to the original text used to derive that entity.

Consider the following (100% correct) outcome:

```javascript
"outcomes": [{
   "_text": "remember to call Ryan tomorrow night",
   "intent": "add_reminder",
   "entities": {
    "datetime": [{
      "to": {
       "value": "2015-03-07T00:00:00.000+01:00",
       "grain": "hour"
      },
      "from": {
       "value": "2015-03-06T18:00:00.000+01:00",
       "grain": "hour"
      },
      "type": "interval"
     }],
    "contact": [ {
      "value": "Ryan"
     }]},
   "confidence": 1
  }]
```
Why not make the datetime entity look like this (notice the last object property):
```javascript
    {
      "to": {
       "value": "2015-03-07T00:00:00.000+01:00",
       "grain": "hour"
      },
      "from": {
       "value": "2015-03-06T18:00:00.000+01:00",
       "grain": "hour"
      },
      "type": "interval",
      "original_text": "tomorrow night"
     }
```
and the contact entity look like this: 
```javascript
    {
      "value": "Ryan",
      "original_text": "Ryan"
     }
```
This would obviously only work for spanned entities.

**Comment by stopachka** [comment]
Hiya Jeff, you can do this :). If we add verbose=true to your query, you'll get much more information -->

```
curl \                                                                                                                                                                                                                           git:master
  -H 'Authorization: Bearer $TOKEN' \
  'https://api.wit.ai/message?v=20150409&verbose=true&q=I%20want%20to%20wake%20up%20at%206am'
{
  "stats" : {
    "total_time" : 20
  },
  "msg_id" : "add53b95-9b0d-4684-a49a-32d6ef4c1a6f",
  "_text" : "I want to wake up at 6am",
  "outcomes" : [ {
    "_text" : "I want to wake up at 6am",
    "intent" : "alarm_set",
    "entities" : {
      "datetime" : [ {
        "grain" : "hour",
        "type" : "value",
        "value" : "2015-04-10T06:00:00.000-07:00",
        "_entity" : "datetime",
        "_end" : 24,
        "_start" : 18,
        "_body" : "at 6am"
      } ]
    },
    "confidence" : 1.0
  } ]
}%
```

You can use the `_start` and `_end` values to highlight entities. For entity names an roles, you will have `_entity` and `_role` respectively. 

Does that help?

**Comment by jeffklassen** [comment]
Wow, that's exactly (if not a bit better than) what I was looking for. Thanks. 

Is this reflected in the documentation anywhere? I had looked around for it, but was unable to find this functionality.

**Comment by l5t** [comment]
Hi Jeff,
You're right. It is no yet documented.
