### ISSUE TITLE
App recognizes nearly everything as a math_expression

### ISSUE THREAD

**Issue by edje123** [wit-ai/wit#1710]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
Adding a math_expression entity makes the app begin understanding almost anything as a math_expression. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Add a math_expression entity. Train the entity on something like "1+1" and validate that this is a math_expression. Next, enter anything else in the "User says..." box. It will begin to understand essentially anything as a math_expression despite repeated training.

Here is a gif showing the issue: https://imgur.com/a/FzHeGUK

**What is the expected behavior?**
The math_expression entity should only recognize math expressions such as "one plus one" or "2 + 3" and not something not related to a math expression.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

626071267980541

**Comment by edje123** [comment]
The only solution I could find was to export my training and import it into a new app. I have left the previous app alone so it can be referenced to see the issue, but it is still frozen at "Done" without actually having processed any new training.

**Comment by jtliao** [comment]
merging with #1711
