### ISSUE TITLE
Bot now recognizing everything as a wikipedia query and refuses to start training

### ISSUE THREAD

**Issue by edje123** [wit-ai/wit#1711]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
No matter what I do, it interprets everything as a wikipedia query. It also is stuck at "Done" training and says it finished quite some time ago even though I've submitted several new trainings just now.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Type something in, it interprets it as a wikipedia search query. Change anything and hit validate, nothing happens and the bot does not begin training.

**What is the expected behavior?**
It should only interpret some things as wikipedia search query and should begin training after told to validate.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
626071267980541

**Comment by edje123** [comment]
The only solution I could find was to export my training and import it into a new app. I have left the previous app alone so it can be referenced to see the issue, but it is still frozen at "Done" without actually having processed any new training.

Now, however, it had yet again gotten stuck at "ongoing"

**Comment by jtliao** [comment]
It seems like the wikipedia model is too greedy. I'll merge with #1615 to keep track of the model improvement for the built-in entity.
