### ISSUE TITLE
Entities tagging wrong keywords

### ISSUE THREAD

**Issue by mohansr03** [wit-ai/wit#1714]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
I have changed my the entities **connect** and **live** from **free text and keywords** to **keywords**
Now whatever the untrained word is typed it is identifying as either connect or live.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Type keyword **show** and check it is identified as connect with the minimal score.
**What is the expected behavior?**
1. The untrained word should not be identified as trained.
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
146162883492071

**Comment by jtliao** [comment]
I can't reproduce this -- just typed `show` and no entities resolved.
