### ISSUE TITLE
can't seem to train intent (trait entity) with samples api but UI seems to work

### ISSUE THREAD

**Issue by swys** [wit-ai/wit#1715]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug? or am I doing something wrong?

**What is the current behavior?**
sending samples to the /samples api I get successful response but when I ask the app the same question I just trained via samples api it doesn't catch the intent, it does catch builtin/keyword entity though. This seems to be happening only with trait entities. When the entity is keyword I am able to get back expected results when keywords are added to entity and I put a question that includes a newly added keyword it rightfully triggers the entity with minimal training.

However if I go to UI and manually point out trait entity, in this example the intent entity, I am able to get it to start recognizing intents. The issue is, I would like to do this programmatically through the samples api, but even if I send 10 20 50 100 samples of the same thing to the samples api I still can't get it to trigger the entity, but if I do like 1 time in the UI it starts to trigger.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

send below sample to /samples api : 
```
{
  "text": "do you open on monday?",
  "entities": [
    {
      "entity": "intent",
      "value": "store_hours",
      "role": "",
      "subentities": null
    },
    {
      "entity": "wit$datetime",
      "value": "monday",
      "role": "",
      "subentities": null
    }
  ]
}
```
get back 200 from /samples api. with body : 
```
{
  "sent" : true,
  "n" : 1
}
```
go back to UI and ask same question I just trained from above and get back : 
```
{
  "_text": "do you open monday?",
  "entities": {
    "datetime": [
      {
        "confidence": 0.96410501003265,
        "type": "value",
        "grain": "day",
        "value": "2020-05-04T00:00:00.000-07:00",
        "values": [
          {
            "type": "value",
            "grain": "day",
            "value": "2020-05-04T00:00:00.000-07:00"
          },
          {
            "type": "value",
            "grain": "day",
            "value": "2020-05-11T00:00:00.000-07:00"
          },
          {
            "type": "value",
            "grain": "day",
            "value": "2020-05-18T00:00:00.000-07:00"
          }
        ]
      }
    ]
  },
  "msg_id": "1uGi9c5iveYwOhEKr"
}
```
Train this sample a lot a lot a lot more times via /samples api and go back to UI and ask same question again, and get back same response as above. The intent is not triggering, though the `wit$datetime` entity is triggering just fine.

Then manually put intent = store_hours in UI 1 time. Then let it train. Then ask same question inside UI and get back response : 
```
{
  "_text": "do you open monday?",
  "entities": {
    "intent": [
      {
        "confidence": 0.9499953467198,
        "value": "store_hours"
      }
    ],
    "datetime": [
      {
        "confidence": 0.98357819840148,
        "type": "value",
        "grain": "day",
        "value": "2020-05-04T00:00:00.000-07:00",
        "values": [
          {
            "type": "value",
            "grain": "day",
            "value": "2020-05-04T00:00:00.000-07:00"
          },
          {
            "type": "value",
            "grain": "day",
            "value": "2020-05-11T00:00:00.000-07:00"
          },
          {
            "type": "value",
            "grain": "day",
            "value": "2020-05-18T00:00:00.000-07:00"
          }
        ]
      }
    ]
  },
  "msg_id": "1B9FxHXJtOidAYhVd"
}
```
So after 1 training in UI it suddenly triggers the intent with ~94% confidence?

Am I doing something wrong in the /sample training, even though I train 100 times same sample I can't get the trait entity to recognize but after just 1 training in UI it triggers.

**What is the expected behavior?**

I expect that if I train via /samples api it should have similar result as when I go to UI and manually callout the entities. This seems to be especially hard for trait entities. Keywords and builtin entities seem to work much better when training from /samples api.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
3030437770345565

**Comment by jtliao** [comment]
can you try removing the `role` input? trait entities should not have roles

**Comment by swys** [comment]
@jtliao thanks! This turned out to be an issue in the lib I'm using to call the wit.ai api. Basically when I don't put value for role or subentities it was still sending the keys in the json, and that seemed to cause a silent error on wit side that prevented good training. 

I was able to fork and fix that issue and now I able to train trait entities just like I do in the UI.

This is a very subtle bug and I really can't blame the lib if wit was still returning a 200 even with bad input. Is it possible to return a 400 in these cases where it won't be able to train because it was given extra keys that would prevent training?

**Comment by jtliao** [comment]
yes, we'll do that
