### ISSUE TITLE
How long do the app takes to complete maintenance?

### ISSUE THREAD

**Issue by mohansr03** [wit-ai/wit#1716]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question
**What is the current behavior?**
Whenever I try to train the entity below notification is getting
Your app is undergoing maintenance, and cannot be updated right now. Please try again later.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
How long does it take to come out of maintenance?
Entity or Intent is not getting trained
**What is the expected behavior?**
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2568345553211430

**Comment by jtliao** [comment]
done
