### ISSUE TITLE
Can't add multiple entities to an expression

### ISSUE THREAD

**Issue by kras95** [wit-ai/wit#1717]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question / Bug

**What is the current behavior?**
Adding multiple entities for an expression is returning only the first entity in the API output. 
Is this normal behavior and is there any workaround for this?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. I am creating a new entity named "question" with lookup strategy "trait"
2. I am adding a couple of questions, which are stored on my database. Depending on the question, wit returns the ID of the detected question.
3. After all of the questions are added, I add additional single-worded expressions and add multiple IDs of questions to them, expecting the API to return the IDs of those question when the user uses the single-worded expression, but the API returns only the first entity I added.

Minimal demo of the problem:
This is my app ID 860002774487618
The problem is in entities/question "дезинфектант"
![image](https://user-images.githubusercontent.com/52287634/81000459-fb201b00-8e4e-11ea-9351-bd097407f778.png)

**What is the expected behavior?**
I expect the API to return the ID of all of the entities I provided for this expression, but it's returning only the first entity.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
860002774487618

**Comment by kras95** [comment]
Hello,

Is there any update for my question?

Is this expected behavior or a bug?

**Comment by jtliao** [comment]
Sorry for the delay -- you can use the `n` parameter to get more entities back https://wit.ai/docs/http/20170307#get__message_link

**Comment by kras95** [comment]
Hello,

This solution does not provide the desired result.

When the user types "дезинфектант" (desinfectant), the bot returns this question array:

```
[question] => Array
        (
            [0] => Array
                (
                    [confidence] => 0.9793326427859
                    [value] => 3
                )
            [1] => Array
                (
                    [confidence] => 0.0021390410225133
                    [value] => 74
                )

            [2] => Array
                (
                    [confidence] => 0.0015532493672051
                    [value] => 8
                )

            [3] => Array
                (
                    [confidence] => 0.00083253193270723
                    [value] => 39
                )

            [4] => Array
                (
                    [confidence] => 0.0006247529946834
                    [value] => 40
                )

            [5] => Array
                (
                    [confidence] => 0.00046735913159236
                    [value] => 7
                )

            [6] => Array
                (
                    [confidence] => 0.00034639032491843
                    [value] => 28
                )

            [7] => Array
                (
                    [confidence] => 0.00033868561639898
                    [value] => 33
                )

        )
```

Going by my first message, it should return only values 3,7,8 right? Or at least show 3,7,8 with a higher confidence, but the confidence is very low for all of them, except for the first one (3).

8 doesn't appear at all in the answers array.
