### ISSUE TITLE
Unable to export to .zip

### ISSUE THREAD

**Issue by fahmidumadi** [wit-ai/wit#1718]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
report a bug
**What is the current behavior?**
Cannot export wit data to .zip
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Download .zip with your data
2. 
![image](https://user-images.githubusercontent.com/7076777/81030356-bf1ea180-8eb2-11ea-881b-64e6187c99e1.png)

**What is the expected behavior?**
1. Download .zip with your data
2. Data successfully download to .zip

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2136203549756950

**Comment by mohansr03** [comment]
APP ID: 2601872093236812
same for my app too

**Comment by FengyangZhang** [comment]
@mohansr03 just fixed your app, it should be good to export now. @fahmidumadi still working on yours.

**Comment by FengyangZhang** [comment]
@fahmidumadi your app is good to export now.

**Comment by fahmidumadi** [comment]
@FengyangZhang thanks!
