### ISSUE TITLE
One App does not load due to javascript errors 

### ISSUE THREAD

**Issue by b-tix** [wit-ai/wit#1719]
`Failed to load resource: the server responded with a status of 500 (Internal Server Error)
static.xx.fbcdn.net/rsrc.php/v3/y8/r/t-zKLr5hb2k.js?_nc_x=Ij3Wp8lg5Kz:9 Uncaught error
znchvkzeuNj.js:56 Uncaught TypeError: Cannot create property 'fileName' on string 'error'
    at onerror (znchvkzeuNj.js:56)
api.wit.ai/inst/b-tix/AvaV2:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
static.xx.fbcdn.net/rsrc.php/v3/y8/r/t-zKLr5hb2k.js?_nc_x=Ij3Wp8lg5Kz:9 Uncaught error
znchvkzeuNj.js:56 Uncaught TypeError: Cannot create property 'fileName' on string 'error'
    at onerror (znchvkzeuNj.js:56)`

Above you see the script error that will cause the page stop loading after showing the title with main navigation. It seems to be a backend problem especially with this app.

The AppID ist 2115985458480186

Could somebody take a look on this please? My other Apps seems to work as usual.

**Comment by FengyangZhang** [comment]
Just fixed it, thanks for the patience.
