### ISSUE TITLE
Apple linker -o error when combine with cocos2d project

### ISSUE THREAD

**Issue by XiWang210** [wit-ai/wit#172]
Hi, i am writing an iOS project which will use cocos2d and wit in object-c.  
I can use wit successfully in my single object-c project, but when i try to combine wit with my cocos2d project, it got apple liker -o errorr like this, it looks like i miss some framework? but i added all framework wit need as tutorial guid. 
i can use wit in my single object-c project, i do not  know why it can not work when combine with cocos2d project. anyone can help?   

Undefined symbols for architecture x86_64:
  "_vDSP_create_fftsetup", referenced from:
      -[WITVad init] in Wit(WITVad.o)
  "_vDSP_ctoz", referenced from:
      -[WITVad get_fft:] in Wit(WITVad.o)
  "_vDSP_fft_zrip", referenced from:
      -[WITVad get_fft:] in Wit(WITVad.o)
  "_vDSP_zvabs", referenced from:
      -[WITVad get_fft:] in Wit(WITVad.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by louisandkatherine** [comment]
What was the solution for this in the end?
