### ISSUE TITLE
Wit/number Roles

### ISSUE THREAD

**Issue by mohansr03** [wit-ai/wit#1720]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
I have trained some entities using wit/number:role
for example(**20 lakhs as wit/number:lk**, **1 crore as wit/number:cr**, **2 bhk as wit/number:bhk**)
Entities were getting identified earlier fine but from few days all things were messed up.
lakhs getting identified as wit/number:bhk
crores getting identified as plain wit/number
and so many entities are being identified wrong
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
It is happening with all my apps.
**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2741036935962163
2606996746291762
3055816804429459

**Comment by FengyangZhang** [comment]
Looking

**Comment by FengyangZhang** [comment]
@mohansr03 can you give an example query that gets mis-classified?

**Comment by mohansr03** [comment]
APP ID: 2568345553211430
query: show me 2 bhk properties in 4th avenue sunteck city
In the above query, everything is

**Comment by jiayexie** [comment]
Hi @mohansr03, it looks like you have trained something with "th avenue sunteck" as the projects entity as a synonym to "4th avenue sunteck" (https://wit.ai/mohansairajubalagam/new_sunteck_city/entities/projects), causing wit to think "4" is a number and "th avenue sunteck" is the project.

If that synonym was added by mistake, can you delete it and try again?

**Comment by mohansr03** [comment]
I have deleted that, It is working fine now.
I'm very grateful for your help.
