### ISSUE TITLE
Roles have been renamed without our doing

### ISSUE THREAD

**Issue by hactar** [wit-ai/wit#1721]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

App ID: 5a2934a4-a921-48f2-8439-960637f89aba

Our long running model (https://wit.ai/hactar/NewWaveV4) is suddenly returning roles differently to what we set up, and to what our apps expect.

```
curl "https://api.wit.ai/message?v=20190505&q=wie%20komme%20ich%20zum%20schwedenplatz&verbose=true" \
     -H 'Authorization: Bearer KEY’
```

This now returns the following entity:

```
    "to_vienna_public_transport_station": [
      {
        "confidence": 0.99966670184084,
        "value": "Schwedenplatz",
        "type": "value",
        "_entity": "vienna_public_transport_station",
        "_role": "to_vienna_public_transport_station",
        "_body": "schwedenplatz",
        "_start": 18,
        "_end": 31
      }
    ],
```

However we had set this up to return something like:

```
    "to": [
      {
        "confidence": 0.99966670184084,
        "value": "Schwedenplatz",
        "type": "value",
        "_entity": "vienna_public_transport_station",
        "_role": "to",
        "_body": "schwedenplatz",
        "_start": 18,
        "_end": 31
      }
    ],
```

the entity name should not be appended to the role.

I cannot tell you the exact time of when this started occuring - last week maybe? But this change was not made by us. Any idea of what happened and how we can revert the roles to the ones our apps expect? Changing the v parameter to an earlier date has no effect.

**Comment by FengyangZhang** [comment]
Hi @hactar, do you mean you didn't create "to_vienna_public_transport_station" as a role for the "vienna_public_transport_station" parser? If that's the case it might be some error on our end because we are going through a big migration. I can help you rename the roles back if you want that.

**Comment by hactar** [comment]
Yes - the correct role would be just "to". This has happened to all roles, they now have their entity name appended. "from_location" role should be "from", "search_modifier_near_location" should be "search_modifier_near", etc.

**Comment by patapizza** [comment]
Sorry about that! Taking it offline for broader context.
