### ISSUE TITLE
Not able to access my apps

### ISSUE THREAD

**Issue by GauravDobhal** [wit-ai/wit#1723]
I am not able to access my wit.ai apps after logging in. It seems stuck.

**Comment by GregorD1A1** [comment]
I've tryed to login trough facebook to try v2 version of wit (normally I'm logging in through github), but page haven't loaded. After that I logged in through github and my aps also dissapears.

**Comment by mohansr03** [comment]
Same with my apps as well, A loading indicator is getting displayed.

**Comment by GregorD1A1** [comment]
Ok, it seems I solved that problem. I think they moved projects from github to facebook profile. Try to signout, after that go to wit.ai/home and login with a facebook

**Comment by dogcalas** [comment]
Same problem. On browser console this message is showed: 
```Endpoint is only accessible to the Wit.ai apps for whitelisted Wit users. TAAL[1]```

**Comment by GauravDobhal** [comment]
Going to wit.ai/home solves the problem for me.

**Comment by patapizza** [comment]
Sorry about that. We're pushing a fix, should be resolved today.
In the meantime, going to `wit.ai/home` as others suggested would do it.

**Comment by patapizza** [comment]
We should be good to go since 3h ago.
