### ISSUE TITLE
wit/location:city split the keyword

### ISSUE THREAD

**Issue by ducla2** [wit-ai/wit#1724]
1. It is a bug.
2. Current behavior:
The wit/location:city splits the keyword as single word not the whole keyword.
a. đà nẵng 
wit/location:city : đà
wit/location:city: nẵng
b. hạ long
wit/location:city : hạ 
wit/location:city: long

3. Expected behavior like before (yesterday)
a. đà nẵng 
wit/location:city : đà nẵng

b. hạ long
wit/location:city : hạ long

4. AppID: 1778316165603240
Is there any update on Wit recently on wit/location:city? I
![wit](https://user-images.githubusercontent.com/22384887/81279962-0313d100-9082-11ea-8e4b-ca6051e9fba3.PNG)
![wit1](https://user-images.githubusercontent.com/22384887/81280079-2fc7e880-9082-11ea-8781-ea81c77a801a.PNG)

t worked well with full "đà nẵng" and "hạ long" before.
Please help to check.

**Comment by hactar** [comment]
Having the same issue with "tokiostrasse 3" which is now split to "tokiostrasse" and "3", both as individual wit/location. This worked a few weeks ago.

**Comment by jiayexie** [comment]
Hi @ducla2 @hactar, thanks for reporting the issue. We have a fix on the way and should be available tomorrow.

**Comment by ducla2** [comment]
xiexie!

**Comment by jiayexie** [comment]
@ducla2 the fix is deployed and I tested with your app - seems to be working. Could you please confirm?

**Comment by ducla2** [comment]
Thanks @jiayexie  for your supporting. Our app works well.

**Comment by ducla2** [comment]
@jiayexie Our app works well for wit/location:city.
BUT all the trained for wit/location:hotel now becomes with/location:city
![image](https://user-images.githubusercontent.com/22384887/81769246-51ecbb00-9507-11ea-8ffc-1fd15c12d1df.png)

![image](https://user-images.githubusercontent.com/22384887/81769285-6af56c00-9507-11ea-8a2e-2814e085b0ac.png)

Please help review

**Comment by jiayexie** [comment]
Hi @ducla2, is this also new behavior that just changed within the past week?

**Comment by ducla2** [comment]
Hi @jiayexie, that's right. This is a new behavior. I already trained samples with these hotel names long time ago. (>6 months).

**Comment by jiayexie** [comment]
Thank you for confirming and sorry for the inconvenience. We're troubleshooting this and will update our progress here.

**Comment by ducla2** [comment]
Add more new behaviors:
1. The already trained wit/number:child now becomes wit/number:price
![image](https://user-images.githubusercontent.com/22384887/81772584-75683380-9510-11ea-99c8-168af7619c67.png)

2. wit/number:rooms now becomes wit/number:price
![image](https://user-images.githubusercontent.com/22384887/81772649-9df02d80-9510-11ea-81e9-c44d251093a8.png)

3. wit/number:nights now becomes wit/number:price

![image](https://user-images.githubusercontent.com/22384887/81772675-a9435900-9510-11ea-800e-b07cd3c4cbff.png)

4. wit/number:childsage now becomes wit/number:rooms
![image](https://user-images.githubusercontent.com/22384887/81772757-dbed5180-9510-11ea-885f-47362c52cd48.png)

**Comment by jiayexie** [comment]
Could you please try again? We just fixed some training data issue on our side and the hotel example seems to be fixed.

**Comment by ducla2** [comment]
Thanks @jiayexie ,
1. wit/number:child  -> OK
2. wit/number:childsage -> OK
3. wit/number:nights -> OK
4. wit/number:rooms -> OK
5. wit/location:city -> OK
6. wit/location:hotel -> OK

**Comment by ducla2** [comment]
Hi @jiayexie ,

Today, the wit re-open this issue:
1. wit/number:child -> wit/number:price
![image](https://user-images.githubusercontent.com/22384887/83391307-7a3c4b00-a41d-11ea-86fa-57d54ac4c11b.png)

2. wit/number:childsage -> wit/number:rooms
![image](https://user-images.githubusercontent.com/22384887/83391205-52e57e00-a41d-11ea-9bd6-334917573acc.png)

3. wit/number:nights -> wit/number:price
![image](https://user-images.githubusercontent.com/22384887/83391166-452ff880-a41d-11ea-92aa-ad374d726bd7.png)

3. wit/number:rooms -> wit/number:price
![image](https://user-images.githubusercontent.com/22384887/83391259-6d1f5c00-a41d-11ea-8370-3ec60051a4e3.png)

Please help review.
Thanks

**Comment by ducla2** [comment]
Related to https://github.com/wit-ai/wit/issues/1786
