### ISSUE TITLE
"Unknown path component" error on my request

### ISSUE THREAD

**Issue by AlexMercan** [wit-ai/wit#1725]
Hello.
This is a question because I don't believe it is a bug on your end.
My question is related to this documentation: https://wit.ai/docs/http/20170307#post__entities__entity_id_values_link

I'm trying to do a POST request to  /entities/$ENTITY_ID/values with this json as body:
```
{
	"value":"test",
	"expressions":["expression1", "expression2"],
        "metadata":"CITY_1234"
}
```
The problem is that whenever I send the json with 1 or more expressions I get this as a response:
```
{
    "error": "Unknown path component '[\"expression1\",\"expression2\"]'",
    "code": "bad-request"
}

```
My entity has the "keywords" lookup strategy, just like the documentation recommended.
The request is done with Postman

**Comment by patapizza** [comment]
Thanks for reporting, looking into it.

**Comment by patapizza** [comment]
Hey @AlexMercan,

We can't reproduce this. Can you share a cURL that is failing for you? What is your app ID?

**Comment by AlexMercan** [comment]
```
curl --location --request POST 'https://api.wit.ai/entities/aaa/values' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer myToken' \
--header 'Content-Type: text/plain' \
--data-raw '{
	"value":"testVal",
	"expressions":["expression1", "expression2"],
    "metadata":"testt"
}
```
That is the cURL generated by Postman
My app ID is 2648112438751664

**Comment by patapizza** [comment]
Thanks!

**Comment by patapizza** [comment]
Issue identified and fix upcoming. It should be resolved in a few hours. Sorry about that.

**Comment by AlexMercan** [comment]
I did a few tests in the morning and the issue seems to be fixed. Thank you 👍
