### ISSUE TITLE
How many number of key values can we train for one entity?

### ISSUE THREAD

**Issue by mohansr03** [wit-ai/wit#1726]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question
How many key values can we train for one entity??
Currently, I have a situation where I have to train an entity with 700 key values.
Is it possible to train those many?

**Comment by FengyangZhang** [comment]
It's definitely possible, we have many apps with entity that has thousands of values. You should expect longer training time though.
