### ISSUE TITLE
Return status code and json seems to be incorrect 

### ISSUE THREAD

**Issue by AlexMercan** [wit-ai/wit#1727]
I think this is a bug.
Everytime I make a DELETE request at entities/$ENTITY_ID/values/$ENTITY_VALUE/expressions/$EXPRESSION_VALUE

I get status code 200 and a json saying I deleted the expression, even though the expression value I provided didn't exist. 
Is this normal behaviour? Shouldn't I get an error, or something like that?
Here's the cURL:
```
curl --location --request DELETE 'https://api.wit.ai/entities/testEntity/values/testVal/expressions/thisExpressionDoesntExistTest' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer myToken'
```
I tried this with both "keywords" and "free-text & keywords" as lookup strategies, but both give the same result.
My app ID is 2648112438751664

**Comment by patapizza** [comment]
Yes this is a good point. We're running this asynchronously, but you're right: we should return a 400 if it doesn't exist.

**Comment by rowe-morehouse** [comment]
Finding something similar:

Even when keyword adding XPUT is successful, I still get :

`0curl: (6) Could not resolve host: XPUT`

… as part of the terminal output.

**Comment by patapizza** [comment]
@rowe-morehouse What is the curl command you're using?

**Comment by rowe-morehouse** [comment]
using these:

`curl XPUT --url https://api.wit.ai/entities/competency_name/keywords?v=20200513 --header 'authorization: Bearer $MY_TOKEN' --header 'content-type: application/json' --data @myFile.json | json_pp`

`curl -XPOST --url 'https://api.wit.ai/utterances?v=20200513' --header 'authorization: Bearer $MY_TOKEN' --header 'content-type: application/json' --data @myFile.json | json_pp`

**Comment by patapizza** [comment]
@rowe-morehouse You're missing a dash `-` before `XPUT` on your first command.

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
