### ISSUE TITLE
How to have Wit translate from "my bedroom" to "master_bedroom" entity, etc

### ISSUE THREAD

**Issue by Glavin001** [wit-ai/wit#173]
On the homepage there are many examples. I am trying to understand how to reproduce.

For example:

Input:

```
Set the temperature to 70° in my bedroom
```

Output:

```
intent      = heating control 
temperature = 70°F 
where       = master_bedroom
```

I am attending a Hackathon tomorrow and would like to use Wit for natural language command processing.

My personal use case (for tomorrow) will be similar to:

Input: `All Computer Science courses between 10am and 2pm`
Output:
```
intent      = "list_courses"
course_subject = "computing_science" 
start_time       = 10am
end_time   = 2pm
```

In the above case "Computer Science" from the human user got translated into "computing_science" that can be used to look up in our database.

Thank you in advance!

**Comment by l5t** [comment]
Hey,
I think the best way to do it is to follow our quickstart guide here:https://wit.ai/docs/console/quickstart
Here is a example that you can fork if you want: https://wit.ai/l5t/TempHack
Good luck for your hackathon tomorrow!
Laurent

**Comment by Glavin001** [comment]
I've actually been playing with Wit quite a bit over the past couple weeks (my account  https://wit.ai/Glavin001) and love it so far!

Thanks for your help and creating a starting point! My main problem was that I wanted `Computer Science` to be passed into the entity as `computing_science`, however I notice even in your sample app that is recognizes it exactly as it was written in the text, `Computer Science`.

When I saw how `my bedroom` in the text became `master_bedroom` in the intent, I though maybe this would solve many of my issues.
Could you please elaborate how this translation from `my bedroom` to `master_bedroom`, or in my case `Computer Science` to `computer_science` could be recognized in Wit? 

Now that I think about it, a more accurate example of what I am trying to do is:

Input texts:
- `show English courses`
- `show ENGL courses`
- `show engl courses`

Output intent:
```
intent: show_courses
course_subject_code: ENGL
```

My specific interest is recognizing `English`, `ENGL`, and `engl` all mean the same thing, `ENGL`, in the same way the Wit.ai example recognized `my bedroom` was mapped to `master_bedroom`. Is this handled by Wit.ai or is this something that is not currently avaible and understanding that `my bedroom` represents `master_bedroom` is handled by my application?

Thank you so much!

**Comment by l5t** [comment]
In this case, I would create the value first and then re-attach the expression to the value. See below and here:
https://wit.ai/l5t/TempHack

![entity_hack](https://cloud.githubusercontent.com/assets/6992759/6763237/95a0a02e-cf31-11e4-9600-3f157af3c5bd.gif)

**Comment by Glavin001** [comment]
That is perfect! Thank you!
