### ISSUE TITLE
Cannot validate new examples.

### ISSUE THREAD

**Issue by devin-moonrise** [wit-ai/wit#1730]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

Bug.

**What is the current behavior?**
The gui/web-based front end for validating new examples for training seems to be broken. The process appears to progress as normal, but then after indicating fields, etc, after clicking 'validate', the message stays in the queue and more importantly validated intents don't feed into subsequent model training.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1) Provide new training example/message to the api end point.
2) Go to wit.ai inbox for the 'app'/exndpoint.
3) Validate an intent.
4) Click validate.

**What is the expected behavior?**

The message/entry is cleared and reflected in the model's training.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

The app ID is: `2829664897119041`

**Comment by FengyangZhang** [comment]
Looking into this

**Comment by FengyangZhang** [comment]
Hi @devin-moonrise , I can't reproduce the issue, do you mean samples cannot be validated (when you click validate, the text stays there), or training is not scheduled?

**Comment by devin-moonrise** [comment]
Hi Fengyang,

Thanks for the followup.

When "validate" is clicked, it doesn't clear the entry and doesn't seem to
reflect in the class predictions going forward.

Thank you!

-D

**Comment by FengyangZhang** [comment]
thanks for clarifying, we are fixing the issue

**Comment by FengyangZhang** [comment]
the problem should have been fixed.

**Comment by devin-moonrise** [comment]
Thank you so much! We will test in the AM :)
