### ISSUE TITLE
App stuck at 'ONGOING' status

### ISSUE THREAD

**Issue by 51100807** [wit-ai/wit#1731]
**Do you want to request a feature, report a bug, or ask a question about wit?**
bug
**What is the current behavior?**
App is stucked in ongoing status. It took 3-4 days.

**What is the expected behavior?**
The expected behaviour is to get trained in like a few minutes similar to the last training time. And for the Samples tab to return the training examples..

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID:
1778316165603240

![wit stuck ongoing](https://user-images.githubusercontent.com/11769396/81765678-adff1180-94fe-11ea-9a1d-186d608a705e.png)

**Comment by jtliao** [comment]
it finished
