### ISSUE TITLE
Duplicate trait values while training with api

### ISSUE THREAD

**Issue by sabinchacko007** [wit-ai/wit#1732]
Bug

When training with post samples api , we are getting duplicate trait values and no expression is added with that trait value 

ps: scrnshot attached

appid:2788662337869759
![Screen Shot 2020-05-13 at 1 30 27 PM](https://user-images.githubusercontent.com/36190477/81787234-5bcde880-951e-11ea-99fd-3fd83bec62d4.png)

![Screen Shot 2020-05-13 at 1 34 26 PM](https://user-images.githubusercontent.com/36190477/81787458-b404ea80-951e-11ea-9141-2f990de73089.png)

**Comment by jtliao** [comment]
merging with #1684
