### ISSUE TITLE
GET /samples does not give all the posted samples

### ISSUE THREAD

**Issue by rahadianahmad** [wit-ai/wit#1733]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

bug / question

**What is the current behavior?**

samples added using `POST /samples` does not exists when loaded using `GET /samples`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. i have around 3500-ish samples
2. i upload all those samples using `POST /samples` in batch, 190 samples each request / minute
3. after all api calls are done, load `GET /samples`, it only returns 2500-ish
4. app status is trained

**What is the expected behavior?**

`GET /samples` api to return the same samples that are added using `POST`
I noticed that most of the times, there are delays between `POST` and `GET`, the `GET` api will start returning correct number of samples x minutes, this work with our smaller apps (< 1000 samples) as the delay time is not that long (< 10 minutes). But with bigger apps (> 2000 samples), the total samples will never catch up with posted samples, even if we re-send the missing samples, the app just wont update the samples.

- it would be great to get insight on how the `POST /samples` api behaves
- what are the best way to handle large samples (> 2000 samples) ?
- initially, we used `PUT entities/intents` api, but with large samples, there are a lot of samples that is not recognised, thats why we move to `POST /samples`

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

`581926776014218`

thanks a lot!

**Comment by patapizza** [comment]
Hi @rahadianahmad,

Do you see all your utterances in the UI?
BTW the samples CRUD APIs have been deprecated as of today in favor of the utterances CRUD APIs. Check them out: https://wit.ai/docs/http/20200513#get__utterances_link

**Comment by ramh** [comment]
@rahadianahmad Closing this since we did not hear back for you yet. Please re-open if you are still facing issues. Thanks.
