### ISSUE TITLE
Detecting wrong built-in entity

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#1734]
Hi team,
Our appid is 1530202523770626
We have some examples trained in wit/greetings which have the keyword "good" in it.
The issue occurred when we input "Goodbye" it detected wit/greetings and showed wrong response.
We tried to retrain but it didn't work.
How should we handle this.
Please advice

Regards
Anjaly

**Comment by jtliao** [comment]
It's on our roadmap to improve the training of built-in entities, to have better dynamic training that takes in user-validated samples more quickly. 

In the meantime, I'd recommend training your own custom entity for greetings if you are experiencing problems. 

Merging with #1615
