### ISSUE TITLE
Restore the inbox view in Wit v2

### ISSUE THREAD

**Issue by dogcalas** [wit-ai/wit#1736]
Request a *feature* in v2
The live utterance, in understanding view, require more time to train the model. To validate, we have to click the dropdown button on each item.
Please, restore the Inbox view, o at least, make training as same as v1

**Comment by patapizza** [comment]
Thanks for your feedback. Keep it coming, we're looking for polishing up the new UX before the full launch.

**Comment by NGame1** [comment]
I agree with @dogcalas. I think Inbox view is so important

**Comment by patapizza** [comment]
Agreed! This is why we've made it the top component of Understanding.
Feedback taken, we'll work on making the Inbox processing more efficient.

**Comment by dsokac** [comment]
Or let us be able to work in v1.... I connected facebook and regreted... and if I want to sign in using git, the page is blank -.-

**Comment by patapizza** [comment]
@dsokac You can still work in v1 using the dropdown menu on the top right corner, after clicking on your username/picture.

v1 is being deprecated though, so it'll be more efficient to say what could be done better so we can improve v2.
