### ISSUE TITLE
Where is the level of confidence in Wit v2?

### ISSUE THREAD

**Issue by dogcalas** [wit-ai/wit#1737]
Level of confidence , completely disappear on v2.

**Comment by patapizza** [comment]
Hi @dogcalas,

I think you're referring to Insights (https://wit.ai/docs/recipes#which-confidence-threshold-should-you-use). We're working on bringing it back, and more. Stay tuned!

**Comment by dogcalas** [comment]
I refer to this number on each utterance.
![download (1)](https://user-images.githubusercontent.com/2521769/81872851-3d78e480-9540-11ea-8f55-6f875d56100b.png)
In v2, where it is???
![image](https://user-images.githubusercontent.com/2521769/81872921-57b2c280-9540-11ea-9ae4-1b449110eccb.png)

**Comment by patapizza** [comment]
Ah, for intents it's shown in the dropdown.

<img width="761" alt="Screen Shot 2020-05-13 at 4 09 18 PM" src="https://user-images.githubusercontent.com/1015208/81875040-31872580-9534-11ea-8514-6a8715561216.png">

**Comment by dogcalas** [comment]
Humm, this is an important data, I believe should be more visible.
