### ISSUE TITLE
Entity suddenly missing

### ISSUE THREAD

**Issue by jmnsf** [wit-ai/wit#1738]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
Entity called "intent" (that exists) suddenly reports 400 bad request on its endpoint. It is also missing from https://api.wit.ai/entities?v=20200224.

The 400 status is also a bug, should be 404, but that's secondary.

The entity exists in the UI:
![image](https://user-images.githubusercontent.com/6831662/81878988-5a81d780-9581-11ea-925f-157ea01c9957.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
GET to https://api.wit.ai/entities/intent?v=20200224 returns 400 status, and the body:
```json
{
  "error": "Entity 'intent' not found",
  "code": "not-found"
}
```

GET to https://api.wit.ai/entities?v=20200224 returns:
```json
[
  "answer",
  "wit$age_of_person",
  "wit$agenda_entry",
  "wit$amount_of_money",
  "wit$contact",
  "wit$creative_work",
  "wit$datetime",
  "wit$distance",
  "wit$duration",
  "wit$email",
  "wit$local_search_query",
  "wit$location",
  "wit$math_expression",
  "wit$message_body",
  "wit$message_subject",
  "wit$notable_person",
  "wit$number",
  "wit$ordinal",
  "wit$phone_number",
  "wit$phrase_to_translate",
  "wit$quantity",
  "wit$reminder",
  "wit$search_query",
  "wit$temperature",
  "wit$url",
  "wit$volume",
  "wit$wdatetime",
  "wit$wikipedia_search_query",
  "wit$wolfram_search_query"
]
```

**What is the expected behavior?**
The `intent` entity should exist in the API.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1056248068094540

**Comment by patapizza** [comment]
Hi,

As announced in the email, intents and traits are now first class citizens. Each of these building blocks have now their own set of APIs. I’ll update the API docs tomorrow PT as I realize we’re missing some of these. In the meantime, try out ´GET /intents’ and ´GET /traits’.

**Comment by jmnsf** [comment]
@patapizza did not get an email about this 😕. Is there somewhere else these announcements are made/archived? Can't find anything in Medium.

**Comment by scottpdo** [comment]
@patapizza I also didn't get an email. Why was this change pushed before API docs were updated? This took me by surprise and it's been an incredibly frustrating day dealing with a production app that is now having issues because of the API change.

**Comment by sebastianarena** [comment]
@patapizza I got a single mail, the day of the rollout, which says:

```
Consistent APIs: Intents, entities, and traits  have their dedicated space in the runtime response. Roles have been made explicit for added simplicity and transparency.
```

No changelog on the API. No warning that intents are not part of the entities anymore. No warning about checking our API calls are all using the current api 20170307 just to be safe. Nothing. Very frustrated as how this was handled.

Which is worst... I got the email. Checked the site. The new site was not rolled out. Just this morning I doubled check just in case where I started seeing the new site, but clients were already reporting broken production apps.

**Comment by patapizza** [comment]
Hi @scottpdo, @sebastianarena,

We did send an email to all our users. It seems like it bounced for Scott - is the email still valid?
The API docs have been updated prior to sending the email.

API versioning is the standard way to guard against API breaking changes, while allowing the development team to move the product forward. It's been on [since 2014](https://wit.ai/docs/http/20200513#api_versioning_link):
> As of June 1st, 2014, requests that do not include a version parameter will hit the latest version of our API.

I'm sorry the change broke your client. It's a tough lesson to learn, but it will pay off for any other API integrations.

The full launch is targeted in June.

**Comment by scottpdo** [comment]
@patapizza I don't know what the email address you have for me as you only offer login through GitHub and Facebook. I had been using GitHub and now that you've deprecated that I had to recover my deactivated Facebook account and log in through that. A dedicated email login would be really helpful.

Also, re: "The API docs have been updated prior to sending the email." — when was the email sent? As of 24 hours ago, the docs did not include information for `/intents` endpoints, among others. They appear to have been updated sometime yesterday afternoon. But the API clearly rolled out before the docs were updated to reflect the changes.

Finally, can you explain what architecture changes were made between entities, intents, and traits? I had several 'entities' that, when I accessed the v2 app admin UI now appear as 'traits.' My code was using the `20170314` API version, but began returning different responses that made it appear that entities also had disappeared.

Again, this has just been incredibly frustrating and I want you to acknowledge that you did not adequately prepare developers using your product for this change.

**Comment by patapizza** [comment]
@scottpdo It's the email address you had on your GitHub account when signing up.

The email has been sent on 5/13 at 2pm. The API docs have been updated the same day around 1:40pm. I included the documentation for intents/traits endpoints yesterday, that was an oversight from my end.

You're right: we could definitely have done a better job in preparing developers for the preview release. My bad on this.

Intents, entities and traits are now separate, for simplicity and transparency. For such a major change, we did have to adapt all CRUD APIs to reflect the new data model. The runtime APIs did not change.

While the transition could have been smoother, I do hope you'll find net added value in the refreshed version of the product.

**Comment by jmnsf** [comment]
@patapizza did not get an email and my GH email address is active still. 

> API versioning is the standard way to guard against API breaking changes

Am using API versioning as evidenced by the issue description, didn't guard against this change.

As Scott mentioned, this could've been handled much better.

**Comment by patapizza** [comment]
@jmnsf Can you check your spam folder?

Indeed, we could have done a better job by sending an advance notice.

**Comment by jmnsf** [comment]
I did, nothing there.

**Comment by patapizza** [comment]
I sent you a message on the previous UX.
