### ISSUE TITLE
App has been stuck training for over a week

### ISSUE THREAD

**Issue by PikaDude** [wit-ai/wit#1739]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
I would like to report a bug.
**What is the current behavior?**
My app has been stuck training for over a week and has been unable to register any new samples
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I am unaware of the steps to reproduce this issue. I don't believe I did anything out of the ordinary for this to happen. I just added a few new samples once and it's been stuck training ever since.
**What is the expected behavior?**
To train the application in roughly 5-10 seconds.
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
`523648621862262`

**Comment by jtliao** [comment]
sorry about that -- we fixed the bug, it should be back to normal
