### ISSUE TITLE
Accessibility support for "training status" dot

### ISSUE THREAD

**Issue by vickychijwani** [wit-ai/wit#174]
Hi, I'm red-green colorblind and I have a lot of difficulty understanding whether my instance is done training or not. The shades of orange and green that denote "on-going" and "done" respectively are confusing for me. I have to open up Chrome Dev Tools and see the CSS class to figure it out :)

I would like to request a tiny improvement in this regard: if you could change the tooltip from the generic string "Training status" to indicate the actual status ("Training on-going" and "Training done"), it would help me immensely.

Thanks for all of your hard work on this platform!

**Comment by stopachka** [comment]
Hiya Vicky, you should be seeing a bunch of updates to the console UI :). Thanks for letting us know about this, it'll be incorporated on the redesign. In the meantime, you can click on the dot to see it's status.

**Comment by vickychijwani** [comment]
Ok, thanks! Please feel free to close this issue whenever you need to.

**Comment by stopachka** [comment]
@vickychijwani sorry for the late action on this. We've added it to the roadmap, expect a push by the end of the week
