### ISSUE TITLE
Content not Available when logging in wit.ai/v2 with Github

### ISSUE THREAD

**Issue by qfavor** [wit-ai/wit#1740]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

When I'm logging into the platform using Github I am redirected to https://wit.ai/v2 and I am receiving the following error:
'Content Not Available
You don't have access to this page. Please contact us if this is unexpected.'
<img width="1672" alt="image" src="https://user-images.githubusercontent.com/54986487/81912691-99427c80-95d7-11ea-91d8-41e694fa95f7.png">

I'm not sure how I can access my account now.

**Comment by patapizza** [comment]
Hi @qfavor,

Thanks for reporting and sorry for the inconvenience. We're looking into this.

**Comment by patapizza** [comment]
Have you tried doing a hard refresh? (Shift + Cmd + R)

**Comment by qfavor** [comment]
It seems that Firefox was the issue. I tried clearing the cache, going incognito, but it still didn't work.

Chrome worked and I was able to migrate to Facebook. Thank you.

**Comment by patapizza** [comment]
Perfect! Glad Chrome is working for you.
