### ISSUE TITLE
Persian support for Speech API

### ISSUE THREAD

**Issue by NGame1** [wit-ai/wit#1741]
Hi there, 
I had a project on WitAI from 3 years ago that having a Speech to text function for Persian language. 
but now I surprisingly see that it doesn't works anymore. 
When the Persian support will back to Sppech API again? 
Isn't there anyway for continuing using the old engine for recognition until the new one gets complete?
Regards

**Comment by jtliao** [comment]
Hi @NGame1, unfortunately we no longer have the capability to support the Persian models. It's not clear when we'll have it back, we hope by the end of the year.
