### ISSUE TITLE
Merge GitHub account with facebook

### ISSUE THREAD

**Issue by vlogkeeper** [wit-ai/wit#1743]
I believe, correct me if I am wrong, that Wit is going to Facebook only.

How do I merge my apps from my Git to my Facebook, or do I just lose all the apps? I feel there should be some sort of way to transfer some/all apps over to a Facebook account.

**Comment by vlogkeeper** [comment]
Welp, for future people asking this question, all my apps transferred over without any problems. My git email and Facebook email are different emails, so it must just detect mac address or IP.

**Comment by patapizza** [comment]
All apps follow your FB account: https://wit.ai/faq.
We don't rely on mac addresses nor IP: we bring along the apps from the logged in GitHub account.
