### ISSUE TITLE
Disappointed, frustrated with API v2 rollout

### ISSUE THREAD

**Issue by scottpdo** [wit-ai/wit#1744]
v2 of the HTTP API seems like it was rolled out with little to no notice or warning to developers. In [this thread](https://github.com/wit-ai/wit/issues/1738#issuecomment-628406443), @patapizza says that there was an email, but I never saw anything — the new API just appeared and, frustratingly, old endpoints now seem to be deprecated and not working correctly with the new architecture. No announcement on Twitter, no post on Medium, no banner in the documentation that would suggest how big of a change this is.

Where's the migration guide? Why was this major change pushed out before API docs were even ready? Why does the previous version of the API (20170307) suggest that those are just deprecated (i.e. planned obsolescence), when it appears that they are actually incompatible with it (i.e. already obsolete)?

I hope I'm not the only developer who's feeling this way. I've been a fan of Wit but I'm seriously reconsidering using it in the future after this experience.

**Comment by sebastianarena** [comment]
You are not alone. This was a dissaster of a launch. It broke our production code without any warning for many hours until we figured the API had changed.

If it is any good advice... put the version number in all your API calls as the documentation says, and the 20170307 is still there working. At least for us, everything returned to normal. There were a couple of calls that didn't include the header, and it broke phenomenally. Well... the API hadn't change in 3 years... so there was no warning at all.

Hope it helps.
And hopefully the wit team will create a proper changelog.
I'm not changing API versions until this v2 is finished.

The new entities vs intents is just so bad IMHO. We'll wait to see if it is settle to be this way forward when proper API documentation comes.

**Comment by deathg0d** [comment]
Also, now that you login with facebook, you do not even get a username. So adding new collaborators to the project is now broken? What a disaster!

**Comment by patapizza** [comment]
@scottpdo @sebastianarena Conversation in https://github.com/wit-ai/wit/issues/1738. Yes, that's why API versioning exists. Full launch targeted in June, this is a preview for existing Wit.ai developers.
@deathg0d Opening up a focused issue is enough, following up in https://github.com/wit-ai/wit/issues/1747.
