### ISSUE TITLE
v2 UX

### ISSUE THREAD

**Issue by ckfchampion** [wit-ai/wit#1745]
I am currently using the WIT interface while I set up and API but I'm not a huge fan of v2 - I think a lot of the spunk and personality has been lost. What's worse is that I can't actually train anymore. I cannot paste the utterance and if I do not type right away and click elsewhere first, I cannot write at all. 
<img width="179" alt="Screenshot 2020-05-14 at 21 28 53" src="https://user-images.githubusercontent.com/65309449/81977317-231b3580-962a-11ea-82cb-31ebc77b78b5.png">

**Comment by scottpdo** [comment]
I am experiencing the same issue.

**Comment by KananRengaraju** [comment]
Experienced the same thing

**Comment by ramh** [comment]
Sorry for the inconvenience. The issue should be resolved now.
