### ISSUE TITLE
Transfering ownership still does not work on v2

### ISSUE THREAD

**Issue by sebastianarena** [wit-ai/wit#1746]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
When adding a contributor, you are allowed to transfer ownership. There's no email. No notification. Nothing on the receiver side to get ahold of the new ownership. Thus the app is not transfered.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- Add a contributor
- Transfer ownership to contributor
Nothing happens

**What is the expected behavior?**
The new owner should receive something to let them know someone is attempting a transfer. As this does not happen, then it is not transfered

It's the second time I report this. I just tried it in the new v2 to see if it was fixed, but it is not.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

Many Apps:
293209488339257
2590165137971610
2637010602987438
769821560213666
2458109600937143
3562849007121040
2690401601189480
2691078394310991
211811950072324

Thanks!

**Comment by patapizza** [comment]
Thanks @sebastianarena, we're looking into this.

**Comment by jtliao** [comment]
Can you check the spam folder in your inbox? I just tried reproducing this and thought it was failing as well, then noticed all the e-mails were sent to the spam inbox.

**Comment by sebastianarena** [comment]
@patapizza @jtliao nothing on the spam folder unfortunately

**Comment by sebastianarena** [comment]
@jtliao just got a test transfer email from you!

**Comment by jtliao** [comment]
Yes, there seemed to be something wrong with sending e-mails to your domain specifically. We found the fix, will let it know once it rolls out to you.

**Comment by jtliao** [comment]
This should be fixed now. Sorry that it look so long to fix.

**Comment by sebastianarena** [comment]
@jtliao thank you, we finally were able to move all apps to a single account. Can you delete this test app? It seems I cant, and I dont want it lingering. Thanks! https://wit.ai/v2/apps/244526590130520

**Comment by patapizza** [comment]
Done!

**Comment by sebastianarena** [comment]
@jtliao I'm sorry to say this issue has re-appeared. In a different form, and I believe it's probably due to the new dashboard. When someone on my team requests to transfer ownership to me, I get an email (great!), I tap on the link, I get to a facebook address (instead of directly to a wit address, which is kind of annoying), but then Facebook asks me to "follow link" and when you tap that, you get to a 404 page at wit, unable to get the ownership.

**Comment by jtliao** [comment]
hey @sebastianarena, do you think you can forward me the transfer ownership e-mail at jtliao@fb.com? I'd like to take a look to see where the link is sending you.

**Comment by sebastianarena** [comment]
Just did!

**Comment by jtliao** [comment]
We'll have a fix out soon. As a work around, you can try manually removing the `/v2` and `/management` from the URL, and it should work again.

**Comment by sebastianarena** [comment]
@jtliao THANK YOU!

**Comment by jtliao** [comment]
@sebastianarena this should be fixed now

**Comment by sebastianarena** [comment]
@jtliao thank you! worked perfectly
