### ISSUE TITLE
Adding collaborators to project is now broken

### ISSUE THREAD

**Issue by deathg0d** [wit-ai/wit#1747]
How do you add collaborators to a project? With a username. But with v2 and 'login with facebook' there is no username for new users. 🙃

**Comment by jtliao** [comment]
Hi @deathg0d, thanks for the feedback. We need to show the username somewhere.

**Comment by deathg0d** [comment]
That's not the issue. How does a **new user** who just logged in to wit v2 with facebook set a username?

**Comment by patapizza** [comment]
Hi @deathg0d,

You can now see your username on the top right corner.
