### ISSUE TITLE
BUG - Your existing Wit.ai app will not be impacted.  - application impacted, does not respond with intent anymore

### ISSUE THREAD

**Issue by chatbotalex** [wit-ai/wit#1748]
BUG - Your existing Wit.ai app will not be impacted.  - application impacted, does not respond with intent anymore

APPID: 2338349596222319
curl \
 -H 'Authorization: Bearer XXXXXXXXXX' \
 'https://api.wit.ai/message?v=20200515&q=*phrase that used to work*'

now responds with 

{
  "text": "phrase that used to work",
  "intents": [],
  "entities": {},
  "traits": {}
}

Why is this happening? We have bots in production affected by this. What can we do?

**Comment by jtliao** [comment]
Can you give an example utterance that is no longer working? I've sent requests with utterances that you've trained your app with, and they're all showing up normally. 

You should be able to use versions before 20200513 to keep the old format.

**Comment by chatbotalex** [comment]
Lots of them appears as "Out of scope". Especially on cod-puk intent.
Example: "**care este codul puk al cartelei mele?**"

I'm using a version older than 14 May 2020.

**Comment by jtliao** [comment]
I see the issue now. Your app had validated samples with that intent with a span, but this is no longer a valid way to annotate samples, so they were not being used for training. I went ahead and re-validated them without the span, so this should work now.

Sorry about that.
