### ISSUE TITLE
Cant train new intents

### ISSUE THREAD

**Issue by silentninja** [wit-ai/wit#175]
I have been trying to train wit with a new intent.The ones i trained recently are not working properly in fact they are not even considered,they doesnt have confidence level shown when a new sentence is entered.

**Comment by anguyenhuy** [comment]
I've been having the same issue.  New utterances are being mis-labeled, and the changes I make to the intents won't get applied.

**Comment by szv** [comment]
Since ~1 day I also can't add new phrases to an instance.

**Comment by lanzalibre** [comment]
Same here

**Comment by oliviervaussy** [comment]
We had a small problem for some instance during the night, it should be fixed now.

**Comment by szv** [comment]
OK, thanks

**Comment by silentninja** [comment]
It is working now!!!!!!.Thanks wit team.

**Comment by lanzalibre** [comment]
Same thing is happening again. Intents cannot be stored of erased. Overall, I can notice that wit works much worse since the acquisition

**Comment by l5t** [comment]
https://github.com/wit-ai/wit/issues/183

**Comment by tobi418** [comment]
how long it takes to be trained (updated) when i entered new intent value or expressions? it is too slow
