### ISSUE TITLE
Entity's data is not available on new Wit.ai

### ISSUE THREAD

**Issue by vietdang7** [wit-ai/wit#1750]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
*bug*
**What is the current behavior?**
Entity's data that we have input now is not available on new Wit AI (they are still visible on the old version)
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Choose any entity, for example, ward_name entity, on the old version it will have 1000 keywords.
Switch to the new Wit AI, there are only 25 keywords on the same entity

**What is the expected behavior?**
All entity's data should be the same as on the old Wit AI

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
The app ID is: 159422038664557

**Comment by cesarve77** [comment]
Now I see, I need to create it. with the prefix wit$, 
Sorry to bother you, I'll close it

**Comment by dogcalas** [comment]
I have the same problem, when training, just a group of entity are showing up, when I have a lot more.

**Comment by cesarve77** [comment]
Now default entities does not exist in your entities by default, you need
to create one by one.

**Comment by patapizza** [comment]
Thanks for reporting, we'll look into it.

**Comment by denzils** [comment]
Similar to this, I can't access my entities from the parsed JSON returned result after the new change. The returned JSON result looks like the below snippet and I can't access "wit$datetime:datetime". As reported in the original bug, there should have been no changes to how you access wit.ai.


{text=Can we get lunch next Thursday, December 22nd at 1pm?, intents=[], traits={}, entities={wit$datetime:datetime=[{id=271360974002304, value=2022-12-22T13:00:00.000-05:00, name=wit$datetime, values=[{type=value, grain=hour, value=2022-12-22T13:00:00.000-05:00}], entities=[], confidence=1.0, type=value, start=36.0, end=66.0, role=datetime, grain=hour, body=Thursday, December 22nd at 1pm}]}}

**Comment by patapizza** [comment]
Fix is upcoming, should be resolved in a few hours.

@denzils Your issue is different, addressed in https://github.com/wit-ai/wit/issues/1760.

**Comment by vietdang7** [comment]
Thank you very much  patapizza!

> Fix is upcoming, should be resolved in a few hours.
> 
> @denzils Your issue is different, addressed in #1760.

**Comment by hasham7861** [comment]
I want to report a BUG

So in my nodejs code I check for keywords and meaning props within the entities object.

I notice this problem occurred on Friday May the 15th.

Currently, I am not seeing "keywords" and "meaning" props within the entities object.

App id is: 1569677726425516

**Comment by patapizza** [comment]
Original issue resolved, I believe @hasham7861's issue addressed by https://github.com/wit-ai/wit/issues/1760.
