### ISSUE TITLE
Letter change when edit a keyword with an Spanish accent on v2

### ISSUE THREAD

**Issue by dogcalas** [wit-ai/wit#1751]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a BUG

**What is the current behavior?**
On edit an entity's keyword  and change it by other with a Spanish accent, the word is incorrectly saved, and the accent letter is replaced by a _.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- Create a free-text & keyword entity
- Add a new keyword  (Urologia)
- Edit the keyword, by adding an Spanish accent (Urología)
![image](https://user-images.githubusercontent.com/2521769/82112945-8cc53d80-9717-11ea-89e5-312df2759446.png)

**What is the expected behavior?**
The keyword should change to the new word.
If you go to the V1 interface, you can see the accent is replaced by a _
![image](https://user-images.githubusercontent.com/2521769/82112967-c007cc80-9717-11ea-9a98-000fdc319bc3.png)

This bug is only happening on v2 when editing, you can add new keywords with accents without problems.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1538755029624526

**Comment by patapizza** [comment]
Sorry about that. We'll fix it.

**Comment by ruoyipu** [comment]
Hi, thanks for reporting! This should now be fixed. New keyword edits going forward should save accents appropriately.
