### ISSUE TITLE
Unable to export app data as .zip

### ISSUE THREAD

**Issue by qfavor** [wit-ai/wit#1753]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
I am unable to export the app data as .zip. Instead of getting the Download File dialog, I am getting an error inside the page: [object Object]

<img width="739" alt="image" src="https://user-images.githubusercontent.com/54986487/82126181-a1571380-97b3-11ea-883f-382db4341c75.png">

The functionality seems to be broken on the old UI as well. On the /v1 UI I am getting this message.
_Something went wrong while exporting your app 😔. Please try again, or contact us._

**Comment by patapizza** [comment]
Hi @qfavor,

What is your app ID?

**Comment by grapevineai** [comment]
We're having the same issue with private app ID: 1784861281563596

**Comment by qfavor** [comment]
I just tested now and it's fixed. Sorry for the delay!

**Comment by patapizza** [comment]
@grapevineai Thanks for reporting and sorry about that. Fix is under way, should be resolved in a few hours.

**Comment by rileyai-dev** [comment]
@patapizza Something very odd just happened... since v2 requires a facebook account, I just created an account (I didn't have one and won't use it except for WIT) and made me the owner of the WIT account. For some reasons, facebook disabled my account thinking it was a fake one. 

Now I m stuck and can't access this my WIT dashboard! Why v2 doesn't support Github? And who can urgently help for these issues?

**Comment by patapizza** [comment]
Hi @grapevineai,
Sorry about that. We're looking into it.

**Comment by rileyai-dev** [comment]
@patapizza Any news on that issue? I'm kinda stuck and can't really move with my project...

**Comment by rowe-morehouse** [comment]
✔︎ Bumping this up. Can't download .zip, so I'm afraid to version it. 

App ID: 852549758568236

**Comment by patapizza** [comment]
@rowe-morehouse I fixed it. 10 utterances were having an intent that has been deleted (fixing root cause), you might want to re-assign an intent (the ones who have `wit/greetings`).

@grapevineai Sorry for the latency, let me look for an update.

**Comment by rowe-morehouse** [comment]
heckin' awesome. Thank you! :)

**Comment by rileyai-dev** [comment]
@patapizza :cry:

**Comment by patapizza** [comment]
@grapevineai You'll need to request a review [here](https://www.facebook.com/help/103873106370583) and provide us with your case number. Thanks!

**Comment by patapizza** [comment]
Closing this one as original issue resolved. @grapevineai Please feel free to reopen an issue once you have the case number.

**Comment by rowe-morehouse** [comment]
copy gold leader.
