### ISSUE TITLE
Entities for /sentiment not available on the new UI

### ISSUE THREAD

**Issue by qfavor** [wit-ai/wit#1754]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
Even though I have trained my app using the /sentiment endpoint, on the old UI, through the functionality provided by the Inbox feature, nothing gets showcased in the new UI (though my entities seem to still be available in the old version):
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/54986487/82126341-c4ce8e00-97b4-11ea-80aa-a7963eb52e3f.png">

Is the /sentiment default entity deprecated now? I'm unable to find more info about how this is a Trait now.

App id: 2599960866722323

**Comment by patapizza** [comment]
Hi @qfavor,

`wit/sentiment` is now a trait:

<img width="427" alt="Screen Shot 2020-05-18 at 8 16 53 AM" src="https://user-images.githubusercontent.com/1015208/82229971-f1cb8f80-98df-11ea-99f3-340cdb882c28.png">

**Comment by qfavor** [comment]
Hello! I'm not seeing that when accessing 'Traits'. Do I need to re-add them or what's going on with /sentiment?
<img width="1660" alt="image" src="https://user-images.githubusercontent.com/54986487/82610312-cdfd9780-9bc6-11ea-90b5-334f7b038dbd.png">
