### ISSUE TITLE
STT HE

### ISSUE THREAD

**Issue by simcha1** [wit-ai/wit#1755]
Until recently the recognition of the Hebrew speech worked fine for me and suddenly now does not work
I understand it is beta but if it works well why not release it?

**Comment by jtliao** [comment]
Hi @simcha1, we deprecated Hebrew speech a few months ago -- unfortunately we can no longer support the models in the near future, we hope to be able to bring it back near the end of the year.

**Comment by simcha1** [comment]
Thank you
This is very important to us

**Comment by simcha1** [comment]
Have you already regained consciousness in a Hebrew speech?
