### ISSUE TITLE
Project not opening on wit v1

### ISSUE THREAD

**Issue by dogcalas** [wit-ai/wit#1756]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
Project not opening on wit v1

![image](https://user-images.githubusercontent.com/2521769/82143329-af834f00-9808-11ea-8390-0cf884ec3112.png)

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1538755029624526

**Comment by patapizza** [comment]
Thanks for reporting @dogcalas, we'll look into it.

**Comment by patapizza** [comment]
@dogcalas The previous UI expects all entities to have a role of the same name. This is now fixed by adding a `ciudad` role to the `ciudad` entity. We're figuring out how to best manage that. What were you looking for in the previous UI that is missing in the new one?
