### ISSUE TITLE
Facing problem while doing speech recognition using python client

### ISSUE THREAD

**Issue by allencarvallo** [wit-ai/wit#1757]
**CODE**

*from dotenv import load_dotenv*
*import os*
*from wit import Wit*

*load_dotenv()*
*access_token = os.getenv('SERVER_ACCESS_TOKEN')*
*client = Wit(access_token)*
*resp = None*
*with open('milk.wav', 'rb') as f:*
  *resp = client.speech(f, {'Content-Type': 'audio/wav'})*
*print()*
*print('Yay, got Wit.ai response: ' + str(resp))*
*print()*

**ERROR**

Traceback (most recent call last):
  File "speech.py", line 15, in <module>
    resp = client.speech(f, {'Content-Type': 'audio/wav'})
  File "C:\Users\Using Wit with python\venv\lib\site-packages\wit\wit.py", line 87, in speech
    resp = req(self.logger, self.access_token, 'POST', '/speech', params,
  File "C:\Users\Using Wit with python\venv\lib\site-packages\wit\wit.py", line 40, in req
    raise WitError('Wit responded with status: ' + str(rsp.status_code) +
wit.wit.WitError: Wit responded with status: 400 (Bad Request)

**Comment by jtliao** [comment]
Can you post in the GitHub issues for PyWit instead? https://github.com/wit-ai/pywit

In the meantime, I'd recommend trying to send a request with cURL directly, to verify that works.
