### ISSUE TITLE
Deprecated warning

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#1758]
Hi team,

After the recent wit.ai UI update we are getting the DEPRECATED warning for the input to wit.ai

{"_text":"3","entities":{"rating_values":[{"confidence":0.73179188591141,"value":"3","type":"value"}]},"WARNING":"DEPRECATED","msg_id":"1gJiZay8LM4ZvuIID"}

Will the update affect the existing APIS and the apps.

Thanks
Anjaly

**Comment by jtliao** [comment]
The existing APIs should remain the same. If you'd like to have the flag gone, change your version past 20200513 and your clients to handle the new response format.
