### ISSUE TITLE
Trait entities are no longer returned in the API response 

### ISSUE THREAD

**Issue by 91ns** [wit-ai/wit#1759]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
The API is returning all of the entities except the ones of type "trait"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

GET https://api.wit.ai/entities 

**What is the expected behavior?**

Retrieve all entities including traits 

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

700090590820295

**Comment by patapizza** [comment]
Hi,

As announced in the email, intents and traits are now first class citizens. Each of these building blocks have now their own set of APIs. Please check out the [latest HTTP API docs](https://wit.ai/docs/http/20200513).

Thanks!
