### ISSUE TITLE
Copying training set from one account to another?

### ISSUE THREAD

**Issue by eygssk** [wit-ai/wit#176]
Is there a means to copy training set of one account to another? If yes, please let me know [either front end (other than copying each and every statement)  / back end].

**Comment by Francis88** [comment]
Hi,
You can probably use create/update or remove expressions API to achieve what you want programmatically: https://wit.ai/docs/http/20141022#create-intent-expressions-link. You can also fork your instance into a new one. You can then delete an intent and all its expressions will move to the inbox where you can assign them to the new Intent. Hope it helps
