### ISSUE TITLE
After the switch to the new Wit UI, wit.ai entities data no longer accessible 

### ISSUE THREAD

**Issue by denzils** [wit-ai/wit#1760]
**Do you want to request a feature, report a bug, or ask a question about wit?**
bug

**What is the current behavior?**
After the switch to the new Wit.AI, the output of entity data is no longer usable or accessible. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I use to use the following code snippet:
var q = encodeURIComponent(searchString);
      var usertimezoneEncoded = encodeURIComponent(userTimeZone);
      var uri = 'https://api.wit.ai/message?q=' + q +"&context=%7B%22timezone%22%3A%22"+usertimezoneEncoded+"%22%7D";

      var auth = 'Bearer ' + CLIENT_TOKEN;
      var response = UrlFetchApp.fetch(uri, {headers: {Authorization: auth}});

      var json = response.getContentText();
      var data = JSON.parse(json);
      Logger.log("wit ai data:");
      Logger.log(data);
      Logger.log("experiment with access");
      Logger.log(data.entities.datetime);

      if(data.entities.duration) {
        Logger.log("has duration");
      }
      if(data.entities.datetime) {
        Logger.log("has datetime");
      }

There should have been no changes to how you access wit.ai. but now I can't access my entities from the parsed JSON returned result after the new change. The returned JSON result looks like the below snippet and I can't access "wit$datetime:datetime". 

data.entities.datetime returns null because the returned json is below:

{text=Can we get lunch next Thursday, December 22nd at 1pm?, intents=[], traits={}, entities={wit$datetime:datetime=[{id=271360974002304, value=2022-12-22T13:00:00.000-05:00, name=wit$datetime, values=[{type=value, grain=hour, value=2022-12-22T13:00:00.000-05:00}], entities=[], confidence=1.0, type=value, start=36.0, end=66.0, role=datetime, grain=hour, body=Thursday, December 22nd at 1pm}]}}

**What is the expected behavior?**
All entity's data should be the same as on the old Wit AI
Previously, I was accessing it by doing 
`data.entities.datetime`

If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.
The app ID is: 234591714616138

**Comment by pokryva** [comment]
I, too, seem to have similar problem. I **haven't yet switched** to the new wit.ai (v2), but API responses seem to be... different.

For instance - I should expect _confidence_ in:

`entities.intent[0].confidence`

but now it seems to be sitting in

`intents[0].confidence`

Also accessing entities changed:

old (good): `entities.XXX[0].value`
new (bad) `entities.XXX:XXX[0].value`

XXX is entity

App ID: 2666741980018303

**Comment by patapizza** [comment]
Hi,

We released a new API version on 5/13 (`20200513`). Please update your code to use the latest format [doc here](https://wit.ai/docs/http/20200513#get__message_link). If you need more time, provide a previous API version as parameter (e.g. `v=20200512`).

From the [documentation](https://wit.ai/docs/http/20200513#api_versioning_link):
> As of June 1st, 2014, requests that do not include a version parameter will hit the latest version of our API.

Thanks!

**Comment by patapizza** [comment]
>  I can't access "wit$datetime:datetime"

Why do you mean? Instead of `entities.datetime`, try `entities['wit$datetime:datetime']`.

**Comment by denzils** [comment]
Yes you're right, I did not know the documentation for the API had changed on 5/13. I will now either have to update all my code to work with this new format or use with with the old API version referenced or not use wit. Thanks for the quick response - I appreciate it!

**Comment by hasham7861** [comment]
Thank you @patapizza adding v=20200512 as one of the query param helped get things back to normal 👍

**Comment by patapizza** [comment]
Sure thing - make sure to upgrade to `20200513` at your earliest convenience though. :-)

**Comment by pokryva** [comment]
Guys, so what's the most natural way to follow wit.ai API updates?

**Comment by kingseaeast** [comment]
Hi @pokryva, in the future we will make better communication on our API updates, especially on breaking changes. Meanwhile, using versioned API call will ensure that stability our your end.
