### ISSUE TITLE
Entity 'wit$greetings'  or 'wit$bye' not found for Spanish

### ISSUE THREAD

**Issue by cesarve77** [wit-ai/wit#1761]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
```
  $ curl -XPOST 'https://api.wit.ai/entities?v=20200513' \
  -H "Authorization: Bearer $TOKEN" \
  -H "Content-Type: application/json" \
  -d '{"name":"wit$greetings",
       "roles":[]}'
```
I got
```
 { error: "Entity 'wit$greetings' not found", code: 'not-found' }
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

  $ curl -XPOST 'https://api.wit.ai/apps?v=20200513' \
  -H "Authorization: Bearer $TOKEN" \
  -H "Content-Type: application/json" \
  -d '{"name": "My_New_App",
       "lang": "es",
       "private": false,
       "timezone": "Europe/Brussels"}'

  $ curl -XPOST 'https://api.wit.ai/entities?v=20200513' \
  -H "Authorization: Bearer $TOKEN" \
  -H "Content-Type: application/json" \
  -d '{"name":"wit$greetings",
       "roles":[]}'

**What is the expected behavior?**

Pre-build entity has been created
```
  {
    "id": "5418abc7-cc68-4073-ae9e-3a5c3c81d965",
    "name": "wit$greetings",
    "roles": ["greetings"],
    "lookups": ["free-text", "keywords"],
    "keywords": []
  }
```

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by jtliao** [comment]
Hi @cesarve77, the "greetings" and "bye" built-in entities are not available in Spanish.
