### ISSUE TITLE
Training in new interface

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#1762]
HI team,

Where am I able to train new inputs. My train button seems disabled.

![image](https://user-images.githubusercontent.com/601711/82293118-adb4b980-99c9-11ea-886c-5c5ac0185f04.png)

**Comment by 51100807** [comment]
i think, wit need intent to validate

**Comment by anjaly** [comment]
That means we need an intent for all inputs to train.
Can't we train an input only with entities?

**Comment by jtliao** [comment]
Utterances now need an intent for validation. As a workaround, you can use some kind of dummy intent for these.
