### ISSUE TITLE
Entities are case sensitive in preview version

### ISSUE THREAD

**Issue by Pixel-Edwin** [wit-ai/wit#1763]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
The new interface detects entities correctly. But when a entity is stored lowercase and the detected entity has a capital letter you will get an error when validating.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Add an entity `test` and write an utterance like 'This is a Test'. Then press Train and Validate and you will get an error.

**What is the expected behavior?**
Detect the entities as they are stored, case insensitive.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
165102864902045

**Comment by jtliao** [comment]
Looking into this

**Comment by jtliao** [comment]
This should be fixed now, thanks for raising and apologies for the inconvenience.
