### ISSUE TITLE
Wit AI demo app is not responding to any command

### ISSUE THREAD

**Issue by pavinduLakshan** [wit-ai/wit#1766]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
I'm a complete beginner to Wit. I tried using the [sample app](https://labs.wit.ai/demo/index.html) to get an idea. However, even for the suggested commands such as `turn on the tv`, `Tell me the weather in las wagas`,  It's only response on the screen as follows.
```
text = turn on the tv
intent = no intent
```
Then the following message is displayed on the bottom right.

> Your intent is default_intent but I have not been trained to do that...

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Go to the sample app [here](https://labs.wit.ai/demo/index.html) and give a voice command.

**What is the expected behavior?**
It should respond to the voice commands and should do the expected actions in the house image.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
No app Id is required

**Comment by patapizza** [comment]
Thanks for reporting, we'll look into this.

**Comment by jtliao** [comment]
This should be fixed now.
