### ISSUE TITLE
How to teach wit to recognize all names without explicitly mentioning them

### ISSUE THREAD

**Issue by dsokac** [wit-ai/wit#1767]
There is one issue that troubles me. I use wit.ai with Croatian locale. We have one use case that requires to detect name and/or surname of a person. I have read online that I can use entity (free text & keyword) and create keywords "XYZ" and "a b c d e f g h i j k" and train with such keywords so wit learns where the name should appear. I did that but it does not seem to work. I wonder if anyone could clarify this or elaborate how does wit.ai understands where the real name is based on keywords I created? Thank you in advance.

Exampe of training phrase: Who is Xyz?, Who is Xyz? Who is a b c d e f g h i j k? etc.

Example of test phrase: Who is Philip? (in real testing, I use croatian names)

Edit: I must add that we taught wit.ai some names because we stored them as keywords and afterwards we deleted them - may this be causing problems? Can wit forget about them?

App ID: 2551588624865480

**Comment by wangsnowyin11** [comment]
Have you try 'wit/contact', that could be useful; otherwise you need to train a custom entity with free-text/keywords

Names are not treated any differently from other text, so if you delete those trained names, wit will forget them

**Comment by wangsnowyin11** [comment]
close by no followup questions
