### ISSUE TITLE
Issues with trained data after update

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#1769]
Hi team,

We are facing some issues after the latest update.
When trying to create a new app by downloading the existing app it shows error.
But the new app is created. While checking, the new app is missing trained values. The intent name is there but the examples trained are not there, so those examples were not working and we had trained all those in the new app. 
Today when we tried the same commands in the existing (old) app it was working. So we tried to create a new app from the existing one, then only we could find the issue. Below was the error on creating the app and it also missed the trained examples.
The appid of the new app that we created today is 1360309894152135
The appid of the existing app that we created today is 1530202523770626

![image](https://user-images.githubusercontent.com/601711/82511141-22066e80-9b2a-11ea-9ea5-96d8546b0d8c.png)

**Comment by anjaly** [comment]
Hi team,

Any update please.

Thanks
Anjaly

**Comment by jtliao** [comment]
I don't totally follow. You're saying that after importing the original app (1530202523770626), the newly created app (1360309894152135) is missing training data?

**Comment by anjaly** [comment]
> I don't totally follow. You're saying that after importing the original app (1530202523770626), the newly created app (1360309894152135) is missing training data?

yes. Examples are missing for some intents.
And also pleaase help in understanding the error occurred in creating app using downloaded data.

**Comment by jtliao** [comment]
This should work now.
