### ISSUE TITLE
No entity value metadata in parsed response

### ISSUE THREAD

**Issue by jodem** [wit-ai/wit#177]
Hi guys,

I am face a little issue. I created entities with metadata (customer name and id).

When I perform a vocal query, the api does find the customer name, but in the response I have only the entity value and not it's value's metadata as it's described in the doc. Any way to have the metadata associated to the entities value in the api response?

``` json

{
  "msg_id": "d5898211-8762-43e8-bffc-13a75bec2a9f",
  "_text": "turnover for smith",
  "outcomes": [
    {
      "_text": "turnover for smith",
      "intent": "kpi",
      "entities": {
        "indicator": [
          {
            "value": "turnover"
          }
        ],
        "data_customer": [
          {
            "value": "smith" <= expected metadata in addition to value
          }
        ]
      },
      "confidence": 0.586
    }
  ]
}

```

**Comment by Francis88** [comment]
Hey jodem, thanks for reporting. This is indeed a regression and we will fix it asap. Will update you when fixed. Sorry for the inconvenience.

**Comment by jodem** [comment]
No problem, thanks for fixing guys.

**Comment by l5t** [comment]
Hi jodem, it should be fixed now. Please confirm and close.
`{
  "msg_id" : "56fecc97-9645-4da7-866f-0e99d17003f8",
  "_text" : "turn off the light in the kitchen",
  "outcomes" : [ {
    "_text" : "turn off the light in the kitchen",
    "intent" : "turnon",
    "entities" : {
      "room" : [ {
        "value" : "kitchen",
        "metadata" : "id=23"
      } ]
    },
    "confidence" : 0.548
  } ]
}`

**Comment by jodem** [comment]
It is ! thanks guys, greetings from Paris.
