### ISSUE TITLE
Not able to train

### ISSUE THREAD

**Issue by GauravDobhal** [wit-ai/wit#1770]
Clicking on 'Train and Validate' after adding an utterance is not doing anything. It seems stuck.Anyone else facing the same?
My app id is: 1757528077591583

**Comment by jtliao** [comment]
Can you give an example of the utterance you're trying to validate?

**Comment by dogcalas** [comment]
Same problem, training is failing on some utterances.

**Comment by dogcalas** [comment]
My app is stuck in training, how can I stop it? 
ID: 1538755029624526

**Comment by jtliao** [comment]
this should be fixed now
