### ISSUE TITLE
Utterances list empty in preview version

### ISSUE THREAD

**Issue by Pixel-Edwin** [wit-ai/wit#1772]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
The Utterances list is empty in the new interface. When I open the console I see that the request get an errorcode 500.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
On our application open the Utterances list in the new interface.

**What is the expected behavior?**
Show a list with all the utterances.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
165102864902045

**Comment by wangsnowyin11** [comment]
Thanks for reporting the issue! 

Pagination is somehow not working properly. investigating now, wondering how many utterances do you have roughly?

**Comment by Pixel-Edwin** [comment]
I think about 5k or more.

**Comment by wangsnowyin11** [comment]
We've found the reason, and we are now actively working on fixing it. Thanks for your patience and sorry for the inconvenience!

**Comment by patapizza** [comment]
We should be good to go!

**Comment by wangsnowyin11** [comment]
Hey we've fixed the issue, could you try again? Let us know if there are anything else wrong.

Thanks for your patience!

**Comment by Pixel-Edwin** [comment]
It seems to be working well now. Thank you very much!
