### ISSUE TITLE
Command from Settings HTTP API not working

### ISSUE THREAD

**Issue by J4DR3** [wit-ai/wit#1773]
When I copy the command:
curl \
 -H 'Authorization: Bearer ***' \
 'https://api.wit.ai/message?v=20******&q=hi'
from settings my terminal is returning the following error:
curl: (6) Could not resolve host: \
and:
'-H' is not recognized as an internal or external command,
operable program or batch file.
I've tried cmd and PowerShell, no luck.

**Comment by jtliao** [comment]
are you sure you're pasting the command correctly in one line? based on the error, it looks like `curl` is being executed as one line, and `-H 'Authorization: Bearer ...'
'https://api.wit.ai/message?v=20******&q=hi'` is being executed separately

**Comment by J4DR3** [comment]
I was pasting it correctly, it turned out to be a Linux native command and it works fine on my ubuntu subsystem. I think that windows support would be great, to have an option to choose from Linux and Windows command from the wit.ai settings page.

**Comment by KartikChugh** [comment]
You can get curl on Windows though.
