### ISSUE TITLE
create a new application using the http API

### ISSUE THREAD

**Issue by wapify** [wit-ai/wit#1775]
I cannot create a new application using the http API.
Also, in the console panel it is not showing the client token acces

**Comment by jtliao** [comment]
Can you please provide more information so we can help debug? What is the request you're making, what is the response, etc.

**Comment by patapizza** [comment]
Just in case, here's the [API reference](https://wit.ai/docs/http/20200513#post__apps_link).

**Comment by patapizza** [comment]
Closing by inactivity.
