### ISSUE TITLE
Can not remove or validate messages included icons

### ISSUE THREAD

**Issue by hungnv-upstart** [wit-ai/wit#1776]
<img width="975" alt="Screen Shot 2020-05-28 at 00 38 30" src="https://user-images.githubusercontent.com/49332965/83053983-d862da00-a07b-11ea-9117-44bb562f022b.png">

**Comment by KartikChugh** [comment]
I think you should provide some more information. Do neither of the buttons let you click them? Or does clicking them not do anything?

**Comment by hungnv-upstart** [comment]
- Click to ignore button at the end of row.
Error: Nothing happen, row is not removed.
Expect: row is removed by ignore

**Comment by hungnv-upstart** [comment]
Consider this request: https://graph.wit.ai/293150315416909/samples?access_token=SIFEISZBW7FFCMZM53HY5BKQOJFJP3E6
<img width="1434" alt="Screen Shot 2020-05-29 at 11 24 25" src="https://user-images.githubusercontent.com/49332965/83221103-186ead80-a19f-11ea-9b3d-e39fa05a5c78.png">

**Comment by jtliao** [comment]
We're looking into the problem -- I'm deleting your latest comment, since you exposed your access token. You should never share that.

**Comment by jtliao** [comment]
@hungnv-upstart can you try again?

**Comment by hungnv-upstart** [comment]
> @hungnv-upstart can you try again?

Yep, it's fixed.
