### ISSUE TITLE
Can't find/veiw my utterances anymore

### ISSUE THREAD

**Issue by JayantDevkar** [wit-ai/wit#1778]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

While I was browsing through my utterances and all of a sudden screen went all white and then when I refreshed the page, I cannot see my utterances anymore. Even when I search and then I tried adding one more utterance it did not appear under the utterance tab

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

336080517369021

**Comment by jtliao** [comment]
Hi @JayantDevkar, there was a bug where deleting a trait didn't delete the utterance entities, so the utterance tab failed. I've manually fixed your app, and we'll have a actual fix upcoming. Thanks for flagging this issue.

**Comment by KartikChugh** [comment]
Requesting manual fix - App ID 612318139492773

**Comment by JayantDevkar** [comment]
Thank you, appreciate it!

**Comment by JayantDevkar** [comment]
> Hi @JayantDevkar, there was a bug where deleting a trait didn't delete the utterance entities, so the utterance tab failed. I've manually fixed your app, and we'll have a actual fix upcoming. Thanks for flagging this issue.

Thanks!
