### ISSUE TITLE
No entities values

### ISSUE THREAD

**Issue by brendonco** [wit-ai/wit#178]
Hi,

I created an intent and entities on wit but the response only return the intent but no entities.
```
 mic.onresult = function (intent, entities) {
        var r = kv("intent", intent);

        for (var k in entities) {
          var e = entities[k];

          if (!(e instanceof Array)) {
            r += kv(k, e.value);
          } else {
            for (var i = 0; i < e.length; i++) {
              r += kv(k, e[i].value);
            }
          }
        }

        document.getElementById("result").innerHTML = r;
      };
```

**Comment by l5t** [comment]
Hello,
I just tried and it works with my Wit instance. I checked your instance and you don't have any entity in your intents. You will need to train Wit to recognize entities first.

**Comment by brendonco** [comment]
ok let me try it out and add the entities. but this could be weird if I have a lot of entities to use. overkill for developer to add the entities. :) rather than concentrate on building the app.
