### ISSUE TITLE
How to upload a big number of seperate utternaces at once?

### ISSUE THREAD

**Issue by J4DR3** [wit-ai/wit#1780]
I have a completed DB that I want to upload to wit, it contains many different sentences that I want to submit to my app as a different utterance each.
The DB is a .txt format, as for now I and my team are copy and pasting each sentence and it takes way too long. Thanks

**Comment by jtliao** [comment]
Use `POST /utterances` (https://wit.ai/docs/http/20200513#post__utterances_link) to send the utterances from your DB to your Wit app.
