### ISSUE TITLE
Can't retrieve utterances from API

### ISSUE THREAD

**Issue by KartikChugh** [wit-ai/wit#1781]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
Using curl to get the meaning of a message works, but trying to retrieve a list of utterances fails.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
```
TOKEN=<token>
curl -XGET 'https://api.wit.ai/utterances?v=20200513&limit=10' \
  -H "Authorization: Bearer $TOKEN"

{"error":"Entity '1691425094342133' not found","code":"not-found"}%  
```

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
668509230657967

**Comment by jtliao** [comment]
Hey @KartikChugh, sorry for the delay here -- is this still an issue? I can't seem to reproduce it.

**Comment by KartikChugh** [comment]
I'm guessing it has to do with #1778 , as my app began bugging as described in that issue, and then I noticed this problem too. I "fixed" it by making a new app.
