### ISSUE TITLE
windows cmd error

### ISSUE THREAD

**Issue by RahulDoddihal** [wit-ai/wit#1782]
C:\>curl \
curl: (6) Could not resolve host: \

C:\> -H 'Authorization: Bearer token' \
'-H' is not recognized as an internal or external command,
operable program or batch file.

This error is arising while copying HTTP API.

**Comment by jtliao** [comment]
Can you try removing the `\`? If you look at the output, it's currently being parsed as two separate lines.

**Comment by RahulDoddihal** [comment]
C:\>curl -H 'Authorization: Bearer ***'
curl: (6) Could not resolve host: Bearer
curl: (6) Could not resolve host: ***'

No sir ,not working still

**Comment by jtliao** [comment]
You're not adding a host to curl, all you're inputting is the token. You need to input the URL you're trying to curl.

**Comment by RahulDoddihal** [comment]
Could you please help me with the code.
I'm trying but not able to do that operation.

**Comment by jtliao** [comment]
What are you trying to do?

**Comment by RahulDoddihal** [comment]
Developing AI app on wit.ai 
Testing my code on cmd using curl but showing error.

**Comment by jtliao** [comment]
Yes, but what are you trying to curl? curl needs a URL to send the request to, and the URL is based on what you are trying to do (message, create app, create entity, etc.). Without knowing that, I'm not sure how to help.

**Comment by RahulDoddihal** [comment]
Means if I type Http API from settings from wit.ai in cmd then cmd should give some response .

**Comment by jtliao** [comment]
If you look at the curl example from the settings tab, you'll see that there is a URL

`curl -H 'Authorization: Bearer $TOKEN' 'https://api.wit.ai/message?v=20200529&q=test'`

You have no URL in your curl request, which is why it's not doing anything.

**Comment by RahulDoddihal** [comment]
Then how to add URL to curl ?

**Comment by jtliao** [comment]
I just gave the example above. Copy and paste that with your token and whatever query you want to use.
