### ISSUE TITLE
can't add contributors

### ISSUE THREAD

**Issue by rowe-morehouse** [wit-ai/wit#1783]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

bug

**What is the current behavior?**

can't add contributors

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

The autosuggest is not working for me when I enter an FB username. Also, pasting in an email does not seem to work. No button for submit, no confirmation that anything happened, no email invite or other invite sent to collaborator.

Mac OS 10.13.6
Version 85.0.4158.5 (Official Build) canary (64-bit)

**What is the expected behavior?**

Autosuggest should find the FB username and allow me to add them as contributor, and offer some type of confirmation that a contributor has been invited.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

852549758568236

**Comment by aforaleka** [comment]
Hi @rowe-morehouse, thanks for reporting. The invite feature doesn't support email yet, can you share the user name you're trying to invite so we can try to repro? 

But in the meantime, you can switch to the old UX to invite the contributor.

**Comment by rowe-morehouse** [comment]
Hi there, using the old UX (v1) did not work. 

… it accepted the email, and emailed him, but the clickthrough gave a blank screen. He navigated to v2 from there, and got "app does not exist message"

trying to invite:

treenguyen1995

also tried his numerical ID on v1 and v2 with no success:

3340553232623602

**Comment by aforaleka** [comment]
Hey @rowe-morehouse, based on the ID you provided, his actual Wit username should be "tringuyen". Can you try using that username to invite him? (Wit username can be found in the top right corner after login.) Let me know if this solves your issue!

And regarding the email link leading to a blank screen, that is unexpected. If you can provide the url he clicked on so we can look into the issue further that'd be great. Thank you!

**Comment by rowe-morehouse** [comment]
Yes, it worked with the username you provided, thank you.

**Comment by rowe-morehouse** [comment]
Hello, still unclear on how to discover a facebook user's Wit username?

For example, I want to invite a new user: cynwong12

what is her Wit username? Does she have to do anything before she gets a Wit username?

how do I find her Wit username?

I think this could be made more clear in the documentation and the interface. If email address is not usable for adding Wit contributors in Wit V2 then this should be clarified as well. 

Thank you.

**Comment by patapizza** [comment]
Hi @rowe-morehouse,

She would need to create a Wit account and share her username with you (found on the right corner after login). I realize this isn't optimal for new users, I'll make a note.

Hope this helps.

**Comment by rowe-morehouse** [comment]
Thank you Julien. As I'm working with the app, I'm making an ongoing list of issues and confusing matters encountered as a new user. After I finalize the list I'll reach out to determine the best way of submitting to the maintainers. cheers.
