### ISSUE TITLE
Wit number is not working

### ISSUE THREAD

**Issue by homelander03** [wit-ai/wit#1784]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
When I type **properties below 10 lakhs**, 10 lakhs is getting identified as wit/number:lk.
But When I type **properties above 10 lakhs**, 10 lakhs is not getting identified at all.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. In the understanding type **properties below 10 lakhs**, check detected entities.
2. Now type **properties above 10 lakhs**, check detected entities.
**What is the expected behavior?**
It should work as same for both
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
APPID: 2529044864091611

**Comment by homelander03** [comment]
The same issue is happening with all my apps.

**Comment by 51100807** [comment]
The same issue is happening with all my apps.
When I type **2 adults**, 2 adults is getting identified as wit/number:adult. But wit understand wit/number:price. 
My appid: 1778316165603240

**Comment by kingseaeast** [comment]
Thanks for reporting! We'll continue to improve the quality of our built-ins entities but it will be hard to guarantee they work 100% of the time due to the probabilistic nature. Meanwhile, the best short term solution is to label and train your own custom entities.

**Comment by patapizza** [comment]
We're looking into it: https://github.com/wit-ai/wit/issues/1786.
