### ISSUE TITLE
Trying to save a version returns server error (500)

### ISSUE THREAD

**Issue by klemensz** [wit-ai/wit#1785]
**Bug**

**What is the current behavior?**

Trying to save a version under "Versioning" of the app results in a server error 500.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

* Go to Settings > Versioning, and enter "v2_prod"
* Click save
* It shows a hint on the button, saying that it's saving
* After half a minute or so, it jumps back, nothing is saved

In the browser's developer console under network requests I can see that the sync request returns `{"error":{"code":1,"message":"An unknown error occurred"}}`. 

Data that is sent: `[{"data":{"tag":"v2_prod"},"type":"created_snapshot"}]`

**What is the expected behavior?**

It should save the version.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

590c3891-b23b-4cb4-b5a2-c3cd0ef17397

**Comment by kingseaeast** [comment]
Thanks for reporting @klemensz ! We'll look into it.

**Comment by kingseaeast** [comment]
@klemensz Does it repro consistently for you?

**Comment by FengyangZhang** [comment]
Hi @klemensz, some of the parsers in the domain have too many values so the versioning process failed. I've manually created the version "v2_prod" for the app. Let us know if it doesn't work.

**Comment by klemensz** [comment]
Thanks. I've got another app (5902737c-e922-4695-bed3-874f70abb502) that is very similar (just a different language version) to this one and for which I want to create a version too. So it won't work there as well?

**Comment by FengyangZhang** [comment]
We've pushed some changes so it should work, can you give it a try?

**Comment by klemensz** [comment]
I tried it, but it still returns the same error (status 500 after 30 seconds).

**Comment by FengyangZhang** [comment]
thanks for confirming, we're looking into it.

**Comment by FengyangZhang** [comment]
sorry for the delay. It's just because the app is big and it takes around a minute to save a version, so server returned 500 after certain time. I've created one manually for the app for now. We'll see if we can support this better.
