### ISSUE TITLE
Error when adding a new synonym 

### ISSUE THREAD

**Issue by serdalbayram** [wit-ai/wit#1789]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
When adding a new synonym to a keyword, it displays "Something went wrong. We've been notified"
custom entity name is "language"  (ID: 2556476351235169)
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
For language entity: https://wit.ai/v2/apps/1622020321212473/management/entities/2556476351235169
I cant add any synonym.

**What is the expected behavior?**
New synonym should be added.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1622020321212473

![synonym](https://user-images.githubusercontent.com/25345380/83488258-339a2f80-a4b5-11ea-9e1c-25629470a260.png)

**Comment by jtliao** [comment]
We're looking into it.

**Comment by jtliao** [comment]
This should be fixed now. Thanks for your patience.
