### ISSUE TITLE
Define a constraint between two datetime entities

### ISSUE THREAD

**Issue by zigzago** [wit-ai/wit#179]
My use case :

en : "I leave on July 10, I go back two days later"
fr : "Je pars le 10 juillet, je reviens deux jours après"

outwardDate : July 10
inwardDate : (July 12) or (today + 2 days) ? -> wit.ai returns today + 2 days

If we can define a relation like "inwardDate depends on outwardDate", then inwardDate would be parsed with outwardDate parsing result as context date, and all would be fine :)

**Comment by l5t** [comment]
So sorry for the late reply... this is indeed a great enhancement for Duckling. I moved it here to keep track of it:https://github.com/wit-ai/duckling/issues/90
