### ISSUE TITLE
Wit app has stopped learning new things

### ISSUE THREAD

**Issue by KrzysiekVRT** [wit-ai/wit#1790]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
My Wit app has stopped learning new things. Everything works good until last friday, but since then it seems like app is stuck. 
I'm trying to teach my app new things in "Understanding" tab - I type new utterance and click "Train and validate" button, then "The utterance is now in training queue" message shows, but it looks like it isn't true. App status is not changing and still says "Training complete. All your changes have been taken into account. Your app last trained on 29.05", but 29.05 was 4 days ago. 
I tried to wait few hours and I tried with few different utterances but still nothing happens and app is not learning.

**What is the expected behavior?**
App should learn new things.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
672413893610053

**Comment by jtliao** [comment]
Sorry about that -- the training was stuck for a bit. It should be back to normal now.
