### ISSUE TITLE
Node-wit not returning Sub-Entities

### ISSUE THREAD

**Issue by alextford11** [wit-ai/wit#1791]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

bug

**What is the current behaviour?**

node-wit is not returning any sub-entities. curl works fine like how it should.

**If the current behaviour is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

My app is trained to return a string like "Change background to Blue" to:

- Change background (entity)
   - background (sub-entity)
- to Blue (entity)
   - Blue (sub-entity)

but node-wit only returns this:

- Change background (entity)
- to Blue (entity)

**What is the expected behaviour?**

above

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

180644303313007

**Comment by patapizza** [comment]
Please redirect `node-wit` issues to the relevant project: https://github.com/wit-ai/node-wit. Thanks!
