### ISSUE TITLE
Issue in trained data on creating nw app from existing app

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#1792]
Hi team,

We have an app with with appId:1530202523770626.
We had exported the data and created a new app from it with appId:274175030436010.
In the new app some training examples in 1530202523770626 are missing.

For Exampe, trained expressionn "whatsapp prospectus" is missing in  appId:274175030436010.
**In appId:1530202523770626  "whatsapp prospectus" returns the below data**
{
  "text": "whatsapp prospectus",
  "intents": [
    {
      "id": "534478210757302",
      "name": "get_sales_brochure",
      "confidence": 0.9942
    }
  ],
  "entities": {
    "products:products": [
      {
        "id": "c9218088-2e24-4129-9744-3a038d1996f0",
        "name": "products",
        "role": "products",
        "start": 0,
        "end": 8,
        "body": "whatsapp",
        "confidence": 0.9619,
        "entities": [],
        "value": "WhatsApp enteprise Access",
        "type": "value"
      }
    ]
  },
  "traits": {}
}

**But in appId:274175030436010, it returns the below data**

{
  "text": "whatsapp prospectus",
  "intents": [
    {
      "id": "617956412144071",
      "name": "get_sales_brochure",
      "confidence": 0.9726
    }
  ],
  "entities": {
    "products:products": [
      {
        "id": "2635071156762216",
        "name": "products",
        "role": "products",
        "start": 0,
        "end": 19,
        "body": "whatsapp prospectus",
        "confidence": 0.575,
        "entities": [],
        "suggested": true,
        "value": "whatsapp prospectus",
        "type": "value"
      }
    ]
  },
  "traits": {}
}

Why is such a mismatch in the apps with same data. How can we trust the new app? 
How will we able to know what all datas are lost.

Thanks
Anjaly

**Comment by patapizza** [comment]
Thanks for reporting, we'll look into it.

**Comment by anjaly** [comment]
@patapizza Thanks for considering. Please let us know once the issue is getting fixed.
And also please let us know if the old apps will get affected by this update because we want to know if we need to update all our existing apps.
Will the newly created apps work with the old api?

**Comment by patapizza** [comment]
Will do.
When you export an app, it doesn't affect its data.
Not sure I understand. All apps use the same API.

**Comment by patapizza** [comment]
Hey @anjaly,

I've exported your app and re-imported back. I could see the `whatsapp prospectus` utterance, with proper prediction.
Can you try exporting and re-importing again to see if it resolves the issue?

Thanks.
