### ISSUE TITLE
API calls create double entries in Entities list

### ISSUE THREAD

**Issue by yvaskovski** [wit-ai/wit#1794]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

bug

**What is the current behavior?**

When API is used to feed data to Wit.ai, all recognized keywords are double-created into the same entity as separate entries, even though they are listed as synonyms to an existing entry. So, the returned value of an entity matches the newly created entry, even though it is supposed to have the value of the main entry, under which the keyword (synonym) is listed. This issue doesn't happen when you feed data to Wit.ai through Wit.ai console (Understanding).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Use API.

**What is the expected behavior?**

The returned value of an entity entry should be the one listed for the main entry.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

2791749641047194

![Screenshot_4](https://user-images.githubusercontent.com/58780400/83817869-88fd5900-a6ce-11ea-86fc-2e69b73ba04b.png)

**Comment by patapizza** [comment]
Hi @yvaskovski,

Good catch.
The `keywords` strategy looks for both the keyword and the synonyms. `keyword` would be the canonical value you're looking for, while all the synonyms AND the keyword would be searched for.
Whether the keyword has its own value as synonym doesn't change anything in the entity behavior.
So to make this explicit, we usually add it the keyword itself as synonym upon creation. It seems it isn't the case for Understanding, which we need to update to maintain consistency.

It results that having synonyms whose value is the same as other keywords would fail (we wouldn't know which keyword should be returned). Please don't do this.

Hope this helps.

**Comment by yvaskovski** [comment]
Hi @patapizza,

Thanks for explanation. So, just to clarify, you suggest to remove the keyword value from the synonyms?

Also, the biggest issue with this matter for me right now, is that when I query API supplying "get rid of", the expected return value is "remove", as "get rid of" is a synonym for "remove", while in reality API returns "get rid of" as a value for the found entity, because Wit.ai creates a new keyword entry to the same entity. 

Also, it looks like I wasn't clear enough, first 4 entries on my screenshot were created by the system itself when I made some queries, I didn't create those myself.

**Comment by yvaskovski** [comment]
@patapizza, I just tried removing keyword values from synonyms, and API calls still add a new keyword entry of a synonym to the entity.

**Comment by patapizza** [comment]
Oh, thanks for the clarification. This is a bug.

**Comment by yvaskovski** [comment]
Hi again @patapizza,

Also just noticed, wanted to clarify; entities - are they case-sensitive? It looks like "Remove" is different from "remove", which doesn't recognize entity.

**update to this comment:**
So, it looks like there is a bug here as well, and it looks like it is a bug with just this one given entity. Here are my thoughts:
1) the bug above, that we have already discussed
2) "Remove" is considered different from "remove" and doesn't get recognized by the system.
3) "replace" and "Replace" are the same for the system, so both get recognized
4) nothing like this happens for any other entity I have in the system

**Comment by rafaeldepablo** [comment]
I am experiencing the same issue using the API to train an app, unwanted "keyboard" are created.

Perhaps an approach to solve this problem would be include in the "value" field in in "POST/ utterances", so you can specify what is the corresponding keyboard.

Right now, when you use "GET/ message" you are getting the "value" field, so it should make sense, during the training, sent the value.

In addition, that information could be use to autocomplete the synonyms field for the entity

Thanks

**Comment by dsokac** [comment]
Can you please speed the solution up? This will potentially create alot more work and troubles than it should have... i was so dumb to switch to preview view -.-

**Comment by patapizza** [comment]
Sorry for the latency here. We'll fix this.

**Comment by patapizza** [comment]
Alright, fix is upcoming. Synonyms should be case-insensitive.

**Comment by patapizza** [comment]
This should not be fixed!

**Comment by dsokac** [comment]
Are you going to explain????? You cannot do this like you are doing some school team project... You should elaborate your decision so we all can decide if it is required or not. :)

**Comment by yvaskovski** [comment]
Hi @patapizza,

I have tried what I have described before again and the same problem is still there. I have recorded a video of reproducing a problem i have described above (it's 1m42s long). 

https://drive.google.com/file/d/1HXWY_XZ8V-QHHRwFeH1ICv9GZ6Z1dL35/view

Here is what I do on this video:

1) i show my entities page, where there is three main entities with different synonyms, while I'm deleting an entry that is a synonym to an already existing entry.

2) i show my understanding panel where all api calls fall

3) using third party software i make an api call to wit.ai to return the JSON data on "no pickles" string.

4) based on the JSON result, "no" was properly classified as a synonym of "remove"

5) The "no pickles" utterance appears in the understanding panel where all resolved value are correct and I press "train" button

6) after i validated that utterance, synonym "no" appears as a separate entry with its own value to the entity it already belongs to (and was recognized before) as a synonym to a different value. 

7) which in sequence, create a different problem, so that when I send api request that contains "no" in its string, it will now be recognized as its own entry rather than a synonym.

--------------------------------------------------------

I also think that this whole problem occured after Wit.ai has changed its everything a few weeks ago and my thinking is that if I recreate the same entity from the scratch and retrain all utterances to the new one, the problem should go away. Does it mean I would have to go back to each query I've used and resync them again, or Wit.ai will train itself to understand that?

**Comment by dsokac** [comment]
@yvaskovski, I got the impression that they do not want to fix this for some unknown reason. They just threw it away without explanation. I guess they think it is not important, but it is.

**Comment by yvaskovski** [comment]
Hi @patapizza, 

I have tried recreating the same entity from the scratch and retraining all utterances I already had. The problem didn't go away, as soon as I validate a live feed utterance, the system creates a new entry to the entity, where a keyword is an already existing synonym of a different keyword.

@dsokac I don't really understand why they switched for "Synonyms should be case-insensitive." My problem lies in a totally different place, and I only mentioned it once before saying that there is an inconsistency in case sensitivity for some reason. I hope they will read this comment and the one with the video above.

**Comment by yvaskovski** [comment]
Hi @patapizza,

I have created a new app for the same purpose and it doesn't have that bug in it. So, just like I expected, the bug I had in the previous app was due to migration to the new version of the platform.

I wish you'd think of that yourself or tried copying my app so I wouldn't have to do this, but I guess since you are ignoring this whole thread, I was left by myself.

**Comment by dsokac** [comment]
@yvaskovski , yup... totally unprofessional of them. Thank you for this notification. Then I may just copy the app into a new one if that is the way of solving the issue. My app is a bit bigger and I cannot do it manually. Can you confirm if copying the app with the issue into new app is a solution to the problem?

And for developers, it is highly unprofessional to shut the thread like this. The last response is rude and does not explain anything. Now we still ask you to help and you ignore.... Well done...

**Comment by yvaskovski** [comment]
@dsokac , hey, i don't know since I did it manually, but I'll try it in a few hours and let you know.

**Comment by yvaskovski** [comment]
@dsokac, so I just tried creating a new app from an export of the one I created manually, and it reproduces the bug. So, my assumption is they have a lot of problems with migration. I switched my API calls back to the manual one and they work fine.

**Comment by dsokac** [comment]
Okay, thank you @yvaskovski
