### ISSUE TITLE
Wrong wit/datetime insted of number

### ISSUE THREAD

**Issue by galubap** [wit-ai/wit#1796]
This is a bug.
Sentence (in Polish) "Ustaw minutnik na 5 minut", what means in English "Set timer for 5 minutes". It was working with no issues for months, but now instead of returning digit "5" as number, I got totally unreasonable datetime. Again, it did work about week ago. Training doesn't help at all, it's always datetime.
App ID 3382588755148772

**Comment by patapizza** [comment]
Hi @galubap,

Thanks for reporting.
`wit/datetime` is powered by Duckling. I don't see any code changes in the last week that could have affected the behavior.

It seems like [`na` + time-of-day](https://github.com/facebook/duckling/blob/master/Duckling/Time/PL/Rules.hs#L872) is a valid pattern in Polish. If this isn't the case, feel free to submit a pull request to fix the behavior.
Looking at your app, I wonder why you're not using `wit/duration`? It would then capture `5 minut` properly, and give you the structured time grain. `wit/duration` and `wit/number` are also powered by Duckling, where `wit/duration` leverages `wit/number` directly.

Hope this helps.
