### ISSUE TITLE
Since your last changed about JSON structure data, I got a critical problem.

### ISSUE THREAD

**Issue by chinhdang** [wit-ai/wit#1797]
In the last version, I can extract any info from the JSON response with the JSON path because there is no '$' in param.

In the lasted update, you changed JSON structure to:
```
{
"text": "sdt 0912333444",
"intents": [],
"entities": {
"wit$phone_number:phone_number": [
{
"id": "2680184365548803",
"name": "wit$phone_number",
"role": "phone_number",
"start": 4,
"end": 14,
"body": "0912333444",
"confidence": 1,
"entities": [],
"type": "value",
"value": "0912333444"
}
]
},
"traits": {}
}
```
**wit$phone_number:phone_number** this structure get a issue.
When I use the JSON path to extract the value (phone number), here is it:
**$.entities.wit$phone_number:phone_number**
There are two '$' symbols in the code. And the JSON path gets wrong.
Is there any solution for this?

**Comment by jtliao** [comment]
You need to find a way to escape the dollar sign. It could be using `\`, another `$`, or something else depending on what language you're using.

**Comment by patapizza** [comment]
Can you use normal JS: `$.entities['wit$phone_number:phone_number']`?

**Comment by chinhdang** [comment]
> Can you use normal JS: `$.entities['wit$phone_number:phone_number']`?

Can not. I only use JSON path to extract data what I need.

**Comment by chinhdang** [comment]
> You need to find a way to escape the dollar sign. It could be using `\`, another `$`, or something else depending on what language you're using.

I can't find a reason why I need find the complicated solution to resolve simple problem. 

They only need to charge '$' sign to '.' or '_', anything except special symbol '$'. And the problem would be removed immediately.

Moreover, I'm not the coder who has ability coding to solving this issue.
