### ISSUE TITLE
Wrong detection of datetime instead of duration in polish language

### ISSUE THREAD

**Issue by galubap** [wit-ai/wit#1798]
This is a bug
In my app sentence (in polish) "ustaw minutnik na 15 minut" (english translation: "set the timer to 15 minutes") doesn't work, because "15 minutes" is detected as datetime "9.06.2020, 15:00:00". This is completly wrong understanding of polish language.
Sentences like: "5 minut", "5 godzin", "5 sekund" (english exact translation: "5 minutes", "5 hours", "5 seconds"), are not datetime. They are duration. Datetime is e.g "godzina 5", "godzina 3:45".
App id: 3382588755148772

**Comment by jtliao** [comment]
datetime and duration are detected by Duckling, which is an open-source library. Feel free to contribute to the project and submit a pull request there: https://github.com/facebook/duckling
