### ISSUE TITLE
Insights page displays no data

### ISSUE THREAD

**Issue by serdalbayram** [wit-ai/wit#1799]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
Insight page displays no data
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
After clicking Insights link (https://wit.ai/v2/apps/1622020321212473/insights), no data is displayed as seen in the attachment.
**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1622020321212473
![Capture](https://user-images.githubusercontent.com/25345380/84276646-3a6f1500-ab3b-11ea-9dea-9ea4c07e4ec3.PNG)

**Comment by lycai-fb** [comment]
Hey @serdalbayram 
Thanks for reporting the error. I can't seem to replicate it on my end.
Do you see no data for all users? Can you provide a user ID for me to test?
Thanks.

**Comment by serdalbayram** [comment]
> Hey @serdalbayram
> Thanks for reporting the error. I can't seem to replicate it on my end.
> Do you see no data for all users? Can you provide a user ID for me to test?
> Thanks.

Hi, userid: serdalbayram_573K5BI best regards Serdal

**Comment by lycai-fb** [comment]
I can't seem to replicate the issue, even when using your access token.
Can you verify that the scripts are being run and loaded (disable adblock or use another browser).
Thanks.

**Comment by serdalbayram** [comment]
Hi @patapizza , you cant replicate because of your language settings, when I change my browser language to english, it is working but with Turkish language , it displays nothing.

**Comment by lycai-fb** [comment]
Thanks @serdalbayram.
It turns out there's a bug handling certain Accept-Language header values.
Will be fixed shortly.

**Comment by lycai-fb** [comment]
Fix should be out thanks.
