### ISSUE TITLE
Multiple intents in a single sentence

### ISSUE THREAD

**Issue by ar7hur** [wit-ai/wit#18]
Example: _"Turn the bathroom light off and remind me to take the trash out."_

There are two independent intents there:
- `turn_lights`
- `set_reminder`

We don't support that yet, but that's on the short term roadmap. We know you want it! Coming soon.

**Comment by Glavin001** [comment]
+1 This would be awesome! Supporting chains of intents in sentences would make it feel so natural to users and less work for the developer.

@ar7hur 's link to `spanless entities` is broken. I found this blog post very informative: https://wit.ai/blog/2013/10/01/entities-update
Thanks!

**Comment by rdefeo** [comment]
Is this feature going to be ready soon?

**Comment by Glavin001** [comment]
I think we are getting closer with Composite Entities: https://wit.ai/blog/2015/05/05/composite-entity
However, it would be great to have Composite Intents. Looking forward to this!

**Comment by kundusandeepan** [comment]
Is multi-intent supported yet ?

**Comment by rossdargan** [comment]
Yup, this would be pretty useful!

**Comment by okaris** [comment]
Any updates on this?

**Comment by olivierlesnicki** [comment]
still broken

**Comment by lahdo** [comment]
Any updates on this?

**Comment by olivierlesnicki** [comment]
no update

**Comment by mattpennington** [comment]
Any updates on this?

**Comment by kundusandeepan** [comment]
I guess it's dead.

**Comment by patapizza** [comment]
@mattpennington @kundusandeepan Thanks for raising this. This is still something we want to support.

**Comment by murat0658** [comment]
any update?

**Comment by l5t** [comment]
https://wit.ai/blog/2017/04/18/supporting-100000-developers-and-beyond

> We are also reintroducing the N-Best feature. Simply put, it means that now Wit.ai will not just return the best intent, but a ranked list of several possible intents. This is especially helpful to implement a reformulation strategy if you’re implementing an FAQ: for an ambiguous query, your app could say “Did you mean X,Y or Z…”. It is also great to implement your own training mechanism: when Wit is not super confident, you could retrieve the 3 most relevant entities and let your user validate the correct one…

**Comment by olivierlesnicki** [comment]
@l5t @stopachka this is not the solution to the problem described here

**Comment by l5t** [comment]
Can you provide a concrete example to help us better understand the use case?

**Comment by kundusandeepan** [comment]
I want to go to Seattle for 3 nights followed by dallas where Sam would
join me from SFO for 3 days.

**Comment by patapizza** [comment]
Hi @kundusandeepan @hactar,

The way to do this would be to use one (binary) `trait` entity per intent, instead of a single `trait` entity named "intent" with multiple values.

For example, instead of having one `trait` entity "intent" (values: "weather_forecast" and "ask_time"), you could have two `trait` entities: "weather_forecast" (values: "true"), "ask_time" (values: "true"). You can then tag sentences like "weather in Paris and what time is it" with both entities.

Hope this helps.

**Comment by kundusandeepan** [comment]
Thanks, I am gonna try.

**Comment by olivierlesnicki** [comment]
@patapizza that's exactly what doesn't work!

**Comment by patapizza** [comment]
@olivierlesnicki Can you be more specific? Do you have an app I can look at? Thanks.

**Comment by mr2tkoollove** [comment]
sorry, but i cant get multiple intent when using "trait"

**Comment by stopachka** [comment]
Hey @mr2tkoollove do you mind giving me an example of what you are trying? Happy to help

**Comment by BrianCanterbury** [comment]
How do I create a custom binary entity?

**Comment by Arthur31** [comment]
@ar7hur , What's up to multiple intents ?
Do i force wit to understand ?

**Comment by blandinw** [comment]
To achieve a similar result, you can create one binary trait entity per intent.
Using the example in this issue, you would create the trait entities "turn_lights" and "set_reminder" with 1 value "true".

**Comment by blandinw** [comment]
Please see my last comment for a workaround. This is not supported today in Wit, but we'd like to work on it at some point.

**Comment by Shinoy-12** [comment]
Hey!
Let's say i have a entity "x" and this entity is defined under intent "y" and "z".
When i write a statement...will wit.ai show intent "y" and intent "z" with entity "x"?

**Comment by natcohen** [comment]
@blandinw Is there any news regarding this?
