### ISSUE TITLE
Feature request : add an optional argument in "get intent as text" rest query

### ISSUE THREAD

**Issue by zigzago** [wit-ai/wit#180]
The response of https://api.wit.ai/message?q=test call does not include the parsing details (ie {"start":0, "end:"4"} data). We need to call https://api.wit.ai/messages/387b8515-0c1d-42a9-aa80-e68b66b66c27 to get it.

Then, when there is an issue with the wit.ai entity parsing (for example : https://github.com/wit-ai/wit/issues/179 ), I need to call systematically https://api.wit.ai/messages/{id} after  https://api.wit.ai/message?q={text} to fix it on my side.

Two issues with this approach : 

- It seems there is a bug today in wit.ai api, not all requests are logged, sometimes I get one for which https://api.wit.ai/messages/{id} returns nothing 
- Anyway, it is ugly to do two http calls for that

So here is the feature request : Add an optional argument "detailed": boolean . if set, the response will include the parsing details as  https://api.wit.ai/messages/{id} does

Thank you for wit.ai!

**Comment by l5t** [comment]
Hello zigzago,
Good point. Hopefully, you can add the param verbose=true to retrieve the parsing details.

**Comment by zigzago** [comment]
Thanks :)
