### ISSUE TITLE
Settings > Save Current Version throws error in UI, even though it works

### ISSUE THREAD

**Issue by rowe-morehouse** [wit-ai/wit#1800]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**  

bug  

**What is the current behavior?**  

in `settings > save the current version` … upon button press the UI throws a toast warning in lower left corner that says "something went wrong" … but then when you refresh the page, it shows that your current version was successfully saved with the name you gave it. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Try it. I'm on MacOS 10.13.6 / Chrome Version 85.0.4167.2 (Official Build) canary (64-bit)

**What is the expected behavior?**

Should refresh the page, and show the version name you gave it, in the "time line" visualization.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**  

852549758568236

**Comment by lintaocui** [comment]
Thanks for reporting. Glad to hear it is not blocking, we will look into this.
