### ISSUE TITLE
Unable to use curl on cmd

### ISSUE THREAD

**Issue by RimJS** [wit-ai/wit#1802]
C:\Users\hp>curl \
curl: (6) Could not resolve host: \

C:\Users\hp> -H 'Authorization: Bearer $TOKEN' \
'-H' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\hp> 'https://api.wit.ai/message?v=20200611&q='
''https:' is not recognized as an internal or external command,
operable program or batch file.
'q' is not recognized as an internal or external command,
operable program or batch file.

App ID: 744253882979014

**Comment by jtliao** [comment]
Try removing the backslashes? The outputs show that each line is being parsed separately. 

And please don't share your token :)

**Comment by RimJS** [comment]
Hi Jason

Thanks for your reply. I'm sorry I didn't knew the token could not be
shared. I tried your suggestion. I'm getting the following output. I would
be grateful if you could take a look.

**Comment by jtliao** [comment]
@RimJS can you share the output?

**Comment by RimJS** [comment]
I'm sorry I didn't get you. This was what I got by typing the command on
cmd.

**Comment by jtliao** [comment]
You said "I'm getting the following output", but did not share the output.

**Comment by RimJS** [comment]
I'd attached the same.

**Comment by jtliao** [comment]
I'm not following what you're saying. To clarify, can you please give the response you're getting when sending the initial cURL, without the backslahes (`\`)?

**Comment by RimJS** [comment]
I'm really sorry to disturb but could you please help. Actually my team is
participating for the Facebook hackathon for building chatbot. But we're
stuck here and unable to proceed.

**Comment by jtliao** [comment]
I'm genuinely trying to help you, but you're not giving any of the information I'm asking for.

**Comment by RimJS** [comment]
I'm really sorry Jason, I think there is a communication issue. Did you
receive the attachment?

**Comment by jtliao** [comment]
No. Please view the thread on GitHub directly to see what I can see, there are no attachments here.

**Comment by RimJS** [comment]
Okay sure. Thank you. I'm really sorry for disturbing. I'm really thankful
for your help.

**Comment by RimJS** [comment]
C:\Users\hp>curl  -H Authorization: Bearer ***************************(token no) https://api.wit.ai/message?v=20200612&q=hello
curl: (6) Could not resolve host: Bearer
curl: (6) Could not resolve host: ********************(token no.)
{"error":"Bad auth, check token\/params","code":"no-auth"}'q' is not recognized as an internal or external command,
operable program or batch file.

**Comment by jtliao** [comment]
You need quotes around `Authorization: Bearer XXX`. This is standard curl notation.

**Comment by RimJS** [comment]
I did that, am still getting the same error.

**Comment by jtliao** [comment]
Share the exact inputs/outputs (without token)?

**Comment by RimJS** [comment]
C:\Users\hp>curl  -H 'Authorization: Bearer ************************' https://api.wit.ai/message?v=20200612&q=hello
curl: (6) Could not resolve host: Bearer
curl: (6) Could not resolve host: *************************
{"error":"Bad auth, check token\/params","code":"no-auth"}'q' is not recognized as an internal or external command,
operable program or batch file.

**Comment by jtliao** [comment]
Use double quotes.

`curl -H "Authorization: Bearer ************************" "https://api.wit.ai/message?v=20200612&q=hello"`

**Comment by RimJS** [comment]
Wow, finally i get this output
{"text":"hello","intents":[{"id":"680174619501335","name":"happy","confidence":0.5387}],"entities":{},"traits":{}}
