### ISSUE TITLE
there is a simple javascript code for wit?

### ISSUE THREAD

**Issue by metaquid** [wit-ai/wit#1803]
I request a *feature* and ask a *question* about wit.

I have to create a front end interface and I want to query wit in the simplest way possible through simple, essential and minimalist javascript (only) functions.
Is there such a possibility and what is the link if it exists?
In particular the microphone functionality and the data returned after voice recognition and all the rest.

**Comment by patapizza** [comment]
Hi @metaquid,

Please check out [node-wit](https://github.com/wit-ai/node-wit) and [microphone](https://github.com/wit-ai/microphone).
