### ISSUE TITLE
what is the latest and most updated wit json data structure?

### ISSUE THREAD

**Issue by metaquid** [wit-ai/wit#1804]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
I request the possibility to receive an alert when the json structure is changed, in a preventive way, say 7 days.
+ what is the current json data structure of wit today? (doc link)
+ how can I read wit's current json data structure from me? (with javascript function)
+ in particular the microphone functionality and the data returned after voice recognition and all the rest.

**Comment by patapizza** [comment]
Hi @metaquid,

Here's the latest [HTTP API docs](https://wit.ai/docs/http/20200513#get__message_link). You can read entities back using e.g. `resp.entities['wit$location:location'].

Hope this helps.
