### ISSUE TITLE
Words Mapping to Incorrect Values

### ISSUE THREAD

**Issue by GauravDobhal** [wit-ai/wit#1805]
When I check the phrase in the web tool to add a new utterance, it maps the entities to correct values. But when sending the same phrase using the wit API, the entity is mapped to incorrect values. Happens with closely related words e.g. 'maintain' is mapped to 'maintains' and 'available' is mapped to 'availables'.

Wit id: 1757528077591583

**Comment by jtliao** [comment]
hi @GauravDobhal, keyword entities use fuzzy string matching, to account for things like typos. This would explain why this is happening here.

**Comment by yvaskovski** [comment]
Hi @jtliao,

This issue looks to be similar to my issue posted [here](https://github.com/wit-ai/wit/issues/1794)

Same problem of mapping entities to correct values through API, while in my case it creates a new entry of a value for the entity that already exists as a synonym for an existing value.
