### ISSUE TITLE
[Request] Validate intents via API calls/posts

### ISSUE THREAD

**Issue by cl0vrfi3ld** [wit-ai/wit#1806]
**Do you want to request a ***feature***, report a *bug*, or ask a *question* about wit?**
Feature
**What is the current behavior?**
There is no current way to validate an intent or change what the intent should've been from the API, unless I'm legally blind and couldn't find it in the docs.

**Comment by jtliao** [comment]
You can create intents via the `POST /intents` endpoint: https://wit.ai/docs/http/20200513#post__intents_link

What do you mean by "change what the intent should've been"?

**Comment by cl0vrfi3ld** [comment]
There’s no way to validate an intent via the API. Say a user gives an utterance and WIT interprets the intent wrong, there’s no way to validate a correct intent via the api, or select what the intent should’ve been, (when WIT incorrectly determines an intent) via the API.

**Comment by jtliao** [comment]
You can validate an utterance with whatever the intent should be with `POST /utterances` https://wit.ai/docs/http/20200513#post__utterances_link
