### ISSUE TITLE
v2 completely not usable for polish language

### ISSUE THREAD

**Issue by galubap** [wit-ai/wit#1808]
*bug* or maybe *feature*

The problem is duckling. For duckling almost every polish phrase with number is datetime. Even phrase "20%" (pl: "ustaw głośność na 20%", en: "set volume to 20%") is parsed as datetime (!). Training do nothing. Reporting issue for duckling do nothing.
The solution would be to use v1 for selected applications, maybe as option in app settings

App ID: 3382588755148772

**Comment by jiayexie** [comment]
Hi @galubap, just to confirm, what do you mean by v1/v2? We recently refreshed the website UX but the /message API should be unrelated to the UX change. Do you mean it was working before the UX switch?

Edit: I see that this was a trained sample and it should be predicted as "wit/number" instead of "wit/datetime". I'm looking into it.

**Comment by patapizza** [comment]
As @jiayexie mentioned, the UI wouldn't change between v1 and v2. As we've pointed out previously [here](https://github.com/wit-ai/wit/issues/1796) and [here](https://github.com/wit-ai/wit/issues/1798), `wit/datetime` is powered by [Duckling](https://github.com/facebook/duckling). Feel free to submit a pull request to fix the issue. It's not `20%` that gets parsed, but `na 20` (refer to my comment [here](https://github.com/wit-ai/wit/issues/1798)).

**Comment by galubap** [comment]
> Hi @galubap, just to confirm, what do you mean by v1/v2? We recently refreshed the website UX but the /message API should be unrelated to the UX change. Do you mean it was working before the UX switch?
> 
First time I noticed problems was 10th of June. But app was not used for a week or maybe 2 weeks. 
And yes, it did work before this date. Also, it's not only one problem with incorrect datetime, see my another post https://github.com/facebook/duckling/issues/492
