### ISSUE TITLE
Cannot upload backedup zip file (parsing entities issue)

### ISSUE THREAD

**Issue by rileyai-dev** [wit-ai/wit#1809]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug/question
**What is the current behavior?**
I go to create a new app & upload a zip file and receive a failed parsing /thistle/entities message
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
i want the utterances, intents, entities, etc to be what's in the zip file
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
i tried to do it with this app: 2547142145600152

**Comment by jiayexie** [comment]
HI @grapevineai, can you tell us more about this zip file? Was it an export from another app? What's the original app id?

**Comment by rileyai-dev** [comment]
@jiayexie Previous app but deleted some intents and deleted those references in
utterances file

**Comment by jiayexie** [comment]
Did you follow the doc (https://wit.ai/docs/recipes) on making manual changes to the exported zip? If you export again, and try importing without making manual changes, does it work?

Also, what's the previous app id and when did you export it? If it was exported a long time ago, then it's likely some of our recent work broke the compatibility and we'll need to look into it. It'd be great if you can provide detailed repro steps for us to diagnose.

**Comment by rileyai-dev** [comment]
Is this correct? I have modified the app.json file to the following:

```
{
    "version": 20200513,
    "zip-command": "zip thistle.zip thistle/app.json thistle/entities/*.json thistle/intents/*.json thistle/traits/*.json thistle/utterances/*.json",
    "name": "thistle",
    "lang": "en",
    "timezone": "America/New_York"
}
```

Previous app ID: 1784861281563596
It was exported 5/29/2020
If I import that unedited version it works.

**Comment by jiayexie** [comment]
Thanks for the information. Your app.json seems fine to me.
Since the unmodified version works, the error is probably a result of your offline editing that broke some of the assumptions. Since we don't know what you did there, it's hard to debug.

To take a step back, it sounds like what you want to do is a copy of the previous app minus certain intents. Can you import the unmodified file and use the UI to delete those intents? The referenced utterances should be automatically deleted that way.

**Comment by rileyai-dev** [comment]
@jiayexie thanks for your response. We actually just deleting the intents, we're trying to merge most of them. Sorry for the confusion. Is that possible to do?

**Comment by jiayexie** [comment]
We don't recommend doing that offline with the raw JSON files; it's very hard to manage. I see you have 2000+ utterances so you probably don't want to do the merging in the UX; please consider using our APIs to programmatically re-annotate utterances and delete the unneeded intents.
