### ISSUE TITLE
My application has stopped loading utterances and I cannot export it

### ISSUE THREAD

**Issue by xakep-sava** [wit-ai/wit#1810]
Hello, my application has stopped loading utterances and I cannot export it:

![image](https://user-images.githubusercontent.com/5329475/84988312-76f9cc80-b14a-11ea-8831-399048490bf0.png)
![image](https://user-images.githubusercontent.com/5329475/84988318-795c2680-b14a-11ea-8999-f7b002df8dd4.png)

I tried it in two versions of the API. Video attached bellow.

[screencast-wit.ai-2020.06.03-00_1.zip](https://github.com/wit-ai/wit/files/4796791/screencast-wit.ai-2020.06.03-00_1.zip)

App ID: 289462435786234
App Name: B24Chat-20-he-old

Thanks!

**Comment by jtliao** [comment]
Your app should be fixed. We're working on fixing the underlying issue.

**Comment by xakep-sava** [comment]
Thanks!
