### ISSUE TITLE
When will Wit.ai/speech return timestamps per word?  (t.y.v.much!)

### ISSUE THREAD

**Issue by sheaw** [wit-ai/wit#1811]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

### YES / FEATURE:

- Wit.ai/**speech API: please also return datetime timestamp per word** _(opens extended transcription services)_

**What is the current behavior?**

API returns text, but no associated datetime timestamps (where the word appears in the audio file) per word.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

NOT A BUG

**What is the expected behavior?**

Wit.ai/**speech API should also return associated array of datetime timestamps timestamp - per word -- i.e., time of the occurrence of the transcribed word in the uploaded / transcribed audio file).

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

N/A

 (t.y.v.much!) ^_^

**Comment by jtliao** [comment]
I'll raise this with the team, but it's unlikely we'll be able to implement this in the near future.

**Comment by hadiidbouk** [comment]
Any Updates on this?

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
