### ISSUE TITLE
Add/Edit Intent Metadata in v2

### ISSUE THREAD

**Issue by web-pda** [wit-ai/wit#1812]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Ask a question/Report a bug?
**What is the current behavior?**
I can't enter Intent Metadata from the screen.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
In v1; you could enter an Intent Metadata from the view. But now, you can't enter or edit Intent Metadata.
**What is the expected behavior?**
You could add/edit Intent Metadata from the screen.
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1622020321212473

**Comment by patapizza** [comment]
Hi @web-pda,

Thank for the feedback! Metadata is a pretty advanced feature. We'll need to think more about it. In the meantime, a workaround would be to implement a simple map lookup on your end.

Let me know if that would work.

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
