### ISSUE TITLE
Removing utterances

### ISSUE THREAD

**Issue by KartikChugh** [wit-ai/wit#1813]
Bug: Removing utterances from the inbox starts the Wit training process

I find this to be problematic because it slows down the UI

**Comment by jtliao** [comment]
Thanks for flagging, we'll work on fixing this.

**Comment by jtliao** [comment]
This should be fixed now.

**Comment by KartikChugh** [comment]
Thanks!

**Comment by KartikChugh** [comment]
Can confirmed that it's been fixed
