### ISSUE TITLE
Download training is not working

### ISSUE THREAD

**Issue by 91ns** [wit-ai/wit#1814]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
Facing an error when attempting to download the training in .zip format
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Click on settings then download training 
**What is the expected behavior?**
Being able to download the training properly 
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

App ID : 2118507648262844

Error Message : 
Entity '5ceb0aee-978f-4d59-aedd-34b1878d2633' not found

 
App ID : 2256792411082295

Error Message : 
Entity 'd22fef49-d74a-483a-a81c-375439a524cf' not found

**Comment by jtliao** [comment]
Can't seem to reproduce this. It may have just taken a bit of time to sync the utterances what whatever changes were made in the app.

**Comment by 91ns** [comment]
Hi @jtliao, 
We are able to download the training .zip now. However when we try to create a new app using one of the training files it fails with the following errors : 

Failed to validate utterance at index 2. Could not find intent "%ch_1da2f0ce-8205-41ce-a722-98938a5e1df5".


Failed to validate utterance at index 0. Could not find intent "%ch_5f8e35a9-61a0-4368-aef0-ac7c1dd1e611".

**Comment by patapizza** [comment]
Indeed, this should be fixed soon.
