### ISSUE TITLE
Enhancement: Manual Training

### ISSUE THREAD

**Issue by KartikChugh** [wit-ai/wit#1816]
It would be nice if there was a button to toggle off automatic training and instead train manually.

It's useful for when users know they have to make a lot of changes (feeding many utterances, renaming entities, etc) and don't want to keep restarting training over and over.

Would probably save Wit resources as well.

**Comment by jiayexie** [comment]
Thanks @KartikChugh for raising this! I've brought this up with the team and we'll prioritize it

**Comment by dsokac** [comment]
Please, make this happen ASAP.... because I am annoyed because of current ux.... v1 was way better...

**Comment by patapizza** [comment]
Thanks for the suggestion.
This wouldn't be an enhancement on the UX. If training doesn't happen as expected, please raise an issue.

@dsokac This isn't much actionable. Please open up specific issues so we can improve. You could also make your voice heard informally through the survey.
