### ISSUE TITLE
Location with custom role not working as expected since few days

### ISSUE THREAD

**Issue by flogaribal** [wit-ai/wit#1818]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

Question & assistance needed

**What is the current behavior?**

I defined a custom role for the location entity which is "destination", I trained it with sentences that provide a context to help it know if a location is a destination or not. However when no context is provided (Ex: "Paris") it should just say that it is a location. 

It worked as expected for about a year now, I did not change anything since 4-5 months but for ONE city ("Toulouse"), since a few days ago, it keeps recognize it as a destination when providing no context. (I tested several cities and the behaviour appears only for "Toulouse")

"_I want to go to Toulouse_" => Toulouse is a **destination**
"_Paris_" => Paris is a **location**
"_Toulouse_" => Toulouse is a **destination**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

Without any context, a location should be recognized as a location.

"_I want to go to Toulouse_" => Toulouse is a **destination**
"_Paris_" => Paris is a **location**
"_Toulouse_" => Toulouse is a **location**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID: 1752915901430243

**Comment by jtliao** [comment]
We recently fixed a bug where custom roles were being suppressed in some cases for built-in entities. In this case, this is leading to issues since "Toulouse" is showing a higher confidence for `location:destination` instead of `location:location`. We'll look into how to mitigate this.

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
