### ISSUE TITLE
Unable to create a new Wit App using zip file 

### ISSUE THREAD

**Issue by 91ns** [wit-ai/wit#1819]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
Unable to create a new wit app using previously downloaded training 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Download app training in zip format 
Create a new wit app using the downloaded content 
The UI shows an error and the training is not imported 

**What is the expected behavior?**
To be able to copy the training and use it to create a new app

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

App ID : 2118507648262844

App ID : 2256792411082295

When Creating a new app we encountered the following errors

Failed to validate utterance at index 2. Could not find intent "%ch_1da2f0ce-8205-41ce-a722-98938a5e1df5".

Failed to validate utterance at index 0. Could not find intent "%ch_5f8e35a9-61a0-4368-aef0-ac7c1dd1e611".

**Comment by jtliao** [comment]
This should work again, there was an issue with the character normalization for existing apps. Note that characters like `%` are no longer allowed, so after importing, you'll notice those characters will be normalized.
