### ISSUE TITLE
404 links in the Doc

### ISSUE THREAD

**Issue by RaedsLab** [wit-ai/wit#182]
The Doc links in `Make an API request` : 
https://wit.ai/docs/web/latest
https://wit.ai/docs/http
https://wit.ai/docs/ios/latest
https://wit.ai/docs/android/latest

all 404ed

**Comment by l5t** [comment]
Thanks for reporting. Will fix it soon.

**Comment by Glavin001** [comment]
+1 I am experiencing this too

**Comment by l5t** [comment]
Just fixed. Thanks for reporting
