### ISSUE TITLE
Unable to import from backup. [object Object]

### ISSUE THREAD

**Issue by dgslv** [wit-ai/wit#1821]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
When I try to create a new app from an existing app's backup it shows me an error [object Object] as following shown:

<img width="336" alt="Screen Shot 2020-06-26 at 12 12 31" src="https://user-images.githubusercontent.com/50027703/85872989-e4d77100-b7a6-11ea-8ba9-77b7a34adbe2.png">

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Try to export your app and then create a new one using a backup.

**What is the expected behavior?**
To create a new app from backup

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2187877334578115 (the app I've taken the backup from)

**Comment by patapizza** [comment]
Thanks for reporting. This is because there are entities having more than 10,000 values. A fix is underway.

**Comment by patapizza** [comment]
All right, I've cleaned up your app from bad keywords (some had "\\" which aren't allowed), and a fix is on its way to properly include all roles when exporting. I've been able to export and re-import your app locally. I'll update and close here once it's fully deployed.

Thanks for you patience.

**Comment by dgslv** [comment]
thanks a lot @patapizza!

**Comment by patapizza** [comment]
Should be good to go now.

**Comment by dgslv** [comment]
just tried to export and re-import my app and I didn't work. same issue :( 
am I doing something wrong?

**Comment by patapizza** [comment]
You're not doing anything wrong, I can repro it too. Sorry about that, looking more into it.

**Comment by dgslv** [comment]
thanks for your time and attention @patapizza!

**Comment by patapizza** [comment]
@dgslv Thank you for your patience on this one. It's still on my list, hoping to get to it on Friday.

**Comment by Chris-Ar** [comment]
Hello,

Reviving an old thread, but we still face this issue when exporting and importing.
Our app does not contain more than 10.000 entities. (app id: 3345749878784230)
Is there a workaround?

Best Regards,
Chris

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
