### ISSUE TITLE
Training is taking longer and longer?  

### ISSUE THREAD

**Issue by jonathanbriggs-hyper** [wit-ai/wit#1822]
Is this a bug or a feature?

I have a very simple Wit.ai data set but I have to wait 3-4 hours now between trainings. Is there a reason for the long wait? It used to be virtually instantaneous.

App ID: 314530112893620

**Comment by jonathanbriggs-hyper** [comment]
Is this a bug or a feature?

I have a very simple Wit.ai data set but I have to wait 3-4 hours now between trainings.  Is there a reason for the long wait?  It used to be virtually instantaneous.

**Comment by patapizza** [comment]
Hi @jonathanbriggs-hyper,

The scheduling depends on the training queue and the state of your app. The dynamically adjusted policy ensures everyone gets a chance to see their app trained as soon as possible. As it happens, sometimes it could take longer than a few seconds.
I see your app is now trained. Let me know if you're seeing your app constantly scheduled for 3-4 hours.

Thanks.
