### ISSUE TITLE
Agent classifies "hello" as age of person

### ISSUE THREAD

**Issue by szabolcsdjangocoder** [wit-ai/wit#1823]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

*bug*

**What is the current behavior?**

`"hello"` is detected as a `wit$age_of_person`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

The agent [https://wit.ai/v2/apps/2827703750831812](https://wit.ai/v2/apps/2827703750831812) is detecting "hello" as age with high confidence.

![Screenshot_1](https://user-images.githubusercontent.com/67679463/86219255-9a7d3800-bb8a-11ea-8c06-30ddc55a4039.png)

![Screenshot_3](https://user-images.githubusercontent.com/67679463/86219267-9e10bf00-bb8a-11ea-8498-3f27be7bcc33.png)

![Screenshot_5](https://user-images.githubusercontent.com/67679463/86219306-abc64480-bb8a-11ea-908e-0d19f4a43776.png)

despite "hello" is already trained.

![Screenshot_6](https://user-images.githubusercontent.com/67679463/86219350-be407e00-bb8a-11ea-8eba-aef2d3d3b98b.png)

![Screenshot_7](https://user-images.githubusercontent.com/67679463/86219402-cdbfc700-bb8a-11ea-8867-a0b1874624f8.png)

exported agent: [internal_default-2020-07-01-00-55-21.zip](https://github.com/wit-ai/wit/files/4856510/internal_default-2020-07-01-00-55-21.zip)

**What is the expected behavior?**

"hello" should not be detected as an age

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

2827703750831812

**Comment by patapizza** [comment]
Thanks for reporting, it's a good data point to improve the built-in entities.

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
