### ISSUE TITLE
Unable to export app data - "Something went wrong. We've been notified"

### ISSUE THREAD

**Issue by lisaterumi** [wit-ai/wit#1825]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a possible bug

**What is the current behavior?**
I can´t export the data of my app, I get the message "Something went wrong. We've been notified."

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Settings page / Export your data / button "Download .zip with your data"

**What is the expected behavior?**
Download a zip file.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2387433377997084

**Comment by drronnie85** [comment]
I have same problem. My AppId is 280801049998375
I can download old application, but when I try export new i have error "Something went wrong. We've been notified"

**Comment by drronnie85** [comment]
Now I writing tool to manual export data. I thing I found reason.
In docs https://wit.ai/docs/http/20200513#get__entities__entity_link fomat of "roles" defined as array of string, but api returned array of id-name objects.

**Comment by drronnie85** [comment]
Api return "Something went wrong. We've been notified" when I try get some utterances. And Page utterances is empty.
So I think I found the problem

**Comment by ladislauek** [comment]
I think this problem is happening when the app is big. It seems that there is a limit to the size of the file that can be exported. I ask the team of wit developers to speed up the fix of this bug.

**Comment by drronnie85** [comment]
I wrote tool for export app on C#. I get every utterance separetly and skip utterance with error. After that build zip.
Problem in some utterances. I think it's happening because i removed some intents (entities, traits) that have utterances.

**Comment by lisaterumi** [comment]
I still get the error.

**Comment by ladislauek** [comment]
I think this problem occurs because the "intent" entity was deleted when the app was created. In apps that have not been deleted, the problem does not occur. It seems that in the new version of Wit.ai the entity "intent" has to exist, even if it does not have any parameter configured. Can anyone there confirm this?

**Comment by ladislauek** [comment]
@jtliao - can you help us?

**Comment by patapizza** [comment]
Sorry about the delay here. I'm looking into it.

**Comment by patapizza** [comment]
Your app is now fixed @lisaterumi.
That's correct @ladislauek, intents are now first-class citizens, and they are required (even if none are actually defined).

**Comment by lisaterumi** [comment]
> Your app is now fixed @lisaterumi.
> That's correct @ladislauek, intents are now first-class citizens, and they are required (even if none are actually defined).

Thank you very much. Now it´s perfectly working.

**Comment by iamkenken** [comment]
I have this problem too. APP ID 1117875451674104
