### ISSUE TITLE
Expressions missed

### ISSUE THREAD

**Issue by contamaiiis** [wit-ai/wit#1827]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug

**What is the current behavior?**
Sometimes when I am deleting or validating some “Expressions” in the Inbox,
Instead of deleting the selected expression, the next one is deleted or validated.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
There are two situations wich this problem occurs:
1º Occurs aleatory
2º And when there are repeated expressions in the inbox and when you start to delete one of them, the next expression is deleted instead of the selected one.

![image](https://user-images.githubusercontent.com/65665965/86494475-a82deb80-bd4b-11ea-8dde-f003f2871953.png)

**What is the expected behavior?**
The expected would be that  just the selected expression be deleted or validated.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2387433377997084

**Comment by patapizza** [comment]
Hi @contamaiiis,

Thanks for reporting. We've deprecated the old UX on June 17; we're focusing on improving the UX on the new web app. Please give it a try at your earliest convenience, and let us know if you experience further issues.
