### ISSUE TITLE
Github login broken

### ISSUE THREAD

**Issue by Pimmetje** [wit-ai/wit#1828]
I am unable to get a API key for wit.ai. The github login seems broken. I can click login. Get a popup with github. But when i end up on wit.ai/v2 it gives me "You don't have access to this page. Please contact us if this is unexpected."

I see your deprecating Github login. Please consider to leave a alternative to Facebook active. As some people may not want to have/create a facebook account. Maybe only the option to get a API key.

**Comment by Animo-girl** [comment]
I have the same issues, please help.

**Comment by luispsantos** [comment]
Hello, I would also like to know when this issue gets fixed.

**Comment by patapizza** [comment]
Thanks for reporting! This isn't expected. The previous website should still be available. I'm working on a fix. In the meantime, after logging with GitHub, hitting https://wit.ai/home should bring you to the previous website.

**Comment by Park0** [comment]
![image](https://user-images.githubusercontent.com/29624334/87179651-5c48ec80-c2df-11ea-9a72-cea43c5a1c5a.png)

**Comment by Pimmetje** [comment]
![image](https://user-images.githubusercontent.com/374414/87179914-d24d5380-c2df-11ea-9236-77b9d8a7fcd9.png)

**Comment by patapizza** [comment]
> But when i end up on wit.ai/v2 it gives me "You don't have access to this page. Please contact us if this is unexpected."

This is the issue currently addressed.

GitHub logins are allowed; GitHub signups are no longer so. More related-FAQ: https://wit.ai/faq.

**Comment by Pimmetje** [comment]
Is there any option do get a API key without a Facebook account?

**Comment by patapizza** [comment]
If you had a Wit account using GitHub login before 6/17, you are still able to use it until 12/30. To reiterate, we don't allow new GitHub signups and encourage existing users to transition to using Facebook login as their earliest convenience.

**Comment by Pimmetje** [comment]
If i did not made a account before, i can't get a API key without a facebook account?
Would u consider making a option that does not require me to have a facebook account? I only need a API key.

**Comment by patapizza** [comment]
Above issue should be addressed now.

To better utilize Facebook infrastructure to ship new features to you, we are transitioning to Facebook login-only. Thank you for your understanding.
