### ISSUE TITLE
Training is not reflected

### ISSUE THREAD

**Issue by 91ns** [wit-ai/wit#1829]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
Trained expressions are not understood correctly 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Train a new utterance then test the understanding, the utterance is misunderstood  

![image](https://user-images.githubusercontent.com/25252530/86586019-f16e7d00-bf8f-11ea-9438-0212af459af9.png)

![image](https://user-images.githubusercontent.com/25252530/86585980-e3b8f780-bf8f-11ea-9eb8-a84c520f7cc1.png)

**What is the expected behavior?**
Training to reflect correctly 
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2941770639283814

**Comment by jurneek** [comment]
I'm having the same issue @91ns did anyone from Wit reach out to you yet?

**Comment by Xueying-Wang** [comment]
Hello, sorry for the delay. @jurneek what's the language of your app and can you provide your app id as well?

Edit: @91ns would you mind providing more details on whether the intent mismatch happened for that utterance only, or for many other utterances as well, since we don't speak Arabic? Also could you check if you have by accident trained similar utterance under any other intent?

**Comment by jurneek** [comment]
@Xueying-Wang the app ID is 1160659604277531

**Comment by patapizza** [comment]
Hi,

To help with this issue, we need to know what is the expected outcome vs the actual result for a few utterances. Please use plain text so we can look the utterances up.

Thanks.

**Comment by jurneek** [comment]
@patapizza another member of wit contacted and was able to fix it although additionally similar issue seems to be happening when our app is opened by two different people with the same phrases it's pulling different intents. I have images I can show if you want to chat via email.

**Comment by patapizza** [comment]
Yes, please share those in the email. Closing as original issue is resolved.
