### ISSUE TITLE
Utterances are empty although I have more than 600 utterances registered

### ISSUE THREAD

**Issue by merianos** [wit-ai/wit#1830]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug

**What is the current behavior?**
After I train, the utterances are empty.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
If you try to train the system, after the training you will find that the utterance doesn't displayed in the utterances pages.

If you need to try your self you can try the following string: 

Andrii Matiushenko vs Ολεξάντρ Ντουκοβένκο [Πινγκ-Πονγκ |   92] {Σετκα Καπ}

**What is the expected behavior?**
After the training to see the utterance in the Utterances page.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1979818378787213

**Comment by nausicaasnow** [comment]
Hi @merianos, sorry for the inconvenience, we are looking into the issue!

**Comment by merianos** [comment]
Hello @nausicaasnow 

Thank you for the update.

Maybe it could help you the fact that I tried to export my data this morning and I got the following error message:

```
{
    "error": "Entity 'f7175d24-2387-4ec3-bd9f-879647799a91' not found",
    "code": "not-found"
}
```

Maybe that could help you :)

**Comment by jtliao** [comment]
This seems to be fixed.

**Comment by merianos** [comment]
Excellent work !! :) Thank you !! :)
