### ISSUE TITLE
Unable to login using newly created github account "nataraj-mik"

### ISSUE THREAD

**Issue by nataraj-mik** [wit-ai/wit#1831]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by nataraj-mik** [comment]
After opening wit.ai when I click Continue with Github a new window opens ups for a sec and disappears after which nothing happens.

**Comment by nausicaasnow** [comment]
Hey @nataraj-mik, thanks for your feedback, can you try again and see if you can successful login? btw, GitHub login will be deprecated by 12/30/2020. Once you "Continue with Facebook", your apps will be associated with your new account. Your apps will remain intact and the runtime won't be affected.

**Comment by nataraj-mik** [comment]
Hello Yupeng,

Thanks for your response. Yes, I do understand that github login is going to be deprecated. But, we’re trying to transfer our account to a different email which has an associated FB account. As part of that transfer we’re trying to invite a couple of users (as friends) to the current wit account and make them primary before we transfer to actual account with FB.

However, I’m still not able to login using GitHub. Am I missing something here?

Thanks
Nataraj
+1 508.564.8482

**Comment by nausicaasnow** [comment]
Hey Nataraj, is the account you can not login your current account with your apps? Or it is a new account just for transferring? If it's the latter, you can register FB accounts to help transferring.

**Comment by nataraj-mik** [comment]
Hi Yupeng,

I’d created a new github account nataraj-mik and am trying to login to Wit using this new github account.

Thanks
Nataraj
+1 508.564.8482

**Comment by nataraj-mik** [comment]
Hi Yupeng,

As suggested, I’d created an FB account with the same email id used for github account nataraj-mik and used “Continue using Facebook” after which I was able to login. A new wit username natarajkavuri_7FZMNSA was created.

I’d also invited this new wit username from an app (App ID = 2095138690517238) in our old account “satyam-mik” which is not upgraded to v2. And now I see the app within natarajkavuri_7FZMNSA under Shared Apps. But, when I try to “Transfer Ownership” to the new user I get a popup which tell that an email will be sent to the user, but I did not receive any emails.

Can you please help transfer ownership of apps (2095138690517238 & 1922464584510522) to natarajkavuri_7FZMNSA username?

Thanks
Nataraj
+1 508.564.8482

From: Nataraj Kavuri <nataraj@michaels.com>
Date: Monday, July 13, 2020 at 3:45 PM
To: wit-ai/wit <reply@reply.github.com>, wit-ai/wit <wit@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: Re: [wit-ai/wit] Unable to login using newly created github account "nataraj-mik" (#1831)

Hi Yupeng,

I’d created a new github account nataraj-mik and am trying to login to Wit using this new github account.

Thanks
Nataraj
+1 508.564.8482

**Comment by nausicaasnow** [comment]
Hi Nataraj,

I have transferred the ownership of these 2 apps to natarajkavuri_7FZMNSA :)
