### ISSUE TITLE
Unable to save intent name with dots "." or space characters

### ISSUE THREAD

**Issue by pitr134** [wit-ai/wit#1832]
After last update, somehow WIT has been automatically changing the name of the intents - where previously has been dots  - "." or space characters, it has been automatically replaced with underscore symbol "_"

Regardless of how I am trying to modify it, it still replaces spaces and dots to underscores. Is there any way to have intent names containing dots and spaces?

**Comment by nausicaasnow** [comment]
Hey @pitr134, this is a new name convention enforcement after we launch the new UI/backend stack.
