### ISSUE TITLE
Intent and Entity Mismatch

### ISSUE THREAD

**Issue by terzano** [wit-ai/wit#1835]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question, possible bug.

**What is the current behavior?**
All my training data has an intent (wiki_get) associated with a particular entity (wit$wikipedia_search_query) yet I am getting wit$wolfram_search_query associated with the wiki_get intent. I cannot explain that behavior. 

<img width="735" alt="utterances" src="https://user-images.githubusercontent.com/343932/87260557-871e7680-c480-11ea-9902-cf77160e625a.png">
<img width="541" alt="request" src="https://user-images.githubusercontent.com/343932/87260567-94d3fc00-c480-11ea-80c2-adbf4a9a616d.png">

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
the entity detected should be wit$wikipedia_search_query

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
679890082563247

**Comment by FengyangZhang** [comment]
Hi @terzano, builtin entities like wit$wolfram_search_query are pre-trained and not affected by the utterances you add. I would suggest you use custom entities if you don't want "define something" to be recognized as wolfram_search_query.
