### ISSUE TITLE
Can't select entities when it's suggested

### ISSUE THREAD

**Issue by TRPostma** [wit-ai/wit#1836]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug ?

**What is the current behavior?**
When a new utterance is sent, wit gives me some suggested entities, but if I select them to set it as one of my custom entities it won't let me. I can select the piece of text, but not give it my custom entity.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- Send a utterance where wit will suggest entities in.
- Select a piece of text that is part of one of your custom entities
- Add it normally to the desired custom entity, watch it not work.

**What is the expected behavior?**
To add my selected text to the custom entity I select?

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1512552172239562

**Comment by nausicaasnow** [comment]
Hey @CraziiTim, you can first click the "X" button to let go the auto-suggested entities, and then annotate with your own entities :)
