### ISSUE TITLE
Unable to download training 

### ISSUE THREAD

**Issue by 91ns** [wit-ai/wit#1837]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
Download training archive is not working 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Go to settings, then click on download
**What is the expected behavior?**
To be able to download the training
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
677077969722217

700090590820295

**Comment by kitchWWW** [comment]
Hello! Thank you for bringing this to our attention. We will look into this and get back with you ASAP.

**Comment by kitchWWW** [comment]
Hello! Can you confirm if you are still having this issue? We've looked into it from our side and it looks like export should be working

**Comment by patapizza** [comment]
I've been able to export both apps.
