### ISSUE TITLE
Cannot Train on New UI - "Train & Validate" Button greyed-out

### ISSUE THREAD

**Issue by idanadut** [wit-ai/wit#1838]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
BUG
**What is the current behavior?**
In "Understanding tab": I think It's not possible to manually train new phrases since the Train button is unclickable ("Train & Validate" Button greyed-out). see image: [](https://ibb.co/N28CvcF)
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Go to "Understanding tab" -> at the bottom try to enter a new phrase and try to click the bottom button "Train & Validate")
**What is the expected behavior?**
Should be able to click the train button
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
This app ID for example: 1990367351029043. (but it happens on a few more of my apps..)

**Comment by idanadut** [comment]
It happens on some of the apps See image in this link: https://ibb.co/N28CvcF

**Comment by kitchWWW** [comment]
Hello! Thank you for sharing this issue with us. I just want to confirm: It looks like from the screenshot that no intent is specified, and it is not marked as "out of scope". If this is the case, this is intentional. Every utterance that is trained must have an intent associated with it. Specifying an intent should make the train button clickable.

**Comment by idanadut** [comment]
Ok, I understand. 
Why did you make that change? In the old UI that option is available. 
Personally (and I think others could have too), I have some use cases that I'd like to train that doesn't include a specific intent - for example (a) analyzing some text sentence/phrase to separate it to different entities (as I believe the system also learns what entities to tag in a sentence according to the order and location of the word in the sentence) or (b) when the intent is ambiguous. I think it does have value - do you agree? Also, the mogration of apps from the old UI suggest models already have such "trained" phrases with no intents.
Do you think it could be enabled to work like in the old UI? or alternatively, should I just tag these with some new intent that I create for these use cases and it should work like I expect?

**Comment by kitchWWW** [comment]
Hello! The change has enabled us to treat intents with higher priority within our code base, and we encourage others to do the same. We provide the "out of scope" checkbox for negative samples, and if there is no intent present, then you do still have the option of creating a dummy intent to use for these specific use cases.
Thank you again for surfacing this concern to us, and let us know if you have any other issues! Thank you.
