### ISSUE TITLE
API Message with tag argument doesn't work.

### ISSUE THREAD

**Issue by drronnie85** [wit-ai/wit#1839]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a possible bug

**What is the current behavior?**
Request message with "tag" argument returns empty response.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. I have created application, added first intent and train app. 
2. I have created first version (tag) with name "v1".
3. I have added second intent and train app. 
4. I have created second version (tag) with name "v2".
5. Now I call message method of API (with arguments "v", "q") first request returns first intent, secont request returns second intent. It is correct.
6. After that I tried call message method of API (with arguments "v", "q") and "tag"=v1. Request returns empty response (not empty, but it can't recognize intent). Request with "tag"=v2 also returns empty response. When I specified tag=v3(that doesn't exist) i got response error "no-tag".

**What is the expected behavior?**
I expected next behaviour. 
with tag=v1 I can recognize only first intent.
with tag=v2 I can recognize both intents.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
272641183996000

**Comment by kitchWWW** [comment]
Thank you so much for reporting this to us! I'll take a look and see if we can help you out.

**Comment by kitchWWW** [comment]
Can you show an example of your URL that you are using? (sans auth tokens?) I'm having a hard time reproing.

**Comment by drronnie85** [comment]
@kitchWWW thank you for your answer.
1. Request `https://api.wit.ai/message?v=20200716&q=%D0%9F%D1%80%D0%B8%D0%B2%D0%B5%D1%82`
Response contains intent.
2. Request `https://api.wit.ai/message?v=20200716&q=%D0%9F%D1%80%D0%B8%D0%B2%D0%B5%D1%82&tag=v1`
Response doesn't contain intent.

But intent was learned before creating v1 tag.

**Comment by FengyangZhang** [comment]
fixing the issue

**Comment by FengyangZhang** [comment]
Hi @drronnie85 , the problem is fixed, you can delete the snapshots you have and create new ones. Thanks for raising this issue!

**Comment by drronnie85** [comment]
@FengyangZhang thank you! It works)
