### ISSUE TITLE
Regression with non-ascii chars

### ISSUE THREAD

**Issue by zigzago** [wit-ai/wit#184]
When we use https://wit.ai/docs/http/20141022#get-intent-via-text-link , non ascii chars are now unsupported

"Paris à 19h" , encoded q=Paris+%C3%A0+19h appears "Paris ? 19h" in the inbox section (and then entity parsing is not ok). It looks ok in the Logs section though. 

When I test the same sentence directly in  the "Try out a sentence" console, it works. The issue is  reproducible only with the rest api.

**Comment by l5t** [comment]
Thanks for reporting. We are already working on it. Will keep you updated

**Comment by l5t** [comment]
Should be fixed now. Thanks for your patience.
