### ISSUE TITLE
I cannot add a contributor to my app

### ISSUE THREAD

**Issue by merianos** [wit-ai/wit#1840]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**
I cannot find another Facebook member in the contributors field of my app settings.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I don't know if this is a bug, but I have try search either by the Facebook member name, Facebook account name _(the one appear in the browser address bar)_ and the account ID but I cannot find the member in my list. _(Actually when I use the field to find the Facebook member, the list is totally empty)_

**What is the expected behavior?**
To see a Facebook member and let the member be a contributor to my app.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
The app ID is the following: 742588889890344

**Comment by jtliao** [comment]
You need to use the their Wit username, i.e. the one in the top right corner.
