### ISSUE TITLE
Bulk Training through API not working properly

### ISSUE THREAD

**Issue by 91ns** [wit-ai/wit#1841]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
The training expressions sent through the API are not trained.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Send expressions to the API in bulk.

Response:

{
  "sent": true,
  "n": 200,
  "WARNING": "DEPRECATED"
}

However, when you go to sample, you can see the expressions there but they are not trained properly. "Intent is missing"

![image](https://user-images.githubusercontent.com/25252530/87535873-d80cb580-c6a0-11ea-9824-f2934351014f.png)

**What is the expected behavior?**

Bulk training through API to reflect correctly.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

1366838986848670

**Comment by kitchWWW** [comment]
Hello! Thank you for reaching out: With the release of our new wit.ai website, we have altered the way that wit.ai handles intents to consider them higher priority / first class parsable information. In the future, we need all samples to be trained to either have an intent, or be marked out of scope. Please see https://github.com/wit-ai/wit/issues/1838 for more discussion.

**Comment by patapizza** [comment]
Hi @91ns,

Can you share an example on how you're querying the API? Seems like you're not using the latest version yet.
To clarify, intents are optional in the [POST /utterances](https://wit.ai/docs/http/20200513#post__utterances_link) API.

**Comment by 91ns** [comment]
Hi @patapizza , 
The issue is that the API doesn't return an error but the expressions are not trained, and this is not always happening. 

We're not able to use POST /utterances at the moment because the new version requires us to create the intents before training instead of automatically training them

**Comment by patapizza** [comment]
Once again, the `intent` field is optional for [`POST /utterances`](https://wit.ai/docs/http/20200513#post__utterances_link). Entities and traits will train regardless of intents.

The Utterances section of the new UX doesn't show the traits and entities when no intent has been annotated, but the traits and entities are still taken into account. The Understanding module should perform properly, according to what has been annotated.
Can you share an example of a request you issued?

**Comment by 91ns** [comment]
Hi @patapizza 

The weird part is that for all of these expressions we have the "intent" field filled but no traits or entities. Yet some of the expressions are trained and some are not.

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
