### ISSUE TITLE
Issues with Intent normalization in Arabic and English

### ISSUE THREAD

**Issue by 91ns** [wit-ai/wit#1842]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
In some of the English language apps we have an issue where the space between words is being normalized to "_"

![image](https://user-images.githubusercontent.com/25252530/87551346-e36bdb00-c6b8-11ea-9060-ac358503bba1.png)

In some of the Arabic language apps the Arabic intent name is being completely replaced by "-" 

![image](https://user-images.githubusercontent.com/25252530/87551166-9daf1280-c6b8-11ea-9f50-3d401e265204.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Train intents having spaces or having Arabic names 

**What is the expected behavior?**
Spacing to remain in place and Arabic names not converted to "-"

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

English App ID 

941330639716785

Arabic App ID 

2941770639283814

**Comment by kitchWWW** [comment]
Hello!
Thank you so much for bringing this to our attention. Per your first question, for many named concepts in wit.ai, we don't allow whitespace to be used. Entity names and intent names are encouraged to be either CamelCase or snake_case. We do allow white space in keywords, synonyms, and trained utterances which should suffice for correctly parsing user input.

I will look into your second issue right away.
