### ISSUE TITLE
Question about the new understanging UI

### ISSUE THREAD

**Issue by asfyra** [wit-ai/wit#1843]
We are a little confused with the "Understanding" functionality on the new UI
Our application id is: 2841817995840539
The old UI shows our application like this

![image](https://user-images.githubusercontent.com/6898230/87789466-c6b1dd80-c847-11ea-906a-875809f206c3.png)

We have 3 entities: intent_faq, poi_location and deposit_type. The entity with the name intent is not generated from us.

The old UI allows us to train the application from the Inbox->Expressions like this:
![image](https://user-images.githubusercontent.com/6898230/87789756-358f3680-c848-11ea-97f8-7aaa5a55cae7.png)

The new UI does not let us train the app, because it seems to need an intent which is something we do not have
![image](https://user-images.githubusercontent.com/6898230/87789966-86069400-c848-11ea-85ae-8a65ba241755.png)
The dropdown is empty and pressing the "Train and Validate" button does nothing.

Could you please show us what we are doing wrong here.

Regards
Alex

**Comment by patapizza** [comment]
Hi Alex,

Intents and traits are now first-class citizens. You don't have any intents ("intent" trait in the old UX). To validate a new utterance, you need to declare an intent or mark it as out of scope. Currently marking as out of scope will ignore the entities and traits. We might revisit this to allow to only work with entities and traits. In the meantime, you can either associate a new intent for each value of the intent_faq trait, or create a new dummy intent to annotate the utterances.

Hope this helps.

**Comment by asfyra** [comment]
Thank you @patapizza
