### ISSUE TITLE
Training through API not working

### ISSUE THREAD

**Issue by jurneek** [wit-ai/wit#1844]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
I see Wit changed their API. We set version in request header However, it doesn’t work.
**What is the current behavior?**
Error message 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by patapizza** [comment]
Hi @jurneek,

Can you share an example of a request you issued? Your app ID would help too.

Thank you.

**Comment by jurneek** [comment]
@patapizza could we email instead to go over this issue?

**Comment by patapizza** [comment]
That works; I sent you an email, taking it offline.
