### ISSUE TITLE
Login to wit.ai website issue

### ISSUE THREAD

**Issue by abouzia** [wit-ai/wit#1845]
When I try to login with facebook or github, an authorization request is sent but nothing happens. the loading page remains like that
<img width="1321" alt="Screen Shot 2020-07-17 at 11 18 05 PM" src="https://user-images.githubusercontent.com/2650972/87834991-c800fb80-c883-11ea-92ba-e9694fa8459c.png">

**Comment by streamgreece** [comment]
I have the same issue.

In my case when I click the "Continue With Facebook" button I get the following in the console:

![image](https://user-images.githubusercontent.com/56753547/87916550-47591f80-ca7c-11ea-990c-2b275c90103e.png)

As a side not, I let you know that I am using Firefox, and I have disable the Ad Blocker as well I have disabled the tracking protection option.

**Comment by kitchWWW** [comment]
Hello! We are looking into this now. Are you still experiencing this issue?

**Comment by alsinitsa** [comment]
Hello!
I have the same issue and same error message in console now.

**Comment by merianos** [comment]
> Hello! We are looking into this now. Are you still experiencing this issue?

@kitchWWW yes, for me. The problem remains the same.

_**Note**: I am the same person as the @streamgreece above, but I handle a different account for a customer project :)_

**Comment by pantelisziazo** [comment]
I have the same issue! First time I tried to login in and never let me in, either using my facebook or my github account!

**Comment by abouzia** [comment]
Problem solved for me, I just delete wit.ai app from Facebook (Settings > Apps and Websites) and login again with another browser with no extensions, I think the problem is tracking protection option as @streamgreece mentioned because I have Privacy Badger extension installed in my brave browser.

**Comment by merianos** [comment]
@abouzia the problem persists.

I have try both with browser without plugins in incognito mode as well with the standard browser I usually run on my computer. In both cases the problem is still there.

I've also used your solution with deleting the app from the Facebook for all of my tries :/

Thank you !! :)

**Comment by abouzia** [comment]
> @abouzia the problem persists.
> 
> I have try both with browser without plugins in incognito mode as well with the standard browser I usually run on my computer. In both cases the problem is still there.
> 
> I've also used your solution with deleting the app from the Facebook for all of my tries :/
> 
> Thank you !! :)

I really don't know, According to your experience there is no specific solution that works for everyone, each one shared the solution that worked for him. It can be a temporary problem from the site itself, but I can't confirm anything.
