### ISSUE TITLE
GET request returns error "Something went wrong"

### ISSUE THREAD

**Issue by eurocharts** [wit-ai/wit#1846]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

Bug

**What is the current behavior?**

Sometimes(often) Errors when try to get request from Wit.ai API
Instead of JSON returns: "Something went wrong" "We've been notified" code:unknown

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

2184728738274083

**Comment by eurocharts** [comment]
Can You fix it? My application cannot work last 3 days due to a lot of errors

**Comment by kitchWWW** [comment]
Good morning! We are looking into this now. Could you provide a sample API request (without auth token) that has returned an error?

**Comment by eurocharts** [comment]
The same request can return error or correct json

text_arg = '22:06 - Выезд из поселка коптевка возле заправки лукойл работа экипаж проверка документов'

# Wit speech API endpoint
API_ENDPOINT = 'https://api.wit.ai/message?v=20200513'

# Wit.ai api access token

    # defining headers for HTTP request

    headers = {'authorization': 'Bearer ' + wit_access_token}

    # making an HTTP post request

    query = {'q': text_arg}
    resp = requests.get(API_ENDPOINT, headers=headers, params=query)

**Comment by mintunitish** [comment]
I am experiencing the same issue. The whole application is down! Is there any update regarding this?

**Comment by lisaterumi** [comment]
> Good morning! We are looking into this now. Could you provide a sample API request (without auth token) that has returned an error?

I have a similar issue (#1825). Can you verify too?

**Comment by jtliao** [comment]
This should be mitigated now.
