### ISSUE TITLE
Login to wit.ai website issue

### ISSUE THREAD

**Issue by merianos** [wit-ai/wit#1848]
When I try to login with facebook or github, an authorization request is sent but nothing happens. the loading page remains like that

![Login Now Allowed](https://user-images.githubusercontent.com/2650972/87834991-c800fb80-c883-11ea-92ba-e9694fa8459c.png)

In my case when I click the "Continue With Facebook" button I get the following in the console:

![Console Errors](https://user-images.githubusercontent.com/56753547/87916550-47591f80-ca7c-11ea-990c-2b275c90103e.png)

Keep in mind that I have try all of the following:

1. [Ubuntu Workstation] Login using my Chrome browser with all the plugins installed.
2. [Ubuntu Workstation] Login using my Chrome browser in Incognito mode and none plugin installed.
3. [Ubuntu Workstation] Firefox with disabled the Ad Blocker and disabled the tracking protection option
4. [Ubuntu Workstation] Firefox in Incognito mode with disabled the Ad Blocker and disabled the tracking protection option
5. [Mac Book] Chrome with plugins installed.
6. [Mac Book] Chrome in incognito mode without plugins.
7. [Mac Book] Safari browser.

From both browsers I cannot login into the with and I get the above error message.

Finally, I did all of the above tests to connect, while I deleted the app from Facebook > Settings > Apps and Websites

Any idea why??

Thank you

**Comment by patapizza** [comment]
Hi @merianos,

We weren't able to repro but made some changes on that code path. Does the issue still occur for you?

Thank you.

**Comment by merianos** [comment]
@patapizza  things seems like have been changed, but yet I cannot access my apps :cry: 

[Watch this video I recorded to see what happen.](https://youtu.be/cp0j187AAJY)

The video is recorded in Ubuntu Desktop, with Chrome browser in incognito mode.

The first part of the video in the Facebook settings, I just show you that I don't have the application registered yet.

**Comment by patapizza** [comment]
Hi @merianos,

I'm not able to reproduce this.

Did you have a Github account previously? If so, do you remember the user name/does signing in with Github work? Otherwise, what is your Facebook account?

Thanks.

**Comment by merianos** [comment]
Ah, @patapizza you may be right. So, what happen is the following.

I have start a project along with a co-worker of me. The project is related to sports events, and we use the wit.ai for extract some data from the sport events.

Initially, we start a wit.ai project, using the previous version of the wit.ai, and the account we made was from GitHub.

Then, I read that you updated the wit.ai version, and that was mandatory to signup with Facebook account. Thus, I decided to make a new account on Facebook, by using the same email address, and then make a new account on wit.ai with the using the newly created Facebook account.

So, far, I guess you are right, and maybe there's a kind of conflict with the same email address.

The email address is [ streamgreece ] @ ( gmail.com ) _(of course without the brackets, spaces and parenthesis :) )_

-------

Other than that, I have also try to make a new project using my personal email address _(and indeed, I did it)_, and try to register my co-worker as a contributor to the project. But in this case, the problem was that I couldn't register him as a contributor :(

Do you think is there any alternative way to give access to my co-worker, on the project I made with my personal account, without sharing my personal credentials ?

------

So far, I would like also to thank you for the time you spend and the help you give me :) I really appreciate it !!

Kind regards :)

**Comment by patapizza** [comment]
Ha, yes, the conflicting email is the issue.

I suggest to 1) login with Github, then 2) login with Facebook using your personal account. You shouldn't create a separate Facebook account for this.

I wonder why adding a contributor doesn't work. What is your co-worker Wit username? Are they using Facebook-login?

**Comment by merianos** [comment]
@patapizza thank you for your help and the details you shared with me.

I followed the exact steps you described, but unfortunately i didn't worked yet :cry: 

Steps I followed:

1. Sign in to my github.com account
2. Sign in to my facebook.com account
3. Delete the Wit from my Apps and Websites
4. Sign in to Wit.ai using the github.com and from the /apps/ I clicked on "Not This Time"
5. From my account inside the Wit.ai _(wit.ai/streamgreece)_ I click on the "Switch to the new Wit"
6. From the /apps/ I click the "Continue With Facebook" and then I click the "Continue as My Name"
7. I remain to the /apps/ page. If I try  again, I get the following error in the console:

![image](https://user-images.githubusercontent.com/1220823/88626298-151a7400-d0b3-11ea-89e6-eea420e8e47d.png)

One think I notice, in my browser console, in the network tab, is that at some point, the wit.ai makes a request to https://api.wit.ai/me/facebook_signin but the response is:

```json
{
   "state": "need_email_reason"
}
```

With the following request information:

![image](https://user-images.githubusercontent.com/1220823/88626476-5ca10000-d0b3-11ea-8308-a50b72b42cd1.png)

![image](https://user-images.githubusercontent.com/1220823/88626497-66c2fe80-d0b3-11ea-8593-18b95c9d9456.png)

![image](https://user-images.githubusercontent.com/1220823/88626530-73dfed80-d0b3-11ea-9f1d-77de13e71943.png)

**Comment by patapizza** [comment]
Are you using the same email address with your Facebook account? Is there another email address I can update your GitHub account with?

**Comment by merianos** [comment]
Hello @patapizza,

I am using the same email address for both accounts.

The address is the: `stream greece -at- gmail dot com` _(without spaces of course and replace the `-at-` with `@` and the `dot` with a real `.` :smiley: )_

Again, appreciate your help !! :) You are awesome ;) :)

**Comment by patapizza** [comment]
Hey @merianos,

Is there another email address I can update your GitHub-login account with?

**Comment by merianos** [comment]
Sorry, I don't understand ?

What are you trying to do? You need to replace the email I currently have with a different email?

If this is the case, unfortunately I don't have second email address. If you think this is mandatory, then let me know to build yet another email address from scratch.

Thank you :smiley_cat:

**Comment by pantelisziazo** [comment]
I have the same problem!

**Comment by patapizza** [comment]
All right, try signing in again @merianos.

@pantelisziazo Tracking in https://github.com/wit-ai/wit/issues/1865.

**Comment by merianos** [comment]
@patapizza still doesn't work :cry: 

Just to let you know, what I do, is with incognito mode, and I continue having the same issue.

thank you :smiley_cat:

**Comment by patapizza** [comment]
Hmm. Can you share in plain text the `x-fb-*` keys-values from the response to `https://api.wit.ai/me/facebook_signin`?

**Comment by merianos** [comment]
Hello @patapizza

Of course.

The Request / Response data are the following:

**General:**
```
Request URL: https://api.wit.ai/me/facebook_signin
Request Method: POST
Status Code: 200 OK
Remote Address: REMOTE-IP:443
Referrer Policy: origin-when-cross-origin
```

**Response Headers:**
```
Access-Control-Allow-Origin: *
Cache-Control: private, no-cache, no-store, must-revalidate
Connection: keep-alive
Content-Length: 35
Content-Type: application/json; charset=UTF-8
Date: Wed, 05 Aug 2020 07:00:04 GMT
Expires: Sat, 01 Jan 2000 00:00:00 GMT
Pragma: no-cache
Strict-Transport-Security: max-age=31536000; preload; includeSubDomains
wit-api-version: v1.0
X-FB-Debug: Nm3ctH0t7pm/y4P/EAkII1yW68Po1jy9Z8blCsTm5HMW28m/lKUtNWXHzysu3zTzeP0U/mOaw05lIFpxcDjngA==
x-fb-request-id: AHDljVoWWCJRIBN_dIPc_fD
x-fb-rev: 1002466576
x-fb-trace-id: FI8fO1rzqzj
```

**Request Headers:**
```
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: el-GB,el;q=0.9,en-GB;q=0.8,en;q=0.7,el-GR;q=0.6
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 752
Content-type: application/json
Host: api.wit.ai
Origin: https://wit.ai
Pragma: no-cache
Referer: https://wit.ai/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/83.0.4103.61 Chrome/83.0.4103.61 Safari/537.36
```

**Request Payload:**
```
email: "myemailaddress@gmail.com"
link_from_token: "hidden-token"
reason: "__wit_refresh"
signed_request: "hidden-token"
```

**Response Body:**
```
{
   "state": "need_email_reason"
}
```

**Comment by andro1970** [comment]
I can't login to the wit.ai to ...

**Comment by patapizza** [comment]
Thank you for the info. I could reproduce the issue and I'm working on a fix.

**Comment by patapizza** [comment]
The fix is on its way; you should be able to sign up in a few hours (I'll close the issue).

**Comment by merianos** [comment]
@patapizza you are the best !! :star_struck: 

I just got access !! Than you very much for your efforts and your help !!

Have a great day.

**Comment by pantelisziazo** [comment]
me too! just now it let me to login in properly ! I hope it will stay that way ! 
thank you very much for your help !!

**Comment by andro1970** [comment]
+1

**Comment by patapizza** [comment]
Glad it's working now! Thanks again for your patience.
