### ISSUE TITLE
Possible inconsistency/bug with statefulness

### ISSUE THREAD

**Issue by andehr** [wit-ai/wit#185]
When I create a new intent, and assign it a state in which it can fire, there's often a long delay (after training light green) before that intent will even get fired under that state. Currently, I can't get one of the intents to even be listed as an outcome with any confidence value, even using one of the example training expressions for that intent.

My instance has two possible states. One of which is "followup". 3 intents are listed with this state (they all start with the word "followup"). When in the followup state, any one of these 3 intents can be fired. But currently, the most recently made intent "followup_location" doesn't even seem to be listed among the possible outcomes when the instance is queried with one of its training expressions (and yet the other 2 always are).

Instance: https://wit.ai/andehr/taxiservice

**Comment by l5t** [comment]
Thanks for reporting there. Will investigate more.

**Comment by andehr** [comment]
Thanks a lot!

**Comment by l5t** [comment]
Can you try again? We just pushed a fix. Thanks

**Comment by andehr** [comment]
That seems to be working now! Thanks a lot!
