### ISSUE TITLE
Post Utterance Wit

### ISSUE THREAD

**Issue by gibranscr** [wit-ai/wit#1850]
hi I am trying to train the model by posting utterances using python. I am structured the function as it is stated on wit.ai, is there any issue with my code?

--------------------------------

import urllib.parse as up
import requests
import json
qry='Characteristics of the benzene'
q = up.quote(qry);
API_ENDPOINT='https://api.wit.ai/utterances?v=20200624'
wit_access_token='xx'
def createMessage(wit_access_token):

    dat={'text':'Characteristics of the benzene',
        'intent':'info_storage_compatibility',
        'entities':
         [
            {
                'entity':'chemical_substance:chemical_substance',
                'start':23,
                'end':29,
                'body':'benzene',
                'entities':
                [{
                    'entity':'chemical_substance:chemical_substance',
                    'start':0,
                    'end':7,
                    'body':'benzene',
                    'entities':[]
                }
                ]
            }
        ],
         'traits':[]
        }

    headers = {'Authorization': 'Bearer ' + wit_access_token,'Content-Type': 'application/json'}
 
    resp=requests.post(API_ENDPOINT,headers=headers,json=dat)
    data=json.loads(resp.content)

    return data
if __name__ == '__main__':
    textt=createMessage(wit_access_token)
    print("Print:",textt)
    if textt is None:
        print("\n Result: Success (200){}")

--------------------

My api ID is 1207616506249607

**Comment by patapizza** [comment]
Hi @gibranscr,

Please do not post your access token publicly. I highly encourage you to reset it in the Settings of your app.
We don't have the bandwidth to look into client-side code. That being said, you might find our Python SDK, [pywit](https://github.com/wit-ai/pywit), useful.

**Comment by gibranscr** [comment]
Hi @patapizza I was just asking about the structure of the post in which I should specify the fields correctly like in this part:

'entity':'chemical_substance:chemical_substance',
            'start':23,
            'end':29,
            'body':'benzene',
            'entities':

I mentioned that I am following the specifications on the wit.ai website,but there is response from the wit.ai when an utterance post is executed. I even am doing the same example that is on the website and it is not working, is there something else that I could do?

where am I stating my access token? are you referring to my api ID? I check that wit.ai people ask about that sometimes this is why I posted it
