### ISSUE TITLE
Speech to Text service sometimes returns Internal Server Error

### ISSUE THREAD

**Issue by papgmez** [wit-ai/wit#1853]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
report a *bug*
**What is the current behavior?**
Sometimes speech to text service returns `Internal Server Error`. 

This happens when I try to transcribe mp3 spanish audios into text.

After that I retry and it works perfectly

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
It happens casually

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
AppID: 521690455382111

**Comment by jtliao** [comment]
It's inevitable to have some Server Errors, our service reliability can be tracked at https://wit.ai/status. Unfortunately, it looks like our server status has dropped as of late, we'll definitely work on bringing that back up, as this is affecting everyone. Thanks for your support.
