### ISSUE TITLE
Stuck at Ongoing 

### ISSUE THREAD

**Issue by ghost** [wit-ai/wit#1854]
appid :2788662337869759 
stuck on ongoing for last 2days
usually when i raise this issue, you guys tell me it is a large application so taking time to train.
but last training took only 1hr and 35 minutes, and the current training is going on for last 2 days
please help
![Screen Shot 2020-07-23 at 11 55 39 PM](https://user-images.githubusercontent.com/36190477/88324485-64724480-cd41-11ea-8237-82817b0b8408.png)

**Comment by jtliao** [comment]
You're right, the training got stuck on our side (it's more susceptible to happening for large apps like yours). I've kicked it off again.
