### ISSUE TITLE
POST Utterance Wit.ai Not Training the Model

### ISSUE THREAD

**Issue by gibranscr** [wit-ai/wit#1855]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
I want you to confirm me about the elements required to do the post of utterances in wit.ai as I am following the guidelines on the website and it is not working
**What is the current behavior?**
I wrote this piece of code to post an utterance, can you verify that it is complete. I mean are all the elements stated correctly? 

dat={'text':'Characteristics of the benzene',
    'intent':'info_storage_compatibility',
    'entities':
     [
        {
            'entity':'chemical_substance:chemical_substance',
            'start':23,
            'end':29,
            'body':'benzene',
            'entities':
            [{
                'entity':'chemical_substance:chemical_substance',
                'start':0,
                'end':7,
                'body':'benzene',
                'entities':[]
            }
            ]
        }
    ],
     'traits':[]
    }
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
I am expected to be able to train the model by inserting post of utterances
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
My api ID is 1207616506249607

**Comment by patapizza** [comment]
Hi @gibranscr,

This seems about right, and the utterance is working:

<img width="758" alt="Screen Shot 2020-07-27 at 9 08 50 AM" src="https://user-images.githubusercontent.com/1015208/88565050-ecc64300-cfe8-11ea-94ff-e3623007c586.png">
