### ISSUE TITLE
Can't retrieve list of intent

### ISSUE THREAD

**Issue by leoyd** [wit-ai/wit#1856]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**

Since July or before when i execute the http request  `GET https://api.wit.ai/entities/intent?v=20180910` for getting the list of my registered intent i resulted with an 
`{
    "error": "Entity 'intent' not found",
    "code": "not-found"
}`

But entity intent exist and got trait type.

i can use the ` https://api.wit.ai/intents?v=20180910` request, it's working fine but it's tagged has deprecated in the documentation so i don't want to integrate it to my project.

thanks for your help.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
just execute `GET https://api.wit.ai/entities/intent?v=20180910` using curl, postman or whatever with authentification bearer

**What is the expected behavior?**
getting the list of my registered intent

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1969562516424162 and many other

**Comment by jtliao** [comment]
`GET /intents` would be the way to do this (documentation: https://wit.ai/docs/http/20200513#get__intents_link).

`GET /entities` is exclusively for entities, which are separate from intents now. 

Hope this helps.
