### ISSUE TITLE
Inaccessible on inbox page

### ISSUE THREAD

**Issue by krishna9626** [wit-ai/wit#1857]
**Bug**

Inaccessible on inbox page and displayed message to report on Github. Meanwhile not able to validate the sentences 

**Fix the bug**

**Comment by patapizza** [comment]
Hi @krishna9626,

What is your app ID? Is it the new UX or the old one? We're pushing a fix for the old one.

**Comment by krishna9626** [comment]
Hi @patapizza 

It is a old one...I checked it ,now it is working i can able to access the inbox page
Thanks
