### ISSUE TITLE
400 HTTP ERROR on the documentation page

### ISSUE THREAD

**Issue by Lemonzyy** [wit-ai/wit#1858]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug report:
**What is the current behavior?**
The documentation is not available, the page return a 400 HTTP error 😕 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Go to [the doc](https://wit.ai/docs)
**What is the expected behavior?**
Accessing the doc'
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
I think it shouldn't help you but it's: 1243595855984384

**Comment by patapizza** [comment]
Thanks, I'm looking into it.

**Comment by Lemonzyy** [comment]
Any news ? :'(
![](https://user-images.githubusercontent.com/47032639/88712491-1d59ca00-d11a-11ea-8281-ef9d1578ab71.jpg)

**Comment by patapizza** [comment]
We're rolling out an updated design for the documentation, yet internal infra issues are currently blocking the full roll-out, which makes the current state unstable. I'm working closely with the right people, yet alas it's mostly outside of our area of control. Thank you for your patience.

**Comment by Lemonzyy** [comment]
The documentation seems to be accessible, I close this issue. Thanks you for having solved this problem 👍

**Comment by Lemonzyy** [comment]
It seems that I can access it on mobile but not on my desktop. Edit: I think it was my cache, it doesn't work now

**Comment by patapizza** [comment]
Let's keep it open until the new docs is live, i.e. when the roll out has been fully completed.

**Comment by Lemonzyy** [comment]
np ^^

**Comment by Lemonzyy** [comment]
we agree that the documentation works correctly? I want to thank you all on your team for fixing the problem ❤ (I'm waiting for you to close the issue)

**Comment by Lemonzyy** [comment]
2 days ago it worked well but since yesterday it doesn't work anymore 😕

**Comment by patapizza** [comment]
The roll out has been resumed last Friday. Hopefully things should settle in by EOD (Pacific Time).

**Comment by Lemonzyy** [comment]
Okay nice, thank you very much :)

**Comment by patapizza** [comment]
The new docs have shipped. Thanks for your patience.
