### ISSUE TITLE
Only recognizing one intent

### ISSUE THREAD

**Issue by eacoeytaux** [wit-ai/wit#186]
My app currently has two intents, but no matter what input I provide it always thinks it belongs to the first intent, even when I input a string the exact same as one I have already associated with the other intent.  Also, every time I tell it a string does not belong to the first intent, it's confidence increases for the next string belonging to that intent.

**Comment by l5t** [comment]
Hello, thanks for contacting us. We have some issues with the training. Can you point me to your Wit app. I can see you have currently 3. And I will investigate further. Thanks

**Comment by eacoeytaux** [comment]
The app is businessHub, thank you!

**Comment by l5t** [comment]
Ok I can reproduce. It is likely in issue with the training. I will investigate and report back. Sorry for the inconvenience

**Comment by l5t** [comment]
Ok it should be fixed now. Thanks for your patience

**Comment by eacoeytaux** [comment]
Great thank you so much!
