### ISSUE TITLE
Traits usage

### ISSUE THREAD

**Issue by gnovis** [wit-ai/wit#1861]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Ask a question.

Hi, I wanted to ask about correct usage of Intents and Traits (at most recent version). What is a typical scenario when to use Traits? Is it sufficient to use only Intents for text classification with e.g. fifty classes?
Thanks.

**Comment by aforaleka** [comment]
Hi @gnovis, good question. Usually it is sufficient to use only intents in an app. We recommend using traits when there is a secondary intent you want to recognize, such as the sentiment of the sentence.

**Comment by gnovis** [comment]
Thank you @aforaleka

**Comment by patapizza** [comment]
To add to this, if you get to a really wide range of classes, with some very closely related, it would help to do a multi-layer classification by grouping under intents, then training custom traits for each subcategory. An example of this would be a list of 100 FAQ grouped by categories (e.g. account, billing, product roadmap).

**Comment by gnovis** [comment]
Thank you @patapizza the example helped me
