### ISSUE TITLE
Utterance preprocessing

### ISSUE THREAD

**Issue by gnovis** [wit-ai/wit#1862]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Ask a question.

Is it recommended to preprocess (normalize) the Utterance before training? For example, lowercase, remove punctuation or lemmatize? Does the Wit normalize the Utterances internally? How? (I'm using Wit for Czech language)
Thanks.

**Comment by patapizza** [comment]
Hi @gnovis,

In general, I'd advocate for the simplest approach first: just try out Wit without any preprocessing, and see if this works well enough. Then you can experiment with custom preprocessing and see if it improves and whether the extra complexity is worth the quality improvement. FWIW most don't do any preprocessing, the models work well for a wide range of languages; it should *just work*.

Hope this helps!

**Comment by gnovis** [comment]
Thank you @patapizza
