### ISSUE TITLE
GET /message doesn't include metadata again

### ISSUE THREAD

**Issue by eduardovoll** [wit-ai/wit#1863]
This is a bug report. GET requests to /message are not including metadata (it was included in the past – I believe it stopped working w/in the past week or so). This looks similar to closed issues #177, #553, #561, #1670 

Example request:
GET /message?v=20200701&q=i%20forgot%20my%20password

Old version
![image](https://user-images.githubusercontent.com/27147492/88832115-b6362700-d1a6-11ea-8122-f631cccf0233.png)

New version
![image](https://user-images.githubusercontent.com/27147492/88832150-c64e0680-d1a6-11ea-9c7d-c410efae85dd.png)

**Comment by aforaleka** [comment]
Hey @eduardovoll, can you provide your app id to help us debug?

**Comment by eduardovoll** [comment]
app_id: **2790653000968194**

It Works
https://api.wit.ai/message?v=20200329&explain=true&verbose=true&autosuggest=true&q=garantia de montagem
It
Doesn't work
https://api.wit.ai/message?explain=true&verbose=true&autosuggest=true&q=garantia de montagem

**Comment by patapizza** [comment]
Hey @eduardovoll,

Thanks for the feedback. We haven't included metadata in the latest version; we need to think more about it. We're tracking this in https://github.com/wit-ai/wit/issues/1812. Here's a workaround: implementing a simple map lookup on your end. Let me know if that would work.

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
