### ISSUE TITLE
Unable to access apps on site

### ISSUE THREAD

**Issue by ashton-southall** [wit-ai/wit#1864]
There is a Bug currently where I am unable to click my app in the list of apps

When I try to click the listing for my app (Browser: Opera GX) the website does nothing
![Annotation 2020-07-30 150344](https://user-images.githubusercontent.com/38774365/88882948-5909a680-d276-11ea-82bb-7b1c2738ba0f.png)

**Comment by tzufstokelman** [comment]
Happend to me as well. try to copy the App ID to the URL to enter the app.

**Comment by patapizza** [comment]
Thanks for reporting, we're looking into it.

**Comment by jiayexie** [comment]
Thanks @Adsnipers @tzufstokelman for reporting. We've reverted the offending change; it should be fixed in ~3 hours.

**Comment by jiayexie** [comment]
Fixed
