### ISSUE TITLE
Cannot log in 

### ISSUE THREAD

**Issue by pantelisziazo** [wit-ai/wit#1865]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
yes
**What is the current behavior?**
I can not log in
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
From home page (wit.ai) I press the button "continue with facebook" and then a window pops out, asks for me to grants facebook permission, I click "continue" and then the home page reload without letting me in. I read tried to log in with github but the problem remains. I also tried the suggested solutions the other users tried as described in older posts but my problem remained. 
**What is the expected behavior?**
I want to log in. This is my first time and I do not know why wit.ai does not letting me in.

**Comment by patapizza** [comment]
Hi @pantelisziazo,

Did you have a GitHub-login account before?
The app ID doesn't seem to exist.

**Comment by pantelisziazo** [comment]
Yes I have.

**Comment by patapizza** [comment]
What is your Wit username or Github account? I couldn't find anything for `pantelisziazo`.

**Comment by patapizza** [comment]
Probably related to: https://github.com/wit-ai/wit/issues/1848. Now that I've been able to reproduce the issue, let's see if the fix resolves your case as well.
