### ISSUE TITLE
Import from a backup not working properly

### ISSUE THREAD

**Issue by idanadut** [wit-ai/wit#1866]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
BUG 

2 different (and perhaps related) bugs.
**What is the current behavior?**
When I opened a new app (Hebrew language) with the new version of Wit.ai, I used imported data from one of the other apps (also in Hebrew) that I have. I added a contributor, and when he opened the same app the Entities contain much more keywords and some of the keywords "changed" their names from English to Hebrew by taking some original synonyms and making them keywords I believe.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
We (The contributor and myself) compare the number of keywords and the information of the keywords (name of keywords for instance) for the same new app, we found out that the mine has much more keywords and also some of the keywords change their name from English to Hebrew (Synonyms are mostly in Hebrew) in my contributor app.
Look at specific Entities - number of keywords is different and there were more keywords added in the imported app.

-I think strange behavior takes place after the initial training of the app (when all utterances in the backup are taken into account) so you might not see it immediately but you will after the training takes place.

**What is the expected behavior?**
Should be identical apps. 

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
Original App Id (where backup zip was downloaded from) - 3475035032571818 (compare for example entity Id 466881160679144 with the imported app)
Problematic App Id (that was opened by using the backup) - 746132436172193 (compare for example entity Id 3352197991671432 with the original app)
These entities should be identical.

**Comment by patapizza** [comment]
Thanks for reporting, this is an interesting behavior. We'll look into it.

**Comment by idanadut** [comment]
Hi @patapizza 
I tried a few more times on different occasions (and after re-training the original app) and it seems to always reproduce. 
BTW, We use the backup feature to start from scratch again or to add similar apps.
Thanks!

**Comment by idanadut** [comment]
Also, the utterances section is empty to search in when importing?
 **I think I understand what happens and this could be a major bug, let me know what you think** @patapizza :
I believe what happens is that in the utterance.json of the backup zip you can tag "stat", "end" & "body"- but "body" isn't always the keyword itself - usually it takes the synonym itself from the phrase.
So, for example, if your phrase is "blueish car" and the original app had "blue" as keyword and "blueish" as a synonym - the backup contains for some reason "blueish" in "body" instead of "blue" so another keyword is unwillingly added ("blueish") when it should have been tagged as "blue".
So I think the problem is actually in the exporting logic and the creation of utterances.json

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
