### ISSUE TITLE
Location not recognized

### ISSUE THREAD

**Issue by saadrawasia** [wit-ai/wit#1867]
bug

When i enter a location, wit does not recognize it. 

![image](https://user-images.githubusercontent.com/16437049/89035385-436aae80-d354-11ea-82e3-b3a76ca79fb6.png)

Previously it was accepting the locations.

Also the geocode is being considered as phone numbers 

![image](https://user-images.githubusercontent.com/16437049/89035664-c7bd3180-d354-11ea-9f7a-861908e05a54.png)

**Comment by patapizza** [comment]
Hi @saadrawasia,

What is your app ID?

**Comment by saadrawasia** [comment]
Hi @patapizza,

This is my test APP ID is 1718695531475815.

It seems like the location is now working but the geocode is still considered as phone number.

**Comment by saadrawasia** [comment]
Sorry i missed the comma between the latitude and longitude of the geocode. Its now working. Thanks
