### ISSUE TITLE
Live utterance search / filters feature request

### ISSUE THREAD

**Issue by ashton-southall** [wit-ai/wit#1868]
**Feature Request**
With my current project using Wit.ai it would make my life a lot easier to have a way to filter search through the live utterances and even a way to discard all live utterances would be really nice. 

I would like to be able to filter through all live utterances and only show certain intents, traits etc.

**Comment by patapizza** [comment]
Hi @Adsnipers,

Thanks for the suggestion. What is your app ID so we can get a better understanding on your use case?

**Comment by ashton-southall** [comment]
> 
> 
> Hi @Adsnipers,
> 
> Thanks for the suggestion. What is your app ID so we can get a better understanding on your use case?

Hi @patapizza 
This is my app ID
902268286921131

I'm pretty sure this isnt an ordinary use case but I'm using Wit to moderate chatrooms

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
