### ISSUE TITLE
Website doesnt load on Firefox

### ISSUE THREAD

**Issue by ashton-southall** [wit-ai/wit#1869]
I am attempting to use the website on Firefox but when I try to load wit.ai the site finishes loading and displays a blank page
![image](https://user-images.githubusercontent.com/38774365/89146495-3f7a9e80-d597-11ea-94c5-2fa03a791c0a.png)

**Comment by patapizza** [comment]
Hi @Adsnipers,

Is it consistent? Is it working for you in another browser? Have you tried hard refreshing?

It's working on my end:
<img width="1208" alt="Screen Shot 2020-08-03 at 9 45 14 AM" src="https://user-images.githubusercontent.com/1015208/89206380-14c82000-d56e-11ea-9152-242b0ffb5859.png">

**Comment by ashton-southall** [comment]
Hi there @patapizza 
It seems to be only in Firefox, I currently use Wit in Microsoft edge just fine with no issues

**Comment by ashton-southall** [comment]
> 
> 
> Hi there @patapizza
> It seems to be only in Firefox, I currently use Wit in Microsoft edge just fine with no issues

I think i've isolated the issue, turning off advanced tracking protection fixes the issue

**Comment by patapizza** [comment]
Glad you got it resolved!
