### ISSUE TITLE
Training is not reflected

### ISSUE THREAD

**Issue by 91ns** [wit-ai/wit#1872]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
The issue reported here https://github.com/wit-ai/wit/issues/1829 is still persistent.
 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Utterance is trained with intent : time_AR
![image](https://user-images.githubusercontent.com/25252530/89508661-e8630c80-d7d6-11ea-81e7-3484b7f90071.png)

but is understood as recommendation 

![image](https://user-images.githubusercontent.com/25252530/89508777-0af52580-d7d7-11ea-80d0-b8439c40fde6.png)

![image](https://user-images.githubusercontent.com/25252530/89508810-16e0e780-d7d7-11ea-9e32-8bda0492ec2a.png)

**What is the expected behavior?**

The intent in Utterances to show in the understanding section as well. 

Expressions used : 

متى اوقات دوام الحضانة ووحدة العناية المركزة للأطفال حديثي الولادة‎
متى اوقات زيارة الحضانة ووحدة العناية المركزة للأطفال حديثي الولادة

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

2941770639283814

**Comment by patapizza** [comment]
Hi,

Indeed all `time_AR` utterances start with `متى اوقات`, and I couldn't find any utterances starting with `متى اوقات` and annotated with a different intent.
I see there are 72 annotated utterances for `time_AR`, yet 479 for `recomendation`. The dataset is not balanced, which makes me wonder if adding more examples of `time_AR` utterances would help. Given that you have many other intents, I'd recommend trying this on a fresh copy of the app (the rebalancing might affect all the other intents which have even a smaller amount of annotated utterances).

Let me know how this goes.

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
