### ISSUE TITLE
Question regarding speech recognition

### ISSUE THREAD

**Issue by crypticminds** [wit-ai/wit#1873]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
777886629686542

I am trying to use the speech API for speech recognition but I have been facing a lot of issues while trying to send the data from my client-side (Javascript) to the Wit.ai app.
I am recording the user's voice and I have a blob object that contains the recording in .wav format and I want to make a POST request to the /speech API to get back the result. I have tried sending the data in various formats (streams, byte array etc) but I am not able to get the response back from the Wit.ai app. 
I see in the documentation and the Medium posts the example shows how to send a file, but since I have a Blob I cannot use the same procedure outlined in the examples. (I could not find a good way to convert a blob to a file since I do not want the recording to be downloaded on the client-side).

If possible, can you please help me out with this? 
It would be really helpful if I can get some code examples for using the speech API with javascript.

I have used the following ->

 ` fetch(WID_SPEECH_URL, {
      method: "POST",
      headers: {
        Authorization: "Bearer XXX",
        "Content-Type": "audio/wav",
      },
      body: blob.stream(),
    });
  }`

I have converted the Blob to base64 and sent it as part of the body.
I have converted it to a byte array and sent it as part of the body.

But for all of these, I have received an empty response.

Please help me out with this since we are blocked in my development due to this issue

Thanks :)

**Comment by patapizza** [comment]
Hi,

Make sure the content you're sending reflects the content-type header: https://wit.ai/docs/http/20200513/#post__speech_link
Also if you're streaming, you should set the `Transfer-encoding` header to `chunked`, as specified in the documentation link above.

Hope this helps!
