### ISSUE TITLE
Restart my app

### ISSUE THREAD

**Issue by ghost** [wit-ai/wit#1874]
appid :2788662337869759

stuck at ongoing
thanks

**Comment by sabinchacko007** [comment]
could you please try to find a solution, as it is getting stuck on training ONGOING daily. am not able to train the app.

**Comment by ghost** [comment]
As our app is consistently getting stuck in training, would it help if we exported this data and created a new app? 
 
The current 1000+ intents is set to grow to around 5000 in the next 6 months. 
 
Or would it make sense to create another app which will take all the new intents we create from here. 
 
We know that we're bothering you guys too often with our app getting stuck in training.
 
Thanks in advance for all your help.

**Comment by patapizza** [comment]
Hey,

Your app is pretty large, which is causing some training infra issue. Creating a new app with the same data unfortunately wouldn't help. We're happy to reset the training for your app until we improve our infra.
Thanks for the heads up regarding the expected growth in intents. How is the performance of your app doing for such a large set of intents?

**Comment by ghost** [comment]
The performance is great. We have problems with the training only when it get stuck in training more often. 
 
Could we slice it up into one more app with the new set of intents going to that new app? Would that help?

**Comment by patapizza** [comment]
Good to hear.

Yes, though you'll have two different models not aware of all the intents; you'll have to figure out which one to trust. A slightly different approach would be to slice the data more coarsely first, and then for each resulting class, create a trait to classify the the finer-grained intents. The top level intent classifier might still be an issue, as it'd be fed the whole dataset. Something worth trying.

I've restarted your app, closing this one.
