### ISSUE TITLE
Site is not opening properly

### ISSUE THREAD

**Issue by johnny14789** [wit-ai/wit#1875]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by johnny14789** [comment]
the site in chrome is not refreshing after sending an authorization token from Facebook login button. And it works on internet explorer but not loading the content properly.

**Comment by patapizza** [comment]
Hi @johnny14789, can you share a screencast of the issue you're facing on Chrome?
