### ISSUE TITLE
Stuck at ongoing

### ISSUE THREAD

**Issue by ghost** [wit-ai/wit#1878]
appid :2788662337869759
thank you

**Comment by ghost** [comment]
It would be better if you not closed this issue until the resolution is found, otherwise i would have to create an issue every time my application got stuck.
Thanks

**Comment by dupengling** [comment]
Hi @sabinchacko007, the training system can get stuck for various of reasons. I've manually trained this app you.

**Comment by ghost** [comment]
now the app is not resolving any intent after the last training
please help 
@dupengling

**Comment by patapizza** [comment]
Tracking in https://github.com/wit-ai/wit/issues/1881
