### ISSUE TITLE
Adding new custom entities?

### ISSUE THREAD

**Issue by RobQuistNL** [wit-ai/wit#188]
Hey guys,

Amazing work you have here! I love it :) Automating my house with it as we speak.

Now i have a question / suggestion - i wanted to have entities like "rain", "snow", "temperature" etc. in my sentences, like so;

Is it going to rain tonight?
Will it snow tomorrow?
What will the temperature be like tomorrow?

Now i can add the "datetime" and it very neatly picks out "tonight" and "tomorrow" - But i would also like it to pick up "rain", "snow" and "temperature".

Now i can create all kinds of sentences and teach it that when i ask about rain that the "weather_type" should be rain, but i would prefer it the same way as you've done with datetimes. Is it possible for me to add a sort like entity? Or should i work around it by just adding a lot of sentences?

Cheers!

Rob

PS; If you're interested - this is the home automation repo where i'm using it; https://github.com/RobQuistNL/PieStation

**Comment by RobQuistNL** [comment]
Aha, i just found out that i can select the text and then add an entity. Very neat, i think this solves the problem :)

**Comment by l5t** [comment]
Indeed Rob, it is called Custom Entities: https://wit.ai/docs/console/complete-guide#create-custom-entities-link

**Comment by RobQuistNL** [comment]
I love you guys <3 this is so freaking awesome. After a bit of training it works so amazingly well! I'll be sure to post a demo of the setup i have here.
