### ISSUE TITLE
App not resolving any intents

### ISSUE THREAD

**Issue by ghost** [wit-ai/wit#1881]
The app was stuck at ongoing and i raised an issue, and the app was manually trained.
Now the app is **NOT RESOLVING ANY INTENT**, but it has started training.
please help
appid 2788662337869759
@dupengling

**Comment by patapizza** [comment]
Looking

**Comment by patapizza** [comment]
Alright, after retraining a few times, `intent` is back! I highly encourage you to [version your app](https://wit.ai/docs/recipes#version-your-app) to freeze a version of the models and use it at [runtime](https://wit.ai/docs/http#get__message_link) by setting the `tag` parameter.

Your app still shows as ONGOING, but the training has been done quite a few times. Save a version, then we can force a retrain.

**Comment by ghost** [comment]
@patapizza **THANK YOU**
