### ISSUE TITLE
Editing detected entities

### ISSUE THREAD

**Issue by gnovis** [wit-ai/wit#1882]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
I wrote the utterance under the Understanding section and some entities were detected (colored) I made a typo so I clicked to Backspace (whole detected entity disappeared) then I started writing again and then blank screen appeared.

I am attaching a screenshot of the error from debug console. I'm using firefox on ubuntu.

![Screenshot from 2020-08-15 10-09-41](https://user-images.githubusercontent.com/4740230/90308512-5c409b80-dee0-11ea-86d9-a20ad57299fc.png)

**Comment by patapizza** [comment]
Hi @gnovis,

Sorry about the bad experience. Are you able to reproduce this consistently?

Thanks.

**Comment by gnovis** [comment]
Hi @patapizza,

yes I tried it just now (I wrote the utterance with entity and when entity word is colored then I typed backspace) and the bug occurred again with the same error message.

Thanks.

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
