### ISSUE TITLE
Is it possible to use Wit.ai in Multiple language in same app?

### ISSUE THREAD

**Issue by kenchoong** [wit-ai/wit#1885]
**Hey a quick question,**

1. May I know is it possible for Wit.ai to support Cantonese? 

2.  Is it possible for wit.ai to support Multiple language in a same wit.ai app? Or it must be done is separate app for separate language? 

3.  If separate app in Wit.ai, how can I query or how can I know which wit.ai app should I send query to? 

For example, user may speak Chinese, english ,Malay or any other language, how can I manage that from my android app?

**Comment by FengyangZhang** [comment]
Hi @kenchoong, thanks for the question! 

1. To support Cantonese you can use "Chinese(zh)" lang.
2. unfortunately we don't support multiple languages in a single wit.ai app yet. 
3. We have a [GET/ language](https://wit.ai/docs/http/20200513/#get__language_link) endpoint, that detects the language used in the query, you can use that to detect user language, then query your apps based on the language. Does that answer your question?

**Comment by kenchoong** [comment]
Got it.. Thanks a lot..This help
