### ISSUE TITLE
App not updating training 

### ISSUE THREAD

**Issue by jurneek** [wit-ai/wit#1886]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**
Despite training in the app since yesterday and today, the app is stuck on training complete saying it last trained June 25, 2020 at 12:36 PM
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Training should say ongoing updating to reflect current training 
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
941708959590532

**Comment by FengyangZhang** [comment]
Hi @jurneek, I've started a retrain of your app and it's completed now. Let us know if you run into the problem again.
