### ISSUE TITLE
Word produce by API is totally different from speech 

### ISSUE THREAD

**Issue by kenchoong** [wit-ai/wit#1888]
**Problems:** 
 Dont know this situation is it just for me.

When I speak for a simple word like "Lunch ten" in English, it return the "text" as "launch time" ,here is some of the example I try:

Breakfast ten -> Breakfast pan
Lunch ten -> Launch time
Bus Fee ten -> What's that
Bus fees ten-> Buzzfeed

At left hand side is the word I speak in english, then it return me in the right hand side word.

Which is totally different case and meaning.

Any suggestion to improve this?

**Comment by kenchoong** [comment]
In Wit dashboard, initially I received the audio file of the utterances from user, but when I change the text, the audio file is gone. 

Therefore, I wanna know,  

1) **Need Clarification:**  is that the Speech recognition will improve from time to time when the training is keep going, or it always will produce the wrong text (the not relatable text) ??

2) **Feature Request:**  And also, is there an API endpoint to let me pass back the  correct `entities`, `keywords` and `text` for the particular speech that get the wrong `text` from the API. 

To be clear I state a scenario: 
- I speak "Breakfast 7am", this produce an audio file. 
- Get a wrong text from API, get "Be fast, 7" as text. 
- So I want to send via API back to Wit.ai for the correct text "Breakfast 7am", and set entities "breakfast" as "keyword" and 7am as "time"  so that this can improve the Speech Recognition and the model get trained at the same time. 

Is it possible to do that? 

I found [POST /utterances ](https://wit.ai/docs/http/20200513/#post__utterances_link), but this seems like only for create a new utterance, but have no way to match with the audio file.

**Comment by FengyangZhang** [comment]
Hi @kenchoong, for your first question, the speech recognition won't change when you train new samples. For the second question, you can just re-annotate the audio sample and validate, then it will be added as a normal training sample.

**Comment by kenchoong** [comment]
Thanks @FengyangZhang for the reply, since the API always produce the wrong text from the audio, any possible way to improve this? Or you will suggest only use text as an input of user?

**Comment by FengyangZhang** [comment]
We are not aware of any quality issue of the speech API, but will definitely keep an eye on improvements! I think if most of the  user audio are not very straightforward or commonly-used sentences, it might be easier to just use text input. For example "breakfast pan" seems more common than "breakfast ten" which is probably why the speech model output the first one.

**Comment by kenchoong** [comment]
Ok thanks
