### ISSUE TITLE
Message requests not in logs nor inbox

### ISSUE THREAD

**Issue by zigzago** [wit-ai/wit#189]
curl -H 'Authorization: Bearer xxx "https://api.wit.ai/message?v=20151010&q=test"

is usually not logged in /logs (and nothing in inbox either) - but the response is ok

On my instances, I notice that only a small fraction of the requests are logged (less than 1/5)

Quite annoying when you build a new intent :(

**Comment by l5t** [comment]
Sorry for the inconvenience, we did have some issues with the training. It has been fixed.
