### ISSUE TITLE
Post Utterance - Failed to validate utterance at index 0

### ISSUE THREAD

**Issue by saaqeb** [wit-ai/wit#1890]
Post Reqeust
=========
Array
(
    [text] => Link Account
    [entities] => Array
        (
            [0] => Array
                (
                    [entity] => wit$search_query
                    [start] => 5
                    [end] => 12
                    [body] => account
                    [entities] => Array
                        (
                        )

                )

        )

    [traits] => Array
        (
            [trait] => wit$sentiment
            [value] => positive
        )

    [intent] => link_account
)

Response Issue
===========
Array
(
    [error] => Failed to validate utterance at index 0
    [code] => bad-request
)

**Comment by FengyangZhang** [comment]
Hi @saaqeb, can you provide the app id so I can take a look? Thanks

**Comment by saaqeb** [comment]
@FengyangZhang app id 655440081732098

**Comment by FengyangZhang** [comment]
Hi, so for the entity, you should use "wit$search_query:search_query". All of the entities should be used in this "entity:role" way. Hope this helps.

**Comment by saaqeb** [comment]
@FengyangZhang  Can it is possible do with only post  {"text":"Link Account","intent":"link_account"} to https://api.wit.ai/utterances

**Comment by FengyangZhang** [comment]
Hi @saaqeb, the "entities" and "traits" are required, so if you want to validate the utterance without entities and traits, you can do {"text":"Link Account","intent":"link_account", "entities": [], "traits": []}.
