### ISSUE TITLE
Retraining after entity lookup strategy is changed

### ISSUE THREAD

**Issue by gnovis** [wit-ai/wit#1893]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question
**What is the current behavior?**
After changing entity lookup strategy from Keywords & Free Text to Keywords only, the app is not retrained. Entities are detected in utterances also in case they don't match the keyword or synonym of the entity.
**What is the expected behavior?**
After changing the lookup strategy, the app should be retrained, is there the explicit way to do that? Thank you.

**Comment by FengyangZhang** [comment]
Hi @gnovis, thanks for the feedback! We'll improve this ASAP, will keep you updated. In the meantime you can manually trigger the retrain for now, like adding or removing an utterance

**Comment by gnovis** [comment]
Ok, thank you @FengyangZhang

**Comment by FengyangZhang** [comment]
Hi, we've updated our retrain logic to retrain when you change the parser lookup to include freetext from keywords-only. For the opposite direction we're still looking for the best solution, for now if you ever find unexpected behavior related to this just manually trigger the retrain. Hope this helps.
