### ISSUE TITLE
scrollbar in Firefox

### ISSUE THREAD

**Issue by gnovis** [wit-ai/wit#1894]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
The scrollbar (for example in Utterances section) unexpectedly jumps to the top of the scrolling area after reaching the bottom of the scrolling area. I'm using Mozilla Firefox for Ubuntu.

**Comment by patapizza** [comment]
Thanks for reporting.

**Comment by gnovis** [comment]
I noticed that the bug is occurring after exporting the app data (only Firefox, Chrome is ok)

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
