### ISSUE TITLE
Intent deletion

### ISSUE THREAD

**Issue by gnovis** [wit-ai/wit#1895]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug & question

**What is the current behavior?**
After deleting the intent which is assigned to some utterances, all utterances disappeared.

**What is the expected behavior?**
I'm not sure, what will happen with the utterances (without traits or entities) which intent was deleted?

**Comment by patapizza** [comment]
What is your app ID?

**Comment by patapizza** [comment]
This is a bug. We're working on a fix.

**Comment by gnovis** [comment]
Sorry @patapizza, the app no longer exists. I needed to continue working so I deleted the app and created the new one from the backup.

**Comment by ramh** [comment]
The issue has been fixed and the changes will be live by end of today. Thank you for your patience.
