### ISSUE TITLE
Unable to Export

### ISSUE THREAD

**Issue by jefferyhayes** [wit-ai/wit#1896]
Do you want to request a feature, report a bug, or ask a question about wit?
Potential bug

**What is the current behavior?**
On the app settings page, I cannot export/download app data

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1 - Click "Download .zip with your data",
2 - Get error "Something went wrong while exporting your app 😣. Please try again, or contact us."

![image](https://user-images.githubusercontent.com/2111685/91233584-646db780-e6e6-11ea-9a44-c5b40e4a2252.png)

**What is the expected behavior?**
1 - click "Download .zip with your data"
2 - .zip downloads

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2464252626970124

**Comment by jtliao** [comment]
This should work now, sorry about that

Edit: scratch that, it should work in a couple hours
