### ISSUE TITLE
Streaming Speech — How to Detect Pauses/Silences

### ISSUE THREAD

**Issue by shawnbzhang** [wit-ai/wit#1899]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question

**What is the current behavior?**
Wit.ai says that they support streaming audio and accept chunked data. However, does Wit detect pauses/silences to indicate when a user has finished speaking? I know Wit's documentation says that an audio stream shouldn't exceed 10s of audio time. Do we need to just wait until 10s have passed?

Right now, I can stream audio and generate text in a buffer. However, I can't determine if a user has stopped speaking to submit into the turn of conversation.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
I would like it so that if I stream the audio, Wit.ai could detect when a user has finished speaking.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by patapizza** [comment]
Hi @shawnbzhang, we don't provide Voice Activity Detection at this point.
Something to implement on your end. This might help: https://stackoverflow.com/questions/60832201/how-can-i-do-real-time-voice-activity-detection-in-python

**Comment by patapizza** [comment]
I don't expect bandwidth for this in the near term.
