### ISSUE TITLE
The 'outcomes' is null

### ISSUE THREAD

**Issue by jamesweb1** [wit-ai/wit#190]
I follow the tutorial and select an internet to test wit-ai. And it always gets nothing from the output.
For example, I use the python api as follow:
```python
response = wit.text_query('What\'s the weather today in San Jose, CA?', access_token)
```
I get the response as follow:
Response: {"_text":"What's the weather today in San Jose, CA?","msg_id":"97554045-d9c4-4fd2-8146-9e598a0c344c","outcomes":[]}

This makes me crazy to use this ai tool. Is this a bug or something I don't figure out? I read the all doc on the website.

**Comment by l5t** [comment]
Hi James, thanks for reaching out and sorry for the bad experience. I just checked and it works for me. Usually the training takes a few seconds when you have a few validated expressions, but it may have been stuck in your case. There is a training status icon that should help. Please confirm that is works for you now.

<img width="336" alt="screen shot 2015-10-13 at 6 17 16 am" src="https://cloud.githubusercontent.com/assets/6992759/10455802/51a05124-7172-11e5-81b7-41d21a138384.png">

**Comment by jamesweb1** [comment]
Yes, it works for me now. But the training status is green and I try tens of times for more than hour still null outcomes. This makes me very confused. However, it works fine now.
