### ISSUE TITLE
Adding regular expression for detecting email

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#1900]
Hi,
Is it possible to identify an email entered in wit.ai as email using regular expression or any built in entity.
Similarly a phone number etc
Tried with built in entity wit/email. Will the builtin entity be identified by default? when I put test@test.in it didn't identify as wit/email.

**Comment by patapizza** [comment]
Hi,

What language is your app using? I can't repro it:
<img width="965" alt="Screen Shot 2020-08-28 at 8 44 37 AM" src="https://user-images.githubusercontent.com/1015208/91586793-be4ec700-e90a-11ea-9c66-f43340c41a1e.png">

We won't offer regexes, see https://github.com/wit-ai/wit/issues/274 for the rationale.
