### ISSUE TITLE
Bonjour SVP j'ai besoins d'aide, j'essaye d'intégrer wit.ai à botman seulement wit.ai ne retourne pas d'erreur mais ne retourne rien

### ISSUE THREAD

**Issue by lekeufackalida** [wit-ai/wit#1901]
mon  code
$botman=resolve('botman');
    
    $wit = Wit::create('key api');
$botman->middleware->received($wit);
$botman->hears('bonjour', function (BotMan $bot) {
   
    $extras = $bot->getMessage()->getExtras();
    $bot->reply('salut');
 
})->middleware($wit);
   //$botman->listen();

**Comment by patapizza** [comment]
Bonjour,

Je ne suis pas familier avec BotMan. Je vous conseille d'ouvrir une issue directement au projet: https://github.com/botman/botman/issues

Bien à vous.
