### ISSUE TITLE
App stuck at "Training Ongoing" after changing lookup strategy

### ISSUE THREAD

**Issue by Chris-Ar** [wit-ai/wit#1902]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug(?)

**What is the current behavior?**
App is stuck at "Training ongoing" for more than 5 days.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Changed entity lookup strategy from " Free Text & Keywords" to "Keywords" and this happended.

**What is the expected behavior?**
Finish in a reasonable amount of time. :) Used to take around 1-3 minutes.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
3345749878784230

Thank you in advance.

**Comment by wangsnowyin11** [comment]
I've manually trained your app, now the training should be finished!

Sorry for the inconvenience
