### ISSUE TITLE
How to programmatically train out-of-scope?

### ISSUE THREAD

**Issue by Bakersbakebread** [wit-ai/wit#1904]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question

**What is the current behavior?**
How do I programmatically train an utterance with no Intents? Currently it is returning 100% confidence on an utterance that I want it to be out-of-scope.

I'm using the `/post/utterances` endpoint to train the model.

**Comment by patapizza** [comment]
Hi @Bakersbakebread,

The `intent` field is optional for [`POST /utterances`](https://wit.ai/docs/http/#post__utterances_link).

From the link above, the documentation for the field:
> The user intent for the utterance. Out-of-scope utterances would leave off this field.
