### ISSUE TITLE
https://free.facebook.com/profile.php?id=100051376837454&refid=46&__xts__%5B0%5D=12.Abq44x9jIp3oLyJe463m20XCrt4DIIu2ihnDy6kc1VRDWeAnPCPc15YusDqRSxAvZNw-IUkQsSNBIgCq7MTtRk0zL9OnsEQZQqelC1RvRBiQyzVkFFjhOl6rA7vqTbfsgHFvtRfhdhTsQCdMxGaK9SoEVDcWJ6UUg94bHqPD3moPRhkKog6dfBNyaTsPS3QR4jF1tuWU_bCxKmB6-IU-kix63nAAfu03v9yDz2uNxZZHfoZbzCGnPKIsmXOiPV0DCyPXIZRq5nsbgWtmuMTtqyaEwzz9k6p4bdUaa90ux3bBEvl7Cpy8P74hfUhfE3mAI5h84rW3W1DuJniuEKxT_HLedIxd5QVCq5CMmrfYS_WnpIMAWA4qaSK-GIzyIGqOlC0Dy5IE7Jg5fL_sw7eeMSjgI16l6t7O42MaqgcdMjq5MQeWFQUIsxOvn_4SNoA59t3y3WrJRBfalYYDyGslAsMzuUplS9yAUBffJcGxqNpewEdJvz5FxIh14yZBLD2lTDHVyUrbJvHgaFsf4gOJrghtD3TvutH2LaeDUbjYgtipmIYE0-r2fExT0Wvz-NRVe58

### ISSUE THREAD

**Issue by rifki858** [wit-ai/wit#1908]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by rifki858** [comment]
https://free.facebook.com/profile.php?id=100051376837454&refid=46&__xts__%5B0%5D=12.Abq44x9jIp3oLyJe463m20XCrt4DIIu2ihnDy6kc1VRDWeAnPCPc15YusDqRSxAvZNw-IUkQsSNBIgCq7MTtRk0zL9OnsEQZQqelC1RvRBiQyzVkFFjhOl6rA7vqTbfsgHFvtRfhdhTsQCdMxGaK9SoEVDcWJ6UUg94bHqPD3moPRhkKog6dfBNyaTsPS3QR4jF1tuWU_bCxKmB6-IU-kix63nAAfu03v9yDz2uNxZZHfoZbzCGnPKIsmXOiPV0DCyPXIZRq5nsbgWtmuMTtqyaEwzz9k6p4bdUaa90ux3bBEvl7Cpy8P74hfUhfE3mAI5h84rW3W1DuJniuEKxT_HLedIxd5QVCq5CMmrfYS_WnpIMAWA4qaSK-GIzyIGqOlC0Dy5IE7Jg5fL_sw7eeMSjgI16l6t7O42MaqgcdMjq5MQeWFQUIsxOvn_4SNoA59t3y3WrJRBfalYYDyGslAsMzuUplS9yAUBffJcGxqNpewEdJvz5FxIh14yZBLD2lTDHVyUrbJvHgaFsf4gOJrghtD3TvutH2LaeDUbjYgtipmIYE0-r2fExT0Wvz-NRVe58

**Comment by wangsnowyin11** [comment]
Hey dear customer,

I am not sure I understand what issue you are facing, could you provide description of your issue and also the app_id?

Thx!
