### ISSUE TITLE
Problem with sox

### ISSUE THREAD

**Issue by KarachiSeLog** [wit-ai/wit#191]
My app is written in python. It runs perfectly locally. But when I try to run the code on the server and do git push heroku master the push gets aborted with the error:
/usr/bin/ld: cannot find -lsox
remote:            collect2: error: ld returned 1 exit status
remote:            error: command 'gcc' failed with exit status 1
And heroku logs gives the error that there is no module named wit. Even though I am certain that wit exists and the app somehow runs locally. I would imagine it is an error with maybe the version of sox I have or the location messed up.

**Comment by dariuszmysliwiec** [comment]
I've encountered the same error (/usr/bin/ld: cannot find -lsox). The solution is to install sox library for my distribution.

**Comment by patapizza** [comment]
So sorry for the late response.

You need to have libsox (with -dev files) installed on your server to be able to run it.
FYI this version of `pywit` is now deprecated, as we've released the beta version of our Bot Engine.
