### ISSUE TITLE
HTTP API doc typo easy fix

### ISSUE THREAD

**Issue by theoptips** [wit-ai/wit#1910]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
report a typo

**What is the current behavior?**
[HTTP document API version 20200513](https://wit.ai/docs/http/20200513/#api_versioning_link)
`const uri = 'https://api.wit.ai/message?v=20200513='+q;`
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
To reproduce, in an index.html file include the following in end of body script tag. To call the HTTP API

```(function (){
const q= encodeURIComponent('any message to wit');
const uri = 'https://api.wit.ai/message?v=20200513='+q;
const auth = 'Bearer   ' +CLIENT_TOKEN;
fetch(uri, {headers: {Authorization: auth}})
.then(res=> res.json())
.then(res=>console.log(res))
})()
```
Error: Failed to load resource: the server responded with a status of 400 (Bad Request)

**What is the expected behavior?**

Easy fix on the *documentation* *tutorial*

URI parameters should be separated with ampersand. 

Replace line 2  with this below.
`const uri = 'https://api.wit.ai/message?v=20200513&q='+q;`

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by patapizza** [comment]
Thank you! We'll fix that shortly.

**Comment by patapizza** [comment]
Done!

**Comment by theoptips** [comment]
Thanks!
