### ISSUE TITLE
Improvement for entity detection

### ISSUE THREAD

**Issue by dsokac** [wit-ai/wit#1911]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Feature.

**What is the current behavior?** 
Wit can identify all entities available in wit without any additional  constriction

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Wit can identify only entites which are used in training phrases by user. So if user uses only "car_model" entity, the wit.ai can only indentify the entity or return as if no entity is detected. Wit should not detect any other entity but "car_model". If user adds new entity "city" then wit can detect either "city" or "car_model". 

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by patapizza** [comment]
Hi @dsokac,

Can you elaborate a bit more?

Thanks.

**Comment by dsokac** [comment]
Let's say you decide to define intent get_employee_info for fetching information on employees.

I will write examples of training phrases and what wit may detect:
"Where is Peter?" - "Peter" is an entity employee
"Where is Peter at the National Theatre?" - "Peter" is an entity employee and "National Theatre" is entity location
"Where is Peter Parker at Some Random address?" "Peter Parker" is an entity employee and "Some Random address" is entity location

Let's say wit should know that the intent get_employee_info knows entities employee and location. Let's say that you have other intents and entities, not just these. Let's say you trained wit to detect weather_condition entity and transport_type entity. 

My proposal is that it is impossible for wit to detect an entity that did not appear in training phrases of the intent. Let's say employee and location are the only entities in the intent get_employee_info.  So, wit could avoid putting random entities in the query if wit know that employee and location are related to the intent get_employee_info and that means that wit will never choose another entity.

I hope this helps!

Danijel Sokač

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
