### ISSUE TITLE
App is not training - needs re-booting

### ISSUE THREAD

**Issue by fedariana** [wit-ai/wit#1913]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug. 

**What is the current behavior?**
App is not training. Last time being trained was June 2020 despite recent training activity. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
<img width="1215" alt="Screen Shot 2020-09-11 at 9 06 27 AM" src="https://user-images.githubusercontent.com/68617768/92948360-165af280-f40e-11ea-9041-65e3f8a21083.png">

**What is the expected behavior?**

App should automatically train after adding new phrases. New phrases were added 9/10/20

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

523810541636590

**Comment by patapizza** [comment]
Hi @fedariana,

Just to confirm: did you validate any new utterances? You first need to review and validate new utterances before your app needs retraining.

**Comment by patapizza** [comment]
Just to make sure, I've just retrained your app.
