### ISSUE TITLE
Can not train my app

### ISSUE THREAD

**Issue by yaofenglu** [wit-ai/wit#1914]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
It can not load the intent, and entity  and can not train 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Loading Intents forever, This makes me can't train the app

**What is the expected behavior?**
it should load intent in a second

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
317839149527733

**Comment by patapizza** [comment]
Thanks for reporting, and sorry about that. We'll look into it.

**Comment by yaofenglu** [comment]
> Thanks for reporting, and sorry about that. We'll look into it.

Any Update?

**Comment by fedariana** [comment]
This issue is occurring for me as well. @patapizza

**Comment by sosoxuc** [comment]
Is this working at all?

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
