### ISSUE TITLE
Native entity (wit$number) cannot be deleted via REST API

### ISSUE THREAD

**Issue by kralikX** [wit-ai/wit#1918]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
BUG

**What is the current behavior?**
We need to manage wit applications via REST API completely and need to retain app IDs and tokens. Therefore prior to uploading newer version of the model I am trying to delete all utterances, intents and entities in the app. 
DELETE endpoint works for custom entities, however call to `DELETE api.wit.ai/entities/wit%24number` ends with `400 Bad Request` error:
```
{
    "error": "You can't add keywords to free-text entities.",
    "code": "unsupported-lookups"
}
```
The same behavior occurs when trying to delete single role in native entity.
Native entity can be deleted using console and created using both console and REST API, so I suppose it should be deletable via API as well.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Create new app
1. Create new entity of type `wit$number`.
1. Try to delete entity via API call `DELETE api.wit.ai/entities/wit%24number`.

**What is the expected behavior?**
Native entities can be deleted via API just like custom ones.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
395976868054977

**Comment by patapizza** [comment]
Hi @kralikX,

Thanks for reporting. We'll look into it.

**Comment by kralikX** [comment]
Hi @patapizza, any news about the issue? Thanks in advance.

**Comment by ChrisyShine** [comment]
@kralikX The problem has been resolved, can you try to delete the entity from you app?

**Comment by nikolaikk** [comment]
Hi, there. I am experiencing the same problem. Cannot delete native entities.
