### ISSUE TITLE
Not able to create utterance some times its create and sometimes its not

### ISSUE THREAD

**Issue by surajsingh92** [wit-ai/wit#1919]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
ask a question.
**What is the current behavior?**
i am using the "https://api.wit.ai/samples?v=20200918" API for utterance. when I post the data with entity some times its create and some times it's not created. and also the utterance section takes time to update the utterance.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
i am posting the following data 
[{
       "text": "What is the response rate for last 2 months for we miss you campaign",
       "entities": [
          {
            "entity": "intent",
            "value": "response_get"
          },
          {
            "entity": "wit$datetime",
            "value": "last 2 months",
            "start":30,
            "end":43
          },
          {
            "entity": "campaign",
            "value": "miss you",
            "start":51,
            "end":59
          }     
        ]
      }]
when I post this data always I am getting {"sent": true,"n": 1,"WARNING": "DEPRECATED"} response .and I can see the entity and intent in their section. but when I go into the utterance section I am not able to see. I am getting this behavior some time and sometimes it created the utterance. I am not able to understand why it's happening.
**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
324212385527094

**Comment by patapizza** [comment]
Hi,

- The above utterance didn't work because you didn't have the `campaign` created at the time. We see a 400 in our logs.
- The `POST /samples` has been deprecated. Please use [`POST /utterances`](https://wit.ai/docs/http/#post__utterances_link) instead.
- This API is asynchronous, the utterances don't post immediately to your app.

Hope this helps.

**Comment by surajsingh92** [comment]
I have already created a campaign entity. even after  that it's not creating the utterance
