### ISSUE TITLE
labs.wit.ai returning DEPRECATED

### ISSUE THREAD

**Issue by rileycrane** [wit-ai/wit#192]
I keep receiving `DEPRECATED` warnings while testing with the labs.wit.ai page
```
{
  "msg_id": "c756023b-b33f-4f23-a3eb-33d74e3db99e",
  "outcome": {
    "confidence": 0.549,
    "intent": "get_temperature",
    "entities": {}
  },
  "msg_body": "what's the temperature outside",
  "WARNING": "DEPRECATED"
}
```

**Comment by l5t** [comment]
Hi Riley,
Thanks for reporting. We haven't had the time yet to update the websocket API to the latest version of our API. This is why you get this WARNING.
