### ISSUE TITLE
wit/location not detecting location  

### ISSUE THREAD

**Issue by jurneek** [wit-ai/wit#1920]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
wit location entity isn't detecting Rochester Indiana instead it's picking up Rochester New York can we add Rochester Indiana to the location 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
57b20cd7-14b8-4cff-9cec-c560cbd21673

**Comment by ChrisyShine** [comment]
Thanks for the feedback. The suggested solution of this problem is to create a custom entity, and train the entity with your own data. So that you can have a better entity specifically for your own feature.

**Comment by jurneek** [comment]
@ChrisyShine can the location please be taken into consideration for adding to the get location entity

**Comment by patapizza** [comment]
We currently don't have the bandwidth to improve the built-in entity. As @ChrisyShine mentioned, you can supplement using your own custom entity for the time being. Thanks.
