### ISSUE TITLE
Issue in arabic understanding

### ISSUE THREAD

**Issue by AymanKhafage** [wit-ai/wit#1923]
We faced bug in arabic understanding.

currently arabic understanding is working fine only as long we are sending the exact word/sentence in the entity keywords.

When we send a word in arabic that is not exist in the entities keywords, instead of comparing to the closest match in the keywords of the entities, It's instead match in strange way, for example when we added the keyword "كتاب" to the entity named "gi" if we send the word with a small difference like "الكتاب" (we just added two Arabic letters in the beginning) it takes me somehow to other entity which is "clinic" even while "clinic" does not have any word close to this one.

We think that currently since you are saving the word in UTF form, maybe you are comparing the UTF and that is why it is
comparing wrong, we think it would work fine if you just compare it using Arabic letters.

APP ID 617162935871400

**Comment by AymanKhafage** [comment]
Kindly looking for any response .

**Comment by chessai** [comment]
This should be resolved after https://github.com/facebook/duckling/pull/577. Let me know if your issue persists.
