### ISSUE TITLE
Wit v2 not loading

### ISSUE THREAD

**Issue by carson-katri** [wit-ai/wit#1924]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug

**What is the current behavior?**
The site is not loading after pressing the "Switch to the new Wit" button.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Press the "Switch to the new Wit" button. After doing so it just keeps loading in the top left corner. I can't access the main page or any of my apps.

**What is the expected behavior?**
The site loads.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
The problem is with my entire account. I can't access any of my apps.

**Comment by patapizza** [comment]
Hi @carson-katri,

What is the URL? Can you load https://wit.ai/apps?

**Comment by carson-katri** [comment]
The url was wit.ai/v2 but /apps is working 👍

**Comment by lintaocui** [comment]
can I close this ticket @carson-katri ?
we do not support wit.ai/v2 anymore.

**Comment by carson-katri** [comment]
Yeah, not sure how I got to that page 🤔😄

**Comment by patapizza** [comment]
It was the previous URL. Maybe you had it as a bookmark?
