### ISSUE TITLE
showing confidance N/A .

### ISSUE THREAD

**Issue by surajsingh92** [wit-ai/wit#1925]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Ask a question.
**What is the current behavior?**
I am going to do the following understanding. i am attaching a screenshot please check it.
![image](https://user-images.githubusercontent.com/66119519/93970538-f02d3f00-fd8b-11ea-8839-9ffb1e88f44a.png)
.
please let me know why its showing confidence N/A. sometimes when I paste the same query in the utterance box then it automatically high light the "last 2 months" keyword and then it shows the confidence 100%.  I am not able to understand why this happening.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Copy and paste the following query in the utterance box.
"What is the response rate for last 2 months" sometime it will automatically detect the last 2 months' keyword and sometimes it's not. if it's not detecting then select the last 2 months and add the DateTime entity. then it will show the confidence N/A.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
324212385527094

**Comment by patapizza** [comment]
Hi,

I can't repro this:
<img width="971" alt="Screen Shot 2020-09-23 at 3 44 08 PM" src="https://user-images.githubusercontent.com/1015208/94080822-bb34e280-fdb3-11ea-838a-9e39cbfbf242.png">

How often do you see that?

**Comment by surajsingh92** [comment]
If I will try 10 times then I will get 7 times. I am also can't say when it will show confidence and when it will not.

**Comment by INzoGravity** [comment]
> If I will try 10 times then I will get 7 times. I am also can't say when it will show confidence and when it will not.
