### ISSUE TITLE
Utterance not creating if entity already exists

### ISSUE THREAD

**Issue by surajsingh92** [wit-ai/wit#1927]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
report a *bug*
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I am posting the following data in sample API(https://api.wit.ai/samples?v=20200921).
[{
       "text": "What is the response rate for the last 2 months",
       "entities": [
          {
            "entity": "intent",
            "value": "response_get"
          },
          {
             "entity": "wit$datetime",
            "value": "last 2 months",
            "start":30,
            "end":43
          }          
        ]
      }]

Now I have two cases.
CASE:1
 I have not any DateTime entity in the entity section. when I post the above data then it creates the utterance and also create the DateTime entity in the entity section. It works fine.

CASE2:
Delete the utterance which we have created in case-1. Delete only the utterance .dont delete the entity and intent.
Now I have already the DateTime entity in the entity section. Now when I post the above data then it's not created the utterance.

I am not able to understand why this happening if I have already a builtin entity. please let me know why this happening and what should I do for creating an utterance.
**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
324212385527094

**Comment by patapizza** [comment]
Case 1 shouldn't create the entity.
`POST /samples` has been deprecated. Please use `POST /utterances` instead.
