### ISSUE TITLE
Can we integrate wit.ai with IVR solution 

### ISSUE THREAD

**Issue by amroamer** [wit-ai/wit#1930]
**Hello,**

Is it possible to integrate wit.ai with an IVR solution ( Genesys, Cisco, Avaya, ..., etc)? If yes can anyone direct me with a link or documentation where to start?

**Thanks,
Amro**

**Comment by chessai** [comment]
As far as I know there is no (public) prior art on this, but it shouldn't be difficult if you're using the speech api, possibly with some preprocessing.
