### ISSUE TITLE
Utterance Page Not Working

### ISSUE THREAD

**Issue by assist-github** [wit-ai/wit#1931]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug

**What is the current behavior?**
The utterance page is not displaying any of the trained phrases for my intents. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Go to the utterance section > select any of the intents to see the associated training phrases 

**What is the expected behavior?**
Should see the list of utterances tied to the associated intent

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1292591027445318
<img width="946" alt="Screen Shot 2020-09-28 at 5 12 50 PM" src="https://user-images.githubusercontent.com/13651378/94591438-181e1600-0256-11eb-84c1-ee5c38c24885.png">

**Comment by ruoyipu** [comment]
Hi! I've tried filtering based on intent using the provided app ID: 1292591027445318 but could not reproduce. The utterances showed as expected.

The intents in the screenshot also do not match the intents in app 1292591027445318.

Please let me know if you're still experiencing issues.

**Comment by assist-github** [comment]
Hi @ruoyipu my apologies but I copied the wrong app ID. Here is the correct one: 2209560069163579

Yes, I am still experiencing the issue.

**Comment by ruoyipu** [comment]
Hi @assist-github! We recently landed a fix this morning where the pagination of the utterance list will properly reset when filters are added, which I believe addresses your issue.

Please do a hard refresh to get the latest version of the site and let me know if you're still experiencing issues.

**Comment by assist-github** [comment]
Hi @ruoyipu I am still experiencing this issue. I tried both on Chrome and Safari. Were you able to repo? The utterances show up fine on our other apps but this one it does not.

**Comment by ruoyipu** [comment]
Hi @assist-github, unfortunately I still cannot repro
<img width="1016" alt="Screen Shot 2020-10-07 at 12 54 25 PM" src="https://user-images.githubusercontent.com/33233694/95381079-7f624880-089c-11eb-9c0f-49769598ea5a.png">

**Comment by assist-github** [comment]
Hi @ruoyipu do you have any other thoughts on what might be the issue for me? This app is tied to the Facebook App on messenger and will be tied to the Facebook Inc account on Messenger as well. It's imperative that it functions correctly.

**Comment by assist-github** [comment]
Hi @ruoyipu checking back in to see if you have any updates?
