### ISSUE TITLE
Issue in training the app

### ISSUE THREAD

**Issue by jbharatrhodes** [wit-ai/wit#1933]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
When trying to review the live utterances, the toggle doesn't work, so can't train the utterances

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
->Use api to post some utterances
->Utterances will be listed in the application for review
->The down arrow button to review the utterances doesn't work
-> The X button also doesn't delete the utterances

**What is the expected behavior?**
The arrow should open and will allow us to review the utterances and train

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
676700103171666

**Comment by gnovis** [comment]
I have the same issue, after click on the utterance down arrow the following error occurs (same behavior in Firefox and Chrome):
![error](https://user-images.githubusercontent.com/4740230/95061115-771ed780-06fb-11eb-99af-4f0bceabaa86.png)

**Comment by jbharatrhodes** [comment]
> I have the same issue, after click on the utterance down arrow the following error occurs (same behavior in Firefox and Chrome):
> ![error](https://user-images.githubusercontent.com/4740230/95061115-771ed780-06fb-11eb-99af-4f0bceabaa86.png)

For the quick fix, I switched back to the old version, then went to inbox, expressions and trained the model

**Comment by ruoyipu** [comment]
Hi, thank you for the report! I can repro and we are investigating now.

**Comment by ruoyipu** [comment]
The fix has landed. Please do a hard refresh to get the latest version of the site and the down arrow should work now.

Let us know if there are any other issues. Thanks!

**Comment by gnovis** [comment]
Works fine now, thank you for the quick fix.
