### ISSUE TITLE
GET /message returning 500 error

### ISSUE THREAD

**Issue by ghost** [wit-ai/wit#1937]
when i try GET /message api after a while the first call will be 500 error showing error status as 

"StatusCodeError: 500 - "{\"error\":\"Something went wrong. We've been notified\",\"code\":\"unknown\"}"

the next api call will work successfully
the issue is now getting consistent on my app (341883513753784)

**Comment by joynahid** [comment]
I had an issue quite similar like this when I was trying to get the wit message directly from facebook. Then I switched to Wit API and It's working fine now.

**Comment by sabinchacko007** [comment]
I'm using wit api

**Comment by xavi1287** [comment]
tengo el mismo errorm cuando inteto recuperar un mensaje
{
    "error": "Something went wrong. We've been notified",
    "code": "unknown"
}
mi id de aplicacion es 1495667643935501

**Comment by ghost** [comment]
any updates

**Comment by ghost** [comment]
@kitchWWW why is my issue being neglected???

**Comment by Xueying-Wang** [comment]
Hi @sabinchacko007 sorry for the delay. We are still trying to figure out what's the issue with the app. I saw that most of the message API calls from your app look successful. Is there any specific utterance that you observe failing consistently?

**Comment by ghost** [comment]
any updates @Xueying-Wang @kitchWWW 
the issue is not yet resolved. Getting it consistently.please help.

**Comment by chessai** [comment]
Can't reproduce, all reported apps seem to have been deleted.
