### ISSUE TITLE
transcribed in Japanese results repeating the same 3 words (separated with "/") for every single word pronounced in a sentence

### ISSUE THREAD

**Issue by poeticcourt** [wit-ai/wit#1938]
Hello, I'm using Wit.Ai on discord as a bot, and transcribing is working fine apart from some inaccuracies and this issue of repeating the same 3 words. For those who don't understand Japanese, I'll write an example in English.

When you say: "open the entrance gate":
it transcribes like: "open/open/open the/the/the entrance/entrance/entrance gate/gate/gate"

Why is this happening? How to get rid of those 2 superfluous repeating words? I don't seem to find any settings regarding it on Wit.Ai's app page. Can anyone enlighten me?

**Comment by jtliao** [comment]
we're looking into it, this is definitely not expected

**Comment by jtliao** [comment]
this should be fixed now
