### ISSUE TITLE
App is stuck in on-going

### ISSUE THREAD

**Issue by 91ns** [wit-ai/wit#1939]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
The app is stuck in on-going state
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
log into the account, the state is always on-going
**What is the expected behavior?**
The app to be trained 
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1920697761332727

**Comment by Xueying-Wang** [comment]
Hi @91ns, I have triggered retraining for your app and the training was successful. Feel free to reach out if you have any more questions!
