### ISSUE TITLE
Intent "1 hr" not being marked up as "hour" unit

### ISSUE THREAD

**Issue by brightsparc** [wit-ai/wit#194]
Hi,

I was wondering if there is any plan to support the abbreviation "hr" for "hour" with the "wit/duration" entity?  I notice you support "min" for "minute".

Thanks,
Julian.

**Comment by l5t** [comment]
We open sourced our linguistic parser for specific entities like number, price and datetime here: https://duckling.wit.ai/. I just updated the rule to support "hr" (https://github.com/wit-ai/duckling/commit/fae6bae66fb9ad868cc6cc8395dfb608f1264c7a). We will push it to production in the next few days.

**Comment by brightsparc** [comment]
Thank you, i can now see the change pushed to wit.ai

The open source library is very nice.  Is there any reason you didn't
include a boolean or "yes"/"no" option into your library?

I notice wit ai has on/off but this is slightly different context.

**Comment by l5t** [comment]
![image](https://cloud.githubusercontent.com/assets/6992759/13166428/a8ff8cb8-d67c-11e5-89d8-2342ef19ed30.png)
Pushed to prod. As for the intent or entity yes_no, this is definitely on our list... stay tuned
