### ISSUE TITLE
Getting  500 Internal Server Error While Creating Entity

### ISSUE THREAD

**Issue by surajsingh92** [wit-ai/wit#1941]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
I am trying to create a built-in entity but when I post data in entity API, I am getting the following 500 internal error.
500
{
    "error": "Something went wrong. We've been notified",
    "code": "unknown"
}
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

I am posting the following data in entity post API("https://api.wit.ai/entities?v=20201014").

{
        "name": "wit$datetime",
        "roles": ["datetime"],
        "lookups": ["free-text", "keywords"],
        "keywords": []
}

when I post the above data I am getting the error
{
    "error": "Something went wrong. We've been notified",
    "code": "unknown"
}

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
324212385527094

**Comment by nausicaasnow** [comment]
Hey @surajsingh92, we have fixed the data issue so it has recovered now, should be unblocked! Thanks for calling out.

**Comment by surajsingh92** [comment]
Thanks, Now its work
