### ISSUE TITLE
App stuck in Training ongoing

### ISSUE THREAD

**Issue by leoyd** [wit-ai/wit#1943]
**What is the current behavior?**

My app on wit.ai is stuck in training ongoing, i want to apply a different intent to the sentence "i want to practise sport" but every time i try to train it it always get the wrong intent and don't care about the new one i'v just set for training, in definitive training the app do nothing.

**What is the expected behavior?**

expected behavior is when i train a sentence with a different intent than the old previously trained i can change it to the one i want after multiple train.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

https://wit.ai/apps/1969562516424162

thanks in advance, Best regard

**Comment by ghost** [comment]
my app also appid (658247231561340)

**Comment by nausicaasnow** [comment]
Retrained :)
