### ISSUE TITLE
I have been locked out of my Wit.ai and Facebook account

### ISSUE THREAD

**Issue by dessant** [wit-ai/wit#1946]
A week ago I have created a new Wit.ai account. Since I did not have a Facebook account, and the GitHub integration is being deprecated, I have signed up for a Facebook account first and logged into Wit.ai with it. I've then set up Wit.ai apps for production use, one for each supported language, and everything worked as expected.

A couple of days ago while I was logging into Wit.ai to check on my apps, Facebook has disabled my account, saying that I have violated their community standards, which makes no sense, since I have only used Facebook to log into Wit.ai.

They have asked for my photo for review, which I have uploaded. Today I've checked the account again and it is now permanently disabled, with no possibility of appeal.

By this point I have shared with Facebook my name, date of birth, my phone number, and my photo.

This looks like an automated takedown by Facebook, and the Wit.ai apps have remained live and operational.

Could you help me get access to my Wit.ai account again?

![Screenshot from 2020-10-18 21-15-24](https://user-images.githubusercontent.com/7513068/96376377-4a50d280-1187-11eb-854c-158b2de54f4e.png)

![Screenshot from 2020-10-18 21-16-27](https://user-images.githubusercontent.com/7513068/96376379-4d4bc300-1187-11eb-917e-e6c91af883e0.png)

**Comment by dessant** [comment]
Hi @jtliao and @patapizza, can you help me regain access to my Wit.ai account?

**Comment by My1** [comment]
honestly when was this even decided to ax github and more notably WHY? I just got a "reminder", didnt remind being told that before tho.

also considering what's happening on oculus right now this seems very hilarious to be honest

Edit: apparently this was kinda a side note in a newsletter from June, where they say:

"To better utilize Facebook infrastructure to ship new features to you, we will be transitioning to Facebook login only by December 30, 2020"

sure what features, social sharing and stuff? I at least am trying to distance myself from facebook and this is not helping

**Comment by jtliao** [comment]
Hey @dessant, unfortunately we can't disclose too much here, I've sent you an e-mail to the address listed on your GitHub profile with latest updates.

**Comment by dessant** [comment]
The account has been reinstated, thanks @jtliao for helping me regain access to my Wit.ai account!

**Comment by dessant** [comment]
Hello again @jtliao! Two days ago I've been notified by my users that the Wit.ai apps have stopped working. I've tried to log into my Facebook account to check what is wrong, but apparently my account was simply deleted, without any notice or warning, and there is no way for me to request support from Facebook for an account that no longer appears to exist.

I am saddened that we are at this point again, and I don't understand how and why are accounts purged without notice. I only use Facebook to log into Wit.ai, so this removal was likely made by error.

Would you be able to contact the appropriate team again to figure out what went wrong? Thanks a bunch for your help!

**Comment by My1** [comment]
> I only use Facebook to log into Wit.ai, so this removal was likely made by error

that's the "problem" likely. oculus users had similar issues when not posting their entire life into facebook.

**Comment by 1blockologist** [comment]
🔵
![image](https://user-images.githubusercontent.com/21366360/127576154-b4db07c5-89a9-4681-b23e-d14ef82b0046.png)

**Comment by NenaBas** [comment]
What seems to be the solution to this? I use wit.ai inside a project in my job and I created a facebook account for the entire project so all the team can have access to the app via the shared project facebook account. Is this a bad thing? One of the members does not have a facebook account (only messenger) and if he creates an account only to log into wit.ai the same thing will occur again.

Will it help if I add some info to the project's facebook profile (like a logo, site, email etc)?

**Comment by GeekCornerGH** [comment]
2023 here, and same thing happends last day.
I thankfully got my facebook account back, so I can log in, as of today.
Still not sure why it got falsely flagged, but if someone founds this, then just try appealing.
