### ISSUE TITLE
App is not training - needs to sync

### ISSUE THREAD

**Issue by fedariana** [wit-ai/wit#1948]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?** Bug

**What is the current behavior?** I have trained phrases in understanding but the app is not training the new phrases. It says it was last trained in June of 2020 even though I trained today. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Screenshot attached

**What is the expected behavior?**
The app should train to sync new phrases trained to intents within a few minutes. The button turns yellow to demonstrate that the training is occurring. 
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
686834745404420
<img width="1168" alt="Screen Shot 2020-10-26 at 1 16 05 PM" src="https://user-images.githubusercontent.com/68617768/97223748-6d821000-178d-11eb-9999-766b7491092f.png">

**Comment by jtliao** [comment]
Done, sorry about that
