### ISSUE TITLE
Utterance training is not working 

### ISSUE THREAD

**Issue by TaraNaser** [wit-ai/wit#1949]
Do you want to request a feature, report a bug, or ask a question about wit?
bug
What is the current behavior?
The Response was true, but the text was not trained
If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
I used the API https://api.wit.ai/utterances?v=20190904
The request:
[
  {
    "text": "تامين السفر بغطي بلد الاقامه؟",
    "intent": "_kb_8709_c98ed0ac___a9fe___43c7___b415___7718ef3163d7",
    "entities": [],
    "traits": []
  },
  {
    "text": "بلد الاقامه مغطيه بالتامين؟ ",
    "intent": "_kb_8709_c98ed0ac___a9fe___43c7___b415___7718ef3163d7",
    "entities": [],
    "traits": []
  },
  {
    "text": "بغطي التامين بلد الاقامه؟",
    "intent": "_kb_8709_c98ed0ac___a9fe___43c7___b415___7718ef3163d7",
    "entities": [],
    "traits": []
  },
  {
    "text": "هل يغطي التامين البلد المقيم بها الشخص المؤمن",
    "intent": "_kb_8709_c98ed0ac___a9fe___43c7___b415___7718ef3163d7",
    "entities": [],
    "traits": []
  }
]
The Response:
{
"sent": true,
"n": 4
}
What is the expected behavior?
The sent expressions to be trained correctly 
If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.
App ID: 2839573536265870

**Comment by jtliao** [comment]
#1955
