### ISSUE TITLE
How to give a phone number to send a message? Everytime it's interpreting the number as text.

### ISSUE THREAD

**Issue by Ansul90** [wit-ai/wit#195]

**Comment by l5t** [comment]
not sure I understand, can you provide an example of what you're trying to do?

**Comment by Ansul90** [comment]
So I am speaking something like "Send message to 8991267439" but it's getting translated to 
"Send message to eight nine nine one two six seven four three nine" and everytime it's either text or something more vague than this.

**Comment by l5t** [comment]
Thanks for the additional details. Unfortunately, we are using a generic language model for our speech layer and won't be able to improve this in the short term. In the meantime, we can probably update our open-sourced parser to take this into account (https://duckling.wit.ai/). We will do it in the next few days.
