### ISSUE TITLE
Can't Train Intents in New Wit UI

### ISSUE THREAD

**Issue by assist-github** [wit-ai/wit#1952]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug 

**What is the current behavior?**
Wit.ai will not let me add additional training phrases

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Copy this "is the climate really changing" 
2. Add it to this intent: "climate_change" 
3. Click Train and Validate

**What is the expected behavior?**
The training should be updated with the new phrase 

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2209560069163579

Additionally, my issue here was also never resolved: https://github.com/wit-ai/wit/issues/1931

Right now, I am having to revert back to the old Wit.ai version in order to get anything done. When this version is fully deprecated, I am not sure how I will be able to use this tool on behalf of our customers. Could these issues be directly tied to my facebook account? Here is my personal account within the org:
<img width="1279" alt="Screen Shot 2020-10-30 at 7 15 17 PM" src="https://user-images.githubusercontent.com/13651378/97764243-56705480-1ae4-11eb-8c24-a2b0297d45a3.png">

**Comment by jtliao** [comment]
@assist-github can you try again? there was an issue with the new UI for a bit

**Comment by assist-github** [comment]
Yes, both issues have been resolved. Thanks @jtliao!
