### ISSUE TITLE
Training button isnt working

### ISSUE THREAD

**Issue by kais509** [wit-ai/wit#1953]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
Training and validation button doesn't work
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Input an utterance or select a live utterance and fill in all the blanks
Press Train and validate
The button stays static and nothing happens
**What is the expected behavior?**
The utterance gets added to queue and the inputs are cleared
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
362162578551439

**Comment by liber2006** [comment]
Same here... application id 3462649767154100. @jtliao and @patapizza can you help us with that?

**Comment by jtliao** [comment]
This should be fixed now, sorry about that.
