### ISSUE TITLE
Expressions not being trained

### ISSUE THREAD

**Issue by TaraNaser** [wit-ai/wit#1955]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
Expressions are not being trained
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
API used: https://api.wit.ai/message?v=20200413

Train the expression
Test the expression
The intent was not understood (The intent was missing)

**What is the expected behavior?**
Expressions to be trained 
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID: 2573697389384605

**Comment by yuzh174** [comment]
Hi @TaraNaser, sorry for the late response. Could you be more specific about the issue? 
Do you mind to share the expression you are training? That would be very helpful.

**Comment by TaraNaser** [comment]
Hi @yuzh174 
The intent is: Balance
The expressions for the intent are:
متى موعد تجديد الاشتراك
متى انتهاء الاشتراك
بدي اعرف ازا خط الانترنت هاد مفصول او لاء
بدي استفسر عن موعد تجديد الاشتراك
ممكن استفسر عن فواتيري
مرحبا معلش بدي اعرف كم عليي دفع ل خط النت البيتي

Thank you for your help

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
