### ISSUE TITLE
Expressions are not being trained

### ISSUE THREAD

**Issue by TaraNaser** [wit-ai/wit#1956]
Do you want to request a feature, report a bug, or ask a question about wit?
Bug
What is the current behavior?
Expressions are not being trained
If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
API used: https://api.wit.ai/message?v=20200413

Train the expression
Test the expression
The intent was not understood (The intent was missing)

What is the expected behavior?
Expressions to be trained
If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.
App ID: 301943441078279

**Comment by jtliao** [comment]
#1955
