### ISSUE TITLE
backup zip file cannot be imported into new agent

### ISSUE THREAD

**Issue by rileyai-dev** [wit-ai/wit#1957]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
I am trying to create a development environment and cannot use a backup file to create a new agent.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Download backup zip
2. Create new agent
3. Attempt to import backup zip file

**What is the expected behavior?**
For the new agent to be created using the backup zip file

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2735542810013495

![image](https://user-images.githubusercontent.com/28606840/98379485-59ec6a00-2015-11eb-8301-96540dfc7c5d.png)

**Comment by jlariza** [comment]
I am experiencing the same issue. Any news about it?

**Comment by chessai** [comment]
Is this issue still persisting for you?

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
