### ISSUE TITLE
Error GET-ting utterances via REST API

### ISSUE THREAD

**Issue by kralikX** [wit-ai/wit#1959]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
*bug*
**What is the current behavior?**
A call to `GET /utterances?limit=10000` with my apps authorization token worked fine so far, however for last couple of days it returns:
```
400 Bad request
{
    "error": "Entity '838796200219811' not found",
    "code": "not-found"
}
```
However there is no ID passed into the REST API call so it clearly is not a Bad request, it is clearly 500 Internal server error. Also I cannot come up with any way how to alleviate the problem. Please advise.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Try the above request with given application. It works with other applications so it is probably messed up internal state of the application, which I don't know how to fix. I'd try to delete utterances and re-create them from scratch, but without successful GET I cannot delete them.

**What is the expected behavior?**
GET should work as expected, returning utterances.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
*999949443796240*

**Comment by jtliao** [comment]
This seems to be fixed

**Comment by kralikX** [comment]
I confirm, the bug doesn't show up any longer. Thanks!
