### ISSUE TITLE
Intents not showing up in the Understanding module

### ISSUE THREAD

**Issue by evoqai** [wit-ai/wit#1960]
I'm testing wit.ai and when I want to train my app I can not see any intents in the drop down list.

The list is blank. There are intents in the app though (I can see them when using the API).

Also the list of intents does not show up when I try to list them in the Intents section.

**Comment by asfyra** [comment]
We are also facing the same problem in our applications (App Id: 2841817995840539)

**Comment by PanoSpent** [comment]
Same with us!

**Comment by voiceflow-gallagan** [comment]
Same here (App Id: 655899228652455)

**Comment by dypham** [comment]
I have a same issue. But the API still working so its maybe a bug and they will fix it soon.

**Comment by JiangDongshuo** [comment]
i have the same issue

**Comment by getrekyyy** [comment]
Same issue here

**Comment by roots-ai** [comment]
Same issue here.

**Comment by jurneek** [comment]
Having the same issue.

**Comment by NxP4Code** [comment]
having the same issue.

**Comment by yuzh174** [comment]
Thanks for reporting this issue. I don't see this error on my end. Quick question: what browser and OS are you using?

**Comment by NxP4Code** [comment]
I tried Edge and Firefox.
![image](https://user-images.githubusercontent.com/56322272/98713846-c042f680-234d-11eb-8d8a-6fd1c596d811.png)

**Comment by NxP4Code** [comment]
![image](https://user-images.githubusercontent.com/56322272/98713907-d94ba780-234d-11eb-9294-fe47b44545cf.png)

**Comment by roots-ai** [comment]
On Chrome as well

<img width="731" alt="Screenshot 2020-11-11 at 12 05 45 AM" src="https://user-images.githubusercontent.com/1976061/98716554-c10d7400-23b1-11eb-9bf9-d5104f811f9d.png">

**Comment by Al-Kohollik** [comment]
Same here on Chrome. Also, adding a new intent causes the "+ Create Intent" button to go grey and load indefinitely for me (it's been loading for at least 20 minutes).
![wit not stopping loading intent](https://user-images.githubusercontent.com/52223836/98719654-e0ba8300-2344-11eb-8475-2882c7e80c74.JPG)

**Comment by jtliao** [comment]
We're looking into it. As a workaround, you can leverage the HTTP API https://wit.ai/docs/http/20200513/

**Comment by getrekyyy** [comment]
**I have just found that I can train my app if I switch to the previous version of wit.ai maybe it works for you**

**Comment by thecodearrow** [comment]
Yes please fix this ASAP! It's annoying to not be able to train the app on new utterances.

**Comment by vinayakpi** [comment]
Hi @thecodearrow you can switch to the older version and continue with your work. Even I was facing the same issue but after switching to the older version, there is no such problem :)

**Comment by kenchoong** [comment]
ya same issue 
And in Intent list and Utterance list is absolutely blank 

https://github.com/wit-ai/wit/issues/1962

**Comment by n3ih7** [comment]
the same issue here in Sydney
and in Intent list and Utterance list is absolutely blank

**Comment by jtliao** [comment]
Should be fixed now

**Comment by evoqai** [comment]
works, thank you
