### ISSUE TITLE
Persian Support

### ISSUE THREAD

**Issue by Lorymi** [wit-ai/wit#1961]
Hi. why Persian (Farsi) not supported for speech recognition?
You previously supported Persian. but now?
**Speech recognition is not supported for language: fa**

**Comment by jtliao** [comment]
We aren't able to support it anymore, we hope to bring it back at some point in the future.

**Comment by NGame1** [comment]
Guys, Please please bring its support back. 😓
What's happening that you can't support it you had it before! and it was one of the strongest 😥

**Comment by behroozbc** [comment]
please support back Persian

**Comment by parsalotfy** [comment]
Bring back our Persian language feature :unamused:

**Comment by mthri** [comment]
We need that, pls

**Comment by Lorymi** [comment]
https://github.com/wit-ai/wit/issues/1741#issuecomment-629370435
"**we hope by the end of the year.**"
@jtliao Any plans??

**Comment by pouyagholami** [comment]
Please bring it back.
today V need U. continue the help chain.

THANK YOU.

**Comment by NGame1** [comment]
@jtliao #1741  
we are at the end of 2020 😓😥
