### ISSUE TITLE
Utterance and Intent list not showing and take forever to load 

### ISSUE THREAD

**Issue by kenchoong** [wit-ai/wit#1962]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Utterance and Intent cant load any data 

**What is the current behavior?**

![Take forever to load](https://user-images.githubusercontent.com/8010129/98764834-98b86080-2417-11eb-8042-f539a47fdc62.png)

This screen already load for 1 hour, still no data showing up. 

In Intent tab, it absolutely no data at all

![No data in intent](https://user-images.githubusercontent.com/8010129/98764939-df0dbf80-2417-11eb-8bee-0eb6b2828886.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Just go to Intent tab and Utterance tab

**What is the expected behavior?**
should be having the Utterance and Intent list shown on screen 

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
362665568171976

**Comment by yuzh174** [comment]
Hi @kenchoong, what browser/OS are you using and have you tried to refresh the browser? Does it consistently happen or just one time?

**Comment by jtliao** [comment]
Should be fixed now

**Comment by kenchoong** [comment]
works..thank you
