### ISSUE TITLE
Wit.ai Ui problem: Previous Highlighted Utterance part disappear when a new part of utterance selected. 

### ISSUE THREAD

**Issue by kenchoong** [wit-ai/wit#1963]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug 

**What is the current behavior?**
This happen when trying to train a Utterance. I attached the screenshot as well. 

**1. I paste in a text I want to train, highlight the words I want to annotate as usual to set the entity for each word.** 

![w1](https://user-images.githubusercontent.com/8010129/99026169-5e7cc980-25a5-11eb-898f-19c4522f887d.png)

Highlight:  Vivian Lim - Wit/Contact 
Highlight:  45 bhabjabaja, 42000 port klang, Selangor - address 

**2. This is what happened:**

![w2](https://user-images.githubusercontent.com/8010129/99026433-e531a680-25a5-11eb-8fdb-88994efe8b13.png)

- In `Utterance` text input space, the address is not **Highlight**
- But in `Vivian Lim` it **Highlight** 2 color (Pink in background, green for underline) 

**3. Then I highlight again for the `019adf3456` part as `Phone Number` , then this happened:** 

![w3](https://user-images.githubusercontent.com/8010129/99026726-99333180-25a6-11eb-8d52-0fea2acf0ea3.png)

As you can see in the screenshot above 
- The address (Appear in the 1st picture above)  that at Entity section is disappear
- The phone number still not highlight
- The phone number is "appear" under "Wit/contact"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

I already describe it above. 

**What is the expected behavior?**

_This is the exact phase for the training._ 
> Vivian lim
> 45 bhabjabaja, 42000 port klang, Selangor
> 019adf5175

_When I highlight as below, it SHOULD appear 3 separated color:_ 
- Vivian lim 
- 45 bhabjabaja, 42000 port klang, Selangor
- 019adf5175

_Then each of them SHOULD appear in Entity section like this:_ 
- Wit/Contact        -> Vivian lim
- address               -> 45 bhabjabaja, 42000 port klang, Selangor
- phone_number   -> 019adf5175

When highlight a new phase in the String, the previous highlighted String _SHOULD NOT_ disappear. 

I sure if change to other Word, it still having the same problem. I try my best to address the situation. 

browser: Mozilla Firefox 
Language for the Wit app: Malay 

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
362665568171976

**Comment by yuzh174** [comment]
Hi @kenchoong , I don't think multiple lines are supported. If you change them to a single line, this should work.

**Comment by yuzh174** [comment]
@kenchoong, have you got a chance to try it if you change it to single line? let us know if it still doesn't work.

**Comment by kenchoong** [comment]
yes..with single line it works as usual..thanks

**Comment by yuzh174** [comment]
Thanks for the confirmation!

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
