### ISSUE TITLE
I can not select the option train and validate in understanding. This is blocked.

### ISSUE THREAD

**Issue by sephiroth2007** [wit-ai/wit#1964]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by yuzh174** [comment]
Could you share more details about the issue? What is the app ID and a screenshot would be very helpful.
