### ISSUE TITLE
how to set entity value in utterances API?

### ISSUE THREAD

**Issue by TaraNaser** [wit-ai/wit#1965]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question

how to set entity value in utterances API, how to add it such that I can send the synonyms in the expression?

**Comment by yuzh174** [comment]
If you are using http api, check the below two apis:
https://wit.ai/docs/http/20200513#post__utterances_link
https://wit.ai/docs/http/20200513#post__entities__entity_keywords__keyword_synonyms_link

**Comment by yuzh174** [comment]
@TaraNaser let us know if the provided apis don't help!

**Comment by TaraNaser** [comment]
@yuzh174 
Here is an example request of train sample api:  https://api.wit.ai/samples?v=20190904
[
  {
    "text": "I want to travel to America",
    "entities": [
      {
        "entity": "intent",
        "value": "Travel"
      },
      {
        "entity": "Country",
        "value": "USA",
        "start": 20,
        "end": 26
      }
    ]
  }
]
Here's an example of train utterances
[
  {
    "text": "I want to travel to America",
    "intent": "Travel",
    "entities": [
      {
        "entity": "Country",
        "start": 20,
        "end": 26,
        "body": "America",
        "entities": []
      }
    ],
    "traits": []
  }
]

How do I set the entity value in the utterances endpoint?

**Comment by yuzh174** [comment]
@TaraNaser , Are you trying to understand the format of this json? In the train utterances example, entity is "Country", and the specific value in this utterance for this entity is "America".

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
