### ISSUE TITLE
Get api returning status code 400 and response Unauthorized source IP address

### ISSUE THREAD

**Issue by homelander03** [wit-ai/wit#1966]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
GET API returning 400 status code for my app while calling the api from AWS EC2 instance.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Im using the api end point https://api.wit.ai to retrieve wit intents and entities.
2. It was working fine when i'm using it from my local system.
3. But while using same exact thing from aws ec2 instance(3.6.75.250), api call returning 400 Status code.
4. Response: {"error":"Unauthorized source IP address","code":"bad-request"}
**What is the expected behavior?**
1. It should not give 400, How can i fix this?
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
APP ID: 1588959071278535

**Comment by FengyangZhang** [comment]
Hi @homelander03, thanks for posting the issue, we are looking into this.

**Comment by FengyangZhang** [comment]
Hi @homelander03, it seems the ip 3.6.75.250 is blacklisted by our infra for some reason. Any chance you can switch to another ec2 instance?

**Comment by homelander03** [comment]
Hi I'm afraid not, I can't switch ec2 instance, Is there anything else I can do to make it whitelisted.
3.6.75.250
3.6.166.160
3.6.151.2

And also @FengyangZhang Can you help me with the reason, why it got blacklisted in the first place. Because this app is being used in our production environment as well. Due to that our project main feature got compromised.

**Comment by FengyangZhang** [comment]
Hi, I'm reaching out to see what we can do. Sorry for the inconvenience and I'll keep you updated.

**Comment by homelander03** [comment]
Yeah please, that would be helpful. Thank you.

**Comment by homelander03** [comment]
Any update?

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
