### ISSUE TITLE
Incremental ud

### ISSUE THREAD

**Issue by sreenivasarvind** [wit-ai/wit#1967]
Question: Is it possible to have incremental updates using existing data which would be trained on few manually entered samples?

Situation: Have json files with text and intents alone, need to train model with other entities based on manually entered examples.

**Comment by FengyangZhang** [comment]
Hi @sreenivasarvind , we don't do incremental training, every time new utterances are entered, the entire model will be retrained. I'm wondering what's your concern? Is it the training speed too slow?

**Comment by sreenivasarvind** [comment]
> Hi @sreenivasarvind , we don't do incremental training, every time new utterances are entered, the entire model will be retrained. I'm wondering what's your concern? Is it the training speed too slow?

I'm using app more for the NLU, not as a chatbot. I wish to train it using existing data without the entities initially and train - new incoming data automatically based on that. Doesn't seem possible but would like to know if I've missed something.

**Comment by FengyangZhang** [comment]
Sorry I might understood "incremental" wrong - so you mean your initial data has no entities but only intents, but the new incoming data will have entities? As long as you annotate the incoming data with the entities, I don't think there's a problem. Let me know if I'm missing something.

**Comment by sreenivasarvind** [comment]
> Sorry I might understood "incremental" wrong - so you mean your initial data has no entities but only intents, but the new incoming data will have entities? As long as you annotate the incoming data with the entities, I don't think there's a problem. Let me know if I'm missing something.

No, it's the other way round, the new data won't have annotated entities.

**Comment by FengyangZhang** [comment]
I see, so the problem is you want to be able to annotate the new data with the intent in the json file, also use the entities predicted by the model trained with your initial data? Yeah I think there's no fast way to do that, you either first call GET /message to get predicted entities then validate the new data, or have to manually validate the new data on the UI.

**Comment by sreenivasarvind** [comment]
> I see, so the problem is you want to be able to annotate the new data with the intent in the json file, also use the entities predicted by the model trained with your initial data? Yeah I think there's no fast way to do that, you either first call GET /message to get predicted entities then validate the new data, or have to manually validate the new data on the UI.

Got it, thank you so much!
