### ISSUE TITLE
Wit.ai UI Issue: Trained utterances not showing anywhere

### ISSUE THREAD

**Issue by SirFace1** [wit-ai/wit#1969]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
Newly trained utterances are not showing up anywhere in the Wit.ai user interface.
Unable to locate them on either of the following screens:
- Understanding Tab
- Management > Utterances Tab

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Creating Utterance
![image](https://user-images.githubusercontent.com/63440756/100404072-98c18d00-30b4-11eb-974c-8054ab2de62c.png)

2. Training ongoing
![image](https://user-images.githubusercontent.com/63440756/100404116-b4c52e80-30b4-11eb-9650-d3ee5f9f7b0d.png)

3. & 4. New utterance not added to 'Understanding' or 'Utterances' tabs
![image](https://user-images.githubusercontent.com/63440756/100404126-be4e9680-30b4-11eb-9a68-32c49c8fe46a.png)
![image](https://user-images.githubusercontent.com/63440756/100404200-edfd9e80-30b4-11eb-83ec-d18847faa735.png)

Note: Additional error found with data export attempt
![image](https://user-images.githubusercontent.com/63440756/100404274-23a28780-30b5-11eb-9abe-740538cf11f6.png)

**What is the expected behavior?**
Newly trained Utterances show up in:
- Understanding Tab
- Management > Utterances Tab

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID: 2262948170392071

**Comment by jtliao** [comment]
Seems to be fixed, closing.
