### ISSUE TITLE
JSONP callback with a "." (dot) in name no longer works

### ISSUE THREAD

**Issue by tennisgent** [wit-ai/wit#197]
We've been using the JSONP text api for months via Angular and it's been working great. But in the last couple of days, our JSONP callbacks stopped working. 

When you use [Angular's `$http` library](https://docs.angularjs.org/api/ng/service/$http#jsonp) to make a [`$http.jsonp(...)`](https://docs.angularjs.org/api/ng/service/$http#jsonp) call, it handles the global callback by namespacing it under `window.angular.callbacks._<some_number>`. For example, the following used to work just fine:

```
GET https://api.wit.ai/message?access_token=<token>&callback=angular.callback._2&q=<some_text>
```

But we noticed that this morning, this now returns a `400 Bad Request` with this response:

```
{
error: "Bad JSONP callback",
code: "bad-jsonp-callback"
}
```

If we use a callback without a `.` in the name, it works. For example:

```
window.CALLBACK = function(resp){ ... };
```

with

```
GET https://api.wit.ai/message?access_token=<token>&callback=CALLBACK&q=<some_text>
```

still works great, but 

```
window.CALLBACKS = { _0: function(resp){ ... } };
```

with

```
GET https://api.wit.ai/message?access_token=<token>&callback=CALLBACKS._0&q=<some_text>
```

receives that `400` error.

**I'm not sure what you guys changed, but we can we still allow callbacks with a `.` in the name?** It's totally broken our site now and we are having to scramble to come up with a new method of making our requests.

**Comment by l5t** [comment]
Thanks for reaching out. We did update the code on our side due to a security issue but can definitely bring back the ```.``` Can you share the URL of your website so that we can test?

**Comment by blandinw** [comment]
@tennisgent This should be fixed now. Can you confirm?

**Comment by tennisgent** [comment]
Great. Thanks for the quick response!

Our site is https://deafi.sh. You can test that everything is working by simply doing a search in the main **Create a new hook** search field on the page.

Let me know if you have other questions. Thank you!

**Comment by tennisgent** [comment]
It's working great!!!! That was some fast turn around! Thank you!

I'll close this issue out. :smile:
