### ISSUE TITLE
"Training Ongoing" never finishes [Bug Report]

### ISSUE THREAD

**Issue by roots-ai** [wit-ai/wit#1970]
App Id: 783739145520383

Status for training never changes from "Training Ongoing", though nothing has been trained last few days, and even before that only a few queries were run, after which the status turned this.

Also, it doesn't show the correct responses for the current data in training mode.

Is Wit stable for production? My experience so far has not been good.

**Comment by kitchWWW** [comment]
Hello! Thank you for bringing this to our attention. I've restarted the training on your job, please post again if it runs into issues. Issues with not showing the correct responses from the data could be tied to restarting this training job, so if the issue persists after training is finished, please create a new ticket and we'll be happy to look into it.

Wit.ai is stable for production, and has been serving thousands of developers for the past seven years. We always appreciate feedback on our services, and if you have any bugs, issues, or actionable feedback, we are always happy to take a look and help out.
