### ISSUE TITLE
Training Ongoing forever!!

### ISSUE THREAD

**Issue by vantony1** [wit-ai/wit#1971]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

502750853982978 : App ID

Hello, I am trying to train some basic utterances and the training has been stuck at ongoing for the last hour. I need this to get trained since my deadline is tomorrow. can someone please help??

**Comment by wangsnowyin11** [comment]
Hi, I have re-trained the app for you, now the training is done. Sorry for the inconvenience!
