### ISSUE TITLE
App stucking in training

### ISSUE THREAD

**Issue by HeyArian** [wit-ai/wit#1972]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
App is stuck in "Training ongoing".
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open the app. Wait until the app is done training. Training never stops (even though it indicates it took last than one minute last time) 
**What is the expected behavior?**
App is expected to finish training in some time. 
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
3455768221204310

Thanks in advance for helping! :)

**Comment by wangsnowyin11** [comment]
retrained the app for you, sorry for the incovenience!
