### ISSUE TITLE
App not exporting 

### ISSUE THREAD

**Issue by jurneek** [wit-ai/wit#1973]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
When trying to export a zip of the app data I'm getting an error message 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2709067149407185

**Comment by jtliao** [comment]
Fixed
