### ISSUE TITLE
Can't train entities 

### ISSUE THREAD

**Issue by jurneek** [wit-ai/wit#1974]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question/feature
**What is the current behavior?**
With the wit update you can't train entities allow they have to be trained with an in intent can this be updated? 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by mnauf** [comment]
My app id is 212317900303131. I have updated the entity in my add but now it also shows the old one as an entity and also the new one

**Comment by jtliao** [comment]
This is no longer supported, since intents are now considered first-class citizens. A workaround for your use case would be to have a dummy intent for these utterances.
