### ISSUE TITLE
NLP not working 

### ISSUE THREAD

**Issue by btanreb** [wit-ai/wit#1976]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug.

**What is the current behavior?**
Wit.ai always return error: "Something went wrong. We\'ve been notified".
NLP not working

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I get this error for every message to our chatbot

**What is the expected behavior?**
The expected behavior is for the nlp to return correct entities

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2758054720947789

**Comment by hajahim** [comment]
Hello,

On our side too, we have facing this issue

Screenshot attached
<img width="1037" alt="Screenshot 2020-12-16 at 14 38 24" src="https://user-images.githubusercontent.com/6651353/102338810-c318b300-3fad-11eb-9af8-9a7aeaff9d53.png">

**Comment by Wikhar** [comment]
Hi, 

Same ... 

![image](https://user-images.githubusercontent.com/47305575/102380772-9e7e0480-3fc8-11eb-80f4-f5d1d325aa6e.png)

**Comment by jragunath** [comment]
Hi Team, We are having the same issue. We have an integration with Facebook Messenger and the nlp object that comes in the Webhook event comes with an error :(

```
"nlp": {
  "errors": [{
    "code": "unknown",
    "message": "Something went wrong. We've been notified"
  }]
}
```

**Comment by Tomaaso** [comment]
Hi guys, 

Same here .. 

![image](https://user-images.githubusercontent.com/47305575/102381647-c6219c80-3fc9-11eb-9085-685325382991.png)

**Comment by jragunath** [comment]
Hi Team, Any update on this? We have also emailed the problem to help@wit.ai 
If you need any info, please let us know. Thanks in advance!

**Comment by PP-Wit-AI** [comment]
Impacted Wit apps for us are below.  Note these work fine on a test Facebook App but not on our production Facebook App.

2144879372219060
1696109917104362
1626751147410281
1713630622010520
2419045264788033
1741133792592343
1674468652621354
1702008049845948
1905211682846112
2054944167879164
1646772502065548
1720888384645508
1901522079860808
1756781464383763
1669523386418862

**Comment by PP-Wit-AI** [comment]
We've confirmed the issue seems to only be impacting pages showing up as affected by the EU changes: https://developers.facebook.com/docs/messenger-platform/europe-updates. just in case this helps anyone else.
My guess is that this is related to getting the locale or something else that helps Facebook/Wit determine which language model to use for a conversation/message.
Exporting and creating a new app, updating the token in Facebook app doesn't help.

(btw this is not a Wit employee, we just named our github account this way for managing the Wit account for our company).

**Comment by Tomaaso** [comment]
Hello so someone have a solution ? The problem persist for me.

My app ID : 742501339691107

Regards.

**Comment by PP-Wit-AI** [comment]
This issue is back for us again this week.  Anybody find any solutions or workarounds?

**Comment by modaresimr** [comment]
i confirm this issue is because of the region
I have two user:
- one from non europian country: nlp works well
- from europian country: nlp shows error

**Comment by matt0fer** [comment]
Was this ever solved? I am affected too :/
