### ISSUE TITLE
Lost my wit account

### ISSUE THREAD

**Issue by injaan** [wit-ai/wit#1977]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
*question*

**What is the current behavior?**
*Lost my wit account. but I have working api tokens and they are working well but I need to manage my wit apps how can I find my wit account (connected email address, github account or facebook account anything (any hints) would helpful)*

**Comment by chessai** [comment]
Were you using GitHub login?

**Comment by injaan** [comment]
thank you, problem is solved
