### ISSUE TITLE
My Apps dissapeared

### ISSUE THREAD

**Issue by injaangames** [wit-ai/wit#1979]
*bug*

**My Apps dissapeared**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**login to wit.ai by Github account and my apps hidden or dissapeared**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
"My Wit account is https://wit.ai/injaan"

**Comment by adityaprasanna** [comment]
The same happened to us as well. Extremely disappointing.
