### ISSUE TITLE
Wit Samples is not training 

### ISSUE THREAD

**Issue by TaraNaser** [wit-ai/wit#1980]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
I am training using POST https://api.wit.ai/samples?v=20190904, it returns "sent": true
But I can't find the trained expressions in 
GET https://api.wit.ai/samples?v=20190904&verbose=true&limit=3000 
I also tried training it in utterances api, same issue.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Request: [
  {
    "text": "بدي اتعرف على الرؤيه والرساله",
    "entities": [
      {
        "entity": "intent",
        "value": "{intent_name}"
      },
      {
        "entity": "{entity_name}",
        "value": "الرؤيه والرساله",
        "start": "14",
        "end": "29"
      }
    ]
  }
]
Response:
{
  "sent": true,
  "n": 1,
  "WARNING": "DEPRECATED"
}
Then check if the expression was added in GET https://api.wit.ai/samples?v=20190904&verbose=true&limit=3000 
**What is the expected behavior?**
To find the expression in GET https://api.wit.ai/samples?v=20190904&verbose=true&limit=3000 
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID: 3682946661741215

**Comment by lintaocui** [comment]
close the old thread. Please open a new one if you still see the issue.
