### ISSUE TITLE
Transfer App ownership error happening 

### ISSUE THREAD

**Issue by jurneek** [wit-ai/wit#1986]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
when trying to transfer ownership to another person I'm getting an error message 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
This is happening to several apps

**Comment by ChrisyShine** [comment]
Can you provide all the app IDs that are affected? The app IDs will help us to locate the problems for your apps.

**Comment by jurneek** [comment]
@ChrisyShine here are the following app IDs 
3155598637999856
3209404729141526
786369538869025

**Comment by ChrisyShine** [comment]
@jurneek We found that the new app owner doesn't have a valid email address registered in our system. The app ownership transfer process will send an email to the new creator to accept the transfer. So can you ask the new app owner to double check the email information in our system?
And if you are sure the email settings are good, and you are still not able to transfer the ownership to the new owner. Can you share all the app IDs that you want to transfer and the new app owner's wit username? We can help to do the app transfer from our end. Thanks!

**Comment by jurneek** [comment]
@ChrisyShine there's no where I seeing to edit account information where do I go for that

**Comment by ChrisyShine** [comment]
@jurneek Can you just share all the app IDs that you want to transfer and the new app owner's username? We will help to do the app ownership transfer.

**Comment by jurneek** [comment]
@ChrisyShine can you just tell me how to update the accounts email address or can I give you the users name and email address to update because we have to transfer several accounts and update tokens right after this will take some time

**Comment by ChrisyShine** [comment]
@jurneek We can help to update the email for the new app owner. Can you share the wit username and email address for the new app owner?

**Comment by jurneek** [comment]
@ChrisyShine yeah can you just updated this account it's jurneesimonton and email is jurnee@paradox.ai

**Comment by ChrisyShine** [comment]
@jurneek The email address has been updated, can you retry the app ownership transfer. And if it still fails, can you just list all the app IDs that need to be transferred?
