### ISSUE TITLE
Training samples is not working

### ISSUE THREAD

**Issue by TaraNaser** [wit-ai/wit#1987]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
Trained samples are not being trained on POST https://api.wit.ai/samples?v=20190904
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Request: [
{
"text": "I have a question",
"entities": [
{
"entity": "intent",
"value": "{intent_name}"
}
]
}
]
Response:
{
"sent": true,
"n": 1,
"WARNING": "DEPRECATED"
}
**What is the expected behavior?**
To find them in GET https://api.wit.ai/samples?v=20190904&verbose=true&limit=2000
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App IDs:  1240908789617975 and 338694930884714

**Comment by ChrisyShine** [comment]
@TaraNaser Can you take a look at our latest API documents, and see if `GET /utterances` and `POST /utterances` work?
