### ISSUE TITLE
Python install on an AWS AMI machine & Ubuntu Machine unicode decode error

### ISSUE THREAD

**Issue by thecannoli** [wit-ai/wit#199]
I am seeing a problem on two different instances of AWS servers. One running the base Amazon AMI and the other running an Ubuntu image. The error looks like this:

sudo pip install wit
Downloading/unpacking wit
  Downloading wit-1.1.tar.gz
  Running setup.py (path:/tmp/pip_build_root/wit/setup.py) egg_info for package wit

Installing collected packages: wit
  Running setup.py install for wit
    Retrieving platform-specific libwit library... libwit-64-linux.a
    building 'wit' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Ilibwit/include -I/usr/include/python2.7 -c pywit.c -o build/temp.linux-x86_64-2.7/pywit.o
    pywit.c:18:18: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     static PyObject *pywit_close()
                      ^
    pywit.c:57:18: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     static PyObject *pywit_voice_query_stop()
                      ^
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/pywit.o -Llibwit/lib -lwit -lrt -lsox -lssl -lcrypto -ldl -lpthread -lrt -lgcc_s -lpthread -lc -lm -o build/lib.linux-x86_64-2.7/wit.so
    /usr/bin/ld: cannot find -lsox
    /usr/bin/ld: cannot find -lssl
    /usr/bin/ld: cannot find -lcrypto
    collect2: error: ld returned 1 exit status
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/wit/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-3NYiVw-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

Retrieving platform-specific libwit library... libwit-64-linux.a

running build_ext

building 'wit' extension

creating build

creating build/temp.linux-x86_64-2.7

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Ilibwit/include -I/usr/include/python2.7 -c pywit.c -o build/temp.linux-x86_64-2.7/pywit.o

pywit.c:18:18: warning: function declaration isn’t a prototype [-Wstrict-prototypes]

 static PyObject *pywit_close()

                  ^

pywit.c:57:18: warning: function declaration isn’t a prototype [-Wstrict-prototypes]

 static PyObject *pywit_voice_query_stop()

                  ^

creating build/lib.linux-x86_64-2.7

x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/pywit.o -Llibwit/lib -lwit -lrt -lsox -lssl -lcrypto -ldl -lpthread -lrt -lgcc_s -lpthread -lc -lm -o build/lib.linux-x86_64-2.7/wit.so

/usr/bin/ld: cannot find -lsox

/usr/bin/ld: cannot find -lssl

/usr/bin/ld: cannot find -lcrypto

collect2: error: ld returned 1 exit status

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/wit/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-3NYiVw-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/wit
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 235, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 52: ordinal not in range(128)

Please advise! I have tried checking Stackoverflow for this error, but everything I have tried is coming up short. Thanks for the help!

**Comment by andreimarcu** [comment]
Hi there, it seems you're missing some dependencies.

```
/usr/bin/ld: cannot find -lsox
/usr/bin/ld: cannot find -lssl
/usr/bin/ld: cannot find -lcrypto
```

Try ```sudo apt-get install python-dev python-pip curl libcurl4-openssl-dev libsox-dev``` and try installing from pip again.

--- 
ps: https://github.com/wit-ai/pywit is the repo for the python sdk

**Comment by thecannoli** [comment]
Andre!

You are the man! That worked! 

I figured I was missing something based on that too, but all the dependencies I was being told to try weren't working. How did you know I needed the ones you recommended based on those lines?

Thanks again!

**Comment by andreimarcu** [comment]
Hi,

The one-liner includes all the dependencies the python sdk should need, so even if you already have some installed, it will install the missing ones.

As far as telling from the error message, -lsox refers to the sox library, and -lssl, -lcrypto to the openssl library.

**Comment by thecannoli** [comment]
Hate to bother you again, but now I am getting an error telling me that wit doesn't have an 'init'... perhaps my install was wrong?

Traceback (most recent call last):
  File "wit.py", line 1, in <module>
    import wit
  File "/var/www/witTest/witTest/wit.py", line 4, in <module>
    wit.init()
AttributeError: 'module' object has no attribute 'init'

**Comment by andreimarcu** [comment]
I would suggest renaming your file wit.py to something different and try again since python will try to import that file instead of the wit library.

**Comment by thecannoli** [comment]
Oh man, thats a head-smack moment! Thanks man!

**Comment by thecannoli** [comment]
Well, I tried it out and I am still having the same error. I moved the file and renamed it to something random : gbh.py .Not sure what else to do.
