### ISSUE TITLE
issue in wit/contact

### ISSUE THREAD

**Issue by ghost** [wit-ai/wit#1990]
"Yes"  is catching as wit/contact.
appid:341883513753784

**Comment by ChrisyShine** [comment]
What is the expected prediction result for this utterance in your app? 
Can you try to add the utterance "Yes" and set the expected intent/entities for the utterance and train the model again?

**Comment by ghost** [comment]
@ChrisyShine  i have no intent to link to this. but i don't want "yes" to resolve as wit/contact

**Comment by ChrisyShine** [comment]
@sabinchacko007 Can you try the checkbox "Out of Scope", and train "yes" as "Out of Scope"?

**Comment by ghost** [comment]
@ChrisyShine  i have done that but still it is resolving to wit/contact

**Comment by ghost** [comment]
@ChrisyShine i dont think the issue is with my app. wit/contact is inbuilt entity so you have to make changes there.

**Comment by ChrisyShine** [comment]
@sabinchacko007 There are 2 solutions to the problem:
1. Remove wit/contact entity and prepare some data and train your custom contact entity.
2. Add a custom OutOfScope intent in your app and train "yes" with the custom OutOfScope intent. And the prediction for "yes" will be the custom OutOfScope intent with wit/contact entity. But in this case, you get the custom OutOfScope intent, so you can ignore the wit/contact entity.
