### ISSUE TITLE
Issue with Swedish input

### ISSUE THREAD

**Issue by harpie1der** [wit-ai/wit#1991]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

Likely bug for Wit.ai v2.

**What is the current behavior?**

It is currently not functioning as intended (I hope) with particular letters as well as spaces becoming underscore/_ instead of their intended letters.
I sent a short email a few months ago relating to this, but am yet to receive reply. See below for an example:

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

"Svågern är kär i öl." is the sample sentence I use, approximately translates to "My brother in love is in love with beer.". When I try add it as a new intent, Wit tells me that "Sv_gern_r_k_r_i_l_" already exists.

Which as you can see definitely isn't what I wanted to write. Do note that this is just a sample sentence, nothing can be correctly input using v2 as is.

To further clarify, I just access Wit.ai normally, log in via FaceBook, and tap intents in the menu. Following that I try to add any sentence to a similar result to the above example.

**What is the expected behavior?**

The intended behavior, as seen with the old version, is for "Svågern är kär i öl." to be added as is with no alterations. 

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2211729492230626

**Comment by ChrisyShine** [comment]
We will investigate the problem and get back to you later.

**Comment by ChrisyShine** [comment]
@harpie1der We no longer support whitespaces or some particular letters as intent name in Wit.ai v2. Can you use english letters and underscores to build your intent name?

**Comment by harpie1der** [comment]
I see. Thank you for the prompt response, I shall discuss it with my boss
in the morning. Best regards.
