### ISSUE TITLE
problem connecting wit.ai to a Messenger App

### ISSUE THREAD

**Issue by elawenisemir** [wit-ai/wit#1992]
Hello everyone, I created my first Wit.ai app (App ID 143969150821051)
and I wanted to connect it to a Messenger app (App ID 2831478360450551)
on my FB page (https://www.facebook.com/Testpage-101104035262973).
To do that, I created a Node app with Glitch (https://repeated-puddle-universe.glitch.me).
However, when I add a callback URL on the Messenger app, through a Callback URL and Verify token, it gives me this error message "The callback URL or verification token couldn't be validated. Please verify the provided information or try again later.". 

Not sure where is the mistake.

Thank you everyone.

**Comment by ChrisyShine** [comment]
@elawenisemir The problem is more like a Messenger app Webhooks settings problem. Did you check this document? https://developers.facebook.com/docs/messenger-platform/webhook

**Comment by elawenisemir** [comment]
Hi Chrisy, thank you for your answer. I solved the problem.
