### ISSUE TITLE
Rate limit on POST /apps

### ISSUE THREAD

**Issue by sohaibilyas** [wit-ai/wit#1993]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question
**What is the current behavior?**
I couldn't find any rate limit on POST /apps, just wanted to confirm this because I'm planning to create separate apps for all different clients' Facebook pages just to have increased rate limit per app e.g. POST /message 600 req/min
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by ruoyipu** [comment]
Hi @sohaibilyas!

Correct, the wit.ai documentation should be up to date so the POST /apps endpoint doesn't have a rate limit. Please let us know if otherwise. Thanks!
