### ISSUE TITLE
Version deprecated

### ISSUE THREAD

**Issue by iatechnologies** [wit-ai/wit#1994]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question

On this post 
https://medium.com/wit-ai/introducing-the-refreshed-wit-ai-3a7c603d325a
It says “We’re also deprecating API versions from before 20200513 (including Built-in NLP in Messenger Platform and Workplace), so we encourage you to upgrade your code by December 30, 2020"
Its a pain to update all code.

Until when can we use older API versions like `20170307`?
Is these version really unavailable by tomorrow, or I can always use it safely with the “v” parameter?
Thanks

**Comment by ruoyipu** [comment]
Hi @iatechnologies!

The API will continue to work with older versions if the 'v' parameter was specified, but will return the older response format.
