### ISSUE TITLE
Wit app is stuck at Ongoing 

### ISSUE THREAD

**Issue by TaraNaser** [wit-ai/wit#1997]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
Wit app is stuck at Ongoing
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Wit app not to be stuck at Ongoing
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID: 338694930884714

**Comment by Xueying-Wang** [comment]
Hi @TaraNaser, thanks for reporting the issue. I've manually retrained your app and the training job has finished.
