### ISSUE TITLE
Showing multiple intents

### ISSUE THREAD

**Issue by mjain1990** [wit-ai/wit#1998]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
BUG

**What is the current behavior?**
The app showing multiple intents with same name which is not allowed by wit platform and also we restrict the end user to create duplicate intent with same name.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
The image below shows the information of the duplicate intents and doesn't display the utterance for those duplicate intents.

![image](https://user-images.githubusercontent.com/4197782/105154874-fd86ea00-5b2f-11eb-80bf-7c8650606eae.png)

**What is the expected behavior?**
Single intent should be visible in the list of intents

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID: 166051884751833

**Comment by ramh** [comment]
Hi @mjain1990, we are currently not able to see multiple intents with the either duplicate names or the ones listed in the image attached. Can you confirm if you are still facing this issue? Thanks.

**Comment by mjain1990** [comment]
Hi @ramh , I checked the app again and found the same duplicate intents highlighted in the attached screenshot of the app intents. Please refer this app id: 166051884751833

Updated the app ID in the question.

**Comment by mjain1990** [comment]
Hi Team, any update on this?

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
