### ISSUE TITLE
Set a production mode

### ISSUE THREAD

**Issue by Willypol** [wit-ai/wit#200]
Hi, 

Is it possible to enable a "production" mode which, if turned on, could prevent all the messages from going into the inbox ? That would be great to manage the training of the app.

thanks !

**Comment by l5t** [comment]
Interesting idea. We haven't had the time yet to improve the Inbox to be more production ready but this is on our roadmap. Not sure if this can help, but you can use the additional param junk=true to prevent an expression to go to the Inbox or Logs. Also if you already validated an expression, it will never appear in the Inbox again.

**Comment by Willypol** [comment]
Thanks, that answers the need !
