### ISSUE TITLE
Delete my account

### ISSUE THREAD

**Issue by toby3d** [wit-ai/wit#2000]
I want to delete my account in the system due to disabling authorization through GitHub. There are no options in the interface to delete the account myself:
![profile options](https://user-images.githubusercontent.com/5412322/105837425-7edaf280-5ff0-11eb-815c-5ac80491be76.png)

And it requires a forced login via Facebook to switch to the new interface.
![sign in screen](https://user-images.githubusercontent.com/5412322/105837477-8e5a3b80-5ff0-11eb-85ce-6dbd1109d3f8.png)

There is no information about deleting an account in the platform documentation:
![email quote](https://user-images.githubusercontent.com/5412322/105837519-a16d0b80-5ff0-11eb-823c-9d7051028d44.png)

What should I do?

**Comment by toby3d** [comment]
The first thing that comes to my mind:
* Create a Facebook account;
* Log in through Facebook to the new wit.ai interface;
* Delete account in wit.ai;
* Delete the Facebook account;

But if this is the only workable solution, I don't have the swear words to fully describe my attitude to both platforms. In essence, it could be described as "get Facebook or get lost". ["You own your data"](https://wit.ai/faq), yeah? I don't think so.

**Comment by wangsnowyin11** [comment]
Hey sorry for the inconvenience! We normally don't expose ways for users to update accounts themselves. Since it's easy to cause issues when update info or delete their account.

Can you provide me with your email that you use for your account and I can help you to delete your account? Thanks!

Sorry again for the inconvenience and thanks for your patience!

**Comment by toby3d** [comment]
> Can you provide me with your email that you use for your account and I can help you to delete your account? Thanks!

I don't see your contributor badge or @wit-ai group membership. And an empty profile doesn't inspire confidence in me to share personal information.

**Comment by crashley1992** [comment]
Hi toby3d,

I am able to assist you with this issue. I will reach out to you via email for follow up on your request to delete your Wit.ai account.

Thank you,
Ashley

**Comment by toby3d** [comment]
> I am able to assist you with this issue. I will reach out to you via email for follow up on your request to delete your Wit.ai account.

Please, delete my `witty_hacker_OUHBDLI` account too, which be created by Facebook signin years ago.

**Comment by crashley1992** [comment]
@toby3d Your Wit.ai account for toby3d has been deleted. Please look at the email that was used to register your account for more details. 

I have also submitted your other account witty_hacker_OUHBDLI for deletion. I will reply to this thread when witty_hacker_OUHBDLI has been deleted.  

Have a great weekend!

**Comment by Nicholaiii** [comment]
Please delete my account too; https://wit.ai/Nicholaiii

**Comment by crashley1992** [comment]
@Nicholaiii please submit this request to help@wit.ai.

**Comment by toby3d** [comment]
> @crashley1992 Your Wit.ai account for toby3d has been deleted. Please look at the email that was used to register your account for more details.

No, my accounts was still not deleted and I still get your emails:
![изображение](https://user-images.githubusercontent.com/5412322/108216360-324c8800-7154-11eb-8e5c-1047e26d49e2.png)

**Comment by crashley1992** [comment]
@toby3d Apologies for the inconvenience. I verified your account was deleted, but you were still on the subscriber list for the emails. I have removed you from that. You should not be receiving any further emails.

**Comment by SanFra13** [comment]
I apologize for my bad timing,

Would Wit.ai Support be so kind to please close my account?
I would like to close my account now, and have my
 - login
 - personal
 - subscriber list of emails
 - etc. data
removed from wit.ai and its affiliates.
Thank you in advance, and again, I apologize for asking on the 26th of February. (I thought I could do it by myself)

Regards,
SanFra13

**Comment by crashley1992** [comment]
@SanFra13 Please email help@wit.ai with your request to delete your Wit.ai account.

Thanks!
