### ISSUE TITLE
App is stuck in training

### ISSUE THREAD

**Issue by HeyArian** [wit-ai/wit#2001]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
App is stuck in "Training ongoing".
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open the app. Wait until the app is done training. Training never stops (even though it indicates it took last than one minute last time)
**What is the expected behavior?**
App is expected to finish training in some time.
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
3455768221204310

This is the second time we've encountered this error, is there any way to prevent (or lower the chances of) this happening? Thanks in advance for helping! :)

**Comment by rrakso** [comment]
Me to!!
Guys! This has happened after the switch to "better" version (...), my app is still training for three days! 

---
My app ID: **2359406400815056**

**Comment by rrakso** [comment]
@patapizza please help!

**Comment by patapizza** [comment]
@HeyArian @rrakso done!

**Comment by HeyArian** [comment]
Sorry for reopening this issue, but accidentally left the wrong App ID in the starting message. The correct App ID is 790110095172328. Sorry for not being careful enough when submitting the issue, but I hope you'll be able to reset training on this ID.
