### ISSUE TITLE
Unable to upload data on Wit

### ISSUE THREAD

**Issue by 360Rinnie** [wit-ai/wit#2003]
Hi Wit Support

This is Rinnie from 360 SMS. I have signed up at wit.ai. Linked it with the Facebook account named Sarah Watson.App Name: 360SMS- Unsub.

I want to **upload training data** on wit but **I don't see an option to upload the data in one go**. The only option I see is manually entering the data, which is extremely time-consuming, considering the large amount of data I have. 

Can you please help me get this done more quickly?

Thanks
Rinnie

**Comment by patapizza** [comment]
Hi, you can use the [POST /utterances](https://wit.ai/docs/http/#post__utterances_link) API.
