### ISSUE TITLE
Question about choosing from a menu

### ISSUE THREAD

**Issue by n-gram-hub** [wit-ai/wit#2006]
Hi, I'm very new to WIT and I'm here only to ask a question about training with WIT.

I should do the following:

- a client GUI displays the menu of a restaurant;
- the user can choose items from this menu (using voice: I should send WIT a file);
- of course, the user can choose *some* items, not all the menu;   :-)

My question: how can I train WIT to recognize what the user choosed? Do I have to train WIT to understand any possibility? Should I create one utterance per menu item? Or one utterance with ALL the menu items? ...

An example of sentence: "I want one item1, a couple of item2, three item3, one item4".

Any help is appreciated.

Thanks in advance   :-)

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
