### ISSUE TITLE
Algorithm and Model Details

### ISSUE THREAD

**Issue by ashispapu** [wit-ai/wit#2008]
Hi Team,
Thanks for the repo. I'm trying to understand the underlying algorithms on which the intent and entity classification models are trained for different languages. It would be helpful if any reference/explanation is shared. It becomes very important to explain the model's prediction for different customers.

Thanks for your support.

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
