### ISSUE TITLE
Extracting name entity from the input

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2009]
Hi,

In our chatbot we have a requirement to identity user's name from an input. We are expecting the inputs as below
My name is XXXX
I'am XXXX
It's me XXXX

We have to fetch XXXX keyword from user reply.
Please advice how should we train our wit app to extract the name entity from the input.

Thanks

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
