### ISSUE TITLE
Validate Expression not working

### ISSUE THREAD

**Issue by condem** [wit-ai/wit#201]
Hi,

I'm training my wit app with new expressions but sometimes Wit does not validate them at all, that means we cannot submit them to Wit via web app. Looks like the app is not stable. Maybe there's a limit on the number of calls?

Thanks
Manuel

**Comment by l5t** [comment]
Hi Manuel,
Thanks for reaching out. Can you provide more details on what you were doing and what you expected to help@wit.ai?
Thanks
Laurent
