### ISSUE TITLE
Cannot post built-in entities to app

### ISSUE THREAD

**Issue by nikolaikk** [wit-ai/wit#2011]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
I am trying to create a built-in entity but when I post data in entity API, I am getting the following error

{"error":"Something went wrong. We've been notified","code":"unknown"}

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I am executing the following command:

curl -XPOST  'https://api.wit.ai/entities?v=20210205'\
  -H "Authorization: Bearer BLABLA12MYTOKEN34BLABLA" \
  -H "Content-Type: application/json" \
  -d '{"name":"wit$message_body",
       "roles":[]}'

**What is the expected behavior?**
Posting a built-in entity wit/message_body. I've tried other built-in entities, it also did not work out.
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
169013484738584, 3668156299930068 - it happens on any App I've created.

Similar issue was mentioned and solved here #1941

**Comment by dupengling** [comment]
Hi @nikolaikk 

Sometimes the built-in entities may not work well. Can you try creating your own entity and validating the necessary samples to make it best fit your case? Thanks

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
