### ISSUE TITLE
Error Status 400, on local development with NGROK

### ISSUE THREAD

**Issue by tritium01** [wit-ai/wit#2013]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Issue
**What is the current behavior?**
Local Development using the pywit example file returns 400 error. I am using the private token key
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
wit.wit.WitError: Wit responded with status: 400 (Bad Request)
**What is the expected behavior?**
I understand it's pywit related but since the issue seems to be with the authorization I am posting the issue here.
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
421448005634754

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
