### ISSUE TITLE
you erased my bot i've already trained for so long . all the entries are gone WTF.

### ISSUE THREAD

**Issue by yoddaa** [wit-ai/wit#2014]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by yuzh174** [comment]
Hi @yoddaa, sorry to hear what happened. Could you describe more what happened? What was the bot and what were included in it?

**Comment by yoddaa** [comment]
i found it in the facebook app but its like i need to retrain it again. i
will let you know
