### ISSUE TITLE
Training taking so long

### ISSUE THREAD

**Issue by amit2k761** [wit-ai/wit#2015]
My app is still training and its been 1 day

**Comment by yuzh174** [comment]
Hi @amit2k761, 

Could you provide more information about your app? What is the App Id and what recent changes you made for the training? If you have any precise time about when you started the training, it will be very helpful as well.

**Comment by amit2k761** [comment]
Hi @yuzh174 I added some entities and trained the bot. Why do you need app id for same. ?

**Comment by amit2k761** [comment]
@patapizza Can you pls help for the same

**Comment by amit2k761** [comment]
App id is 204729828065842

**Comment by yuzh174** [comment]
Sorry about the issue. The training is complete now. This shouldn't happen often but let us know if you see issues like this again. We can quickly fix it.
To expedite the process. Please send us the app ID with the request. That helps in our process.

**Comment by amit2k761** [comment]
@yuzh174 I think my app got stuck again in training . App id is same as above 204729828065842 . Is this happening because I have lots of entities ? In my app I have around 100 entities.

**Comment by yuzh174** [comment]
Training is complete now. I will investigate why your app always takes longer to train.

**Comment by RibeiroAna** [comment]
@yuzh174 I'm having the same issue. My app id is: 289886732511215, it happened after I deleted a bunch of Entities keywords (the entity ID is 491832958680721). I let the app available for a colleague who still is laearning about NLP and she created a bunch of keywords that were not part of that entity, when I noticed what she have done I deleted all the keywords she created and after that the wit training just crashed, it is on "Training ongoing" like forever (before it took 1 minute or so).

**Comment by PanoSpent** [comment]
Hi i opened an issue here https://github.com/wit-ai/wit/issues/2090 and i am facing the same issue @yuzh174

**Comment by Toba99** [comment]
same is happening to me app Id 624225555631153

**Comment by chefkoch24** [comment]
hello, I faced the same problem today for my app id: 579792616852583

**Comment by doggeral** [comment]
Close the task since the training stuck issue has been fixed.
