### ISSUE TITLE
Context object (json) in GET message endpoint, what is it used for in the refreshed wit version? 

### ISSUE THREAD

**Issue by macscripter** [wit-ai/wit#2017]
Hi, honestly, the current documentation is not clear, at least for me regarding to the context json object that is sent as an optional parameter for /message endpoint. Can someone please, clarify what is it used for in the refreshed wit version?
Some easy examples would be greatly welcome!

If I put my own context in the request and receive a json object without any context (I sent previously), my question is what is its practical use?

Thanks in advance

**Comment by patapizza** [comment]
Hi, from the [documentation](https://wit.ai/docs/http/#context_link), it's to configure the resolution of the built-in entities `wit/datetime` and `wit/location`.
