### ISSUE TITLE
Please delete my account

### ISSUE THREAD

**Issue by madebynoxc** [wit-ai/wit#2018]
I don't have facebook account and I am not going to create one. Why there is no option to remove my account on the website?
The email you sent me is broken and doesn't have any useful links.
![image](https://user-images.githubusercontent.com/6795044/108112035-8cb9eb80-7063-11eb-91b7-99cd8ef915fa.png)

FAQ page doesn't even load...

I do not want my github account to be associated with wit anymore.
Thank you

**Comment by FengyangZhang** [comment]
Hi, the account is deleted. Thanks for the patience.
