### ISSUE TITLE
App is stuck in training again

### ISSUE THREAD

**Issue by HeyArian** [wit-ai/wit#2019]
**Do you want to request a feature, report a bug, or ask a question about wit?**
Bug
**What is the current behavior?**
App is stuck in "Training ongoing".
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open the app. Wait until the app is done training. Training never stops (even though it indicates it took 35 seconds last time)
**What is the expected behavior?**
App is expected to finish training in some time.
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
790110095172328

Thanks in advance for helping :)

**Comment by FengyangZhang** [comment]
Hi, I restarted the training and it's done now. Thanks for the patience.
