### ISSUE TITLE
Unable to start witd

### ISSUE THREAD

**Issue by KRens** [wit-ai/wit#202]
I am trying to start the witd-armv6 on my Raspberry pi, but when I execute the command, I get following output.
pi@max2play ~ $ sudo ./witd-arm &> witd.log &
[1] 3236

If I run it manually without outputting details I get:
pi@max2play ~ $ sudo sh witd-armv6
witd-armv6: 1: witd-armv6: Syntax error: word unexpected (expecting ")")
pi@max2play ~ $ sh witd-armv6
witd-armv6: 1: witd-armv6: Syntax error: word unexpected (expecting ")")

Fyi, the link in your documentation is broken:
https://wit.ai/docs/raspberry-pi/quickstart
The link on the words "witd-arm executable" returns a 404.

I downloaded it in the end from:
https://github.com/wit-ai/witd/releases

**Comment by KRens** [comment]
Additional comment:
The download is named: witd-armv6
But the documentation comment states:
sudo ./witd-arm ...

Do you see the difference?
Would be nice to update documentation as well.

**Comment by martinraison** [comment]
Hi, apologies for the late reply. We haven't had time to maintain witd lately, so your best bet is probably to call the HTTP API directly (https://wit.ai/docs/http/latest). Feel free to submit a pull request, though.
