### ISSUE TITLE
API Change 

### ISSUE THREAD

**Issue by jurneek** [wit-ai/wit#2020]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question/Help
**What is the current behavior?**
Are any of the APIs changing on Feb 28th once the github login is no longer available?
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by FengyangZhang** [comment]
Hi, the APIs are not changing with the deprecation of github login. If there's a change we'll update in https://wit.ai/docs/http/20200513/ and you can use API versioning to use older version.
