### ISSUE TITLE
Download .zip data is not working: Something went wrong

### ISSUE THREAD

**Issue by benrz** [wit-ai/wit#2021]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
Export the data is not working, it gives the following error: **Something went wrong. We've been notified**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
After clicking the "Download .zip with your data" button under the "Export Your Data" part, the error message is displaying

**What is the expected behavior?**
Download the .zip file

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2096249480457187

**Comment by FengyangZhang** [comment]
thanks for reporting! I'm looking into it

**Comment by benrz** [comment]
Thanks for the reply, I'll be waiting

**Comment by FengyangZhang** [comment]
Hi, removed some bad data and it should work now. Let us know if it doesn't!

**Comment by benrz** [comment]
It's working! thankyou
