### ISSUE TITLE
Cannot set a trait alone without a built-in/custom intent

### ISSUE THREAD

**Issue by SpeedyCraftah** [wit-ai/wit#2022]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?** Question

**What is the current behavior?** You cannot set a trait alone, you also have to add an intent before you can train.

**What is the expected behavior?** You should be able to set a trait alone without adding an intent, I know you can just add a random intent called anything but it seems very annoying having to do that.

I heard traits are better used for full-text predictions (in my case predicting if a piece of text is a question or not) than intents (say otherwise if this is false). 

Example:
![image](https://user-images.githubusercontent.com/45142584/108697077-47ca0500-74fa-11eb-96dd-8d7d0645c5b9.png)

(I also don't believe this is a bug hence why I labelled it as a question)

**Comment by FengyangZhang** [comment]
Hi @SpeedyCraftah , thanks for the question. This is how the utterance structure is designed currently. Intent and trait works the same, the difference is intent is unique for the utterance and should categorize the user intent, so we assume every utterance should have this. In your case it might be better to have an intent ask_question.
