### ISSUE TITLE
Please delete my account

### ISSUE THREAD

**Issue by sidbhatt11** [wit-ai/wit#2023]
I do not use wit.ai and I no longer want my GitHub account or email associated with wit.ai. Please permanently delete my account. 

Also, one should not have to raise an issue on GitHub for some admin task like this. Your FAQ page is also not very helpful.

**Comment by crashley1992** [comment]
@sidbhatt11 Thank you for the feedback. Can you please send this request to help@wit.ai. We'll be able to assist you more there.

**Comment by patapizza** [comment]
@sidbhatt11 You should now be able to delete your account directly right after logging in with GitHub. Thanks.
