### ISSUE TITLE
Utterances is not training all expressions

### ISSUE THREAD

**Issue by TaraNaser** [wit-ai/wit#2024]
Do you want to request a feature, report a bug, or ask a question about wit?
bug
What is the current behavior?
Trained texts for intents are not being trained
If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
I used the API https://api.wit.ai/utterances?v=20190904
The request:
[
{
"text": {text},
"intent": {intent},
"entities": [],
"traits": []
}
]
The Response:
{
"sent": true,
"n": 1
}
What is the expected behavior?
The Response was true, but the text was not trained
If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.
App ID: 2715834708531432

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
