### ISSUE TITLE
App wont start training when adding new utterances

### ISSUE THREAD

**Issue by VaggBout** [wit-ai/wit#2025]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug

**What is the current behavior?**
Despite adding new utterances from WitAI panel the app wont start training and the app is stuck on training complete saying it last trained at 12:11 PM.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Add new utterance from witai panel & click Train and Validate. 

**What is the expected behavior?**
Training should say Ongoing and apply new changes

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
467558157610250

**Comment by VaggBout** [comment]
As a workaround we created a new witai app, we imported the data from the previous one to the new application and now we are working our chatbot with the new application. Not an optimal solution but this issue can me marked as closed :)

**Comment by VaggBout** [comment]
Unfortunately the problem reappeared on the new app too. The application does not start training when adding new utterances. Could you help us as?
App ID of new application: 258366865911810

**Comment by lycai-fb** [comment]
Hi @VaggBout,
I've checked your app and I don't see the issue; it appears to have finished training at 6am today, and also successfully finished the retraining I scheduled.
Closing, but feel free to reopen if you continue to have issues.
