### ISSUE TITLE
App Data not showing 

### ISSUE THREAD

**Issue by jurneek** [wit-ai/wit#2026]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
When creating a new app using an export from an old app none of the data is showing only entities are available are the utterance aren't showing
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2583875375242957

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
