### ISSUE TITLE
Out Of Scope Function not working 

### ISSUE THREAD

**Issue by jurneek** [wit-ai/wit#2027]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
When training a phrase to out of scope the app is still picking up the phrase even though it's been trained to out of scope multiple times
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1504918609519459

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
