### ISSUE TITLE
Inconsistent response depending on query case - reproducible

### ISSUE THREAD

**Issue by avoinkov** [wit-ai/wit#2028]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
BUG

**What is the current behavior?**
No intent being sent in response (although it correctly resolved)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
REQUEST1
```
curl --location --request GET 'https://api.wit.ai/message?q=buy%20XL%20yellow&context=%7B%7D' \
--header 'Authorization: Bearer TOKEN' \
--header 'Content-Type: application/json'
```
RESPONSE1
```
{
    "text": "buy xl yellow",
    "intents": [],
    ...
}
```
REQUEST2
```
curl --location --request GET 'https://api.wit.ai/message?q=buy%20XL%20yellow&context=%7B%7D' \
--header 'Authorization: Bearer TOKEN' \
--header 'Content-Type: application/json'
```
RESPONSE2
```
{
    "text": "buy XL Yellow",
    "intents": [
        {
            "id": "898290500971755",
            "name": "buy_product_by_full_description",
            "confidence": 1
        }
    ],
    ...
}
```
Notice the difference between REQUEST1 and REQUEST2: it is the case of word "XL"

**What is the expected behavior?**
Expected that REQUEST1 and REQUEST2 get same response that is RESPONSE2

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2429a725-c4a3-42be-a948-8fb4f035b640 (It can be already deleted when you check this)

Also I would like to share this screenshot that shows that queries were parsed and resolved correctly
![correct](https://user-images.githubusercontent.com/22505887/110406703-516f7300-808b-11eb-8e8d-8e32a634fff6.png)

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
