### ISSUE TITLE
Wit AI got 500 (internal server error)

### ISSUE THREAD

**Issue by t-weilin** [wit-ai/wit#2029]
I have posted the issues in the link below. Basically, I got error 500 while using python to call speech api.

https://stackoverflow.com/questions/66576626/wit-ai-got-500-internal-server-error-while-using-python-api

**Comment by siyanew** [comment]
Is there any way to fix this ?

**Comment by t-weilin** [comment]
I think they have resolved the issues. It ran perfectly today. It's due to the internal issues I suppose.
BTW, I was using the simplify Chinese one, I am not sure about other languages.

**Comment by francescor93** [comment]
Any other feedback on this? I call speech API in a PHP project but I have been receiving error 500 for two days without having changed anything in my code:

`Server error: POST https://api.wit.ai/speech resulted in a 500 Internal Server Error response:
{
  "code": "wit",
  "error": "An error occurred in speech recognition."
}`

**Comment by t-weilin** [comment]
500 Internal Server Error happens on their server side. I have encountered the same issues using their python API. But, it worked fine the next day and I did not change my code. I think you might have to wait for them to fix it.

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.

**Comment by aneeshd27** [comment]
I tried this on a Google Colab notebook but I am receiving the internal 500 error.Perhaps it is beacuse I am using an online platform or something else?
