### ISSUE TITLE
Fails to add predefined entities through the API

### ISSUE THREAD

**Issue by rileyai-dev** [wit-ai/wit#2030]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
BUG

**What is the current behavior?**
Fails to send "wit$" entities through POST /entities endpoint. Returns `{ error: "Something went wrong. We've been notified", code: 'unknown' }`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Simply POST:
```json
{
    "name": "wit$location",
    "roles": [
        "location"
    ]
}
```
to /entities endpoint

**What is the expected behavior?**
Work

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
514480996202123

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
