### ISSUE TITLE
Speech recognition seems to fail a lot

### ISSUE THREAD

**Issue by backmeupplz** [wit-ai/wit#2031]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

It's probably a bug

**What is the current behavior?**

Speech recognition API returns errors

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Use speech recognition

**What is the expected behavior?**

Speech recognition should work

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

Probably can check `1614167535377114` or `1783239468423659`

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
