### ISSUE TITLE
wit/location isnt working

### ISSUE THREAD

**Issue by PanoSpent** [wit-ai/wit#2033]
I want to report a bug on wit ai. The built-in entity wit/location isnt working for new apps. I already haveolder apps where it
is still working, but on any new app i try to use it i simply can not. I can highlight a word and choose wit/location as the entity, but after that whatever i write is flagged as a location. Also it is impossible to delete the entity even though there is no apparent association with the app. Finally i want to mention that i use the wit/datetime built in entity without problems at the same app.

![Screenshot 2021-03-22 110457](https://user-images.githubusercontent.com/12428756/111965503-78538d80-8afe-11eb-84fe-f0d386899df2.png)
![Screenshot 2021-03-22 110429](https://user-images.githubusercontent.com/12428756/111965508-78ec2400-8afe-11eb-90f8-c21be74e53ba.png)

The app id where i experience the issue is 339053820531515

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
