### ISSUE TITLE
Adding response for intents in wit.ai

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2034]
Hi team,

Is there any possibility that we can add response to be triggered for an intent in wit.ai. 
Also can we pass context for specific intents from the wit interface.

Thanks

**Comment by ChrisyShine** [comment]
@anjaly wit.ai is a NLP only service for now.
You can develop your own service to achieve the features you mentioned.

**Comment by patapizza** [comment]
Hi @anjaly, we've recently launched the [alpha release of Composer](https://medium.com/wit-ai/introducing-composer-alpha-b3b808e1cdc3), a way to manage the dialogue state, support multi-turns and responses. [Check it out!](https://wit.ai/docs/recipes#respond-to-different-user-queries)
