### ISSUE TITLE
How to export 'Understanding' pending live utterances

### ISSUE THREAD

**Issue by unu-1** [wit-ai/wit#2035]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question

Is there a way for me to bulk export the utterances that appear in the 'Understanding' section of my app?
I would like to be able to classify them in another way than through the web interface.

Thank you,
qfavor

**Comment by ChrisyShine** [comment]
@qfavor Go to Settings page and click the button "Download .zip with your data". You will get a zip file. And if you unarchive the zip file, you can see a json file for utterances. You will get all the utterances from that json file. And you can read that json file and analyze the data.

**Comment by unu-1** [comment]
> @qfavor Go to Settings page and click the button "Download .zip with your data". You will get a zip file. And if you unarchive the zip file, you can see a json file for utterances. You will get all the utterances from that json file. And you can read that json file and analyze the data.

Thank you for the reply and sorry for the late response. Unfortunately, the way you described will only net me the already trained data. 

I want a way to export everything that's pending and which shows up in the 'Understanding' section of the app.

I still haven't found a way to do this. If anyone found a way, please let me know. Thank you!

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
