### ISSUE TITLE
App not training

### ISSUE THREAD

**Issue by jurneek** [wit-ai/wit#2036]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
I've marked a phrase to out of scope several times over the past 2 weeks but my app still picks it up I don't think the app is training properly 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1504918609519459

**Comment by ChrisyShine** [comment]
@jurneek What is the training status at the top right side of the page? Is it shown as Training ongoing or Training completed?

**Comment by jurneek** [comment]
@ChrisyShine complete

**Comment by ChrisyShine** [comment]
@jurneek Can you share the utterance for OutOfScope case? And we need enough data to improve the model quality. So can you try to annotate more similar sentences for the OutOfScope case and see if the model is improved?

**Comment by jurneek** [comment]
@ChrisyShine I have the phrase is "Is there anyway we can do between 10 and 12?" Additional this is issue has been happening when trying to train intents as well with this app

**Comment by ChrisyShine** [comment]
@jurneek Can you add more similar utterances for this sentence? There are many utterances in your app, so a single sentence may not be enough to get an accurate prediction result.

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
