### ISSUE TITLE
Export, then Import, fails!

### ISSUE THREAD

**Issue by lmessinger** [wit-ai/wit#2039]
**bug**

**What is the current behavior?**
a model saved to a file (Export Your Data). Then, I create a new app using the exported file (Import From a Backup) - the file exported exactly 1 minute ago. an error report says 'something went wrong. We have been notified'. Have you? this already happened a month ago

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
see above
**What is the expected behavior?**
not to crash

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
738692573720153

**bug**

**What is the current behavior?**
a model saved to a file (Export Your Data). Then, I create a new app using the exported file (Import From a Backup) - the file exported exactly 1 minute ago. an error report says 'something went wrong. We have been notified'. Have you? this already happened a month ago

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
see above
**What is the expected behavior?**
not to crash

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
738692573720153

![image](https://user-images.githubusercontent.com/1693213/113132060-a172cd00-9226-11eb-9a92-baa1bc711f1f.png)

**Comment by ruoyipu** [comment]
Hi @lmessinger,

Thank you for the bug report. We are investigating and will report back once the fix is landed.

**Comment by jlariza** [comment]
@ruoyipu this issue has been reported several times https://github.com/wit-ai/wit/issues/1957

I even reported it on the facebook community. Are there news about it?

Thank you

**Comment by ruoyipu** [comment]
Hi @lmessinger,

The fix has been pushed for the issue that appID 738692573720153 faced. Please let me know if the behavior continues.

**Comment by ruoyipu** [comment]
Hi @jlariza,

A fix has been pushed recently, please try again with your app. If the issue persists please let me know along with your app ID and I can investigate in more detail.

**Comment by lmessinger** [comment]
@ruoyipu thank you. i tried the same scenario - export and immediately starting a new app, and importing the exported file. now the import didn't crash - that's a progress. all the intents have been imported, BUT there are no utterances. meaning, the utterances haven't been imported. so the new model really doesn't understand anything of the previous one.
could you please provide a fix ASAP? that'd be great.

![image](https://user-images.githubusercontent.com/1693213/114347419-96486700-9b6d-11eb-9191-41a0f85c999b.png)

**Comment by lmessinger** [comment]
hi @ruoyipu thanks for that. i did try - import works. however, i got 500 when tried to get intents. the app id is 3875490032560370. an example utterance is How are you
can you please take a look? thanks!

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
