### ISSUE TITLE
Training same intent different entities versus two intents.

### ISSUE THREAD

**Issue by onionjake** [wit-ai/wit#204]
I am trying to train wit.ai how to display graphs for either groups of servers or specific server names.  I initially trained a single intent to understand either the server entity or the server_type entity. Both server and server_type are closed lists.  The result was wit.ai understood servers very well (the one I trained first) and never really was able to get server types.  I then removed that intent and created two intents:   show_server_graphs and show_server_type_graphs.  After training all of my initial input, wit.ai is super confused and cannot get either intent even close to right.

Perhaps it is because the distinction between the entities is so subtle?  For example:

servers = [web-1.production, web-3.production,database-2.production]
server_type = [web, database]

What would be the best way for me to train wit.ai to understand the differences between servers and server_types?

**Comment by l5t** [comment]
Thanks for contacting, it should work the way you set it up initially. Please contact us with the name of your wit app so that we can investigate at help@wit.ai
