### ISSUE TITLE
Api for finding App training status

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2040]
Hi,

Is there any api for finding if the app training is complete or not.
In our ui how can we show a status if the training is completed.

Thanks in advance

**Comment by ruoyipu** [comment]
Hi @anjaly,

We do not have such an api today, you will have to check it on the wit.ai site. Thank you for the feedback, we'll consider adding such an api in the future!

**Comment by anjaly** [comment]
Thanks @ruoyipu

**Comment by zjn0505** [comment]
https://wit.ai/docs/http/20200513#get__apps__app_link
It contains `training_status`

**Comment by patapizza** [comment]
As @zjn0505 said!
