### ISSUE TITLE
Websocket speech no longer returning results

### ISSUE THREAD

**Issue by jholt1** [wit-ai/wit#2042]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

Question/bug

**What is the current behavior?**

`wss://ws.wit.ai/speech_ws` is no longer returning results, has it been switched off? 

Returning:

```
["result",{"_text":"","entities":{}}]
```

**Comment by chessai** [comment]
This should be resolved. See https://github.com/wit-ai/wit/issues/2153
