### ISSUE TITLE
Bot refusing to train on new utterances

### ISSUE THREAD

**Issue by benmwilson** [wit-ai/wit#2043]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question/Bug

**What is the current behavior?**
The bot refuses to train on any new utterances. It says "Training complete" but it last trained on Wednesday, 9 days ago.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Add any new utterance and try to train/validate.

**What is the expected behavior?**
It is expected to train on new utterances

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
147699423802328

**Comment by MeNicolas** [comment]
I am having the same issue 
App ID : 788884121748612

Also when I click on my app in the list I get redirected to the list.

**Comment by ruoyipu** [comment]
Hi @benmwilson @MeNicolas,

I've restarted training for app IDs: 147699423802328 and 788884121748612.
Please let us know if the behavior continues. We recently pushed out a fix related to training and are monitoring closely.

**Comment by ruoyipu** [comment]
@MeNicolas for the app redirection issue, is it still occurring? If so, please respond on issue #2045, thanks!
