### ISSUE TITLE
Persian (Farsi)

### ISSUE THREAD

**Issue by AliShahesmaeili** [wit-ai/wit#2044]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question

Speech recognition is not supported for language: fa
Persian (Farsi)
is there any plan for this issue?

**Comment by ruoyipu** [comment]
Hi @AliShahesmaeili,

Unfortunately we no longer have the capability to support speech recognition for Farsi. We hope to bring it back at some point in the future, in the meantime please refer to https://wit.ai/faq for the official speech languages we support.
