### ISSUE TITLE
I can't log in to the app on the site

### ISSUE THREAD

**Issue by emil97-isaev** [wit-ai/wit#2045]
Hi, I am trying to log in to my app on the site wit.ai in my personal account to add something, but as soon as I click on my app, the page starts to reload. I can't get into my app. What should I do about it?
![1](https://user-images.githubusercontent.com/77544797/113489364-875a1880-94cc-11eb-851e-a2caa64798c1.png)

**Comment by darkloor** [comment]
Yes I am having the same issue

**Comment by ruoyipu** [comment]
Hi, thank you for reporting this issue.

I cannot repro, is this issue still occurring? If so, could you provide the app ID that is not loading?

**Comment by ruoyipu** [comment]
Closing until further info is provided.
