### ISSUE TITLE
API is operational, but there seems to be an issue with the website training page

### ISSUE THREAD

**Issue by frankmaione** [wit-ai/wit#2046]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by frankmaione** [comment]
I'm having the same issue as emil97-isaev

**Comment by ruoyipu** [comment]
Duplicate of #2045

Hi @frankmaione, as this is the same issue as the linked thread, I will close this one in favor of the other thread.

Please provide the app ID you're having issues with in the other thread.
