### ISSUE TITLE
SUPPORT EMAIL NEVER RESPONSE TO ME!!!!

### ISSUE THREAD

**Issue by hosam-ai** [wit-ai/wit#2047]
I had so many issues with wit.ai front-end app and I tried to contact support and post in their fb group but they never response to me!! every time I keep trying to fix it my own or even create a new app and Strat from scratch cuz some bugs fro example (one of entities refuse to be removed which cased a problem with ai understanding). can you please give more attention to the support email and fb group please, I really love to use wit.ai but we need support!!

PS. We don't have a problem to pay for a support plan

**Comment by ruoyipu** [comment]
Hi @hosam-ai,

Apologies for the lack of support response. We are working on improving.

Could you provide your app ID and the entity you are trying to delete so that we can investigate the entities issue?

**Comment by hosam-ai** [comment]
Hello! Thanks for your reply I appreciate, don’t worry about the entity i
already created a new application to solve this issue, Happy that i can
find support here will post next time in GitHub directly
