### ISSUE TITLE
Wit app is stuck at ongoing

### ISSUE THREAD

**Issue by TaraNaser** [wit-ai/wit#2049]
Do you want to request a feature, report a bug, or ask a question about wit?
bug
What is the current behavior?
Wit app is stuck at Ongoing
If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

What is the expected behavior?
Wit app not to be stuck at Ongoing
If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.
App ID: 494161211557462

**Comment by ruoyipu** [comment]
Hi @TaraNaser,

Thank you for the report, I've manually restarted your app training. Please let us know if it continues to get stuck, we pushed a fix recently and are monitoring to see if the behavior continues.
