### ISSUE TITLE
How can I use wit intents?

### ISSUE THREAD

**Issue by shzamani** [wit-ai/wit#205]
Hi,

Could you please tell me how can I use the wit Internet of Things intents?
https://wit.ai/Francis88/Internet%20of%20Things/intents/lights
This is for lights, but I don't know how can I use it for turning on or off lights? which brand of light? is there any specific "wit" brand light?! 
I am a beginner, so I'm a little confused about these.

Thanks

**Comment by l5t** [comment]
Wit allows you to turn text or audio queries into structured data. For example, if you send "turn off the lights in the kitchen", Wit can return this JSON.

![image](https://cloud.githubusercontent.com/assets/6992759/14411186/b337cc30-fef5-11e5-9e38-fec6682cc9fc.png)


Then on your app or device (basically your code), you can parse this answer and trigger the function that will actually turn on or off the lights.

**Comment by shzamani** [comment]
So, you mean wit does not execute a command or API itself, yes? I thought that there are some APIs in it, and when user enters expressions it can trigger them.

**Comment by l5t** [comment]
You're right, Wit doesn't execute the command or API itself.
