### ISSUE TITLE
App Training Taking Too Long To Complete

### ISSUE THREAD

**Issue by ibadanisNow** [wit-ai/wit#2050]
Hi,

I am getting this message at Training scheduled: Your app is scheduled to train at Mon 23:05.
It is taking too long for training my app, any solution?
App ID: **620495821933587**.

Thanks

**Comment by ibadanisNow** [comment]
****

**Comment by ruoyipu** [comment]
Hi @ibadanisNow,

I've manually restarted training for app 620495821933587. Please let us know if this behavior continues, we pushed a fix recently and are monitoring closely.

**Comment by ibadanisNow** [comment]
Thanks @ruoyipu, the training is complete.
