### ISSUE TITLE
add member telegram

### ISSUE THREAD

**Issue by knowledgecomputer2018** [wit-ai/wit#2051]
hi mr add member telegram :
step 1 : run init.py
step2: run get_data.py 
error : database is lock ???? or 
client is disconnect.

thank you very much for reply me .

**Comment by lycai-fb** [comment]
Hi @knowledgecomputer2018 

I'm not entirely sure what you're asking for here. Feel free to reopen another task following the [issue template](https://github.com/wit-ai/wit/blob/master/ISSUE_TEMPLATE.md).

Thanks.
