### ISSUE TITLE
Training doesn't start (stuck on Training complete)

### ISSUE THREAD

**Issue by danielskrzeszowski** [wit-ai/wit#2052]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
Training doesn't start despite adding new utterances. Status is stuck at `Training complete` (Last training was 1.04, 6 days ago)
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Training should start (with delay) after new utterances are added.
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
265679611713973

**Comment by danielskrzeszowski** [comment]
Same problem with app: 288363119332118

**Comment by danielskrzeszowski** [comment]
Same with app: 2840344789568784

**Comment by Xueying-Wang** [comment]
Hi @Dom3lq, I've successfully retrained all your apps
