### ISSUE TITLE
Entity '288641289300176' not found when i try to export my app.

### ISSUE THREAD

**Issue by abudakar** [wit-ai/wit#2053]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
yes

**What is the current behavior?**
when i try to export my app it gives me an error which is : Entity '288641289300176' not found

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- go to setting 
- scroll down till you find export your data
- click on download .zip with your data 
- you will see the error says : Entity '288641289300176' not found

**What is the expected behavior?**
export successfully and download a zip file containing my app data so i can import it later . 

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID : 722194405081812

**Comment by Xueying-Wang** [comment]
Hi @abudakar, I've fixed the issue for your app. Can you try exporting it again?

**Comment by abudakar** [comment]
thank you very much is fixed and i could export it . 

Regards .

**Comment by abudakar** [comment]
thank you very much it's fixed and i could export the app . 

Regards :)
