### ISSUE TITLE
Issue with API to create new entity 

### ISSUE THREAD

**Issue by fhgs2001** [wit-ai/wit#2055]
I am trying to create a new entity to my wit.ai app but it gives me the following error:

{
    "error": "Couldn't read entity from request body",
    "code": "json-parse"
}

The Following is the Request I sent:

curl --location --request POST 'https://api.wit.ai/entities?v=20200513' \
--header 'Authorization: Bearer $TOKEN' \
--header 'Content-Type: application/json' \
--data-raw '{
    "name":"testing",
    "roles":"keyword",
    "lookups":["free-text","keywords"]
}'

Please Help with that,thanks.

**Comment by Xueying-Wang** [comment]
Hi @fhgs2001, I think you miss the brackets for the "roles" field. Please try with this:

curl --location --request POST 'https://api.wit.ai/entities?v=20200513'
--header 'Authorization: Bearer $TOKEN'
--header 'Content-Type: application/json'
--data-raw '{
"name":"testing",
"roles":["keyword"],
"lookups":["free-text","keywords"]
}'

You can find more details at Wit.ai docs https://wit.ai/docs/http/20200513/#post__entities_link

**Comment by lycai-fb** [comment]
Feel free to reopen if you are still having issues.
