### ISSUE TITLE
Utterance training not working

### ISSUE THREAD

**Issue by sadfarhan124** [wit-ai/wit#2056]
After adding a new utterance this error appears:

There was an error validating the utterance.
Something went wrong. We're working on getting this fixed as soon as we can. You may be able to try again.

**Comment by keithlim** [comment]
Facing a similar issue, mine displays

![image](https://user-images.githubusercontent.com/53687690/114669025-043e8b00-9d34-11eb-9b75-95e1ea785fb6.png)

**Comment by nausicaasnow** [comment]
Thanks for reporting! It's a transient issue, should be recovered now :)

**Comment by gauthier-th** [comment]
It isn't for me:

![image](https://user-images.githubusercontent.com/37781713/114790395-f9601680-9d84-11eb-8417-178f4f2da299.png)

**Comment by sadfarhan124** [comment]
![image](https://user-images.githubusercontent.com/79442003/114817246-13284a80-9dd3-11eb-9caa-c9b13e170a91.png)

Still happening with some occurrences
