### ISSUE TITLE
App is training for 48 hours

### ISSUE THREAD

**Issue by mmalbergier** [wit-ai/wit#2058]
Our app 160245738836120 has been training for the last 48 hours and haven't finished yet.
We are very concerned about this.

![image](https://user-images.githubusercontent.com/2797810/114877435-a8c4d980-9dd5-11eb-8de7-a6d54a2ccb58.png)

If you see something unusual about our app, please let us know to change it.

**Comment by nausicaasnow** [comment]
Retrained :)

**Comment by mmalbergier** [comment]
Hello,
Please don't close this issue. We need to understand why this happens.
