### ISSUE TITLE
Can't Export App data.

### ISSUE THREAD

**Issue by offraildev** [wit-ai/wit#2059]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
report a bug
![image](https://user-images.githubusercontent.com/26507562/114984136-09741500-9eaf-11eb-8a26-a94da9bf7b35.png)
![image](https://user-images.githubusercontent.com/26507562/114984256-2a3c6a80-9eaf-11eb-9c9d-cf6c01d74583.png)

**What is the current behavior?**
Some of my apps are showing this behavior, when i try to export the data it shows some entity with id: ***** is missing and data doesn't get exported. Also there is a problem with training new sentences, the app seems to be in training status since last week but doesn't take into account the new sentences added for training.  

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
app_id: 3011009849122695
app_id: 1705692829602931

**Comment by FengyangZhang** [comment]
Hi, sorry about the delay, I've fixed export for 3011009849122695. For 1705692829602931 do you know if there's a language change for the app?

**Comment by offraildev** [comment]
thank you for the fix, for the case of app: 1705692829602931, yes there was a language change from English to Hindi

**Comment by FengyangZhang** [comment]
Changing language is not well supported. For 1705692829602931 app, I think you'll need to first remove the entities created before the language change, and create them again so they're in Hindi.
