### ISSUE TITLE
Hebrew support

### ISSUE THREAD

**Issue by VadimGut** [wit-ai/wit#206]
I am trying to create Hebrew stories but it just doesn't seem to recognize none of the words, or the cities
any suggestions ?

**Comment by patapizza** [comment]
Supporting new languages is on our short-term roadmap: https://github.com/wit-ai/wit
Stay tuned!

**Comment by patapizza** [comment]
Since 4/28, we've added support for Hebrew (in beta): https://wit.ai/blog/2016/04/28/new-languages

**Comment by thematan** [comment]
@patapizza 
I wanted to contribute and create datetime in hebrew,
but i didn't find hebrew in duckling's repo. how is it possible?

**Comment by patapizza** [comment]
@thematan
Nobody started working on an Hebrew implementation for Duckling.

To add a new language and start contributing, please refer to the FAQ in the [documentation](https://duckling.wit.ai/#contributing).

**Comment by eladelad** [comment]
@thematan Did you start contributing to the Hebrew datetime?
I also wish to have it and can contribute. But I didn't understand how and when it is merged to wit.ai

**Comment by thematan** [comment]
No i havent
בתאריך 3 בינו 2017 16:35, "Elad Hefetz" <notifications@github.com> כתב:
