### ISSUE TITLE
Wit.ai website is not responding

### ISSUE THREAD

**Issue by TaraNaser** [wit-ai/wit#2065]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
I not able to access wit apps through their UI, Wit.ai website is not responding
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
![image](https://user-images.githubusercontent.com/71825913/115208479-476a7680-a105-11eb-8e64-2ac17d95d31e.png)
Try opening https://wit.ai/apps
**What is the expected behavior?**
The page to open
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by nausicaasnow** [comment]
Thanks for reporting, we are working on a fix for it!

**Comment by nausicaasnow** [comment]
should be fixed now :)
