### ISSUE TITLE
Utterance training is not being trained

### ISSUE THREAD

**Issue by TaraNaser** [wit-ai/wit#2067]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
Trained texts for intents are not being trained
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I used the API https://api.wit.ai/utterances?v=20190904
The request:
[
{
"text": {text},
"intent": {intent},
"entities": [],
"traits": []
}
]
The Response:
{
"sent": true,
"n": 1
}
**What is the expected behavior?**
In https://api.wit.ai/message when I send the expression in q to get the intent
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID: 298027741480469

**Comment by kitchWWW** [comment]
Can you verify what this looks like on the UI? Are your utterances showing up in the utterances tab? Does the training indicator appear to have completed training? (And if you send in a new utterance, do you wait for training to have completed before sending the request to the message API?)

**Comment by TaraNaser** [comment]
hi @kitchWWW 
The utterance is showing in Get https://api.wit.ai/utterances?v=20190904&limit=10000
But when it is sent in messages it doesn't return the intent name, this was trained more than a week ago.
![image](https://user-images.githubusercontent.com/71825913/115524414-c80cac80-a296-11eb-9cc9-b06cd4be6c69.png)
![image](https://user-images.githubusercontent.com/71825913/115524514-e4a8e480-a296-11eb-8ddb-cfca0c9c411d.png)

**Comment by kitchWWW** [comment]
Thanks for this information. I've gone ahead and restarted the training. Please re-open this task if you continue running into issues.
