### ISSUE TITLE
Training Model Not Updating

### ISSUE THREAD

**Issue by assist-github** [wit-ai/wit#2069]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
The training is not being updated 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

- If you look at the intent for "Account Deletion" you will see the training phrases 
- If you then go to the Utterance tab and type "Deactivate my account" the wrong intent is being triggered. 

**What is the expected behavior?**
The agent model should be updated with the correct training. It has been showing "Training Ongoing" for more than a few days now. 

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID: 277589403658028

**Comment by kitchWWW** [comment]
Hello! - Thanks for this information. I've gone ahead and restarted the training on this app. Please let us know if you have any more continuing issues with this.
