### ISSUE TITLE
Keeps failing to correctly relate word to entity

### ISSUE THREAD

**Issue by theboyWhoCriedWoolf** [wit-ai/wit#207]
Hello,

I have started with the wit.ai quick start example but have since extended the functionality adding three more stories which seem to work.

However, now when I interact with the bot wit.ai keeps failing to map words to the correct entity. I have taken it through rigorous amounts of training which does nothing.

For example I have the word `london` mapped to location, however whenever this word is used wit.ai keeps mapping it to every other entity other than location. I have checked over and over and the word is not mapped to any other entities, I have repeatedly written the word in the understanding tab and even there is fails over again. It seems that however the word is weighted, its confidence is miscalculated.

Please let me know if this is a known issues, or how I should proceed as the interface at the moment seems to prevent from any manual confidence mapping.

Thanks

**Comment by stopachka** [comment]
hey @theboyWhoCriedWoolf, we will ping you in the in-app support, to get information about the instance.

**Comment by girikuncoro** [comment]
is there any update on this? I'm facing the exact same issue.
