### ISSUE TITLE
How to recognize 2 location entities (from-to) in an utterance ?

### ISSUE THREAD

**Issue by raymondPswivel** [wit-ai/wit#2070]
I am new to NLP and wit.  I would like to recognized 2 location entities in an utterance, while these 2 locations are with a relation of "From" and "To". 
A simple example may be "I am going from USA to Japan", is it possible that the recognition can also identify the location entity of type "From" or "To" in this case? How should I do it in Wit? Million Thanks.

**Comment by lycai-fb** [comment]
Hey @raymondPswivel

I believe your use case may not be supported by the built-in entities but one thing you can try is to define some custom entities to capture "from" and "to" (and their respective synonyms) and then do some postprocessing in your app to match them based on location in the utterance string.

Good luck!

<img width="1006" alt="Screen Shot 2021-04-28 at 12 03 47 PM" src="https://user-images.githubusercontent.com/52939420/116458725-cce2da80-a819-11eb-8f8f-d2f08433fe16.png">
