### ISSUE TITLE
Can the Intents and Entities be trained separately for the same sentences/utterances?

### ISSUE THREAD

**Issue by ramki-chatgen** [wit-ai/wit#2071]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Ask a *question* about wit.

**What is the current behavior?**
1) Create a new app, create "rings" intent, create "metal_type" entity
2) Train the sentence "show me gold rings" for rings intent but no entity to be trained through API. Wit is giving rings intent as output.
```
utterance = {
            'text': "show me gold rings",
            'intent': "rings",
            'entities':[],
            'traits':[]
        }
```
3) Train the sentence "show me gold rings" for metal_type entity with the value "gold" but no intent to be trained through API. Wit is giving the "metal_type" entity with the value "gold" but no intent is detected.
```
utterance = {
            "text": "show me gold rings",
            "entities": [
                {
                    "entity": "metal_type:metal_type",
                    "start": 8,
                    "end": 12,
                    "body": "gold",
                    "entities": []
                }
            ],
            "traits": []
        }
```
4) Train the sentence "show me gold rings" for rings intent but no entity to be trained through API. Wit is giving "rings" intent and "metal_type" entity value of "gold" as output.
```
utterance = {
            'text': "show me gold rings",
            'intent': "rings",
            'entities':[],
            'traits':[]
        }
```

If I download the trained data from settings, utterances only has the latest trained data for "show me gold rings" (refer 4 above).

**If the current behaviour is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
930636174161657

It seems to me training may get overwritten for the same sentence if I train intents and entities separately, but it also seems to work too after training again. 
1) Can I get an insight into how the training is being done when an utterance is added into wit, especially when a particular utterance was previously trained?
2) Can the Intents and Entities be trained separately for the same sentences/utterances in the same app without affecting the performance of eachother?

**Comment by lycai-fb** [comment]
Hey @ramki-chatgen 

The training is done through machine learning models (statistical and otherwise) so providing contradicting training utterances may cause reduced performance. Therefore the recommendation is that you don't train them separately but you are free to try out different approaches to get the results you want. Many models in use are akin to black boxes so we can't easily predict the results before trying it out.

Good luck.
