### ISSUE TITLE
"Continue with Facebook" button doesn't work

### ISSUE THREAD

**Issue by spherebread** [wit-ai/wit#2072]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
About wit authorization

**What is the current behavior?**
"Continue with Facebook" doesn't work at all. There are no any requests, no actions.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Go to https://wit.ai/apps
2. Press "Continue With Facebook"

**What is the expected behavior?**
Successful sign in/up

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by lycai-fb** [comment]
Hi are you still having problems signing in?
It might have just been a transient infrastructure issue.

**Comment by spherebread** [comment]
Hi @lycai-fb 
Resolved with #2073
