### ISSUE TITLE
can't login via facebook to wit.ai

### ISSUE THREAD

**Issue by pQ96VJItXy0oe8FYcrYsTDXKG7CKm9jX** [wit-ai/wit#2073]
I try to login with FB and the button doesn't even work, I can click forever and It will never redirect to login,
![image_2021-04-30_190917](https://user-images.githubusercontent.com/43665460/116736276-92c73380-a9e7-11eb-961f-5aff23fa1788.png)

help?

**Comment by spherebread** [comment]
Same here #2072

**Comment by thesnes** [comment]
Same issue here. The button is not active for some reason.

**Comment by thesnes** [comment]
Issue seems to be resolved

**Comment by lycai-fb** [comment]
Thanks for the update.
