### ISSUE TITLE
I get 500 error after deleting intents

### ISSUE THREAD

**Issue by ItayGershman** [wit-ai/wit#2075]
Hey, today I deleted 2 intents and replaced them with one intent that supposed to match them both. When I run the application I get 500 error for the same input.

for e.g:
I had 2 intents - 'consent' and 'accept' which both of them received positive answers as input like : 'yes', 'i would like to', etc.
Now I made new intent called 'yes' and I suspect that when I say the same utterances as before I get this 500 error.

I would really appreciate your help in the matter.

**Comment by lycai-fb** [comment]
Hi @ItayGershman 
Please follow the [issue template](https://github.com/wit-ai/wit/blob/master/ISSUE_TEMPLATE.md) as we need some information from you to be able to help.
Thanks.

**Comment by ItayGershman** [comment]
Do you want to request a feature, report a bug, or ask a question about wit?
bug

What is the current behavior?
500 error

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
I deleted two intents and made a new one instead that receives the same utterances, after doing so wit has responded to me with 500 error for these utterances.
For example, I had 2 intents that should get utterances like yes, yes I do, I would like to, sure, of course, etc.
After removing these intents I created "yes" intent that receives these utterances and when I send these messages I get 500 error.

What is the expected behavior?
return the new intent I created.

If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.
3386412438134900

Thank you!

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
