### ISSUE TITLE
Wit stuck on "training ongoing" after deleting entity keywords

### ISSUE THREAD

**Issue by RibeiroAna** [wit-ai/wit#2076]
**What is the current behavior?**

A collaborator of my app added a few "bad" keywords to my entity (they should not have been part of this entity). When I noticed that, I tried to delete all of them as quick as I could (so I didn't wait wit to finish training after each deletion), and wit got stuck on the status "training ongoing" for 2 days already.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
My app id is: 289886732511215, the entity ID is 491832958680721

**Comment by lycai-fb** [comment]
Hey @RibeiroAna 

I've manually retrained your app. Please let us know if you encounter any additional issues.

Thanks.
