### ISSUE TITLE
Trained input not getting identified

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2079]
Hi,

appId: 478226853535154
Intent:  test_2
Input: Test 2

When we try 'Test 2' in understanding tab, the intent 'test_2' is not recognizing. What is the issue.
Earlier it was working.

Thanks

**Comment by ChrisyShine** [comment]
@anjaly I noticed that, in your app there are many utterances with word "test" and annotated as OutOfScope. This may be the reason for "Test 2" not working. Can you train the app with some meaningful utterances and distinguish with other "test" OutOfScope utterances?

**Comment by anjaly** [comment]
Hi,

If we delete an intent without removing the examples, will those examples will be considered as outofscope.
In our app we are deleting intent and adding the same again using api. But the issue is that once we delete and retrained it then the input is not getting identified.
Thanks

**Comment by ChrisyShine** [comment]
@anjaly Removing the examples won't make them considered OutOfScope.
Removing utterances and adding them back won't affect the model quality. If the utterances and annotations are the same, the model should provide the same prediction result.

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
