### ISSUE TITLE
API methods for stories

### ISSUE THREAD

**Issue by citizenrich** [wit-ai/wit#208]
Seems stories can't be created/modified via API. Maybe I'm missing it. Enhancement?

**Comment by patapizza** [comment]
You're right, it's not currently possible to do so.
Maybe in the longer term we'll support this.

**Comment by mikedeshazer** [comment]
Stories still not available via the api...? 1 year later from original question... It's the best part of the service...

**Comment by jagreene** [comment]
Ditto, has there been any movement on this? Its pretty necessary for my usecase.

**Comment by blandinw** [comment]
@jagreene @mikedeshazer can you please provide more information about your use case? And why you could not use NLP + client-side code instead of using Stories?

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018.https://wit.ai/blog/2017/07/27/sunsetting-stories
