### ISSUE TITLE
"+1000 See More" keyword in entity is super slow in UI

### ISSUE THREAD

**Issue by idanadut** [wit-ai/wit#2080]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug & feature
**What is the current behavior?**
when pressing the link on the bottom "+1000 See More" (to see all keywords in the entity) -> If this entity has a few hundreds keywords or more -> the UI is super slow and it makes it impossible to maintain and add synonyms.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Create an entity with 1000 keywords and synonyms in keywords. Inn the entity page click on "see more". try to search, add, delete synonyms. super slow and heavy.
**What is the expected behavior?**
To be able to work normally and faster. Perhaps add pagination or search filter to see less keywords in the same view. or fix the bug.
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
All apps

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
