### ISSUE TITLE
Hi, I am unable to press the hyperlink to log in to wit.ai. After clicking "Continue to Facebook" it is still not redirecting me. Am I the only one experiencing this issue?

### ISSUE THREAD

**Issue by russellchkang** [wit-ai/wit#2081]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by yuzh174** [comment]
HI @russellchkang , could you share a screenshot or record a video?

**Comment by skalecki-imblox** [comment]
I have a similar issue. I'm redirected, but `/apps` URL is just forever loading, and a blank page is visible. After some time I'm getting a message "website has stopped responding". The same in incognito mode and in Firefox. The website was working fine ~week ago. 

Chrome Version 91.0.4472.77, Linux. 

![witai_login_problem](https://user-images.githubusercontent.com/79854875/120784591-87a67c80-c52c-11eb-87c4-42a30b4699af.gif)

**Comment by chessai** [comment]
Is this issue still persisting?

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
