### ISSUE TITLE
How to check via api if an example is marked as outOfScope

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2082]
Hi,

We are trying to train an example via api. But most of the cases after training it won't work and when we searched the utterances with the text in ui it was shown 2 times. 
One with small case and other with camel case.. The camel case is the one which we trained and the other one was the input we tried and it was in small case.
Won't the nlp identify the intent in incasesensitive way. Please advice.

Thanks

**Comment by yuzh174** [comment]
@anjaly, what appID is it? Also could you share a few sample utterances so we can take a look?

**Comment by chessai** [comment]
Hi @anjaly, due to no response I'm going to close this. If you continue having issues and wish for us to investigate please feel free to re-open.
