### ISSUE TITLE
TOKEN when creating a new app

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2083]
Hi,

We are creating an app in wit.ai via api. 
In the api header we need to add $TOKEN, from where can we take the token on creating an app.

Thanks

**Comment by anjaly** [comment]
Hi all,
Any updates?

**Comment by chessai** [comment]
Hi @anjaly, 

Click on your app, then click 'Settings', then you should see the token.

**Comment by anjaly** [comment]
> Hi @anjaly,
> 
> Click on your app, then click 'Settings', then you should see the token.

Hi @chessai 

If we don't have any existing app, do we need to create a dummy app and use that token for creating new apps via api?

**Comment by chessai** [comment]
> > Hi @anjaly,
> > Click on your app, then click 'Settings', then you should see the token.
> 
> Hi @chessai
> 
> If we don't have any existing app, do we need to create a dummy app and use that token for creating new apps via api?

Yes, I believe that will work. I'm not sure how else you would accomplish this.
