### ISSUE TITLE
Wit app doesn't recognize May as a date

### ISSUE THREAD

**Issue by TaraNaser** [wit-ai/wit#2085]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
May is not being recognized as a date
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
May should be recognized as a date
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App id: 571405710215995

**Comment by yuzh174** [comment]
You have "may" used in your several of your utterances samples. They are all used as the verb "may". This will bias the system. If you add a few samples in the utterance with meaning of the date "May" and train again. It should fix the problem.

**Comment by patapizza** [comment]
`May` alone is not recognized, as it clashes with the verb. It's marked as latent in [Duckling](https://github.com/facebook/duckling).
