### ISSUE TITLE
App stuck on Training ongoing

### ISSUE THREAD

**Issue by ariel-paz** [wit-ai/wit#2087]
Do you want to request a feature, report a bug, or ask a question about wit?
BUG

What is the current behavior?
Training is stuck on TRAINING ONGOING

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
I have many apps. And often I spend days without training a new set on an app. Often, after I train something new, I'm left with 10+ hours waiting for the new set to be trained, instead of triggering something sooner.

What is the expected behavior?
I would expect that WIT trains my set faster when I update it

What is the App ID where you are experiencing this issue (if applicable)?
Right now I have one waiting for 2+ hours: 414579643241513

**Comment by FengyangZhang** [comment]
Hi, apologies that sometimes it does get stuck and stays in the state for a long time. I've retrained the app just now.

**Comment by ariel-paz** [comment]
Thanks!
