### ISSUE TITLE
The app doesn't finish training

### ISSUE THREAD

**Issue by gnovis** [wit-ai/wit#2088]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
BUG

**What is the current behavior?**
The app doesn't finish training. The status is still "Training ongoing". New added utterances are not trained.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
910051436505352

**Comment by FengyangZhang** [comment]
Hi, I've retrained your app just now, thanks for the patience.

**Comment by gnovis** [comment]
Hi @FengyangZhang, thank you, where was the problem? It happens to me sometimes, did I make a mistake?
