### ISSUE TITLE
I have created a chatbot but cant able to trial in wit site itself. Is there any options to check whether the chatbots working properly or not?

### ISSUE THREAD

**Issue by KrishnenduSG** [wit-ai/wit#2089]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by wangsnowyin11** [comment]
Hi,
Thanks for using our product! You should be able to test directly in the wit site by typing in your test samples. If the sample is trained, the prediction will be produced automatically in the annotation bar.

Let me know if the annotation bar doesn't work and it would be awesome if you can provide more details where doesn't work. Sorry for the inconvenience!
