### ISSUE TITLE
Arabic expressions in utterances are in a very strange structure + Trained expressions are not understood

### ISSUE THREAD

**Issue by TaraNaser** [wit-ai/wit#2093]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
The majority of the intents and expressions are showing training in progress 
and the message api doesn't return the intent of for any of the trained expressions
Arabic expressions in utterances are in a very strange structure
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Using https://api.wit.ai/utterances?v=20190904&limit=10000
And https://api.wit.ai/message?q=?&verbose=true&v=20190904
![image](https://user-images.githubusercontent.com/71825913/119799356-a7aebe00-bee4-11eb-8a71-7a7a7551810f.png)
![image](https://user-images.githubusercontent.com/71825913/119800732-b8136880-bee5-11eb-9265-2ebae76e7b85.png)

**What is the expected behavior?**
The message Api to return the trained expressions' intent.
The arabic letters to be in the correct language/structure.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2101186346677141

**Comment by patapizza** [comment]
This has been resolved now (https://github.com/wit-ai/wit/issues/2091).
