### ISSUE TITLE
{"error":"Something went wrong. We've been notified","code":"unknown"}

### ISSUE THREAD

**Issue by CelestineAkpanoko** [wit-ai/wit#2096]
**I think there's an issue with the API response to request**

**I keep getting an error when I request an utterance.**

**I kept on feeding it utterances and assigning it to an intent yet I am still getting an error.**

**I expect to get a JSON format output denoting the confidence level and the other info.**

**App ID: 382809739782590**

**Comment by 91ns** [comment]
Hi,
We're facing the same issue with App ID 571405710215995

**Comment by ArenaGrenade** [comment]
Hi! facing the same issue for App ID 186646363362467. Its the first time I am trying out wit.ai. Neither the python sdk nor a simple curl request works.

__EDIT__
Sorry for the mentions. But, this server downtime has been going for the past 3 days, hope this gets your attention. @zpao.

**Comment by chessai** [comment]
> 382809739782590

We have no traffic associated with that App ID. Are you sure it's correct?

Also, the other App IDs mentioned on this thread do show the 500 issue others are reporting.

**Comment by ArenaGrenade** [comment]
@chessai so this issue is specific to certain apps or accounts? Would creating a new account help?

**Comment by chessai** [comment]
See https://github.com/wit-ai/wit/issues/2105#issuecomment-856296095

Also @ArenaGrenade a new account/app probably won't help.

**Comment by ArenaGrenade** [comment]
Thanks!

**Comment by chessai** [comment]
This should be resolved. See https://github.com/wit-ai/wit/issues/2105#issuecomment-860916172
