### ISSUE TITLE
Wit Apps are not showing on the UI 

### ISSUE THREAD

**Issue by 91ns** [wit-ai/wit#2097]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
When I log into wit I'm not able to access any of the Apps 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Log in on Wit.ai then click on My Apps, the page keeps loading 
**What is the expected behavior?**
Being able to access Wit Apps through the UI 
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
I'm not able to see any of the apps 
![image](https://user-images.githubusercontent.com/25252530/120160136-97595480-c1fe-11eb-82b2-961125e03311.png)

**Comment by patapizza** [comment]
Closing in favor of https://github.com/wit-ai/wit/issues/2122.
