### ISSUE TITLE
Training in Utterance is not working

### ISSUE THREAD

**Issue by TaraNaser** [wit-ai/wit#2098]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
I am training using POST https://api.wit.ai/utterances?v=20190904 and it is returning true but its not reflecting the training on GET https://api.wit.ai/utterances?v=20190904
![image](https://user-images.githubusercontent.com/71825913/120201186-d3f07480-c22d-11eb-911e-bc7ecfb3c80a.png)
![image](https://user-images.githubusercontent.com/71825913/120201241-e5398100-c22d-11eb-9455-808c238b0966.png)

And the status for training is done.
![image](https://user-images.githubusercontent.com/71825913/120201305-f84c5100-c22d-11eb-8c96-1891052b1fd0.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Train in post utterance and then check in get utterance after the training is done 
**What is the expected behavior?**
For the trained utterances to show in get utterances API
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1177227119455280

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
