### ISSUE TITLE
Is Wit.ai down??? (Internal Server Issue)

### ISSUE THREAD

**Issue by KrishnenduSG** [wit-ai/wit#2099]
i'm getting WitError: Wit responded with status: 500 (Internal Server Error) consistently. Here's the whole error:

Traceback (most recent call last):
  File "demo1.py", line 8, in <module>
    resp = client.message(message_text)
  File "C:\Users\Krishnendu\AppData\Roaming\Python\Python37\site-packages\wit\wit.py", line 69, in message
    resp = req(self.logger, self.access_token, 'GET', '/message', params)
  File "C:\Users\Krishnendu\AppData\Roaming\Python\Python37\site-packages\wit\wit.py", line 42, in req
    ' (' + rsp.reason + ')')
wit.wit.WitError: Wit responded with status: 500 (Internal Server Error)

**Comment by ArenaGrenade** [comment]
Seems like it. They have been down for the past 5 days or so.

**Comment by KrishnenduSG** [comment]
> Seems like it. They have been down for the past 5 days or so.
Thankyou so much for your response :)

**Comment by KrishnenduSG** [comment]
@ArenaGrenade Thank you so much for your response :)

**Comment by ArenaGrenade** [comment]
Haha, am a user as well. Been waiting for some time :(. This was my first try with wit.ai and boom it doesnt work :)

**Comment by abv** [comment]
I'm running into the same issue -- spotted this in the headers. Tried refreshing my token no luck. <img width="864" alt="Screen Shot 2021-06-03 at 1 58 53 PM" src="https://user-images.githubusercontent.com/250306/120691619-b06b3b00-c474-11eb-896c-c176d2024ae8.png">

**Comment by chessai** [comment]
What are your App IDs?

**Comment by abv** [comment]
Thanks for looking into this.

My app id is **3745799722113420**

For what its worth, I tried creating a new app & importing the original app's config. The newly created app (id **1023368994859005**) also returns the same error.

**Comment by kevinjon27** [comment]
@abv any update bro? still error?

**Comment by abv** [comment]
@kevinjon27 Nope, still not working for me. @chessai Is there anything else I can provide you with to help get to the bottom of this issue?

**Comment by chessai** [comment]
See https://github.com/wit-ai/wit/issues/2105#issuecomment-856296095

**Comment by chessai** [comment]
Closing. See https://github.com/wit-ai/wit/issues/2105#issuecomment-860916172
