### ISSUE TITLE
Natural spoken sentences

### ISSUE THREAD

**Issue by Dyljyn** [wit-ai/wit#21]
To teach the service in the most natural spoken way, I think it would be great to add the speech option to the sentence input field.

This doesn't have to be very complicated: adding 'x-webkit-speech' to the input field is in my opinion enough.

**Comment by Glavin001** [comment]
+1 I would love to be able to train with voice right in the web console. Currently I see the `train some more` button however clicking it does not do anything:
![image](https://cloud.githubusercontent.com/assets/1885333/7591516/ae8e8c44-f8a4-11e4-802a-d8356380b959.png)

Adding the Wit.ai browser speech input to the sentence input field would be exceptional!

**Comment by l5t** [comment]
So sorry for the 3y old reply :-(. We never had the time to do it. With the new release of Bot Engine, our priority is more around semantic and dialog, and not speech. So I'm afraid we won't be able to do it anytime soon. In the meantime, you can use: https://labs.wit.ai/speech
