### ISSUE TITLE
Stories error breaks next possible story

### ISSUE THREAD

**Issue by DiegoRBaquero** [wit-ai/wit#210]
Hello,

I've been trying wit a lot lately and I always encounter the following error:
1. If no story match, node-wit will throw error and not callback empty context to wit.
2. Next phrase/word that user sends is not matched to any story, it just callbacks to my code and that's it. If I send the same phrase/word again, it works.

Still gotta say, great work on the beta engine and I hope we work together on making it better.

**Comment by patapizza** [comment]
Hi Diego,

What do you mean by "no story match"? Can you show me what error is thrown, as well as the conversation?

**Comment by DiegoRBaquero** [comment]
I have just one story. One which takes one word, which is an entity. There are no more stories.

So, if you type to the bot "Hello" which won't match that story, wit.runActions() will end up with error action which outputs "Oops, I don't know what to do" (that's from the example). But then, if I send the the exact story word which should match the entity and run my actions, it doesn't, it just callbacks to me after the merge. If I send the same word again, it works.

**Comment by patapizza** [comment]
Sorry for the late reply.
Do you confirm the exact story word yields the expected extracted entities? Is your merge action working properly (adding the right things in the context)?

**Comment by jrnjerin** [comment]
Hi I am also getting "Oops, I don't know what to do" if we send anything which is not in the stories.
Can anyone please tell what to do on this case?
Thanks in advance

**Comment by jrnjerin** [comment]
@patapizza , I am still getting "Oops, I don't know what to do"  if we send anything which is not in the stories.
Can anyone please tell what to do on this case?
Thanks in advance

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
