### ISSUE TITLE
Intents not detected and why? (spanish)

### ISSUE THREAD

**Issue by mmalbergier** [wit-ai/wit#2101]
We have a project 894780091336235, 

We've added utterance for one intent: 
![image](https://user-images.githubusercontent.com/2797810/120377302-5727ce00-c2f3-11eb-8d8f-6333b8e0868d.png)

And when we try the following, we get NO intentions: "quiero obtener mi tarjeta"
But, using the following text: "quiero obtener una tarjeta" we receive over 80% confidence.
How "mi" versus "one" can get the AI incorrect results?

**Comment by patapizza** [comment]
Hi, it looks like `quiero obtener una tarjeta` is now marked as out of scope.
