### ISSUE TITLE
Training utterance with trait not working

### ISSUE THREAD

**Issue by TaraNaser** [wit-ai/wit#2102]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
![image](https://user-images.githubusercontent.com/71825913/120652091-190fe300-c488-11eb-934c-f164f2b9417f.png)
After trying to train an utterance with a trait I receive "Failed to validate utterance at index 0. Could not find value \"_\" for trait \"about_NH_values "
But the trait is created
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
![image](https://user-images.githubusercontent.com/71825913/120652261-48265480-c488-11eb-800c-1a5b726d8df3.png)

**What is the expected behavior?**
To train the utterance with the trait
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2101186346677141

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
