### ISSUE TITLE
All the live utterances (~3000) pending training disappeared yesterday from dashboard

### ISSUE THREAD

**Issue by roots-ai** [wit-ai/wit#2104]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
BUG

**What is the current behavior?**
EMPTY DASHBOARD

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Around 3000 messages pending to be trained disappeared. 

<img width="901" alt="Screenshot 2021-06-05 at 12 17 49 PM" src="https://user-images.githubusercontent.com/1976061/120882915-0d432e80-c5f8-11eb-816d-4b1bcd34b7cb.png">

**What is the expected behavior?**
Dashboard that shows last messages and auto highlights intents and entities on adding a utterance.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
783739145520383

**Comment by roots-ai** [comment]
Is anyone here?

**Comment by roots-ai** [comment]
I am still facing these issues. Can someone from the team help?

**Comment by azmatrana** [comment]
I am also facing this issue.

**Comment by patapizza** [comment]
Thanks for reporting.
This is a side effect of https://github.com/wit-ai/wit/issues/2105. Both issues are now resolved.
