### ISSUE TITLE
[URGENT] Our production app: 783739145520383 has started giving 500 error since yesterday

### ISSUE THREAD

**Issue by roots-ai** [wit-ai/wit#2105]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
BUG

**What is the current behavior?**
500 ERROR

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
All API requests are giving 500 ERROR.

**What is the expected behavior?**
return a JSON response

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
783739145520383

**Comment by roots-ai** [comment]
Is anyone here?

**Comment by roots-ai** [comment]
I am still facing these issues. Can someone from the team help?

**Comment by kevinjon27** [comment]
Yeah, our commercial chatbot using wit.ai. And now, broken more than 1 week already. Email not answered, Wit.ai no update. Now I am so scared using Wit.ai. Staff no update.

**Comment by roots-ai** [comment]
Since how long this has been happening? Is wit.ai retiring?

**Comment by roots-ai** [comment]
@chessai @patapizza @FengyangZhang

**Comment by chessai** [comment]
I am working on this.

**Comment by roots-ai** [comment]
> I am working on this.

**Comment by chessai** [comment]
I'm going to try to have this resolved by EOD tomorrow. Have been investigating internally all day Friday/today. Finally honed in on an issue which may be causing these symptoms.

**Comment by roots-ai** [comment]
@chessai Thank you for the update. 
We are facing [this](https://github.com/wit-ai/wit/issues/2104) issue along, maybe it's linked.

**Comment by azmatrana** [comment]
This happened with me multiple times from yesterday. Even api is also returning 500.

**Comment by roots-ai** [comment]
> I'm going to try to have this resolved by EOD tomorrow. Have been investigating internally all day Friday/today. Finally honed in on an issue which may be causing these symptoms.

Any updates here?

**Comment by chessai** [comment]
> > I'm going to try to have this resolved by EOD tomorrow. Have been investigating internally all day Friday/today. Finally honed in on an issue which may be causing these symptoms.
> 
> Any updates here?

We've now identified the exact issue causing these symptoms and are working on a fix.

**Comment by ArenaGrenade** [comment]
> > > I'm going to try to have this resolved by EOD tomorrow. Have been investigating internally all day Friday/today. Finally honed in on an issue which may be causing these symptoms.
> > 
> > 
> > Any updates here?
> 
> We've now identified the exact issue causing these symptoms and are working on a fix.

Good Day @chessai! How is the fix going?

**Comment by roots-ai** [comment]
Hi @chessai! Any updates here?

**Comment by roots-ai** [comment]
> Hi @chessai! Any updates here?

**Comment by chessai** [comment]
We have developed a fix and are going to test it tomorrow with a single app. If it works we will roll it out to all affected apps.

**Comment by chessai** [comment]
The fix was rolled out. The issue should be resolved. I tested all affected apps and they are now behaving as expected.

**Comment by ArenaGrenade** [comment]
Thanks for your work @chessai! I just tested my app and it works!

**Comment by ufo355** [comment]
> The fix was rolled out. The issue should be resolved. I tested all affected apps and they are now behaving as expected.

Hi @chessai, my app with ID 127425832565573 is still returning this error, could you look at it?

**Comment by kevinjon27** [comment]
@chessai my app with ID 365518614749604 still returning error also

**Comment by barbierb** [comment]
Hi @chessai i have the same problem here 952929405484786 since. Can you please also check mine ?

**Comment by chessai** [comment]
@ufo355 @kevinjon27 @ItsPower I'm looking into this.

**Comment by ufo355** [comment]
> @ufo355 @kevinjon27 @ItsPower I'm looking into this.

@chessai do you have some update on this? Can you give a rough estimation when it can start working?

**Comment by chessai** [comment]
> > @ufo355 @kevinjon27 @ItsPower I'm looking into this.
> 
> @chessai do you have some update on this? Can you give a rough estimation when it can start working?

See https://github.com/wit-ai/wit/issues/2112#issuecomment-866192800

**Comment by chessai** [comment]
@kevinjon27 @ItsPower @ufo355 your apps should now be functional.

**Comment by cheeseblock** [comment]
@chessai - still getting 500 error here app 949539342164783

**Comment by chainao** [comment]
@chessai, I am facing this same issue (500 Internal Server Error). My app id is 359014025633978. Could you, please, help me with that?

**Comment by painful-bug** [comment]
I'm still getting the same error
