### ISSUE TITLE
Is wit.ai something one shouldn't use for commercial purposes?

### ISSUE THREAD

**Issue by roots-ai** [wit-ai/wit#2106]
- There are several bugs and issues. It looks like a beta version and is unstable.
- The support staff is not active.

**Comment by kevinjon27** [comment]
Yeah, our commercial chatbot using wit.ai. And now, broken more than 1 week already, client . Email not answered, Wit.ai no update. Now I am so scared using Wit.ai. scolded by client, delay deadline, can't continue the project, staff no update.

**Comment by patapizza** [comment]
Hey @roots-ai, it's really up to you. What are the issues you've been experiencing?

Companies have been able to successfully use wit.ai. While we could be more responsive, we do provide support within our bandwidth.

**Comment by roots-ai** [comment]
> Hey @roots-ai, it's really up to you. What are the issues you've been experiencing?
> 
> Companies have been able to successfully use wit.ai. While we could be more responsive, we do provide support within our bandwidth.

Thank you for the reply.
We had been facing these issues for more than a week now
- https://github.com/wit-ai/wit/issues/2105
- https://github.com/wit-ai/wit/issues/2104

This caused a few 1-star ratings and a bad user experience to our initial user base. 

We are just a startup, I am not sure how bigger companies are tackling these bugs.

**Comment by patapizza** [comment]
Thanks for pointing me to these issues, and for your patience.

We're actively working on #2105 - we've prioritized your app, it should be fixed soon.
We'll look at #2104 once #2105 is resolved - they might be related.

**Comment by patapizza** [comment]
Both issues are now resolved. Let us know if you experience more issues.

Thank you!
