### ISSUE TITLE
"Failed parsing entities/Weather-Type.json" This is the error which i am getting every time when i am trying to upload the following zip file

### ISSUE THREAD

**Issue by Navin456** [wit-ai/wit#2107]

**Comment by Navin456** [comment]
"Failed parsing entities/Weather-Type.json" This is the error which i am getting every time when i am trying to upload the following zip file can anyone help me with [this?[](url)](url)
[wit_training_data.zip](https://github.com/wit-ai/wit/files/6606122/wit_training_data.zip)

**Comment by patapizza** [comment]
Closing in favor of https://github.com/wit-ai/wit/issues/2108.
