### ISSUE TITLE
"Urgent" Error in uploading a file which has been extracted by wit.ai only

### ISSUE THREAD

**Issue by Navin456** [wit-ai/wit#2108]
I was trying to upload a file in wit.ai to create an app. The file which I was uploading has been extracted by a working app created on wit.ai The error which I am getting is "Failed to validate utterance at index 30. Could not find value "7_day" for trait "Weather-Type". The file which I am uploading is 
[Smart-Mirror (3).zip](https://github.com/wit-ai/wit/files/6608156/Smart-Mirror.3.zip)  Can anyone help me with this? My app id is 151697126983342

**Comment by Navin456** [comment]
@chessai @patapizza @FengyangZhang Anyone of you can help?

**Comment by Navin456** [comment]
@chessai ??

**Comment by chessai** [comment]
Hi @Navin456, I'm taking a look at this, to diagnose the issue.

**Comment by chessai** [comment]
This is now resolved.
