### ISSUE TITLE
Understanding the use of Trait

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2111]
Hi,

Can anyone please help in understanding the use of Traits.
Checked the documentation but couldn't understand when we have to exactly use it and what is the difference between entities and Traits.

Thankyou

**Comment by patapizza** [comment]
Hi,

There's some info in the pro-tip of this recipe: https://wit.ai/docs/recipes#do-sentiment-analysis.

Traits help classifying a sentence into different categories of the same dimension. For example, intents are technically the different categories of the user intent dimension - they are values of a trait. `wit/sentiment` is another example, where a sentiment can be negative, positive or neutral.

Entities on the other hand, extract and resolve a particular sequence of words in a sentence, such as a location or a color.

Hope this helps!
