### ISSUE TITLE
[Urgent] Apps still returning 500

### ISSUE THREAD

**Issue by kevinjon27** [wit-ai/wit#2112]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
BUG

**What is the current behavior?**
500 error

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
All API requests are giving 500 ERROR.

**What is the expected behavior?**
return a JSON response

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
365518614749604

<img width="1440" alt="Screen Shot 2021-06-15 at 09 52 28" src="https://user-images.githubusercontent.com/12078441/122045004-5de03600-ce07-11eb-8043-9230dc5a1bda.png">
<img width="1025" alt="Screen Shot 2021-06-15 at 09 56 52" src="https://user-images.githubusercontent.com/12078441/122045012-60429000-ce07-11eb-835d-c34b4d0b9d0a.png">

I open again this issue because my issue already closed by admin and I can't reopen the issue.

**Comment by chessai** [comment]
Thanks for opening another issue. Looking into why your app is still returning a 500.

**Comment by chessai** [comment]
Hey @kevinjon27, we've identified why your app and others are returning a 500 error and are working on a fix. It's a separate issue than the other group of apps, but just happened around the same time.

**Comment by kevinjon27** [comment]
@chessai any updates?

**Comment by kevinjon27** [comment]
update from me.
just checking, create new project with indonesian language, train intent welcome and it's work.

but for the existing one still not working.

**Comment by chessai** [comment]
> update from me.
> just checking, create new project with indonesian language, train intent welcome and it's work.
> 
> but for the existing one still not working.

Can you try adding bulitin entities, eg. number and see if it works then?

**Comment by chessai** [comment]
> @chessai any updates?

An attempt at a fix has been rolled out. It should take effect sometime today. If it works I'll let you know.

**Comment by kevinjon27** [comment]
I already add builtin entities still not working on my existing project. but I create my new project with Indonesian language working so well. Because I need to fix urgently, we create new project and train one by one.

**Comment by patapizza** [comment]
We've found the issue and things should be back to normal by the end of the day.

**Comment by chessai** [comment]
Issue is resolved, just checked your app. Please let us know if you continue to have issues or something happens in the future.

**Comment by kevinjon27** [comment]
Hi @chessai & @patapizza thank you for helping. No problem so far, will update to you if there are still problems.

**Comment by andreper** [comment]
Hi @chessai. I have the same problem. My App ID is 835670900498791

**Comment by geekgarage** [comment]
Hi @chessai getting the same issue on app id 213144757442387. Calling intent to get the list works just fine but trying message query give error code 500

EDIT:
I created a new app, did nothing but make a GET message with the hello and it returned 200 in response but the intent was ofc empty. Then i did the "how far is it from [city1] to [city2]" utterance and trained it like the instruction video.

then i did another call and i got response code 500 on that app aswell (ID 587611892618701)

**Comment by chessai** [comment]
Hi @andreper @geekgarage if you are still experiencing issues, please open an issue with your app IDs and reproduction steps. Thanks
