### ISSUE TITLE
[Urgent] Wit.ai returns "Something went wrong, we've been notified" in a chatbot

### ISSUE THREAD

**Issue by benrz** [wit-ai/wit#2113]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
report a bug

**What is the current behavior?**
The wit.ai returns status: 500(internal Server Error), when I tried to access with the curl API. It seems to always return "Something went wrong, we've been notified" on every interaction with the chatbot.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
The message sent is:
{
    "error": "Something went wrong. We've been notified",
    "code": "unknown"
}

**What is the expected behavior?**
The expected behavior is for the NLP to return all of the entities defined.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App id: 905540740224967

**Comment by benrz** [comment]
I'm tried to make a new app with Indonesian (ID) (BETA) again, but it keeps replying this:
{
"error": "Something went wrong. We've been notified",
"code": "unknown"
}

I think there is a problem in Indonesian (ID) (BETA), because in English it returns the expected response. 
Please help me with the issue.

**Comment by kevinjon27** [comment]
ah I see, I tried using English version for new apps and its work. I'm also using Indonesian (ID) Beta, even tried new app using ID and still returning a error.

fyi @chessai

**Comment by chessai** [comment]
Working on it. See https://github.com/wit-ai/wit/issues/2112#issuecomment-862640243

**Comment by benrz** [comment]
Okay thanks for the info, I'll be waiting

**Comment by patapizza** [comment]
Closing this one in favor of https://github.com/wit-ai/wit/issues/2112.
