### ISSUE TITLE
Not able to transfer ownership of app

### ISSUE THREAD

**Issue by ghost** [wit-ai/wit#2114]
when i try to change ownership, i got the email but the transfer is not happening.

could you change the ownership of the following apps to dennispaulm
appid:
341883513753784
298845591193874
926130737835101
658247231561340
730010757588451
384048945885676
921723305012533
309918573489943
5567695856604353

**Comment by barbierb** [comment]
Hello @sabinchacko007 , have you tried to export your apps as files and let the second person import them as new app ? 

If this can help you :)

**Comment by ChrisyShine** [comment]
@sabinchacko007 The ownership of these apps have been transferred to dennispaulm. Can you take a look?

**Comment by ghost** [comment]
@ChrisyShine  thank you.
