### ISSUE TITLE
wit.ai local setup error

### ISSUE THREAD

**Issue by KrishnenduSG** [wit-ai/wit#2115]
Hi All

I was actually trying http://github.com/wit-ai/pywit. The steps I took were -

1- clone the repository.
2- run setup.py file.

I am getting couple of errors. I am posting the actual error below.

usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

please help me with this

**Comment by chessai** [comment]
Hi @KrishnenduSG, have you tried instead `pip install .`?

**Comment by KrishnenduSG** [comment]
@chessai now I have tried this with the help of pip install. Is there any other methods?

**Comment by chessai** [comment]
> @chessai now I have tried this with the help of pip install. Is there any other methods?
> 
> 

Did pip install fail? If yes, how did it fail?

**Comment by patapizza** [comment]
Please use https://github.com/wit-ai/pywit/issues for issues related to `pywit`.
