### ISSUE TITLE
Limits of Intents Creation 

### ISSUE THREAD

**Issue by KrishnenduSG** [wit-ai/wit#2116]
Is there any limits in intent creation? because i need to create more intents. Anyone know this???

**Comment by nishsinghal20** [comment]
@KrishnenduSG Can you provide some more context? Are you getting any error when trying to create a new Intent? How many intents does your have currently have?

**Comment by KrishnenduSG** [comment]
@nishsinghal20  I have only few intents but i wanna create around 1000 intents so that's why I have a doubt about this. is there any limits in intent creation???

in dialogflow ES edition I have seen that maximum number of intent creation is 2000 but I have no idea about wit.ai.

**Comment by patapizza** [comment]
There's no hard limit, but bear in mind that the model might start to have a hard time classifying data on 100+ classes.
