### ISSUE TITLE
App gone/deleted

### ISSUE THREAD

**Issue by danpickford** [wit-ai/wit#2117]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
I just logged into the portal and the app has been deleted no longer there.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I can see a test app but not the one I've been using for the past year or 2.
**What is the expected behavior?**
App that I built presentl.
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
My app stopped working around a week ago assume that's when it was deleted.

**Comment by patapizza** [comment]
Hi, are you the owner of the app?

**Comment by danpickford** [comment]
Yes for the last few years, logged in today and it was gone.

**Comment by patapizza** [comment]
Who are the contributors of your app if any?

**Comment by danpickford** [comment]
Just me, it's fine I've started recreating I'll be sure to download a backup this time.

**Comment by patapizza** [comment]
Are you sure there was no contributor added in the past to your app?
