### ISSUE TITLE
Message API "Something went wrong, we've been notified" when adding wit$datetime

### ISSUE THREAD

**Issue by TaraNaser** [wit-ai/wit#2118]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
After adding entity wit$datetime the message api for all trained expressions returns "Something went wrong, we've been notified", after deleting the entity the message api work fine
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
-Add wit$datetime entity
-Use https://api.wit.ai/message?q=&verbose=true&v=20190904
**What is the expected behavior?**
The message API to continue working
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID: 197690912223027

**Comment by patapizza** [comment]
Hi @TaraNaser,

Thanks for reporting. We're on it (https://github.com/wit-ai/wit/issues/2112).
