### ISSUE TITLE
Deleted Apps

### ISSUE THREAD

**Issue by ladislauek** [wit-ai/wit#2119]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

Report a bug.

**What is the current behavior?**

When I access the wit.ai site, two of my apps are no longer there, and the request responses for them fail.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Request for the production app:
curl -H 'Authorization: Bearer HBI75MQ7COSKPLHJBGR5ZLGXK3TLN3LC' 'https://api.wit.ai/message?v=20210623&q=hello%20wit'

Output:
{"error":"App not available","code":"bad-request"}

**What is the expected behavior?**

I would like my applications to be recovered, because in them there are a large number of already trained utterances, and my chatbot depends on this to work.
I don't understand why the applications got deleted.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

Production app:
2387433377997084

**Comment by patapizza** [comment]
Hi @ladislauek, which user is the owner of these apps, which are other contributors if any?

**Comment by ladislauek** [comment]
Hi @patapizza! I am the owner of these apps and have given access permission to co-workers who help me train and maintain a chatbot.

**Comment by unixguru2k** [comment]
Same as happened to us for two of our wit app instances.

They got randomly deleted in last couple days

And the backup isnt working as advertised after import.

**Comment by patapizza** [comment]
Hi, in the process of deleting Wit.ai accounts using GitHub login and data following the deprecation notice, we've uncovered a bug in the data model. The deletion of Wit.ai accounts using GitHub login also deleted the apps the accounts were contributing to. The data can't be recovered.

I'm really sorry.

<img width="1273" alt="Screen Shot 2021-06-24 at 9 38 39 AM" src="https://user-images.githubusercontent.com/1015208/123301026-065d5c80-d4d0-11eb-94e5-87f79e88ff58.png">


We're working on fixing the import feature, and on fixing the data model bug.

**Comment by ladislauek** [comment]
My co-workers and I, who logged in with Facebook accounts, decided to abandon wit.ai and use another solution.

As seen, the wit.ai platform proved to be unstable and unreliable.

I'm the one who has to say sorry.

**Comment by kenjij** [comment]
Just wanted to share if anyone else stumbles upon like me.

My app disappeared around July 1st. No warning, no alerts. I'm not opening a ticket as I see they're just getting closed.
Very lame handling, saying working on a bug fix and closing the ticket without actually doing so.

So is the solution just to go somewhere else? What is offered to us here? Thanks 👎

**Comment by patapizza** [comment]
The data model issue has been fixed, but the lost apps can't be covered.
We're still working on the import fix.

**Comment by klemensz** [comment]
Two of our apps that we use in production disappeared, and we're just getting "App not available" back from the API. The apps were connected to my Facebook account, other apps (that we don't actually use any more) are still there.
