### ISSUE TITLE
German datetime

### ISSUE THREAD

**Issue by hactar** [wit-ai/wit#212]
German still appears to be missing datetime. I forked duckling a few months ago here to add German support for dates: https://github.com/hactar/duckling

I haven't created a pull request because some of my tests fail, but my closure expertise is not good enough to fix the tests. The following issues would need to be fixed:

1) ----
German uses no spaces in numbers. The number 33 is dreiunddreissig in german, which is three (drei) and (und) thirty (dreissig). I have created a rule that successfully matches "drei und dreissig" but I cannot figure out how to get the rule to ignore the spaces. C
```
"numbers und" 
[(integer 2 9) #"und" (integer 20 90 #(#{20 30 40 50 60 70 80 90} (:value %)))] 
{:dim :number 
:integer true 
:value (+ (:value %1) (:value %3))}
```

```
duckling.core=> (play :de$numbers "drei und dreissig") 
W ----------------- 3 | number | numbers und | P = 0.0000 | integer (0..19) + + 
-------- 2 | number | integer (20..90) | P = 0.0000 | 
---- 1 | number | integer (0..19) | P = 0.0000 | 
drei und dreissig
1 winners: 
number {:type "value", :value 33} {:integer true} 
For further info: (details idx) where 1 <= idx <= 3 
#'duckling.core/token 
duckling.core=> (play :de$numbers "dreiunddreissig") 
dreiunddreissig
0 winners: 
For further info: (details idx) where 1 <= idx <= 0 
#'duckling.core/token 
duckling.core=>
```

2) ----
The test "heute um 20:00" (today at 20:00) fails, even though when playing the string, the result appears to be correct:
```
3 winners: 
number {:type "value", :value 20} {:integer true} 
number {:type "value", :value 0} {:integer true} 
time {:values ({:type "value", :value "2013-02-12T20:00:00.000-02:00", :grain :minute}), :type "value", :value "2013-02-12T20:00:00.000-02:00", :grain :minute} {:direction nil}
```

**Comment by patapizza** [comment]
Hi hactar,

Thank you for the interest!
We're about to release a Duckling update that will allow partial work. Hopefully this will enable to support new languages more quickly.

**Comment by l5t** [comment]
Thanks again for the hard work and so sorry for the lack of support. I added the issue in the Duckling repo https://github.com/wit-ai/duckling/issues/91. Closing
