### ISSUE TITLE
Deleted App

### ISSUE THREAD

**Issue by web-pda** [wit-ai/wit#2120]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?** Report a Bug

**What is the current behavior?** One of our apps is deleted. Yesterday it was there but when we checked today it was gone.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.** If you check with this App ID, you will see that app is not available: 2348639601920387

**What is the expected behavior?** We need recovery of the app because there were lots (years) of trainings on that app.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.** App ID: 2348639601920387

**Comment by patapizza** [comment]
Hi @web-pda, are you the owner of the app? Which are the other contributors to your app?

**Comment by web-pda** [comment]
@patapizza I am the owner of the app and have given access permission to one of my co-workers who help me train and maintain the chatbot.

**Comment by patapizza** [comment]
Hi @web-pda, thanks for confirming.
I'm sorry about the data loss. See my comment in https://github.com/wit-ai/wit/issues/2119.
