### ISSUE TITLE
App Import Error

### ISSUE THREAD

**Issue by web-pda** [wit-ai/wit#2121]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?** Report a Bug

**What is the current behavior?** When we try to create a new app from a backup, we experience this bug. There are no intent with the name in the error.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.** Tried to import a backup file.

**What is the expected behavior?** Successful import of all intents, entities and utterances. Currently only entities are imported.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
Backup App ID: 2348639601920387
New App ID: 321717662918828

![2021-06-23 215901](https://user-images.githubusercontent.com/48081365/123154813-0463b100-d470-11eb-8627-1f3878709114.png)

**Comment by chessai** [comment]
Was the backup app deleted? I can't find it anymore.

**Comment by ramh** [comment]
Closing since there was no response.
