### ISSUE TITLE
Wit.ai portal is not loading apps

### ISSUE THREAD

**Issue by unixguru2k** [wit-ai/wit#2122]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**
Wit.ai is not loading any apps

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
It should load apps

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
for all app ids

**Comment by magicwarms** [comment]
Same here mate! I can't open all my apps...

**Comment by gnovis** [comment]
wit.ai/apps returns message: **Sorry, this content isn't available right now**

**Comment by johnnietien** [comment]
Same with me... I using facebook account and cannot open wit.ai/apss --> Sorry, this content isn't available right now.
The API request also fail.

**Comment by dlmwright** [comment]
Same yes its not working.

**Comment by dlmwright** [comment]
wit.ai/apps returns message: Sorry, this content isn't available right now

**Comment by nishsinghal20** [comment]
Hi folks! Thanks for reporting the issue. We are aware of this and are actively working on addressing it as soon as possible!

**Comment by simonprickett** [comment]
Same issue here.  the app is working via the SDK but I can't manage it in the wit.ai site.

**Comment by SisikHBS** [comment]
Sorry, this content isn't available right now on /apps page can't access any apps, opened another account still got same error. My sister opened a account from different city she also saw same error, seems like system-wide issue

**Comment by nishsinghal20** [comment]
We've submitted a fix for this issue. We expect the fix the issue to be resolved by 3:00 pm (PDT) today.

**Comment by nishsinghal20** [comment]
This issue should be resolved now. Can folks please confirm?

**Comment by AceTheCreator** [comment]
@nishsinghal20 bot seems not to be learning... when I create nested entities and train, then when I input the text again for confirmation, it doesn't return the expected result

**Comment by AceTheCreator** [comment]
and for whatever reason, it's just showing training ongoing only(even when there's no ongoing training)

**Comment by SisikHBS** [comment]
> This issue should be resolved now. Can folks please confirm?

Yes, thank you so much!

**Comment by gnovis** [comment]
> This issue should be resolved now. Can folks please confirm?

Yes, now it works, thank you.

**Comment by magicwarms** [comment]
> This issue should be resolved now. Can folks please confirm?

It worked now, thanks, team!

**Comment by patapizza** [comment]
@AceTheCreator Please open a new issue with your app ID. Thanks.

**Comment by legendko** [comment]
I'm having the same issue now. I've just logged in for the first time, wanted to create my first app, but the [apps page ](https://wit.ai/apps) is infinitely loading
