### ISSUE TITLE
Wit.ai app not redirecting to Facebook page

### ISSUE THREAD

**Issue by Vidyaradhya** [wit-ai/wit#2123]
When we login to Facebook from wit.ai app, it is throwing an error **"Sorry, this content isn't available right now".**
we tried in 3 different systems and the issue persists.
Is the server down? if so when is it expected to be fixed.

**Comment by patapizza** [comment]
Thanks for reporting. Closing in favor of https://github.com/wit-ai/wit/issues/2122

**Comment by nishsinghal20** [comment]
Hello! Thanks for reporting the issue. We are aware of this and are actively working on addressing it as soon as possible.

**Comment by Vidyaradhya** [comment]
Thanks a lot. It is working fine now!
