### ISSUE TITLE
App is GONE

### ISSUE THREAD

**Issue by nickcbarone** [wit-ai/wit#2124]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
I don't see my app at all anymore. When I go to its URL (https://wit.ai/apps/1919183118151191/ ), I get "Page Not Found We cannot find the app you're looking for."

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I go to https://wit.ai/apps/1919183118151191/ and don't see my app.

I go to https://wit.ai/apps and don't see my app

**What is the expected behavior?**
I should see my app on the /apps page

I should land on the Understanding page of my app when I go directly to its URL

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1919183118151191****

**Comment by terolepisto** [comment]
Mine dissappeared also. Not sure if it has something to do with the fact I've created the Apps with legacy Github account. Somehow the user persmissions haven't transferred right for my Facebook Account so now the Wit.ai's App is unaccessible.

The Api call's and everything else shows the app is up and running, but Dashboard is not accessible.

**Comment by patapizza** [comment]
Hi @nickcbarone,

Sorry about that, see my comment in https://github.com/wit-ai/wit/issues/2119.

@terolepisto All your apps will transfer to your FB linked account.
