### ISSUE TITLE
Failed to validate utterance: POST /utterances

### ISSUE THREAD

**Issue by richwednesday** [wit-ai/wit#2125]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?** 
report a *bug*

**What is the current behavior?**
POST /utterances returns 
```
{
    "error": "Failed to validate utterance at index 0",
    "code": "bad-request"
}
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
My request is
```
[{
    "text":"what's your sex",
    "entities": [{"entity":"intent","value":"gender"}],
    "trait": [],
    "intent":"gender"
}]
```

**What is the expected behavior?**
```
{ sent: true, n: 1 }
```

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID is 575775526932360

I am having to re-train because my apps disappeared.

**Comment by patapizza** [comment]
HI @richwednesday, it looks like you're trying to set the intent both in the `intent` field and as an entity. Intents are no longer considered entities; try to provide an empty array for the `entities` field.

**Comment by richwednesday** [comment]
Hello @patapizza, it is the same behavior. I had tried different alterations of the same request.

**Comment by richwednesday** [comment]
<img width="551" alt="Screenshot 2021-07-05 at 10 17 31" src="https://user-images.githubusercontent.com/16841165/124456493-48ad5600-dd7a-11eb-8c9e-2b0bdf767b10.png">

Hello @patapizza , see it is the same behaviour.
