### ISSUE TITLE
App is deleted

### ISSUE THREAD

**Issue by terolepisto** [wit-ai/wit#2126]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
My live app is deleted.

I've used the app Jun 10 so I'm pretty sure i've logged in with Facebook to use it. 

Now our client contacted us that they can't log in to wit.ai and after that several created Wit.ai Apps inclunding our clients live app that've been in use daily were gone.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID:
2215129178546496

**Comment by Chris-Ar** [comment]
Hello,

Our app was deleted too.
AppID: 3345749878784230

It was a shared app. Please restore it as it was a live app.

Best Regards

**Comment by patapizza** [comment]
Hi @terolepisto and @Chris-Ar,

Sorry about that, see my comment in #2119.
