### ISSUE TITLE
Message API {"error":"Something went wrong. We've been notified","code":"unknown"}

### ISSUE THREAD

**Issue by andreper** [wit-ai/wit#2127]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
The app was working fine a few weeks ago, but now it isn't work and I didn't make any change on it. It allways returns the same message: {"error":"Something went wrong. We've been notified","code":"unknown"} 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- PHP CURL
- URL: 'https://api.wit.ai/message?q='.urlencode('quiero hacer una reserva')
- Header: Authorization: Bearer XXXXXXXXXXX
**What is the expected behavior?**
The message API to continue working
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID: 835670900498791

**Comment by andreper** [comment]
Some feedback about this issue?

**Comment by CleanestMink126** [comment]
Hi @andreper! We've been taking a look into this issue and will update you when we have a fix on the way (unfortunately most likely after the long weekend).

**Comment by chessai** [comment]
Hi @andreper, I'm looking into this now.

**Comment by chessai** [comment]
Hi @andreper, I have rolled out a fix, it should land soon.

**Comment by chessai** [comment]
This fix rolled out. Let us know if you have any other problems.
