### ISSUE TITLE
Typing in the "Utterance" field throws me to the "My apps" page

### ISSUE THREAD

**Issue by PaavoNykanen** [wit-ai/wit#2128]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
When typing utterances, the site works fine for a few hours and after some time starts throwing me to the "My apps" page after typing anything in the utterance field. Happened today and yesterday and both times worked fine for a few hours and then for the rest of the day this problem occurred. Only the utterance field does this and typing just one letter triggers it.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- Just typing utterances, works fine for an hour or so. 
- After some time, typing anything in the utterance field throws me to the "My apps" page.
**What is the expected behavior?**
The same as before the bug starts. Typing in the utterance field doesn't switch pages.
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
In all the applications I try to type in. They all use the Finnish language. 
Here is one App ID: 418025925910798

**Comment by CleanestMink126** [comment]
I'm having a hard time replicating the error, can you confirm:

1. This is the main Utterance input box on the "Understanding" page.
2. What browser you're using.
3. The error persists after reloading the page and restarting the browser.

Thanks!

**Comment by PaavoNykanen** [comment]
1. Yes, the main utterance box
2. I'm using Firefox, but it also happened with Chrome and Microsoft Edge
3. Yes

**Comment by ghost** [comment]
Hi, I am also experiencing this bug. 
I thought I could circumvent it by sending myself live utterances through the API and then editing them in the "Review your live utterances..." section, but upon clicking the caret next to the utterance, I get redirected to the "My Apps" page.

I am using Chrome (98.0.4758.102), the same happens in Firefox (97.0.1).
My App ID is 745966103054232.

Thanks for your help.

**Comment by yuzh174** [comment]
Sorry to be super late in this question thread. I believe this issue should be gone by now. Let us know if you still experience this bug.

**Comment by yuzh174** [comment]
Close this task. Please create a new issue if you see it happens again.
