### ISSUE TITLE
CORS issue on website

### ISSUE THREAD

**Issue by safwank** [wit-ai/wit#213]
I'm not sure if this is the right forum for reporting this kind of issue, but I'm unable to sign on to the website using my GitHub account. I keep getting the following error

> XMLHttpRequest cannot load https://api.wit.ai/me/github_signin. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://wit.ai' is therefore not allowed access. The response had HTTP status code 500.

Looks like a CORS issue to me.

**Comment by martinraison** [comment]
We had an issue in production today, sorry for the inconvenience. Are you able to sign up now?

**Comment by safwank** [comment]
@martinraison All good now, cheers!

**Comment by cgarvis** [comment]
I get a CORS error on the inbox page.  Coming from cloudfront.

**Comment by blandinw** [comment]
Thanks for the report @cgarvis. We're working on a fix. The error is about a font and should not impact your experience too much
