### ISSUE TITLE
App Not training 

### ISSUE THREAD

**Issue by jurneek** [wit-ai/wit#2131]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
When putting phrases to train the app isn't picking them up even pasted phrases that have been trained and picked up previously aren't pulling any intents
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2949637558381508
781287162557039

**Comment by CleanestMink126** [comment]
Hello thanks for submitting this issue. We're currently tracking this in #2130 so please follow there and we'll let you know when we have more updates.
