### ISSUE TITLE
My app suddenly disappeared

### ISSUE THREAD

**Issue by 14leander** [wit-ai/wit#2132]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

The app suddenly dissapeared the app id was 2096249480457187

**Comment by kelisidian** [comment]
We run into the same issue, but we don't know the app id. What we can provide is the Server Access Token, which I have sent to the help@wit.ai mail address.

**Comment by alxferraz** [comment]
Same thing happened to me this morning. I'll try emailing them.

**Comment by CleanestMink126** [comment]
Hi everyone, sorry about this issue. We've identified the problem and you can see more details in #2119.
