### ISSUE TITLE
App stopped understanding - limitations inquiry

### ISSUE THREAD

**Issue by mohammad-melhem** [wit-ai/wit#2133]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
A question (or possibly a bug)

**What is the current behavior?**
When we reached 3000 validated utterances, the app stopped understanding most of the sentences (which was working on the live app for so long successfully in our bot). And also, we weren't able to validate any more utterances, we would get the following error:

![wit-train-error](https://user-images.githubusercontent.com/10730846/124379304-ddeb1480-dcbe-11eb-92f6-2991259deec9.png)

However, after we deleted around 20 utterances, it went back to understanding and validating as expected (so now everything is fine again, but we want to check what is the issue in order to know how to proceed with training if there are limitations). So the question is are there any limitations on utterances per app (or per entity or intent) that might have caused this? or is there another issue that might have happened and maybe deleting retrained the app causing it to understand again. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
We are assuming the cause reaching 3000 utterances.

**What is the expected behavior?**
understand/validate utterances with no limit (we need the ability to continue training without affecting the live bot responses). 

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1920151674738030

Thanks a lot in advance ^_^

**Comment by yuzh174** [comment]
Hi @mohammad-melhem , sorry to get back to this thread super late. I assume this is not an issue anymore. I can see your app is working as expected. Let us know if you still see any issues.
