### ISSUE TITLE
Entity '594785521910281' not found when I try to export or get utterances

### ISSUE THREAD

**Issue by TaraNaser** [wit-ai/wit#2134]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
When I try to get utterances or export the wit app I get Entity '594785521910281' not found 
and Entity '1012312876260892' not found for another wit app
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
![image](https://user-images.githubusercontent.com/71825913/124385845-341c7f80-dce0-11eb-827f-f6f90c6f4242.png)

**What is the expected behavior?**
To display the utterances trained 
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID: 2837091073271500
App ID: 315538893568231

**Comment by CleanestMink126** [comment]
Hello! Looks like a couple entities were deleted from the apps but not successfully removed from the listed utterances. I've now removed all its references and the utterances should be successfully loading now.
