### ISSUE TITLE
Wit app doesn't recognize May as a date 

### ISSUE THREAD

**Issue by TaraNaser** [wit-ai/wit#2135]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
May is not being recognized as a date
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
![image](https://user-images.githubusercontent.com/71825913/124436965-38e44080-dd7f-11eb-82a3-aef12f5b0f23.png)

**What is the expected behavior?**
To recognize the date and return entity DateTime 
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App id: 2278713975545975

**Comment by chessai** [comment]
This is actually a duckling issue. See https://github.com/facebook/duckling/issues/565
