### ISSUE TITLE
/samples not working

### ISSUE THREAD

**Issue by web-pda** [wit-ai/wit#2136]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?** Report a Bug

**What is the current behavior?** API /samples not working. It is giving this error: _Unsupported get request. Object with ID 'samples' does not exist, cannot be loaded due to missing permissions, or does not support this operation_. /intents, /traits or /entities are working but /samples is not working.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Call https://api.wit.ai/samples (GET or POST) with your Server Access Token and you will see the error.

**What is the expected behavior?** It should return samples or we should be able to add samples. (Depending on the call)

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.** App ID: 1842044665953940

**Comment by chessai** [comment]
Hi @web-pda, this endpoint is unsupported, and most use cases of it should be covered by GET /utterances.
