### ISSUE TITLE
wit doesn't return nointent 

### ISSUE THREAD

**Issue by sophiexr** [wit-ai/wit#2137]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
I assume it's a bug

**What is the current behavior?**
Since 15/06 we don't get nointentmatch and therefore our customers see answers in every question, even gibberish (e.g. aslkdnas) with very low confidence. 

In May, 3094 out of 17000 questions got a reply nointentmatch (around the same percentage as in the previous months) but after June 15th  we have 0.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Type any characters or questions that make no sense. Bot will  return a trait value instead of no intent match

**What is the expected behavior?**
Bot should only give replies to questions that has been trained. It was working just fine up to 15/06.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot**
app id 2841817995840539

**Comment by ruoyipu** [comment]
Hi @sophiexr,

About a year ago, we made intents first class citizens and gave them their own dedicated field in the response.
We have examples of the new response format here: https://wit.ai/docs/http/20200513/#get__message_link

If wit doesn't match an intent, the `intents` field in the http response will contain an empty array.
I would suggest checking the `intents` field first for empty array before checking the `traits` field.

**Comment by sophiexr** [comment]
hello again,

@ruoyipu 
I am aware of the change in the intents since we're a using the app for few years. This change you're referring to didn't affect the training of our app.

Our question is if something has changed on the algorithm on how Wit.Ai matches unknown trained answers.
Before 31/5 we were getting no matches but now we are always getting a match (even with low confidence ).

Here are some examples below from our logs in order to make sense.

In this example, we had a Query of "01" and we got no matches as its the correct behavior
but after 06/2021 we started getting matches for the same Queries.

Example 1
At 5/31/2021, 4:13:35.653 PM
we're getting no match from our Query in Wit.Ai as follows below
{
"MachineName":".........X12",
"Type":"message",
"Message":"nointentmatch:",
"ConversationId":"............-a",
"ChannelId":"directline",
"ActivityId":"..........-a|0000028",
"From":".....575",
"CustomerType":"Individual",
"CustomerCode":"......5",
"To":"onprempirbot@Szs5wE8wLbE",
"LuisResult":"{"query": "01","intents": [],"entities": []}",
"Query":"01"
} 

and at 7/13/2021, 4:40:27.989 PM
we're getting a match "LOAN_NEW" from the same Query in Wit.Ai as follows below which is irrelevant
{ 
"MachineName":".........X1",
"Type":"message",
"Message":"Mπορείτε να κάνετε άμεσα αίτηση για νέο δάνειο επιλέγοντας [e-Loan](winbank://eLoan/eLoanCalc).",
"ConversationId":"............-a",
"ChannelId":"directline",
"ActivityId":"8..........-a|0000003",
"From":".....668",
"CustomerType":"Individual",
"CustomerCode":"......4",
"To":"onprempirbot@Szs5wE8wLbE",
"Query":"01","Intent":"LOAN_NEW"
} 


Example 2
At 5/31/2021, 4:07:55.201 PM 
we're getting no match from our Query in Wit.Ai as follows below
{
"MachineName":".........X1",
"Type":"message",
"Message":"nointentmatch:",
"ConversationId":".........-a",
"ChannelId":"directline",
"ActivityId":".........-a|0000007",
"CustomerCode":".....065",
"CustomerType":"Individual",
"From":"......5",
"To":"onprempirbot@Szs5wE8wLbE",
"LuisResult":"{"query": "ειναι στανταρ σε μενα ομως γιατι?""intents": [],"entities\": []}",
"Query":"ειναι στανταρ σε μενα ομως γιατι?"
} 

and at 7/13/2021, 4:41:21.694 PM 
we're getting a match "PERSONAL_INFO" from the same Query in Wit.Ai as follows below which is irrelevant
{
"MachineName":" .........  X1",
"ConversationId":" ........  a",
"Message":"Δεν μου επιτρέπεται να μιλάω για προσωπικά θέματα.",
"ChannelId":"directline",
"ActivityId":" ........  -a|0000005",
"Type":"message",
"CustomerType":"Individual",
"CustomerCode":"6347104",
"From":"EB1607668",
"To":"onprempirbot@Szs5wE8wLbE",
"Query":"ειναι στανταρ σε μενα ομως γιατι?","Intent":"PERSONAL_INFO"
}

**Comment by sophiexr** [comment]
any news on that problem? we would really appreciate an investigation in that matter, as it creates issues with our customers.
thanks

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
