### ISSUE TITLE
Wit stuck with Training Ongoing

### ISSUE THREAD

**Issue by sudeepjd** [wit-ai/wit#2138]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question about Wit training.

**What is the current behavior?**
I have about 48 to 50 utterances and 7 intents and 8 entities.. The last training time took 47 seconds.. I added 1 another utterance about 5 hours ago and the training is still ongoing.. I think it is stuck in a training loop. I tried adding more utterances, deleting utterances and updating them to try and get the training restarted, but to no avail.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Training should restart when new data is added in.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
534235761222426

Would be helpful if someone can help restart the training process. Thanks.

**Comment by ruoyipu** [comment]
Hi @sudeepjd,

I've restarted the training process. It's should now be complete.

**Comment by sudeepjd** [comment]
Thank you... Works now!!!
