### ISSUE TITLE
Message API not returning intents for some trained utterances

### ISSUE THREAD

**Issue by TaraNaser** [wit-ai/wit#2139]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
Message API not returning intents for some trained utterances
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
![image](https://user-images.githubusercontent.com/71825913/124771925-3a129a80-df44-11eb-827d-5102da53dc73.png)
![image](https://user-images.githubusercontent.com/71825913/124771969-41d23f00-df44-11eb-9bad-866493c65118.png)
**What is the expected behavior?**
To return the intent name
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App id: 5a7836d3-c59b-4914-84b3-10819489f65d

**Comment by ruoyipu** [comment]
Hi @TaraNaser,

The app ID provided is not valid. Could you go to the settings page of the wit.ai app and copy the "App ID:" number from there?

Thank you!

**Comment by ruoyipu** [comment]
Hi @TaraNaser,

Unfortunately I've been unable to repro the issue.

Here's a paste of what I've tried and received:
```
> curl \
 -H 'Authorization: Bearer $TOKEN' \
 'https://api.wit.ai/message?v=20190604&q=location'
> {"_text":"location","entities":{"intent":[{"confidence":0.94938643278642,"value":"location"}]},"WARNING":"DEPRECATED","msg_id":"1NeioH9310xOflfzD"}
```

One thing you could try is updating the version of the request. We've updated our apis to separate intents and entities into their own fields in the response. https://wit.ai/docs/http/20200513/#get__message_link
For example: 
```
> curl \
 -H 'Authorization: Bearer $TOKEN' \
 'https://api.wit.ai/message?v=20210708&q=location'

> {"text":"location","intents":[{"id":"925003287859353","name":"location","confidence":0.9494}],"entities":{},"traits":{}}
```

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
