### ISSUE TITLE
Issue in creating intent via api

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2141]
Hi,
We created an app in Khmer language and when we tried to create an intent with khmer language using the api, it showed the below error . But we were able to create the intent in khmer language via ui. How can we create an intent in different language via api.

API
===
https://api.wit.ai/intents?v=20200513

BODY
====
{"name":"តើរបៀបចុះឈ្មោះយ៉ាងដូចម្តេច?"
}

RESPONSE
=======
{
    "error": "Only use 2+ alphanumeric and underscore characters when naming your intent. The intent name cannot start with a number.",
    "code": "bad-request"
}

**Comment by chessai** [comment]
Hi,

Only english uppercase and lowercase characters and numbers (0-9) are supported.
