### ISSUE TITLE
Sub Entities inside Entities on Utterance training gets deleted

### ISSUE THREAD

**Issue by sudeepjd** [wit-ai/wit#2142]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug

**What is the current behavior?**
On the Wit.ai page, when selecting a _Resolved Value_ for a specific keyword inside another entity, the entity gets deleted and the selection of the entity on the Utterances box changes and moves to some other location at the beginning of the statement. So I am not able to select a resolved value for a subentity. The value selected then adds into the keywords.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**After the selections:**
![image](https://user-images.githubusercontent.com/12654213/126065940-cc3053d5-9b3f-4a19-8b2c-b037b543ef8b.png)

**When changing the Value to the Keyword**
I then change the Resolved value of the sub-entity _program_ to the correct Keyword 'Single Aisle Programs' and the following happens:
![image](https://user-images.githubusercontent.com/12654213/126065981-edd88d9d-e74a-450c-907b-1481e6d6743d.png)
The earlier selected entities get deleted and the position of the selection in the Utterance box changes to the beginning.

Also I by mistake trained one of the utterances after changing the Resolved value and now even though I corrected and the model is retrained.. It seems to be giving me incorrect entities as can be seen in the Add New Utterance snapshot below. 

![image](https://user-images.githubusercontent.com/12654213/126067042-0f05102e-c138-4331-8d4f-1e660a514282.png)

**What is the expected behavior?**
The entities should not get deleted and only the Resolved Value should change to the Keyword selected value.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
818026398887716

**Comment by patapizza** [comment]
Hi @sudeepjd, this is indeed a bug. Thanks for reporting.

**Comment by nausicaasnow** [comment]
fixed.
