### ISSUE TITLE
Training Stuck

### ISSUE THREAD

**Issue by sudeepjd** [wit-ai/wit#2144]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question

**What is the current behavior?**
Training has been stuck for over 4 hours. Please help restart training

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Training should automatically restart when new utterances have been added. This has happened to me twice on different apps. Something seems to be causing the training to go in a loop and not getting completed. Please help restart the training. Or if possible, provide a method where we can restart the training from the Wit platform, if it is stuck for over an hour. I only have 38 utterances.

**What is the expected behavior?**
Training should automatically restart when new utterances have been added.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
563735461658203

**Comment by nausicaasnow** [comment]
Retrained:)
