### ISSUE TITLE
Training Stuck saying ongoing

### ISSUE THREAD

**Issue by DylWaters** [wit-ai/wit#2145]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question
**What is the current behavior?**
My app has been stuck saying training ongoing for over an hour even though it said the last train took 39 seconds, it has been a long time since it has said training complete and i am concerned that is has bugged or needs to be restarted  
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
That the training should be completed within a certain amount of time yet it has been stuck saying training ongoing
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
670398657011970

**Comment by nausicaasnow** [comment]
Retrained :)
