### ISSUE TITLE
Custom sentences?

### ISSUE THREAD

**Issue by ghost** [wit-ai/wit#2146]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question

**What is the current behavior?**
i'm not sure how to do this, so it just doesnt work

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
not a bug, not sure how to fix

**What is the expected behavior?**
What I want is that if I say "Play a song" or "Play some random song" it infers that the intent is "play_song".

For example: 
Currently if I say "Play Nights by Frank Ocean" it infers the intent is "play_song". (correct)
What I want is that if I say "Play a song" or "Play some random song" it infers that the intent is "play_song" and attach the "random" trait. I have tried to do this in the understanding tag but it infers "some random song" as a song name and correcting it does nothing. So the question is: Are custom specific commands possible?

The endgoal is: Use wit.ai voice to text and then pass it through this ai to play music. I know this has been done but I wanna do this to learn. Another solution is maybe check the voice to text result and if its not in a set of customized questions it goes through the ai? I'm not sure. Just wondering.

Also, is there a way to set preset words? For example only use the play_song intent if the sentence starts with "play".

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
not applicable

**Comment by patapizza** [comment]
Hi @IdanYekutiel,

Are you getting the `random` trait? Entities are going to be recognized in similar sentence context, to generalize to unseen inputs. You'd need to filter these entities out based on your database of songs.

Hope this helps. If you need more help, please share an app ID so we can look into what you've built so far.

**Comment by ghost** [comment]
I could train it to get the random trait, but, that's not the only issue. What I want to achieve is getting the random trait + some other intent or trait.

For example, if I say "Play some music" it's going to infer that the song name is "some music". The idea is for it to infer that the intent is play_music with the random trait and no song name so that I can understand to play a totally random song.

Edit: Just read the answer again a couple of times and I understood exactly what you meant know. Makes a ton of sense, thanks! Would appreciate it if you responded my other questions tho :)

----

Also, another question: if i have "Play the latest Travis Scott album" or "Play the latest Travis Scott song". 

Should that be 2 intents? play_album and play_song? or should it have some kind of trait? I'm wondering because because I wanna know if it's a good idea to have different intents for small modifications of the same idea instead of having a generalized play_music intent.

Generalized it's easier to understand because I can say "Play the Blonde album" and the AI will understand that Blonde is the album name. The issue only comes when I have to give the "same thing" (in the previous example "Travis Scott") for different things. (So "song" and "album") 

How do I manage that? Do I just make a lot of intents? What should I do?

----

Also,  my app ID would be useless as I deleted all utterances because I am going to get a ton of info from spotify and pass it in. The thing is that before doing so I wanna know how to handle this small things.

**Comment by ghost** [comment]
Also, I don't have a database of songs. The songs could be anything. Does not matter how random it sounds. These song names I did the examples with are just random and not part of a database. I just want the AI to infer I want to play a song if I say "play x by y" and etc.

**Comment by ghost** [comment]
Also, another question: (hope i'ts not annoying) should I have different apps for different things or just all in one? For example: If I want an assistant to tell me the weather, play music, set timers, etc etc can that all be in one app? Or should I first check the prefix of what I want to do and send it to the corresponding app?

And another one: If I wanna have something like "Play my favorite song" how does that work? a play song intent with some kind of "type" trait or something similar? How would that tie with the previous question? a type trait could be used for a ton of different things so it would have a ton of values or what would you do?

I'm just trying to ask as much as I can haha.
