### ISSUE TITLE
Training ongoing indefinitely

### ISSUE THREAD

**Issue by zapteryx** [wit-ai/wit#2148]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug

**What is the current behavior?**
Training ongoing indefinitely

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I can't provide steps to reproduce.

**What is the expected behavior?**
Training ongoing finishes after awhile

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID: 480451076271253

**Comment by zapteryx** [comment]
Hi, any updates on this? I'm unable to add any new intents due to this issue as the AI refuses to learn anything new, and it's been a real pain trying to add anything due to this.

**Comment by patapizza** [comment]
Hi @zapteryx, I just fixed your app.
