### ISSUE TITLE
The whole request doesnt actually happen.

### ISSUE THREAD

**Issue by ghost** [wit-ai/wit#2149]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug report, I think.

**What is the current behavior?**
Basically if I send 200 utterances to the API not all of them actually get added. Only about 170-180 usually. Or for example I had 250 utterances which I did a delete request for but after a while 80 where not deleted. I'm not sure if this is intended behavior or if there is something wrong with the request I'm doing but if possible I wanna fix it.

The thing about the delete request is that I am getting all utterances and using that same data to do the request so if I send the same data I receive (ofc, with the correct format) there is no way that's the issue.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I just do a post or delete request. If necessary I can send the request I'm doing.

Also: Does your app get retrained after a delete request?

**What is the expected behavior?**
All utterances posted or deleted.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
776884552991902

**Comment by kitchWWW** [comment]
Hello! Thanks so much for reaching out to us. I suspect if you are doing these in large one-off batches, you are running into rate limiting issues. Please email help@wit.ai with more details about your use case and we'll see if we can help you out! Please re-open if you continue to have issues.

**Comment by ghost** [comment]
Hi, message sent. :)

**Comment by ghost** [comment]
Hi, just wondering how long it takes for the team to respond.
