### ISSUE TITLE
Entity/Story not recognised

### ISSUE THREAD

**Issue by tiberiumaxim** [wit-ai/wit#215]
Found this: https://wit.ai/blog/2016/04/19/botengine-day7
And tried to reproduce the example for myself. I created the stories and mapped the entities then trained it in the understanding tab.

When tested it, in the console, I get no reply from the chat bot or wrong reply (For example: My name is Bob returns Booked your flight)
Tested it via api (node) and I get the same wrong reply.

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
