### ISSUE TITLE
can i migrate a project from Wit.ai to WCP ( the enterprise version of Wit ? 

### ISSUE THREAD

**Issue by abudakar** [wit-ai/wit#2152]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
can i migrate a project from Wit.ai to WCP ( the enterprise version of Wit ?

**Comment by kitchWWW** [comment]
Hi! Wit.ai is not associated with WCP. Our services are free to use, and we provide all the features we offer equally without a paywall. If there are any features you would like to see that we don't currently offer, feel free to make a pull request or open a specific issue and we'll see if it aligns with our roadmap!
