### ISSUE TITLE
Wit Speech API return empty text

### ISSUE THREAD

**Issue by siyanew** [wit-ai/wit#2153]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

report a bug

**What is the current behavior?**

speech api always returns empty text

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

In every situations it returns empty text

**What is the expected behavior?**

return speech was spoken in wav or ogg files

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

_485244245601693_ and _1172799353138600_

**Comment by n0th1ng-else** [comment]
This happens to me as well! Previously it was working fine. But now the response is empty!

appId 585410835512762 language is set to Russian

**Comment by DegtiarDmitro** [comment]
Also, this happens to me! Everything worked fine until July 28.
Almost all responses are empty. Sometimes the response is not empty, but really not correct. I have 10 standard audio files (for test), and when I made a test requests all the responses were correct. But now all the responses to my test requests  are empty or incorrect.

appId 2654426877976507 language is also set to Russian

**Comment by patapizza** [comment]
Hi, thanks for reporting. I'm looking into this.

**Comment by mancu37** [comment]
Same here!, most of the time responses are empty and when return something is not correct. AppId: 2727554580829122. The Application is set to Spanish.

**Comment by patapizza** [comment]
Can you all confirm the encoding of your files using `file`? https://wit.ai/docs/http/#post__speech_link
Also can you confirm you're getting a 200 HTTP status back?

**Comment by mancu37** [comment]
Hi, I've been using this library since 2019 and I've never had an issue since a few days ago. I'm using wav file. I'll paste a screenshot below. this what I have:

![image](https://user-images.githubusercontent.com/5923503/127915919-91f149b2-71a1-4a89-bf32-01dc5042f6cb.png)

And this is the code that I'm using

![image](https://user-images.githubusercontent.com/5923503/127916399-980b8c57-43cd-431e-b3a5-2b5237063704.png)

Also, after this issue, I've tried HTTP API Request but it does not work. I get empty response.

![image](https://user-images.githubusercontent.com/5923503/127916044-243a2363-d546-4256-857d-2c3ab6755efd.png)

Let me know if you need more details.

Thanks,
Martin

**Comment by n0th1ng-else** [comment]
one of the sample files ` file output.wav 
output.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, mono 48000 Hz`

**Comment by n0th1ng-else** [comment]
same for @mancu37 I have been using wit.ai for a while and did not change anything. it just stopped working the other day. (the response is the same)

**Comment by siyanew** [comment]
I got responses just like @mancu37 , `200` with empty `_text`.

**Comment by patapizza** [comment]
Got it, thanks. I've recently updated the [HTTP doc](https://wit.ai/docs/http/#post__speech_link); a 16k sample rate would fix the issue, and also speed up the processing. It's something you might want to look into.
I'm working on deploying a fix.

**Comment by DegtiarDmitro** [comment]
Thank you! It work

**Comment by siyanew** [comment]
My problems have been solved by converting the wav file to 16k bitrate. I appreciate your help. 
@patapizza

**Comment by mancu37** [comment]
It worked for me too! with16k sample rate. Thanks @patapizza !

**Comment by mariolenis** [comment]
It's not just the sample rate, I tried with ogg at 8Khz and it works, it seems to be failing only on wav files.

**Comment by patapizza** [comment]
@mariolenis The issue is for some `wav` and `flac` encodings, where we need to convert back to 16khz. Other encodings like ogg aways get converted, so there's no issue, but the latency would be higher due to the conversion.

**Comment by FelipeBonadykov** [comment]
It also happens to me when I send opus files 
{
  "entities": {},
  "intents": [],
  "text": "",
  "traits": {}
}

**Comment by FelipeBonadykov** [comment]
Hi @patapizza ! I am wondering whether wit.ai supports WhatsApp audios in voice recognition, if currently empty string response is a bug and if I can somehow temporally resolve this issue in the later case.
Waiting forward to your reply

**Comment by patapizza** [comment]
Hi @FelipeBonadykov, here's the list of the currently supported encodings: [HTTP docs](https://wit.ai/docs/http/#post__speech_link). Opus isn't currently supported, `audio/ogg` is. If you share the output of the `file` format of an `.ogg` file, I'll be able to confirm the support.

**Comment by FelipeBonadykov** [comment]
Hi @patapizza ! This is the output of whatsapp ogg file (downloaded from whatsapp web)
{
  "entities": {},
  "intents": [],
  "text": "",
  "traits": {}
}

same is the output when I try with opus files that have type as "audio/ogg; codecs=opus" (is it considered as audio/ogg type?)

**Comment by Logerfo** [comment]
I'm experiencing empty text responses when sending ogg files, but correct responses if I convert the same files to mp3 or wav beforehand.
