### ISSUE TITLE
My app throws HTTP 500 now

### ISSUE THREAD

**Issue by n0th1ng-else** [wit-ai/wit#2154]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
It's a **bug**? something I can not solve by myself.

**What is the current behavior?**
the POST for `/speech` request throws this ('Content-Type: audio/wav')
```
status: 500,
statusText: 'Internal Server Error',
data: { code: 'wit', error: 'An error occurred in speech recognition.' }
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I run into it with any wav voice file. 

**What is the expected behavior?**
I found it today, few days ago it was working fine.
The source code can be found here https://github.com/n0th1ng-else/voice-to-text-bot/blob/master/src/recognition/wit.ai.ts

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
appId is 561129664549395, the language is set to be English

**Comment by BenAAndrew** [comment]
I have the same issue in the following notebook: https://colab.research.google.com/drive/1i5hJRZVc0S-tgt5XM8kSoTu2nHBPOPrF

**Comment by patapizza** [comment]
Hi, thanks for reporting. I'm looking into this.

**Comment by patapizza** [comment]
Working on deploying a fix.

In the meantime @n0th1ng-else, I noticed you're using 48k sample rate. I've recently updated the [HTTP doc](https://wit.ai/docs/http/#post__speech_link); a 16k sample rate would fix your issue currently, and also speed up the processing. It's something you might want to look into.

**Comment by n0th1ng-else** [comment]
Oh great to hear that! I will check @patapizza, appreciate the help 👍

**Comment by patapizza** [comment]
The 500s seem to be gone now. Let me know if you still experiencing issues.

**Comment by n0th1ng-else** [comment]
@patapizza finally managed to have some time for the fix and it works. thank you much 🚀
