### ISSUE TITLE
Training Stuck saying ongoing more than 2 days

### ISSUE THREAD

**Issue by tehkokhan** [wit-ai/wit#2155]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question

**What is the current behavior?**
My app has been stuck saying training ongoing for more than 2 days even though it said "Your app is currently training. Last time it took your app 1 min 44 s to train."
![image](https://user-images.githubusercontent.com/16042693/127983904-ecf0319e-7785-4e43-9a98-e70615d0826c.png)
New utterances did not trained even I click Train and validate
 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Since I started train the app with Chinese characters

**What is the expected behavior?**
That the training should be completed within few seconds yet it has been stuck saying training ongoing for few days

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
814846032499007

**Comment by patapizza** [comment]
Hi @tehkokhan, I've fixed your app.
