### ISSUE TITLE
Export Your Data - Permissions Error

### ISSUE THREAD

**Issue by HanSoon98** [wit-ai/wit#2156]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug

**What is the current behavior?**
Trying to export my app's .zip file results in a permissions error even though I own it.
![image](https://user-images.githubusercontent.com/51464223/128135576-ed6808e9-e4c3-47c9-b8fd-3d625f92ec91.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Creating a new app and trying to export a .zip from it still results in a permissions error.

**What is the expected behavior?**
I have done this previously, and successfully downloaded the .zip data. 

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
559347772089747 and 2718394494890162

**Comment by lycai-fb** [comment]
Thanks for the report @HanSoon98. We're looking into it.

**Comment by patapizza** [comment]
This should be fixed by the end of the day.

**Comment by patapizza** [comment]
This is now resolved.
