### ISSUE TITLE
Showing training scheduled in wit app on calling via api

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2157]
Hi,

We are trying to train some examples using the wit app 'https://api.wit.ai/utterances?v=20200513'.
When we try the same, now it is showing 'Training scheduled' in wit app and is taking too much time for training. It was working earlier. It is the same for all apps in the account.
Can anyone please assist?

Thanks

**Comment by lycai-fb** [comment]
Hi @anjaly

Please take a look at the [issue template](https://github.com/wit-ai/wit/blob/master/ISSUE_TEMPLATE.md) as we will not be able to assist otherwise.

Thanks.

**Comment by lycai-fb** [comment]
Feel free to reopen with more info.
