### ISSUE TITLE
Speech API returns 503

### ISSUE THREAD

**Issue by SisikHBS** [wit-ai/wit#2158]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

I want to report a bug.

**What is the current behavior?**

Most speech API requests return 503 service is not available error. I have Turkish and Portugues applications both of them returns same error. It returns 200 success message on approximately only 10 percent of requests.

      <h1 id="sorry">Sorry, something went wrong.</h1>
      <p id="promise">
        We're working on it and we'll get it fixed as soon as we can.
      </p>

**What is the expected behavior?**

It should return 200 success return message and text relevant to speech data.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
192304942914836

**Comment by patapizza** [comment]
Thanks for reporting, I'm looking into it.

**Comment by SisikHBS** [comment]
> Thanks for reporting, I'm looking into it.
Thank you so much for fast response. Really appreciate a quick fix.

**Comment by patapizza** [comment]
Fix upcoming.

**Comment by patapizza** [comment]
It looks like things are getting better. Can you guys confirm?

**Comment by SisikHBS** [comment]
> It looks like things are getting better. Can you guys confirm?
It works now. Thank you so much for lightning-fast debug!!
