### ISSUE TITLE
 java.io.IOException: Server returned HTTP response code: 503 for URL: https://api.wit.ai/speech?v=20210805

### ISSUE THREAD

**Issue by FelipeBonadykov** [wit-ai/wit#2159]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
 java.io.IOException: Server returned HTTP response code: 503 for URL: https://api.wit.ai/speech?v=20210805 when trying to post a file
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
recognized text
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
With all ap ids e.g. 419398523080427

**Comment by patapizza** [comment]
Thanks for reporting; closing in favor of https://github.com/wit-ai/wit/issues/2158.
