### ISSUE TITLE
Whatsapp voice messages text not recognized

### ISSUE THREAD

**Issue by FelipeBonadykov** [wit-ai/wit#2160]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
feature/bug
**What is the current behavior?**
when posting a request with ogg file and selecting audio/ogg chanel, there is no text recognition
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
recognized text
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
With all ap ids e.g. 419398523080427

**Comment by patapizza** [comment]
Hi @FelipeBonadykov, what HTTP status are you getting back?

**Comment by FelipeBonadykov** [comment]
503

**Comment by patapizza** [comment]
Closing in favor of https://github.com/wit-ai/wit/issues/2158
