### ISSUE TITLE
Error 502 when sending post request with Whatsapp opus file

### ISSUE THREAD

**Issue by FelipeBonadykov** [wit-ai/wit#2161]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug/feature/question
**What is the current behavior?**
Server returned HTTP response code: 502 for URL: https://api.wit.ai/speech?v=20210805 when making a post request with WhatsApp .opus or .ogg file in "audio/ogg" chanell
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Try to make a post request to /speech with WhatsApp .opus or .ogg file in "audio/ogg" 
**What is the expected behavior?**
Text recognized
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
419398523080427

**Comment by patapizza** [comment]
Hi @FelipeBonadykov, are you still experiencing the issue? We had some down time this morning, but we should be back to normal.

**Comment by FelipeBonadykov** [comment]
Hi @patapizza Right now when I make post requests with .opus whatsapp audio file specifying type as "audio/ogg", I receive "text": ""

**Comment by patapizza** [comment]
Got it, so not 5xx anymore. Closing in favor of https://github.com/wit-ai/wit/issues/2153.
