### ISSUE TITLE
Trouble posting trait to wit

### ISSUE THREAD

**Issue by bferster** [wit-ai/wit#2163]
I'm trying to add a new trait to my wit.ai project, but running the following code yields the error:

_{error: "Bad auth, check token/params", code: "bad-request"}_

	const url="https://api.wit.ai/traits?v=20210806&name=phase2&value=1"
	let body={  name:"phase", value:1 }
  
	fetch(url,{ method:"POST",
				headers: { Authorization:'Bearer '+CLIENT_TOKEN, 'Content-Type':'application/json'}, 
				body: JSON.stringify(body);
				})	
		.then(res => res.json())
		.then(res => console.log(res))

**Comment by lycai-fb** [comment]
Hey @bferster,
Please check out the [issue template](https://github.com/wit-ai/wit/blob/master/ISSUE_TEMPLATE.md).

Did you try running that code as is? You need to substitute "+CLIENT_TOKEN" with your app's auth token.
