### ISSUE TITLE
User authentication flow

### ISSUE THREAD

**Issue by spyshow** [wit-ai/wit#2165]
*question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

Hi i am new here and i couldn't find anything helps me in the docs
So i have a node js backend and i want the bot to ask the user for user name and password and then send them to the backend to authentic the user .. if its ok then the backwnd will return a jwt string which the bot should save it for the current user to send it later.
After that the user can ask the bot a question and the bot will make an api request to the backend woth the saved jwt (which will be sent in each backend request)

How can make this flow in wit

**Comment by lycai-fb** [comment]
Hey @spyshow
Auth in wit is done through app-specific access tokens ([docs](https://wit.ai/docs/http/20200513)) so most likely you'd build out whatever auth in your backend for your user and forward the requests to wit with your app token.
Hope that helps :)
