### ISSUE TITLE
Training won't complete & can't view utterances

### ISSUE THREAD

**Issue by diabolical-ninja** [wit-ai/wit#2166]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
Two buggy behaviours are being experienced (if these would be better as separate issues, let me know & I'll separate them out)

1. In the UI it always says "Training Ongoing", even after hours or days. Despite the below image saying "last time it took 19s" I've not ever experienced it & for the past couple of weeks it's always been in the amber training state. Based on #404 it seems like the app requires restarting?
<img width="396" alt="image" src="https://user-images.githubusercontent.com/15998949/128592889-48e3bd12-2497-46d9-9b85-76e0fef79940.png">

2. Cannot view utterances. Selecting the utterances page returns the message "Error: Something went wrong. We've been notified"
<img width="364" alt="image" src="https://user-images.githubusercontent.com/15998949/128592929-063ccad0-20b9-469e-9d1b-bd41e6a9a7d3.png">

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
To reproduce the issues:
**Issue 1**: navigate to the "understandings" page within the wit.ai UI for the app
**Issue 2**: navigate to the "Utterances" page within the wit.ai UI for the app

**What is the expected behavior?**
**Issue 1**:  After a period of time training completes
**Issue 2**:  Able to view existing utterances

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1750909285010578

**Comment by lycai-fb** [comment]
Hey @diabolical-ninja,
I've retrained your app. Feel free to reopen if you still have any issues.

**Comment by diabolical-ninja** [comment]
Thanks very much @lycai-fb. The training status is now reflecting the true status.

Unfortunately the utterances page is still returning the same error. Are there any other options to resolve that?
