### ISSUE TITLE
Cannot Export App Data

### ISSUE THREAD

**Issue by olengs** [wit-ai/wit#2167]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
when i press export in settings, results in "Bad auth, check token/params".
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
press export in settings page
**What is the expected behavior?**
export app data as zip
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2923621804620384

**Comment by chessai** [comment]
Are you still experiencing this issue?

**Comment by olengs** [comment]
> Are you still experiencing this issue?
yes

**Comment by ChrisyShine** [comment]
From the error message, it looks like an auth problem. If you still encounter the problem, can you refresh the server and client token and try to export again?

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
