### ISSUE TITLE
App stuck on training for 3 weeks

### ISSUE THREAD

**Issue by Michael-m24** [wit-ai/wit#2168]
Do you want to request a feature, report a bug, or ask a question about wit?
bug

What is the current behavior?
The app is stuck on training for 3 three weeks since I noticed, we teached it 2k sentences via your api and wit.ai shows us that it teached only 1k sentences.
App ID: 1202097196881348

We tried to copy all the content to a new app and teach it again via import,
the app finishes the import and it shows us the following message:
![bug_App172](https://user-images.githubusercontent.com/28590939/128973402-d021390b-b125-41ba-b554-5b5357f595c0.jpg)
App ID: 921246648736172

We would appreciate your assistance.

**Comment by yuzh174** [comment]
We have retrained the model. This is fixed.

**Comment by yuzh174** [comment]
We will retrain the app 1202097196881348 for you. 

For app 921246648736172, this may be a temporary UI error. Do you notice anything not working?

**Comment by Michael-m24** [comment]
Thank you the assistance,
the app 1202097196881348 is still stuck on training.
and the app 921246648736172 still has the error and I tried to enter some sentences and it doesn't recognize them...

**Comment by doggeral** [comment]
Training issue has been fixed.
