### ISSUE TITLE
App Ownership Transfer Failing

### ISSUE THREAD

**Issue by HanSoon98** [wit-ai/wit#2169]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug

**What is the current behavior?**
Clicking an ownership transfer link does not successfully transfer ownership to the target user. 

More context:
An upperclassman of mine is attempting to transfer app ownership of Academic-Dialogue (App ID down below) to me, but the ownership transfer email link does not register the ownership transfer itself. It just brings me back to the app on wit.ai.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Currently, the known way to reproduce the bug is to clone the Academic-Dialogue app (App ID down below) via the .zip extract, adding a contributor, and setting ownership to that added contributor. When the contributor accepts the transfer via the link through email, the transfer still should not go through.

**What is the expected behavior?**
Once ownership is set to another contributor and the email is received, the contributor should now be listed as owner of the app with the appropriate owner privileges.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2718394494890162

**Comment by yuzh174** [comment]
We are investigating this issue

**Comment by yuzh174** [comment]
The app ownership transfer should work now. Could you try again and let us know?

**Comment by chessai** [comment]
Hi @HanSoon98, are you still experiencing this issue? Please let us know.

**Comment by HanSoon98** [comment]
Hi @chessai, sorry I haven't gotten back. I tried logging in today and I could not.

![image](https://user-images.githubusercontent.com/51464223/131592451-aafda7a1-84a8-438f-81ed-461d425522db.png)

Not sure what's going on, since I only use my FB account for wit. I spaced out a retry 2 hours later, still didn't work. I'll try again tomorrow. Sorry for the delay!

**Comment by HanSoon98** [comment]
@yuzh174, @chessai - The ownership transfer works now. Thanks!
