### ISSUE TITLE
Utterance Processing Not Functioning

### ISSUE THREAD

**Issue by HanSoon98** [wit-ai/wit#2170]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a Bug

**What is the current behavior?**
Typing an utterance via the Understanding tab to a cloned app (cloned via .zip export), does not produce the entity keyword matching behavior expected.

Here is what happens on the cloned app, even though the keyword is defined in the entities:
![image](https://user-images.githubusercontent.com/51464223/129106489-b9564847-1751-4034-ab65-9e55cdf09c92.png)
![image](https://user-images.githubusercontent.com/51464223/129106333-777b2d08-c8e8-4981-9d13-357a426a1071.png)

Adding new entities, removing and re-adding entities, manually training utterances under the Management->Utterances tab does not resolve the issue. 

Sending an utterance via Python app using the wit API and Server Access Token also results in a 500 response, with the sent utterance nowhere to be seen in the utterance history of the app (Management->Utterances or Understanding)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Clone Academic-Dialogue (via .zip export), and attempt to process a phrase or keyword either through a Python program or on the app itself via Understanding. Either way, the phrase or keyword will not be recognized even though it is strictly defined in entities.

**What is the expected behavior?**
Utterance should be processed, with keywords and phrases recognized and matched to entities.

Here is what is expected to happen (image from original app) vs what happened above:
![image](https://user-images.githubusercontent.com/51464223/129106591-5979e936-ef0a-4d96-8fbf-62d13e6fdbd8.png)

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2718394494890162 - Original App (Academic-Dialogue)
559347772089747 - Cloned App where issue persists (collegebuddy)

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
