### ISSUE TITLE
issue with exporting app from another account

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2171]
Hi,

We are trying to export one wit app from an account and importing in to a new account. When we try this, some entity synonyms are getting added as extra entities and the intents and entities are mapped differently. . It is the same for all apps in the account.
Can anyone please assist?

**[Old app](url)**
![image](https://user-images.githubusercontent.com/601711/129837745-bb1e0263-ecb8-4ce1-b8f4-77d0fd7a667a.png)

**imported app**
![image](https://user-images.githubusercontent.com/601711/129837838-5263296a-b98c-469a-8c90-c7f903e8aca1.png)

Thanks

**Comment by FengyangZhang** [comment]
Hi, happy to look into this, can you provide the id of the app you want to export?

**Comment by anjaly** [comment]
> Hi, happy to look into this, can you provide the id of the app you want to export?

Hi 

The app id that we have exported is 1530202523770626 and the new app which we have created with the exported data is 883953822523052

Thanks

**Comment by anjaly** [comment]
Hi,

Any update?

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
