### ISSUE TITLE
Training is scheduled at distant dates

### ISSUE THREAD

**Issue by VaggBout** [wit-ai/wit#2172]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Possible bug

**What is the current behavior?**
When adding new utterances on one of our applications training is scheduled at distant dates, in comparison with our other applications 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Add a new utterance from the UI and check the Training scheduled date on top-right.  
For further info we provide some screenshots when adding a new utterance. One is from the App with the issue and the other is from another that does not present this issue. Both apps have similar number of trained utterances and both screenshots where taken at the same day/time. 

App with the issue(929627037790564):
![image](https://user-images.githubusercontent.com/37812224/130224618-d941b0a7-2c88-4b97-9849-4b56bb5483c1.png)

App that does not present the issue(132640028378117 -> App ID of properly working app for reference):
![image](https://user-images.githubusercontent.com/37812224/130224648-5ca12d45-b40e-4945-93bb-96a5fba0c627.png)

Notice that the first one is scheduled for training after ~7 hours and the other one starts training almost instantly.

**What is the expected behavior?**
To add a new utterance and the training will be scheduled on a reasonable time-frame. 

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
929627037790564

**Comment by FengyangZhang** [comment]
Hi, the scheduled time is calculated based on previous training durations, if the recent training is quick, it should be scheduled sooner.
