### ISSUE TITLE
My app 710302613248630 is getting 500 errors, please help, thanks!

### ISSUE THREAD

**Issue by wangyi041228** [wit-ai/wit#2174]
Do you want to request a feature, report a bug, or ask a question about wit?
Bug

What is the current behavior?
App keeps getting 500 errors

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
Every time we send a request it mostly returns a 500 error - as with bug #2105

What is the expected behavior?
No 500s

If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.
710302613248630

**Comment by FengyangZhang** [comment]
Hi, can you share the curl request you made?

**Comment by chessai** [comment]
Closing due to no response.

Please comment with reproduction steps if you wish to pursue resolving this issue further, and I will re-open.
