### ISSUE TITLE
Training ongoing forever

### ISSUE THREAD

**Issue by mmalbergier** [wit-ai/wit#2175]
We have a project 794028094630581 that is training and never finishes.

Can you assist us?

**Comment by jbourquin** [comment]
I think I am in the same boat: 880441882887985
I've also noticed that my models are not behaving as they used to, WIT is being really aggressive picking out numbers from strings of text even though they are supposed to belong to a different entity all together.

**Comment by wangsnowyin11** [comment]
Hi mmalbergier, jbourquin, I have helped you retrain both of the apps. Now they should be ready.

**Comment by mmalbergier** [comment]
Hello. Thanks. 
But we need to understand why this happens and how to avoid this in the future. 
It's been more than 24 hours since the ticket was open and we need to avoid this "ongoing" training. 
Any suggestions will be appreciated
