### ISSUE TITLE
Getting 500 errors when doing requests

### ISSUE THREAD

**Issue by bobkosse** [wit-ai/wit#2178]
Every time I do the request:

`https://api.wit.ai/message?v=20210831&q='My first name is Bob'`

I get a 500 error with the response body:

```
{
    "error": "Something went wrong. We've been notified",
    "code": "unknown"
}
```

My models are trained and this has worked for the last months. I notice this error since last Saturday.

**Comment by chessai** [comment]
Did you read the issue template? 

What is your app id? We cannot help without that.

Thanks

**Comment by ramh** [comment]
Closing since we have not received any updates for a while.
