### ISSUE TITLE
App Not Picking Up on New Training

### ISSUE THREAD

**Issue by ZaraElena** [wit-ai/wit#2179]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
- Report a Bug

**What is the current behavior?**
- We've trained about 20-30 phrases to an intent and not seen an increase of confidence (i.e. still sitting at 38%). We've seen this happen before where our app isn't taking our training, even though sufficient amounts have been provided. Can some assistance be provided on how to get our app to reflect the training? 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- X phrase should be getting picked up by the intent, but instead, the confidence is staying the same, so the reproduction steps are minimal as it's a training issue.

**What is the expected behavior?**
- X phrase should be getting picked up by the intent.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1504918609519459

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
