### ISSUE TITLE
Clone an app feature

### ISSUE THREAD

**Issue by mahieddine** [wit-ai/wit#218]
Hi,
Is it possible to clone an existing app ? 

Thanks

**Comment by l5t** [comment]
No yet for new app with Stories but we have that on our roadmap

**Comment by mahieddine** [comment]
Ah that's cool 👍  thank you

**Comment by zoro273** [comment]
Any updates on this ?

**Comment by patapizza** [comment]
Hi @zoro273 @mahieddine,

It is possible to clone an app by exporting your data and importing it back as a new app.
See documentation here: https://wit.ai/docs/recipes#copyexportversion-my-app
