### ISSUE TITLE
Wit App is stuck on ongoing

### ISSUE THREAD

**Issue by TaraNaser** [wit-ai/wit#2180]
Do you want to request a feature, report a bug, or ask a question about wit?
bug
What is the current behavior?
Wit app is stuck at Ongoing
If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

What is the expected behavior?
Wit app not to be stuck at Ongoing
If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.
App IDs: 
3983728971698916
860179131501435

**Comment by pokryva** [comment]
Hi,
It seems to be stuck on "Training ongoing" status in my App, too.
APP ID: 2666741980018303

**Comment by shorouqmajali** [comment]
Hi my app have the same issue App Id : 181708470710187

**Comment by doggeral** [comment]
Verified on wit.ai. all these apps were unblocked.
