### ISSUE TITLE
Phrases Error out when training 

### ISSUE THREAD

**Issue by jurneek** [wit-ai/wit#2182]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
When trying to validate phrases we're receiving an error message this has been going on for over a week 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
361308138221092

**Comment by chessai** [comment]
What do you mean by "I'd like to register"? Do you not have an App ID?

EDIT: Thanks for editing and adding your App ID!

**Comment by chessai** [comment]
What is the error message in question?

**Comment by jurneek** [comment]
There was an error validating the utterance.

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
