### ISSUE TITLE
Something went wrong. We've been notified ,Get utterances API

### ISSUE THREAD

**Issue by TaraNaser** [wit-ai/wit#2184]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
GET https://api.wit.ai/utterances?v=20210904&limit=10000 
![image](https://user-images.githubusercontent.com/71825913/132121643-0d10c833-8a9e-4fb7-9375-d0e2c0f3193f.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
GET https://api.wit.ai/utterances?v=20210904&limit=10000 

**What is the expected behavior?**
To return the trained utterances
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App id: 677077969722217

**Comment by chessai** [comment]
<s>I cannot find that app. Has it been deleted?</s>

EDIT: it was an issue on my end.

**Comment by pokryva** [comment]
Hi,
I get similar error while trying to access utterances via wit.ai UI: https://wit.ai/apps/2666741980018303/utterances ​

![image](https://user-images.githubusercontent.com/15121868/132812065-fb91c3f5-9ffa-4c12-ab37-28ed885cfa42.png)

App ID: 2666741980018303

**Comment by chessai** [comment]
> Hi,
> I get similar error while trying to access utterances via wit.ai UI: https://wit.ai/apps/2666741980018303/utterances ​
> 
> ![image](https://user-images.githubusercontent.com/15121868/132812065-fb91c3f5-9ffa-4c12-ab37-28ed885cfa42.png)
> 
> App ID: 2666741980018303

There should be a fix out for this by the end of the day.

**Comment by pokryva** [comment]
> There should be a fix out for this by the end of the day.

Hi @chessai, I'm not sure if you were replying to @TaraNaser issue - "something went wrong" in API, or my - "something went wrong" in UI, but just to let you know - UI still thorws this error message :(

**Comment by ChrisyShine** [comment]
@TaraNaser @pokryva Both 677077969722217 and 2666741980018303 should be able to show the Utterances page correctly.

**Comment by pokryva** [comment]
@ChrisyShine I can confirm utterances page in my app is ok now, thanks!
