### ISSUE TITLE
code: "wit"  error: "Something went wrong. We've been notified."

### ISSUE THREAD

**Issue by riztan** [wit-ai/wit#2185]
Hi, I am having a problem with wit.ai, previously I made the request and got a json with recognizable data, even the text corresponding to the audio correctly. However now it doesn't do it, I only get:
{
  "code": "wit",
  "error": "Something went wrong. We've been notified."
}

Example of the cURL statement used:
curl -X POST -k -H 'Authorization: Bearer $TOKEN' -H 'Content-Type: audio/ogg' -i 'https://api.wit.ai/speech?v=20200912' --data-binary '@test.ogg'

Application ID: 134545556868904832

I think it is worth noting that if I try to execute some instructions given in the documentation using cURL, I also get errors.

Thanks for any support you can provide.

Translated with www.DeepL.com/Translator (free version)

---------------------------------------------------------------------------------------

Hola, estoy teniendo un problema con wit.ai, anteriormente hacia la solicitud y obtenía un json con datos reconocibles, incluso el texto correspondiente al audio de forma correcta. Sin embargo ahora no lo hace, solo obtengo:
{
  "code": "wit",
  "error": "Something went wrong. We've been notified."
}

Ejemplo de la instrucción cURL utilizada:
curl -X POST -k -H 'Authorization: Bearer $TOKEN' -H 'Content-Type: audio/ogg' -i 'https://api.wit.ai/speech?v=20200912' --data-binary '@test.ogg'

Id de la aplicación: 1345455568904832

Creo conveniente señalar que si intento ejecutar algunas instrucciones dadas en la documentación usando cURL, también obtengo errores.

Gracias por el apoyo que puedan prestar.

**Comment by chessai** [comment]
I have edited your comment to not include the server access token. Please DO NOT share this, as it can be used to operate destructively on your app. Because it is visible in the edit history, you should refresh your access token in the settings of your app.

**Comment by riztan** [comment]
> I have edited your comment to not include the server access token. Please DO NOT share this, as it can be used to operate destructively on your app. Because it is visible in the edit history, you should refresh your access token in the settings of your app.

excuse me please, I forgot to remove the token

**Comment by chessai** [comment]
Do you get errors when executing any request other than speech, or just speech?

**Comment by riztan** [comment]
I was following up the tutorial with cURL and I still get errors. It seems to be something associated with cURL or maybe some blocking by geographic area (still to be ruled out). 

example:
curl 'https://api.wit.ai/message?v=20200513&q=hello' -H 'Authorization: Bearer $TOKEN'
reply:
{"error":"Something went wrong. We've been notified","code":"unknown"}

**Comment by Tolarion** [comment]
I have almost the same issue on "Utterances" page. Getting err: "Error: Something went wrong. We've been notified"

**Comment by lintaocui** [comment]
please open the issue if you can repro it. close it for now.
