### ISSUE TITLE
Error: Something went wrong. We've been notified, Code: Unknown

### ISSUE THREAD

**Issue by aliugur** [wit-ai/wit#2187]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug

**What is the current behavior?**
Utterances not loading for some apps. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Call https://api.wit.ai/utterances?limit=1000 with GET request and you will get the error.

**What is the expected behavior?**
It should list utterances of the App.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID: 2085604151492734

**Comment by chessai** [comment]
I have a fix out, this should be resolved by end of day.

**Comment by whopiyush** [comment]
still experiencing the same issue

**Comment by chessai** [comment]
> still experiencing the same issue

What is your app id?

**Comment by whopiyush** [comment]
> > still experiencing the same issue
> 
> What is your app id?

509741850113335

**Comment by whopiyush** [comment]
Also, I'm experiencing the issue while training my app - https://graph.wit.ai/509741850113335/samples endpoint. 
![image](https://user-images.githubusercontent.com/18086566/133199008-9cde7c53-8434-4dd1-bdb1-fbb731edec68.png)

**Comment by aliugur** [comment]
> I have a fix out, this should be resolved by end of day.

Hi. I am still experiencing the same issue.

![image](https://user-images.githubusercontent.com/3797833/133201168-98c8b5eb-206e-45e6-a86d-ff94a10c5738.png)

**Comment by whopiyush** [comment]
Hey @chessai , any updates?

**Comment by ChrisyShine** [comment]
Both of the app 2085604151492734 and 509741850113335 should be able to show the utterances page successfully. Can you try again?

**Comment by whopiyush** [comment]
Hey @ChrisyShine , I'm having the issue while I'm trying to train my app (App ID - 509741850113335).
![image](https://user-images.githubusercontent.com/18086566/133872338-2d10ea87-8a7b-4950-a624-fb833728ca24.png)

I first thought about creating another issue, but there are already a ton of issues out there for unknown error. Let me know if I should create another issue for it.

**Comment by Tolarion** [comment]
Hello! Getting "Error: Something went wrong. We've been notified" on Utterances page.
AppID: 252324006265683
Please, help!

**Comment by whopiyush** [comment]
any updates?

**Comment by ChrisyShine** [comment]
@Tolarion The utterances page for 252324006265683 is fine now.

**Comment by ChrisyShine** [comment]
@officialpiyush The utterance validation error is another problem. Can you create a new issue to track that? And if all the utterances page problems are resolved, I will close this issue.

**Comment by ChrisyShine** [comment]
And to solve the utterance validation problem, a question for @officialpiyush : Have you ever modified the app's language settings?

**Comment by whopiyush** [comment]
> And to solve the utterance validation problem, a question for @officialpiyush : Have you ever modified the app's language settings? 

@ChrisyShine Yes I did modify my app's language a few days ago, but I had changed it back to English again.

**Comment by whopiyush** [comment]
> @officialpiyush The utterance validation error is another problem. Can you create a new issue to track that? And if all the utterances page problems are resolved, I will close this issue.

Oh, sure

**Comment by aliugur** [comment]
> 2085604151492734

Hi. Yes I can open Utterances page but when I try this endpoint (https://api.wit.ai/utterances?limit=1000), I can't still get the result:

{
    "error": "Something went wrong. We've been notified",
    "code": "unknown"
}

**Comment by Tolarion** [comment]
> @Tolarion The utterances page for 252324006265683 is fine now.

Thanks a lot. Really appreciate your attention

**Comment by ChrisyShine** [comment]
@aliugur The problem comes from the utterance "MGM nedir?". Can you go to Utterances page and search for "MGM nedir?"? There are 2 utterances with different annotations. Can you decide which one is correct and annotate the other one with the same intent?

**Comment by aliugur** [comment]
> @aliugur The problem comes from the utterance "MGM nedir?". Can you go to Utterances page and search for "MGM nedir?"? There are 2 utterances with different annotations. Can you decide which one is correct and annotate the other one with the same intent?

Thank you very much; I selected with correct intent and the problem solved. But why is it giving this kind of error instead of not showing wrong utterances? It is kind of confusing but the issue is fixed nonetheless.

**Comment by mnoory** [comment]
i am facing something else, the app doesn't understand utterance although its already trained before
App ID 1920151674738030
