### ISSUE TITLE
Question - Control game via Voice - Definitely select one response.

### ISSUE THREAD

**Issue by max-critcrew** [wit-ai/wit#2188]
I've started to play around with Wit.ai with the extract entities/keywords recipe and it is working quite okay for what I'm trying to do, but not perfect.

I'm trying to make one of our games controllable with voice, that means the user can say "Go left", "Go right", "Go Center" and then the main character moves this way. There's always only one possible way to go and for every voice command sent to Wit.ai we want to figure out the most likely response that the user meant to say. 

The problem of the current approach is that for unclear audio input, Wit.Ai returns no response - but even for unclear audio inputs we would like to know a confidence level for each of the 3 possible responses.

Can this be achieved and if yes - how?

Thanks already for your time.

**Comment by lintaocui** [comment]
For unclear voice, we are not able to recognize the text, based on which the prediction is done.
