### ISSUE TITLE
ability to train wit programatically via api

### ISSUE THREAD

**Issue by fczuardi** [wit-ai/wit#219]
It would be cool to be able to skip the web UI and setup/validade entities on expressions via HTTP endpoints. This would make it easier to migrate apps from other similar services like LUIS that offers an "export" option that gives you structured data about your already validated statements.

And it would be a temporary workaround for the lack of fork/clone/export in the current version of wit. If I train the app only programatically and log everything that I did, then "recreate" an app following the same steps would be possible.

**Comment by fczuardi** [comment]
some related discussion about this is ongoing on https://github.com/fczuardi/calamarcopolo-training/issues/1 (the comments are related to this shell script https://github.com/fczuardi/calamarcopolo-training/blob/master/tasks/import-intents.sh that uses the undocumented browser api endpoint "sync")

**Comment by l5t** [comment]
We are transitioning to a new model with Bot Engine Beta hence some gap in our documentation/API.

We released a new version of the API and docs. You can now train a keyword or trait entity via https://wit.ai/docs/http/20160526#post--entities-link
You cannot use our HTTP API to train a "free-text" entity currently (you will need to define where the entity is inside the sentence). For now, you can rely on hacking the /sync like @fczuardi kindly exposes above. This is in our roadmap though and we expect to support this directly from the API

**Comment by lmessinger** [comment]
hi,

I'm trying to use https://api.wit.ai/intents/ with not much success

see https://wit.ai/docs/http/20160330#intents-index-link

I only get the default_intent

same for all other intents/ api

any ideas? suggestions?

thanks very much

**Comment by l5t** [comment]
You can now use /samples https://wit.ai/docs/http/20170307#post--samples-link
Example here: https://github.com/wit-ai/wit-api-only-tutorial#train-with-existing-data

**Comment by lmessinger** [comment]
thanks. it works, but it does take a 10-20 minutes until the engine can indeed recognize the same text. is that a normal behavior? any way to know when it was learnt?

thanks again

**Comment by stopachka** [comment]
Hey lmessinger -- POST /samples speed should increase as we move to more robust infra. Currently, your samples go into a queue, and the 10-20 minutes depends on how many are left in the queue
