### ISSUE TITLE
App not exporting

### ISSUE THREAD

**Issue by brennadoyle** [wit-ai/wit#2191]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
The app will not export and shows an error message that says "Something went wrong. We've been notified"
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Go to the app and click on the 'download .zip with your data' button
**What is the expected behavior?**
For the .zip to be exported
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1504918609519459

**Comment by brennadoyle** [comment]
Hi, I need to export this app and am still getting an error. Is there anything that can be done to get this exported?

**Comment by ChrisyShine** [comment]
@brennadoyle Can you try again? The export should be good now.

**Comment by brennadoyle** [comment]
Got it thank you!!
