### ISSUE TITLE
App staying in 'training ongoing' for surprisingly long time?

### ISSUE THREAD

**Issue by MiniPlaysCreator** [wit-ai/wit#2192]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question

**What is the current behavior?**
So, my app (ID 341206027716466) has been staying in 'training ongoing' mode for 2 hours already, which is quite unexpected since it usually takes up to a minute. At this point I only got 42 utterances, so I heavily doubt it should take that much time. The question is - is this intended and if not, what do I do?

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
341206027716466

**Comment by c0pper** [comment]
Same, my app (888858615075203) has been training for more than 24h a this point. Also, the status page on the witAI website never loads so maybe they're experiencing issues?

**Comment by ChrisyShine** [comment]
Both 341206027716466 and 888858615075203 training status is DONE now.
