### ISSUE TITLE
App stuck in training ongoing.

### ISSUE THREAD

**Issue by c0pper** [wit-ai/wit#2193]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question

**What is the current behavior?**
My app (ID 888858615075203) has been training for at least 2 days by now. Is there an issue on wit ai end or is it me? Can I do anything other than waiting?

**What is the expected behavior?**
Complete training

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
888858615075203

**Comment by ChrisyShine** [comment]
@c0pper Can you just try if the new utterances can be predicted correctly? It seems that, the training status signal is incorrect, but the training is already done.

**Comment by c0pper** [comment]
This seems to be the case. Not ideal but I can work with that for the time being.
