### ISSUE TITLE
Training ongoing indefinitely

### ISSUE THREAD

**Issue by zapteryx** [wit-ai/wit#2194]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug

**What is the current behavior?**
Training ongoing indefinitely (second time)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
n/a

**What is the expected behavior?**
Training complete or done

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
480451076271253

**Comment by ChrisyShine** [comment]
The app's training status shows "Done" now.

**Comment by zapteryx** [comment]
App is stuck in training ongoing again.
