### ISSUE TITLE
Wit App stuck in on going 

### ISSUE THREAD

**Issue by shorouqmajali** [wit-ai/wit#2195]
My app is stuck in ongoing for 3 hours 

the app with Id : 181708470710187 status is ongoing for 3 hour and unable to train

The expected is to complete training

the APP Id is : 181708470710187

**Comment by ChrisyShine** [comment]
The App's training status shows "Done".

**Comment by pokryva** [comment]
> The App's training status shows "Done".

Hi @ChrisyShine  you seem to be able to fix things around here - can you please heal my app - 2666741980018303 - with the "stuck in ongoing" problem? :)

**Comment by ChrisyShine** [comment]
@pokryva The app (2666741980018303) status should be DONE now. In fact, your app's training was already done before, but the signal is incorrect. You can verify the utterance prediction result and see if the prediction is good. The training status signal may not be accurate.
