### ISSUE TITLE
Error validating utterance:  Something went wrong

### ISSUE THREAD

**Issue by whopiyush** [wit-ai/wit#2196]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
It's a bug

**What is the current behavior?**
When I try to train my program, it gives me `There was an error validating the utterance` message. A sample text to try would be `mayu play beethoven`. It works perfectly when I remove `beethoven` and just keep `mayu play`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I'm not sure how to reproduce it. But I'll attach a screenshot of the training screen

**What is the expected behavior?**
The app should add the utterance into the training queue and train the app.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID: `509741850113335`

**Extra Information**
I was asked if I had changed my app's language in https://github.com/wit-ai/wit/issues/2187#issuecomment-923448604 , yes I did change the app's language to `HINDI`, but had changed it back to `English` later

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/18086566/134108388-c47602e9-fae4-4fb4-830d-fefaf0084016.png)

**Comment by ChrisyShine** [comment]
@officialpiyush The error should be fixed. Can you try again?

**Comment by whopiyush** [comment]
> @officialpiyush The error should be fixed. Can you try again?

Yes, It works now, thanks
