### ISSUE TITLE
Failing App

### ISSUE THREAD

**Issue by brennadoyle** [wit-ai/wit#2197]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

Question

**What is the current behavior?**

Currently, an app is bringing about thousands of errors and is constantly unstable. Is there something on the back end that's wrong with it?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

For the app to stay constant and not have outages every day. 

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

149898058347644
<img width="1236" alt="Screen Shot 2021-09-22 at 2 59 28 PM" src="https://user-images.githubusercontent.com/87776601/134427827-4abf1ea2-d544-4a1a-8dad-43ffa92bdc55.png">
6

**Comment by nishsinghal20** [comment]
Hi @brennadoyle! I tried the same request as yours but couldn't repro the issue. I did notice some timeouts for some queries in your app and we'll be addressing those issues soon on our end.

**Comment by brennadoyle** [comment]
@nishsinghal20 Will I be notified of when those timeouts will be addressed or is there a timeline on it?

**Comment by nishsinghal20** [comment]
We'll dedicate some time in early October to fix those issues. In the meantime, please feel free to create another issue if you continue to experience problems with your app. We'll do our best to help address them.

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
