### ISSUE TITLE
Wit App returns confidence level for a sentences that is not trained

### ISSUE THREAD

**Issue by TaraNaser** [wit-ai/wit#2199]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
Wit App returns confidence level for a sentences that is not trained
Using API https://api.wit.ai/message?n=8&v=20190904&q=عبدالرحيم عليان 
The api returns intent even though the sentence was not trained in any intent
![image](https://user-images.githubusercontent.com/71825913/134521838-6fd99bf4-2d41-401b-b8e5-129e3c8b5fc5.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
test using API https://api.wit.ai/message?n=8&v=20190904&q=عبدالرحيم عليان 
**What is the expected behavior?**
To not understand
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
315538893568231

**Comment by nishsinghal20** [comment]
Hello @TaraNaser! It's expected to get some results back even on untrained utterances, as long as the model can find some matches. The confidence value indicates how close the match is.

**Comment by TaraNaser** [comment]
Hi @nishsinghal20 the trained utterances under the first intent are not similar or close to the sentence, but the confidence level is still high.

**Comment by nishsinghal20** [comment]
@TaraNaser Do you consistently see the same response for that utterances, or was it just once? Could you try another similar utterances and see if you still get similar response and confidence scores back? You can also try training your model with a larger sample of utterances to improve it's prediction accuracy.

**Comment by TaraNaser** [comment]
Hi @nishsinghal20 I get the same response for that sentence all the time. This sentence is not trained under any intent. similar sentences give back the same intent but a lower confidence level.
For example: 
![image](https://user-images.githubusercontent.com/71825913/135045353-1cb24d22-04a0-4554-b397-d0226f646d78.png)

**Comment by nishsinghal20** [comment]
Hello @TaraNaser! Apologies for the late reply. One thing you can do is to annotate your utterances as "Out of scope"
![image](https://user-images.githubusercontent.com/27743368/138782454-637e9e2f-a7da-4116-9d2f-398f90219b81.png)

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
