### ISSUE TITLE
my app unable to train

### ISSUE THREAD

**Issue by shorouqmajali** [wit-ai/wit#2201]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit? my app status is onGoing for 3 weeks 

**What is the current behavior?** my app with Id : 262921882021843 is still ongoing for more than 3 weeks , and i am unable to train any intent

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.** : the training should be completed 

**What is the expected behavior?** the app to complete training  

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.** 262921882021843

**Comment by nishsinghal20** [comment]
Hello @shorouqmajali! I've manually re-triggered the training for your app. It should succeed this time, but if it still seems stuck, please feel free to comment on this issue and we'll take a look at it.

**Comment by shorouqmajali** [comment]
it seems like the issue is still exist , I am unable to train the app , and the status is still ongoing

**Comment by nishsinghal20** [comment]
@shorouqmajali thanks for the update. I'll investigate the issue.

**Comment by nishsinghal20** [comment]
I just checked and the training for this app has finished now. Please let me know if you see any further issues.
