### ISSUE TITLE
Wit.ai gives error: "Something went wrong. We've been notified"

### ISSUE THREAD

**Issue by ristomoilanen** [wit-ai/wit#2203]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
BUG

**What is the current behavior?**
Wit.ai gives result: "Something went wrong. We've been notified"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
curl -H "Authorization: Bearer [MY_TOKEN]" "https://api.wit.ai/message?v=20210929&q=Test"
->
{"error":"Something went wrong. We've been notified","code":"unknown"}
**What is the expected behavior?**
Intent

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
418025925910798

**Comment by CleanestMink126** [comment]
Sorry, I've been unable to reproduce any errors for this domain. I've tried both through manual tests and through the Wit UI and it seems to be working as expected. Is this still occurring?

**Comment by ristomoilanen** [comment]
Thank you for your response. Our app seem to be working now and this ticket is ok to be closed.
