### ISSUE TITLE
New tokens 

### ISSUE THREAD

**Issue by sophiexr** [wit-ai/wit#2205]
hi

Today, the Server & Client Access Tokens in the settings area of our app (2841817995840539) changed **without** clicking "Generate New Token". The only action performed today on that section, was to remove a user from the contributors list. 

Are there any logs to see what action might have triggered the tokens to change? 
Could removing a user (former owner of the app) automatically change the tokens?

Thanks

**Comment by CleanestMink126** [comment]
Hello!
Yes, transferring ownership of an app to a new user will transfer the existing tokens as well, so this is expected.

**Comment by sophiexr** [comment]
@CleanestMink126  

thanks for your reply. Ownership changed weeks ago. Today we just deleted a contributor (who was previously owner of the app) and the tokens changed. 
Do tokens change every time you delete a contributor??

Thanks

**Comment by CleanestMink126** [comment]
I see, this might be an artifact of deleting an old owner and them having their tokens revoked, which could revoke the transferred tokens.

It shouldn't happen when removing a normal contributor though, let us know if it does.
