### ISSUE TITLE
App is unable to train and facing issue as timeout for send message function. 

### ISSUE THREAD

**Issue by azmatrana** [wit-ai/wit#2207]
My app id is 320718746231538
From last 2 days, we are facing issue for training new question we are using ruby client of wit. All of our messages are going to out of scope now. And wit web app is also behaving weird. We send a message in understanding to train we click on add intent and click on "Train and validate" but nothing happen.

**Comment by CleanestMink126** [comment]
I can't seem to reproduce this issue, is this still going on?
