### ISSUE TITLE
**What is the expected behavior?**

### ISSUE THREAD

**Issue by July39** [wit-ai/wit#2208]
*My recorded file is correct on the web site, but i never get the text or the intent in return...  The returned text is only 2 or 3 characters and my .wav is prefect...
here is my app id:178092027786246 
I am a student in AI and I would really like to understand you tool..Maybe it's because I speak french...

Please help,

[TestJulyDulac.zip](https://github.com/wit-ai/wit/files/7274562/TestJulyDulac.zip)

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
