### ISSUE TITLE
Cannot differentiate 2 intent

### ISSUE THREAD

**Issue by vanhtuan0409** [wit-ai/wit#221]
2 create new entity intent with 2 possible value: greeting and request_introduce
I use Understanding tab to train ML with some sentence for each intent
But when I try to chat with the bot, I can only recognize the first intent which is greeting. The request_introduce usually categorized as greeting even when i input the same sentence as training
Should I create 2 entity for each intent or just keep 1 entity with 2 possible value

**Comment by l5t** [comment]
Sorry for the late reply. Just checked and it seems to work now
![image](https://cloud.githubusercontent.com/assets/6992759/15338503/09e22a56-1c35-11e6-8e85-5c29e022618b.png)
Reopen if you still have an issue. Best
