### ISSUE TITLE
wit.ai is down

### ISSUE THREAD

**Issue by brennadoyle** [wit-ai/wit#2210]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by brennadoyle** [comment]
The website is down and my apps are not responding

**Comment by SisikHBS** [comment]
Same here.  [ERROR] WitError: Wit responded with status: 503 (No server is available for the request)

**Comment by citiznru** [comment]
The same error.
https://api.wit.ai/speech?q=": context deadline exceeded

**Comment by brennadoyle** [comment]
@SisikHBS @citiznru looks like all of Facebook is down

**Comment by patapizza** [comment]
Yes, closing in favor of https://github.com/wit-ai/wit/issues/2209.
