### ISSUE TITLE
Wit doesn't return 'nointentmatch' anymore

### ISSUE THREAD

**Issue by haribalos** [wit-ai/wit#2213]
**AppId** : 2841817995840539
Hi everyone, 

My question is if something has changed on the algorithm on how Wit.Ai matches unknown trained answers.
Before 31/5/2021 we were getting results with the 'nointentmatch', but now we are always getting a match even if the question is gibberish.

Here are some examples below from our logs in order to make sense.

In this example, we had issued a Query of "01" and we got no matches, which was the correct behavior,
but after 06/2021 we started getting matches for the same type of Queries.

**Example 1**
**At 5/31/2021, 4:13:35.653 PM**
we're getting no match from our **Query** in Wit.Ai as follows below
{
"MachineName":".........X12",
"Type":"message",
"**Message**":"**nointentmatch**:",
"ConversationId":"............-a",
"ChannelId":"directline",
"ActivityId":"..........-a|0000028",
"From":".....575",
"CustomerType":"Individual",
"CustomerCode":"......5",
"To":"onprempirbot@Szs5wE8wLbE",
"LuisResult":"{"query": "01","intents": [],"entities": []}",
"**Query**":"01"
}

and at 7/13/2021, 4:40:27.989 PM
we're getting a match "LOAN_NEW" from the same **Query** in Wit.Ai as follows below which is irrelevant
{
"MachineName":".........X1",
"Type":"message",
"Message":"Mπορείτε να κάνετε άμεσα αίτηση για νέο δάνειο επιλέγοντας e-Loan.",
"ConversationId":"............-a",
"ChannelId":"directline",
"ActivityId":"8..........-a|0000003",
"From":".....668",
"CustomerType":"Individual",
"CustomerCode":"......4",
"To":"onprempirbot@Szs5wE8wLbE",
"**Query**":"01","Intent":"LOAN_NEW"
}

Example 2
At 5/31/2021, 4:07:55.201 PM
we're getting no match from our Query in Wit.Ai as follows below
{
"MachineName":".........X1",
"Type":"message",
"**Message**":"**nointentmatch**:",
"ConversationId":".........-a",
"ChannelId":"directline",
"ActivityId":".........-a|0000007",
"CustomerCode":".....065",
"CustomerType":"Individual",
"From":"......5",
"To":"onprempirbot@Szs5wE8wLbE",
"LuisResult":"{"query": "ειναι στανταρ σε μενα ομως γιατι?""intents": [],"entities": []}",
"**Query**":"ειναι στανταρ σε μενα ομως γιατι?"
}

and at 7/13/2021, 4:41:21.694 PM
we're getting a match "PERSONAL_INFO" from the same Query in Wit.Ai as follows below which is irrelevant
{
"MachineName":" ......... X1",
"ConversationId":" ........ a",
"Message":"Δεν μου επιτρέπεται να μιλάω για προσωπικά θέματα.",
"ChannelId":"directline",
"ActivityId":" ........ -a|0000005",
"Type":"message",
"CustomerType":"Individual",
"CustomerCode":"6347104",
"From":"EB1607668",
"To":"onprempirbot@Szs5wE8wLbE",
"**Query**":"ειναι στανταρ σε μενα ομως γιατι?","Intent":"PERSONAL_INFO"
}

**Comment by ruoyipu** [comment]
Hi @haribalos,

This result format does not look like what wit api returns. What endpoint are you querying and do you have any pastes of a direct response from wit.ai?

Thank you!

**Comment by haribalos** [comment]
hi @ruoyipu, below you will find the data you requested.

My issue if you see below is that I'm quering the app with a gibberish question
and the question is getting matched with a trait that has no training for that, it should be returning no matches.
Can you share your opinion on that behavior? it would be of great help since the app was responding correctly some time ago.
Thank you in advance. 

Query Endpoint: https://api.wit.ai/message?v=20170416&q=0khkjhkjhkjh

Direct response : 
{
    "_text": "0khkjhkjhkjh",
    "entities": {
        "intent_faq": [
            {
                "confidence": 0.71373072941779,
                "value": "INTNT-GEN_GREETING"
            }
        ]
    },
    "WARNING": "DEPRECATED",
    "msg_id": "25d50a49-8127-47fe-91f2-1c689e7bd1d2"
}

**Comment by ruoyipu** [comment]
Hi @haribalos,

Thank you for this data.

Some time ago, we separated intents/entities/traits and made intent a first class citizen as referenced in the "Consistent APIs" section in this article: https://medium.com/wit-ai/introducing-the-refreshed-wit-ai-3a7c603d325a

When you train utterances as "out of scope" it affects our intent classifier, but not the trait, which is why you're seeing the intent_faq trait being returned.

My suggestion is to look for an "intent" field in the response to detect no intent match.

**Comment by haribalos** [comment]
Hi @ruoyipu,

Thank you for your answer i will retrain our utterances with intent in a copy application to test the results.
