### ISSUE TITLE
App hanging in "Training ongoing" after Facebook's shutdown

### ISSUE THREAD

**Issue by sebastianarena** [wit-ai/wit#2214]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
BUG

**What is the current behavior?**
An app has been hanging with status "training ongoing" for hours, and we cannot unblock it

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
324520075312254

Thanks!

**Comment by ruoyipu** [comment]
Hi @sebastianarena,

I've gone ahead and manually requested a new retraining. It should now be unstuck.

Thanks!
