### ISSUE TITLE
Wit.ai App responds no intents anymore; training stucked

### ISSUE THREAD

**Issue by 4ivonne** [wit-ai/wit#2216]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
No intents returned within the API response.
Response is always status 200, but empty intent array.
Entities are still recognized.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
The Insights on the website shows zero calls.
Last voice utterance are available to play.
But when I train utterances in the list, they don't disappear.
I tried older days as version as well: same empty result.
ZIP export only as JSON structure of intents, but no utterances.

> curl \
>  -H 'Authorization: Bearer xxx' \
>  'https://api.wit.ai/message?v=20211010&q=guten%20tag'
> {"text":"guten tag","intents":[],"entities":{},"traits":{}}%  

> curl \
>  -H 'Authorization: Bearer xxx' \
>  'https://api.wit.ai/message?v=20211010&q=umschalten%20auf%20pro%20sieben'
> {"text":"umschalten auf pro sieben","intents":[],"entities":{"channel:channel":[{"id":"58643ff3-f19f-4b07-b3ad-c269b53ed6c5","name":"channel","role":"channel","start":15,"end":25,"body":"pro sieben","confidence":1,"entities":[],"value":"ProSieben","type":"value"}]},"traits":{}}%  

**What is the expected behavior?**
The example "guten tag" should return the intent "greeting".
The example "umschalten auf pro sieben" should return the intent "switchTV".

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID: 1118802294908311

**Comment by patapizza** [comment]
Hi @4ivonne,

I was able to get intents for some of your utterances.
I see that `guten Tag` is marked as Out of scope. The intent model learnt to ignore these inputs. If you now want to get intent predictions, you'll need to re-annotate the utterance with the proper intent (e.g. `greeting`). Make sure to review all out-of-scope utterances so they're all consistent with your mental model.

<img width="245" alt="Screen Shot 2021-10-12 at 10 29 33 AM" src="https://user-images.githubusercontent.com/1015208/137002556-df5ccd7b-b4a2-4140-b914-87a7f3beb842.png">


Hope this helps.
