### ISSUE TITLE
Please restart my bot training. Suffering from never ending bot training. 

### ISSUE THREAD

**Issue by SendseiPM** [wit-ai/wit#2217]
Dear WIT.ai team,

I am suffering from never ending bot training and have been for a week now.
It shows the orange/yellow status and says "Training ongoing".

Could you please restart it?
Please restart my bot training:

App ID:
630222481292872

Owner account: charlesfarley

**Comment by ruoyipu** [comment]
Hi @SendseiPM,

I've restarted the training for 630222481292872 and it should be complete now.

**Comment by SendseiPM** [comment]
Thank you. I can confirm the training does complete now and shows green again! Much appreciated.
