### ISSUE TITLE
Wit App is not working 

### ISSUE THREAD

**Issue by Sarah-Aabid** [wit-ai/wit#2219]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit? I can not see any app 

**What is the current behavior?  I can not see any app when I login , it keeps loading without any result.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. When I log in, I should be able to see my apps.

**What is the expected behavior? When I login, I should be able to see my apps.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help. 181708470710187

**Comment by ruoyipu** [comment]
Hi @Sarah-Aabid,

I cannot repro this issue, is this still happening? If so, can you attach a screenshot?

I have tried loading both https://wit.ai/apps and https://wit.ai/apps/181708470710187 and both load well.

**Comment by Sarah-Aabid** [comment]
Now it's working fine 
Thank you
