### ISSUE TITLE
Intents, what's the deal?

### ISSUE THREAD

**Issue by jejacks0n** [wit-ai/wit#222]
I guess I'm a legacy dev, but I'm starting to work with wit.ai again, and am struggling with resolving the old "intent" model and the new "story" model.. so, in the documentation I see a lot of stuff for the old `message` endpoint, which returns an intent and behaves more or less as I was expecting.. but I can't for the life of me figure out how to train an intent in the new application interface -- I played around with an "intent" entity, but that doesn't seem to work that great.

The problem I have with the `converse` endpoint is there seems to be no way to just respond without state.. e.g. user sends "hello", bot responds with "hi back!" without making at least two requests (the first one with the query, which responds with a merge), the second one without the query which responds with a msg. Is there still a stateless/session-less concept to use?

Sorry if this isn't an issue directly, or has already been asked/answered.

**Comment by avinash8526** [comment]
If you want to train your bot , go to the understanding tab under ur app console

**Comment by jejacks0n** [comment]
Not a useful addition, but I'm closing it anyway.
