### ISSUE TITLE
Utterances Screen has been crashed with unclear msg

### ISSUE THREAD

**Issue by Nisreena93** [wit-ai/wit#2220]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
I can't see the Utterances because the view is crashed

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1- go to my app https://wit.ai/apps/1920151674738030/utterances
2- from the left menu choose the Utterances tab.
3- the following will show
![Capture](https://user-images.githubusercontent.com/92379124/136965364-c4090fe0-74c5-4b87-a30c-3bec3d0004b1.PNG)

**What is the expected behavior?**
Gonna able to see the trained utterances.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1920151674738030

**Comment by Xueying-Wang** [comment]
Hi @Nisreena93 I've cleaned up inconsistent utterances and the page should be back now. Thanks for your patience!
