### ISSUE TITLE
Can`t get qualitative result for Russian language

### ISSUE THREAD

**Issue by assopri** [wit-ai/wit#2223]
#question 

**What is the current behavior?**
I send this file http://prismotrov.com/downloads/test.wav (mono wav file with Russian spoken text) and get very bad (incorrect) recognition result. For instance, audio with the same quality (is recognized by telegram Voicy bot also using wit.ai very good). 

Language in setting is set to russian:
![image](https://user-images.githubusercontent.com/73235464/137590036-22d8b63b-59bc-440d-9b00-65f83c82b96d.png)

I tried to send the similar audio files (but in English) to default app (with English selected as launguage) and recognition is completely OK.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
My app ID: 274626504392780

Thank you for your help in advance!

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
