### ISSUE TITLE
Speech recognition in languages other then En

### ISSUE THREAD

**Issue by Danielfromhere** [wit-ai/wit#2225]
""More like a *problem* about wit but could also be a question**

Hi everyone, 
Soo I have a problem with  speech recognition in Polish (pl_PL).
I know this language is in beta but it cannot recognize even a single word.
I don't know if polish speech recognition has yet not been developed or it is a bug.
I am sending my audio files via  API "POST" method to api.wit.ai/speech.

**What is the current behavior?**

It outputs single words in polish that are not even related and they also repeat themselves.
For example it often outputs word "nie" which just means no.  
kinnda funny like when it does that. It sounds like machines revolt.

Here is my App ID: 933974354138108
Looking forward for any replay. maybe someone else had this problem too.

**Comment by Danielfromhere** [comment]
Started using SpeechRecognition() library. It works fine for me now

**Comment by andysagar** [comment]
Can you tell me how u changed output language from English to another in postman
