### ISSUE TITLE
Unable to train and validate utterances using the wit/search_query entity

### ISSUE THREAD

**Issue by lisafindo** [wit-ai/wit#2227]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
BUG: 
I can't train and validate any utterances with the entity wit/search_query anymore. Other utterances with any other entity and intent work as expected.

**What is the current behavior?**
When trying to train and validate, I get the following error 
"​There was an error validating the utterance. Something went wrong. We've been notified"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Enter a new utterance like "Ich suche einen Tisch"
2. Intent and Entity get automatically selected correctly
3. click on train and validate
4. Error: "​There was an error validating the utterance. Something went wrong. We've been notified"

**What is the expected behavior?**'
The app should train and validate - no error should occur (it worked before)

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
339340300985534

**Comment by ziadrida** [comment]
I am getting "There was an error validating the utterance." only when trying to train. But problem only started today.
I made a couple of changes to the Facebook side of the app but not in wit.ai

**Comment by ziadrida** [comment]
Found my problem. I forgot that I changed the language in settings in wit.ai to a language which was BETA (Arabic)
Changed back to "nEglish" and problem is gone.
