### ISSUE TITLE
POST /speech not working for me

### ISSUE THREAD

**Issue by Pexeus** [wit-ai/wit#2228]
I am trying to use the POST /speech endpoint of WIT AI, using the code pasted below:

```
import requests
import json

def read_audio(WAVE_FILENAME):
    # function to read audio(wav) file
    with open(WAVE_FILENAME, 'rb') as f:
        audio = f.read()
    return audio

API_ENDPOINT = 'https://api.wit.ai/speech'
ACCESS_TOKEN = 'REDACTED'

# get a sample of the audio that we recorded before. 
audio = read_audio("payload.mp3")

# defining headers for HTTP request
headers = {'authorization': 'Bearer ' + ACCESS_TOKEN,
           'Content-Type': 'audio/mpeg3 '}

#Send the request as post request and the audio as data
resp = requests.post(API_ENDPOINT, headers = headers,
                         data = audio)

#Get the text
data = json.loads(resp.content)
print(data)
```
However, I can send any mp3/wav file I want, all i get back is this:
{'entities': {}, 'intents': [], 'text': '', 'traits': {}}

I tried several recordings but any field is empty every time.

**Comment by chessai** [comment]
I have edited your comment to redact your access token. Please do not post your access token again in the future, as it can be used to operate destructively on your app. I highly suggest that you generate a new access token from your app's settings page.

**Comment by chessai** [comment]
What is your App ID?

**Comment by ramh** [comment]
No response, closing. Please re-open if needed.
