### ISSUE TITLE
POST/speech returns multiple JSON objects

### ISSUE THREAD

**Issue by Adracir** [wit-ai/wit#2229]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug

**What is the current behavior?**
When sending a POST/speech request containing an audio file in the body (tested with audio/wav and audio/mpeg3), I get back multiple JSON objects as such:

```
{
  "text": "Hallo,"
}
{
  "text": "Hallo, dies ist ein Te"
}
{
  "text": "Hallo, dies ist ein Test."
}
{
  "entities": {},
  "intents": [
    {
      "confidence": 1,
      "id": "182676829878400",
      "name": "just_read"
    }
  ],
  "text": "Hallo, dies ist ein Test.",
  "traits": {}
}
```
The number of objects given depends on the length of the given text.
To me, this seems to be a bug, as the response is not valid JSON and the problem occurs regardless from where I am calling the API (tested in Thunder Client and my Android app (using Retrofit2&Okhttp3)).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
See above. For more details, you can ask me.

**What is the expected behavior?**
I would expect the API to only return the last object, starting with { "entities"..... 

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
436269147378738

**Comment by ricvail** [comment]
This is explicitly mentioned in the docs, so I believe it's intentional. But yes, it's frustrating, I had to write a function ad-hoc to extract the actual json response.

**Comment by patapizza** [comment]
The response is returning standard HTTP/1.1 chunks: https://wit.ai/docs/http/20210928/#post__speech_link.
More details here in [our blog post](https://medium.com/wit-ai/improving-voice-experiences-52492b4849b4).
