### ISSUE TITLE
wit/quantity not found [bug]

### ISSUE THREAD

**Issue by AnthonyPaulO** [wit-ai/wit#223]
bake me a cake with 2 teaspoons of butter and 1 cup of milk

I am able to get the custom intent (bake), custom subject (cake), and the unit (teaspoon/cup) and product  (butter/milk) but am totally unable to get it to understand wit\quantity in the story. I click on 2, select wit\quantity, then click 1, select wit\quantity, then validate and it seems to save that correctly, but when i test it the quantity never seems to be parsed. I must be doing something wrong so I'd appreciate someone pointing me in the right direction.

**Comment by AnthonyPaulO** [comment]
Okay I just started it all from scratch; everything works except for wit\quantity. I've already added a "unit" and "product" keyword entity as per the wit\quantity tooltip and even though I've validated several examples it keeps missing quantity whenever I type in the same examples into "Try out an expression"; everything else gets parsed except for quantity. I'm starting to believe this may be a bug.

**Comment by AnthonyPaulO** [comment]
Would someone please confirm whether this is a bug or am I incorrectly implementing it?

**Comment by l5t** [comment]
Sorry for the late reply. It works already a little bit. You don't want to validate any expressions with unit or product. But add directly the values (and synonyms) from the entities page. So to make it work, I would go in both the product and unit entity page and remove all the validated expressions

![image](https://cloud.githubusercontent.com/assets/6992759/16662604/0ad7227a-442d-11e6-93fc-0aa2d1e5ca8a.png)

**Comment by awnali** [comment]
I need to parse responses like following 1 meat, 3 bottles, fifty cables, 2 hundred lights etc. can you please guide how i can do this in wit using quantity?

**Comment by sriraman** [comment]
Any updates?

**Comment by tapan420** [comment]
Hey @l5t trying to train with "I want 22 gm black pepper, 30 gm Table salt, 40 gm Turmeric " with product, item_list and wit/quantity. like this 
![screenshot from 2017-06-05 18-31-48](https://cloud.githubusercontent.com/assets/19327489/26784866/6672c4a8-4a1d-11e7-8fd6-241779f12432.png)

But after training it for more than 5 times, again with the same statement, "I want 22 gm black pepper, 30 gm Table salt, 40 gm Turmeric ". It didn't show any wit/quantity. 
![screenshot from 2017-06-05 18-36-01](https://cloud.githubusercontent.com/assets/19327489/26784975/ddb5e82e-4a1d-11e7-8a28-de9ada565b3e.png)
Is this error with wit/quantity or some training issues?
please help me with that

**Comment by l5t** [comment]
wit/quantity doesn't work super well now. If you have time to improve it, you can look at the new duckling here: https://github.com/facebookincubator/duckling/blob/e85d2f507cf56008de11f3e0c174ce41f2561f25/Duckling/Quantity/EN/Rules.hs
If you need to move fast, I suggest using composite entities: https://wit.ai/blog/2017/03/28/reintroducing-composite-entities

**Comment by serraventura** [comment]
Is it still not working well ?

**Comment by tapan420** [comment]
Migrated to Amazon lex

**Comment by l5t** [comment]
Yes it should work now. Please reopen if you have any issue
![image](https://user-images.githubusercontent.com/6992759/37267241-2b68339e-257c-11e8-93c8-6d312ec6b163.png)
