### ISSUE TITLE
Unable to export data

### ISSUE THREAD

**Issue by rvi2021** [wit-ai/wit#2231]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
I am unable to export my app. Button text changes to "exporting" but then reverts back after a few seconds. No error message is displayed and the file is not downloaded.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Go to settings and click on the 'download .zip with your data' button

**What is the expected behavior?**
The .zip file should be geenerated and downloaded.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
4192215510894037

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
