### ISSUE TITLE
app is stuck in training 

### ISSUE THREAD

**Issue by sophiexr** [wit-ai/wit#2232]
hi, 

Our application 2841817995840539 is stuck on training mode for over a week now. Could you help?

thanks

**Comment by idanadut** [comment]
Also this one is stuck. Can you help?

Id: 337695227605625

**Comment by lycai-fb** [comment]
I've reset training for both, thanks.

**Comment by idanadut** [comment]
@lycai-fb 
Id: 337695227605625 still in "Training ongoing"
Makes sense? can you check?
