### ISSUE TITLE
Wit responded with status: 500

### ISSUE THREAD

**Issue by crick328** [wit-ai/wit#2235]
Do you want to request a feature, report a bug, or ask a question about wit?
Report a bug

What is the current behavior?
Error 500, Wit doesn't respond to API calls, training nor can analyze phrases from web app
Error log:
wit.wit.WitError: Wit responded with status: 500 (Internal Server Error)

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
You could try to make an API call or analyze a sentence

What is the expected behavior?
return a JSON response

If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.
581864409463679

For me, Wit is in this state since the fist day of October at least...

**Comment by lycai-fb** [comment]
Hi @crick328 can you give a redacted example of how you're calling the service?

**Comment by crick328** [comment]
Hello @lycai-fb 
I'm using a Python script to receive responses from Wit, specifically a module called "wit". These are the lines of code that do it:

from wit import Wit                       # import the module
wit = Wit(access_token)                 # getting access to wit
output = wit.message(input)         # send the sentence to analyse (input) and return json

The last line of code triggers the error. In addition, Wit doesn't even respond to my input from the web page. It is trained and cannot even recognise the native wit/datetime entity. 
![Screenshot (687)](https://user-images.githubusercontent.com/84636865/139941755-1cde424c-c691-4b47-be88-7edb9a455da7.png)
Lastly, there is no point in training the network. It says that the training is successfully completed, but it cannot detect any entity or intent from the same or other sentences.

**Comment by crick328** [comment]
Update:
I created another app by importing the data from the previous one as a zip file and the problem remains unchanged

**Comment by crick328** [comment]
excuse me @lycai-fb, are these informations enough?

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
