### ISSUE TITLE
Not able to Login!!

### ISSUE THREAD

**Issue by DXB-MEA** [wit-ai/wit#2236]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a BUG

**What is the current behavior?**
The login not working

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I'm not able to login to Wit.ai, API for login failing with the below error
email: "omar@thinglogix.com"
login: "mhdmaktabi"
![image](https://user-images.githubusercontent.com/66663320/139530840-1d159992-f3d6-46ce-83be-a0959680af46.png)

**What is the expected behavior?**
Able to login
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by lycai-fb** [comment]
We're tracking this in #2234 , thanks.
