### ISSUE TITLE
Wit app stuck on ongoing

### ISSUE THREAD

**Issue by TaraNaser** [wit-ai/wit#2239]
Do you want to request a feature, report a bug, or ask a question about wit?
bug
What is the current behavior?
Wit app is stuck at Ongoing
If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

What is the expected behavior?
Wit app not to be stuck at Ongoing
If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.
App ID: 572119990802632

**Comment by lycai-fb** [comment]
Should be reset now, please try again.
