### ISSUE TITLE
Differentiate stories

### ISSUE THREAD

**Issue by rithvikvibhu** [wit-ai/wit#224]
I have 2 stories as you see below:

![witai1](https://cloud.githubusercontent.com/assets/5113343/15215318/85fd123c-186f-11e6-8377-3fe5e240380d.PNG)
![witai2](https://cloud.githubusercontent.com/assets/5113343/15215319/8601d0ec-186f-11e6-8180-78baf7747e66.PNG)

Querying `Get me the 5th episode of the 2nd season of Arrow` runs the 'latest episode' story. What can I do to be able to run different stories?

**Comment by rithvikvibhu** [comment]
I'm guessing it's because of the beginning of the query `Get me the...`. Any ideas?

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
