### ISSUE TITLE
Training not taking affect

### ISSUE THREAD

**Issue by brennadoyle** [wit-ai/wit#2240]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
As I train the confidence levels of phrases matching with intents does not change, even after the training says it is complete.

**What is the expected behavior?**
After training has completed I should see changes in the app confidence levels when typing the same phrases into the Understanding area.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1504918609519459

**Comment by yuzh174** [comment]
Hi @brennadoyle 
The confidence doesn't necessarily need to be 100%. Sometimes it may not go higher. As long as the request is resolved successfully, you don't need to worry about the confidence level.

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
