### ISSUE TITLE
Api for refreshing app token

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2241]
Hi,

Is there any wit api for refreshing the wit app tokens.

Thanks

**Comment by yuzh174** [comment]
Hi we have API to refresh/get client tokens but not server tokens. 

You can refer to this API doc https://wit.ai/docs/http/20210928/#post__apps_link in section "Create or Fetch Client Tokens"

**Comment by yuzh174** [comment]
If this is for the invalid token issue mentioned here https://github.com/wit-ai/wit/issues/2234. This issue should be resolved. You can use your existing token to access the service if you haven't refreshed by yourself.

**Comment by anjaly** [comment]
> If this is for the invalid token issue mentioned here #2234. This issue should be resolved. You can use your existing token to access the service if you haven't refreshed by yourself.

Need one clarification 
1. Regarding the $TOKEN to be used with the APIs, are the $TOKEN supposed to be client token or server token.
2. Can we generate new token if the existing token is invalid
3. Will this api refresh server token also

**Comment by yuzh174** [comment]
1. This API is to replace the client token. The $TOKEN used in the request needs to be the server token. 
2. Yes. It doesn't matter the client is valid or not. But the server token has to be valid
3. We don't have an API to refresh server token. You have to use the UI to do that.
