### ISSUE TITLE
Imported keyword entities are inconsistent

### ISSUE THREAD

**Issue by gnovis** [wit-ai/wit#2243]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
After importing an application that contains keywords entities, entities that were annotated when training utterances are added as new separate entities. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Create the App with keyword entities
2. Annotate and train utterances (containing entities)
3. Export the App
4. Import the App
5. Compare keywords entities from original App and imported App

**What is the expected behavior?**
The imported App should contain the same entities as the exported App.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
I created two Apps which demonstrates the bug:

- Original (exported) App ID: 1928500717323841
- Imported App ID: 3053902241564598

The Apps contains only one entity, so you can see the differences between exported App entity and imported App entity.

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
