### ISSUE TITLE
Getting HTML instead of json as an output to speech recognition

### ISSUE THREAD

**Issue by backmeupplz** [wit-ai/wit#2244]
Hi there! Started to get `Unexpected token &lt; in JSON at position 0` when trying to parse the json response of the speech recognition API.

Going to look into the actual response sometime soon, but here's one of my affected apps in case you can find the issue sooner than I do: 1139646093110797

**Comment by backmeupplz** [comment]
Probably some type of an error is returned

**Comment by vsile** [comment]
The similar error: "unable to decode error message: invalid character '<' looking for beginning of value"

**Comment by backmeupplz** [comment]
Seems like the issue is resolved 🤔 no more errors like this, didn't have a chance to see the actual body
