### ISSUE TITLE
Our app fails with long-ish queries (less than 100 characters)

### ISSUE THREAD

**Issue by ricvail** [wit-ai/wit#2247]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
Whenever we query any endpoint with a long-ish utterance (for example "Esta colección de edificios fue inaugurada el nueve de junio de mil novecientos noventa y ocho"), the response is `{"error":"Something went wrong. We've been notified","code":"unknown"}`.
The error always happens after exactly 10 seconds, so I'm guessing it's a timeout problem.
I tried both the /message endpoint via curl command, and the /speech endpoint. With the /speech endpoint the response looks like this: 
```
{
  "text": "a"
}
{
  "text": "está"
}
{
  "text": "esta colección"
}
//[Omitted for brevity]
{
  "text": "esta colección de edificios fue inaugurada el nueve de junio de mil novecientos noventa y"
}
{
  "text": "esta colección de edificios fue inaugurada el nueve de junio de mil novecientos noventa y ocho"
}
{
  "code": "wit",
  "error": "Something went wrong. We've been notified."
}
```
So the speech is recognized correctly, but then the analysis of the utterance fails.

We also tried the "Add new utterance" field in the Understanding page with this same phrase, and we don't see an error but the intent dropdown does not auto-compile (remains on "choose or add intent"), and from the networking tab in chrome developer's tools it looks like the http call fails (but I'm not sure because there are a lot of calls).
It might be relevant to mention that the app was trained with this exact same phrase, so it shouldn't have any problem recognizing it.

We tried multiple phrases, and shorter one usually work without problems (both phrases from the training set and new phrases), while longer ones always fail (again this happens both with new phrases and phrases that were in our training set).

It might also be relevant to mention that our app was configured in a non-standard way. We have one single intent, upon which we defined around 230 entities. I haven't seen any warnings in the documentation about a limit on the number of entities on the same intent, but I'm suspecting that this might have to do with our time-out issue, since using the same phrases on a new, smaller, app does not result in the same error, and instead results in the expected response.

Also. most (if not all) our entities have "free text and keywords" as their look up strategy. Would it help to switch (where possible) to "keywords only", or is this completely unrelated to our issue?

What are our options to work around the problem?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Simply call our app with this request:
`curl -H 'Authorization: Bearer [OMITTED]' 'https://api.wit.ai/message?v=20211110&q=Esta%20colecci%C3%B3n%20de%20edificios%20fue%20inaugurada%20el%20nueve%20de%20junio%20de%20mil%20novecientos%20noventa%20y%20ocho'` (or any other phrase with more than 90 characters)

**What is the expected behavior?**
The app should return the normal response for the /message endpoint (possibly without taking more than 10 seconds)

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
949539342164783

**Comment by FengyangZhang** [comment]
Thanks for reporting the issue, we're looking into it.

**Comment by ricvail** [comment]
Thank you for looking into it @FengyangZhang. Do you have any news?

**Comment by ricvail** [comment]
Hello, sorry to bother you but it's been 2.5 months and we still experience this issue. Do you have any news?

**Comment by ricvail** [comment]
Looks like the issue has been fixed. Thank you :)
