### ISSUE TITLE
Speech Recognition gives empty response in polish language

### ISSUE THREAD

**Issue by steamyvino** [wit-ai/wit#2248]
Hello, 

I am have an issue where speech recognition in polish languages gives me empty response. No matter what I will say 
Response looks like this: 
{u'traits': {}, u'entities': {}, u'intents': [], u'text': u''}

When I switch on english it gives correct responses like this :

 {u'traits': {}, u'entities': {}, u'intents': [{u'confidence': 1, u'id': u'398807555229723', u'name': u'name_response'}], u'text': u"What's the time"}

**Comment by FengyangZhang** [comment]
Hi, please provide the app id so we can look into it, thanks!

**Comment by steamyvino** [comment]
4064219447012181

**Comment by FengyangZhang** [comment]
Hi, @steamyvino , when did you start to see this happen? I'm trying to figure out whether support Polish (in the doc it says supported, but we had some infra changes)

**Comment by steamyvino** [comment]
Actually I just started using it 4 days ago.  So that means polish is not supported anymore ?

**Comment by FengyangZhang** [comment]
Yes, it is not supported for now, we have some infra team working on the support but I don't have a clear timeline. Apologies for the inconvenience.
