### ISSUE TITLE
Error code unknown

### ISSUE THREAD

**Issue by JustAVibingDude** [wit-ai/wit#2249]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
Throwing Error: {"error":"Something went wrong. We've been notified","code":"unknown"}

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Just try to analyze any text or audio message. 
For example:
curl  -H 'Authorization: Bearer $BEARER'  'https://api.wit.ai/message?v=20211111&q=Schalte%20das%20Licht%20im%20Flur%20an'

**What is the expected behavior?**
Get a normal reponse with intents, entities, ... 

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
481682656184552

**Comment by INzoGravity** [comment]
ฉันไม่เข้าใจว่ามันเกิดอะไรขึ้น

ส่งจาก iPhone ของฉัน

**Comment by FengyangZhang** [comment]
Hi @JustAVibingDude , do you know when did the issue start to happen to your app?
