### ISSUE TITLE
messenger integration with two stories

### ISSUE THREAD

**Issue by vepak** [wit-ai/wit#225]
I'm new to wit.ai, trying to build messenger bot.

I'm having two stories, first is when user says hello, it greets with message with his name....

second is getting details of the cab with cab number... but when I try it's only executing only one story, its very confusing at this point how to debug... could you please help me. TY.

My app: trafficbuddybot

![screen shot 2016-05-15 at 12 56 03 pm](https://cloud.githubusercontent.com/assets/873685/15272623/7bc630d0-1a9c-11e6-8aa2-cd38c1cc778e.png)

**Comment by rithvikvibhu** [comment]
@vepak which story runs?

**Comment by vepak** [comment]
always the first... cab {vehicle_no}

**Comment by rithvikvibhu** [comment]
I have the same issue at #224
Since 3 days ago.

**Comment by rithvikvibhu** [comment]
#224

**Comment by vepak** [comment]
I played with the stories by going to understanding and trained with various keywords, now it's behaving bit differently...

when I say hi or hello the second story in the screenshot is running.

But when I say cab ap09tva1213 both 1st and 2nd story are running. so I'm getting two outputs :(

Any ideas??

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
