### ISSUE TITLE
Future plans for free users and commercial usage.

### ISSUE THREAD

**Issue by SisikHBS** [wit-ai/wit#2251]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question

**What is the current behavior?**
Future plans for free services 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Hello I have developed several tools with WIT AI apis and services are amazing, we are glad to have WIT! I would like to learn if wit has plans to decrease free service allowances in the future? If there is a plan to limit free usage, will wit ai notify existing developers in advance so that developers can find alternate solutions? 

Additionally Wit has changed API response formats few times such as response of speech to text response (now it has intermediary results and is in different json format). Due to this change some of my applications required updates. Is it possible if Wit notifies existing developers via mail for the upcoming changes before actually implementing them.

Thank you so much!

**Comment by FengyangZhang** [comment]
Hi, thanks for the questions. If there's changes in services that Wit.ai provides, developers will absolutely be notified before the change. For API format changes, we have API versioning to make sure the changes are backwards compatible, check out the docs: https://wit.ai/docs/http/20210928/#api_versioning_link
