### ISSUE TITLE
Trained utterances not showing anymore

### ISSUE THREAD

**Issue by HatoonH** [wit-ai/wit#2254]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
1-We cannot manage and view all Utterances we trained before anywhere.
**Mangment>Utterances**
![Screenshot (459)](https://user-images.githubusercontent.com/73424635/142453259-2d053709-460b-4ebb-b79f-8d14d4f2f457.png)

2-We cannot Download our data
**Settings>Download .zip with your data**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

The utterances are entered and training is complete.
![image](https://user-images.githubusercontent.com/73424635/142454447-dbd8513c-0deb-4c7b-8748-0891810e14e3.png)
1-Mangment>Utterances tab is not showing up any utterances! an error occurs "Error: Something went wrong. We've been notified"
![Screenshot (459)](https://user-images.githubusercontent.com/73424635/142453259-2d053709-460b-4ebb-b79f-8d14d4f2f457.png)

2-Settings>Download .zip with your data showing error
![WhatsApp Image 2021-11-19 at 3 08 08 PM](https://user-images.githubusercontent.com/73424635/142977532-9358de68-b98c-49c4-8460-7adc4d0aa025.jpeg)

**What is the expected behavior?**
1-All utterances show up in Mangment>Utterances tab
2-Data downloading complete successfully
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID: 277717187596622

**Comment by wangsnowyin11** [comment]
Hey sorry for the inconvenience! We are actively fixing the issue! Will let you know when it's fixed

**Comment by wangsnowyin11** [comment]
Hey the issue is resolved. Now your page is loaded successfully. Sorry for the inconvenience!
