### ISSUE TITLE
Speech API not working

### ISSUE THREAD

**Issue by backmeupplz** [wit-ai/wit#2256]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

A bug

**What is the current behavior?**

Speech recognition API returns an error "Sorry, something went wrong. We're working on it and we'll get it fixed as soon as we can."

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Try to use the speech recognition API

**What is the expected behavior?**

Speech API working

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

Can't see my apps, says "Your session is expired" when I try to login to backmeupplz@gmail.com.

Looks like someone likes to deploy to production on Fridays? 😅

**Comment by Danielfromhere** [comment]
Same thing, can't access to the fetch function. Console says that it has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

**Comment by ramh** [comment]
Hi, can one of you verify if this issue is still happening. If so, please comment with your App ID for us to investigate? thanks.

**Comment by backmeupplz** [comment]
Seems like it's all good @ramh

**Comment by ramh** [comment]
Thank you for checking.
