### ISSUE TITLE
Remove role from intent programmatically

### ISSUE THREAD

**Issue by AngelidisChris** [wit-ai/wit#2259]
Hi folks, 
I would like to remove entity role from intent programmatically, but, as far as I can tell there is no endpoint atm to do this. Am I making a mistake? Can we expect an update in the future? 
Thank you for your time.
![Capture](https://user-images.githubusercontent.com/45776886/143008962-4f74e3d9-0a84-4c74-b697-093e593d2e56.PNG)

**Comment by lintaocui** [comment]
here is the api to delete a role from entity: https://wit.ai/docs/http/20210928/#delete__entities__entity_role_link.
but we do not have the api to delete a role from intent.
