### ISSUE TITLE
application not responding

### ISSUE THREAD

**Issue by sophiexr** [wit-ai/wit#2260]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
We are getting empty responses and when we click on utterances we can't see any and get the following error message
Error: Something went wrong. We've been notified

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

through postman when we call the message end point with a trained question we are getting empty result as shown below
{
    "text": "πως ανοιγω λογαριασμο",
    "intents": [],
    "entities": {},
    "traits": {}
}

Also in all options in wit (understanding and traits) we can't find any of our 500 traits. Seems like the disappeared all. 

**What is the expected behavior?**

when we ask a trained question the traits property shouldn't be empty 
(our app is working like that for almost 3 years)

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.** 
app id 2841817995840539

thanks 
Sophie

**Comment by sophiexr** [comment]
kind reminder

it's very important for us to solve that issue asap 

thanks

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
