### ISSUE TITLE
app not responding in certain trained utterances

### ISSUE THREAD

**Issue by sophiexr** [wit-ai/wit#2261]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**!

bug 

**What is the current behavior?**

Following the issue we have with our app 2841817995840539,  on Tuesday, we created a backup application and uploaded about 86000 utterances. Our app is responding for the most part correctly, but it can't respond to small talk questions (e.g. INTNT_GEN_GREETING, 
INTNT_GEN_HOW_R_U ) although many utterances have been uploaded for them.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Our app is in Greek language, so in understanding in the add new utterance section, type Καλημερα (good morning  in greek). It won't return any intent or trait but as you can see in the image attached, there are over 200 utterances trained for this greeting 

**What is the expected behavior?**

It should respond to all trained utterances 

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
211582031122227

<img width="1249" alt="Screen Shot 2021-11-26 at 2 37 53 PM" src="https://user-images.githubusercontent.com/48153186/143582357-72255781-923c-4660-8f79-090dc7a782ff.png">

**Comment by bluegr** [comment]
For reference, the original issue was submitted in #2260

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
