### ISSUE TITLE
Access token does not match

### ISSUE THREAD

**Issue by AVimmerse** [wit-ai/wit#2262]
**Report a bug**

**What is the current behavior?**
I am attempting to use the API to upload utterances, following the guidance via the page: https://github.com/wit-ai/wit-api-only-tutorial?fbclid=IwAR1LlNILTnYdz7jEAtlMTB3Kyky_xs6H3GAr1r2Dp_b7iAZiAXLmwETxq7M 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
When trying to communicate with my app, I am getting an error 'Access token does not match'.  I have tried to use a new app, changed the token, deleted other apps etc but I am still getting the issue.  

**What is the expected behavior?**
I want to be able to upload hundreds of utterances on a spreadsheet.  

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
448906548449560
![Capture](https://user-images.githubusercontent.com/32142200/143599342-b0c4639c-17ba-4598-8a44-6f93d25a7ce1.PNG)
1

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
