### ISSUE TITLE
Intents not loading

### ISSUE THREAD

**Issue by brennadoyle** [wit-ai/wit#2265]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
The intents don't load

**What is the expected behavior?**
Intents to load

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
150491860951945
<img width="779" alt="Screen Shot 2021-12-01 at 10 47 38 AM" src="https://user-images.githubusercontent.com/87776601/144287202-7d6aa307-b66e-4216-9951-3dc7bb419ee6.png">
9

**Comment by brennadoyle** [comment]
This is still not working.

**Comment by brennadoyle** [comment]
This is still not working and needs attention. The intents do not load in the Utterances tab or in the intents tab.

**Comment by brennadoyle** [comment]
This is still not working. The utterances don't load, the intents don't load, and if I try to train a query to out of scope it doesn't train. Please let me know how we can get this working.

**Comment by brennadoyle** [comment]
This is still an issue. Intents are not loading in the app so training cannot take place.

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new issue should the subject persist.
