### ISSUE TITLE
400 Bad request WIT.AI

### ISSUE THREAD

**Issue by darshanamadlani** [wit-ai/wit#2267]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
https://api.wit.ai/message?v=20211202
{
   "error": "Bad auth, check token/params",
   "code": "no-auth"
}

using above data and giving error.
**What is the current behavior?**
While calling API in Unity through C# code it's giving 400 bad requests.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Expected behavior: it should return the value and run the animation
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
APP ID: 287425183206431

I have tried creating a new ID and New app not allowing to add Utterances.

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
