### ISSUE TITLE
Trained utterances not showing 

### ISSUE THREAD

**Issue by kevinjon27** [wit-ai/wit#2269]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**
my app error, traits and utterances

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
<img width="1424" alt="Screen Shot 2021-12-03 at 21 06 34" src="https://user-images.githubusercontent.com/12078441/144615860-281a6c66-0812-40a9-b67a-5a2644ec18ec.png">
<img width="1425" alt="Screen Shot 2021-12-03 at 21 08 01" src="https://user-images.githubusercontent.com/12078441/144615895-c8be61ef-fdfe-4813-aaff-d40b1de6a934.png">

error when open the menu

**What is the expected behavior?**
utterances = Error: Something went wrong. We've been notified

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
- 1421496151549477

**Comment by kevinjon27** [comment]
Addition from me:

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/12078441/144821565-7ba95150-3722-4497-8fb8-60d7546fccd4.png)
- Before the error, our wit.ai can recognize the text correctly. But now it's a mess.

when we try to retrain the words, we get an error like this
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/12078441/144822072-722181af-b94c-413e-a689-34040f61474c.png)

**Comment by kevinjon27** [comment]
Help @wangsnowyin11 @lintaocui @FengyangZhang @yuzh174

**Comment by CannonFodderr** [comment]
We are having issues saving utterances as well.
Both with api calls & with the wit.ai dashboard, seems like utterances are just not saved.

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
