### ISSUE TITLE
empty inbox

### ISSUE THREAD

**Issue by mnannt** [wit-ai/wit#227]
My inbox shows 100+ received inputs

![inbox](https://cloud.githubusercontent.com/assets/675065/15317156/8cf97c42-1c20-11e6-93f8-cb59c6d54e4c.png)

but then I open the inbox no input would be shown

![emptyinbox](https://cloud.githubusercontent.com/assets/675065/15317184/b590d6a0-1c20-11e6-82f4-ae5cc654c5dd.png)

Last week it works fine.

**Comment by l5t** [comment]
Closing since this was probably fixed a while ago. Please reopen if you still have the issue.
