### ISSUE TITLE
app training for days 

### ISSUE THREAD

**Issue by sophiexr** [wit-ai/wit#2270]
Hi, 

Our app seems to be stuck in training mode for the past 4-5 days. Can you please check and restart?

app 298620675435521

thanks

**Comment by sophiexr** [comment]
@patapizza could you please help us,  

our app is stuck on training for many days 

thanks

**Comment by Nisreena93** [comment]
Hello Wit team,
My App also 341248294209239
Please make a restart for training or anything we are pending till the problem is solved.
