### ISSUE TITLE
Increase rate limit?

### ISSUE THREAD

**Issue by bfavero** [wit-ai/wit#2271]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Hi, is there a way to apply for a higher rate limit?

**Comment by ChrisyShine** [comment]
Can you share the Wit app ID? And what is the higher rate limit that you are looking for?

**Comment by bfavero** [comment]
Sure, the id is 1405971863131969. I'm developing an app for journalists
that includes an asynchronous transcription tool (that uses Wit.ai's
engine), so it makes quite a lot of requests. I'd say that ideally, we'd
need around 4800 requests per minute to be able to have some scale.

**Comment by patapizza** [comment]
Hi @bfavero, this is quite a lot of requests.
It looks like you're only using ASR, not NLU. Let's see if we can carve out a better endpoint for this.
In the meantime, let's scale up gradually - can you ramp up traffic to 60 requests per minute to start with?

**Comment by bfavero** [comment]
Hi @patapizza, thanks for your reply! Yes, that's right, I'm only using ASR. 

To be clear, the use of the API would be intermittent, I wouldn't be such a high number of requests often. 

The problem I have is that I'm using Wit to transcribe long-ish audio files and I'd like for my app to transcribe at a 10:1 speed (10 minutes of speech in one minute). I split the audio files into 20s chunks and send them through Wit's API. So for a 1-hour-long audio file, for example, I use at least 180 requests. 

I haven't launched the app yet, so the API limit hasn't been a problem. My fear is that, once I launch it, transcription will get really slow very quickly. For example, if I receive 1-hour-long files from ten different users to process at the same time, the app would take at least 30 minutes to finish transcribing them.

Anyway, sorry for the long reply, and thanks for your help, I'm happy to scale up gradually.

**Comment by patapizza** [comment]
Thanks for the added context. It indeed looks like a new endpoint would better support your use case.

**Comment by ramh** [comment]
Please use the our /dictation endpoint. Thanks.
