### ISSUE TITLE
Retraining entity

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2272]
Hi,

We created an entity 'Single' in our wit app with synonyms 'Single'. But on inputting 'Single' we are getting the built in entity wit/number.
Is there any way that we can retrain the entity to 'Single' instead of wit/numbers for the keyword 'Single'.

Thanks

**Comment by ChrisyShine** [comment]
Can you share your app ID?

**Comment by anjaly** [comment]
> Can you share your app ID?

App ID : 4500267580035639

**Comment by ChrisyShine** [comment]
There is no training data for the 'single' entity in the app. Can you go to Understanding tab and add some training data for this entity?

**Comment by anjaly** [comment]
> 

@ChrisyShine Can you please let us know how we should add training data for this entity from Understanding tab. Below is the Screen shot of how it shows
![image](https://user-images.githubusercontent.com/601711/145516798-3976b1b5-ec5e-4570-aa26-6e66faff5659.png)

**Comment by ChrisyShine** [comment]
Click the X button at the right side of the entity panel to delete the default annotation. And then select the span of the "single" and select your own entity.
![Screen Shot 2021-12-10 at 9 56 40 AM](https://user-images.githubusercontent.com/30825086/145620188-d1dcd924-5403-4f3b-af99-520adf7b59ba.png)
![Screen Shot 2021-12-10 at 9 56 49 AM](https://user-images.githubusercontent.com/30825086/145620207-f7d32cbe-8eee-4a24-9d7b-0ee58fc93284.png)

**Comment by anjaly** [comment]
> Click the X button at the right side of the entity panel to delete the default annotation. And then select the span of the "single" and select your own entity. ![Screen Shot 2021-12-10 at 9 56 40 AM](https://user-images.githubusercontent.com/30825086/145620188-d1dcd924-5403-4f3b-af99-520adf7b59ba.png) ![Screen Shot 2021-12-10 at 9 56 49 AM](https://user-images.githubusercontent.com/30825086/145620207-f7d32cbe-8eee-4a24-9d7b-0ee58fc93284.png)

Tried to do the same but the 'Train and Validate' button is disabled
![image](https://user-images.githubusercontent.com/601711/145755636-0e643439-2dfb-49cb-ab54-ba2bf796a841.png)

**Comment by ChrisyShine** [comment]
Intent is required to train an utterance.

**Comment by anjaly** [comment]
> Intent is required to train an utterance.

We are handling this with entity only. So how can we retrain an entity if no intent is required

Thanks

**Comment by ChrisyShine** [comment]
Intent is required to train an utterance, you can prepare a dummy intent for this entity and just ignore the intent result when you receive the prediction result.

**Comment by anjaly** [comment]
> Intent is required to train an utterance, you can prepare a dummy intent for this entity and just ignore the intent result when you receive the prediction result.

Dummy intent is created for this entity, but when we enter other intent inputs, we are getting this entity in prediction result.

**Comment by ChrisyShine** [comment]
Can you share some real examples? The utterances, the expected prediction results and the real prediction results?

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
