### ISSUE TITLE
utterance is trained but intent is not recognized

### ISSUE THREAD

**Issue by ariel-paz** [wit-ai/wit#2274]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
utterance is trained but intent is not recognized
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
i train "quiero comprar franui" with intent='Quiero_comprar' and entity="Productos" value="franui", wit detect keyword "franui" but the intent is not detected
**What is the expected behavior?**
detect intent with keyword
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID: 2612150429082382

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
