### ISSUE TITLE
"Something went wrong. We've been notified" on every app

### ISSUE THREAD

**Issue by JuanCouste** [wit-ai/wit#2275]
I am experiencing issues with wit.ai in general, I suposse they are bugs

"Something went wrong. We've been notified" and "App not found" are popping everywhere, from the http api to the web apps at "https://wit.ai/apps/*".

- It happens on every app that I create, or the ones I asked another dev to create
- It happens on both Open & Private
- It happens on both Spanish & English

Sometimes it gets so broken that the "Permanently Delete This App" button says "App not found", and for some reason switching Visibility "fixes" it for a little bit.

To reproduce
- Create an app
- Register an utterance
- The second one should prompt ​

"There was an error validating the utterance.
Something went wrong. We've been notified."
 
 I'll provide an app Id, but this happens on every app that i've created today, and in diferent ways

 279025807534909

**Comment by ghost** [comment]
I'm running through the same issue. And I'm using builtin Wit.ai with Facebook Messenger.
I've succeeded making it work again temporarily by changing the n-best values in the advanced parameters of Messenger product under Facebook application.
But after 2 or 3 successful requests, it stops working again.

**Comment by ramh** [comment]
Hi, can you check and confirm if you are still facing these issues. Thanks.

**Comment by jansila** [comment]
Hi, yes it has been happening to my app as well for a couple of days now. I tried renew the server token etc, but to no vail. 

My app ID is 1545378798907769. 

Thanks for investigating!

**Comment by patapizza** [comment]
Hi @JuanCouste it looks like the app doesn't exist anymore. I'm not able to reproduce on new apps.

@jansila I've identified the issue with your app. Looking to fix it.

**Comment by JuanCouste** [comment]
> Hi, can you check and confirm if you are still facing these issues. Thanks.

Hi @ramh , there were no major issues the next day I posted this, "Something went wrong. We've been notified" still apeared in some places but it was usable through the http api

**Comment by JuanCouste** [comment]
> Hi @JuanCouste it looks like the app doesn't exist anymore. I'm not able to reproduce on new apps.
> 
> @jansila I've identified the issue with your app. Looking to fix it.

Hi @patapizza , It seems to have been resolved

**Comment by jansila** [comment]
> Hi @JuanCouste it looks like the app doesn't exist anymore. I'm not able to reproduce on new apps.
> 
> @jansila I've identified the issue with your app. Looking to fix it.

Hi @patapizza, 

is there any progress with this, please?
I thought that at worst I can download the app data and create a new one. But it is not possible either:

![image](https://user-images.githubusercontent.com/12913856/151769903-53eaf30b-ebcf-4200-8dea-7efac887c8e6.png)

It would be great if we could keep the rich history of the app.
Thanks a lot for and update!

**Comment by patapizza** [comment]
@jansila Thanks for following up. We're still working on this. Thank you for your patience.

**Comment by jansila** [comment]
> @jansila Thanks for following up. We're still working on this. Thank you for your patience.

Hi @patapizza, sorry to bother you again, but is there any progress? My client is asking about it. Is it necessary to create a new app and start training it again?

**Comment by jansila** [comment]
@patapizza @ramh  
Hi, it has been a month now , is there any progress, please?

**Comment by doggeral** [comment]
@jansila Checked on wit.ai, seems the issue is gone. Feel free to let me know if you need any helps.

**Comment by gfish35** [comment]
Hi @patapizza and @ramh
The issue still seems to persist.

The error occurs while training and validating - 
![image](https://user-images.githubusercontent.com/59993175/163327009-edaf7a4d-57d8-44af-91a2-bb255af6fe41.png)

App deletion, token re-generation, adding utterances all fail.

My app ID: 1149114369241258

Thanks for your attention!
