### ISSUE TITLE
/utterances api not working for an app

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2276]
Hi,

We are calling the below api for training examples in wit.ai app
https://api.wit.ai/utterances?v=20200513
When we checked after calling the api we are getting the below success message
{
"sent": true,
"n": 1
}
But it is not getting trained in the wit.ai app.
The examples are not getting listed in the utterances tab
Can you please check.
Our AppId is 605564230824603

Also while we try to train example from understanding tab it is sowing the attached error
![image](https://user-images.githubusercontent.com/601711/146313397-6e313c6e-84ec-47c6-9b68-ce0207902c62.png)

Also when we try to delete the intent it is not deleting.

Thanks

**Comment by anjaly** [comment]
Hi,
Today when we checked we were able to delete those examples and intent from wit ui. Then we added intent and examples via api.
Now it is listing under 'bluedart' intent in Utterances tab.
But in Understanding tab when we try 'bluedart' the intent is not showing.

**Comment by anjaly** [comment]
Any update

**Comment by ramh** [comment]
Hi @anjaly, glad to know the deletion and other UI issues are resolved now.

In regards to adding "Blue Dart" as an utterance, it seems to be added to the Utterances tab right now. Can you check and let us know if you are able to add more utterances without an issue? Thanks.

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
