### ISSUE TITLE
Wit app website keeps loading and doesn't respond

### ISSUE THREAD

**Issue by TaraNaser** [wit-ai/wit#2277]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
Wit app website keeps loading and doesn't respond
![image](https://user-images.githubusercontent.com/71825913/146329110-bf13967c-695c-4397-a7c7-9710253a2c4a.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
