### ISSUE TITLE
wit/location entity not found on save

### ISSUE THREAD

**Issue by JakobReiter** [wit-ai/wit#228]
Input Sentence: "I need a place to eat in Vienna"
Vienna is marked correctly as wit/location in der story view BUT when the story is saved an error message says: "Wit could not find this entity"

When I go to the understanding menu and type the same sentence, then it correctly associates Vienna as wit/location though.

**Comment by l5t** [comment]
Hi, this happens when your app needs more training. Go to the Understanding tab and try out the sentence and validate it with the entities you want. While at it, try to validate synonymous sentences. The more, the better.
