### ISSUE TITLE
Training ongoing since a month!!

### ISSUE THREAD

**Issue by Nisreena93** [wit-ai/wit#2284]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
My App stuck on the status 'Training ongoing' since one month ago!
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Go to the main screen on the app and you will show 'Training ongoing' at the right top.
**What is the expected behavior?**
Training usually took 5 min max to procceesd!
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
341248294209239

**Comment by yuzh174** [comment]
Looking into it

**Comment by yuzh174** [comment]
The training is complete. Let us know if you still see issues.
