### ISSUE TITLE
App stuck at training

### ISSUE THREAD

**Issue by SarahAabid** [wit-ai/wit#2288]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?
Report a bug

**What is the current behavior?
App is stuck at "Training ongoing"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
Start training from Wit.ai dashboard

**What is the expected behavior?
Training should be completed

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.
580041809784935

**Comment by SarahAabid** [comment]
The app is still not working. 580041809784935
Please check it

**Comment by yuzh174** [comment]
Looking at it

**Comment by yuzh174** [comment]
The training has completed. Let me know if you see other issues.
