### ISSUE TITLE
Users Not Able to See Intents, Train Phrase, or Check Confidences in App

### ISSUE THREAD

**Issue by ZaraElena** [wit-ai/wit#2289]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
- Bug

**What is the current behavior?**
- As a user of an app, I am not able to train. The dropdown for intents is showing up blank as if none exist, and when I type in any phrase, I don't receive any kind of response,, even for the simplest of phrases. This is happening consistently to multiple users on the app, and intermittently for others on the app.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
![image](https://user-images.githubusercontent.com/89899221/148121046-83d0c34c-b852-4bdd-bb41-4e5ad64d1342.png)
![image](https://user-images.githubusercontent.com/89899221/148121075-88355b16-7191-479c-9b95-86c41e4f670d.png)
1. Access the app
2. Expand the dropdown for "Intent" in the **Understanding** tab for the app
3. Notice that no intents populate
4. Type a basic phrase into the text field (i.e. "hi there" or "how are you?" which should both trigger intents in our app)
5. Notice that no intent matches come up and no confidences come up

**What is the expected behavior?**
- Expected behavior is every user of the app should be able to see the intents in the app, train in the app, check phrase/intent confidences, and so on - so the basic user behavior for apps.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
- App ID: 1504918609519459

NOTE: This issue has been occurring for WEEKS and other users of the app have reported issues and we have received no response. This is a really critical issue for us and some assistance would be greatly appreciated.

**Comment by brennadoyle** [comment]
This is similar to my issue: https://github.com/wit-ai/wit/issues/2265 This is critical for training to occur.

**Comment by jayyteee** [comment]
Hello @ZaraElena thanks for bringing this issue to our attention, we are looking into it.

**Comment by brennadoyle** [comment]
@jayyteee Hello, any update on when this will be fixed?

**Comment by jayyteee** [comment]
Hello @brennadoyle @ZaraElena the issue should be resolved now, can you confirm it's working for your apps?

**Comment by jayyteee** [comment]
closing, feel free to open another issue if this problem comes back
