### ISSUE TITLE
api.wit.ai/sync receives status 500 - Internal Server Error

### ISSUE THREAD

**Issue by JakobReiter** [wit-ai/wit#229]
When I save a story or change the app details I get a status 500 error on the console and the action is not properly executed:
![screen shot 2016-05-17 at 16 57 31](https://cloud.githubusercontent.com/assets/9266151/15327110/a13c3f70-1c50-11e6-85b6-422a1aa02ed3.png)

**Comment by l5t** [comment]
Thanks for reporting. We do have an issue right now with some of the apps. I will update your when fixed.

**Comment by l5t** [comment]
It was fixed 3 hours ago. Closing
