### ISSUE TITLE
Training inputs showing 'Training ongoing' and is not completing

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2290]
Hi,

When we try to train an input , via /utterances api or directly through wit ui it is showing 'Training ongoing' in wit app and is still the same after more than half an hour. It was working earlier. 
Can anyone please assist?

Attached the SS.
![image_2022_01_07T05_26_00_407Z](https://user-images.githubusercontent.com/601711/148496833-12954709-3512-48dd-896d-3008763ccab2.png)

AppId: 4844325972264845

Thanks

**Comment by jayyteee** [comment]
Hello @anjaly, I just checked and it looks like training has completed, can you confirm? Occasionally for various reasons training can stall for awhile or take longer than expected to complete. Let us know again in you continuously are running into this issue.

**Comment by srambabu-souvenirapps** [comment]
hi i am also facing the same problem. @anjaly Is your problem resolved?
