### ISSUE TITLE
utterances for the app show an error msg

### ISSUE THREAD

**Issue by RadhikaPallavi** [wit-ai/wit#2292]
Need help to load the utterances back. 
![image](https://user-images.githubusercontent.com/97292380/148563612-3662a3e3-e657-488b-918b-1040803185b2.png)

App ID - 572046700564927

**Comment by jayyteee** [comment]
Thanks for opening this issue @RadhikaPallavi we are taking a look

**Comment by RadhikaPallavi** [comment]
@jayyteee Could you please share an update if any. The utterances still do not load. 
Also if you could you guide me with the understanding why does the app does not display training completed ever. It always show ongoing training, unless the we train few more questions, when we get a message about training scheduled.

**Comment by jayyteee** [comment]
@RadhikaPallavi the issue should be resolved now. I also checked why it was always ongoing and it looks like it was due to an old job getting stuck - I manually restarted it so that should also be resolved now. Feel free to open another issue if you run into it getting stuck again like before.
