### ISSUE TITLE
Offline voice command recognition

### ISSUE THREAD

**Issue by JbfProductions** [wit-ai/wit#2294]
Dear Wit AI team,

For a small university VR project me and three other students are developing a Mixed Reality App using passthrough mode for Quest. Our idea was to implement really simple voice command like "fire" or may be a set of two voice commands like "lock on target" and "fire". We would like to use Oculus Voice SDK. After experimenting with Wit.ai I discovered that voice recognition and transcription in Oculus Voice SDK works only online. Is there any chance to train the app on Wit Ai Server and then to use the library locally without sending the recording each time to the server, as this would introduce latency to out app? The set of commands we want to use is really simple.
I also saw that in app voice experience script delivered in Oculus Voice SDK there is a possibility of custom transcription with a custom NLU provider. Is there any NLU libraries, which will work locally on Quest 2?
Thank you for your answers in advance.
Kind Regards
Jeff

**Comment by jayyteee** [comment]
Hello, sorry for the late response on this - at this time there is no plan to have an offline library to replace the server's functionality. For the Voice SDK, we provide NLU through our wit server, so any other custom NLU provider we are unable to help with. If you have specific use cases and requirements in mind, feel free to send an email to help@wit.ai to discuss further. Depending on how much latency is acceptable for your usecase, using our online server for NLU could work as latency is not too high.
