### ISSUE TITLE
'Something went wrong. We've been notified'

### ISSUE THREAD

**Issue by RMariegaard** [wit-ai/wit#2295]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
The app used to reply just fine, now it responds with an error without an error code to all input
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I don't know if it can be replicated as it seemed to come out of nowhere
**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
Add ID: 435908908022865

Imma get an F on this exam if you don't respond lmao

**Comment by jayyteee** [comment]
Hello @RMariegaard, I took a look and it looks like the error for this appId is that you are currently exceeding the rate limit, with over 600 requests per minute from your appId. If you need to increase this limit, please send us a email at help@wit.ai and provide more details about your use case and your estimated requests rate.
