### ISSUE TITLE
My app stuck in training

### ISSUE THREAD

**Issue by arscslvt** [wit-ai/wit#2297]
Hi, my app 619772309312044 is stuck in training for 2h at least. How can I fix?

**Comment by ksaitor** [comment]
Same situation. But it's been days now.
Also receiving "Something went wrong. We've been notified" error on every request.

**Comment by jansila** [comment]
> Same situation. But it's been days now.
> Also receiving "Something went wrong. We've been notified" error on every request.

There is another issue for that. 
https://github.com/wit-ai/wit/issues/2275

**Comment by patapizza** [comment]
Looks like the training is done now.
