### ISSUE TITLE
Stuck utterences on the understanding tab

### ISSUE THREAD

**Issue by UnitTHK** [wit-ai/wit#2299]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Reporting a bug
**What is the current behavior?**
Currently, I seems to be having some issue with some utterences that are captured from the API calls, when I click the "Train and Validate" button on the dashboard, the utterance doesn't go away as it would normally, and it only appears to happens to a few of the utterences, most specifically, ones that have multiple lines, I think. I haven't seen any that doesn't have multiple line get stuck with this yet, clicking the X button do get rid of the utterance though
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Please read above
**What is the expected behavior?**
The utterance validation to process normally
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
my app ID is 515063659744789

**Comment by doggeral** [comment]
App looks good now.
