### ISSUE TITLE
Wit always executing error function

### ISSUE THREAD

**Issue by vivekpd15** [wit-ai/wit#230]
I have multiple stories in my Wit interface. It was working all good a day ago. Since yesterday, whatever question I am throwing at wit, it always returns the error function after merge instead of the function which is supposed to solve that problem. The entities that were extracted from the merge function were correct. But wit executes error function post that and that too 4 times in a row. Please see the attached image from my Wit console: 

![capture](https://cloud.githubusercontent.com/assets/14350316/15422512/9612f0e2-1e96-11e6-9b28-41c452032d83.PNG)

**Comment by xbili** [comment]
Having the same issue here as well!

**Comment by Yoshi3003** [comment]
Hi, I'm also about to open the same issue! It actually happened to me since last week!
I sent a normal merge request just like usual but now all return HTTP response is:

`{
type: error,
confidence, 1
}`

I asked the live chat support but did not get a response from them yet (usually I would get one).

**Comment by Bongsakorn** [comment]
Same issue

**Comment by l5t** [comment]
HI, sorry for the late reply. It may happen if you keep using the same sessions ID. Make sure you start with a unique session ID when you restart a conversation.

**Comment by vivekpd15** [comment]
Thanks a lot. The problem was resolved. It will be great if you can add this fact to the readme or somewhere. There is no documentation about this anywhere.

**Comment by Francis88** [comment]
Good idea, thanks

**Comment by vigneshmanikandan97** [comment]
How do I create new Session IDs for new conversations? 
A link or a piece of code would be really helpful.
Thank You.

**Comment by stopachka** [comment]
Hey @vigneshmanikandan97 

You can use a temporary id, and increment it whenever you want to create a new session. i.e 

```
let _sessionId = 0;
const newSessionId = () => {
  return_sessionId++;
}
```

It would help to get more context on what you are trying to do. If you need more help, try creating a new task, and include a code snippet, and the goal for what you are trying to do
