### ISSUE TITLE
GET wit.ai/message constantly timesout !

### ISSUE THREAD

**Issue by kostas-simi** [wit-ai/wit#2302]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
since the 17th of January 2022 wit.ai request times out several times on more than 10 apps concerning the IP 185.60.216.56:443

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
sending a get request to https://wit.ai/message and then the request times out

10:14:41 error: WitAi error :{"message":"connect ETIMEDOUT 185.60.216.56:443","name":"Error","stack":"Error: connect ETIMEDOUT 185.60.216.56:443\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)","config":{"url":"https://api.wit.ai/message","method":"get"

**What is the expected behavior?**
the request should return the intent of the message

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
this affects mutlpiple apps i am listing the from most to least error occurrences 
132640028378117
929627037790564
853500071886823
528239974867467
2972366752982301
3893436137436505

**Comment by doggeral** [comment]
Tested on wit.ai, seems the issue is gone.
