### ISSUE TITLE
app stuck on "training ongoing" ONE MONTH

### ISSUE THREAD

**Issue by kostas-simi** [wit-ai/wit#2303]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
BUG

**What is the current behavior?**
The app status is stuck on "training ongoing" for 1 (one) WHOLE month now.. it is starting to affect us badly as we can not schedule new trainings... when will this be fixed?? can someone please re-start the training?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Initialized training from WitAI dashboard and then got stuck for a month.

**What is the expected behavior?**
The training procecdure normally lasts 2 mins not A MONTH long

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
929627037790564

**Comment by ruoyipu** [comment]
Hi @kostas-simi, I've restarted the training and it's now complete. Please let us know if it happens again.
