### ISSUE TITLE
"item" entities lost?

### ISSUE THREAD

**Issue by galubap** [wit-ai/wit#2306]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

Bug

**What is the current behavior?**

My application lost almost all "item" entities I did train last 2 years. Problems occurs today, yesterday everything worked perfect.
Also clicking "Train and validate" gives message "There was an error validating the utterance. Permissions error".

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

3382588755148772

**Comment by ruoyipu** [comment]
Hi @galubap,

I still see that app 3382588755148772 has the "item" entity, and there's about 131 utterances using that entity. Was it re-added recently?
<img width="1016" alt="Screen Shot 2022-01-28 at 1 38 51 PM" src="https://user-images.githubusercontent.com/33233694/151625220-0c31fc7e-b38d-4405-b0bb-51cfd339ecab.png">


Could you provide a screenshot and example of what utterance you're trying to train and I can try to repro?

**Comment by patapizza** [comment]
Taking a random utterance, it seems like it's working:
<img width="1079" alt="Screen Shot 2022-02-02 at 6 25 39 AM" src="https://user-images.githubusercontent.com/1015208/152172718-88dfc2be-fe5d-4cc9-931d-de8dbfd5c742.png">


Can you share examples of utterances that don't work and what is the expected outcome?

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
