### ISSUE TITLE
Training status ongoing for way longer than usual

### ISSUE THREAD

**Issue by miezzi** [wit-ai/wit#2307]
I added a story and tried to train wit.ai for the same, but the training status remains ongoing(remains yellow) and has not changed since.
Before It used to get green after few minutes of training.
I've also tried validating new examples in Understanding tab but nothing changed. Please help to restart my app. It isn't the first time that it happens to me with a wit.ai project.

AppId: **1327750504270664**
AppName: **Compensar_Recreacion**

The endpoint doesn't work either. 
curl \
 -H 'Authorization: Bearer private_token' \
 'https://api.wit.ai/message?n=4&q=Hola'

The response is 
{
    "error": "Something went wrong. We've been notified",
    "code": "unknown"
}

**Comment by ruoyipu** [comment]
Hi @miezzi,

I've restarted training for app 1327750504270664, and it looks like it's now complete.

We deployed a bad package yesterday which is now fixed, let me know if you're still having any endpoint issues.

**Comment by miezzi** [comment]
Hi @ruoyipu 
The first point has already been solved. training is complete. Thanks for the quick solution.

We have several trainings in wit.ai and the endpoint of all of them work fine except this one. The endpoint still responding the same error.
AppId: **1327750504270664**
AppName: **Compensar_Recreacion**

**Comment by doggeral** [comment]
The issue has been fixed.
