### ISSUE TITLE
Entity Keyword strict match / end in space?

### ISSUE THREAD

**Issue by MattWIP** [wit-ai/wit#2308]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question / Possible Feature request?

**What is the current behavior?**
Utilizing a Keyword + Free Text strategy I've noticed we can't have a "strict" match of the keyword. For example, we have a keyword for "BAC", but it will match the word "back" for example. We would like to make it so it only matches "BAC" ( stand-alone word ending in a blank space or period).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
There isn't a bug. I believe I'm either using the keyword incorrectly or it's just not built for my intentions.

**What is the expected behavior?**
We are hoping for it to match just the keyword and not the substrings of a word.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
N/A

Is there another strategy we should be using to get this match more accurate? 

Thank you!

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
