### ISSUE TITLE
URGENT Cannot log into Wit.ai and access my apps!

### ISSUE THREAD

**Issue by nickcbarone** [wit-ai/wit#2309]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
report a bug

**What is the current behavior?**
I can't sign into my apps even though I successfully authenticate via Facebook.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I go to wit.ai
I try to log in by authenticating through Facebook
I successfully authenticate my FB account
I land on the wit.ai homepage still, and cannot access any of my apps
When I enter my app URLs directly, I land on wit.ai's sign in page and am asked to log in again

**What is the expected behavior?**
I should land on My Apps page when I successfully authenticate via Facebook.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
One of my main apps is ID: 1650554041800318

**Comment by alxferraz** [comment]
Same here

**Comment by patapizza** [comment]
Thanks for reporting and sorry about the issue. We're on it.

**Comment by patapizza** [comment]
This should now be fixed. @nickcbarone @alxferraz Can you confirm?

**Comment by nickcbarone** [comment]
@patapizza Confirming this issue has been fixed for me. Thank you for the fast resolution.

**Comment by alxferraz** [comment]
fixed for me, thank you very much!

**Comment by patapizza** [comment]
Thank you for confirming!
