### ISSUE TITLE
How to create intents in latest version?

### ISSUE THREAD

**Issue by raghavendrav6** [wit-ai/wit#231]
Hi,

This is not an issue. I was going through some videos and docs. It is changed that how to create an intent. I am a newbie, Please tell me or share a link which explains how to create/use a custom intent in console. I have tried using HTTP API but its giving an error "**Cannot create intents, it confuses your bot**". I am not sure what's wrong.?

Thanks

**Comment by avinash8526** [comment]
Create a new story , then goto understanding tab , follow this gif, in this example below I have created pizza_intent as new intent
![Uploading it Console20160527145854.gif…]()

**Comment by leeola** [comment]
This seems odd, won't `pizza_intent` be mapped to an entity rather than an "intent"? It appears that, on the current Bot Engine, there are no Intents. Only stories, that map to Actions. Training seems to only map context-less sentences to entities.

**Comment by avinash8526** [comment]
@leeola true , in new bot engine , there is no intent .Sorry my bad. I think they have replaced the intent with the search strategy . Currently one can have 3 different search strategy mapped to an entity.
https://wit.ai/docs/recipes#which-entity-should-i-use

**Comment by RameshKrishnamoorthy** [comment]
Are you guys able to create a new entity which can have multiple different values? For example, if the entity was pizza, how do you train the Bot Engine to understand the different pizzas? Do we need to add all the different pizza names as values to the entity? Or, will the bot engine be intelligent enough to understand a pizza name from a sentence once it is trained on a few? It doesn't seem to work like that and there is no one help also!

**Comment by avinash8526** [comment]
goto understanding tab and train bot with few sentences and add proper entity ,U don't need to add value  always. Values are returned whenever api call is made.
Since wit.ai is damm slow, whenever u hit validate, wait for the status icon to go yellow and then green. it means bot engine has trained itself. If u try to validate too many expression at once , nothing will be saved at backend.

**Comment by athirauk** [comment]
where does the stories,entities and intent in wit.ai gets stored?

**Comment by l5t** [comment]
They are stored inside the Facebook datacenter. You can get a copy via the import/export: https://wit.ai/docs/recipes#copyexportversion-my-app

**Comment by lbustelo** [comment]
I may be overloading this question, but I want to know then answer to this, but programatically. I the API docs it says that that `/intents` API is deprecated. What is the replacement and where can I find examples/instructions?

**Comment by blandinw** [comment]
@lbustelo We merged "intents" and "entities" last year. Intents are now simple entities of type "trait". Intents as you know them are gone.

You can programmatically manipulate entities [using the /entities API](https://wit.ai/docs/http/20170307#get--entities-link), [read specifically about how "intents" work now](https://wit.ai/docs/recipes#categorize-the-user-intent), or [read more about "trait" entities and the 2 other types](https://wit.ai/docs/recipes#which-entity-should-i-use).

Feel free to reopen if you have further questions.

**Comment by lbustelo** [comment]
Thanks @blandinw. I'll give that a try.

**Comment by anjitha-devan** [comment]
How can I add a follow up intent on wit.ai like in dialogflow?

**Comment by jtliao** [comment]
Hi @anjitha-devan, there isn't really an idea of a follow up intent in Wit, you would have to add the logic on your side after receiving a message of a certain intent

**Comment by anjitha-devan** [comment]
Thanks @jtliao

**Comment by anjitha-devan** [comment]
@jtliao, @blandinw, I want to implement a location selection by user in Facebook chat bot.
While I am looking into message.attachment, it don't have a location type.
The chat bot is sending a map and user selecting the required location on map.
How can I implement this?

**Comment by jtliao** [comment]
hi @anjitha-devan, this seems outside the scope of Wit, unfortunately I don't think we're the best to help you with this issue. 

Additionally, in the future, please avoid following up on old threads with new issues, it makes it harder to track.

**Comment by mohit2494** [comment]
> @lbustelo We merged "intents" and "entities" last year. Intents are now simple entities of type "trait". Intents as you know them are gone.
> 
> You can programmatically manipulate entities [using the /entities API](https://wit.ai/docs/http/20170307#get--entities-link), or [read specifically about how "intents" work now](https://wit.ai/docs/recipes#categorize-the-user-intent), or [read more about "trait" entities and the 2 other types](https://wit.ai/docs/recipes#which-entity-should-i-use).
> 
> Feel free to reopen if you have further questions.

This was really helpful.
