### ISSUE TITLE
Voice recognition returns HTML errors

### ISSUE THREAD

**Issue by backmeupplz** [wit-ai/wit#2310]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

A bug

**What is the current behavior?**

Voice recognition returns the error, probably HTML, my response parser errors with `Unexpected token &lt; in JSON at position 0`, that's `<` :)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

N/A

**What is the expected behavior?**

Voice recognition works

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

Here's one of the app ids experiencing issues: 1139646093110797

**Comment by patapizza** [comment]
Closing in favor of https://github.com/wit-ai/wit/issues/2311
