### ISSUE TITLE
[503 Service Unavailable] on https://api.wit.ai/speech 

### ISSUE THREAD

**Issue by rhenanbartels** [wit-ai/wit#2311]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
requests to `https://api.wit.ai/speech` return with 503 status

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

```python
import requests

headers =   {
                "Authorization": "Bearer " + api_key,
                "Accept": f"application/vnd.wit.20200513+json",
                "Content-Type": "audio/wav",
            }

chunk = b""  # binary data containing wav sound
resp = requests.post('https://api.wit.ai/speech', headers=headers, data=chunk)
```

**What is the expected behavior?**
The request is expected to return 200 with the field `text`

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
- 1405971863131969
- 482412936218681
- 614470649974920
- 261358745932567

## Requests error message
```
<ClientResponse(https://api.wit.ai/speech) [503 Service Unavailable]>
<CIMultiDictProxy('Content-Type': 'text/html; charset=utf-8', 'Access-Control-Allow-Origin': '*', 
'Proxy-Status': 'no_server_available; e_isproxyerr="AcLt_FreSYAztrv5E9hgk4-Q__MkLvqeHJA47xfO3OdBnm98n0FIr0WAKNIq-A";
'Date': 'Thu, 27 Jan 2022 21:14:28 GMT', 'Connection': 'keep-alive', 'Content-Length': '2959')>

```

**Comment by dzlandis** [comment]
Having the same issue on an application which has been tested to work just fine previously! +1

**Comment by patapizza** [comment]
We've had a bad deployment and should be back now. Sorry about that. Can you @rhenanbartels @dzlandis @backmeupplz  confirm?

**Comment by rhenanbartels** [comment]
@patapizza Everything is back on track!  Thank you for your prompt reply and for the amazing work

**Comment by dzlandis** [comment]
Back and working for me as well! Thanks ❤️

**Comment by backmeupplz** [comment]
@patapizza all good, thank you!

**Comment by patapizza** [comment]
Thank you all for your understanding and confirming!
