### ISSUE TITLE
Im getting error when I use node-wit

### ISSUE THREAD

**Issue by soultellegend** [wit-ai/wit#2312]
I was using node-wit. I have a small json file with texts. I tried foreach to send all texts to wit but I think I tried sending them too fast. Now I cant use node-wit. I'm getting error.  "[wit] [message] Error: Something went wrong. We've been notified
Something went wrong. We've been notified". Before the mass request it was working fine

**What is the current behavior?**
Getting error. [wit] [message] Error: Something went wrong. We've been notified
Something went wrong. We've been notified

**What is the expected behavior?**
Sending the text to api without any errors.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
645332253379642

**Comment by ruoyipu** [comment]
Hi @soultellegend,

We do have rate limiting on requests. I see around 1am PST there were several timeouts and throttling errors for app 645332253379642, but those errors have stopped now. Are you still experiencing those issues?

**Comment by soultellegend** [comment]
Thank you. Its fixed
