### ISSUE TITLE
Need help with training stuck "Training Ongoing"

### ISSUE THREAD

**Issue by RadhikaPallavi** [wit-ai/wit#2313]
We have 2 applications which are stuck with the training showing the status "training ongoing".
It's difficult to understand if the training is even completed.
Could you please help us with clearing any job if stuck?
App id for the two apps are - 618389522541052 & 4926118934078909

**Comment by ruoyipu** [comment]
Hi @RadhikaPallavi,

I've restarted training for those 2 apps and it looks like they're now complete.

**Comment by RadhikaPallavi** [comment]
@ruoyipu, Thanks a lot! This is very helpful
