### ISSUE TITLE
https://wit.ai/apps Giving error

### ISSUE THREAD

**Issue by soultellegend** [wit-ai/wit#2314]
Im getting 
![image](https://user-images.githubusercontent.com/63239999/151571481-aa63df3a-913f-4f86-bcf7-234db51c064f.png)

**Comment by ruoyipu** [comment]
Hi @soultellegend,

I cannot repro with my account, is this still occurring? If so, could you provide the app ID of any one of your apps?

**Comment by soultellegend** [comment]
Its fixed too.
