### ISSUE TITLE
Internal server Error 

### ISSUE THREAD

**Issue by Maha-ms20** [wit-ai/wit#2315]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?** report a bug 

**What is the current behavior?**
the app is working, but some times when run the code the error appear  
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
![PHOTO-2022-01-30-22-03-18](https://user-images.githubusercontent.com/78106995/151714884-483c9b71-3cd3-4fc9-9762-13d54420d1f2.jpg)

**What is the expected behavior?**
always run the app without any error 
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
277717187596622

**Comment by patapizza** [comment]
Hi @Maha-ms20 which endpoint are you hitting?

**Comment by Maha-ms20** [comment]
What do you mean by endpoint ?
________________________________

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
