### ISSUE TITLE
Wit returning wrong intents with high confidence 

### ISSUE THREAD

**Issue by 91ns** [wit-ai/wit#2316]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
wit returning the wrong intents with high confidence
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

https://api.wit.ai/message?v=20210904&q=3111357835

{
    "text": "3111357835",
    "intents": [
        {
            "id": "1122815944802197",
            "name": "RegistrationEN",
            "confidence": 0.6751
        }
    ],
    "entities": {},
    "traits": {}
}

**What is the expected behavior?**

Input that wasn't trained shouldn't return an intent 

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

2456049344704473

**Comment by soultellegend** [comment]
I have the same issue

**Comment by dieggh** [comment]
We have a similar issue with the intents confidence. In our case we lost all the intent's confidence but the entities confidence is okay.
And also the trainings are not working

**Comment by nishsinghal20** [comment]
Hello! It is expected that any utterance will return a "best matching" intent, not just the utterances in the training set. In order for the app to not handle any utterances, please check the "Out of scope" box in the Understanding section.

![image](https://user-images.githubusercontent.com/27743368/152035365-f88831f3-bb3c-419e-ae31-314a358a7b5c.png)

**Comment by patapizza** [comment]
Hi Nour, what is the expected intent for the utterance `3111357835`? Was it working before? Can you share a few more examples of expected vs predicted?

@soultellegend @dieggh Can you share your app ID with a few examples of expected vs predicted?

Thank you for your patience.

**Comment by patapizza** [comment]
@91ns Your app has been fixed.

@soultellegend @dieggh Please share your app ID. Thanks.
