### ISSUE TITLE
Intent value returned for any gibrish question.

### ISSUE THREAD

**Issue by RadhikaPallavi** [wit-ai/wit#2318]
We have issues with the api returning the Intent where as the App does not show any intent in the understanding.
please find the snapshot from the witAi and api for the same question below:
![image](https://user-images.githubusercontent.com/97292380/152151381-373aaf69-0c7d-425b-b7ab-d725c16499d8.png)
![image](https://user-images.githubusercontent.com/97292380/152139471-00ff9403-7fbc-4c57-baee-0d6b8c252b4f.png)

App ID for the provided snapshots is - 572046700564927
The same also happens for another application with the app ID - 618389522541052

However it does not return any intent in the app id - 4926118934078909. This app works fine.

All these three apps are provided with the same initial training to start with.

Could you please help us understand the difference and correct the error with the same?

**Comment by patapizza** [comment]
Thanks for reporting @RadhikaPallavi, we're looking into this.

**Comment by patapizza** [comment]
Your apps have been fixed.

**Comment by RadhikaPallavi** [comment]
@patapizza Thank you very much!! This was very helpful.
