### ISSUE TITLE
Issue in identifing out of scope inputs

### ISSUE THREAD

**Issue by prajisha** [wit-ai/wit#2319]
Hi,

We are facing an issue that Khmer workspace identifies english input which is not trained and it returning correct intent.
'Hi' returning 'greeting' intent in khmer workspace.
'Job' returning 'static_intent_job' intent in khmer workspace.
We expect english input to return out of scope response in khmer workspace.
Is there any way to solve it?

Thanks
![image](https://user-images.githubusercontent.com/47774278/152287540-16ff4520-0c93-4dfe-92e6-5514c4dca4e5.png)
![image](https://user-images.githubusercontent.com/47774278/152287605-397d140d-5d19-4f1d-9ce7-35854b8b522f.png)
![image](https://user-images.githubusercontent.com/47774278/152287925-0ca8bd87-efda-470c-8909-62e3328e87d6.png)
![image](https://user-images.githubusercontent.com/47774278/152288023-8d938691-21f0-4d98-b243-17e0fbaa105c.png)

**Comment by nishsinghal20** [comment]
Hi @prajisha! Thank you for bringing this to our attention. Can you please share the app ID so we can investigate this further?

**Comment by prajisha** [comment]
App ID :  468448841441795

**Comment by prajisha** [comment]
> Hi @prajisha! Thank you for bringing this to our attention. Can you please share the app ID so we can investigate this further?

App ID : 468448841441795

**Comment by patapizza** [comment]
Hi @prajisha,

The current scope for a Wit.ai app is per-language. For inputs from another language, the behavior is undetermined.
I'd recommend to call [`GET /language`](https://wit.ai/docs/http/#get__language_link) to filter inputs for the supported languages, and route to the relevant Wit.ai app.

Hope this helps.
