### ISSUE TITLE
Wit.ai unable to map intent even after training it for the same text

### ISSUE THREAD

**Issue by avinash8526** [wit-ai/wit#232]
Reference stackoverflow:
http://stackoverflow.com/questions/37478196/wit-ai-understanding-tab-is-not-resulting-expected-intent-roles/37479564#37479564

**Comment by avinash8526** [comment]
As per the wit crew , my story was in hung state, they restarted my bot engine,  after that entity is mapped properly but it is dammmmmm slow...

**Comment by l5t** [comment]
Closing, please open a new issue if you still experience this
