### ISSUE TITLE
Intent values displayed in wit app for gibberish value.

### ISSUE THREAD

**Issue by RadhikaPallavi** [wit-ai/wit#2320]
@patapizza, with Reference to the issues resolved yesterday (https://github.com/wit-ai/wit/issues/2318),  could you please help us resolve the Gibberish issue with one more application as well. The Other application is now showing return values for the gibberish text.
Please find the snap shot below:
![Gibberish](https://user-images.githubusercontent.com/97292380/152312202-ed7b7f02-6130-49e8-a56d-b0391bae7fc2.JPG)

The app id -  4926118934078909.
Also it would be great, if you could please help us with the understand what goes wrong, so we can avoid such problems in future.

**Comment by nishsinghal20** [comment]
Hey @RadhikaPallavi! I can help you with this. Let me get back to you once we have a fix on our side.

**Comment by nishsinghal20** [comment]
This should be fixed now :)

**Comment by RadhikaPallavi** [comment]
@nishsinghal20 Thankyou very much for the quick resolution!! 😊😊
