### ISSUE TITLE
Issue in identifing intent which has no relation with keyword

### ISSUE THREAD

**Issue by prajisha** [wit-ai/wit#2323]
Hi

We are facing an issue with the wit workspaces.
If we input a random text "aaa" or "bbb" or "test", we are getting an intent which has no relation with the keyword.
Can you please look into the issue with high priority, as it is affecting our business.
'aaa' returning 'hi' intent.
'test' returning 'tentative' intent.
We are facing this issue with all worspaces and here is the app id of one of the workspace.
App ID : 4344353432292657

Thanks

![image](https://user-images.githubusercontent.com/47774278/152479279-37c3d5db-60b0-4b97-b313-1d7ab92c685d.png)
![image](https://user-images.githubusercontent.com/47774278/152479287-580e0269-119a-4097-af6c-9eb6413ebde8.png)
![image](https://user-images.githubusercontent.com/47774278/152479304-8b57925f-806b-4254-bf28-99dbfbaab95a.png)
![image](https://user-images.githubusercontent.com/47774278/152479313-07aedbd0-e64f-4487-b459-18f7717c1dad.png)

**Comment by nishsinghal20** [comment]
@prajisha Yes sure, we'll take a look into this. Thank you for your patience!

**Comment by patapizza** [comment]
Hi @prajisha,

The confidence level for the provided inputs is very low. While we do provide the confidence and auto-populate the intent to speed up the annotation, we don't return them under 50% confidence in the API runtime. The 50% confidence threshold would optimize for recall over precision. For higher quality, I encourage you to use the model insights on the intent page to find the best confidence threshold for your use case using precision/recall, and ignore API predictions below that threshold. Most apps should probably use at least a 85% confidence threshold, but again that depends from one product to another one.

Hope this helps.

**Comment by prajisha** [comment]
> 

Hi

 When i tried random inputs via API am getting intents in the response  even if the confidence level is too low.Below are two examples,

wit_response {"_text":"test","entities":{"intent":[{"confidence":0.22642825830761,"value":"tentative"}]},"WARNING":"DEPRECATED","msg_id":"03pVd4dOzh6iurirG"}

wit_response {"text": "xxxx","intents": [{"id": "381104606705616","name": "authenticate","confidence": 0.215}],"entities": {},"traits": {}}

Till earlier last week, we were not getting the intents in response if its confidence level is too low.
The issue seems to occur from thursday.

Thanks

**Comment by patapizza** [comment]
@prajisha Oh indeed. Thanks for reporting. Let me look into this.

**Comment by GuilhermeXlab** [comment]
We have the same issue here..

People names has been identified with "curse" without any correlation.

Client names like "Guilherme" or "Marinalda" have 90% to 99% of confidence.
Equally with randoms: https://api.wit.ai/message?q=adwefaefsdf

Our AppId: 4151339554959163

Thanks!

**Comment by prajisha** [comment]
> @prajisha Oh indeed. Thanks for reporting. Let me look into this.

Hi @patapizza, Do you have any updates on this? This is badly affecting our customers.

**Comment by prajisha** [comment]
> @prajisha Oh indeed. Thanks for reporting. Let me look into this.

Hi @patapizza, Any update on this?

**Comment by doggeral** [comment]
> > @prajisha Oh indeed. Thanks for reporting. Let me look into this.
> 
> Hi @patapizza, Any update on this?

We're working on the fix now. Will keep you updated.

**Comment by prajisha** [comment]
> > > @prajisha Oh indeed. Thanks for reporting. Let me look into this.
> > 
> > 
> > Hi @patapizza, Any update on this?
> 
> We're working on the fix now. Will keep you updated.

Hi @patapizza Any update on this issue? This is badly affecting our customers for more than a week.

**Comment by doggeral** [comment]
@prajisha verified on wit.ai, your issue has been fixed!

**Comment by anjaly** [comment]
Hi @doggeral 

We are currently facing this issue in the following  AppId: 623134488936494.
We are getting intents with high confidence for non trained inputs.

Can you please check.

**Comment by GuilhermeXlab** [comment]
Please, our app have the same issue:
https://api.wit.ai/message?q=marinalda = (99,1% confidence)
Our AppId: 4151339554959163

Thanks!

**Comment by amtdevops** [comment]
> Hi @doggeral
> 
> We are currently facing this issue in the following AppId: 623134488936494. We are getting intents with high confidence for non trained inputs.
> 
> Can you please check.

@doggeral @patapizza Any update on this.

**Comment by anjaly** [comment]
> Hi @doggeral
> 
> We are currently facing this issue in the following AppId: 623134488936494. We are getting intents with high confidence for non trained inputs.
> 
> Can you please check.

@doggeral @patapizza Any update on this.

**Comment by doggeral** [comment]
> 

@GuilhermeXlab @anjaly You can add the the utterance as out of scope and retrain the app.

**Comment by GuilhermeXlab** [comment]
> 


we have already done this for many cases, however, it is impossible to predict all possible words that may be used. every day many phrases are identified as out of scope and categorized, and this behavior is new to us.

All these examples have high confidence without any explanation:

https://api.wit.ai/message?q=ambulancia
https://api.wit.ai/message?q=amendoim
https://api.wit.ai/message?q=mauricio
https://api.wit.ai/message?q=tulio

Our AppId: 4151339554959163

In a restart attempt, we cloned the app and it behaved the same for a while. Soon after the fix announced here, it stopped working sending us the return 500: 
{
	"error": "Something went wrong. We've been notified",
	"code": "unknown"
}

new AppId: 661807068294184
