### ISSUE TITLE
Internal Server Error 500 occasionally

### ISSUE THREAD

**Issue by DekelShabat** [wit-ai/wit#2324]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug

**What is the current behavior?**
Occasionally I get 500 from the server.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I call the message API through Python. See the scenario below:
```
wit_client = Wit(cfg.conf.wit_ai_access_token)
wit_client.message("do u hae a bf? single?")
2022-02-02 12:02:44,452 - program- error_modular - DEBUG - Wit responded with status: 500 (Internal Server Error)
  File "C:\program\src\program.py", line 296, in get_wit_response_if_above_threshold_otherwise_none
    wit_intent = find_highest_confidence_intent(wit_client.message(message))
  File "C:\Python\Python39\lib\site-packages\wit\wit.py", line 69, in message
    resp = req(self.logger, self.access_token, 'GET', '/message', params)
  File "C:\Python\Python39\lib\site-packages\wit\wit.py", line 41, in req
    raise WitError('Wit responded with status: ' + str(rsp.status_code) +
**wit.wit.WitError: Wit responded with status: 500 (Internal Server Error)**
```
**What is the expected behavior?**
Getting the relevant intent
It's usually working. Sometimes I'm getting this 500, I assume there was a downtime or some other issue?

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
3006313322920736

Also, how should I handle these errors? 
Should I encapsulate the calls with try except or go I get a grace with the response code and should just verify the status code?
The documentation doesn't really say anything about response code or format except the posibility to get it in JSON.

Thanks in advance

**Comment by gnovis** [comment]
I have the same issue for several of my apps. I´m using /message endpoint with version 20200513 (from pywit package).

**Comment by nishsinghal20** [comment]
@DekelShabat Thank you for reporting this. From your snippet, the timestamp looks to be `2022-02-02 12:02:44`. Could you confirm the timezone so that I can lookup the logs on our side?

**Comment by nishsinghal20** [comment]
Actually I was able to pull up the logs. It seems like an internal timeout issue which should be a one-off incident, but we'll keep investigating on our side to make the service more robust. Please feel free to open the issue again if this happens consistently.
