### ISSUE TITLE
Internel Server Error when calling `speech`

### ISSUE THREAD

**Issue by zhiyzuo** [wit-ai/wit#2325]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
>When using the speed function, I received a WitError of Internal Server Error
```python
WitError: Wit responded with status: 500 (Internal Server Error)
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
> My code:
```python
token = My_TOKEN
client = Wit(token)
resp = None
with open(MY_WAV_FILE, 'rb') as f:
    resp = client.speech(f, {'Content-Type': 'audio/wav'})
```

**What is the expected behavior?**
> Speech recognition.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
>262386845897320

**Comment by nishsinghal20** [comment]
Hi @zhiyzuo! Thanks for reporting this. Let me investigate and get back to you.

**Comment by nishsinghal20** [comment]
@zhiyzuo are you still experiencing this issue?

**Comment by zhiyzuo** [comment]
@nishsinghal20  Yes, I am still unable to get it work. Is it because of my audio file?
<img width="296" alt="image" src="https://user-images.githubusercontent.com/7501149/153112870-c0c5101a-e30c-492b-9ac2-61f7debfbd26.png">

**Comment by nishsinghal20** [comment]
@zhiyzuo could you try with some other audio file? Also, I looked at the server side logs and I see that sometimes your requests are successful. It's possible that since this audio file is big, there are sometimes issues in uploading it to the server. I'll try to get more information on this.

**Comment by nishsinghal20** [comment]
@zhiyzuo It indeed seems related to your audio file. Per our [documentation](https://wit.ai/docs/http/20210928/#post__speech_link) we enforce a 20 seconds limit on the input audio.

**Comment by zhiyzuo** [comment]
20 seconds seem to be too short for practical application. Is there any workaround to analyze audio data beyond that size limit?


Best,
Zhiya
