### ISSUE TITLE
App Stuck in Training 

### ISSUE THREAD

**Issue by gadielmyron** [wit-ai/wit#2326]
My App is taking huge training time like more than 4-5 hours for a single utterance. 

**AppId**: `1479811922390057`
**AppName**: `bluebirddev`

**Comment by nishsinghal20** [comment]
Hey @gadielmyron! I just checked and the app seems to have finished the training. Are you still experiencing this issue?

**Comment by gadielmyron** [comment]
Hey @nishsinghal20! Yes, I'm experiencing the same issue still. Please check this issue
![image](https://user-images.githubusercontent.com/32515749/152732579-c0db1717-15ea-4c3d-b8e5-015f8b067b1b.png)

**Comment by gadielmyron** [comment]
Is there anyone? I need help because my app will go live soon

**Comment by nishsinghal20** [comment]
@gadielmyron I just kicked-off a forced retrain of your app from my end. Let's see if that fixes the issue.

**Comment by AlexRL** [comment]
I am having the same issue since yesterday: 
AppId: 4773465376078345
AppName: pav_en
Any solution?

**Comment by gadielmyron** [comment]
@nishsinghal20 again It's going to take 24 hours for a single utterance. May I need to talk with Nancy?

**Comment by nishsinghal20** [comment]
@gadielmyron Can you help me understand your issue? Are you noticing that your training is getting scheduled after a long time? Or is it that your training starts but takes a long time to finish? From my end, it seems your training finished at 02/08/22 06:27:46 AM PST. Also Nancy is no longer with the team. We'll try our best to get your issue resolved.

@AlexRL could you please also explain your issue?

**Comment by AlexRL** [comment]
@gadielmyron, if I add any new utterance or I modify an existing one, i noticed that the training process will be scheduled after 12 hours, which is a lot of time. In my other apps the training process is almost instantly (within a minute or few). I was wondering if there is a problem with the current app (AppId: 4773465376078345) or if I can do anything to make the waiting time for the training process shorter? Thank you for your help.

**Comment by nishsinghal20** [comment]
@AlexRL Thank you for the context! Let me look into that and get back to you. @gadielmyron Can you confirm if the issue you're seeing is the same as Alex mentioned above?

**Comment by gadielmyron** [comment]
@nishsinghal20 yes, I'm facing the same issue. Here, I shared a snapshot below. My time is Wednesday 12:08 PM but the app is scheduled for a single utterance training on Thursday at 12:05 AM. 
![image](https://user-images.githubusercontent.com/32515749/153131973-2c01896e-c61b-4f6d-8a62-c51c117b8f08.png)

**Comment by AnabelleG** [comment]
Hi all. I have the same issue as the above reported.

App ID: 542373750414845

App Name: ALCOM


App is scheduled to train 11 hours later:

![image](https://user-images.githubusercontent.com/99320425/153156041-dfd887f5-a2f3-4a7b-8ac0-155b8d71dc61.png)

**Comment by AnabelleG** [comment]
Can anyone please help as I need to train the app till today. Or can guide me on how to force retrain the app?

**Comment by nishsinghal20** [comment]
@AlexRL and @AnabelleG I've manually triggered training of your apps. @gadielmyron we're still investigating the issue as to why the training is taking so long to schedule. Thank you for your patience!

**Comment by AnabelleG** [comment]
It's training now. Thanks

**Comment by AlexRL** [comment]
@nishsinghal20, I added now a new utterance and the waiting time for the training process is around 30 minutes which is a reasonable time. Thank you a lot for your help.

**Comment by gadielmyron** [comment]
@nishsinghal20 thank you for your help. right now the app is taking utterance data for training but take around 15-20 minutes.

**Comment by AnabelleG** [comment]
I added an entity and it gave me 2 hours waiting time to train :/
