### ISSUE TITLE
trained utterances giving wrong intent 

### ISSUE THREAD

**Issue by shorouqmajali** [wit-ai/wit#2328]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
many utterances were trained to a specific intents , but now the response in understanding is wrong and we are unable to traine them again
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
the utterance "حجز موعد تجربة سيارة" should trigger the intent => testDrive , but we have no response 
**What is the expected behavior?**
"حجز موعد تجربة سيارة"  is  utterance for testDrive 
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
580041809784935

**Comment by nishsinghal20** [comment]
Hey @shorouqmajali! It seems that many of your training utterances are also marked as out of scope. For example "حجز موعد اختبار سياقة" is marked as "testdrive" as well as out of scope. If an utterance is marked as out of scope, the models will just predict them as out of scope. Could you try to fix the training data and label the utterances with appropriate intents?
