### ISSUE TITLE
Intent is not recognized on understanding page after import Zip data

### ISSUE THREAD

**Issue by Chejin-cheol** [wit-ai/wit#2329]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
I exported zip data, 
and did import data to another app.
when train is completed,
all factor (Intents, Trait, Entities, Utterances, Settings) is successfully initialized.
but, when I add new utterance to Understanding page
app cannot recognize only intent that are registered from zip data 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
first, create new app and import existed zip data
second, after training completed, I test app through new utterance 
third, not recognize intent only

**What is the expected behavior?**
detect intent from trained data

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
app ID: 693263904996418

**Comment by nishsinghal20** [comment]
Hi @Chejin-cheol! Our apologies for the late response. Are you still seeing this issue? I tried to repro this on my end and it seems to be working okay. Please let us know if you still have this issue.

**Comment by Chejin-cheol** [comment]
![image](https://user-images.githubusercontent.com/41323651/157570434-2d035a28-c467-4c48-9deb-6c26bff6dc50.png)

yet..  utterance page cannot detect intent keyword. 
"조회" is intent keyword
but it is only [choose or add intent]

Should i retrain passive all utterances to detect intents ?

**Comment by nishsinghal20** [comment]
@Chejin-cheol yes please try re-training those utterances. That should fix this issue.
