### ISSUE TITLE
Inconsistent web console

### ISSUE THREAD

**Issue by kampta** [wit-ai/wit#233]
Had lots of trouble using web console (while defining/training entities).
I have an `entity` called `intent` which uses **trait** as `search-strategy`. It should be able to take one of the five values - `[thanks, greeting, search, farewell, boo]`

But while adding/training the entities,  web interface shows multiple-occurrences of same value.

![screenshot from 2016-05-30 18 07 51](https://cloud.githubusercontent.com/assets/1719140/15649941/db8f5f4e-2692-11e6-9ce7-18e612f3fc60.png)

![screenshot from 2016-05-30 18 08 17](https://cloud.githubusercontent.com/assets/1719140/15649961/fa7d2bf2-2692-11e6-8fcd-a0eacb6f1f4d.png)

However, if I go to the entity page, it shows only 5 values for `intent`.
![screenshot from 2016-05-30 18 08 28](https://cloud.githubusercontent.com/assets/1719140/15650020/47df3890-2693-11e6-9177-d5ac73cae1b0.png)

I am not sure if it's an issue or my understanding of `entity` is wrong.
Posting here in case anyone else went through the same.

**Comment by howawong** [comment]
![image](https://cloud.githubusercontent.com/assets/760880/15651958/756c0438-26b5-11e6-873a-e3d25a39a5d2.png)

Same here, failed to save / update stories.

**Comment by jhoelzl** [comment]
same here, the UI is very slow and buggy today...

**Comment by gil13** [comment]
The platform is not working well since last friday, I lost all my morning work and nobody reply the chat  assistance.

**Comment by avinash8526** [comment]
yes wit crew replied that , they are facing some tech issue at their end. Not sure how long it will take to fix

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
