### ISSUE TITLE
My app is scheduled to train After 3 hours

### ISSUE THREAD

**Issue by SarahAabid** [wit-ai/wit#2330]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?
I added a story and tried to train wit.ai for the same, but the training scheduled after 3 hours

**What is the current behavior? App is stuck in "Training scheduled".

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
Open the app. Wait until the app is done training.

**What is the expected behavior?
App is expected to finish Training scheduled in some time.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.
408965087275379

**Comment by nishsinghal20** [comment]
Hi @SarahAabid! On my end, it shows that all training jobs for app ID 408965087275379 have already finished. Are you not seeing "Training Finished" on your end?

**Comment by nishsinghal20** [comment]
I'll go ahead and close this issue for now. Please feel free to re-open it in case your app is having issues with training.
