### ISSUE TITLE
Utterances not shown at UI

### ISSUE THREAD

**Issue by gnovis** [wit-ai/wit#2331]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
Utterances send from the API are not shown at UI (below Train Your App heading).
![2](https://user-images.githubusercontent.com/4740230/152963406-4484a90f-896b-481f-ae4a-8ccf7ca01c51.png)

**What is the expected behavior?**
Show send utterances at UI.
![1](https://user-images.githubusercontent.com/4740230/152963466-3ba648aa-e1b8-4e81-b4f4-6a2bb74c0225.png)

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
656371248845039
149912677149347
496850848334298
576653509713419
1219919261725943

**Comment by dogcalas** [comment]
Same problem.

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
