### ISSUE TITLE
"error":"Something went wrong. We've been notified","code":"unknown"

### ISSUE THREAD

**Issue by Arjen-Houweling** [wit-ai/wit#2333]
im am getting {"error":"Something went wrong. We've been notified","code":"unknown"} on every API request
everything worked fine yesterday. 

Error occures every api call on AppID 150571963614026 and AppID 642589933740604

**Comment by kamil-spletsteser** [comment]
Same here, Facebook support does not respond on opened bug...

**Comment by ViktorSchroeder** [comment]
I also get this message very often and have additionally bad response times. #2418

**Comment by chijete** [comment]
I have the same problem now, after having the "training ongoing indefinitely" problem...
{error: "Something went wrong. We've been notified", code: 'unknown'}

**Comment by doggeral** [comment]
Let's track the issue in the thread https://github.com/wit-ai/wit/issues/2418
