### ISSUE TITLE
Entity picks up on more keywords than there actually are in the entity even though the type is keyword

### ISSUE THREAD

**Issue by aya-labiba** [wit-ai/wit#2334]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
entity picks up on more keywords than there actually are in the entity even though the type is keyword

![image](https://user-images.githubusercontent.com/99329638/153191267-0df61c5e-3240-483a-b2d9-69eab29280b1.png)

![image](https://user-images.githubusercontent.com/99329638/153191299-6fb62327-abe5-4912-ad8b-b0b55eae0a77.png)

![image](https://user-images.githubusercontent.com/99329638/153191331-844baf5e-0f32-44a3-8744-3fe0a834277c.png)

response returned from message API:
[Message API response.txt](https://github.com/wit-ai/wit/files/8032192/Message.API.response.txt)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Send the following: 
هل تكتفي الجهة المتعاقدة من المورد بتوريد المبلغ للهيئة أو هناك نموذج أو ايميل أو شخص يجب التواصل معه وتزويده بنسخة من أمر الدفع والمشروع؟

**What is the expected behavior?**
There should be only one entity picked up on which is "person" and the keyword to be شخص

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

App ID: 348182026969043

**Comment by doggeral** [comment]
Same issue with https://github.com/wit-ai/wit/issues/2341, will close the issue and track it on https://github.com/wit-ai/wit/issues/2341
