### ISSUE TITLE
App stopped picking up on entities that are already trained in the App and started returning them as suggestions

### ISSUE THREAD

**Issue by aya-labiba** [wit-ai/wit#2335]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
The NLP stopped picking up on entities that are already trained in the App and started returning them as suggestions

![image](https://user-images.githubusercontent.com/99329638/153192992-5545d0e2-9c9d-4ee6-8b6e-9eacf191b3a5.png)

Sample responses:
[Message API response 1.txt](https://github.com/wit-ai/wit/files/8032314/Message.API.response.1.txt)

[Message API response 2.txt](https://github.com/wit-ai/wit/files/8032315/Message.API.response.2.txt)

[Message API response 3.txt](https://github.com/wit-ai/wit/files/8032316/Message.API.response.3.txt)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

send the following:

App ID (1532251193629758) : ماهي الفاتوره الالكترونيه

**What is the expected behavior?**
Pick up on relevant entities, entities not be suggested

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

App IDs:
1532251193629758
540306813916111
333179811665805

**Comment by doggeral** [comment]
Seems like you have the n-best setting in you input parameter. Try to remove the setting for querying the endpoint. https://wit.ai/docs/http/20210928/

**Comment by aya-labiba** [comment]
Hi @doggeral, n-best input parameter was removed from the request but that didn't solve the issue, entities are still returned as 'suggested'

Response without 'n' parameter: 
[without 'n' parameter.txt](https://github.com/wit-ai/wit/files/8109338/without.n.parameter.txt)

Response with 'n' parameter:
[with 'n' parameter.txt](https://github.com/wit-ai/wit/files/8109339/with.n.parameter.txt)
