### ISSUE TITLE
The app picks up on synonyms of a keyword in an entity as a keyword with confidence 100%

### ISSUE THREAD

**Issue by aya-labiba** [wit-ai/wit#2336]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
The app picks up on synonyms of a keyword in an entity as a keyword with confidence 100%

![image](https://user-images.githubusercontent.com/99329638/153194372-fa4ab18f-4c8c-4c33-b022-e3188e474fd9.png)

Message API response:
[Message API response.txt](https://github.com/wit-ai/wit/files/8032376/Message.API.response.txt)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Send: من وين ادخال مشتريات / مبيعات

**What is the expected behavior?**
Only pick up on  keyword  "المبيعات"

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

App ID: 303451605153947

**Comment by doggeral** [comment]
The same issue has been reported https://github.com/wit-ai/wit/issues/2341 
Closed the issue to de-duplicate.
