### ISSUE TITLE
Expression detraining

### ISSUE THREAD

**Issue by aya-labiba** [wit-ai/wit#2337]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
When an expression is detrained, the detrained intent is sometimes being understood and sometimes not

on 1/28/2022 15:44: 
[Top 10 scoring intents 1.txt](https://github.com/wit-ai/wit/files/8033195/Top.10.scoring.intents.1.txt)

![image](https://user-images.githubusercontent.com/99329638/153214795-2732fe64-f93d-40da-a958-0a6358d9c8ee.png)

on 1/30/2022 12:55:
[Top 10 scoring intents 2.txt](https://github.com/wit-ai/wit/files/8033197/Top.10.scoring.intents.2.txt)

![image](https://user-images.githubusercontent.com/99329638/153214876-8a4f3769-88b6-4486-b67e-014bf16be759.png)

**What is the expected behavior?**
To detrain and not understand the intent

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

App ID: 1532251193629758

**Comment by doggeral** [comment]
We've fixed the issue, low confidence intent will be discarded.
