### ISSUE TITLE
App Stuck in Training

### ISSUE THREAD

**Issue by AseelHamamreh** [wit-ai/wit#2339]
My App is taking huge training time like more than 4-5 hours for a single utterance.

AppId: 282001570685460
AppName: samacoprod2

**Comment by Scordium** [comment]
Same issue here. App has been stuck for at least 2 hours and utterances stopped showing up.

AppId: 481738333540629

**Comment by doggeral** [comment]
Your app has been fixed!

**Comment by juancvas** [comment]
Same issue with my app
It is taking huge training time like more than 24 hours for single utterance or entity.

AppId: 407022797877055
AppName: chatbot_boston_scientific
