### ISSUE TITLE
Wit website a little bit strange

### ISSUE THREAD

**Issue by fabiomlferreira** [wit-ai/wit#234]
Since today my test bot stop working well an on the wit.ai website I get thinks like this:
![image](https://cloud.githubusercontent.com/assets/1872297/15718152/f5b39f08-2821-11e6-96ba-003e62c7fa56.png)

**Comment by l5t** [comment]
thanks for reporting. We are investigating now

**Comment by avinash8526** [comment]
+1 for this issue

**Comment by l5t** [comment]
Hi @avinash8526  it seems you have another issue. I checked and your app will need more training. I recommend to create an entity called intent and to validate a few expressions in the Understanding tab related to the value "greetings"

**Comment by stddd** [comment]
+1 for issue, intent entity problem with conflicts
