### ISSUE TITLE
Entity not detected

### ISSUE THREAD

**Issue by aya-labiba** [wit-ai/wit#2340]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
When sending "Invoice" with capital 'I', the correct entity is detected. Otherwise wrong entity is returned.

Message API result with capital 'I':
[Captal 'I'.txt](https://github.com/wit-ai/wit/files/8039844/Captal.I.txt)

Message API result with small 'i':
[Small 'i'.txt](https://github.com/wit-ai/wit/files/8039847/Small.i.txt)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Send 'Invoice' with capital 'I' (correct entity detected), then send 'invoice' with small 'i' (wrong entity detected)

**What is the expected behavior?**
The correct entity to be detected whether the letters are capital or small 

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID:  369624867975093

**Comment by doggeral** [comment]
Refresh the model, your issue has been fixed.
