### ISSUE TITLE
Non-existing keyword returned

### ISSUE THREAD

**Issue by aya-labiba** [wit-ai/wit#2341]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
Keywords are being returned within entities even though they are not defined as keywords.
Example: when sending 'بدي أسافر' the word 'أسافر ' is being understood as a keyword in the entity 'InsuranceTypeAR' although it is not a defined keyword and is a synonym for the keyword تأمين سفر

Message API sample response: 
[response.txt](https://github.com/wit-ai/wit/files/8040463/response.txt)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Send 'بدي أسافر'

**What is the expected behavior?**
Not to return keywords within entities that are not defined as keywords. 

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID: 2839573536265870

**Comment by doggeral** [comment]
Thanks for reporting the issue. The machine learning model has the generalization capability to understand the synonym. Could you help to share more context why you don't hope to recognize the synonym as entity?

**Comment by patapizza** [comment]
@doggeral Here [`InsuranceTypeAR`](https://wit.ai/apps/2839573536265870/entities/350081036172478) is a keywords-only entity, so it should strictly recognize the set of provided keywords and synonyms.

<img width="636" alt="Screen Shot 2022-02-11 at 8 25 22 AM" src="https://user-images.githubusercontent.com/1015208/153629416-2ff4d367-e611-41c7-95fa-d8363dd9cdbb.png">

**Comment by doggeral** [comment]
The issue has been fixed. For the keyword-only parser, won't return the free text entity.
