### ISSUE TITLE
Issue with triggering intent for non trained input

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2343]
Hi

We are facing an issue with the Khmer wit workspace.

When i tried random inputs which are not trained in workspace via API, I am getting the intent and its confidence level above 90%. 
As we have not trained this input we expect to return no intent. Till earlier two weeks, we were not getting any intents for this input.

Below is an example response from the api,
 {"_text":"ទីតាំងកំណើត បុរីកីឡា សង្កាត់វាលវង់ ខណ្ឌ ៧មករា អគារទី ៧ ជាន់ទី៥","entities":{"intent":[{"confidence":0.99360610804149,"value":"static_intent_office_location"}],"number":[{"confidence":1,"type":"value","value":7},{"confidence":1,"type":"value","value":7},{"confidence":1,"type":"value","value":5}]},"WARNING":"DEPRECATED","msg_id":"0U1scObSAY19jrw0b"}

Can you please look into the issue with high priority, as it is affecting our business.

Our AppId is 555590445502765

![image](https://user-images.githubusercontent.com/601711/153405648-17ef0fb3-a871-400a-a51e-9c1003bd95c1.png)
![image](https://user-images.githubusercontent.com/601711/153405782-fa30bc19-7533-433d-9446-27a701cc63dd.png)

Thanks

**Comment by doggeral** [comment]
Thanks for reporting the issue. You can add the "Out of Scope" utterance and retrain your app. I've added it for you.
![image](https://user-images.githubusercontent.com/1651153/153471698-54ee60a3-9bb2-4ba1-b5e7-07a5ce4b2eea.png)

**Comment by anjaly** [comment]
> Thanks for reporting the issue. You can add the "Out of Scope" utterance and retrain your app. I've added it for you. ![image](https://user-images.githubusercontent.com/1651153/153471698-54ee60a3-9bb2-4ba1-b5e7-07a5ce4b2eea.png)

Here the bot expecting an address from user, so user can type any address. If i add this input as "Out of Scope" it will work, but when user type a new address it will trigger the "static_intent_office_location" intent. We can't predict all the address. So can i get a proper solution for this?
