### ISSUE TITLE
App stuck in training 

### ISSUE THREAD

**Issue by RagadZuaiter** [wit-ai/wit#2344]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question

**What is the current behavior?**
Our app seems to be stuck in training mode for the past 3 hours , its stuck in "Training status: ongoing". 

**What is the expected behavior?**
Training should've finished by now.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
AppId: 481886623380793
AppName: nathealth_ar_newnew

**Comment by francovp** [comment]
Same here, maybe it's an internal issue
ApddId: 690457341626148

**Comment by doggeral** [comment]
@francovp @RagadZuaiter  your issues have been fixed.
