### ISSUE TITLE
Wrong intent detected

### ISSUE THREAD

**Issue by aya-labiba** [wit-ai/wit#2345]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
When sending a random expression with no meaning that should not be understood, a wrong intent is being detected
Example: When sending 'شسيبلا', 'Assistance_and_Help_AR' intent is being detected, which is wrong.

[response.txt](https://github.com/wit-ai/wit/files/8042033/response.txt)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

The expression to not be understood

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App id:  1682759491848662

**Comment by doggeral** [comment]
I've added it as the "out of scope" sample and retrain the app. It should fix your issue.
