### ISSUE TITLE
App Stuck at Training

### ISSUE THREAD

**Issue by gadielmyron** [wit-ai/wit#2347]
Is there anyone here, I need emergency help. 4 Days ago one of wit team members helped me with Utterances training stuck. Again, my app is stuck on Training. Check out the below snapshot.

**App ID**:  1479811922390057

![image](https://user-images.githubusercontent.com/32515749/153748607-30a9c636-be15-4500-8c87-5b34f000c4d1.png)

**Comment by doggeral** [comment]
Thanks for reporting the issue, your app has been fixed.
