### ISSUE TITLE
Speech recognition is not working 

### ISSUE THREAD

**Issue by SisikHBS** [wit-ai/wit#2348]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
Almost 50% of speech recognition requests fails and returns this: {'code': 'wit', 'error': 'An error occurred in speech recognition.'}
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Just try speech recognition it is either returning half of the text or returns error.
**What is the expected behavior?**
It should return the text.
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1778ea57-fcef-4d8d-a921-5bbc1aeb9297

**Comment by SisikHBS** [comment]
I believe you have changed the speech recognition algorithm the current algorithm is much worse than the previous one, and it is unusable, do you plan to go back to the previous version?

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
