### ISSUE TITLE
Transfer Ownership of App

### ISSUE THREAD

**Issue by MilesWen** [wit-ai/wit#235]
Is there a way to transfer the ownership of a Wit App to another user? One of my teammate left recently and he would love to transfer the Wit App he developed to one of the remaining team member. We could not find the option for transfer anywhere on the web console or in the API documentation.

**Comment by l5t** [comment]
Please contact us at help@wit.ai with your app id and the new owner

**Comment by blandinw** [comment]
We did add this feature in the Settings page of your app

**Comment by l5t** [comment]
and we are updating the docs
![image](https://user-images.githubusercontent.com/6992759/30657461-883f74a0-9dec-11e7-8875-b19037a9d9d0.png)
