### ISSUE TITLE
App stuck

### ISSUE THREAD

**Issue by RagadZuaiter** [wit-ai/wit#2352]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question
**What is the current behavior?**
Our app seems to be stuck in training mode for the past 1 days , its stuck in "Training status: ongoing".

**What is the expected behavior?**
Training should've finished by now.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
AppId: 316307847182568
AppName: gig_newapp_en

and 

AppId: 295546689227570
AppName: gig_newapp_ar

**Comment by wangzhenict** [comment]
investigating. will update soon.

**Comment by wangzhenict** [comment]
I forced a retrain for it. and now its status is done from my side. can you check if you are unblocked. Thanks for your patience!

**Comment by doggeral** [comment]
Verified on wit.ai, the issue has been fixed!
