### ISSUE TITLE
Utterances are not showing at all

### ISSUE THREAD

**Issue by zyinshi** [wit-ai/wit#2353]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
Utterances are not showing at all
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
https://wit.ai/apps/1850213565053139/utterances
![Screen Shot 2022-02-15 at 9 28 22 AM](https://user-images.githubusercontent.com/6267828/154116713-12a75e70-c6b9-4be9-b071-e76f0195a4c8.png)

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1850213565053139

**Comment by wangzhenict** [comment]
Hi @zyinshi , 
I applied a fix on it. it looks good to me now. can you double confirm if the issue is addressed?
Thanks for your patience!
