### ISSUE TITLE
No Intents Identified

### ISSUE THREAD

**Issue by BSimmelink** [wit-ai/wit#2354]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a Bug.

**What is the current behavior?**
All previously trained Intents are now resulting in 0 confidence, regardless of the text provided. This occurs when using the GET /message HTTP endpoint. As well as when entering an utterance in the understanding page of the Wit.AI UI. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Perform GET request to the /message endpoint on versions 20170307 and 20210928. (such as "what is the shipping?")
2. View the response

OR
1. Navigate to the understanding page
2. Enter an utterance that has previously had degree of confidence (such as "what is the shipping?")
3. Note no intent is suggested.

**What is the expected behavior?**
When entering a commonly used utterance, an intent is expected. Currently returning no intents with any confidence, regardless of the utterance. 

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
4264576556935373

**Comment by doggeral** [comment]
Your issue has been fixed!
