### ISSUE TITLE
App stuck in training

### ISSUE THREAD

**Issue by M3Z47** [wit-ai/wit#2355]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question

**What is the current behavior?**
App has been stuck in training for the past 6 days

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Not a bug

**What is the expected behavior?**
It shouldn't take this much time to train continuously

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID: 6924265890981719
App name: prod_final_new

Kindly look into the issue. Thanks.

**Comment by wangzhenict** [comment]
Hi @M3Z47 , 

I just unblocked it, it seems done from my side. can you double confirm if you are unblocked.

Thanks for your patience!

**Comment by M3Z47** [comment]
Hello, thanks @wangzhenict  for super fast response!

Yes, it shows training completed. But what was the reason for it getting stuck? Also, it adds gibberish synonyms to keywords a lot during training. (e.g. er, ler etc for bowler), is it normal? And what should I do to stop such additions impacting the training?

Thanks again!

**Comment by doggeral** [comment]
@M3Z47
> But what was the reason for it getting stuck?

It seems that your app was imported 02/06. We upgraded the training system recently, there maybe some transient issues during the upgrade. 

> it adds gibberish synonyms to keywords a lot during training

What do you mean? You mean some new utterance was added into the training data? The training data is fully controlled by app developers, the model training just pick the training utterance and feed into our training system.

**Comment by AlexisNichel** [comment]
same here plz helpme, app id = 1856185531061946

**Comment by wangzhenict** [comment]
> same here plz helpme, app id = 1856185531061946

already unblocked it. it is done.

**Comment by M3Z47** [comment]
@wangzhenict @doggeral 
I re-confirmed this issue. Whenever I train by posting utterances, it adds gibberish values by itself to synonyms. Right now, it added "a" for player asad-ali-rehemtulla-83716, similarly it added "in" for another player which had "in" in its surname. I had to write a code to remove some of the patterned gibberish values after every training is done.
Please look into it. I can give all the ~26000 utterances that I have trained for this app.
Thanks.
