### ISSUE TITLE
App in infinite traning

### ISSUE THREAD

**Issue by AlexandreRgx** [wit-ai/wit#2356]
Do you want to request a feature, report a bug, or ask a question about wit?
Question

What is the current behavior?
App has been stuck in training for the past 1 day

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
Not a bug

What is the expected behavior?
It shouldn't take this much time to train continuously

If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.
App ID:  1154503718388969
App name: prod_smalltalk

Kindly look into the issue. Thanks.

**Comment by doggeral** [comment]
Retrain your app, I think your issue will be fixed.

**Comment by AlexandreRgx** [comment]
Hi @doggeral 
Thanks for your reply, but my app is still stuck after retraining (for 7 days now).
