### ISSUE TITLE
App stucked at training and api returning errors

### ISSUE THREAD

**Issue by ristomoilanen** [wit-ai/wit#2359]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
Our app is infitinely training and api is returing errors:  "Something went wrong. We've been notified"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
training shoudl work and api returning detected intents

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
418025925910798

**Comment by doggeral** [comment]
Our system shows the training is successful, we need to investigate why the UI has the inconsistent behavior.

**Comment by doggeral** [comment]
Retain your app and the issue was fixed.

**Comment by ristomoilanen** [comment]
Everything seem to be ok now, thank you!
