### ISSUE TITLE
Group stories in the console

### ISSUE THREAD

**Issue by giorgosera** [wit-ai/wit#236]
In order to keep everything tidy and organized it'd be useful if we could group stories in the console. 

Let's take for example a bot created for a company that has many products. A set of stories could pertain to product A while another set to product B. 

After some point it can become tedious to search through a long list of stories to find the one(s) you need to inspect/change etc.

This is purely a UX improvement for the people who create and maintain the stories.

**Comment by jhoelzl** [comment]
+1

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
