### ISSUE TITLE
What is the NLP architecture used by Wit?

### ISSUE THREAD

**Issue by pereirarodrigo** [wit-ai/wit#2361]
Hello there,

Some questions have arisen in my team regarding what kind of NLP architecture is used by the platform. Is this a publicly available information? Furthermore, does the platform use a language model on transcription results?

**Comment by doggeral** [comment]
@pereirarodrigo  thanks for your interest in the wit.ai model. 
> NLP architecture 

The model is based on encoder-decoder architecture. The encoder layer is built on top of the [XLM-R](https://arxiv.org/pdf/1911.02116.pdf) model, and the decoder layer is the MLP. 

> Does the platform use a language model on transcription results?

Yes.
