### ISSUE TITLE
Wrong entities and keywords detected

### ISSUE THREAD

**Issue by aya-labiba** [wit-ai/wit#2364]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
The result is returning wrong entities and keywords.
Keywords are being returned in Arabic, where all the trained keywords are in English and their synonyms are in Arabic.

Example: When sending 'طبيب اسنان في عمان', the entity 'HCP_type' is returned for the value: "ب اسنان", where the entity should be "speciality_Ar" for 'اسنان' and 'HCP_type' for  "طبيب".
Also, in Cities entity, the keyword 'عمان' is returned in Arabic, where the actual key word is 'amman', and 'عمان' is a synonym of 'amman'

API Response: 
[Response.txt](https://github.com/wit-ai/wit/files/8087125/Response.txt)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Send 'طبيب اسنان في عمان'

**What is the expected behavior?**
To return correct entities and keywords as trained in the app

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
Apps IDs:
315538893568231
333179811665805

**Comment by doggeral** [comment]
you have conflict annotation in your training sample, please fix the annotation issue first, then retrain your model. 
<img width="877" alt="image" src="https://user-images.githubusercontent.com/1651153/154538916-88e74509-7e31-4088-bc5c-1be88c74ceef.png">
