### ISSUE TITLE
Speech API returning "Bad auth, check token/params"

### ISSUE THREAD

**Issue by dzwiedzmin** [wit-ai/wit#2365]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

Bug.

**What is the current behavior?**

All requests are rejected with 
{
  "code": "no-auth",
  "error": "Bad auth, check token/params"
}

but only to the Speech API, other functions seem to work as expected

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

curl -XPOST  "https://api.wit.ai/speech?v=20220217" -i -L -H "Authorization: Bearer <TOKEN>" -H "Content-Type: audio/wav" --data-binary @sample.wav

**What is the expected behavior?**

Should work.

**Comment by patapizza** [comment]
Hi,

Thanks for reporting. We had a bad deployment, we're reverting.

**Comment by Mirkoddd** [comment]
I was about to report it, but I see it was already reported. Thanks to OP.
Edit: is working fine now 👍

**Comment by patapizza** [comment]
We're fully back now. Sorry again about the inconvenience.
