### ISSUE TITLE
intent from postman and the one shown in the understanding differs & training issues.

### ISSUE THREAD

**Issue by RadhikaPallavi** [wit-ai/wit#2366]
When we try to type in the question in the understanding for the Wit App, it show some random Intent. However they are not correct or trained. However when we try to run the URL from the Post man it does not return intent(as it should be).
Also there are some gibberish text entered which displays and return the intent on both the app and the postman. Could you please help us with these cases in three apps happening randomly, may be not for all questions:

The App IDs are : 618389522541052, 4926118934078909 & 572046700564927.

Please find the image attached for reference.
**1. Wrong Intent for Gibberish**
![image](https://user-images.githubusercontent.com/97292380/154705902-789774b3-b12f-43ca-b53c-dfcf1d7c0d8a.png)
![image](https://user-images.githubusercontent.com/97292380/154705931-c017f27f-fca6-4cd9-8fba-9c643978259f.png)

**2. Different Intent for the Question in Wit App & the Postman**
![image](https://user-images.githubusercontent.com/97292380/154706033-312d0622-6d46-4d9d-a5e1-9e9c19df9e0f.png)
![image](https://user-images.githubusercontent.com/97292380/154706073-908e03fe-e21e-4f0a-a857-21462956ba06.png)

**3. No Intent Question displays the Intent on the App but not on Postman.**
![image](https://user-images.githubusercontent.com/97292380/154706343-b27b2281-6549-4e33-a404-553bd7ca9ee6.png)
![image](https://user-images.githubusercontent.com/97292380/154706359-cb2d557e-5785-4871-a2ab-ad70fe2a6d30.png)

Kindly help and guide on the same please!

**Comment by wangzhenict** [comment]
Hi @RadhikaPallavi ,
this issue is because the app doesn't have enough training data, you can add more data and retrain the model and then check if it get better. 
also you can use "out of scope" feature for less training data situation.

**Comment by doggeral** [comment]
> 1. Wrong Intent for Gibberish

As wangzhenict mentioned, there are not enough [Out_Of_Scope] utterances. Once the model trained, it may biased for the intents provided by training sample and hard to recognize the pattern for out of domain input. You can try to add some Out_Of_Scope samples for the fix.

> 2. Different Intent for the Question in Wit App & the Postman

Please take the CURL response as the authorities for the model output. The reason you might see the difference is when you type your testing utterance from inbox, the model response might not reflected on UI timely. E.g. you input ABCDEF, the UI might show the response for ABCD once you just finish the typing.

> 3. No Intent Question displays the Intent on the App but not on Postman.

Same reason with 2.

**Comment by RadhikaPallavi** [comment]
@wangzhenict & @doggeral - thankyou for your inputs. This helps a lot!!
