### ISSUE TITLE
Ongoing issue 100% confidence and 500 errors

### ISSUE THREAD

**Issue by CannonFodderr** [wit-ai/wit#2367]
https://github.com/wit-ai/wit/issues/2363 was closed before we could confirm.

@doggeral after checking the apps only one of them is now fixed: 1184234872397015

The rest of the apps are still malfunctioning:

978810119619693
233334358781880
271386008408980
651606172847922
987727735495683
286268900241585
1292133577973221

plus customer created 2 new apps which also gets these issues:

353659586134377
321292556446914

**Comment by doggeral** [comment]
@CannonFodderr could you elaborate your issues? I verified on these apps, looks good to me.

**Comment by CannonFodderr** [comment]
@doggeral 
I.e. in both App ids: 271386008408980 and 651606172847922, utterance "Hello world" is out of scope, but message with "Hello world" will return the intent with high confidence.

![Capture](https://user-images.githubusercontent.com/36086310/155091924-7d7672c3-388a-4a48-bff4-db92d5c847f3.PNG)
![Capture2](https://user-images.githubusercontent.com/36086310/155091993-f4e5fd08-2c63-447f-ab65-ded0ea0fe0e4.PNG)

**Comment by doggeral** [comment]
Retrain your app, verified on wit.ai, the issue has been fixed!
