### ISSUE TITLE
Error just after "Posting speech to http"

### ISSUE THREAD

**Issue by berniedb** [wit-ai/wit#237]
I'm using [this code sample code](https://github.com/wit-ai/wit-android-eval) to try making a cool app for myself and when i try running it in my device, a motorola moto g 3rd gen (in debug mode), i get this error in my log:

`06-07 12:28:09.060 22317-22693/ai.wit.eval.wit_eval E/AndroidRuntime: FATAL EXCEPTION: Thread-24978
                                                                      Process: ai.wit.eval.wit_eval, PID: 22317
                                                                      java.lang.ArrayIndexOutOfBoundsException: length=12800; index=12800
                                                                          at ai.wit.sdk.WitMic$SamplesReaderThread.short2byte(WitMic.java:227)
                                                                          at ai.wit.sdk.WitMic$SamplesReaderThread.run(WitMic.java:207)
06-07 12:28:09.209 22317-22523/ai.wit.eval.wit_eval E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb860c120`

When i imported the project code to my android studio (android studio 2.0) i updated the project's gradle dependenced as requested by android studio.
Here's full log:
`06-07 12:28:02.630 22317-22317/ai.wit.eval.wit_eval I/art: Late-enabling -Xcheck:jni
06-07 12:28:03.936 22317-22523/ai.wit.eval.wit_eval D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
06-07 12:28:03.988 22317-22523/ai.wit.eval.wit_eval I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build:  (I14a17c7611)
                                                                  OpenGL ES Shader Compiler Version: XE031.06.00.02
                                                                  Build Date: 12/04/15 Fri
                                                                  Local Branch: workspace
                                                                  Remote Branch: 
                                                                  Local Patches: 
                                                                  Reconstruct Branch: 
06-07 12:28:03.989 22317-22523/ai.wit.eval.wit_eval I/OpenGLRenderer: Initialized EGL, version 1.4
06-07 12:28:08.183 22317-22317/ai.wit.eval.wit_eval D/ai.wit.sdk.Wit: streamRawAudio started.
06-07 12:28:08.188 22317-22694/ai.wit.eval.wit_eval D/Wit: Requesting SPEECH ....audio/raw;encoding=signed-integer;bits=16;rate=16000;endian=little
06-07 12:28:08.220 22317-22694/ai.wit.eval.wit_eval D/Wit: Posting speech to https://api.wit.ai/speech?v=20141022&context=%7B%22reference_time%22%3A%222016-06-07T12%3A28Z%22%7D
06-07 12:28:09.060 22317-22693/ai.wit.eval.wit_eval E/AndroidRuntime: FATAL EXCEPTION: Thread-24978
                                                                      Process: ai.wit.eval.wit_eval, PID: 22317
                                                                      java.lang.ArrayIndexOutOfBoundsException: length=12800; index=12800
                                                                          at ai.wit.sdk.WitMic$SamplesReaderThread.short2byte(WitMic.java:227)
                                                                          at ai.wit.sdk.WitMic$SamplesReaderThread.run(WitMic.java:207)
06-07 12:28:09.209 22317-22523/ai.wit.eval.wit_eval E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb860c120
06-07 12:28:11.855 22317-22693/ai.wit.eval.wit_eval I/Process: Sending signal. PID: 22317 SIG: 9
`
A friend of mine who's using android studio 1.2 can make it work

**Comment by UrmiBhanani** [comment]
@berniedb : Did you get any solution for above issue?

**Comment by blandinw** [comment]
The code sample provided there is from > 3 years ago and Android evolved quite a bit since then.
We don't have Android engineers with enough bandwidth to fix it, but we'll gladly accept pull request @ https://github.com/wit-ai/wit-android-eval
