### ISSUE TITLE
Requesting you to kindly let me know if I can extend the utterance for training the dataset or let me know if there is any paid version.

### ISSUE THREAD

**Issue by Ananyag02** [wit-ai/wit#2370]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by yuzh174** [comment]
Hi @Ananyag02 , I am not sure if I understand your need. Could you explain your use case and request a bit more?
