### ISSUE TITLE
Issues with understanding questions disappearance.

### ISSUE THREAD

**Issue by RadhikaPallavi** [wit-ai/wit#2371]
We are trying to train/remove utterances from the understanding as suggested wrt to issue https://github.com/wit-ai/wit/issues/2366. 
However, while trying to do the same, after training/removing few questions, the complete questions in the understanding disappears. Then after a very long wait, and multiple refresh, they reappear and the same sequences happens in a loop again. 

Could you please help us with the same or guide us for proper way to train them?
Also the training on the our has been going on for a very long time, and never ending. Could you check for any task if stuck and help us complete the present set of training please? App ID - 572046700564927

Snapshot for reference when they go blank and later reappears with questions.
![image](https://user-images.githubusercontent.com/97292380/155096388-a7e049a0-7bd3-481d-a7f2-58c4aa25bb4b.png)
![image](https://user-images.githubusercontent.com/97292380/155096596-1edef069-b923-42eb-8748-5eff6e25e7d3.png)
Thanks in Advance!!

**Comment by doggeral** [comment]
Your apps training is successful, we will investigate why the UI still shows the ongoing message.

**Comment by RadhikaPallavi** [comment]
@doggeral - Thank you for the update on the training. 
Could you please also guide us on the questions disappearing from the understanding? It would be great help, if you please guide us with how do we proceed training the app, if we got other way to do it better?

**Comment by yuzh174** [comment]
@RadhikaPallavi , could you provide a few utterances you'd like to remove? We could try to repro it and investigate for you.

**Comment by RadhikaPallavi** [comment]
@yuzh174, you could delete all what are present now until the utterances count in the understanding reaches 440. It some how tosses at this number, for us.

**Comment by yuzh174** [comment]
@RadhikaPallavi , I deleted a few utterances from the UI and they were gone. Not coming back. You can try to script this to delete more utterances you need. 

Another option if you simply don't want to use all the utterances, you may create another app for this purpose. 

If you still want to keep this app, but just delete the utterances, let me know, and I will see if I can do it on my end. I may be able to delete all of them if that's what you want.

**Comment by RadhikaPallavi** [comment]
@yuzh174 we were able to clear everything from the training. So probably for now we can go ahead and mark this close, and we could raise the issues if we get into trouble again. Thank you for help !!
