### ISSUE TITLE
Trained Utterance return no Intent from February 13th 

### ISSUE THREAD

**Issue by juanantoniorobles** [wit-ai/wit#2372]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
I receive no answer from Wit.ai, no error was returned either.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Send an API call to the wit.ai and I expect an intent that is not returned.
Message: Mujer > Camiseta > Camiseta Verde
Expected intent: Apparel_Accessories_Clothing_Shirts_Tops
Returned intent: [] 

**What is the expected behavior?**
Message: Mujer > Camiseta > Camiseta Verde
Expected intent: Apparel_Accessories_Clothing_Shirts_Tops

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
297708945108795

**Comment by yuzh174** [comment]
HI @juanantoniorobles , I see "Mujer > Camiseta > Camiseta Verde" is not trained as utterances. So the system may not be able to recognize it. You can add it to the utterance list for that purpose and train again.

**Comment by doggeral** [comment]
@juanantoniorobles Thanks for reporting the issue, we'll take a look.

**Comment by juanantoniorobles** [comment]
Hello,

please try with this one instead:

PANTALONES> PANTALONES F > PANTALÓN SUPER SKINNY ESLABÓN

it was trained and it returns nothing.

Please, review it and let me know.

Regards!

**Comment by doggeral** [comment]
@juanantoniorobles your issue has been fixed!
