### ISSUE TITLE
Issues in detecting entities

### ISSUE THREAD

**Issue by aya-labiba** [wit-ai/wit#2374]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
Wrong entities are being returned that are not within the synonyms.
Entities are being returned in Arabic, where all keywords are defined in English.
Entities are not always returned in the response

Example: 
[Message API response.txt](https://github.com/wit-ai/wit/files/8125021/Message.API.response.txt)

When sending 'مختبر في وادي السير' it is returning the keyword "مختبر"  in Arabic within the "HCP_type", where it should be returned as "lab"
And the keyword 'وادي السير' within the entity "AreaDecriptionAR" is not always being returned.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Send 'مختبر في وادي السير'

**What is the expected behavior?**
Correct entities to be returned

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
333179811665805

**Comment by yuzh174** [comment]
@aya-labiba, Is the entity type "HCP_type" not desired? What is "lab"? I don't see it in your entity definition.

**Comment by aya-labiba** [comment]
@yuzh174 "HCP_type" is the entity that should be returned, "lab" is the keyword that should be returned within this entity, but instead it's returning "مختبر" in Arabic which is a synonym:

![image](https://user-images.githubusercontent.com/99329638/155870576-bb9e59a3-01da-41e7-b9ba-e4ce476126c9.png)

[HCP_type entity.txt](https://github.com/wit-ai/wit/files/8148145/HCP_type.entity.txt)

**Comment by doggeral** [comment]
The issue has been fixed.
Verified on wit.ai, the resolved entity of HCP_type is lab now.
