### ISSUE TITLE
App stuck in ongoing training

### ISSUE THREAD

**Issue by German-Hernandez** [wit-ai/wit#2375]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**

Application stuck in "training ongoing", don't know if it's the UI or if it got stuck and isn't even training  

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Just adding new Utterances to train, then pressing the "Train and Validate" button

**What is the expected behavior?**

Chage, UI to "Training scheduled" then "Training ongoing" and when it ends "Training completed"

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

Id: 1344017032461624

**Comment by yuzh174** [comment]
The issue is fixed. Your app training is completed
