### ISSUE TITLE
Identifying intents for untrained inputs 

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2376]
Hi @doggeral @patapizza 

We are again facing the issue that we are getting intents with high confidence for non trained inputs.
 AppId: 623134488936494.

Same issue as in https://github.com/wit-ai/wit/issues/2323
Can you please check.

**Comment by doggeral** [comment]
You can add the utterance as out of scope training sample and retrain your app. 
Checked your app, 300 training sample supports >35 intents, the model may not have enough data to recognize the patterns for each intent.

**Comment by anjaly** [comment]
> You can add the utterance as out of scope training sample and retrain your app. Checked your app, 300 training sample supports >35 intents, the model may not have enough data to recognize the patterns for each intent.

@doggeral  Below if the response we are getting on inputting "test" keyword
{
    "text": "test",
    "intents": [
        {
            "id": "348644030031736",
            "name": "enquires",
            "confidence": 0.9669
        }
    ],
    "entities": {},
    "traits": {}
}
But this intent's example doesn't even have a keyword 'test' in any of its utterances. Then how come it can get this intent with .9 confidence. Earlier it was not returning any intent.
This issue was reported earlier and it was fixed. Now it is coming again.
This is affecting out business
Attaching ScreenShots for reference
![image](https://user-images.githubusercontent.com/601711/155665966-fa02eb7e-668a-4dc7-ac76-2569700b1cb9.png)
![image](https://user-images.githubusercontent.com/601711/155666070-b4a2d4e5-8c3f-49f8-bed4-556d41bbc447.png)
![image](https://user-images.githubusercontent.com/601711/155666117-8b9e9dc5-59b9-4c4a-802a-e06364b6de0d.png)

**Comment by anjaly** [comment]
> > You can add the utterance as out of scope training sample and retrain your app. Checked your app, 300 training sample supports >35 intents, the model may not have enough data to recognize the patterns for each intent.
> 
> @doggeral Below if the response we are getting on inputting "test" keyword { "text": "test", "intents": [ { "id": "348644030031736", "name": "enquires", "confidence": 0.9669 } ], "entities": {}, "traits": {} } But this intent's example doesn't even have a keyword 'test' in any of its utterances. Then how come it can get this intent with .9 confidence. Earlier it was not returning any intent. This issue was reported earlier and it was fixed. Now it is coming again. This is affecting out business Attaching ScreenShots for reference ![image](https://user-images.githubusercontent.com/601711/155665966-fa02eb7e-668a-4dc7-ac76-2569700b1cb9.png) ![image](https://user-images.githubusercontent.com/601711/155666070-b4a2d4e5-8c3f-49f8-bed4-556d41bbc447.png) ![image](https://user-images.githubusercontent.com/601711/155666117-8b9e9dc5-59b9-4c4a-802a-e06364b6de0d.png)

@doggeral @patapizza Any update on this issue.

**Comment by anjaly** [comment]
@patapizza 

We have created a new app with the AppId: 655872215623399 (We are creating app and train intents using the wit APIs).
We have added a few intents which are attached in SS.
![image](https://user-images.githubusercontent.com/601711/157673950-1ebb1336-ceca-426a-9eeb-0fe90e1d431b.png)

We are facing the issue that we are getting the "hi" intent with high confidence even for the untrained inputs. Actually we are supposed to get no intents for these untrained inputs.
We are facing this issue recently in most of our wit apps.
Please provide a solution ASAP for fixing this issue.

Thanks

**Comment by doggeral** [comment]
@anjaly we upgraded the model architecture recently, but it seems the app still attached to a old model, that's why the model performance is not good. I've upgrade your model version, it should be good now.

**Comment by anjaly** [comment]
> @anjaly we upgraded the model architecture recently, but it seems the app still attached to a old model, that's why the model performance is not good. I've upgrade your model version, it should be good now.

Thanks @doggeral.
So will this fix be applicable to all the apps in the same account
