### ISSUE TITLE
Unknown error after calling API

### ISSUE THREAD

**Issue by German-Hernandez** [wit-ai/wit#2377]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**

After sending some requests to the Wit API, the resonse body is this: {"error":"Something went wrong. We've been notified","code":"unknown"}.

This behavior happens with some requests, not all of them, so we don't know if it's an API's problem or if we are sending some words/text that the API doesn't support.

So it's impossible to know what's going on.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

The only step we do is calling the API's message endpoint sending the q parameter with the text to process.
Some of the requests get this response while others get a normal response with the intents, entities, text, etc in the respose's body.

**What is the expected behavior?**

The API response should have an error code and message that provides information of what's the problem, or in most cases the response body should have the intents,entities,etc.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

App id:  1344017032461624

**Comment by yuzh174** [comment]
@German-Hernandez what are the messages you sent? Do you have an example so we can repro?

**Comment by doggeral** [comment]
Tried some random utterances, seems the app is good now.
