### ISSUE TITLE
Error after calling API

### ISSUE THREAD

**Issue by chrisneyo** [wit-ai/wit#2379]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
After sending some requests to the Wit API, i get error : { Something went wrong. We've been notified }.
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App id: 450318990128142

**Comment by yuzh174** [comment]
Hi @chrisneyo , could you tell us more of the repro steps? How do you send requests to the server, though VoiceSDK or raw HTTP API? What are the utterances you sent?

**Comment by chrisneyo** [comment]
Hi @yuzh174 yuzh174
the script it is sending request via raw http request.
Thanks

**Comment by yuzh174** [comment]
Could you provide some sample utterances we can repro this?
