### ISSUE TITLE
App Not Training

### ISSUE THREAD

**Issue by brennadoyle** [wit-ai/wit#2380]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
The app is always training and always says that it takes 5 hours 13 min. The app hasn't updated in weeks or took anything that has been trained.
<img width="283" alt="Screen Shot 2022-03-02 at 1 09 23 PM" src="https://user-images.githubusercontent.com/87776601/156441907-4a320106-1188-4586-99a0-b63ee7026003.png">

**What is the expected behavior?**
The app should train and load the new utterances that have been inputted.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1591580640869653

**Comment by jayyteee** [comment]
Hello @brennadoyle I took a look and there were a few training jobs from while back that had gotten stuck which caused this issue. I forced your app to retrain and confirmed that training has completed.
