### ISSUE TITLE
Something went wrong. We've been notified

### ISSUE THREAD

**Issue by aliugur** [wit-ai/wit#2381]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a Bug

**What is the current behavior?**
After deleting an entity, /utterances and /message not working.
/message output: 
{
    "error": "Something went wrong. We've been notified",
    "code": "unknown"
}
/utterances output:
{
    "error": "Entity '274965393675976' not found",
    "code": "not-found"
}

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Delete an entity which some of the utterances depend on. It doesn't update (remove entity from) utterances and you can't use the bot.

**What is the expected behavior?**
It should remove entity from utterances and it should return a response from /message.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID: 343263113454123

**Comment by kamil-spletsteser** [comment]
Same here, Facebook support does not respond on opened bug...

**Comment by jayyteee** [comment]
@aliugur I took a look and have removed the bad values from your app, can you confirm if you are still seeing this issue? Most likely cause was after deleting an entity there was an error that caused it to be only partially removed.

**Comment by kamil-spletsteser** [comment]
@jayyteee Could you look on my app too ? :) ID: 1190820401413569, same problem...

**Comment by jayyteee** [comment]
@kamil-spletsteser I'm not seeing any errors for that app id, can you verify what the exact error is and how to repro?

**Comment by kamil-spletsteser** [comment]
@jayyteee Error is in message which comes to webhook integrated with Facebook app:

`{
  "object":"page",
  "entry":[
    {
      "id":"108725650840500",
      "time":1644998493172,
      "messaging":[
        {
          "sender":{
            "id":"2727675210692892"
          },
          "recipient":{
            "id":"108725650840500"
          },
          "timestamp":1644998492819,
          "message":{
            "mid":"m_Y_a9kFccc5NRpOi1Uld0hT54lEzW-9KN0mzwcH1IzTZEU5dg0oK-SUMt55V3IzQTxL-2RwZ16bVz4bBUPD9byg",
            "text":"Jak zap\u0142aci\u0107 ?",
            "nlp":{
              "errors":[
                {
                  "code":"unknown",
                  "message":"Something went wrong. We've been notified"
                }
              ]
            }
          }
        }
      ]
    }
  ]
}`

More detailed description in opened bug: https://developers.facebook.com/support/bugs/4601850406607287/

I'm not sure if you can help me with that always worth to try :)

**Comment by jayyteee** [comment]
@kamil-spletsteser I only see a ~11 requests for this appId in the last 2 weeks and there is only 1 error, where where it looks like the message was over the 280 character limit. If this is the right appId and you've tried more than 11 requests, it looks like the error is happening before it gets to Wit
