### ISSUE TITLE
App stopped training

### ISSUE THREAD

**Issue by imwide** [wit-ai/wit#2382]
My app is not training.
This seems to happen frequently. It is my second time that this happens, oalst time someone was kind enough to retrain it. I think it should be a button to retrain so we dont have to ask for help in here everytime.

The app ID is 475401714148910

Thanks in advance :)

**Comment by jayyteee** [comment]
Hello @imwide sorry you've been having this issue several times. I went ahead and retrained your app so it should be good to go now. We are also starting to explore ways right now to make this a less manual process to retrain any apps that get stuck.
