### ISSUE TITLE
Stuck on Training Ongoing. 

### ISSUE THREAD

**Issue by imwide** [wit-ai/wit#2383]
This is the third time happening now. I wish there was an easy way to retrain the app on your own so you don't have to wait for someone from the team to do it for you. 

The app ID is 475401714148910

**Comment by jayyteee** [comment]
Sorry again you are facing this issue often @imwide, I have force retrained your app and it finished successfully. Like I mentioned before we are exploring ways to make this process less manual but this might take some time to get done
