### ISSUE TITLE
Speech recognition immediately deactivates after activating (Oculus Voice, Unity)

### ISSUE THREAD

**Issue by dan-geniusx** [wit-ai/wit#2384]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
1. Activate speech recognition via Oculus Voice
2. Only ~1ms later, speech recognition deactivates and invokes OnStoppedListeningDueToTimeout.

Speech recognition was last confirmed working in our app on 2/28.
Bug is affecting older builds that were working, so not due to any changes on our end.

Occurs in Unity Editor with build target Android and in Quest APKs.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. In Unity 2020.3.24f1, import the official Oculus Integration from the Asset Store https://assetstore.unity.com/packages/tools/integration/oculus-integration-82022
2. Run the Oculus Voice example scene "BuiltInDemo"
3. Click the Activate button.
4. UI briefly shows "Listening..." then speech recognition deactivates almost immediately.

**What is the expected behavior?**
1. Activate speech recognition via Oculus Voice
2. Speech recognition works as usual.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
our AppID: 637639804215252
Also the Built-In Models app that the demo scene uses by default.

**Comment by jayyteee** [comment]
Thanks for reporting, we have already found the issue and should be rolling out the fix shortly

**Comment by jayyteee** [comment]
We are back now @dan-geniusx sorry for the inconvenience.
