### ISSUE TITLE
Witai is Down

### ISSUE THREAD

**Issue by dzlandis** [wit-ai/wit#2385]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
Transcription isn't returning any text and I can't access the apps panel.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
Can't get it right now because the dashboard isn't working...

**Comment by dzlandis** [comment]
Okay update, it appears to have resolved itself. It must have been a temporary issue or something like that. On another note, I found out that trying to login with Facebook from https://wit.ai/apps doesn't work but doing it from the main website does work so may wanna take a look at that 🤷🏻‍♂️

**Comment by jayyteee** [comment]
Thanks for reporting this @dzlandis we did have an issue with /speech earlier today but the fix has recently been rolled out. Sorry for the inconvenience. For the login issue, I'm having issues reproing right now but will take a closer look to see if I can find any issues

**Comment by jayyteee** [comment]
Closing this as the transcription issue has been fixed, if you find more issues with logging in from wit.ai webpage please feel free to open another issue specific to that!
