### ISSUE TITLE
Issue with untrained inputs

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2391]
HI,

We have created a new app with the AppId: 655872215623399 (We are creating app and train intents using the wit APIs).
We have added a few intents as in the  attached SS.
![Uploading image.png…]()

We are facing the issue that we are getting the "hi" intent with high confidence even for the untrained inputs. Actually we are supposed to get no intents for these untrained inputs.
We are facing this issue recently in most of our wit apps.
Please provide a solution ASAP for fixing this issue.

Thanks

**Comment by anjaly** [comment]
@patapizza 

Any update on this.?
Is there any change in the API side? What should we do to fix this. Training inputs as "Out of scope" also didn't help.
Please provide a solution to fix this as client reporting issues.
If there is any issue from the API end pls tell how to overcome it from our side?

Also when we try to train n input , app is showing training scheduled. This is affecting our functionality.

Where can we we view the inputs trained under "Out of Scope". Seems "Out of Scope" is also not working.

Thanks

**Comment by anjaly** [comment]
Hi all,
Any update, nothing is working. Please provide a solution.
on trying to train an input why this is always showing scheduled?

**Comment by doggeral** [comment]
@anjaly Could you tell a bit how you create your app?

**Comment by anjaly** [comment]
> @anjaly Could you tell a bit how you create your app?
@doggeral 
We are using the below api for creating app
https://api.wit.ai/apps?v=20170307

**Comment by anjaly** [comment]
> > @anjaly Could you tell a bit how you create your app?
> > @doggeral
> > We are using the below api for creating app
> > https://api.wit.ai/apps?v=20170307

@doggeral Any update?

**Comment by doggeral** [comment]
I see. There is ongoing issue to use the API to create the new app, we're working on the fix right now. Could you create app from wit.ai then upload your training utterance from API?

**Comment by anjaly** [comment]
> I see. There is ongoing issue to use the API to create the new app, we're working on the fix right now. Could you create app from wit.ai then upload your training utterance from API?

@doggeral Please update on this once it is fixed as we ae always creating our apps using the api. Also pls note on the issue with out of scope training .

**Comment by doggeral** [comment]
@anjaly this is the same issue with https://github.com/wit-ai/wit/issues/2386 , close the issue and track the progress from another thread.
