### ISSUE TITLE
Wrong entities are returned after importing app data

### ISSUE THREAD

**Issue by aya-labiba** [wit-ai/wit#2392]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
After exporting the app data from an existing app, and importing it to a new one the entities returned are wrong. It's returning an entity for every letter in the sentence sent.
Example 1: 
When sending 'كم سعر بطاقه زين مكس فئه 5.5'.
The entities that should be returned: 'Best_packages' and 'offers'
But in the imported app it's returning an entity for every letter.

Message API result from the exported app:
[Exported app message API result 1.txt](https://github.com/wit-ai/wit/files/8244619/Exported.app.message.API.result.1.txt)

Message API from the imported app:
[Imported app message API result 1.txt](https://github.com/wit-ai/wit/files/8244634/Imported.app.message.API.result.1.txt)

Example 2:
When sending 'اريد ان اشحن خطي'

The entities that should be returned are "Best_packages", "Recharge", and "offers"
But in the imported app it's returning an entity for every letter as per screenshot below:
![image](https://user-images.githubusercontent.com/99329638/158167993-2708a42f-9407-45ec-815e-750bcf51306e.png)
 

Message API result from the exported app:
[Exported app message API result.txt](https://github.com/wit-ai/wit/files/8244501/Exported.app.message.API.result.txt)

Message API from the imported app:
[Imported app message API result.txt](https://github.com/wit-ai/wit/files/8244504/Imported.app.message.API.result.txt)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Send: 'كم سعر بطاقه زين مكس فئه 5.5' or  'اريد ان اشحن خطي'

**What is the expected behavior?**
To return the correct entities

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
Exported app ID: 280962410285788
Imported app ID: 513391373512729

**Comment by doggeral** [comment]
@aya-labiba we're working on the fix.

**Comment by doggeral** [comment]
Your app has been fixed.
