### ISSUE TITLE
Issue with case-insensitive identifying if intent for text

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2393]
Hi,

We are facing an issue with identifying intent for text  irrespective of case. For example
We have trained an intent 'digo' using the api with an example 'digo'. When we try 'Digo' or 'DIGO' the intent is not getting identified.
Earlier the case insensitive identifying of intent was working.
Can you please check and fix the issue.

Thanks

**Comment by ChrisyShine** [comment]
Can you share your app ID?

**Comment by anjaly** [comment]
> Can you share your app ID?

Following is the AppId: 4344353432292657. But we have trained the above examples separately for it to work now.

**Comment by doggeral** [comment]
Closed the issue per customer's reply.

**Comment by anjaly** [comment]
> Closed the issue per customer's reply.

@doggeral only this input is trained with all cases.
Will the case insensitive identification of intents works for other inputs?
