### ISSUE TITLE
Persian

### ISSUE THREAD

**Issue by AliShahesmaeili** [wit-ai/wit#2394]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Create a app
Set lang to Persian
Train the app
Call 'https://api.wit.ai/message?v=20220322&q=your_text'
In several initial requests the value of **intents** will be empty
After several more attempts, the error _'Something went wrong. We've been notified'_ is returned

**What is the expected behavior?**
Persian language support

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
358857569313087

**Comment by ruoyipu** [comment]
Hi @AliShahesmaeili,

Thank you for reporting this issue. I've confirmed a repro and we're investigating.

**Comment by ruoyipu** [comment]
There is currently an issue with our built-in entities wit/location and wit/datetime. Our current recommendation is to workaround this by using a custom entity instead.

**Comment by AliShahesmaeili** [comment]
@ruoyipu Thanks for reply.
Another question?!
About 3 years ago, you supported Persian (farsi) speech recognition, but now you have stopped supporting it.
and @jtliao said it might be usable again soon
Is there any new news?

**Comment by ruoyipu** [comment]
Hi @AliShahesmaeili, I'm sorry we do not have any updates on Persian speech recognition right now.

**Comment by Lorymi** [comment]
@ruoyipu  May I ask what was the reason for stop support for Persian speech recognition?

Persian is the fifth most popular and widely used language on the Internet
https://w3techs.com/

**Comment by patapizza** [comment]
Hi @AliShahesmaeili, you had the same question in https://github.com/wit-ai/wit/issues/2044. Unfortunately we haven't been able to develop a new speech model for Farsi so far. As soon as we have one available we'll bring back support to Wit.ai. Thank you for your understanding.

**Comment by mastermehrdad** [comment]
> Hi @AliShahesmaeili, you had the same question in #2044. Unfortunately we haven't been able to develop a new speech model for Farsi so far. As soon as we have one available we'll bring back support to Wit.ai. Thank you for your understanding.

Hi @patapizza 
In your list of languages, farsi is still listed !!!?? at least remove farsi from that list, so, when ever,  you decide to support it again, you can put it back on that list, making it easier for us to check.

p.s take a look at this please:

https://home.treasury.gov/news/press-releases/jy0974
