### ISSUE TITLE
POST req voice - response  w/ chunked text cannot json parse

### ISSUE THREAD

**Issue by glitjch** [wit-ai/wit#2395]
I'd like to ask a question about wit.
I am getting a post speech recognition response from the API, however for some reason it is returning the JSON with preceding chunked text. I believe that is optional according to the docs, but I intend to only return the data that can be JSON parsed to be more usable. Any help is much appreciated.
APP ID 751387866245902

**Comment by ruoyipu** [comment]
Hi @glitjch,

Could you provide an example request(including headers) and response?

The optional header "Transfer-encoding: chunked" is what's used for sending chunked data: https://wit.ai/docs/http/20210928/#post__speech_link

**Comment by glitjch** [comment]
Hi and thank you for your response. I just found that someone else had opened the issue: 

"I'm getting the wrong data after the update #2206"

That is what I'm experience so I'll look into the solutions there more.

I do have another issue regarding recording length, which I will start a new issue request. Thank you.

**Comment by patapizza** [comment]
Commented on #2206.
