### ISSUE TITLE
Error in Utterances and Intents

### ISSUE THREAD

**Issue by aya-labiba** [wit-ai/wit#2397]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug 

**What is the current behavior?**
When trying to retrieve the utterances, we are getting the below error:
Error: Something went wrong. We've been notified

![image](https://user-images.githubusercontent.com/99329638/159903786-f3870181-8d29-4905-9c35-76b3bfff64a7.png)

Also, the intents names were changed to not include spaces or special characters but on messages API the old intent name is being returned:

Intents API response:
[Intents response.txt](https://github.com/wit-ai/wit/files/8340930/Intents.response.txt)

![image](https://user-images.githubusercontent.com/99329638/159904327-8de7b7a8-3058-476a-9bea-79f1170c20af.png)

Message API response:
[message API response.txt](https://github.com/wit-ai/wit/files/8340932/message.API.response.txt)

![image](https://user-images.githubusercontent.com/99329638/159904411-056ca435-2d0a-41bf-ad53-8a8b8c736d6c.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
send: 'my balance'

**What is the expected behavior?**
For the utterances to appear, and the message API to return the updated intents names

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1649358388514097

**Comment by ruoyipu** [comment]
Hi @aya-labiba,

I've fixed the "Error: Something went wrong. We've been notified" on your utterances page so now those should load.

We are still investigating the outdated Intent values returned from the /message api and will update as soon as possible.

**Comment by ruoyipu** [comment]
Hi @aya-labiba, I've retrained your app to force an update and the responses should now have the updated names.

We're still looking into a way to update intent names without a retrain, but this should resolve the issue for your app for now.
