### ISSUE TITLE
Wrong Trait returned from the curl URL

### ISSUE THREAD

**Issue by RadhikaPallavi** [wit-ai/wit#2398]
The Training on the app was showing completed. 
Check the question on the app, it shows trained to a trait value and the same when retrieved from the postman, returns a wrong trait value.
Due to this, the answers are displayed wrong in the Bot. Please do verify the same and find the snapshot as an example.
App ID - 618389522541052
![image](https://user-images.githubusercontent.com/97292380/159913741-cd1eb8e3-c056-448b-b4fb-376603f96bf3.png)
![image](https://user-images.githubusercontent.com/97292380/159913824-848bb8b8-8923-46a7-944b-3fafc0c2722e.png)

Thanks in Advance!!

**Comment by ruoyipu** [comment]
Hi @RadhikaPallavi,

Is this still an issue? I just tried and cannot repro.

I noticed in your image the top right says "Training Ongoing". It's possible that the app needed to finish training before the update.

**Comment by RadhikaPallavi** [comment]
Hi @ruoyipu ,
We also noticed that the app now returns the correct trait and we get the answer as expected. But however, the app still shows as training ongoing for last 4 days now. Could you please help us check if there seems to be any job which is stuck and needs to be cleared for the training to be completed.
Thank you in Advance !!
