### ISSUE TITLE
https://wit.ai/apps is down

### ISSUE THREAD

**Issue by rahuluss** [wit-ai/wit#2400]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
wit.ai/apps is currently down, showing a page that says: "Sorry, something went wrong. We're working on getting this fixed as soon as we can."

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
<img width="1085" alt="Screen Shot 2022-04-02 at 5 52 49 PM" src="https://user-images.githubusercontent.com/3276849/161406602-0eccbd60-e4f4-4135-9cec-42c911c76b93.png">

**What is the expected behavior?**
Load the wit.ai apps page

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
Cannot currently retrieve the appID since the whole site is down

**Comment by nishsinghal20** [comment]
Hey @rahuluss! Are you still seeing this error? I was able to visit the page without any issues. If you're still experiencing the issue, please feel free to re-open this ticket and we'll investigate and resolve this issue for you!
