### ISSUE TITLE
Entity Error

### ISSUE THREAD

**Issue by aya-labiba** [wit-ai/wit#2401]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
When trying to export the app, or retrieve the utterances through the API the below error is returned:
{
    "error": "Entity '641641706936693' not found",
    "code": "not-found"
}

Noting that the app doesn't have such entity, and when trying to add the entity to be able to export the app, and new error with a new entity name is being returned (all the names returned are numbers)

![image](https://user-images.githubusercontent.com/99329638/161943314-5a439af0-2b06-450b-b488-fffca7717f52.png)

![image](https://user-images.githubusercontent.com/99329638/161943368-9f266948-70aa-4e41-ae08-66ec73f6f814.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Export the app, or get the utterances through the utterances API

**What is the expected behavior?**
To be able to export the app, and retrieve the utterances without getting an error of an entities that were not added to the app.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1172640176841764

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
