### ISSUE TITLE
High confidence for incorrect utterances

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2402]
Hi @doggeral 

This is wrt to ticket #2386 . We face the same issue for our existing apps. 
Today we have created a new appi AppID: 581634206160276.
We have trained 3 intents 
![image](https://user-images.githubusercontent.com/601711/162167160-08aba8e0-87a8-47ca-92cb-71e298c6c36d.png)

When we try any other inputs,  we are getting the "hi" intent with high confidence.
We have so many apps that use wit as the nlp engine. Most of the clients are reporting the same issue and we are not able to fix it.
Some times it works and sometimes it doesn't

Can you pls find a solution ASAP to fix this.

Thanks

**Comment by anjaly** [comment]
@doggeral 

Any update on this issue.
Why is this happening so often?
We have the same issue in the following AppId also 356366686436340. We have deleted all intents from this.

Please provide a solution ASAP.

Thanks

**Comment by doggeral** [comment]
> When we try any other inputs, we are getting the "hi" intent with high confidence.

Checked the training sample, looks like these utterances are meaningless samples. We can't expect model return correct response if we feed into low quality training data.

**Comment by anjaly** [comment]
> 581634206160276

Can u try in this app 581634206160276.
In this app we have trained a Hi intent. We are creating intents and training examples using the wit api via our application.
Before adding intent, we wil check if the corresponding example is returning any intent using the message api.
IN this case there wa no issue when training Hi, After that  wen we try any inputs f.e Talk to agent, track parcel etc. the api is getting 'Hi' intent with high confidence. So we are not able to train any of these.

**Comment by AlexisNichel** [comment]
I have the same problem, wit started behaving strangely and detecting wrong intentions with high probability. Sometimes it is solved by retraining, but others not

**Comment by doggeral** [comment]
@anjaly What's the expected response for "Talk to agent"? If you expect it's "out of scope", then add is as "out of scope" and retrain the app.

**Comment by doggeral** [comment]
> I have the same problem, wit started behaving strangely and detecting wrong intentions with high probability. Sometimes it is solved by retraining, but others not

Could you share your app and the issue?

**Comment by doggeral** [comment]
No response, close the issue
