### ISSUE TITLE
Error in API call using /mesage endpoint with "n" parameter different to "1".

### ISSUE THREAD

**Issue by fredygamez** [wit-ai/wit#2403]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
this is the result to a call using the `n` parameter different to `1`. For example this call use a number `2`
here the api call: `https://api.wit.ai/message?v=20210928&n=2&q=test` 
I receive the error
```
{
    "error": "Something went wrong. We've been notified",
    "code": "unknown"
}
```

**Comment by rahadianahmad** [comment]
hello, any update on this issue? having same problem here

**Comment by doggeral** [comment]
Fix has beed deployed in prod. Close the issue.
