### ISSUE TITLE
How can I use properly the Dynamic Entities parameter in /message endpoint?

### ISSUE THREAD

**Issue by fredygamez** [wit-ai/wit#2404]
In WIT documentation, there is an example of how to send a parameter `entities` in the GET /message [endpoint](https://wit.ai/docs/http/20210928/#get__message_link) 
https://wit.ai/docs/http/20210928/#get__message_link
However, when I have tried to implement my own `dynamic entites`  the response of the API is the same. 

Here the generic example 
```
$ curl -XGET 'https://api.wit.ai/message?v=20210928&q=how%20many%20people%20between%20Tuesday%20and%20Friday' \
    -H 'Authorization: Bearer $TOKEN'
```
API Response
```
{
    "color": [
      {
        "keyword": "purple",
        "synonyms": ["violet", "magenta"]
      },
     {
        "keyword": "blue",
        "synonyms": ["aqua blue", "marine blue"]
      }
    ]
}
```
How this feature could be used or what is the context to have a different  response?

**Comment by patapizza** [comment]
Hi,

From the note in the API doc you shared:

> Dynamic entities can be only used to extend existing keywords entities defined in your Wit.ai app.

What is your app ID? Do you have a color entity in your app? The request you show is "how many people between Tuesday and Friday", which wouldn't have a color. And the API response looks like the payload for the `entities` parameter.

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
