### ISSUE TITLE
Training Ongoing seems to have stuck

### ISSUE THREAD

**Issue by Sachanski** [wit-ai/wit#2405]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
Training seems to be stuck on "Ongoing"
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
A couple of training rounds completed successfully, but once I added a new intent it is stuck on the "Training ongoing" for the past approximately 6 hours
**What is the expected behavior?**
Previous trainings finished in about a minute or two
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
3009235916066567

**Comment by doggeral** [comment]
Your issue has been fixed.
