### ISSUE TITLE
Timeout Error

### ISSUE THREAD

**Issue by aya-labiba** [wit-ai/wit#2406]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
The messages API is exceeding our timeout limit which is 10 seconds.

The issue occurred in the below timestamps:
2022-04-04 10:25:36.037
2022-04-04 07:59:14.647
2022-04-03 11:04:21.213

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
To return the result without a timeout error

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
677077969722217
280962410285788

**Comment by doggeral** [comment]
It should be transient issue.
