### ISSUE TITLE
Wrong Intents Returned

### ISSUE THREAD

**Issue by aya-labiba** [wit-ai/wit#2407]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
Intents that are returned are different than the ones that were trained for a certain expressions.

Example:
When sending "خط النت مفصول رغم انه لغايه 1/4فعال ليس", the intent that should be returned is "Complaint_AR", but the API sometimes returns the correct intent, and sometimes it returns incorrect ones (in this case it returned a character intent "_ch_75b64bb3___5a67___4b6e___a293___aef29fabf2d3") 

Below are a sample of the two different responses that were returned to the same expression.
This issue happened on 4-April-2022 to different expressions, the API is currently returning correct intents.

Correct Intent:
[Correct Response.txt](https://github.com/wit-ai/wit/files/8458898/Correct.Response.txt)

Incorrect Intent:
[Incorrect Response.txt](https://github.com/wit-ai/wit/files/8458899/Incorrect.Response.txt)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Send "خط النت مفصول رغم انه لغايه 1/4فعال ليس"

**What is the expected behavior?**
To return the correct intents

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
280962410285788

**Comment by doggeral** [comment]
The app has been trained couple times in the past few days. Machine learning model can't guarantee the 100% accuracy. If you would like the utterance to have high confidence score, you can add more similar training samples.
