### ISSUE TITLE
Issue with Importing the App

### ISSUE THREAD

**Issue by aya-labiba** [wit-ai/wit#2408]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
We are trying to import an app as V1 (v = 20190904), but we are getting the below error:
{
    "error": "\"filter_ar\" already exists",
    "code": "already-exists"
}

![image](https://user-images.githubusercontent.com/99329638/162619086-28456704-3037-4539-9c65-dd9a6f1808e0.png)

We have entities and roles in other entities that has the same name, so if one of them is imported before the other it throwing an error that the entity already exist.

Example:

We have an entity named: "filter_ar", and another entity named "currency_ar" that has a role named "filter_ar". The error is returned when importing "currency_ar":

"currency_ar" has 4 roles, but it's only importing the first role, and then the error is returned:
![image](https://user-images.githubusercontent.com/99329638/162619028-e947a7f4-d90b-4aec-ab03-a92c5afab946.png)

Screenshots from the new imported app:
 
![image](https://user-images.githubusercontent.com/99329638/162619080-f1f59556-64ad-4610-a752-394346309ef0.png)

The same issue is with the below entities:
"nickname_ar" entity has a role named "from" and "filter_ar" has a role with the same name "filter_ar", the same error is returned.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Export the app with the id: 677077969722217 and try to import it to a new one

**What is the expected behavior?**
To be able to import the app

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
Exported app ID: 677077969722217
Imported app ID: 1112976329482703

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
