### ISSUE TITLE
Roles are not understood as trained 

### ISSUE THREAD

**Issue by 91ns** [wit-ai/wit#2409]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

Bug

**What is the current behavior?**

roles are not understood correctly. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

The following sentence was retrieved from the trained utterances 

 {
      "text": "بدي احول مصاري من حسابي الجاري لحسابي التوفير",
      "entities": [
        {
          "entity": "products:products",
          "start": 9,
          "end": 14,
          "body": "مصاري",
          "entities": []
        },
        {
          "entity": "products:products",
          "start": 18,
          "end": 22,
          "body": "حساب",
          "entities": []
        },
        {
          "entity": "filter_ar:from",
          "start": 24,
          "end": 30,
          "body": "الجاري",
          "entities": []
        },
        {
          "entity": "products:products",
          "start": 32,
          "end": 36,
          "body": "حساب",
          "entities": []
        },
        {
          "entity": "filter_ar:to",
          "start": 40,
          "end": 45,
          "body": "توفير",
          "entities": []
        }
      ],
      "traits": [
        {
          "trait": "financial_inquiry",
          "value": "التحويل"
        }
      ],
      "intent": "الخدمات المالية"
    }

However, when the same sentence is tested via the messages API, the following response is returned 

{
    "text": "بدي احول مصاري من حسابي الجاري لحسابي التوفير",
    "intents": [
        {
            "id": "222108088888071",
            "name": "الخدمات المالية",
            "confidence": 1
        }
    ],
    "entities": {
        "filter_ar:to": [
            {
                "id": "b4429fd7-6a0a-4646-aff4-45070b176342",
                "name": "filter_ar",
                "role": "to",
                "start": 24,
                "end": 30,
                "body": "الجاري",
                "confidence": 1,
                "entities": [],
                "value": "C",
                "type": "value"
            },
            {
                "id": "b4429fd7-6a0a-4646-aff4-45070b176342",
                "name": "filter_ar",
                "role": "to",
                "start": 69,
                "end": 83,
                "body": "التوفير",
                "confidence": 0.999,
                "entities": [],
                "suggested": true,
                "value": "التوفير",
                "type": "value"
            }
        ],
        "filter_ar:from": [
            {
                "id": "c002e766-4aa2-407e-b7f1-33a66469ed75",
                "name": "filter_ar",
                "role": "from",
                "start": 43,
                "end": 55,
                "body": "الجاري",
                "confidence": 0.999,
                "entities": [],
                "suggested": true,
                "value": "الجاري",
                "type": "value"
            }
        ],
        "products:products": [
            {
                "id": "aab6c7f4-89a7-4a95-92dc-35499c200198",
                "name": "products",
                "role": "products",
                "start": 18,
                "end": 23,
                "body": "حسابي",
                "confidence": 1,
                "entities": [],
                "value": "الحسابات",
                "type": "value"
            },
            {
                "id": "aab6c7f4-89a7-4a95-92dc-35499c200198",
                "name": "products",
                "role": "products",
                "start": 32,
                "end": 37,
                "body": "حسابي",
                "confidence": 1,
                "entities": [],
                "value": "الحسابات",
                "type": "value"
            }
        ],
        "fin_inquiry:fin_inquiry": [
            {
                "id": "233f6927-4329-45c9-89cf-89d7ee3bd57d",
                "name": "fin_inquiry",
                "role": "fin_inquiry",
                "start": 4,
                "end": 8,
                "body": "احول",
                "confidence": 1,
                "entities": [],
                "value": "التحويل",
                "type": "value"
            }
        ]
    },
    "traits": {
        "financial_inquiry": [
            {
                "id": "d3a162b1-9978-471d-9512-6fe9c59b6d37",
                "value": "التحويل",
                "confidence": 0.9733
            }
        ]
    }
}

**What is the expected behavior?**

Note that the response is supposed to be as follows :

الجاري => filter_ar:from with the value C
توفير => filter_ar:to with the value S

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

677077969722217

**Comment by doggeral** [comment]
Sorry about the issue, we need to investigate it.

**Comment by doggeral** [comment]
I added some utterances and retrain your model, the model can recognize the from and to role correctly.
