### ISSUE TITLE
Free text entities are not detected as trained 

### ISSUE THREAD

**Issue by 91ns** [wit-ai/wit#2410]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

Bug

**What is the current behavior?**

Free text entities are not detected as trained 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Sample of trained utterance 

 {
      "text": "بدي احول الى ماري",
      "entities": [
        {
          "entity": "fin_inquiry:fin_inquiry",
          "start": 4,
          "end": 8,
          "body": "احول",
          "entities": []
        },
        {
          "entity": "filter_ar:to",
          "start": 13,
          "end": 17,
          "body": "ماري",
          "entities": []
        }
      ],
      "traits": [],
      "intent": "الخدمات المالية"
    }

When testing with a similar sample, the following response is returned 

{
    "text": "بدي احول الى محمد",
    "intents": [
        {
            "id": "222108088888071",
            "name": "الخدمات المالية",
            "confidence": 0.9118
        }
    ],
    "entities": {
        "fin_inquiry:fin_inquiry": [
            {
                "id": "233f6927-4329-45c9-89cf-89d7ee3bd57d",
                "name": "fin_inquiry",
                "role": "fin_inquiry",
                "start": 4,
                "end": 8,
                "body": "احول",
                "confidence": 1,
                "entities": [],
                "value": "التحويل",
                "type": "value"
            }
        ]
    },
    "traits": {
        "financial_inquiry": [
            {
                "id": "d3a162b1-9978-471d-9512-6fe9c59b6d37",
                "value": "التحويل",
                "confidence": 0.9928
            }
        ]
    }
}

**What is the expected behavior?**

In the tested sample محمد is supposed to be detected as filter_ar:to because the entity is of type free-text 

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

677077969722217

**Comment by doggeral** [comment]
@91ns Could you add "بدي احول الى محمد" as training sample and retrain the app?
