### ISSUE TITLE
Error after changing Intents names

### ISSUE THREAD

**Issue by aya-labiba** [wit-ai/wit#2412]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug 

**What is the current behavior?**
Some entities names were changed inside the app, when calling the messages API the API is returning the following error on the expressions that returns the changed intents names:

{
    "error": "Something went wrong. We've been notified",
    "code": "unknown"
}

API Result before changing the intents name:

![image](https://user-images.githubusercontent.com/99329638/163397765-aa4e3b23-d5ec-455f-80b8-eb52a8274634.png)

API Result after changing the intents names:

![image](https://user-images.githubusercontent.com/99329638/163397900-b0e29ee7-606a-42f7-9b2a-42e349b38317.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Send "رصيدي" or "لا استطيع استعراض المتبقي من بيانات باقة جوالي من خلال تطبيق الايفون"

**What is the expected behavior?**
To return a response with the new updated names without an error.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1084780965411406

**Comment by doggeral** [comment]
Thanks for reporting the issue, we'll work on the fix

**Comment by aya-labiba** [comment]
Hi @doggeral, any updates regarding this issue?

**Comment by doggeral** [comment]
Sorry for the late reply, we're working on the issue now.

**Comment by wangzhenict** [comment]
Hi I found the error is: "Expected WitEntBackedValue, got WitStringValue" when constructing intents response, so the intent entity's value is string value, it is not expected. @doggeral , let's discuss how could this happen.

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
