### ISSUE TITLE
"There was an error validating the utterance." Error while training

### ISSUE THREAD

**Issue by bugbrekr** [wit-ai/wit#2413]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug report
**What is the current behavior?**
Throws an error while trying to validate and train.
![image](https://user-images.githubusercontent.com/59993175/163569878-a87db1fb-da7b-4e56-a437-14e4cfdaeb68.png)

**Please provide the steps to reproduce.**
1. Go to the Understanding tab
2. **Type in an utterance**
3. Choose intent and entities
4. **Press "Train and Validate"**
5. You get an error that says "There was an error validating the utterance."

**What is the expected behavior?**
Train as normal and not throw an error.

**App ID: 1149114369241258**

A similar error also occurs when I try to delete a particular keyword of an entity.
![image](https://user-images.githubusercontent.com/59993175/163570193-f1c49719-3d86-47fe-b957-fecdf537f0a7.png)

Thank you for your attention.

**Comment by gfish35** [comment]
Bump!

Sorry to bother too much, but is there any progress on this issue? It's been happening to many other users. Is there something we can do on our side?

Wit.ai is so far the best NLP platform that offers so many features but such issues make the software unusable. We hope to see some progress on this issue soon.

Thanks a lot!

**Comment by bugbrekr** [comment]
The problem is not fixed with *this* app, but creating a new app fixed this bug, somehow.
1. Go to the settings tab of your current app
2. Export your data
3. Create a new app
4. Under "Import From a Backup", choose the .zip file you've just downloaded

This should revert everything back to normal.

I don't know what caused this issue, but doing the above steps worked in my case (as a workaround).
