### ISSUE TITLE
Wit stops working when built and run on Quest 2

### ISSUE THREAD

**Issue by DanielPortelaByrne** [wit-ai/wit#2414]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug
**What is the current behavior?**
Everything works fine when developing in Unity and testing wit response to voice commands with the Meta Quest 2 using oculus link through a usb-c connection. When the app is built and package into an APK to be run as a standalone app on the Quest 2, wit stops responding and gives no action to voice input.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
507095727432467

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
