### ISSUE TITLE
Training not working , 

### ISSUE THREAD

**Issue by ahmadfrijat** [wit-ai/wit#2415]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug.
**What is the current behavior?**
Training not working .
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
train a question with specific intent , it still not trained .   
**What is the expected behavior?**
the question trained with the correct intent . 
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
662810334939780

**Comment by yuzh174** [comment]
I see the training is complete in your app. Could you check again? If there is still issues, could you elaborate more on the problem you see.

**Comment by ahmadfrijat** [comment]
for example i trained this question many times but it still out of scope 
![image](https://user-images.githubusercontent.com/75928390/164176205-deb58617-162a-42c3-bea8-981d1af1494e.png)

**Comment by yuzh174** [comment]
out of scope means if you want the app to recognize some utterances but not handle them, you can mark the utterances as out of scope. It always has the option for you, but if you don't check on it, it won't use it as out of scope. 
The out of scope option there is for your input, so you can check the box or not. It doesn't mean the utterance is out of scope.

**Comment by ahmadfrijat** [comment]
what i meant by of out of scope , is that after the training of a specific question with the correct intent , the question still not trained .

**Comment by yuzh174** [comment]
Do you mean that if you send the question (utterance), it is not recognized to the correct intent? If so, what is the response?
Could you send me the utterance in text?

**Comment by ahmadfrijat** [comment]
yes , there are more than one utterance, for example "الدفع في شامل" with payments intent

**Comment by yuzh174** [comment]
When I put "الدفع في شامل" in the understanding tab, it shows the "PaymentB". Is that not right? What is the expected intent. 
![Screen Shot 2022-04-25 at 4 14 51 PM](https://user-images.githubusercontent.com/73909056/165189472-bab6ed13-e58a-4d1c-b998-8a7c900c897d.png)

**Comment by kalpa277** [comment]
I have 50 utterances per intent ,how to write in Utterance box {can we use comma }
@yuzh174  @ahmadfrijat
