### ISSUE TITLE
[wit] [speech] Error: Something went wrong. We've been notified.

### ISSUE THREAD

**Issue by Rit-tan** [wit-ai/wit#2416]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
prints out [wit] [speech] Error: Something went wrong. We've been notified.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I was attempting to print out text in a wav file, sample code is provided below:

const client = new Wit({accessToken: 'EXAMPLETOKEN'});
var pathToFile = 'test.wav'
const data = fs.readFileSync(pathToFile);

client.speech('audio/wav', data)
.then(data => {
    console.log(JSON.stringify(data));
})
.catch(console.error);

**What is the expected behavior?**
print out message in the wav file

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
318474643730594

**Comment by jayyteee** [comment]
Hello @Rit-tan, I took a look at the logs and from what I can tell it seems like it might be an issue with the .wav file you're sending. I can't see what the file so it's hard to say exactly what could be wrong, but I would first try with different audio files to see if that fixes the issue for you.

**Comment by jayyteee** [comment]
I would also try sending a request directly to our server via curl or postman with the .wav file, to see if it could be an issue with how your client is sending the request with the audio.
