### ISSUE TITLE
Can not login to my account

### ISSUE THREAD

**Issue by fryingbrains** [wit-ai/wit#2417]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**
Press the login button of Facebook and then nothing happens. I have tried it with another facebook account and it logged in to an empty wit dashboard as expected. However when I do it with mine it just doesn't login, nothing happens on the screen and it just stops there on the login page. Damn Facebook.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Press the login button and it just doesnt work. works with another facebook account.
**What is the expected behavior?**
Logging in
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
Fuck login with facebook !

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
