### ISSUE TITLE
Poor response times and "Something went wrong" responses

### ISSUE THREAD

**Issue by ViktorSchroeder** [wit-ai/wit#2418]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug / problem

**What is the current behavior?**
Poor response times (about 10 seconds) and frequent "Something went wrong. We've been notified" responses.

**What is the expected behavior?**
Response within or less than 2 seconds.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
There are several APPs and all APPs have a poor response time. 

Main APP: **2115985458480186**
This APP has not been changed for a long time but recently there are issues with this APP with response time and response itself. If it does not result in a "Something went wrong. We've been notified", then the response time is about 10 seconds. I created other APPs by exporting the main APP, reducing its data and importing it into a new APP to eliminate the amount of data as a problem. See the following APPs.

Exact import of the main APP: **531208095257608**
I've exported the data from the main APP and imported it into a new APP. The utterances are not displayed after the import. Performance remains poor. Also the APP has been training for more than 24 hours and is still not done.

Reduced utterances APP: **1047565459513799**
I have reduced the main APP to about 500 utterances. No improvements are noticeable.

Reduced utterances and synonyms/keywords APP: **822968505759921**
I have reduced the main APP to about 70 utterances and synonyms/keywords also to 70. The response time is about 8 seconds.

New APP: **1159881918110720**
I have created a completely new APP and trained it a bit. The response time is already about 4-5 seconds.

**Comment by b-tix** [comment]
The apps above are in fact not useable anymore for any production purposes. Are there any more findings? What should we do to solve it?

**Comment by doggeral** [comment]
@ViktorSchroeder your app 2115985458480186 has so many traits, we recommend customer use less than 10 traits. Otherwise, the system might have the timeout issue for your request.

**Comment by b-tix** [comment]
Our solution: Switch to Rasa. This ticket can be closed.
