### ISSUE TITLE
Feature request: CORS support

### ISSUE THREAD

**Issue by olivierlesnicki** [wit-ai/wit#242]
I'm unable to use the API within my client because of CORS errors.
I'd like to use the converse end-point (leveraging the `POST` method - for which JSONP is not available). Please advise.

**Comment by olivierlesnicki** [comment]
Any help @l5t

I've generated a client token and whitelisted my domain... Still doesn't work...

**Comment by blandinw** [comment]
@olivierlesnicki The domain whitelisting feature was created a while back specifically for our https://github.com/wit-ai/microphone SDK (WebSockets). It does not feed back into our CORS checker for now, but it's something we could make happen if demand is strong enough. We are focusing on reliability and stability for this couple of weeks and will have a closer look at new features shortly after.

**Comment by tstrickland415** [comment]
I'd like to see this implemented as well for the exact same reason

**Comment by akapei** [comment]
+1

**Comment by ALenfant** [comment]
I agree this is a big issue with a simple fix, this completely prevents me from using Wit.ai on the client side...

**Comment by blandinw** [comment]
OK, looks like we're getting critical mass on this one and will reprioritize.
To be clear, today you can do GET requests using JSONP, but not POST requests.
I'd like to gain a better understanding of what the usage would be.

What calls would you like to make from a webpage?

@ALenfant @akapei @tstrickland415 @olivierlesnicki any other potential user

**Comment by stopachka** [comment]
Hey all! GET /message, GET /entities now support CORS. 

More and more endpoints will gradually support this, as we migrate towards new infra. If you have other endpoints that you wish to have CORS support immediately, let us know and we can speeden up their process down the funnel.
