### ISSUE TITLE
The wit stuck in "Training ongoing"

### ISSUE THREAD

**Issue by ahmadfrijat** [wit-ai/wit#2421]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?** 
The wit stuck in "Training ongoing" 
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
![image](https://user-images.githubusercontent.com/75928390/167288618-735fa224-9b95-45a8-bc27-3bb0256f88a8.png)

**What is the expected behavior?**
Training finished
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
269447701979025

**Comment by patapizza** [comment]
Thanks for reporting, we're looking into it.
Closing in favor of https://github.com/wit-ai/wit/issues/2420.
