### ISSUE TITLE
Stuck in training

### ISSUE THREAD

**Issue by BrooklynLrx** [wit-ai/wit#2422]
Do you want to request a feature, report a bug, or ask a question about wit?
The wit stuck in "Training ongoing"
What is the current behavior?

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
![image](https://user-images.githubusercontent.com/44015133/167289012-bcec3754-3f83-4f79-81c3-4c9eebd10efd.png)

What is the expected behavior?
Training finished
If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.

661187201782793

**Comment by Joinfield** [comment]
me too! app 796877037948700

**Comment by aryasuryapp** [comment]
me too app 549541153276495

**Comment by patapizza** [comment]
Thanks for reporting, we're looking into it.
Closing in favor of https://github.com/wit-ai/wit/issues/2420.
