### ISSUE TITLE
Issue with intent training

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2424]
HI,

We are trying to train intents/examples in our app 949216419119159. It is showing 'Training ongoing' for long time. Still showing the same.
Even though intents and examples are listed in wit app, when we try with the examples in understanding tab it is not working.
Please help to fix this Issue.

Thanks

**Comment by patapizza** [comment]
Thanks for reporting, we're looking into it.
Closing in favor of https://github.com/wit-ai/wit/issues/2420.
