### ISSUE TITLE
Stuck in training

### ISSUE THREAD

**Issue by SarahAabid** [wit-ai/wit#2425]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
The wit stuck in "Training ongoing"
**What is the current behavior?**
If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
Training ongoing
**What is the expected behavior?**
Training finished
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
957582438253288

**Comment by patapizza** [comment]
Thanks for reporting, we're looking into it.
Closing in favor of https://github.com/wit-ai/wit/issues/2420.
