### ISSUE TITLE
App Stuck At Training

### ISSUE THREAD

**Issue by web-pda** [wit-ai/wit#2426]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug

**What is the current behavior?**
App Stuck at Training

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Added some utterances and app is training for hours

**What is the expected behavior?**
Training should be finished

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1146876935819292

**Comment by patapizza** [comment]
Thanks for reporting, we're looking into it.
Closing in favor of https://github.com/wit-ai/wit/issues/2420.
