### ISSUE TITLE
App stuck in training

### ISSUE THREAD

**Issue by Borys-Kostka** [wit-ai/wit#2427]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
I have seen the "Training ongoing" sign since i created my application (yesterday)
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
So the sign will stop saying "Training ongoing" i guess
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1036093763781805

**Comment by patapizza** [comment]
Thanks for reporting, we're looking into it.
Closing in favor of https://github.com/wit-ai/wit/issues/2420.
