### ISSUE TITLE
Bot "Ongoing Training" indefinitely

### ISSUE THREAD

**Issue by MashroomMan** [wit-ai/wit#2428]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question. The bot training has been stuck on "training ongoing" for a few days. How could I fix this?

**What is the current behavior?**
training ongoing

**What is the expected behavior?**
training completed

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
372252781333109

**Comment by Nisreena93** [comment]
Hello Wit!
My App Also facing the same issue 
App ID: 1920151674738030

**Comment by doggeral** [comment]
apps have been fixed.
