### ISSUE TITLE
train stuck on "on going"

### ISSUE THREAD

**Issue by shorouqmajali** [wit-ai/wit#2429]
Do you want to request a feature, report a bug, or ask a question about wit?
The wit stuck in "Training ongoing"
What is the current behavior?
If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
What is the expected behavior?
Training finished
If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.
876998832983929 , 398676275458193

**Comment by Nisreena93** [comment]
Hello Wit!
My App Also facing the same issue 
App ID: 1920151674738030

**Comment by doggeral** [comment]
All the apps have been fixed.
