### ISSUE TITLE
Failing to delete app with api call

### ISSUE THREAD

**Issue by CannonFodderr** [wit-ai/wit#2431]
We try to delete apps with api call and get 400 code with response
```
{
    "error": "Access token does not match",
    "code": "bad-request"
}
```
Same result when coping the app token directly from WIT.AI dashboard and doing a request to wit api with it.

When trying to delete the app from dashboard failed with error: 
![Capture6](https://user-images.githubusercontent.com/36086310/168091659-bb72b372-cda3-40a3-9679-3d46a502725c.PNG)

It seems to happen with multiple apps here are some app ids that failed for me:
794697344828694
540067887695279
524180816027460

So currently we are unable to delete any app

**Comment by CannonFodderr** [comment]
Any update about this? We are still not able to delete apps with api calls or from the dashboard.

**Comment by andersdu** [comment]
do we have any update about this?

**Comment by CannonFodderr** [comment]
@doggeral Is there any update about this issue ?

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
