### ISSUE TITLE
The whole date is not being detected

### ISSUE THREAD

**Issue by aya-labiba** [wit-ai/wit#2433]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
When sending the a date, only the month and year are being returned in the response the day is not being returned.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Send: "i want to take a leave on 20/05/2022 at 3 pm"

Response: 

[Message API response.txt](https://github.com/wit-ai/wit/files/8694718/Message.API.response.txt)

**What is the expected behavior?**
To return the correct complete date

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
468849228311171

**Comment by aya-labiba** [comment]
Hi Wit, any updates?

**Comment by doggeral** [comment]
Thanks for reporting the issue. We should improve the built-in-entity model for datatime.

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new issue should the subject persist.
