### ISSUE TITLE
Date Interval not returned 

### ISSUE THREAD

**Issue by aya-labiba** [wit-ai/wit#2434]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
A date interval should be returned in the response, but it is only taking the first date value.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Send : "يجب أن آخذ مغادرة عاجلة اليوم من الساعة 2 الظهر حتى 4 مساءً" which translates to: I need to take an urgent leave today from 2 PM until 4 PM
It's only returning "2022-05-15T14:00:00.000+03:00"

Message API response: 
[Message API response.txt](https://github.com/wit-ai/wit/files/8694732/Message.API.response.txt)

Also, on Wednesday  11/5/2022 the API was returning a different response:

![image](https://user-images.githubusercontent.com/99329638/168469286-4a706d52-a8a9-4c18-9a0b-c500eb8b8b8a.png)
 It used to take 2 PM correctly, but 4 PM was taken as 3:09 PM

**What is the expected behavior?**
To return a correct date interval

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
398875828702387

**Comment by aya-labiba** [comment]
Hi Wit, any updates?

**Comment by doggeral** [comment]
Take a look at your app, it seems the built-in-entity is not well supported for Arabic language. As a work around, could you create the entity for time, and label the timestamp in your training utterance and retrain your model?

**Comment by aya-labiba** [comment]
Hi @doggeral, can you please provide me with more details on how this workaround can be done?
Thank you
