### ISSUE TITLE
Date not returned

### ISSUE THREAD

**Issue by aya-labiba** [wit-ai/wit#2435]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
The date that is sent within the sentence is not being returned in the response:

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Send: "بدي اخد اجازتي السنويه من تاريخ 18/1/2022" which translates to: "I want to take my annual vacation from the date 18/1/2022"
18/1/2022 is not being returned in the response at all.

Message API response: 
[Message API response.txt](https://github.com/wit-ai/wit/files/8694735/Message.API.response.txt)

**What is the expected behavior?**
To return the date

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
398875828702387

**Comment by aya-labiba** [comment]
Hi Wit, any updates?

**Comment by doggeral** [comment]
Same issue with https://github.com/wit-ai/wit/issues/2433, closed for dedup.
