### ISSUE TITLE
Date Interval not returned

### ISSUE THREAD

**Issue by aya-labiba** [wit-ai/wit#2436]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
When sending a date interval, it is taking the second date only.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Send: "بدي اخد اجازتي السنويه من تاريخ 18/1/2022 الى تاريخ 01/02/2022" which translates to "I want to take my annual vacation from date 18/1/2022 to date 01/02/2022 "

Message API response: 
[Message API response.txt](https://github.com/wit-ai/wit/files/8694743/Message.API.response.txt)

**What is the expected behavior?**
Return the correct interval with the correct dates

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
398875828702387

**Comment by aya-labiba** [comment]
Hi Wit, any updates?

**Comment by doggeral** [comment]
Same issue with https://github.com/wit-ai/wit/issues/2433, closed for dedup.
