### ISSUE TITLE
Speech outputting "Hey Facebook" when unable to understand.

### ISSUE THREAD

**Issue by dzlandis** [wit-ai/wit#2439]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
It returns "Hey Facebook" as the text.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Use Wit.ai speech and submit quiet audio, or audio that is difficult to understand, multiple times.

**What is the expected behavior?**
It returns something saying it wasn't able to understand the audio or it just doesn't output any text.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
Every application I have that works with speech has this issue. If you actually need an App ID, please follow up.

**Comment by ChrisyShine** [comment]
@dzlandis Can you share several App IDs with the problem?

**Comment by ChrisyShine** [comment]
We are working on the fix for this problem.

**Comment by dzlandis** [comment]
Hi there, thanks. Is there any updates on this?

**Comment by ChrisyShine** [comment]
@dzlandis We are still working on the fix.

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
