### ISSUE TITLE
Create new app via the API

### ISSUE THREAD

**Issue by mark-stephenson-** [wit-ai/wit#244]
Linked to: #218 (https://github.com/wit-ai/wit/issues/218)

I'd like to be able to create a new app, or sub app via the API.  Being able to create an app will allow us to automate the creation of specific bots for multiple clients.

**Comment by hfinck** [comment]
This would be of great help to me, too. Without the ability to programmatically create new apps it is difficult to include wit in a self-serving platform. The amount of work involved creating a new app and registering it for a client on our end holds me back to integrate wit in our production environment.

**Comment by ankit-saxena** [comment]
I second that! Is this somewhere on the roadmap?

**Comment by AndreaPivetta** [comment]
Still no plans?

**Comment by JSValleybe** [comment]
Would be great if this comes available

**Comment by shazadmaved** [comment]
Hey 

I believe you are looking for something like this? Its in the documentation.

Create a new app

Creates a new app for an existing user.


Definition

  POST https://api.wit.ai/apps
Example request

  $ curl -XPOST 'https://api.wit.ai/apps?v=20170307' \
  -H "Authorization: Bearer $TOKEN" \
  -H "Content-Type: application/json" \
  -d '{"name":"My_New_App",
       "lang":"en",
       "private":"false"}'
Example response

{
  "access_token" : "NEW_ACCESS_TOKEN",
  "app_id" : "NEW_APP_ID"
}


https://wit.ai/docs/http/20170307#authentication-link

**Comment by patapizza** [comment]
Indeed, thanks @shazadmaved!
