### ISSUE TITLE
Returning wrong entity values

### ISSUE THREAD

**Issue by aliugur** [wit-ai/wit#2440]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug

**What is the current behavior?**
It is returning wrong entity value

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Entity "serialNumber" has 20 values and its type is "Free Text & Keywords". It has value: "5CG8021DD4". When I ask with "5CG8021DE4", AI returns "wit/number" with 3 values: "5", "8021", "4"

**What is the expected behavior?**
It should return "serialNumber", "5CG8021DE4"

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
417419780182583

**Comment by ChrisyShine** [comment]
We will fix this issue.

**Comment by doggeral** [comment]
@aliugur Seems you retrained your model, I test it on the wit.ai, "5CG8021DE4" was recognized correctly. 
<img width="875" alt="image" src="https://user-images.githubusercontent.com/1651153/172778385-73331fca-4b23-48df-9b11-52130d8d6bb4.png">

**Comment by aliugur** [comment]
@doggeral Yes, I had to change intent because of a business request. I have done it 15 minutes ago. Now it is as you said, it captures the entity correctly. What was changed?
