### ISSUE TITLE
NLP not working - Something went wrong. We've been notified

### ISSUE THREAD

**Issue by matt0fer** [wit-ai/wit#2441]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
{"object":"page","entry":[{"id":"119739501385602","time":1653228435240,"messaging":[{"sender":{"id":"253221xxxxxxxxxx"},"recipient":{"id":"119739501385602"},"timestamp":1653228434758,"message":{"mid":"m_kqEXkrMJ6jBQz7y7ZDTUIpgJW8ioyQz7cGIF8C2zOa1PfFICgV2TvZj4lBag6U031MGPpCZRecQMlDXoqIDfUQ","text":"fa rima con porc","nlp":{"errors":[{"code":"unknown","message":"Something went wrong. We've been notified"}]}}}]}]}
200 POST /webhook

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Every attempt to message to our chatbot returns this error

**What is the expected behavior?**
The app used to work correctly, returning NLP, which is then processed and utilized to provide users appropriate results.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2614205462213696

**Comment by ChrisyShine** [comment]
@matt0fer Can you double check if the app is still broken? And can you try our /message API to see if the utterance works? https://wit.ai/docs/http/20220503/#get__message_link

**Comment by matt0fer** [comment]
Yes, app is still broken unfortunately :(

The API works correctly 

<img width="706" alt="API-test" src="https://user-images.githubusercontent.com/56958394/169955820-9a7989b2-d9c9-4e6a-a221-311b9eec7537.png">

**Comment by ChrisyShine** [comment]
@matt0fer Can you double check if the wit.ai app is really 2614205462213696? Since the wit.ai app works well with /message API, if the NLP webhook setting is correct, it shouldn't return the wit.ai related error message: "Something went wrong. We've been notified".

**Comment by matt0fer** [comment]
<img width="680" alt="image" src="https://user-images.githubusercontent.com/56958394/170170000-6f1050f1-27e5-4039-b403-f17231eb1f73.png">

If you search for the same error you'll see it happened to several people, e.g. https://github.com/wit-ai/wit/issues/1976 and some assumptions have been made in relations to GDPR impact on Messenger. I'm not sure if it was true or if something changed since then (last update Jan 2022, bug opened Dec 2020).

**Comment by matt0fer** [comment]
No news? :( I'd really love to have my app working back. Is there a workaround Facebook/Meta/Wit.AI can advice on?

**Comment by ChrisyShine** [comment]
At first, can you go to the Messenger webhook settings page and double check if the nlp setting looks good? 
And if the setting looks good, can you try to send requests to your chatbot for multiple times (more than 10 times) and share the timestamp?

**Comment by matt0fer** [comment]
webhook is listening
sha1=c1b0c4ee386a2ca1ca6a276debad5c7714420baf
{"object":"page","entry":[{"id":"119739501385602","time":1654390293814,"messaging":[{"sender":{"id":"2532218000195687"},"recipient":{"id":"119739501385602"},"timestamp":1654390293254,"message":{"mid":"m__Sz0q-kaaVLfKsfsXJnAXJgJW8ioyQz7cGIF8C2zOa0H64H46-VSyKtLqt8_MUu7PaZ4m6H_XoEwOrMhydQVlg","text":"fa rima con pipistrello","nlp":{"errors":[{"code":"unknown","message":"Something went wrong. We've been notified"}]}}}]}]}
200 POST /webhook

sha1=70d5d6b7210c55c409955829142e50bfa4de6193
{"object":"page","entry":[{"id":"119739501385602","time":1654390457146,"messaging":[{"sender":{"id":"2532218000195687"},"recipient":{"id":"119739501385602"},"timestamp":1654390456842,"message":{"mid":"m_yqxmPc0V7n74c6zZIK8nmpgJW8ioyQz7cGIF8C2zOa1MuN301VcW9PDO87bEwaoPmqf9aZW0XgytfMwr44dvTw","text":"fa rima con castoro","nlp":{"errors":[{"code":"unknown","message":"Something went wrong. We've been notified"}]}}}]}]}
200 POST /webhook

sha1=22fe01ffb76a8e16874579e56413f9e803f8b4c5
{"object":"page","entry":[{"id":"119739501385602","time":1654390460714,"messaging":[{"sender":{"id":"2532218000195687"},"recipient":{"id":"119739501385602"},"timestamp":1654390460327,"message":{"mid":"m_EbOks7YH9zTyeQp3G0K1kZgJW8ioyQz7cGIF8C2zOa1SiiEvheivwG_KBbEu8ED-uw3I1X6kKYIt1VrGvADejg","text":"ponte","nlp":{"errors":[{"code":"unknown","message":"Something went wrong. We've been notified"}]}}}]}]}
200 POST /webhook

sha1=74421cca3181de1627d01a93f0f6b8cea51c3228
{"object":"page","entry":[{"id":"119739501385602","time":1654390463146,"messaging":[{"sender":{"id":"2532218000195687"},"recipient":{"id":"119739501385602"},"timestamp":1654390462777,"message":{"mid":"m_OXQoZKPqaGGzVJBkv5Kt-JgJW8ioyQz7cGIF8C2zOa20xhePZQRejS3pcTfd0Bvaj1n4cpTT6heS_kqdi5rPiw","text":"simpatico","nlp":{"errors":[{"code":"unknown","message":"Something went wrong. We've been notified"}]}}}]}]}
200 POST /webhook

sha1=ad346cd6c3eb012c0b968220fe4a0f91e142ba30
{"object":"page","entry":[{"id":"119739501385602","time":1654390467396,"messaging":[{"sender":{"id":"2532218000195687"},"recipient":{"id":"119739501385602"},"timestamp":1654390466971,"message":{"mid":"m_nL83Q5TbYz_8Er1pMLZw9pgJW8ioyQz7cGIF8C2zOa13N0zcCm5XXpPf6UgkICOYhfKMEE1Ec0U9Xfy825gi9A","text":"fa rima con somaro","nlp":{"errors":[{"code":"unknown","message":"Something went wrong. We've been notified"}]}}}]}]}
200 POST /webhook

sha1=7e7956917cf01662f8cef55b0ee50db3571ae71b
{"object":"page","entry":[{"id":"119739501385602","time":1654390473317,"messaging":[{"sender":{"id":"2532218000195687"},"recipient":{"id":"119739501385602"},"timestamp":1654390472896,"message":{"mid":"m_8RZKU3jQoamnjJVzaff-MpgJW8ioyQz7cGIF8C2zOa0RizwQV3lVPoBt5SpJtLCma-re87Wvz6k274ERzmN4bA","text":"fa rima con facbook","nlp":{"errors":[{"code":"unknown","message":"Something went wrong. We've been notified"}]}}}]}]}
200 POST /webhook

sha1=1eae5e7c6aaccb35462e563b1cd12e1a8236ee27
{"object":"page","entry":[{"id":"119739501385602","time":1654390484525,"messaging":[{"sender":{"id":"2532218000195687"},"recipient":{"id":"119739501385602"},"timestamp":1654390484081,"message":{"mid":"m_QybbRkLoa-MfHRI5u9B21ZgJW8ioyQz7cGIF8C2zOa2CIe06WM5d7PMjfQz3_SrXZNxV2Zr8MvVCHGVR8xXzRQ","text":"fa rima con puerile di 5 lettere","nlp":{"errors":[{"code":"unknown","message":"Something went wrong. We've been notified"}]}}}]}]}
200 POST /webhook

sha1=e1b2d20b2e91717c517eaada44b4b59791902f85
{"object":"page","entry":[{"id":"119739501385602","time":1654390492391,"messaging":[{"sender":{"id":"2532218000195687"},"recipient":{"id":"119739501385602"},"timestamp":1654390492007,"message":{"mid":"m_mWm_oCwFPka-MuMVZoaMgpgJW8ioyQz7cGIF8C2zOa1MIG8bPSonOigiz8GUHb4Ef6tWtvleO5nedbKQjfkE-A","text":"fa rima con senile","nlp":{"errors":[{"code":"unknown","message":"Something went wrong. We've been notified"}]}}}]}]}
200 POST /webhook

sha1=42e58cc8aa1f38625d41c1dd52461427440f24a9
{"object":"page","entry":[{"id":"119739501385602","time":1654390501808,"messaging":[{"sender":{"id":"2532218000195687"},"recipient":{"id":"119739501385602"},"timestamp":1654390501495,"message":{"mid":"m_r29cwlhprkb1egI-Y0IbupgJW8ioyQz7cGIF8C2zOa21fhcGthzZT8coZYygBzpFVp1GEb8vIQPhaPwY6VZ0zA","text":"fa tima con povero","nlp":{"errors":[{"code":"unknown","message":"Something went wrong. We've been notified"}]}}}]}]}
200 POST /webhook

sha1=3948aaf81546a2afa91d03c448c898c85d6b0d0b
{"object":"page","entry":[{"id":"119739501385602","time":1654390505411,"messaging":[{"sender":{"id":"2532218000195687"},"recipient":{"id":"119739501385602"},"timestamp":1654390505095,"message":{"mid":"m_eJZ-G_pEpX3BaMskiBIpDpgJW8ioyQz7cGIF8C2zOa3MLq1gESFpoWYdIcVSIofi6Z2pUcDU74s6Hki1v0zRLg","text":"fa rima con supporto","nlp":{"errors":[{"code":"unknown","message":"Something went wrong. We've been notified"}]}}}]}]}
200 POST /webhook

sha1=e91e67ef411d66c3109fe0c32fc9cfaa3d8c663f
{"object":"page","entry":[{"id":"119739501385602","time":1654390513167,"messaging":[{"sender":{"id":"2532218000195687"},"recipient":{"id":"119739501385602"},"timestamp":1654390512550,"message":{"mid":"m_TEUMt6qTc0D_2sysyCg-s5gJW8ioyQz7cGIF8C2zOa1fUlsl_sGpphSZh34lqYYTKd6ZSNuRkGqjYTf8Myu2Gw","text":"fa rima con tecnico di 4 sillabe","nlp":{"errors":[{"code":"unknown","message":"Something went wrong. We've been notified"}]}}}]}]}
200 POST /webhook

**Comment by matt0fer** [comment]
NLP settings are fine on the Facebook page, Webhook working correctly. The chatbot overall used to work without any issues. Can't figure out what is wrong without your help :(
What's the workaround? Removing the integration and do an additional step to call the wit.ai API separately?

**Comment by patapizza** [comment]
Hi @matt0fer, I pinpointed the issue to the `n=2` advanced option. We're investigating why setting higher than n=1 creates issues. In the meantime, feel free to temporarily set the `n` parameter to 1.

**Comment by matt0fer** [comment]
Hi @patapizza , switched back to 1 as recommended.  I am seeing the same behavior for now. Thanks for your help, appreciate it!

**Comment by matt0fer** [comment]
Any updates? :) Was this confirmed by any chance? https://github.com/wit-ai/wit/issues/1976#issuecomment-1025585527

**Comment by doggeral** [comment]
@matt0fer we are working on the fix, should be deployed in production by end of week.

**Comment by doggeral** [comment]
The fix has been deployed. Close the task.

**Comment by matt0fer** [comment]
I still experience the same error though...

**Comment by matt0fer** [comment]
[nodemon] starting `node index.js`
webhook is listening
sha1=88db1b9c3d6afdb36d13a089a385579629498d44
{"object":"page","entry":[{"id":"119739501385602","time":1656144750784,"messaging":[{"sender":{"id":"2532218000195687"},"recipient":{"id":"119739501385602"},"timestamp":1656144750226,"message":{"mid":"m_qXcrM1EK0u0szBrpbmojBpgJW8ioyQz7cGIF8C2zOa1yKSnWok5iSJMFb4mSS-1iREnJC5JmHJhGnd8xqp1DZw","text":"porta","nlp":{"errors":[{"code":"unknown","message":"Something went wrong. We've been notified"}]}}}]}]}
200 POST /webhook
sha1=8c8bf6691affeeb29f38749f3e87caa0c152a15c
{"object":"page","entry":[{"id":"119739501385602","time":1656144765124,"messaging":[{"sender":{"id":"2532218000195687"},"recipient":{"id":"119739501385602"},"timestamp":1656144764787,"message":{"mid":"m_0u7gTa-CmPG-h7pnSD5tBJgJW8ioyQz7cGIF8C2zOa3IiD6sBYEYfPrv1Ru9wFj8pzujp-WeME0dxwN6qPEBxA","text":"fa rima con torta","nlp":{"errors":[{"code":"unknown","message":"Something went wrong. We've been notified"}]}}}]}]}
200 POST /webhook
sha1=768a9bd8fbf4ca978e82a387da43300d0c989726
{"object":"page","entry":[{"id":"119739501385602","time":1656144768717,"messaging":[{"sender":{"id":"2532218000195687"},"recipient":{"id":"119739501385602"},"timestamp":1656144768263,"message":{"mid":"m_r_QrY3n34dX6YVe69135vpgJW8ioyQz7cGIF8C2zOa0Cfw23phcgIkg88rwHEbOa4Qrc8S66w7BmPcrIzLxhDw","text":"portento","nlp":{"errors":[{"code":"unknown","message":"Something went wrong. We've been notified"}]}}}]}]}
200 POST /webhook
sha1=9bd89a66bb57fa9314bba7cef45e46772c0e442b
{"object":"page","entry":[{"id":"119739501385602","time":1656144771693,"messaging":[{"sender":{"id":"2532218000195687"},"recipient":{"id":"119739501385602"},"timestamp":1656144771386,"message":{"mid":"m_9wiNv82_f_IvLFPWNpKRPJgJW8ioyQz7cGIF8C2zOa2ajatG46ly1s4nDy-PJ6kxD7c8kp5pncYvNyZ5gGS5tg","text":"calamita","nlp":{"errors":[{"code":"unknown","message":"Something went wrong. We've been notified"}]}}}]}]}
200 POST /webhook
sha1=ebd3348a4250874c4947743ec95c0846a7eace53
{"object":"page","entry":[{"id":"119739501385602","time":1656144775233,"messaging":[{"sender":{"id":"2532218000195687"},"recipient":{"id":"119739501385602"},"timestamp":1656144774918,"message":{"mid":"m_VVNUJeN_KaXvsWNFBYzbsJgJW8ioyQz7cGIF8C2zOa2uNfnczFHmqiDTvntXGPMVT2oGfR3AL9MLyuDMzn8YEg","text":"toro","nlp":{"errors":[{"code":"unknown","message":"Something went wrong. We've been notified"}]}}}]}]}
200 POST /webhook
sha1=296dd6a5492e2b079c8c7eb60d368407308e5934
{"object":"page","entry":[{"id":"119739501385602","time":1656144778994,"messaging":[{"sender":{"id":"2532218000195687"},"recipient":{"id":"119739501385602"},"timestamp":1656144778646,"message":{"mid":"m_8gR0aVy778INEYZ2MEFJlZgJW8ioyQz7cGIF8C2zOa21ZXqxqWIr4lr2bTsbuu_-hhYn15NfDlF-maJPLMwnjA","text":"faccia","nlp":{"errors":[{"code":"unknown","message":"Something went wrong. We've been notified"}]}}}]}]}
200 POST /webhook
sha1=16b30af516d0c2ca9e2ab84986019368c6ca6bb4
{"object":"page","entry":[{"id":"119739501385602","time":1656144781431,"messaging":[{"sender":{"id":"2532218000195687"},"recipient":{"id":"119739501385602"},"timestamp":1656144781110,"message":{"mid":"m_i6ruKPNMWsdMEkkCPOFIXZgJW8ioyQz7cGIF8C2zOa1V8VKX-QsMa0PHsns6vSPqb6hXXS1PF_3tKJZlDl8HvA","text":"libro","nlp":{"errors":[{"code":"unknown","message":"Something went wrong. We've been notified"}]}}}]}]}
200 POST /webhook
sha1=233aa902a413468d5b54936823817c186b707ac4
{"object":"page","entry":[{"id":"119739501385602","time":1656144786587,"messaging":[{"sender":{"id":"2532218000195687"},"recipient":{"id":"119739501385602"},"timestamp":1656144786267,"message":{"mid":"m_sUVjWbQuvk6DBoHfTdYcPpgJW8ioyQz7cGIF8C2zOa2Jm-zlXpg9V0TNeI7RMNF8N566i0Ge9AttutKGSeWl2Q","text":"immane","nlp":{"errors":[{"code":"unknown","message":"Something went wrong. We've been notified"}]}}}]}]}
200 POST /webhook
sha1=633a66c273897acc5deca476b5cf1e1ddeb4b914
{"object":"page","entry":[{"id":"119739501385602","time":1656144791222,"messaging":[{"sender":{"id":"2532218000195687"},"recipient":{"id":"119739501385602"},"timestamp":1656144790850,"message":{"mid":"m_8qQXqoS23ohSFcQydjEHkJgJW8ioyQz7cGIF8C2zOa32qac3VsG7QWmQmqGn8Ny77Mxw8S5jIsHd1CW8nbVJIw","text":"maledetto","nlp":{"errors":[{"code":"unknown","message":"Something went wrong. We've been notified"}]}}}]}]}
200 POST /webhook
sha1=87b31d189a32705929d2567fe69475b164b474b9
{"object":"page","entry":[{"id":"119739501385602","time":1656144799517,"messaging":[{"sender":{"id":"2532218000195687"},"recipient":{"id":"119739501385602"},"timestamp":1656144799187,"message":{"mid":"m_K3YpzX7cDkv9AFT4iI3fJ5gJW8ioyQz7cGIF8C2zOa1Bw-hd2diIzwviz3HBGjuXpHmH5nBH4zTcEcBmueZ7vQ","text":"merda","nlp":{"errors":[{"code":"unknown","message":"Something went wrong. We've been notified"}]}}}]}]}
200 POST /webhook

**Comment by matt0fer** [comment]
@patapizza Are there any updates? Should I give up Messenger integration and just call the API separately? :(

**Comment by patapizza** [comment]
Hi @matt0fer still looking into it. Thanks for your patience.

**Comment by matt0fer** [comment]
webhook is listening
sha1=5c68cc09292fe5ca5d46cd0aaf3bf7df3c944ac1
{"object":"page","entry":[{"id":"119739501385602","time":1657172286508,"messaging":[{"sender":{"id":"2532218000195687"},"recipient":{"id":"119739501385602"},"timestamp":1657172285943,"message":{"mid":"m_bPKmdSko1CWugwhvexxDzJgJW8ioyQz7cGIF8C2zOa1SQIHa45hMGFApVmd6MaXz0WfPQF8nZA_w8kyr-3Ra1g","text":"fa rima con facebook","nlp":{"errors":[{"code":"unknown","message":"Something went wrong. We've been notified"}]}}}]}]}
200 POST /webhook
sha1=e3f1f06720202b1467d2be36b9acc38d494823c3
{"object":"page","entry":[{"id":"119739501385602","time":1657172301393,"messaging":[{"sender":{"id":"2532218000195687"},"recipient":{"id":"119739501385602"},"timestamp":1657172301088,"message":{"mid":"m_0kqAGmCu-JcPIdvcHBQd1ZgJW8ioyQz7cGIF8C2zOa0D5vFPfh-H2mgmlCeN4Y0XEPJvX_ULHrQM1YbH_iBEmQ","text":"pollo","nlp":{"errors":[{"code":"unknown","message":"Something went wrong. We've been notified"}]}}}]}]}
200 POST /webhook
sha1=ea9032f07f18a90a4a4e907ad6b57eed21f59162
{"object":"page","entry":[{"id":"119739501385602","time":1657172304183,"messaging":[{"sender":{"id":"2532218000195687"},"recipient":{"id":"119739501385602"},"timestamp":1657172303825,"message":{"mid":"m_hWMcmhGB658m2rDSitR4iZgJW8ioyQz7cGIF8C2zOa3fqWNRabdXPJLAvQxIIKmGx9erP05MlraKq774XR7bQA","text":"pancetta","nlp":{"errors":[{"code":"unknown","message":"Something went wrong. We've been notified"}]}}}]}]}
200 POST /webhook
sha1=8cbcd537277d576fa747d9b7d61f994af2559dbb
{"object":"page","entry":[{"id":"119739501385602","time":1657172309155,"messaging":[{"sender":{"id":"2532218000195687"},"recipient":{"id":"119739501385602"},"timestamp":1657172308810,"message":{"mid":"m_JAPvnWFqhbwyn0OmizRFF5gJW8ioyQz7cGIF8C2zOa0KjtUXQpawbQAYtIskr8uF0A3PBUD3YVKLOrYQSlD4zg","text":"singolare","nlp":{"errors":[{"code":"unknown","message":"Something went wrong. We've been notified"}]}}}]}]}
200 POST /webhook
sha1=e17b08565e7a089c316e25a32fa60db7dbb45e1b
{"object":"page","entry":[{"id":"119739501385602","time":1657172311485,"messaging":[{"sender":{"id":"2532218000195687"},"recipient":{"id":"119739501385602"},"timestamp":1657172311113,"message":{"mid":"m_EjBCTEkosXNJ7G-l7MZWx5gJW8ioyQz7cGIF8C2zOa0dgRZLHfeeMYfRoF3Nv8ZmrtI25ykzxGtClHe9cWJVDA","text":"puerile","nlp":{"errors":[{"code":"unknown","message":"Something went wrong. We've been notified"}]}}}]}]}
200 POST /webhook
sha1=bd2e210f28c63efa76b35c1c9224555e53173874
{"object":"page","entry":[{"id":"119739501385602","time":1657172318233,"messaging":[{"sender":{"id":"2532218000195687"},"recipient":{"id":"119739501385602"},"timestamp":1657172317910,"message":{"mid":"m_wgVDowk7CQ04QcxBNiw9fZgJW8ioyQz7cGIF8C2zOa08S_uF0Ij_JhoduzJ0IM6_OkFMVPRIGTamKU4_FAnZ2w","text":"rime per puledro","nlp":{"errors":[{"code":"unknown","message":"Something went wrong. We've been notified"}]}}}]}]}
200 POST /webhook
sha1=9fe36469898dd22bb6d826d4da3da06f068a5c56
{"object":"page","entry":[{"id":"119739501385602","time":1657172321257,"messaging":[{"sender":{"id":"2532218000195687"},"recipient":{"id":"119739501385602"},"timestamp":1657172320971,"message":{"mid":"m_dhWbv4VciVQH1Go7n7kxBpgJW8ioyQz7cGIF8C2zOa1mH_Mq5VYXobp4jw4UyYCMNc1ievsYV3DguVJBE6mEsw","text":"satollo","nlp":{"errors":[{"code":"unknown","message":"Something went wrong. We've been notified"}]}}}]}]}
200 POST /webhook
sha1=0f8f8a74dbf34d93c036eb821ca630143b0ff3b6
{"object":"page","entry":[{"id":"119739501385602","time":1657172326722,"messaging":[{"sender":{"id":"2532218000195687"},"recipient":{"id":"119739501385602"},"timestamp":1657172326397,"message":{"mid":"m_HclrlZYsVRC0sz8QmDHyw5gJW8ioyQz7cGIF8C2zOa3e-BoOc2GjAa33Z_0TDZkBu7b2p50elBFavrkSVP89SA","text":"trinciapollo","nlp":{"errors":[{"code":"unknown","message":"Something went wrong. We've been notified"}]}}}]}]}
200 POST /webhook
sha1=8fb6edf2922ff0b68664c4b455578cd734ec7fca
{"object":"page","entry":[{"id":"119739501385602","time":1657172330686,"messaging":[{"sender":{"id":"2532218000195687"},"recipient":{"id":"119739501385602"},"timestamp":1657172330305,"message":{"mid":"m_cdSc76I2rHmkYm1EMUN95JgJW8ioyQz7cGIF8C2zOa1mHyrn4IOtNj59eOAFzlg9ACqu7y04mBMUudKONjgX1A","text":"fa rima con faccia","nlp":{"errors":[{"code":"unknown","message":"Something went wrong. We've been notified"}]}}}]}]}
200 POST /webhook
sha1=77c7659c5027f0a12308a77df1074e4202e41a59
{"object":"page","entry":[{"id":"119739501385602","time":1657172335224,"messaging":[{"sender":{"id":"2532218000195687"},"recipient":{"id":"119739501385602"},"timestamp":1657172334946,"message":{"mid":"m_ne6csTe5x9O7reyX7wXz75gJW8ioyQz7cGIF8C2zOa2gKeql1LqDfBYkKk_GI0bZxDBFzlyz7VnOSEg2rBA7IA","text":"rime per libro","nlp":{"errors":[{"code":"unknown","message":"Something went wrong. We've been notified"}]}}}]}]}
200 POST /webhook

**Comment by patapizza** [comment]
We should be back now. Sorry for the inconvenience.

**Comment by matt0fer** [comment]
webhook is listening
sha1=a01592cd3fe73fdfadc85a8d4847361dfee9c782
{"object":"page","entry":[{"id":"119739501385602","time":1658295972760,"messaging":[{"sender":{"id":"2532218000195687"},"recipient":{"id":"119739501385602"},"timestamp":1658295972330,"message":{"mid":"m_ZJ2DOdDDpnVXP-IzwWFQJJgJW8ioyQz7cGIF8C2zOa3iENXVk61qcWyt6iJiWPHsGhUxWXSIHiDGigFNro07KA","text":"Fa rima con test","nlp":{"errors":[{"code":"unknown","message":"Something went wrong. We've been notified"}]}}}]}]}
200 POST /webhook

Still not working :'( @patapizza

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
