### ISSUE TITLE
Wrong date returned in date interval

### ISSUE THREAD

**Issue by aya-labiba** [wit-ai/wit#2443]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
When a date interval is sent to the API, one day is added to the 'To' date
Also, the same issue in the ticket number #2442 is happening here. (Wrong date format)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Send: "I want to take a vacation from 07/08/2022 to 09/12/2022"

The from date is: 09/12/2022 (day: 9, month: 12)
Response returned from message API: "2022-09-13T00:00:00.000+03:00" (day: 13, month: 9)

Full Message API response: 
[Message API response.txt](https://github.com/wit-ai/wit/files/8768974/Message.API.response.txt)

**What is the expected behavior?**
The correct date to be returned 

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
468849228311171

**Comment by doggeral** [comment]
Same issue with https://github.com/wit-ai/wit/issues/2433, closed for dedup.
You can create your own entity to recognize the datatime as workaround.
