### ISSUE TITLE
Intent identifying issue

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2444]
Hi,

We have an app with AppId: 963220754340785. 
We have trained an intent 'Hi'. 
When we tried 'Tution fee' in understanding tab, it is returning 'Hi' intent instead of unrecognized (No intent is expected)
How to fix this issue?

Thanks.

**Comment by anjaly** [comment]
> Hi,
> 
> We have an app with AppId: 963220754340785. We have trained an intent 'Hi'. When we tried 'Tution fee' in understanding tab, it is returning 'Hi' intent instead of unrecognized (No intent is expected) How to fix this issue?
> 
> Thanks.

Any update?

**Comment by doggeral** [comment]
Usually you can add these utterance as "out_of_domain" and retrain the app to make sure the model can label these utterance as "out of domain"
