### ISSUE TITLE
URGENT URGENT URGENT URGENT URGENT BUG- Not getting reponse in the wit.ai message API

### ISSUE THREAD

**Issue by prateeknarayan** [wit-ai/wit#2445]
**Report a *bug***

**We are not getting any response in the APIs after provding Utterances for particulat intents**

**While hit the endpoint (https://api.wit.ai/message?q=Please stop) we are getting blank response from wit.ai end**
![image](https://user-images.githubusercontent.com/63106338/170985280-60a04005-e15c-47a6-965c-4525de9afcd8.png)

**We should get response like below attached screen shot**
![image](https://user-images.githubusercontent.com/63106338/170985563-fe07a412-1a2d-4bff-80c6-eeba9e18ae16.png)

**App ID - 222079316196879 & we need to get response in the wit.ai APIs**

**Kindly look into this and provide the soluton of it ASAP**

**Comment by prateeknarayan** [comment]
Team - Is there any update on this?

**Comment by prateeknarayan** [comment]
Team - Can we get the response on this?

**Comment by prateeknarayan** [comment]
Team - It's been a long time, when will you share the update on it?

**Comment by JaiBhatia-coder** [comment]
Hello Team
It's been really long we are waiting for your response could you please share an update on the same?

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
