### ISSUE TITLE
Date that contain 'May' is not returned 

### ISSUE THREAD

**Issue by aya-labiba** [wit-ai/wit#2446]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug 

**What is the current behavior?**
Whenever a date that contains the month 'May' is sent to the 'message' API, and empty response is returned from the API. It is working fine for all the other months.

Example:
May 2021:

![image](https://user-images.githubusercontent.com/99329638/171001076-e57e89b1-a739-481a-ac1d-326338b806e0.png)

September 2021:
![image](https://user-images.githubusercontent.com/99329638/171001130-cfe37d3e-dd82-4a17-a9b7-0a847ef4c3ec.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Send: May 2022

**What is the expected behavior?**
To return the date result for all months

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2278713975545975

**Comment by chessai** [comment]
This is a duckling issue, not a wit issue.

https://github.com/facebook/duckling/issues/565

**Comment by doggeral** [comment]
Close it since it's duckling issue.
