### ISSUE TITLE
Training scheduled 12 hours from now

### ISSUE THREAD

**Issue by eirikstein** [wit-ai/wit#2447]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
When I add a new utterance and want to train the app, the training is scheduled 12 hours from now. Instead of 11AM, it is scheduled 11PM.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Add new utterance and click Train. I'm in central european timezone and we use 24-hour clock, not 12 hour clock, don't know if that has anything to do with it.

**What is the expected behavior?**
To start training almost immediately.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1276122279586374

**Comment by nishsinghal20** [comment]
Hi @eirikstein! The training schedule is decided by our system based on the current load and the last training duration. So this is expected.
