### ISSUE TITLE
App is stuck on Training Ongoing

### ISSUE THREAD

**Issue by glcoan** [wit-ai/wit#2448]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
App is stuck on Training Ongoing

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
The app to finish training

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
845297083094464

**Comment by nishsinghal20** [comment]
Hi @glcoan! This issue should now be fixed. Please let us know if you're still running into this.
