### ISSUE TITLE
Some utterances give error "Request Stack Trace"

### ISSUE THREAD

**Issue by eirikstein** [wit-ai/wit#2449]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
We have an utterances for "Do you hear me?", "Can you hear me", as well as "Do you see me", "Can you see me" etc. These utterances have the intent "patient_sense". In Unity, when sending the utterances with Understanding Viewer, it works fine, but when recording them, it almost always fails. In the console we can see this error: 
![2022-06-03 09_42_33](https://user-images.githubusercontent.com/71495314/171811410-98eccff0-435c-4c35-a324-79024580e4c2.jpg)

Other times the WitResponseNode["text"] is just empty.

We only seem to have this problem with the utterances with the intent "patient_sense", and the strange thing is, if we just say "you see me?" or "you hear me?", it seems to work like intended, but if we say "Do you hear me?", "Are you able to hear me?" etc. it fails.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Activate the recording and say "Can you hear me?", it should fail and give error message in console. Say just "You hear me?" should work.

**What is the expected behavior?**
Have the same result when saying "Do you hear me?" as when you say "You hear me?".

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1276122279586374

**Comment by eirikstein** [comment]
I have also tried making a new app with just the utterances mentioned above and the inten "patient_sense". Then it seems to work fine. But when I start to add new intents with corresponding utterances, it starts failing again.

**Comment by nishsinghal20** [comment]
Hi @eirikstein! Thank you for reporting this. Let us investigate this issue and get back to you.

**Comment by yolanother** [comment]
@eirikstein what version of wit-unity are you using? Is this through the Voice SDK or an older version of wit-unity? This should be fixed on the latest TOT wit-unity and will be fixed in v41 of Voice SDK. We also have a temporary server side fix for this issue and it should just start working regardless of the version of wit-unity or voice sdk when the server fix deploys.

**Comment by eirikstein** [comment]
Hi @yolanother, We have been using the Voice SDK v38. I can try to upgrade. Do you know when v41 of Voice SDK will be released?

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
