### ISSUE TITLE
What audio quality should I be sending for speech recognition?

### ISSUE THREAD

**Issue by dzlandis** [wit-ai/wit#2451]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question

What audio quality should I be sending for speech recognition?
I was wondering specifically, what is the minimum audio quality I can send for speech recognition while still maintaining good quality recognition. Also, what is too high of a quality to be sending for speech recognition?

**Comment by nishsinghal20** [comment]
Hi @dzlandis! This public documentation on the POST /speech API has some information about the speech formats and specifications. Let us know if this helps your case?
https://wit.ai/docs/http/20220503/#post__speech_link

**Comment by dzlandis** [comment]
@nishsinghal20 thank you, that was helpful. I have a few follow up questions:
1. Does using a stream mean you can only process 10 seconds of audio instead of 20 seconds of audio? Or am I misunderstanding that.

2. How do the parameters used (bits, rate, etc) effect the quality of the speech recognition?

Any help is greatly appreciated.

**Comment by nishsinghal20** [comment]
Hi @dzlandis! 
1. We process max 20 sec of audio duration, both streaming non-streaming.
2. Parameters shouldn't affect the quality, but for better latency, it's recommended to use the specifications mentioned in the API documentation. See API docs https://wit.ai/docs/http/#post__speech_link 

> "For faster processing, we highly recommend to use signed-integer 16 bits, 16k sample rate and little endianness, for either raw, flac or wav file formats."

**Comment by nishsinghal20** [comment]
A little more clarification on the 10 seconds:
Each audio chunk can be at most 10 seconds, but the total audio duration is limited to 20 seconds
