### ISSUE TITLE
When training a new expression under an intent, the other expressions training changes 

### ISSUE THREAD

**Issue by aya-labiba** [wit-ai/wit#2452]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
When sending the expressions that are under the 'Main_Menu_AR' Intent, the intent is returned correctly with the highest value in the intents list, but whenever we try to train a new expression under it, 'Main_Menu_AR' is not returned as an intent of these expressions, as well as for the new expression.
When checking the training status, it says that it's complete.

And after a while, it gets back correctly to how it was before.

Example:
When sending: "السلام عليكن", it used to return 'Main_Menu_AR' as the top scoring intent:
Timestamp: 6/6/2022 1:19 PM
[Message API.txt](https://github.com/wit-ai/wit/files/8844407/Message.API.txt)

We tried to train the below expression: 'مراحب', then the top scoring intent returned for 'السلام عليكن' changed:
Timestamp: 6/6/2022 3:33 PM
[Message API - السلام عليكن.txt](https://github.com/wit-ai/wit/files/8844418/Message.API.-.txt)

The result for 'مراحب'
[Message API - مراحب.txt](https://github.com/wit-ai/wit/files/8844432/Message.API.-.txt)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Send one of the below:
'مراحب'
'السلام عليكن'
'هلا'
'مرحبا'

**What is the expected behavior?**
The trained intent to not change after training new expressions.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1682759491848662

**Comment by doggeral** [comment]
Do you mean once you retrain the model, these utterance can't be picked up by the new model? 
Per your description, looks like the cold start issue. Once you complete your model training, the new model takes some time to be loaded by system, the first few request might get empty response. That's why you can get the right intent after a while.
