### ISSUE TITLE
API Versioning Question

### ISSUE THREAD

**Issue by dzlandis** [wit-ai/wit#2453]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question

What is the easiest way for me to know when a new API version exists? Where can I find information relating to all of the versions?
Any help is greatly appreciated.

**Comment by patapizza** [comment]
Hi @dzlandis, there are 2 ways: one is to go to https://wit.ai/docs/http, which will redirect you to the latest HTTP API docs. Another one is to look at the *What's New* section of https://wit.ai/apps, where we send updates of top API changes. Psst - we've just released live understanding ;-)
