### ISSUE TITLE
Training Ongoing for the past 11 hours

### ISSUE THREAD

**Issue by M3Z47** [wit-ai/wit#2456]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
I need to report a bug.

**What is the current behavior?**
The wit App is stuck on training for the past 11 hours.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Training should have been completed already.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID: 6924265890981719
App name: prod_final_new

Looks like the app has frozen. Please unfreeze it.
Thanks.

**Comment by PanoSpent** [comment]
This issue just keep happening for the past year maybe more. The only way i found to unfreeze the app is download it and then create a new one with these data. Can anyone from wit just comment on this? This issue is continuing for so many months nad noone is telling anything,

**Comment by yuzh174** [comment]
I am looking at it now

**Comment by M3Z47** [comment]
Please also look into the issue of Wit app adding gibberish synonyms after each training. These gibberish values need to be removed after going through each keyword manually.
Thanks.

**Comment by yuzh174** [comment]
Could you give me an example of unexpected synonyms? Or do you mean none of the keywords should contain any synonyms?

**Comment by PanoSpent** [comment]
Hi @yuzh174 my app ids that remain stuck for over a month now are the following:

- 2092345764240756
- 339053820531515

**Comment by yuzh174** [comment]
Hi @M3Z47, you app 6924265890981719 is training complete now.

**Comment by yuzh174** [comment]
@PanoSpent, Let me check these two apps

**Comment by yuzh174** [comment]
@PanoSpent both of the apps complete the training now.

**Comment by PanoSpent** [comment]
Thank you @yuzh174 . Bu twhy is this keep happening? Should we do something different?

**Comment by M3Z47** [comment]
@yuzh174 Thanks!
Yeah, I am attaching some from my list of gibberish synonyms that I remove by a code:
'as', 'fo', 'ings', 'ngs', 'gs', 'ted', 'an', 'ball', 'ks', 'ers', 'tors', 'iators', 'ons', 'ns', 'gons'
What happens is this:
Suppose I have a keyword: leg-spinners
Its synonyms are: "leg spin", "leg spinner", "leg spinners", "leg-spin", "leg-spinner", "leg-spinners", "leggie", "legspin",                   "legspinner", "wrist spinner"
After training with utterances having this particular keyword, gibberish values like: "ers", "spinn", "ner", "nner", etc. are added automatically as synonyms to the keyword "leg-spinner".
These I have to remove after every training. However, the gibberish synonyms are added only on those entities' keywords which are in the utterances that are being trained, not to any other entities keywords.
Hope I have explained my issue clearly. Thanks.

**Comment by yuzh174** [comment]
> Thank you @yuzh174 . Bu twhy is this keep happening? Should we do something different?

We are getting the root case of this. Once we better understand the issue, it should be fixed on our side. In the meantime, please post issues for stuck training and we will resolve them for you manually.

**Comment by yuzh174** [comment]
> @yuzh174 Thanks! Yeah, I am attaching some from my list of gibberish synonyms that I remove by a code: 'as', 'fo', 'ings', 'ngs', 'gs', 'ted', 'an', 'ball', 'ks', 'ers', 'tors', 'iators', 'ons', 'ns', 'gons' What happens is this: Suppose I have a keyword: leg-spinners Its synonyms are: "leg spin", "leg spinner", "leg spinners", "leg-spin", "leg-spinner", "leg-spinners", "leggie", "legspin", "legspinner", "wrist spinner" After training with utterances having this particular keyword, gibberish values like: "ers", "spinn", "ner", "nner", etc. are added automatically as synonyms to the keyword "leg-spinner". These I have to remove after every training. However, the gibberish synonyms are added only on those entities' keywords which are in the utterances that are being trained, not to any other entities keywords. Hope I have explained my issue clearly. Thanks.

Thanks for the explanation. Yes it is clear. Is this a real entity that I can investigate? Could you also share with me the appID (if it's not 6924265890981719) and the name of the entity?

**Comment by M3Z47** [comment]
Hello,
Yeah, its the same app and the keyword "leg-spinner" is from this app itself. Right now I have not pushed any new query to train, will share when I train again the gibberish synonyms. Also, I am making a new app, if I encounter this problem in the new app, I will notify for sure.
Thanks.

**Comment by yuzh174** [comment]
> Hello, Yeah, its the same app and the keyword "leg-spinner" is from this app itself. Right now I have not pushed any new query to train, will share when I train again the gibberish synonyms. Also, I am making a new app, if I encounter this problem in the new app, I will notify for sure. Thanks.

Thanks. For now, I would close this thread since it is about training ongoing. You can open a new issue once you have a repro. It's easier to track that way. We can jump in to investigate. Please also include the entity name for the keyword in your report. You can also link to this task for reference.
