### ISSUE TITLE
Question about Time entity

### ISSUE THREAD

**Issue by aya-labiba** [wit-ai/wit#2457]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question

**What is the current behavior?**
My questions is about the workaround suggested in the below ticket:
#2434

"create the entity for time, and label the timestamp in the training utterance and retrain your model"

Can you please provide more clarification on how this can be done?

**Comment by yuzh174** [comment]
Hi @aya-labiba , just like what you did to other utterances here, you can train this entire utterance "يجب أن آخذ مغادرة عاجلة اليوم من الساعة 2 الظهر حتى 4 مساءً" (copied from your original question), then highlight the part of times and mark them as wit/datetime entity. You need to mark both of them. 

Similar to the one below but you need to also do the same for "4pm" . 
![Screen Shot 2022-06-09 at 10 48 37 AM](https://user-images.githubusercontent.com/73909056/172911761-17cc80e2-7777-4fbe-a4ca-ffa6b2cde18e.png)

**Comment by aya-labiba** [comment]
Hi @yuzh174, please note that I am already doing this, but I have some special cases that are being returned wrong. The answer to my ticket was that  the built-in-entity is not well supported for Arabic language. And the below workaround was suggested:

create the entity for time, and label the timestamp in your training utterance.

This is a screenshot of the expression after training the same way you suggested in your comment, but the same issue is still there:

![image](https://user-images.githubusercontent.com/99329638/173221294-eb4e6331-a2e5-4021-ba17-ecc4bde60da6.png)

We want to know what is the difference between what we are already doing and the suggested work around?

**Comment by patapizza** [comment]
Hi @aya-labiba,

`wit/datetime` is powered by [Duckling](https://github.com/facebook/duckling). Feel free to submit a PR to help improve the resolution of this entity.
