### ISSUE TITLE
Returning wrong entity values

### ISSUE THREAD

**Issue by aliugur** [wit-ai/wit#2458]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a *bug*

**What is the current behavior?**
It is returning wrong entity value

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Entity "serialNumber" has 8 values and its type is "Free Text & Keywords". When I ask with "**2ua8511qjp**", AI returns value: "**2ua8511qjj**" which is one of the values.

**What is the expected behavior?**
It should return "2ua8511qjp" as it is a new value

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1323686431435891

**Comment by yuzh174** [comment]
Hi @aliugur , just to confirm:
You have multiple (possibly infinite numbers of) serialNumbers. In the wit.ai web tool, you have picked and trained a few of them. Now you are testing with new values that's not trained. The expectation is to return with what ever value is in the utterance.

For example, you have trained "pcinfo 2ua8511qjj". Now if you test with "pcinfo 2ua8511qjp", the result entity value is "2ua8511qj" instead of "2ua8511qjp"

We will take a look. Thanks for reporting

**Comment by ghost** [comment]
> **Do you want to request a _feature_, report a _bug_, or ask a _question_ about wit?** Report a _bug_
> 
> **What is the current behavior?** It is returning wrong entity value
> 
> **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.** Entity "serialNumber" has 8 values and its type is "Free Text & Keywords". When I ask with "**2ua8511qjp**", AI returns value: "**2ua8511qjj**" which is one of the values.
> 
> **What is the expected behavior?** It should return "2ua8511qjp" as it is a new value
> 
> **If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.** 1323686431435891

**Comment by yuzh174** [comment]
The issue is that you are using "Free Text & Keywords". Changing it to to just "Free Text" solves the problem. cc: @doggeral

**Comment by aliugur** [comment]
> The issue is that you are using "Free Text & Keywords". Changing it to to just "Free Text" solves the problem. cc: @doggeral

Isn't "Free Text & Keywords" like this: return value if it is in the list, if not, return new value and add to the list?
It seems ok with "Free Text" now but before I was using with the other option. What has changed?

**Comment by yuzh174** [comment]
If you enabled keywords, it will try its best to return an already trained value, in this case, that's not what you want. 
I don't think there is any changes. It's possible the training make the keyword detection more sensitive.

**Comment by yuzh174** [comment]
Close as resolved.
