### ISSUE TITLE
Websockets with /speech

### ISSUE THREAD

**Issue by dzlandis** [wit-ai/wit#2460]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question

Hi there, I was wondering if it was possible to use websockets with speech recognition or if its just a REST API. Please let me know, thanks.

**Comment by yuzh174** [comment]
Hi, we only support REST API, no websockets. That being said, we support http2, so if your need is just bidirectional streaming, that should be supported.
