### ISSUE TITLE
How do you train when an utterance concatenates two equally valid intents?

### ISSUE THREAD

**Issue by baroquedub** [wit-ai/wit#2462]
***question* about wit?**

I've already trained my app to recognise "No I'm not" as an intent (wit$negation) and "Leave me alone" as another intent (Custom: Stop).

However when I say "No I'm not. Leave me alone" the utterance appears as Out of Scope. How do I train the app in the Understanding section, so that both intents are recognised?

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID:
586523202720149

**Comment by patapizza** [comment]
Multiple intents per utterance are not supported as-is in the data model. A way to get around that would be to split your intents into binary traits. The training would likely require more out of scope utterances to get a good precision.

Hope this helps.

**Comment by baroquedub** [comment]
Thanks, although my apologies, I'm not sure I fully understand the workaround.

Are you saying that I should add Traits as well as my Intents? Then train with one phrase as the Intent and the other as a Trait?

I'm not sure why you say that " training would likely require more out of scope utterances to get a good precision".

**Comment by baroquedub** [comment]
@patapizza So sorry to ping you (I'm guessing you might not get a notifications after you closed the ticket)

Would you mind clarifying what you meant? I'm unsure how to proceed with training those 'double intents'.
