### ISSUE TITLE
Issue with triggering Entity

### ISSUE THREAD

**Issue by HornDaneth** [wit-ai/wit#2464]
Hi

We are facing an issue with the Khmer wit workspace.

When i tried to input the answer which are not trained in entity in workspace via API, I am getting the intent and its confidence level 100% for the trained entity. however it is responded intent which is not match to our expectation output.

Below is an example of response, 

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/12178991/173512655-2c8c548b-5002-4e5b-bd8a-3eb2c4a80dd3.png">

Can you please look into the issue with high priority, as it is affecting our business.

Our AppId is 555590445502765

**Comment by HornDaneth** [comment]
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/12178991/173515080-ebd9cd36-3c21-4ba6-a721-9e58c5e1529c.png">

**Comment by wangzhenict** [comment]
Hi @HornDaneth ,
as my understanding, you were saying that the 100% is not expected, right? or the entity was totally wrong?
BTW, can you also paste the text you input. 

Thanks,

**Comment by HornDaneth** [comment]
Hi @wangzhenict , thanks for your response. 
The confidence showed 100%. The response message from bot is not our expectation. Let say when user input "Primary School", the bot should response "A"; however the bot response "B" instead of "A" which is the correct one.

**Comment by HornDaneth** [comment]
<img width="903" alt="image" src="https://user-images.githubusercontent.com/12178991/173725114-21aabedd-10a1-486f-97aa-7506fe26e6dc.png">

i just found that the input as number always response wrong both english and khmer language.

**Comment by doggeral** [comment]
@HornDaneth you can add the training utterance and retrain your model

**Comment by HornDaneth** [comment]
thanks
