### ISSUE TITLE
Issue with Response with input Number 

### ISSUE THREAD

**Issue by HornDaneth** [wit-ai/wit#2465]
We are facing an issue with the wit workspace.

When i tried to input number the answer which are not trained in entity in workspace via API, I am getting unexpected output.

below screenshot is the issue when user input number: 

<img width="898" alt="image" src="https://user-images.githubusercontent.com/12178991/173766095-e1e7aecf-5aef-4939-a97f-041f9fcda961.png">

Can you please look into the issue with high priority, as it is affecting our business.

Our AppId is 162781225974874

**Comment by doggeral** [comment]
@HornDaneth do you mean the number can't be recognized correctly? I tested on wit.ai, it can be recognized correctly. 
<img width="762" alt="image" src="https://user-images.githubusercontent.com/1651153/173926650-8bf7a5d2-94a4-4dfb-8e98-e3d07fe6646f.png">

**Comment by HornDaneth** [comment]
@doggeral, it worked fine now. yesterday i tested typing with number above, it also results other intent. thanks for your reply.
