### ISSUE TITLE
App stuck in training

### ISSUE THREAD

**Issue by unu-1** [wit-ai/wit#2467]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
App training continues endlessly.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
After training utterances through the UI, the training starts but does not end. Even though I have been training new utterances on multiple days past weeks, the following message is displayed while training is ongoing, which makes me think that no training has been successful past weeks:
<img width="251" alt="image" src="https://user-images.githubusercontent.com/54986487/174024244-bce72061-f504-4199-b6d3-b50d769c9047.png">

**What is the expected behavior?**
Training completion.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2599960866722323

**Comment by Toba99** [comment]
hello I'm also experiencing this issue. this is my app id - 624225555631153

**Comment by wangzhenict** [comment]
@qfavor , it seems you have so many utterances, so slow training is expected. is it still blocking? if so, please let me know and I'll prioritize the debug. Thanks

**Comment by wangzhenict** [comment]
@Toba99 I restarted your training and it succeeded. let me know if you still see something wrong.
