### ISSUE TITLE
Gibberish synonyms being added automatically

### ISSUE THREAD

**Issue by M3Z47** [wit-ai/wit#2468]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug

**What is the current behavior?**
After every training, gibberish synonyms get added to keywords.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
No synonyms should be added automatically unless specified.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID: 424214919568822
Name: prod_app_3

e.g. In the entity: player_role, keyword: leg-spinners. After training, these gibberish synonyms have been added: nner, inner, inners, in, n, etc.

**Comment by M3Z47** [comment]
@yuzh174 Please have a look. Thanks.

**Comment by M3Z47** [comment]
Hello,
I have been waiting and had put my app's training on hold as I thought somebody would have a look. It looks like I will have to remove the gibberish synonyms for now and continue with the training. I am attacjing a scrrenshot, if anyone needs some info of the gibberish synonyms.
Thanks.
![Screenshot from 2022-06-26 18-17-00](https://user-images.githubusercontent.com/36403064/175817645-760a0786-5c81-4307-9dfd-8872a51e8322.png)

**Comment by wangzhenict** [comment]
Hi @M3Z47 , I'm looking into it. after you removed the gibberish synonyms and re-training, are these gibberish ones still there?

**Comment by M3Z47** [comment]
I removed these synonyms for now. They re-appear after every training. Will ping again after training is complete and gibberish synonyms added.

**Comment by M3Z47** [comment]
Hello,
Could you also delete these 2 apps (I am unable to delete these, its throwing errors):
1642059329521409 - staging_final
500468024721873 - staging_new
Thanks.

**Comment by wangzhenict** [comment]
> 

I've tried to delete 1642059329521409 - staging_final, can you verify if it was gone?
if yes, I'll delete next one.

**Comment by M3Z47** [comment]
Yes, its gone. Thanks!

**Comment by wangzhenict** [comment]
I've deleted 500468024721873 as well.

**Comment by M3Z47** [comment]
Thanks. Could you please unfreeze this app: 6924265890981719
It is stuck in training since the past 2 days.

**Comment by M3Z47** [comment]
Thanks. Please look into the gibberish synonyms problem as well, it is persisting.

**Comment by doggeral** [comment]
Could you add the gibberish utterances as out_of_domain and retrain your app? Usually it can fix the issue.
