### ISSUE TITLE
App stuck on training

### ISSUE THREAD

**Issue by FranciscoAX** [wit-ai/wit#2471]
Do you want to request a feature, report a bug, or ask a question about wit?
Bug

What is the current behavior?
App stuck on training.

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
After adding entities and submitting the utterances for training, the app got stuck on "training ongoing" for almost 24 hours now. The previous training took only 16 seconds. 

What is the expected behavior?
Training completion.

If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.
1942615845923527
Edit: 3427009277526715 is stuck as well

**Comment by doggeral** [comment]
your app has been fixed.
