### ISSUE TITLE
Api does not return app information (GET) when using app_id received at the time it was created through the api (POST)

### ISSUE THREAD

**Issue by glcoan** [wit-ai/wit#2472]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**

When I create a new app, the api returns the app_id as a uuid, but when using this uuid to make a GET call specific to this app, I get the error: {"error":"App not found","code": "not found"}

Just informing the app_id that is inside https://wit.ai/apps/app_id/settings in the api call, I get the app information

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Create a new app through the api, then use the credentials returned to retrieve the information from the same app that was just created

**What is the expected behavior?**
I expect to receive something similar to the following:
{
    "name":"myapp",
    "lang":"pt",
    "private":true,
    "created_at":"...",
    "last_training_duration_secs":0,
    "will_train_at":"...",
    "last_trained_at":"...",
    "training_status":"done",
    "id":"..."
}

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
I'm trying with multiple apps, the problem is not related to just one specific app

**Comment by glcoan** [comment]
APP ID of one of my apps:

App_id which is in /settings: 553991222948913

App_id received on app creation via api: 775a98b2-8674-4b0d-b99e-eedaee72b796

**Comment by agency8** [comment]
I have the same problem

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
