### ISSUE TITLE
Contributors

### ISSUE THREAD

**Issue by dracero** [wit-ai/wit#2473]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by dracero** [comment]
I was trying to add some contributors but I could not find them with their Facebook's username in Wit.ai Setting contributors pane.
Does anyoine have some advide in order to help me.

Thanks in advance.

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
