### ISSUE TITLE
Something went wrong. We've been notified

### ISSUE THREAD

**Issue by grenoblicronYT** [wit-ai/wit#2474]
Hello I am here because I need your help.
When I send text to wit ai it shows the error 
`[wit] [message] Error: Something went wrong. We've been notified`
I'm looking for it and apparently it applies when you've exceeded the allowed quota, but I did not use this app and wit for a mouth or more and so I don't undestand.
Here is my app id : 371599661627993

**Comment by macuna** [comment]
I'm having the same issue, I have several  apps in production that works well, while in others like this 3293800800852131, I'm getting constantly the following error:
```
{
	"error": "Something went wrong. We've been notified",
	"code": "unknown"
}
```

**Comment by crisgio24** [comment]
Hello, I have the same problem, I constantly receive the same problem.

We would appreciate any feedback to provide a solution.

{
    "error": "Something went wrong. We've been notified",
    "code": "unknown"
}

**Comment by patapizza** [comment]
Thanks for reporting. Closing in favor of https://github.com/wit-ai/wit/issues/2480
