### ISSUE TITLE
Sent audio file is not uploaded fully.

### ISSUE THREAD

**Issue by IntegratedSalad** [wit-ai/wit#2476]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
*bug*

**What is the current behavior?**
I'm sending a .wav file of a friend speaking for 8 seconds. Transcribed text covers only 3 seconds of the audio - I've checked on wit.ai's app page, in "understanding" tab, and audio clips that there are, are only 3 seconds long (instead of 8, as the original audio), sometimes 4~5. The language of this app is polish (pl).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Here's the pastebin: https://pastebin.com/PZiyqFk5 . I've checked if I send/stream the file correctly, and it doesn't seem to be a problem.
**What is the expected behavior?**
It would be to have a transcript of the whole 8s long audio, and on the wit.ai app page, I would hear the audio file in its entirety.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
422199539556541

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
