### ISSUE TITLE
Wrong Trait returned from the curl URL

### ISSUE THREAD

**Issue by Hanssenzhang** [wit-ai/wit#2477]
I have bug, when i traning to trait and validate some sentence the trait is training completed but not showing  trait value when running cURL online, i trying more time delete and make a new utterance with a trait again but get same problem no value trait showing but the other like entities and intents showing! 

Please do verify the same and find the snapshot as an example App Id: 890556582343769

that'is my training completed issue status, when adding  trait is have wit/on value is on

![Screenshot 2022-06-28 102632](https://user-images.githubusercontent.com/108278316/176085757-babb0175-8b60-46f0-b151-e14cda02062d.jpg)

that'is my curl online status, don't have value trait

![Screenshot 2022-06-28 103101](https://user-images.githubusercontent.com/108278316/176086074-4127e286-23ee-4354-9cd5-46c631bbdccb.jpg)

**Comment by jayyteee** [comment]
Hi @Hanssenzhang, I took a look and was able to see this issue for your app. I would first try to train a few more similar phrases to see if it can learn to correctly identify the wit on/off trait in your utterances - but if that doesn't work I would try to create your own trait. 

If you go to the wit.ai trait page in your app, you can create a new trait and add in the possible values, which look like would be 'nyalakan' and 'matikan', and then retrain the utterances using the new trait.

**Comment by Hanssenzhang** [comment]
Thankyou Very Much, @jayyteee, i try your solution and the value is now showing!
![image](https://user-images.githubusercontent.com/108278316/176620605-1b511a8d-5bf7-495a-ba6c-b39ee1fd9000.png)
