### ISSUE TITLE
[URGENT] Facing issue with /message api

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2479]
Hi team,

We had one app which is using wit as nlp(APPID: 363040778909543). This was already running app and we trained one new question today. After that when we tried the question in bot we are getting the below error from /message api. We are using npm node-wit
Getting the same error for previously trained inputs also.

Error => Something went wrong. We've been notified

We have an urgent demo with client. Can u pls check ASAP and fix the issue.

In all the wit apps we are facing the same issue

**Comment by patapizza** [comment]
Thanks for reporting, closing in favor of https://github.com/wit-ai/wit/issues/2480.
