### ISSUE TITLE
api.wit.ai/message returns WARNING: DEPRECATED

### ISSUE THREAD

**Issue by savvopoulos** [wit-ai/wit#248]
curl   -H 'Authorization: Bearer (omitted)'   "https://api.wit.ai/message?v=20160627&q=I+wasn't+for+a+walk"

Queries to /message return a deprecation warning, despite using today's date. I can't find anything in the documentation. Should I be worried? What is getting deprecated and what's the new alternative?

{
  "msg_id" : "(omitted)",
  "_text" : (omitted),
  "outcomes" : [ {
    "_text" : (omitted),
    "confidence" : 0.993,
    "intent" : "reportNotDone",
    "entities" : { }
  } ],
  "WARNING" : "DEPRECATED"

**Comment by savvopoulos** [comment]
ping? Would be very comforting to know that our service won't suddenly explode :-)

**Comment by l5t** [comment]
It won't, sorry for the late reply. It's because you have an old app (without Stories). We don't deprecate the API until we have a migration feature from old app to new app.

**Comment by savvopoulos** [comment]
Thank you 👍

**Comment by kmhoran** [comment]
Is this warning still relevant now that stories are going away?
https://wit.ai/blog/2017/07/27/sunsetting-stories

**Comment by l5t** [comment]
Yes it is... it is more about the app before we created Stories (with intent as first class citizen) vs apps now with intent as trait entities... see below an old app with an intent tab
![image](https://user-images.githubusercontent.com/6992759/33137088-cfc9a458-cf5b-11e7-9b20-c3bdc8532640.png)
