### ISSUE TITLE
[URGENT]   /message api error

### ISSUE THREAD

**Issue by jijoamt** [wit-ai/wit#2480]
We are getting error for the /message API . can you please check it urgently. Our chatbots are not working now.
See the attached screen shot
![wit-error](https://user-images.githubusercontent.com/700933/177928961-575588bc-48a0-4a54-af11-921ffed8e82b.png)

**Comment by macuna** [comment]
The same here, the app id is 3293800800852131

**Comment by nclifton** [comment]
It appears to be intermittent, if we use a retry-wait loop, we can eventually get a response. It's affecting all our apps, so it would not appear to be app specific.
Also occasionally seeing an SSL error.

**Comment by macuna** [comment]
I have some apps that works without problem, but others not. Yes I you put a retry-wait loop it eventually works in the 3rd try but that makes the response terribly slow.

**Comment by FranciscoAX** [comment]
Also experiencing the same issue and it also appears to be intermittent. 

App id: 3427009277526715

**Comment by TimDiaz** [comment]
Same intermittent issue for intent matching, also occasionally seeing SSL error. 

App Id: 994708554407758

**Comment by gnovis** [comment]
I have the same issue with my apps. It seems to be similar problem as #2324 #2327 #2315 half year ago.

**Comment by CannonFodderr** [comment]
We are experiencing same issue with multiple wit apps since yesterday (About 12 - 13 hours ago), seems like wit api is responding with 500 status code. service is currently not usable. It comes back from time to time and then fails again.
![wit error](https://user-images.githubusercontent.com/36086310/177976604-4fa47685-f735-4fc0-b8be-4898bdef5479.jpeg)

**Comment by mohansr03** [comment]
Happening for my apps as well, still not resolved

**Comment by georgiep** [comment]
Same issue, App id 132199201885007

**Comment by crisgio24** [comment]
Hello, I have the same problem, I constantly receive the same problem.

We would appreciate any feedback to provide a solution.

{
"error": "Something went wrong. We've been notified",
"code": "unknown"
}

**Comment by patapizza** [comment]
Thanks for reporting, looking into it.

**Comment by serdalbayram** [comment]
the same for my apps (e.g. App Id: 1622020321212473)
Return message : Body:{"error":"Something went wrong. We've been notified","code":"unknown"}

**Comment by alxferraz** [comment]
same here App Id:810774776498106

**Comment by patapizza** [comment]
We've identified the issue and are deploying a fix. Thank you for your patience.

**Comment by jijoamt** [comment]
> We've identified the issue and are deploying a fix. Thank you for your patience.

@patapizza Do you have an estimated timeline for the fix? We are having high pressure from our customers as their chatbots are not working. Please fix the issue at the earliest and let us know. Thanks

**Comment by patapizza** [comment]
We should be back since 10pm PT yesterday. Reliability slowly making its way back up: https://wit.ai/status. Sorry for the inconvenience.
