### ISSUE TITLE
Live utterances in Khmer Wit Workspace 

### ISSUE THREAD

**Issue by HornDaneth** [wit-ai/wit#2481]
Hi

We are facing an issue with the Khmer wit workspace Live utterances. It does not have the trained data. We noticed that when the live utterances does not show the trained data, our chat bot always has issue with response, wrong response to the input intent. 

Below is an screenshot of live utterances,

<img width="1333" alt="image" src="https://user-images.githubusercontent.com/12178991/177967130-4e7fa01d-8ddd-4568-a0be-59805832eb80.png">

Our AppId is 555590445502765

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
