### ISSUE TITLE
wit detects different intents for the same text 

### ISSUE THREAD

**Issue by AlexisNichel** [wit-ai/wit#2484]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a Bug

**What is the current behavior?**
wit detects different intents for the same text even though it is only trained for one

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Write the word hello in the field several times (Same error is observed with the API)

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1856185531061946

<img width="1001" alt="Captura de Pantalla 2022-07-08 a la(s) 12 14 12" src="https://user-images.githubusercontent.com/15020002/178030781-469c2678-6c94-4ac0-b988-40ae196b41f5.png">
<img width="1010" alt="Captura de Pantalla 2022-07-08 a la(s) 12 14 36" src="https://user-images.githubusercontent.com/15020002/178030787-e766d343-8d6e-4abc-859c-5b86db678f3e.png">

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
