### ISSUE TITLE
Utterances disappear in Training

### ISSUE THREAD

**Issue by nickcbarone** [wit-ai/wit#2485]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
On the Understanding page, when I'm training the bot, the utterances disappear. I wait for a 20-30 seconds and then they reappear. I cannot train my bot efficiently when the utterances keep disappearing.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Go to the Understanding page
2. Start training the utterances

**What is the expected behavior?**
The expected behavior is that the utterances remain on the screen until I click the Train and Validate button.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID: 1650554041800318
![ezgif com-gif-maker (5)](https://user-images.githubusercontent.com/11508524/178046866-b54ebbfa-8b5d-494e-80a7-63efea93195e.gif)
![ezgif com-gif-maker (6)](https://user-images.githubusercontent.com/11508524/178046992-0e27f4a7-b02b-4d99-ada4-44ebfda8233b.gif)

**Comment by nickcbarone** [comment]
Any updates here?

**Comment by nickcbarone** [comment]
Hello, please help. This issue is continuing to happen.

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
