### ISSUE TITLE
Intermittence on Wit's API.

### ISSUE THREAD

**Issue by rsmngdlmx** [wit-ai/wit#2486]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
Starting on yesterday, we encountered an intermittence when connecting to your API: we randomly get a 500 error every few requests. The error message reads _**"Something went wrong. We've been notified"**_ and the error code is _**"unknown"**_. Although the error's not constant, this intermittence is hitting our production app.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Every few requests we make to the endpiont in **_https://api.wit.ai/message?q=someMessage_** we get a **500 error** response. Even sending the exact same request with the same text many times, some requests return a successful 200 response and some others, a 500 error.

**What is the expected behavior?**
The expected behaviour would be to always get a successful 200 response for every request made to the endpoint mentioned above.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2845127739086451

**Comment by serdalbayram** [comment]
the same for my apps (e.g. App Id: 1622020321212473)
Return message :  Body:{"error":"Something went wrong. We've been notified","code":"unknown"}

**Comment by patapizza** [comment]
We're actively working on this: https://github.com/wit-ai/wit/issues/2480
