### ISSUE TITLE
I Receive this error Along Today "wit.wit.WitError: Wit responded with status: 500 (Internal Server Error)" and I need Solution 

### ISSUE THREAD

**Issue by ghost** [wit-ai/wit#2487]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by patapizza** [comment]
We're working on it: https://github.com/wit-ai/wit/issues/2480
