### ISSUE TITLE
App stuck in training repeatedly

### ISSUE THREAD

**Issue by M3Z47** [wit-ai/wit#2488]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
App repeatedly gets stuck in training, even if sending only 250 utterances to train

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Training should be completed within few hours and not days.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
6924265890981719

**Comment by M3Z47** [comment]
@wangzhenict

Please unstuck the app.... Need urgently..

**Comment by doggeral** [comment]
Retrain your model from CLI, and your model's state is good now. 
But per the UI, seems we can't trigger model training from utterance tab. We'll do the troubleshooting.

**Comment by doggeral** [comment]
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/1651153/178395511-6f63ff18-c1a3-4bed-bcdf-c13d1e83447d.png">
