### ISSUE TITLE
App stuck in training

### ISSUE THREAD

**Issue by CannonFodderr** [wit-ai/wit#2493]
App ID: 600203844760380
App Name: app-62982ff3644de63609534a2f-th

This app is stuck on training, we tried to add and remove utterances to trigger a re-training but nothing seems to work.
we just keep getting the status:  

> Training ongoing
> Your app is currently training. Last time it took your app 45 s to train

Please advise

**Comment by nishsinghal20** [comment]
Hi @CannonFodderr! This should now be fixed. :)
