### ISSUE TITLE
Issue with WitAI response

### ISSUE THREAD

**Issue by MetaHumanREAL** [wit-ai/wit#2496]
Hello, I started using WitAI yesterday and I ran into this issue that I can't figure out. For some reason no matter what route I use for speech to text I always get a string response instead of a JSON response which I believe WitAI docs says I should get. It transcribes it for me but I can't grab the text it returns.

`
async function test() {
    var audioBuffer = fs.createReadStream('Record.mp3');
    fetch('https://api.wit.ai/dictation', {
        method: 'POST',
        headers: {
            'Authorization': 'Bearer mytoken',
            'Content-Type': 'audio/mpeg3'
        },
        body: audioBuffer
    }).then(async info => {
        console.log(await info.text())
    })
}
test();
`

When I log info.text() I get this response as a string:
`{
  "speech": {
    "confidence": 0.8115,
    "tokens": [
      {
        "end": 1620,
        "start": 620,
        "token": "Test"
      }
    ]
  },
  "text": "Test"
}
{
  "speech": {
    "confidence": 0.5927,
    "tokens": [
      {
        "end": 1740,
        "start": 740,
        "token": "Testing"
      }
    ]
  },
  "text": "Testing"
}
{
  "is_final": true,
  "speech": {
    "confidence": 0.8706,
    "tokens": [
      {
        "end": 1740,
        "start": 740,
        "token": "Testing"
      }
    ]
  },
  "text": "Testing"
}
{
  "speech": {
    "confidence": 0.9561,
    "tokens": [
      {
        "end": 3120,
        "start": 2700,
        "token": "Two"
      }
    ]
  },
  "text": "Two"
}
{
  "speech": {
    "confidence": 0.891,
    "tokens": [
      {
        "end": 3120,
        "start": 2700,
        "token": "Two"
      },
      {
        "end": 3360,
        "start": 3120,
        "token": "three"
      }
    ]
  },
  "text": "Two three"
}
{
  "is_final": true,
  "speech": {
    "confidence": 0.9265,
    "tokens": [
      {
        "end": 3120,
        "start": 2700,
        "token": "Two"
      },
      {
        "end": 3360,
        "start": 3120,
        "token": "three"
      }
    ]
  },
  "text": "Two three"
}
{
  "speech": {
    "confidence": 0.475,
    "tokens": [
      {
        "end": 4860,
        "start": 4320,
        "token": "Thing."
      }
    ]
  },
  "text": "Thing."
}
{
  "is_final": true,
  "speech": {
    "confidence": 0,
    "tokens": [
      {
        "end": 4860,
        "start": 4320,
        "token": "Thing."
      }
    ]
  },
  "text": "Thing."
}`

When I log info.json() I get an invalid-json response:
`FetchError: invalid json response body at https://api.wit.ai/dictation reason: Unexpected token { in JSON at position 172`

I am using node-fetch version 2.6.6, any help would be appreciated!
Thank you.

**Comment by nishsinghal20** [comment]
Hi @MetaHumanREAL! Thank you for reporting this. Let us investigate this and get back to you with a solution. Thank you for your patience! :)

**Comment by jayyteee** [comment]
Hey @MetaHumanREAL it looks like the issue is you are trying to parse the full response at once, when the full response contains several chunks of json rather than 1 full json response. If you split the response by the `\r\n\` delimiter before parsing that should fix the issue. Take a look at the api docs [here](https://wit.ai/docs/http/20220622/#post__dictation_link). 

We recommend you use our node-wit SDK https://github.com/wit-ai/node-wit/ as the latest version supports /dictation. Check the speech-synthesis example there for an example implementing dictation as well

**Comment by DUK3135** [comment]
[]()I've just started
