### ISSUE TITLE
App stuck on ongoing 

### ISSUE THREAD

**Issue by shorouqmajali** [wit-ai/wit#2497]
Do you want to request a feature, report a bug, or ask a question about wit?
Bug

What is the current behavior?
App stuck on training.

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
After adding entities and submitting the utterances for training, the app got stuck on "training ongoing" for almost 24 hours now. The previous training took only 16 seconds.

What is the expected behavior?
Training completion.

If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.
262921882021843 and 1266472757490068

**Comment by doggeral** [comment]
Your app has been trained successfully.
