### ISSUE TITLE
App stuck at 'Training ongoing'

### ISSUE THREAD

**Issue by arnolddenzil** [wit-ai/wit#2498]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
report a bug

**What is the current behavior?**
Training ongoing

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I just tried to train an utterance

**What is the expected behavior?**
'Training complete' as a few seconds or minutes. 

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1984323115104219

**Comment by doggeral** [comment]
Your app was trained successfully.
