### ISSUE TITLE
Receiving 400 response with no code change?

### ISSUE THREAD

**Issue by dzlandis** [wit-ai/wit#2499]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
I'm getting 400 responses after changing nothing about my code.

I tried using both /speech and /dictation.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
516648883046464

**Comment by yuzh174** [comment]
Hi @dzlandis , are you sending requests from scripts? 
We have rate limit on requests send. It seems your app usually has a boost of request. That's why some of them are throttled. 
Could you tell us more about your usage pattern? I would suggest to spread the requests if they are from testing (like add artificial wait between requests). If they are real prod usage, depending on the usage pattern, we can check how to get you a better solution.

**Comment by dzlandis** [comment]
Hi @yuzh174, I am using WitAI in production so that is probably the cause for the many requests.
I am confused as to why I am still getting 400 responses permanently now though, even when sending no requests for 15 hours of time.
Any help is greatly appreciated.

**Comment by yuzh174** [comment]
Do you know your request patterns, that would help. Like roughly how many requests per minute? 
Do you expect spike of requests? 

Regarding the 400 requests, I don't see any today.

**Comment by dzlandis** [comment]
~~@yuzh174 I just tried POSTing after roughly 15 hours of no requests and am still receiving 400 responses.
I'm not sure what to do.~~
I was just able to resolve the issue of 400 responses, it was an issue on my end :)

**Comment by dzlandis** [comment]
> Do you know your request patterns, that would help. Like roughly how many requests per minute? Do you expect spike of requests?

With regards to this, it varies from time to time. It varies between 120 requests per minute and your max requests of 240 per minute.
This wasn't what I was referring to when I first opened this issue but getting an increase in requests I can send per minute would be great!

**Comment by patapizza** [comment]
Hey @dzlandis looking at your app it seems like you're not using Understanding. So I've upgraded the limit to 250 requests per minute for `POST /dictation`.

**Comment by dzlandis** [comment]
Hi @patapizza, I so appreciated when you were able to upgrade the limit on dictation so I could take in more requests last time! I was hoping to be able to add more languages to my app which can be used with transcription and was wondering if you'd be able to upgrade the following app dictation rate limits so I could have this option. It isn't feasible to just change the language for the app you upgraded the limit for as that could result in transcriptions being sent for the wrong language if it was switched back and forth.

If you could upgrade the limits for the following apps, that would be spectacular:
1027417661438117
3138313153118090
367781718479168

I hope to use the upgrade to add Spanish, French, and a third language (tbd) without worrying about hitting limits :)
