### ISSUE TITLE
Feature request: resolve and normalize wit/location

### ISSUE THREAD

**Issue by that1guy** [wit-ai/wit#25]
I have defined a wit/location of "San Francisco", and this works.  Is it necessary for me to define the many cities and states in US that a user could include in their search string?

Also, in the case that the user types "SF, CA", must I define these scenarios as well?

Thanks for all the help!

**Comment by vdisawar** [comment]
Wanted to follow up here to say that wit/location doesn't work well with street addresses. For example, if a wit app recognizes both wit/number and wit/location, and you send it a street address: 

2S121 Waltham Ct

You get back from wit:
"entities": {
        "location": [
            {
                "confidence": 0.93408,
                "suggested": true,
                "type": "value",
                "value": "Waltham"
            }
        ],
        "number": [
            {
                "confidence": 1,
                "type": "value",
                "value": 2
            },
            {
                "confidence": 1,
                "type": "value",
                "value": 121
            }
        ]
    }

how should recognizing street addresses be resolved currently?

**Comment by patapizza** [comment]
Hi @vdisawar, in this case the whole text should be tagged as `wit/location`. Make sure you validate the examples wrongly annotated, we're working on improving `wit/location`. This is different than this issue though (more relevant: #757).

**Comment by patapizza** [comment]
We shipped this [in June](https://medium.com/wit-ai/a-smarter-wit-location-24f8f99f7296). cc @that1guy @alexdown
