### ISSUE TITLE
Utterances UI "Error: Something went wrong. We've been notified"

### ISSUE THREAD

**Issue by leamir** [wit-ai/wit#2500]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug report

**What is the current behavior?**
Page only displays "Error: Something went wrong. We've been notified"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
When using the UI, the 'utterances' page shows the error, the API(using curl) is returning the expected result

**What is the expected behavior?**
A list with the utterances

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1227409388094427

**Comment by wangzhenict** [comment]
Hi @leamir ,

it works to me. can you check whether it has been recovered to you?

**Comment by leamir** [comment]
@wangzhenict it still shows the same message.
I created a new app and downloaded the data from this one and it works normally, I haven't deleted the one with the bug tho
![image](https://user-images.githubusercontent.com/16721818/182951215-8a32dca2-8867-4f7c-a0f7-d8de06b0da75.png)

**Comment by yolanother** [comment]
@leamir is this still an issue for you?

**Comment by wangzhenict** [comment]
@leamir have applied a fix to the app. it works to me. I'll close this issue, if you see the issue again, please re-open. thanks
