### ISSUE TITLE
[URGENT] Training scheduled for the app

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2502]
Hi,

APP ID: 4344353432292657
ISSUE: Deleted and intent at 16:50 IST and in wit app it still shows 
![image](https://user-images.githubusercontent.com/601711/182848315-bf02547e-c1de-4511-871f-c26157fc7b0b.png)

On calling client.message function of npm node-wit it is still returning the deleted intent for input. But if we try the same input using https://api.wit.ai/message it is showing error.

Can someone please complete the training status and update

Thanks

**Comment by wangzhenict** [comment]
Hi @anjaly, I noticed the training has been complete half hour ago, can you check whether the issue was gone?

**Comment by anjaly** [comment]
> Hi @anjaly, I noticed the training has been complete half hour ago, can you check whether the issue was gone?

The issue still persist if we train any other input

**Comment by doggeral** [comment]
Training is done.
