### ISSUE TITLE
App training is exceedingly slow

### ISSUE THREAD

**Issue by CannonFodderr** [wit-ai/wit#2506]
We are experiencing very slow training time on several applications
i.e. App ID: 1288676948626962
Training can go over multiple hours to be completed just for adding 1 utterance or intent.

Is there a way we can improved this ?

**Comment by ChrisyShine** [comment]
Our service may schedule the training in several hours based on the service capacity. The app training was done in several minutes, just the training job was in the queue to be trained, and the waiting time may be several hours.
