### ISSUE TITLE
intent scores are not stable and low

### ISSUE THREAD

**Issue by MeranTumeh** [wit-ai/wit#2507]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?** 
bug

**What is the current behavior?**
The intent scores are not stable, they keep changing every time we check it. 
On 10-8-2022 4:24 pm the expression 'الانترنت بطيء' appeared as pending and it used to return a low score as shown in the screenshot : 
![image](https://user-images.githubusercontent.com/111044474/184099398-9187beb7-19bc-459a-a196-0f05ffa53271.png)

and on 11-8-2022 9:56 am it returned high score as shown : 
![image](https://user-images.githubusercontent.com/111044474/184099615-08c028e6-804b-49ee-88d1-88bb9367b1ef.png)

Also, most of the pending expressions are returning low scores as shown : 
![image](https://user-images.githubusercontent.com/111044474/184100009-65401f0e-397a-418f-b103-9df7a508aac5.png)
![image](https://user-images.githubusercontent.com/111044474/184100064-9d7518fc-ffab-4dac-85a8-dd6b21748492.png)
![image](https://user-images.githubusercontent.com/111044474/184100125-d6c1942b-ea09-4b02-b471-7f5be998b821.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
send "الانترنت بطيء" or "بدي اشتكي"  or " ما بشتغل" or "كيف ممكن ارجع خط مفصول؟"

**What is the expected behavior?**
to return a response with high score of the intent 

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
280962410285788

**Comment by yolanother** [comment]
@MeranTumeh generally low confidence scores like these mean you need to train more utterances for the intent. Do you know how many have you trained for this intent?

**Comment by MeranTumeh** [comment]
@yolanother It was trained long time ago and it was working fine and then it kept showing that the training is in progress and  the problem of low scoring showed up, this doesn't happen always to the same intents

**Comment by MeranTumeh** [comment]
Hi @yolanother, is there any updates?

**Comment by MeranTumeh** [comment]
Hi @yolanother, we are still facing the same problem, can you help?

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
