### ISSUE TITLE
Major wit issue! Entities not showing more than 25 keywords across all apps as if deleted, the ones that have not been trained in a while too

### ISSUE THREAD

**Issue by M3Z47** [wit-ai/wit#2508]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
Many entities not showing more than 25 keywords.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
The list of keywords should all be visible, it is as if the are deleted!

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
This app I am using and training regularly: 260786572917658. Many entities that had more than 4,500 keywords now show only 25 keywords! Entities like: player, participant, bowler_stat and many others seem to have only a few keywords.
This app I had not tinkered in a while: 424214919568822. Even this has the same problem!

Also, even after pushing many queries for training, the app does not show any scheduled training time.
Please look into it urgenty.

**Comment by M3Z47** [comment]
Using API in Postman to get entities, it shows all 4,500 keywords for different entities, but is not visible on the UI panel of wit.ai

**Comment by yolanother** [comment]
Thanks for the report. We'll take a look.

**Comment by M3Z47** [comment]
Also, could you look into the App ID: 260786572917658
I am sending for queries to train, but its not scheduling any new training and no "Training ongoing" either. Please unlock the app if thats the case as I am unable to train. Its showing last trained at "Thursday" which was 4 days ago and have sent many new queries since.
Thanks.

**Comment by ChrisyShine** [comment]
The problem about only 25 keywords is just a UI display problem. The keywords still exist in the backend. The UI fix is on the way.

**Comment by M3Z47** [comment]
> Also, could you look into the App ID: 260786572917658 I am sending for queries to train, but its not scheduling any new training and no "Training ongoing" either. Please unlock the app if thats the case as I am unable to train. Its showing last trained at "Thursday" which was 4 days ago and have sent many new queries since. Thanks.

Its working now.

**Comment by doggeral** [comment]
Resolved the issue.
