### ISSUE TITLE
Character intents disappeared from training 

### ISSUE THREAD

**Issue by aya-labiba** [wit-ai/wit#2509]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
There was a number of character intents that were already trained in the app, when we tried to retrain them an error message is returned that says that the intents are not found.

![image](https://user-images.githubusercontent.com/99329638/184898595-b7199ddf-8bcd-49eb-8d86-991838acc0d1.png)

Example of the intents that were unable to be retrained:
_ch_b76f0f31___ba79___4846___b610___23e9f9bf187c
_ch_94859304___00f5___403c___832d___393e5579eef6
_ch_1da2f0ce___8205___41ce___a722___98938a5e1df5
_ch_3a0da367___a8dc___4e3a___8b9c___d2462959a104

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

try to train the blow character intents using the 'utterances' API:
[character utterances.txt](https://github.com/wit-ai/wit/files/9351746/character.utterances.txt)

**What is the expected behavior?**
To be able to retrain the existing intents

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
468849228311171
398875828702387

**Comment by aya-labiba** [comment]
Hi Wit Team, any updates regarding the issue?

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
