### ISSUE TITLE
wit/duration only identifies number

### ISSUE THREAD

**Issue by descrip** [wit-ai/wit#251]
Under the understanding tab, I've tried strings like "three days". According to the description, `wit/duration` should normalise this to seconds. However, `wit/duration` only returns a number, "3":

![2016-06-28--1467132686_1360x768_scrot](https://cloud.githubusercontent.com/assets/6173806/16425022/8d4bc3b8-3d30-11e6-9cde-e79a73671e40.png)

This happens for all other periods of time: "30 min", "20 years", etc. Is this how `wit/duration` is supposed to work? If so, how do I also retrieve a unit from the text?

**Comment by l5t** [comment]
Thanks for reporting. We don't display it yet in the UI but if you curl your app (in the Settings tab) you will see that Wit will normalize it in seconds.

**Comment by descrip** [comment]
Do you know when the UI will be able to display this?

**Comment by AnthonyPaulO** [comment]
Wow. An hour after this question was posted it was answered, but it's an answer to the same question I posted on May 11th and have been waiting almost two months for an answer. See https://github.com/wit-ai/wit/issues/223

I'm glad this finally got answered but I wish someone would tell me what I was doing wrong that prevented me from getting a single answer; this way I know for the next time.

**Comment by descrip** [comment]
Just when I finish writing code to sidestep this issue, the bug is fixed. Well, okay.

**Comment by descrip** [comment]
No, wait! I take that back! Under the Understanding tab, the duration is correctly parsed with a unit, but when constructing Stories, only the number is identified again.

**Comment by l5t** [comment]
Why would you want to get it inside the stories? As mentioned [here](https://wit.ai/docs/recipes#extract-and-store-information-from-user-messages), Only trait entities have their value influence the prediction.

**Comment by descrip** [comment]
I don't want it to influence a prediction, I want the bot to print out the unit of a `wit/duration`. For example, when I tell the bot to say `The duration is {duration}`, it only prints out `The duration is 3` if wit identifies `3 days` as the duration. 

Am I doing it wrong? Is there a way to retrieve the unit as an entity?

**Comment by l5t** [comment]
You mean in the Chat Mode?  In the real world you will probably parse the entities in your action on your side and create a context key with the format you want. Then your `Bot sends` will use this context key. Here is what your action will receive for example
```json
{
  "confidence" : 0.04328004115161279,
  "type" : "msg",
  "msg" : "For here? Yes or No?",
  "entities" : {
    "duration" : [ {
      "confidence" : 0.9811668790472403,
      "minute" : 3,
      "value" : 3,
      "unit" : "minute",
      "normalized" : {
        "value" : 180,
        "unit" : "second"
      }
    } ],
    "intent" : [ {
      "confidence" : 0.9706844428095582,
      "value" : "meeting"
    } ]
  }
}```

**Comment by descrip** [comment]
Yeah, I made my bot use meaning from GET requests instead of relying on Stories. So there is no way to retrieve that unit until more work is done on Stories?

**Comment by l5t** [comment]
The example above is from /converse.... It will work with Stories but the test Chat Mode in the console will only show you the value of the entity (here 3). If you want to reformat the duration, you will parse the `duration` entity on your code and create a formatted_duration context key that you can use in your stories.

**Comment by descrip** [comment]
Okay, got it. Thanks.

**Comment by windmaple** [comment]
Is there a way to normalize the duration to days instead of seconds?

**Comment by descrip** [comment]
@windmaple: Sadly, no. @l5t recommends using the [HTTP API](https://wit.ai/docs/http/20160526#get--message-link) instead, from which you can get raw time data.
