### ISSUE TITLE
[URGENT] Empty entity returned for "/message" API

### ISSUE THREAD

**Issue by jijoamt** [wit-ai/wit#2510]
For the wit app with APPID: 4844325972264845, we are getting empty entity array for the below API. This was working fine until yesterday.
https://api.wit.ai/message
{
    "text": "airline",
    "intents": [],
    "entities": {},
    "traits": {}
}

We have tried in the "Understanding" tab in WIT UI also, but no intent is getting identified there also.
can you please check this.

**Comment by anjaly** [comment]
Any update on the above issue?

**Comment by doggeral** [comment]
Retrain your app, the issue should be fixed now.
