### ISSUE TITLE
train failed

### ISSUE THREAD

**Issue by aref-thinglogix** [wit-ai/wit#2511]
Do you want to request a feature, report a bug, or ask a question about wit?
Bug
What is the current behavior?
App stuck on training.
If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
After adding entities and submitting the utterances for training, the app got stuck on "training ongoing" for almost 24 hours now. The previous training took only 16 seconds.
What is the expected behavior?
Training completion.
If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.
208092464505720

**Comment by ChrisyShine** [comment]
The training is done in the app now. 
Our training scheduler may put the training job in a queue to be trained several hours later, based on our service capacity. So sometimes, the training job may be done in 24 hours.
