### ISSUE TITLE
Wrong intent of the previously trained word

### ISSUE THREAD

**Issue by AlexisNichel** [wit-ai/wit#2513]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a Bug

**What is the current behavior?**
I type the word "hola" and wit detects the intent "humanize"
![image](https://user-images.githubusercontent.com/15020002/186768670-7ee8d751-f86c-476b-a477-a9e750867bc3.png)

However, no trained phrase has the text "hola" anywhere for the humanize intent.
![image](https://user-images.githubusercontent.com/15020002/186768878-f2406f4e-a0e0-4aee-ac7a-fe4597b82c9e.png)

The expected intention is "greeting" which is what is previously trained
![image](https://user-images.githubusercontent.com/15020002/186769176-dfc26d4e-cf0e-4e01-ab5a-b124de98fb6e.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Simply typing the word "hola"

**What is the expected behavior?**
The expected intention is "greeting" which is what is previously trained

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1856185531061946

**Comment by AlexisNichel** [comment]
Another example:
Text: "menu" and wit detects the intent "equipament_purchase"
![image](https://user-images.githubusercontent.com/15020002/186771145-1aaa76a2-64d1-466e-83ab-3fa415c40571.png)

However, no trained phrase has the text "menu" anywhere for the equipament_purchase intent.
![image](https://user-images.githubusercontent.com/15020002/186771402-7c6980b8-5bc6-48ef-af40-5bc1234707cd.png)

The expected intention is "feature_list" which is what is previously trained
![image](https://user-images.githubusercontent.com/15020002/186771637-ec8f1e35-537e-43c8-91a1-7466295f07b5.png)

**Comment by doggeral** [comment]
We are working on the infra upgrade, the new change will roll out gradually. Try to retrain your model for quick fix.

**Comment by AlexisNichel** [comment]
I already retrained and nothing :(
