### ISSUE TITLE
INTENT NOT WORK

### ISSUE THREAD

**Issue by crisgio24** [wit-ai/wit#2514]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a Bug

**What is the current behavior?**
All my Intent stopped working according to the associated utterance.
![image](https://user-images.githubusercontent.com/80471701/186775305-6a98ee29-5158-4d4f-b27e-6406ca6d901d.png)

Please support me, this shouldn't happen.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
typing start but intent selection doesn't update.

**What is the expected behavior?**
In the intent selection it should show me Menu_Principal.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
394693855538917

**Comment by doggeral** [comment]
I noticed you've started the model retraining. It should fix the issue.
