### ISSUE TITLE
[URGENT] Empty entity returned for "/message" API

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2515]
Hi,

For the wit app with APPID: 356366686436340, we are getting empty entity array for the below API. The app was working until yesterday.
https://api.wit.ai/message
{
"text": "Integration&Design Tools",
"intents": [],
"entities": {},
"traits": {}
}

We have tried in the "Understanding" tab in Wit UI also, but no intent is getting identified there also.
Can you please check this on priority.
We faced this issue for another app last day.

**Comment by jijoamt** [comment]
We are facing the same issue with App ID 623134488936494 also

**Comment by doggeral** [comment]
Seems the transit issue? Looks good from my side.
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/1651153/186998974-3fab01f6-6f46-4aac-8ea1-b627cabc28c7.png">
