### ISSUE TITLE
App stuck in training mode. app ID 542373750414845

### ISSUE THREAD

**Issue by AnabelleG** [wit-ai/wit#2517]
App 542373750414845 has been training for more than an hour

**Comment by AnabelleG** [comment]
It refreshed, but now app is set to train 12 hours from now! at 9:21pm. Please help as I need to deliver this

**Comment by anjaly** [comment]
Same for us also. when ever the app is getting trainined either it is scheduled to a later time or showing training without any completion.

**Comment by doggeral** [comment]
The training is done.

**Comment by AnabelleG** [comment]
@doggeral the training was done after 12 hours of waiting. I just trained my app again and it's scheduled to train in 3 hours. I need it to train sooner
