### ISSUE TITLE
Slow Training Times 

### ISSUE THREAD

**Issue by gs109111** [wit-ai/wit#2518]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?** : Bug/Question

**What is the current behavior?**: Training for projects takes more time, even up to a few hours 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**: The training shouldn't take this long

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.** 434865881937841

**Comment by doggeral** [comment]
training is done.
