### ISSUE TITLE
Yes/No Story giving conflict on Story Save.

### ISSUE THREAD

**Issue by StillOnMyWay** [wit-ai/wit#252]
Hey guys, so far, liking the update. I was following it from last night when it was posted. 

I'm attempting all of the major recipes which have changed, but the new structure of Yes No stories, using branches is consistently giving me a conflict, stating that I'd need to have the same response in my no, as in my yes. Posting 2 images below. 
![image](https://cloud.githubusercontent.com/assets/8432037/16457042/20b4aba8-3de8-11e6-9a29-d987a5009073.png)

![image](https://cloud.githubusercontent.com/assets/8432037/16457127/5e88fe52-3de8-11e6-9fda-8e9a9d94eb65.png)

**Comment by francisforever** [comment]
Your `yes_no` entity should be of type "trait", is this the case?

**Comment by StillOnMyWay** [comment]
Perfect. Thank you so much, it was of types trait and keywords before.

**Comment by ar7hur** [comment]
We should update the docs. The reason is that for non-trait entities, the value is ignored with regards to action prediction. Only trait entities (like typically intent) have their value influence the prediction.

**Comment by StillOnMyWay** [comment]
What about the export Bot feature? I'm not seeing it within the settings menu.

**Comment by l5t** [comment]
Glitch on our side, it is only available to certain users... Will open it later today.

**Comment by l5t** [comment]
You should be able to access it now. Hard refresh your browser if needed

**Comment by yoniholmes** [comment]
Hi. I'm still seeing the same error above. I created a yes_no intent of type 'trait'. When I create two branches within a story based on Yes/No values, I cannot successfully save the story due to the error 'Conflicts with [name of the other response]'. The docs say I can do this, and yet I can't seem to be able to do it. Any ideas?

**Comment by yoniholmes** [comment]
Update: I was able to get this to work. As I was developing, without being aware of it I had been accumulating Actions. Those actions don't disappear if you delete them from the story. I had to go to the Actions tab and manually remove all the old actions that I never wanted. Once they were removed, I was able to rebuild my story, and was able to save it successfully using the yes_no entity.

**Comment by l5t** [comment]
Thanks for reporting.

**Comment by athirauk** [comment]
Hi. I'm still seeing the same error above. I have deleted the old actions

**Comment by yoniholmes** [comment]
@athirauk probably not of much help, but using the live chat tool under 'Help', some of the devs at Wit.ai told me that they were having problems (this happened at least twice), where no matter what changes I made I was getting errors. They weren't explicit about what went wrong but they did tell me 'try again it should be working for you now' which seemed to say there were problems with some of their services. I'm working in the UK, so not sure whether that's a bad time for them? I found the system to be too intermittent to be productive so I've stopped work on this for the time being. Good luck with it though!

**Comment by ljmyz** [comment]
Dear wit.ai developper, 
Having the same problem when trying to pass quick replies. Always the same annoying message: conflicts with "...". Deleting actions, refreshing browser, changing to traits, writing final action, restarting all the story multiple times. Nothing works. :(

Can you help me on this? 

https://wit.ai/ljmyz/MedBot/stories/0d2e966d-0dee-410d-8980-a01f5f05dd5f

**Comment by StillOnMyWay** [comment]
Your bot story is locked, you'll have to make it public for me to see. Also
if you don't feel comfortable doing that you can try screenshotting it.

**Comment by ljmyz** [comment]
The app is public. It is only at early stage :) no problems with privacy now...
But, a teammate manage to access the story without problem. How to unlock a bot story?

**Comment by ljmyz** [comment]
![1](https://cloud.githubusercontent.com/assets/15046041/22925463/2c270744-f2a9-11e6-9e33-fe04196daed6.png)

Is it correct to "solve" this problem by adding an intent to the "yes" user response and not to the "no"? It is the only way founded to solve the conflict...

![2](https://cloud.githubusercontent.com/assets/15046041/22925485/3963bb8c-f2a9-11e6-90b4-25ec6cb97076.png)

**Comment by l5t** [comment]
Your yes_no should be a trait entity not at keyword one. https://wit.ai/docs/recipes#handle-yesno-answers

**Comment by ljmyz** [comment]
Thank you!!! The **don’t highlight the “yes”** is really important. Sorry I miss that point. Your doc is a little to interactive for me... :)
Anyway, it is working perfectly now. Thanks again.

**Comment by ljmyz** [comment]
... sorry to bother you again, but... What if your quick replies are: 'toto' and 'tito'? The training with those almost identical trait words is not working. Is it really impossible to have bot responses based on keywords? Sure, it can be done with a js function but is a bit annoying.

**Comment by priyanshi555** [comment]
I am having trouble with branching thing..it gives "conflict with..." error message again and again. please help me out
https://wit.ai/priyanshipandey/schemes_final/stories

**Comment by ljmyz** [comment]
Finally I did it with a js function... Only way I found to avoid conflicts with similar "trait" words.

**Comment by blandinw** [comment]
Yes, we recommend writing client-side code when you need more flexible and custom logic than the UI tool can provide.
