### ISSUE TITLE
My App is Stuck in the 'Training on going' status

### ISSUE THREAD

**Issue by nisreen93** [wit-ai/wit#2522]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
My App is Stuck in the 'Training on going' status
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
open the app and monitor the status
**What is the expected behavior?**
Training utterances must be scheduled and auto-trained within 5 min as usual.
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1920151674738030

**Comment by doggeral** [comment]
Seems the training is done.
