### ISSUE TITLE
Incomplete import of an app using POST /import

### ISSUE THREAD

**Issue by PaulThblt** [wit-ai/wit#2523]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug regarding the import from a zip file

**What is the current behavior?**
Hi, i am trying to backup my app with a fetch to **/import** but when imported, the clone app is filled with only about 50% of the parent app's utterances.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I exported the source app as a zip file, then used fetch /import with the file's binary in the body, creating the clone app in the process

**What is the expected behavior?**
The exported zip file seems to be correct, so I am assuming the problem must come from the import, but everything should work as the clone is appearing in the wit console.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
The clone's ID is 1168191893737969, the sources' ID is 1154503718388969

**Comment by AlexandreRgx** [comment]
Same problem here. Did you find a solution?

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
