### ISSUE TITLE
Very long pending time for model training 

### ISSUE THREAD

**Issue by benjo0010** [wit-ai/wit#2524]
Hello, we want to report on the unusual behavior of the system. All of our apps experience a very long pending time before training.  We have been using the system for over one year and this is a very unusual behavior that started a few days ago. 

Here are two apps ID  as an example

- f05996af-2c76-4765-933e-bdfedc6aa049
- 6c9453a0-3a52-484b-921d-93a0c3627614

**Comment by ajith007** [comment]
I'm facing similar issue too. I see the below message, almost 12hrs wait time to start the training. I'm new to wit, so not sure about the usual training delays. 
Training scheduled
Your app is scheduled to train at 11:23 PM

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
