### ISSUE TITLE
App training is very slow and two of the apps started missmatching intents

### ISSUE THREAD

**Issue by haribalos** [wit-ai/wit#2525]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question
**What is the current behavior?**
Two of our three apps are stuck in training for a long time, and recently after the 26th of Aug they seem to not match questions
with the correct intents. 
They worked fine and then suddenly we're getting weird matches and we had to turn our app to the App that is working correct.
Keep in mind the two other apps are a copy and share similar training for most of the intents in matter of utterances.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Our model is build based on greek language so if you ask the mobile model  (AppId:618389522541052) 
καλημερα (good morning)  we re not getting any match and if u ask the second model the same question (Appid:4926118934078909)
we re getting a wrong intent match. 
The app that is working correct ( AppId:572046700564927) returns the correct intent which is INTNT_GEN_GREETING.
**What is the expected behavior?**
It is described above.
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
AppId:618389522541052
Appid:4926118934078909

**Comment by benjo0010** [comment]
We have the same issue exactly

**Comment by doggeral** [comment]
retrained your app, the issue should be fixed soon.
For future training slow issues, feel free to retrain the app from the UI, most of the case retrain will addreess the issue.
