### ISSUE TITLE
App showing ongoing training for 2 days

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2527]
@ChrisyShine 
Related to #2526
 App ID 397837775835719 is showing ongoing training for 2 days. Can you please le us know why this is taking too much time.

**Comment by ChrisyShine** [comment]
@anjaly The app training should be fine now.

**Comment by anjaly** [comment]
> @anjaly The app training should be fine now.

@ChrisyShine Why this is happening always. Do we need to contact you each time for complete the training.
