### ISSUE TITLE
[URGENT] Issues with app training

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2528]
@ChrisyShine 
Related to #2526 and #2527

We had one major issue reported by client that when numbers are chosen, NLP is returning another intent thank_you.
So we tried to retrain the numbers to outofscope from Understanding tab to remove the intent and return only entity @sys-number. 
1. Can you please confirm what we are doing to remove the intent selection for numbers is correct.
2. Also This was working perfect before. Can you please let us know why this is showing the unwanted intent now.
3. **ALSO WHEN WE TRIED TO RETRAIN, THE APP IS SCHEDULED TO TRAIN AT 13:09 IST. CAN YOU PLEASE TRAIN IT MANUALLY**

**Comment by ChrisyShine** [comment]
@anjaly You are sharing the app token instead of app id. I think you'd better re-generate the token, or your app is in risk that anyone can use the token to make changes to your app if it is a server-token.

**Comment by ChrisyShine** [comment]
The app training is done now. As we have explained, we have a scheduler to schedule the training job. So it is possible that the training job is scheduled for several hours later.
If the job is scheduled, you will expect it to be trained as the schedule. But if the app is already on-going training, but stuck at the training for a long time, you can contact with us to resolve the training stuck problem.

**Comment by ChrisyShine** [comment]
About the numbers problem, can you share some concrete examples? What is the utterance, what is the current Wit result, and what is the expected Wit result?

**Comment by anjaly** [comment]
> @anjaly You are sharing the app token instead of app id. I think you'd better re-generate the token, or your app is in risk that anyone can use the token to make changes to your app if it is a server-token.
@ChrisyShine 
ooh Sorry. I have edited the content. Is that ok

**Comment by anjaly** [comment]
> The app training is done now. As we have explained, we have a scheduler to schedule the training job. So it is possible that the training job is scheduled for several hours later. If the job is scheduled, you will expect it to be trained as the schedule. But if the app is already on-going training, but stuck at the training for a long time, you can contact with us to resolve the training stuck problem.
@ChrisyShine 
But this started recently only. We have some automated training scenarios and this is getting stuck due to the scheduling issue.

**Comment by ChrisyShine** [comment]
@anjaly People can still see your app token when checking the edit history. And there are chances that your app token is already copied by someone. The most safe solution is to re-generate a new token in Wit.ai settings page which means you have to update your callsites with a new token.

**Comment by anjaly** [comment]
> About the numbers problem, can you share some concrete examples? What is the utterance, what is the current Wit result, and what is the expected Wit result?
@ChrisyShine 
This issue is fixed after we have trained it as out of scope for removing the unwanted intent. Actually on inputting numbers we were expect only the built in entity wit/number but instead it was triggering intent thank_you

**Comment by ChrisyShine** [comment]
We are trying to improve the training experience.
