### ISSUE TITLE
500 error on endpoint GET Utterances when applying limit over 1100 utterances 

### ISSUE THREAD

**Issue by christosangelidis** [wit-ai/wit#2529]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
On GET Utterances endpoint, when I apply a limit of over 1100 utterances (the app has over 2k utterances) the server responds with a 500 error and a JSON message of: 
{
    "error": "Something went wrong. We've been notified",
    "code": "unknown"
}

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Just use GET Utterances endpoint and apply a limit of over 1100.

**What is the expected behavior?**
Return all the available utterances

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App 1: 339053820531515   (limit > 1100)
App 2: 2092345764240756 (limit > 600)

**Comment by ChrisyShine** [comment]
There was some data inconsistency issue before, I've fixed the inconsistent data. Now both the apps should be able to return all the utterances.

**Comment by christosangelidis** [comment]
Much appreciated, thank you.
