### ISSUE TITLE
Bug of wit/number:role

### ISSUE THREAD

**Issue by fox721** [wit-ai/wit#253]
I had created different roles for the wit/number entity and everything was working fine till some days ago. Now it returns only wit/number instead of wit/number:role.
You can see the bug summarized by the following images:

![original](https://cloud.githubusercontent.com/assets/19403591/16482443/0a37610e-3eb0-11e6-8767-1f499d157807.png)
![faulty](https://cloud.githubusercontent.com/assets/19403591/16482444/0d063068-3eb0-11e6-840c-58c019ab82da.png)

**Comment by hashAI** [comment]
ya wit/location and wit/datetimes roles are working but not wit/number

**Comment by fox721** [comment]
Is it a bug that will be fixed or is it a precise choice of the wit.ai team?

**Comment by ar7hur** [comment]
It's a bug

**Comment by fox721** [comment]
Thank you, are you already working on this bug?

**Comment by hashAI** [comment]
Is it possible to mark nested entities?? Please tell me how??

**Comment by l5t** [comment]
As for nested/composite entities, we are working to add them.

**Comment by ktsakas** [comment]
They are there, but they are not first class yet. Here is how I got them to work:

If you go to the understanding tab and select your entity.
Go to expressions now say you are matching "5 guests" in an expression, then select the number 5 (i think it only works if you do it left to right) and add the wit/number type.
It will show up as a composite entity.

If you go to your stories you will  not see it (i think they are working on that), but when you use the API it will give you back the sub-entity (the number in this case).

![composite-entities](https://cloud.githubusercontent.com/assets/4787050/16823922/9c88b136-4935-11e6-860a-3bd524790348.gif)

**Comment by l5t** [comment]
Thanks for sharing the hack, it will indeed work with both /message and /converse but the UI won't do a good job at showing these composite entities if you refresh your entity page for example.

**Comment by hashAI** [comment]
Im hoping you guys will support it in the main UI asap. Thanks for the hack @ktsakas

**Comment by dimirc** [comment]
@l5t @ktsakas I was like crazy trying to find out why it was getting erased when I reload the browser. I confirm that API is replying composite entities correctly, just the UI isnt showing them,  hope UI gets updated soon

**Comment by awnali** [comment]
i tried every single solution but no one worked out for me, this is sort of last hope for me, please guide how to solve my following problem:
users can send composite message like 10 meat and hundred vegs, meat and 4 veg is there any way i can get the response in such a way that i can get how many number of meat and how many number of veg.
i'm getting the following response, 
{
  "msg_id" : "8e26f9bc-fa79-406a-bb56-4a19777d1db9",
  "_text" : "1 meat and lite",
  "entities" : {
    "number" : [ {
      "confidence" : 1,
      "type" : "value",
      "value" : 1
    } ],
    "item_type" : [ {
      "confidence" : 1,
      "type" : "value",
      "value" : "meat"
    }, {
      "confidence" : 1,
      "type" : "value",
      "value" : "lite"
    } ]
  }
}

I want something like: 

{
  "msg_id" : "$ID",
  "_text" : "find a 2007 red mustang",
  "outcomes" : [ {
    "_text" : "find a 2007 red mustang",
    "intent" : "find_car",
    "entities" : {
      "car" : [ {
        "value" : "2007 red mustang",
        "entities" : {
          "number" : [ {
            "value" : 2007,
            "type" : "value"
          } ],
          "color" : [ {
            "value" : "red"
          } ],
          "model" : [ {
            "value" : "mustang"
          } ]
        }
      } ]
    },
    "confidence" : 0.52
  } ]
}

Please Help.

**Comment by l5t** [comment]
I just created a example app here: https://wit.ai/l5t/CompositeExample/settings
Because of the UI bug, you will only be able to highlight the top entity in the Understanding tab. In my case, I called this entity `product`.
Then you can go to the Entities page to do the nested entities tagging: https://wit.ai/l5t/CompositeExample/entities/product

See below how to do so:
![composite_entity](https://cloud.githubusercontent.com/assets/6992759/17289575/982e3710-57da-11e6-9477-6348dfe24edd.gif)

**Comment by awnali** [comment]
Thank you so much @l5t but somehow i'm doing the same but i'm not getting the response as single array including quantity and product. 

Even i tried few inputs in your application and its not working for me, for example:

if i enter 1 veg and 2 meat, i should get following output:

```
{
	"msg_id": "$ID",
	"_text": "1 veg and hundred meats",
	"outcomes": [{
		"_text": "1 veg and 2 meat",
		"intent": "user_order",
		"entities": {
			"inputs": [{
				"value": "1 veg",
				"entities": {
					"number": [{
						"value": 1,
						"type": "value"
					}],
					"product": [{
						"value": "veg"
					}]
				}
			}],
		  "inputs": [{
				"value": "hundred meat",
				"entities": {
					"number": [{
						"value": 100,
						"type": "value"
					}],
					"product": [{
						"value": "meat"
					}]
				}
			}]
		},
		"confidence": 0.52
	}]
}

```

**Comment by l5t** [comment]
Can you provide the url to your app?

**Comment by l5t** [comment]
You user_oder_imput entity must be free-text also (not only keyword). I also noticed that you only have 1 validated example. Please provide at least 5 examples for Wit to start learning this

**Comment by awnali** [comment]
this is the application: https://wit.ai/awnali/Test/entities

**Comment by l5t** [comment]
I checked. You need to validate at least 5-10 examples

**Comment by awnali** [comment]
when you are planning to fix this issue and push it to live server?

**Comment by ksperling** [comment]
@lt5 Even when following what you do in the video exactly making the nested text selection never works for me... I highlight the nested span, and as soon as I click on the 'add a new entity' option the nested text selection disappears. If I go ahead and add the entity anyway it just gets added as a trait without referencing a span of the text.

**Comment by egalluzzo** [comment]
I am seeing the same behavior as @ksperling.  Are composite entities still supported?  If not, what should we be using instead to decompose them?

**Comment by begizi** [comment]
Also having the same issue as @ksperling. Is there any update on composite entities?

**Comment by carluccyo** [comment]
I'm hoping you guys will support it in the main UI asap. Thanks

**Comment by l5t** [comment]
Just reintroduced them: https://wit.ai/blog/2017/02/24/reintroducing-composite-entities. Thanks for your patience

**Comment by miteymouse** [comment]
Why is this closed?  I don't see a solution...
