### ISSUE TITLE
Different Intents keep changing from "trained" to "in progress" and then scores are not stable

### ISSUE THREAD

**Issue by MeranTumeh** [wit-ai/wit#2530]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
The intents were trained long time ago and they were working fine and now it keeps showing for some that the training is still in progress, this doesn't happen always to the same intents. Also the scores of intents in progress are not stable, they keep changing every time we check it, and they are low.

On 10-8-2022 4:24 pm the expression 'الانترنت بطيء' appeared as pending and it used to return a low score as shown in the screenshot :
![image](https://user-images.githubusercontent.com/111044474/191187840-7430840e-70a3-4e23-96bd-d391090d9f17.png)

and on 11-8-2022 9:56 am it returned high score as shown :
![image](https://user-images.githubusercontent.com/111044474/191187986-ed6e7d09-8c83-4955-9b32-b6b636e7e538.png)

Also, most of the pending expressions are returning low scores as shown :
![image](https://user-images.githubusercontent.com/111044474/191188059-0964c332-06ff-44bc-8491-a7a689a0f9b2.png)
![image](https://user-images.githubusercontent.com/111044474/191188083-353c433a-1ee6-4af6-8ce2-1f37a33a055f.png)
![image](https://user-images.githubusercontent.com/111044474/191188119-0c3e4129-b689-412c-8a2b-7d7655a113d1.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
send "الانترنت بطيء" or "بدي اشتكي" or " ما بشتغل" or "كيف ممكن ارجع خط مفصول؟"

**What is the expected behavior?**
to return a response with high score of the intent

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
280962410285788

**Comment by doggeral** [comment]
Retained your app, these utterance can be recognized with high confidence.
