### ISSUE TITLE
APP Suddenly Disappeared from Dashboard.

### ISSUE THREAD

**Issue by memson** [wit-ai/wit#2532]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
BUG

**What is the current behavior?**
APP suddenly disappeared without warning or notice.
Not visible on the dashboard.
API calls return {"error":"App not available","code":"bad-request"}

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
No idea how to reproduce this. One day the APP is working fine, the next day it's gone without trace.

**What is the expected behavior?**
That the appear continues to operate until manually deleted by the owner.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1784317085254258

Regards,
Michelle Emson
White Ribbon Alliance

**Comment by nishsinghal20** [comment]
Hi @memson! Thank you for reporting this. We're investigating this issue on our end and will soon get back to you with a resolution. Thank you for your patience!

**Comment by doggeral** [comment]
We've fixed your app, and verified from the UI. Closed the task for now. Feel free to reopen it if you need any helps from us.
