### ISSUE TITLE
App stuck in training

### ISSUE THREAD

**Issue by M3Z47** [wit-ai/wit#2533]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
App is stuck in training

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Training should be complete by now

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID: 260786572917658

**Comment by M3Z47** [comment]
@doggeral

**Comment by M3Z47** [comment]
Please unlock the app urgently, as it is in production...

**Comment by M3Z47** [comment]
@yolanother @ChrisyShine

**Comment by ChrisyShine** [comment]
There are too many samples in this app. I've scheduled retrain for this app, but the amount of training data may lead to a very long training time and may not finish successfully.
Do you really need so many training data in a single app?

**Comment by M3Z47** [comment]
Thanks for reply.
It seems the app is stuck. Could you stop its training process? I will push only few new queries to train this time.
Also, to train a particular type of query, how many variations should I send?
Suppose I have a base query (with a particular intent, here "runs"): "Total runs by Shane Watson", and I want this query to work with multiple chains (All PnCs): in World cup, at position number 3, against Sydney warriors, since 2017, etc.: What is the best way forward? (There are nearly 16 chainings that I need to work, obviously in the 280 character limit of Wit)
My number of queries to train becomes large as I push to train all PnCs of chains with base queries (at different positions in the statement too)
Please help. Thanks.

**Comment by ChrisyShine** [comment]
Current problem is the total samples in your wit app are too many for the training to work. Currently, wit.ai doesn't support incremental training. So every time, when you add a new utterance, wit.ai will take all of the samples for training. It will be more and more slow with more and more utterances.

And about different variations of the utterances, does the keyword entity helps? Instead of adding all the variants as different utterances, you can annotate the utterance with entities and add more keywords for entities.

**Comment by M3Z47** [comment]
In the above case, the chaining items are entities themselves. e.g. in World cup: world cup is a keyword under "Tournament" entity. Thing is, I used to train with less PnCs but Wit used to give inaccurate results if I added some chain to the base query that has not been trained before...

Could you tell me what are the resources devoted to evry app for training? As Wit is free, there must be huge number of apps, so is it the case that less computing resources are given to each app?

Thanks.

**Comment by doggeral** [comment]
Your app has been fixed. Since the app has huge amount of training utterance, the training is slow and fragile. It might be stuck for your future refresh. If it's possible, you can revisit the training set and try to keep it concise and simple.
