### ISSUE TITLE
How to get response in particular language 

### ISSUE THREAD

**Issue by andysagar** [wit-ai/wit#2534]
![image](https://user-images.githubusercontent.com/43470421/192465502-d9a97ba5-4ab0-4823-9c2a-f12a041f1b91.png)

I am not able to understand the language support of speech Api (audio to text), I have Hindi audio with me, and I am getting output in English text. What should I add in postman to get back Hindi text

**Comment by Satellite-system** [comment]
@andysagar  have you got a way, I too want the output text in speech API in hindi language, but getting it in english can you please help me ?
