### ISSUE TITLE
Http api not working

### ISSUE THREAD

**Issue by amit2k761** [wit-ai/wit#2537]
My http api is not working. The API is giving 500

I am using the following endpoint

https://api.wit.ai/message?v=20220928&q=water

My App id 247216750353110

Please help
<img width="978" alt="Screenshot 2022-09-28 at 4 58 58 PM" src="https://user-images.githubusercontent.com/17537897/192767818-656de73f-cdb6-41be-961f-afee4b826f6f.png">

**Comment by amit2k761** [comment]
@ChrisyShine  Please help

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
