### ISSUE TITLE
500 error on endpoint GET message

### ISSUE THREAD

**Issue by amit2k761** [wit-ai/wit#2538]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
On using the API https://api.wit.ai/message?v=20220503&q=water.
The server returns me{
    "error": "Something went wrong. We've been notified",
    "code": "unknown"
}`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Just use the GET Message endpoint 

**What is the expected behavior?**
Return all the available utterances

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
APP id  - 247216750353110

**Comment by amit2k761** [comment]
@ChrisyShine  please help

**Comment by ChrisyShine** [comment]
The get /utterances endpoint should be good for your app. Can you double check? And can you confirm which endpoint is broken? You mentioned 2 endpoints: get /message and get /utterances.

**Comment by amit2k761** [comment]
@ChrisyShine  /message endpoint is broken for me

**Comment by amit2k761** [comment]
@ChrisyShine  Please help on this .

**Comment by ChrisyShine** [comment]
There are some problems with the built-in entities. We are investigating and working on the fix.

**Comment by berniceburgos1** [comment]
APP id - [247216750353110](tel:247216750353110)

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
