### ISSUE TITLE
Timestamps not aligning with audio

### ISSUE THREAD

**Issue by bfavero** [wit-ai/wit#2539]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question

**What is the current behavior?**
I'm developing a transcription editor based on Wit and I was super happy when I saw you started sending timecodes for each word on the Dictation endpoin. However, in my experience, the words' time codes do not align very well with the audio, it's always off by a few hundred milliseconds. Is there anything I'm missing? Do you have any tips on how I could get more accurate time codes?

Thanks for the great work you guys do!

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by bfavero** [comment]
Hi, sorry to insist but does anyone from the Wit.ai team has any thoughts?

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
