### ISSUE TITLE
Request: Migration Assistant

### ISSUE THREAD

**Issue by hactar** [wit-ai/wit#254]
I know it was mentioned in a blog post at some time - but as I'm not seeing it on the "todo" list I'd like to remind and request that old "pre-stories" apps need some way to migrate to the new story system without having to redo everything please.

**Comment by l5t** [comment]
Thanks for flagging!

**Comment by erniedeferia** [comment]
Any update on this? When can we expect this capabiliy/feature to be released?

**Comment by hactar** [comment]
Closing as stories are deprecated ;).
