### ISSUE TITLE
Character Encoding Critical Bug - Foreign language apps do not tag existing explicit keywords

### ISSUE THREAD

**Issue by idanadut** [wit-ai/wit#2540]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
BUG
**What is the current behavior?**
Foreign language apps do not tag existing explicit keywords
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Some synonyms aren't recognized/tagged to the Entity keyword (even though they are explicitly mentioned in the synonyms list, and even though trained that word in an Utterance). I have many example in entities like "Brand", "ItemType" (most in hebrew). Try Utterance "נייק" which should be connected to "Nike".

This is a super critical bug in my opinion and known issue you fixed twice before, which I discussed with @patapizza  but it keeps coming back. ("Character Encoding Bug")
**What is the expected behavior?**
That existing explicit synonym keywords in entities will be tagged.
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
337695227605625

**Comment by patapizza** [comment]
Thanks for reporting, we're looking into it.

**Comment by idanadut** [comment]
Hi @patapizza 
It's still happening.  Any fix soon?
It's urgent since it doesn't tag most of the words in an app, and you fixed it in the past.

Thanks

**Comment by doggeral** [comment]
@idanadut I'm looking into it now.

**Comment by doggeral** [comment]
@idanadut  Seems that set the brand as the KeyWord can fix the issue. I've verified in wit.ai, it looks good now.
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/1651153/201285647-9b73dca9-6093-4398-8948-ac2ee849bfff.png">

**Comment by idanadut** [comment]
@patapizza @doggeral 
This is one small case, there are a lot of cases in which there is a keyword which is the same as the entity and it doesn't work. For example "נייק מכנסיים" (second word), or "שער". This is a bug I think you fixed in the past but it keeps coming back

**Comment by doggeral** [comment]
@idanadut for these cases, I recommend you to set up the "Lookup Strategies" as "Keywords" because you have lot of pre defined list, and the setting will provide high accuracy. 
Now the second word can be resolved correctly 
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/1651153/204646195-bccc9bc4-24e3-4c6d-a7d6-0842dcaa9fb7.png">

**Comment by idanadut** [comment]
@doggeral @patapizza 
-Did you change the lookup strategy in the app yourself? what changes did you do exactly? I brought them back to "Free Text & Keywords"

-The point is not to change the lookup strategy to "Keywords", since It's supposed to be opened to new values as well. This way you suggested will not guess new values when they come. When the strategy is "Free Text & Keywords" it is supposed to tag the existing keywords as a priority. In my opinion, this is a clear bug. 
Why Doesn't the predefined list of keywords work (also when the entity is opened to new values)?

You fixed this bug the past..but it came back

**Comment by doggeral** [comment]
@idanadut I see your point! I totally understand this is frustrating experience. To answer your questions: 
> Why doesn't the predefined list of keywords work

In wit implementation, the model and keyword can provide the inference response, then we run a merge logic to generate the final output. This means that the model prediction result can affect the final result and might make keyword setting ineffective. I check the training corpus, majority of the training utterance is very short. With the increasing of training utterances, it's hard for model to recognize the pattern very well. Also, some of the annotation might miss some labels. For example, Shall we tag the "Xiaomi" as brand? But from the training utterance provided, it has empty label. 

For the model part, I need more time to investigate. So I recommend you to set the lookup strategy to "Keywords" as quick workaround solution. In the meanwhile, I'll deep dive to see how to improve the model for your use case.

**Comment by idanadut** [comment]
Hi @doggeral @patapizza 
Thanks for the elaborated response.
Can't use the workaround since it must be opened to tag new values. To answer your question, Xiaomi should be tagged as brand (if its not then its a mistake, but the mistakes are probably rare).

Keywords should have priority. But even if not then look at the issue -it does tag a word as itself (**a lot of times in the correct entity**), instead of the keyword it belongs to in the predefined list. For example "שער" is tagged as ItemType "שער", so the _model does recognizes it as ItemType_, but it just doesn't tag it to the pre-defined list which is already there. It should be tagged to the keyword "Gate". 
Moreover to emphasize the issue, sometimes even when the keyword is in the predefined list, and also there is an exact utterance in the corpus that is already tagged correctly (like "שער כדורגל" or "נייק מכנסיים"), it still doesn't work . This behaviour is weird.
Would appreciate your help in checking this issue, and looking into a fix

**Comment by patapizza** [comment]
Thanks for the feedback @idanadut. This is indeed a bug. It looks like a difference in character encodings prevent keyword & free-text to merge results together.

**Comment by doggeral** [comment]
@idanadut the fix has been deployed. verified in production, it can resolved the entity correctly 
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/1651153/205722496-24a3d629-4b45-4cac-a3c3-6045e2711304.png">

**Comment by doggeral** [comment]
Closed the task, feel free to reopen it if you have any other questions.

**Comment by idanadut** [comment]
Thanks!
@doggeral @patapizza

**Comment by idanadut** [comment]
Hi 
@doggeral  @patapizza 
Happening again.
Sent example to @patapizza email.

**Comment by idanadut** [comment]
Hi
@doggeral @patapizza 
It's Happening once again. How come this bug keeps coming back?
Try "שער כדורגל" again
