### ISSUE TITLE
when importing intents from app to another, not all expressions are added

### ISSUE THREAD

**Issue by MeranTumeh** [wit-ai/wit#2541]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
We imported intents from an account on wit and exported them on a new account, but some expressions are not added to the new one.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
you can check the screenshots, "zain_jo_ar_new" is the old account and "zain_ar_178" is the new one.
![image](https://user-images.githubusercontent.com/111044474/193453353-56a09814-a5ef-4be8-9385-c1a5860eba82.png)!![image](https://user-images.githubusercontent.com/111044474/193453364-ef430b17-3fef-4dfb-8a2c-3f6b538d1084.png)
![image](https://user-images.githubusercontent.com/111044474/193453368-8fdd6416-32fd-4577-abeb-f232ddabeaae.png)

**What is the expected behavior?**
all the expressions should be added to the new account "zain_ar_178"

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
old account :  280962410285788
new account : 603072651299756

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
