### ISSUE TITLE
Is there any plan to add audio/mp3 to POST Synthesize

### ISSUE THREAD

**Issue by babakshir** [wit-ai/wit#2542]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by wangzhenict** [comment]
Hi @babakshir,
for better performance, we highly recommend audio/wav. 
can you elaborate your need about mp3? I want to collect more information about this and bring it to our discussion.
Thanks

**Comment by babakshir** [comment]
Hi wangzhenict,
Thank you so much for the replay. We are using the service on an embedded system with a very limited wireless chip (our wifi device is an esp8266). Our system cannot receive audio/wav and play it back continuously at the same time. We have no problem with POST /speech  using audio/mpeg3. The only real benefit of using WAV is simplicity.  Arguably the audio quality of WAV should be better than MP3, but that is mostly for music and not for speech.  Also, the amount of power used for transferring a large audio message is significantly larger than the power used to decode an MP3. Power usage is very important for battery powered embedded devices. I don't really see any performance benefit in using WAV.  It's just simpler.
Thanks again

**Comment by babakshir** [comment]
Release 20221114 supports mp3 output now. 
Thank you for your consideration
