### ISSUE TITLE
App training issue

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2543]
@ChrisyShine 
AppId: 376879450680207 is showing ongoing training for 2h. 
Can you please fix this.
And also why is this happening?

**Comment by JumanaNajdawi** [comment]
Same here Wit.ai
2906294449590571

Appreciate your help

**Comment by anjaly** [comment]
> @ChrisyShine AppId: 376879450680207 is showing ongoing training for 2h. Can you please fix this. And also why is this happening?

Now it got scheduled to a time after 2hrs :(
Can it be trained manually?

**Comment by ChrisyShine** [comment]
@anjaly The training is done now.

**Comment by ChrisyShine** [comment]
@JumanaNajdawi Your app's training is done now.
