### ISSUE TITLE
my app unable to train

### ISSUE THREAD

**Issue by Sarah-Aabid** [wit-ai/wit#2544]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**my app status is onGoing for 2 days

**What is the current behavior?**my app with Id : 1844458915724517 is still ongoing for more than 2 days , and i am unable to train any intent

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.*the training should be completed

**What is the expected behavior? the app to complete training

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**1844458915724517

**Comment by yuzh174** [comment]
Thanks for reporting this issue. Your app has finished training now.
