### ISSUE TITLE
Intent mismatch wrt character case(Upper/Lower)

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2545]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
We have created a wit.ai app in German language. The app is behaving differently according to the character case of the input. 
We have experienced the same for other languages also.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Step 1 : Input text "Wo ist das Rathaus" in the understanding tab. It will return the intent "where_can_i_park_in_schwbisch_gmnd"
Step 2: Input text "wo ist das rathaus"  in the understanding tab. It will return no intent.

**What is the expected behavior?**
The NLP should return the intent case insensitively ie for bot upper and lower case of the same text, it should return the same intent.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
AppId: 564876891603671

**Comment by anjaly** [comment]
> **Do you want to request a _feature_, report a _bug_, or ask a _question_ about wit?** bug
> 
> **What is the current behavior?** We have created a wit.ai app in German language. The app is behaving differently according to the character case of the input. We have experienced the same for other languages also.
> 
> **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.** Step 1 : Input text "Wo ist das Rathaus" in the understanding tab. It will return the intent "where_can_i_park_in_schwbisch_gmnd" Step 2: Input text "wo ist das rathaus" in the understanding tab. It will return no intent.
> 
> **What is the expected behavior?** The NLP should return the intent case insensitively ie for bot upper and lower case of the same text, it should return the same intent.
> 
> **If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.** AppId: 564876891603671

@ChrisyShine Can you please help us in fixing this issue.

**Comment by doggeral** [comment]
@anjaly what's the expected intent for the utterance? I retrain your app, both "Wo ist das Rathaus" and "wo ist das rathaus" has very low confidence.

**Comment by anjaly** [comment]
> Wo ist das Rathaus

Any update on the case insensitive handling of intents

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
