### ISSUE TITLE
Utterances are not all imported 

### ISSUE THREAD

**Issue by MeranTumeh** [wit-ai/wit#2546]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
when importing expressions from the utterances API to the wit app , it returns success but doesn't take them all

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
We have 2963 utterances for different intents, when importing them it only takes 2876

**What is the expected behavior?**
it should import the 2963 all

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
469629138450244

**Comment by imwide** [comment]
idk if this is the reason for sure since i cant see ur uterances but i know for a fact that it doesnt take double uterances

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
