### ISSUE TITLE
HTTP API error "Something went wrong. We've been notified" with code "unknown" (Status code 500 - Internal server error)

### ISSUE THREAD

**Issue by asvirtual** [wit-ai/wit#2547]
Wit HTTP API stopped working, and every time I make a request to the /message endpoint I get a 500 error with the message "Something went wrong. We've been notified".

The app ID is "1923421354481850", however I suspect the same issue is encountered for all my projects

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
