### ISSUE TITLE
Contributors added via API.

### ISSUE THREAD

**Issue by JacekLozinski** [wit-ai/wit#2549]
Can contributors be added via API? I haven't found an option anywhere. Are there such plans?

**Comment by jayyteee** [comment]
Hello @JacekLozinski thank you for your question. Currently there is no way to add in a contributor via API, so any contributors must be added through the wit.ai webpage from the app's settings page. We unfortunately have no plans at the moment to make this available via API, though it is something we could possibly consider in the future if we hear more feedback asking for this feature.
