### ISSUE TITLE
Urgent Bug - service returning "Bad auth" sometimes

### ISSUE THREAD

**Issue by idanadut** [wit-ai/wit#2550]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
BUG - super urgent
**What is the current behavior?**
"message" requests returning "Bad auth, check token/params" randomly every few calls (using v=20170307)
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
make same call to the service ~20 times, see it sometimes returns
{code: 'no-auth', error: 'Bad auth, check token/params'}
and sometimes it returns correct valid response

https://api.wit.ai/message?q=shirt&v=20170307&access_token=useYourAccessToken
**What is the expected behavior?**
correct valid response results to be returned always
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
337695227605625

**Comment by idanadut** [comment]
update - Works if you send as header 
'Authorization': 'Bearer <your token>',
but only if its in query sting it works sometimes

**Comment by jayyteee** [comment]
Hi @idanadut thanks for reaching out. As noted in our HTTP docs, it is expected that you include the access token as a header. See our docs here https://wit.ai/docs/http/20220622/#authentication_link
