### ISSUE TITLE
Wit adds plus signs to promt

### ISSUE THREAD

**Issue by imwide** [wit-ai/wit#2551]
Hey there! This is my code:

```
print("3", x)
resp = model_picker.message(x)
```

In the console it prints x like it should: 3 Test message
But in Wit in the utterances that were submitted with API it appears like this: "+Test+message"

This is nothing i can fix there is no piece of my code doing that. This has to be a prblem with wit. If not, please correct me

**Comment by patapizza** [comment]
Hi @imwide, this repo is to track Wit.ai service issues. It looks like you're using the Python SDK (`pywit`) - please submit a ticket [here](https://github.com/wit-ai/pywit/issues). Thanks!
