### ISSUE TITLE
Wit.ai Composer is unable to deploy flow to the runtime

### ISSUE THREAD

**Issue by jiemichong** [wit-ai/wit#2552]
*bug*

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Sending a POST request to /event gives me a 500 internal server error; and on the Composer page, the flow isn't being deployed to the runtime.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID: 2002661133457280

**Comment by MicheleYin** [comment]
Hi, I was wondering how you managed to solve the issue because I have the same problem. Thank you
