### ISSUE TITLE
Irrelevant response to wit api

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2554]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
After deleting all intents from the wit.ai app, "hi" text is returning "auto_entry_1" intent in npm node-wit message api. 
Also https://api.wit.ai/message?q=hi is returning the below response 
{
    "error": "Something went wrong. We've been notified",
    "code": "unknown"
} 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Try with npm node-wit message api for text:hi 
Try with https://api.wit.ai/message?q=hi 

**What is the expected behavior?**
'hi' shouldn't return an intent in both the npm api and api.wit.ai/message api

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID: 3203866336594782

**Comment by anjaly** [comment]
> **Do you want to request a _feature_, report a _bug_, or ask a _question_ about wit?** bug **What is the current behavior?** After deleting all intents from the wit.ai app, "hi" text is returning "auto_entry_1" intent in npm node-wit message api. Also https://api.wit.ai/message?q=hi is returning the below response { "error": "Something went wrong. We've been notified", "code": "unknown" } **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.** Try with npm node-wit message api for text:hi Try with https://api.wit.ai/message?q=hi **What is the expected behavior?** 'hi' shouldn't return an intent in both the npm api and api.wit.ai/message api **If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.** App ID: 3203866336594782

@patapizza Any update on the above issue. We are still not able to train the inputs via api.

**Comment by anjaly** [comment]
> 



> **Do you want to request a _feature_, report a _bug_, or ask a _question_ about wit?** bug
> 
> **What is the current behavior?** After deleting all intents from the wit.ai app, "hi" text is returning "auto_entry_1" intent in npm node-wit message api. Also https://api.wit.ai/message?q=hi is returning the below response { "error": "Something went wrong. We've been notified", "code": "unknown" }
> 
> **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.** Try with npm node-wit message api for text:hi Try with https://api.wit.ai/message?q=hi
> 
> **What is the expected behavior?** 'hi' shouldn't return an intent in both the npm api and api.wit.ai/message api
> 
> **If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.** App ID: 3203866336594782

@ChrisyShine Can u please look into this issue.

**Comment by ChrisyShine** [comment]
Looks like the app has been deleted.

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
