### ISSUE TITLE
Wit.AI 500 Internal server Error

### ISSUE THREAD

**Issue by Herbiebank** [wit-ai/wit#2555]
{
    "code": "wit",
    "error": "Something went wrong. We've been notified."
}

My App response getting frequently. its respond sometime its not getting response on some time. We will getting response like above.

**Comment by patapizza** [comment]
Hi @Herbiebank,

What is your app ID?

**Comment by Herbiebank** [comment]
Dear Team,

Kindly find the below App ID.

OGWQMWBETB5OSBBWH6UJYKP7UJUD73O4

**Comment by patapizza** [comment]
Hi @Herbiebank, this is your private app token, not your app ID. Please reset your token and share your app ID. Thanks.

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
