### ISSUE TITLE
Weird encoding case with Greek language

### ISSUE THREAD

**Issue by christosangelidis** [wit-ai/wit#2558]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
Weird encoding in some requests
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
We call this API endpoint.
AppId: 2092345764240756
"https://api.wit.ai/message?v=20200602&q=%CE%91%CE%B3%CF%8C%CF%81%CE%B1%CF%83%CE%B1%20%CE%AD%CE%BD%CE%B1%20%CE%B5%CE%B9%CF%83%CE%B9%CF%84%CE%AE%CF%81%CE%B9%CE%BF%20%CE%B5%CF%87%CE%B8%CE%AD%CF%82%20%CE%B7%CE%BB%CE%B5%CE%BA%CF%84%CF%81%CE%BF%CE%BD%CE%B9%CE%BA%CE%AC%20%CE%BA%CE%B1%CE%B9%20%CF%84%CE%B1%20%CE%BC%CE%AF%CE%BB%CE%B9%CE%B1%20%CF%80%CE%BF%CF%85%20%CE%B4%CE%B9%CE%BA%CE%B1%CE%B9%CE%BF%CF%8D%CE%BC%CE%BF%CF%85%CE%BD%20%CE%BC%CE%B5%20%CF%84%CE%B7%CE%BD%20%CE%B1%CE%B3%CE%BF%CF%81%CE%AC%20%CE%B1%CF%85%CF%84%CE%BF%CF%8D%20%CF%84%CE%BF%CF%85%20%CE&context={"locale":"el_GR"}"

Output:
{\n
  "entities": {},\n
  "intents": [],\n
  "text": "╬æ╬│¤î¤ü╬▒¤â╬▒ ╬¡╬¢╬▒ ╬Á╬╣¤â╬╣¤ä╬«¤ü╬╣╬┐ ╬Á¤ç╬©╬¡¤é ╬À╬╗╬Á╬║¤ä¤ü╬┐╬¢╬╣╬║╬¼ ╬║╬▒╬╣ ¤ä╬▒ ╬╝╬»╬╗╬╣╬▒ ¤Ç╬┐¤à ╬┤╬╣╬║╬▒╬╣╬┐¤ì╬╝╬┐¤à╬¢ ╬╝╬Á ¤ä╬À╬¢ ╬▒╬│╬┐¤ü╬¼ ╬▒¤à¤ä╬┐¤ì ¤ä╬┐¤à ╬",\n
  "traits": {}\n
}

You can also test it like this(unencoded):
q="Αγόρασα ένα εισιτήριο εχθές ηλεκτρονικά και τα μίλια που δικαιούμουν με την αγορά αυτού του εισιτηρίου δεν τα παρέλαβα γιατί;;;
 Ενημερώστε με"

**What is the expected behavior?**

No weird characters should be present.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2092345764240756

**Comment by ChrisyShine** [comment]
The url doesn't seem correct, how did you generate this url?
The query encoding seems wrong and the context format is wrong. We expect json serialized and uri encoded data for the context param.

**Comment by christosangelidis** [comment]
It was indeed a problem with the encoding from our part. Thank you very much for you help, I will close the issue.
