### ISSUE TITLE
Utterances not appearing in Understanding tab / Cannot train app

### ISSUE THREAD

**Issue by nickcbarone** [wit-ai/wit#2559]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
1. I log into Wit.ai
2. I select my app
3. I navigate to the Understanding tab so that I can train my app
4. I don't see any utterances available to train even though there should be hundreds

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. I log into Wit.ai
2. I select my app
3. I navigate to the Understanding tab so that I can train my app
4. I don't see any utterances available to train even though there should be hundreds

**What is the expected behavior?**
I should see hundreds of utterances that have come through our application from real users. I want to be able to train those utterances from real users.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1650554041800318

**Comment by nickcbarone** [comment]
Please help

**Comment by nickcbarone** [comment]
My paying customers need this resolved ASAP.

**Comment by maidaneze** [comment]
Hi Nick,

We are looking into this issue now. Will keep you updated.

**Comment by maidaneze** [comment]
Have you tried clicking on the start review button after you get into the understanding viewer section?

1. Log into Wit.ai
2. Select app
3. Navigate to the Understanding tab to train app
4. Click start review button
5. Select an intent for a utterance
6. Click entity matching
7. Click next
8. Make any amendments required
9. Click train and validate

Please let me know if this solved your issue.
<img width="1390" alt="Screenshot 2022-11-22 at 12 06 30" src="https://user-images.githubusercontent.com/8594849/203310117-232ed10a-3ade-43a1-8f2c-df28132caa15.png">
<img width="1350" alt="Screenshot 2022-11-22 at 12 09 55" src="https://user-images.githubusercontent.com/8594849/203310797-08fb1d95-b05c-4f40-9ca9-710d5fdb3341.png">
<img width="969" alt="Screenshot 2022-11-22 at 12 10 48" src="https://user-images.githubusercontent.com/8594849/203310803-8f07c270-4c77-45b3-ab45-e4817583b611.png">
<img width="1025" alt="Screenshot 2022-11-22 at 12 11 13" src="https://user-images.githubusercontent.com/8594849/203310808-1c3768ff-0ede-4b58-a1d5-73b1f4b12417.png">

**Comment by maidaneze** [comment]
Hi Nick,

We can see the utterances from our end.
You should be able to see the utterances on the understanding section.
Have you tried reloading the understanding section?
Is there a start review button in the understanding section?

**Comment by nickcbarone** [comment]
I don't see a "start review" button in my understanding. Attached is what I see.

As of today, I'll see the utterances, train one, and then they all disappear.

This is really hurting our business right now. Really appreciate your help.

<img width="1552" alt="Screen Shot 2022-11-22 at 8 37 30 AM" src="https://user-images.githubusercontent.com/11508524/203370505-d81c6be5-8b05-4cef-b99e-ece85eec06f3.png">

**Comment by nickcbarone** [comment]
Refreshing the page and/or clearing cache do not help

**Comment by nickcbarone** [comment]
Here's a video showing what we're experiencing: 

https://user-images.githubusercontent.com/11508524/203415283-752758e0-1283-42bb-8760-d0186f482a6e.mov

**Comment by yuzh174** [comment]
Hi @nickcbarone , thanks for reporting the issue. We utterances disappeared due to an internal refreshing logic which caused the wrong results. We are actually working on an improvement of the understanding page. You will get early access to it in 30 min. It's the same url, you just need to refresh the page. In the new page it's easier to review and you can batch annotate utterances. It should also resolve the issue that utterances disappeared.

**Comment by nickcbarone** [comment]
Thank you so much! I cannot wait to check it out. This has been a recurring issue for our business for the past 3 years.

**Comment by yuzh174** [comment]
You should have access to the new design of the understanding page. Let us know if it's helpful or if you have other feedbacks.

**Comment by nickcbarone** [comment]
Hello. I see the new version now but still having the same issue where the utterances disappear

**Comment by yuzh174** [comment]
That's strange. Does it disappear in the middle of the review process?
Could you attach another video recording of that?

**Comment by yuzh174** [comment]
I see in your app, now you don't have utterances to annotate from live traffic. So it's expected to see no data. 
The Understanding page will only show you the utterances from live traffic that has not been annotated yet. You can find all your annotated utterances under the Management/Utterances section https://wit.ai/apps/1650554041800318/utterances

**Comment by nickcbarone** [comment]
There are at least 40 utterances that had not been annotated yet from live traffic. They are still disappearing in the middle of training. Please help us resolve this issue.

**Comment by nickcbarone** [comment]
Please help. We're still having this issue and can't run our business effectively until it's fully resolved. Can someone please help us figure out where all of our utterances are? We're still not seeing any but can confirm we've received hundreds of utterances from real users.

**Comment by nickcbarone** [comment]
@yuzh174 Are you still able to help us?

**Comment by doggeral** [comment]
The training issue has been fixed.
