### ISSUE TITLE
Composer screen loading infinitely, can't download .zip for backup.

### ISSUE THREAD

**Issue by dmatheu22** [wit-ai/wit#2560]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug Report

**What is the current behavior?**
Cannot access composer screen as it loads infinitely. other menus work fine.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Logging in and opening composer screen.

**What is the expected behavior?**
Obvious

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
684414326383143

**Comment by yuzh174** [comment]
@dmatheu22 , curious did you delete any intent that's being referenced by the composer?

**Comment by yuzh174** [comment]
You have a Context node that seemed to reference a non-existing intent/entity. It's a dangling Context node that's not used. I have deleted for you. Now you composer UI is working and you should be able to export. 

We will work on a fix to solve the issue when referenced assets are removed

**Comment by patapizza** [comment]
it's recommended to [save a version](https://wit.ai/docs/recipes#version-your-app) after deploying, and use that version using the `tag` API parameter for latency (caching) and to ensure the runtime is unaffected by further app changes. We're looking into ways to automate that, but in the meantime, you have full control on avoiding this issue.
