### ISSUE TITLE
Trainings are stuck

### ISSUE THREAD

**Issue by aliugur** [wit-ai/wit#2561]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a *bug*

**What is the current behavior?**
Trainings are stuck

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Add new samples

**What is the expected behavior?**
Trainings should be finished

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1993006834227477, 2901888516784002, 430357495765959, 815593082829957

**Comment by maidaneze** [comment]
All of these apps seem to have finished training.

Please let me know if there is anything else you might need help with.
Otherwise I will close this issue tomorrow.
