### ISSUE TITLE
App in ongoing training status for long time

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2562]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
App showing 'Training' status for long time. The new intent and utterance are showing, but no response is getting on trying from 'Understanding' tab

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
App should train and return the intent on trying in understanding tab.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID: 821271815901275

**Comment by maidaneze** [comment]
Training is done for 821271815901275

Please let me know if there is anything else I can help you with.
