### ISSUE TITLE
App in ongoing training status for long time

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2563]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
App showing 'Training' status for long time. The new intent and utterance are showing, but no response is getting on trying from 'Understanding' tab
We are facing this issue for other apps also from yesterday.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
App should train and return the intent on trying in understanding tab.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID: 4344353432292657

**Comment by anjaly** [comment]
@maidaneze we are facing the issue for all the apps when we try to train a new question.
Clients are reporting issues. Please fix ASAP.
App ID: 4344353432292657
App ID: 949216419119159

**Comment by anjaly** [comment]
> @maidaneze we are facing the issue for all the apps when we try to train a new question. Clients are reporting issues. Please fix ASAP. App ID: 4344353432292657 App ID: 949216419119159

@maidaneze @patapizza @ChrisyShine Any update on this issue.

**Comment by maidaneze** [comment]
Hello anjaly,

We are looking into it.
Will give you an update later today.

**Comment by anjaly** [comment]
@maidaneze Any update on this. It has been 4 days it is showing as training.

**Comment by ChrisyShine** [comment]
Both 4344353432292657 and 949216419119159 are showing that training is done. Can you double check?

**Comment by anjaly** [comment]
> Both 4344353432292657 and 949216419119159 are showing that training is done. Can you double check?

One was done automatically yesterday. But other was not automatically done and we tried to retrain from the app and it completed training after that.
Was any fix done?

**Comment by maidaneze** [comment]
We are currently looking into it

**Comment by doggeral** [comment]
@doggeral Seems all training is done. Closed the issue. Feel free to reopen it if you have any questions.
