### ISSUE TITLE
App stuck in training for 20 hours. app ID:  542373750414845

### ISSUE THREAD

**Issue by AnabelleG** [wit-ai/wit#2564]
It has been training since yesterday morning. How can I deliver with such issues

**Comment by maidaneze** [comment]
Hi Anabelle,

I understand this can be inconvenient. We have limitations on the training capacity.
Training is currently ongoing and should finish soon.

**Comment by AnabelleG** [comment]
Thanks I will keep on checking

**Comment by AnabelleG** [comment]
Even APP 903255284174142 is blocked

**Comment by AnabelleG** [comment]
Both still training...

**Comment by idanadut** [comment]
Hi
Same here
App Id 337695227605625

**Comment by AnabelleG** [comment]
@maidaneze this app is till in training after 4 days: 542373750414845 🙄

**Comment by maidaneze** [comment]
Hi,
Training should be done for all of the apps
