### ISSUE TITLE
Slotfilling Chatbot gets stuck - Cannot start test conversation and cannot save properly (Composer)

### ISSUE THREAD

**Issue by wuestenloewe** [wit-ai/wit#2565]
I am trying to implement a Slotfilling Chatbot. It should extract 3 entities (Date, Duration, Project) from Userinput.
When some of those 3 are missing, it should ask specifically about those. (f.e. User gives a Date -> Bot should say "I still need the duration and the project")

I have created a Wit Bot that extracts given entities and saves them in the context, then checks what entities are saved, and then queries for the missing ones.

I'm new to Wit, so I'm not sure if the way I've done it is the best way to do it. Nonetheless, it should work logic-wise.

Anyway, my Problems are:

1. I cannot start a test conversation. I can only talk to the bot when I simplify it, so that it has less 'components'. Right now, it just keeps showing the orange dot in the right top corner, and when I hover over it, it says 'Validating'

2. The Bot often gets stuck while saving

Is it possible, that my Bot is already 'too large' ?

App ID is 1024408651607648

**Comment by yuzh174** [comment]
Thanks for reporting this issue. We are looking at it.

**Comment by yuzh174** [comment]
Sorry for the late response. The issue should be fixed now. Let us know if you still see any issues.
