### ISSUE TITLE
Dashboard view & app update issue

### ISSUE THREAD

**Issue by CannonFodderr** [wit-ai/wit#2567]
1. I Cannot view the wit.ai dash board, the page loads with no content & many console errors -See attached

2. This app: 1afad558-4217-4132-a9ff-0d6fee8573d4 returns errors for some reason when trying to edit or delete intents and utterances. 

<img width="1728" alt="Screenshot 2022-12-04 at 10 38 45" src="https://user-images.githubusercontent.com/36086310/205481687-c3024329-c344-4d4c-8aed-d27ad6396cac.png">

<img width="1728" alt="Screenshot 2022-12-04 at 10 38 31" src="https://user-images.githubusercontent.com/36086310/205481683-f9cd86ac-59ad-4e27-b93c-971a58a2c9de.png">

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
