### ISSUE TITLE
WIT scheduled training problems

### ISSUE THREAD

**Issue by anhphtuTVC** [wit-ai/wit#2569]
My app was training normally with 13k Utterances
But when i add 1 more Utterances for training and validate and then my app was Scheduled training. i have to wait many hours for the training start. 
Does anyone know how to train it immediately? help mee

**Comment by jayyteee** [comment]
Hi @anhphtuTVC can you give your app id? There could be a few reasons such as having other training jobs queued/in progress or its possible a job got stuck, but we need the app id to check your app's status

**Comment by anhphtuTVC** [comment]
1283324885786553 here is my app id . 
i just added 1 more utterances. and my current time is 9:08 AM. it says my training will start at 9:08pm . i think i have to wait 12hours again

**Comment by anhphtuTVC** [comment]
hi @jayyteee here is my app id. 1283324885786553 
i just added 1 more utterances. and my current time is 9:08 AM. it says my training will start at 9:08pm . i think i have to wait 12hours again

**Comment by anhphtuTVC** [comment]
here is seccond app id : 1087043918644857 . this app only have 3  Utterances. same waitting time (12hours)

**Comment by doggeral** [comment]
The issue has been fixed.
