### ISSUE TITLE
new version of Understanding 

### ISSUE THREAD

**Issue by sophiexr** [wit-ai/wit#2570]
hi, 

I have a question regarding the new version of training in Understanding. How do we delete the questions that we don't want to train or mark as out of scope?

We have a model with over 70.000 utterances and we mostly train the questions concerning new intents. The rest of the question are either irrelevant (that we could mark out of scope) or the intents are well trained (some with hundreds of utterances) so we don't won't to add anymore (those we **can't** mark as out of scope) . 

thanks

**Comment by yuzh174** [comment]
HI @sophiexr, in the intent match page, you can mark the intents as "Out of scope".

![Screen Shot 2022-12-20 at 10 10 13 PM](https://user-images.githubusercontent.com/73909056/208834030-ceee7299-6062-41d9-80f0-87f132a380b0.png)

**Comment by jqol** [comment]
Hi, I really miss the delete button. Would more Out of Scope utterances make training slower?

**Comment by yuzh174** [comment]
I can add back the button of delete, but since you already reviewed the utterances, if it is actually out of scope, I would recommend to mark them as out of scope. What is your app ID?

**Comment by sophiexr** [comment]
hi, 

we would really like the delete button back ! we have thousands of new questions everyday so it takes forever too mark the ones we don't have time to read as out of scope.

Also many questions that we delete are not really out of scope. we just don't want to add any more utterances in specific intents.

If there is an option to add back the delete button we would really appreciate it.

We have 3 apps and the ids are:

572046700564927

4926118934078909

618389522541052


thanks

**Comment by yuzh174** [comment]
Thanks for the explanations. Let me check to bring back the delete button.

**Comment by yuzh174** [comment]
Hi @sophiexr, we added the delete button in the new design. In the first review page for intent matching, if you hover over the utterances, it will show a cross button. That will delete the utterance from review. Hope that helps.

**Comment by sophiexr** [comment]
@yuzh174 
thanks so much !! that really helps a lot!! 

one more question, in the previous version you could see how many utterances are in the queue for training. Is there any way you can see that in the new version?

Thanks !!

**Comment by yuzh174** [comment]
Glad it helps. For the total number of utterances, you can't see that in the new version.
We encourage app owners to review live utterances but it's not required to complete all of them. The system should be able to handle unseen utterances from the already annotated ones.

**Comment by sophiexr** [comment]
thanks again for the resolution and the quick reply
