### ISSUE TITLE
Something went wrong. We've been notified

### ISSUE THREAD

**Issue by aliugur** [wit-ai/wit#2572]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a *bug*

**What is the current behavior?**
/utterances endpoint returns an error: "Something went wrong. We've been notified"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
get /utterances

**What is the expected behavior?**
Return utterances

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1919666991477468

**Comment by nishsinghal20** [comment]
Hi @aliugur! We're looking into this issue and will get back to you with a fix soon.

**Comment by ChrisyShine** [comment]
There were some inconsistency in the annotated utterances. We have fixed the problem. The /utterance API should be good now.
