### ISSUE TITLE
Bug: Can't export data

### ISSUE THREAD

**Issue by JumanaNajdawi** [wit-ai/wit#2573]
What is the current behavior?
I can't export the app data as zip, it works fine on our other apps, only this one has this issue.

Just click the 'download .zip with your data' button on the settings page, an error message appears saying "Something went wrong. We've been notified."

What is the expected behavior?
Launch the download of a zip file containing the bot data.

What is the App ID where you are experiencing this issue (if applicable)?

1920151674738030

**Comment by wangpingsx** [comment]
@JumanaNajdawi  we have fixed that for you, could you please try again?  thanks

**Comment by JumanaNajdawi** [comment]
It is solved now.
Thank you

**Comment by fertandil87** [comment]
same for me @wangpingsx  122782877418894 also the review page is broken when I move to the tab Update entity

Can you help? Thanks
