### ISSUE TITLE
Bug: Cannot Export Data due to entity Not found

### ISSUE THREAD

**Issue by aquilaadrian** [wit-ai/wit#2574]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
I want to report a bug.

**What is the current behavior?**
I cannot export my data form wit.ai
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I deleted one entity before exporting.
Then, i tried to press the download button, this error comes: "Entity '1130973670943475' not found"
![grafik](https://user-images.githubusercontent.com/35338628/211034814-2e6c7805-6c96-43ff-8b92-ed2f01752cdc.png)
**What is the expected behavior?**
It should export succcessfully
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
My AppID: 715012159778267

**Comment by wangpingsx** [comment]
@aquilaadrian  fixed, please try again.  thanks

**Comment by aquilaadrian** [comment]
tested and export is working now @wangpingsx, Thanks 🙏🏼

**Comment by iamkenken** [comment]
I have the same issue Entity 'd694e792-d92c-4e44-95fa-cb782d96367e' not found

APP ID: 1117875451674104

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
