### ISSUE TITLE
Switching between the stories

### ISSUE THREAD

**Issue by misysdclabs** [wit-ai/wit#258]
I'm wondering what happens if I change my mind inside a story and I start talking about a new topic.

Let's say I have two stories:
- order_pizza: a simple pizza ordering flow, specifying toppings and size
- reserve_a_table: the user want to come to the restaurant, and need a table in advance

With the old version, before the Bot Engine arrived we had states to handle this. When I knew that I need more data for the pizza I used an "order_pizza_re" intent to capture, which I indicated to use by pushing in a state. And the system tried to interpret the next input in this order:
- 1. as part of the pizza ordering
- 2. BUT if no match for the 1st, jump off from the state and try to match to any other intent

And that way I could switch easily the topic, just as I do when I talk to a human.

So now I'm experimenting with my two stories, but I don't understand what happens... sometimes it jumps to the other story, but most of the times doesn't. What is clear, that the interpreter understand the change, I see in the entities list that my "intent" entity changed as expected. But the flow handling is wacky.

Can somebody tell us how to handle these kind of situations?

**Comment by misysdclabs** [comment]
Maybe my question is not clear os just too complicated?

I try to make it short:
How and when will my bot change the story?

Or please let me know how can I help to make it clear.

**Comment by misysdclabs** [comment]
Thanks @ar7hur, the theory sounds good and sometimes my wit.ai app works exactly like this. But sometimes not, and even I found some crazy logs...

I created a big pack with screenshots, code and logs. I use the latest wit.ai node.js sdk, I use the quickstart.js as a starting point, I created here my actions and used the interactive mode for testing and saving these logs.

Please find attached the screenshots about my stories and the relevant part of my quickstart.js.

[order_pizza_rt.zip](https://github.com/wit-ai/wit/files/349532/order_pizza_rt.zip)

These logs are only examples, so I can't find a pattern like 'the switch works for one of the directions and not for the other one', as I see it works totally unpredictable.
TOC for the logs:
1 Switching from reserve_table to order_pizza
2 First order_pizza AND AFTER a reserve_table
3 Switching from order_pizza to reserve_table, that's real crazy...
4 Switching from order_pizza to reserve_table, now works right

Description for the logs:
- rt is an abbrevation for reserve_table
- _pre function is the first in the story and checks if every parameter is given for the command
- reset_context function is called after the user confirms the order and simply clears out the context

-------------------------
1 Switching from reserve_table to order_pizza
  - sessionId: 39d309d0-4352-11e6-a063-bd2cbb4c5f29
  - not working...

my node.js console log:
\> Book a table for 5 please
rt_pre
context in:  {}
entities in:  {"number":[{"confidence":1,"type":"value","value":5}],"intent":[{"confidence":0.9676418718944542,"value":"reserve_table"}]}
context out:  {"missingDate":true,"number_str":5}
sending... {"text":"When do you need this table?"}
\> Forget it, I want a pizza with tomato
rt_pre
context in:  {"missingDate":true,"number_str":5}
entities in:  {"pizza_topping":[{"confidence":0.826078442051885,"type":"value","value":"tomato"}]}
context out:  {"missingDate":true,"number_str":5}
sending... {"text":"When do you need this table?"}
\> I want a large pizza with tomato
rt_pre
context in:  {"missingDate":true,"number_str":5}
entities in:  {"contact":[{"confidence":0.8584893863488056,"type":"value","value":"I","suggested":true}],"pizza_size":[{"confidence":0.9635096456914578,"type":"value","value":"Large"}],"pizza_topping":[{"confidence":0.8264890981183097,"type":"value","value":"tomato"}],"intent":[{"confidence":0.9781756597764433,"value":"order_pizza"}]}
context out:  {"missingDate":true,"number_str":5}
sending... {"text":"When do you need this table?"}

-------------------------
2 First order_pizza AND AFTER a reserve_table
  - sessionId: afef2540-4357-11e6-84d8-fb472df08f4a
  - working

my node.js console log:
\> I want a large pizza
pizza_pre
context in:  {}
entities in:  {"contact":[{"confidence":0.86088002227462,"type":"value","value":"I","suggested":true}],"pizza_size":[{"confidence":0.9616087770809949,"type":"value","value":"Large"}],"intent":[{"confidence":0.9985352171103083,"value":"order_pizza"}]}
context out:  {"missingTopping":true,"size_str":"LARGE"}
sending... {"text":"Which toppings would you like to have on your pizza?"}
\> tomato
pizza_pre
context in:  {"missingTopping":true,"size_str":"LARGE"}
entities in:  {"pizza_topping":[{"confidence":0.7605930147356286,"type":"value","value":"tomato"}]}
context out:  {"size_str":"LARGE","topping_str":"TOMATO"}
sending... {"text":"You want a LARGE pizza with TOMATO, is that right?"}
\> yes
pizza
context in:  {"size_str":"LARGE","topping_str":"TOMATO"}
entities in:  {"yes_no":[{"confidence":0.9690613651302235,"value":"yes"}]}
context out is:  {"pizza_success":"Ok, it is on the way :)"}
sending... {"text":"Ok, it is on the way :)"}
reset_context
context is:  {"pizza_success":"Ok, it is on the way :)"}
entities is:  undefined
context out is:  {}
\> Book a table for 3
rt_pre
context in:  {}
entities in:  {"number":[{"confidence":1,"type":"value","value":3}],"intent":[{"confidence":0.981816246195783,"value":"reserve_table"}]}
context out:  {"missingDate":true,"number_str":3}
sending... {"text":"When do you need this table?"}
\> today 7pm
rt_pre
context in:  {"missingDate":true,"number_str":3}
entities in:  {"datetime":[{"confidence":0.9992612613905385,"type":"value","value":"2016-07-06T19:00:00.000-07:00","grain":"hour","values":[{"type":"value","value":"2016-07-06T19:00:00.000-07:00","grain":"hour"}]}]}
context out:  {"number_str":3,"date_str":"2016-07-06T19:00:00.000-07:00"}
sending... {"text":"You want to book a table for 3 at 2016-07-06T19:00:00.000-07:00, is that right?"}
\> yes
rt
context in:  {"number_str":3,"date_str":"2016-07-06T19:00:00.000-07:00"}
entities in:  {"yes_no":[{"confidence":0.9690613651302235,"value":"yes"}]}
context out is:  {"rt_success":"Ok, the table is waiting for you."}
sending... {"text":"Ok, the table is waiting for you."}
reset_context
context is:  {"rt_success":"Ok, the table is waiting for you."}
entities is:  undefined
context out is:  {}

-------------------------
3 Switching from order_pizza to reserve_table, that's real crazy...
  - sessionId: 8289f0c0-4358-11e6-a791-277fd52fc647
  - CRAZY mode

my node.js console log:
\> I want a large pizza with tomato
pizza_pre
context in:  {}
entities in:  {"contact":[{"confidence":0.8584893863488056,"type":"value","value":"I","suggested":true}],"pizza_size":[{"confidence":0.9635096456914578,"type":"value","value":"Large"}],"pizza_topping":[{"confidence":0.8264890981183097,"type":"value","value":"tomato"}],"intent":[{"confidence":0.9781756597764433,"value":"order_pizza"}]}
context out:  {"topping_str":"TOMATO","size_str":"LARGE"}
sending... {"text":"You want a LARGE pizza with TOMATO, is that right?"}
\> Book a table for 5 at 9pm
pizza
context in:  {"topping_str":"TOMATO","size_str":"LARGE"}
entities in:  {"number":[{"confidence":1,"type":"value","value":5}],"datetime":[{"confidence":0.9350618019346955,"type":"value","value":"2016-07-06T21:00:00.000-07:00","grain":"hour","values":[{"type":"value","value":"2016-07-06T21:00:00.000-07:00","grain":"hour"},{"type":"value","value":"2016-07-07T21:00:00.000-07:00","grain":"hour"},{"type":"value","value":"2016-07-08T21:00:00.000-07:00","grain":"hour"}]}],"intent":[{"confidence":0.9969443043913672,"value":"reserve_table"}]}
context out is:  {"pizza_success":"Sorry, forget it."}
sending... {"text":"When do you need this table?"}
sending... {"text":"Which size do you want your pizza?"}

-------------------------
4 Switching from order_pizza to reserve_table, now works right
  - sessionId: 15ca2b20-4359-11e6-8f87-13627f1017b5
  - Working like a CHARM

my node.js console log:
\> Give me a pizza with salami
pizza_pre
context in:  {}
entities in:  {"contact":[{"confidence":0.8063150963052043,"type":"value","value":"me","suggested":true}],"pizza_topping":[{"confidence":0.6974931286328502,"type":"value","value":"salami"}],"intent":[{"confidence":0.7738858874377668,"value":"order_pizza"}]}
context out:  {"topping_str":"SALAMI","missingSize":true}
sending... {"text":"Which size do you want your pizza?"}
\> Forget it, I want a table for 5 at 9pm
rt_pre
context in:  {"topping_str":"SALAMI","missingSize":true}
entities in:  {"number":[{"confidence":1,"type":"value","value":5}],"datetime":[{"confidence":0.9331298340132422,"type":"value","value":"2016-07-06T21:00:00.000-07:00","grain":"hour","values":[{"type":"value","value":"2016-07-06T21:00:00.000-07:00","grain":"hour"},{"type":"value","value":"2016-07-07T21:00:00.000-07:00","grain":"hour"},{"type":"value","value":"2016-07-08T21:00:00.000-07:00","grain":"hour"}]}],"intent":[{"confidence":0.5440458382089909,"value":"reserve_table"}]}
context out:  {"topping_str":"SALAMI","missingSize":true,"date_str":"2016-07-06T21:00:00.000-07:00","number_str":5}
sending... {"text":"You want to book a table for 5 at 2016-07-06T21:00:00.000-07:00, is that right?"}
\> yes
rt
context in:  {"topping_str":"SALAMI","missingSize":true,"date_str":"2016-07-06T21:00:00.000-07:00","number_str":5}
entities in:  {"yes_no":[{"confidence":0.9690613651302235,"value":"yes"}]}
context out is:  {"topping_str":"SALAMI","missingSize":true,"rt_success":"Ok, the table is waiting for you."}
sending... {"text":"Ok, the table is waiting for you."}
reset_context
context is:  {"topping_str":"SALAMI","missingSize":true,"rt_success":"Ok, the table is waiting for you."}
entities is:  undefined
context out is:  {}

**Comment by misysdclabs** [comment]
screenshot logs
1 Switching from reserve_table to order_pizza

![screen shot 2016-07-07 at 17 34 52](https://cloud.githubusercontent.com/assets/14309287/16659146/31f94ffe-4469-11e6-8201-ceb79a68b1ac.png)
![screen shot 2016-07-07 at 17 35 03](https://cloud.githubusercontent.com/assets/14309287/16659149/35c99788-4469-11e6-8d3b-35193233ed9c.png)

**Comment by misysdclabs** [comment]
2 First order_pizza AND AFTER a reserve_table

![screen shot 2016-07-07 at 17 36 18](https://cloud.githubusercontent.com/assets/14309287/16659218/74d59008-4469-11e6-8059-7f4c7074d550.png)
![screen shot 2016-07-07 at 17 36 28](https://cloud.githubusercontent.com/assets/14309287/16659228/7aeae902-4469-11e6-866f-bf7dc195945b.png)
![screen shot 2016-07-07 at 17 36 37](https://cloud.githubusercontent.com/assets/14309287/16659233/7faed750-4469-11e6-953f-90ce8d1383b1.png)
![screen shot 2016-07-07 at 17 36 45](https://cloud.githubusercontent.com/assets/14309287/16659239/84b5a152-4469-11e6-8afc-f1072e5ee433.png)

**Comment by misysdclabs** [comment]
3 Switching from order_pizza to reserve_table, that's real crazy...

![screen shot 2016-07-07 at 17 38 23](https://cloud.githubusercontent.com/assets/14309287/16659272/a2008970-4469-11e6-9a59-5d65322eff13.png)

**Comment by misysdclabs** [comment]
4 Switching from order_pizza to reserve_table, now works right

![screen shot 2016-07-07 at 17 39 06](https://cloud.githubusercontent.com/assets/14309287/16659314/c4389046-4469-11e6-8bdf-4f3f2334fe7c.png)
![screen shot 2016-07-07 at 17 39 22](https://cloud.githubusercontent.com/assets/14309287/16659319/c9a821f4-4469-11e6-9e5a-075cd8b49088.png)

**Comment by ktsakas** [comment]
I think the Wit.ai way would be to have a branch on every question that jumps to the other story. Then on every action if you detect a new intent you set a certain property in order to go to that branch.

But this way it's very complicated and you would have to have a branch on each question for each story you could possibly go to.

My solution it to check the intent on every action and if I detect a new intent I resend the response with a new session_id to the server with the same context. That way it's as if you start a new conversation, but you can also transfer the context.

The reason Wit.ai does not support this very well is that you gotta give it some sort of hint that it's possible to go to another conversation from a given point (otherwise it has no way of knowing this is possible), but if you wanna be able to jump to any story it's impossible to give it all the combinations (hence the solution above).

**Comment by misysdclabs** [comment]
New session_id! Very clever work around :)
I will try, thanks @ktsakas!

**Comment by misysdclabs** [comment]
@ar7hur, did you have a chance to check out my logs? Is there any news with this issue?

**Comment by dustinsmith1024** [comment]
I would like this too. Something to just say 'clear context after this response'.  I have the need to ask the same question back to back with different items in the context and they are cached and never hit my function.

**Comment by MathieuDuboy** [comment]
How do you clear the content @dustinsmith1024  ? Thank you

**Comment by Yashasvi1225** [comment]
**> order a small pizza**
pizza_pre
context in: {}
entities in: {"pizza_size":[{"confidence":0.9494761894238386,"type":"value","value":"small"}],"intent":[{"confidence":0.9196227762891878,"type":"value","value":"pizza"}]}
context out: {"missingTopping":true,"size_str":"SMALL"}
**reply from bot... {"text":"Which toppings would you like to have on your pizza?"}
> tomato and cheese**
pizza
context in: {"missingTopping":true,"size_str":"SMALL"}
entities in: {"pizza_topping":[{"confidence":0.903476673466153,"type":"value","value":"tomato"},{"confidence":0.9151907613757402,"type":"value","value":"cheese"}],"intent":[{"confidence":0.9022563004361318,"value":"pizza"}]}
newData: {"pizza_topping":[{"confidence":0.903476673466153,"type":"value","value":"tomato"},{"confidence":0.9151907613757402,"type":"value","value":"cheese"}],"intent":[{"confidence":0.9022563004361318,"value":"pizza"}]}
context out is: {"size_str":"SMALL","newData":{"pizza_topping":[{"confidence":0.903476673466153,"type":"value","value":"tomato"},{"confidence":0.9151907613757402,"type":"value","value":"cheese"}],"intent":[{"confidence":0.9022563004361318,"value":"pizza"}]}}
**reply from bot... {"text":"Which toppings would you like to have on your pizza?"}**
**APP ID**
YWOJ5LUHFKYT3VWEWZW7URLLLBA4HLYG

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
