### ISSUE TITLE
Use a token to interact with `/apps` endpoint

### ISSUE THREAD

**Issue by L0y3r** [wit-ai/wit#2582]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question

**What is the current behavior?**
At this moment there is no documentation about how get a token that lets me interact with [`/apps` endpoint](https://wit.ai/docs/http/20221114/#get__apps_link)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
You can use the provided example
```bash
curl -XGET 'https://api.wit.ai/apps?v=20221114&offset=1&limit=2' \
  -H "Authorization: Bearer $TOKEN" \
  -H "Content-Type: application/json"
```
**What is the expected behavior?**
Use `/apps` endpoint properly

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by yuzh174** [comment]
Hi @L0y3r , you can use a server access token from any app you own. A server access token can be obtained at the Settings page under an app. 
We will also improve our documentation on this.
