### ISSUE TITLE
Composer incorrectly handles multiple entities from a single utterance.

### ISSUE THREAD

**Issue by JEEPortman** [wit-ai/wit#2585]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

Bug

**What is the current behavior?**

Composer incorrectly handles multiple Entities derived from a single utterance as can be seen from this example:

<img width="832" alt="Screen Shot 2023-01-30 at 9 33 47 AM" src="https://user-images.githubusercontent.com/46435617/215440195-be6540e2-c268-4b0e-a62b-16d48a53d504.png">

<img width="353" alt="Screen Shot 2023-01-30 at 9 35 04 AM" src="https://user-images.githubusercontent.com/46435617/215440386-91017057-ff9b-43c2-8d04-2efce99ffe15.png">

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

A project is created as per the Recipe example called "Provide custom context":

<img width="1238" alt="Screen Shot 2023-01-30 at 9 17 24 AM" src="https://user-images.githubusercontent.com/46435617/215436283-080ea54c-ed7f-4a06-ab17-5c7308d1abc3.png">

The Entities color and shape are added to the project:

<img width="435" alt="Screen Shot 2023-01-30 at 9 19 26 AM" src="https://user-images.githubusercontent.com/46435617/215436688-23f5ff0b-ada2-4c08-a91c-e9ca7185b6b4.png">

A query is created and the context map set as per the example:

<img width="381" alt="Screen Shot 2023-01-30 at 9 20 40 AM" src="https://user-images.githubusercontent.com/46435617/215437099-dedf94a3-f54f-45b8-9d59-009c2de406e6.png">

The query is run with the following results:

<img width="360" alt="Screen Shot 2023-01-30 at 9 22 54 AM" src="https://user-images.githubusercontent.com/46435617/215437494-356c8718-b9d3-4f45-bd87-bb8c74742132.png">

**What is the expected behavior?**

The expected behavior as per the example is:

<img width="459" alt="Screen Shot 2023-01-30 at 9 24 37 AM" src="https://user-images.githubusercontent.com/46435617/215437885-d0d71691-b96d-4170-9b4d-d90154a69781.png">

**Further information**

The Understanding looks to be correct:

<img width="313" alt="Screen Shot 2023-01-30 at 9 27 19 AM" src="https://user-images.githubusercontent.com/46435617/215438678-e360a096-7c7d-47ff-9b20-b344975f79c1.png">

But the interpretation of the context commands is incorrect:

<img width="219" alt="Screen Shot 2023-01-30 at 9 29 09 AM" src="https://user-images.githubusercontent.com/46435617/215438932-a2519f66-7ec6-4cee-af43-aa9749068280.png">

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

My sample project can be found at this App ID: 3444606662449219

**Comment by patapizza** [comment]
Thanks for reporting, I'll look into it.

**Comment by patapizza** [comment]
Found the issue, fix upcoming.

**Comment by patapizza** [comment]
This is now fixed.
