### ISSUE TITLE
Feature request - Convert text field of response block to textarea field so that lengthy responses can be easily reviewed

### ISSUE THREAD

**Issue by adhilmunna** [wit-ai/wit#2586]
<img width="363" alt="image" src="https://user-images.githubusercontent.com/36878485/216379406-786c03db-2e61-4858-92f3-510152456e35.png">

Has to scroll horizontally and read entire response. Very difficult to review and edit response texts

**Comment by patapizza** [comment]
Thanks for the feedback, makes sense!

**Comment by CleanestMink126** [comment]
@adhilmunna 
If you load the page now, it should be a text area. Let us know if you have any more feedback!
