### ISSUE TITLE
Question - What is step through execution path?

### ISSUE THREAD

**Issue by adhilmunna** [wit-ai/wit#2587]
<img width="363" alt="image" src="https://user-images.githubusercontent.com/36878485/216380892-e18aa853-9e2b-4eeb-8d5c-c6acf5d978e7.png">

**Comment by patapizza** [comment]
When using the Play! interface, the path taken by the conversation is highlighted on the Composer flow. When enabled, it's auto-followed until the last module visited. When disabled, you can visually follow the path taken module by module. Hope this helps.

**Comment by adhilmunna** [comment]
> When using the Play! interface, the path taken by the conversation is highlighted on the Composer flow. When enabled, it's auto-followed until the last module visited. When disabled, you can visually follow the path taken module by module. Hope this helps.

Thanks. understood
