### ISSUE TITLE
Error Http 503

### ISSUE THREAD

**Issue by aquilaadrian** [wit-ai/wit#2592]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
When saying utterances or sending utterances typing via Understanding Viewer, cannot get result.
![grafik](https://user-images.githubusercontent.com/35338628/219043213-7ae69aa1-ba51-400e-9a54-b0ba05e2c545.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Say something using App Voice Experience, or sending utterances via understanding Viewer not getting result.
Console Reporting Error
"Http Request Failed [503]: The remote server returned an error: (503) Service Unavailable."
**What is the expected behavior?**
Uterrances should return intentions

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
AppID : 715012159778267

**Comment by aquilaadrian** [comment]
Also try to regenerate token and paste new token to Wit.conf but seems not working

**Comment by nishsinghal20** [comment]
Hi @aquilaadrian! Are you still seeing this issue? We investigated and think that it might have been a one-off instance where the availability of our service was affected temporarily. If you're still seeing this issue, please re-open this issue. It might be helpful if you can provide the exact time when you tried and it didn't work so we can look into our logs.
