### ISSUE TITLE
Wit responded with status: 500 (Internal Server Error). Language: Vietnamese. March 03, 2023

### ISSUE THREAD

**Issue by clarkondever** [wit-ai/wit#2594]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
a bug

**What is the current behavior?**
**/speech** API returns: "An error occurred in speech recognition."
It's working normally for the past year but appears to have this problem just now.
Language: Vietnamese

**The App ID where you are experiencing this issue**
123598113815657

**Comment by kisato126** [comment]
I have the same problem, I provide services in Vietnam, but my app cannot convert audio (OTP) into text. Please help me.

**Comment by wangzhenict** [comment]
Hi @clarkondever , @kisato126 , 
we are working on addressing the problem, will keep you updated.

**Comment by wangzhenict** [comment]
Hi @clarkondever , @kisato126, I think the problem has been fixed, can you check from your side? thanks!
