### ISSUE TITLE
Intent name in /intents endpoint case-insensitive but intent name in /utterances endpoint is case-sensitive

### ISSUE THREAD

**Issue by aliugur** [wit-ai/wit#2595]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a *bug*

**What is the current behavior?**
If you try to add same intent with lower-case, system returns ".. already exists" but if you try to add an utterance with intent name in lower-case, system returns "Could not find intent ..".

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Add an intent like "Test1". Try to add an utterance with "test1" as intent. It will give an error.

**What is the expected behavior?**
Intent name in /utterances endpoint should be case-insensitive too.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2117724271597207

**Comment by yuzh174** [comment]
Thanks for reporting this issue. We will check this issue and work on fix. 
To confirm, you can still develop using the matching case, not blocked by this bug. Is it right?

**Comment by aliugur** [comment]
Yes but I had to get intents and find the matching case to continue with the process.

**Comment by yuzh174** [comment]
This is fixed now. The /utterances endpoint now is case insensitive for intent names.
