### ISSUE TITLE
Update entity fails and result in blank page.

### ISSUE THREAD

**Issue by JellyfishCreations** [wit-ai/wit#2602]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
I am reporting a bug on the wit.ai understanding page

**What is the current behavior?**
When i am review predicted intents, and go to the "Update entity" step the page is just blank, and logging the following error to the console: `Cannot read properties of undefined (reading 'values') [Caught in: caught error in module ReactComponent (base)]`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I simple just go to review predicted intents, and not matter if i do any changes to the step before, when i go to "Update entity", no matter how i get to the step.

**What is the expected behavior?**
That the review flow works.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
513665250945711

**Comment by fertandil87** [comment]
same for me, I can't review

**Comment by nickcbarone** [comment]
Same here. My ticket is https://github.com/wit-ai/wit/issues/2604

**Comment by yuzh174** [comment]
Thanks for reporting this issue. We will release a fix to it soon.

**Comment by yuzh174** [comment]
The issue is fixed.
