### ISSUE TITLE
[Request] Will wit ever have support for other languages for text-to-speech?

### ISSUE THREAD

**Issue by Dannark** [wit-ai/wit#2603]
More support for other languages is something that I would love to see in wit. An also more variations of English voices to use..

BTW, Can we help or do our own voice models?

**Comment by jayyteee** [comment]
Hi @Dannark thanks for the feedback! We do plan to support more languages beyond English, but it is not the top priority at the moment so it likely won't be available until later this year or next year. There will be more variations of voices added throughout the year as well. As for using your own voice models, this is something we also are looking into and may have support for later this year.
