### ISSUE TITLE
Bug: Emojis not working in response

### ISSUE THREAD

**Issue by adhilmunna** [wit-ai/wit#2606]
**Response set in Wit builder**
<img width="356" alt="image" src="https://user-images.githubusercontent.com/36878485/229352507-3961b3d8-ebe8-4ced-8a69-54e9bf6f363a.png">

**Response sent by Wit to 3rd party app**
<img width="701" alt="image" src="https://user-images.githubusercontent.com/36878485/229352464-837e9331-2edb-4b89-bf13-e13886eb50e8.png">

**Comment by CleanestMink126** [comment]
Hello! Thanks for bringing this to our attention, you should be able to use emojis now. It will only work on **new** text, so you'll need to re-input the emojis into the response module to get it to work. Let us know if you're still seeing issues!
