### ISSUE TITLE
Unexpected UUID app_id when creating new app

### ISSUE THREAD

**Issue by lyntcelec** [wit-ai/wit#2607]
I used the following command to create a new app, but I received an app_id that looked like a uuid. Something doesn't seem right. If you use GET https://api.wit.ai/apps, the returned list will contain app_ids that are just 16-character strings.
<img width="719" alt="Screenshot 2023-04-03 at 2 17 40 PM" src="https://user-images.githubusercontent.com/12840833/229441806-dce10832-1a12-485e-ac50-67224c1dd8d7.png">

**Comment by maidaneze** [comment]
This is a legacy id. You can use it instead of the appID and the apis will still work.
If you want to get the new appId you can do so from the wit.ai/apps section.
Currently there are no plans to update this api to use the new appId
