### ISSUE TITLE
Training stuck in status "ongoing"

### ISSUE THREAD

**Issue by jBernavaPrah** [wit-ai/wit#2612]
Hi there!

this is the appID: 1723729534315875

Currently is stuck in ongoing like 3 hours. 
Can be fixed?

Thanks!

**Comment by jBernavaPrah** [comment]
Hi, now is more than 20 hours that is stuck. 

@zpao @ramh @Barbog @blandinw 

Sorry to tag you all, but I'm evaluating the product and I would like to complete it before the end of this weekend.

Thanks!

**Comment by Barbog** [comment]
Hi @jBernavaPrah , thanks for letting us know. 
I've looked into it and you should now be fine.

**Comment by jBernavaPrah** [comment]
Confirming now is completed! 

There is in someplace a roadmap for next the development for wit.ai? Like new features, fix of this issue, etc?

Thanks
