### ISSUE TITLE
How Change Voices Presets to use others langages FR/DE i.e ? UNITY v2021.3.23f1 - Oculus Integration V51.0

### ISSUE THREAD

**Issue by JZJeff** [wit-ai/wit#2618]
How can we change the language from text to speech? 
I am creating a vocal chatbot in VR application. I use Voice to Text and I would like to use Text To Speech as well.

By creating a French profile in Wit.AI it made Voice to Text in French possible. Now when I use the default scene in Oculus Integration: "TTSSample". I look to have the right wit-ai configuration based in French. I type "bonjour, comment vas tu?" and use the play mode.This generates errors. The error is simple, I try to make a french text speak to english voices...  When I look at the wit-ai configuration only the application is French and the Voices are still in English. When I click on Open Wit.ai at the bottom of the voices frame, I expect to see a Voices Presets Generator where I can choose the language and some available voices... But I can't find anything. Instead there is only this new system of voice commands... which doesn't interest me at all.

To reproduce my bug: 
1. Create an application in a language other than English (French for me) in the interface of wit.ai
2. Create a Unity application, by importing the Oculus Integration package
3. Then link your wit.ai application with Unity by creating either a new wit-ai configuration, or by using the one used in the TTSSample scene. Add the server and client tokens.
4. You will notice that in the application tab, this one is well noted as the one you have configured on wit.ai
5. In the Voices tab you will see that the available voices are only in English. There is no way to modify them or to create new ones.
6. Launch the TTSSample scene... Type a sentence in the chosen language and you will get the same error. 

How can I create or modify voices presets to use it in another language(French or Deutsch for me) than English ?

My wit.ai app id is : 235654159108028

**Comment by CleanestMink126** [comment]
Hi @JZJeff , unfortunately we do not support TTS with languages other than english at this point, so TTS can only be used with English apps. Though, we do plan to add it in the future.

**Comment by Uralstech** [comment]
Hi! I also ran into this issue while using Wit. I know this report is closed, but I would like to share my feedback.

> Hi @JZJeff , unfortunately we do not support TTS with languages other than english at this point, so TTS can only be used with English apps. Though, we do plan to add it in the future.

I think TTS support for additional languages is a very important feature for many developers who want to create multilingual apps using Wit. It would be great if you could update the FAQs to clearly state the current limitations of the TTS service. This way, developers can make informed decisions about whether to use Wit or look for other alternatives.

Still, I think Wit is a great free service from Meta, and I appreciate your work on this amazing tool. Thank you!
