### ISSUE TITLE
¿Is the Client Acces Token Shareable?

### ISSUE THREAD

**Issue by naielv** [wit-ai/wit#2624]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question
**What is the current behavior?**
Dockerized python web server (flask) that responds with a intent
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1280525479337574

Hi, ¿Is the Client Acces Token Shareable? (ej: the back-end source code is public, and there is a api-token inside the file "token.json")
Also: what are the differences between a client and a server access token

**Comment by patapizza** [comment]
Hi @naielv,

The client token is meant to power client-side applications (mobile, web, etc). It's not meant to be openly shareable.
