### ISSUE TITLE
Need API's to train Wit

### ISSUE THREAD

**Issue by prakashkrishnan1985** [wit-ai/wit#2631]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
This is a question: I want to train using an API call

**What is the current behavior?**
I used the end point as : https://api.wit.ai/samples?v=20220202 and https://api.wit.ai/samples

And I get the following error:

Training failed. Response code: 400
{"error":"Unsupported post request. Object with ID 'samples' does not exist, cannot be loaded due to missing permissions, or does not support this operation","code":"bad-request"}

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

I used the end point as : https://api.wit.ai/samples?v=20220202 and https://api.wit.ai/samples

And I get the following error:

Training failed. Response code: 400
{"error":"Unsupported post request. Object with ID 'samples' does not exist, cannot be loaded due to missing permissions, or does not support this operation","code":"bad-request"}

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by patapizza** [comment]
Hi @prakashkrishnan1985,

As part of the [refresh launch](https://medium.com/wit-ai/introducing-the-refreshed-wit-ai-3a7c603d325a) in 2020, we've moved to [`POST /utterances`](https://wit.ai/docs/http/20230215/#post__utterances_link).
