### ISSUE TITLE
Issue - Urgent attention required: Bot resets when reply is sent after just 5 or 10 mins

### ISSUE THREAD

**Issue by adhilmunna** [wit-ai/wit#2634]
as per reply in #2598 , session reset time is 30 days. However, bot defaults to step 1 when user replies are sent after just 5 mins. @yuzh174

![Group 89891](https://github.com/wit-ai/wit/assets/36878485/99bef78f-a263-4a39-b6ad-b45cd9e5833a)
![Group 89892](https://github.com/wit-ai/wit/assets/36878485/53ed6d78-eca9-479f-8383-2e768eb40c94)

**Comment by adhilmunna** [comment]
@harisvsulaiman

**Comment by patapizza** [comment]
Hi @adhilmunna, what is your app ID? Do you send the same `session-id` parameter?

**Comment by adhilmunna** [comment]
@harisvsulaiman, please elaborate....

@patapizza 1271982880337269

**Comment by harisvsulaiman** [comment]
@patapizza yes we send the same session I'd which we persist to the db.

**Comment by harisvsulaiman** [comment]
@patapizza @yuzh174 pinging you Just in case

**Comment by adhilmunna** [comment]
@patapizza 1271982880337269
@patapizza yes we send the same session I'd which we persist to the db.

**Comment by adhilmunna** [comment]
@patapizza incase you missed last mention. pinging you.

**Comment by adhilmunna** [comment]
@yuzh174
@patapizza
