### ISSUE TITLE
Migration to Meta accounts

### ISSUE THREAD

**Issue by bfavero** [wit-ai/wit#2640]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question

**What is the current behavior?**
Hi! Is there any action that needs to be taken by app owners before the upcoming migration to Meta accounts? Wit's homepage says that " we will set out the simple steps you need to follow at the end of June" but I haven't received any instructions.

**Comment by ChrisyShine** [comment]
Refer to our blog post for the Meta account login details: https://medium.com/wit-ai/were-moving-to-meta-account-log-in-deb2472aad3b
Following the blog post instructions, you can easily migrate to Meta account login by keeping all your existing wit apps with tokens not changed.

**Comment by bfavero** [comment]
Thanks for the link. Can you clarify if the credentials and apps of accounts that don't do migration before the June 27 deadline will stop working?
