### ISSUE TITLE
Test exception on PICO 4.

### ISSUE THREAD

**Issue by kat310** [wit-ai/wit#2641]
When I tested on PICO 4 (Android 10), I found that the network sent abnormally, and the data returned by the server was empty. Pico reported that the system recording was normal, and the ssdp permission was abnormal.
[logcat0620.log](https://github.com/wit-ai/wit/files/11795547/logcat0620.log)

**Comment by maidaneze** [comment]
Could you share the wit app id so we can debug this further?

**Comment by maidaneze** [comment]
Closing because of inactivitiy
