### ISSUE TITLE
Very slow performance for simple `session_id`

### ISSUE THREAD

**Issue by olivierlesnicki** [wit-ai/wit#265]
For example, requesting this url:

```
https://api.wit.ai/converse?v=20160704&q=hello&session_id=1
```

Takes between 10 seconds and 20 seconds to return a response.

While using a complex session_id such as `98b456a0723fa616284a632d9d31821b` consistently returns a response in sub 1 second.

My first guess is that the session ids are shared between all wit.ai clients - which would explain the performance issue and could highlight a security flaw.

**Comment by l5t** [comment]
Thanks for sharing. No sessions ids are not shared between all wit users ;-) As mentioned [here](https://wit.ai/docs/recipes#integrate-link), the session_id is a unique ID you generate on your side to group messages from the same user request/conversation. When you start a new conversation, you should generate a new one. You should generate a new one, even when the user is the same.
If you did 500 tests with the same session_id, we will try to fetch the history/data and then run the prediction model with this... that can take a lot of time. In practice, conversation will last on average 10 to 20 turns...

**Comment by olivierlesnicki** [comment]
I fully understand the concept of the session_id but nonetheless I thank you for this explanation.

However, the session ids that exhibit a very slow behavior (10-20 seconds) haven't even been used once in my app.

Considering our bot is not currently live, I've been using the current date/time to generate a "unique" id `(new Date()).getTime()`. Until yesterday this wasn't causing any issue. Since yesterday I can see the huge delays happening consistently.

I've asked for my bot to be retrained - and it didn't solve the issue. By appending a completely unique string (my first name) at the end of each session id I managed to remove the horrible delay.

**Comment by olivierlesnicki** [comment]
After much investigation we identified it as being an issue with our client and not wit.ai.
I confirm wit.ai doesn't have any issue with session_id.
