### ISSUE TITLE
Intent always returns 0 

### ISSUE THREAD

**Issue by DieterSupportSquare** [wit-ai/wit#2653]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
Intent has high confidence but always fails and states confidence is 0
![afbeelding](https://github.com/wit-ai/wit/assets/139466575/68f81361-9c63-4850-b639-b8f2dc9c5154)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
intents get wrong confidence score, seems like something is wrong with the JSON conversion.
**What is the expected behavior?**
getting the correct confidence score
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
658880399620628

**Comment by Barbog** [comment]
Hello. 
Looking at your screenshot, I'm seeing a confidence value of nearly 100%  (that is 0.93, which == 93%), which should indeed be a pass. 
What version of the API are you using?

**Comment by DieterSupportSquare** [comment]
I was using the latest version, but im sorry to say we stopped using wit.ai in the project.

**Comment by Barbog** [comment]
Ah. Sorry to read that. Sometimes these issues get missed. 
I hope you found a suitable solution for your games.

**Comment by DieterSupportSquare** [comment]
i debugged it a bit while i was still working with it and as far as i could see the problem was in the parsing of the JSON, hope u guys can fix this problem so other people dont have to deal with this becouse its a great product! pulling wit.ai from the project was not my call :)
