### ISSUE TITLE
I can't log in to Wit with the meta account

### ISSUE THREAD

**Issue by danielmarcovich** [wit-ai/wit#2656]
I made the migration to the meta account correctly, I managed to log in for several days and see my applications, however today I tried to log in and it won't let me log in to the applications, please can you help me?

User: daniel@marcovichsolutions.com

**Comment by yuzh174** [comment]
Hi @danielmarcovich , the problem should be fixed now. Could you try again and let us know if it is still happening?

**Comment by danielmarcovich** [comment]
> Hi @danielmarcovich , the problem should be fixed now. Could you try again and let us know if it is still happening?

Thank you very much, I can now enter wit.ai I was very scared hehe thank you very much!

**Comment by danielmarcovich** [comment]
Thanks!
