### ISSUE TITLE
Can Voice Stream be set to run indefinitely and not timeout with silence or max stream length?

### ISSUE THREAD

**Issue by calidave88** [wit-ai/wit#2658]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

Question - I'm setting up an app on a Meta Quest device to transcribe text in near-realtime and so far it's working well, however the voice stream stops after a few seconds when speaking stops, or of speaking continues at ~22 seconds. Is there a way to maintain the voice stream indefinitely while the user has initiated the voice transcription and not limit it to stop after hearing silence or timeout at 22 seconds when someone might still be speaking?

**What is the current behavior?**

~22 max voice stream with continuous speaking, or voice stream stops when there is silence

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

On Oculus device initiate voice commands and double press the Oculus button twice to start the voice stream.

**What is the expected behavior?**

I would like to set the voice stream to run indefinitely once the user has double clicked the Oculus button to allow for continuous voice transcription.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

1251327068809661

Thanks!

**Comment by jayyteee** [comment]
Hello @calidave88, is this our /dictation or /speech API you are using? If it is our /dictation endpoint, we do not end the request after silences on our end, so most likely it is the client that is ending the request at some point after the silence. You can test this by using a curl command with sox to our /dictation endpoint directly (examples in our HTTP docs). If you are using /speech, that endpoint will cut off after a long silence, so I would recommend using /dictation instead.
