### ISSUE TITLE
Question on adding 2nd language

### ISSUE THREAD

**Issue by jandieg** [wit-ai/wit#2664]
Our agent is doing fine with English, I see it does resolve some intents written in Spanish (without training), which is good. However things like wit/datetime do fail, for example.

So in plans to add a second language, whats the recommended approach? Is there a way to export and somehow transfer learnings into a new Wit in Spanish?

I am asking from the perspective of not having to train everything again.

Thanks

**Comment by nishsinghal20** [comment]
Hi @jandieg! wit/datetime is powered by Duckling. The app language sets the ruleset in Duckling (per language)
but you can override that per request by setting context & locale in the request (https://wit.ai/docs/http/#context_link)

In general, the current data model is one language per app.
