### ISSUE TITLE
Not detecting raw numbers as wit/datetime

### ISSUE THREAD

**Issue by jandieg** [wit-ai/wit#2665]
**Enhancement**

**What is the current behavior?**
Sometimes a time response is needed, and saying "12" is not recognized as a time.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

- Input "9"
- Entity suggested as wit/search_query
- There is no wit/datetime entity

**What is the expected behavior?**
- Input "9"
- Suggest wit/datetime entity (9:00AM/PM Today/tomorrow)

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
582793603989068

**Comment by nishsinghal20** [comment]
Hi @jandieg! Unfortunately, responding with just numbers is hard to capture as datetime unless there's more context, such as "9 pm" or "9 tomorrow", etc. You might be able to capture the numbers using the wit/number built-in entity type and then add some custom handling logic in your app/project to treat it as datetime.
