### ISSUE TITLE
Wit.ai Converse endpoint Error

### ISSUE THREAD

**Issue by mahieddine** [wit-ai/wit#267]
Hi,
Currently i'm facing a really strange issue (that i hadn't before)  
When i call for example wit.ai 

https://api.wit.ai/converse?v=20160727&session_id=didine5&q=très bien et toi?

I get a merge that's ok 
but 
Then  i call again wit 
https://api.wit.ai/converse?v=20160727&session_id=didine5

and i get an error instead of the stop 

{
  "confidence": 1,
  "type": "error"
}

Why??

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
