### ISSUE TITLE
Wit makes any numbers datetimes

### ISSUE THREAD

**Issue by mikob** [wit-ai/wit#268]
I'm trying to get wit.ai to learn/extract subjects. The subjects look like this:
Math 101
Math 2536
Phys 3500
Eng 3591
ECE 2536
etc.

I've created a free-text/keyword entity for subject. But even though I've trained it for the exact keyword "math 101"  and "Math 2536" it always takes "math" as the subject and makes the 101 or 2536, or whatever number as a datetime. The only things I've trained as a datetime are relative dates like "today" "tomorrow" and "yesterday". I would like the users to be able to say just "math" too, and I'll decide whether we need to disambiguate the subject based on their other classes. Basically it seems the subject intent needs to be more greedy.

Also there's a certain question where the answer from the user will basically always be just the subject (ie. Bot: Which class? User: ECE 2536) So I guess the substring extraction recipe won't work for this because there's no leading/following text?

**Comment by mikob** [comment]
This is pretty related so I'll put it in here. If I make an intent for subject and add "Speech and Composition", but also "Speech" and "Composition" separately, wit always matches two subjects "speech" and "composition" when I use the exact phrase I added earlier "Speech and Composition". I think it would ideally match the longest substring possible.

**Comment by l5t** [comment]
It seems to work now. Closing
![image](https://user-images.githubusercontent.com/6992759/35887993-08e9429a-0b4b-11e8-9f92-6373209b821a.png)
