### ISSUE TITLE
When is the deprecated API Deleted?

### ISSUE THREAD

**Issue by halemrani1996** [wit-ai/wit#2683]
I used this API https://api.wit.ai/message?v=20170307&verbose=true&q=مرحبا

and I got this response 
{
    "WARNING": "DEPRECATED",
    "_text": "مرحبا",
    "entities": {
        "intent": [
            {
                "_entity": "intent",
                "confidence": 0.9996006891901057,
                "value": "Get_Welcome"
            }
        ]
    },
    "msg_id": "MI6u7QQqLm1HOVC5nhp"
}

i need to know this API How long will you keep working until Upgrade works?

**Comment by jayyteee** [comment]
Hi @halemrani1996 the reason you see deprecated is your version number in the GET /message request is from 2017 and is no longer supported - we recommend testing out and switching your request to use the latest version available which currently is 20230215. See our docs for the latest version here: https://wit.ai/docs/http
