### ISSUE TITLE
Discrepancy Between User Interface and API Response: Missing Intents Data

### ISSUE THREAD

**Issue by AlexisNichel** [wit-ai/wit#2687]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug

**What is the current behavior?**
The current behavior is that the API response does not include any data in the "intents" field, even when an intent is detected in the query. The "intents" field is empty in the API response, even though the corresponding intent is displayed in the user interface (UI).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Steps to reproduce:
Make a GET request to the Wit.ai API with a valid authorization token.
Use the following query: "cancelar mi plan".
Inspect the API response and observe that the "intents" field is empty, even though there should be an intent detected.

**What is the expected behavior?**
The expected behavior is that the API response should include the detected intent when an intent is present in the query. In this case, the detected intent should be "cancelar mi plan."

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
APP IDs: 1492533901537194 AND 1856185531061946

UI (correct intent):
![image](https://github.com/wit-ai/wit/assets/15020002/eeb6c44a-f6ec-4cdf-9016-39607e186b29)

API (empty intent):
<img width="490" alt="image" src="https://github.com/wit-ai/wit/assets/15020002/11a61d23-cf7a-4258-898f-443bd5f9972f">

**Comment by halemrani1996** [comment]
We also suffer from the same problem. We do not have the same intentions. Please solve this problem
APP ID: 1920151674738030
![wit_umniah](https://github.com/wit-ai/wit/assets/109739943/068f08a9-b3f1-4c4a-a1ac-acc490d09055)

**Comment by alexemmfp** [comment]
Same here

**Comment by alexemmfp** [comment]
@patapizza could you please assist us? This is affecting many of our clients.

**Comment by guilhermebiegelmeyer** [comment]
I have the same problem, any solution?

App id 
842963869513825

**Comment by nomiero** [comment]
Looking into this.

**Comment by crisgio24** [comment]
Hi, i have the same problem.
App ID:
394693855538917

**Comment by nomiero** [comment]
Can you try now and let us know if it's back to work ?

**Comment by crisgio24** [comment]
Ready, it works fine

**Comment by AlexisNichel** [comment]
Ready, it works fine. Thanks you

**Comment by crisgio24** [comment]
Thank you very much.

**Comment by magnusburton** [comment]
Still not working for me (602750488506714). Not been receiving intents for the past couple of days.

In my statistics I've been getting a huge increase in 'out of scope' matches, which may result in no intent being returned. What could be the issue?

**Comment by nomiero** [comment]
This issue should be resolved now. Please reopen the ticket if it still exists.
