### ISSUE TITLE
wit returns no intents

### ISSUE THREAD

**Issue by halemrani1996** [wit-ai/wit#2688]
We have a problem reproducing intents by interpreting sentences from this API. Please support quickly

These apps ids : 1920151674738030
![wit_umniah](https://github.com/wit-ai/wit/assets/109739943/697a41ce-3e54-4bb8-862a-604592ed783c)

Thanks

**Comment by Barbog** [comment]
Hi halemrani1996,
I've tried a few different utterances from within the Understanding Viewer and it seemed to be working fine. 
Could you also try out the equivalent `curl` call with one of the utterances from the Utterances tab?

**Comment by AlexisNichel** [comment]
Hi @Barbog, 
I have same problem https://github.com/wit-ai/wit/issues/2687

**Comment by guilhermebiegelmeyer** [comment]
I have the same problem, any solution?

App id
842963869513825

**Comment by nomiero** [comment]
This issue should be resolved now. Please reopen the ticket if it still exists.
