### ISSUE TITLE
[Urgent] Message API is returning empty response for multiple apps

### ISSUE THREAD

**Issue by aya-labiba** [wit-ai/wit#2689]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
The message API is returning an empty response that does not contain any intents or entites 
Below is a screenshot that shows the issue:

![image](https://github.com/wit-ai/wit/assets/99329638/24b193e0-0471-4633-8f58-f279065d8c7e)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Call the API response for the below App id: 1649358388514097

**What is the expected behavior?**
The API to return correct responses that contain Intents and entites 

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1649358388514097
280962410285788
204584064787119
1087225748463876
**(will add more app ids once given)**

**Comment by AlexisNichel** [comment]
Same here https://github.com/wit-ai/wit/issues/2687

**Comment by guilhermebiegelmeyer** [comment]
I have the same problem, any solution?

App id
842963869513825

**Comment by crisgio24** [comment]
Hi, i have the same problem.
App ID:
394693855538917

**Comment by nomiero** [comment]
Issue should be resolved since last week. Please reopen if it still exists.
