### ISSUE TITLE
Wit.ai infinit loop 

### ISSUE THREAD

**Issue by mahieddine** [wit-ai/wit#269]
Hi,
I'm currently facing a really strange issue in wit. i have a simple story where basically the user says Hi, then i have a merge where i get the intent, then i call an action on my side to add his name to the context and final send a Hi {firstName}  

Hi

```
                                     Merge
                                         Salutations
                                     getUserFirstName
                                        firstName

                                     hi {firstName}
```

The problem is that : 
1 - Wit.ai don't take this story when the user says hi
2 - Wit performs an infinite loop (which is very dangerous !!), basically wit never stops, whenever i call the converse api to advance wit sends the same message and doesn't stop, how do i know when to stop if i don't received a stop message

When i remove my getFirstName action everything works well any ideas ?

PS : i already checked in my actions tab that my message action Hi {firstName} has only if salutations+firstName

Thank you !

**Comment by l5t** [comment]
Did you create an intent entity to detect the Hi? Can you share your Wit app URL so that we can look into it

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
