### ISSUE TITLE
Confidence in wit training

### ISSUE THREAD

**Issue by halemrani1996** [wit-ai/wit#2691]
I'm facing an issue with some Sentences It returns to us with less than 65% confidence,please can advice me?
![wit_issue](https://github.com/wit-ai/wit/assets/109739943/f733775c-a84b-464b-8791-24973e7cbbb7)

**Comment by nishsinghal20** [comment]
Hi @halemrani1996! Could you please share the Wit app ID? Also, have you trained your app on the sentences that you're trying to validate? To increase the confidence, we recommend training variations of the sentence to facilitate the system to better recognize the sentences.

**Comment by nishsinghal20** [comment]
Closing due to lack of Wit App ID. As suggested above, please train the app on more variations of the utterances so that the model can better recognize them.
