### ISSUE TITLE
API does not return Intent for utterance, but UI does

### ISSUE THREAD

**Issue by tomlancasterburst** [wit-ai/wit#2694]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
Processing an utterance through the API does not return any Intent, whereas processing the same utterance through the UI does return an Intent. For now this issue seems limited to this app ID = **3118831018157410** but in the past it has happened to other apps in our account.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Request a response using the API for GET https://api.wit.ai/message?q=no thats incorrect bob@gmail.com&v=20231121 and the API key associated with app ID = **3118831018157410**
Notice the intent array is empty while the entity wit$email is returned correctly.

Result from API (intent array is empty)
![image](https://github.com/wit-ai/wit/assets/92904501/a25766b2-8a90-416a-9dbf-bc7aae262bf0)

**What is the expected behavior?**
Intents found in an utterance should be returned in the API response just like the UI.

Response from UI (intent 'No_Incorrect_Address' is there)
![image](https://github.com/wit-ai/wit/assets/92904501/43cdb94b-bc2e-49d5-aea4-c8ae37af7c72)

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
Current issue is on App ID = **3118831018157410**
This also occasionally happens on other Apps in our account and then at some point starts working again. The exact same issue described in this ticket happened recently for App ID = **520911122279739** but after about a week it was resolved. **Is there a way we can we fix this issue ourselves so that it does not interrupt our business in the future?**

**Comment by nomiero** [comment]
Thanks for reporting, looking into it.

**Comment by nomiero** [comment]
This should be fixed now. Can you please try on your side ?

**Comment by tomlancasterburst** [comment]
Thanks @nomiero !
Yes it's working now. Is there anyway I can fix this myself next time short of recreating the app?
![image](https://github.com/wit-ai/wit/assets/92904501/ded3b049-52b1-4048-b1e4-38d824fca336)

**Comment by nomiero** [comment]
For this specific case, we had an issue on your side and it caused side effects like that and we had to fix it on our side. the only other way was to recreate the app. 
 But in general, when such issues happen. The first thing to try is to add any new utterance and then retrain the app and see if that helps.

**Comment by tomlancasterburst** [comment]
Thanks again!
