### ISSUE TITLE
Arabic support not working

### ISSUE THREAD

**Issue by amjadkamali** [wit-ai/wit#270]
Hi, I set up a new bot on wit in Arabic along with some basic entities, but wit isn't parsing the text correctly.

It's reading مرحبا as ￙ﾅ￘ﾱ￘ﾭ￘ﾨ￘ﾧ so even though I have it saved as a keyword, it's not getting the entity.

curl -H 'Authorization: Bearer $token' 'https://api.wit.ai/message?v=20160711&q=مرحبا'
Response:
{
  "msg_id" : "1c7a3f43-417e-4d1f-a940-a289ffd8ec8c",
  "_text" : "￙ﾅ￘ﾱ￘ﾭ￘ﾨ￘ﾧ",
  "entities" : { }
}

**Comment by patapizza** [comment]
@amjadkamali Sorry for the latency here.

Please reopen if you still experience the issue (provide your app id). Thanks!
