### ISSUE TITLE
[URGENT] Not getting intent via /message API in production app

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2700]
Hi team,

We had a problem with one of our production apps today (worked till 3:37am UTC). When checked after logging into the wit.ai account, the inputs in the 'Understanding' tab return the correct intent. But with the /message API, the same input returns the below response.

{
    "entities": {},
    "intents": [],
    "text": "hi",
    "traits": {}
}

We need to check urgently why the API isn't returning the intent. Please help.

AppId: 852586566300145
AppId: 240207492155841

Thanks

**Comment by r-alnairab** [comment]
We had the same issue, but the engine is working now.
Is it working for you now @anjaly ??

**Comment by halemrani1996** [comment]
same issue and These apps IDs: 1920151674738030,1850539691729312

**Comment by anjaly** [comment]
@r-alnairab The above mentioned app ids are working but have issue with another app id also 972992800582921

**Comment by r-alnairab** [comment]
@anjaly seems like instability issue

**Comment by nomiero** [comment]
Please let us know if the issue is still happening. It should be resolved now.

**Comment by halemrani1996** [comment]
> Please let us know if the issue is still happening. It should be resolved now.

on my apps the issue was solved.

**Comment by anjaly** [comment]
> Please let us know if the issue is still happening. It should be resolved now.

@nomiero The issue is fixed now.
