### ISSUE TITLE
wit returns no intents

### ISSUE THREAD

**Issue by halemrani1996** [wit-ai/wit#2701]
We have a problem reproducing intents by interpreting sentences from this API. Please support quickly

These apps ids : 1920151674738030,1850539691729312
![image](https://github.com/wit-ai/wit/assets/109739943/1e1d9207-094d-4fa9-9aab-010131c0af6a
![image](https://github.com/wit-ai/wit/assets/109739943/1f76c5d6-439b-484a-9ffd-adcb11dc7cc0)
![image](https://github.com/wit-ai/wit/assets/109739943/24728d44-fcc0-420c-9925-93c941767011)
![image](https://github.com/wit-ai/wit/assets/109739943/f61ee508-4e62-40ec-be87-7d7e3441ef1d)

**Comment by nomiero** [comment]
Marking as resolved per the other thread
