### ISSUE TITLE
Training Issue

### ISSUE THREAD

**Issue by abdalrahman-alhmouz** [wit-ai/wit#2704]
I am currently facing an issue while training my bot. After training any utterance, the chatbot is unable to recognize it in the understanding view. Additionally, I encountered this issue after creating a new bot.

**Comment by nomiero** [comment]
Thanks for reporting the issue. can you provide the app id ? Also is that in the UI only or via http requests as well ?

**Comment by nomiero** [comment]
Actually we found the bug related to this, we will fix it and update here. This should only affect the UI and not the http requests.

**Comment by nomiero** [comment]
This should be resolved now. Please confirm if you are still running into the issue.

**Comment by abdalrahman-alhmouz** [comment]
i checked this issue from my side and it is working now thank you
