### ISSUE TITLE
question: How to pass multiple variables to single context

### ISSUE THREAD

**Issue by adhilmunna** [wit-ai/wit#2707]
How can I construct a string after taking multiple user input and pass it to a single context aka, save it to one variable.

**Comment by yuzh174** [comment]
@adhilmunna what is the use case? Do you want to concatenate multiple round of user transcription into one long string?

**Comment by adhilmunna** [comment]
> @adhilmunna what is the use case? Do you want to concatenate multiple round of user transcription into one long string?

Yes. Kind of. Creating a summary out of specific user inputs collected over multiple steps and pass it to external app as a single string.

**Comment by yuzh174** [comment]
We currently don't support this directly inside the composer, but you have more control on the client side to concatenate strings and send them in the context map (if you need them inside the composer processing)

**Comment by adhilmunna** [comment]
Hmm... Thats additional work though. Could have been better if there was an option to do that from within wit. Not super necessary for now though.
