### ISSUE TITLE
Wit makes a number a location

### ISSUE THREAD

**Issue by mahieddine** [wit-ai/wit#271]
I'm using wit.ai (french app), and i'm using wit/location intent, the problem is that wit whenver i say "à something..." wit detects it as a location which is wrong how can i deal with this please ? thank you

**Comment by MathieuDuboy** [comment]
+1

**Comment by nkov** [comment]
+1, frequently when detecting numbers such as 1500, 850, it parses as a location instead of a number.

**Comment by blandinw** [comment]
@nkov what language are you using?

We're working on a smarter algorithm to detect and resolve locations.
At the moment, we recommend that you do some validation on the location detected by Wit to make sure it makes sense for your application.

**Comment by michaelulin** [comment]
+1

**Comment by blandinw** [comment]
Thanks, we're tracking this internally

**Comment by patapizza** [comment]
This should be fixed now.
