### ISSUE TITLE
question: [TextToSpeech] How do I switch the language of the TTS voice using code at runtime?

### ISSUE THREAD

**Issue by 96Rick** [wit-ai/wit#2710]
I use wit.ai's text-to-speech function on my oculus device. It's really great, especially some events during runtime! They are very detailed and really helpful!
There is just a small problem for me. As the requirements change:

1. I want the TextToSpeech function to speak voices in different languages ​​besides English, including German, French, etc.
2. And I need to be able to dynamically switch the voice I want to speak at runtime.

I noticed in the FAQ that wit.ai should have this function now like the picture down there, but unfortunately I didn’t find a clear tutorial to explain how to achieve the above requirements.
Could you help me and explain the requirements to achieve the above, if so, it would be really helpful for me. 

Thanks very much!
![Picture](https://github.com/wit-ai/wit/assets/25795949/a4394fde-10fa-4e85-b155-681ea6b410a3)

**Comment by jayyteee** [comment]
Hi @96Rick thanks for reaching out. While the list of languages you shared are supported for certain features on Wit.ai, we currently only support English officially for our text-to-speech service at this time. In the future we do plan to support more languages in our /synthesize API but at this time they are not available. There is no timeline yet on when additional language support will be added, but I recommend checking back later this year.
