### ISSUE TITLE
Please just save by default

### ISSUE THREAD

**Issue by DavidAwad** [wit-ai/wit#272]
if I'm making stories I don't want to have to save every time. I've already gotten the "unsaved changes" javascript alert button 300 times. Someone will always be fine tuning their bot, it doesn't matter whether you do addditional saves. Just make sure to have some 600 millisecond wait time for additional keystrokes or changes.

**Comment by l5t** [comment]
Thanks for sharing. Interestingly we just moved away from auto save cause we received a lot of feedback from the community. It was highly disruptive to have auto save, check, warning while creating a story.

**Comment by mahieddine** [comment]
The save button is a good idea, it wasn't the case before and we hadn't a feedback if the story was saved or not.

**Comment by patapizza** [comment]
@DavidAwad You can hit Cmd+s to save your story. After a couple of times, you won't need to think about it anymore :-)
