### ISSUE TITLE
Every question is returning the same intent

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2736]
Bug

We have created a new app with 5 intents
![image](https://github.com/user-attachments/assets/72148538-9e85-440a-92b4-8b73516fc702)
For most of the questions, the app is returning intent 'hi'

'hi'  intent is trained only with the utterances 'hi', 'howdy-d', 'i need help' and 'hello'. Even if we input 'How many continents are there?' it is returning 'hi' intent with 84% confidence
![image](https://github.com/user-attachments/assets/39ce1139-1f23-4b5d-bb3e-761860a51371)

![image](https://github.com/user-attachments/assets/759e43dc-bfd7-4120-857e-a1eac780ccf6)

On inputting questions that are no trained it should return no intent.

App Id : 999960068279528

Please suggest a way where no intent gets returned for random questions asked.

Thanks in advance

**Comment by anjaly** [comment]
@patapizza can you please help in resolving the issue

**Comment by maidaneze** [comment]
@anjaly Wit will try to match any utterance to one of the intents. You can create a default intent to catch most phrases that aren't recognized.

**Comment by anjaly** [comment]
@maidaneze   Since we were facing the same issue from the beginning we used to create 2 intent auto_entry_0 and auto_entry_1 automatically (with the following entries) on creating the app .


auto_entry_0
--------------
49ugqqa78hpg4xbw
ykuda5ycvzpyymst
zs85ks6d9zsgrrar


auto_entry_1
--------------
tdezyy6nsrj4juh2
yesr7ch7uhtpqx5v
nmjhzmeaaxqyb56a

But this is not helping to fix the concern our clients are facing. So currently we are trying to train the keywords 'What', "When', 'How', 'Where' etc in these two intents.
Then we came across another issue that the NLPis returning different intent/confidence according to the text case (lower/upper.)
Below is the example

what day is today?  Reply with 128 character or less => returns no intent
![image](https://github.com/user-attachments/assets/58800639-a46f-4f9f-821e-44f9d87d34fb)

what day is today?  reply with 128 character or less => Returns 'hi' intent
![image](https://github.com/user-attachments/assets/2d77cd8b-abf2-4ff9-bddd-158415b1b174)

Can the case sensitive issue be fixed

Thanks & Regards

**Comment by anjaly** [comment]
@maidaneze Any update on the case sensitive issue

**Comment by anjaly** [comment]
@maidaneze  @patapizza Can you please help us in fixing the training and case sensitivity issue.

**Comment by maidaneze** [comment]
I've just tried out the case sensitivity issue, and I can't replicate it. Could you give more examples?

**Comment by anjaly** [comment]
Hi @maidaneze 

Can you please check the following question in the provided app id

Question1 : what day is today? reply with 128 character or less
Question2: What day is today? Reply with 128 character or less

App ID: 1026170528689872

**Comment by maidaneze** [comment]
I've copied the app you provided and ran the following tests.

Question1 : what day is today? reply with 128 character or less
[https://justpaste.it/agq5c](https://justpaste.it/agq5c)
Question2: What day is today? Reply with 128 character or less
[https://justpaste.it/fjtew](https://justpaste.it/fjtew)
what day is today? reply with 128 character or less
[https://justpaste.it/cxvpj](https://justpaste.it/cxvpj)
What day is today? Reply with 128 character or less
[https://justpaste.it/edogo](https://justpaste.it/edogo)

They return no intents. Is this the behaviour that you are expecting?
Can you also tell me what wit version are you using? This would be the 'v' url parameter. If you don't specify this parameter, you are going to use the default wit version.

**Comment by maidaneze** [comment]
@anjaly Can you confirm if the issue is still happening?

**Comment by anjaly** [comment]
@maidaneze we are using npm node-wit: `"^5.0.0"`"[^5.0.0](https://npmjs.com/package/node-wit)"
