### ISSUE TITLE
Regexp matching for entities?

### ISSUE THREAD

**Issue by matthewmueller** [wit-ai/wit#274]
Wondering if it's possible to supply a regexp or some sort of matcher. Would that be where actions come into play?

**Comment by ar7hur** [comment]
It's not possible at the moment, but we are considering adding this feature.

What is your use case?

**Comment by jhernandezme** [comment]
Looking for this too, 

In my case the bot is going to check car plates

e.g. 
P-123ABC
C-456ZXY
M-346MNL

So the bot needs to have the ability to catch this entities to perform an action.

**Comment by l5t** [comment]
Thanks for sharing. In this case, you would have to do this in an action on your side. The `request` contains the text message send by the user: https://github.com/wit-ai/node-wit#request. Then branch on the context key that you action can set whether the user matches the regex or not

**Comment by matthewmueller** [comment]
Actually in my case I'd like to match on anything. I mentioned it in intercom, but:

```
bot: What would you like to name this task?
user: Email Users
bot: Okay I'll name this task "Email Users"
```

**Comment by l5t** [comment]
Can't you do it on your side? Don't create an entity for this just rely on the text that is part of the request in the action on your side

**Comment by guillegette** [comment]
Hi @l5t would it be ok if, following the plates example, before sending the request to Wit I replace the plate on the message with something like %plate% and then in Wit I create an entity that matches (keyword match?) %plate% so that way you can build the different ways you can enquiry about any plate? Makes sense?

Thanks!

**Comment by Hyperclaw79** [comment]
@l5t 
Use case: 
Matching against the format: "The book called *book name* was written by *author*" 
It's easy to match author as it is usually a single word or two. However  it is difficult to match the book name which is of variable length and could be anything. I'll need wit.ai's training model to extract the book name.

**Comment by blandinw** [comment]
@Hyperclaw79 This should be possible with `free-text`, or `keywords + free-text` entities (https://wit.ai/docs/recipes#which-entity-should-i-use).
How does it relate to this issue (regexp-based entities)?

**Comment by blandinw** [comment]
Also closing as wontfix since we've decided not to implement it internally because:
- it's easy to implement on the user's side
- it is a potential security vulnerability, would require proper sandboxing, etc.
