### ISSUE TITLE
Strange text displayed

### ISSUE THREAD

**Issue by anuraagdjain** [wit-ai/wit#275]
I'm getting some strange text in response from wit. The (logs) section in wit.ai shows the proper text. 
Check this image. On iPhone I get strange text, whereas on my iPod I get the exact text back from the wit.ai. Console prints the same thing which is displayed on the screen. 
I'm not using iOS-sdk. I'm recording and uploading voice in .wav format.![img_1225](https://cloud.githubusercontent.com/assets/4705103/16893110/193dfb8e-4b4b-11e6-9f1c-5462ff2ed075.PNG)

**Comment by JoabMendes** [comment]
Hi @anuraagdjain , I'm sorry I didn't come here to help with your question but to ask you something. Could you share your code? I am trying to do the same thing and I have no ideia how I could start and record-and-upload feature to use the speech api.

**Comment by patapizza** [comment]
Sorry for the latency here.
This seems like a client-side issue, closing.
