### ISSUE TITLE
Results returned from Message API is unstable and not correct after importing an existing app

### ISSUE THREAD

**Issue by aya-labiba** [wit-ai/wit#2751]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
We exported an app that was under an account that was deleted because it was not migrated to meta, after importing the app files into a new app we are facing issues with the training.

The confidence of the intents returned is not stable, it is different each time sometimes it has high confidence and it sometimes it has low confidence which is affecting the accuracy of our product.
Sample sentence: السادة خدمات المشتركين وصلني رسالة من مكتب محاماه لمراجعته ولا اعلم ما هو المطلوب ملى حيث الي لا اذكر لى معامله او ارتباط او مبالغ مترتبه علي

Is should return this intent: LawyerAR and it should be higher than 0.6, every time it is returned  in a different confidence 

This is happening with multiple sentences 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Send this sentence to the messages API: 
السادة خدمات المشتركين وصلني رسالة من مكتب محاماه لمراجعته ولا اعلم ما هو المطلوب ملى حيث الي لا اذكر لى معامله او ارتباط او مبالغ مترتبه علي

**What is the expected behavior?**

For the confidence to be returned stable as it was on the original app

we have a question, is there a way that we can restore the deleted account that has the original app?

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
Original App (Exported app): 280962410285788
New App (Imported apps):  836423232009613, 1067091141686019

**Comment by aya-labiba** [comment]
@ramh @blandinw @dwwoelfel @hactar 
Can you please help us with this, this is an urgent matter and it's affecting out product

**Comment by aya-labiba** [comment]
@ramh @blandinw @dwwoelfel @hactar your urgent support is needed please

**Comment by patapizza** [comment]
Hi @aya-labiba,

It looks like that particular sentence now works for your imported apps:

<img width="1718" alt="Screenshot 2024-10-29 at 2 02 59 PM" src="https://github.com/user-attachments/assets/4096cbae-65ad-483b-9775-e8287716ae14">

<img width="1714" alt="Screenshot 2024-10-29 at 2 04 44 PM" src="https://github.com/user-attachments/assets/abed9de6-46c5-403a-850c-3235d53d09fa">
