### ISSUE TITLE
Trained Intent Not Recognized for Relevant Utterances

### ISSUE THREAD

**Issue by agussuparman** [wit-ai/wit#2756]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
I would like to report a bug.

**What is the current behavior?**
I created an intent named "greetings" and added several utterances to this intent, such as:
- good morning
- good afternoon
- good night

After completing the training, I tested the intent using a cURL request to the API. However, the response did not return any intent. Instead, the intents field in the response always contains an empty array.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Create an intent named "greetings" in wit.ai.
2. Add the following utterances:
- good morning
- good afternoon
- good night
3. Train the model.
4. Send a request to the wit.ai API using a cURL command with one of the added utterances (e.g., "good morning"):
```
curl \
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN" \
  "https://api.wit.ai/message?v=20241021&q=good%20morning"
```
5. Observe the response; the intents field is always an empty array.
```
{
  "entities": {},
  "intents": [],
  "text": "good morning",
  "traits": {}
}
```

**What is the expected behavior?**
The expected behavior is that the response should contain the "greetings" intent when sending a valid utterance like "good morning". For example:

```
{
  "text": "good morning",
  "intents": [
    {
      "id": "intent_id_here",
      "name": "greetings",
      "confidence": 0.98
    }
  ],
  "entities": [],
  "traits": []
}
```

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID: 900808455317648

**Comment by CleanestMink126** [comment]
@agussuparman Thanks for the report. Could you try again? We've fixed an issue with the training pipeline and the issue should be resolved.

**Comment by agussuparman** [comment]
Thank you so much for your quick response and fix! I’ve tried it again, and everything is working perfectly now. I really appreciate your prompt support and effort in resolving the issue.

Have a great day!
