### ISSUE TITLE
[Urgent] Service Unavailable

### ISSUE THREAD

**Issue by PeihengCai** [wit-ai/wit#2767]
**PLEASE PLEASE!!!! It is really important to me. I am going to show demo 10 hours later!!!!**

**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
When I try to connect Meta Voice SDK understanding viewer in Unity, just got error "HTTP/1.1 503: Service Unavailable. Server Response: !DOCTYPE html". I found wit cannot be logged in for a while. Is it the server problem?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
I changed nothing in my Unity, so it should connect the server successfully. 

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
User Name: peihengcai
Email: caiph_0410@163.com

**Comment by CleanestMink126** [comment]
@PeihengCai Sorry, there's currently a service outage across several Meta products which unfotunately is affecting Wit as well. We expect it to be mostly recovered in the next couple hours, but can update you if our expectations change.

**Comment by anjaly** [comment]
We are also facing the same issue for multiple apps in wit.ai
@patapizza  Can you please look into this ASAP.

**Comment by halemrani1996** [comment]
i got this also on my apps 
 my apps ids is 1850539691729312,1920151674738030
 @patapizza Can you please look into this ASAP.

**Comment by davidthhuang** [comment]
same here!

**Comment by crazyrabbit0** [comment]
We fixed it by regenerating our API keys, as stated on #2768

**Comment by CleanestMink126** [comment]
Update:
We're rolling out deployments to our wit servers and started to see the sporadic 503s dissappearing. We expect them to resolve over the next hour.
