### ISSUE TITLE
wit.ai message api is not working correct(urgent)

### ISSUE THREAD

**Issue by halemrani1996** [wit-ai/wit#2769]
i have issue on api https://api.wit.ai/message?v=20210928&q=عروض
i got wrong intents for example i got this response
processedMsgResp: ProcessMessageRespWrapper [msgId=null, text=عروض, entities=[], intents=[UtteranceIntentWrapper [Id=7, name=Welcoming, confidence=1.0, intentGroupId=4]]]

but this statment عروض
for is correct intent Get_UmniahOffers 
please urgent support 
my apps ids is 1850539691729312,1920151674738030

**Comment by halemrani1996** [comment]
any update please?

**Comment by CleanestMink126** [comment]
See #2767
