### ISSUE TITLE
[URGENT] wit.ai NLP returning 503 service unavailable error

### ISSUE THREAD

**Issue by jyothisjose** [wit-ai/wit#2770]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
All the request to the below wit.ai apps are returning error

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
NLP should identify the intent on inputting a text.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID: 400365182541948
App ID: 736678881746027

**Comment by CryptAlchemy** [comment]
+1

**Comment by CleanestMink126** [comment]
Merge with #2767
