### ISSUE TITLE
Massive 503 error response with endpoint /message with multiple apps

### ISSUE THREAD

**Issue by asisteclick** [wit-ai/wit#2771]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
BUG

**What is the current behavior?**
Massive 503 error responde for multiple apps

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Execute the /message endpoint and you'll get a 503 error with the message "Sorry, something went wrong. We're working on it and we'll get it fixed as soon as we can.":

curl \
  -H "Authorization: Bearer XXXX" \
  "https://api.wit.ai/message?v=20241212&q=hello"

**What is the expected behavior?**
It should respond with the NLP intent classification.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
- 876919203603456
- 1132216884427731
- 1036448524721620
- 1132216884427731
- and many, many more

**Comment by sebastianarena** [comment]
+1 for us, same problem, not with all the apps, just some

**Comment by terezatodova** [comment]
+1, same problem here (using it as a part of Unity Voice SDK)

**Comment by alexjadame** [comment]
Same issue here... we need a fix asap.

**Comment by ansdresles** [comment]
+1 Same issue here, with some apps

**Comment by Haribou** [comment]
Same issue here today. I am POSTing to the /event endpoint and receive 503 consistently for app 1584835525763145.

**Comment by CryptAlchemy** [comment]
Same here.

**Comment by CleanestMink126** [comment]
Merge with #2767
