### ISSUE TITLE
500 error on validating in "understanding"

### ISSUE THREAD

**Issue by jholt1** [wit-ai/wit#278]
Getting a error message in the top right hand corner "Could not validate this expression"

In the console:

![screenshot 2016-07-22 10 03 47](https://cloud.githubusercontent.com/assets/7101754/17052036/a2f7e702-4ff3-11e6-818a-17864f4127bc.png)

**Comment by l5t** [comment]
I should be fixed. Can you confirm?

**Comment by jholt1** [comment]
Thanks, yes I can confirm it is fixed.

**Comment by zaal** [comment]
Same here. In the Inbox, when I validate the expression, the same expression pops back in, without the yellow notification.
in the console:
<img width="477" alt="screen shot 2016-10-20 at 11 19 14" src="https://cloud.githubusercontent.com/assets/71133/19549790/60eb04a6-96b7-11e6-9f93-cf22553b5caa.png">
can somebody please explain what's going on? Many thanks.

**Comment by atinder90** [comment]
I am also facing issues like this with.
Unable to validate and see Expressions Text.

I am willing to use it but not able to because of too many bugs in the UI.

**Comment by happyjedi** [comment]
The same problem that above
