### ISSUE TITLE
Training instability

### ISSUE THREAD

**Issue by nelson687se** [wit-ai/wit#279]
I have three stories in total, when I modify just a single thing in one of them, like adding a question mark to the text and click save, I get "1 story failing" and my changes aren't being saved, same if I want to create a new story and add just any text what has no conflict with other stories. 
After trying for a few times it ends up working, but it's quite difficult and time wasting to do this.
Is this something you are already aware of?
It also has been in yellow status (training) for hours

**Comment by jholt1** [comment]
Getting a similar experience over the last ~30 hours

**Comment by l5t** [comment]
Thanks for reporting. We are investigating and will report back

**Comment by l5t** [comment]
We just restarted the service that was slow.  Can you confirm it works?

**Comment by aldomarostica** [comment]
I've got the same issue right now. 3 stories without any apparent conflict, in one of them the first answer from the bot is signed as "conflicts with" so I can't save and it remain in conflict even if I change the answer or switch to a function.

**Comment by enricopenzo** [comment]
same here, it seems it's very slow to update the changes made through the UI

**Comment by milindaj** [comment]
Even I am facing the same issue as @aldomarostica. The first answer is showing is conflict when I try to create a branch in a simple workflow and I can't save the changes. Because of this not able to proceed with creating even a simple workflow from last few days. Please help!

**Comment by mariogintili** [comment]
Facing the same issues, my app is failing to understand fairly crystal clear stories

the input query `I want home insurance` yielded the following response

```json
{
	"confidence": 0.36787944117144233,
	"type": "action",
	"action": "insurance-request",
	"entities": {
		"intent": [
			{
				"confidence": 0.9779955939194599,
				"value": "insurance-request"
			}
		]
	}
}
```

`0.367` seems a little bit too low for the following setup 👀 

<img width="800" alt="screen shot 2016-08-08 at 16 43 02" src="https://cloud.githubusercontent.com/assets/3522106/17486034/3a003460-5d87-11e6-8d38-4cad354f617d.png">
