### ISSUE TITLE
Bulk add keywords

### ISSUE THREAD

**Issue by jholt1** [wit-ai/wit#280]
It would be good to be able to bulk add keywords. I have tried to export my app and then import it back to a new app with all the keywords added, but I get a 400 error when trying to add.

**Comment by jholt1** [comment]
Doing a `curl -XPUT` on the entity allows me to do a bulk add of keywords. However I am trying to upload over 3000 keywords and as of now only 981 gets added (not in order of the json - seemingly randomly picked?)

**Comment by dimitridewit** [comment]
I was trying to get this to work too. Same here, 400's. Tried to format the json exactly the same way.. still 400's. Did anyone have any luck with this ?

**Comment by jholt1** [comment]
I didn't. The only way I could get some of them to be added was through the curl, but I couldn't get all of them. Haven't tried since. https://wit.ai/docs/http/20160526#put--entities-:entity-id-link

If I get some time this weekend I will have another go

**Comment by mennafateen** [comment]
Did anybody find a solution for this?

**Comment by blandinw** [comment]
For batch updates, we recommend to use our HTTP API (https://wit.ai/docs/http/20160526#put--entities-:entity-id-link)

A simple Bash scripts using `curl` or Python using `requests` should do the trick :-)
