### ISSUE TITLE
Bookmark and jump disappeared

### ISSUE THREAD

**Issue by misysdclabs** [wit-ai/wit#281]
I left alone my wit.ai app for a couple of days... and what I found, in two of my stories the bookmarks and jumps are disappeared:

![screen shot 2016-07-27 at 13 35 25](https://cloud.githubusercontent.com/assets/14309287/17175402/a4196396-5407-11e6-97d5-a4c99f940265.png)

Does anyone have something similar experience? What happened?

**Comment by enricopenzo** [comment]
it happened to me as well multiple times

**Comment by zetos** [comment]
Same issue here..

**Comment by kanedaki** [comment]
Same here

**Comment by joinworldtv** [comment]
Same here... And when I restore the app from Zip, the bookmarks are not restored (but they are in Zip file)

**Comment by JonghunYu** [comment]
Same thing happen to me. I added some entities from the actions tab.
I just guess it causes the problem.

**Comment by patapizza** [comment]
Thanks for reporting guys. We'll look into it.

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018.https://wit.ai/blog/2017/07/27/sunsetting-stories
