### ISSUE TITLE
wit/amount_of_money misses amounts and I fail to train it

### ISSUE THREAD

**Issue by vitalybe** [wit-ai/wit#282]
For example, the following strings were not identified:
- 10 ILS
- 10 NIS
- 10 pesos
- 10 rubels

I've tried training wit by re-adding wit/amount_of_money, selecting the text and validating. Still, whenever I put these values, it would ignore them.

**Comment by kashmadze** [comment]
Same problem for me , how can we add knowledge to this entity ?

**Comment by thiagobustamante** [comment]
Same problem.

**Comment by magnusburton** [comment]
https://duckling.wit.ai/#contributing

They need all help they can get!

**Comment by patapizza** [comment]
As @magnusburton pointed out, Duckling is supporting wit/amount_of_money and extending the support to these inputs should be made in https://github.com/wit-ai/duckling.

**Comment by thiagobustamante** [comment]
Thank you very much! I will try it.

Em 14 de mar de 2017 5:13 PM, "Julien" <notifications@github.com> escreveu:
