### ISSUE TITLE
UX improvement for working with action/response hints

### ISSUE THREAD

**Issue by hfinck** [wit-ai/wit#283]
I recently thought there is room for improvement when editing response and actions hints.

Consider the following scenario:

Your are working within the stories tab editing actions and responses. At the same time you might want to refine the response and action hints to really make sure these are fired given the correct context.

For this I have to switch to the „Actions“ tab, scroll down and find the action or response for which I want to edit the hints. If you already have a bunch of actions and responses this can be quite cumbersome.
Even more so if they look quite similar at first glance.

Wouldn’t it be great to be able to directly jump to the exact action or response from within a story? This would save quite some time.

Some thoughts on how this might be optimised:
- Give action and response items in the „Stories“ view a context option to jump to this exact item in the „Actions“ tab
- Option to edit action/response hints directly within a story
- Option to group actions and responses by story within the „Actions“ tab. This makes it easier to find the desired item.

**Comment by hfinck** [comment]
@l5t Here is the issue you asked for. Let me know if you need any further information.

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
