### ISSUE TITLE
Wit recognizes unwanted words as location despite hours of training

### ISSUE THREAD

**Issue by guribe94** [wit-ai/wit#285]
Is there any way to stop wit from selecting certain keywords as locations? I can't seem to stop wit from recognizing words like "security" and "gate" as locations despite training wit on hundreds of different examples and even when using the story exactly as it is defined in the story.

**Comment by jvdalen** [comment]
Not sure if this is helpful. I had a problem similar to yours, and my solution was stupid but it worked.

I had an intent request BMI, where I wanted it to recognize sentences that contained the word "BMI",  but wit kept recognizing the word BMI as a "contact". Similar that your word "security" is recognized as a "location". 

When training wit, I had trained a few examples with a "span" of exactly the size of the word "BMI", while the search strategy was "trait". When I retrained these examples with full span (whole sentence), and not just the one word, it stopped classifying it as a "contact". Not sure if that was coincidence, but it worked :P. Didnt try replicating it. 

Hope that helps. If you need any clarification, -> jeroen <thingy> boundlss . youknowhat

**Comment by l5t** [comment]
Closing. Some built-in entities like wit/contact or wit/location can be a bit too greedy because they are trained across thousands of Wit apps. We did improve them so I would suggest to test them again
