### ISSUE TITLE
Wit Hub

### ISSUE THREAD

**Issue by dangerimp** [wit-ai/wit#289]
I see that there's now import/export available.  Is there something like Wit Hub coming (modeled similarly to https://hub.docker.com/) where people can share their bots in a community?

Thanks.

**Comment by mickeyckm** [comment]
Hi @dangerimp, it is already on the roadmap. Please refer to this: https://github.com/wit-ai/wit/issues/266

Cheers.

**Comment by patapizza** [comment]
Closing in favor of https://github.com/wit-ai/wit/issues/266.
