### ISSUE TITLE
Possible to keep entities across branches in the same story?

### ISSUE THREAD

**Issue by mickeyckm** [wit-ai/wit#290]
Is it possible to keep entities across branches in the same story?
## 

User: 
- Are you open?

Entities:
- intent: is_open
- open_close: open
- wit/datetime
## 

checkIfOpen(context) 
- missingDatetime
## 

Bot:
- Which day?
## 

User:
- Today

Entities:
- intent: is_open
- wit/datetime
## 

Loop to checkIfOpen()
## 

The second call for checkIfOpen(), the entity 'open_close' is missing. I need it for scenario where someone ask, "Are you close?". Then when user reply 'Today', the bot can reply according to the value in "open_close".

So is it possible to have open_close entity be pass during the story? At the moment, the only possibility I can think of is to create another story "Are you close?" with a separate intent 'isClose'.

I hope I explain clearly here. Thanks in advance for looking into this.

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
