### ISSUE TITLE
HTTP logs for API requests and responses

### ISSUE THREAD

**Issue by tefrati** [wit-ai/wit#291]
Hi,

It would be very helpful to have add to the logs tab a trace of all HTTP requests/responses between our clients and wit.ai. Specifically, calls to /converse. It will help improve our debug experience.
Thanks

**Comment by scruffjinks** [comment]
Also useful to see similar from the test bot. (Could always have a switch to route the test bot through the logs which with above would be a good solution)

**Comment by tefrati** [comment]
Any response?

**Comment by patapizza** [comment]
We've [sunset Bot Engine](https://medium.com/wit-ai/launching-built-in-nlp-for-messenger-and-sunsetting-bot-engine-beta-46e9038869a5) in July 2017.
