### ISSUE TITLE
Confidence threshold

### ISSUE THREAD

**Issue by tefrati** [wit-ai/wit#292]
Sometimes the SDK is calling one of the actions even when the threshold is very low.
I suggest adding a threshold under which, an action won't be called. Or, add a middleware to the SDK to let the developer decide if he wishes to execute the action given a low confidence score.

**Comment by tefrati** [comment]
For whom it may concern, I have changed wit.js to support handling of intent's low confidence value. Here're code snippets:

- In function Wit

`const {
    accessToken, apiVersion, actions, headers, logger, witURL, lowConfidenceThreshold
  } = this.config = Object.freeze(validate(opts));
`

- in continueRunActions, under the 'action' handler:

```
else if (json.type === 'action') {
        let action = json.action;
        // json.confidence is confidence of next step which is NOT what we need
        // We need to know how confident Wit is with the intent identification
        const confidence = json.entities && json.entities.intent &&
                    Array.isArray(json.entities.intent) &&
                    json.entities.intent.length > 0 &&
                    json.entities.intent[0].confidence;

        if ( confidence && confidence<lowConfidenceThreshold)
          action = 'lowConfidence'
```

Works much better now.

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
