### ISSUE TITLE
"You cannot archive expressions"

### ISSUE THREAD

**Issue by tefrati** [wit-ai/wit#293]
In inbox'/expressions', when pressing on 'x' to archive an expression, I'm getting an error message "You cannot archive expressions."

**Comment by tefrati** [comment]
any response?

**Comment by l5t** [comment]
Just tested and it worked for me. Can you share your wit app URL or send it to help@wit.ai?

**Comment by tefrati** [comment]
https://wit.ai/zefrati/who-are-you-bot-prod-3.0/inbox/semantic

**Comment by stopachka** [comment]
(most likely no longer relevant -- feel free to re-open with a template if still facing issues)
