### ISSUE TITLE
Cannot save new stories

### ISSUE THREAD

**Issue by scruffjinks** [wit-ai/wit#295]
I cannot save anything with wit.ai after adding a new story, I just get a 'red' error failed to save status

In the console window I can see

https://api.wit.ai/sync 500 (Internal Server Error)

I have sent messenger information to the help desk but get no response.

**Comment by EdgarSun** [comment]
I have the same problem, it looks like the bot engine server is messed up. the response from the server is super slow and was not able to save a story.

**Comment by hoodsy** [comment]
Getting the same thing here.

**Comment by gilles-bogaert** [comment]
Same here too :/
What did you decide to do?

**Comment by hoodsy** [comment]
Sometimes, I would open the dashboard in a new tab and the stories turned out to be saved correctly.

Other times I refreshed the page and lost my work.

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
