### ISSUE TITLE
Can't delete actions/responses

### ISSUE THREAD

**Issue by thegregthomp** [wit-ai/wit#297]
Like the title says, once you enter one, even if it's a typo, it's stuck there. I then notice this causes conflicts creating new responses. 

![image](https://cloud.githubusercontent.com/assets/1554124/17747352/71706cba-6482-11e6-93a0-d14d018c1d2c.png)

**Comment by thegregthomp** [comment]
I've also noticed that the renamed actions create a conflict. Basically, if you create an action and try and rename it, wit still tries to reference the old function

**Comment by jhoelzl** [comment]
I got the same problems, however, sometimes it helped to refresh the page (F5) and then i was able to remove the incorrect action. Then i could reference the new action in my story without conflict.

**Comment by thegregthomp** [comment]
@jhoelzl how exactly do you remove it? It doesn't seem to even have an option to remove it.

**Comment by jhoelzl** [comment]
If the action is not used by any story, there is a link below the action to remove it.
So you can remove the conflicting story and then you also should be able to remove the action.

**Comment by thegregthomp** [comment]
It appears this has finally been resolved.
