### ISSUE TITLE
API converse doesn't respond with bookmarked action

### ISSUE THREAD

**Issue by scruffjinks** [wit-ai/wit#301]
I feel I must be doing something wrong in the API. I am following the weather example with a missing location. The story works fine.

However when I use the API over http using postman for testing purposes I cannot get it to raise the action after sending back the location from the user, It always returns a stop message. I think I must be not sending the correct context across or similar.

My understanding is as follows:
1. send across message 'I want to know the weather'
2. raises action from wit: 'Weather' (works correctly)
3. Respond with 'missingLocation'
4. wit replies with msg 'Which location do you want to know the weather for?' (works correctly)
5. I respond with 'Paris' in the message (no context all with same session)
6. wit replies with finding the entity 'Paris' but a 'stop' and no action. Here I would expect to get an action request again with everything I need to know this time. This is what happens when I use the story and test using the bot mesenger.

Any ideas from anyone? I expect I need to respond with something more than just 'Paris'  in the message 

Thanks.

**Comment by hfinck** [comment]
Do you have included a jump to the bookmark at the end of this story path?

**Comment by scruffjinks** [comment]
yes I have the bookmark, as I say it works fine using the test bot on the wit GUI, but not using something like Postman to send my requests.
 It is when I send back the http request for  e.g. 'Paris'. I am not sure what should be in the context (if anything). So I send Paris in the 'message' with no context. I would expect to jump to my bookmark as per the story and get the action raised again.

**Comment by TareqAteik** [comment]
I have the same problem, did you manage to solve it?

**Comment by toxuin** [comment]
This thing has been going on since August. No answer I could find here, nor on the docs or on stackexchange. What are we doing wrong?..
Guys from wit: with all due respect for making such an awesome project a reality, you suck at managing the community of your users. Manuals are only partially up to date, API still dates back to MAY (that's 6 months!) and features that are beta and may break are the only option to use.
This kinda makes wit.ai not ready for use in production, don't you think so?

**Comment by TareqAteik** [comment]
I've posted the same question on stackoverflow, but didnt get an answer.
Not sure if we have a big community for Restful apis anyway...

http://stackoverflow.com/questions/40447074/wit-ai-api-converse-doesnt-respond-with-bookmarked-action

For me, I've already moved to Microsoft Bot framework (nice documentation, and clear samples)

**Comment by abhishek-raj** [comment]
You are most probably sending the wrong context, can you show me the postman http requests you send?
Export it as a curl request and paste it here

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
