### ISSUE TITLE
Cannot create bookmark with previously used name after recreating story

### ISSUE THREAD

**Issue by hfinck** [wit-ai/wit#302]
This problem happens while working with the story mode. It is not possible to create a new bookmark with a previously used name, even if the story or bookmark in question has already been deleted.

Steps to reproduce:
1. Create a story with a function and bookmark
2. Save that story
3. Delete the previously created story
4. Create a new story with the same setup as before
5. Name the bookmark the same as in the first story

--> "xx is already a known bookmark. Please create a new one"

**Comment by jhoelzl** [comment]
Related: https://github.com/wit-ai/wit/issues/257
