### ISSUE TITLE
Data export doesn't export search strategies entities

### ISSUE THREAD

**Issue by mahieddine** [wit-ai/wit#305]
Hi,
It seems like when we make a data export of an app, search strategies get lost and therefore when you import this data in another app, you notice that the search strategy for each entity is not the same as in the original app

**To reproduce this issue** : 
Create an app or pickup an existing app with different entities having different search strategies
Export Data
Import them in a new app

The new app will have different search strategies

Thanks 

Kindly,
chermah

**Comment by l5t** [comment]
Closing as we fixed this.
