### ISSUE TITLE
Currency code AED and AUD not working in wit/amount_of_money entity

### ISSUE THREAD

**Issue by santhanakumar4199** [wit-ai/wit#306]
Currency code AED and AUD and all not working properly in wit/amount_of_money entity

**Comment by l5t** [comment]
Thanks for reporting. This entity is using our open source parser here: duckling.wit.ai. Feel free to push a PR to add these currency codes

**Comment by l5t** [comment]
Fixed. Closing.
![image](https://user-images.githubusercontent.com/6992759/50257794-aabb3100-03b1-11e9-9877-fc061e3dcbd4.png)
