### ISSUE TITLE
Session is dead and got only error respond since text is cannot get any entity

### ISSUE THREAD

**Issue by golfapipol** [wit-ai/wit#307]
I have a lot of error when Wit got some text that don't have any entity, It will make the session that type that text got only error. and never came back
![13988161_10204800017879133_539305981897631518_o](https://cloud.githubusercontent.com/assets/8346755/18001429/2812c004-6bad-11e6-9c2f-736211f02575.jpg)

**Comment by l5t** [comment]
Closing as we deprecated Stories https://medium.com/wit-ai/launching-built-in-nlp-for-messenger-and-sunsetting-bot-engine-beta-46e9038869a5
