### ISSUE TITLE
Getting 3 action responses with one message to bot

### ISSUE THREAD

**Issue by mikob** [wit-ai/wit#308]
![screenshot from 2016-08-27 16-49-47](https://cloud.githubusercontent.com/assets/492864/18026060/4fa3f326-6c76-11e6-9329-51d28d59c455.png)

Also none of these are the right action. I've trained this exact phrase a few times to return the postToClass action.

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
