### ISSUE TITLE
A story on wit.ai has a different behaviour than messenger

### ISSUE THREAD

**Issue by aldomarostica** [wit-ai/wit#310]
Hi,
I've built a messenger app based on wit.ai hosted on heroku. When I test it on wit console and via curl i get the right answers instead when i try it directly on facebook, some question remain unanswered. Isn't strange? Some suggestion? Ideas?

**Comment by hactar** [comment]
Tell the wit team the name of the app, what the "some question" are exactly, and they might actually be able to help...

**Comment by aldomarostica** [comment]
I wrote (2-3 times) on wit.ai one month ago, unanswered even there! I've tried again today, will see

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
