### ISSUE TITLE
Can't login with FB account (CORS)

### ISSUE THREAD

**Issue by rbeltraof** [wit-ai/wit#313]
Hey folks, found similar ticket opened but not referred to FB account therefore created this new one. I'm currently unable to login with my FB account getting the error: 
XMLHttpRequest cannot load https://api.wit.ai/me/facebook_signin. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://wit.ai' is therefore not allowed access. The response had HTTP status code 502.

**Comment by l5t** [comment]
Thanks for reporting. We are working on a fix

**Comment by stopachka** [comment]
(fixed)
