### ISSUE TITLE
Entity value lookup based on similar string match

### ISSUE THREAD

**Issue by greenroutes** [wit-ai/wit#314]
Hi Guys,
     I have created an entity called frognames and populated that with common and scientific names of some of the frogs. I uploaded these bulk using HTTP API. I have kept the free-text and keywords ON for this entity. 

In the Understanding Tab, if I make a spelling mistake, it won't find the nearest match. Is there a way to do this? I can use a  Levenshtein distance algorithm on the code side (nodejs), but as the engine is not able to resolve my search into the entity called frognames, I have no way of doing the above.

I also referred to this section in the recipe.
https://wit.ai/docs/recipes#extract-an-entity-that-generally-takes-a-value-in-a-predefined-list-open-enum-but-you-are-open-to-new-values

But, even the above example is not working for me. 

Please give me some ideas / suggestions as to what is the best way I can resolve this issue.

Thanks

**Comment by l5t** [comment]
Closing. Sorry for the lack of answer. Please reopen if you still experience the issue
