### ISSUE TITLE
The X button hides texts when writing RTL

### ISSUE THREAD

**Issue by erlichmen** [wit-ai/wit#315]
In "Understanding" Tab when wiring in right to left languages the text is partly hidden by the X (clear) button.

<img width="643" alt="screen shot 2016-09-09 at 5 05 15 pm" src="https://cloud.githubusercontent.com/assets/691823/18389751/fc08f18c-76af-11e6-9b30-ec188d58ae55.png">

**Comment by l5t** [comment]
Closing, as this was fixed a few years ago ;-)
![image](https://user-images.githubusercontent.com/6992759/50187597-635e7300-02d3-11e9-971c-33a64a8092e4.png)
