### ISSUE TITLE
Export/Import not working correctly in some cases

### ISSUE THREAD

**Issue by eh3rrera** [wit-ai/wit#316]
I have the following story with some branches:

![story](https://cloud.githubusercontent.com/assets/11665759/18415397/2d3d1646-77b6-11e6-8b18-9c717e650710.png)

When I import the app as a ZIP file into a new application, the first issue is that this new application shows up as private, even tough I choose to create it as public.

Second, sometimes the search strategies are not exported correctly (issue #305).

Third, in almost all cases, a Server Access Token is not created, I have to either refresh the page or regenerate it.

Fourth, sometimes, it seems that the new app is not created correctly because the `getTrivia` action gives the error `There is something wrong with this action`. The funny thing is that if I refresh the page or change between sections, sometimes the story turn to green. However, if I refresh the page once again, the error comes back (possibly related to issue #279?).

If this happens (the action error), on the client, node-wit gives the error `No 'null' action found`, but I can say that I get a correct response one or two times out of ten attempts (this only happens in the _new_ app, the original works correctly 99% of the time).

**Comment by smalltalk-josh** [comment]
I have been trying to create a new App using Import, but it does not finish. Now long is it taking others to create new Apps with import?

**Comment by eh3rrera** [comment]
It happened to me once also @smalltalk-josh, the process never finished. Just close the window and try until it gets created.

**Comment by kaerusdev** [comment]
+1

**Comment by froasiooneloop** [comment]
+1
I'm having the same problem. I can't get my stories imported correctly.

**Comment by patapizza** [comment]
Closing since we've [sunset Stories](https://medium.com/wit-ai/launching-built-in-nlp-for-messenger-and-sunsetting-bot-engine-beta-46e9038869a5).
