### ISSUE TITLE
HTTP api converse using php curl not working properly?

### ISSUE THREAD

**Issue by abhishektn** [wit-ai/wit#320]
I'm trying to use api.wit.AI/converse with my chat application and I'm not able to send the context value (ex: forecast value) me, me I'm not able to send action results to boot using PHP curl. 
and kindly update documentation with some working code examples so that for starters like me can easily use wit appears 

Thank you

**Comment by kalpeshmahida** [comment]
Have a look at https://github.com/tgallice/wit-php/ you can use this library to communicate with wit. The author has also written some examples.

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
