### ISSUE TITLE
Inbox stays empty

### ISSUE THREAD

**Issue by dimitridewit** [wit-ai/wit#322]
My inbox is staying empty while I'm using the http API a lot the last couple of days!
Botname: 4-oct-prod-flammy
Account: MHGGH

**Comment by magnusburton** [comment]
Sometimes when I post to Wit.ai a few of my sentences don't end up in the inbox. I think it's because of the certainty level. If wit.ai is almost 100% certain that they understood the sentence it might not end up in the inbox I think.

**Comment by l5t** [comment]
Yes, we will only show in the Inbox expressions that are not yet validated. You can go in the Logs tab to see all the request

**Comment by dimitridewit** [comment]
Ok, I see! thank you. I have checked my Logs, but they are empty too, although my bot has seen some heavy use. I found out my authorization headers when making http calls contained an older version. Im updating that as we speak... maybe that could be it..?

**Comment by dimitridewit** [comment]
My apologies for this late of a response. But my logs are also empty?

**Comment by dimitridewit** [comment]
I created a new app with an export, that seemed to have fixed to problem

**Comment by samuelwight** [comment]
Having the same problem. My inbox remains empty even if I send sentences that my app has never seen before. I've checked the logs, but all I see is the app context and then the bot's response. Pretty sad, I was looking forward to using this for my project, but now that I can't see what my users are saying I'm going to have to migrate my app to a new service. :(

**Comment by blandinw** [comment]
@samuelwight :(

If you send me your app id, we can have a look. The Inbox and Logs are supposed to show what your users say, unless you got throttled.

**Comment by blandinw** [comment]
The inbox is working fine. There is a bug in the logs, which we're working on, high-pri.
Tracked here #470.
Closing this.
