### ISSUE TITLE
story failing

### ISSUE THREAD

**Issue by zkkyaw** [wit-ai/wit#323]
In wit story panel, a red dot is show to alert that "your app may fail to handle...". But I could not figure out what parts is failing. Is there any way to know which parts is failing?

**Comment by l5t** [comment]
Can you share your wit app URL and the name of the story that fails

**Comment by zkkyaw** [comment]
https://wit.ai/zkkyaw/taxi/stories/d7c49ddc-cbbd-4823-a813-8c01ffe58691 (Hire taxi)

**Comment by l5t** [comment]
You need to have a `bot executes` or `bot sends` at the end of all your stories. For example in the Help Story 
![image](https://cloud.githubusercontent.com/assets/6992759/19217832/709608fe-8d9a-11e6-9e8e-79d6b26cd199.png)

The other issue is that your app seems to need more training
![image](https://cloud.githubusercontent.com/assets/6992759/19217846/0dbf845c-8d9b-11e6-9c9f-ab0da7cbe127.png)
`i want to hire a taxi from palo alto` don't provide the intent you have in your story

**Comment by zkkyaw** [comment]
You are right. Missing intent is causing to fail. It is fixed now. Thanks.

On Sun, Oct 9, 2016 at 12:06 PM, Laurent Landowski <notifications@github.com
