### ISSUE TITLE
Scrollbars show up when not needed.

### ISSUE THREAD

**Issue by magnusburton** [wit-ai/wit#324]
If you go to the logs section of Wit.ai using Chrome on Windows 10 the scrollbars will show up for the right sidebar's context and bot response section. See picture below.

![Scrollbars](https://cloud.githubusercontent.com/assets/3188613/19215199/8740729a-8d97-11e6-963c-760e0553ccc6.png)

**PS.** I think they also show up in the stories if you have a bunch of predicates. I looked at it in inspector on Chrome and saw the `overflow-x: scroll;` for the `.branches-list` part of Stories. I tested it out and changing it to `auto` fixes it.

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
