### ISSUE TITLE
Following quick start fail to save

### ISSUE THREAD

**Issue by choonggg** [wit-ai/wit#327]
I am just following the quick start guide creating a weather story here - https://wit.ai/docs/quickstart

Can never get pass step 8 and story fails to save even after recreating a new app.

Additional note: Kept getting an error about bot misunderstanding the sentence.

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018.https://wit.ai/blog/2017/07/27/sunsetting-stories
