### ISSUE TITLE
How can I reply to quickreplies message ?

### ISSUE THREAD

**Issue by bagnos** [wit-ai/wit#328]
hi,

I'm writing a bot using http api.
I'm using the stories approach, this is my initial message:

https://api.wit.ai/converse?v=20160526&session_id=777&q=ho%20un%20problema%20con%20la%20stampante
{
  "confidence": 1,
  "type": "msg",
  "msg": "La Stampante ha alimentazione?",
  "quickreplies": [
    "Si",
    "No"
  ],
  "entities": {
    "intent": [
      {
        "confidence": 0.9946968678716906,
        "value": "AssistenzaStampante"
      }
    ]
  }
}

Can you telI me how I have to compose the json answer message? I need to tell "SI" for example.

**Comment by l5t** [comment]
You can look at WittyFiddle here: https://github.com/wit-ai/witty-fiddle or here for an example:https://wit.ai/docs/recipes#add-quick-replies-to-my-bot
