### ISSUE TITLE
Validation fails as well as saving and adding new entities (& more)

### ISSUE THREAD

**Issue by magnusburton** [wit-ai/wit#329]
Hello!

During the last couple of hours Wit.ai has been so so so problematic that it's been almost impossible to try to train my bot. I haven't been able to validate almost anything because your website has been throwing errors left and right. This is not the first time the website acts up. Some times the website runs so fast and flawless and it's a blessing to use it and other times (like now) it's a nightmare. Are you guys pushing updates to the server or something like that without testing first? Looks in the inspector that the requests to _https://api.wit.ai/sync_ fails big time

Looking forward to your response and I hope I didn't come off as offensive or insulting in some way. I just love Wit.ai so I want to see it improve.

Thanks,

**Comment by aleSuglia** [comment]
I'm experiencing strange behaviours too. I hope that they will fix as soon as possible.

Thank you for your great work!

**Comment by stopachka** [comment]
Hey everyone! Apologies, we indeed had a few issues recently. The fix for validate is coming in the next 30 minutes. We will be continuing to make increase robustness on the server side

**Comment by magnusburton** [comment]
Thank you so much!

**Comment by aleSuglia** [comment]
Sorry for writing after that issue has been closed by the op. 

At the moment I'm experiencing problems when I annotate user utterances with the built-in entity "wit/contact" or "wit/age_of_person".  For example, if I annotate the utterance: "My name is Alessandro" where "Alessandro" is a "wit/contact" entity and then I annotate "I'm 23 years old" where "23" is "wit/age_of_person", the system continues to incorrectly annotate names and ages. This happens also after annotating some bunch of examples in the "Understanding" section.

Any suggestions about this kind of problem? 

Thank you in advance for your answer.
