### ISSUE TITLE
500 error on Save Story action and validating in "understanding"

### ISSUE THREAD

**Issue by happyjedi** [wit-ai/wit#331]
I'm getting an error message when I'm trying to Save Story. And also I have problem with validating of expression ( in the top right hand corner "Could not validate this expression"), like it was here  - https://github.com/wit-ai/wit/issues/278

In the console:
![error](https://cloud.githubusercontent.com/assets/6420175/19798701/6134004e-9cfb-11e6-97de-bafad10c8771.png)

**Comment by gitbnw** [comment]
+1

**Comment by ernestohegi** [comment]
Still not working for me, the story fails to be saved most of the time with error message: https://api.wit.ai/sync Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by ernestohegi** [comment]
It seems to be fixed now!

Thanks guys.
