### ISSUE TITLE
Incorrect response using converse API

### ISSUE THREAD

**Issue by swapdeepqa** [wit-ai/wit#332]
Hello,

I am experiencing a different behaviour between my bot in the Wit.ai chat and API request /converse using cURL. At the moment, my bot swapdeepqa/test should act like this:

```
user> Hello
bot> Hi! What's your name?
user> My name is Alessandro
bot> Alessandro, how old are you?
...
```

The bot acts correctly in the Wit.ai chat, but the response generated by the API doesn't contain the name of the user as expected. In particular, these are the requests and the responses of the bot:

```
➜  ~ curl -XPOST 'https://api.wit.ai/converse?v=20160526&session_id=test5&q=Hello' -H "Content-Type: application/json" -H "Accept: application/json" -H 'Authorization: Bearer $TOKEN'
{
  "confidence" : 1,
  "type" : "msg",
  "msg" : "Hi! What's your name?",
  "entities" : {
    "intent" : [ {
      "confidence" : 0.9690792126222261,
      "value" : "chitchat"
    } ]
  }
}%
➜  ~ curl -XPOST 'https://api.wit.ai/converse?v=20160526&session_id=test5' -d {} -H "Content-Type: application/json" -H "Accept: application/json" -H 'Authorization: Bearer $TOKEN'
{
  "confidence" : 1,
  "type" : "stop"
}%
➜  ~ curl -XPOST 'https://api.wit.ai/converse?v=20160526&session_id=test5&q=My%20name%20is%20Alessandro' -H "Content-Type: application/json" -H "Accept: application/json" -H 'Authorization: Bearer $TOKEN' 
{
  "confidence" : 1,
  "type" : "msg",
  "msg" : ", how old are you?",
  "entities" : {
    "user" : [ {
      "confidence" : 0.9794614875606298,
      "type" : "value",
      "value" : "Alessandro"
    } ],
    "intent" : [ {
      "confidence" : 0.9983682741347581,
      "value" : "chitchat"
    } ]
  }
}%
```

Is there something wrong with my requests or is it a bug?
Thank you.

**Comment by nielsenaa** [comment]
Hi swapdeepqa,

You omit to **post** the intent found (chichat)  back to the bot, in your second curl call
If you don't, you are saying to your bot that you do not confirm that intent. Go check back the online api doc

Hope this helped;

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
