### ISSUE TITLE
Docs: add verbose=true to HTTP docs 

### ISSUE THREAD

**Issue by aleSuglia** [wit-ai/wit#333]
Hi there,

I'm having some problems with role annotations using your REST API. I go in the "Understanding" section and I annotate an utterance with a specific entity(e.g., "genre"). I assign to it a role (e.g., genre:positive) and I validate it. I check the API return structure generated by the "Preview API output" 
and I got an incorrect response. Here there is the response structure that I get for the utterance "I like thriller movies" both using the preview mode and the _pywit_ library :

```
[
  {
    "_text": "I like thriller movies",
    "confidence": null,
    "intent": "default_intent",
    "entities": {
      "positive": [
        {
          "confidence": 0.922704169311831,
          "type": "value",
          "value": "thriller "
        }
      ],
      "intent": [
        {
          "confidence": 0.9979329170617052,
          "value": "recommendation"
        }
      ]
    }
  }
]
```

I tried to use the Chrome inspection utility in order to recognize what kind of request is done by the frontend to understand if there is something wrong with the official _pywit_ package. What I can see is that the frontend makes its requests to another address and obtains completely different responses. This is what I get:

```
{
  "msg_id" : "c8c9e9c6-208d-4b0c-b5ab-a2f11cbd5725",
  "_text" : "I like thriller movies",
  "outcomes" : [ {
    "_text" : "I like thriller movies",
    "confidence" : null,
    "intent" : "default_intent",
    "entities" : {
      "positive" : [ {
        "_body" : "thriller",
        "confidence" : 0.922704169311831,
        "_start" : 7,
        "_end" : 15,
        "_role" : "positive",
        "_entity" : "genre",
        "type" : "value",
        "value" : "thriller "
      } ],
      "intent" : [ {
        "confidence" : 0.9979329170617052,
        "_entity" : "intent",
        "value" : "recommendation"
      } ]
    }
  } ],
  "WARNING" : "DEPRECATED"
}
```

Maybe this problem can be related with the issue: #326
Is there something that you are changing in the API? What can we do to fix it? I really need to use Wit.ai for my project and I hope that you will fix as soon as possible.

Cheers,
Alessandro

**Comment by nocon** [comment]
I have the same issue 8 months later. Only role name is returned, without any mention of base entity. Workaround would be to incorporate entity names into role names ("genre:genre.positive"), but this really does require a proper fix.

**Comment by blandinw** [comment]
Try adding `?verbose=true` to your query params. It should return the `_entity` key inside each entity. I'm keeping this open to add this to the HTTP docs.

**Comment by l5t** [comment]
Done. https://wit.ai/docs/http/20170307#get__message_link
