### ISSUE TITLE
Story throws error 'can't end stories with user message' even when actions exist below

### ISSUE THREAD

**Issue by magnusburton** [wit-ai/wit#334]
I don't know if the title do justice for the problem but basically my story throws an error because it thinks that my story ends with an user message which it doesn't. See below;

![Screenshot](https://cloud.githubusercontent.com/assets/3188613/19844192/4c70afaa-9f2a-11e6-83a0-6bb195dc2eed.png)

**Comment by gitbnw** [comment]
I've gotten this error when all my quick reply branches weren't ending with a bot reply i.e. the problem may be further down stream.

**Comment by magnusburton** [comment]
Thank you @gitbnw totally didn't see that one! Closing
