### ISSUE TITLE
What is the best way to declare a default story ?

### ISSUE THREAD

**Issue by Bamsoo** [wit-ai/wit#335]
Hi there,

As suggested in this [SO post](http://stackoverflow.com/questions/38334663/make-chatbot-wit-ai-reply-that-it-doesnt-have-a-proper-answer)  I try to define a default intent to handle cases where my bot is simply not relevant. Is it a good practice to declare a story with no associated intent ?

![screen shot 2016-11-06 at 18 21 05](https://cloud.githubusercontent.com/assets/12754385/20039936/d5b5059a-a44d-11e6-8c76-a42855d357d7.png)

I have seen other solution based on analysing the confidence scoring, which one is best ?
In my tests, the story-with-no-associated-intent solution seems to work like a charm. 

When a sentence which I want to be handled by this default story is entered, in the app inbox, I remove all traits and keyword detected and then validate : is that a good way of feeding the learning process in that case.

Thanks for any insight !

PS : Very enthusiastic about your plateform, we wish nevertheless to see it in action in something else than a garage door opener or a weather forecast service ! So, Where could we find a wit.ai powered bot in a real life context ?

**Comment by leizard** [comment]
+1. I wonder the same thing. Do you have any idea about this yet ?

**Comment by davidheijl** [comment]
I too would like to get some feedback on this.

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018.https://wit.ai/blog/2017/07/27/sunsetting-stories
