### ISSUE TITLE
A missing feature - Set a variable in the context

### ISSUE THREAD

**Issue by wallali** [wit-ai/wit#336]
I have been trying out the new Wit.ai conversation workflow and enjoyed some of its features. However one feature that is missing still and I would like the dev team to consider adding is the ability to add/set a variable in the input of an action or in the context (either way would be fine). 

Currently the only things you can pass into an action is the context and any detected entities and intents. Entities require the user to have said specific words to have been detected. However there are cases where during a conversation the programmer designing the flow would like to insert a value into the context. The value could influence the behaviour of an action. This is very hard to do at the moment with wit. What you have to instead do is write separate actions, because the only thing you can manually specify is the _name_ of the action to execute.

**Comment by nemphys** [comment]
+1

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018.https://wit.ai/blog/2017/07/27/sunsetting-stories
