### ISSUE TITLE
Status stuck as dirty for days!

### ISSUE THREAD

**Issue by giorgiomarzianidepaolis-was** [wit-ai/wit#337]
We are experiencing training status is often stuck as dirty for more than 2 days. Is it possibile to relaunch manually? Is it possible to give to the users the possibility to relaunch training if status is stuck as dirty?

**Comment by l5t** [comment]
sorry for the late reply. Is it still stuck? if so can you share the Wit app URL?

**Comment by giorgiomarzianidepaolis-was** [comment]
Hey, thanks for reply!
No, it's not, we asked on facebook group and got faster help! :)

Thanks,
Giorgio


Giorgio Marziani de Paolis / Technology Director / We Are Social
T: +39 02 89708506 M: +39 344 2436223  Skype: netrace  Twitter: @giorgiomarziani
A: Corso San Gottardo 42/a, 20136, Milano W: wearesocial.it 
Milan x London x New York x San Francisco x Paris x Munich x Berlin x Singapore x Shanghai x Sydney x São Paulo
