### ISSUE TITLE
Bot engine doesn't understand certain things even after teaching it.

### ISSUE THREAD

**Issue by atinder** [wit-ai/wit#338]
Went to **understanding tab** in dashboard.

Entered: Cafe

Taught bot that

**intent**: some_query
**agenda**: Cafe

Now if I enter Cafe again, bot does not seem to understand what I taught.

However it does understand if I change Cafe to Restaurant.

The problem is, its not saving data what is being taught for certain things.

**Comment by MathieuDuboy** [comment]
+1 exact same thing for me, It seems it doesn't learn what I've thought to him

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018.https://wit.ai/blog/2017/07/27/sunsetting-stories
