### ISSUE TITLE
Wit/Quantity for people

### ISSUE THREAD

**Issue by thomasnivot** [wit-ai/wit#339]
Hi,

i'd like to find the right entity to make my bot understand that quantity: 50 employees

should i take wit/number only for the "50" or wit/quantity for "50 employees" ?

Quantity requires 2 customs entities to works (like liters & milk) despite this would it work ?

Thanks!

**Comment by l5t** [comment]
Hello, you should use wit/number (wit/quantity is tricky and doesn't work well). Soon we will bring back composite entities that will allow you to do what wit/quantity was supposed to do

**Comment by thomasnivot** [comment]
Thank you for the tips :) guess numbers cannot understand what they refers to ... like i have to select only 50 and not "50 people" else wit wont understand ?

**Comment by l5t** [comment]
Correct but if you have different numbers in your queries you can use Roles:https://wit.ai/docs/recipes#differentiate-several-entities-according-to-their-role-in-the-message

**Comment by thomasnivot** [comment]
Thanks! 

In this exemple wit understand that the word "an" isn't a number but in french "an" refers to the same meaning as "one" and is written the same way (**un** appartement avec **1** salle de bain) could i disabble the function that wit understand numbers in letters as a wit/number ? or Should i go for myself with my own entity "number_people"

![](https://wit.ai/docs/images/recipes/roles-1-1e913521.png)
