### ISSUE TITLE
Add CORS support to the Wit HTTP API

### ISSUE THREAD

**Issue by andrewserff** [wit-ai/wit#34]
I would like to send requests to the Wit API from a browser application, but without building a server proxy, I can't make cross domain requests to the Wit server.  Would it be possible to add [CORS](http://www.html5rocks.com/en/tutorials/cors/) support to the API so that we can make cross domain requests?  

Then you would be able to do something like this from the browser:
<pre><code>handleResult = function(textResult) {
    $.ajax({
        url: 'https://api.wit.ai/message',
        headers: {'Authorization': 'Bearer mykey'},
        data: {
            'q': textResult
        },
        method: 'POST',
    })
            .done(function(result) {
                console.log(result);
            })
            .fail(function() {
                alert("error");
            });
}
</code></pre>

Right now when you attempt the above request, you get:
>XMLHttpRequest cannot load https://api.wit.ai/message. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access.

**Comment by murat0658** [comment]
any update? how can we use "POST" method in Ajax, jQuery. We tried JSONP before and it gave bad URL exception.

**Comment by blandinw** [comment]
JSONP can only be used with GET. If you really want CORS, please reopen an issue and we'll leave it open as a feature request to see if it gains traction

**Comment by murat0658** [comment]
ok. thank you. i will ask another: is there any other way of getting bot's response to my query in my web site?

**Comment by blandinw** [comment]
You can use the `GET /message` API from your website, as this does not require CORS.
You'll need to write some code to generate a bot answer from the intent and entities you extract.

CORS support has been requested here #242 by the way
