### ISSUE TITLE
Where do we get other users stories and how to import that in our app in wit.ai?

### ISSUE THREAD

**Issue by newdev7** [wit-ai/wit#340]
I have created a new app in wit.ai. I created new stories for that app with intent and replies using 'Bot sends'. I'm using node.js. It works normally as expected. There is no issues with this.

What I want to know is 1. Where do we get the other users stories. 2. How do we import that stories in our existing app?

We can import the zip file of an existing app, while creating a new app. But how do we import in our app which is already created? All wit.ai related articles mention about reducing training time by using stories of other users, but I'm not able to find such stories.

Thanks.

**Comment by froasiooneloop** [comment]
+1 for this, same doubts.

**Comment by newdev7** [comment]
@froasiooneloop Are you able to find the solution for this issue?

**Comment by froasio** [comment]
@newdev7 No, you can only import a previous app from .zip when you are creating a new app. It would be great to have this feature because it is very difficult to version the app, too cumbersome to have a production and staging environment.

**Comment by newdev7** [comment]
@froasio Do you know where do we get the .zip of the other open projects?

**Comment by froasio** [comment]
@newdev7 You can find that here

https://wit.ai/docs/recipes#copyexportversion-my-app

**Comment by blandinw** [comment]
For now, you can import existing .zip files.
We're thinking of adding more community-oriented features, but this is low-pri and still very much in the air.
Closing.

**Comment by aiiskatel** [comment]
Why this branch closed without clear answer?

**Comment by patapizza** [comment]
@aiiskatel The answer is: import/export zip files. Regarding including other stories into your own app, it is not of high priority right now so there is no point in keeping a ticket hanging.
