### ISSUE TITLE
Variables in quick replies

### ISSUE THREAD

**Issue by magnusburton** [wit-ai/wit#341]
I'd like to suggest the feature to be able to use variables (the ones in curly brackets) in quick replies. It'd add the possibility for the bots to be even more dynamic with ever changing quick replies.

Thank you!

**Comment by sabinbajracharya** [comment]
You could put the variables in "response text" itself and then in your server split the response text if you have multiple variables and use any one of the quick replies and combine with it.

Example for weather:
Your response text  =  "cloudy 25°C"
Your 1st quick reply = "Its is @ with a temperature of @" 
Your 2nd quick reply = "Its @" 

Now you would split the response text and use either one or both "cloudy" or "25°C" by replacing the @ with the values 

Output : Its cloudy with a temperature of 25°C or Its cloudy
