### ISSUE TITLE
'Thank you’ being detected as search query always. Even after training it for entity

### ISSUE THREAD

**Issue by newdev7** [wit-ai/wit#342]
I have created a new app in wit.ai. In stories, I have created entity with different intents. Here I used 'Thank you' as a different intent. But when I send 'Thank you' to wit, it considers it as a search query instead of the entity which I created. I trained it for that entity in the 'Understanding tab. But still it is considering it as a search query. Like that for some other intent also, it considers as a search query only. What shall I do to make the 'Thank you' string as an entity instead of search query?

Thanks.

**Comment by l5t** [comment]
Some built-in entities like wit/search_query are trained across thousands of Wit apps hence can behave a little bit strange. I suggest you create your own custom entity for search query

**Comment by bojnordsky** [comment]
HI everyone.
I have similar problem. I need to search something throw the wikipedia, how can I do it?

**Comment by patapizza** [comment]
Hi @bojnordsky, please open a new ticket for new issues, it's easier to track.
You can use `wit/wikipedia_search_query`.
