### ISSUE TITLE
Not getting correct action using wit Converse API while test bot works fine

### ISSUE THREAD

**Issue by manish323** [wit-ai/wit#346]
My story works perfectly with the test bot , while doing the same with converse API it does not work and I abruptly receive 'stop'.
See the screen shot:
Test bot:
![capture](https://cloud.githubusercontent.com/assets/19220819/21226354/1ad1cfa2-c2fb-11e6-928c-8d01f8f0c6df.PNG)

Same thing with API  Log view:
![capture](https://cloud.githubusercontent.com/assets/19220819/21226433/7adba832-c2fb-11e6-8cd6-d509290b23b6.PNG)

If needed I can share the App with you.

thanks
-manish

**Comment by asssmidt** [comment]
Not many responses on all these issues :(

I believe I have the same issue, and it could also be the same issue as this one: https://github.com/wit-ai/wit/issues/311

No responses on that one either...

**Comment by Rclemens** [comment]
This has been asked multiple times now and still no answer...

**Comment by l5t** [comment]
It's probably related to your session id. You will use a new session id to start a new conversation. More info here: https://wit.ai/docs/recipes#integrate-link. If you keep using the same session_id for test, then the model will try to take into account the previous states of the context. Wit use the current context (keys only for now), the previous states of the context (at interaction N-1, N-2….) but also the user message (trait entities) to predict the next action

**Comment by manish323** [comment]
Thanks Laurent, I do not think  this is related to session Id as I am taking system time in milli sec as my session id for each new conversation automatically.

Thanks
-manish

**Comment by manish323** [comment]
https://wit.ai/manish323/NewFly/

Here is the location of my test story ..

Thanks
-manish

**Comment by asssmidt** [comment]
@l5t Did you look into this? We've spend almost a week looking into this converse thing. So would be kind of nice to know if this - pretty core - feature is working, and even nicer how!

Thanks!

**Comment by Rclemens** [comment]
@asssmidt I gave up on it! I'm going to use a combination of the IBM watson converse and wit.ai message api

**Comment by asssmidt** [comment]
@Rclemens It's just a Danish language bot we're building :(

Also, Converse is the %$%#% 2nd thing Wit mentions in their docs, can't believe/understand how that can't be working and why their team wouldn't be doing something to fix it (or remove it from their docs at least).

**Comment by l5t** [comment]
@asssmidt  I did answered via email

**Comment by asssmidt** [comment]
@l5t How could I have missed that, sorry! I just replied back with out Wit app URL.

Thanks!

**Comment by Rclemens** [comment]
@asssmidt Please share

**Comment by asssmidt** [comment]
Promise to share any breakthroughs.

**Comment by manish323** [comment]
Hi Laurant,

Gentle reminder for below. We are kind of stuck ..

 

From: Tapan Saxena [mailto:tapan.saxena16@gmail.com] 
Sent: 28 December 2016 01:30 PM
To: Manish Agrawal <manish.agrawal@yagnaiq.com>
Subject: Fwd: RE: Converse Api not working

 





Hello Laurent 


Good Morning , hope this mail finds you well.

 

We have tried using the converse API from our code as well as an rest client (DHC) and in both the cases the results are same where we see Wit missing a step. 

As mentioned earlier we are talking about the 

https://wit.ai/manish323/NewFly/stories

 

Here is the step by step description of the issue and our request response with wit API:

 

 

STEP 1

​ 

I want to fly from Mumbai to Pune and gets correct action that is Flight

Expected Behaviour : No Issues 

Request:

 

POST /converse?v=20160523&session_id=tapanyagna123&q=want+to+fly+from+mumbai+to+pune HTTP/1.1

Host: api.wit.ai <http://api.wit.ai> 

Authorization: Bearer WBLUFAVLTZEZPZOZ4GEQDZBNT6364NQG

 

Response:

HTTP/1.1 200 OK

Server: nginx/1.8.0

Date: Tue, 20 Dec 2016 06:19:14 GMT

Content-Type: application/json

Content-Length: 518

Connection: keep-alive

 

{

  "confidence" : 0.005513573407392054,

  "type" : "action",

  "action" : "flight",

  "entities" : {

    "intent" : [ {

      "confidence" : 0.792877412477589,

      "type" : "value",

      "value" : " fly "

    } ],

    "origination" : [ {

      "confidence" : 0.9931157928027375,

      "type" : "value",

      "value" : "mumbai",

      "suggested" : true

    } ],

    "destination" : [ {

      "confidence" : 0.9499681498564528,

      "type" : "value",

      "value" : "pune",

      "suggested" : true

    } ]

  }

}


STEP 2

Now as we received both origination as well as destination we set the context “gotBoth”. The wit API responds with "when do you want to fly" asking time 

Expected Behaviour : No Issues 

Request

POST /converse?v=20160523&session_id=tapanyagna123&q HTTP/1.1

Host: api.wit.ai <http://api.wit.ai> 

Authorization: Bearer WBLUFAVLTZEZPZOZ4GEQDZBNT6364NQG

{"gotBoth":"answer"}

 

Response

HTTP/1.1 200 OK

Server: nginx/1.8.0

Date: Tue, 20 Dec 2016 06:20:09 GMT

Content-Type: application/json

Content-Length: 96

Connection: keep-alive

 

{

  "confidence" : 0.006158704170897137,

  "type" : "msg",

  "msg" : "When do you want to fly"

}

 

STEP 3

 

Expected Behaviour : Issue as wit responded with action as ‘Stop’ while it was expected to send action as ‘final_flight’. 

 

when mention 24 Dec16 it gives a stop command instead of final - flight 

POST /converse?v=20160523&session_id=tapanyagna123&q=today HTTP/1.1

Host: api.wit.ai <http://api.wit.ai> 

Authorization: Bearer WBLUFAVLTZEZPZOZ4GEQDZBNT6364NQG

HTTP/1.1 200 OK

Server: nginx/1.8.0

Date: Tue, 20 Dec 2016 06:20:40 GMT

Content-Type: application/json

Content-Length: 587

Connection: keep-alive

 

{

  "confidence" : 0.005145573674196805,

  "type" : "stop",      ----- expected was final_flight

  "entities" : {

    "datetime" : [ {

      "confidence" : 1,

      "values" : [ {

        "value" : "2016-12-24T00:00:00.000-08:00",

        "grain" : "day",

        "type" : "value"

      }, {

        "value" : "2017-12-24T00:00:00.000-08:00",

        "grain" : "day",

        "type" : "value"

      }, {

        "value" : "2018-12-24T00:00:00.000-08:00",

        "grain" : "day",

        "type" : "value"

      } ],

      "value" : "2016-12-24T00:00:00.000-08:00",

      "grain" : "day",

      "type" : "value"

    } ]

  }

}


STEP 4

 

Surprise !! : If we send the above request again this time the converse API sends the correct response.—Why??

 

 

POST /converse?v=20160523&session_id=tapanyagna123&q=today HTTP/1.1

Host: api.wit.ai <http://api.wit.ai> 

Authorization: Bearer WBLUFAVLTZEZPZOZ4GEQDZBNT6364NQG

HTTP/1.1 200 OK

Server: nginx/1.8.0

Date: Tue, 20 Dec 2016 06:21:11 GMT

Content-Type: application/json

Content-Length: 635

Connection: keep-alive

 

{

  "confidence" : 0.004272406566285844,

  "type" : "action",

  "action" : "final_flight",

  "entities" : {

    "datetime" : [ {

      "confidence" : 0.8633299697906186,

      "values" : [ {

        "value" : "2016-12-24T00:00:00.000-08:00",

        "grain" : "day",

        "type" : "value"

      }, {

        "value" : "2017-12-24T00:00:00.000-08:00",

        "grain" : "day",

        "type" : "value"

      }, {

        "value" : "2018-12-24T00:00:00.000-08:00",

        "grain" : "day",

        "type" : "value"

      } ],

      "value" : "2016-12-24T00:00:00.000-08:00",

      "grain" : "day",

      "type" : "value"

    } ]

  }

}

​


What we are wondering is why wit is sending ‘stop’ action instead of giving the recommended (final_flight) action.

How come sending the same request next time fixes the issue?

 

We are really struck here .The code is working fine in the console but giving errors when working with converse api .


Please help at the earliest as we have some deadlines to show a prototype bot 

Thanks and Regards 

Tapan

​

**Comment by l5t** [comment]
I answered to your email but posting here for the sake of the community. I encourage you to test in WittyFiddle first to see if this is the API or your integration. Example here: https://wit-ai.github.io/witty-fiddle/?id=4a526582ecee7a3c8cc5b2939dff75cd

The issue you have is that you don't call the API until you get a action=stop. Here is an extract of our API documentation

> To retrieve the whole sequence of actions, you need to successively call /converse until the type is stop. See example on the right. In the initial call, you would set q to the user message. In the following calls, you should leave it null (don’t set it).

(source: https://wit.ai/docs/http/20160526#post--converse-link)

So before sending another user input in an API call, you need to get a stop first. Here is the sequence of action that you can try (please change the session_id each time you retry the sequence)

`curl -XPOST 'https://api.wit.ai/converse?v=20160526&session_id=123cba321&q=want%20to%20fly%20from%20mumbai%20to%20pune'
      -H "Content-Type: application/json"
      -H "Accept: application/json"
      -H 'Authorization: Bearer WBLUFAVLTZEZPZOZ4GEQDZBNT6364NQG'`


`curl -XPOST 'https://api.wit.ai/converse?v=20160526&session_id=123cba321' 
      -d '{"gotBoth":"answer"}' 
      -H "Content-Type: application/json" 
      -H "Accept: application/json" 
      -H 'Authorization: Bearer WBLUFAVLTZEZPZOZ4GEQDZBNT6364NQG'`

`curl -XPOST 'https://api.wit.ai/converse?v=20160526&session_id=123cba321' 
      -d '{"gotBoth":"answer"}' 
      -H "Content-Type: application/json" 
      -H "Accept: application/json" 
      -H 'Authorization: Bearer WBLUFAVLTZEZPZOZ4GEQDZBNT6364NQG'`

This last call returns STOP

`curl -XPOST 'https://api.wit.ai/converse?v=20160526&session_id=123cba321&q=today' 
      -H "Content-Type: application/json" 
      -H "Accept: application/json" 
      -H 'Authorization: Bearer WBLUFAVLTZEZPZOZ4GEQDZBNT6364NQG'`

`curl -XPOST 'https://api.wit.ai/converse?v=20160526&session_id=123cba321' 
      -d '{"info":"IT WORKS!!!"}' 
      -H "Content-Type: application/json" 
      -H "Accept: application/json" 
      -H 'Authorization: Bearer WBLUFAVLTZEZPZOZ4GEQDZBNT6364NQG'`

`curl -XPOST 'https://api.wit.ai/converse?v=20160526&session_id=123cba321' 
      -H "Content-Type: application/json" 
      -H "Accept: application/json" 
      -H 'Authorization: Bearer WBLUFAVLTZEZPZOZ4GEQDZBNT6364NQG'`

This last call returns also a STOP

Hope it helps
