### ISSUE TITLE
"week" elicits a single datetime value

### ISSUE THREAD

**Issue by duaraghav8** [wit-ai/wit#349]
sentences like

"what is jerry doing **this week**?" OR
"do I have a meeting **next week**", etc.

elicit a single datetime value corresponding to 00:00 of Monday of the week in context.

In my opinion, it should instead be a range: ```from Monday 00:00 to Friday 23:59```
Because **weekend** behaves in that way (```Friday 6pm to Monday 00:00```)

(EDIT 1: Same could apply to "this year", "this month", etc)

What do you think?

**Comment by ksperling** [comment]
The behaviour is consistent with 'week', 'day', 'month', 'hour' etc, they are all treated as a single value with the `grain` property specifying the unit. 'weekend' is different in that it isn't a unit of time as such.

In practice a fair bit of post-processing of datetime entities seems to be required to get the right semantics at the application level.

**Comment by duaraghav8** [comment]
thanks @ksperling

**Comment by duaraghav8** [comment]
Follow up:
Is there an exhaustive list of possible values for ```grain```?

I looked up up several documents including [this](https://wit.ai/docs/http/20160526#get--message-link) and [this](https://duckling.wit.ai/#introduction), but couldn't find it.

Or do I have to find them out from the Duckling source code itself?
