### ISSUE TITLE
I'm traying to access from C# and I get always (401) Unauthorized

### ISSUE THREAD

**Issue by javirs85** [wit-ai/wit#35]
this is my code, simple: string

```
        using (WebClient wc = new WebClient())
        {
           string URI = "https://api.wit.ai/message?q=what%20time%20is%20it%3F";
            wc.Headers[HttpRequestHeader.Authorization] = "Authorization: Bearer BF54VOR3AJ33WKYEXEAYFFAEPJVR726V";
            string HtmlResult = wc.UploadString(URI, "");
        }
```

I guess the error comes from bearer but .. no idea how to express it correctly. Is there any documentation beside the cURL ?

**Comment by 02zarna** [comment]
How can i add multiple parameter in this coding

**Comment by 02zarna** [comment]
using (WebClient wc = new WebClient())
        {
            string URI = "https://api.wit.ai/message?q=what%20time%20is%20it%3F";
            wc.Headers.Add("Content-Type", "text");
            wc.Headers[HttpRequestHeader.Authorization] = "Bearer xxxxxxxxxxxxxxxxxxx";
            string HtmlResult = wc.DownloadString(URI);
        }

I want to send multiple parameter in this code then how, this code working for me but i want this with multiple parameter pass in string. please hep me its solve my problem.

**Comment by l5t** [comment]
Have you looked at other examples from the community? https://github.com/search?l=C%23&q=wit.ai+c%23&type=Repositories

**Comment by 02zarna** [comment]
Can i get Bluedart API Format in C# Asp.net. If you have any source code regarding this please give it to me.

**Comment by aforaleka** [comment]
Hi @02zarna, you may want to ask the community in our FB group instead

**Comment by 02zarna** [comment]
Which FB group?

**Comment by l5t** [comment]
https://www.facebook.com/groups/withackers
