### ISSUE TITLE
Datetime doesn't understand several date expressions in portuguese

### ISSUE THREAD

**Issue by BeatrizHerculano** [wit-ai/wit#353]
When i train several date expressions in Portuguese, the entity datetime doesn't understand like date. Some expressions are:

"mês passado"
"semana passada"
"dia X" (just like in "day 4")
"ano retrasado"

Thanks.

**Comment by l5t** [comment]
Thanks for reporting. You can help/contribute since this part is open sourced here: duckling.wit.ai
