### ISSUE TITLE
Stuck in "training status: ongoing"

### ISSUE THREAD

**Issue by redbaron76** [wit-ai/wit#354]
My app stuck at first story...
https://wit.ai/redbaron76/Lastaurant

**Comment by manish323** [comment]
Looks like something is not right with wit today because even our (mine and my coworker) stories also getting stuck.

 

Thanks

-manish

**Comment by georgereason** [comment]
Same here... 

https://wit.ai/georgereason/Orlando_Informer_Assistant

**Comment by l5t** [comment]
We fixed an issue with the Understanding training. Please validate a new example to restart the training automatically. We are also investigating an issue with the story training and will update you when fixed

**Comment by stopachka** [comment]
Checking both of these, and it looks like they are running. There is an ongoing issue with some story training checks failing. Will update regarding that on https://github.com/wit-ai/wit/issues/357
