### ISSUE TITLE
Stuck in training mode...

### ISSUE THREAD

**Issue by omidai** [wit-ai/wit#357]
My app got stuck in training mode. I think something wrong happened in Wit

**Comment by l5t** [comment]
We are investigating the stories issue cc @stopachka

**Comment by Mariskavh** [comment]
sadly I have the same issue. It has been stuck in training mode since yesterday even though I really didn't add that many example phrases.

**Comment by l5t** [comment]
Can you share your Wit app URL?

**Comment by sindre** [comment]
Same here.  It has been stuck in training mode since last Thursday even though I changed only one story.

**Comment by Mariskavh** [comment]
Hi I5t, the URL is https://wit.ai/marisvh/RequestResources

**Comment by l5t** [comment]
Should be good now
