### ISSUE TITLE
Import function not working when compressing folder manually

### ISSUE THREAD

**Issue by Davidovich4** [wit-ai/wit#358]
Hi,

When I export an app from wit.ai I get a .zip file as a result. If I straight up import the .zip file as version 2, it works, but if I decompress it and then compress it again and try to upload, then I get an unknown error (in the upper right corner).

![witai import bug](https://cloud.githubusercontent.com/assets/3731667/21638791/24ab1d72-d26d-11e6-9202-4d7c82d3c922.png)

How do you get through this?

Sincerely,
Dave

**Comment by stopachka** [comment]
this happened most likely because import requires the app to come in order (you can follow the `zip-command` in app.json. we will soon create a version where the order won't matter
