### ISSUE TITLE
wit is very slow today

### ISSUE THREAD

**Issue by eoquendo** [wit-ai/wit#360]
hi! earlier this week wit was got stuck on training mode. I created another app yesterday and it started working. However today, all my apps have been working really slow. 

I am running a node.js server on Heroku and whenever I call wit it gets stuck by 20-30 seconds. 

I have tried it with multiple apps and it is equally slow.

my apps are: 
https://wit.ai/emmanuelfoquendo/mediabot-devnew
https://wit.ai/emmanuelfoquendo/news_bot_upd_dec_28

I appreciate your help.

**Comment by carloscarvallo** [comment]
Same here

**Comment by jhoelzl** [comment]
+1

**Comment by carloscarvallo** [comment]
I have _training status, ongoing_ constantly

**Comment by l5t** [comment]
cc @patapizza we had some issues 8hours ago but it should be better now. If not, please paste the Wit app URLs that  are stuck in training

**Comment by patapizza** [comment]
Yes it's resolved now. Feel free to reopen with your app if that's not the case.

**Comment by carloscarvallo** [comment]
https://wit.ai/carloscarv/MillerBOT this is my app, training status, ongoing about a week

**Comment by patapizza** [comment]
@carloscarvallo Just fixed it!

**Comment by jstnn** [comment]
im stucked also https://wit.ai/jstnn/callbot/stories

**Comment by l5t** [comment]
Should be better now

**Comment by hakkinepally** [comment]
My App is really slow with 3 minutes delay.

What is the App ID where you are experiencing this issue (if applicable)?
5a4de5ec-f56b-496a-abb6-152820bfcd8a

**Comment by l5t** [comment]
sorry for the late reply. Do you still experience this?

**Comment by hakkinepally** [comment]
yes i do

**Comment by blandinw** [comment]
@hakkinepally I'm seeing sub-second response times. Where are you calling our servers from? Are all sentences slow, or just some? If only some, can you send an example slow sentence?

**Comment by hakkinepally** [comment]
@blandinw I am calling the Servers from India. Is it only restricted to United States ? Yes, all Sentences are very slow. I have only two intents: greetings and quantity. Pretty Basic.

**Comment by bkurowski** [comment]
I have same problem "Ongoing" training non stop.
Created test app to play around but it is stuck.
My APP ID: 5b487835-f9fa-43e0-b98c-8947b2e111a5
Any possible help out there ?
Thanks !
