### ISSUE TITLE
Is there some issue with wit.ai today?

### ISSUE THREAD

**Issue by gadife** [wit-ai/wit#362]
Works quite slow today, and sometimes getting "WitError: Wit responded with status: 500 (Internal Server Error)"

**Comment by l5t** [comment]
There were earlier this morning but we fixed them

**Comment by missdielle** [comment]
I'm consistently getting WitError: Wit responded with status: 500 (Internal Server Error) today...is it down?

**Comment by coolnic** [comment]
getting an error with long speech recorded wav file while converting into text...
WitError: Wit responded with status: 500 (Internal Server Error)

**Comment by abhijain1351** [comment]
What audio length is preferable for speech recognition using wit.ai?
