### ISSUE TITLE
My bot doesn't learn what I teach him

### ISSUE THREAD

**Issue by MathieuDuboy** [wit-ai/wit#364]
I'm trying to teach my bot to understand wit/datetime (In French format and other) but it doesn't recognize what I've thought to him lately.
What is wrong with this ? Am I doing something wrong ?
Thank you

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/11943636/21955260/850d78d4-da67-11e6-8cd4-0789f17e4526.gif)

**Comment by patapizza** [comment]
This now works.
