### ISSUE TITLE
Best practices for validations in Wit

### ISSUE THREAD

**Issue by srijan17** [wit-ai/wit#365]
Sorry Im a newbie.Maybe my question may seem dumb but I wanted to add validations to my Wit facebook messenger. could someone point me in a direction on how to validate for stories input. I tried an approach with bookmarking before every question and checking for error but that seemed useless. Also what are some best practices while branching and bookmarking.

**Comment by blandinw** [comment]
Have you tried reading the documentation? https://wit.ai/docs
Feel free to reopen.
