### ISSUE TITLE
How to change the charset in converse request

### ISSUE THREAD

**Issue by m7vm7v** [wit-ai/wit#366]
Hi everyone. 
I have a problem with the french charset. 
When I ask the bot in wit it answers right. 
But when I ask from my server and the request is for example:

https://api.wit.ai/converse?v=20160526&session_id=123abc&q=Comment&q=ça

There are the french characters but in the log in wit it apperars that I have not asked 'Comment ça', but 'Comment ￃﾧa'

My headers are 

```
-H "Content-Type: application/json" \
-H "Accept: application/json" \
-H 'Authorization: Bearer token'
```

Do you think that I need to add something in the headers to make it working.
What an I do about that. Thanks

**Comment by l5t** [comment]
You need to URLencode your query. In your example it will be:
Comment%20%C3%A7a

**Comment by m7vm7v** [comment]
Yep, I am sorry for the example but right now I am encoding every blank space with '%20' so the 'q' i am sendin is q=Comment%20ça .... But it is still not recognized ..... Do I need to engode the french characters too?

**Comment by l5t** [comment]
Yes as shown in my example: %A7 for ç
