### ISSUE TITLE
How to get respond from the stories

### ISSUE THREAD

**Issue by m7vm7v** [wit-ai/wit#368]
Hi,
How can I get all the messages form the story.

And in my Stories Section I have a story 
User says: Test
Bot Sends: test1 ....and right after another message: test2 

When I chat with the Bot from Wit when I ask him Test he answeres with test1 and another message test2 right after the first one.

In my server side so far I have a post request to https://api.wit.ai/converse?v=20160526&session_id=243&q=Test and the respond is something like:

```
array:4 [
  "confidence" => 0.067749119195621
  "type" => "msg"
  "msg" => "Test 1"
  "entities" => array:2 [
    "test" => array:1 [
      0 => array:3 [
        "confidence" => 0.93487934317773
        "type" => "value"
        "value" => "test"
      ]
    ]
  ]
]
```

But I do not have the value from the second message that the Bot says.
How can I get all the messages from the bot from stories.

Thanks for your time

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018.https://wit.ai/blog/2017/07/27/sunsetting-stories
