### ISSUE TITLE
Intent metadata

### ISSUE THREAD

**Issue by Seraf** [wit-ai/wit#37]
Hello Wit team,

Is it possible to implement a metadata field on an intent ?
I need to add a description field on intent to describe what will be the goal of this intent.

In my case, a user will ask my software what it can do. My sofware will list intents and vocalize for each intents the description field.
I think this metadata field should be flexible, I mean I should be able to insert an embedded json dictionnary in this metadata field.

What do you think about it ? I will help filling the gap between wit and ours softwares.

Thanks !

**Comment by alexandruf** [comment]
Hi Guys!
Please, excuse me to open this topic again.
Do you know if we can put a regex for an user defined intent? If not, can we have this?
