### ISSUE TITLE
Stuck in training status ongoing

### ISSUE THREAD

**Issue by roumeng** [wit-ai/wit#371]
Hi,
My app is stuck on training status since hours 
https://wit.ai/roumengueorguiev/Rentila/stories

Could you help me with this matter ?

**Comment by rfun** [comment]
I have the same issue with my app : 

https://wit.ai/rfun/Face2FaceDev

@l5t ?

**Comment by divyashan** [comment]
I'm having the same issue; is there a way to exit/halt this training phase manually? 

https://wit.ai/divyashan/MyFirstApp/
https://wit.ai/deeptir18/Test-App-2

**Comment by l5t** [comment]
Restarted manually

**Comment by rfun** [comment]
@l5t  : Thanks, but if I update my story, the same issue happens again. What is causing this issue? Am I doing something wrong with my entities or story to cause this to get stuck?

**Comment by rfun** [comment]
@l5t  : I also tried to validate a new example and it is still stuck. Any help is appreciated

**Comment by l5t** [comment]
We have identified an issue and working on a fix. Thanks for your patience

**Comment by blandinw** [comment]
We have found the issue, rolled back the faulty code and retroactively retrained (hopefully) all 803 impacted apps.
We do sincerely apologize for the inconvenience *sad robot*
