### ISSUE TITLE
bookmark issue

### ISSUE THREAD

**Issue by ankit13555** [wit-ai/wit#372]
my bookmark is not working correctly......i have attached screenshots of it ...please help.......

![a7c267c6-954e-4ff0-b3fc-ab93e8ff0b1c](https://cloud.githubusercontent.com/assets/8336668/22582454/0f2d1092-ea0d-11e6-86c2-56d2f09381d8.jpg)
![a7c267c6-954e-4ff0-b3fc-ab93e8ff0b1c 1](https://cloud.githubusercontent.com/assets/8336668/22582461/1833e648-ea0d-11e6-9033-da94ecee0cbb.jpg)

**Comment by ankit13555** [comment]
![a7c267c6-954e-4ff0-b3fc-ab93e8ff0b1c 2](https://cloud.githubusercontent.com/assets/8336668/22585338/4e28d62c-ea1d-11e6-86b6-a8210b4cac08.jpg)

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
