### ISSUE TITLE
Localization and i18n for bots

### ISSUE THREAD

**Issue by srijan17** [wit-ai/wit#374]
So I was working on creating a localized chat bot using wit.ai and I require it to work on multiple languages. My problem is though there are a few methods with which people have successfully localised their chatbot but none of those methods are scalable.
I found a few methods but I am still unsure what are the best practice for the same.
https://chatbotsmagazine.com/do-you-want-your-chatbot-converse-in-foreign-languages-my-learnings-from-bot-devs-9b608f685f5b#.638a4ib7d

I found this post regarding localisation but this seems to be a bit old. Has the new updates brought any new functionality for i18n.
https://github.com/wit-ai/wit/issues/5

**Comment by blandinw** [comment]
At the moment, we do not provide easy ways to translate your app to other languages. Keeping this open to track the need and foster discussion.

**Comment by srijan17** [comment]
Thank you, so do we have to make different stories for each language?

**Comment by blandinw** [comment]
The recommended way for now is to create one app per language.
Wit won't function properly if you mix use more than 1 language in the same app.
