### ISSUE TITLE
Unable to login with Github

### ISSUE THREAD

**Issue by arunmathewthomas** [wit-ai/wit#375]
I am unable to login to Wit via Github login. I keep getting the same message

Uh oh... You cannot access this page
You'll need to sign in to view this page! Sorry about that!

**Comment by jjkalafut** [comment]
I've also had this problem. I was able to circumvent it by only having one wit.ai tab open at a time.

**Comment by hactar** [comment]
I'm having this issue too. Logging into an account I just created using facebook works fine, but github login appears to be broken (tried with safari, firefox and chrome).

**Comment by blandinw** [comment]
This issue was fixed shortly after being reported.
@hactar Looking into your issue now.

**Comment by blandinw** [comment]
@hactar The issue persisted for older accounts (thanks for being an early user!)
I pushed a fix to production, so you should be able to log in.
Let us know if you encounter any other issue!

**Comment by venkateshreddy** [comment]
@blandinw I am encountering the issue again.
I am not able to access the WIT pages with github login. 
My user name is venkateshreddy.

many times i tried to login. My github is open in another tab. When I click on login with github, it is showing some bubble kind of animation and stays calm again saying "Uh oh... You cannot access this page. You'll need to sign in to view this page! Sorry about that! ".

Thanks in advance.

**Comment by bharathgrk** [comment]
@blandinw I too am facing the same issue of not being able to login with my github account.
I have attached a screenshot of the wit.ai/home page that shows the error as well as the console error, if it will be of any help.

![screen shot 2018-05-22 at 12 37 29](https://user-images.githubusercontent.com/9738122/40347284-55db9fb6-5dbd-11e8-95c3-a0c705ca403f.png)

**Comment by IceCheater** [comment]
Unfortunately I have the same problem.
![zrzut ekranu 3](https://user-images.githubusercontent.com/38458401/40348806-fb9f8278-5da4-11e8-9845-8af07c06e4fd.png)

**Comment by patapizza** [comment]
@venkateshreddy @bharathgrk @IceCheater Thanks for reporting - issue https://github.com/wit-ai/wit/issues/1086 has been resolved.

**Comment by stopachka** [comment]
Hey team, there was an intermittent error last night. All should be well, more context here https://github.com/wit-ai/wit/issues/1178.

If you are still having issues please open up a new task

**Comment by Mirdrack** [comment]
Is there is a walk around to do this?

**Comment by aforaleka** [comment]
hey @Mirdrack, are you experiencing issues logging in? please open a new github issue if that's the case, thank you!

**Comment by tolui** [comment]
@blandinw Same problem here, I cannot login to WIT with my git account. I have not logged in for a while.  "Uh oh... You cannot access this page You'll need to sign in to view this page! Sorry about that!"

**Comment by equisde** [comment]
@tolui same problem here i can't login with facebook or github
