### ISSUE TITLE
Number to datetime

### ISSUE THREAD

**Issue by leizard** [wit-ai/wit#376]
I get an issue with my training data. I input 2000 and try to get as custom number entity but wit always get as default entity wit/datetime .I think wit will alway priority default value more than custom value.

**Comment by blandinw** [comment]
Thanks for your feedback! You're right. `wit/datetime` wins over `wit/number` (2000 could be the year 2000).
I understand this is a pain, but you should be able to work around this with some client-side code. We have ideas on how to fix this and will implement some time in the future, but this is not high priority for now.
