### ISSUE TITLE
Sharing Wit apps with other users

### ISSUE THREAD

**Issue by hahamark1** [wit-ai/wit#378]
Dear reader,

My wit.ai is coupled to a facebook account. THe apps in there will however be used by people that cannot acces this account. Is it possible to share apps to other accounts?

The share this app functions does not do anything.

Cheers,

**Comment by blandinw** [comment]
You can share your app with other people from the Settings tab.
What is not working?

**Comment by RiverExplorer** [comment]
No settings tab. Where is it?
