### ISSUE TITLE
error when adding new expression for trait entity

### ISSUE THREAD

**Issue by eoquendo** [wit-ai/wit#383]
Hi!

Been getting this error the last days when adding new expressions to the "brain_descripcion" entity that also has free-text expression "keyword_programa". 

It looks like it validates the expression but then suddenly throws an error. 

Also, when I go to the "brain_descripcion" entity section, it shows that the expression was saved but only with "keyword_programa" entity and not "brain_descripcion" which is the trait one. 

I would appreciate a lot your help. Thanks!

<img width="1280" alt="screen shot 2017-02-26 at 4 39 29 pm" src="https://cloud.githubusercontent.com/assets/19807950/23343747/b493de58-fc46-11e6-8685-0d1b6598f73f.png">
<img width="924" alt="screen shot 2017-02-26 at 4 49 20 pm" src="https://cloud.githubusercontent.com/assets/19807950/23343748/b4954428-fc46-11e6-82be-65c43181b253.png">
<img width="961" alt="screen shot 2017-02-26 at 4 49 14 pm" src="https://cloud.githubusercontent.com/assets/19807950/23343749/b497781a-fc46-11e6-9103-8b7d74c15d7c.png">
<img width="1279" alt="screen shot 2017-02-26 at 4 39 12 pm" src="https://cloud.githubusercontent.com/assets/19807950/23343750/b49b7262-fc46-11e6-816c-3d87057194b0.png">

**Comment by l5t** [comment]
We had some issue earlier but it should be fixed. Will close, please reopen if it happens again.
