### ISSUE TITLE
The Bot will Stop instead

### ISSUE THREAD

**Issue by hoodsy** [wit-ai/wit#384]
For some reason one of my stories says "The bot will stop instead" of executing my function.

It's very difficult to continue work on my project without being able to run my functions. There seems to be a timeout (sync) error in the console as well.

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018.https://wit.ai/blog/2017/07/27/sunsetting-stories
