### ISSUE TITLE
Invalid intent over the past couple of days

### ISSUE THREAD

**Issue by ConnectionGhost** [wit-ai/wit#386]
I seem to be having issues testing an intent over the past couple of days seems like the intents don't match with what i taught the bot. The bot correctly identifies the intent in the understanding tab but when i  test the bot using the console test and chat with the bot it will incorrect identify the intent and moves to default intent. did something break recently?  anybody else seeing this issue?
![image](https://cloud.githubusercontent.com/assets/1825535/23473007/5d30634a-fe74-11e6-81f7-1bebe2f07bcd.png)

**Comment by blandinw** [comment]
Apologies for the delay.
Can you confirm the issue still exist?
Closing in the meantime, please reopen with more info
