### ISSUE TITLE
Ducking is updated but the entity doesn't act like it mean to be.

### ISSUE THREAD

**Issue by BeatrizHerculano** [wit-ai/wit#388]
When i test the portuguese expression "vou pagar no dia 20" (i am going to pay on day 20) on the Duckling it works fine, but Wit can't get the datetime on de expression.

![capture](https://cloud.githubusercontent.com/assets/15809077/23579547/961e1d26-00ce-11e7-80da-b8c385e71959.PNG)
<br>
<br>
![capture2](https://cloud.githubusercontent.com/assets/15809077/23579549/979e6e80-00ce-11e7-957d-91da93b2ff7b.PNG)

**Comment by blandinw** [comment]
Is your app language set to Portuguese?
If so, could you provide me with your app id?

**Comment by blandinw** [comment]
Please reopen this issue if the problem still exists, we'd be happy to help.
Duckling open-source contributions are not applied to production right away.
