### ISSUE TITLE
Stuck At Training

### ISSUE THREAD

**Issue by rabberbock** [wit-ai/wit#392]
The training seems to be going on forever. Here is our [bot url](https://wit.ai/daveperson/Benefits_demo/stories/60c88ec5-99d5-4504-ab8f-1c735bc8d076). Any help would be much appreciated.

Thanks!

**Comment by l5t** [comment]
Restarted

**Comment by rabberbock** [comment]
Thanks for being so quick!

**Comment by rabberbock** [comment]
@l5t 
Can you please restart it again? It seems to be stuck again. Thanks!

**Comment by l5t** [comment]
done

**Comment by blandinw** [comment]
I just fixed a bug in the training scheduling that should be very relevant to this issue. Let us know if this happens again.
