### ISSUE TITLE
{"confidence":1,"type":"error"}

### ISSUE THREAD

**Issue by hamg26** [wit-ai/wit#393]
I keep getting `{"confidence":1,"type":"error"}`, even when there is a message or action that according to the context can be called.

Sometimes I get the error after the **checkBookingLocation** action puts correctly the key "location" in the context, sometime it's after the **confirmLocation** action.

![captura de pantalla 2017-03-07 a la s 16 11 32](https://cloud.githubusercontent.com/assets/4305176/23680736/ec190224-0351-11e7-87a0-268e71c997e1.png)

Hope you can help.

**Comment by hamg26** [comment]
![captura de pantalla 2017-03-07 a la s 16 25 17](https://cloud.githubusercontent.com/assets/4305176/23680987/c9b9c87a-0352-11e7-9f3a-5ade8e823318.png)

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
