### ISSUE TITLE
Long Flow Support

### ISSUE THREAD

**Issue by rabberbock** [wit-ai/wit#394]
I am trying to use stories for a survey like flow of about 10 questions. For some reason the flow works perfectly with seven steps in the flow, but more than that the flow seems to break and loop at the end.

Are stories supposed to support very long survey like flows or is this pushing it too much?

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
