### ISSUE TITLE
Handle out-of-scope / I don't know what you're talking about

### ISSUE THREAD

**Issue by blandinw** [wit-ai/wit#395]
This tracks a change to the API, or the confidence score to denote sentences/inputs that the Wit app is not able to understand. e.g. Asking for the weather to an alarm clock app.

**Comment by mashedkeyboard** [comment]
Is there an ETA on implementation for this? Would be awesome to have the ability to add out-of-scope default options as predicates.

**Comment by blandinw** [comment]
We don't have a clear ETA, but it is one of our few high-pri items. We'll update this issue as we make progress. It is still unclear whether we want to return a low confidence score for "out-of-scope" items, or if we want to add a field to the API. It will probably be a breaking change and require a version bump anyway.

**Comment by mashedkeyboard** [comment]
Awesome, excited for it :)
