### ISSUE TITLE
Question re converse api, sessions, intent & replies

### ISSUE THREAD

**Issue by mhjb** [wit-ai/wit#397]
Hi team

I'm a bit confused by Wit.ai's converse api. I'm building a sort of FAQ-bot, to answer questions that students or parents might have at school. Until today I was sending a new session_id with every request, and wit was doing a good job of matching the inputs with the saved intents. Now today I've started sending the userid as session_id, reasoning that wit will be able to make better guesses about a conversation flow if it knows what's been said before. However now I'm getting responses like the one in the screenshot. Wit has correctly detected the intent 'If my school has a uniform, do I have to wear it?', but the type is set to 'stop' rather than 'msg', and no msg containing wit's stored reply is sent.

Any clues?
Matthew

![image](https://cloud.githubusercontent.com/assets/1380991/23734401/c099fa2a-04e3-11e7-9003-81ba1944298c.png)

**Comment by l5t** [comment]
You will use a new session id to start a new conversation. More info here: https://wit.ai/docs/recipes#integrate-link. If you keep using the same session_id for test, then the model will try to take into account the previous states of the context. Wit use the current context (keys only for now), the previous states of the context (at interaction N-1, N-2….) but also the user message (trait entities) to predict the next action.

**Comment by mhjb** [comment]
Thanks @l5t, but can you explain why it correctly identifies the "If my school…" intent, but doesn't send the associated message back?

Also, why are their two confidence variables sent back?

**Comment by l5t** [comment]
There are 2 confidences: the prediction confidence influenced by the session id and the Undestanding confidence. For example we take the trait entity in the prediction model. As a result, usually your first call to /converse with a user query will have a high confidence compared to the second call with just an updated context and no user query.

**Comment by mhjb** [comment]
Thanks Laurent. I wonder if my [use case](https://wit.ai/mhjb/wagbot) (access a knowledge base, rather than complete a transaction) is not quite suitable for Wit.ai.
