### ISSUE TITLE
wit/reminder entity detection not working properly

### ISSUE THREAD

**Issue by anutammewar** [wit-ai/wit#398]
I have created a bot just to identify reminder-phrase from a sentence. I used the built-in wit/reminder for the same, initially tweaked a bit by validating some samples. We are using it in a real system where a lot of reminder queries are asked. We hit the bot around 1000 times in a day. I keep on validating the queries everyday. All worked fine initially. But since last few days, I'm facing a lot of issues.

A lot of times the entity is not identified, even in simple examples. Whenever this happens, I have to validate some queries from "inbox" and it starts working again.

But, since last 2 days this is also failing. Now, it is not working at all, it keeps on training/updating model but does not identify anything.

As it is being used in our app, it very important for us to detect this entity.

I'm not being able to understand why would this happen.

One of the reasons I could think of is: because our queries are from chat, and the language used is not grammatical, validating such examples a lot of times could have affected the builtin entity.

Please help me with this.

App ID: 585b850d-1a7c-4e23-a51c-acf2fd27b039

Making the app "private" would help?

**Comment by blandinw** [comment]
I assume your app is configured to be in English?

**Comment by blandinw** [comment]
@anutammewar This is not due to something you did. We have suffered a small outage and some of our builtin entities needed to be retrained.
I rolled out a new model for `wit/reminder`. It should work fine now.
Please reopen the issue if the problem persist!
