### ISSUE TITLE
Enable travis for wit-ios-sdk

### ISSUE THREAD

**Issue by hactar** [wit-ai/wit#400]
The iOS SDK (https://github.com/wit-ai/wit-ios-sdk) now includes a travis file for CI that compiles the sdk and runs tests to ensure the sdk still works after a PR. It would be great if someone could enable travis building for the wit-ios-sdk under https://travis-ci.org/profile/wit-ai .

**Comment by blandinw** [comment]
Just did, let us know if we need to enable something else!
![image](https://cloud.githubusercontent.com/assets/413070/23965182/6a4cb0c8-0974-11e7-84bc-fd7c0f338ffb.png)
