### ISSUE TITLE
TRIM-ing entity keywords

### ISSUE THREAD

**Issue by bmcclenahan** [wit-ai/wit#401]
This is a feature request.
When entity keywords are created through training, if there is an inadvertent space at the end of the selected text, that space is saved into the keyword, and returned in subsequent entity identification. This requires the calling software to TRIM every entity returned to ensure that matches work properly.

Would it be possible to TRIM the entity keywords when they are stored ?

**Comment by patapizza** [comment]
This has been fixed.

**Comment by bmcclenahan** [comment]
Thanks !

On 28 Dec 2018, at 10:09 am, Julien Odent <notifications@github.com<mailto:notifications@github.com>> wrote:


This has been fixed.
