### ISSUE TITLE
Expressions in Inbox keep reappearing.

### ISSUE THREAD

**Issue by novan-p-simanjuntak** [wit-ai/wit#402]
I want to report a bug where after I validate some expressions in inbox, it keeps reappearing (even though I don't add any new expressions) after I press refresh button.
This is only happened for some entity (not all). When I go to understanding tab and click related entity, and see its list of expressions, the expressions are there.

I don't know how to reproduce the bug. But I can give the wit app link and the screenshot of some expressions in inbox that keeps reappearing.

I expect the correct behaviour is the expressions doesn't reappear after validated.

**Comment by lauraRuzicka** [comment]
I have the same problem last two weeks

**Comment by blandinw** [comment]
Thanks for your feedback and patience, this issue should now be fixed.
Once validated, the expressions should not come back in the inbox.
Please feel free to reopen.

**Comment by lauraRuzicka** [comment]
Hello, it is happening again. The messages keep reappearing.
