### ISSUE TITLE
Yes_no is always no

### ISSUE THREAD

**Issue by vinnie1234** [wit-ai/wit#403]
Hello,

I work now a few time with wit.ai, but still have 1 problem.

I’ve make a yes_no, but when I try it with the integrated bot he always use yes… This also is when I try it width Facebook Messenger directly!

When I try it in understanding he recognize yes and no.

I've add some screens.

![ja](https://cloud.githubusercontent.com/assets/10955777/23786996/2f7465b6-0570-11e7-87d4-146443c5d89b.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/10955777/23786999/2f7534aa-0570-11e7-9313-492fbafce297.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/10955777/23786998/2f74f1b6-0570-11e7-8c19-1b26164a6528.png)
![vraag1](https://cloud.githubusercontent.com/assets/10955777/23786995/2f740e72-0570-11e7-90e4-83b1353189f6.png)
![vraag2](https://cloud.githubusercontent.com/assets/10955777/23786997/2f74a878-0570-11e7-9cb6-dcfd2d9826df.png)

My bot is in dutch.
Can anyone help me to solve this problem?

**Comment by vinnie1234** [comment]
Fixed it. 

I had my yes/no search strategy on: trait/free-text/keywords and this has to be trait only

**Comment by vinnie1234** [comment]
I was to early...

When set it in trait he understand "Ja"(Yes). But when i want to learn the word "Nee" (No) he set it always on keyword + trait and then it wil no longer work.

**Comment by l5t** [comment]
You probably want to look at all the expressions you validated for this trait entity in the Understanding tab and make sure none of them highlights any part of the expressions

**Comment by vinnie1234** [comment]
Sorry for my late comment. The yes/no problem i've solved. (really dont know what I did but it works now)

Now I have almost the same problem with another entitie. So as you can see I want to use my coverage (WA, WA+ and All Risk). In Understanding its works perfectly, but like before in de bot not.

I've check all the other entities, but there is nothing special to see.  

![understanding2](https://cloud.githubusercontent.com/assets/10955777/23901148/3f254526-08bc-11e7-8f1e-01750b26a3ce.png)
![understanding1](https://cloud.githubusercontent.com/assets/10955777/23901146/3f219098-08bc-11e7-92ec-25cfcd44b012.png)
![coverageentity](https://cloud.githubusercontent.com/assets/10955777/23901147/3f21ddd2-08bc-11e7-8cc8-e3c755f63876.png)
![coverage](https://cloud.githubusercontent.com/assets/10955777/23901145/3f216082-08bc-11e7-8877-56cdf44c6532.png)
![understanding3](https://cloud.githubusercontent.com/assets/10955777/23901144/3f20f570-08bc-11e7-8fad-a0866844f952.png)
