### ISSUE TITLE
Bot suck in Training

### ISSUE THREAD

**Issue by roumeng** [wit-ai/wit#404]
Hi, my bot is stuck in training since few hours. It happened few times already.
Could you please tell me what goes wrong with my teaching and what to avoid ? 
https://wit.ai/roumengueorguiev/rentilabot/

Thank you in advance

**Comment by amitpaz** [comment]
+1

**Comment by Ufosek** [comment]
Same here :/ Maybe there should be a button to restart training - I saw that administrators sometimes restarted it for users with such problem.

**Comment by amitpaz** [comment]
I don't think it's a specific application issue IMHO (tried to upload and create a new app - all with the same result) I suspect there is some service malfunctioning which requires a restart.

It would be great if we had a page with the  upcoming / current status of services and upgrade / downtime notifications - this can eliminate much of our guess work

It would be really awesome if the team would detect and fix these kind of issues in a shorter duration ;)

**Comment by javimoya** [comment]
same problem here............. it's so unreliable....

**Comment by MathieuDuboy** [comment]
Same problem here : Training status : ongoing 
My app ID : https://wit.ai/mathieuduboy/monuments/stories

**Comment by nipek** [comment]
@l5t help me restart my bot, ongoing for hours
i have tried validating new stories but it cant, i cannot also delete new intent that might be causing this
https://wit.ai/nipek/Hep/stories
also maybe a restart button should be implemented

**Comment by l5t** [comment]
I restarted your training manually for those that shared your app url. Sorry for the inconvenience cc @blandinw

**Comment by Ufosek** [comment]
Please restart this also https://wit.ai/piotrufosszaciski/XchangerBotTest/stories

**Comment by amitpaz** [comment]
Please restart this: https://wit.ai/amitpaz/rest_demo_2_0_0/stories
10x

**Comment by gilles-bogaert** [comment]
I have the same problem here. I am not sure what is the solution. Could someone help? Thanks a lot.

**Comment by l5t** [comment]
Done

**Comment by rafaels88** [comment]
Hi, same here =)
https://wit.ai/luzvc-dev/Clara/stories
Thanks!

**Comment by tandracek** [comment]
Mine is stuck as well, thanks.
https://wit.ai/tandracek/WiscPOCV2/stories

**Comment by l5t** [comment]
just restarted

**Comment by mmerchant** [comment]
Mine is stuck as well -- https://wit.ai/mmerchant/test-aem 
Thank you!

**Comment by l5t** [comment]
voila

**Comment by MathieuDuboy** [comment]
Can you please restart my app https://wit.ai/mathieuduboy/WineBot/ 
Thank you !

**Comment by amit2k761** [comment]
@l5t Can you please restart for app id 204729828065842
