### ISSUE TITLE
Why is "merge" its own type in the converse API?

### ISSUE THREAD

**Issue by hactar** [wit-ai/wit#405]
The documentation for type states:

> The type of the bot response. Either merge (first bot **action** after a user message), msg (the bot has something to say), action (the bot has something to do) or stop (the bot is waiting to proceed).

and

> merge means that you need to execute the merge **action**;

Is there a reason why merge is its own type? To me merge could simply also be an action with the name "merge", removing this type altogether (action, msg and stop would remain) and so reducing complexity.

I've successfully created stories which never appear to call merge at all, https://wit.ai/hactar/ConverseTest, instead the action I define in the story is called, which is what I expect to happen. This makes this merge type even more confusing, because it is not necessarily the first bot action after a user message as the documentation suggests.

**Comment by l5t** [comment]
Spot on. We initially made `merge` special but now it is simply an action like any other. We should update the doc to reflect this. Good catch

**Comment by hactar** [comment]
Closing as stories are deprecated ;).
