### ISSUE TITLE
I can't save new stories

### ISSUE THREAD

**Issue by javimoya** [wit-ai/wit#406]
Currently is impossible to create new stories. When I click "Save Story" always fails.
I have created a new app, with the simplest story possible and fails.
thanks

**Comment by MathieuDuboy** [comment]
Same problem. Wit as serious issues right now. I hope they will be fixed very soon.

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
