### ISSUE TITLE
Down?

### ISSUE THREAD

**Issue by mvcmania** [wit-ai/wit#407]
Can not create a story, can not update bookmarks, can not training, we are stuck at the middle of the challenge.

**Comment by individual11** [comment]
in the same boat. can't validate any understanding.

**Comment by Cpz6942** [comment]
Mine is down aswell.

**Comment by patapizza** [comment]
We're experiencing issues, will update when we're back up. Sorry about that!

**Comment by tpizzle** [comment]
I'm unable to log in

**Comment by patapizza** [comment]
We should be back up.
