### ISSUE TITLE
Can I flag profanity?

### ISSUE THREAD

**Issue by jogarret1** [wit-ai/wit#409]
I have a quick question (love the platform)

Is there a way to provide the AI with a list of curse words that if seen, would immediately return a different intent?

I can train it with the words I suppose, however is that the best way if I'm using trait instead of keywords for my intent?

Thanks!

**Comment by hactar** [comment]
In my apps I usually have a separate intent called insult for this instead of picking out individual words in a keyword list. Sentenced by users are marked intent=insult, and my bot responds with a witty message accordingly.

**Comment by jogarret1** [comment]
Good call.



-------- Original message --------

**Comment by marexv** [comment]
@hactar Could this be a new wit entity? Something line **wit/insult**?

**Comment by hactar** [comment]
@marexv I'm not actually part of the wit team, just a "veteran" user. Yes, I think it could make a good official entity, but someone from wit would have to give you an official response :).

**Comment by marexv** [comment]
Thank you @hactar! I will read all the suggestions and open a new one if there isn't something going on already :)

**Comment by patapizza** [comment]
@jogarret1 @marexv Using a trait entity is the way to go here. No current plans for `wit/insult`.
