### ISSUE TITLE
Can I upload a  bulk training data.

### ISSUE THREAD

**Issue by manikandan-velu** [wit-ai/wit#410]
I want to upload a training data set in .json fromat that contains the intents and entities of each utterances. How can I bulk upload that data to train my Wit.ai app

**Comment by Joinfield** [comment]
Great idea, like ibm watson. Or like the initial setup of an app. Or just to import trained/learned data from another app into production app.

**Comment by KJlmfe** [comment]
Also, I really need this feature.

**Comment by captainjackrana** [comment]
when can we have this feature ? Its already there on Api.ai but their NLP parser isnt very good.

**Comment by l5t** [comment]
While we don't have yet a nice UI to do it, yo should be able to do this via the API ( /samples)
Example here: https://github.com/wit-ai/wit-api-only-tutorial#train-with-existing-data

**Comment by AVimmerse** [comment]
Is there an update on this process, as I want to upload data to train my ai?  I've searched for videos and pages on the process, but as a non-programmer there are knowledge gaps I am trying to fill.  Trying to follow along with the tutorial: https://github.com/wit-ai/wit-api-only-tutorial

Thanks
