### ISSUE TITLE
Cannot return Action Function Value from API

### ISSUE THREAD

**Issue by MohammedMagdi** [wit-ai/wit#411]
the user enter for example "i want 5 balls"
my action "sure, you want {number} balls"
i return the expected value in wit.ai website but when use APIs or postman it return msg "sure, you want   balls" but cannot get the value of {number}
any help please !?

**Comment by magnusburton** [comment]
Are you adding `number` to your context?

**Comment by MohammedMagdi** [comment]
no, but the value returned in "entities" with the msg not in the msg,
do i have to send the value from entities again to be returned in the msg
excuse me i'm confused about this

**Comment by magnusburton** [comment]
@MohammedMagdi to use the placeholder function (that is; showing a value inside `brackets { }`) you need to add the value to your context. 

See [this](https://wit.ai/docs/quickstart) for more info and an example that would help you.

**Comment by MohammedMagdi** [comment]
@magnusburton i understand i need to send value with context like in weather example,
but in my case all values i already send at first time and suppose wit return back the whole msg this what i don't understand !! 
thanks

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
