### ISSUE TITLE
understanding new numbers or words in arabic

### ISSUE THREAD

**Issue by MohammedMagdi** [wit-ai/wit#414]
how i add new numbers and words to the dictionary !?

**Comment by blandinw** [comment]
Please provide more context as to what you're trying to do.
Did you try extracting numbers with wit/number? What words/dictionary are you talking about?
Reopen with more info, thanks.

**Comment by MohammedMagdi** [comment]
i want to add some arabic slang words which maybe number or common word 
is there anyway !?
thanks
