### ISSUE TITLE
Trouble importing app through zip

### ISSUE THREAD

**Issue by swapkh91** [wit-ai/wit#417]
I exported an app which created, decompressed it and made some changes in intent.json. Then I compressed the folder again and I'm trying to import the zip file but it is stuck at 'We are creating your instance. Please do not refresh' for the past 10-15mins. I've attached the app.json screenshot.
What could be wrong?

![app](https://cloud.githubusercontent.com/assets/5755405/24030699/521383ec-0b04-11e7-8f58-e978cf463748.PNG)

**Comment by JoabMendes** [comment]
+1

**Comment by jtliao** [comment]
Merge with #513
