### ISSUE TITLE
Bookmarks getting reset

### ISSUE THREAD

**Issue by swapkh91** [wit-ai/wit#418]
All the bookmark names have disappeared from the stories.

**Comment by Godoy** [comment]
Same here :(

**Comment by tpizzle** [comment]
Not to be whiny, but this bookmark thing seems to be getting worse and worse. I literally lost about 60% of my bookmarks today and my application basically fell apart because of it. It's pretty difficult just because half my logic may fall apart at any second!

**Comment by joinworldtv** [comment]
Same here...

**Comment by adinhodovic** [comment]
I'm still having a issue with this... Any updates on bug fixes?

**Comment by mashedkeyboard** [comment]
Also having this issue.

**Comment by henriquenogueira** [comment]
I am also facing this issue.

**Comment by blandinw** [comment]
Can anyone give steps to reproduce this issue?

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
