### ISSUE TITLE
Story to long? *bug*

### ISSUE THREAD

**Issue by vinnie1234** [wit-ai/wit#419]
Hello,

I'm not absolutly sure if this the right problem, but it looks like it.

I've add 2 screen witch my story. My last question is: "Ben jij een man of een vrouw?".
The response of the user in this case is "man".
The first thing after will work correct (in this case SaveGender, but when i change it in anything else it works fine) but after that he return in a loop and go back to "Ben jij een man of een vrouw". 

The story I want is an lot longer.

* I've test this is different apps but the result is always the same on the same place!
![screenshot_5](https://cloud.githubusercontent.com/assets/10955777/24035041/1acd5940-0af4-11e7-8c72-c42a7a4d0dea.png)
![screenshot_6](https://cloud.githubusercontent.com/assets/10955777/24035040/1acd3ca8-0af4-11e7-8f2d-baeb5a0ec844.png)

https://wit.ai/vincentmaarschalkerweerd/test

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
