### ISSUE TITLE
one of my apps is always training - never goes green

### ISSUE THREAD

**Issue by bmcclenahan** [wit-ai/wit#420]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
my app is always dirty - continually training

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
it would go green

**Comment by patapizza** [comment]
What is your app?

**Comment by bmcclenahan** [comment]
thanks


https://wit.ai/brucemcclenahan/churchbot/inbox/semantic



________________________________

**Comment by individual11** [comment]
mine is doing it as well.

**Comment by l5t** [comment]
what's your Wit app URL?

**Comment by l5t** [comment]
@bmcclenahan just restarted

**Comment by bmcclenahan** [comment]
that's great - thanks !


it's learning again


________________________________

**Comment by blandinw** [comment]
Closing, please reopen this issue if needed

**Comment by bmcclenahan** [comment]
thanks !


________________________________
