### ISSUE TITLE
how to handle app users in different timezones

### ISSUE THREAD

**Issue by bmcclenahan** [wit-ai/wit#422]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
I have a question - what is the recommended way to deal with app users in different timezones
**What is the current behavior?**
the context parameter used to allow timezones to be included in queries but the docs say this has been deprecated
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Comment by blandinw** [comment]
You're right that context.timezone is the way to go. We may need to update the docs.
Where did you see the context.timezone parameter marked as being deprecated?

**Comment by bmcclenahan** [comment]
Thanks - that is good to hear

I may have misinterpreted this sentence in the HTTP API doc ...

State is only available for older apps without Stories and is deprecated for current Wit apps.

On 22 Mar 2017, at 4:32 am, Willy Blandin <notifications@github.com<mailto:notifications@github.com>> wrote:


You're right that context.timezone is the way to go. We may need to update the docs.
Where did you see the context.timezone parameter marked as being deprecated?

**Comment by bmcclenahan** [comment]
Actually I spoke to soon.

The deprecated reference is



________________________________

**Comment by bmcclenahan** [comment]
actually I spoke too soon


the reference to deprecated is in the HTTP API docs ...

Arguments
name    required        type    doc
q       required        string  User’s query. Length must be > 0 and < 256
context optional        context object (JSON)   Context (deprecated)<https://wit.ai/docs/http/20160526#context-(deprecated)-link>
Could you help me explain what this means ?
is it that passing context as a parameter is deprecated ?
In which case how do I pass it - is POST supported for q queries ?

thanks
Bruce

________________________________

**Comment by bmcclenahan** [comment]
ok, looks like passing timezone in context as a query parameter works so not sure what the deprecated reference is about - maybe to an old section of the document ?


next question : the doc refers to a reference on Canonical IDs for timezones.

This reference implies that timezones like "GMT+10:00" should be valid.

Wit throws an error when I use this format - is it not supported ?

Facebook messenger just gives a timezone number as part of the user profile (+10) so supporting the GMT format would be convenient in some cases


thanks

Bruce


________________________________

**Comment by l5t** [comment]
Closing: https://wit.ai/blog/2017/10/23/locale-support-for-dates-and-times
