### ISSUE TITLE
BUG: `quickstart` link in settings page is broken

### ISSUE THREAD

**Issue by nodtem66** [wit-ai/wit#423]
***BUG***

**What is the current behavior?**
the target url is `https://wit.ai/.../.../function%20(t)%7Breturn%20this.wit_base_url+t%7D/docs/quickstart`

**What is the expected behavior?**
`https://wit.ai/docs/quickstart`

** Step to reproduce **
1. Enter ***Settings*** page for the project
2. Go to ***API Details*** section
3. Click on ***quickstart*** link

![image](https://cloud.githubusercontent.com/assets/220425/24072595/0c4ab93e-0c1c-11e7-9b77-013e97a7b886.png)

**Comment by stopachka** [comment]
Indeed, we're on it!

**Comment by stopachka** [comment]
the fix is in prod!
