### ISSUE TITLE
Question about conflicting stories

### ISSUE THREAD

**Issue by buritica** [wit-ai/wit#424]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
*Question* about my specific wit implementation, not sure if `bug` or my fault

**Context**
Given two stories for my bot (out of several):
- Story one responds to greeting intent
- Story two responds to help intent

**What is the current behavior?**

Bot replies to both intents (help, greeting) with help story. (hola -> greeting, ayuda -> help)

<img width="301" alt="screen shot 2017-03-19 at 4 44 50 pm" src="https://cloud.githubusercontent.com/assets/228120/24084612/846884b2-0cc3-11e7-95f4-e45126dc1276.png">

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

It seems like I have a bug in my training data. I have completely deleted these two intents, their training data, the stories and set them up again, to no avail. But if I set identical stories in a clean app I get the correct behavior

**What is the expected behavior?**

Bot responds correctly to greeting and help intents, you can see an [example here](https://wit.ai/buritica/help-hello/stories)

<img width="298" alt="screen shot 2017-03-19 at 4 48 43 pm" src="https://cloud.githubusercontent.com/assets/228120/24084627/f823c060-0cc3-11e7-9769-e3a5f8582305.png">

I already have some fairly complex stories that work pretty well, and I'd prefer not to start from scratch for this conflict. I already did with a past one and it was not fun. 

Do you have any ideas on how I may solve this issue?

**Comment by buritica** [comment]
Ok, so I've been able to reproduce this:

- I created a new app with a backup of my existing app
- removed all stories, entities and actions to see if I could identify the culprit
- I was left with a barebones app, 2 stories, 2 entities. help, greeting

Problem is still there, but in this case, the default response is for greeting and not for help

<img width="298" alt="screen shot 2017-03-19 at 5 35 08 pm" src="https://cloud.githubusercontent.com/assets/228120/24084988/77e0095c-0cca-11e7-821e-a3aa3c495505.png">

This can now be reproduced in https://wit.ai/buritica/help-hello-bug/stories

**Comment by buritica** [comment]
Here's some last info, after cleaning all the expressions and reducing that app I can see a conflict come up, and would appreciate any help on how I should deal with these kind of use cases.

https://wit.ai/buritica/help-hello-again/stories

Thanks so much!

**Comment by l5t** [comment]
![image](https://cloud.githubusercontent.com/assets/6992759/24088122/e4a49878-0ce3-11e7-80ec-5ba0a9eee90b.png)
There seems to be an issue with your intent entity. It should be trait only (not freetext/keyword).

Only trait entities (like typically intent) have their value influence the action prediction. For non-trait entities, the value is ignored with regards to action prediction.

So please click on the trait strategy and make sure your intent is a trait entity

**Comment by buritica** [comment]
thanks @l5t, I tried that but it went back to this :/

**Comment by l5t** [comment]
I'm closing as I think you got it work. If this happens again, it means you highlighted some part of one or few expressions for this entity.
