### ISSUE TITLE
how to generate a new session_id?

### ISSUE THREAD

**Issue by swapkh91** [wit-ai/wit#425]
I'm getting confused as to how to generate a new session_id
I have an `intent` with value `greeting`. So I want to start a new session whenever the user sends a 'hi' or related string.
I'm using node.js

**Comment by patapizza** [comment]
Hi @swapkh91, so the session-id needs to be generated on your side.
For example, you can do it with `node-uuid`, or based on the current time (e.g. https://github.com/wit-ai/node-wit/blob/master/examples/messenger.js#L97), or a custom value that you increment...
In the Wit.ai console, you can set a story starting with a `greeting` value for `intent` and run a custom action that would generate that session id (e.g. `genNewSessionId`).
Hope this helps.

**Comment by swapkh91** [comment]
It helped, thanks :)
