### ISSUE TITLE
wit.ai returns {"body":"wit the hell?"}

### ISSUE THREAD

**Issue by mwinje** [wit-ai/wit#426]
I have just created a public App in wit.ai platform and called it WapiActual. I have followed the 'quick start' tutorial in creating Stories,and I have taught the app to process simple conversations.I have tested it by chatting with a visual bot in the platform.
Now when I try to test it from Cloud9 terminal using the command:
curl \
 -H 'Authorization: Bearer MY_TOKEN' \
 'https://api.wit.ai/message?v=20170320&q=Where can find restaurants?'
wit.ai always replies with the response: {"body":"wit the hell?"}
This is very frustrating,I don't know if its a bug or if there is something I am not doing right.I've searched this but I can't find a single issue similar to this.
The main issue here is I'm having problems integrating wit.ai to my php web application,I can't even test it.

**Comment by l5t** [comment]
You need to URL encode the query parameter. Space should be %20 for example

**Comment by mwinje** [comment]
Thanx very much,I will try
