### ISSUE TITLE
Page scroll disappears on Understanding page

### ISSUE THREAD

**Issue by swapkh91** [wit-ai/wit#427]
When I click on `Edit Metadata` on any of the trait values in the Understanding tab, a dialog box slides down and after closing it the page scroll disappears.

**Comment by stopachka** [comment]
Indeed, I can repro two things: 

1. open a modal
2. close it by clicking away
3. try to reopen the modal
ERR: see that it does not open up

1. open a modal
2. type {}
3. save it
ERR: see that you can't scroll anymore

Thanks for reporting @swapkh91! We're on it

**Comment by stopachka** [comment]
the fix is in prod!
