### ISSUE TITLE
400 Error Being Returned For Messages Over 256 Characters

### ISSUE THREAD

**Issue by JackBarmby** [wit-ai/wit#428]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
*bug*
**What is the current behavior?**
Messages over 256 characters are returning a 400 error (screenshot attached) 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Send any message that is over 256 characters long
**What is the expected behavior?**
It will process the message and return the expected response. 

![image](https://cloud.githubusercontent.com/assets/3406030/24140901/91423a6e-0e19-11e7-8367-66abce063356.png)

**Comment by blandinw** [comment]
This is intended to avoid abuse.

**Comment by JackBarmby** [comment]
Ok - that seems quite restrictive - are there any plans to change this?

**Comment by blandinw** [comment]
Yes! We'd like to get rid of this limit or at least make it way higher. We'll reconsider this once we complete our re-architecturing project, but we cannot provide any guarantees/ETA. In the meantime, the workaround is to split the message into chunks of 256 or less chars.
