### ISSUE TITLE
Search in Sites and get results

### ISSUE THREAD

**Issue by Aravind-WMG** [wit-ai/wit#430]
I would like to know whether this scenario can be handled using wit.

Suppose a user type for news, wit should get the latest beaking news from any channell site like BBC and show to user.

Please let know Whether this can be done.If yes, please guide me.

Thanks !

**Comment by swapkh91** [comment]
Sure its possible. Its just like the quickstart guide where you have to use a weather api to get results.

https://newsapi.org/

This is an api you can use to get news results and display the same using a variable in context. Read through the api to know what all request parameters are handled
