### ISSUE TITLE
Provide a way to download logs.

### ISSUE THREAD

**Issue by jbeuckm** [wit-ai/wit#431]
*feature*

We need the ability to download eg. a text file of all the conversations that have been handled by our app.

**Comment by hactar** [comment]
If you hit the backup button in your app you'll find an expressions.json file with these. If you need more you could always track what you send to wit and what you get from wit in your own app/backend?

**Comment by jbeuckm** [comment]
expressions.json does not provide the information from the logs tab.

**Comment by flogaribal** [comment]
Hi, 
Is there a way now to download logs from an app ? 
I really need them to do some statistics and improve our chatbot understanding.
Thanks in advance !

**Comment by stopachka** [comment]
Hey @flogaribal 

Could something like this work for you for now? 
- In your app, anytime you make a request -- log the output with either some logging library, or a file

**Comment by flogaribal** [comment]
Hey @stopachka !
Yes it could for the future logs/interactions but can you give me the old logs to be able to do statistics without waiting to have enough information with the new one.
Thanks in advance 
Florian

**Comment by patapizza** [comment]
Hi @jbeuckm @flogaribal, just to confirm: do you need the text, the context and the API response?

**Comment by flogaribal** [comment]
Hi @patapizza,
I would like to know if you have any updates about this ? 
Could you be able to send me our logs by email while waiting for a concrete feature to be developed ? 
Thanks a lot in advance

**Comment by patapizza** [comment]
Hi @flogaribal,
We've prioritized this and should get working on this soon.

**Comment by flogaribal** [comment]
Ok that's perfect ! Thanks a lot

**Comment by flogaribal** [comment]
Hi @patapizza,
As our project about statistics and improvement of our entities is starting very soon, I was wondering if you have any idea about the release date of this functionality or if you can send me our logs by email while it is being developed ? 
Thanks a lot in advance, it would save us!

**Comment by patapizza** [comment]
Hi @flogaribal, we won't be able to open up this soon enough. What is your email address?

**Comment by flogaribal** [comment]
Ok no problem!
My email address flo.garibal[a t]gmail .com

**Comment by patapizza** [comment]
Sent.

**Comment by flogaribal** [comment]
Received! Thanks a lot!

**Comment by nadirio** [comment]
Hi @flogaribal (since you received the logs), @patapizza,

Do the logs contain the HTTP request details / the request URI of requests to `/message`? I need it for debugging, and the current view of the logs is pretty limited to message only.

**Comment by serdalbayram** [comment]
Dear Colleagues, is there any update or planned release date about this enhancement?

**Comment by terryds** [comment]
I really need this feature. Hope there are updates coming soon

**Comment by jtliao** [comment]
Logs will be deprecated in the near future. It's recommended to implement on the client side, it should be very simple.
