### ISSUE TITLE
Does having multiple 'stop' response in a story by design?  How can I tell if a story has ended?

### ISSUE THREAD

**Issue by ronaldyang** [wit-ai/wit#432]
I always get a 'stop' type response if the previous response is 'msg', even when I am requesting with user's next input message. The story keeps flowing if I request again with the user's input message and use the same sessionId. But these 'stop' responses in mid of the story makes me confused when the story really ends and when I should clear the sessionId. 
Q: 
Does having multiple 'stop' in a story by design?
Is one sessionId supposed to be corresponding to one story or a user?
How can I tell if a story has ended?

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
