### ISSUE TITLE
Conflict between user branches

### ISSUE THREAD

**Issue by annikahanna** [wit-ai/wit#433]
I made a  yes_no, but the no-bot response shows me that it has a conflict with the yes-bot response

![unbenannt](https://cloud.githubusercontent.com/assets/26456904/24247224/1daf2f54-0fcb-11e7-903c-a32c5a2c131f.PNG)
![unbenannt1](https://cloud.githubusercontent.com/assets/26456904/24247280/5730b7a2-0fcb-11e7-8e39-eeb8ffab4cc9.PNG)

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
