### ISSUE TITLE
Mismatching wit/location and local_search_query

### ISSUE THREAD

**Issue by miriamhallongren** [wit-ai/wit#434]
The app fails to recognize locations as _wit/location_, instead it validates to _local_search_query_.

After manual correction and validation, it still thinks e.g. "Amsterdam" is a _local_search_query_. When a longer sentence is given, and e.g. when an _intent_ is also recognized, the app recognizes "Amsterdam" as a _wit/location_. 

The app has been trained and fed with a lot of expressions and it used to work without any problem.

**Is this a bug?** Feedback or help is much appreciated. Thanks in advance!

User: MHGGH
App name: 21-Feb-Intent-Experiment-Clean

**Comment by dimitridewit** [comment]
Any progress in this?

**Comment by MHGGH** [comment]
@patapizza hi there, our Chatbot is still broken since half March. We would really appreciate it to hear about the status of this but. Thanks!

**Comment by MHGGH** [comment]
@patapizza Can you please inform us on the status of this bug? We're organising a Dutch ChatBot event at the Facebook office, would be weird then if the ChatBot is still broken because of this bug

**Comment by exquisiteboy** [comment]
location is mismatching when used withing sentences like which country Islamabad is city of ? it matches to the entire sentence as is and doesn't extract the location from it.correcting also doesn't seems to be working .

**Comment by patapizza** [comment]
Hi @miriamhallongren @dimitridewit @MHGGH @exquisiteboy,

Sorry for the latency here.

For the few examples I've tried, it looks like `Amsterdam` is recognized as a `wit/location`.
Can you share a few examples that don't work?

@exquisiteboy: Got it, we'll need to fix `wit/local_search_query`.

**Comment by exquisiteboy** [comment]
Which country has Islamabad as city?
Not getting recognized as wit/location although if I change the position of
Islamabad to the start of the sentence like
Islamabad is city of ?
then it is recognized correctly wit/location

**Comment by blandinw** [comment]
Wow, apologies for the inconvenience and late answers here @miriamhallongren @dimitridewit @MHGGH.

It sounds like wit/location is fixed for Amsterdam, please comment in this issue if there's any other problem with it, by providing **full** example sentences.

Also, please don't use `wit/local_search_query` if it does not suit your needs, especially if it takes over other entities.

**Comment by patapizza** [comment]
@exquisiteboy "Which country has Islamabad as city?" now shows `Islamabad` as a `wit/location`.
