### ISSUE TITLE
Ending time of a duration of datetime entity

### ISSUE THREAD

**Issue by aradhyamathur** [wit-ai/wit#435]
I lately found that the case in which we send a duration to Datetime in wit. The start time that it detects is correct however it adds an hour to the end time of the duration.
Is it a bug or a functionality ?
I have attached the screenshot below.
for the time 1-2 pm it shows 1:00 to 3:00 pm
![wit_time_duration](https://cloud.githubusercontent.com/assets/6674956/24286035/2a1f626c-1099-11e7-8f5f-eec0df27309e.png)

**Comment by l5t** [comment]
This is the normal though debatable behavior. As for the interval, we decided to always have an exclusive upper limit. So if you say "this weekend" the API will give you:
From: Friday, 9 January 2015 at 18:00:00 +0000 (UTC)
To: Monday, 12 January 2015 at 0:00:00 +0000 (UTC)
We may change this in the future as we've received a lot of feedback on this. There is a "grain" field that should help you infer the inclusive upper limit.

**Comment by tanisha96** [comment]
I want to extract start and end date-time from my bot.
Eg: "Send me data for today." -> must detect
Start-date_time = 2017-6-29 00:00:000
End-date_time = 2017-6-29 23:59:59

How do I go about this?

**Comment by l5t** [comment]
You add wit/datetime to your app and validate an expression: https://wit.ai/docs/recipes#extract-date-and-time
