### ISSUE TITLE
Queries frequently take over 30 seconds

### ISSUE THREAD

**Issue by hactar** [wit-ai/wit#436]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
Wit queries usually take about 4 seconds to complete. But about **every 10th query** I send to wit (message API, but I see the same issue with the converse API) takes **over 30 seconds**, even it  is the exact same query I just sent.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Here are the stats from one of the queries.
<img width="547" alt="paw" src="https://cloud.githubusercontent.com/assets/645674/24304514/e605b2ae-10b9-11e7-852a-365e30e17469.png">
You can find the request I sent as well as the response I received here: https://paw.pt/ccUiRvju . The response is correct. The request is being sent to https://wit.ai/hactar/Wave%20German768c-43b

To reproduce, just keep sending this same request again and again, around 1/10 of the requests will come back after 30+ seconds.

**What is the expected behavior?**
Answers should not take longer than a few seconds.

**Comment by shameeriqbal** [comment]
Having same issue. Having a status page would help tremendously

**Comment by adinhodovic** [comment]
Same issues here. Hard to write tests because of it as well. Please implement a status page so you know what's going on and expected time it is fixed.

**Comment by erniedeferia** [comment]
Same issue here. Very slow response times (app https://wit.ai/erniedeferia/dokkumento)

**Comment by blandinw** [comment]
We noticed it too, we sincerely apologize for the inconvenience.
This is due to some people abusing the API and knocking over shards.
We're currently implementing fixes to avoid these issues until we migrate to our new architecture. Bear with us, this is definitely our top priority at the moment.

**Comment by hactar** [comment]
This appears to be fixed. Closing.
