### ISSUE TITLE
Feature request: handle timezones like GMT+10 in context

### ISSUE THREAD

**Issue by bmcclenahan** [wit-ai/wit#437]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question
**What is the current behavior?**
the timezone property in the context object states it must be a Canonical ID. 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
The documentation at the provided link describes timezone strings of the format GMT+10 or GMT+10:00 however these throw an error through the WIT API. 
**What is the expected behavior?**
It would be helpful if these formats were supported as the Facebook user profile returns a timezone number, (eg 10) not a name (eg Sydney) 
It there a format like GMT+10 that is supported ?
Could there be please ?

**Comment by blandinw** [comment]
Thanks for your feedback!

Where in the docs did you see that GMT+10 was allowed?

Wit expects either a UTC-formatted time (e.g. `2014-10-30T12:18:45-07:00`) or a timezone name (e.g. `America/Los_Angeles`). These names are supposed to follow [the tz database](https://en.wikipedia.org/wiki/Tz_database).

We might allow other formats later, but this is not our immediate priority.

**Comment by bmcclenahan** [comment]
There's a bit about timezone formats on the Java Timezone class site your docs refer to

here: http://docs.oracle.com/javase/6/docs/api/java/util/TimeZone.html


Yes, I could use the reference time as a roundabout way to achieve the same thing.


The key disconnect I saw is that the Facebook API provides the timezone as a number rather than a name, and it would be cleaner if parameters could pass more directly between them and you rather than having to reformat.


It's a bit like the disconnect on sound formats where facebook messenger supplies audio in a compressed format that your recogniser doesn't support, so again there's a reformat required to connect the two.


Just sayin' ....


Cheers

Bruce


________________________________

**Comment by bmcclenahan** [comment]
Indeed you were, then they bought you, and started directing people to Wit as their NL service provider [😊]

So, coming to Wit from Messenger as I did, and with that guidance from FB, it would be nice if things meshed cleanly.


I'd really like to use your speech API, but it's just too hard for me to do the format conversion.

You're not alone in this - every speech service I've looked at requires clean uncompressed audio. It's just that everything coming from users is compressed.


Thanks for getting back, and for considering it as a feature request.

Bruce



________________________________

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
