### ISSUE TITLE
values returned for builtin datetime entity

### ISSUE THREAD

**Issue by bmcclenahan** [wit-ai/wit#438]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question
**What is the current behavior?**
when the datetime entity returns values for "Sunday" there is a value property and a values array of 3 objects with values a week apart.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
what is the meaning of the array of 3 values ?
is there any documentation on the return values of the datetime entity ?

**What is the expected behavior?**

**Comment by Joinfield** [comment]
we use that array as an interval, if the user asks for "appointment on sunday" its not clear which sunday. if you ask "next sunday" it's clear. but maybe there is something special, let me know.

**Comment by patapizza** [comment]
As @Joinfield highlighted, time is often ambiguous. If there is not enough information in the input/context, the `values` array will provide up to the next 3 future occurrences.
