### ISSUE TITLE
Bug report: [wit] [converse] Error: Bad auth, check token/params

### ISSUE THREAD

**Issue by abhilashmurthy** [wit-ai/wit#439]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
Cannot connect to wit's converse API :( my bot's users are very sad

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Hit the converse api with any request and you will get this:
[wit] [converse] Error: Bad auth, check token/params

**What is the expected behavior?**
Should not show error

**Comment by joechoi-git** [comment]
I second this. We are seeing the same exact issue all of sudden since about 10 minutes ago.
Not all of the requests are failing... Happening about 80% of the requests.
We have not made any change to the token value in either wit.ai dashboard or our app.

0|index    | [wit] [message] Error: Bad auth, check token/params

**Comment by blandinw** [comment]
We're rolling back our latest push. Things should be better now.

**Comment by joechoi-git** [comment]
Thank you for the quick response on this. 

To work around this issue, I reset "server access token" from the app setting page and switched our app to use the new token value.

**Comment by blandinw** [comment]
To be transparent and give you more background, we're starting to migrate some components to our new infrastructure (cf. https://wit.ai/blog/2017/02/10/wit-community-update). The testing around migrating access tokens was not thorough enough and a bug wasn't caught early in our deployment.
