### ISSUE TITLE
MRCP interface

### ISSUE THREAD

**Issue by benlangfeld** [wit-ai/wit#44]
It would be excellent if Wit supported an MRCP interface, especially for those of us involved in telephony. The benefits of MRCP over your current API:

* Easy integration into telephony use cases
* Remote (wit end) audio endpointing, removing the necessity of energy detection from the client side.
* Possibility of recognition occurring prior to transmitting all audio

Is this something you guys have on the roadmap? Do you have any idea of when it might become available? Do you need assistance implementing it (those of us @MojoLingo might be able to lend a hand)?

**Comment by tm1000** [comment]
@benlangfeld 
Hey Ben! Let me know what you need resources wise. I'd like to check this out for FreePBX (using Asterisk as the telephony/PBX driver)

**Comment by benlangfeld** [comment]
It would need an engineer well versed in C who can commit a couple of weeks to this, @tm1000 :)

**Comment by zandermath** [comment]
Is anyone still following this up or was it abandoned? I work for a speech tech company called verbio www.verbio.com and am interested if this was ever worked on or if there was ever any success or was it abandoned after the acquisition?

**Comment by benlangfeld** [comment]
My above comments continue to be an accurate reflection of the progress of this issue.

**Comment by blandinw** [comment]
@benlangfeld do you think having an MRCP interface is still relevant for Wit?
It's not a priority for us, but I'm willing to leave this issue open to centralize the discussion.

**Comment by benlangfeld** [comment]
This is no longer a priority for me, either, and closing this fits with the same motivation for #45.
