### ISSUE TITLE
Intent/Story mismatching and Stories Training

### ISSUE THREAD

**Issue by froesmatheus** [wit-ai/wit#440]
I want to report a bug

Hi, I'm facing a weird bug in my Wit project. I have a couple of intents and each intent has it's own associated story. Sometimes when I say something, the bot is able to figure out the right intent but it's mismatching the story. Here's an example

I have a "consultarFaltas" intent. I've trained it and if I go to the "Understanding" tab, it correctly goes to the right intent

![capturar](https://cloud.githubusercontent.com/assets/8764566/24405890/cf445030-139c-11e7-8240-d5c1d6580406.PNG)

Here's the associated story

![capturar2](https://cloud.githubusercontent.com/assets/8764566/24405912/e24fbb24-139c-11e7-9aef-cbbb2442c71e.PNG)

Now here's what happen when I use the API or the Bot Chat in the right corner

![capturar3](https://cloud.githubusercontent.com/assets/8764566/24405935/f5830c96-139c-11e7-9b9f-95880363ef6b.PNG)

![capturar4](https://cloud.githubusercontent.com/assets/8764566/24405943/00d53448-139d-11e7-8c4c-5c577077b0f1.PNG)

Wit goes to a completely different story. It is able to match the intent with a high confidence but it's returning the wrong story.

Here's the intent that Wit is wrongly matching

![capturar5](https://cloud.githubusercontent.com/assets/8764566/24406048/574dd38e-139d-11e7-8c8c-c219e6e09eb5.PNG)

If I do the same thing and go to the "Understanding" tab here's what happen

![capturar6](https://cloud.githubusercontent.com/assets/8764566/24406281/4a45803c-139e-11e7-9f2c-0aa8f42776eb.PNG)

It matches the right intent. Here's the bot chat

![capturar7](https://cloud.githubusercontent.com/assets/8764566/24406322/6dd2599e-139e-11e7-9b25-a7e4b12d3123.PNG)

It matches the right story.

Do you guys have any plans to release the Inbox "Stories" tab? It would help a lot to fix these problems. Thanks

**Comment by tpizzle** [comment]
@patapizza I run into the same issue pretty often as well; what I usually do in that case is simply create a new entity of type `trait` that isn't called intent, but serves the same purpose. Afterwards, if I'm still running into the same issue, as a last resort, I can at least go to the "Actions" tab and exclude the `intent` entity for the action I want the bot to respond with.

**Comment by froesmatheus** [comment]
@tpizzle Interesting. Thanks for the tip!

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
