### ISSUE TITLE
How to USE FB messenger template on wit custom response

### ISSUE THREAD

**Issue by Aravind-WMG** [wit-ai/wit#441]
I was developing on bot and i would like to use fb messenger template on wit custom response. i find some suggstion on isssue #416 . But its not clear.Could some help on it. Code attached

Thanks !!!

[index.txt](https://github.com/wit-ai/wit/files/875892/index.txt)

**Comment by l5t** [comment]
Wittyfiddle is a great example: https://github.com/wit-ai/witty-fiddle. Alternatively you can look at this example: https://github.com/wit-ai/node-wit/blob/master/examples/messenger.js and the Messenger docs:https://developers.facebook.com/docs/messenger-platform/send-api-reference/button-template

**Comment by Aravind-WMG** [comment]
Hi @l5t  Thanks for the replay...

Here is my fiddle.

https://wit-ai.github.io/witty-fiddle/?id=98907fea0159955980cff71361e30d58

In fiddle it's showing correct response and on messenger it's not showing. I didnt deployed using Heroku but i modified my index.js file accordingly.

Could you please have a look in to it.

Thanks a ton !!!
[new 4.txt](https://github.com/wit-ai/wit/files/879534/new.4.txt)

**Comment by Aravind-WMG** [comment]
Hi @patapizza @l5t  

Could please have a look it the issue i mentioned above

Thanks !
