### ISSUE TITLE
Getting 404s in production

### ISSUE THREAD

**Issue by tpizzle** [wit-ai/wit#442]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
I'm getting 404s from my production instance. Tests are working fine, and I can hit the API in development

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Some of my stories are working (ones that don't hit an action on my back-end). So simple "Hello"s work, as well as some other basic responses. As soon as I need to hit my back-end to complete logic, I get 404s.

**What is the expected behavior?**

To continue with stories.

**Comment by blandinw** [comment]
Hi @tpizzle, we had a small outage that has been fixed in the meantime.
Thank you for your patience
