### ISSUE TITLE
Is Wit.ai down today? I keep getting--WitError: Wit responded with status: 500 (Internal Server Error). March 28, 2017

### ISSUE THREAD

**Issue by missdielle** [wit-ai/wit#443]
I'm getting WitError: Wit responded with status: 500 (Internal Server Error) consistently. Here's the whole error: 
C:\tfs2012\Redhawk\Tools\Python Testing Tools>speechrecwit.py [key] acct\part0.wav acct.txt
Traceback (most recent call last):
  File "C:\tfs2012\Redhawk\Tools\Python Testing Tools\speechrecwit.py", line 28, in <module>
    response = client.speech(wavFile, True, {'Content-Type':'audio/wav'} )
  File "C:\Python27\lib\site-packages\wit\wit.py", line 92, in speech
    data=audio_file, headers=headers)
  File "C:\Python27\lib\site-packages\wit\wit.py", line 34, in req
    ' (' + rsp.reason + ')')
wit.wit.WitError: Wit responded with status: 500 (Internal Server Error)

**Comment by patapizza** [comment]
Hey @missdielle we had a small outage which should be resolved by now.
Feel free to reopen if you still experience the issue.

**Comment by missdielle** [comment]
I just tried it again and am still getting the same error

**Comment by blandinw** [comment]
@missdielle can you try again?

**Comment by missdielle** [comment]
still not working....I've been commenting on #444...feel free to close one of these open tickets.

**Comment by missdielle** [comment]
ah, the other one's closed, I'll keep checking here. Thanks!
