### ISSUE TITLE
#443 re-open - Still getting 500 error

### ISSUE THREAD

**Issue by missdielle** [wit-ai/wit#444]
I wasn't sure if commenting on the closed issue reopens it or if I should do a new issue, so I'm doing both. I'm still getting the 500 error. This is the first day I'm trying to get this to work, so please let me know if it could be something I'm doing/sending. My coworker got this to work months ago and it's his key we're using (please let us know if it's expired, but I'm guessing it's working since we're getting the 500 error). Thanks in advance!!

Here is the entire error in case it helps:
C:\tfs2012\Redhawk\Tools\Python Testing Tools>speechrecwit.py [key] acct\part0.wav acct.txt
Traceback (most recent call last):
  File "C:\tfs2012\Redhawk\Tools\Python Testing Tools\speechrecwit.py", line 28, in <module>
    response = client.speech(wavFile, True, {'Content-Type':'audio/wav'} )
  File "C:\Python27\lib\site-packages\wit\wit.py", line 92, in speech
    data=audio_file, headers=headers)
  File "C:\Python27\lib\site-packages\wit\wit.py", line 34, in req
    ' (' + rsp.reason + ')')
wit.wit.WitError: Wit responded with status: 500 (Internal Server Error)

**Comment by missdielle** [comment]
also....if my wav file has dtmf tones from pressing buttons during a phone call, will those tones mess up the speech rec or can it handle those? (this is a future task, my wav file today is speech only)

**Comment by blandinw** [comment]
@missdielle You should definitely not post your access_token publicly...
You should also click the reopen button to reopen an old issue.

What is the link to the previous issue?
Can you confirm that the script is not working at the moment?

**Comment by missdielle** [comment]
ooo, good catch on the key (I forgot to delete it this time).

The issue is still happening as of 2:23pm 3/28.  My original issue is #443 at https://github.com/wit-ai/wit/issues/443

**Comment by missdielle** [comment]
I keep trying it and it's still not working. Last attempt was 3:16pm. Is there anything on my end I should be checking?

**Comment by missdielle** [comment]
Still not working as of 4:51pm.

**Comment by missdielle** [comment]
woohoo! it's working! Thank you for all your hard work behind the scenes, you all rock!

**Comment by missdielle** [comment]
nope, just kept trying the same command as I pasted above...it just started working all on it's own

**Comment by missdielle** [comment]
our company upped it's network security a few weeks ago and have been having weird issues with our emails not getting received even by people who have us white-listed....I suppose something could have been getting in the way on our end. (I'm a programmer, not a network or IT person, so I really don't know)

**Comment by blandinw** [comment]
OK, do you know your app-id or wit.ai URL so that we can check if something was wrong on our side? I'll close the issue since it seems to be fixed

**Comment by missdielle** [comment]
I'll have to ask my co-worker who wrote the code since it was his account
that we used the key from. The name of the program is speechrecwit.py and
the owner of the account is Andy Waxman in case that helps. I'll get more
details tomorrow. Thanks again!

On Mar 28, 2017 5:45 PM, "Willy Blandin" <notifications@github.com> wrote:

OK, do you know your app-id or wit.ai URL so that we can check if something
was wrong on our side? I'll close the issue since it seems to be fixed

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/wit-ai/wit/issues/444#issuecomment-289948233>, or mute
the thread

**Comment by missdielle** [comment]
Andy said to tell you we were just using the python client...does that help?
