### ISSUE TITLE
Same bug as yesterday - [wit] [converse] Error: Bad auth, check token/params

### ISSUE THREAD

**Issue by abhilashmurthy** [wit-ai/wit#445]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
I get a bad auth check token/params when I hit the converse API

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Same as yesterday: https://github.com/wit-ai/wit/issues/439

**What is the expected behavior?**
Same as yesterday: https://github.com/wit-ai/wit/issues/439

Thanks for fixing this so quick yesterday guys :) appreciate the quick reverts.

**Comment by girijan** [comment]
Please retry now; should be working!

**Comment by danielkhan** [comment]
I'm experiencing the same bug today every few requests.
