### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by dhalai** [wit-ai/wit#446]
Hi, guys! 
Something goes wrong with one of my apps. I can do nothing with it, each request returns 500 error with the response `Something went wrong. We've been notified.`. It's been started since yesterday. Whereas, others apps are working fine. Could you give me some details about it?
BTW, are you planning to have a status page?

**Comment by patapizza** [comment]
Hey dhalai what is your app and which endpoint are you hitting?

**Comment by blandinw** [comment]
We're planning to have a status page at some point later, we are working and higher priority features/scaling effort

**Comment by dhalai** [comment]
Hi @patapizza. It's all about https://api.wit.ai/sync. I have a private app called `cherrie_eng` and I can't even delete it.

**Comment by patapizza** [comment]
@dhalai Sorry for the latency here.
Feel free to reopen and provide your app id if you still experience the issue.
