### ISSUE TITLE
Correct action not fired

### ISSUE THREAD

**Issue by swapkh91** [wit-ai/wit#447]
My bot is showing unusual behavior by firing an incorrect action.
Link - https://wit.ai/swapkh91/OMDB/stories

Just try chatting with the bot, starting with a 'Hi'. You will see what the behavior is.

I'm not able to understand what is happening. Any help would be appreciated.

P.S. I'm still new to Wit, so maybe its a silly mistake

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
