### ISSUE TITLE
Destroy App - No Feedback from UI

### ISSUE THREAD

**Issue by hactar** [wit-ai/wit#448]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
If you click "destroy app" in wit.ai to destroy an app, the UI asks you to confirm. If you confirm the dialog disappears, but nothing else appears to happen, you are still within the destroyed story, and if you go back to the main menu the story is still listed an accessible. 

After a few minutes though, the app does disappear, so destroy does seem to work, just delayed and with no feedback that it will work.

**Comment by blandinw** [comment]
Probably low-pri given our current roadmap, putting it on your radar @stopachka

**Comment by ivgenyk** [comment]
I have also encountered this behavior, it was really unclear if the app was deleted or not. Tried to repeat the action several times until I saw the app disappear finally.
