### ISSUE TITLE
Open-source compilation of instances into Pocketsphinx language model

### ISSUE THREAD

**Issue by benlangfeld** [wit-ai/wit#45]
You guys [provide an API for exporting the instance corpus](https://wit.ai/docs/api#toc_17), and suggest that this could be used to build a Pocketsphinx language model, should the user not wish to make use of your provided recognizer (see also #44).

It would be extra useful if you could release the tools you guys use to build language models for your recognizer, such that this could more readily be reproduced client-side.

**Comment by martinraison** [comment]
Hi, apologies for the very late reply and lack of updates. We haven't had time to work on this recently. With the recent release of Bot Engine, we decided to focus our efforts more on the semantic analysis and dialogue parts of Wit.ai rather than the speech recognition.
