### ISSUE TITLE
question: how to remember entity until end of conversation

### ISSUE THREAD

**Issue by diegolopezcdm** [wit-ai/wit#450]
I am working on a wit conversation and I have a question.

In the first user message, I got a entity that need to be remember until end of conversation. How do I achieve this? any idea.

I already tried with merge action without sucess. I also already search for a similar thread like https://github.com/wit-ai/wit/issues/239 but I did not get a solution

![screen shot 2017-03-29 at 2 02 03 pm](https://cloud.githubusercontent.com/assets/10872882/24477743/d0bbb370-149d-11e7-8f7d-29334cfe139d.png)
![screen shot 2017-03-29 at 2 01 54 pm](https://cloud.githubusercontent.com/assets/10872882/24477746/d22969aa-149d-11e7-881d-9364f06933a0.png)

**Comment by blandinw** [comment]
You should have a mapping from session ID to conversation state somewhere in your code.
Simplest in JS would be to have a global object, used something like that:
```
var states = {};
// your code to handle the message and Wit's interaction [...]
states[session_id] = {"location": mylocation};
```

You can look at how the `sessions` object is used here: https://github.com/wit-ai/node-wit/blob/master/examples/messenger.js#L84

**Comment by diegolopezcdm** [comment]
thanks
