### ISSUE TITLE
wss://api.wit.ai/speech_ws giving 301 error

### ISSUE THREAD

**Issue by skokenes** [wit-ai/wit#451]
Hi, I am using a websocket connection over wss://api.wit.ai/speech_ws to send audio samples to my app and get intent back. That url is now giving me a 301 error. Has this endpoint been moved to a new location?

**Comment by blandinw** [comment]
This is a known issue. Basically, we didn't expect the `ws` library not to follow redirects as we moved our infra to a more scalable architecture. We unfortunately don't have any other way to deal with this but ask people to upgrade their code.
We offer a workaround and a fix at https://github.com/wit-ai/microphone/issues/15.
