### ISSUE TITLE
Writing an immediate response before action deletes entity

### ISSUE THREAD

**Issue by tpizzle** [wit-ai/wit#452]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
I have a story where I apply some custom logic based off a URL the user submits. It's the only entity that's usually present, and it has been working fine for some time. However, the back-end logic can take some time to process depending on what kind of website I'm analyzing. Whenever I add a "Please wait" message _before_ running my action, the entities disappear and I have no URL to analyze. I've written a test that checks that the method works when there is no pre-action message, so I'm confused why just adding a simple message deletes everything.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Add a story that depends on a non-trait entity, and run an action that uses this entity. Then, add a message before the action. See that the entity is (or is not) there.

**What is the expected behavior?**

I would still have the entity for the back-end logic

**Comment by swapkh91** [comment]
A workaround can be

- user enters URL
- bot executes action storeURL(). Here you can store the URL in `url` variable in context object at your back-end.
- update context keys with `url`
- bot sends 'Please wait'
- bot executes processURL(). Here you have the `url` in context.

**Comment by tpizzle** [comment]
@swapkh91 that's very helpful, thank you!

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
