### ISSUE TITLE
Wit-ios-sdk: cocoapods trunk needs update

### ISSUE THREAD

**Issue by hactar** [wit-ai/wit#454]
The 4.2.0 release of the wit-ios-sdk needs a push to the cocoapods trunk. Please either add me to the owners by running `pod trunk add-owner Wit my-email-which-you-have-on-file` or update yourself by:

1. Cloning https://github.com/wit-ai/wit-ios-sdk.git
1. `cd wit-ios-sdk`
1. `pod trunk push`

**Comment by blandinw** [comment]
In progress, will close when done.
I also added you as a contributor!

**Comment by blandinw** [comment]
@hactar looks like I'm missing some Xcode utils, I'll let you update the spec

**Comment by hactar** [comment]
Perfect, done, thanks.
