### ISSUE TITLE
Problems in training of Food Recipes Bot in Arabic Slang Language

### ISSUE THREAD

**Issue by BasantMT** [wit-ai/wit#456]
I and a team are making a chatbot about food recipes and cooking in Egyptian Arabic Slang language and we're facing some problems the training
At first, wit didn't recognize some words, when we increased the keywords of the entities, the errors have increased not decreased

There are 3 types of errors that have appeared in the training

1- it does not take the whole entity as it should do
مكرونه بالبشاميل بالخضار 
it doesn't take  بالخضار with entity

2- when we enter سمبوسك باللحمه
it takes سمبوسك بالبطاطس
We don't understand why he took سمبوسك and add to it بالبطاطس although it is not in the word

3- if we enter صينيه بطاطس
it takes صيني as we have entity for cuisines

We don't know if they're wit's problems or misuse from us, we know that it uses keywords and free text but we don't understand how algorithm moves
Here're some samples of the errors
https://drive.google.com/open?id=0BySqPJGlZ151Qk1MbkpGUTVGaVk

we really need to understand the algorithm that it uses in text similarity to avoid these mistakes or to be able to fix em.

**Comment by parvathysarat** [comment]
Hey, was this issue ever fixed? Did you get around to using wit.ai effectively for the Arabic bot?

**Comment by stopachka** [comment]
There's been a lot of changes since this -- closing for now, if you have any news or recent results let us know an app id and we can take a look
