### ISSUE TITLE
Duplicate Story

### ISSUE THREAD

**Issue by mashedkeyboard** [wit-ai/wit#457]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Request a feature

Can we have the ability to duplicate Stories? I want to create the same Story in multiple languages, so it'd be great to be able to duplicate the logic from one to another.

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
