### ISSUE TITLE
Support Brazilian Portuguese language

### ISSUE THREAD

**Issue by bgbraga** [wit-ai/wit#458]
Feature: 
Please add support to Brazilian Portuguese language.
It is different of standard Portuguese.

Let me see if you need help.

**Comment by l5t** [comment]
We use mainly machine learning techniques so it should work well for Brazilian Portuguese. The only language specific part we use is for specific entities like datetime or number. We open sourced the code here: https://github.com/facebook/duckling so feel free to create BR specific rules there.
https://medium.com/wit-ai/locale-support-for-dates-and-times-b77251788cf8
