### ISSUE TITLE
Bot breaks on one of my Stories

### ISSUE THREAD

**Issue by mashedkeyboard** [wit-ai/wit#461]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug/question

**What is the current behavior?**
In one of my Stories, the bot just seems to completely break. The editor shows it as having a conflict between two completely unrelated things, and simply goes haywire as soon as you start trying to follow the script in the demo... help?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

https://wit.ai/mashedkeyboard/Overtreding.be/stories/1b90c8bc-489c-4f45-9188-e32d988d23c6

**What is the expected behavior?**

For the bot to follow the Stories, and for this Story in particular to validate.

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
