### ISSUE TITLE
Handling false positive - mismatched intent

### ISSUE THREAD

**Issue by mlamgohire** [wit-ai/wit#462]
General Training Question:

As I train my bot's understanding.  I have predefined, intents/traits I want to be able to identify when a questions is asked.  When Wit incorrectly mismatches a question to an intent, how do I correct these?  If I don't 'validate' it from my inbox, than how do i make Wit discard or give the question a very low confidence score so that it doesn't get mapped to the incorrect intent?

**Comment by patapizza** [comment]
This is on our roadmap: #395.
