### ISSUE TITLE
Stories frozen

### ISSUE THREAD

**Issue by tpizzle** [wit-ai/wit#463]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
Stories are frozen (spinning circles for about an hour); Started after all bookmarks were deleted
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
green dots and bookmarks intact

**Comment by tpizzle** [comment]
![screen shot 2017-04-03 at 2 26 16 pm](https://cloud.githubusercontent.com/assets/11740989/24632599/a1118098-1879-11e7-8ec6-f49c024ad580.png)

**Comment by stopachka** [comment]
Hey @tpizzle  -- we are having an intermittent issue, on it! 

Will update here as soon as it's resolved

**Comment by l5t** [comment]
just restarted your training

**Comment by tpizzle** [comment]
@stopachka or @l5t  would you mind restarting it again? All my stories are still spinning from yesterday!

**Comment by l5t** [comment]
do you mind sharing your Wit app URL?

**Comment by tpizzle** [comment]
https://wit.ai/tpizzle/2MG-2.4.1

**Comment by l5t** [comment]
done

**Comment by tpizzle** [comment]
Thanks a ton @l5t

**Comment by MathieuDuboy** [comment]
@l5t Can you please restart my training please : https://wit.ai/mathieuduboy/musees
Some trained entities has disappeared since yesterday, like mine bookmarks in stories. I'm really frustrated ... My bot doesn't want to "learn" anymore !! Thank you
