### ISSUE TITLE
can I use wit.ai in persian language?

### ISSUE THREAD

**Issue by mrmrn** [wit-ai/wit#464]
Dear wit.ai programmers, thank you for this great bot engine.
I have a simple question, Can I use wit.ai to create an e-commerce bot in persian language?
for example I want to have something like [this](https://youtu.be/SeHYuLtjsdU) in persian language.could I have such wit.ai powered PERSIAN bot?

**Comment by l5t** [comment]
Thanks for reaching. Persian is in Beta so you should give it a try. Some of the built-in entities like date, duration and number may not be available for this language. But you can contribute to the open source project here: duckling.wit.ai

![image](https://cloud.githubusercontent.com/assets/6992759/24665095/368e4bdc-1911-11e7-941e-78fcec0887cc.png)

**Comment by mrmrn** [comment]
thank you.
I used speech to text in  persian.and works nice but most be better.
I will contribute on duckling.wit.ai
