### ISSUE TITLE
distinguishing names of people and cities

### ISSUE THREAD

**Issue by bmcclenahan** [wit-ai/wit#465]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question
**What is the current behavior?**
when the question is "who lives in <name of city or suburb>" or "who lives at <city or suburb>" with most commonly returns a contact entity rather than a location.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I have entered many training samples, but it doesn't seem to be improving 
**What is the expected behavior?**
 I understand that the names can be interchangable at times, but was hoping the form of the query might help it distinguish - is there any other approach to train it or otherwise improve this behaviour?

**Comment by bmcclenahan** [comment]
my tags were removed in the editor - the questions submitted are "who lives in city/suburb" etc.

**Comment by l5t** [comment]
Closing. Some built-in entities like wit/contact can be a bit too greedy so I would suggest creating your own entities if the built-in entities don't fit your need.
