### ISSUE TITLE
Predicates don't move with "Bot sends" objects

### ISSUE THREAD

**Issue by mashedkeyboard** [wit-ai/wit#466]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
When moving a "Bot sends" object up or down a Story, the related predicates do not move with it. Likewise, if you create a new "Bot sends" object at the end of a story, and move it upwards, then try to create a predicate where it is placed, you cannot: it simply jumps to the next closest predicate.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Create a Story
2. Add a few "bot sends" and "user sends" items - doesn't matter what
3. Add a predicate to one of the "Bot sends"
4. Create a new "Bot sends" at the bottom of the story
5. Move the new "Bot sends" upwards
6. Try to create a predicate related to this "Bot sends"

**What is the expected behavior?**
The ability to create predicates wherever the "Bot sends" element is in the Story

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
