### ISSUE TITLE
Exporting composite entities get lost

### ISSUE THREAD

**Issue by onepixelaway** [wit-ai/wit#467]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
When exporting, the composite entities get lost in the export.

**What is the current behavior?**
You export, you import and all composite entities are dead.

**What is the expected behavior?**
Should keep composite entities.

**Comment by jeremynevans** [comment]
Seconded - please fix this ASAP otherwise it's impossible to export the full data!

**Comment by blandinw** [comment]
Got it, prioritized as urgent.

**Comment by blandinw** [comment]
Thanks for your patience, this should now be fixed, please feel free to comment/reopen if not.
