### ISSUE TITLE
Question: More than one response for an intent

### ISSUE THREAD

**Issue by larenzon** [wit-ai/wit#468]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
***Question***

Hi team, 
First of all, I would like to say that I just have started to use wit.ai and I'm very excited with the results! It is just awesome!

I would like to know if someone could give me some recommendations for having more than one response for an intent.

For instance:

*User says: Hello Robot!*

I would like to have more than one quick answer for this intent like:

*Bot sends: Hi Welcome!*
or 
*Bot sends: Hello My friend!*
or 
*Bot sends: Hi*

Is it possible to have more than one answer for the same intent in a story?
Or is it better to parse the intent in my server side in order to select the response?

Thanks in advance!

**Comment by l5t** [comment]
We don't currently support variations of the same answer. So it is probably better to handle this on your side

**Comment by larenzon** [comment]
It is OK! 
Thank you very much for your quick response!
