### ISSUE TITLE
Wit not validating when number of intents/expressions are large

### ISSUE THREAD

**Issue by sourjatilak** [wit-ai/wit#469]
Expressions are not getting validated on our wit:  https://wit.ai/MyJio/MyJiov2
We are getting errors: "Could not validate this expression", every now and then.

We have around 6500 expressions and around 600 intents.
The validation are happening at all whenever we are trying to add more expressions/intents and validate existing ones from inbox.

Moreover, The response form wit is taking around 4-5 seconds at an average. The Response time is getting slow slower every day.

Is this a bug as we have so many expressions and intents?

**Comment by l5t** [comment]
Closing as this issue is hold. Please reopen or create a new one if you still experience the issue
