### ISSUE TITLE
No text in Logs

### ISSUE THREAD

**Issue by dsouzajoe** [wit-ai/wit#470]
When i go to my logs it shows no text 
<img width="307" alt="screen shot 2017-04-05 at 5 37 41 pm" src="https://cloud.githubusercontent.com/assets/18027420/24728111/9fab4b9a-1a26-11e7-8284-eb113a3abc8e.png">

It used to show all entries before? Am i doing something wrong?

App id: 5850192a-4abe-450d-9ba6-e67d66f9ef3f

**Comment by endoplasmic** [comment]
I'm having the same issue in my logs as well. I'm also wondering if that's a byproduct of my app being in a "Dirty" state for about a day now :(

**Comment by blandinw** [comment]
Looking into it. Please provide your app id when you open issues.

**Comment by blandinw** [comment]
Will push a fix shortly.

**Comment by blandinw** [comment]
Thank you for your feedback! It should be fixed now.

**Comment by dsouzajoe** [comment]
Thank you, its fixed
