### ISSUE TITLE
App in "Dirty" state for many hours

### ISSUE THREAD

**Issue by endoplasmic** [wit-ai/wit#471]
I went ahead and exported an app I was working on to duplicate it and make a branch of it for developing _(I'm not sure if it's possible already to do this, which would be fantastic, but that's for another post)._

I imported the zip to my new "dev" version and have been in a dirty state ever since _(coming up on a day now)_.

Is this a known thing? Training on my original app takes only a few seconds before it's clean again. 

So sadly the whole idea of having a dev branch of the app to train it new things before rolling it into my main one is a bit of a bust :(

Main app id: **589a604f-46b4-4847-bd3e-7a43de827b35**
Dev app id (the one that is still dirty): **58e2c74a-8551-4de6-a295-21db54fa270a**

**Comment by endoplasmic** [comment]
Updated first post with ids, sorry about that.

**Comment by l5t** [comment]
Done
