### ISSUE TITLE
Stories for shopping website

### ISSUE THREAD

**Issue by aayushrangwala** [wit-ai/wit#473]
Hello everyone,

I am working on building the FB bot for shopping websites just like shopify or spring bots.
But i am having so much trouble in making stories. So please anyone worked on same domain could share their sample stories

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
