### ISSUE TITLE
Chatbot respondes differently for the same input

### ISSUE THREAD

**Issue by victorhf** [wit-ai/wit#474]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
![screen shot 2017-04-07 at 4 02 50 am](https://cloud.githubusercontent.com/assets/9014125/24789000/1cb61e3c-1b47-11e7-86fb-59e0107ed670.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
The screenshot shows exactly the problem

**What is the expected behavior?**
The expected behavior was the bot to respond the same answer.

**Comment by l5t** [comment]
Can you share your wit app url?

**Comment by victorhf** [comment]
Solved the problem exporting the app and creating a new one.

@l5t the app is private. How can I send it directly to you?

**Comment by victorhf** [comment]
@l5t Having the same problem. Do you know if there is some context on the messages that is triggering this error?

![screen shot 2017-04-11 at 10 28 59 am](https://cloud.githubusercontent.com/assets/9014125/24911790/8c0c9172-1ea2-11e7-914d-c690febf6a28.png)
![screen shot 2017-04-11 at 10 29 31 am](https://cloud.githubusercontent.com/assets/9014125/24911797/923b7b1c-1ea2-11e7-9b03-88dc1ca56ca8.png)

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
