### ISSUE TITLE
Second Query is launching without the first one

### ISSUE THREAD

**Issue by Walter87** [wit-ai/wit#475]
I have simple story where user asks about possibility to contact us. It works fine as a whole story but the problem is, sometimes when I type in some unexpected message as a user it starts from the middle of the story. How to prevent launching second query if first one was not launched yet.

This is my story:
![image](https://cloud.githubusercontent.com/assets/12779031/24793118/1a53187c-1b81-11e7-8c23-dda98fca101c.png)

And example of wrong behauvior in messenger.

![image](https://cloud.githubusercontent.com/assets/12779031/24793173/54434a98-1b81-11e7-8d22-b98242e384e7.png)

Should I setup contactUs action with "Only if " and how to use this syntax. What should I put there. 
In example: Only if: intent = contact us.

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
