### ISSUE TITLE
Stuck in 'Training status: ongoing" for more than 3 days

### ISSUE THREAD

**Issue by asstergiBSQ** [wit-ai/wit#476]
Hello,

I have created an App on wit.ai. Everything was running smoothly until two days ago when it's stuck on the training phase.

Could you please help?
Here is the like to the App: https://wit.ai/asstergi/Euroleague_chatbot/

**Comment by l5t** [comment]
Done

**Comment by asstergiBSQ** [comment]
@l5t Thanks a lot!
