### ISSUE TITLE
Training ongoing: Please restart it?

### ISSUE THREAD

**Issue by candycanetrain** [wit-ai/wit#478]
My app keeps on saying there's ongoing training. It's been several days. 
https://wit.ai/owlie/unnamed/

Is there a way to restart it? I'm not able to delete or validate anything in the inbox.

**Comment by l5t** [comment]
done

**Comment by ASC689561** [comment]
Same issue here...status has been "dirty" for hours...Could you help restart it pls? Anything I did wrong with my bot? https://wit.ai/ASC689561/Cukcuk_GoiMon

**Comment by l5t** [comment]
restarted
