### ISSUE TITLE
Fail to validate turn

### ISSUE THREAD

**Issue by candycanetrain** [wit-ai/wit#479]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
I'm trying to add an entity to the main story and it is not letting me update the story.

https://wit.ai/owlie/unnamed/stories/992697af-e951-4708-b323-1de0fa0116e6

This was my attempt to fix a bigger bug. Right now I am able to type "I want to buy a gift for mom" and it will call the merge action. However, when I type "buy gift", the intent is registered, but the merge action is skipped.

**Comment by l5t** [comment]
Seen to be working now after a retraining
