### ISSUE TITLE
Getting incorrect action in application, but testbot works

### ISSUE THREAD

**Issue by Axxa764** [wit-ai/wit#480]
I have a simple story which works fine with the test bot. But if I try to integrate it with Facebook Messenger, it won't follow this story. 

![1](https://cloud.githubusercontent.com/assets/15095363/24855938/610cd186-1de3-11e7-9dac-9f63baa2da07.PNG)

In Logs we can see that after user input "Ako sa máš?" action pozdravit() is called instead of giving simple answer "Dobre {name}".

![2](https://cloud.githubusercontent.com/assets/15095363/24856293/75fe58ac-1de4-11e7-91b4-25c289b31a54.PNG)

It seems bot doesn't continue in the story because same behavior we can see if we start conversation with "Ako sa máš?" in test bot.

![3](https://cloud.githubusercontent.com/assets/15095363/24856604/9c632aee-1de5-11e7-9e26-4b77b92678bd.PNG)

Location of my test story: https://wit.ai/Axxa764/Skuska/stories/772eac92-8530-486a-b13b-061918bd62fb.

Please, can you explain we, where I make mistake? Here is part of my code. 
[ms.txt](https://github.com/wit-ai/wit/files/909742/ms.txt)

Thank you.

**Comment by patapizza** [comment]
Hi @Axxa764, it seems like when you send the message "Ako sa máš?", the context doesn't contain `name` anymore. Hence the bot can't answer the question. Make sure to send the updated context all along.

**Comment by Axxa764** [comment]
I understand but I don't know where in my code is mistake. Can you help me?
