### ISSUE TITLE
Bug/Question - Wit.ai misunderstood keyword search strategy

### ISSUE THREAD

**Issue by victorhf** [wit-ai/wit#484]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug.

**What is the current behavior?**

I created a entity "comando" and assigned the keyword strategy.
The wit.ai should recognize the phrase as a keyword, but it is misunderstanding it.
Sometimes the search strategy also changes to no option selected.

![screen shot 2017-04-11 at 1 25 18 am](https://cloud.githubusercontent.com/assets/9014125/24892867/1ecb2b9c-1e56-11e7-9d33-cc4493511d15.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Screenshots:
![screen shot 2017-04-11 at 1 26 04 am](https://cloud.githubusercontent.com/assets/9014125/24892835/ed37635c-1e55-11e7-97a9-9a1910a5c233.png)
![screen shot 2017-04-11 at 1 01 51 am](https://cloud.githubusercontent.com/assets/9014125/24892848/054fa5da-1e56-11e7-9de9-a958395660b1.png)
![screen shot 2017-04-11 at 1 01 43 am](https://cloud.githubusercontent.com/assets/9014125/24892851/08c02da2-1e56-11e7-8e50-38e4b6faf2fa.png)

**What is the expected behavior?**

The expected behavior is the entity be recognized. (There should be no misunderstood on keywords right?)

URL https://wit.ai/lucasschanner/eduqmais (private)

**Comment by victorhf** [comment]
There is a word limit for the keyword strategy?

**Comment by MathieuDuboy** [comment]
I have the same bug ... Sometimes the search strategy also changes to no option selected.
What's wrong ?

**Comment by l5t** [comment]
Closing. This has been fixed when we sunset Stories UI. Please reopen if you still experience this behavior
