### ISSUE TITLE
Wrong work of simple intent "Hello"

### ISSUE THREAD

**Issue by DenisUmnov** [wit-ai/wit#486]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

Question

**What is the current behavior?**

I'm using a simple app with one story where

User says: Hello
Entity: user-defined "intent" with value "greetings", search strategy "trait"
Bot says: OK Helllo

But my bot says "OK Hello" when user types any chain of symbols like "blablabla":

User says: Hello
Bot says: OK Hello
User says: Bye
Bot says: OK Hello
User says: fjkjdskfsdfslfjl
Bot says: OK Hello

What I'm doing wrong?

**What is the expected behavior?**

Bot must answer me only if user said "Hello".

**Comment by patapizza** [comment]
Hey @DenisUmnov, you can try to teach the bot how it should respond by extending the story with your conversation example.
Wit uses the context and the conversation history to predict the next bot action. So if the above suggestion doesn't work, you can update the context to help the bot follow the expected flow.
Hope this helps.
