### ISSUE TITLE
Intent not recognized

### ISSUE THREAD

**Issue by mazerab** [wit-ai/wit#487]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Think I found a bug
**What is the current behavior?**
A question asked to the bot returns a message that is for another intent.
Asking same question in understanding, links the question to the correct intent.

The understanding tab and chat bot should behave the same.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Please contact me if you need to see the issue first hand.
**What is the expected behavior?**
The unique intent specified for a question is respected in both understanding tab and chat bot.

**Comment by mazerab** [comment]
![screen shot 2017-04-11 at 11 36 38](https://cloud.githubusercontent.com/assets/15131317/24924858/3131ec94-1eab-11e7-9174-780602a9784b.png)

**Comment by mazerab** [comment]
![screen shot 2017-04-11 at 11 38 23](https://cloud.githubusercontent.com/assets/15131317/24924932/680551c0-1eab-11e7-986e-47f1bf7b8656.png)

**Comment by l5t** [comment]
Closing as this issue is hold and stories are deprecated.
