### ISSUE TITLE
Intents match correctly but app gives wrong answer

### ISSUE THREAD

**Issue by agrey** [wit-ai/wit#489]
*bug*, *question*

I have an app with a lot of stories - about 200 of them.
The intents match correctly when I test them in Understanding, but when I run the bot it gives answers from the wrong story. Since Understanding validates intent correctly as if everything is working, I have no idea how to move forward. It's extra strange since the same question gives different answers if I ask it twice in a row. For instance, I have a story for when the user says "Hi", that responds with a welcome message. When I test "Hi" in understanding it matches it correctly. And when I run it and type in "Hi", I get the welcome message the first time... but if I write "Hi" again, I get a random response from a different story.

Generally, the first question I ask correctly is matched correctly and answered correctly... but subsequent questions produce random responses even though the questions are correctly intent-matched, which we have validated in Understanding. 

Help! Anyone know what the heck is going on?

**Comment by stopachka** [comment]
Hey @agrey -- what is your username on wit.ai? I can try to take a look and debug what is going on

**Comment by agrey** [comment]
That would be awesome! :) I will add your username to the project - it's not currently public. Thanks!!

**Comment by agrey** [comment]
To test: Just wait for the app to compile / go "all-green"... then type Hello... and wait... and type Hello again... you will get two different responses. Totally mystifying!

**Comment by stopachka** [comment]
Hey @agrey -- I may have missed this email -- if you could tell me your wit.ai username, I could figure it out.

Generally, as stories is a highly beta feature, I don't think it will be able to handle 200 stories well. I would suggest sticking with /message

**Comment by agrey** [comment]
Hey @stopachka you can't just decide this is closed. This issue is not resolved. Stories being in beta is all well and good but that's not a resolution, that's a "let's see if this issue does resolve later once we are no longer in beta". Otherwise it incorrectly implies that the issue has been fixed, which it clearly has not. Please re-open the issue, otherwise I will re-create it (but that's sloppy since we already have the thread in existence here).
