### ISSUE TITLE
Feature request: better dataset/expressions filtering and sorting

### ISSUE THREAD

**Issue by aripatrick** [wit-ai/wit#49]
I would appreciate the ability to toggle the sort of expressions by their header columns (specifically "name" and "entities") as well as by id. In different circumstances, each sort is useful.
- id - Seeing expressions in the order they were added is useful when trying to locate a miscatagorized expression
- Name - Useful for seeing the distribution of sentence starters (i.e. does every expression start with "what")
- Entities - Useful for seeing the distribution of entities (i.e. do most expressions leave out datetime)

This can be a lower priority, as it is a niceity.

**Comment by patapizza** [comment]
We shipped this [in August](https://medium.com/wit-ai/all-your-app-samples-at-a-glance-c4d6dbefeca3). cc @aripatrick
