### ISSUE TITLE
Why does the bot act differently when deployed on facebook? 

### ISSUE THREAD

**Issue by kottorp** [wit-ai/wit#490]
Our bot is trained to understand multiple yes/no questions in an hand full of stories. All of these works fine when we interact with it on wit.ai. We have now deployed the bot on facebook, and when we interact with the bot in messenger it acts differently and doesn't follow the correct path in the stories. 

Why is it behaving like this, and what can be done to fix it?

**Comment by stopachka** [comment]
Hi @kottorp -- we would need more info here. For example, a minimal repro of a messenger bot + stories that are behaving differently. 

Stories is still in beta, and usually the main culprits are too many branches

**Comment by l5t** [comment]
You can also troubleshoot via Witty Fiddle: https://github.com/wit-ai/witty-fiddle

**Comment by patapizza** [comment]
Might be an issue with the context/session-id as well. Please provide us with more details.

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
