### ISSUE TITLE
Problems with Search Strategy in training mode

### ISSUE THREAD

**Issue by MathieuDuboy** [wit-ai/wit#491]
Is there a problem with the Search Strategy ?
When I train my bot and validate a sentence, a keyword or something else, Search Strategy turns off.
For an keyword entity for my payloads, the Search Strategy "Keyword" (wich is already selected) is disabled everytime I validate a new entry.

What's wrong with this please ? Thank  you
https://wit.ai/mathieuduboy/test/

![capture d ecran 2017-04-13 a 15 16 40](https://cloud.githubusercontent.com/assets/11943636/25006209/48864c98-205c-11e7-8d51-22801f5dea3d.png)

**Comment by blandinw** [comment]
Thanks for your feedback, I'll investigate tomorrow!
I assume it actually does not prevent the entity from being extracted from the sentence?

**Comment by MathieuDuboy** [comment]
This "bug" seems to be corrected now. I'll keep in touch with you if it happened again.
Thank you for what you've done (or not :-) )
