### ISSUE TITLE
Stories web UI is broken?

### ISSUE THREAD

**Issue by klemensz** [wit-ai/wit#492]
Bug:

The web UI is currently completely unusable for me. On the stories page, the entities get duplicated when you click around. It also displays entities that shouldn't be there. The backup/export seems to be fine.

![bildschirmfoto 2017-04-13 um 18 31 03](https://cloud.githubusercontent.com/assets/1116517/25016166/2f7d6a7e-207f-11e7-9147-55f5c3453301.png)

Tried with Safari, Firefox and Chrome on macOS Sierra.

**Comment by mashedkeyboard** [comment]
I've occasionally had this issue - it seems to randomly come and go...

**Comment by stopachka** [comment]
Wow, that doesn't look good. Do you have an example app, with a repro step I can look at?

**Comment by klemensz** [comment]
@stopachka I gave you access to a private app.

**Comment by klemensz** [comment]
Any updates on that issue?

**Comment by stopachka** [comment]
Hey @klemensz -- I am able to repro and am investigating. Should have a fix out mid-week. Thanks for bringing this up and dogfooding stories. Will update here as the fix progresses

**Comment by klemensz** [comment]
Well I don't know how I got there as well. It has been working fine until I noticed the issue about two (?) weeks ago. When you switch between stories the old entities seem to stay there so over time even more entities appear that don't belong to that story.

Let me know if you need additional information.

**Comment by stopachka** [comment]
Hey @klemensz -- Indeed -- this was the case. 

I went ahead and made two changes

- Made sure that the entities "seemingly transitioning over" in the UI was fixed
- Made sure that there is no way to have duplicate entities anymore in stories. 

This should address the issues you were having.
