### ISSUE TITLE
Feed url not being detected as url

### ISSUE THREAD

**Issue by tpizzle** [wit-ai/wit#497]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question
**What is the current behavior?**
This link: http://feeds.latimes.com/~r/latimes/sports/football/nfl/~3/YA-v2Q_Za4s/la-me-ln-fresno-professor-trump-tweet-20170413-story.html

is detected by my bot as having 2 wit/number entities, and the query "football", but is not recognized as a url, even after I add it to understanding (even adding each piece individually). What can I do to fix this?
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
See what the URL detects in another bot.

**What is the expected behavior?**
It would extract the entity as wit/url

**What is the App ID where you are experiencing this issue (if applicable)?**
58d2c3e6-debc-4433-899a-eee73e38a912

**Comment by patapizza** [comment]
Thanks for reporting, this is a bug.

**Comment by patapizza** [comment]
Actually it looks like this works:

![Capture](http://i.imgur.com/OGyU5Bt.png)

**Comment by tpizzle** [comment]
glad it works now, thanks @patapizza
