### ISSUE TITLE
MIME type ('application/json') is not executable, and strict MIME type checking is enabled.

### ISSUE THREAD

**Issue by byucelyigit** [wit-ai/wit#498]
In a chrome browser Irecieve:

**Refused to execute script from '*' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.**

**Resource interpreted as Document but transferred with MIME type application/json:** 

"https://api.wit.ai/message?callback=jQuery32007478922012370341_1492178480959&q=test&access_token=$MY_TOKEN&_=1492178480960".

with a response from wit.ai

jQuery32007478922012370341_1492178480959({
  "msg_id" : "eea5dd6c-673a-40e3-8b88-2fd16a1bbe89",
  "_text" : "test",
  "entities" : {
    "search_query" : [ {
      "confidence" : 0.8136680032309246,
      "type" : "value",
      "value" : "test",
      "suggested" : true
    } ]
  }
});

Same code was working perfectly two days ago.

is there any change in response format?

code:

                    $.ajax(
                                {
                                    url: 'https://api.wit.ai/message',
                                    data: {
                                        'q': myQuery,
                                        'access_token': 'AKX46J4DR7SJ4JGSJ5KB6GL5DSEW35AX'
                                    },
                                    dataType: 'jsonp',
                                    method: 'GET',
                                    success: function (response) {
                                        console.log(response);
....

**Comment by blandinw** [comment]
We implemented a few security-related fixes (x-content-type-options: nosniff), which prevents  pure JSON responses from being executed in the browser. JSONP was mistakenly returned as content-type: application/json, it should have been application/javascript (cf. http://stackoverflow.com/questions/111302/best-content-type-to-serve-jsonp)

This should be fixed in the next few hours.

**Comment by blandinw** [comment]
Should be fixed now, feel free to reopen otherwise!
