### ISSUE TITLE
I'm having an issue with context in a yes/no question

### ISSUE THREAD

**Issue by Gniac** [wit-ai/wit#499]
I'm working on a bot that can be used to manage a shopping list. The story in which we are having an issue is where the user can choose to display the list of products.

> **user**: Can you display my shopping list?
> **bot**: You currently have 24 products on your list, do you want me to display them?
> **user**: Yes
> **bot**: Here they are: (aaaa, bbbb, ccc, ....)

For answering the first question, I need to execute an action to obtain the number of products, after replying yes, I need another action to download a list of products. So there are two actions, which bot give back context information.

The problem I'm having is that the bot sometimes replies with a completely different answer for a different story where I also use a yes/no question to confirm an action. Sometimes, it also replies with the 'no' answer, even if I replied 'yes'

**Comment by Gniac** [comment]
here's the bot: https://wit.ai/gino/listBot

**Comment by l5t** [comment]
can you share steps to repro?

**Comment by Gniac** [comment]
Here: this is the actual bot/story I'm talking about: https://wit.ai/gino/shopping-bot/stories/207e9b52-676f-4431-9980-03425222b5cd
I'll try to explain the steps you need to take to reproduce, because it's in dutch.

- **Try to ask it:** _Wat staat er op mijn lijstje?_ (translated: what's on my list?)
- **Then update context with:** _MultipleProducts, NumberOfProducts & ProductNames_
- **It will then respond with:** _Er staan meerdere producten op je lijstje. Heb je graag dat ik ze voorlees?_ (translated: there are multiple products on your list, do you want me to read them for you?)
- **answer**: _Ja_ (translated: yes)
- **It will read:** _Ok._ instead of listing the products products.

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories

**Comment by Harshitharaj06** [comment]
There is an operation permission error when i deploy wit.ai chatbot using aws lambda

"errorMessage": "[Errno 1] Operation not permitted",
--
"errorType": "PermissionError", | "errorType": "PermissionError",
"stackTrace": [ | "stackTrace": [
"  File \"/var/task/lambda_function.py\", line 97, in lambda_handler\n    client.interactive(handle_message=handle_message)\n", | "  File \"/var/task/lambda_function.py\", line 97, in lambda_handler\n    client.interactive(handle_message=handle_message)\n",
"  File \"/var/task/wit/wit.py\", line 104, in interactive\n    message = prompt(INTERACTIVE_PROMPT, history=history, mouse_support=True).rstrip()\n",''' | "  File \"/var/task/wit/wit.py\", line 104, in interactive\n    message = prompt(INTERACTIVE_PROMPT, history=history, mouse_support=True).rstrip()\n",
**the below is the code:**
def lambda_handler(event, context):
client = Wit(access_token=access_token)
client.interactive(handle_message=handle_message) 
return { 
'statusCode': 200, 
'body': json.dumps('Hello from Lambda!') 
} 

Can i know how to deploy it on aws using aws-lambda or can i know what are minor changes i can make to the code.
