### ISSUE TITLE
How do I get multiple replies to my user's query out of which wit selects any one at random?

### ISSUE THREAD

**Issue by abhinavreddy98** [wit-ai/wit#500]
I want my bot to respond a little differently everytime a user repeats their question. For example if the user says hello, I want my bot to respond with hello/hi/hey, etc randomly

**Comment by stopachka** [comment]
hey @abhinavreddy98 

If you are using stories, you can use an action -- 

For example, create an action `sayHello`

In your code, you could sample a list of responses, and you'll have what you desire

If you use /message, you can simply do this in the switch statement
