### ISSUE TITLE
How to find what's wrong with story?

### ISSUE THREAD

**Issue by maciejjozwiak** [wit-ai/wit#501]
It says 'your app may fail to handle this story properly'. My story is pretty robust and have many branches - how am I able to find out quickly where is the problem? Now only option is to browse all the options and branches and find one red colored that implies some errors.

My appId: 
58f492b4-9e0d-493c-a011-35343d407683

**Comment by patapizza** [comment]
You're right, that's the only option today.
Maybe playing with the bot in the console might also help pinpointing where the flow is broken.
