### ISSUE TITLE
wit timezone

### ISSUE THREAD

**Issue by TrejGun** [wit-ai/wit#502]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question/bug

**What is the current behavior?**
Wit returns date with strange offset
I don't understand why it is -7, this is not my timezone
```js
// 2017-04-20T00:00:00.000-07:00
```
**What is the expected behavior?**
Wit returns date without offset
```js
// 2017-04-20T00:00:00.000+00:00 or 2017-04-20T00:00:00.000Z
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
because it makes it difficult to test dates
for example
```js
import moment from "moment";
import {Wit} from "node-wit";

const client = new Wit({accessToken: ""});
const date = moment();

client.message(date.format("dddd D MMMM"), {})
.then(res => {
    console.log(res.entities.datetime[0].value === date.startOf("d").toDate().toISOString()); // false
    console.log(date.startOf("d").isSame(res.entities.datetime[0].value)); // false
});
```

**Comment by patapizza** [comment]
Hi @TrejGun, you can set the timezone for your app in Settings (defaults to America/Los_Angeles).
It's also possible to override it in the context: https://wit.ai/docs/http/latest
Hope this helps.

**Comment by TrejGun** [comment]
thanks!
