### ISSUE TITLE
Stuck in training status: ongoing

### ISSUE THREAD

**Issue by fadlykayo** [wit-ai/wit#503]
Hello,

I have an issue with the bot status "training status: ongoing". It's stucked with training status since the last couple hours, could you help me? Thank you in advance!

My bot url: https://wit.ai/fadlykayo/yuna-test-2

**Comment by patapizza** [comment]
Hi @fadlykayo, this should be fixed now.

**Comment by fadlykayo** [comment]
@patapizza thanks a lot!
