### ISSUE TITLE
Restoring a large app backup does not function the same as original

### ISSUE THREAD

**Issue by agrey** [wit-ai/wit#504]
I've found that with my large-ish app (with ~200 stories), when I back up and then restore from the backup, the restored version doesn't behave the same as the original. It's often full of errors, or doesn't compile at all, or doesn't match intents correctly / the same as the original.

Anyone else encounter this? 

It seems to work ok for small apps with few stories and minimal complexity, but as our app size grew, the backup-restore process started to get unpredictable.

Any tips?

**Comment by hactar** [comment]
Likely related to #381

**Comment by agrey** [comment]
Interesting. I scanned the thread. I don't get stuck in the same place as the others... and I don't get any error messages.

But you're right, it might be related.

**Comment by hactar** [comment]
The error only appears if you look in your browsers error console.

**Comment by agrey** [comment]
Oh thanks. I will check that later and if it's the same issue I will kill this thread. Thanks!

**Comment by jtliao** [comment]
Merging with #513
