### ISSUE TITLE
how to set the context for my bot?

### ISSUE THREAD

**Issue by simpel** [wit-ai/wit#505]
Hi all! 

This might not be the right place to ask since this really isn't a bug, it's just me not knowing how to code ;) 

Anyways, I have a story that calls a function on my server, I'd like that function to update the context of my bot but it doesn't work. So what am I doing wrong here? What values do I have to send, is OK with ONLY the context variable or do I always have to provide a session_id and version? 

    $witcall = $this->wit->post($this->wit_base_url.'/converse', 
            [
             	'form_params' => [
                	'context' => [
                		'username' => '$entities->contact[0]->value'
                	]
                ],
                'query' => [
                	'v' => '1',
                	'session_id' => 'vk-'.$this->thread_id
                ]
            ]
        );

The call above generates the following error:

`GuzzleHttp\Exception\ClientException: Client error: 'POST https://api.wit.ai/converse?v=1&session_id=vk-1' resulted in a '400 Bad Request' response: Unable to parse context in body in /home/vagrant/Github/chatbot/www/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:111...
`

Last but not least, I'm using the WIT HTTP API and my server runs with Laravel and I'm using the Guzzle HTTP client.

**Comment by patapizza** [comment]
I'm not familiar with Guzzle, but it seems like you should pass the context in `body`, not `form_params`: http://docs.guzzlephp.org/en/latest/request-options.html#body.

**Comment by simpel** [comment]
*facepalm* :)

It's true. This is would be the correct way of doing it:

    $call = $this->wit->request('POST', 'converse', [
    		    'json' => Session::get('context'), 
    		    'query' => [
		        'v' => '1',
            	        'session_id' => 'vk-'.$this->thread_id
    		    ]
		]);
