### ISSUE TITLE
wit API extremely slow response

### ISSUE THREAD

**Issue by ivgenyk** [wit-ai/wit#506]
*bug*

**What is the current behavior?**
When I send parsing requests to wit API it takes >1 min to return a reply.
I have another wit app, this one works fine. The apps are almost the same (were exact copies 2 weeks ago).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Send the app requests via API several times and watch the response time

**What is the expected behavior?**
API response of <1 sec

**What is the App ID where you are experiencing this issue (if applicable)?**
57f4b475-f32b-4842-a5e6-a5028fc052a0

**Comment by blandinw** [comment]
What time window did you observe the slowness in?
Is it still happening now?

**Comment by ugurarpaci** [comment]
We event receive timeouts

**Comment by ivgenyk** [comment]
Hi, it is not happening anymore.
It happened 24-20 hours ago.

**Comment by ivgenyk** [comment]
We had this happening several times before over this week, if you want to contact me in private I can send you logs with exact timings

**Comment by blandinw** [comment]
@ivgenyk we have a lead on what's going on. It is probably a race condition in a threading library that we use. I'll keep this issue updated with progress. ETA 1 or 2 days before fix deployed to production. Also know that we implemented performance/reliability tweaks at the beginning of the week, and will switch /message to our new architecture pretty soon too.
