### ISSUE TITLE
Timeout of "bot executes"

### ISSUE THREAD

**Issue by douglasoliveira-sossego** [wit-ai/wit#507]
Hello,
I'm looking for wit.ai timeout "bot executes" action, but I did not find the answer.
Does anyone know how long the call to action by my side should respond to wit.ai?

**Comment by patapizza** [comment]
Hi @douglasoliveira-sossego, as this is asynchronous there is no timeout: you are making calls to wit.ai (and not wit.ai making calls to you). Our different libraries don't set a timeout either.
