### ISSUE TITLE
How to interact my app with Android?

### ISSUE THREAD

**Issue by augustocadini** [wit-ai/wit#508]
I want integrate my app and my entities with an app Android, for example:

I say for Android "Turn on the led!"
And in my app in wit.ai, I taught with on/off led. Where "LED" is a entity and "ON/OFF" be values.

For now I downloaded a sample application and did nothing else, only say something.
The app that I use is -> https://github.com/wit-ai/wit-android-eval

**Comment by stopachka** [comment]
Hey @augustocadini -- 

Do you have a specific issue when doing the setup? 

The general idea is: 

- Get voice / text from android
- Send request to wit
- parse request in android
- take action from response

**Comment by augustocadini** [comment]
Yes, it this! But I don't know how to use the library for java. I has created an example on the website for my definitions and lack integrate with app.

**Comment by UrmiBhanani** [comment]
I have also tried wit-android-eval example but getting below error. Also didn't find any proper documentation for implement Wit.ai with Android app. Check below exception:
FATAL EXCEPTION: Thread-20472
                                                                      Process: ai.wit.eval.wit_eval, PID: 17956
                                                                      java.lang.ArrayIndexOutOfBoundsException: length=12800; index=12800
                                                                          at ai.wit.sdk.WitMic$SamplesReaderThread.short2byte(WitMic.java:227)
                                                                          at ai.wit.sdk.WitMic$SamplesReaderThread.run(WitMic.java:207)

**Comment by blandinw** [comment]
Closing for same reasons as https://github.com/wit-ai/wit/issues/237
