### ISSUE TITLE
Could not validate this expression 

### ISSUE THREAD

**Issue by zuni10** [wit-ai/wit#509]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question

**What is the current behavior?**
Sometimes, the wit motor tells me that i can't validate the expression.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
To enter the right intention and to make the phrase work in the wit response

**What is the App ID where you are experiencing this issue (if applicable)?**
571e37ac-7178-43bc-bb5f-0b4ca801722e

<img width="1387" alt="screen shot 2017-04-20 at 00 15 26" src="https://cloud.githubusercontent.com/assets/27821463/25240944/e831dcd2-25b9-11e7-9bb2-9a609c7b8e08.png">

**Comment by stopachka** [comment]
Hey @zuni10 -- We had some transitive infrastructure issues last week. When did it happen? This should fix soon, as we migrate the infra to Facebook.

**Comment by katapp** [comment]
Hi, same problem here since 1 hour. When I enter sentences that I had already trained, I get now the error "Could not validate this expression". Last week I had no problems.

**Comment by AhmedMashour** [comment]
The same here , I had no problem last week but today I'm having these issues

**Comment by zuni10** [comment]
Today, and last week also.

**Comment by leokamwathi** [comment]
Having same issue toady. 
I can't train it to understand an expression.
'find point of interest in japan'

The expected output.
```
find = intent
point of interest = search query
japan = location 
```

It ignores [point of interest] even after I train it over and over. its refuses to validate it. 
It outputs. 
```
find = intent
japan = location 
```

**Comment by blandinw** [comment]
@leokamwathi could you provide us with your app-id?

**Comment by leokamwathi** [comment]
@blandinw  the app id is 590077b4-2c51-494b-b14f-3215f9e016c6

**Comment by blandinw** [comment]
@leokamwathi I looked at your app and it is working as expected.

`wit/local_search_query` is a community-wide entity. If it doesn't fit your need, then don't use it. As of now, you won't be able to train it to make it do what you want. We're working on a better solution to allow you to reuse and personalize community entities like `wit/local_search_query`.

I recommend creating your own entity, which you'll be able to train and personalize more easily.
Closing this issue. Please reopen another issue if the original problem resurfaces. From our own testing, everything's working fine.
