### ISSUE TITLE
Getting 503

### ISSUE THREAD

**Issue by tpizzle** [wit-ai/wit#510]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
503 when I try to make requests to the API
**What is the current behavior?**
503 Service Unavailable
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Expected 200 response
**What is the expected behavior?**
200
**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by danm** [comment]
same here, i get the error when using github to authenticate

**Comment by blandinw** [comment]
I can't reproduce. Can you provide a specific request @tpizzle ?

**Comment by tpizzle** [comment]
Same as w/ @danm, seems to be working again! Sorry bout that

**Comment by blandinw** [comment]
It was probably a transient issue on the FB network. I'll investigate a bit.
Would be useful to know which IP address you were hitting, if possible!
Thank you for reporting this.

**Comment by tpizzle** [comment]
@blandinw my logging isn't the greatest and I just replaced my instance so I think I lost some info, but I was just making POST requests to https://api.wit.ai/converse

**Comment by tynano** [comment]
just heads up i'm getting these 503 service unavailable's randomly today (really just this afternoon, east coast time) with the /message endpoint. saw this thread figured i would add my data point to the mix

I.e. for the same given request, something like:

https://api.wit.ai/message?q=blah+blah+blah%3F

a request that normally returns 200, sometimes it will return 200 as expected, then it not work and return 503 for 4-5 requests... then it works again like magic. 

is this network issue, some kind of throttling? just curious as i'm loving the wit service thus far and really want to press on the gas, so to speak. Thnx!

**Comment by blandinw** [comment]
Hi @tynano, thank you for your feedback.

Your assumption is right, nodes die and the LBs are not updated quickly enough. Having a specific time window (to the minute) would help debug further. We're working on a solution so that it never happens again (unless facebook.com is down :)).

We sincerely apologize for the inconvenience.

**Comment by tynano** [comment]
@blandinw no worries! thanks for the reply

good call, my b, i'll make sure to provide specific timestamps if i see this kind of thing again
