### ISSUE TITLE
I can't see the import function in settings? is it removed?

### ISSUE THREAD

**Issue by iamkenken** [wit-ai/wit#511]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by hactar** [comment]
The "import" button has been moved from settings to a button when actually adding an app. Add a new app and you'll be offered the option to import your exported data.

**Comment by l5t** [comment]
Thanks @hactar

**Comment by iamkenken** [comment]
What if the application already exist?
