### ISSUE TITLE
Bot stuck in 'training status: ongoing' since yesterday

### ISSUE THREAD

**Issue by ulska** [wit-ai/wit#512]
Hi!

I have an issue with [my app](https://wit.ai/klaszcze/elpassion-bot-live): since yesterday it is stuck in `training status: ongoing`. ☹️
Tried to restart it by validating new example but it didn't help. 

Could you please check it?

Thanks! 🙏

**Comment by l5t** [comment]
Done.

**Comment by ulska** [comment]
Thank you! 😊
