### ISSUE TITLE
Locked out of my account: 503 Service unavailable

### ISSUE THREAD

**Issue by duaraghav8** [wit-ai/wit#514]
Hey guys, I'm unable to train my wit apps. I suddenly got logged out and now the authorize url just throws back a 503. Please look into this asap (**wit.ai/duaraghav8**)
![wit](https://cloud.githubusercontent.com/assets/12758282/25285974/c11de106-26d9-11e7-9012-ee3ed0fd7eb8.png)

**Comment by l5t** [comment]
Thanks for reporting. We do have an issue with logging. Will update when this is fixed. Thanks for your patience  https://www.facebook.com/groups/withackers/permalink/244724692600452/

**Comment by duaraghav8** [comment]
I've been able to log back in now. Thanks=)
