### ISSUE TITLE
Export system incorrectly sets search strategies

### ISSUE THREAD

**Issue by hactar** [wit-ai/wit#515]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
When exporting an app, such as https://wit.ai/sindre/WienBot-PROD most entity search strategies are set to "keywords","free-text" even though entities are set to just "keywords". 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1) Export an app such as https://wit.ai/sindre/WienBot-PROD
2) Open up the entities folder and open a json file, such as 1010.json
3) Take a look at the lookups key.

**What is the expected behavior?**
The lookups key says

```
    "lookups" : [
      "free-text",
      "keywords"
    ],
```

even though the web interface only had "keywords" selected before exporting.

**What is the App ID where you are experiencing this issue (if applicable)?**
https://wit.ai/sindre/WienBot-PROD

**Comment by hactar** [comment]
To add, sometimes the lookups entry contains keywords twice: `"keywords","keywords"` - this causes the "traits" keyword to be selected even though it wasn't before.

**Comment by yegeniy** [comment]
I'm seeing this as well.. Mostly in the case where the lookup strategy is just "keywords", but the lookups are changed to add "free-text" a bunch of times.

To reproduce, edit an entity via the GUI by adding a few synonyms; then download a backup of it.

**Comment by vladtco** [comment]
App ID for the above is `59949513-33b7-4ce3-91b7-11484efd664f`

**Comment by blandinw** [comment]
Thank you, looking now

**Comment by yegeniy** [comment]
Thanks Willy!

**Comment by stopachka** [comment]
(this looks to be solved -- let us know if you have any issues!)

**Comment by yegeniy** [comment]
I've noticed this as working since the frontend included the button for `keywords & free-text` as a separate option.
