### ISSUE TITLE
Export system has escaped quotes entity values

### ISSUE THREAD

**Issue by hactar** [wit-ai/wit#516]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug/question
**What is the current behavior?**
Not sure if this is intended or not...

When exporting an app, the value entries in both expressions.json and stories.json are escape quoted:

```
    {
      "text" : "1. Bezirk Kurzparzonen",
      "entities" : [
        {
          "entity" : "parken",
          "value" : "\"kurzparkzone\"",
          "start" : 10,
          "end" : 22
        }
      ]
    },
```
Notice the  ```"\"kurzparkzone\""```, which contains escaped quotes. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1) Export an app such as https://wit.ai/sindre/WienBot-PROD
2) Open up the stories.json and expressions.json values (escape-quoted)
3) Compare with the json files in the entities folder (not escape-quoted)

**What is the expected behavior?**
Maybe this is intended, but it appears odd that its inconsistent between stories/expressions.json and the entities json files themselves. Also, the new /samples API appears to not want escape-quoted values according documentation, so to feed the expressions.json file back to the /samples API, I would have to fix the escaped quotes first (unless wit magically fixes this, haven't tried)

**What is the App ID where you are experiencing this issue (if applicable)?**
https://wit.ai/sindre/WienBot-PROD

**Comment by jtliao** [comment]
cleaning up old issues, this is intended on our side for importing
