### ISSUE TITLE
Erroring object list

### ISSUE THREAD

**Issue by mashedkeyboard** [wit-ai/wit#517]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Feature request

It would be really great if we could have a list of all the erroring objects in the story we're building! We can find them manually by looking for the red objects in the story, but that doesn't allow you to quickly find them - especially if you have a very large story, as I do. It becomes impossible to hunt for all the errors without having an easily accessible list.

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
