### ISSUE TITLE
400 error on PUT sync request from web interface

### ISSUE THREAD

**Issue by mashedkeyboard** [wit-ai/wit#518]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
Seemingly random 400 Bad Request errors issued by the API's sync endpoint (and by the POST request to /ajax/bz on the main site) when called by the wit.ai interface

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Uncertain at this time, but a .HAR of the traffic is visible [here](https://pastebin.com/rpFDBLWy)

**What is the expected behavior?**
Synchronization without any issues

**What is the App ID where you are experiencing this issue (if applicable)?**
58de90e4-7da7-43b4-ae71-bc8f51590b80

**Comment by patapizza** [comment]
@mashedkeyboard Do you still experience the issue?

**Comment by mashedkeyboard** [comment]
Very difficult to tell: it happens completely randomly as far as I can see.

**Comment by patapizza** [comment]
Closing, feel free to reopen if it's coming back.

**Comment by mashedkeyboard** [comment]
Yep, I've got it again.
