### ISSUE TITLE
Using the weather app (slot-filling) with two variables.

### ISSUE THREAD

**Issue by ditikos** [wit-ai/wit#519]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
A question about wit

**What is the current behavior?**
![wit_weather_app](https://cloud.githubusercontent.com/assets/480594/25395260/2b8cbf46-29e9-11e7-8f06-3c46291e5f09.JPG)

**What is the expected behavior?**
If I ask for the weather without a location or a date, wit should ask me for location then a date (or vice versa).

**What is the App ID where you are experiencing this issue (if applicable)?**
58fcfb9f-9b6f-4176-be3f-812bcedd5bff

I am trying to use this with node.js, I have defined a promise over the getForecast() function like this:

```javascript
        // Action defined in our story.
        getForecast({ context, entities }) {
            //console.log(`Context-IN: ${JSON.stringify(context, undefined, 2)}`);

            return new Promise(function(resolve, reject) {
                const location = firstEntityValue(entities, 'location');
                const date = firstEntityValue(entities, 'datetime');
                //console.log(JSON.stringify(entities, undefined, 2));
                if (location) {
                    context.location = location;
                    delete context.missingLocation;
                    entitiesFound.location = context.location;
                } else if (entitiesFound.location != "") {
                    context.location = entitiesFound.location;
                    delete context.missingLocation;
                } else {
                    context.missingLocation = true;
                    delete context.forecast;
                    resolve(context);
                }


                if (date) {
                    console.log("Here!");
                    context.date = date;
                    delete context.missingDate;
                    entitiesFound.date = date;
                } else if (entitiesFound.date != "") {
                    console.log("Here 2");
                    context.date = entitiesFound.date;
                    delete context.missingDate;
                } else {
                    console.log("Here 3");
                    context.missingDate = true;
                    delete context.forecast;
                    resolve(context);
                }

                console.log(entitiesFound);

                if (context.location && context.date) {
                    //console.log("Both entities are having values");
                    context.forecast = '38 degrees';
                }

                //console.log(`Context is: ${JSON.stringify(context, undefined, 2)}`);
                //call the API here
                resolve(context);
            });
        }
```

But every time I get asked for the date again and again. I know there is a logic error there or something, can someone explain what is going wrong?

The scenario I am trying to achieve is:

> I want to know the weather in Rome in 10 minutes.
> The weather in {Rome} in {10 minutes} would be {38 degrees}

The above works.

> I want to know the weather.
> When?
> In 10 minutes.
> Where?
> In Rome
> The weather in {Rome} in {10 minutes} would be {38 degrees}

The above doesn't work, it constantly asks me for the "when".

**Comment by l5t** [comment]
You can check this wittyfiddle here: https://wit-ai.github.io/witty-fiddle/?id=5a387f6ccb4be4a1f77f2113747a558a

**Comment by ditikos** [comment]
Ok, so my problem is --- 
I have a location, date and forecast context. Also present are missingLocation and missingDate contexts.
When data is irrelevant (removed as entity so does the context keys of date and missingDate) everything works fine. When I also add the date, it loops through the datetime.

For example I might ask wit.ai:

[S0]> I want to know the weather.
It will start replying
[S1]> Where?
In Rome.
[S2]> When?
In 10 minutes
[S3]> Where?
...
> When?

Checking at the context object I can see it doesn't hold anything past S3 question and it starts all over again.  I remember on the old docs there were `context.missingLocation = true;` when Location was missing, but what about if date + location are missing and one of these two get populated?

It could be a generic programming thing, but I am stuck with it three days now  :)

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
