### ISSUE TITLE
Wit /samples endpoint timeout

### ISSUE THREAD

**Issue by hactar** [wit-ai/wit#520]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
When submitting bigger samples to the /samples endpoint, a timeout can occur after 2 minutes. The exact number of lines or entries is difficult to predict. I've had 400+ expressions succeed, but sometimes 300 expressions can fail.
 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Create a file with 1000 expressions and try to upload it to the /sample endpoint.

**What is the expected behavior?**
 - The /samples endpoint should not timeout - if necessary set a limit to the number of samples it can accept at once, but guarantee that it will not time out with that number of samples.
- What happens when the endpoint times out? Are some of the samples processed or is the app not updated at all? This is not explained in the documentation. 

Thanks.

**Comment by l5t** [comment]
cc @stopachka

**Comment by stopachka** [comment]
Great point @hactar looking into this, alongside a full fix now. Will update here with progress
