### ISSUE TITLE
Large App Optimisation

### ISSUE THREAD

**Issue by hactar** [wit-ai/wit#521]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question

I'm currently working with a customer's wit app which I've merged with one of my apps. The result app (https://wit.ai/hactar/WienBotNewTest/) has hundreds of stories, hundreds of entities, and thousands of samples. It appears we've reached a point where wit can't handle the app properly:

- We receive errors from the /converse endpoint at random points: 500 internal server error
- Responses, if they do complete, take 20+ seconds, which isn't really usable.

Are such big apps supposed to work? Is there anything we can do to optimise the app other than not using stories and doing those parts of the app in our backend instead?

**Testing**
Send "baden" to the app. The response will take 20+ seconds or fail with 500 internal server error. Each further call to complete the session and get all messages also takes 20+seconds  and has the chance to fail with 500 internal server error.

**Comment by blandinw** [comment]
hi @hactar, I'll have a look tomorrow.
It's definitely more Stories and Entities than we usually deal with. Do you have a hard time constraint on this?

Using your own code instead of Stories would certainly speed things up, but there may be low-hanging fruits for us to fix, I'll let you know.

We're also about to switch to the new pipeline for Entities processing, I'll check if things are faster there.

**Comment by hactar** [comment]
Thanks, time contraint in which I need it to work? Yesterday :). Or do you mean how quickly the response would need to complete - The usual up to 5 seconds would be good enough... The interesting part is that, individually the apps (https://wit.ai/hactar/Wave%20German768c-43b, https://wit.ai/sindre/WienBot-PROD) are fast enough, its the merge that appears to blow the limits.

**Comment by hactar** [comment]
You must have done something because the response time has dropped down to a few seconds, yeay!

But:
- Roles no longer work: "wie komme ich zum schwedenplatz" results in schwedenplatz being a vienna_public_transport_station and not a vienna_public_transport_station:to
<img width="928" alt="wit_ai_-_wienbotnewtest" src="https://cloud.githubusercontent.com/assets/645674/25461840/89e64b7c-2aeb-11e7-9bd6-1a6e701a3b1c.png">

- Weird entities with UUIDs as their name appear on my entity lists on the website as well as api results
<img width="927" alt="wit_ai_-_wienbotnewtest2" src="https://cloud.githubusercontent.com/assets/645674/25461888/d8a2beda-2aeb-11e7-98e7-b7ee6d6f8504.png">

**Comment by l5t** [comment]
I assume this was fixed. @hactar please reopen if not
