### ISSUE TITLE
Unable to work with wit.ai at all.

### ISSUE THREAD

**Issue by z4nD4R** [wit-ai/wit#523]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
*question*
**What is the current behavior?**
Hello all,

I know the topic looks pretty odd, but it is realy current situation for me. For me the whole wit.ai behaves doggy.

I can not add any "user defined" entity - Receives error: entity could not be created :(
I can not validate any expression - Expresioun could not be validated
I can not delete any user defined entity - Hit the trash, confirm and nothing happend
I can not delete my apps - the same behaviour like with previous issue
I was not able to create new app - Hit create nothing happend -> created via `curl`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
N/A

**What is the expected behavior?**
The page itself is working.

**What is the App ID where you are experiencing this issue (if applicable)?**
every App in my account.

**Comment by Sara-InfoSupport** [comment]
Me too; I can use it through Wit's console but my own app can't access it at all, getting 500 internal server error from Wit! I hope it's being worked on, and that someone could give us an ETA ...

**Comment by blandinw** [comment]
@Sara-InfoSupport can you provide us with an app id to look at?

@z4nD4R can you confirm that the issue still persists? Did you try refreshing the page? Did you see any error message?

**Comment by MathieuDuboy** [comment]
I have the same issue in my app : https://wit.ai/mathieuduboy/musees
Impossible to create/delete entities ... And by the way, I had to recreate some Bookmarks which has disappeared since last night (The were here last night !!)
Can you please restart my app please and/or look into it please @blandinw.
Thank you

**Comment by z4nD4R** [comment]
Hello All,

I can confirm the page is now working without any issues :)

Thank you for help.
