### ISSUE TITLE
Composite Entities not working

### ISSUE THREAD

**Issue by miteymouse** [wit-ai/wit#526]
I'm trying to make setNumerical as a Composite Entity with wit/number and minBedrooms as child entities.

When i go into setNumerical and check one of the expressions, it shows that it is correctly labelled but when i preview the API output, it gives an incorrect result.

![screen shot 2017-04-27 at 1 55 24 pm](https://cloud.githubusercontent.com/assets/5608505/25469951/23c0aa42-2b52-11e7-89d5-3264bf9f51b2.png)

When i test my bot in 'Understanding' tab, i've inputted 7 bedrooms it gives a result similar to the incorrect API output.

![screen shot 2017-04-27 at 2 00 25 pm](https://cloud.githubusercontent.com/assets/5608505/25469977/53496f7e-2b52-11e7-8969-1a4c5610fdec.png)

A bit of help please...thanks

**Comment by l5t** [comment]
I just tested and it works for me. For composite entities, you may need to validate at least 4-5 examples. Example here: https://wit.ai/lololando/testcomposite
