### ISSUE TITLE
Does not train my app data *bug*

### ISSUE THREAD

**Issue by tobi418** [wit-ai/wit#527]
whole day training does not work 17-04-27, my updated data does not trained, still responding old intent names. wit is down? or something happened?

**Comment by kresnoadiw** [comment]
Having the same issues here. Any updates?

**Comment by tobi418** [comment]
still training doesn't work

**Comment by l5t** [comment]
can you share your Wit app URL?

**Comment by l5t** [comment]
We just fixed an issue that was impacting. It should work now.
