### ISSUE TITLE
Stuck in 'Training status: ongoing" for hours

### ISSUE THREAD

**Issue by asstergiBSQ** [wit-ai/wit#528]
Hi @l5t ,

I have created an App on wit.ai. I had opened another ticket 20 days ago ([#476](https://github.com/wit-ai/wit/issues/476)) about wit.ai getting stuck on the training phase.

Today, the app gets stuck on the training phase for a lot of time, then goes green again but the system does not learn anything new.

Could you please restart the training?
Here is the like to the App: https://wit.ai/asstergi/Euroleague_chatbot/

**Comment by patapizza** [comment]
HI @asstergiBSQ,

Sometimes it does take a while to train - it seems like the issue is resolved.
Feel free to reopen if that's not the case.

Thanks
