### ISSUE TITLE
Destroy app doesnt work

### ISSUE THREAD

**Issue by lauraRuzicka** [wit-ai/wit#529]
I have an application. In its "Settings" I can click "Destroy app" and click "tick"/OK but nothing happens. 
I tried to repeat more than ten times since yesterday.

![image](https://cloud.githubusercontent.com/assets/25172366/25480831/dc87d1ac-2b4a-11e7-9acc-d8e12758b3d9.png)

I also tried deleting from "My Account" also without success.

![image](https://cloud.githubusercontent.com/assets/25172366/25480925/4cb6a598-2b4b-11e7-9311-49af98e76f76.png)

I did not receive any error but applications are not removed.

**Comment by l5t** [comment]
Thanks for reporting. I just tried and it is indeed taking a few seconds but it worked for me. Can you check if it eventually deleted your app?

**Comment by lauraRuzicka** [comment]
I tried again few moments ago and no success.
It is already 19 hours since my first attempt.

**Comment by l5t** [comment]
do you want me to try removing it? if so please provide your wit app url

**Comment by lauraRuzicka** [comment]
I tried again today
I failed to Destroy application at first
But then I changed application to Public
And then tried to Destroy application again and I succeeded.

I tried also to change the application to Public last time but it failed too.

**Comment by stopachka** [comment]
I am playing with the destroy button. The operation can take a while, and we don't provide any indication when it's happening. (this is leftover from the days of a younger wit, which had such few apps that operations were very fast)

-- 

will look into ways to make this clearer or faster

**Comment by lauraRuzicka** [comment]
For now the situation described above is much better.
