### ISSUE TITLE
Wit dashboard only show one trait entity

### ISSUE THREAD

**Issue by novan-p-simanjuntak** [wit-ai/wit#530]
I want to report a bug.

In the dashboard of my wit app, specifically in understanding and inbox tab, wit only show one trait entity even though I label it as 2 trait entity.
For example, my expression has two trait entity, I try to label using two trait entity but wit keeps forced showing only one trait entity. This is only happened in dashboard (understanding and inbox tab). When I call via wit api, the result is correct (wit api exactly return two trait entity).
Because of this I can not train new expression with multiple trait entity.
Strangely this only happened in this wit app, I try another wit app and it works correctly.

I expect I could train multilple trait entity in wit dashboard like usual.
Please help. Thanks.

**Comment by l5t** [comment]
cc @stopachka

**Comment by stopachka** [comment]
Get @novan-p-simanjuntak - could you tell me:

 - the name of your app
 - an example sentence that returns two trait entities

Apologies for the inconvenience, we in fact updated some logic here that could have caused the issue. Looking into it

**Comment by novan-p-simanjuntak** [comment]
My app name is BCA_BOT_PHASE1_DEV.
The sentence `cek saldo sama isi pulsa` should shows two trait entities (`check_balance` and `top_up_mobile_balance`), but it only show top_up_mobile_balance. In the first second wit correctly shows 2 trait entities, but then it shows only one.

**Comment by novan-p-simanjuntak** [comment]
Hi @stopachka , this problem happened again now. It's the same wit app. 
Could you please check? Thanks.

**Comment by stopachka** [comment]
Will do @novan-p-simanjuntak! I'll update here with what I find

**Comment by stopachka** [comment]
Update: bug identified -- fix will land in 24 hours!
