### ISSUE TITLE
Can't train yes_no entity to retain value

### ISSUE THREAD

**Issue by twisstosin** [wit-ai/wit#532]
bug

yes_no entity set to trait, not highlighted, still bot can't understand the entity

App ID : 58d0f6c4-ec8e-4f4e-88ac-18c22c2ec09f

#175 
<img width="721" alt="wit buging" src="https://cloud.githubusercontent.com/assets/12116352/25521057/21db90b2-2bf6-11e7-9412-ba041af8e92f.PNG">

<img width="567" alt="wit buging2" src="https://cloud.githubusercontent.com/assets/12116352/25521055/218501f2-2bf6-11e7-9b66-0be795e8e7c3.PNG">

**Comment by l5t** [comment]
can you share your Wit app URL?

**Comment by patapizza** [comment]
Looks like it's working.

![Understanding](http://i.imgur.com/rw0joJc.png)

![Stories](http://i.imgur.com/52YCO7Z.png)

**Comment by twisstosin** [comment]
Fixed by Removing and Adding back the entity.
