### ISSUE TITLE
500'ing

### ISSUE THREAD

**Issue by tpizzle** [wit-ai/wit#534]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

Getting 500 response
**What is the current behavior?**

Stories 500'ing randomly
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

Get 200 response
**What is the App ID where you are experiencing this issue (if applicable)?**

58d2c3e6-debc-4433-899a-eee73e38a912

**Comment by MathieuDuboy** [comment]
500 ERROR : Impossible to connect to my stories 
![capture d ecran 2017-05-01 a 08 36 31](https://cloud.githubusercontent.com/assets/11943636/25573844/5dce6aea-2e49-11e7-9679-a99db2da26f6.png)

**Comment by l5t** [comment]
should be fixed now. Closing
