### ISSUE TITLE
500 (Internal Server Error) on loading stories

### ISSUE THREAD

**Issue by MathieuDuboy** [wit-ai/wit#535]
I'm having trouble when I log in my console and want to see all my stories.
For each of them, always the same results : It's loading and nothing is shown.
I'm having this issue in browser console :
![capture d ecran 2017-05-01 a 08 36 31](https://cloud.githubusercontent.com/assets/11943636/25574712/0f4558a4-2e51-11e7-8c66-5473c22ae106.png)

You can test the behavior on your own with this link : https://wit.ai/mathieuduboy/test
Thank you !

**Comment by l5t** [comment]
It should be back to normal. Can you confirm?
