### ISSUE TITLE
wit responding very slow, what happened?

### ISSUE THREAD

**Issue by tobi418** [wit-ai/wit#536]
cannot access to wit control panel and api requests very very slow! what is happening?

**Comment by MathieuDuboy** [comment]
+1 ! I'm stuck and can't work with wit.ai today

**Comment by l5t** [comment]
Sorry for the inconvenience, we did have issues a few hours ago. It should be back to normal now.

**Comment by MathieuDuboy** [comment]
Confirmed ! Thanks a lot
