### ISSUE TITLE
Bot Returns Empty Variables

### ISSUE THREAD

**Issue by NikitaVr** [wit-ai/wit#537]
Question/Possible Bug

The Bot properly fills in variables with data when tested on the website but when sent a post from server it does not.

Story:
![story](https://cloud.githubusercontent.com/assets/10101970/25633305/ad9e1c0e-2f44-11e7-97fb-2224d6187e98.png)

Test on Website:
![websitetest](https://cloud.githubusercontent.com/assets/10101970/25633320/b757b78c-2f44-11e7-97a3-187dac75e18d.png)

Log of test from Server:

![chat](https://cloud.githubusercontent.com/assets/10101970/25633359/d3bffe5c-2f44-11e7-82e9-d301484bbe83.png)

![json](https://cloud.githubusercontent.com/assets/10101970/25633364/d6688386-2f44-11e7-8947-2d2a93f2c613.png)

The server does receive the message, and in the returned entities I can even see that the name is John, but the message itself does not contain the variable filled in with John, and instead contains an extra space where "John" should be.

Server runs dotnet core and accesses wit.ai through HttpClient.

Not sure if this is some mistake on my end or perhaps a bug.

App ID: 5836933f-ee25-4228-8199-d352c21b2cb6

**Comment by walez** [comment]
Hello @NikitaVr Please were you able to figure out a solution to this issue?

**Comment by NikitaVr** [comment]
@walez sorry but no luck so far. It is not a priority project for me so I set off the personal investigation until later.

**Comment by walez** [comment]
@NikitaVr thanks for the reply, I figured out what was wrong in my case.
Apparently it looks like you cannot use an entity variable in a _bot response_ with out first specifying an action function before it.

**Comment by NikitaVr** [comment]
@walez oh thank you! I think I might be missing the same thing. Will take a look at it when I have some time and report back here.

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
