### ISSUE TITLE
Cannot delete User-defined entity

### ISSUE THREAD

**Issue by javiercast** [wit-ai/wit#542]
Hello,

Im trying to train a new app, but the i have sever issues,
- cannot delete User-defined entity
- cannot destroy an app
- cannot create a new entity sometimes
- wit/greetings entity cannot use, sometimes.

appIDs 57167a2a-e793-40ad-99e8-11aaadb37f66

            590a43f7-9e63-40d3-ac5b-ce6225294fbd

**Comment by blandinw** [comment]
When you say "cannot", what do you mean? Does it hang, do you see an error message?

**Comment by javiercast** [comment]
I do not receive any messages, just do nothing..thanks for you attention

**Comment by blandinw** [comment]
hi @javiercast, I managed to create an app, destroy entities and destroy app on my end.
Is the issue still here? If not, how long did the issue persist?
Closing now.

**Comment by javiercast** [comment]
thanks @blandinw is working now...
