### ISSUE TITLE
http api "Add new values to an entity" does not work

### ISSUE THREAD

**Issue by tobi418** [wit-ai/wit#543]
requesting bug fix
problem is: cannot add new values to existing entities through http api.
followed this guide: https://wit.ai/docs/http/20170307#post--entities-:entity-id-values-link
http request returned following error "{ error: 'Something went wrong. We\'ve been notified.',code: 'wit' }"
it was working well 2 days before. not working since yesterday

my app id: 58be0f75-3f34-437f-843b-398918ce60db

**Comment by blandinw** [comment]
Thanks, looking into it.

**Comment by blandinw** [comment]
Thanks, you uncovered an actual inefficiency in the way we query our database.
This should be fixed, please reopen if this is not the case.

**Comment by tobi418** [comment]
thank you, it works now :)
