### ISSUE TITLE
I can't type 'a' in 'User says' text box in 'Understanding page'. 

### ISSUE THREAD

**Issue by UnnikrishnanBhargavakurup** [wit-ai/wit#544]
Hi,

I can't type letter 'a' in 'User says' text box, input focus automatically goes to 'Add a new entity' box. But I can copy my text from a text editor to that input field. 

example:

if I type 'apple' in 'User says' text box. 'pple' will come in 'Add a new entity' box and nothing is showing in 'User says' text box.

Seems like some javascript issue.

Thanks.
Unnikrishnan B.

**Comment by UnnikrishnanBhargavakurup** [comment]
Now it's working find, thanks for the fix.

**Comment by UnnikrishnanBhargavakurup** [comment]
This is happening again but randomly, not know exact steps to replicate the issue.

**Comment by stopachka** [comment]
Hey Unni, `A` is the keyboard shortcut to open the entity editor. This should only happen if you are not already `focused` in the User says text box.

When this happens, where you actually focused on the user says text? If yes, a demo video could help me figure out what is the issue

**Comment by UnnikrishnanBhargavakurup** [comment]
@stopachka,

This issue is not happening every time. I couldn't replicate it now may be we close this issue for now and if it happens again we will reopen it.

Thanks,
Unnikrishnan B.

**Comment by mark-stephenson-** [comment]
Its happening to me :(  Itermittently.  

I've just gone to make a video and its working 😄 / 😢

**Comment by 610** [comment]
@stopachka Personally I didn't have this issue (mac), but my colleague on windows machine experiencing this issue all the time. 
As I understand it happens when you are navigating from stories to understanding tab, the 'a' button is not released from shortcut event and you can not type it anywhere since then. His workaround is to close the page and open it again.

**Comment by stopachka** [comment]
That helps a lot @610 -- Could you tell me what browser and version he is using on windows?

**Comment by stopachka** [comment]
(closing, please reopen if repro)
