### ISSUE TITLE
Bad auth, check token

### ISSUE THREAD

**Issue by danielkhan** [wit-ai/wit#545]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
After a number of requests the API replies with `"Bad auth, check token\\/params","code":"no-auth"`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Send a few requests. Tried to use Bearer token auth as well as passing the token as request parameter

**Comment by stopachka** [comment]
hey @danielkhan looking into this now!

**Comment by stopachka** [comment]
(Update: the fix should have gone like about 5 hours and 30 minutes ago) -- let me know if anything!

**Comment by danielkhan** [comment]
Looks good thank's for the fast response!
