### ISSUE TITLE
i need to integrate my app '(stories) in my application nodejs

### ISSUE THREAD

**Issue by iliasabdelali** [wit-ai/wit#546]

**Comment by iliasabdelali** [comment]
intergrat with nodejs >>> tutoriel

**Comment by patapizza** [comment]
HI @iliasabdelali,

You check out the `examples` provided with the `node-js` project, e.g. https://github.com/wit-ai/node-wit/blob/master/examples/quickstart.js.

**Comment by iliasabdelali** [comment]
thanks you


2017-05-09 20:12 GMT+01:00 Julien Odent <notifications@github.com>:
