### ISSUE TITLE
'to' date gets transformed to next date.

### ISSUE THREAD

**Issue by swapkh91** [wit-ai/wit#547]
When I enter a date like 5/7/2017 to 5/8/2017 it gets transformed to 5/7/2017 to 5/9/2017. Why is it so? 
It shows 12 AM maybe that's the reason, if so, what's the workaround?
![sss](https://cloud.githubusercontent.com/assets/5755405/25797418/be015984-33fa-11e7-94e7-966a593b4c87.PNG)

**Comment by patapizza** [comment]
@swapkh91 The `wit/datetime` entity is powered by [Duckling](https://github.com/facebookincubator/duckling). For time, Duckling returns left-closed, right-open intervals (exclusive upper limit). In your example, you provided dates so the time grain is `day`. Days start at 12am.
To get the inclusive upper limit, you'd need to do something like: `to` - `grain`.
