### ISSUE TITLE
Multiline replies in stories

### ISSUE THREAD

**Issue by Vinno97** [wit-ai/wit#549]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Feature

**What is the current behavior?**
There isn't currently any way (to my knowledge) to respond with multiline text in stories. I have tried to use both `shift + enter` and `\n`.

I currently have the following:
![image](https://cloud.githubusercontent.com/assets/9059378/25828295/bf2308d0-344f-11e7-84e9-9e70791d5cbf.png)

**What is the ~~expected~~ desired behavior?**
I'd like to have the `{source}` on a new line like on the following (photoshopped) screenshot:
![image](https://cloud.githubusercontent.com/assets/9059378/25828520/db72d578-3450-11e7-8fe5-779126e1e578.png)

This does not seem that hard to implement, but would allow for a lot more customization of the responses.

**Comment by patapizza** [comment]
Hi @Vinno97,

This is a good point. In the meantime, you can hack it by adding a special token and replace it before sending the bot response.

**Comment by Vinno97** [comment]
Thank you patapizza,

Yes, I ended up using the section sign `§` to act as a newline character. Just thought I might as well make a feature request.

**Comment by patapizza** [comment]
Hey @Vinno97, multilines replies are now supported.

**Comment by vpebrouw** [comment]
Thank you, that was also pretty quick!
