### ISSUE TITLE
API output preview not consistent with whats displayed in UI

### ISSUE THREAD

**Issue by miteymouse** [wit-ai/wit#550]
I've tried to train 'Hi' to include a 'Greetings' intent multiple times.  But when i check the API output, it doesn't show the intent.

Am i doing something wrong?  

Thanks in advance.

![screen shot 2017-05-10 at 11 08 59 am](https://cloud.githubusercontent.com/assets/5608505/25881775/80c72b98-3571-11e7-8648-fb98323262ca.png)

**Comment by stopachka** [comment]
Hi @miteymouse what is your username and app in wit? (can take a look)

**Comment by miteymouse** [comment]
chenghtmark propbot

**Comment by l5t** [comment]
I just tested and the issue seems to be fixed now. Closing
