### ISSUE TITLE
Cannot validate or delete expressions in my Inbox

### ISSUE THREAD

**Issue by joshuacrowley** [wit-ai/wit#551]
**bug**

Trying to validate some of my expressions here -> https://wit.ai/joshuacrowley/Jiro/inbox/semantic

When I click validate, they disappear and then return after a second.

Console log returns: PUT https://api.wit.ai/sync?verbose=true 500 (Internal Server Error)

I cannot delete them either. I think these expressions could be months old.

**Comment by stopachka** [comment]
Hey @joshuacrowley, apologies this task fell through.

took a look, and the cause was due to an error we had with metadata on the entities. Pushed a fix, and now the validation is working.

**Comment by vikitries** [comment]
Problem still persists and can't delete or validate items in inbox?
Can anyone help?

**Comment by l5t** [comment]
Which app are you experiencing this issue?
