### ISSUE TITLE
Empty logs

### ISSUE THREAD

**Issue by skakben** [wit-ai/wit#552]
My app is not showing the logs anymore. When looking at the request i can see that there is a GET being made to https://api.wit.ai/threads?limit=15&offset=0. That is responding with a 500 and "Something went wrong. We've been notified.". This has been the case for atleast two months now.

My APP-id id 585a4b45-efb5-4f4e-86a9-86b6c599a9e9

**Comment by araczkowski** [comment]
I have the same on the page with logs 
and additional on the Inbox 
api.wit.ai/threads?limit=15&offset=0
"Failed to load resource: the server responded with a status of 500 (Internal Server Error)"

**Comment by skakben** [comment]
I managed to solve this by creating a new application and exporting and importing the faulty one into the new. Then everything was back to normal. However i believe that all old logs was removed. But new ones started to appear in the new app.

**Comment by araczkowski** [comment]
Thanks for the tip, I will try this workeround tomorrow.
Btw
My impression is that somethings  goes wrong wit.ai, so I started to learn tensorflow

**Comment by araczkowski** [comment]
hi @skakben again thank you for the hint
unfortunately it doesn't work for me - still the same problem in logs:

> GET https://api.wit.ai/threads?limit=15&offset=0 

> 500 (Internal Server Error)

but the inbox is back, I can see and I can manage the "Expressions", so there is a progress

**Comment by l5t** [comment]
I just checked and it seems to work now. Please reopen if you still experience the issue
