### ISSUE TITLE
Bug in GET /message endpoint

### ISSUE THREAD

**Issue by Orisbaum** [wit-ai/wit#553]
Hey,
When i query the message endpoint with a GET command i don't get the metadata back in the JSON
Example:
GET https://api.wit.ai/message?v=20170307&q=יש לי פיפי
app id : 587f3ea0-7c4e-4b53-8c03-80d857636679

Outcome JSON:
{
  "msg_id": "0diRSG4govU2q8zkL",
  "_text": "יש לי פיפי",
  "entities": {
    "intent": [
      {
        "confidence": 0.93674614201095,
        "value": "search_for_restroom"
      }
    ]
  }
}

When i try the same thing with a POST command:
POST https://api.wit.ai/message?v=20170307&q=יש לי פיפי
app id : 587f3ea0-7c4e-4b53-8c03-80d857636679

I do get the metadata field.
Outcome JSON:
{
  "msg_id": "68579eb5-2f18-404f-914f-084da3c4b4f7",
  "_text": "יש לי פיפי",
  "entities": {
    "intent": [
      {
        "confidence": 0.9367461420109483,
        "metadata": "SNTC_search_for_restroom",
        "value": "search_for_restroom"
      }
    ]
  }
}

the q value is in Hebrew.
Thanks in advance!

**Comment by stopachka** [comment]
Thanks for the report @Orisbaum looking now

**Comment by stopachka** [comment]
Hey @Orisbaum there was a transient error. I went ahead and updated this lookup. If there is an issue, try saving the lookup once more. In the meantime, I'll look to see a fuller fix

**Comment by Orisbaum** [comment]
Hey, @stopachka 
I've encountered the same issue with different app ( this time in English):
app-id: 58f86eee-1ab2-4d53-8cf7-8289990455d0

GET https://api.wit.ai/message?v=20170307&q=i love jerusalem output:
{
  "msg_id": "0Jhw03BQCLiY2Ge07",
  "_text": "i love jerusalem",
  "entities": {
    "location": [
      {
        "suggested": true,
        "confidence": 0.99076647603319,
        "value": "jerusalem",
        "type": "value"
      }
    ],
    "intent": [
      {
        "confidence": 0.95938004248656,
        "value": "jerusalem_info"
      }
    ]
  }
}
POST https://api.wit.ai/message?v=20170307&q=i love jerusalem output:
{
  "msg_id": "12e9d4e8-88cf-4eb1-b625-b5660f893e78",
  "_text": "i love jerusalem",
  "entities": {
    "location": [
      {
        "confidence": 0.9907664760331903,
        "type": "value",
        "value": "jerusalem",
        "suggested": true
      }
    ],
    "intent": [
      {
        "confidence": 0.9593800424865582,
        **_"metadata": "SNTC_jerusalem_info",_**
        "value": "jerusalem_info"
      }
    ]
  }
}
