### ISSUE TITLE
Messages not received from facebook messenger

### ISSUE THREAD

**Issue by d4rkspir1t** [wit-ai/wit#554]
I am experiencing a bug when using a modified version of pywit's [messenger example](https://github.com/wit-ai/pywit/blob/master/examples/messenger.py).

I am running ngrok with port 80, which provides a webhook when the messenger script from pywit is run. Everything is set properly in facebook, but whenever I send a message, nothing happens, it's like the webhook is not receiving anything. However, when I enable the facebook messenger integration through API.AI and leave all the settings (callback URL, tokens) to point to the messenger script, the messages come through and I can converse with the bot.

Do you know what I can do about it or how I could avoid always switching on the api.ai integration to receive messages?

Wit [app ](https://wit.ai/d4rkspir1t/MessengerTrial-2)ID: 591011d7-7055-43aa-9508-2fc1750381e2

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
