### ISSUE TITLE
Something went wrong. We've been notified.

### ISSUE THREAD

**Issue by swapkh91** [wit-ai/wit#555]
Getting this error since this morning

**Comment by sindre** [comment]
+1

**Comment by l5t** [comment]
just tested and it worked for me. Do you mind sharing what type of API call you're doing?

**Comment by l5t** [comment]
Should be better now!

**Comment by UnnikrishnanBhargavakurup** [comment]
I'm also getting the error when accessing by curl.

`    <div id="core">
      <h1 id="sorry">Sorry, something went wrong.</h1>
      <p id="promise">
        We're working on it and we'll get it fixed as soon as we can.
      </p>
      <p id="back-link">
        <a id="back" href="//www.facebook.com/">Go Back</a>
      </p>
      <div id="footer">
        Facebook
        <span id="copyright">
          &copy; 2017
        </span>
        <span id="help-link">
          &#183;
          <a id="help" href="//www.facebook.com/help/">Help Center</a>
        </span>
      </div>
    </div>`

please look into it.

Thanks,
Unnikrishnan B.

**Comment by patapizza** [comment]
We should be back. Sorry about that.

**Comment by UnnikrishnanBhargavakurup** [comment]
Hi,

I am still getting this error, anything I need to do from my end? or is it a different issue?

Thanks.
Unnikrishnan B.

**Comment by swapkh91** [comment]
working for me now

**Comment by UnnikrishnanBhargavakurup** [comment]
Yes, now it's working fine thanks for the fix!

**Comment by sarfarazengglb** [comment]
still its coming

**Comment by sarfarazengglb** [comment]
Its working fine with Node Wit Client.
