### ISSUE TITLE
Question : Wit converse api returning "Model not found" error

### ISSUE THREAD

**Issue by anujmehta** [wit-ai/wit#559]
I had created an app and the message api works fine. When I started accessing Converse api I get following response 

`{"body":"Model not found"}`

Following is my request

`curl -XPOST 'https://api.wit.ai/converse?v=20170515&session_id=123abc&q=find%20nearby%20churches' -H "Content-Type: application/json" -H "Accept: application/json" -H 'Authorization: Bearer $myToken'`

Am I missing something here? How can I see the logs? Kindly let me know if I am making any mistake?

**Comment by anujmehta** [comment]
Can someone please help me with this? I am unable to use the converse api. Are there any logs which I can help me in debugging this issue?

**Comment by patapizza** [comment]
Hi @anujmehta,

Do you have any stories? Is the training status of your stories green?

**Comment by patapizza** [comment]
@anujmehta Feel free to reopen if you experience the issue and confirm my questions above.

**Comment by lamkent00** [comment]
Hi everyone,
I'm try to running messenger.js and get error:
[wit] [converse] Error: Model not found (404)
Google tell me must create a story for bot.
But it was solusion in 2016. For now, WIT notification Stories and POST /converse have been deprecated. This will break in February 2018!
==> So, anyone can help me to pass it plz ? any solusion for this problem in 2017 ?
