### ISSUE TITLE
Wit Error

### ISSUE THREAD

**Issue by richwednesday** [wit-ai/wit#560]
`Oops! Got an error from Wit: SyntaxError: Unexpected token S in JSON at position 0 at Object.parse (native)`

This is the error that gets printed out when the user sends a message ('Hi' in this instance). It works sometimes and at other times,  it just throws this error. I don't really know if this is a problem from Wit or my code though.

**Comment by stopachka** [comment]
Hi @richwednesday -- do you have some sample code we can take a look at? or the stacktrace that follows that error?

**Comment by richwednesday** [comment]
My app is currently live, and I don't know what triggers this error. It just pops up in some messages. I'll copy the stack trace when next it shows up. Thanks.

**Comment by patapizza** [comment]
This happens because the response is `Something went wrong. We've been notified.`.
To make sure you always receive JSON, set the `Accept` header to `application/json`.

The underlying issue might be a transient error - you might want to implement a retry policy.

**Comment by hoerlanton** [comment]
I wanted to get started with the Node.js SDK for Wit.ai. I followed the steps according to the comments in the messenger.js file:

// 1. npm install body-parser express request

// 2. Download and install ngrok from https://ngrok.com/download

// 3. ./ngrok http 8445

// 4. WIT_TOKEN=your_access_token FB_APP_SECRET=your_app_secret FB_PAGE_TOKEN=your_page_token node examples/messenger.js

// 5. Subscribe your page to the Webhooks using verify_token and https://<your_ngrok_io>/webhook as callback URL.

// 6. Talk to your bot on Messenger!

When I send a message to the server via Facebook messenger I receive the following error:

invalid json response body at https://f91805fe.ngrok.io/converse?session_id=2017-08-06T15%3A37%3A04.862Z&q=ldldl reason: Unexpected token T in JSON at position 0 invalid-son Oops! Got an error from Wit: Error at /Users/antonhorl/Documents/projekte-lokal/HotelMessenger/bots/node-wit-bot/node_modules/node-fetch/lib/body.js:49:31 at at process._tickCallback (internal/process/next_tick.js:188:7)

My node version is the latest stable one.

Has somebody any idea why? Thanks a lot for the effort.
