### ISSUE TITLE
POST /samples always returns 'Failed to validate sample at index 0'

### ISSUE THREAD

**Issue by swapkh91** [wit-ai/wit#563]
I'm testing the endpoint /samples to train a new app but every time I get the response 
`{
  "error": "Failed to validate sample at index 0",
  "code": "bad-request"
}`

I'm trying the request given on the [HTTP API](https://wit.ai/docs/http/20170307#post--samples-link) reference itself.

I tried 2 things:

1. Create intent 'flight_request' and then POST /samples - gives the error stated above
2. Directly POST /samples - gives response
`{
  "error": "You tried to create 'intent'. Use POST /entities instead",
  "code": "bad-request"
}`

**Comment by stopachka** [comment]
hi @swapkh91 what does your request look like?

**Comment by swapkh91** [comment]
I'm using the one stated on the HTTP API page itself.
`curl -X POST \
  'https://api.wit.ai/samples?v=19%2F05%2F2017' \
  -H 'authorization: Bearer <>' \
  -H 'content-type: application/json' \
  -d '[{
	"text": "I want to fly to sfo",
    	"entities": [
        	{
            	"entity": "intent",
            	"value": "flight_request"
        	},
        	{
        		"entity": "wit$location",
            	"start": 17,
            	"end": 20
        	}
        ]
}]'`

So if the app is empty and I try this, I get the response:
`{ "error": "You tried to create 'intent'. Use POST /entities instead", "code": "bad-request" }`

Then I create an intent:
`curl -X POST \
  'https://api.wit.ai/entities?v=19%2F05%2F2017' \
  -H 'authorization: Bearer <>' \
  -H 'content-type: application/json' \
  -d '{"doc":"Flight Request",
       "id":"intent",
       "values":[{"value":"flight_request"}]}'`

And try the /samples request again and I get:
`{
  "error": "Failed to validate sample at index 0",
  "code": "bad-request"
}`

**Comment by choufractal** [comment]
I had the same problem, and it was solved here: https://github.com/wit-ai/wit/issues/557

**Comment by swapkh91** [comment]
@choufractal thanks for the reply, the solution works. But as @stopachka mentioned there are 3 points to implement so I guess they are not yet done.
Also @stopachka could you please update the docs to include `"value": "sfo"` in the entity for the time being. I'm sure others will also run into the same problem and raise issues on git.

Thanks again.

**Comment by stopachka** [comment]
Added to the list of action items. Thanks for the idea @swapkh91!
