### ISSUE TITLE
Question: How to get response like in interactive mode?

### ISSUE THREAD

**Issue by makoy21** [wit-ai/wit#564]
Here the code using converse api:

```
const {Wit, log} = require('node-wit');
const interactive = require('node-wit').interactive;
//Extract an entity value from the entities returned by Wit
const firstEntityValue = (entities, entity) => {
  const val = entities && entities[entity] && Array.isArray(entities[entity]) && entities[entity].length > 0 && entities[entity][0].value;
  if (!val) {
    return null;
  }
  return typeof val === 'object'
    ? val.value
    : val;
};

const accessToken = '';
const actions = {
  send(request, response) {
    const {sessionId, context, entities} = request;
    const {text, quickreplies} = response;
    console.log('sending...', JSON.stringify(response));
  },
  findPlayerProfile({context, entities}) {
    var player = firstEntityValue(entities, 'player');
    if (player) {
      context.player = player + ' profile here'; // we should call a  API here
      console.log('Player found');
    } else {
      console.log('No player found');
    }
    return context;
  }
};
const client = new Wit({
  accessToken,
  actions
});

// converse
client.converse(new Date().getMilliseconds().toString(), 'Who is mario?', {}).then((data) => {
  console.log('Yay, got Wit.ai response: ' + JSON.stringify(data));
}).catch(console.error);

// interactive(client);
```

result: `Yay, got Wit.ai response: {"confidence":1,"type":"action","action":"findPlayerProfile","entities":{"player":[{"confidence":0.8727827778067268,"type":"value","value":"mario","suggested":true}],"intent":[{"confidence":0.9862693117393985,"value":"findPlayerProfile"}]}}`

What I want is the return when interative mode, Like this: 
![wit](https://cloud.githubusercontent.com/assets/9860394/26152117/4ba47e8a-3b38-11e7-918f-3abaf47e7641.png)

**Comment by patapizza** [comment]
In interactive mode, the bot response is shown (in this case, "Your about to know mario profile here"). The bot response is send through the `send` action.
Under the hood, `interactive` uses `runActions` which calls `converse` until the bot has nothing left to do (`stop`). So here you'd need to keep calling converse until a `stop` type action is returned (as described here: https://wit.ai/docs/http/latest#post--converse-link). When the action type is `msg`, you will get what you are looking for.
I recommend using `runActions` over `converse`, which returns the updated context.
