### ISSUE TITLE
Can't go to the next step of the story

### ISSUE THREAD

**Issue by ThibautCantet** [wit-ai/wit#565]
I have a bug with my story :

When I validate the 7th steps (over 10 steps) of my story (for each step I update context key), it blocks to this step. If I remove the context, the story continues. But I can't validate the user's input.

The context is correctly updated but the bot doesn't go to the next step (8th).

Why ?

My App ID : 58ef669f-e6a6-4f8f-a8c6-71c910769797

**Comment by patapizza** [comment]
Are you referring to the "Commande d'encre" story, step "du lundi au vendredi"? Are you sure of the implementation of `saveOpeningTimeContext`?

The HTTP request/response would be useful with expected/actual.

**Comment by ThibautCantet** [comment]
Yes, this is the "Commande d'encre" story.
Even in the web chat preview, the flow is blocked.
The implementation is the same for each step.

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
