### ISSUE TITLE
/message endpoint offline: 503 no servers available.

### ISSUE THREAD

**Issue by hactar** [wit-ai/wit#566]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**

When trying to use the /message endpoint, wit returns a 503, no server available for this request error.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

See: https://paw.pt/cll6xScT

**What is the App ID where you are experiencing this issue (if applicable)?**
Trying to use https://wit.ai/hactar/Wave%20German768c-43b

**Comment by hactar** [comment]
The /converse endpoint appears unaffected.

**Comment by JoabMendes** [comment]
The same is happening with me. Yesterday the endpoint was offline for around 30 min and today it has been already 2hs offline. /:

**Comment by joechoi-git** [comment]
When accessing message endpoint using "node-wit" library, we are getting an error as well.

SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at .../node_modules/node-fetch/lib/body.js:43:15
    at process._tickCallback (internal/process/next_tick.js:103:7)


Also, noticing that https://wit.ai/ website is down.

**Comment by JoabMendes** [comment]
I believe all the services are down. I tried to find any report about this from the wit org and couldn't find anything. That is really sad when a lot of my services depend on them.

**Comment by l5t** [comment]
just tested and it works for me, can you provide a curl that failed

**Comment by swapkh91** [comment]
its working

**Comment by l5t** [comment]
thanks for confirming.

**Comment by patapizza** [comment]
Sorry for the inconvenience. We had an issue between 12:40pm and 5:30pm, affecting /message and the website.
@JoabMendes We communicated the issue as soon as we noticed it in the Wit.ai Hackers group.

**Comment by JoabMendes** [comment]
@patapizza nice. Where could I connect with the group? :smile:

**Comment by patapizza** [comment]
@JoabMendes https://facebook.com/groups/withackers/

**Comment by JoabMendes** [comment]
@patapizza thanks
