### ISSUE TITLE
Import of Project Data fails

### ISSUE THREAD

**Issue by vibee** [wit-ai/wit#567]
Hi,
if i try to create a new App from the attached Files, the wit.ai Plattform tells me "We are creating your instance. Please do not refresh". After a while, the dialog disappears and no app is created. 
Please find my imported Zip File attached.

[Archiv.zip](https://github.com/wit-ai/wit/files/1010827/Archiv.zip)

**Comment by vibee** [comment]
Hi,
if i try to create a new App from the attached Files, the wit.ai Plattform tells me "We are creating your instance. Please do not refresh. After a while, the dialog disappears and no app is created. 
Please find my imported Zip File attached.

[Archiv.zip](https://github.com/wit-ai/wit/files/1010827/Archiv.zip)

**Comment by jtliao** [comment]
Merge with #513
