### ISSUE TITLE
Wit ai portal stopped working for one app

### ISSUE THREAD

**Issue by Krmenaldo** [wit-ai/wit#568]
My app SoggetaEnglish stopped working. When I try to open it from the browser I get 500 error. My other app Soggeta works fine.

**Comment by swapkh91** [comment]
same here

**Comment by mingyangzhou1226** [comment]
Same here.  The app is in "training mode" forever. When I refresh the page, I cannot access it anymore.

**Comment by chemok78** [comment]
I have this problem too:

Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by nikhilsaldanha** [comment]
I think it is having issues opening the bigger apps. I have an app with just a couple of entities and stories and it opens up just fine, but another app with a large number of stories and intents fails to open

**Comment by patapizza** [comment]
Hey guys, we had an issue since 4:54am PDT that is partly resolved (affects apps that use stories). I'll update here when the console is back. Apologies for the inconvenience!

**Comment by chemok78** [comment]
Hi, still having this problem...

**Comment by rciyihm** [comment]
Same here.

**Comment by l5t** [comment]
Thanks for your patience, we won't be able to fix the console until Monday morning PT

**Comment by krishadvani** [comment]
When user says 'hi' it identifies entry "bot_smalltalk" which is correct, but it should trigger "hi" rather than "thanks". I tried changing that entry several times, but it is not switching.

Url: https://wit.ai/QuickWorkDeveloper/QarmaBot/

**Comment by mightystrong** [comment]
Happening to my app as well. Looking forward to the sun rising on the West Coast :).

**Comment by patapizza** [comment]
Sorry for the delay here. This will be fixed tomorrow morning PT.

**Comment by patapizza** [comment]
It should be fixed now.
