### ISSUE TITLE
Builtin entity datetime is gone

### ISSUE THREAD

**Issue by choufractal** [wit-ai/wit#569]
Hello,
There might be a bug with the builtin entity datetime. Since a few minutes ago, I can't find it in the entity list and it has been replaced by a $wit/wdatetime with the description "DO NOT USE: datetime experiment".
Did you decide to remove the builtin datetime?

**Comment by GreasyBacon** [comment]
@choufractal beat me to it. 

In the wit.ai interface, it looks like it's still highlighting the entity phrase but it doesn't come up as an entity value.  

![no_entity](https://cloud.githubusercontent.com/assets/5730803/26249033/4eb6c762-3c6a-11e7-996c-0b5489c05dbe.png)

**Comment by patapizza** [comment]
Hi @choufractal, indeed wit/datetime vanished for English at 4:54am PDT. The /message API was not affected. The entity should be back now. Sorry about that!

**Comment by amtdevops** [comment]
Hi, 
For my app also wit/datetime not showing in the entity list.
