### ISSUE TITLE
Can't access my app in wit.ai console

### ISSUE THREAD

**Issue by UnnikrishnanBhargavakurup** [wit-ai/wit#570]
Hi,

I can't access my app in wit.ai console. Could you please see the attached screenshot, it's keep on loading.

<img width="1428" alt="screen shot 2017-05-20 at 4 54 24 pm" src="https://cloud.githubusercontent.com/assets/825646/26275414/51c5c0f2-3d7d-11e7-89df-d0beab38343e.png">

Thanks,
Unnikrishnan B.

**Comment by billchalmers** [comment]
Same issue here, both apps,

Dev console is showing http 500

**Comment by l5t** [comment]
We are still investigating the issue. Thanks for your patience. cc @patapizza

**Comment by l5t** [comment]
#568
