### ISSUE TITLE
My app is stuck in "training mode"

### ISSUE THREAD

**Issue by HimadriP** [wit-ai/wit#571]
says "training status:ongoing"
https://wit.ai/HimadriNitk/Beatest/
App ID : 59202f0c-ac0b-46d7-be5f-08ff93f6ae18

**Comment by paulopadopalos** [comment]
I've got the same problem - App ID: 58e3e532-34cd-4e3c-9e88-5f5ece6a165f

**Comment by l5t** [comment]
@HimadriP should be good now. @paulopadopalos  can you share your wit app URL?

**Comment by paulopadopalos** [comment]
Here you go: https://wit.ai/paulopadopalos/timetablebot/entities

**Comment by l5t** [comment]
Done

**Comment by paulopadopalos** [comment]
Legend. Thank you!

**Comment by HimadriP** [comment]
Thank you!

**Comment by HimadriP** [comment]
Did we go wrong somewhere? For future reference, so that we won't raise the
issue again!

**Comment by l5t** [comment]
Nothing on your side, sometime the training gets stuck.

**Comment by HimadriP** [comment]
Oh okay, thanks again!
