### ISSUE TITLE
training entities is not working

### ISSUE THREAD

**Issue by eoquendo** [wit-ai/wit#572]
report a bug

problem:
- created two new trait entities called "ecoexploratorio" and "eclipse_lunar" 
- added multiple expressions like - "ecoexploratorio" to entity:"ecoexploratorio"
- when I test the app it does not recognize this entity 

steps:
- see expressions of entity "ecoexploratorio"
- test the app with one of those expressions (e.g. when I use "https://api.wit.ai/message?v=20170515&q=ecoexploratorio&n=2" it does not even show the new entity in the list)

expected behavior:
- it should match entities when trained

app-id --> 58972b13-3d69-4936-8cab-84586c659ee2

**Comment by PaulRosset** [comment]
The "**Extract an entity that generally takes a value in a predefined list (open enum), but you are open to new values**" functionalities from the doc, is not working anymore aswell, even when I train a lot my entity.

**Comment by patapizza** [comment]
@eoquendo Can you try again now and report back?

@PaulRosset What's your app id? Do you have an example that doesn't work?

Thanks

**Comment by PaulRosset** [comment]
My app Id : 5912346f-25be-4b50-adff-5b44e01de1a1

Expected result : 
I want to have the same behavior of this : "Extract an entity that generally takes a value in a predefined list (open enum), but you are open to new values" like the doc.

What im doing :

I got a sentence like this : 
  - "3 meaning of find"

This sentence is cut in 3 entitys, 
 - The **number** with 'wit/number', (3) (optional)
 - The **identificator** , User defined, who is 'meaning of' (mandatory)
 - And finally the **word** entity, User defined,  which is there 'find', but it will be always a new word, so Im  open to a new values. (mandatory)

Even with a hard train, it didnt pay off :)

Problem :
  The number and identificator aren't a problem, they are always found.
  The problem come from the **word** entitys, which is never recognized, if its a new value.

Thanks, :)

**Comment by patapizza** [comment]
It looks like you've validated 8 expressions having `word`. Can you try training more and see if it helps?

**Comment by PaulRosset** [comment]
I validated now 20 expressions. 
I got an entity named 'account', this one work perfectly with the behavior of new value.

**Comment by eoquendo** [comment]
@patapizza it is working now. Was this a bug from the wit side or was it something I could prevent next time?

**Comment by patapizza** [comment]
@eoquendo Great! We had an issue in our backend.

@PaulRosset Closing this one, feel free to open a new issue.
