### ISSUE TITLE
Wit/bye Entity Not Deleting

### ISSUE THREAD

**Issue by richwednesday** [wit-ai/wit#573]
My App ID is 58ee873f-fa8a-4802-b80d-6f8c0144e32a

The wit/bye Entity is very buggy and for messages that are not related to 'goodbye', it pops up and replies the user. I am trying to delete this entity but it's not working.

Is it possible to remove this entity from your end.
Thank you.

**Comment by l5t** [comment]
Can you share your wit app url? cc @patapizza

**Comment by patapizza** [comment]
@richwednesday Thanks for the feedback. Do you have examples of messages? Did you try setting a higher confidence threshold?

**Comment by richwednesday** [comment]
@patapizza It just keeps replying users with 1 or 0. I just want to delete the wit/bye entity. Examples of such messages are;
What's showing at ozone today, Ozone, Most Thumbnails seem not to be loading, I want to eat ofada etc.
They are really many and is causing users to leave the bot.
Thank you.

**Comment by richwednesday** [comment]
Also, my stories have just been loading since yesterday and it's not turning green. I can not create a new story.

**Comment by richwednesday** [comment]
This has been fixed.

**Comment by patapizza** [comment]
@richwednesday Confidence thresholds range between 0 and 1. You can see it as a percentage. One thing you can try is to set it to a high value like 0.85 or 0.9 and see if it improves the precision.

**Comment by richwednesday** [comment]
@patapizza Thank you. One more thing, my app is replying users with 1 or 0. Why is this so?

**Comment by patapizza** [comment]
@richwednesday Not sure, I don't see any bot sends with "1" or "0" in your stories. Do you have a request/response example?
