### ISSUE TITLE
My app is always training

### ISSUE THREAD

**Issue by gcolmen** [wit-ai/wit#575]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
The training status of my app is stuck in "ongoing" after several days.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
It should pass to "clean" after a couple of minutes...

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by l5t** [comment]
Can you share the wit app URL?

**Comment by gcolmen** [comment]
Sure!! It's:
https://wit.ai/gcolmen/BilingoBot/entities

Thanks a lot for your support!

**Comment by tpizzle** [comment]
I'm having this issue as well @l5t could I also get a reboot? https://wit.ai/tpizzle/2MG-2.4.1

**Comment by l5t** [comment]
restarted
