### ISSUE TITLE
wit does not train

### ISSUE THREAD

**Issue by tobi418** [wit-ai/wit#576]
app id : 58be0f75-3f34-437f-843b-398918ce60db
wit does not train new data

**Comment by l5t** [comment]
please share your Wit app url?

**Comment by tobi418** [comment]
https://wit.ai/tobi418/ckbankbot

**Comment by l5t** [comment]
Seems to be trained. Can you share an example?

**Comment by tobi418** [comment]
trained to intent = "transaction" but response has no intent

**Comment by tobi418** [comment]
http://oi67.tinypic.com/ou1frd.jpg

**Comment by edzzn** [comment]
![spectacle v29652](https://cloud.githubusercontent.com/assets/14936466/26292427/73685720-3e7b-11e7-8835-d37f7e53bf79.png)

Maybe it is a different problem... but wit.ai is not working at all. And the status has not changed for a few hours.

![spectacle n29652](https://cloud.githubusercontent.com/assets/14936466/26292451/b0850b9e-3e7b-11e7-82a0-648cfaa3d3f5.png)

**Comment by eunicepoh98** [comment]
I have the same problem...

**Comment by patapizza** [comment]
It should work now. Feel free to reopen if that's not the case.
