### ISSUE TITLE
Inbox is empty in all apps

### ISSUE THREAD

**Issue by duaraghav8** [wit-ai/wit#577]
Wit Username: ```duaraghav8```

My wit apps (some of which are in prod) are all showing that inbox is empty. That shouldn't be the case since our dev & prod servers are constantly sending messages to wit.

I'm unable to validate the incoming messages.

**Comment by patapizza** [comment]
@duaraghav8 Thanks for flagging. The inbox should be back now.

**Comment by duaraghav8** [comment]
@patapizza works fine now=)
