### ISSUE TITLE
Wit.ai not able to capture multiple free text entities.

### ISSUE THREAD

**Issue by sanjeevmassal** [wit-ai/wit#578]
I have three **free text entities** as name, address and skills . wit.ai gives random response for them. Some time it extract name  and some time address for same user action. i tried to set all three as single entity as **user detail** but still not working.

**Comment by patapizza** [comment]
What is your app id? Can you provide a failing example with expected vs actual?

Thanks

**Comment by sanjeevmassal** [comment]
Thanks for reply.
My app id is **59201c48-ada5-455c-8db6-78cfa40b4783**
I was using three free text entities like below(third is name). 
![image](https://cloud.githubusercontent.com/assets/2031742/26343347/4bc136b2-3fb9-11e7-8acc-8da92acce9d7.png)

Mean time for temporary solution  I have used default raw reply text instead of entities to resolve my issue.

Thanks

**Comment by patapizza** [comment]
Your entities only have one example. To help Wit disambiguate between those on a given text, go to Understanding and provide more examples for each entity type.
Let me know if that helps.

**Comment by richwednesday** [comment]
Hi @patapizza I have a similar error. Two entities are clashing; wit/location and wit/number. wit/location works fine until I input an address that has two different numbers then two wit/number comes up.

Example if I input 500, Ayinde Akinmade Street, Lekki Phase 1. I get wit/number - 500 and wit/number - 1. It seems the limit entities that can be returned is two.

Anyway, I have tried training the app in the case where there are two numbers to still recognize the location but nothing yet.
My app ID is 58ee873f-fa8a-4802-b80d-6f8c0144e32a. 
Thank you.

**Comment by patapizza** [comment]
Thanks @richwednesday, this looks similar to #581.

**Comment by richwednesday** [comment]
@patapizza Please mention me when that is resolved. Thank you.

**Comment by l5t** [comment]
Closing as #581 is closed now
