### ISSUE TITLE
Specific value multiple times in "Trait values" and the same in "Expressions Filter by:" completion insight

### ISSUE THREAD

**Issue by lauraRuzicka** [wit-ai/wit#579]
I have a backup of my Wit.ai model in .zip file.

If I add some sentences to "expressions.json" including intent specification then put back to .zip file and create new application from this modified backup I get model that seems to work fine except one thing: 
Some values are multiple times in "Trait values" list and are multiplicated also in in the "Expressions Filter by:" completion insight

If I also modify "intent.json" then no intents are uploaded at all and no Expression is bound to any intent.

![expressionsinsinuator](https://cloud.githubusercontent.com/assets/25172366/26310918/c96d3c6c-3f02-11e7-898f-7656c40ed21b.png)
![trait valueslist](https://cloud.githubusercontent.com/assets/25172366/26310923/cc078428-3f02-11e7-91dc-8b881fe04009.png)

Also when I try to delete "remaining" instances of "multiplicated intents" then this is not possible:
Even if confirm "delete" nothing happens.

![confirmdelete](https://cloud.githubusercontent.com/assets/25172366/26311278/056c1872-3f04-11e7-9104-204b48b54ab0.png)

**Comment by stopachka** [comment]
Hey @lauraRuzicka -- could you send me the original zip file, alongside the changed one? Can take a look 

(stopachka@fb.com)

**Comment by lauraRuzicka** [comment]
Email sent 23.5.2017 at 22:34 CEST

**Comment by stopachka** [comment]
Problem addressed. Make sure that the values do not have extra spaces / cases when generated. 

Feel free to ping me if you have any more questions :)
