### ISSUE TITLE
Project stucks at 'ongoing' status after changing order in stories

### ISSUE THREAD

**Issue by kGielo** [wit-ai/wit#580]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
Project stucks at 'ongoing' status after changing order in stories. Status lasts 2 days from now.

**What is the App ID where you are experiencing this issue (if applicable)?**
5915d2db-4b47-4460-942f-c833f5656fc4

**Comment by patapizza** [comment]
Fixed.
