### ISSUE TITLE
wit/url not detecting valid URL

### ISSUE THREAD

**Issue by tpizzle** [wit-ai/wit#581]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**

Some URLs are being recognized as wit/number, instead of a URL. An example URL:
http://feeds.foxnews.com/~r/foxnews/video/~3/daWZPyh0g8M/

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Try the example URL (http://feeds.foxnews.com/~r/foxnews/video/~3/daWZPyh0g8M/) and the output will be wit/number 3 and wit/number 8.

**What is the expected behavior?**

It would be recognized as wit/url

**What is the App ID where you are experiencing this issue (if applicable)?**

58d2c3e6-debc-4433-899a-eee73e38a912

**Comment by patapizza** [comment]
Thanks for reporting @tpizzle, I'll look into it.

**Comment by l5t** [comment]
Closing as this is fixed
![image](https://user-images.githubusercontent.com/6992759/50316263-c8989c80-046a-11e9-93b2-79c8a86283ac.png)
