### ISSUE TITLE
Sharing, admin and remove people from App?

### ISSUE THREAD

**Issue by macasas** [wit-ai/wit#582]
While using the Wit web interface I have shared the App with someone.

This person now has full access to the app. Right?

Is it possible to shared the app so this person can only look at the stories?  So they cannot see the settings, keys, etc...

How do I remove that person from the App?

**Comment by patapizza** [comment]
@macasas If you share an app with somebody, that person will see his/her own key in settings. He/she will be able to make requests to your app using his/her own token.
It is not possible today to scope access to the Stories only.
To remove somebody, you can click on the cross on the right of the name under the 'Share this app' box in Settings.

**Comment by macasas** [comment]
Thank you for your response. I didn't notice that the keys were different for each person.

Also, the shared user didn't appear in the shared list straight away, it was just me. When I went back the next day the shared user was listed.

Hopefully wit will allow some sort of admin in the near future, so users can be added as Viewers, Editors, Testers or Admins. 

 want to invite people to just be able to follow through the conversations, others to just be able to go into Inbox and validate, and still others who cannot create a story but who can edit the story content. This type of functionality would be ideal for teams.
