### ISSUE TITLE
A 500 error after training samples programatically

### ISSUE THREAD

**Issue by thion** [wit-ai/wit#583]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
A bug.

**What is the current behavior?**
I trained my instance using the new POST `/samples` API with about 10000 examples and 6 entities. As I try to use the GET `/message` endpoint, I get a 500 error on _any_ message I send:

```
I, [2017-05-23T09:41:35.003653 #71250]  INFO -- : get https://api.wit.ai/message?q=test&v=20170307
D, [2017-05-23T09:41:35.003785 #71250] DEBUG -- request: User-Agent: "Faraday v0.12.1"
Authorization: "Bearer [...]"
I, [2017-05-23T09:41:36.555685 #71250]  INFO -- Status: 500
D, [2017-05-23T09:41:36.555892 #71250] DEBUG -- response: www-authenticate: "OAuth \"Facebook Platform\" \"invalid_request\" \"\""
wit-api-version: "unversioned"
access-control-allow-origin: "*"
pragma: "no-cache"
cache-control: "no-store"
x-fb-rev: "3038369"
content-type: "application/json; charset=UTF-8"
x-fb-trace-id: "DGATzHXq3tf"
expires: "Sat, 01 Jan 2000 00:00:00 GMT"
x-fb-debug: "acER7iGN4/LUWM/7gVWheDZPhb1F7u8nmn3IkfPtDSHpOU1+NOaICocXgbgIA8s1xZeiiQIt9QVNM4gcRsvdaw=="
date: "Tue, 23 May 2017 07:41:36 GMT"
connection: "close"
content-length: "70"
{"error":"Something went wrong. We've been notified","code":"unknown"}
```

I encountered this issue yesterday, waited for a day, thinking it may be temporary, but it still doesn't work today.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Difficult to reproduce as I trained 10k examples which I don’t want to share publicly.

**What is the expected behavior?**
I’d like to get my entities. :)

**What is the App ID where you are experiencing this issue (if applicable)?**
59236da8-6d7b-4db4-b8e6-a3609df1692b

**Comment by l5t** [comment]
Closing. Please reopen if you still experience this issue.
