### ISSUE TITLE
My app is kept in the state training on going

### ISSUE THREAD

**Issue by mingyangzhou1226** [wit-ai/wit#587]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug 
**What is the current behavior?**
My app is kept in the state training on going. Since last Friday, I can no longer access to the app. Apparently you guys fixed this part. However, now I can access it but it stays on training. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**
The App ID is 
590e865d-9e29-4521-8cb9-4b4cf828f5e4

Let me know if you need any other information. 

Thanks

**Comment by l5t** [comment]
What is your Wit app URL?

**Comment by mingyangzhou1226** [comment]
https://wit.ai/mingyangzhou1226/bot2 

Thanks

**Comment by l5t** [comment]
just retrained, it should be better in a few minutes
