### ISSUE TITLE
Not able to converse with the bot at wit console

### ISSUE THREAD

**Issue by tapan420** [wit-ai/wit#588]
Hello Team@wit.ai
I am not able to converse with the bot at the the wit console. It is not able to fetch the any information after executing the first statement .All my apps are behaving like this. Is there any up-gradation going.
Before this every thing was working fine.
Please help me that 
Thanks
https://wit.ai/tapan420/RFonebyone/stories/8bfb02a3-9c6d-4776-91dc-f393f3a150aa

**Comment by patapizza** [comment]
Hey @tapan420,

Besides the bad formatting (we're on it), I could successfully converse with the bot:

![screenshot](http://i.imgur.com/LkZ6ATb.png)

Can you share a screenshot of what is not working?

Thanks

**Comment by tapan420** [comment]
Is the issue with the screen of my laptop or its from your side
Because the console is not fully visible from my side

**Comment by patapizza** [comment]
The formatting issue is from our side, we'll fix it shortly.

**Comment by tapan420** [comment]
Hey Julien
   When I am giving the number of users , there no output on the console.
You can see it in the  screenshot I have shared
their should be function called . But nothing happens
Waiting for your fix

**Comment by patapizza** [comment]
@tapan420 I don't see the screenshot. Did you click on `routergotuser` and then on the green checkmark?

**Comment by tapan420** [comment]
No the getrouter function didn't poped up
It got stopped after mentioning the user

**Comment by tapan420** [comment]
When Mentioning the number of users like 33 , after that nothing happens on screen . I am not able to see functions which should be called when giving users.
![screenshot from 2017-05-24 20-25-38](https://cloud.githubusercontent.com/assets/19327489/26436838/1b73c8f6-4137-11e7-810b-ad2ff4e1190d.png)

**Comment by tapan420** [comment]
Problem solved . It wasn't working on Firefox . When I  switched to chrome ,It started working fine.
 May be browser issue 
Thanks for the prompt help 
Tapan

**Comment by patapizza** [comment]
The formatting issue is fixed.

**Comment by tapan420** [comment]
Thanks a lot Julien
