### ISSUE TITLE
Incorrect highlight of entities in specific expressions in intent detail in section Understanding

### ISSUE THREAD

**Issue by lauraRuzicka** [wit-ai/wit#589]
Even though entities are detected correctly and they are correctly displayed in "expression detail"  they are incorrectly highlighted in "expression text"

![incorrecthighlightofentitiesintext](https://cloud.githubusercontent.com/assets/25172366/26404425/2e1ee292-4092-11e7-9e59-9e29288bb7e4.png)

**Comment by patapizza** [comment]
Hi @lauraRuzicka,

What is your app id?

**Comment by lauraRuzicka** [comment]
It is: 592581ef-294f-4996-b6aa-b20d0f1fa628

**Comment by patapizza** [comment]
Now `DepartureAirport` is correct, but `ArrivalAirport` shows "Malaga echter":

![screenshot](http://i.imgur.com/dM3YCyx.png)

Looking at the validated expressions for `ArrivalAirport`, I see a few that are not highlighted correctly, which makes the classifier confused.

![screenshot2](http://i.imgur.com/undefined.png)

I would review the validated expressions and update with the correct highlighting to see if that resolves the issue.

Feel free to reopen if the issue remains after cleaning up the dataset.

**Comment by lauraRuzicka** [comment]
I'm sorry but your explanation seems to be incomplete.

I understand that you found sentences where entities are highlighted correctly - how is that related to reported problem?

"I would review the validated expressions and update with the correct highlighting to see if that resolves the issue."
I'm sorry but it doesn't make much sense for me.
In my opinion you just confirmed what was reported that: in sentence the highlighting is not correct while in the fields below the sentence the value is correct - this is clearly visible at your screenshots.
