### ISSUE TITLE
wit/number return billions on `g` 

### ISSUE THREAD

**Issue by trungtnm** [wit-ai/wit#591]
I'm working with wit/number and found an issue with it, since it recognizes the `g` in expression as billions and converts it to a number. In my app, people are usually using the `g` letter as `grams`.
Example:
- Expression : `300g` or `300 g` of sugar
  -> Result: `wit/number`: 300000000000

**Comment by patapizza** [comment]
The SI symbol for billion is G. I agree that it's rarely used.

Curious about the reason behind not using `wit/quantity`?

**Comment by trungtnm** [comment]
I tried `wit/quantity` also, but the result is not as expected. 
Example:
- Expression: `half a cup of coffee`
 -> Result with `wit/quantity`: `a cup` -> `1cup`
My app is for people inputting their `ingredients` to a `recipe`, so they often use the term like that.

**Comment by patapizza** [comment]
`wit/quantity` is backed by [Duckling](https://github.com/facebookincubator/duckling).
Feel free to contribute to make your app work!

**Comment by l5t** [comment]
I would suggest not to use wit/quantity as it may be hard to configure. Prefer composite entities: 
https://wit.ai/blog/2017/03/28/reintroducing-composite-entities

**Comment by patapizza** [comment]
wit/quantity should handle these cases now.
