### ISSUE TITLE
Handling wrong inputs

### ISSUE THREAD

**Issue by Krmenaldo** [wit-ai/wit#592]
I have the following scenario:
1. User asks a question
2. Wit gives appropriate answer in a form of a question
3. User gives a WRONG answer for that story, but RIGHT answer for a different story.
4. Wit gives wrong answer (from a different story) with a very low confidence. I can handle this and ask the user again jumping to step 2.
5. User gives a RIGHT answer
6. Wit goes crazy, gives an answer from a third story.

If the user gives the RIGHT answer in step3, everything works fine. I believe the problem is that step5 is analyzed based not only on step 1,2 but also 4. 

How can I tell Wit to ignore those unexpected answers?

**Comment by patapizza** [comment]
Hi @Krmenaldo,

Can you share your app id and an actual script? This would be helpful.

Thanks!

**Comment by Krmenaldo** [comment]
Hi,
the appId is SoggetaEnglish.
I don't know what type of script you are referring to. We use a custom .net code for conversations. Anyway below is a sample from our testing tool.
First the user asks information about Cash loans and the story CASHLOAN is started and the CheckIfPermanentEmployment action is executed.
After that the user is expected to enter yes or no answers, but if he enters, lets say, his location, this will get detected as coordinates from another story (FindNearestAtm) and the FindNearestAtm action is executed, which is completely wrong.
If the user then send yes it wont get detected properly.

![story](https://cloud.githubusercontent.com/assets/25805012/26467643/d788267a-4193-11e7-90dd-d0950a446e49.png)

**Comment by patapizza** [comment]
This is the name of your app - the app id is in the Settings page.
By script I meant an example of an actual conversation.

If you want to prevent your bot from jumping from one story to another one, you can use the context to gate it. For example, at the beginning of one story you can have your first action set a "story1" key in the context, and require for example `FindNearestAtm` to not have "story1" in the context (in the Actions tab).

Hope this helps.

**Comment by Krmenaldo** [comment]
Sorry,
the appId is 592823ce-2f53-48cf-95e8-fae5b8ac06f6

The solution you provided is not practical, and actually not working completely. This would mean that if I have 10 stories and 20 actions, I would have to set for each action ONLYIF 9 times for each of the stories I want to avoid. A this is for a small app. For a bigger app it would take a lot more.

As for the not working part I tried adding context keys to actions to avoid triggering them and it works on the first try, but on the second, it gives an action from the same story, but a completely wrong action. Below is an example.

![combine_images](https://cloud.githubusercontent.com/assets/25805012/26524232/d3acc598-432c-11e7-8744-3b8eed28983e.jpg)

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
