### ISSUE TITLE
Speech API is super slow.

### ISSUE THREAD

**Issue by chrisvip** [wit-ai/wit#593]
The speech API is taking about 30+ seconds to respond with a small .wav file (39k). Please see the example curl call below and note the timestamps from HTTP 100 to HTTP 200. Is this expected? This would make the service pretty unusable for my project.

```
C:\temp> curl -XPOST "https://api.wit.ai/speech?v=20170307" -i -L -H "Authorization: Bearer $MYTOKEN" -H "Content-Type: audio/wav" --data-binary "@test.wav"
HTTP/1.1 100 Continue
Date: Fri, 26 May 2017 00:40:28 GMT

HTTP/1.1 200 OK
Server: nginx/1.8.0
Date: Fri, 26 May 2017 00:41:00 GMT
Content-Type: application/json
X-Content-Type-Options: nosniff
Connection: keep-alive
Content-Length: 183

{
  "msg_id" : "bac7aba0-a346-4afa-a059-7645dc94c1b5",
  "_text" : "hello hello",
  "entities" : {
    "greetings" : [ {
      "confidence" : 1.0,
      "value" : "true"
    } ]
  }
}

C:\temp>dir test.wav
 Volume in drive D has no label.
 Volume Serial Number is D4F5-0DE1

 Directory of D:\temp

05/25/2017  05:06 PM            39,794 test.wav
               1 File(s)         39,794 bytes
               0 Dir(s)  78,095,380,480 bytes free



```

**Comment by sylmanu** [comment]
@chrisvip , Have you found a solution? I've been experiencing high latency with the speech API too...

**Comment by stopachka** [comment]
This may have been a temporary issue during the time, that has either come up once more or we are dealing with a different regression -- 

Let's consolidate the current issue to https://github.com/wit-ai/wit/issues/784

**Comment by autumnleaf666** [comment]
Hi, 
@chrisvip, did you solve this issue? I am running into this issue currently. Speech Service does not response for more than 20s.
 Thanks for any input.

**Comment by stopachka** [comment]
Hey @autumleaf666 -- this is most likely unrelated to this issue. 

If you are seeing errors, please open a new issue, and give us as much information as you can (repro of requests, etc)
