### ISSUE TITLE
Bot skips action and replies with message from other story

### ISSUE THREAD

**Issue by nikhilsaldanha** [wit-ai/wit#594]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug

**What is the current behavior?**
I have two identical stories, 'invite accepted' and 'invite rejected':

- **invite accepted**
1. User sends a message: ACC 100
2. Bot skips action and replies from a different story depending on the variables context

- **invite rejected**
1. User sends a message: REJ 100
2. Bot executes action and replies with correct message from same action

Even though the two stories are identical except for different names. I've gone through the stories multiple times, but haven't found a solution

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

In my app(App ID below), using the chatbot interface on the website, run the following steps:
1. User sends `INIT 100`
2. Chatbot executes `init()` and updates context keys with `initMessage`,`user` and `username`
3. Chatbot replies with `{initMessage}`
4. User sends `REJ 100`
5. Chatbot executes `inviteRejected()` and updates context keys with `inviteRejectedMessage`
6. Chatbot replies with `{inviteRejectedMessage}` **<<- EXPECTED BEHAVIOR**

**Now reset the session:**
1. User sends `INIT 100`
2. Chatbot executes `init()` and updates context keys with `initMessage`,`user` and `username`
3. Chatbot replies with `{initMessage}`
4. User sends `ACC 100`
5. Chatbot skips any action and replies with `{initMessage}` **<<- UNEXPLAINED BEHAVIOR**

The two stories show different results even though they are virtually the same

**What is the expected behavior?**

**Start a new session:**
1. User sends `INIT 100`
2. Chatbot executes `init()` and updates context keys with `initMessage`,`user` and `username`
3. Chatbot replies with `{initMessage}`
4. User sends `ACC 100`
5. Chatbot executes `inviteAccepted()` and updates context keys with `inviteAcceptedMessage`
6. Chatbot replies with `{inviteAcceptedMessage}`

**What is the App ID where you are experiencing this issue (if applicable)?**
59272b12-c41c-4beb-908f-866c58823409

**Comment by nikhilsaldanha** [comment]
The issue is fixed currently. I just renamed the intent and it started working. Not sure how to reproduce this. The issue seems to crop up seemingly randomly

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
