### ISSUE TITLE
Keyword intent not considering the keyword value

### ISSUE THREAD

**Issue by RendyTan** [wit-ai/wit#595]
***Question***

is wit.ai supposed to search for keyword including the keyword value itself?

Let's say I'm creating a time keyword intent. I will be providing a keyword value of 'morning' with synonyms of 'am', 'early', etc. I was expecting the morning keyword to also resolve to this intent. However, it wasn't the case. Trying to add synonym with the same value as the keyword value itself does not do anything.

Right now I'm resolving this issue by creating a different keyword value that only I understand and the user is not expected to use this keyword. I believe that it will be better if the keyword value also resolves to its own intent.

**Comment by patapizza** [comment]
Hi @RendyTan, indeed this should work. What is your app id? Can you provide an example request that doesn't work?

Thanks!

**Comment by RendyTan** [comment]
app id: 59245033-11b4-4ef8-a6c5-83972c6eafe2

Currently I am resolving it by putting another name as the main keyword value.
Try infoIntent, it is the keyword value. The synonym would be info(initial keyword value that doesn't work) or information.

**Comment by patapizza** [comment]
Sorry for the late response here.

It seems like synonyms of value `infoIntent` for the `mainIntent` entity work as expected:

<img width="990" alt="screen shot 2018-12-27 at 3 16 55 pm" src="https://user-images.githubusercontent.com/1015208/50497217-8b905500-09ea-11e9-9883-6cdbca05a3b7.png">
