### ISSUE TITLE
Adding new intents/expressions is not working

### ISSUE THREAD

**Issue by labdmitriy** [wit-ai/wit#597]
We have a problem of creating new intents and expressions using API. We are using /samples endpoint in our Python code, and last Friday we can create it with the same code.
Now I tried to add intents and expressions even using curl requests, but the problem is the same.
In both cases, we have response with status code 200 and correct body like the following:

{
  "sent" : true,
  "n" : 1310
}

I also tried to upload  #few samples (5), but the problem remains - there are no intents and expressions in UI, and intent detection is not working. It is possible now to create intents and expressions manually, but for us this is not desired solution.
Could you please look at our application, what is wrong? Do you have any limits on apps/requests?

We`ve also noticed last week (when we can add intents and expressions), that if we try to delete app, and recreate it with the same name and upload the same data for training, prediction is not working right after uploading, and we had to wait for a specific time to resend prediction requests to get detected intents.

App ID - 592c0f71-922c-4681-b1d5-83e668446c2d

Thank you.

**Comment by labdmitriy** [comment]
Hello,

Today I recreate app with the same name, and everything is working, but there is a delay between uploading samples for training, and first stable predict, so I need to wait for about 1 minute to send first query to get stable results, even if there is green training indicator within this 1 minute.

Is it correct behavior?

If I try to create app again, and use the same data for training, even after waiting for more than 1 minute (5 minutes), the intent detection results are different from the first app creation and training. 

What is the procedure for recreating and training, to get stable results?
What can be the reason of the original problem, when intents and expressions were not uploaded?

Thank you.

**Comment by youmustfight** [comment]
+1

Also getting a successful response POSTing to `/samples`:
```
data: { sent: true, n: 1010 } }
```

Was working for me yesterday, but at times would hang up. I'm not sure if this had impacted things, but it seemed to work again when I deleted my intent data or reset my server token but that may have been more a coincidence of timing. Today, I've had successful posts but haven't see any updates. I tried creating a whole new app even but had no luck there either.

App ID: `59304d1a-49a3-4e61-a12b-bb294d9fd0df`

**Comment by omudretsov** [comment]
Me too. Also stuck at this. POST to /samples succeeds:

200 OK
{
  "sent" : true,
  "n" : 175
}

Two days passed since then, but still no update in entities. Tried on different apps, different languages and even different accounts. No success. Please suggest, how to sort this out?

App IDs:
592d7556-6791-4741-92c1-f7a46445a95a
592e95a7-91ec-482a-91ae-795725e10282

**Comment by stopachka** [comment]
Hey all, this happens because, POST /samples adds what needs to be validated into a queue. 

Based on throughput, this can take a bit of time to process. During some moments, bugs could also cause the queue to stall. 

We are working on a migration, that will dramatically speed up POST /samples

**Comment by stopachka** [comment]
(conversation moved to https://github.com/wit-ai/wit/issues/699)
