### ISSUE TITLE
How to train 2 or more binomial entities (A confidence + B confidence + N confidence = 100% confidence)

### ISSUE THREAD

**Issue by gabbiano83** [wit-ai/wit#598]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question

**What is the current behavior?**
currently my app show both entities cases of a binomial distribution

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
I'd like to understand how to define 2 entities binomial distributed, like :
-open ticket 
-closed ticket

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by patapizza** [comment]
Hi @gabbiano83, you can use a trait entity with different values (e.g. "open", "closed"). To get the confidence for all values, you can use the parameter `n`.

Hope this helps
