### ISSUE TITLE
 unable to delete (unused) actions - extrem slow

### ISSUE THREAD

**Issue by sindre** [wit-ai/wit#600]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
I habe troubles deleting my (unused) ACTIONS. When opening the "All Actions" Tab and when trying to delete an (unused) Action my browser getting extrem slow and stops. Tried different browsers from Chrome to Firefox.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
click on the "all actions" Tab > loades extrem slow/ crashes the browser
click on delete on an (unsued) action > extrem slow response/ crashes the browser
**What is the expected behavior?**
Opening the "all actions" tab and deleting an (unused) action should be possible
**What is the App ID where you are experiencing this issue (if applicable)?**
573c7652-5ac4-4a83-96d2-d81d7d79a239

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
