### ISSUE TITLE
How to create a different story

### ISSUE THREAD

**Issue by richwednesday** [wit-ai/wit#601]
Hello,

This is not very clear from the guides but I want to create a story where the user says - how are you? Bot answers I'm fine, you? And next, whatever the user says in reply, the bot should response with Alright.

In my current implementation, I left the second user says field blank - and then bot replies but the bot is also sending this 'Alright' reply in places where the how are you question is not asked. 

What would be a good way to implement such a story.
My APP ID is 58ee873f-fa8a-4802-b80d-6f8c0144e32a
Thank you.

**Comment by patapizza** [comment]
Hi @richwednesday,

One way you could implement this is by adding a bot action after the first user says that sets a context key (e.g. "alright" to true), then setting a random user says (e.g. "good") and then add the bot sends "Alright".

Hope this helps.
