### ISSUE TITLE
Fail to Create a new entity via the HTTP API 

### ISSUE THREAD

**Issue by InesBensalah** [wit-ai/wit#602]
Hello 
I want to create a new entity via curl but I have an error, 

![capture](https://cloud.githubusercontent.com/assets/6861858/26586019/34314bfa-454e-11e7-9013-2007638b3022.PNG)

Thank you.

**Comment by patapizza** [comment]
Hi @InesBensalah, it looks like you need to escape double quotes when passing the request body. You might find easier to surround the whole body with single quotes so that there is no need to escape the double quotes.

**Comment by InesBensalah** [comment]
I don't think so, if i use a single quotes I have a other problem : 

error : Invalid JSON
code : json-parse
