### ISSUE TITLE
How modelate turn on/off and set Timer for leds?

### ISSUE THREAD

**Issue by augustocadini** [wit-ai/wit#603]
I have a application (Android) that need turn on/off and set a timer for leds on Arduino, the on/off already running. I created two entities in the Wit.ai, "ON" and "OFF", and for each I has added "LED A, LED B, LED C" like values. So, I don't know how organizering the timers. I'am new on the Wit.ai and I don't know excactly how this works. I seek for ideas about how implements this in the Wit.ai and how teaching the bot with time of use. Anyone have a suggest for how modelate this? If I need create other entity or other ways....

**Comment by swapkh91** [comment]
For timer you can use wit/duration entity.  As for LEDs, there can be an entity LED which can take values like LED A, LED B, LED C. Plus you have intents TURN_ON and TURN_OFF. Example:
User: Turn on LED A after 30 minutes

intent - TURN_ON
entities - {"LED": "LED A", "duration": {"from": "datetime entry", "to": ""}}

**Comment by augustocadini** [comment]
Ok, but how create Intent/Entity? Because I only create the Entities. Besides that how I link this with the Timer? Like, "TURN_ON LED A FOR 30 MINUTES"?

![captura de tela 2017-06-01 as 09 34 15](https://cloud.githubusercontent.com/assets/18659348/26679923/870f2a62-46ad-11e7-9920-74e51019bd1d.png)

**Comment by swapkh91** [comment]
![dem](https://cloud.githubusercontent.com/assets/5755405/26683623/19a480c6-4702-11e7-90ad-e0188d5bffca.PNG)

click on intent and then in value type TURN_ON. Train it with some examples. Same for OFF. Whenever wit is not able to identify the intent, assign it yourself.

**Comment by augustocadini** [comment]
Thank you for help! It's works! 
![captura de tela 2017-06-02 as 09 49 23](https://cloud.githubusercontent.com/assets/18659348/26726298/cdf37c46-4778-11e7-8e05-82da4e642645.png)

But I can't understand how implement the Timer. I thought in add value "Timer" in the intent, but this need a value for the time. Or create other entity, how is the best way? In addition to these described.

**Comment by swapkh91** [comment]
![dem](https://cloud.githubusercontent.com/assets/5755405/26728428/d37ad1ce-47c7-11e7-8c0d-246e85a57e11.PNG)

as you can see wit/duration will capture the duration and you can use that at backend like, get current system time and set duration from wit response.

**Comment by augustocadini** [comment]
But if I speak for example, "1:22" , that I wants say : "One Hour and Twenty and two minutes". The wit not undertand. Exists a way for insert times of type "hh:mm" ?

**Comment by swapkh91** [comment]
About that I have no clue

**Comment by patapizza** [comment]
@augustocadini It looks like "1:22" is more like a datetime than a duration. `wit/duration` is backed by [Duckling](https://github.com/facebookincubator/duckling), which doesn't handle composite durations yet like "1 hour and 22 minutes" (pull requests welcome!).

**Comment by augustocadini** [comment]
I did this question, because when I speak "SET TIMER A FOR 1 HOUR AND 30 MINUTES", the text that Wit understand is: "1:30". And with this I can't modelate to extract the real time, like when the text is similar to: "One hour and thirthy minutes"
