### ISSUE TITLE
Client Access Token stopped working

### ISSUE THREAD

**Issue by hactar** [wit-ai/wit#604]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
A few hours ago the wit client access token for https://wit.ai/hactar/Wave%20German768c-43b stopped working. If I try it with my server access token, everything works. I cannot try to create a new client access token as this client access token is used in production in my iOS and android apps.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

```
curl \
 -H 'Authorization: Bearer REDACTED' \
 'https://api.wit.ai/message?v=20170602&q=wo+ist+der+stephansdom'
{"error":"Bad auth, check token\/params","code":"no-auth"}%
```
**What is the expected behavior?**
The client access token should work.
**What is the App ID where you are experiencing this issue (if applicable)?**
 https://wit.ai/hactar/Wave%20German768c-43b

**Comment by patapizza** [comment]
Thanks for reporting @hactar, this is now fixed.
