### ISSUE TITLE
Wit API slower than expected

### ISSUE THREAD

**Issue by rajaraodv** [wit-ai/wit#605]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Why is wit.ai is so slow? I searched google and looks like a lot of people are experiencing it
Are you planning a paid faster version?
<img width="1039" alt="screen shot 2017-06-02 at 6 47 56 am" src="https://cloud.githubusercontent.com/assets/626337/26728607/a3153fbe-475f-11e7-8842-1e647e2ab952.png">

**Comment by patapizza** [comment]
Hi @rajaraodv, what is the latency you're experiencing? Which endpoint are you calling?

Thanks

**Comment by l5t** [comment]
And yes we have had latency issues in the last 6months due to our growth (from 20K to 100K developers in the last 12 months) and we have been working hard on scaling so it should be better now: https://wit.ai/blog/2017/04/18/supporting-100000-developers-and-beyond

**Comment by JonghunYu** [comment]
I have a latency problem as well. It gets much slower than few months ago and have kept exceeding time limit of the chat platform I am using.
I am calling converse endpoint.

**Comment by blandinw** [comment]
Please specify the endpoint you're using, app-id and the location of your servers.
/converse is expected to be slow, /message should be fast.
Closing as non-responsive.
