### ISSUE TITLE
Question: Is there a way to autocomplete entities (web interface)?

### ISSUE THREAD

**Issue by rajaraodv** [wit-ai/wit#606]
Question: Is there a way to autocomplete entities? If the user is typing "Piz" or "Pizz", I'd like to show autocomplete suggestions and show "Pizza". How to go about achieving it?

**Comment by patapizza** [comment]
Hi @rajaraodv,

There is an autocomplete both in Understanding and Stories when adding a new entity:

![understanding](http://i.imgur.com/Id4boh1.png)
![stories](http://i.imgur.com/Uup0kPO.png)

Also when editing the text input, we look ahead for entities (both in Understanding and Stories). You can see a "Searching for entities..." label.

Am I missing something?
