### ISSUE TITLE
Matches intent correctly but gives a wrong answer; right answer first time and same wrong answer every subsequent time

### ISSUE THREAD

**Issue by agrey** [wit-ai/wit#607]
Super weird bug: the first time I query the bot within Wit, I get the right answer. If I ask the exact same question twice in a row, the second time it gives the wrong answer:

Who get's ear infections?
8:07:33 AM
Children can be divided into three groups of roughly equal size: no ear infections, sporadic ear infections, and frequent ear infections. The children who are more prone might have immune systems that are not as mature as those of their counterparts. Their eustachian tubes might be shorter, narrower, or less efficient than average. Or they could have allergic tendencies or exposure to environmental irritants. Ear infections do tend to occur more commonly in boys than in girls (for unclear reasons). Children who have their first ear infection before six months of age are more likely to be otitis prone, as are those who are bottle-fed as opposed to breast-fed. Children in group day-care settings are also at greater risk.
8:07:34 AM
Who get's ear infections?
8:07:43 AM
Clindamycin is a third-line antibiotic: It's typically only used when acute otitis media persists after appropriate first- and second-line choices have both failed. It is superb against some infections caused by penicillin-resistant Strep pneumo. The major drawback is that this powerful drug can cause colitis and/or severe diarrhea. 

Conversely, when I interact with the Wit app from the outside (http / POST), it actually matches the question correctly with high confidence but then assigns an incorrect answer with low confidence:

Question Who get's ear infections
Resp {'confidence': 0.11013876303959169, 'type': 'msg', 'msg': "Clindamycin is a third-line antibiotic: It's typically only used when acute otitis media persists after appropriate first- and second-line choices have both failed. It is superb against some infections caused by penicillin-resistant Strep pneumo. The major drawback is that this powerful drug can cause colitis and/or severe diarrhea. ", 'entities': {'intent': [{'confidence': 0.8069430342275964, '_entity': 'intent', 'value': 'Who is most likely to be prone to ear infections?'}]}}

When I go back here on the Wit website into "Understanding", and type in the question "Who get's ear infections", it does correctly match the intent as "Who is most likely to be prone to ear infections". You might wonder, could the story have the wrong answer entered in for that question? No. When I go to the story for that question, the answer is correctly entered:

In Stories, the answer to "Who is most likely to be prone to ear infections?" is:
Children can be divided into three groups of roughly equal size: no ear infections, sporadic ear infections, and frequent ear infections. The children who are more prone might have immune systems that are not as mature as those of their counterparts. Their eustachian tubes might be shorter, narrower, or less efficient than average. Or they could have allergic tendencies or exposure to environmental irritants. Ear infections do tend to occur more commonly in boys than in girls (for unclear reasons). Children who have their first ear infection before six months of age are more likely to be otitis prone, as are those who are bottle-fed as opposed to breast-fed. Children in group day-care settings are also at greater risk.

Also, when it starts giving the wrong answers, it is the *same* wrong answer each time, each with a confidence of .11... regardless of what question has been asked. It correctly detects the question with a confidence of >.8, but returns the wrong answer with very low confidence. 

Note that our Wit app compiles "green", and each question within the app is "green" as well. There are apparently no conflicts with training and no issues identifying the question.

Help! How is this possible that it gives the right answer the first time but the same wrong answer to every question the second time? And how is it possible that it is correctly matching the question but giving the wrong answer anyway?

Please note that this is a private Wit app, and that this content has been copyrighted by the author who gave me explicit permission to use it.

**Comment by patapizza** [comment]
Hi @agrey,

What is your app id?

**Comment by agrey** [comment]
@patapizza 58ffa953-f75e-408f-92b9-1e1d1490b594

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
