### ISSUE TITLE
Triggering actions Always If

### ISSUE THREAD

**Issue by oximer** [wit-ai/wit#608]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
You ask Wit to execute a action "Always if" some context exist, but It doesn't trigger the action.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
For me it was pretty straight. I created a action story that only has an action. I don't have to wait for the user to type anything. 

Then I went to the panel and choose to trigger that action always if some parameter exist. 
Nothing  happen.

**What is the expected behavior?**
Trigger the acttion.

**What is the App ID where you are experiencing this issue (if applicable)?**
590e3812-29be-45f6-bb28-0e4216cdfedd

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
