### ISSUE TITLE
Message endpoint returns all entities

### ISSUE THREAD

**Issue by jibrang** [wit-ai/wit#613]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
When a message is sent to the `/message` endpoint, it returns all of the existing entities, even when most of them are not trained for those sentences.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
The most basic one:
`hey` should return a  `greeting: true` entity, but it returns a whole set more.
<img width="1029" alt="captura de pantalla 2017-06-09 a la s 15 14 31" src="https://user-images.githubusercontent.com/17800593/26992934-6f3fd7e0-4d26-11e7-99e0-af8f0d30ce39.png">

**What is the expected behavior?**
It should only return the entities it was trained for.

**What is the App ID where you are experiencing this issue (if applicable)?**
590220ce-1441-491f-9e25-a07cc0e0cedd

**Comment by tobi418** [comment]
Exact same problem here
app id: 58a2d010-677f-4e42-8d29-cd11b5db9c2e

**Comment by patapizza** [comment]
Thanks for reporting. Closing in favor of #612.
