### ISSUE TITLE
Wit displays entities in an undocumented manner

### ISSUE THREAD

**Issue by DrWala** [wit-ai/wit#615]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

Asking a question

**What is the current behavior?**

Under some circumstances which I am not entirely sure of, wit does this:

Example 1:
![image](https://user-images.githubusercontent.com/6803997/27012337-5ed8045a-4f00-11e7-9400-456817d9bd60.png)

Example 2:
![image](https://user-images.githubusercontent.com/6803997/27012350-a004a0b4-4f00-11e7-9399-e7b2ed2970f5.png)

My question is: What is the 'arrow pointing up' on the entity under the intent? It isn't documented anywhere.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

I believe when you select a value from the text box for an intent, associated entities fall under in that manner? However that can only be seen in Example 2. I'm not entirely sure what causes this behaviour in the first place.

**What is the expected behavior?**

No idea. 

**What is the App ID where you are experiencing this issue (if applicable)?**

Don't think its relevant as I can do this in new apps as well. I can add the App ID later if that's deemed necessary to troubleshoot.

**Comment by ccfz** [comment]
It is a composite Entity. The arrow points to the parent entity. https://wit.ai/blog/2015/05/05/composite-entity

Just check the value you are assigning and maybe read up on the "which entity to use" section in the docs
