### ISSUE TITLE
Context Object changing actions my app should take

### ISSUE THREAD

**Issue by richwednesday** [wit-ai/wit#616]
I have written some stories and I have actions for each story, When I test it in the wit.ai console by clicking ~, it executes the right action, but when I use my code where I get to change the context object, Wit decides to change the right action and execute something else. 

How does the context object really work, I can't leave it empty because other parts of my code require it.

Example case, when the user types a number, wit.ai is supposed to execute a particular function - 'smartreplies', it does so on the Wit's website but in my code, I get another action due to the context object I'm probably passing to Wit.

My App ID is 58ee873f-fa8a-4802-b80d-6f8c0144e32a
Is there a way to disable this context object from changing the right actions to take? Thank you.

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
