### ISSUE TITLE
Amount_of_money on multiple occurrences in the same sentence.

### ISSUE THREAD

**Issue by raincrash** [wit-ai/wit#618]
We're planning to build a minimal e-commerce chatbot that uses WIT. WIT fails to recognise two different amount_of_money instances from a provided input. For example, "I want to buy some red color shoes the costs between 250 to 700 dollars". The 700 dollars is identified as an "wit/amount_of_money" entity but not the first.

On attempting to input two different prices, as above, it recognises one instance but not the other one.
 
Is there a way to recognise both the prices as amount_of_money entities?

The App ID is 5881ebd9-ac2c-429f-9cc3-9ee6a79fbc10, if it helps.

**Comment by patapizza** [comment]
Hi @raincrash,

Wit relies on [Duckling](https://github.com/facebookincubator/duckling) for the `wit/amount_of_money` entity. I'll see if we can extend it to support intervals.
In this case, it would be a single entity with body "between 250 to 700 dollars", and there would be `from` and `to` keys in the structured value.

**Comment by raincrash** [comment]
Thanks @patapizza. I can work on the corpus/rules too, if you're okay with the mentoring. :)  Do lemme know.

**Comment by patapizza** [comment]
@raincrash Thanks, I've actually already started working on this.
I'm happy to help you get started if you'd like to extend Duckling in some other way. :)

**Comment by patapizza** [comment]
This is now implemented!
