### ISSUE TITLE
Feature - Destroy app programatically through the REST API

### ISSUE THREAD

**Issue by bigman73** [wit-ai/wit#619]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
*feature* 

**What is the current behavior?**
Destroy App functionality is only available through the UI

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Provide a DELETE /apps/{app_id} REST API method
There are POST and PUT APIs, but a DELETE (and actually also GET) are missing to complete a full CRUD.

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by bigman73** [comment]
I managed to programmatically destroy/delete an app using the very powerful and undocumented /sync endpoint [PUT], following the concepts presented in https://github.com/fczuardi/calamarcopolo-training/issues/1 and with a little reverse engineering of the wit.ai UI. 

`[{"data":{"instance_id":"$APP_ID_GUID$"},"type":"deleted-instance"}]`

So obviously this is doable. A little nice REST DELETE API will make it cleaner - That's all this feature request is about.

**Comment by Boyko-Karadzhov** [comment]
The browser token seems to expire. I have managed to get fresh tokens using a GitHub account by POSTing here:
```
https://api.wit.ai/me/github_signin
```

Payload:
```
{"t":{"access_token":"[your github personal access token here]","token_type":"bearer","query_param":"access_token","params":{"scope":null},"refresh_token":null}}
```

Your github personal access token will not expire if you have created it through you account settings.

**Comment by igatanasov** [comment]
It will be better if the user is able to destroy the application only with application token

**Comment by RayBenefield** [comment]
I'm just hear echoing the need for full CRUD for applications. Definitely important if Wit.AI's goal is to provide the ability to build platforms on top of Wit.AI. Thanks for the initial CRUD operations, they are great. :)

And just having to use the Application Token would definitely be the best route.

**Comment by blandinw** [comment]
Hey everyone, thank you for your feedback and apologies for the slow response. We'll definitely implement this in the next few months! Keeping open as feature request.

**Comment by blandinw** [comment]
Done: https://wit.ai/docs/http/20170307#delete--apps-:app-id-link
