### ISSUE TITLE
Feature - Ability to get the app training status through an API

### ISSUE THREAD

**Issue by bigman73** [wit-ai/wit#620]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
*feature*

**What is the current behavior?**
The training status for a given app is available only by monitoring at the web UI and waiting for it to change from animated to green. 
In a fully automated app generation scenario (enabled by the newapp API), trying to send messages before the training has completed results in no matches or requires some large fixed waiting period before the system can be considered functional.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Query the training status using a REST get API. For example GET /trainingstatus

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by mbarber-gala** [comment]
Is there a plan to implement this? As bigman73 said, it would be very useful in automated deployment scenarios.

**Comment by stopachka** [comment]
Hey @mbarber-gala 

This is indeed a key piece in the New API

- (also important for solving #876)

Will keep you updated on the state, there is still one unresolved piece of the API, that once unblocked should be ready for release

**Comment by aongwachi1** [comment]
@l5t  could you please tell us to released date?
thank you

**Comment by l5t** [comment]
We are working on it and hope to release it in the next 2-3 weeks. I will update the thread when ready

**Comment by mehfuzh** [comment]
Do we still have a status for this API?

**Comment by stopachka** [comment]
Keep an eye out in the blob, this will be coming veery soon

**Comment by jtliao** [comment]
This is now available here https://medium.com/wit-ai/introducing-get-apps-id-846edab36a20
