### ISSUE TITLE
Feature - Ability to get a list of current apps through an API

### ISSUE THREAD

**Issue by bigman73** [wit-ai/wit#621]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
*feature*

**What is the current behavior?**
The only way to get a list of apps is through the web UI

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Use a REST GET API to return a list of all apps as a JSON structure, with their basic information (id, accesscode, timestamps)
The access token of some existing "master app" will be used for authentication (similar to how newapp API works)

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by bigman73** [comment]
Similarly to my comments here: https://github.com/wit-ai/wit/issues/619
I managed to programmatically get a list of all apps using the very powerful and undocumented /sync endpoint [PUT]

`[]`

All the instances show up in the response body

**Comment by jtliao** [comment]
https://wit.ai/docs/http/20170307#get__apps_link
