### ISSUE TITLE
Something went wrong message on message endpoint

### ISSUE THREAD

**Issue by JonathanRoyGagnon** [wit-ai/wit#622]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
I've been receiving the following JSON response while calling the `/message` GET endpoint.

`{"error":"Something went wrong. We've been notified","code":"unknown"}`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Unpredictable behavior. Would fail for multiple request for ~10 seconds and then work again. Unable to reproduce, it works and fails at unpredictable times.

**What is the App ID where you are experiencing this issue (if applicable)?**
I'm experiencing this on multiple apps.

I received this error at one time for the following message: `Hi, Fumei`.
The App Id is `583c15bb-a7f1-4928-8d76-846bf81e6e32`.
The time is about June 13, 03:40 UTC.

**Comment by patapizza** [comment]
Closing as this was probably a transient issue. Feel free to reopen if you still experience this.
