### ISSUE TITLE
Bug: Wit classifies 'perhaps' as a greeting

### ISSUE THREAD

**Issue by jibrang** [wit-ai/wit#624]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
When you type the word 'perhaps', Wit classify it as wit/greetings

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Type the word perhaps
![captura de pantalla 2017-06-15 a la s 11 51 18](https://user-images.githubusercontent.com/17800593/27192656-c82b2c16-51c1-11e7-87ce-6c1314fc4580.png)

**What is the expected behavior?**
It should not classify it ass wit/greetings

**What is the App ID where you are experiencing this issue (if applicable)?**
590220ce-1441-491f-9e25-a07cc0e0cedd

**Comment by patapizza** [comment]
Hi @jibrang,

The confidence on "perhaps" is 0.4844. To get a higher precision, you can drop results below a given confidence level.

Hope this helps.

**Comment by jibrang** [comment]
Ok,

thanks for your help :)

2017-06-16 12:02 GMT-05:00 Julien Odent <notifications@github.com>:
