### ISSUE TITLE
chat bot does not reply

### ISSUE THREAD

**Issue by sohymg** [wit-ai/wit#625]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
When asked the exact "User says", the chat bot does not reply.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- In Stories, press "~" to chat with bot
- Type "showtimes for wonder woman at vivo for today at 6pm" which is the same as the "User says" in the story
- Chat bot does not reply

**What is the expected behavior?**
- Chat bot should reply with "Hello {movie} {cinema} {wit/datetime}". I noticed that if I remove "{wit/datetime}" from Bot executes, the chat bot will reply as expected.

**What is the App ID where you are experiencing this issue (if applicable)?**
59433617-209e-421b-b5dd-916b6851306d

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
