### ISSUE TITLE
training status endless ongoing!!!

### ISSUE THREAD

**Issue by tobi418** [wit-ai/wit#626]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
training status ongoing endless, but nothin trained
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
it was very fast trained before
**What is the App ID where you are experiencing this issue (if applicable)?**
59428e2f-cbf0-4a70-ab8a-88889be17d8c

**Comment by bbucek** [comment]
We're experiencing a similar problem at the moment.
App ID: `58ac325b-3f22-4c59-96da-448661502014`

**Comment by l5t** [comment]
Can you share your Wit App url?

**Comment by l5t** [comment]
Just restarted your training

**Comment by bbucek** [comment]
All back to normal, thanks a lot! 👍  ❤️
