### ISSUE TITLE
Server returns {"sent":true,"n":2} but the app is not trained

### ISSUE THREAD

**Issue by DiamondLopes** [wit-ai/wit#627]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug 

**What is the current behavior?**
Training apps via the HTTP api does not work for any of my apps no matter how long I waint.

Here's an example (the app language is set to portuguese):

Request 1 of 2: lâmpada não funciona 
Request 2 of 2: tarefa 

JSONArray: [{"entities":[{"value":"Repair Request","entity":"intent"},{"start":0,"end":8,"value":"lâmpada ","entity":"Object"}],"text":"lâmpada não funciona "},{"entities":[{"value":"Task","entity":"intent"}],"text":"tarefa "}]

Response from Wit: {"sent":true,"n":2}

The app however is not trained nor does it show that there's a training ongoing.

**What is the expected behavior?**
After a few times, the app should be trained with the new expressions. It worked before but I encountered some issues with duplicate values for entities.
I have also posted in the Wit.ai Hackers facebook group:
https://www.facebook.com/groups/withackers/permalink/257037521369169/

**What is the App ID where you are experiencing this issue (if applicable)?**
The lastest test was performed on this app: 
59469c16-1f9e-4c86-875f-e0af48b8ec26

**Comment by rowanvanekeren** [comment]
its because that wit.ai works a-sync so it just says it is received good and then begins processing.. i think

**Comment by patapizza** [comment]
@DiamondLopes 

Both `tarefa` and `tarefa ` do return `intent` with the value `Task`.
Looking in the values for the `intent`, there's a mismatch: the existing value is `Repair request` (vs `Repair Request` as sent). We should be more robust to that.
I've re-validated `lâmpada não funciona` with `Repair request` and it works now:

![](https://i.imgur.com/wSnxpTv.png)
