### ISSUE TITLE
Machine stuck in training mode for 3 days

### ISSUE THREAD

**Issue by abourdin** [wit-ai/wit#628]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug

**What is the current behavior?**
Machine is still stuck in training mode since friday afternoon

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Training should be over and machine should respond correctly to queries

**What is the App ID where you are experiencing this issue (if applicable)?**
58eca373-f088-4984-99a4-ff489fe5797a

**Comment by l5t** [comment]
Just restarted your training.
