### ISSUE TITLE
The default application seems to be based on an old version of WIT

### ISSUE THREAD

**Issue by sebastien-roch** [wit-ai/wit#629]
I want to report a **bug**

**What is the current behavior?**
The default application does not show tabs like "understanding" or "stories" at all. If I create a new app, those tabs would appear.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I logged in with my github profile and started to configure the default app (called _instance-XXXXXX_). It was on Monday, 19th June. It's only later I noticed some functionalities were missing.

**What is the expected behavior?**
"Understanding" and "stories" tabs and their functionalities are available.

**What is the App ID where you are experiencing this issue (if applicable)?**
Instance 52fb9d81

**Comment by l5t** [comment]
Closing. Please reopen if you can reproduce
