### ISSUE TITLE
Enhancement: Inbox API

### ISSUE THREAD

**Issue by drewcrawford** [wit-ai/wit#63]
My customers might dictate things that don't make sense to me.  For example, consider these two transcriptions:

> I help Apple recognize speech
> I help Snapple wreck a nice beach

The first is a plausible statement from someone who works on Siri, the second is a plausible statement from an environmentally-conscious soft drink employee.  **I** certainly have no idea what the person meant.

Another case is where there may be industry-specific jargon.  I say `UIScrollView`, you say "You Aye Scroll View".  I can't reliably guess what my customer said unless I know the technical background.

If there was some sort of API for training, then I could expose some sort of GUI downstream to my customer to correct transcriptions.  And then if my customer happens to use, say, trucking jargon or programming jargon or whatever, then they can go in and correct their own recognition without my intervention.  Instead of what they currently do, throw up their hands at the recognition solution because there's no way to teach it `UIScrollView`.

**Comment by blandinw** [comment]
So sorry for the lack of updates. 😔
We released a few APIs to manage expressions and intents.
We're still interested in having an Inbox API but haven't had enough demand to justify spending time on it yet. I'll leave this issue open to keep the discussion centralized.

**Comment by oplatek** [comment]
It would be awesome if I can use the programmatic API, I could use a crowd of my users or use a crowdsourcing platform to generate training data for my bot.

Actually, I would also prepare the training data for my bot in advance and I would just upload it after I design my stories.

**Comment by guns2410** [comment]
Rightly said by @oplatek. I do see that the Inbox API would be of great use and help. I believe wit.ai would be more effective using the Inbox API

**Comment by dimirc** [comment]
+1

**Comment by chipopox** [comment]
I would  also like to have an API for the inbox

**Comment by Orisbaum** [comment]
We would LOVE to use the potential inbox API. Is there any way to validate the inbox via the API?

**Comment by blandinw** [comment]
This is being worked on with high priority :-) we'll post an update soon.

**Comment by stopachka** [comment]
This is now out! https://wit.ai/blog
