### ISSUE TITLE
Pre define entity wit/amount_of_money is not working properly

### ISSUE THREAD

**Issue by tapan420** [wit-ai/wit#630]
Hello Team 
I am facing a problem with th entity **wit/amount_of_money**. I wanted to use it in my app urgently ,
But whenever I click on that it gets corrupted and I have to refresh the page to get back.
I am sharing a printscr.
Please help me with that .
@l5t 
![screenshot from 2017-06-20 17-54-13](https://user-images.githubusercontent.com/19327489/27333264-edaa08b6-55e2-11e7-889b-d26693570a71.png)
thanks
Tapan

**Comment by patapizza** [comment]
Hi @tapan420,

Can you describe the exact steps to take to get to this screen?

Thanks!

**Comment by patapizza** [comment]
Ok got a repro. I'm working on a fix.
In the meantime, you can add wit/amount_of_money programmatically with [POST /samples](https://wit.ai/docs/http/20170307#post--samples-link).

**Comment by tapan420** [comment]
Hi Patapizza 
Thank you for looking into the issue .
Now the entity wit/amount_of_money is working for a single value not for multiple values.
Example : **I want 333 vfkffkkf_FdddsdS_ddd  $43  and ffffff_fddddAAA  34  $33**  
![screenshot from 2017-06-21 15-50-03](https://user-images.githubusercontent.com/19327489/27379575-63177d84-5699-11e7-8974-f4390fa7d809.png)
You can see its taking only  $43  as wit/amount_of_money and not $33.
can you please look into that  
Thanks!

**Comment by patapizza** [comment]
Hi @tapan420, yes this is now fixed.
Closing this ticket since main issue is resolved.

The issue you're having is related to Duckling, I'm looking into it.
