### ISSUE TITLE
Facing understanding problem

### ISSUE THREAD

**Issue by tapan420** [wit-ai/wit#631]
Hello @l5t 
I am facing  issues regarding the understanding of the app. I have trained the app on
that **"i want 33 <part_name>" using 1 user based entity part_name and in that we have 2 composite entity part_number and wit/number .**

So the problem comes when I give it ,**" I want 44 ASR1002X-20G-K9  "**
**So it takes only user entity <part_name>  and wit/number - 44  and  not the
part_number** .
![screenshot from 2017-06-16 12-40-25](https://user-images.githubusercontent.com/19327489/27333964-531334dc-55e5-11e7-8574-047df25eb32c.png)

**Instead I am getting wit/number with vale of 100 , 20 , 9.
what can be the problem , I am kind of struck here
please help me out with it.**

Thanks 
Tapan

**Comment by l5t** [comment]
Closing. Please reopen but I don't understand why you would want to have a wit/number inside your part name. In your example "I want 44 ASR1002X-20G-K9", what will be the wit/number inside "ASR1002X-20G-K9"
