### ISSUE TITLE
Unable to register new intents

### ISSUE THREAD

**Issue by ecrmnn** [wit-ai/wit#632]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
Unable to register a new entity of type intent

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
When I write a sentence and want to add a new entity of type ``intent`` I'm unable to select that option. The screen just turns completely white.

Tested in Chrome and Safari.

In Firefox the page turn completely white when writing a sentence.

**What is the expected behavior?**
I should be able to choose a new entity type of ``intent`` and then set the name of that ``intent``.

**Comment by blandinw** [comment]
@ecrmnn Thank you for your feedback(s)!
I'm pushing a fix, it should be live in a few hours.
Please let me know and feel free to close the task if it's fixed.
We apologize for the inconvenience 🤖🤕
