### ISSUE TITLE
Inbox not working at all

### ISSUE THREAD

**Issue by ecrmnn** [wit-ai/wit#633]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
1. Click on ``Inbox``
2. Nothing to see
3. Click "refresh" icon in UI or just wait a few seconds
4. Page turns completely white

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Click on ``Inbox``
2. Nothing to see
3. Click "refresh" icon in UI or just wait a few seconds

**What is the expected behavior?**
1. Click on ``Inbox``
2. Loads recent messages and suggests entities
3. Can be validated or trashed

**Comment by patapizza** [comment]
Hi @ecrmnn, do you still experience the issue? What is your app id?

**Comment by joZephhh** [comment]
Same problem here

**Comment by blandinw** [comment]
@joZephhh @ecrmnn I'm not able to reproduce the issue, could you provide me with your appids?

**Comment by Rolfjdra** [comment]
My page also goes blank, but not on the inbox. The page goes blank whenever I:
-Click on one of my stories
-Try to create a story
-When I try to feed new data in understanding

Maybe it would also go blank when I click on inbox if it were not empty at the moment.

**Comment by ecrmnn** [comment]
Inbox goes blank, but Understanding isn't working either.
See this #632. Hugh issue for me, as out clients chatbot is now live but we're not able to adjust the understanding.

App id: 58aaadcd-1513-46ce-bda1-90ab913643f5

**Comment by ruwidoresearch** [comment]
Hi guys,

i'm also facing the same problem. My page goes blank if i click on Inbox, or if i try to train my app in the Understanding mode.

my other apps are working, but 
App id 591ee406-3dd5-429d-89ae-f0fab8b6c3fb is not

Thanks for your help!

**Comment by rijkvanzanten** [comment]
This might be a bigger issue than just inbox. I'm experiencing the same problems as @Rolfjdra on one of my Wit apps.

App id 59302cab-cf20-4ca0-82b8-2a4012690276

**Comment by iamkenken** [comment]
same problem here. the page goes blank when I try to create a story
APP ID: 586b5880-86c8-439f-b202-9f09b4279ca2

**Comment by BeatrizHerculano** [comment]
Hi, I am having a similar problem. When i select a entity while training a new sentence the page goes blank.

My App ID: 5936f7e5-6b50-4c15-b5eb-68c42bda0231

**Comment by sgelves** [comment]
Hello, I am facing the same issue, but it happens when I enter my app, then switch to the stories tab, and when I click the story, the page goes blank.

My App ID: 593b0b52-3b7b-483c-89ac-5127826e8b7e

**Comment by ecrmnn** [comment]
This is still not working for me. Anything new @patapizza?

**Comment by blandinw** [comment]
@ecrmnn and all Thank you for your feedback(s)!
I'm pushing a fix, it should be live in a few hours.
Please let me know and feel free to close the task if it's fixed.
We apologize for the inconvenience 🤖🤕

**Comment by ecrmnn** [comment]
@blandinw Still not working

![kapture 2017-06-23 at 10 29 59](https://user-images.githubusercontent.com/1481696/27473316-0bee4512-57ff-11e7-8c76-ef330e1049f7.gif)

**Comment by rijkvanzanten** [comment]
Same here @ecrmnn 

What is the ETA of the fix @blandinw? (We were planning on releasing our chatbot yesterday but we might want to shift that to Monday if this issue persists...........)

**Comment by dandevri** [comment]
@ecrmnn @rijkvanzanten Everything seems to be working again. 🎉
Thanks for the fix @blandinw 🙏

**Comment by ecrmnn** [comment]
🎉 🦄

**Comment by joZephhh** [comment]
Seems to me fixed for me too! Thanks 🎉
