### ISSUE TITLE
Unable to create new story and Unable to open previously created stories 

### ISSUE THREAD

**Issue by anuradhaurgunde** [wit-ai/wit#634]
unable to open stories what I have created, but I am able to see summery of stories that I have created.

stories are in working condition but I am unable to open them as well as unable to create new stories.

after logged in to wit by using Facebook login, unable to add a new story to my existing App. 

The expected behavior is wit should be able to create new stories and allow me to allow stories which are created previously.

App id:59467368-3c6a-4914-aa1d-dcbe1fe5e04b

**Comment by rijkvanzanten** [comment]
This is discussed in #633 as well

**Comment by mani541** [comment]
Same Problem here. I am not able to view one of my story, it redirects me to a blank page.

**Comment by mani541** [comment]
I am able to view my story now. Fixed for me. Thanks.

**Comment by rijkvanzanten** [comment]
Hooray! Thanks @blandinw 🤙

**Comment by daxlopes** [comment]
@blandinw Same Problem here. I am not able to view one of my story. APP ID: 126091124721205
Could you help me with this problem? 
![image](https://user-images.githubusercontent.com/33169827/32130993-32ad0ee0-bb82-11e7-8ded-b46644ea0d31.png) -> These are the options

**Comment by patapizza** [comment]
Hi @daxlopes, it looks like you haven't had any stories created, which is expected as you created the app on October 26th.

**Comment by l5t** [comment]
In case you missed it: https://wit.ai/blog/2017/07/27/sunsetting-stories

**Comment by daxlopes** [comment]
Ok, Thanks guys! I am using Hubot and I intend use Wit too.
