### ISSUE TITLE
reference_time does not work in /message

### ISSUE THREAD

**Issue by znat** [wit-ai/wit#635]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
BUG

**What is the current behavior?**
App timezone is PST so for the following request:

`https://api.wit.ai/message?v=20170307&q="in 10 minutes"&reference_time="2017-06-22T10:00:00.000-04:00"
`
I'd expect the following result:
```

"datetime": [
            {
                ....
                "value": "2017-06-22T7:10:00.000-07:00",
                ...
            }
]
```
But I just get the current time in PST + 10 minutes

**What is the App ID where you are experiencing this issue (if applicable)?**
584ac155-f1bf-4f81-a6da-c9e7ea417537

**Comment by patapizza** [comment]
Closing in favor of #614.

**Comment by patapizza** [comment]
Hey @znat, `reference_time` should be inside `context`. Make sure you encode the context object correctly as a URL string.
