### ISSUE TITLE
request to change the meaning of "night" and "evening" to start from 5pm in datetime

### ISSUE THREAD

**Issue by bmcclenahan** [wit-ai/wit#638]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
feature

**What is the current behavior?**
when "night" or "evening" are used in a datetime in a message, the time range 6pm-12am is returned for the given date. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
observing usage by users entering "night" and "evening" into requests, they are expecting that 5pm would be included in the datetime range. currently "afternoon" seems to be from 12pm to 6pm. I believe a better interpretation of "night" and "evening" in a datetime would be 5pm to 12am. Could you please consider changing this setting ?

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by patapizza** [comment]
Hi @bmcclenahan,

`wit/datetime` is powered by [Duckling](https://github.com/facebookincubator/duckling).
There is an [open ticket](https://github.com/facebookincubator/duckling/issues/29) to override time assumptions.
