### ISSUE TITLE
Question - How to identity credit/debit card number input?

### ISSUE THREAD

**Issue by schatekar** [wit-ai/wit#641]
How do I identify credit/debit card numbers entered by users? I don't think I can use built-in entity for a number as 16 digit card number is just too big for it. Another complication is that users may enter card numbers in multiple different ways (as they appear on the card) e.g. four groups of 4 numbers for a 16 digit card number. 

I think I can capture the whole user input in an entity of trait type but I am not sure how to train the bot around such setting. What if user enters some text and then the number e.g. `Here is my card number 4444333322221111`?

**Comment by patapizza** [comment]
Hi @schatekar,

The best tool for the job seems to be a simple regex. Have you tried that?
