### ISSUE TITLE
Entity is not found from a large set of values - again

### ISSUE THREAD

**Issue by klemensz** [wit-ai/wit#642]
I cannot re-open the original issue https://github.com/wit-ai/wit/issues/548 - so I opened a new one. The issue still exists (after a new import). This is really a problem because the entity values change over time (new ones will be added), so we need to import periodically.

**Bug / Question**

I have an entity, let's call it "person", with something like 1000 values that I imported using the API. If I train the app "Tell me about John Doe" and mark John Doe as one of the person values, it will work. If I then try "Tell me about Mark Spencer" it won't recognize the name, although it's one of the values. Basically it means I would need to train each of the 1000 values once for it to work.

Also, if I type just "John Doe", it will be recognized, but not "Mark Spencer".

Expected behaviour: It should also recognize Mark Spencer as a person entity.

When we export the app, we can see that all the entity values are there in the exported JSON file. If we import even more values, the value won't even be recognized when highlighting it in the "training" input field.  

**What is the App ID where you are experiencing this issue (if applicable)?**

590c3891-b23b-4cb4-b5a2-c3cd0ef17397 and 5902737c-e922-4695-bed3-874f70abb502

**Comment by maximFromThe6ix** [comment]
I am having a similar problem that has only started occurring recently

**Comment by hlditdcstwita101** [comment]
I am new to wit.ai and don't know if mine is the same case as yours. I encountered it yesterday. For entity values which were uploaded via PUT/entities/:entity-id in batch, the values were not recognised.

Until I found out that "expressions" must be provided at least one content which is the same as the value content. Then it works. e.g. {"value": "hello", "expressions":["hello"]}....

**Comment by klemensz** [comment]
Following @hlditdcstwita101's hint we can not import the values and recognition will work correctly when using the API. What doesn't work yet is the recognition when using the "understanding" page on the website. It seems to recognize the entity but will also propose to create a new value. Only those 1000 or so values that are shown on the web page will also be recognized correctly. So it seems to be a web UI issue with some limit of the number of values.

**Comment by g10** [comment]
the wording is confusing:
> Create new value for "name-of-existing-value"
suggests it is recognised correctly (having the unique "name-of-existing-value"), so validating it works (next call on the api returns the correct value)

adding a new entity (selecting a word, linking to existing one) does not work if the values are not in the first 1000, which makes it impossible to train

also, can that label length be increased? `Create new value for "name-of-exi…` is hard to guess ;)

**Comment by l5t** [comment]
cc @stopachka
