### ISSUE TITLE
Cordova plugin

### ISSUE THREAD

**Issue by whimsicaldreamer** [wit-ai/wit#643]
Is there any plugin for using it with Cordova apps? Or is there any planning to do so?

**Comment by stopachka** [comment]
@whimsicaldreamer -- would node-wit work on cordova? It looks like it is a project based on node, so it may be possible to simply import it

**Comment by amuramoto** [comment]
There's one here for iOS, though I haven't used it, so can't speak to whether it's a viable plug-in. https://github.com/AdFabConnect/cordova-plugin-wit
