### ISSUE TITLE
Bot cannot recognise start and end time for a day/month

### ISSUE THREAD

**Issue by tanisha96** [wit-ai/wit#644]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
I want to extract start and end date-time from my bot.
Eg: "Send me data for today." -> bot must detect
Start-date_time = 2017-6-29 00:00:000
End-date_time = 2017-6-29 23:59:59

How do I go about this?

Currently, it just detects the default date-time:

![image](https://user-images.githubusercontent.com/25116272/27685294-2cccac24-5ceb-11e7-834b-d4787e96e260.png)

**Comment by l5t** [comment]
You will have to do this on your side and rely on the `grain`
![image](https://user-images.githubusercontent.com/6992759/27695726-9753a9e0-5ca4-11e7-98a2-dfe6f0d8d497.png)
