### ISSUE TITLE
[Export .zip of your data"] - The zip exported is not the entire dataset

### ISSUE THREAD

**Issue by giorgiomarzianidepaolis-was** [wit-ai/wit#645]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug/Question

**What is the current behavior?**
I have a huge and trained wit.ai application, many intents, lots of expressions validated. Exporting data results in empty intents and/or not the entire list of expressions.

**What is the expected behavior?**
Export the entire dataset

**What is the App ID where you are experiencing this issue (if applicable)?**
57e25ba9-ab3a-4928-b469-4c12d597dcbb

**Comment by yegeniy** [comment]
I can't confirm / give proof, but I feel like I have seen similar behaviour in previous versions of my model... It usually corrected itself if I try again in a little while.

**Comment by blandinw** [comment]
@giorgiomarzianidepaolis-was Thank you for your feedback!
This is really a limitation of the current system. This is one of our highest priority to fix in the coming months. We want to get our basics working really well, and we'll communicate about ours plans soon. Keeping this open to track
