### ISSUE TITLE
How to send the missing entity when bot requests

### ISSUE THREAD

**Issue by aravindtrue** [wit-ai/wit#647]
I want to ask a ***question*** about wit.

Here is the use case,

1. Just like Siri, user wants to create an event with subject, start date and end date
2. User can say `Create an event` or `Create an event with subject meeting starts tomorrow at 4pm` or `Create an event with subject meeting starts tomorrow at 4pm and ends tomorrow at 6pm`

When I execute the below request,
```
curl  -H 'Authorization: Bearer $TOKEN'
-XPOST 'ttps://api.wit.ai/converse?v=20170701
&session_id=234290348
&q=create%20an%20event%20with%20subject%20meeting%20with%20offshore%20team%20starts%20tomorrow%20at%206am'
```
I'm getting `message_subject: meeting with offshore team` and `startDateTime: 2017-07-02T06:00:00.000-07:00`. Then, I am creating a follow up request like,
```
curl  -H 'Authorization: Bearer $TOKEN'
-XPOST 'ttps://api.wit.ai/converse?v=20170701
&session_id=234290348' -d '{"subject": "meeting with offshore team", "startDateTime": "2017-07-02T06:00:00.000-07:00"}'
```
The bot is requesting the endDateTime in the response,
```
{
  "confidence" : 0.056668316354728646,
  "type" : "msg",
  "msg" : "What's the end date and time of the event?"
}
```
**Questions**

1. How to send the end date back to the bot i.e., endDateTime: Tomorrow at 5pm?
2. Why the confidence is really low and what are the ways to improve it?

**What is the App ID where you are experiencing this issue (if applicable)?**
59582926-5d14-41ec-8b98-580c911d944e

**Comment by aravindtrue** [comment]
Any idea or updates?

**Comment by blandinw** [comment]
If you describe this conversation in a story, you can extract the date using the built-in entity wit/datetime.
You can also just use the NLU feature of Wit (GET /message) to extract a date from the user message. I'll close, please reopen if you have further questions.
