### ISSUE TITLE
still not trained after 2 days

### ISSUE THREAD

**Issue by tobi418** [wit-ai/wit#648]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
some datas still not trained after 2 days later. (used HTTP API for train)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
you can query text "onigoo" but it is not classified

**What is the expected behavior?**
text "onigoo" is classified to "wit-onigoo" intent

**What is the App ID where you are experiencing this issue (if applicable)?**
58a2d010-677f-4e42-8d29-cd11b5db9c2e

**Comment by afedosin** [comment]
The same thing in my app.

**What is the App ID where you are experiencing this issue (if applicable)?**
594ac308-1b5a-4f3d-b9dc-686878f3302c

**Comment by blandinw** [comment]
@tobi418 Your instance is trained. "onigoo yapiach" gives intent "wit-onigoo".
I looked closer and "onigoo" gives "wit-onigoo" with 0.488 confidence, which is below our threshold, so we do not return it by default. You can get around this by specifying n=2 (or more) when calling /message to get the unfiltered list of guesses. In that case, please manually check the confidence level in your code.

@afedosin you'll have to provide more details, your instance seems to be trained as well.

Closing now.

**Comment by afedosin** [comment]
@blandinw what information should I provide?

App ID: 594ac308-1b5a-4f3d-b9dc-686878f3302c
Training status: ongoing. For a day now.
