### ISSUE TITLE
Question: How to specify a role in entity name in train API request?

### ISSUE THREAD

**Issue by afedosin** [wit-ai/wit#649]
I'm trying to train my app with API requests. How can I specify entity name with a role?

From the docs:
POST https://api.wit.ai/samples
entity - The entity name. This can be the name of an entity you created, or a builtin entity. i.e food or wit$on_off.

Is it possible to set the role?

**Comment by patapizza** [comment]
Hi @afedosin,

Did you try setting a "role" key?

**Comment by javimoya** [comment]
Hi @afedosin, I have the same issue. Did you find a way?
thanks

**Comment by blandinw** [comment]
duplicates #699
