### ISSUE TITLE
can't mark entities on a multi line input in hebrew 

### ISSUE THREAD

**Issue by Arsenikr** [wit-ai/wit#650]
i received input from a user: 

![screen shot 2017-07-04 at 10 14 05](https://user-images.githubusercontent.com/11831368/27819153-8978309c-60a1-11e7-8df8-c3883e45b1b9.png)
 
as you can see i mark the word "מעניין" but the entity chosen is "יחה מע" which is wrong.

note that in one liner messages it works correctly. i assume this is related to RTL.

also already trained entities that should have been identified and do identified in one liners, failed to identify here.

app-id: 591b5074-9f07-48b1-ba0e-36aa1fa756bb

**Comment by Arsenikr** [comment]
happened again.


anyone?

**Comment by stopachka** [comment]
hey @Arsenikr -- the UI currently does not handle tagging multi-line sentences well. This is something that we will work to address.

For the moment, feel free to simply remove line breaks from these sentences, and tag them. You will still be able to use /GET message on multi-line messages, and removing line breaks will not affect training.  

Alternatively, if you 100% wish to keep the multi-line aspect of it, you could use the POST /samples API to train via the API (https://wit.ai/docs/http/20170307#post--samples-link)
