### ISSUE TITLE
Unable to login with Github

### ISSUE THREAD

**Issue by Octylpy** [wit-ai/wit#651]
I can't seem to login with Github. After authenticating with Github, it just closes the Github sign in window and just sits at the public wit.ai page without refreshing or anything. I've tried different browsers, logging out of Github, clearing caches but nothing seems to be working.

There was one time where I tried to login and I got a plain JSON response of `{"body":"nope."}`. No idea what's going on.

Any help would be appreciated, thanks.

EDIT: I've also tried logging in with Facebook and I can't get past the screen that asks for a username, email and what I'll do with wit.ai. The "go down the rabbit hole" button doesn't do anything.

EDIT 2: Logging in with Facebook only seems to work on Safari, not Chrome or Firefox..

EDIT 3: After finally being able to login with Facebook, I closed my browser and now I can't login. Pressing the Github login button or Facebook login button shows a popup to login, but nothing happens after that. I can't get into Wit.AI's console in any way.

**Comment by l5t** [comment]
Thanks for reporting. Do you still experience the issue? I was able to log in just now.

**Comment by l5t** [comment]
Apparently confirmed it works now: https://github.com/wit-ai/wit/issues/652#issuecomment-313089401

**Comment by Octylpy** [comment]
@l5t Same here, looks I'm able to login normally now.

**Comment by eekshi** [comment]
Iam also facing the same issue Is any body know the solution?
