### ISSUE TITLE
Github login to wit.ai won't work

### ISSUE THREAD

**Issue by HimadriP** [wit-ai/wit#652]
When I hit the login via github button, an authorization request is sent but no change happens later. Can't login.

**Comment by mojobiri** [comment]
+1 same for facebook

**Comment by dmitriylab** [comment]
+1
Usually I'm using Chrome, login is not working now via GitHub, but using Mozilla I can login 15 minutes ago. Now even using Mozilla login is not working.
Also there are another problems - I tried to create application using API, didn't receive response from API request, tried to create for 4 times - no application was created. But after 10 minutes 4 application with the same name are created, and I can't delete these applications.
Could you please help with this common problem.

**Comment by vladislav-sevostyanov** [comment]
+1

**Comment by dmitriylab** [comment]
Now it seems to be working.

**Comment by l5t** [comment]
Thanks for confirming. We are investigating on what could have happened.

**Comment by HimadriP** [comment]
Thanks, the issue is resolved.
