### ISSUE TITLE
Feature request: Samples CRUD

### ISSUE THREAD

**Issue by hristoborisov** [wit-ai/wit#655]
Hello Wit Team,

We are programmatically training chatbots on top of Wit.ai from existing client's data, and we find it very limiting that the Samples API doesn't support full CRUD operations, and just creation of new samples.

Without providing meaningful samples, the Wit.ai is not returning good confidence for entities. That is why, we provide a UI for our clients to provide Sample expressions, and we want to make sure that users can add and remove samples if they are no longer valid.

We really appreciate that Wit.ai is moving in the direction to make it's NLP as a service offering, and is far beyond the rest of the competitors.

Thank you for considering this,
Hristo

**Comment by blandinw** [comment]
@hristoborisov thanks for your feedback. I agree that we should at least provide a way to delete samples that are no longer relevant. Keeping this as a feature request to be prioritized soon.

**Comment by pierodetomi-euris** [comment]
Hello, do you have any update on this? I think this feature is vital for who relies only on the API...
Any idea on when this feature will be available?

Thank you in advance,
Piero

**Comment by stopachka** [comment]
Hey @pierodetomi-euris, could you expound a bit on your use case, and which part of the API is the most vital? (i.e only DELETE /samples, or is there a different need?)

**Comment by stopachka** [comment]
Cheers @pierodetomi-euris, 

I will report back on this, with a timeline. We are currently hard at work migrating the underlying infra to scaled FB infra. This is a highly requested feature though, and we'll see what we can do to ship this to you :)

**Comment by pierodetomi-euris** [comment]
Sounds good! Looking forward to hear about the timeline :)

Thank you,
Piero

**Comment by pierodetomi** [comment]
Hi @stopachka, any news on the timeline for that feature?
Sorry to bother you again, but I need to at least have an idea of how we'll have to wait for this. :)

Thank you in advance,
Piero

**Comment by stopachka** [comment]
Hey @pierodetomi I should have answer to the timeline by the end of the week

**Comment by gorenbox** [comment]
Hi @stopachka . Is there an update on this much needed feature?

**Comment by blandinw** [comment]
@gorenbox DELETE /samples is coming very soon (in the next few weeks)

**Comment by gorenbox** [comment]
THANK YOU

**Comment by stopachka** [comment]
(reopening to track the GET side of samples crud)
