### ISSUE TITLE
Training status ongoing With Bookmark problem

### ISSUE THREAD

**Issue by MathieuDuboy** [wit-ai/wit#656]
Here is my App : https://wit.ai/mathieuduboy/SucBotv2 and it seems to be a bug this evening in my stories.

The training status is very long and sometimes I t takes more than a minute to train the bot.
More, when I add a Bookmark, all my stories are acting strange. The bot doesn't recognize the good intent. It's only when I add one bookmark. I had to remove all of them in order to work properly.

Why can't I add or re-create bookmarks in my stories ?

Thank you very much for your help.

**Comment by blandinw** [comment]
@MathieuDuboy thank you for your feedback, this does sound like a bug.
However, you need to follow the issue template provided, otherwise we can't help you.
Please reopen with more details:
```
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**
```
