### ISSUE TITLE
How to POST /samples with built-in entities (e.g. wit$datetime)

### ISSUE THREAD

**Issue by yegeniy** [wit-ai/wit#657]
This is a _question_:

**What is the [canonical value](https://wit.ai/docs/http/20170307#post--samples-link) we should use for POST /samples containing `wit/datetime`?**

As per https://wit.ai/docs/http/20170307#entities-format, `wit/datetime` requires an ISO value, but that's not always easy to figure out without using the Understanding tab in the wit.ai GUI for each example.

Should we interpret 
> value | required | string | Canonical value of the entity or the text span

as "Canonical value of the entity, or just the text span defined by `start` and `end`."

**What is the current behavior?**

> curl -XPOST 'https://api.wit.ai/samples?v=20170307'
 -H "Authorization: Bearer P77LZZKUKJZW532WCB2IWF6KILC4HZK2"
 -H "Content-Type: application/json"
 -d '[{"text":"what about the game next Tuesday?","entities":[{"entity":"intent","value":"gameinfo"},{"entity":"wit$datetime","value":"next Tuesday","start":20,"end":32}]}]'`

response is:

```
{
  "sent" : true,
  "n" : 1
```

and downloading the app as a zip provides us with a zip that contains the value I encoded; however, when putting the data in via the Understanding tab, an ISO-8601 payload appears.

```json
{
  "data" : [
    {
      "text" : "tomorrow",
      "entities" : [
        {
          "entity" : "datetime",
          # This is the value set by the Understanding tab
          "value" : "\"2017-07-10T00:00:00.000-07:00\"",
          "start" : 0,
          "end" : 8
        }
      ]
    },
    {
      "text" : "what about the game next Tuesday?",
      "entities" : [
        {
          "entity" : "datetime",
          # This is the bogus value I set. Am I ruining my model? Should I figure out the correct ISO8601 value for Tuesday by leveraging Duckling? or is wit.ai already ignoring my provided value and leveraging Duckling?
          "value" : "\"next Monday\"",
          "start" : 20,
          "end" : 32
        }
      ]
    }
  ]
}
```

**Comment by yegeniy** [comment]
Setting the value of "what about the game next Tuesday?" to be the `wit/datetime` of "next Monday" doesn't seem to ruin wit.ai's ability to detect the datetime as Tuesday the 11th, instead of Monday the 10th:

```
> set --local api_key 2HHMLPLGE4DCVKQL6LRSL4GIMDFR5YKS;
> curl -s -H "Authorization: Bearer $api_key" \
"https://api.wit.ai/message?v=20160526&q=what+about+the+game+next+Tuesday?" | jq '.'
{
  "msg_id": "0misrTmf1CkBmhIYJ",
  "_text": "what about the game next Tuesday?",
  "entities": {
    "datetime": [
      {
        "confidence": 0.99878863902093,
        "values": [
          {
            "value": "2017-07-11T00:00:00.000-07:00",
            "grain": "day",
            "type": "value"
          }
        ],
        "value": "2017-07-11T00:00:00.000-07:00",
        "grain": "day",
        "type": "value"
      }
    ]
  }
}
```

**Comment by yegeniy** [comment]
It seems that POSTing these built-ins work, but they won't show up in the UI or the .zip backup unless an utterance is trained manually with the GUI

**Comment by blandinw** [comment]
@yegeniy Thank you for your feedback.
What do you mean by they won't show up in the UI?
Does this tutorial help? https://github.com/wit-ai/wit-api-only-tutorial#add-date-detection
I'm trying to understand what we can do better.

**Comment by yegeniy** [comment]
Wow! @blandinw this looks awesome and is exactly the resource I was looking for! Consider adding that link in big bold letters at the top of https://wit.ai/docs/http/20170307 :)


---


> {
            "entity": "wit$datetime",
            "value": "tomorrow",
            "start": 26,
            "end": 34
          }

This tells me that using the "value" from the sentence is enough for the `POST /samples` endpoint to allow the `wit$datetime` entity.
 
I'll close this issue out and check the tutorial out some more!
