### ISSUE TITLE
Feature request: Import API

### ISSUE THREAD

**Issue by jagreene** [wit-ai/wit#658]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Feature

**What is the current behavior?**
POST to /app doesn't allow .zip payloads

**What is the expected behavior?**
It would be awesome to be able to programmatically upload exported apps. This would allow us to automate our back up process and allow us to create new stores by modifying and posting the exported zip files

**Comment by yegeniy** [comment]
There is a workaround of sorts for now: 

1. [POST /apps](https://wit.ai/docs/http/20170307#post--apps-link)
1. [PUT /apps](https://wit.ai/docs/http/20170307#put--apps-link) for any attributes, such as timezone.
1. [POST /entities](https://wit.ai/docs/http/20170307#post--entities-link)
1. [POST /samples](https://wit.ai/docs/http/20170307#post--samples-link)

That should get you to the same place. 

The only problem is that creating the samples is not the easiest job. I'm planning on making some small modifications to this [script to generate the samples to POST](https://gist.github.com/yegeniy/5d058a9be74630cefe64412eb56f1e2f#file-test1-txt), but am still unsure of [how to add built-in entities to the POST /entities and POST /samples endpoints](wit-ai/wit#657)

**Comment by blandinw** [comment]
Thanks for your feedback!
Relabeling the issue as feature request for a proper /import API

**Comment by yegeniy** [comment]
Ignore my comment. This API tutorial should be enough to get started until a `/import` API is created:

 https://github.com/wit-ai/wit-api-only-tutorial

**Comment by gorenbox** [comment]
@stopachka @blandinw If i may give my thoughts about the import api....
I think the main thing is that it should be an append operation. That way you can easily add to an existing model (which is the main use case), or create a new one, by appending to an empty model.
Thanks again for all the great work on the apis lately

**Comment by aforaleka** [comment]
Thanks for the feedback @gorenbox, we'll definitely consider it!

**Comment by gorenbox** [comment]
Hi, would it be possible to update about the import api. I think we discussed it about a year ago here and in some other threads.

**Comment by aforaleka** [comment]
Hi @gorenbox, we have prioritized it and will have it done in the near future. Thanks for your continued support in Wit!

**Comment by gorenbox** [comment]
Wow.

Thank u!!

**Comment by FengyangZhang** [comment]
The import API is added, you can find it in the doc: https://wit.ai/docs/http/20170307#post__import_link

**Comment by gorenbox** [comment]
Thank u so so much!!
