### ISSUE TITLE
App has been training for a week

### ISSUE THREAD

**Issue by maximFromThe6ix** [wit-ai/wit#660]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
Will not stop training, also some of the expected behaviour that I was getting in a previous app from which I imported the data for this current app is not occuring anymore
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Not train forever
**What is the App ID where you are experiencing this issue (if applicable)?**
594bfa3f-42d2-4d9d-9ec6-f6a41f60bfdc

**Comment by l5t** [comment]
Just restarted
