### ISSUE TITLE
failed to validate run

### ISSUE THREAD

**Issue by aawaheed** [wit-ai/wit#662]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
*bug*

**What is the current behavior?**
Everything seems to be working fine until last 20-30 min. Now unable to save stories and create new entity.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
try to edit a story

**What is the expected behavior?**
should save

**What is the App ID where you are experiencing this issue (if applicable)?**
5963592c-d4ab-43ab-ab27-02d472d90f2d

**Comment by blandinw** [comment]
Are you still experiencing the issue?
If so, what is the actual behavior? What do you mean by "unable to save Stories"?
Does it hang, do you see any error?

Closing, please reopen with more info if needed.
