### ISSUE TITLE
Previously working training data, has strange effects when imported into new instance

### ISSUE THREAD

**Issue by maxim-isakov-ross** [wit-ai/wit#663]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
I have imported previous instance data into a new instance and 99% of my training data was unchanged but certain entities are no longer being detected like they were before and my intents are wrong at times.

And certain times a completely blank response is provided, like so:

{
"msg_id": "0kJfPfB4BWIwjPWAY",
"_text": "Sample Sentence",
"entities": {}
}

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**
App ID: 594bfa3f-42d2-4d9d-9ec6-f6a41f60bfdc

**Comment by blandinw** [comment]
Your app seems to be responding fine though.
```
λ curl \
 -H 'Authorization: Bearer <REDACTED>' \
 'https://api.wit.ai/message?v=20170712&q=Sample%20Sentence'

{"msg_id":"04yRO0q9sqywa7aEK","_text":"Sample Sentence","entities":{"intent":[{"confidence":0.57140916979722,"value":"answer"}]}}
```

What are the steps to reproduce your issue?

**Comment by maximFromThe6ix** [comment]
@blandinw try this url:

https://api.wit.ai/message?v=20170627&verbose=true&q=493 U.S.P.Q. 59
