### ISSUE TITLE
Manual audio transcripts are being reset

### ISSUE THREAD

**Issue by Krogsager** [wit-ai/wit#665]
Either I'm using Wit wrong or there is a bug. 
I have 8 audio clips, transcribed, in my inbox. I am able to edit the transcript and validate it, but when i reload the page, the transcript is reset to the wrong machine translation. 

http wit.ai/'username'/'appname'/inbox/semantic
I expected this to be my platform for training the voice recognition.  (Danish language)

AppID 
595f485e-00ab-40cb-a114-87648bb35fd0

**Comment by blandinw** [comment]
@Krogsager thank you for your feedback!
Can you confirm that the transcript is wrong after refreshing ~30 seconds later?
I want to understand if the update fails or if it's just really slow.

**Comment by Krogsager** [comment]
Without a doubt, the transcrit do not update. I tried edit them multiple times. 24-48 hours later they are still the original machine translation.

**Comment by Krogsager** [comment]
Additionally, the red mark on the inbox remains after all expressions have been validated or deleted.
![image](https://user-images.githubusercontent.com/27994384/28206057-dd7f17a6-6884-11e7-8705-b9b60584538e.png)
