### ISSUE TITLE
wit/datetime : wrong understanding for a French sentence

### ISSUE THREAD

**Issue by sophieso16** [wit-ai/wit#666]
Just want to report a new bug: 

I've created a private French app in wit.ai. 

The purpose is to create an event for a contact. 

Since several days, when I train the bot (in the "Understanding" section) with sentences like this one:
"Ana **a un** cours de tennis"
This part of the sentence "**a un**" is selected as a **wit/datetime**.

Please find a screenshot of the situation:
<img width="975" alt="capture d ecran 2017-07-12 a 17 15 02" src="https://user-images.githubusercontent.com/26087031/28128003-289392c2-6726-11e7-89bb-51b5c2a3a410.png">

**Comment by blandinw** [comment]
@sophieso16 thank you for the report! Definitely a bug
