### ISSUE TITLE
wit/datetime, am/pm vs 24h notation collides at 12 and midnight

### ISSUE THREAD

**Issue by peterel** [wit-ai/wit#667]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug

**What is the current behavior?**
All that has 12:XX gets "translated" to "00:XX". While e.g. 13:XX gets translated correctly to 1:XXpm.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

<img width="996" alt="screen shot 2017-07-13 at 01 00 59" src="https://user-images.githubusercontent.com/24371993/28143735-7b4641fe-6767-11e7-96a4-ee707cdec270.png">

**What is the expected behavior?**
12:XX should translate to 12:XX and not "00:XX".

**What is the App ID where you are experiencing this issue (if applicable)?**
591618b7-2b5a-49eb-aa92-87d8fdc06652

**Comment by peterel** [comment]
Hmm, I guess it needs to default to either 12:00 (noon) or 00:00 (midnight) when someone writes "12:00". My question is, how do I get it to default to noon when writing "12:XX"?

**Comment by l5t** [comment]
can you post the issue in our open source parser that manages this entity: https://github.com/facebookincubator/duckling
