### ISSUE TITLE
Date periods without any boundaries

### ISSUE THREAD

**Issue by camdufau** [wit-ai/wit#668]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Ask a question

**What is the current behavior?**
"from January 2017" or "since January 2017" return only "01/01/2017"

**What is the expected behavior?**
How can it return "01/01/2017 to 31/01/2017" even if I don't write the full "from X to Y" or "since X until Y" sentence.

**Comment by l5t** [comment]
Currently you will have to rely on the "grain" as we don't return interval. Technically "since" should return you from <date> to <now>. You can follow and post the issue in our open source parser that manages this entity here: https://github.com/facebookincubator/duckling
