### ISSUE TITLE
Quick replies on Facebook messenger

### ISSUE THREAD

**Issue by PN9** [wit-ai/wit#669]
We have implemented quick replies in wit.ai but the replies dont seem to appear when integrated with Facebook messenger. Can any one let us know how to implement quick replies on facebook messenger.

Thanks in Advance!

**Comment by yegeniy** [comment]
https://developers.facebook.com/docs/messenger-platform/send-api-reference/quick-replies

I would recommend starting there.

@PN9 - it might be a bit more than you're looking for, but as far as I know, wit.ai has very little to do with facebook messenger, other than a few tutorials that show you how to integrate the two.

**Comment by blandinw** [comment]
Closing, feel free to reopen if something is blocking you.
