### ISSUE TITLE
The HTTP API is getting slower with 1 to 2 seconds avg responses times

### ISSUE THREAD

**Issue by m19brandon** [wit-ai/wit#670]
**Do you want to request a feature, report a bug, or ask a question about wit?**
Bug - Performance is slow

**What is the current behavior?**
The HTTP message API has always return results between 0.500ms to 1 seconds.

For the past month or so is has been trending up to between 1 and 2 seconds but it is not uncommon to see 3 and 5 seconds response times.

My code is in Python but I use the HTTP message API and I can recreate with the curl examples from the docs.

curl -o /dev/null -s -w %{time_total}\n -H 'Authorization: Bearer sometoken' 'https://api.wit.ai/message?v=20170514&q=test'

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
curl -o /dev/null -s -w %{time_total}\n -H 'Authorization: Bearer sometoken' 'https://api.wit.ai/message?v=20170514&q=test'

**What is the expected behavior?**
.500ms would be great. I understand that a new code base is coming out soon, can we move early. A 1 to 2 seconds response time makes for a poor user experience.

**What is the App ID where you are experiencing this issue (if applicable)?**
554d70e9-7074-4d2c-bc86-b2dc1833fb75

**Comment by m19brandon** [comment]
Between 7/16 22:30 and 22:50 EDT
```bash
curl -o /dev/null -s -w %{time_total}\n -H 'Authorization: Bearer sometoken' 'https://api.wit.ai/message?v=20170514&q=test'
1.926818

curl -o /dev/null -s -w %{time_total}\n -H 'Authorization: Bearer sometoken' 'https://api.wit.ai/message?v=20170514&q=test'
1.070027

curl -o /dev/null -s -w %{time_total}\n -H 'Authorization: Bearer sometoken' 'https://api.wit.ai/message?v=20170514&q=test'
1.107358

curl -o /dev/null -s -w %{time_total}\n -H 'Authorization: Bearer sometoken' 'https://api.wit.ai/message?v=20170514&q=test'
1.055638

curl -o /dev/null -s -w %{time_total}\n -H 'Authorization: Bearer sometoken' 'https://api.wit.ai/message?v=20170514&q=test'
1.025842

curl -o /dev/null -s -w %{time_total}\n -H 'Authorization: Bearer sometoken' 'https://api.wit.ai/message?v=20170514&q=test'
1.419672
```

**Comment by blandinw** [comment]
Thanks for the detailed report @m19brandon!
This looks like an inefficiency for your app in particular. I'll look deeper into how the time is spent and will probably be able to speed it up. Stay tuned

**Comment by m19brandon** [comment]
Wow, 0.391s that is fast. What did I do so I don't do it again and how do I figure it out without help next time? Thanks

**Comment by blandinw** [comment]
@m19brandon There's nothing you can do at the moment. We're in the process of replicating our service across the world, leveraging FB datacenters to reduce worst-case latency. Where in the world are you calling us from?

**Comment by m19brandon** [comment]
East Coast USA

**Comment by blandinw** [comment]
Thanks for your input! I'll close this issue for now. We did a lot of work to improve the reliability of the API (should not go down, and should be able to handle more load), but we're still in the process of doing performance work (basically reduce latency). I can't give you a more precise time estimate, but it will happen before the end of the year, hopefully in the next few months.
