### ISSUE TITLE
Wit AI returns type: 'stop' when 'jump' is required in 'Stories'

### ISSUE THREAD

**Issue by AbdullahUsmani** [wit-ai/wit#672]
I have an issue, probably I am missing something.

I have made just 1 story for an intent ('*apptMake*' - to make an appointment). On successful intent recognition, the bot asks the user for date. When the user sends a date, the bot successfully recognizes an entity of type '*datetime*' but the '*type*' I receive is '*stop*'.

I have added a '*Jump*' in the end, pointing to the flag above '*makeAppointmentMerge*'. So shouldn't it return: *'type':'action', 'action':'makeAppointmentMerge'* ?

![witquery](https://user-images.githubusercontent.com/10168941/28401889-7c8a4226-6d3a-11e7-9062-768c1fe6d070.png)

Here is a link the public app: https://wit.ai/abpn77ahtest/appointment_bot/stories. I was testing the story using http APIs on Postman.

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018.https://wit.ai/blog/2017/07/27/sunsetting-stories
