### ISSUE TITLE
Website redirects when validating voice recordings

### ISSUE THREAD

**Issue by Krogsager** [wit-ai/wit#673]
Bug report:
[Screen Recording (18-07-2017 09-31-19).zip](https://github.com/wit-ai/wit/files/1155003/Screen.Recording.18-07-2017.09-31-19.zip)

Given a list of voice recordings at https://wit.ai/'username'/'appname'/inbox/voice,
When I start training after pressing the green button "Start Training (2 minutes)",
Then I am redirected to https://[...]inbox/voice, when I press the dark-green Validate button

I expect the browser to stay at at the voice training page.

**Comment by stopachka** [comment]
Wow, that is a bug. Thanks for reporting @Krogsager -- on it

**Comment by stopachka** [comment]
fixed!
