### ISSUE TITLE
My story keep being failed because wit/duration entity doesn't recognize March... ?!

### ISSUE THREAD

**Issue by misysdclabs** [wit-ai/wit#674]
Hi Guys,

I have a story where I recognise date duration with built-in wit/duration. During the learning phase it works well, recognise everything, like last month, July, 2017, from 5th till 13th of June, etc. When I build a story with it I get stuck in failed status :(

![image](https://user-images.githubusercontent.com/14309287/28307475-589e3252-6ba3-11e7-8bf9-312f2858ed70.png)

I tried to push on the red arrow, reteach the whole sentence at least ten times, but still no luck. Even though, I see that it learned well well my "March" sentence (in the understanding section, at the wit/duration entity):

![image](https://user-images.githubusercontent.com/14309287/28307192-5e001108-6ba2-11e7-9242-c15b9a2bba9c.png)

What am I doing wrong?

Best,
Krisztián

**Comment by yegeniy** [comment]
You may want to use `wit/datetime` @misysdclabs instead of `wit/duration` (duration is for _periods_ of time such as "1 month", not for specific times (such as "march").

**Comment by yegeniy** [comment]
Search for `wit/datetime` in https://wit.ai/docs/http/20170307 for more documentation

**Comment by misysdclabs** [comment]
@yegeniy thanks, that's my fault - I mixed with api.ai, there you can use sys.date-period like this.
