### ISSUE TITLE
Feature request: Create Samples with composite entities using HTTP API

### ISSUE THREAD

**Issue by justinaL** [wit-ai/wit#675]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Feature

**What is the current behavior?**
Currently `POST samples` API endpoint doesn't support creating samples with composite entities.

**What is the expected behavior?**
A way to create composite entities using `POST /samples` API endpoint

**Comment by stopachka** [comment]
(this is now implemented)
