### ISSUE TITLE
Quick replies not working in wit.ai Node.js Integration

### ISSUE THREAD

**Issue by Ghost1999** [wit-ai/wit#676]
I made a node.js app with heroku, I integrated it with Wit.ai , sending and recieving messages.are optimal but i cant seeem to make the quick replies aka.(buttons with text in them as choices to work) please help
I used this
https://github.com/JakobReiter/WitAI-Facebook-Messenger-chatbot-boilerplate

**Comment by blandinw** [comment]
What do you call quick replies? What is your app id? Is it a problem with Messenger Platform or Wit?
Please reopen with more info

**Comment by Ghost1999** [comment]
The buttons that the user can pres on messenger as areply like yes or no buttons underneath question they are called quick replies in wit.ai

**Comment by blandinw** [comment]
Thanks for the clarification, you need to open an issue on https://github.com/JakobReiter/WitAI-Facebook-Messenger-chatbot-boilerplate. We're not responsible for this project.
