### ISSUE TITLE
Question : Wit wrongly recognizes linking words

### ISSUE THREAD

**Issue by camdufau** [wit-ai/wit#677]
Hello,
**What is the current behavior?**
I created an entity state which contains US states names as "NY","IN","ON",CA".
When Wit get a sentence with a connector like "in Carnegie Hall" or "on the year 2017" it recognizes them as US state.

**What is the expected behavior?**
I would like Wit to not recognize these words as entity "state".
Could you help me on the training strategy for this?

Thanks.
Camille.

**Comment by blandinw** [comment]
Hi Camille, thank you for your feedback 🙂
I'd be happy to look into your issue, but I can't reproduce it.
Please provide your appid and reopen this issue
