### ISSUE TITLE
[Feature request] Foreign language names recognition

### ISSUE THREAD

**Issue by elegos** [wit-ai/wit#679]
Hello! I'd like to expose a problem I've faced using Wit.ai. I'm currently developing a home-made multi-purpose home AI, with as first "module" a Spotify-connected speaker functionality.

I'd like to talk to this speaker in order to let it change the music by talking to it, like "let's play some jazz", or "play 'Le Papillon Solitaire' of Franz Gordon".

The problem is that I want to run this AI in a language different from English, and even then, it's hard to let Wit.ai recognize the artists' names, because most of them are not in English, or even if in English, not in a "standard" form.

So I'm facing two different problems:

- the first is if I set the language of my Wit.ai AI, I won't be able to correctly detect foreign words (see the example above). This could be solved by allowing foreign words "if not clearly detected in the current language". Not an easy task though, I assume.
- the second is a known words dictionary for "public" names, so that Wit.ai is able to easily detect the artists' names.

**Comment by l5t** [comment]
Indeed that would be great. We have been focusing our energy on scaling Wit as we went from 20K to [100K developers on our platform](https://wit.ai/blog/2017/04/18/supporting-100000-developers-and-beyond).
To be completely honest with you, speech is not a priority anymore for us as most of our community are building for text input (chat bots). We provide a generic speech model that works pretty well for turning speech into commands or actionable data. We also provide the text but as a piece of information only as speech engine usually makes mistakes. We may re-prioritize speech at some point in the future.
As an ugly workaround, you may try to have 2 wit apps (one in English and one in the other language) and query both.

**Comment by blandinw** [comment]
Hi @elegos, thank you for your input.
Basically, what @l5t said. We don't support mixed languages in our speech recognition and don't have plans to add it to the API. Closing as wontfix
