### ISSUE TITLE
zip backup is strangely indented all of a sudden

### ISSUE THREAD

**Issue by yegeniy** [wit-ai/wit#682]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

I want to report a *bug*.

**What is the current behavior?**

At some point in the last few days, the .zip file that we pull down got seriously indented. This isn't too bad, since the data wasn't affected, but it doubled the size of my `.zip` backup, and made creating a `diff` difficult.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

To reproduce, download a .zip backup of an existing wit.ai model.

The `expressions.json` file will look like this (note how far to the right every line but the first one is):

```json
{
                                                                                                                        "data" : [
                                                                                                                          {
                                                                                                                            "text" : "Angels last score",
                                                                                                                            "entities" : [
                                                                                                                              {
```

**What is the expected behavior?**

I would expect that it look like it previously did:

```json
{
  "data" : [
    {
      "text" : "Angels last score",
      "entities" : [
        {
```

**What is the App ID where you are experiencing this issue (if applicable)?**

In case this is just unique to me, the App ID is `5963c176-4180-494d-ab78-e5766208cf62`

**Comment by blandinw** [comment]
Thank you for your feedback!
Hm, that's very odd, especially if it started happening in the last few days...
I'll keep open as bug and part of our import/export improvement work.

**Comment by yegeniy** [comment]
And now it's resolved!

> ....zip | Bin 11649 -> 7055 bytes
