### ISSUE TITLE
Cannot create new values for intent entitity - Internal Server Error

### ISSUE THREAD

**Issue by klemensz** [wit-ai/wit#683]
**Bug**

**What is the current behavior?**

Trying to create a new intent value using the "Understanding" or "Stories" web UI results in an Internal Server Error after 39 seconds. 
PUT https://api.wit.ai/sync?verbose=true 500 (Internal Server Error)
The response is "Something went wrong. We've been notified."

Basically what I do is to add a new value for the "intent" entity, and then click "Validate" (or Save in stories). This error started to appear something like 2 weeks ago. I can see in the Chrome developer console that a 500 error is returned.

**App ID**
5902737c-e922-4695-bed3-874f70abb502

**Comment by blandinw** [comment]
Thanks for your feedback, I'm looking into

**Comment by blandinw** [comment]
@klemensz I looked at your app and cannot reproduce the issue. Is it happening every time you validated an expression? Do you have steps to reproduce it?

**Comment by blandinw** [comment]
I assume you used Chrome Network inspector to see that 500 Internal Server Error.
If this happens again, could you right-click on the failed request, select Copy as cURL and paste the output **in an email to my first name at fb.com**? (do not post it publicly here).

**Comment by klemensz** [comment]
Sent you an email with subject "Wit Github Issue #683".

**Comment by blandinw** [comment]
Found the root cause. A keywords entity had several canonical values with the same name and different metadata. Wit got confused and returned a 500 instead of a useful error message. I'm fixing Wit to return a helpful error message when the data is inconsistent.

**Comment by jojoman2** [comment]
I have this problem as well. For me it made the entire instance stop working. Luckily, I found this post so I was able to find the cause. It would be incredibly helpful if Wit would give a better message. Possibly it could be given already when inserting the conflicting value.

**Comment by blandinw** [comment]
We just deployed something that should help diagnostic this issue, with a helpful error message both in the UI and the API. Please let me know if you encounter this problem again and the error message is not clear.

**Comment by klemensz** [comment]
Now I get a 504 (server timeout) error when I try to validate a new sentence.

![bildschirmfoto 2017-08-24 um 10 30 39](https://user-images.githubusercontent.com/1116517/29657293-6f76f474-88b7-11e7-96a9-2c5a03ef4d47.png)

**Comment by stopachka** [comment]
hey @klemensz 

Could you right click on the failed request, copy as curl:

![image](https://user-images.githubusercontent.com/984574/29692399-a0de16dc-88e4-11e7-9894-9192e717c5a5.png)

You can send it to (stopachka [at] fb.com), Happy to take a look

**Comment by klemensz** [comment]
Any update on this? I still get the 504 error.

**Comment by stopachka** [comment]
Hey @klemensz  -- If you could send me the curl I'd appreciate it -- if you have already and I missed it, apologies. let me know your email and I can dig through

**Comment by klemensz** [comment]
I already sent it on August 25 - my email is zleptnig [at] creativeworkline.at - let me know if you have it, otherwise I can send it again.

**Comment by stopachka** [comment]
Found it! Oky doke, looking. Will aim to update asap. Thanks for the patience @klemensz

**Comment by blandinw** [comment]
@klemensz this has now been fixed. We had an inefficient piece of code in the validation pipeline, which did not play well with your large dictionary of values.
Thank you for reporting this bug and for your patience.
