### ISSUE TITLE
Question about extracing an "amount" (either a fraction, a whole number or the two combined)

### ISSUE THREAD

**Issue by geoffreydv** [wit-ai/wit#684]
I have a question about something I noticed the learning AI seems to have trouble with picking up.

I'm training the model to recognize parts in ingredients of a recipe. Some examples are:

- 1/3 cup onion (your favorite kind, raw or sauteed, chopped or strips)
- 1/2 tablespoon sugar
- 1 1/3 cloves of garlic

I'm trying to extract the "amount", the "unit" and the "product". For the first example that would be:
amount: "1/3", unit: "cup", product: "onion". Note: amount is my own amount entity, not the wit/amount one.

I think I have provided about 200 examples, the accuracy of extracting the unit and the product was quite good after a couple of entries.

My question is about the amount. Even after about 200 training entries it fails very often. Some valid amounts would be "1", "1 1/3", "1/3", "7/8". Instead I almost always get all the different digits as separate amount entitites and the slash is not included.

So in the "1 1/3" case it would return 1, 1 and 3, no slash.

My guess is that it is hard because "1" or "3" also appear on their own as a unit in the training data.

My question is if there is anything I can do to to improve the accuracy here or some more explanation why this is hard to learn. Maybe I just need to provide a couple of 100 more training entries?

The app id is 59783580-2842-4be2-a254-71ec0d0fdd34

**Comment by patapizza** [comment]
Hi @geoffreydv,

Since ingredients of a recipe follow a common structure, it is probably better to use a rules engine to deal with that. `wit/quantity` relies on [Duckling](https://github.com/facebookincubator/duckling) for that.
Have you tried `wit/quantity`? What doesn't work? Would you be able to extend Duckling to support that?

Thanks.

**Comment by geoffreydv** [comment]
Hello @patapizza,

To be honest, I did notice that the entity wit/quantity was there but had no clue how to use it. 

I created the entities product and unit like the description said. After that I selected the whole ingredient text and marked it as a wit/quantity. Somehow I expected it to split it into the three parts (an amount, unit and product). I didn't get some kind of visual feedback there that it "worked".

At that point I decided I wanted to try to just mark the different entities and not use the wit/quantity which seemed to give pretty accurate results after a couple of examples. This made me continue down that path :)

This is probably me not marking the sentence correctly or doing something wrong but I thought I'd share my thought process here. I'm going to look into the documentation a bit more to see if I can find something there that I missed.

Thanks for bringing up the Duckling project, it's interesting to learn how the parts of wit fit together! If I can get the quantity entity to work maybe I can extend the project with some of my training examples that it doesn't pick up correctly.

**Comment by patapizza** [comment]
Thanks for the thorough explanation!

`wit/quantity` doesn't need `product` and `unit` anymore; we need to update the documentation to reflect that. The best way to see if it works would be to query the `GET /message` API directly.

Please give it another try, and see if there is a way to extend Duckling to support what doesn't work today. I'll go ahead and close the issue now, and feel free to reopen if you are stuck!

Thanks.
