### ISSUE TITLE
Stuck in training

### ISSUE THREAD

**Issue by Rolfjdra** [wit-ai/wit#685]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
Training status: ongoing
Stuck in training. Can you reset it manually? :)
Any tips on how to avoid this in the future, as my app will undergo a lot of training?

**What is the App ID where you are experiencing this issue (if applicable)?**
5975e26e-10a1-4138-ada3-dab53b2f624c

Thank you

**Comment by l5t** [comment]
can you share the wit app url as well ?

**Comment by Rolfjdra** [comment]
Here is the app url:
https://wit.ai/Rolfjdra_066PP/GupshupBot/entities

Thank you so much!

**Comment by l5t** [comment]
Done
