### ISSUE TITLE
wit ai doesn't understand the word drill as a qualifier for Intent

### ISSUE THREAD

**Issue by rotsen49** [wit-ai/wit#686]
**I want to report a *bug*

**What is the current behavior?**
1) I input the word drill into a User says sentence ... Example: "Get me the drill" and I associate the default intent as the value "D1"

2) Then I run the microphone app and speak the phrase "Get me the drill" through my client connection
    then it hardly ever makes the connection to get me the value "D1" ... and I've tried to teach it through the inbox.

3) If I create the User phrase: "Get me drama" and I associate the default intent as the value "DR" then I get the "DR" value 90% of the time after speaking the phrase into the microphone.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
AD ID : 5975d85a-37e4-4682-92ae-92d2074b17f8
Client Access Token: 3QRTMRIZ7VMZECAPOTDW5PCU5EA3P7GR

**Comment by patapizza** [comment]
Hi @rotsen49,

It looks like your entity `intent` has the search strategies `free-text` and `keywords`.
All your validated samples for `intent` don't have a span in the text, so the search strategy should be `trait` (as it is initially).

Can you try to set it back to `trait` and once it's retrained, see how it goes?
Feel free to reopen the issue if that doesn't work.

Thanks.
