### ISSUE TITLE
*Bug* Wit/Number

### ISSUE THREAD

**Issue by jroysdon** [wit-ai/wit#687]
I have two inputs where the "bold" are wit/number expressions : 

Find me a game for **10** - **12** players

NUMBER :  [ 
{ confidence: 1, value: 10, type: 'value' },
{ confidence: 1, value: -12, type: 'value' } ]

Find me a game for **2** - **12** players
NUMBER :  [ 
{ confidence: 1, value: 212, type: 'value' } ]

The first works fine as expected whereas the other does not. The second one should be:
NUMBER :  [ 
{ confidence: 1, value: 2, type: 'value' },
{ confidence: 1, value: -12, type: 'value' } ]

If I change the input to  "2-4", it returns:
NUMBER :  [ 
{ confidence: 1, value: 2, type: 'value' },
{ confidence: 1, value: -4, type: 'value' } ]

It appears WIT cannot that if the numbers are of "mixed length", the "numbers" fail. 

One solution would be to offer a Wit/Intent or Wit/Expression a "Wit/Range".

**Comment by jroysdon** [comment]
On a whim, I also tried: Find me a game for **12** - **1** players

NUMBER :  [ 
{ confidence: 1, value: 12, type: 'value' },
 { confidence: 1, value: -1, type: 'value' } ]

So, this appears to work when the number lengths are reversed. I tested this with:
Find me a game for 10 - 20 players
and this works as well:
Find me a game for 10 - 200 players

The only time that fails is when the first digit has a length of 1 and the second number is 2 digits in length.

**Comment by patapizza** [comment]
Thanks for reporting @jroysdon.

**Comment by jroysdon** [comment]
While this still appears to be an issue, I have found two work arounds. 

The first is to "train" wit with number ranges, a LOT of them. This comes at a cost of training (feeding in a bunch of number ranges and validating them) AND seems to slow down the query some. 

The second is to make my own "entity" called "range". It seems to work well. Wit recognizes all the numbers on both sides and returns the object as a string. I can then split the string as a two numbers in my own code (and also process it when a single number is given).

**Comment by blandinw** [comment]
@jroysdon impressive workarounds, glad you unblocked yourself
If anyone comes across this again, please reopen this issue and comment, thanks!
