### ISSUE TITLE
wrong keyword match after adding expressions

### ISSUE THREAD

**Issue by g10** [wit-ai/wit#688]
—bug?

when initially importing keyword entities, they are correctly recognised in a message, but once (unrelated!) expressions are added, certain keywords are returned wrong (mainly values with spaces in it ?!)

e.g..

message | expected value | actual value (after expressions)
--|--|--
light-brown sugar | Brown sugar | White sugar
palm sugar | Palm sugar | White sugar
ground black pepper | Black pepper | Pepper
corn tortillas | Corn Tortilla | Tortilla
spring onions | Scallion * | Onion

_* note: certain values match on synonyms_

**Comment by patapizza** [comment]
Hi @g10,

What is your app id?

**Comment by g10** [comment]
hi, app-id `59774102-7fad-4d0b-aa14-d62f3c69d868` 
tnx for looking into this

**Comment by patapizza** [comment]
It looks like it's working now:

message | entities
--|--
light-brown sugar | `{"ingredients__fp":[{"metadata":"{ \"id\": 60 }","confidence":1,"value":"Brown sugar","type":"value"}`
palm sugar | `{"ingredients__fp":[{"metadata":"{ \"id\": 6273 }","confidence":0.97086681539558,"value":"Palm sugar","type":"value"}`
ground black pepper | `{"ingredients__fp":[{"metadata":"{ \"id\": 157 }","confidence":0.98733342547004,"value":"Black pepper (dried)","type":"value"}`
corn tortillas | `{"ingredients__fp":[{"metadata":"{ \"id\": 1147 }","confidence":0.94337512296419,"value":"Corn Tortilla","type":"value"}`
spring onions | `{"ingredients__fp":[{"metadata":"{ \"id\": 3784 }","confidence":0.97492160667001,"value":"Scallion","type":"value"}`
