### ISSUE TITLE
Wit ai automatically adding one more hour

### ISSUE THREAD

**Issue by samiotproject** [wit-ai/wit#689]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
report a bug
**What is the current behavior?**
it adds one more hour "to 2017. 8. 2. 오전 9:00:00"
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
"turn ac on from 7am to 8am" will produce datetime of 
from2017. 8. 2. 오전 7:00:00 to 2017. 8. 2. 오전 9:00:00
"turn ac on from 3am to 4am" will produce datetime of 
from 2017. 8. 2. 오전 3:00:00 to 2017. 8. 2. 오전 5:00:00
**What is the expected behavior?**
should be 8:00:00 and 4:00:00. 
**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by patapizza** [comment]
Hi @samiotproject,

As described in the [docs](https://wit.ai/docs/http/latest#response-format-link):

> For datetime entities that are interval, Duckling always returns an exclusive upper limit. So if you say “this weekend” the API will give you from Friday 18:00:00 to Monday 0:00:00. We may revisit this choice later. For now, there is a “grain” field that should help you infer the inclusive upper limit.
