### ISSUE TITLE
Entities highlighted incorrectly after editing input.

### ISSUE THREAD

**Issue by Talon876** [wit-ai/wit#69]
If you edit a phrase with a tagged entity, the highlighting of that entity becomes incorrect and won't refresh itself even after validating and coming back to it.

1. Go to Intents > Pick any intent

2. In the "How will your users express this intent? Type an example." textbox, enter an example of your intent.

3. Select your new phrase from the list.

4. Highlight something in the phrase and tag it as an entity.

5. Select the Cog icon > Edit

6. Reword the phrase so that the total number of character's is different.

7. Observe that the highlighting of the tagged entity is incorrect and won't refresh to the correct highlighting even after validating and refreshing the page.

**Comment by blandinw** [comment]
We fixed the tagging logic with the release of Bot Engine. Closing now. 😊
