### ISSUE TITLE
Only one entity being retrieved in a response

### ISSUE THREAD

**Issue by anugyaagarwal** [wit-ai/wit#690]
report a *bug*

Is there a way to get all entities that are registered for an expression? Presently only one entity is retrieved in response when call is made by 'https://api.wit.ai/message'.

**Comment by patapizza** [comment]
Hi @anugyaagarwal,

What is your app id? Can you provide an example of text with the expected entities and the actual entities returned?

Thanks.

**Comment by anugyaagarwal** [comment]
App id: 5975b109-0901-41c9-b3c5-7039adb1db18
Example:
text:  what is the use of crs pnr
Expected entities: target , intent, activity, platform
Actual entities returned: target

**Comment by patapizza** [comment]
In the validated examples for `target`, the whole sentences are tagged as `target` (and show up as synonyms). Can you try to clean the dataset by tagging only the right span, and by validating some examples that have all four entities correctly tagged?

Feel free to reopen if that doesn't work.

**Comment by anugyaagarwal** [comment]
Can we do the above task, the way you suggested, programmatically?

**Comment by l5t** [comment]
You should be able to do it with the /samples https://wit.ai/docs/http/20170307#post--samples-link 
and
/delete/entities/entity/expressions https://wit.ai/docs/http/20170307#delete--entities-:entity-id-values-:value-id-expressions-link

**Comment by anugyaagarwal** [comment]
Thanks @l5t . That did the job.
Could you please suggest how can we build a story or do what /converse did( both are deprecated) ?
Any alternate way ?

**Comment by l5t** [comment]
You can look at this: https://github.com/wit-ai/wit-stories-migration-tutorial
