### ISSUE TITLE
Newly created entiy not recognized

### ISSUE THREAD

**Issue by vladimirocorsi** [wit-ai/wit#691]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
Newly created entity "smalltalk" is not recognized, even by providing training data.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Submit the text "Good morning" to the machine text analysis service.

**What is the expected behavior?**
Entity should be recognized with value "goodMorning".

**What is the App ID where you are experiencing this issue (if applicable)?**
58c25d89-2d47-43e9-b348-99f330c9b5cd

**Comment by patapizza** [comment]
Hi @vladimirocorsi,

It looks like the three values for `smalltalk` are `goodMorning`, `goodbye` and `thankYou`. Have you tried using `wit/greetings`, `wit/bye` and `wit/thanks`?

**Comment by vladimirocorsi** [comment]
Hi @patapizza , this is of course good advice, thanks. But still I am worried about my entity not working at all.

**Comment by vladimirocorsi** [comment]
wit/greetings has serious issues: 11 am and similar are recognized as a greeting.

**Comment by patapizza** [comment]
Hi @vladimirocorsi,

It seems like you've validated a bunch of examples without any entities (including `smalltalk`), like `Good morning`, `Hello`, `Hey`, `Hi`, `Good day`, `What's up`, etc.
Can you try to revalidate those with the correct value of `smalltalk` and see if that helps?

Feel free to reopen if it doesn't help. Thanks!
