### ISSUE TITLE
Getting random replies from the bot when integrated with Facebook messenger

### ISSUE THREAD

**Issue by PN9** [wit-ai/wit#692]
We developed a bot and integrated with Facebook messenger. We are connecting to the SFDC backend through Node for getting the data. After a successful end to end flow, the bot is responding by giving random replies. we tried checking the same commands in wit.ai, we could see that the bot is responding properly in wit and not from Facebook messenger.
Please suggest on how to handle this scenario, if anyone has encountered it earlier.

Thanks!

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018.https://wit.ai/blog/2017/07/27/sunsetting-stories
