### ISSUE TITLE
put request is not working for entity?

### ISSUE THREAD

**Issue by kschouhan** [wit-ai/wit#693]
I am using wit entities api to put values in entity as per the given documentation:
https://api.wit.ai/entities/entitity_name?v=20170307
But its giving me bad request. - { error: 'Bad request', code: 'bad-request' }
Post request is working. Sometimes its giving wit the hell??

**Comment by l5t** [comment]
Can you share a curl request (without your access token) so that we can check?

**Comment by kschouhan** [comment]
curl --request PUT \
  --url 'https://api.wit.ai/entities/59302952-f225-47fc-9d9c-e27736785ba2?v=20170307' \
  --header ': ' \
  --header 'authorization: Bearer TOKEN' \
  --header 'content-type: application/json' \
  --data '{ "value": "faq.eye.makeup.not.coming.off",\n  "expressions": \n   [ "Why is my eye makeup not coming off?",\n     "Why is it so difficult to remove my eye makeup?",\n     "Why is it so hard to remove my eye makeup?",\n     "Why do I always have a problem taking off my eye makeup?",\n     "Why is it so difficult to take off my eye makeup?",\n     "Why is it so hard to take off my eye makeup?",\n     "I can\\'\''t remove my eye makeup." ],\n  "metadata": "faq.eye.makeup.not.coming.off" }'

**Comment by l5t** [comment]
Thanks, it seems that you're missing a key "values". See above example 
![image](https://user-images.githubusercontent.com/6992759/28965343-e8d28380-7910-11e7-9bc3-954e80d4010a.png)
