### ISSUE TITLE
Number incorrectly interpreted as date (German)

### ISSUE THREAD

**Issue by klemensz** [wit-ai/wit#694]
**Bug**

See screenshot - using a German as the language settings.

![bildschirmfoto 2017-08-05 um 12 40 30](https://user-images.githubusercontent.com/1116517/28994944-abe8db10-79db-11e7-9f29-a4bb6fa1a9ec.png)

The same works correctly in the English version: Direct translation is: "Next 5 games of FC Barcelona".

**What is the expected behavior?**
It should recognize 5 as a number, not a date.

**What is the App ID where you are experiencing this issue (if applicable)?**
5902737c-e922-4695-bed3-874f70abb502

**Comment by patapizza** [comment]
Thanks @klemensz, this is indeed a bug.

Wit.ai uses Duckling behind the scenes for `wit/datetime`.
Have you looked in to [Duckling](https://github.com/facebookincubator/duckling) to see if you can fix this issue?

**Comment by klemensz** [comment]
@hactar thanks for the pointer! ;) https://github.com/facebookincubator/duckling/blob/master/Duckling/Time/DE/Rules.hs#L1221

Notes in German: "triggered und sollte es nicht. Die rule müsste verfeinert werden so das “nächste 5” nicht triggered, aber z.b., “nächsten dienstag”, “nächste woche” aber schon."

**Comment by klemensz** [comment]
Another issue: "Ich bin so traurig" (I'm so sad) --> It thinks "so" is a Date (Sonntag - Sunday).
