### ISSUE TITLE
Feature request: add import/export to legacy apps

### ISSUE THREAD

**Issue by swapagarwal** [wit-ai/wit#695]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Ask a question.

**What is the current behavior?**
I don't see the fork button on app page. I have used it in the past. Has it been removed?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Not Applicable

**What is the expected behavior?**
A fork button on the app page should clone the app into the logged in user's account.

**What is the App ID where you are experiencing this issue (if applicable)?**
Not Applicable

**Comment by l5t** [comment]
Thanks for asking. We have replaced the fork feature by the import/export: https://wit.ai/docs/recipes#copyexportversion-my-app
We will be working on it soon to make it better/faster cc @stopachka

**Comment by swapagarwal** [comment]
I don't see the export button under settings.
Also, will the export button be visible to other users that might want to fork my app?

**Comment by l5t** [comment]
yes. Can you share your Wit app URL?

**Comment by swapagarwal** [comment]
https://wit.ai/swapagarwal/JARVIS-on-Messenger/

**Comment by l5t** [comment]
Indeed, this is because this is an app that was created before March 2016. We are currently working on it to bring in the import/export to these apps also. cc @stopachka
