### ISSUE TITLE
Number not detected in Russian even with exact phrase saved through website

### ISSUE THREAD

**Issue by suhinini** [wit-ai/wit#696]
Hi guys,

I'm posting a phrase "На обед было три банана" to wit.ai ("For lunch I had 3 bananas"), where "три" is "3". This very phrase was saved through the website on Understanding tab with "три" explicitly marked as wit/number. However, result keeps ignoring "три" and it only sees myself eating bananas without any explicit number.

Any idea why this might be happening?

Thanks

**Comment by suhinini** [comment]
Another case of this with "Два" (Two) not being detected.

**Comment by l5t** [comment]
Thanks for reaching out. wit/number is governed by our open sourced linguistic parser here: https://github.com/facebookincubator/duckling. Feel free to contribute to improve it.
Thanks

**Comment by suhinini** [comment]
@l5t checked out duckling, there is "два" in tests (see https://github.com/facebookincubator/duckling/blob/master/Duckling/Numeral/RU/Corpus.hs#L35) and tests pass:

```
      RU Tests
        Corpus Tests:          OK
```

However, when I try to parse "Два жареных яйца" with Wit - it doesn't work.

**Comment by blandinw** [comment]
@suhinini thank you for checking, it is much appreciated!
Could you open an issue in the Duckling repo about this?
Thanks!
