### ISSUE TITLE
How to get the old response structure

### ISSUE THREAD

**Issue by swapagarwal** [wit-ai/wit#697]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Ask a question.

**What is the current behavior?**
I have an old wit app, that returns response in the following format:
```
"outcomes":
{
    "intent":"" // identified intent
    "entities":
    {
        // entities extracted
    }
}
```
When I create a new app, it returns response in the following format:
```
"outcomes":
{
    "entities":
    {
        "intent":
        {
            // identified intent
        }
        "some_other_entity":
        {
            // entities extracted
        }
    }
}
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Not Applicable

**What is the expected behavior?**
Can I make the new app return the response in the old structure, say by providing an old version?

**What is the App ID where you are experiencing this issue (if applicable)?**
Not Applicable

**Comment by l5t** [comment]
Thanks for reaching out. Why would you want to get this structure? We are moving away from this format so this is very unlikely that we provide this capability.

**Comment by swapagarwal** [comment]
It's because I have an app in production which uses the old structure. Till when will this be supported? Can you point me to a resource that lists the changes for migration?

**Comment by blandinw** [comment]
@swapagarwal You can specify a version number when calling the API (passing a `v` query param). We do recommend that you update your code to the latest version though. See https://wit.ai/docs/http/20170307#versioning-link
