### ISSUE TITLE
[bug] take role into account in POST /samples

### ISSUE THREAD

**Issue by javimoya** [wit-ai/wit#699]
**Do you want to request a feature, report a bug, or ask a question about wit?**
Feature

**What is the current behavior?**
Currently POST samples API endpoint doesn't support creating samples where you specify a role in the entities.

**What is the expected behavior?**
A way to create entities with roles using POST /samples API endpoint

sample json:
`[{
      "text" : "donde está mi envío 69441 para el cp 69116",
      "entities" : [
        {
          "entity" : "intent",
          "value" : "\"info_paquete\""
        },
        {
          "entity" : "wit$number",
          "value" : "69441",
          "role" : "localizador",
          "start" : 20,
          "end" : 25
        },
        {
          "entity" : "wit$number",
          "value" : "69116",
          "role" : "cp",
          "start" : 37,
          "end" : 42
        }
      ]
    }]`

**Comment by l5t** [comment]
cc @stopachka

**Comment by hactar** [comment]
Is this currently not the case? I'd need this too...

**Comment by stopachka** [comment]
Hey team, I'll aim to have this added and ready by end of next week

**Comment by hactar** [comment]
I've just played around with the samples endpoint:

- [x] The sample endpoint accepts json samples that contain a role attribute.
- [x] The role attribute is added: If you go back to your app on the website, the roles are listed in the expressions.
- [ ] FIXME: When querying the /message endpoint, the results do not include the trained roles, nor is the role returned in the "understanding" tab

See app id 598a2aa4-ee8e-4379-ae42-8c551b19bb3a for example - I've uploaded a few thousand expressions with roles to this new app, however they are not returned from the /message api. Ask the message api "Wie komme ich am schnellsten nach Meidling" - the message endpoint does not include the role "to" for Meidling, nor does the understanding tab, but the "expressions" part of the "vienna_public_transport_station" does contain the correct role, as can be seen in the screen shot.

<img width="729" alt="wit_ai_-_newapp" src="https://user-images.githubusercontent.com/645674/29252743-19487e58-806d-11e7-862f-0847011a9f25.png">

**Comment by stopachka** [comment]
Thanks for the in-depth look @hactar! Will take a look and aim to pop in a fix by end of next week.

**Comment by recime-platform** [comment]
Well it seems other than intent nothing get persisted (i mean both built-in and custom entities (keywords) when submitting data in this endpoint.

**Comment by kazimanzurrashid** [comment]
At this moment other than intent nothing gets persisted, neither custom nor built-in.

**Comment by blandinw** [comment]
@kazimanzurrashid I saw your issue in https://github.com/wit-ai/wit-api-only-tutorial/issues/4, there may be an issue with your request. I need your app-id to debug this further.
What's your app-id?

**Comment by kazimanzurrashid** [comment]
@blandinw here is the app id 59948af7-5376-4eca-80fa-e3185037c1bb,
do let me know if you need anything more.

**Comment by blandinw** [comment]
@kazimanzurrashid We had a huge backlog of samples to process via POST /samples.
Your samples simply may not have been processed yet. We're slowly catching up, will update issue then

**Comment by kazimanzurrashid** [comment]
ok waiting.

**Comment by hactar** [comment]
Any update on this? I'm currently stuck as I can't supply my thousands of samples via /samples because of this bug, and I can't import them due to #513 . Or is there any other workaround anyone can think of?

**Comment by stopachka** [comment]
Thanks for the patience @hactar -- currently the sample queue is slowly draining. Goal is to have this fixed and shipped early to mid this week

**Comment by l5t** [comment]
The sample queue is empty now. So it should be better. We are also working on improving the process to prevent this in the future

**Comment by hactar** [comment]
Cannot confirm that this issue is solved. My app 5990bedd-4665-424b-9d57-0884919a419f still does not offer the trained roles via the /message endpoint or via "try out the sentence" feature, even though they are listed in the wit web-ui list of expressions. Just to be sure, I've created a fresh app (599d495a-4d45-45a0-be3b-625a32e86cca), and trained them with the same samples, and roles are not returned.

**Comment by stopachka** [comment]
hey @hactar,

I tried to repro this on a new app, but the roles worked in that case. Here's the curl I used:

```
curl -X POST \
  https://api.wit.ai/samples \
  -H 'authorization: Bearer $TOKEN' \
  -H 'content-type: application/json' \
  -d '[{
	"text": "hi there, i want a ferrari",
	"entities": [
		{
			"entity": "car",
			"value": "ferrari",
			"role": "end",
			"start": 19,
			"end": 26
		}
	]
}]'
```

Does your curl request look different? (may be a bug hiding somewhere there) 

Otherwise, this may be an issue with roles itself -- if possible, would be awesome to create a demo app, with just the problem entity and the first few expressions, to see when it starts to fail.

**Comment by stopachka** [comment]
Also, for subentities, indeed there was a bug were we were not processing them. Update has landed. 

```
curl -X POST \
  https://api.stopachka.sb.facebook.com:8443/samples \
  -H 'authorization: Bearer $TOKEN' \
  -H 'content-type: application/json' \
  -d '[{
	"text": "hi there, i want a red ferrari",
	"entities": [
		{
			"entity": "car",
			"value": "red ferrari",
			"role": "desired",
			"start": 19,
			"end": 30,
			"subentities": [{
				"entity": "color",
				"start": 0,
				"end": 3,
				"value": "color"
			}]
		}
	]
}]'
```

**Comment by hactar** [comment]
Here's my curl (have included the client access key cause the app is not in use until we find a fix):

`curl \
 -H 'Authorization: Bearer 7CSE2K2JY2PTQP7BSPL475QDDT7HFROB' \
 'https://api.wit.ai/message?verbose=true&v=20170823&q=wie%20komme%20ich%20um%2018%3A00%20vom%20Stephansplatz%20zum%20Schwedenplatz'`

And here is the response:
`{"msg_id":"0BvnP7caEHLKUO3sL","_text":"wie komme ich um 18:00 vom Stephansplatz zum Schwedenplatz","entities":{"special_location":[{"confidence":1,"value":"current location","type":"value","_entity":"special_location","_body":"ich","_start":10,"_end":13}],"datetime":[{"confidence":1,"value":"2017-07-08T18:00:00.000+02:00","type":"value","_entity":"datetime","_body":"um 18:00","_start":14,"_end":22}],"location":[{"confidence":1,"value":"Stephansplatz","type":"value","_entity":"location","_body":"Stephansplatz","_start":27,"_end":40}],"vienna_public_transport_station":[{"confidence":1,"value":"Schwedenplatz","type":"value","_entity":"vienna_public_transport_station","_body":"Schwedenplatz","_start":45,"_end":58}],"intent":[{"confidence":0.99999999804621,"value":"get_route","_entity":"intent"}]}}`

the datetime should have a role, Stephansplatz should have a role of from, Schwedenplatz should have a role of to.

I honestly wouldn't know where to start to create a smaller version of this demo, I can send you the import zip file version of what I'm trying to provide via the sample api if that is of any help if you provide me with your email.

**Comment by stopachka** [comment]
hey @hactar, sure thing!

my email is stopachka [at] fb.com

The curl I am curious about is the curl you use to send to POST /samples

**Comment by stopachka** [comment]
(closing this for now, will open a more specific issue when I get the email)

**Comment by hactar** [comment]
Thanks - just sent you the mail.
