### ISSUE TITLE
Publicize development roadmap?

### ISSUE THREAD

**Issue by aripatrick** [wit-ai/wit#70]
Seeing issues marked as "on-roadmap" is nice, but it'd be much nicer to see what the development team's priorities are. As my app is very NLP based, it would be beneficial to see what features/enhancements you all have planned for the more immediate future, as well as those that are a little further down the road, so I can plan around them. I'd love to be able to know, for instance, that an offline/embedded version of Wit will be available before I'll have the ability to exclude/selectively include intents through the API. Just my two cents. :)

**Comment by Glavin001** [comment]
+1! This would be great! I love where Wit.ai is going and being able to know where they are going helps me think of what I *can* do with my future apps so when Wit is ready I can start developing.

I've seen UserVoice around a lot. Here's what it looks like for GitLab: http://feedback.gitlab.com/forums/176466-general
UserVoice: https://www.uservoice.com/

**Comment by patapizza** [comment]
We've opened up our short-term roadmap about a week ago: https://github.com/wit-ai/wit
