### ISSUE TITLE
Could you please return the entities in an aray instead of unique objects below entities? (GET /Message)

### ISSUE THREAD

**Issue by MxSinan** [wit-ai/wit#701]
Hi guys

I don't get when returning the JSON at GetMessage that you include the entities below "entities" as objects and not returning in an array of objects? Those are technically not unique objects, all are an WIT.ai entity with same 3 fields in it...

by returning the entities in an array, I can include them as an General Wit.AI entity instead of creating 74 different entities which I am using just for the name.

would be much appreciated, if possible.

**Comment by patapizza** [comment]
Hi @MxSinan,

The rationale behind returning an object is that it's easier to look into specific entities without traversing the array of all entities.
You can still convert the response into an array by traversing the (key, value) pairs and ignore the keys. Have you tried that?

Feel free to reopen if this doesn't help.
