### ISSUE TITLE
Feature request: change Built-in NLP behavior when text greater than 256 characters

### ISSUE THREAD

**Issue by vdisawar** [wit-ai/wit#702]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
This is a bug

**What is the current behavior?**
If built-in NLP is enabled, and user enters text larger than 256 characters, the JSON returned is an error that the message is larger than 256 characters. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Turn on built-in NLP for a page and send text larger than 256 characters.

**What is the expected behavior?**
The text should be truncated to 256 characters or less to get the NLP on what the user said.

**Comment by stopachka** [comment]
This is a great point @vdisawar 

If this happens, would you find it useful to receive something in the response, telling you that built-in nlp truncated the request?

**Comment by blandinw** [comment]
Thanks @vdisawar, that's great feedback.
We'll keep track internally and provide a better solution in a future release.

**Comment by vdisawar** [comment]
How do you propose we should handle this issue while this is being worked on internally? 

My thoughts are to detect the length and truncate and make the call to /message again

**Comment by stopachka** [comment]
@vdisawar that should work as well. If you have thoughts on how you would like built-in-nlp to behave in this scenario, there much appreciated!

i.e -- would you want the request to tell you that the text was trimmed?

**Comment by vdisawar** [comment]
sure! that would be helpful

**Comment by jmderueda** [comment]
@stopachka i have the same issue here. @vdisawar I think solution depends if you have independent sentences or not.

Ie in my case i am using speech recognition so I do not have dots in long conversations, in that case, if I truncate randomly (or by 256 chars) i can break the logic of the sentence. I was thinking about summarizing the text and then passing them in chunks. Do you have any thoughs on this? BTW great tool and congrats on the fb acquisition!

**Comment by stopachka** [comment]
Hm, interesting idea for dividing by commas! 

As a note, do you see your responses get highly long? i.e what if we made the max length 1000?

**Comment by jmderueda** [comment]
in theory it should be sufficient https://strainindex.wordpress.com/2008/07/28/the-average-sentence-length/ if sentence is correctly bounded

My problem is that we are getting 5~15 minutes conversations as our speech to text layer input, that means long texts without dots or commas as an output for wit.ai

What about implementing a 'pause detector' from endpoint /speech? Maybe we can share knowledge :)

**Comment by stopachka** [comment]
Good ideas all! 

For Built-In NLP I think if we increase the length seems like that would do the best

For POST /speech -- indeed, a pause detector, or maybe a division of the api into transcription + NLP could help.

**Comment by jmderueda** [comment]
"a division of the api into transcription + NLP could help" this would be
great and quick to implement.

ᐧ

**Comment by arvalaan** [comment]
@stopachka What's the ETA on the character amount increase? We're running into this analysing feedback messages.

**Comment by stopachka** [comment]
@arvalaan increased the limit to 1000 for apps going through built-in-nlp path! Let us know if you still see issues.
