### ISSUE TITLE
Reopen: Number not detected in Russian even with exact phrase saved through website

### ISSUE THREAD

**Issue by suhinini** [wit-ai/wit#704]
Hi guys,

Didn't find a way to reopen an issue, hence the new one.

I'm posting a phrase "На обед было три банана" to wit.ai ("For lunch I had 3 bananas"), where "три" is "3". This very phrase was saved through the website on Understanding tab with "три" explicitly marked as wit/number. However, result keeps ignoring "три" and it only sees myself eating bananas without any explicit number.

**Duckling has "три" in there and tests pass so library does understand it, so it seems to be a problem at Wit.ai end.**

Any idea why this might be happening? E.g. I'm training recognition of my entities and I show every single time that numbers are important as I need every number said by user. Then I add a specific phrase through Understanding tab and I expect same numbers I've marked to pop up when getting meaning through the API. They do not.

Thanks a lot

**Comment by patapizza** [comment]
Hi @suhinini,

I could not repro. What is your app id?

![screenshot](http://i.imgur.com/22jCdzh.png)

**Comment by suhinini** [comment]
Hi @patapizza 

App id is 59874010-3514-44a4-ab26-31b305088e64

**Comment by patapizza** [comment]
It looks like `wit/number` is correctly detected, but in this example, it's being swallowed by `foodRecord`. `wit/number` should still show up under `foodRecord` though.

**Comment by suhinini** [comment]
That would be all I wish for :D It does in some times, it doesn't in others. Is there a way to define a structure for `foodRecord`? E.g. "always detect numbers within the record" or something like that?

On the other hand, maybe I just have too few examples and it will get better with more data?

**Comment by patapizza** [comment]
It looks like composite entities is the right tool for the job.

If `foodRecord` doesn't need to capture things like `6 bananas`, but rather things like `3 cups of sugar`, I would say to use `wit/quantity`.

**Comment by suhinini** [comment]
@patapizza I wish I could but input will be very fast so "6 bananas" is more likely than "3 cups of sugar".

I do have my own detection of numerics to fix `foodRecords` when they come from wit.ai but one day it would be great to set a stricter scheme for custom entities. E.g. "each `foodRecord` will always have a `food`, might have a `number`", etc.

Thanks for checking this case anyway.

**Comment by patapizza** [comment]
@suhinini It looks like it's working now:

![screenshot](http://i.imgur.com/RWCs5Yu.png)

Feel free to reopen if you still experience issues.

**Comment by suhinini** [comment]
Thank you!

**Comment by suhinini** [comment]
It stopped working with actual numbers present in input. Wit has exact examples saved but still ignores wit/number present in input text. Why can't anyone rely at at least explicitly specified input structure?

**Comment by patapizza** [comment]
Hi @suhinini,

Can you share a few examples along with what is expected? That would be helpful.
When did it stop working?

Thanks.

**Comment by suhinini** [comment]
@patapizza it stopped detecting numbers roughly when I added the first trait to the system (I've been only using keywords and free-text before). I fed around 6-8 examples teaching the system to identify numbers again and it's all working now. Funny thing, the same examples it knew before.

I have a set of tests (around 50) I'm using to check if it's still working and any time I add something new - something breaks. I feed more examples and it gets back to normal, but in some cases like this one it's really frustrating. Like, hey, I did teach you to recognize numbers, almost any input I feed to you has numbers, why would you suddenly stop identifying those?

Thanks

**Comment by patapizza** [comment]
@suhinini Glad it's working now. If you experience any more issues please share the examples that don't work.
