### ISSUE TITLE
Importing with large number of expressions fails

### ISSUE THREAD

**Issue by 5amuraix** [wit-ai/wit#705]
Hello,

**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
I'd like to report a bug.

**What is the current behavior?**
We are importing data from another NLP service and have converted it to match Wit.ai's format.
We are treating "utterances" and their registered intents from our previous dataset as expressions with coupled with their respective intent entity and appropriate value (as matched from the previous data).

When I try to create a new project by importing a zip file that includes 1,271 expressions in the expressions.json file, the page displays "We are creating your instance. Please do not refresh" and after a while, the dialog disappears and no app is created.

Lowering the amount of expressions to around 286 gives a successful result and the project gets created after a couple of minutes.  Please note we did not do thorough testing of this final amount.  We started with 1271, reduced roughly half and tried again (with failure), and reduced by about half again  to get to 286.  So the "sweet spot" could be somewhere >286 and <512

Is there a limit to the number of expressions that can be imported?  Is this behaving as intended?
Can you provide any recommendations?

Thank you!

**Comment by blandinw** [comment]
Is everything ok now?

**Comment by hactar** [comment]
Assuming this is a duplicate of #513 , then yes, it still persists. Imports time out after 3 minutes if they have too many expressions, with an error of "Failed to load resource: the server responded with a status of 504 (Server timeout)"

**Comment by 5amuraix** [comment]
Hi, this issue I reported is a subset of the issue hactar had posted. 

I found a workaround by importing my app with a blank expressions.json file and then adding the expressions one by one using the wit HTTP API (https://wit.ai/docs/http/20170307#post--entities-:entity-id-values-:value-id-expressions-link)  with a script I wrote.

**Comment by hactar** [comment]
Yup, the workaround works, as long as you don't use roles, which are bugged in samples, as reported in #699
