### ISSUE TITLE
Bad auth, check token/params on /converse

### ISSUE THREAD

**Issue by abhilashmurthy** [wit-ai/wit#708]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
A lot of calls return 'invalid json response body' on /converse for some reason. Affecting 200+ users in the past 3 hours.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Send anything to `/converse`, it will throw this error
`Bad auth, check token/params`

**What is the expected behavior?**
No error

**What is the App ID where you are experiencing this issue (if applicable)?**
58023ff9-8490-41fe-816b-0f18f418092a

**Comment by sindre** [comment]
Same problem here.

**Comment by blandinw** [comment]
Looking

**Comment by blandinw** [comment]
@abhilashmurthy your app works fine on my end. Can you post an example cURL that reproduces the issue (**without your access token**)?

**Comment by abhilashmurthy** [comment]
@blandinw last known occurrence was about 2 hours ago:
`https://api.wit.ai/converse?session_id=1550462234996740&q=Thanks`

BUT, I took this as a firefighting opportunity to replace my `/converse` endpoint with the `/message` endpoint following the deprecation notice. No more issues, all under control now 😄

**Comment by blandinw** [comment]
duplicates #698
