### ISSUE TITLE
dropdown boxes with userdefined values are suddenly empty

### ISSUE THREAD

**Issue by Tessgyldendal** [wit-ai/wit#709]
Reporting a bug in the Understand interface
current behavior: When I want to change the values of my user defined entities, the drop down is empty.
I can see the values are still there, just not shown in the drowpdown.
<img width="957" alt="screen shot 2017-08-10 at 10 44 56" src="https://user-images.githubusercontent.com/30626770/29164629-62964004-7dc0-11e7-8898-1788a05d66df.png">

1. write question
2. add intent entity with previously defined values
3. press the values field (drowdown box) - it will open without values, and without the possibility to create new ones.

expected behavior: dropdown should include my values, so they are selectable.

app id:  59885301-8aa8-4242-9045-d03732a96ad5

**Comment by makstaks** [comment]
I am experiencing the same issue and I would like to also add that I cannot create a new intent and validate.

**Comment by hweiler** [comment]
I experienced the same issue earlier today. None of my user-defined intents are appearing when I search for the value in the dropdown.

**Comment by adilnaut** [comment]
The same issue. I can't validate through both inbox and understanding pages.

**Comment by blandinw** [comment]
We published a first fix to mitigate validation, second fix should be coming soon (cf. #712).
The blank dropdowns should be fixed soon as well. We do apologize for the inconvenience.
I'll close this issue when the dropdown does not appear empty anymore.

**Comment by blandinw** [comment]
The CSS glitch has been fixed.
