### ISSUE TITLE
Renaming intents is confusing

### ISSUE THREAD

**Issue by Talon876** [wit-ai/wit#71]
Renaming entities is nice because there's a big blue button that says "Rename this entity".

I wasn't even sure renaming an intent was possible until I noticed its name was in a large text box and chrome was letting me resize it.

Having a similar "Rename this intent" button would be nice to have.

**Comment by stopachka** [comment]
hey @all, apologies for the late response on this. we've updated the ux on entities / show. If you still have issues, please feel free to reopen
