### ISSUE TITLE
Create new Application HTTP API timeout

### ISSUE THREAD

**Issue by Boyko-Karadzhov** [wit-ai/wit#711]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
[HTTP requests to create an application fail](https://wit.ai/docs/http/20170307#post--apps-link) with 408 Request Timeout (response text: "Server timeout").

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Request to create a new application via the HTTP API: [HTTP requests to create an application fail](https://wit.ai/docs/http/20170307#post--apps-link) 
Here is a sample payload:
```json
{
    "name":"BoykoCreateTest",
    "lang":"en",
    "private":"true"
}
```

**What is the expected behavior?**
An app should be created and the response to the request should be with status 200.

**What is the App ID where you are experiencing this issue (if applicable)?**
N/A

**Comment by blandinw** [comment]
@Boyko-Karadzhov thank you for your feedback, this is much appreciated.
The POST /apps call seems to be working fine on my end, is it now working for you too?
Do you have a rough idea of when the call started misbehaving?

**Comment by Boyko-Karadzhov** [comment]
@blandinw I can confirm that the service is working for me now.

The first failure I got was at about 11:05 UTC (10th Aug) and I have been checking it periodically until 16:00 UTC (10th Aug). It was failing consistently. I did not check it again until now and now it is working.

Thanks!
