### ISSUE TITLE
I just created a new project and I don't see the "stories" feature like I did in my first test? How does it get turned on?

### ISSUE THREAD

**Issue by naelshawwa** [wit-ai/wit#713]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by blandinw** [comment]
Stories has been deprecated, see https://wit.ai/blog/2017/07/27/sunsetting-stories
