### ISSUE TITLE
Wit the Hell is wrong with Converse API

### ISSUE THREAD

**Issue by nixxholas** [wit-ai/wit#714]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
**Bug**

**What is the current behavior?**
We noticed the date formatting changed, but to no avail. Converse does not work.
<img width="1065" alt="screen shot 2017-08-11 at 12 44 33 pm" src="https://user-images.githubusercontent.com/4703269/29201664-d6ff8f0e-7e92-11e7-8ca4-322d32ac7cf2.png">

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Simply send an API call to Converse.

**What is the expected behavior?**
As shown in the screenshot above.

**What is the App ID where you are experiencing this issue (if applicable)?**
58be72f1-25c4-4fe8-ad93-7f98c5194039

**Comment by nixxholas** [comment]
Made a mistake.

**Comment by blandinw** [comment]
hi @nixxholas, can you tell us what mistake you made so that the next person can find this issue and fix their issue as well? It may also be an opportunity to make Wit better.

**Comment by nixxholas** [comment]
Be sure to encode the string before you send it to Wit.
