### ISSUE TITLE
POST /speech, HTTP 400 when resulting text is too long or empty

### ISSUE THREAD

**Issue by Syesy** [wit-ai/wit#715]
Hi, yesterday I encountered the following problem:
I make this request to wit API
`curl -v -XPOST 'https://api.wit.ai/speech' \
   -i -L \
   -H "Authorization: Bearer MY_TOKEN" \
   -H "Content-Type: audio/mpeg3" \
   --data-binary "@tr.mp3"`
and i get the HTTP error 400 `{
  "error" : "Bad request",
  "code" : "bad-request"
}` response. 

Since everything worked before yesterday I can't figure out what's going on. Maybes someone can help me? Thank you in advance!

**Comment by blandinw** [comment]
Please follow the issue template when posting a new issue.
What is your app-id? Are you still experiencing the issue now?

**Comment by Syesy** [comment]
Hi, I apologize for the wrong form of my issue, this is my app-id: 597f5184-1b7a-4871-aa16-b1dbc839df28 and yes, I'm currently experiencing the issue. It only seems to happen when I send audios that are greater than a certain length (I think 15sec). Do you have some limitation? 
Thank you again

**Comment by blandinw** [comment]
@Syesy we have a limitation on the size of the text, indeed. It is limited at 255 characters. You obviously don't know the size of the text when you send the audio file, so I understand of this can be confusing. Let me think about how we can make it better for you.

**Comment by Syesy** [comment]
Thanks for your explanation, now I understand. I will keep me up to date on Wit changes in case something will change about this feature. Thank you again @blandinw

**Comment by pnmartinez** [comment]
Hi @blandinw ,

I'm having the same problem.

Is this 255 character limitation something recently added? If so, could you please refer me to somewhere I can double-check that?

Thanks in advance!!

**Comment by backmeupplz** [comment]
Hey everybody, having exactly the same issue here. Why did you add this new limit without letting anyone know? Yep, docs still don't mention the limit: https://wit.ai/docs/http/20160526#post--speech-link.

I hope it's a bug, not a feature. Tens of thousands of my non-commercial startup users depend on wit.ai voice recognition working properly. I hope they get it back to just a 50-second limit.

**Comment by stopachka** [comment]
Thanks for the ping @backmeupplz -- this bug was introduced in a migration to more scaled infra.

We're looking into a full fix now, we definitely want to make sure you and your clients are well served. We're actively thinking about this, and will update here with a solution asap

**Comment by backmeupplz** [comment]
@stopachka thank you a lot! Wit.ai is the best and you prove this high status 🥇

**Comment by stopachka** [comment]
update: bugfix is ready, we will aim to have this in prod by mid next week

**Comment by pnmartinez** [comment]
@stopachka , may I ask that you post here a warning when it's implemented?

Thanks in advance.

**Comment by stopachka** [comment]
Hey @pnmartinez -- for sure, and I wanted to note that this actually has been implemented and is in production
