### ISSUE TITLE
Wit.ai app broken, all expresssions are missing...

### ISSUE THREAD

**Issue by misysdclabs** [wit-ai/wit#716]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
BUG
**What is the current behavior?**
I have a wit.ai app, just become broken. When I look into the app I see all my expressions are just disappeared... maybe that cause to fail to understand anything.

Here is my app:
https://wit.ai/misysdclabs/Prototype%20-%20Personal%20Financial%20Assistant

@l5t can you please help me? Can you put back my expressions?

Thanks!

Best,
Krisztián

**Comment by blandinw** [comment]
@misysdclabs thank you for your feedback.
Looking at your app, I still see expressions in your app.
Can you be a little more specific? Which entity is missing expressions?
Please provide precise steps to reproduce the issue.

**Comment by misysdclabs** [comment]
@blandinw thanks, now everything is all right! Got back the expressions and the app works like a charm. Maybe there was some temporary problem? I saw all in my intents that the expression list is empty...

Anyway, thanks again, I close this issue.

Best,
Krisztián
