### ISSUE TITLE
Feature request: Add historic lines to Insights

### ISSUE THREAD

**Issue by magnusburton** [wit-ai/wit#718]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
*Feature request*

**What is the expected behavior?**
A button to toggle on and off historic lines representing the precision and recall lines on previous update or similar. This way it'd be easier for us to detect the impact our training has on the scores.

**Comment by patapizza** [comment]
Indeed @magnusburton, this is something we'd like to provide in the future (no current plans yet).

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
