### ISSUE TITLE
Stuck in training

### ISSUE THREAD

**Issue by gkf01** [wit-ai/wit#719]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
stuck in training
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**
58763ed1-bbcf-44a6-a44d-5607869e8f54

app url: https://wit.ai/ghassanfakher/rasawit

**Comment by l5t** [comment]
Just restarted. Should be better now

**Comment by blandinw** [comment]
How long did you wait? Your app looked fine from my end.
Training can take more than a minute depending on the current load on the system.

**Comment by gkf01** [comment]
I waited 3 or 4 days. However, once the training was restarted, everything came back to normal. Thank you for your help.
