### ISSUE TITLE
Retrieve logged in facebook user's first and last name using wit.ai and Node.js

### ISSUE THREAD

**Issue by PN9** [wit-ai/wit#720]
How can we retrieve logged in facebook user's first and last name using wit.ai and Node.js?

**Comment by blandinw** [comment]
Wit.ai has no concept of FB user. You'll need to use the features provided by whatever platform you're using. If you're using FB Messenger, you may want to ask in the official Messenger community group (https://www.facebook.com/groups/messengerplatform/).
