### ISSUE TITLE
400 (Bad Request) on streaming .raw file

### ISSUE THREAD

**Issue by Krogsager** [wit-ai/wit#721]
Bug:
When I attempt to stream a raw file i get an error:
Traceback (most recent call last):
  File "witStreamTest.py", line 80, in <module>
    wst.procurement()
  File "witStreamTest.py", line 60, in procurement
    resp = client.speech(gen, None, {'Content-Type': 'audio/raw;encoding=floating-point;bits=32;rate=16000;endian=little', 'Transfer-encoding': 'chunked'})
  File "/home/nao/.local/lib/python2.7/site-packages/wit/wit.py", line 92, in speech
    data=audio_file, headers=headers)
  File "/home/nao/.local/lib/python2.7/site-packages/wit/wit.py", line 34, in req
    ' (' + rsp.reason + ')')
**wit.wit.WitError: Wit responded with status: 400 (Bad Request)**

Demo: Python 2.7:
client.speech(gen, None, {'Content-Type': 'audio/raw;encoding=floating-point;bits=32;rate=16000;endian=little', 'Transfer-encoding': 'chunked'})

Expected: I expect to get a response with a transscript. Previous tests with .wav files work fine.

AppID:
595f485e-00ab-40cb-a114-87648bb35fd0

**Comment by blandinw** [comment]
Most likely duplicates #715

**Comment by Krogsager** [comment]
Not quite, because I send just empty noise, so I shouldn't be generating any characters at all. The duration is below 10 seconds.

**Comment by Krogsager** [comment]
Hi blandinw, can you please reopen this issue? I have tested the request again and can tell that it does not relate to issue #715.
With a file that I know is working, the issue seems to be with the line
`client.speech(gen, None, {'Content-Type': 'audio/raw;encoding=floating-point;bits=32;rate=16000;endian=little', 'Transfer-encoding': 'chunked'})`

**Comment by blandinw** [comment]
@Krogsager An empty text (just a noise audio clip) is also related to #715, I'll update the issue to reflect that.

Are you saying the audio file you're using should have a length between 1 and 255 chars and is still returning a 400? If so, could you please comment with steps to reproduce the issue? Audio file would help too. If you're uncomfortable posting it here, you can send it by email at my first name @fb.com

**Comment by Krogsager** [comment]
I'm uploading my code and raw audio to a zip. If you want to verify the file you can import it into Audacity with the settings shown in the screenshot.  
The raw file should translate into Danish; "skru op for lyden"
[New folder.zip](https://github.com/wit-ai/wit/files/1234572/New.folder.zip)

**Comment by stopachka** [comment]
Thanks @Krogsager, we'll take a look and update here after the investigation

**Comment by Krogsager** [comment]
Hi guys, any news in this case?

**Comment by patapizza** [comment]
Thanks for pinging in @Krogsager. We're on a fix that should come up soon.

**Comment by sylmanu** [comment]
I think this has to deal with the size of the chunks streamed to tto the speech API! I tried to increase it from 1024 to 20480 and was able to get results! But there is still huge latency, same as if I was just sending wav file so I don't really know what's going on there...

**Comment by stopachka** [comment]
Interesting! cc @Krogsager does changing the chunk size solve the problem for you?

re: long response times, You're @sylmanu -- we're looking into this, there has been a regression in our latency for speech.
