### ISSUE TITLE
Cannot validate audio in Inbox

### ISSUE THREAD

**Issue by cyebrtanott** [wit-ai/wit#722]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question

**What is the current behavior?**

Recently, after sending the audio streaming data to my app, I cannot listen the audio in the Logs page and there is no any data in the "validate audio" of Inbox, this issue has been lasting for few days.

I have tried to create 3 different app to test, but it looks the same.

**What is the expected behavior?**

Can listen and validate audio in the app page.

**What is the App ID where you are experiencing this issue (if applicable)?**
59926013-a730-4b58-bab0-390ae078d468
599256a2-13fd-4cd8-a8c3-9aa08b2f9429
598179ba-f837-452d-afeb-0a2bf0284c0c

**Comment by blandinw** [comment]
@cyebrtanott Thanks for your feedback, this is known issue and one we'll fix soon

**Comment by cyebrtanott** [comment]
@blandinw Thanks for your reply, but this issue looks still the same today.

**Comment by stopachka** [comment]
Thanks for pinging in @cyebrtanott, we'll aim to take a look by end of week

**Comment by cyebrtanott** [comment]
There is another error today:

08-30 06:38:09.751 19760 22147 D Wit     : Done sending data
08-30 06:38:10.438 19760 19760 D Wit     : Wit : Response {
08-30 06:38:10.438 19760 19760 D Wit     :   "error" : "Something went wrong. We've been notified.",
08-30 06:38:10.438 19760 19760 D Wit     :   "code" : "wit"
08-30 06:38:10.438 19760 19760 D Wit     : }
08-30 06:38:10.447 19760 19760 D Wit     : Gson : Response {}

**Comment by sylmanu** [comment]
@cyebrtanott , is this issue solved on your side?

**Comment by Krogsager** [comment]
This is starting to get critical on my end. Voice clips are never shown, so I can't train the voice recognition. 
![image](https://user-images.githubusercontent.com/27994384/30212785-b976dd28-94a6-11e7-8e8a-d31e108a7176.png)

**Comment by sharma-ji** [comment]
The same goes for me. I can't see voice clips and even in the logs I can't see the recently transcribed words. It shows the words from history with the time stamp of recent.

**Comment by stopachka** [comment]
Thanks for the in-depth user-reports. Looking into this now, will update eod

**Comment by Splitter** [comment]
Any word when/if this will be fixed?

**Comment by Krogsager** [comment]
Is it possible that someone is training the transation wrong, as a joke. Some responses to common words are translated into pop culture references.

**Comment by stopachka** [comment]
@Splitter -- the fix is in, we should be deploying within the next day or so!

@Krogsager -- Usually not, if you could open a new task, with some examples of the errors you are coming across, we can look deeper

**Comment by Krogsager** [comment]
@stopachka 
I'm still not seeing any audio in the inbox
App id 59a94f2d-f77a-4644-bbda-0812536a0942

**Comment by stopachka** [comment]
Thanks @Krogsager -- I'll update you asap as soon as this is fully landed

**Comment by stopachka** [comment]
Aand it's back! Let us know if you are not seeing voice audio still

**Comment by sharma-ji** [comment]
Nope, its still not working for me

**Comment by stopachka** [comment]
@sharma-ji Happy to take a look! 

--- 

What

**Comment by sharma-ji** [comment]
@stopachka I am clicking on the Train some more button but I don't get anything. Also in the logs options I can't see the icon to listen to the transcribed words, as it was seen earlier..

**Comment by stopachka** [comment]
Understood. Did you send an audio sample after Sep 21? 

If yes, please let me know your app-id, and I can go debug

**Comment by l5t** [comment]
Closing. Please reopen with app-id if you still experience the issue

**Comment by theflyingmantis** [comment]
Facing same issue. 
App ID: 5a18713b-2edf-4c5c-8f82-5780b468e0fe

**Comment by patapizza** [comment]
@theflyingmantis Just sent an audio request to your app and saw it in the voice inbox:

<img width="319" alt="screen shot 2018-04-13 at 6 05 41 pm" src="https://user-images.githubusercontent.com/1015208/38762811-5adf42b0-3f45-11e8-95cd-b2ed37fb4456.png">

Note that if the transcript recognized from your audio sample is already present in your app, it won't show up.

**Comment by matgott** [comment]
This is happening to me right now. I send an audio from Messenger but in "Validate Audio" never appears.

App id: 5aff1a4a-2b35-4ce0-a092-29315d06cbe9

**Comment by redoyh7** [comment]
I'm still not seeing any audio in the inbox! Please Help.

**Comment by patapizza** [comment]
@redoyh7 Please open up a new issue, using the provided template.
