### ISSUE TITLE
Cannot enable built-in entity through API

### ISSUE THREAD

**Issue by Boyko-Karadzhov** [wit-ai/wit#723]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
I have been using the [`samples`](https://wit.ai/docs/http/20170307#post--samples-link) endpoint to add `wit$datetime` to my projects. Today this has no effect.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Create a new application in english.
1. Add a sample with datetime through the API:
```bash
curl --request POST \
  --url 'https://api.wit.ai/samples?v=20170307' \
  --header 'accept: application/json' \
  --header 'authorization: Bearer {{my token}}' \
  --header 'cache-control: no-cache' \
  --header 'content-type: application/json' \
  --data '[\r\n    {\r\n        "text": "tomorrow",\r\n        "entities": [\r\n            {\r\n                "entity": "wit$datetime",\r\n                "value": "tomorrow",\r\n                "start": 0,\r\n                "end": 8\r\n            }\r\n        ]\r\n    }\r\n]'
```

Result: The service responds with status 200 OK and response text:
```json
{
    "sent": true,
    "n": 1
}
```
but datetime entities are not recognized and the entity type is not visible in the UI.

**What is the expected behavior?**
It is expected that datetime will appear in the list of entities for the application and datetime will be extracted from messages.

**What is the App ID where you are experiencing this issue (if applicable)?**
5992f330-5eb1-4b7e-9d69-4e296fd65f4c

**Comment by blandinw** [comment]
We had a huge backlog of samples to process via POST /samples.
Your samples simply may not have been processed yet. We're slowly catching up, will update issue then.

**Comment by blandinw** [comment]
The backlog has been processed, you should be able to add builtins to your app using POST /samples. Please feel free to comment or reopen this issue if things are not working as expected!
