### ISSUE TITLE
/converse timeout then blocked

### ISSUE THREAD

**Issue by Ottunger** [wit-ai/wit#724]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug

**What is the current behavior?**
When I use node-wit to converse with wit.ai, the first request goes through well, the second times out and the following ones return something which starts with 'S' (breaks JSON.parse) 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
When I use node-wit to converse with wit.ai, the first request goes through well, the second times out and the following ones return something which starts with 'S' (breaks JSON.parse) 

**What is the expected behavior?**
All /converse calls should work without error. Actually this seems like a regression to me.
I have reported it on node-wit as well but I think this is server side: https://github.com/wit-ai/node-wit/issues/154

**What is the App ID where you are experiencing this issue (if applicable)?**
59267786-1817-4567-b6ed-cd20c71367af

**Comment by blandinw** [comment]
linked to #698

**Comment by l5t** [comment]
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories
