### ISSUE TITLE
[wit] add verbose=true to documentation

### ISSUE THREAD

**Issue by traa** [wit-ai/wit#725]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question/bug

**What is the current behavior?**
Requests from command line returns reponse in this format:
```
...
entities: {
  "flowers": [
    {
      "confidence":0.9571594794871,
      "value":"Closures",
      "type":"value"
    },
 }]
}
```

However, if i'm looking into "Logs" tab, i'm seeing under the "Outcomes" section:
```
...
entities: {
 "flowers": [{
  "confidence": 0.9571594794871
  "start": 55
  "end": 63
  "body": "rose"
  "value": {
      "value": "rose"
  }
  "entity": "rose"
  }]
}
```

I'm quite interested in getting `start` and `end` props in response.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Do a request using cURL, get the result (first data), then check "Logs" tab on wit.ai

**What is the expected behavior?**
`start` and `end` props are present in response

**What is the App ID where you are experiencing this issue (if applicable)?**
5996d50d-386f-47e9-bcb0-3c21980b5a1e

**Comment by hactar** [comment]
try adding verbose=true to your query: https://api.wit.ai/message?q=hello&verbose=true

**Comment by traa** [comment]
awesome!
Thanks for that!
Is this somewhere in the docs? I haven't found this

**Comment by hactar** [comment]
Nope. The wit team said they'll add it to the documentation a while back. But we all know how we all love to do documentation. Coding ist just so much more fun... :D

**Comment by stopachka** [comment]
Great point team, and thanks for pinging in @hactar -- will prioritize this.

**Comment by stopachka** [comment]
added! https://wit.ai/docs/http/20170307#get--message-link
