### ISSUE TITLE
Feature Request: Bring back Contexts

### ISSUE THREAD

**Issue by jojoman2** [wit-ai/wit#726]
The possibility to add contexts was previously removed when the "Converse" feature was added. Now when "Converse" has been removed again it there is no way to include any type of context at all. This makes it hard to create a bot which could have a conversation of more than one exchange. For that reason, it would be great if you could bring back the possibility to add contexts that was included before.

**Comment by stopachka** [comment]
Hey @jojoman2 

Could you give me an example, of where the lack of context on wit's side blocked you?

Want to get a good understanding of how you would like to use it

**Comment by jojoman2** [comment]
I am making a bot for playing radio/podcast content. A few examples

- If the user mentioned a radio show but not what to play from it, he or she could be asked what to play from the program. At that point the user might say "latest" or "random". However,  saying any of those things without the context of a program would not make sense.

- If the user has asked for a random episode, he or  she might say "again" to play another. That would also not make sense without that context.

- If a user previously wanted to play an episode from a program, he or she might say "No, play blahblah episode instead"

Of course it is possible to teach wit to understand these expressions otherwise but there would always be a risk that they would be recognized out of their contexts.

**Comment by stopachka** [comment]
Hey @jojoman2 

For the above cases, this may be better managed in the code itself. i.e, you keep a context object, and based on what is filled, and the entities you have, you take next steps. The context in this case is highly coupled with business logic. i.e you could have the users previous preferences in the db, and would want to use that.

Passing the context to wit would be good for wit itself, to make it so certain entities are only detected during certain states. However, this is only good if there are so many entities, that wit is having trouble detecting what you want. 

Have you noticed the above to the case?

**Comment by sauronnikko** [comment]
Hi @stopachka. In the [wit.ai documentation](https://wit.ai/docs/http/20170307#context-link) there are still mentions of context. I'm confused reading this issue, because what I'm inferring from your comments is that context is currently not supported. Are they still supported? If yes, will they be deprecated?

**Comment by patapizza** [comment]
The context one can provide to /message is different than the one used in /converse.
In /message, a reference time and/or a timezone can be provided to resolve the `wit/datetime` entity differently than the app defaults (e.g. using the user timezone). For apps before Stories, a state can be provided as well (requires a setup in the console).

In /converse, a different context (a map) was required to feed in the dialogue engine. This part can be emulated in the client as @stopachka explained.

Hope this helps.
