### ISSUE TITLE
Unable to invoke inst action as a creator of an app.

### ISSUE THREAD

**Issue by wincenty-z-kielc-2017** [wit-ai/wit#730]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
A bug.

**What is the current behavior?**
I constantly get HTTP 500 and “_Something went wrong. We've been notified._” in the response when invoking https://api.wit.ai/inst/Wojciech%20Stelmaszewski/PL_chatbot_PL, therefore I’m unable to enter my app management panel.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Invoke GET HTTP action on https://api.wit.ai/inst/Wojciech%20Stelmaszewski/PL_chatbot_PL url.
2. You'll receive HTTP 500 and “_Something went wrong. We've been notified._” in the response.

Important factor seems to be that I try to invoke above action as the creator of the app. When any other member (non-creator) of above app tries to invoke inst action there is no problem at all.

**What is the expected behavior?**
Invoking GET HTTP action on https://api.wit.ai/inst/Wojciech%20Stelmaszewski/PL_chatbot_PL url doesn't end in HTTP error 500.

**What is the App ID where you are experiencing this issue (if applicable)?**
{
      "role" : "creator",
      "access_token" : "***",
      "name" : "PL_chatbot_PL",
      "desc" : "Upgrade to original setup",
      "private?" : true,
      "id" : "58e4e482-b010-40e1-95e5-9769e6b93b79",
      "username" : "Wojciech Stelmaszewski"
}

**Comment by stopachka** [comment]
hey @wincenty-z-kielc-2017

fixed this up for you -- we currently have a small bug, where if you are a contributor to another user's app, with the same name as yours (in this case rjmuggers/PL_chatbot_PL), loading the app starts to come with an issue. a full fix for this coming soon.
