### ISSUE TITLE
Wrong entity value returning

### ISSUE THREAD

**Issue by khwstech** [wit-ai/wit#731]
Have created an 'intent' and have two values:

values:
whatIs2000
whatIs1000

Two phrases and validated against both... 
what is super 2000 oil -> expected return whatis2000
what is super 3000 oil -> expected return whatis3000 
however they both return whatIs2000

**Comment by l5t** [comment]
Can you share your Wit app URL so that we can investigate?

**Comment by khwstech** [comment]
Hi there I believe i was training the data wrong. I followed some tutorials and seemed to get it working. Made an error based on highlighting wrong part of text.

**Comment by stopachka** [comment]
Cheers @khwstech
