### ISSUE TITLE
can't validate new expressions to wit/thanks

### ISSUE THREAD

**Issue by ofirdagan** [wit-ai/wit#732]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

question / bug

**What is the current behavior?**

I'm continuously validating "you rock" as `wit/thanks`. It also shows under the expressions list when I click on the `wit/thanks` entity but it doesn't returns it. Not even with low confidence.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Not sure if it's a bug or I just doing it wrong.

App Id - 5836b64d-e3c4-4825-aa03-e13cd0e5a04b

to reproduce: issue a query with text `you rock`

**What is the expected behavior?**

To get `wit/thanks` entity when I write "you rock" (just one example)

**What is the App ID where you are experiencing this issue (if applicable)?**

App Id - 5836b64d-e3c4-4825-aa03-e13cd0e5a04b

**Comment by khwstech** [comment]
Think this scenario was doing it wrong. Just been following more tutorials and that seems to be working fine now

**Comment by stopachka** [comment]
Because wit/thanks is a built-in entity, it uses all user data, so both the training time, and the strength of the samples, are a bit harder to influence. 

Looking deeper, and will update with the state and next steps here. Thanks for reporting @ofirdagan !

In the meantime, you can make a custom entity, custom_thanks, to detect these

**Comment by ofirdagan** [comment]
Thank you @stopachka !

**Comment by patapizza** [comment]
Hi @ofirdagan,

If you specify a higher `n` (e.g. `n=2`), you'll get `wit/thanks` with a confidence of `0.0169`. As @stopachka mentioned, the entity uses all user data and it might be that other users didn't validate `you rock` as `wit/thanks`.

**Comment by ofirdagan** [comment]
@patapizza - thank you!! I appreciate the help. I will create my own `thank-you` label and train it.
