### ISSUE TITLE
M3 (as in BMW) returns Greetings (true)

### ISSUE THREAD

**Issue by khwstech** [wit-ai/wit#733]
Bug.

So working on a conversation flow to do a vehicle look up.
At this point I am expecting WIT to not find anything... and just let the text go through.
However my flow of conversation goes like:
What is the make of your vehicle
Answer: BMW
What is the model of your BMW?
Answer: M3

At this point WIT returns ... wit/greetings with a value of true?

Quite a big issue right there...

**Comment by stopachka** [comment]
Indeed the confidence when we query this is at 0.94, which points to the possibility that this entity is overfitting. Flagigng this to look deeper, thanks @khwstech!

**Comment by patapizza** [comment]
Thanks for flagging @khwstech. Although `wit/greetings` is still in beta, we definitely should look into improving the model.

**Comment by khwstech** [comment]
No worries. Glad to help

**Comment by jtliao** [comment]
Merging with #1615 for tracking
