### ISSUE TITLE
Extract an entity that generally takes a value in a predefined list (open enum), but you are open to new values

### ISSUE THREAD

**Issue by khwstech** [wit-ai/wit#734]
*Question* or *Bug*

**What is the current behavior?**
I am trying to extract an entity that isnt part of the list yet as stated by subject line.

eg:
I drive a BMW

Expected value:
entity: vehicleMake
value: BMW

I have BMW in my training data but i want it to be able to extract the value for values not currently defined. Similar to the pepperoni example in the doc guide. I followed the same steps but wasnt able to make it work

**What is the App ID where you are experiencing this issue (if applicable)?**
59945ded-a991-458b-9458-1ea934a685af

**Comment by stopachka** [comment]
Thanks for reporting @khwstech, looking into this

**Comment by stopachka** [comment]
(same as #734)
