### ISSUE TITLE
Posting to /samples does not appear to do anything.

### ISSUE THREAD

**Issue by simonvl5** [wit-ai/wit#735]
As the title says, when I post samples to the /samples endpoint, no changes show in my application. I posted about 200 samples, received 
{
"sent": true,
"n": 200
}
from the server and waited for over a day. It does not show up as training samples in the application and when I query it through the API it is clear that the model has not been trained.

My application id :5995a782-4ed3-4997-9831-93d4962f73bf

**Comment by 5amuraix** [comment]
I have the same issue.  I'm trying to train intents with entity positions defined.  The server response is 200 OK, JSON:  {
"sent": true,
"n": 1
} 

but my trained sentences and values don't show up anywhere and the Wit.ai training status just shows "clean."

**Comment by stopachka** [comment]
Indeed, the queue is currently in a backlog -- discussion here: #699
