### ISSUE TITLE
is state inside the context really supported on /message

### ISSUE THREAD

**Issue by Grey-Bit** [wit-ai/wit#737]
HTTP documentation seems to imply that it's old and pre-stories, but now that stories are cancelled...

Is it safe to use it or will it be nixed as well? 

How do I train my data with the state? How do I see state in the inbox?

**Comment by stopachka** [comment]
Hey @Grey-Bit 

What is the use case you have for using it? Are you coming across any issues, where certain entities are too eager? 

--- 

We could make it prominent again, but would love to hear what use case you have in mind

**Comment by Grey-Bit** [comment]
The overall need is in the stateful conversation bots.

A few examples that I am hitting:

When somebody just enters "333", it should be a "number" if the state is "we are calculating something" or "identifier" if we are asking about user ID. 

When somebody enters "right", it's a "confirmation" if we ask some yes/no question or it's a "direction" if we are in geo related conversation.

I see the need mostly where the sentences that user provides are short and don't provide enough context by themselves. 

It's obviously possible to create dummy entities and then interpret them inside the app itself according to the context, but it becomes very cumbersome when certain complexity is reached.

**Comment by patapizza** [comment]
As the documentation reads, the state in the context is only available for apps created before Stories.
For new apps, the state (or dialog engine) should be emulated on the client side.
