### ISSUE TITLE
Improve "Filter by" feature for entities

### ISSUE THREAD

**Issue by hweiler** [wit-ai/wit#741]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
I'm reporting a bug for the "Filter by" feature when viewing entities in Wit.

**What is the current behavior?**
I use the "Filter by" option frequently since we have a large number of intents built into our app. Currently, only the top 5 results appear when you search for an intent value. This creates a problem for us because of the way we set up our app. Our intent values have some of the same starting values, which means we aren't seeing all of them when we search since we're limited to the top 5 results. We can't use this feature at all, even though it would be really useful for us.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open an entity and enter a value into Filter by
Entities with similar values only show up to 5 results

**What is the expected behavior?**
It would be great if this was similar to the Understanding tab. Adding values to Understanding is way easier because I can search for a part of the intent rather than typing out the exact value. If that's not possible, it would be much better to see more or all of the results when searching for a value in Filter by.

**What is the App ID where you are experiencing this issue (if applicable)?**
58c80d0b-dc8a-443a-9570-013e22a1bf8c

**Comment by stopachka** [comment]
Hey @hweiler, great points. This piece of the UI definitely needs improvement. Will add to the queue to fix up

**Comment by patapizza** [comment]
We've added those items to the queue (see #749).
