### ISSUE TITLE
Wit/location greedy?

### ISSUE THREAD

**Issue by exquisiteboy** [wit-ai/wit#742]
wit is misunderstanding a long string of only alphabets as location ?
when i enter the text "kdshkfjahskjdhfkjahskjfhakjsdhfka" into the console it recognize it as wit/location which make no sense .i wondering how it is recognizing this kind of string as a location .

You can train your app by adding more examples
kdshkfjahskjdhfkjahskjfhakjsdhfka
wit/location : kdshkfjahskjdhfkjahskjfhakjsdhfka

**Comment by l5t** [comment]
Thanks for reporting. What is the confidence? Wit/location is trained across all Wit apps that use it so some developers may have validated examples like this. The confidence should be very low though

**Comment by patapizza** [comment]
Thanks for flagging @exquisiteboy. We're actively working on improving `wit/location`.

**Comment by patapizza** [comment]
"kdshkfjahskjdhfkjahskjfhakjsdhfka" doesn't trigger `wit/location` anymore.
