### ISSUE TITLE
Duplicate trait values for intent

### ISSUE THREAD

**Issue by magnusburton** [wit-ai/wit#743]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
I currently see 4 different rows of `overview` in the list of trait values etc.

**What is the expected behavior?**
There should only be 1 value of each trait value if I'm not mistaken. This was previously not a problem and has occurred just now.

**What is the App ID where you are experiencing this issue (if applicable)?**
https://wit.ai/magnusburton/Lisa_SV/entities/intent

**Comment by l5t** [comment]
thanks for reporting.

**Comment by patapizza** [comment]
@magnusburton I removed the duplicates for your intent entity.
