### ISSUE TITLE
App stuck in training since Thursday

### ISSUE THREAD

**Issue by exs6350** [wit-ai/wit#745]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question

**What is the current behavior?**
App has been stuck in ongoing training since Thursday. Not sure if this is valid or something else is happening. I think this is what's contributing to slow queries returning from my wit app. I did insert a lot of values into my app last week ~10k.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.** Inserted a lot of values into an entity (~10k). App has been in ongoing training since then. I've seen a slower response than usual when querying my app.

**What is the expected behavior?**
Training should've finished by now.

**What is the App ID where you are experiencing this issue (if applicable)?**
598ddb6f-f8f9-4a3e-940f-682ed0eb9bae

**Comment by patapizza** [comment]
Hi @exs6350,

Sorry about that. I fixed your instance.
