### ISSUE TITLE
Question: How to properly train WIT?

### ISSUE THREAD

**Issue by icemanTopGun** [wit-ai/wit#746]
Hello everyone. I have been playing around with the WIT service over the past few months and I am trying to understand what is the best practice for training WIT AI. This is what I have so far:
1. Identify intents (what will user want to ask/do with the topic) - this has been done with my dev team. Essentially came up with a list of actions that our bot will do.
2. Identify entities - our dev team was able to identify keywords that are relevant to our domain. 
3. Train intents with variations of expressions - 

A couple of questions: 
For 2. can entities exist in multiple domains/topics in a chat bot?

For 3 - this is where I am stuck. We have not leveraged real users to provide any expressions because we want to initially train WIT before releasing out to our beta testers.  How should I go about finding expressions that are relevant enough to train these intents? Is it a matter of just manually entering expressions and then engage our end users to build/re-train our WIT. 
Also is there a process that you all use on how to get users to test out the chatbot.

Thanks everyone.

**Comment by patapizza** [comment]
Hi @icemanTopGun,

The overall process makes sense to me.
Re 2: Yes, the same entity can show up across multiple intents.
Re 3: This is a tricky one. When building a chatbot, one usually has a rough idea on what the users would say to it. These expressions should be used to initially train the app. Of course there might be weird inputs (you can't control what the users say), hence the beta testing and more training.

More thoughts welcome here!

**Comment by l5t** [comment]
Usually you start with Beta testers and can leverage the Console Inbox to validate more expressions

**Comment by icemanTopGun** [comment]
Thanks l5t and patapizza

the problem with this is we don't have any logs or data to look at - it feels that we are putting in manual expressions. Not sure what to do as there is no documentation on how to properly get expressions that most users will ask

**Comment by patapizza** [comment]
This is a form of a cold-start problem.
I would suggest to feed a few sentences, bring in a few beta testers, and as new samples come in, monitor closely and validate on the go (tight feedback loop), get a better model, bring more users, etc. 
I'm closing this ticket. Maybe you can get more ideas from the Wit Hackers group on Facebook.
