### ISSUE TITLE
cannot add new traits for intent

### ISSUE THREAD

**Issue by mlu-converse** [wit-ai/wit#748]
I want to report a *bug*. I'm trying to define new traits for entity Intent. I frequently receive a 'Could not validate this expression' message. My intention is to define 2 intents (in Polish languge): 'yes' ('tak' in Polish) and 'no' ('nie' in Polish), to understand whether client generally agrees or disagrees in his message.
![my_wit_error](https://user-images.githubusercontent.com/30246552/29817706-5b7c50c6-8cb9-11e7-8944-b955205ee72e.png)

app id is ConverseApp on my account.

**Comment by mlu-converse** [comment]
Maybe more detail: I'm not able to define trait 'nie'. Every try in 'Understandig' menu fails.. Only one training example passed for 'tak', the next also fail and the api does not return this trait even for an exact copy of trained message.

**Comment by patapizza** [comment]
Hi @mlu-converse,

Please use the template (e.g. app id) when reporting an issue.
Do you still experience the issue?

**Comment by mlu-converse** [comment]
App ID: 596d3f18-2f40-433e-ba71-20f850e6ec5e
It happens frequently on other intents as well. I've tried to make a different approach and I've created a new entity 'tak_nie'. I only managed to add a few examples. Rest of them yields the same result: an error popup.

**Comment by mlu-converse** [comment]
I want to report a *bug*. I'm trying to define new traits for entity Intent. I frequently receive a 'Could not validate this expression' message. My intention is to define 2 intents (in Polish languge): 'yes' ('tak' in Polish) and 'no' ('nie' in Polish), to understand whether client generally agrees or disagrees in his message.
![my_wit_error](https://user-images.githubusercontent.com/30246552/29817706-5b7c50c6-8cb9-11e7-8944-b955205ee72e.png)

app id is ConverseApp on my account.

**Comment by patapizza** [comment]
Thanks @mlu-converse, I'll look into it.

**Comment by patapizza** [comment]
@mlu-converse This should be fixed now.
