### ISSUE TITLE
Searching is taking a long time to load

### ISSUE THREAD

**Issue by hweiler** [wit-ai/wit#749]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
I'm reporting a bug related to the "Search through your expressions" feature.

**What is the current behavior?**
I unfortunately can't fully utilize the Filter By feature since the limit of 5 options makes it impossible to search for all of my intents. I had hoped to utilize the Search feature instead, however, it's take a really long time to load and I have to continually select "See More" to get any expressions to appear. I'm searching words that I know should be in the expressions, and yet the system doesn't display them right away.

As an example, I just trained an intent yesterday where the expressions included the word "modify." No expressions appeared at all, and I'm still selecting "See More" to pull up more search results.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Enters a word or phrase to search through expressions
2. The system doesn't load any expressions, but still shows the "See More" button
3. Continually selects "See More" to get expressions to load.

**What is the expected behavior?**
I'd expect the first few results to pop up right away, and the "See More" button should only be used to see more than 5 or 10 matching expressions.

**What is the App ID where you are experiencing this issue (if applicable)?**
58c80d0b-dc8a-443a-9570-013e22a1bf8c

**Comment by patapizza** [comment]
Hi @hweiler,

Thanks for reporting this.

Although the `Filter By` feature only shows 5 options, it is actually a type ahead and if you type in another value, it will update and you'll be able to use the feature properly. This can definitely use a better UX.

Re the `Search` feature, it looks like it's only filtering results already shown (i.e. you would need to do `See More` of all your expressions before being able to do a exhaustive search).

I'll make a note internally with these 2 items, and I'm closing this issue as it looks like the `Filter By` feature should cover your need. Feel free to reopen if you are still blocked.
