### ISSUE TITLE
No inbox samples for Built-In NLP

### ISSUE THREAD

**Issue by Arsenikr** [wit-ai/wit#751]
i've connected my custom wit app to the new FB messenger built in nlp feature.
so now facebook takes care of calling wit for me and returns the entities to my backend.

all is working well but for about a week now no new messages are arriving to inbox and i do see users talking to my bot (about 10 users per day).

please check it, i can't train my app..

app-id: 591b5074-9f07-48b1-ba0e-36aa1fa756bb

**Comment by patapizza** [comment]
Hi @Arsenikr,

Thanks for reporting this. We're currently working on it.

**Comment by Arsenikr** [comment]
ETA?

**Comment by patapizza** [comment]
We should be able to come up with a fix next week.

**Comment by Arsenikr** [comment]
worl
