### ISSUE TITLE
How can I map an intent trait to the intent response? (Always returns default_intent)

### ISSUE THREAD

**Issue by christianrondeau** [wit-ai/wit#752]
Hi! I guess this is a question, but might be a defect or a request, depending on what I did wrong!

When I type `Hello!`, I have created an `intent` with the type `trait`, which is correctly found by wit.ai. However, even though it does return the `intent` as an entity, it also returns `default_intent` in the response (from the wit.ai _logs_):

    [
      {
        "entities": {
          "intent": [
            {
              "confidence": 0.98002834722638,
              "value": {
                "value": "bot_status"
              },
              "entity": "intent"
            }
          ]
        },
        "confidence": null,
        "_text": "Hello!",
        "intent": "default_intent",
        "intent_id": "default_intent_id"
      }
    ]

I'd expect the `intent` to be `bot_status` in this case.

I believe something might be wrong in my config, because when I create a new entity without values (e.g. `Let's debug this!`, with the entity `debug_intent`, I have no luck, it doesn't see a perfect match even though it does find it in the Understanding tab. Here's the log:

    [
      {
        "entities":
        {
        },
        "confidence":
        null
        "_text":
        "Let's debug this!",
        "intent":
        "default_intent",
        "intent_id":
        "default_intent_id"
      }
    ]

Intents did work at some point before. I guess something might be wrong, either with how I configured things or with my app data. It might be because I deleted the built-in `intent` entity at some point (not 100% sure)

My app ID is `59a5d3b0-afb4-402e-a056-cae3858b4e41`

Thanks! (By the way, wit.ai is really, really cool!)

**Comment by christianrondeau** [comment]
Mmmh, I did some more tests, and the `debug_entity` behaves weird. When I type it again in the `Undersanding` tab, it doesn't find it. I can register it again and again, it doesn't fail, but it doesn't match it either. Also, the entity doesn't get passed in the PUT request when I press `Validate`...

The `messages`. I get back looks like this:

    {
       "msg_id": "0nLqSxuNWqRpUb8y4",
       "_text": "Let's debug this!",
       "outcomes": [
          {
             "confidence": null,
             "intent": "default_intent",
             "_text": "Let's debug this!",
             "entities": {
             }
          }
       ],
       "WARNING": "DEPRECATED"
    }

I'm stumped. And I can't create a new app (that's another issue I guess), so I can't just make another app from scratch to confirm it's an app-specific issue.

**Comment by christianrondeau** [comment]
I created a new app, in which I added a `hello` value in the `intent` entity through the Understanding tab, by typing `Hello!` and same behavior, I receive `default_intent`.

I also tried re-creating the `debug_intent` value-less entity with `Let's debug this!` in the Understanding tab, and again it doesn't get detected, and the `entities` block in the response is empty.

The new App ID is `59a6d912-44b2-4113-82d3-066957e96e32` (I'll keep both for now, just in case you need them)

For what it's worth, I'm using https://github.com/jsgoecke/go-wit as the client, and https://github.com/BeepBoopHQ/go-slackbot/blob/master/examples/wit/wit.go, pretty much as-is.

**Comment by patapizza** [comment]
Hi @christianrondeau,

Thanks for your kind words and trying Wit!

- Trait entities need a value. One way to do that is to create a new trait entity for each intent, as you did, with a default value, like `true`. Another way would be to reuse the `intent` entity and add a different value for each intent. In both apps, the `debug_intent` entity doesn't have any validated expressions. Make sure you validate a few examples for each intent to train Wit.
- It looks like you managed to create a new app now. Is it that you missed the `+` button or it just didn't work?
- Those 2 clients are pretty outdated and rely on an old API format. Please refer to the API format in https://wit.ai/docs/http/latest#get--message-link (i.e. rely on the `entities` key only, not `outcomes`).

Hope this helps. Feel free to reopen if running into any issues.

**Comment by christianrondeau** [comment]
* Trait entities need a value: understood. I misunderstood (so let's forget about the debug_intent)
* For a while it didn't work (tried refreshing), and when I tried again later it worked. I should have inspected the HTTP calls, but I didn't, sorry about that. There was a spinner after naming the app, and nothing happened. Might have been slow, I don't know.
* I'll write my own wrapper then, or look for someone who might have written one in Go already :)

However, my main question remains: the `intent` field *always* returns `default_intent`. When you say "rely on the `entities`, not `outcomes`, do you mean I should _ignore_ the `intent` field completely, and only rely on the `intent` entity in the `entities` block? If so, my issue is resolved, and I'll search for the `intent` entity. Thanks for the help, that'll get me moving :)

**Comment by patapizza** [comment]
Yes that is correct: ignore the `intent` field completely.

**Comment by christianrondeau** [comment]
If someone ever comes back here, I upgraded the library to the latest version: https://github.com/christianrondeau/go-wit (version `20170307`). There's a few forks floating around, but they're quickly getting out of date since the original author didn't maintain the project. I tested it and it works, though the BeepBoopHQ example is also out of date (since it's using outcomes, instead of looking for the `intent` entity)

**Comment by patapizza** [comment]
Nice and quick turnaround! Thanks for sharing :)
