### ISSUE TITLE
Wrong entities returning

### ISSUE THREAD

**Issue by vduxproto** [wit-ai/wit#757]
Today I tested two commands, and found it returns wrong entities.
1. London weather tomorrow
-> It doesn't send 'wit/location' for 'London'.
```
curl -H 'Authorization: Bearer QKCHEV3N5C33EBQEXUGTUBLTWA7C7MJS' 'https://api.wit.ai/message?v=20170901&q=London%20weather%20tomorrow' -k
{"msg_id":"0yjJRjqseZ5lEn58W","_text":"London weather tomorrow","entities":{"ux_ambient":[{"confidence":0.98119275613579,"value":"weather","type":"value"}],"datetime":[{"confidence":0.95969,"values":[{"value":"2017-09-02T00:00:00.000+09:00","grain":"day","type":"value"}],"value":"2017-09-02T00:00:00.000+09:00","grain":"day","type":"value"}],"on_off":[{"confidence":0.98681196389405,"value":"on"}],"intent":[{"confidence":0.87731106583629,"value":"weather"}]}}
```
```
curl -H 'Authorization: Bearer QKCHEV3N5C33EBQEXUGTUBLTWA7C7MJS' 'https://api.wit.ai/message?v=20170827&q=London%20weather%20tomorrow' -k
{"msg_id":"03xeJG54LSbcyJcJd","_text":"London weather tomorrow","entities":{"ux_ambient":[{"confidence":0.98119275613579,"value":"weather","type":"value"}],"datetime":[{"confidence":0.95969,"values":[{"value":"2017-09-02T00:00:00.000+09:00","grain":"day","type":"value"}],"value":"2017-09-02T00:00:00.000+09:00","grain":"day","type":"value"}],"on_off":[{"confidence":0.98681196389405,"value":"on"}],"intent":[{"confidence":0.87731106583629,"value":"weather"}]}}
```

2. What's the weather
-> It send 'wit/location' for 'the'.
```
curl -H 'Authorization: Bearer RAJE5G5FCT4HOD3WF72OQYESLD6OYKHR' 'https://api.wit.ai/message?v=20170801&q=What%27s%20the%20weather' -k
{"msg_id":"0GQ5OehpJRqNfcF21","_text":"What's the weather","entities":{"location":[{"suggested":true,"confidence":0.86106,"value":"the","type":"value"}],"ux_ambient":[{"confidence":0.99316801480556,"value":"weather","type":"value"}],"intent":[{"confidence":0.99819107872459,"value":"weather"}],"on_off":[{"confidence":0.92937758917217,"value":"on"}]}}
```

It worked well in yesterday and I didn't change entities.
We also tested with former versions, but it still works same.

My App ID is **5923ed2d-61c8-41d9-92d1-6343e44a2a77**

Thanks.

**Comment by patapizza** [comment]
Hi @vduxproto,

Thanks for reporting. I'll look into it.
You probably want to reset your token now.

**Comment by kl-wong** [comment]
I had the same problem. 
![screen shot 2017-09-01 at 3 44 44 pm](https://user-images.githubusercontent.com/31428678/29956751-97860664-8f2c-11e7-93bd-e17c43b81006.png)
Only Sydney picked as wit/location
App ID: 59a498fb-c649-471f-89b4-2b64a0658dff

**Comment by patapizza** [comment]
Got it @kl-wong. Make sure to validate the sample to help Wit get better.

**Comment by kl-wong** [comment]
@patapizza I did validate those sample. It seems like the app only pick up the first location if the second location was the last word in the sentence.
Adding any word after the second location is fine
![screen shot 2017-09-01 at 5 05 35 pm](https://user-images.githubusercontent.com/31428678/29958810-e92600e0-8f37-11e7-8f4e-de4be308cf6e.png)

**Comment by patapizza** [comment]
Update: I've found the root cause and I'm working on a fix.

**Comment by vdisawar** [comment]
Responding from #25 

I highlighted and validated a street: '326 joliet st' for wit/location. When I GET /message the same address, it recognizes it's a location, but only returns 'joliet'

"entities": {
        "location": [
            {
                "confidence": 0.93722,
                "suggested": true,
                "type": "value",
                "value": "joliet"
            }
        ]
    }

Happy to provide more information to help resolve this.

**Comment by patapizza** [comment]
This should work better now.
