### ISSUE TITLE
[QUESTION] no data training when using built in NLP facebook messenger

### ISSUE THREAD

**Issue by mr2tkoollove** [wit-ai/wit#758]
I have a question when i using built in NLP fb messenger.
according to i know, when i using built in NLP and connect to my project in wit.ai.
When an user send message for my bot -> a webhook post to my host with all entities detected,
and if no entity found then will a webhook sending to my inbox of my project in wit?

please help me!
sorry for my bad english :(

**Comment by patapizza** [comment]
Hi @mr2tkoollove,

Once #751 resolves, yes. Closing in favor of #751.
