### ISSUE TITLE
Bug - same keyword value for two different entities

### ISSUE THREAD

**Issue by icemanTopGun** [wit-ai/wit#759]
Hello there,

I am trying to create two different entities (i.e. topics) say:

Entity: Air
Entity: Drive clean

The value that I want assign for each entity is "test" for example. I have validated several expressions that have the entity 'Drive Clean' when it parses 'test' but once I have a different set of expressions with the word 'test' that should be entity 'Air', WIT ai always goes back to the entity 'Drive clean', despite me remove this entity and re-assigning to the other entity.

Can I have the same keyword value for two different entities - if not, how can I have a domain that spans with multiples topics but may share same values to train WIT.

Thank you

**Comment by patapizza** [comment]
Hi @icemanTopGun,

Please use the template when reporting issues. What is your app id?

**Comment by icemanTopGun** [comment]
Hi @patapizza 

Sorry for misusing the template - app id is MikeBot. 

I used the expression where can I get a drive clean test? but test always gets assigned to air entity even after i change it.

**Comment by patapizza** [comment]
@icemanTopGun This is the app name, you can find the app id in the Settings. Thanks!

**Comment by icemanTopGun** [comment]
@patapizza apologies again. Here is the app id 591651ff-60cd-4a04-9446-6b00a317a9a4

**Comment by icemanTopGun** [comment]
Hi patapizza,

I added another entity: spill that has the keyword value 'test' and any re-assignment would take the last created entity. Just something to look out for I guess but not sure if this is an error.

**Comment by stopachka** [comment]
Hey @icemanTopGun -- Great point. We should make it clear how the model deals with this. when there are 2 free-text entities with the same span. 

I'll research more deeply and follow up

**Comment by stopachka** [comment]
Update: let's use this task as a way to gather all the concrete use cases of two free-text entities that would need to have the same span. We can think of a good solution based on the examples

**Comment by icemanTopGun** [comment]
Hi, I just want to make it clear - I am using the entities as "keywords" for the lookup strategy. When this value exists in two entities - it seems WIT just defaults to one of the entities. I haven't leveraged the free-text strategy

**Comment by stopachka** [comment]
Understood! 

The current data model, and the UI model don't do well with representing the same span as different entities. 

I can see how this could be useful though for keyword entities. i.e something could be all three of "song", an "author", or an "album", at the same time.
