### ISSUE TITLE
Can wit.ai provide text-to-speech?

### ISSUE THREAD

**Issue by rocendroll** [wit-ai/wit#760]
As in title, guys, is it possible using wit.ai, or is it only for speech-to-text?

If not, do you know any other possible tool, that could do that? I'm trying to do a chatbot, and I think I can't do that on Messenger so I'm looking for alternative. Once again, I'm looking for TTS, so user could hear my displayed messeges to him.

**Comment by patapizza** [comment]
Hi @rocendroll,

Wit.ai doesn't provide TTS today, and there is no plan in the near future to support that.
