### ISSUE TITLE
Where I can browse other users open apps?

### ISSUE THREAD

**Issue by asuiu** [wit-ai/wit#761]
**It's a BUG on web-site.**

Website lacks any link to other users open apps.
Wit Documentation states that:

> **open app** can be browsed and later forked by anybody. Only the Understanding page is visible, but read-only. In particular, the Inbox and Logs sections are not visible.

Expected behavior would be showing on the home page a link to a page where a user can browse the other users open apps.

Thank you.

**Comment by patapizza** [comment]
Hi @asuiu,

Thanks for reaching out.

What the documentation says is that open apps can be browsed provided one has the link. I think what you're expecting is an index of all open apps, which we haven't had the chance to prioritize yet.

**Comment by asuiu** [comment]
So this is something is not implemented yet. 
@patapizza Is there an open issue for this?

**Comment by blandinw** [comment]
@asuiu no issue for this, we're tracking this internally and trying to prioritize against other improvements we have in mind. Before opening an issue, we have to scope it better, which should happen in the following months

**Comment by patapizza** [comment]
Hi @juliomac, no updates on this yet. We'll need to prioritize this.
Although different, we can keep track of it in https://github.com/wit-ai/wit/issues/266, as it is related.

**Comment by efleurine** [comment]
So I am the 2020 user to find this open to browse but difficult to find.

patient new user

**Comment by prashantchaudhary1** [comment]
And I'm the 2023 user complimenting Product Roadmap manager of Wit...bravo!
