### ISSUE TITLE
Response times of 1 to 4 seconds with HTTP API

### ISSUE THREAD

**Issue by stijn-de-witte** [wit-ai/wit#762]
Do you want to request a feature, report a bug, or ask a question about wit?
Bug - Performance is slow.

I read in ticket https://github.com/wit-ai/wit/issues/670 that this is something I can't solve myself. I am accessing the API from Belgium

What is the current behavior?
The HTTP message API has always return results between 1.200ms to 4 seconds.

I tested the response time using terminal and PHP curl requests

curl -o /dev/null -s -w %{time_total}\n -H 'Authorization: Bearer mytoken' \
 'https://api.wit.ai/message?v=292017&q=test'

What is the expected behavior?
.500ms would be great.

What is the App ID where you are experiencing this issue (if applicable)?
5992d385-4a87-4c6c-9205-01f9a35fc3fe

A sidenote: we use the service in Dutch and we are really pleased with the results, keep up the good work!

**Comment by patapizza** [comment]
Hi @stijn-de-witte,

Thanks for your kind words.

This is indeed high latency! We're not seeing that on our end.
Can you share a few inputs that we can use to test the latency on your app?

Thanks.

**Comment by stijn-de-witte** [comment]
Hi,

You can test it on our testing environment: https://fluxit.be/ai/demo2/ -> click on right bottom and enter 'test'.

We do include a small database request in PHP, but that's not causing the delay. Here you see a screenshot of the latency: https://snag.gy/ciGEhd.jpg

Let me know if you need other input.

Thanks

**Comment by stijn-de-witte** [comment]
Hi @patapizza ,

Have you been able to look at this?

Thanks

**Comment by stopachka** [comment]
Hey @stijn-de-witte -- apologies for the late response on this -- we are going through a migration to more robust infra, where the speed will increase dramatically. 

Even now though > 500ms is quite bad -- will look into this early next week.

**Comment by sylmanu** [comment]
Thanks for the tremondous work guys but we're really expecting this to be settled!

**Comment by stopachka** [comment]
Cheers @sylmanu! https://github.com/wit-ai/wit/issues/721 is indeed related to this

**Comment by stijn-de-witte** [comment]
Hi @stopachka ,

Any update on this? We would like to demo this to a potential customer but at the moment the latency makes the chat feel slow.

Sometimes I even get response times of 4.3 sec.

Thanks for the effort

**Comment by stopachka** [comment]
Hey @stijn-de-witte  -- I am able to repro the sometimes drastic latency blips. Will update here as soon as I have info

**Comment by stopachka** [comment]
Closing the loop on this. The P90 for /message is currently 1s for this request. 

Both /message and /speech are slow currently because they are in the middle of migration to more stable infra, which will perform at FB scale. These changes will land in the next few months, and the speed should increase considerably

**Comment by john-bonachon** [comment]
@stopachka :) great.. where would it be announced (if that happens)?
