### ISSUE TITLE
New sample posted through API, doesn't appear on web console

### ISSUE THREAD

**Issue by kkim025** [wit-ai/wit#763]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

bug

**What is the current behavior?**

When I post sample (training) through HTTP API, I get success response but doesn't seem to be working - not showing on web console. If I try to add it from web console (add expression), it works

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

I am trying to post new sample requests through HTTP API, here are my request and response:

URL: https://api.wit.ai/samples?v=20170905
JSON DATA: [{"text":"any minimum contract periods?","entities":[{"entity":"intent","value":"about"},{"entity":"accounts","value":"contract"}]}]

And I get this response back:
{
    "sent": true,
    "n": 1
}

But nothing added in expression nor the GET message API.

(I have both 'intent' and 'accounts' entities.)

**What is the expected behavior?**
Update web console, and adds new expression.

**What is the App ID where you are experiencing this issue (if applicable)?**

All of them, these are the App IDs:
59a49d5d-a929-44c4-8794-70bd4611482b
59a8bdf4-6598-484e-b5da-8c805d67c62e
59a8f9bb-dff7-41b3-af69-903cb2fd6128

**Comment by blackingbar** [comment]
i got the same problem!

**Comment by hactar** [comment]
I have the same problem with a test app (59ad61fa-2db7-4951-9586-89963fb2b922) - I've waited 24 hours in case this is the back log issue, but nothing appeared.

**Comment by patapizza** [comment]
Thanks for reporting, we'll look into it.

**Comment by patapizza** [comment]
@kkim025 I can see the sample in 59a49d5d-a929-44c4-8794-70bd4611482b, did you add it manually?
@blackingbar @hactar Do you still experience the issue? What was the JSON (and app-id @blackingbar)?

**Comment by kkim025** [comment]
It seems to working now. I'm testing them at the moment and its looking good so far!

**Comment by patapizza** [comment]
Great, closing. @blackingbar @hactar Feel free to reopen if it doesn't work for you.

**Comment by hactar** [comment]
Yes, the samples in my app have been processed too now, it just took more than a day before they appeared.
