### ISSUE TITLE
POST Built-in entities using Wit.ai programmatically

### ISSUE THREAD

**Issue by greeeg** [wit-ai/wit#765]
Bug

I'm trying to automate the creation of built-in entities using the Wit.ai HTTP API. Using the tutorial available here [https://github.com/wit-ai/wit-api-only-tutorial#add-date-detection](https://github.com/wit-ai/wit-api-only-tutorial#add-date-detection), I'm trying to create a built-in entity as follows:

#### Sends the POST request
```
curl -XPOST 'https://api.wit.ai/samples?v=20170307' \
  -H "Authorization: Bearer $NEW_ACCESS_TOKEN" \
  -H "Content-Type: application/json" \
  -d '[{
        "text": "I want an appointment for tomorrow please",
        "entities": [
          {
            "entity": "intent",
            "value": "appt_make"
          },
          {
            "entity": "wit$datetime",
            "value": "tomorrow",
            "start": 26,
            "end": 34
          }
        ]
      }]'
```

#### Receives the response
```
{ "sent" : true, "n" : 1 }
```

But when I try to test this out using the `GET /message` endpoint, no entity is detected and my newly created entity doesn't appear in my Wit.ai App dashboard.

**Is there any other way to use the API to create built-in entities?**

**Concerned Wit.ai App:** *59415cbf-6477-4b27-92cc-d5bea5ac055b*

**Comment by stopachka** [comment]
Hey @greeeg, currently the POST /samples endpoint puts your request into a queue, to be processed asynchronously. It may have been that the queue was backed up during that time. Took a look at your app and I see the entities there. Let me know if above is not the case
