### ISSUE TITLE
Approach conversations with HTTP API

### ISSUE THREAD

**Issue by rowanvanekeren** [wit-ai/wit#766]
Hi,

We are building a chatbot. Getting the intent and providing a correct answers works as expected.

However, we don't know the best approach for actual conversations.

For example:
User: Tell me a joke
Bot: tells a joke
User: tell me another one

We can store the current intent of the conversation, but can we send the current intent of the conversation to wit (in this case current intent = tell joke and query = another one)? Or should we get the intent 'tell me another one' and build the logic ourselves?

If we have to write the logic ourselves, do you have resources explaining the best practices?

Thanks

**Comment by patapizza** [comment]
Hi @rowanvanekeren,

The part where you send over the state of the conversation was handled by Stories, which we've deprecated: https://wit.ai/blog/2017/07/27/sunsetting-stories. In the blog post we've linked a tutorial on how to do the same thing using intent detection and entities extraction only.
Now for your use case, you can map "tell me another one" to the same intent to recognize it as well, or if your bot handles different commands to have a more generic "tell me" intent and another entity to capture which thing to tell (e.g. "joke", "news"). Then you could store the last one in your code and when you get the "tell me" intent with no other entity, default to the last one stored.

Hope this helps.
