### ISSUE TITLE
Question: Overlapping Entities

### ISSUE THREAD

**Issue by milesaverydixon** [wit-ai/wit#767]
Question

I have a restaurant application that stores the entities: "group" (as in burger, cocktail, espresso, etc.), "meal" (breakfast, dinner, etc.) and "product" (specific dishes like t-bone steak). One of the products is named "grilled salmon dinner". "salmon" is a group, and "dinner" obviously a meal, so wit.ai will pick up the entities group and meal, instead of the product "grilled salmon dinner". At the same time, however, it will pick up "bacon burger", a product, and not just "burger", a group. Is there a way to teach wit what to choose? It needs to always choose the products, but no matter how much I validate examples it doesn't change.

The expected behavior would be for the application to understand what to choose after validating enough examples.

Is it ever a good idea to download the app's .zip and manually go into the expressions.json to delete maybe an accidental validation that may be causing the problem? ...

Thanks!

**Comment by Krogsager** [comment]
I'm curious as well. I wonder if this could have been solved with states (now deprecated).

**Comment by l5t** [comment]
my understanding is that is should always take the one that maximize the span so in your example grilled salmon dinner. @patapizza  can you confirm.
Re: states that are now deprecated, they were only boosting the intent (not entities). You can probably replicate the behavior on our side by boosting the confidence return based on your context

**Comment by patapizza** [comment]
Hey @milesaverydixon,

Are you using composite entities? The way to go would be to highlight `grilled salmon dinner` as `product`, and add `salmon` as composite `group` under `product` and `dinner` as composite `meal` under `product`.

**Comment by l5t** [comment]
@milesaverydixon  does it answer your question? Please reopen if not.
