### ISSUE TITLE
Phone numbers with forward slash '/' in format

### ISSUE THREAD

**Issue by eanajjar** [wit-ai/wit#768]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
Phone numbers with the format 01/234567 cannot be detected using the builtin wit/phone_number entity. Only the part after the forward slash gets extracted. Defining a custom entity and training it to detect the phone numbers would work. However, a new problem comes up when adding a wit/number entity to the app. The wit/number considers the '/' as a division, evaluates the expression and outputs the result as the value of the wit/number entity.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- Create a new app
- Add wit/phone_number entity (or train a new my_phone_number entity) 
- Add a wit/number entity
- Test: 01/123456

**What is the expected behavior?**
Expected result: phone_number entity with 01/123456 as value
Actual result: number entity with 0.0000081000518403318 as value

**Comment by l5t** [comment]
Thanks for reporting, this entity is controlled by our open-sourced parser. Feel free to contribute and send us a PR there.https://github.com/facebookincubator/duckling
Out of curiosity, where is this phone number format used?
