### ISSUE TITLE
Question about extracting values depending on sentence structure

### ISSUE THREAD

**Issue by exs6350** [wit-ai/wit#769]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question

**What is the current behavior?**
I have a stock symbol that I want to parse out from a sentence. Wit is extracting the wrong symbols on certain sentences. 
An example sentence is: I want to buy 20 shares of NFLX at market price
Here NFLX is the stock symbol that should be parsed out but wit is also picking up two more symbols: AT and I (which are valid symbols but just not in this sentence). I currently have an entity for parsing out stock symbols set to free text and keywords. I'm not sure how I can train wit to parse out the correct symbols depending on the sentence structure. I tried validating a couple of sentences where I correct the behavior but wit keeps picking up extra stock symbols especially symbols that are just one character ( like A or B )

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Wit should only be returning valid stock symbols based on the sentence structure. Is there a way I can train wit to return values based on the sentence structure? Do I have to change the way wit is searching on that entity? 

**What is the App ID where you are experiencing this issue (if applicable)?**
598ddb6f-f8f9-4a3e-940f-682ed0eb9bae

**Comment by stopachka** [comment]
Hey @exs6350 

In this case, this entity is solely based on keywords, and the sentence structure does not matter. 

For this case, I'd suggest you change the lookup strategies for your entity, to be keywords only. You can then upload a database of keywords to wit, to extract the stock.
