### ISSUE TITLE
Wit is not learning from my suggestions/inputs

### ISSUE THREAD

**Issue by abhilashmurthy** [wit-ai/wit#770]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
*bug*

**What is the current behavior?**
My app does not learn from my suggestions; it's been working fine for 9 months but recently it does not understand some key inputs and does not map them to the right intents

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- Using my app, entering `:)` should take you to the findBusTime intent
- Entering `Shakalakaboomboom` should understand that as a wit/location

**What is the expected behavior?**
When I hit 'Validate' in the Understanding tab, it should accept my input as a suggestion and show me the entities I entered the next time I enter it. It's been working fine for 9 months, but recently (for about a week or more) stopped learning and doesn't recognise my suggestions

**What is the App ID where you are experiencing this issue (if applicable)?**
58023ff9-8490-41fe-816b-0f18f418092a

**Comment by patapizza** [comment]
`Shakalakaboomboom` now works for `wit/location`.

**Comment by abhilashmurthy** [comment]
@patapizza thank you for that, that part works now

However now a lot of other things are falling back to `wit/location` 🤔  A couple of inputs I do **not** want falling back to `wit/location` are `More` and `Back`. Could you please take a look at this again?

**Comment by patapizza** [comment]
`wit/location` is a bit greedy, especially for short inputs. The best way to go around that is to teach it by validating samples without `wit/location`, like the ones you mentioned.

**Comment by abhilashmurthy** [comment]
@patapizza I've been training `More` and `Back` to NOT be locations, but it never learns when I valid `NOT-wit/location`. 

My only other option here is to create another entity called `reserved_keywords` or something, and train my app to classify `More` and `Back` to this, instead of `wit/location`. In your opinion, is that good practice? I can't justify that it's good because I just don't want them to be locations...

**Comment by blandinw** [comment]
duplicates #772 
let's discuss and list false positives there
