### ISSUE TITLE
Wit returns 'What's' as a wit/location.

### ISSUE THREAD

**Issue by vduxproto** [wit-ai/wit#772]
I uploaded an issue about 'Wrong entities returning' a week ago. #757 
Now it works fine. Thanks :)

But some cases are still returning wrong entities.
When I test 'What's the weather' and 'How's the weather' without city(location) name,
wit picked 'What's' and 'How's' as wit/location.

![whats](https://user-images.githubusercontent.com/28075321/30254758-d048374e-96d7-11e7-9fc1-d61406a906fb.PNG)
![hows](https://user-images.githubusercontent.com/28075321/30254757-d01d4e1c-96d7-11e7-866c-bc76aaec1500.PNG)

If I test those commands with city, then it works fine.

![city](https://user-images.githubusercontent.com/28075321/30254756-cff2fdc4-96d7-11e7-8b19-2e128ab01db6.PNG)

My App ID is 5923ed2d-61c8-41d9-92d1-6343e44a2a77.
Thanks.

**Comment by bmcclenahan** [comment]
I've noticed that over the past week people's names are being returned as location rather than contacts.
this happened for a while a long long time ago, then got better, but it seems to have deteriorated.

**Comment by l5t** [comment]
We are working on wit/location so that may explain some regressions. cc @patapizza on our side

**Comment by bmcclenahan** [comment]
Thanks for checking back
It must be difficult to distinguish contacts from locations at times - many places are named after people and many surnames  sound like places - street , lake, etc
All the best

On 12 Sep 2017, at 1:24 am, Laurent Landowski <notifications@github.com<mailto:notifications@github.com>> wrote:


We are working on wit/location so that may explain some regressions. cc @patapizza<https://github.com/patapizza> on our side

**Comment by stopachka** [comment]
Hey @bmcclenahan -- if you have more samples of incorrect classifications, please let us know!

**Comment by bmcclenahan** [comment]
I’m just seeing missing contact classifications.
Here are some examples from my log

[
{
"entities":
{
}
"confidence":
null
"_text":
"
Angela adamo
"
"intent":
"
default_intent
"
"intent_id":
"
default_intent_id
"
}
]

[
{
"entities":
{
"intent":
[
{
"confidence":
0.99844862869474
"value":
{
"value":
"
roster_query
"
}
"entity":
"
intent
"
}
]
}
"confidence":
null
"_text":
"
When is Slater next on
"
"intent":
"
default_intent
"
"intent_id":
"
default_intent_id
"
}
]


[
{
"entities":
{
}
"confidence":
null
"_text":
"
Jared
"
"intent":
"
default_intent
"
"intent_id":
"
default_intent_id
"
}
]

[
{
"entities":
{
"position":
[
{
"confidence":
1
"start":
28
"end":
34
"body":
"
roster
"
"value":
{
"value":
"
roster
"
}
"entity":
"
position
"
}
]
"intent":
[
{
"confidence":
0.94632679070279
"value":
{
"value":
"
roster_query
"
}
"entity":
"
intent
"
}
]
}
"confidence":
null
"_text":
"
What is stephen sanderson's roster
"
"intent":
"
default_intent
"
"intent_id":
"
default_intent_id
"
}
]


[
{
"entities":
{
"intent":
[
{
"confidence":
0.99829965136626
"value":
{
"value":
"
person_query
"
}
"entity":
"
intent
"
}
]
}
"confidence":
null
"_text":
"
Who is Karola Williams
"
"intent":
"
default_intent
"
"intent_id":
"
default_intent_id
"
}
]

**Comment by l5t** [comment]
Closing at it seems to work now. Please reopen if you are still experiencing the issue.

**Comment by bmcclenahan** [comment]
Ok to close.
It's not perfect but is quite usable.
It intermittently returns names and other words as locations.
Happy to close

Bruce
________________________________
