### ISSUE TITLE
WIT.ai app won't train or recognize intents

### ISSUE THREAD

**Issue by DFOchat** [wit-ai/wit#773]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
WIT.ai app won't train or recognize entities. Maybe my app needs a hard-reset.

**What is the App ID where you are experiencing this issue (if applicable)?**
https://wit.ai/DFOchat/DFOchatbot
59a7eda9-197d-440e-982d-c44a18fa86ab

**Comment by stopachka** [comment]
Hey @DFOchat 

What is an example sentence that is not recognized currently? 

(Tried `Jeg har brukt sykkel. Kan jeg få kmgodtgjørelse?` as an example, and it worked)

**Comment by stopachka** [comment]
(assuming all is well. Please reopen with an example if there is an issue)
