### ISSUE TITLE
Question: Training WIT using API on intent and entities

### ISSUE THREAD

**Issue by icemanTopGun** [wit-ai/wit#774]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question

**What is the current behavior?**
Just wondering in the WIT API tutorial - https://github.com/wit-ai/wit-api-only-tutorial - would it be possible to train entities via the API on top of the intent via CSV file? I only saw expressions with INTENT only.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by stopachka** [comment]
Hey @icemanTopGun -- Yes indeed. You can see some examples with entities here: 

https://wit.ai/docs/http/20170307#post--samples-link
