### ISSUE TITLE
engine NOT recognizing singular/plurals, verb tenses etc.

### ISSUE THREAD

**Issue by cognitivelutech** [wit-ai/wit#776]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
**question** for clarification for other languages: "italian"
**What is the current behavior?**
Distinction between singular and plurals seems not working without explicit validation
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Create an entity "category"
add value: "telecomando"
set entity as "freetext-keyword"
test your application with this sentence: "Ho un problema col telecomando" 
(which means I have a problem with my TV remote control)
Validate the example highlighting the "telecomando" word and then selecting the entity "category" with the value "telecomando"
**What is the expected behavior?**
I would expect that such sentence is used as reference.
If I test it again with same sentence BUT using the plural form "ho un problema con i telecomandi" it does not recognize anything, which is very strange. 
I would expect it recognizes as before. A basic stemming algorithm would match the two sentences.

Same issues apply when using tenses using the infinitive as reference.

For sure I misunderstood how to use it :(
Could you please help me pointing some clear resource in order better understand?

**What is the App ID where you are experiencing this issue (if applicable)?**

Thanks

**Comment by l5t** [comment]
Can you share you app id, we will investigate? cc @stopachka

**Comment by l5t** [comment]
Closing. @cognitivelutech please reopen with your app id so that we can look at it.
