### ISSUE TITLE
Feature request: timezone for Built-In NLP

### ISSUE THREAD

**Issue by bmcclenahan** [wit-ai/wit#777]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question/bug

**What is the current behavior?**
when I use built-in NLP with facebook messenger,  the timezone used seems to be the default setting for the wit app. It does not use the client timezone setting when interpreting datetime entities

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
I would expect that built-in NLP would use the timezone from the messenger client, so that datetime entities are correct for that client.

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by l5t** [comment]
very good feedback, thanks for posting. Let's investigate how and when we can add it.

**Comment by bmcclenahan** [comment]
Hi Laurent,

I'd be interested to hear if you're making any progress with this.

While you're considering it, could you think about how to incorporate other useful query parameters like "n" and "verbose" in the build-in NLP model.

Kind regards
Bruce
________________________________

**Comment by l5t** [comment]
Yes we are making progress and hope to release it in next month. Good idea also with the advance settings (n-best and verbose). We will try to include them as well.

**Comment by bmcclenahan** [comment]
Thanks for the update
I'm looking forward to it
Bruce

On 13 Oct 2017, at 3:01 am, Laurent Landowski <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes we are making progress and hope to release it in next month. Good idea also with the advance settings (n-best and verbose). We will try to include them as well.

**Comment by l5t** [comment]
Added https://wit.ai/blog/2017/11/07/messenger-built-in-nlp.

**Comment by bmcclenahan** [comment]
Thank you - I noticed that

Awesome work 👍

On 17 Nov 2017, at 3:07 am, Laurent Landowski <notifications@github.com<mailto:notifications@github.com>> wrote:


Added https://wit.ai/blog/2017/11/07/messenger-built-in-nlp<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwit.ai%2Fblog%2F2017%2F11%2F07%2Fmessenger-built-in-nlp&data=02%7C01%7Cbmcclenahan%40hotmail.com%7C9324ad52f07b412104f108d52d14949b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636464488764249632&sdata=%2F2HEONX74PGvhaPRz2TFIqKjrGX5nA7SMSTOEhWD7G4%3D&reserved=0>.

**Comment by bmcclenahan** [comment]
How exactly is the timezone meant to work.
I reset the timezone in my messenger client to UTC and confirmed it by querying the profile of my user.
when I entered "midnight"the NLP returned a datetime with value 2017-11-20T00:00:00.000+10:00
it got the midnight right but the +10 indicates it hasn't picked up the timezone of the user/client
+10 is the default timezone of my app
is there another setting to force the client timezone to override ?

**Comment by bmcclenahan** [comment]
Hi Laurent,

I was so excited to see this released, and then disappointed in finding it doesn't work as expected.

I reset the timezone in my messenger client to UTC and confirmed it by querying the profile of my user.
when I entered "midnight"the NLP returned a datetime with value 2017-11-20T00:00:00.000+10:00
it got the midnight right but the +10 indicates it hasn't picked up the timezone of the user/client
+10 is the default timezone of my app
is there another setting to force the client timezone to override ?

Thanks
Bruce
________________________________

**Comment by l5t** [comment]
cc @stopachka any idea? I thought we tested this

**Comment by stopachka** [comment]
Hey team, will look into this and update. There is a potential lag between timezone vs offset, that we'd need to fix up.

**Comment by stopachka** [comment]
Hey @bmcclenahan -- could you walk me through exactly how you set your timezone on messenger? (aiming to reproduce)

**Comment by bmcclenahan** [comment]
Hi Stepan,

I had a bit of trouble with this on my phone as there's no setting for it in the messenger App.

I ended up doing it on my windows PC - I set the timezone on the PC, then logged out of facebook in the browser and logged back in and used messenger from there. This was effective and even caused messages from my phone to then arrive in the new timezone.

I hope this helps.
Bruce

________________________________

**Comment by bmcclenahan** [comment]
Hi guys,

I set the timezone in facebook to UTC and waited 8 hours -  The messenger user profile API was reporting timezone as 0 and the NLP was showing +10 in datetime entities. I'm not sure if the +10 is coming from the wit App default, or my previous facebook timezone. I might try to check that next.

Bruce
________________________________

**Comment by stopachka** [comment]
Hey @bmcclenahan -- What is your app-id? (Can check for you where it is coming from)

---

re: Discrepancy between Timezone and Offset from the Profile API

What is happening is:
- We get the timezone of the user, which is dependent on *both* the offset, and the location info we know about the user. (For example, from their IP address history)
- This means that when you change the offset on your mac, the offset information will save right away, but the timezone information will stay in a limbo state, until it's more certain about where you are.

---

@bmcclenahan -- what would be the ideal wait time for your use case? I am looking into a few options:
 - The first is to keep this behavior, and wait until we are more certain
 - The second is to defer to the offset, when we are not sure about the location

**Comment by bmcclenahan** [comment]
Hi Stepan,

My app id is

58aecb8b-e2a7-46ff-8f5d-3a04e81575ac

the way you are doing the timezone is more thorough - however, it makes it quite difficult to test.

The reverse situation could occur when someone travels but fixes their phone in their home timezone. In this case the user is making a decision about the timezone they want to operate in, and the IP location could work against this by creating a limbo state .

For my case I would be happy with the simpler option of just using the offset.

If this offset comes to facebook from the setting on the user's device, it's easier to explain to the user, and easier to test. The addition of the IP location is good when it's confirming, but bad when it's in disagreement as it introduces confusion where perhaps none really exists.

Thanks for asking about this

Kind regards
Bruce


________________________________

**Comment by stopachka** [comment]
Cheers Bruce -- The problem with using only offsets are, that we lose the
information about which specific timezone the user is in.

There may seem like there is little difference, but consider if someone
says:
- 3 weeks from now at 2pm
- It is possible that within the next three weeks, their timezone will
undergo daylight savings, and that offset will no longer be correct

You are right though that this is quite hard to test, and the point about
specifically setting their timezone is also valid, and we'll need to make
sure these are addressed in the final solution

**Comment by stopachka** [comment]
Update: I tested by using a VPN, to log into Facebook from New York, with a New York Offset. The change in timezone in this case was instant. 

This means you can expect the timezone to match exactly where the users are coming from!

**Comment by bmcclenahan** [comment]
Thank you for confirming this - much appreciated !
Bruce
________________________________

**Comment by bmcclenahan** [comment]
Yes, that's a very specific use case, and you are correct that the simple offset might not return the correct result.
It's a shame Fb simplified it down to a number.

I look forward to your solution.
Thanks for listening
Bruce


PS: I'm not sure if this is the place, but there's an associated feature request -

would you consider reporting the timezone in the NLP object, possibly in the verbose option ?

While it's possible to infer the user's timezone from the datetime entity, there are situations when there us no datetime entity but the bot/app needs the timezone for its response :
eg
user: when is my next meeting
bot: you are meeting a client at 2pm on 3 Dec  <== would be helpful to format this according to the timezone of the user

thanks
Bruce

________________________________

**Comment by stopachka** [comment]
Cheers Bruce! The feature request is interesting! Will close this issue and explore this in a new thread
