### ISSUE TITLE
Response time is aprox 2 seconds for wit.message api

### ISSUE THREAD

**Issue by onkarjanwa** [wit-ai/wit#778]
**Looking for high performance of message api**

**What is the current behavior?**

When i run a query "gyms in jaipur" on our chatbot, it send us response in 3 seconds. And from this time approx 2 seconds has been taken by wit.message api.
`
Time tracking of client and server communication
- Clint - Frontend Send Message TIME :: 1505457903523
- Server - New Message Receive TIME :: 1505457903526 - 3 miliseconds
- Server - wit.message TIME :: 1505457905719 - 2200 miliseconds (approx 2 second)
- Server - Send Message TIME :: 1505457906299 -  0580 miliseconds
- Client - Frontend Receive Message TIME :: 1505457906307 - 8 miliseconds

`

**What is the expected behavior?** Wit.ai should send us response in 500 ms max.

**What is the App ID where you are experiencing this issue (if applicable)?**
588b1027-6be1-4ab0-818e-649c66abb958

**Comment by amuramoto** [comment]
Closing as duplicate and to add more context to https://github.com/wit-ai/wit/issues/762
