### ISSUE TITLE
Enhancement: clearer way of providing duckling entities in POST /sample

### ISSUE THREAD

**Issue by KaiFuhrmeister** [wit-ai/wit#779]
Hi,

it was easy to train samples by the http-API unless I tried to expect Monetary Amounts. I tried with 

{"entity" : "wit$amount_of_money", "value" : 10, "unit" : "EUR", "type" : "value"}

but then I always receive an error, that this item could not be parsed. If I remove this, everything works like a charm....

Regards
  Kai

**Comment by stopachka** [comment]
Hey @KaiFuhrmeister --

Good point here, we need to figure out what to do with duckling entities.

Currently, you do not actually need to train wit$amount_of_money. As it is completely backed by duckling -- github.com/facebookincubator/duckling

**Comment by KaiFuhrmeister** [comment]
Ok, good to know. Besides that: thanks for the great work you all did, was quite easy to get some remarkable results from your engine!

**Comment by patapizza** [comment]
Hey @KaiFuhrmeister,

Thanks for your kind words! Have you tried sending the body as value: `{"entity" : "wit$amount_of_money", "value" : "10 euros"}`?
