### ISSUE TITLE
Could not validate this expression when training Hebrew

### ISSUE THREAD

**Issue by lmessinger** [wit-ai/wit#780]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
BUG 
**What is the current behavior?**
Could not validate this expression when training an sentence in Hebrew

even when just using one intent for the sentence.

sentence is:

אני רוצה להעביר 680 שח לחשבון 132

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
i should 
**What is the App ID where you are experiencing this issue (if applicable)?**
59be60f6-fa25-471e-835e-4db911c0bb3f

**Comment by stopachka** [comment]
Thanks for reporting @lmessinger 

--- 

Wanted to confirm -- the sentence fails from the UI (i.e when typing it in /understanding)?

**Comment by l5t** [comment]
I was able to validate. Please reopen if you still experience the issue and provide steps to reproduce

![image](https://user-images.githubusercontent.com/6992759/31188400-9f0de308-a8e9-11e7-9857-603bcb03b477.png)
