### ISSUE TITLE
Difficulties to separate hours and minutes with punctuation

### ISSUE THREAD

**Issue by rianrajagede** [wit-ai/wit#783]
I want to ask a question

This is part of a bigger project using Indonesia language, So I can't create it using built-in function. I want to create a simple hours-minutes separator in many forms:
```
input: 19.45
output: 
time:hours = 19
time:minutes = 45
```
The input is sometimes separated with '.', ':', or just a whitespace. Wit.ai can find where is the time in the sentence. but it still gets difficult to separate into `hours` and `minutes`, even I've trained a lot of  times. But, this difficulty only happen when the separator between hours and minutes is not a whitespace. When the separator is a whitespace wit ai can exactly find which part of it is `hours` or `minutes`.

I've created the simple app to reproduce this behavior:
59c08fcd-94b7-4b1a-8907-0bde45cc4f15

is this a bug? or any solution to solve this?

**Comment by l5t** [comment]
Using ML models to learn this is probably not optimal. I would use a regex instead.

**Comment by rianrajagede** [comment]
Exactly, For now, for this development, we are using regex, wit.ai only detect where is the time, then we separate hours-minutes using regex

**Comment by l5t** [comment]
Ok closing then.
