### ISSUE TITLE
[Question] How to collect variables in stories of user and Bot ?

### ISSUE THREAD

**Issue by lamkent00** [wit-ai/wit#785]
Hi everyone,
I'm using node + Wit.AI + fb messenger to create chatbot.
Is there any example about make request from variables which collected from stories of user and chatbot ?
I mean this:
User: flight cost from var_A to var_B
BOT: when?
User: Tomorow (var_C)
BOT: how many people?
User: 1 adult (var_D)
==> collect var_A, var_B, var_C, var_D for request flight information.
Thanks so much :+1:

**Comment by l5t** [comment]
Duplicate. Closing
https://github.com/wit-ai/node-wit/issues/160#issuecomment-330977368
