### ISSUE TITLE
Inbox is empty (500 internal server error)

### ISSUE THREAD

**Issue by Alpha200** [wit-ai/wit#786]
The inbox of my app does not work anymore. It shows always that my inbox is empty, but I know that it can't be empty. As I see in the developer console of firefox, wit.ai responds always with a 500 Internal Server Error message while loading the inbox data.

App ID: 58c45ceb-7b33-4c28-8605-8f12b01939c4

**Comment by Krogsager** [comment]
Sounds like it is related to 
https://github.com/wit-ai/wit/issues/722

**Comment by stopachka** [comment]
Thanks for the id and the report Alpha200. Will look into this and update here with what I find

**Comment by stopachka** [comment]
Hey @Alpha200 the bug is identified. Working through a fix. Will update here when it hits prod

**Comment by stopachka** [comment]
Fix is live!

**Comment by gulbinas** [comment]
Have same problems with Inbox.

Chrome console gives:
```
GET https://api.wit.ai/inbox?limit=10 500 (Internal Server Error)
```

App ID:5a11f551-d02e-4fdf-a379-b35db88e2d74
