### ISSUE TITLE
Share Intents and Entities between apps

### ISSUE THREAD

**Issue by richwednesday** [wit-ai/wit#790]
I am building an app similar to my previous, how do I transfer some intents/entities from the previous app to this new one. Thank you.

**Comment by l5t** [comment]
You will have to use the HTTP API to transfer your intent/entities https://wit.ai/docs/http/20170307#get--entities-:entity-id-link or use the export/import. We may add a way to share intent/entities between apps but it won't be ready anytime soon.

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
