### ISSUE TITLE
The contact entity hasn't worked very well for a few days

### ISSUE THREAD

**Issue by bmcclenahan** [wit-ai/wit#791]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
wit doesn't identify contact entities in queries it used to 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
ask when is Steve on roster

**What is the expected behavior?**
identifies Steve as a contact

**What is the App ID where you are experiencing this issue (if applicable
brucemcclenahan/churchbot

**Comment by bmcclenahan** [comment]
contact is fully broken.
it never identify name entities.
this has crippled my app - please help

**Comment by stopachka** [comment]
Related to https://github.com/wit-ai/wit/issues/791 -- we recently introduced a new model, and though we backtested, looks like we introduced some errors. 

As we look into this, for a hotfix I suggest adding a custom_contact entity, that picks up all that wit/contact misses

**Comment by stopachka** [comment]
Update: tracking all the regressions on https://github.com/wit-ai/wit/issues/796

**Comment by bmcclenahan** [comment]
You're kidding me !
How long is this going to take to fix ?
You're asking me to introduce a new entity, train it, build it into my code, test it, and then wind it all out again ?
I'm looking at days

Can't you regress till you get it sorted ?
Bruce
________________________________
