### ISSUE TITLE
Join multiple same entity which separated

### ISSUE THREAD

**Issue by rianrajagede** [wit-ai/wit#792]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question

**What is the current behavior?**
Is it possible using wit to join multiple same entity which separated by another entity

Example (in English, but my project is using Indonesian language):
Go to work at 6.00 am with Danny

Entities
description = Go to work with Danny
time = 6.00 am

**Comment by stopachka** [comment]
Hey @rianrajagede 

Now that you have `description`, `time` entities, what would you like wit to do?

**Comment by l5t** [comment]
Unfortunately, you won't be able to have an entity that will have multiple spans at the moment. In your example, you can capture "Go to work" or "with danny" but not "go to work with Danny"
