### ISSUE TITLE
Training status: Ongoing

### ISSUE THREAD

**Issue by naman21** [wit-ai/wit#793]
My [bot](https://wit.ai/namankasliwal/botaromaV2) has been on training for a day now. Kindly resolve. How should I train to avoid happening of such an issue? 

Thanks

**Comment by l5t** [comment]
What's your app ID?

**Comment by naman21** [comment]
59c4cabc-40fd-491c-90e2-88428176974e

**Comment by naman21** [comment]
59c4cabc-40fd-491c-90e2-88428176974e

**Comment by l5t** [comment]
restarted. It should be better now
