### ISSUE TITLE
wit/on_off suddenly not working 

### ISSUE THREAD

**Issue by kentwait** [wit-ai/wit#794]
The wit/on_off entity suddenly isn't working for my app. It was working earlier today but now it can't detect it in the sentence - zero recall.

It doesnt even recognize simple messages like"on", "off", "turn on", "turn off".

Note that it was working just earlier today.

**Comment by stopachka** [comment]
Hey @kentwait -- if you could post more examples as well it would be helpful. A recent update to builtins has introduced some regressions. The more samples we have the better

**Comment by l5t** [comment]
Just tested and it seems to work. Please reopen if you still have an issue and provide steps to reproduce
