### ISSUE TITLE
[QUESTION] Entity's as tree?

### ISSUE THREAD

**Issue by NyphonMediaGroup** [wit-ai/wit#795]
Hey i is there a way to get entitys in a tree ?

Example: "Hey i'm Ted and i'm 21 years old."

it would be somthing like this:

person - "Ted"
└age - 21
intent - "greeting"

**Comment by l5t** [comment]
Unfortunately, we don't support this. We support composite entities (https://wit.ai/blog/2017/03/28/reintroducing-composite-entities) but that won't help in your situation.
