### ISSUE TITLE
POST speech "error" : "Something went wrong. We've been notified.",

### ISSUE THREAD

**Issue by basickarl** [wit-ai/wit#797]
I am aware of the node api module, however I'd like to use the request library to achieve this. I'm using the https://github.com/gillesdemey/node-record-lpcm16 to stream a wav to the request. As follows:
```
    record.start({
            recordProgram: 'sox',
        }).pipe(request.post({
                'url': 'https://api.wit.ai/speech?v=20170307',
                'headers': {
                    'Authorization': `Bearer ${witToken}`,
                    'Content-Type': 'audio/wav',
                }
            }, (error, response, body) => {
                if (error) {
                    throw error;
                }
                console.log(body);
            }));
```
I get the body:
```
{
  "error" : "Something went wrong. We've been notified.",
  "code" : "wit"
}
```
I've read the documentation: https://wit.ai/docs/http/20170307#post--speech-link

What am I missing?

**Comment by l5t** [comment]
It can happen for a lot of reasons (are you streaming a real wav). I suggest you look at these examples:
- https://www.npmjs.com/package/node-witai-speech 
-  https://github.com/wit-ai/DEPRECATED-node-wit

**Comment by blandinw** [comment]
I'm closing as this is not very actionable.
`Something went wrong` is not a good enough error message. If you still encounter the issue, please comment here with the precise timestamps (and your timezone) so that we can look deeper and either fix it, or make the error messages more useful.

**Comment by 488kuroi** [comment]
I have a similar issue, since few day, speech api is not working correctly anymore.
Giving a "400: Bad request", where earlier all was working correctly.
