### ISSUE TITLE
[api-bug] no clear way to set keyword-only entities through the api

### ISSUE THREAD

**Issue by gugulete** [wit-ai/wit#798]
I am using the web API to manage the bot entities. According to the documentation, the lookup strategy should not be specified when creating an entity. Posting to `/samples` sets the lookups to either ['trait'] or ['keywords', 'free-text'] depending on whether `start` and `end` properties are specified. Posting to `/entities/$ENTITY_ID/values` does not affect the lookups (it remains empty). How can I set the lookups to ['keywords'] only through the web API?

**Comment by stopachka** [comment]
Hey @gugulete 

**Short term workaround**

The `POST /entities` endpoint still secretly accepts lookups. You could create a keyword-only entity with the following curl:

```
curl -X POST \
  'https://api.wit.ai/entities?v=20170307' \
  -H 'authorization: Bearer $TOKEN' \
  -H 'content-type: application/json' \
  -d '{"id":"name_ex", "lookups": ["keywords"]}'
```

Longer-term, we need to think of a good DX, for supporting both the majority of use cases for users, and allowing devs to have more fine-grain control for lookups. We can use this task to track the improvement here

**Comment by jtliao** [comment]
You can now set the lookups to free-text, keywords, or free-text & keywords through the API. 

Something like this would work for your use case

`curl -XPUT 'https://api.wit.ai/entities/$ENTITY_ID?v=20170307' -H 'Authorization: Bearer $TOKEN' -H 'Content-Type: application/json' -d '{"lookups":["keywords"]}'`

See the docs for details: https://wit.ai/docs/http/20170307#put--entities-:entity-id-link
