### ISSUE TITLE
Reset/Clear inbox

### ISSUE THREAD

**Issue by icemanTopGun** [wit-ai/wit#799]
**Question about WIT**

**What is the current behavior?**
App stores incoming expressions into the Inbox. As a team, we have not been validating our inbox and has become bloated. Is there the ability to reset/clear the inbox via the interface?

**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**
ID: 59a5d230-7ba8-4479-a9f7-2d644f94a9e2

**Comment by l5t** [comment]
Thanks for asking. This is currently not available. The temporary workaround is to duplicate your app (export/import)

**Comment by Barbog** [comment]
These issues have been closed as "Not planned now"   and the comment 
`Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.`
