### ISSUE TITLE
The wit/number entity doesn't seem to know about 14/16/17/18/19

### ISSUE THREAD

**Issue by belzedaar** [wit-ai/wit#80]
I have an intent that captures wit/number. The issue is with numbers written
as text e.g. "fourteen".
"thirteen" works as expected. So does "fifteen". But "fourteen", "sixteen", 
"seventeen", "eighteen" and "nineteen" do not. "twenty" works, and so do
multi-word values like "twenty five"

Is this just because no-one has trained wit/number to deal with those values?
I assumed that the built in ones were a bit more hard-coded, to be able to 
deal with cases that nobody would ever train explicitly, like e.g
"two hundred and sixteen thousand and four"

It's not a big deal for me because I'm only dealing with a pretty small set
of numbers. I can make sure I only submit actual digits to wit.
But I still found it a bit odd.

**Comment by alxferraz** [comment]
Hi, i'm working on a project in portuguese. I'm trying to identify numbers above 100 written or said as text. Any chances of adding those too?

**Comment by l5t** [comment]
You can contribute here: https://github.com/facebookincubator/duckling

**Comment by alxferraz** [comment]
@l5t by contributing to duckling it will affect wit?

**Comment by l5t** [comment]
Indeed, we use Duckling internally at Wit and open sourced it to make sure the community could contribute and help improve it. When we accept your PR, it takes a few days to get to Wit

**Comment by alxferraz** [comment]
Done! thank you!
