### ISSUE TITLE
Error about retries to the api

### ISSUE THREAD

**Issue by pablodlm** [wit-ai/wit#800]
ConnectionError: HTTPSConnectionPool(host='api.wit.ai', port=443): Max retries exceeded with url: /message?q=que+hora+es (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f13eac9be90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

I am getting this error, anyone know how to avoid it?

**Comment by blandinw** [comment]
Are you still experiencing this error? It looks like you cannot connect to api.wit.ai, which is surprising.

**Comment by l5t** [comment]
Closing. Please reopen if you still experience the issue
