### ISSUE TITLE
Unable to create new app based on backup

### ISSUE THREAD

**Issue by ecrmnn** [wit-ai/wit#801]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
AJAX request timeouts after 2 minutes, so I never get redirected from "New app" page.
If I check my apps the app have been created but is missing half of the imported data and is not working correctly.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Visit ``https://wit.ai/apps/new``
2. Enter details including backup (Zip-file. My backup is ~26KB)
3. Click ``Create App``
4. AJAX request timeouts after 2 minutes

```
// General

Request URL:https://api.wit.ai/import?name=x&desc=x&lang=nb&private=false&login=xxxx
Request Method:POST
Status Code:504 Server timeout
Referrer Policy:origin-when-cross-origin

// Request headers
Accept:*/*
Accept-Encoding:gzip, deflate, br
Accept-Language:en-US,en;q=0.8,nb;q=0.6
Authorization:Bearer XXX
Cache-Control:no-cache
Connection:keep-alive
Content-Length:25792
Content-Type:application/zip
DNT:1
Host:api.wit.ai
Origin:https://wit.ai
Pragma:no-cache
Referer:https://wit.ai/
```

// Response
[https://jsfiddle.net/2tkt4z9L/](https://jsfiddle.net/2tkt4z9L/)

**What is the expected behavior?**
App should be created with correct data

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by Joinfield** [comment]
Same here in some cases. Maybe the import should run in background?

**Comment by bnsh** [comment]
I'm getting a "Bad Scope" when I try to create a new app from a backup that I downloaded from "Download .zip with your data".. Am I doing something wrong?

**Comment by stopachka** [comment]
Apologies for dropping the ball on this issue -- I am assuming this was intermittent and all is well. We have had new infra land on this, which should make this obsolete -- let us know if you still experience issues
