### ISSUE TITLE
how do i integrate stories and actions in my app dashboard?

### ISSUE THREAD

**Issue by nnahmed** [wit-ai/wit#803]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by nnahmed** [comment]
APP ID - 59c82291-07a9-40a2-ac10-95272955f1e1

**Comment by fredrick745** [comment]
i can't see the story icon on my wit.ai account?
can you help

**Comment by l5t** [comment]
We are deprecating Stories and will focus on the NLP API: https://wit.ai/blog/2017/07/27/sunsetting-stories
So I would suggest using /message + code on your side to manage the conversation/answer instead if you were thinking of using Stories

**Comment by nnahmed** [comment]
How do i go about this please?

**Comment by l5t** [comment]
You can look at this tutorial https://github.com/wit-ai/wit-api-only-tutorial#send-responses
