### ISSUE TITLE
Question: can't identify a simple date

### ISSUE THREAD

**Issue by henricazottes** [wit-ai/wit#804]
**What is the current behavior?**
When I send a simple date (in french) like "le 25 octobre" or even "25 octobre", WIT doesn't recognize it. I'm almost sure it was working two or three days ago but now I just can't make it recognize a date. However as soon as I specify the entity (by highlighting it) it gives me the correct answer. I use the context with {id: "datetime"} in my requests but same result.

Edit: I just test right now with "01/02/2017" and nothing is returned... It was working 30min ago. What is going on ? :'(

**What is the expected behavior?**
A simple date should be recognized ! :p

**What is the App ID where you are experiencing this issue (if applicable)?**
59d206d4-67ab-4384-85fd-b840d8ffd858

Thanks :)

**Comment by l5t** [comment]
Work for me. We are looking into it
![image](https://user-images.githubusercontent.com/6992759/31146883-e199723a-a83c-11e7-9f78-ac245370778b.png)

**Comment by henricazottes** [comment]
Here is a recording:

![](https://i11.servimg.com/u/f11/13/84/06/30/bug_wi10.gif)

Am I missing something ?

**Comment by l5t** [comment]
There seems to be an issue with your specific app. We are investigating and will report back. Thanks for your patience

**Comment by blandinw** [comment]
@henricazottes Your app was affected by a backend bug that we now fixed. We'll keep an eye out going forward. Apologies for the inconvenience!

**Comment by AdrienXL** [comment]
Hello, I'm having the same behaviour, also with french format :(
App id : 59d5e5df-7211-4bc5-91ab-4bc03daf212e
