### ISSUE TITLE
Bug: could not validate this expression

### ISSUE THREAD

**Issue by henricazottes** [wit-ai/wit#805]
**What is the current behavior?**
From time to time, I get the warning "Could not validate this expression" popup. I don't know why and I didn't identified any trigger for it.

**What is the expected behavior?**
Correctly validate the sentence

**What is the App ID where you are experiencing this issue (if applicable)?**
59d206d4-67ab-4384-85fd-b840d8ffd858

Thanks :p

**Comment by blandinw** [comment]
@henricazottes thanks for reporting this issue!
I looked at the logs and traced back the issue to a transient error with our dataset storage system. This is our current focus in terms of infra reliability so it should get better soon.

**Comment by henricazottes** [comment]
@blandinw I still have the "Could not validate this expression" sometimes :/

**Comment by justuseapen** [comment]
Yeah I am currently getting this as well. Any news on a fix?

**Comment by stopachka** [comment]
Hey @justuseapen -- this was once again a transient issue -- the main culprit is actively being migrated to more robust infra, that will handle FB scale
