### ISSUE TITLE
Can not identify "tonights" or "weekends" misspelling as a datetime.

### ISSUE THREAD

**Issue by iwilliams** [wit-ai/wit#806]
**What is the current behavior?**

Will not recognize the misspelling "tonights" of "tonight's" or "weekends" of "weekend's" as a datetime despite training. The misspellings "tomorrows", and "yesterdays" seems to work fine.

**What is the expected behavior?**

"tonights" and "weekends" would be recognized.

**What is the App ID where you are experiencing this issue (if applicable)?**

59cda2eb-cef0-4887-a514-68db26123c51

**Comment by l5t** [comment]
Thanks for reporting. Wit/datetime entity relies on Duckling, our open source linguistic parser: https://github.com/facebookincubator/duckling. I went ahead and made a [pull request](https://github.com/facebookincubator/duckling/pull/90) to change this but in the future don't hesitate to contribute there. It will take a few days to come to production.

**Comment by iwilliams** [comment]
Thanks!

**Comment by l5t** [comment]
Updated in production.
