### ISSUE TITLE
Cannot use HTTP API /samples endpoint - Something went wrong.

### ISSUE THREAD

**Issue by tommasnik** [wit-ai/wit#807]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
I am not able to use /samples HTTP API. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
In my application I've got entity intent. I'm trying to create a new value for it - "test-intent" with this request:
```
POST https://api.wit.ai/entities/intent/values?v=20170307 
{ method: 'POST',
  headers: 
   { Authorization: 'Bearer <TOKEN>',
     Accept: 'application/json',
     'Content-Type': 'application/json' },
  body: '{"value":"test-intent"}' 
}
```

I get correct response:
```
{"builtin":false,"doc":"User-defined entity","exotic":false,"id":"599ee1ab-a965-4355-a677-b63dcbde9bdd","lang":"cs","lookups":["trait"],"name":"intent"}
```

Then (after one second) I'm trying to add a new value for this intent:
```
POST https://api.wit.ai/samples?v=20170307 
{ method: 'POST',
  headers: 
   { Authorization: 'Bearer <TOKEN>',
     Accept: 'application/json',
     'Content-Type': 'application/json' },
  body: '[{"text":"test intent","entities":[{"entity":"intent","value":"test-intent"}]}]' 
}
```
But I'm getting HTTP 500 error:
```
{ error: 'Something went wrong. We\'ve been notified.',
    code: 'wit' 
}
```

**What is the App ID where you are experiencing this issue (if applicable)?**
599ee1aa-3c0c-4199-af8b-10700bfd32a7

**Comment by reizY10** [comment]
I'm having the same issue!

**Comment by blandinw** [comment]
@tommasnik @reizY10 
We had a temporary issue with our queueing system (which we're in the process of replacing for something more robust) which prevented your requests to be processed. The system is back online now.

We do apologize for the inconvenience. Feel free to reopen if the issue is not fixed!
