### ISSUE TITLE
Log in with Facebook button not working on the UI

### ISSUE THREAD

**Issue by yegeniy** [wit-ai/wit#812]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

*bug*

**What is the current behavior?**

Hi, not an urgent issue, but
For at least the last hour or so these endpoints have been giving me trouble:

https://wit.ai/bambots-dev
https://wit.ai/home

I've tested on Chrome (in regular and private browsing mode), Firefox, and Safari on OS X and Chrome on someone else's computer on (who's never been to the wit.ai site).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

The Log in with GitHub button works by showing a pop-up, but the Log in with Facebook does not currently do so.

![image](https://user-images.githubusercontent.com/292802/31301194-3d597594-aac6-11e7-8e7b-3b772cb92898.png)

**What is the expected behavior?**

Clicking on `Log in with Facebook` usually results in a popup which logs me in via Facebook
**What is the App ID where you are experiencing this issue (if applicable)?**
N/A

**Comment by l5t** [comment]
Sorry for the inconvenience and thanks for reporting. Apparently the issue just got fixed. Do you mind confirming?

**Comment by blandinw** [comment]
To be clear, this is an issue with FB Login, not Wit. It should be fixed now, or very soon.

**Comment by l5t** [comment]
Actually it may take up to 1 hour. Thanks for your patience

**Comment by yegeniy** [comment]
It's fixed. Thank you for the quick work, FB Login folks.
