### ISSUE TITLE
My training status stucked  

### ISSUE THREAD

**Issue by historylife** [wit-ai/wit#813]
Dear support. 

I want to create a gender guesser base on wit.ai, 
I uploaded more than 4000 labeled name to wit, Now , the training status still going forever 

here is my URL
https://wit.ai/basharalmasri/gender

How can I upload 1000,000 labeled name in one shot?

Regards

**Comment by l5t** [comment]
Thanks for contacting us. I just retrained your app but basically Wit is not the best tool to do first name gender detection based on our current machine learning stack. 
In addition, uploading 1M labeled name is not possible and won't provide good results. I assume you would also want to validate some names both as female or male (Alex for example) which is not possible currently

**Comment by historylife** [comment]
@l5t thank you for restarting , i think you have to add an option for this in panel , well after adding 3 new names , loading take some time.... 

but by testing 20 names which is not in the database i got 99% good results!
Well i will keep  feeding the bot ,via 
```

curl -XPOST "https://api.wit.ai/samples?v=20171009" \
  -H "Authorization: Bearer MEGHRGBR****************5G" \
  -H "Content-Type: application/json" \
  -d \'[{
        "text": "theName",
        "entities": [
          {
            "entity": "intent",
            "value": "Male"
          }
        ]
      }]\'
```
but can i include all names in this POST ?
