### ISSUE TITLE
Wit doesn't recognize dates

### ISSUE THREAD

**Issue by AdrienXL** [wit-ai/wit#815]
**What is the current behavior?**

I'm working with french terms. 
WIT doesn't recognize simple terms as "demain" (tomorrow) or "15 octobre".  When I highlight the problematic term and specify it as a date, wit somehow gives me the correct answer. 
If I retry the exact same sentence, wit will repeat its mistake. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

![wit](https://user-images.githubusercontent.com/6432047/31386977-072039f8-adc9-11e7-800d-575a28bcac29.gif)

(I didn't had the search_query intent active before, but the date detection was already problematic.)

**What is the expected behavior?**

"15 octobre" should be recognized has a date.

**What is the App ID where you are experiencing this issue (if applicable)?**

59d5e5df-7211-4bc5-91ab-4bc03daf212e

Thank you.

**Comment by patapizza** [comment]
Hi @AdrienXL,

It looks like `wit/search_query` is eager and takes over `wit/datetime`. Do you need `wit/search_query`? I see that you're saying that before adding `wit/search_query` it was already problematic. Can you try to remove `wit/search_query` and provide us with examples that don't work?

Thanks!

**Comment by AdrienXL** [comment]
Hello, 

I removed `wit/search_query` and did a couple of new examples :
 
![wit-example](https://user-images.githubusercontent.com/6432047/31459588-e5768fa4-aec3-11e7-8a2c-c351a0996c28.gif)

![wit-example2](https://user-images.githubusercontent.com/6432047/31459589-e596a8de-aec3-11e7-9a1d-bf43281e4e8e.gif)

Before posting, I did some research and found [this closed issue](https://github.com/wit-ai/wit/issues/804) reporting the same behaviour. 

Thank.

**Comment by AdrienXL** [comment]
Hello,

I think my issue is gone. 
I don't know If you've done something but I did :
I first created a new app with the same settings to see if `wit/datetime` works correctl -> it does.
After destroying that new app I changed the language of my faulty app to english, waited for the green light and then switched back to french. After that, no more issue with `wit/datetime` !

**Comment by blandinw** [comment]
@AdrienXL thanks for the report. You were indeed affected by the same bug as #804.
Glad to hear it is now working, please let us know if we can help further.
