### ISSUE TITLE
Wit is not recognizing expressions correctly.

### ISSUE THREAD

**Issue by mehfuzh** [wit-ai/wit#816]
I've created the following intents:

<img width="958" alt="screen shot 2017-09-28 at 3 25 31 pm" src="https://user-images.githubusercontent.com/141204/31394119-5fd80cb0-ad92-11e7-82cb-7141e5767333.png">

Testing it from samples:

<img width="1031" alt="screen shot 2017-09-28 at 3 26 21 pm" src="https://user-images.githubusercontent.com/141204/31394160-7e379932-ad92-11e7-96c3-9369d12f7d78.png">

I am adding a new expression here ("about"):

<img width="966" alt="screen shot 2017-09-28 at 3 27 37 pm" src="https://user-images.githubusercontent.com/141204/31394252-be9708c8-ad92-11e7-865a-17a75a4405d4.png">

"About"

![image004](https://user-images.githubusercontent.com/141204/31405455-ef1552f4-adb3-11e7-8180-5c25f9a1fbb9.png)

"Beer"

![image005](https://user-images.githubusercontent.com/141204/31405507-f64f3bac-adb3-11e7-82ef-bf21adf7000b.png)

It should not resolve as "about"

**Comment by l5t** [comment]
What's the confidence here? Wit will try in the console to suggest one trait based on your validated expressions. If you only have a few, Wit will have a hard time to suggest the right one

**Comment by mehfuzh** [comment]
Hi Laurent,
Just checked it again using the wit API and working. However, I found this:

https://api.wit.ai/message?v=20170416&q=How+are+you?

```
{
  "msg_id": "0N5VaMr86R9oDumpe",
  "_text": "How are you?",
  "entities": {
    "intent": [
      {
        "confidence": 0.53117540729963,
        "value": "menu"
      }
    ]
  }
}

```
https://api.wit.ai/entities/intent?v=20170307

```
{
  "builtin": false,
  "doc": "User-defined entity",
  "exotic": false,
  "id": "59cb4b77-352c-490d-9e0d-03fc0ea3da75",
  "lang": "en",
  "lookups": [
    "trait"
  ],
  "name": "intent",
  "values": [
    {
      "value": "menu",
      "expressions": [
        "hello",
        "hi",
        "menu",
        "Show me menu"
      ]
    },
    {
      "value": "default",
      "expressions": []
    },
    {
      "value": "start",
      "expressions": []
    },
    {
      "value": "about",
      "expressions": [
        "about"
      ]
    }
  ]
}

```
Thanks!

**Comment by patapizza** [comment]
Hi @mehfuzh,

The confidence level for `menu` on "How are you?" is 0.5312, which is pretty low. To improve your app quality, I would suggest to validate more examples for each category, and set a confidence level under which your app would ignore the entities (e.g. 0.85).

Feel free to reopen if you experience further issues after providing more examples.
