### ISSUE TITLE
Wit did not update my "entities"

### ISSUE THREAD

**Issue by historylife** [wit-ai/wit#817]
i am sending some "entities" via
my url : https://wit.ai/basharalmasri/gender/entities

```

curl-XPOST"https://api.wit.ai/samples?v=0000000"-H"Authorization: Bearer MEGHRGBROXIY2HGHGFGHHJJ4M5ADHJ5G"-H"Content-Type: application/json"-d'[{
	"text": "Aabbee",
	"entities": [{
		"entity": "intent",
		"value": "female"
	}]
},
{
	"text": "jswwweqw",
	"entities": [{
		"entity": "intent",
		"value": "female"
	}]
},
{
	"text": "Aada",
	"entities": [{
		"entity": "intent",
		"value": "female"
	}]
},
{
	"text": "Aadam",
	"entities": [{
		"entity": "intent",
		"value": "male"
	}]
},
{
	"text": "Aaden",
	"entities": [{
		"entity": "intent",
		"value": "male"
	}]
},
{
	"text": "Aadhya",
	"entities": [{
		"entity": "intent",
		"value": "female"
	}]
},
{
	"text": "Aahil",
	"entities": [{
		"entity": "intent",
		"value": "male"
	}]
},
{
	"text": "Aahliyah",
	"entities": [{
		"entity": "intent",
		"value": "female"
	}]
},
{
	"text": "Aahron",
	"entities": [{
		"entity": "intent",
		"value": "male"
	}]
},
{
	"text": "Aailiyah",
	"entities": [{
		"entity": "intent",
		"value": "female"
	}]
}]'
```

Wit Return 
```

{
	"sent": true,
	"n": 10
}r
```

But when i reviewed the  "entities" i can not find this set !
i have a lot to send in order to make the bot learned  more and more names ...

it seems you need to restart something :)

**Comment by rizkiaditya24** [comment]
I have the same problem when I use API to validate the sentence into entity name and value, on the dashboard, the entity and value won't update, but when I try to validate thru wit dashboard, it updated

**Comment by l5t** [comment]
We had some issues with /samples, do you mind trying again?

**Comment by historylife** [comment]
Dear @I5t
I have this replay form one of your team :
__________________________________________________
Hello,
We had to block your app since your /samples requests were impacting the community (https://github.com/wit-ai/wit/issues/817). If you stop sending /samples, we can unblock you app.
Thanks for your understanding
__________________________________________________

Well ,  i am not spammer, i am sending learning samples, which is the main fundamental aspect of the AI, how can i make the app work better, now if you see the success rate, you will understand that it is working..

How you present this project as an AI which based on learning sample, and you block me from sending learning samples.

I am not a sure how AI should works if you block the main function..

**Comment by blandinw** [comment]
@historylife Please don't forget that this is a community of developers built around a free service and an interest for NLU. We work hard to make this community pleasant for everyone and we ask people to have a positive attitude and assume good intent.

We contacted you because we detected abnormal activity from your account. Even though we're working on highly scalable dataset storage, we can't have all our users upload 1M samples at the moment.

We also contacted you to try and understand what you're working on and how we can help, or give (free) advice on a better solution (since we're also NLU engineers 😇). If you insist on using Wit to do a simple male/female classification, we simply ask that you don't upload more data than you need (1M seems overkill) and at a slower rate than you did.

You could also try other AI services since you already have a dataset of 1M validated samples, they may work better for you.

Thanks for your understanding!

**Comment by historylife** [comment]
Dear @blandinw ,

First of all , your replay is a wonderful , Thank you form all my heart.
When i got the email i got the feeling that i am a bad dev, and a SPAMER , which is the most thing i heat on the all world. and i got frenzy ,and angry since there is  no documentation about (Please Slow Down).

And Even more , i got blocked without any note. Which make me VERY SAD. But now all is understandable.

Well , I will not use any other AI service , facebook made such AI GOD , which is some thing even google TensorFlow can not match it (not even close) , I love facebook , it is home for me , and when owner of this home ask me to slow down , i have nothing but say as you wish , and with love.

We are a big team , friends , and family here in this community. and i do respect your free service.

Now please can you guide  me to  such documentation which i can know what is my limitation.
Regarding 1m , i will not upload it any more , or i will upload  50k each day (is it good or do you have any advice) .

And please note that we are building some crawler , this program will ask for  gender very often , is there any limitation (not learning just send the name to api and get back the json  ).

Thank you in advanced and i am very sorry for the misunderstanding.
Yours
