### ISSUE TITLE
Understanding doesn't work for new entities

### ISSUE THREAD

**Issue by hristoborisov** [wit-ai/wit#818]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug

**What is the current behavior?**
An entity is being trained over the API with a set of expressions, and the NLP engine doesn't recognize it at all.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Train an entity with a set of expressions using your latest API.
2. Open the trained entity and the set of expressions. There are many duplications, most probably related to #743 
![wit](https://user-images.githubusercontent.com/29565898/31438694-d936a008-ae91-11e7-8894-800408c43f19.png)
3. Go to the Understanding tab, and provide an expression.
4. Wit.ai doesn't recognize it. The same is happening if we try the understanding using the latest API.
![wit2](https://user-images.githubusercontent.com/29565898/31438702-e537a1ae-ae91-11e7-9c48-cb0a788bbb1b.png)

**What is the expected behavior?**
The entity should be recognized with some confidence.

**What is the App ID where you are experiencing this issue (if applicable)?**
59ddc7f4-4421-4085-99cf-e1f0ca120fae

It's very disturbing to experience a regression in such core functionality of Wit.ai product.

**Comment by patapizza** [comment]
Thanks for reporting @hristoborisov.

The issue might be related to the duplicates. We're working on a fix.

**Comment by patapizza** [comment]
@hristoborisov I manually removed the duplicates pending the fix and retrained your instance.

![](https://i.imgur.com/FZjHHtv.png)

Feel free to reopen should you experience any more issues.
