### ISSUE TITLE
Yes and NO are recognised as "Wit/Location"

### ISSUE THREAD

**Issue by omidai** [wit-ai/wit#819]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
*bug*
**What is the current behavior?**
"Yes" and "No" are recognised as "Wit/Location" while they must be recognised as only "yes_no" ( a user-defined entity with trait lookup strategy). )

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
An Screenshot has been attached to this post.
![screen shot 2017-10-10 at 12 59 20](https://user-images.githubusercontent.com/11214991/31385400-08016b02-adbb-11e7-8135-f08578010905.png
**What is the expected behavior?**
Yes and No must be recognised as only "yes_no" ( a user-defined entity with trait lookup strategy). 
**What is the App ID where you are experiencing this issue (if applicable)?**
586a809b-e283-4a30-9862-7edcbeeb9b2f

**Comment by omidai** [comment]
@patapizza Hi, could you please update me regarding this bug. Thanks.

**Comment by patapizza** [comment]
Thanks for reporting @omidai, I'm working on it.

**Comment by patapizza** [comment]
This should be fixed now.
