### ISSUE TITLE
wit/contact keeps recognize me/you words a wit/contact (Update: even on 'list' word. it gets weirder)

### ISSUE THREAD

**Issue by Orisbaum** [wit-ai/wit#820]
Hey,
**Do you want to request a feature, report a bug, or ask a question about wit?**
bug

**What is the current behavior?**
wit's algorithm recognize 'me' / 'you /  'list' as wit/contact entities.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
for example:
{
    "msg_id": "0WTNPcCZjbSINBHbn",
    **"_text": "speakers list please",**
    "entities": {
        **"contact": [
            {
                "suggested": true,
                "confidence": 0.93217,
                "value": "list",
                "type": "value"
            }**
        ],
        "intent": [
            {
                "metadata": "SNTC_speakers",
                "confidence": 0.99662045695308,
                "value": "speakers"
            }
        ]
    }
}

{
    "msg_id": "0n52Y8A9UmBv6lYxU",
    "_text": "can you tell me something about this university?",
    "entities": {
        "contact": [
            {
                "suggested": true,
                "confidence": 0.91122,
                "value": "me",
                "type": "value"
            }
        ]
    }
}

**OR**
{
    "msg_id": "02eJ0eJ9cXSMpaQCw",
    "_text": "how are you?",
    "entities": {
        "contact": [
            {
                "suggested": true,
                "confidence": 0.93786,
                "value": "you",
                "type": "value"
            }
        ],
        "intent": [
            {
                "metadata": "SNTC_whatsup",
                "confidence": 0.88360927054689,
                "value": "whatsup"
            }
        ]
    }
}

from my understanding this is an unexpected behavior.

**What is the App ID where you are experiencing this issue (if applicable)?**
app id : 597df042-d9da-4ef0-9c7e-5175ac15c6fc

**Comment by l5t** [comment]
Seems that wit/contact is to greedy. While we look at it, if you don't need it, you can remove it or if you need it, build your own custom 'contact' entity

**Comment by patapizza** [comment]
This should be fixed now.
