### ISSUE TITLE
**What have happened wit stories, I can't configure app response.  I would like to know where can I configure the agent response? help me please**

### ISSUE THREAD

**Issue by KathyLiz** [wit-ai/wit#821]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by l5t** [comment]
Not sure you saw our update but we are deprecating Stories and will focus on the NLP API: https://wit.ai/blog/2017/07/27/sunsetting-stories
So I would suggest using /message + code on your side to manage the conversation/answer instead if you were to use Stories. Tutorial here:
https://github.com/wit-ai/wit-stories-migration-tutorial
