### ISSUE TITLE
Feature request: GET /apps

### ISSUE THREAD

**Issue by vctrferreira** [wit-ai/wit#823]
*feature*

**What is the current behavior?**
So I tried find in your documentation any way to get list of my current applications (with tokens to get dynamic bots based in my application), I believe that will be a great feature to implement.

**What is the expected behavior?**
the expected behavior for me is a get method to list all my applications and your releted's tokens to use.

**Comment by l5t** [comment]
@comloo just launched it! https://wit.ai/docs/http/20170307#get--apps-link
