### ISSUE TITLE
Daylight savings issue with wit/datetime

### ISSUE THREAD

**Issue by Boyko-Karadzhov** [wit-ai/wit#824]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
The application is in the default timezone - `America/Los_Angeles`. Message `15th November 2017` has wit/datetime entity with value `2017-11-15T00:00:00.000-07:00`.

`2017-11-15T00:00:00.000-07:00` converted to `America/Los_Angeles` is `2017-11-14T23:00:00.000-08:00`.

Currently, the application behaves as it is in "Etc/GMT+7". `utcNow` as `currentReftime` provides a constant offset.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Create an application with a `wit/datetime` entity. It is an English application in America/Los_Angeles timezone
1. While you are in daylight saving, message the application with the following text `15th November 2017` (if you are already in winter time you can probably ask for a summer day to get a similar issue)

```bash
 curl -XGET 'https://api.wit.ai/message?v=20170307&q=15th%20November%202017' \
      -H 'Authorization: Bearer xxxxxx'
```

3. Result:
```
"entities":{"datetime":[{"confidence":0.96853833333333,"values":[{"value":"2017-11-15T00:00:00.000-07:00","grain":"day","type":"value"}],"value":"2017-11-15T00:00:00.000-07:00","grain":"day","type":"value"}]}
```

**What is the expected behavior?**
The returned value should be in the application's timezone. In this case, the expected value is `2017-11-15T00:00:00.000-08:00`.

The returned value should stay the same when presented in the timezone of the application.

**What is the App ID where you are experiencing this issue (if applicable)?**
59e4c649-8e9d-4a35-aeb3-8ab47d20ff0d

**Comment by patapizza** [comment]
Thanks for reporting @Boyko-Karadzhov, I'll look into it.

**Comment by patapizza** [comment]
This should be fixed now.
