### ISSUE TITLE
Bug- unable to upload a .zip when making a new app

### ISSUE THREAD

**Issue by JFCCoding12** [wit-ai/wit#825]
I am trying to upload an old backup but its not uploading, it says it failed but when I reload its there but none of my commands are working

**Comment by blandinw** [comment]
Please explain the issue better and provide reproduction steps.
If you do not want to share the backup file, please send it by email at help@wit.ai referencing this GitHub issue.

Closing for now, will reopen with more info

**Comment by JFCCoding12** [comment]
[This is the zip file](https://github.com/HackerHouseYT/AI-Smart-Mirror/blob/master/models/wit_training_data.zip)

**Comment by blandinw** [comment]
@JFCCoding12 I'll push a fix tomorrow night and you can tell me if it works better
