### ISSUE TITLE
Unable to update value using POST /samples

### ISSUE THREAD

**Issue by rizkiaditya24** [wit-ai/wit#826]
I have an issue when validating a sentence using POST /samples with given text, entity, and value, the value doesn't update at all. But, when I try to validate using WIT console, the value is updated.

Here's the steps I do:

1. After I create new app, then I create new entity with this API
```
curl -X POST \
  'https://api.wit.ai/entities?v=20170307' \
  -H 'authorization: Bearer API_KEY' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -d '{
    "id":"how_to",
    "doc": "how to related operation"
}'
```
It returns 200 OK with JSON Response

2. Then I try to create value using this API
```
curl -X POST \
  'https://api.wit.ai/samples?v=20170307' \
  -H 'authorization: Bearer API_KEY' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -d '[{
    "text": "order gimana",
    "entities": [
    	{
        	"entity": "how_to",
            "value": "order"
    	}
    ]
}]'
```
It returns 200 OK, but when I check into wit console, seems the value of that entity doesn't update at all.

3. I try to validate manually from wit console, it works just fine.

Did I miss something here?

**Comment by l5t** [comment]
Thanks for reporting, we do experience some lagging in the training via /samples and are investigating

**Comment by l5t** [comment]
We fixed the issue. It should be back to normal now. Sorry for the inconvenience.
