### ISSUE TITLE
Address being identified as phone number

### ISSUE THREAD

**Issue by michaelulin** [wit-ai/wit#828]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
The address 989 45th street oakland ca is being classified as a phone number, not a location. I've manually highlighted this and classified it as an expression in the Wit.AI platform, but it is still being classified as a phone number.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Should be classified as a location.
**What is the App ID where you are experiencing this issue (if applicable)?**
59dbb6a6-5341-4dfe-88c7-a5c1b47a730c
![image](https://user-images.githubusercontent.com/4452086/31797528-89cf5818-b4e3-11e7-98a6-689a603df1b8.png)

**Comment by patapizza** [comment]
I've just tried in your app and it seems working:

![](https://i.imgur.com/PeCJugO.png)

Feel free to reopen if you still experience the issue.

**Comment by michaelulin** [comment]
It's still being classified as a phone number:
[
  {
    "confidence": null,
    "intent": "default_intent",
    "_text": "989 45th st oakland ca",
    "entities": {
      "phone_number": [
        {
          "confidence": 0.9577825,
          "value": "989 45"
        }
      ]
    }
  }
]

![image](https://user-images.githubusercontent.com/4452086/31798285-9e273a52-b4e7-11e7-8f87-a6e98669293f.png)

**Comment by michaelulin** [comment]
![image](https://user-images.githubusercontent.com/4452086/31798381-3849a5e8-b4e8-11e7-8c0e-50d1dcae6f9a.png)

**Comment by michaelulin** [comment]
It works now. Thanks!
