### ISSUE TITLE
Correct intent but very low confidence

### ISSUE THREAD

**Issue by theslickmd** [wit-ai/wit#83]
Hi All

I'm working on code that retrieves winning lottery results from the internet.

Info needed from the user is the draw number, number of rows played and the six numbers played on the first row.

I created an intent called "getLottoResults" which is spanless and is used to trigger the code.

The code prompts the user to input the draw number. The app is set into state "lottoDrawNumber" and Wit is called with this state as context.

Created intent called "inputLottoDrawNumber" with state "lottoDrawNumber" and entity "wit/number" to catch the 4 digit number.

This is returned to my app as expected.

Once the code receives the above info, it prompts the user for the number of rows played. State = "lottoRows".

Created intent called "inputLottoRows" with above state and entity = "wit/number" to catch the number of rows.

Wit matches the correct intent but gives a very low conf score of below 0.3 and my app has a threshold of around > 0.4 upwards.

intents (with states) capturing numbers on expressions that just contains numbers are not matched correctly and if they are, they are scored well below 0.3.

the draw number will always be 4 digits...the row number will be max 2 digits (1 - 99) and the lotto numbers will always be max 2 digits (1 - 49). Is it possible to somehow include this in my entity so Wit can match and score the intent more accurately?

I currently have to include words in my expression for the intent (with state) matching to work, eg. for the rows the expression "1 row" or "2 rows" instead of just "1" or "2" and for the lotto numbers "number 1" or "number 49 (expressed as "number 4 9")"
or is there another way I should do this?

tnx

**Comment by Glavin001** [comment]
I am consistently getting worryingly low confidence scores:

```
Glavin Wiechert: hey
confidence 1
Executing merge action
confidence 0.04232921962320499
Executing say with message: Hi Glavin Wiechert.
confidence 0.01264675426361282
Executing action: say-intro
confidence 0.0058284885245586315
Glavin Wiechert: hey!
confidence 1
Executing merge action
confidence 0.002570578475971742
Executing say with message: Hi Glavin Wiechert.
confidence 0.0018192726200667265
Executing action: say-intro
confidence 0.0013933801190890705
Glavin Wiechert: find javascript articles
confidence 1
Executing merge action
confidence 0.0009691486221019784
Executing say with message: Let me see what I can find about javascript...
confidence 0.0008491867029277942
Executing action: find-articles
confidence 0.0009449970521124507
Executing say with message: Alright, I'm back.
confidence 0.0008323156500700088
Executing action: say-articles
confidence 0.0008548454283247143
```

Is this to be expected with the new Bot Engine?
