### ISSUE TITLE
PUT a bulk list of Keywords to a Entity

### ISSUE THREAD

**Issue by grinono** [wit-ai/wit#830]
When i push a list of keyword to a entity via the API. These words are not recognized when testing strings with these words. Why is that?

**Comment by patapizza** [comment]
Hi @grinono,

Please use the provided template. What is your app id? Do you have an example of a sentence that doesn't work, along with the expected output?

Thanks.

**Comment by grinono** [comment]
app ID is 59d39849-884d-4840-aad9-ca4e4221110b
entity is > productCategory there is a list of 100 items, non are at default accepted/recognized.

**Comment by stopachka** [comment]
Hey @grinono -- thanks for the info, looking into it. May be related to https://github.com/wit-ai/wit/issues/811

**Comment by patapizza** [comment]
@grinono I repaired your app. Will track internally to fix the root cause.

![](https://i.imgur.com/JZonhGX.png)
