### ISSUE TITLE
An expression against multiple entities (traits) using http API

### ISSUE THREAD

**Issue by noumanbsc125** [wit-ai/wit#831]
Hi,
 I am not a able to add an expression against multiple entities of same lookup strategy "trait" through http API,  or is there any other way to do it by using http API. ?  it works fine with wit console.

Thanks

**Comment by patapizza** [comment]
Hi @noumanbsc125,

What is your app id? Can you provide an example of a request that didn't work?

Thanks.

**Comment by noumanbsc125** [comment]
Hi @patapizza,
App ID = 59c8bb52-df69-44a5-9a66-e3e56111cd4d

 let me give of an example, like i have created two entities "Test1" and "Test2" , with a trait values test1 and test2 respectively, now when i try to add an expression "Hi" for both entities through http api, wit keeps the value of last entry and remove the expression from the first entity vice versa. hopefully you will get my point.

Thanks

**Comment by patapizza** [comment]
Hi @noumanbsc125,

Thanks for the additional info. Can you share the request you're making to add an expression `Hi` to both entities?

**Comment by noumanbsc125** [comment]
@patapizza  Thanks, below are my requests through http API.

curl --request POST \
  --url 'https://api.wit.ai/entities/test_1/values?v=20171026' \
  --header 'authorization: Bearer 2VSGIIC............................5XC' \
  --header 'content-type: application/json' \
  --data '{
  "value":"test1",
    "expressions":["HI"],
     "metadata":"greetings"
  
}'


curl --request POST \
  --url 'https://api.wit.ai/entities/test_2/values?v=20171026' \
  --header 'authorization: Bearer 2VSGIIC............................5XC' \
  --header 'content-type: application/json' \
  --data '{
  "value":"test2",
    "expressions":["HI"],
     "metadata":"greetings"
  
}'

**Comment by patapizza** [comment]
> This only applies to keyword entities. For trait or free-text entities, use POST /samples

As the HTTP docs read, please use `Post /samples` for trait entities.
Feel free to reopen if that doesn't work.

**Comment by noumanbsc125** [comment]
Thanks a lot @patapizza , i was looking in a wrong direction.
