### ISSUE TITLE
Could not validate this expression

### ISSUE THREAD

**Issue by NicholasIoanJones** [wit-ai/wit#833]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
*bug*

**What is the current behavior?**
"Could not validate this expression" reported trying to execute the example 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

![image](https://user-images.githubusercontent.com/13794355/31964050-601f8054-b8c8-11e7-90a3-5967caad7d35.png)

**What is the expected behavior?**
It should work

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by NicholasIoanJones** [comment]
Cleared this error by refreshing the page, though that's not acceptable. Pretty much none of the buttons/functions actually do what they are meant to and everything is ridiculously slow.

**Comment by stopachka** [comment]
Hey @NicholasIoanJones -- are you able to consistently repro this, could you go in a bit deeper on what is ridiculously slow and how? 

Happy to help, but need more info

**Comment by NicholasIoanJones** [comment]
OK 

 

So the original problem of “Could not validate this expression” was cleared by refreshing the screen. Obviously this is not an acceptable situation.

 

After that, nothing much seemed to do anything. I could not add a new app or delete this app. If I typed in a new phrase nothing happened or sometimes there was a response after 30-40 seconds

 

I’ve worked in IT for 33 years (dev, design, architecture) and this was just broke. I’ve not tried today

**Comment by patapizza** [comment]
Hi @NicholasIoanJones,

Are you still unable to create a new app, delete an app? Does the website still feel slow to you?

**Comment by NicholasIoanJones** [comment]
I’ve just been able to add a new app. I need to try it out properly when I’m back in the office later

**Comment by patapizza** [comment]
Ok, closing for now. Please reopen if you still experience any issue.

**Comment by Prasengupta** [comment]
Guys, I'm facing this issue again. Could anyone have some solution for this?

**Comment by blandinw** [comment]
@Prasengupta please open a new issue explaining and follow the provided template to report an issue (app id, repro steps, etc.)
