### ISSUE TITLE
Expressions Inbox Empty?

### ISSUE THREAD

**Issue by montylounge** [wit-ai/wit#835]
Reporting a possible bug.

Our expressions inbox is empty, although we previously had a queue of messages.

We expected to see previous inbox messages and messages from the last 24 hours of usage.

Any thoughts on what would cause this?

App_ID: broadway-concierge-2

**Comment by stopachka** [comment]
Thanks for reporting @montylounge -- It indeed looks suspicious -- looking into it.

**Comment by patapizza** [comment]
Hey @montylounge, I can see some samples in your inbox - probably a transient issue.

![](https://i.imgur.com/UoVHTKo.png)

**Comment by montylounge** [comment]
Thanks @patapizza
