### ISSUE TITLE
Entity Keyword - Synonyms not adding?

### ISSUE THREAD

**Issue by montylounge** [wit-ai/wit#836]
Report a *bug*.

I am unable to add a keyword synonym for one specific entity.

I can replicate this consistently.

For other entities it appears to be working, so it seems it's specific to this one entity.

Expectation? When adding a keyword synonym the new synonym appears in the UI and is saved correctly.

AppID: broadway-concierge-2
Entity: support_type

I checked the console and saw no exceptions raised. It appears to fail silently.

**Comment by stopachka** [comment]
Hey @montylounge -- this is because the strategy for the entity was "free-text" only -- updated it to free-text + keywords, to make synonyms work

**Comment by montylounge** [comment]
Thank you @stopachka
