### ISSUE TITLE
Expression can't be deleted from entity/value

### ISSUE THREAD

**Issue by rizkiaditya24** [wit-ai/wit#837]
Hi Guys, 

when bot extract wrong meaning from a sentence, how to delete it so when I get meaning again, it won't extract the same wrong meaning again? 

I've tried to use:
```
DELETE https://api.wit.ai/…/$ENTITY_…/expressions/$EXPRESSION_VALUE
```

But Bot still returns the same wrong meaning. My expectation when using that API (because it said "Remove an expression from an entity"), I can delete the pairs of expression and entity/value, then I can set new entity/value for that expression, so that when I get the meaning again, it doesn't return wrong entity/value again. Is it possible?

**Comment by patapizza** [comment]
Hey @rizkiaditya24,

> Delete an expression of the canonical value of the entity.

This API removes a synonym for a `keywords` entity. It doesn't remove the value associated with this synonym. Use `DELETE https://api.wit.ai/entities/$ENTITY_ID/values/$ENTITY_VALUE` instead.

Hope this helps.
