### ISSUE TITLE
CORS speech Need result

### ISSUE THREAD

**Issue by ZvirUSka** [wit-ai/wit#838]
POST https://api.wit.ai/speech
How can I get the result with no help from CORS. 
`$.ajax({
				  url: 'https://api.wit.ai/speech?v=20170307',
				  data: {
					blob,
					'access_token' : ''
				  },
				  dataType: 'jsonp',
				  method: 'GET',
				  success: function(response) {
					  console.log("success!", response);
				  }
				});`

**Comment by stopachka** [comment]
POST /speech now supports CORS!
