### ISSUE TITLE
Entities with specific ranges

### ISSUE THREAD

**Issue by theslickmd** [wit-ai/wit#84]
Hi

Good job so far guys. New site looks good.

Is it possible to create an entity with a numeric range?
I have an entity "Age" with state "inputAge" and I want this entity to be activated only when the request contains the state "inputAge" and the expression contains a value from 1 to 49.

I find that for the "Age" intent I have to manually add the above range as expressions, one by one, to produce a perfect match.

tnx.

**Comment by martinraison** [comment]
Hi, apologies for the late reply and lack of updates. As of today we still don't offer a way to add those kind of constraints to custom entities, but things like range could be useful. Adding it to the roadmap.

**Comment by patapizza** [comment]
* States are part of legacy apps.
* `wit/age_of_person` could help for this, or `wit/number` with a post-filtering on the value.
