### ISSUE TITLE
multiple locations in a message

### ISSUE THREAD

**Issue by nikhilpal** [wit-ai/wit#840]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
*question*

**What is the current behavior?**
book my flight from Sydney to Delhi on the 10th Dec, this returns Sydney as a wit/location but not Delhi, even though I have added multiple samples.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
We should be able to extract both Sydney and Delhi as the wit/location entity.

**What is the App ID where you are experiencing this issue (if applicable)?**
59a39bef-0ce6-4e80-b097-9794e9b58d76

**Comment by patapizza** [comment]
This is now fixed.

**Comment by nikhilpal** [comment]
@patapizza thanks for the quick turn around, whats the process from here, when does it get reflected in the engine on the wit.ai site?
