### ISSUE TITLE
Training killed automatically for older messages, why and /samples api is helping

### ISSUE THREAD

**Issue by onkar-infoobjects** [wit-ai/wit#841]
Hello,

Message "Can you name a good law firm in Chennai?" was trained like showing below. I have picked up the entities from expressions.json file the downloaded data.

> {
      "text" : "Can you name  a good law firm in Chennai?",
      "entities" : [
        {
          "entity" : "action",
          "value" : "business"
        },
        {
          "entity" : "intent",
          "value" : "fetchItems"
        },
        {
          "entity" : "bizCategory",
          "value" : "law firm",
          "start" : 21,
          "end" : 29
        },
        {
          "entity" : "wit$location",
          "value" : "Chennai",
          "start" : 33,
          "end" : 40
        }
      ]
    }

We trained this message few days back but when i looked today, i did not get the entities which were trained.

And this is happening with many messages. Its a critical point. We are loosing the efforts we put on.

And i am trying to train those messages with **/samples** api and that api is sending correct response but still wit response for the message is same.

**What should be done in this case?**

**Comment by blandinw** [comment]
@onkar-infoobjects Apologies for the late reply. There's probably a logical explanation to this, no need to panic.
Please follow the issue template so that we can better help you. What is your app id?

**Comment by onkar-infoobjects** [comment]
Hey @blandinw ,

Sorry i missed the notification.
The App id is: 588b1027-6be1-4ab0-818e-649c66abb958

Would you be able to let me know if i am doing something wrong with the training?

**Comment by onkar-infoobjects** [comment]
Hey @blandinw,

Any luck?

**Comment by gulbinas** [comment]
App ID: 5a11f551-d02e-4fdf-a379-b35db88e2d74

Appears in aforementioned app we have same issues.

Looks like there is misconception how to use /samples API endpoint.

To my understanding this endpoint should emulate consoles "Verify" button, am I right?

**Comment by blandinw** [comment]
The POST /samples API queues up requests to be processed asynchronously when the system is under pressure. The system experienced slowness lately, hence POST /samples returning a 200 and app not being trained right away. We're implementing 2 things: a) massive speed ups of queue processing and b) training status API for you to know when the training actually will happen or happened.

**Comment by gulbinas** [comment]
@blandinw in that case, this is still useful: https://github.com/wit-ai/pywit/pull/101

**Comment by stopachka** [comment]
Both issues, and the new training API tracked on #876
