### ISSUE TITLE
Inbox items cannot be deleted

### ISSUE THREAD

**Issue by fpunny** [wit-ai/wit#844]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
report a bug

**What is the current behavior?**
If you click the trashcan icon, it would delete for a split second before reappearing again. Reloading does not fix this.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Click the trashcan icon for an item and it would disappear for a split second before reappearing

**What is the expected behavior?**
The item gets removed from inbox

**What is the App ID where you are experiencing this issue (if applicable)?**
59fe3f13-a937-41b8-985e-e9a55353ef95

**Comment by blandinw** [comment]
Thanks for the feedback, I'm looking into it

**Comment by stopachka** [comment]
duplicates https://github.com/wit-ai/wit/issues/481
