### ISSUE TITLE
bug: While using pywit receiving: wit.wit.WitError: Wit responded with status: 400 (Bad Request)

### ISSUE THREAD

**Issue by AvielNiego** [wit-ai/wit#845]
I JUST NOTICED THAT THIS ISSUE IS DUPLICAT,
THE OTHER ISSUE IS HERE: https://github.com/wit-ai/wit/issues/822

I have a problem using `pywit` which is the python library for WitAi

For couple of days I've been using `pywit` in my app, which has 5K~ uses per day.
Until today everything worked perfect.

This is my code:
`
Wit('TOKEN').speech(open('file.wav', 'rb').read(), headers={'Content-Type': 'audio/wav'})['_text']
`
For a couple of hours now, I sometimes get this error:

> Traceback (most recent call last):
>   File "<input>", line 1, in <module>
>   File "C:\Develop\XXX\wit_ai_client.py", line 14, in recognize
>     return Wit(XXX).speech(wav_content, headers={'Content-Type': 'audio/wav'})['_text']
>   File "C:\Python35\lib\site-packages\wit\wit.py", line 102, in speech
>     data=audio_file, headers=headers)
>   File "C:\Python35\lib\site-packages\wit\wit.py", line 41, in req
>     ' (' + rsp.reason + ')')
> wit.wit.WitError: Wit responded with status: 400 (Bad Request)

Sometimes the translation return just right, but sometimes `pywit` throws this error

The app id is: 59f30c07-1f08-4c0f-90ac-ad61a7e22662

**Comment by blandinw** [comment]
Thanks for the feedback, I'm looking into it
