### ISSUE TITLE
Response Time wildly varies for same query (0.5 to 16 seconds)

### ISSUE THREAD

**Issue by hactar** [wit-ai/wit#846]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
We have a wit app (id see below) where response times vary wildly for the same query. If you send the query 10 times in a row, always waiting for a response before sending of the next query, sometimes wit returns the response in less than a second, and frequently, the *same* query takes over 10 seconds.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

```
curl \
 -H 'Authorization: Bearer SECRET' \
 'https://api.wit.ai/message?v=20171105&q=fundamt'
```
Send this to the server 10 times in a row, not in parallel, one after the other (so as to prove its not a rate limit issue)

Watch the response times. I've graphed one of my tests here. Response time is in seconds.

<img width="1166" alt="wit-speed" src="https://user-images.githubusercontent.com/645674/32420106-d163d708-c285-11e7-9640-e6094fa8e56b.png">

**What is the expected behavior?**

In an ideal world Wit would always return in less than a second, but it should never take more than 4? seconds? Definitely not over 10.

**What is the App ID where you are experiencing this issue (if applicable)?**
573c7652-5ac4-4a83-96d2-d81d7d79a239

**Comment by blandinw** [comment]
Thanks for reporting. We're usually seeing slow response times for apps with a large number of different entities (as seems to be the case here). The high variance is definitely suspicious, I'll look into it more closely.

**Comment by hactar** [comment]
Thanks. I understand that the model isn't optimal for wit, so I'm less surprised with the 0-4 second replies. But having the exact same request vary between 0.7 seconds and 16 seconds within an hour of requests, when one is not hammering the server with requests, appears very weird.

**Comment by blandinw** [comment]
I found the issue. Your trained models include 170 *free-text* entities, which leads to abnormally long cache warmup time for this app. Once cache is warm, requests execute quickly, if cache is cold, requests are slow.

After looking closer, I see that there's only a few entities with the free-text strategy enabled. Did you change this recently? That should help bringing the cold cache time way down. The app may need to be retrained.

**Comment by hactar** [comment]
Neat, we've removed free-text from our entities and waited for retrain to complete: first tests look positive, response time appears much more stable. I'll close the issue and reopen it should secondary tests fail.

Thanks for the help!
