### ISSUE TITLE
Bad request, without specifications

### ISSUE THREAD

**Issue by 488kuroi** [wit-ai/wit#847]
Hello, since few days, using this package, I'm receiving this error during the response:
Bad Request: 400
I'm pretty sure that audio files and authentication tokens are correct, because they worked until now.
Can you help me?

Here's a snippet of my code:

`
(() => {
'use strict';
let instance = null;
module.exports = class AudioModel extends Model {
constructor() {
super();
}

 callSTT( cred, blob ){
    return new Promise( ( resolve, reject ) => {;

        let buf = new Buffer( blob[ 'blob' ], 'base64' ); // decode
        let filePath = path.join( __dirname, '../record.wav' );

        fs.writeFile( filePath, buf, ( err ) => {

            if(err) {
                console.log( "err from fs:", err);
            } else {

                let APIresponse = '';
                let headers = { 'Authorization': 'Bearer ' + cred.token,
                                 'Content-Type': 'audio/raw',
                 };
                 let dataString = '@record.wav';
                 let options = { url: cred.url,
                     method: 'POST',
                     headers: headers,
                     body: fs.createReadStream( filePath )
                 };
                 let callback = (error, response, body) => {
                
                     console.log( response );
                
                     if (!error && response.statusCode == 200) {
                         console.log( 'responding to Controller' )
                         APIresponse = JSON.parse( body );
                         resolve( APIresponse );
                     } else {
                         reject( 'error from audio api ' + error );
                     }
                 };
                
                 request(options, callback);
                // // end of call to the API
            }
        });

    } );

  }

  callTTS( data ){
      return new Promise( ( resolve, reject ) => {

          googleTTS( data[ 0 ][ 'word' ], 'it', 2)   // speed normal = 1 (default), slow = 0.24
              .then(function (url) {
                  // console.log(url); // https://translate.google.com/translate_tts?...
                  data[ 0 ][ 'audio_url' ] = url;
                  resolve( data );
              })
              .catch(function (err) {
                  console.error(err.stack);
                  reject( 'error retrieving audio from STT:', err.stack );
              });
      } );
  }
}

})();
`

**Comment by blandinw** [comment]
@488kuroi please use the provided issue template.
We'll need your app id and some of the audio files you used.
Is there any error message in the response *body*?

**Comment by 488kuroi** [comment]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
Service responds with error 400 - Bad request
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

code snippet:

`
callSTT( cred, blob ){
    return new Promise( ( resolve, reject ) => {

    let buf = new Buffer( blob[ "blob" ], "base64" ); // decode
    let filePath = path.join( __dirname, "../test.wav" );

    fs.writeFile( filePath, buf, ( err ) => {

        if(err) {
            console.log( "err from fs:", err);
        } else {

            let APIresponse = "";
            let headers = { "Authorization": "Bearer 6VNDLXYDXVM3N65RWW46C3WG56DOTUPX",
                            "Content-Type": "audio/wav",
            };
            let dataString = "@test.wav";
            let options = { url: "https://api.wit.ai/speech?v=20170307",
                method: "POST",
                headers: headers,
                body: fs.createReadStream( filePath )
            };
            let callback = (error, response, body) => {
        
                console.log( response );
        
                if (!error && response.statusCode == 200) {
                    console.log( "responding to Controller" )
                    APIresponse = JSON.parse( body );
                    resolve( APIresponse );
                } else {
                    reject( "error from audio api " + error );
                }
            };
        
            request(options, callback);
            // end of call to the API
        }
    });

} );

}

`

**What is the expected behavior?**

Service should return an object that should contain a text string extracted from the audio file

**What is the App ID where you are experiencing this issue (if applicable)?**

my app id is: 5911a77b-3669-4e1e-b61d-b3242b181ec1

**Comment by stopachka** [comment]
Hey @488kuroi -- what is your audio file? 

-- 

Also, I suggest you change your token -- it is currently visible in the snippet you sent

**Comment by 488kuroi** [comment]
@stopachka I've already changed it, thank you.
And here's the audio file
[test.wav.zip](https://github.com/wit-ai/wit/files/1470037/test.wav.zip)

**Comment by peterdev6** [comment]
Any update on this issue?
I am having the same issue. I am using [react-native-audio](https://github.com/jsierles/react-native-audio) to record the audio and [rn-fetch-blob](https://github.com/joltup/rn-fetch-blob) to send the audio file. But I am getting 400 (bad request).

This is how i made the request: 
```
RNFetchBlob.fetch('POST', url, {
   'Authorization' : 'Bearer ' + token,
   'Content-Type' : 'audio/ulaw'
}, RNFetchBlob.wrap(uri))
```
This is my app id: `5af84604-5c5f-480f-8884-238cdd01ab5c`

Thanks in advance!

**Comment by blandinw** [comment]
@peterdev6 did you figure it out? Can you copy/paste the whole output you're getting? Reproducing the issue with a cURL command + providing the sound file would be great.

**Comment by blandinw** [comment]
Will close, feel free to comment back here and provide repro steps
