### ISSUE TITLE
BUG, Build Entities with API - Samples don't work

### ISSUE THREAD

**Issue by zivbrachia** [wit-ai/wit#848]
I want to report a bug and I need a solution for it.
I'm building entities with wit.ai API. I have the same code from last week.
last week it worked fine, and now when I create new app with the same entities (after I waited for a day)
and nothing. I have no Insights. the samples are not working.
What is the reason? help, please.

**Comment by stopachka** [comment]
hey @zivbrachia 

Could you provide
- your app id
- an example request
- what you get back as the error
- what you expect to happen

**Comment by zivbrachia** [comment]
- App id:
      - Working model: 59f058c0-0661-4795-b557-cbd83f161aa7
      - Not working model: 5a001e9e-52c3-4890-a371-49be3949e409
   - Example request:
      - What is my balance
      - What is my balance
   - Response:
      - intent name: "intent_balance", intent value: "balance" - *This is
      what I expect to happen*
      - nothing!! (the response need to be the same as the working model)

**Comment by stopachka** [comment]
Could be related to sample issues in #811. Will look into this and update you

**Comment by stopachka** [comment]
main issue tracked on: https://github.com/wit-ai/wit/issues/876
