### ISSUE TITLE
Stories UI blank page

### ISSUE THREAD

**Issue by sindre** [wit-ai/wit#849]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
When opening the stories tab, the page loads and a blank page apears. Browser COnsole shows an error: 
SYsRpzRSNEw.js:20 Uncaught TypeError: Cannot read property 'forEach' of undefined
    at D (-vdtiovlx7k.js:17)
    at F (-vdtiovlx7k.js:17)
    at z.render (-vdtiovlx7k.js:17)
    at C (SYsRpzRSNEw.js:20)
    at B (SYsRpzRSNEw.js:20)
    at O (SYsRpzRSNEw.js:20)
    at W (SYsRpzRSNEw.js:20)
    at Do (SYsRpzRSNEw.js:20)
    at Go (SYsRpzRSNEw.js:20)
    at lp (SYsRpzRSNEw.js:20)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
click on the stories tab

**What is the expected behavior?**
Stories tab shows the Stories.

**What is the App ID where you are experiencing this issue (if applicable)?**
every app i have

**Comment by lc090d** [comment]
Having the same issue, same error in console on the logs page

**Comment by maximFromThe6ix** [comment]
Same, I cannot access the "stories" on my instance

**Comment by stopachka** [comment]
Thanks for reporting in all, bug identified and fix coming! will update here when all is ready

**Comment by stopachka** [comment]
fixed!
