### ISSUE TITLE
[Question] English + French

### ISSUE THREAD

**Issue by gregblt** [wit-ai/wit#850]
Hi,

I'm working on a messenger bot and I'm wondering if there is a way to work with english and french?

Can I use french and english in my wit.ai app?

**Comment by hactar** [comment]
At the moment there is no built in way in wit to have multiple languages within one wit app. 

My usual workflow for this is to create the app in english, with english intent names, entity names and examples. I then create a german app where I again use the english intent names and entity names, but provide german entity **values** and examples. My app or webservice then detects the language (via an app or device setting) and switches the api key to send to wit accordingly.

So, 1 app per language you plan to support. Maintaining your app is easy enough as you always use english to map your intents, etc within your app; maintaining the models isn't as easy, as whenever you add an intent or entity, you have to remember to do it in all your apps.

It works, but could be more convenient.

**Comment by gregorymichelet** [comment]
Thank you for your answer!

Alright, that is what  I taught but I was not sure. I'm a new user of wit and messenger API since few days during my free time and used only the built-in NLP of messenger to get the entities.

I'll go with your way then !

**Comment by stopachka** [comment]
Indeed! We are looking into supporting multi-lingual wit apps. Will update here when this gets closer in the roadmap

**Comment by birdietorerik** [comment]
Hi!

I have a bot on a page, and working fine. But when i added a new page, and set developer-facebook to olso use this page. The bot dosent show up on my page ?

**Comment by jtliao** [comment]
this may be useful https://medium.com/wit-ai/introducing-language-identification-38d714f86ffc
