### ISSUE TITLE
GET /message returning empty entities after successful training

### ISSUE THREAD

**Issue by bpleao** [wit-ai/wit#851]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
I've created the app, added entities and samples, all using the REST API. Training took many hours but finished with status "clean". However responses from the app (e.g. to GET /message) return no entities.
 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

When I make a GET /message request:
curl \
 -H 'Authorization: Bearer E4JRPUWITCKTEHAOIP6QWLTIIDMAATJU' \
 'https://api.wit.ai/message?v=8/11/2017&q=como ter paciência?'

I get no entities:
{
    "msg_id": "0Us4HeAs0WVIqh2Rb",
    "_text": "como ter paciência?",
    "entities": {}
}
**What is the expected behavior?**

I'd like to get the associated entities, as I get for instance with App ID 59e4a3e1-e6fb-466c-a1d3-4e6df68a1256:

{
    "msg_id": "0gEJJDtMekE094qC4",
    "_text": "como ter paciência?",
    "entities": {
        "intent": [
            {
                "confidence": 0.99912042548059,
                "value": "Q254"
            },
            {
                "confidence": 0.00040700582721336,
                "value": "Q1"
            },
            {
                "confidence": 0.000045070944765325,
                "value": "Q131"
            },
            {
                "confidence": 0.000029709705425361,
                "value": "Q20"
            },
            {
                "confidence": 0.000021819199155717,
                "value": "Q2"
            }
        ]
    }
}

**What is the App ID where you are experiencing this issue (if applicable)?**
5a018818-d238-4fd7-afbf-28db298e1adf

**Comment by zivbrachia** [comment]
I reported the same bug yeterday.
https://github.com/wit-ai/wit/issues/848

**Comment by stopachka** [comment]
We can look into the bug in #848 then
