### ISSUE TITLE
Training is erased after creating new app based on backup

### ISSUE THREAD

**Issue by mbetard-squid** [wit-ai/wit#852]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
When I want to create an app based on a backup I have an error message.
Then the app is created with all the entities created from the back up but the wit app is unable to recognize any.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Visit https://wit.ai/apps/new
2. Enter details including backup (Zip-file. My backup is ~26KB)
3. Click Create App
4. You have the following error message ![error](https://user-images.githubusercontent.com/23653748/32608512-e000e4d4-c55c-11e7-94ac-3605e3eb149b.png)
5. Go back to your profile and open the app just created. Try to type something to test your app. There is no recognition. If you go on an entity, all training expressions are missing.

**What is the expected behavior?**
App must be created and the training must be kept.
**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by stopachka** [comment]
Hey @mbetard-squid Could you email me your zip file ? stopachka at fb com. Also, did you edit the zip file in any way?

**Comment by mbetard-squid** [comment]
I just did it.

**Comment by Joinfield** [comment]
**Same here.** Just try it yourself, just a bigger training set, it won't work! Thanks for fixing, need to clone App.

**Comment by mbetard-squid** [comment]
What is the status for this issue. Do you plan to solve it ? I just cloned an app and need to do the training all over again.

**Comment by patapizza** [comment]
Thanks for pinging @mbetard-squid and sorry for the latency on this one.

**Comment by stopachka** [comment]
Apologies for the latency here. 

There are two issues in this report.

1. Something went wrong when uploading a specific zip
- Looking into this, will update you with news here. 

2. Training not triggering correctly
 - This is the same issue with https://github.com/wit-ai/wit/issues/876
   - To go deeper, please comment in there, with:
       - The app-id that experienced the issue
       - The time and date that you experienced the issue
   - This is a tricky bug, and we are actively working on tracking this down. 
   - If you have a zip file handy, feel free to email me stopachka [a.t] fb [d.ot] com

**Comment by stopachka** [comment]
Update on 1: 
- This was caused by a bug, where certain samples in your app were failing to validate. Fixed the issue, and now the zips should upload well. Let me know if that isn't the case

For 2, let's move a detailed repro  to #876
