### ISSUE TITLE
contacts with possessives

### ISSUE THREAD

**Issue by bmcclenahan** [wit-ai/wit#853]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
from the question "what is brian's mobile" wit identifies a contact entity with value "brian's"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
the contact entity returned should be "brian" - until recently, wit was able to identify the possessive expression and return this correctly

**What is the App ID where you are experiencing this issue (if applicable)?**

58aecb8b-e2a7-46ff-8f5d-3a04e81575ac

**Comment by stopachka** [comment]
Great point Brian. Will add this to our enhancement of built-in entities, and update here as we get it fixed

**Comment by patapizza** [comment]
In the meantime, a quick fix would be to strip `'s` from the end of `wit/contact` entities as a post-processing step.

**Comment by ashokpatsamatla** [comment]
@patapizza - Wit is having issues recognizing "john's" as a wit/contact. So this workaround maynot work.

**Comment by patapizza** [comment]
@ashokpatsamatla Do you have an example where it does not work?

<img width="982" alt="screen shot 2018-05-23 at 6 25 18 pm" src="https://user-images.githubusercontent.com/1015208/40454401-ba5c509e-5eb6-11e8-830f-e8908f52a342.png">
