### ISSUE TITLE
Feature request: Blacklist Synonyms

### ISSUE THREAD

**Issue by rianrajagede** [wit-ai/wit#855]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Feature request

**What is the current behavior?**
In Indonesia (and maybe another language too), we have the same word to express a different meaning. Example: "Minggu" (sunday), "Minggu Depan" (next week), and "Minggu ini" (this week).

Let say I have a keyword entity `Sunday`. If I use synonym "Minggu" to detect keyword `Sunday`, when user input "Minggu Depan", sometimes it detects keyword `Sunday`, because it detects "Minggu" and ignore the word "Depan" in the next of it.

**What is the expected behavior?**
Maybe if possible, I think it is good to put a "blacklist synonyms" or something which is a list of similar word which can't be detected as synonym of the keyword. For example, in the case above, in keyword `Sunday` I will said "Minggu" as synonym and "Minggu Depan" as blacklist synonym. So if user input "Minggu depan" at least it will not detected as synonym of `Sunday`

Thank You

**Comment by l5t** [comment]
Not sure a blacklist feature would be very easy to use. In this use case, I would suggest to contribute to use Duckling, our open source linguistic probabilistic parser: https://github.com/facebook/duckling
If you add the support for date, you will then be unlocking wit/datetime for all Indonesian developers.
