### ISSUE TITLE
[Question] Training required when using PUT request on an entity?

### ISSUE THREAD

**Issue by wimvdc** [wit-ai/wit#856]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question

**What is the current behavior?**
Let's say I have a list of products which I "mapped" to a entity (keyword based).
I manually add some keyword with some synonyms and test it and all goes well.

In reality I have hundreds of products which I don't want to add manually of course.
If I would use the wit.ai API to  update the entity (using PUT https://api.wit.ai/entities/$ENTITY_ID) with all my products on a daily/weekly basis (in an automated way of course). 

Question: Do I need to "train" the test data again every time I update the keywords/synonyms knowing that most keywords/synonyms won't change that often?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
 /

**What is the expected behavior?**
/

**What is the App ID where you are experiencing this issue (if applicable)?**
/

**Comment by patapizza** [comment]
Hi @wimvdc,

Assuming that by "train" you mean "validate more examples", there is no need for that for keyword entities (you can see it as a fuzzy string matching).
