### ISSUE TITLE
error : Bad request

### ISSUE THREAD

**Issue by abaradia1978** [wit-ai/wit#857]
I am getting below response
{
  "error" : "Bad request",
  "code" : "bad-request"
}

my request is as under:
curl -X POST https://api.wit.ai/message -H "Content-Type: application/json" -H "Authorization: Bearer MY_TOKEN" -d '{"v":"15/11/2017" , "q":"will"}'

**Comment by patapizza** [comment]
Hi @abaradia1978,

It seems like we had a transient issue that should now be resolved. Feel free to reopen if you still experience the issue.

**Comment by abaradia1978** [comment]
Still facing the same issue - pls help

**Comment by patapizza** [comment]
@abaradia1978 My bad - the issue is actually in the request.

Please add the data as URL parameters (not body): https://wit.ai/docs/http/20170307#get--message-link

**Comment by abaradia1978** [comment]
Thanks.

My revised request is as under:
curl -XGET https://api.wit.ai/message?v=17/11/2017&q=will -H 'Authorization: Bearer MYTOKEN'
tried by changing dateformat for variable v
curl -XGET https://api.wit.ai/message?v=20171117&q=will -H 'Authorization: Bearer MYTOKEN'

but I am getting Bad Auth
{
  "error" : "Bad auth, check token/params",
  "code" : "no-auth"
}'q' is not recognized as an internal or external command,
operable program or batch file.

I have rechecked and I am inputting my token correctly. Is the account getting blocked or something - can you please check or let me know what else is the issue.

**Comment by abaradia1978** [comment]
await your revert - still getting same error message

**Comment by patapizza** [comment]
@abaradia1978 Try to wrap the URL with quotes.

**Comment by abaradia1978** [comment]
it need double quotes and not single quotes - it worked now - Thanks
