### ISSUE TITLE
BUG - Location entity

### ISSUE THREAD

**Issue by kjanko** [wit-ai/wit#858]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
I trained the entity on synonyms of the following sentence: "do you have open positions" and "do you have open positions in X"

First bug: using wit/location, "positions" was being recognized as a location, while It was trained on cities word which do not correlate to "positions" at all.
Second bug: I made a custom location entity, using keyword-freetext search on custom words. It started to recognize cities fine, however if a question mark was lacking at the end, It wasn't able to recognize the entity ( the trained data was with a question mark at the end of the sentence). Punctuation should not matter during train process.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I have explained above.
**What is the expected behavior?**
Punctuation should not matter. wit/location should not be able to recognize non-correlated words. Maybe a new entity can be trained that would only capture cities/villages? Since currently wit/location captures street names as well, so I can see where the issue could come from.
**What is the App ID where you are experiencing this issue (if applicable)?**
5a017c34-c903-4b8b-9796-490e81d305bd
(I have removed wit/location for now)

**Comment by patapizza** [comment]
Hi @kjanko,

Thanks for reporting.

Re 1), we're actively working on improving `wit/location` (it's too greedy today).
Re 2), do you have an example that doesn't work? I can't repro:

![](https://i.imgur.com/uxirz7Z.png)

**Comment by kjanko** [comment]
@patapizza I will check the postman logs and update tomorrow as I have no access atm.

**Comment by patapizza** [comment]
1) has been fixed - `positions` no longer triggers `wit/location`.
Try to reuse `wit/location` and let me know how it goes. Feel free to reopen if you experience further issues.
