### ISSUE TITLE
wit/greetings and wit/thanks not working

### ISSUE THREAD

**Issue by marexv** [wit-ai/wit#859]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
*bug* 

**What is the current behavior?**
wit/greetings and wit/thanks are not recognizing even simple inputs such as "hi, "hello" or "thank you". These features were working great for past 6 months. I do understand that both are still in BETA but both are important in customer support environment and for general politeness.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
To reproduce the problem just type something as simple as "hi", "hello", "thank you" or "thanks" into the understanding input field and watch as nothing happens. I have included some images:

both entities are used:
![inkedscreenshot-2017-11-15 wit ai - dinitkotest1 6 _li](https://user-images.githubusercontent.com/18647669/32840272-75fdb0ac-ca17-11e7-8886-63d827c3ee92.jpg)

Greetings:
![screenshot-2017-11-15 wit ai - dinitkotest1 1](https://user-images.githubusercontent.com/18647669/32840300-8b2025d2-ca17-11e7-92e3-02d410bfdc43.png)
These examples worked fine before:
![screenshot-2017-11-15 wit ai - dinitkotest1 3](https://user-images.githubusercontent.com/18647669/32840308-8ee9af80-ca17-11e7-85ac-ee732b8f9022.png)
When calling API this is the response:
![inkedconsole2_li](https://user-images.githubusercontent.com/18647669/32840356-adeae192-ca17-11e7-927f-13d525d5195f.jpg)
![screenshot-2017-11-15 wit ai - dinitkotest1 7](https://user-images.githubusercontent.com/18647669/32840444-eb439700-ca17-11e7-99eb-656c90d3a4c5.png)

Thank you:
![screenshot-2017-11-15 wit ai - dinitkotest1 8](https://user-images.githubusercontent.com/18647669/32840476-0c4daa94-ca18-11e7-8204-4b8abb5126fc.png)
These examples worked fine before:
![screenshot-2017-11-15 wit ai - dinitkotest1 4](https://user-images.githubusercontent.com/18647669/32840484-11f159be-ca18-11e7-9591-7b362c1dc5ff.png)
When calling API this is the response:
![inkedconsole1_li](https://user-images.githubusercontent.com/18647669/32840518-2db5a09c-ca18-11e7-9632-a80766537c46.jpg)
![screenshot-2017-11-15 wit ai - dinitkotest1 5](https://user-images.githubusercontent.com/18647669/32840537-3c26c5d4-ca18-11e7-8618-e729c6adac50.png)

**What is the expected behavior?**
Entry "greetings" inside "entities" with "value" equal to "true" or (depending on the case) entry "thanks" inside "entities" 

**What is the App ID where you are experiencing this issue (if applicable)?**
590c5804-1746-42b5-863d-0af25a350a54

**Comment by patapizza** [comment]
Hi @marexv,

I can't repro - do you still experience the issue?

```
$ curl  \
 -H 'Authorization: Bearer xx' \
 'https://api.wit.ai/message?v=20171115&q=hello'
{"msg_id":"0oj6QeepmTkpxcEGP","_text":"hello","entities":{"greetings":[{"confidence":0.99988770484656,"value":"true"}]}}% 

$ curl  \
 -H 'Authorization: Bearer xx' \
 'https://api.wit.ai/message?v=20171115&q=hi'
{"msg_id":"0cP5tAnDVD321DKND","_text":"hi","entities":{"location":[{"suggested":true,"confidence":0.87836,"value":"hi","type":"value"}],"greetings":[{"confidence":0.99993050098374,"value":"true"}]}}%
                                                                                                                                                      
$ curl  \
 -H 'Authorization: Bearer xx' \
 'https://api.wit.ai/message?v=20171115&q=thank+you!'
{"msg_id":"05uTGbnzBIg1mknke","_text":"thank you!","entities":{"bye":[{"confidence":0.64467639232131,"value":"true"}],"thanks":[{"confidence":0.99391925325786,"value":"true"}]}}%
```

**Comment by marexv** [comment]
Hi @patapizza, Thank you for responding!

Unfortunately, the issue persists. I have tried to remove both entities and include them back into the app, everything is still the same though. both wit/greetings and wit/thanks work on my other app. Am I using too many entities in this app? (Currently I am at 18 (4 wit + 14 custom)). Do you have any other suggestions? 

Here are some screenshots:
![hi1](https://user-images.githubusercontent.com/18647669/32883806-b01b2dcc-cab8-11e7-8651-deb78a4fd2eb.PNG)
![screenshot-2017-11-16 wit ai - dinitkotest1 2](https://user-images.githubusercontent.com/18647669/32883826-beaadaae-cab8-11e7-9b43-e660c0d8df02.png)
 
![hello1](https://user-images.githubusercontent.com/18647669/32883834-c48157c8-cab8-11e7-8c1b-5240428fd3dc.PNG)
![screenshot-2017-11-16 wit ai - dinitkotest1](https://user-images.githubusercontent.com/18647669/32883852-d027087a-cab8-11e7-847a-0e7355da1d43.png)

![thankyou1](https://user-images.githubusercontent.com/18647669/32883867-dc0f4788-cab8-11e7-8017-83b960afa67c.PNG)
![screenshot-2017-11-16 wit ai - dinitkotest1 1](https://user-images.githubusercontent.com/18647669/32883876-e04de624-cab8-11e7-8b3a-58e3544a91af.png)

Just as demonstration that curl works properly although it says that it cannot resolve host (I am usig python backend and requests(http://docs.python-requests.org/en/master/) for calling API and there are absolutely no issues there.
![creditcards1](https://user-images.githubusercontent.com/18647669/32884023-4b6ffd48-cab9-11e7-83ed-92c58e1960ad.PNG)
![screenshot-2017-11-16 wit ai - dinitkotest1 3](https://user-images.githubusercontent.com/18647669/32884058-65d24ae2-cab9-11e7-9b2a-73f70f32415c.png)

**Comment by patapizza** [comment]
@marexv I found the issue, will fix today.

**Comment by patapizza** [comment]
This is now fixed.

**Comment by anhhtz** [comment]
Hello,

I cannot find `wit/thank, wit/bye, wit/greetings` in Console. Does it available in `Vietnamese` language ?

Thanks !

**Comment by aforaleka** [comment]
Hello @anhhtz, thanks for supporting Wit. `wit/thanks`, `wit/bye` and `wit/greetings` are only available in English and Chinese at the moment. But we may look into adding more languages in the future!
