### ISSUE TITLE
How to return metadata values?

### ISSUE THREAD

**Issue by toanld** [wit-ai/wit#860]

**Comment by patapizza** [comment]
We're looking into this.

**Comment by stopachka** [comment]
![image](https://user-images.githubusercontent.com/984574/33152839-a77cbafc-cf93-11e7-9b09-bd0b02321ab3.png)

Hey there,

1. Go to the "Understanding" Tab
2. Click on the entity you would like to set metadata for
3. Hover of the value, and click "Edit Metadata"
