### ISSUE TITLE
throws random http 500

### ISSUE THREAD

**Issue by kazimanzurrashid** [wit-ai/wit#861]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
it returns server side error.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

requesting https://api.wit.ai/entities/intent?v=20170307 throws random http 500 status code with the following response:

```
body
:
"{↵  "error" : "Something went wrong. We've been notified.",↵  "code" : "wit"↵}"
headers
:
{server: "nginx", date: "Mon, 20 Nov 2017 15:49:22 GMT", content-type: "application/json",…}
connection
:
"close"
content-length
:
"78"
content-type
:
"application/json"
date
:
"Mon, 20 Nov 2017 15:49:22 GMT"
server
:
"nginx"
x-content-type-options
:
"nosniff"
statusCode
:
500
statusMessage
:
"Internal Server Error"
````
**What is the expected behavior?**
it should return the correct data

**What is the App ID where you are experiencing this issue (if applicable)?**
5a12f5be-3515-46d4-8d61-0254204037cf

**Comment by mheimschild** [comment]
same here
App ID 59ff419e-cac2-4639-84fb-17edc3794818

and only a fraction of messages land in expression inbox what makes training practically impossible

**Comment by gulbinas** [comment]
same here

App ID 5a11f551-d02e-4fdf-a379-b35db88e2d74

**Comment by blandinw** [comment]
Our inbox database was experiencing issues at that time, please comment if the issue is not resolved. Note that we're working on a better inbox system to be deployed by end of year.

**Comment by mheimschild** [comment]
@blandinw - it worked for few seconds but now returns https://api.wit.ai/inbox?limit=10 permanently 500

**Comment by gulbinas** [comment]
Same here, It works until you make enough actions places via API.

For new users this is very misleading. I think you should keep this issue open until you deploy update.

If not this issue I'd think app is broken...

**Comment by stopachka** [comment]
Hey @gulbinas -- which part was misleading? would a different error message have helped? Happy to hear your thoughts, and see if we can implement that in the interim, as we migrate this infra

**Comment by gulbinas** [comment]
Hello @stopachka,
by misleading I meant that it took time for me as a newcomer to find that API 500 error because at first place I didn't expected that and secondly there was no UI notification indicating that.

Even more, I find related github issue which is closed and I got it reopened just to find out that site is unusable, issue is known and fix is being developed.

UI notification and open github issue would saved some time.

For now site works fine.

**Comment by stopachka** [comment]
Great point @gulbinas -- Maybe we can have a quick on the main site, when it is experiencing difficulties. Will bring this to the team to the put to the roadmap
