### ISSUE TITLE
Training API not working as Expected

### ISSUE THREAD

**Issue by sachintah** [wit-ai/wit#862]
My app id is 5a12cf99-abb6-4013-afe1-18a5a3cfbfcc and is a private app, training API was working fine however suddenly it stopped reflecting training data. surprisingly it is returning correct API response.

Please help.

Sachin

 curl -XPOST 'https://api.wit.ai/samples?v=20170307' \
  -H "Authorization: Bearer $MyToken" \
  -H "Content-Type: application/json" \
  -d '[{
        "text": "What is Mongo DB?",
        "entities": [
          {
            "entity": "intent",
            "value": "Mongo DB is a dodument database"
          }
        ]
      }]'

**Comment by Roger13** [comment]
I'm having the exactly same issue, posted data returns a success with "{ sent: true, n: 1 }" however it doesn't reflect on the interface. Was working fine a few days ago...

**Comment by l5t** [comment]
We are investigating... sorry for the inconvenience

**Comment by leeppolis** [comment]
My understanding is that also the web interface for training the engine has some problem today.

**Comment by l5t** [comment]
Quick update, there were some issues with the /samples calls and thhis cluttered our training queue.  We are slowly recovering so the training should happen in the next few hours. Will update when the issue is resolved

**Comment by sachintah** [comment]
Thanks for your reply Laurent, my only concern is around the response received from the API. API is sending positive response even when training is not happening, such response changes the flags at our end
Please let us know if such probability may arise in future and if you are planning to change response in such cases

**Comment by l5t** [comment]
This should be back to normal. Thanks for your patience and sorry for the inconvenience.

**Comment by sachintah** [comment]
Hello, 

This issue cropped again, we are getting exact same issue......Please help.

Sachin

**Comment by rafadorado** [comment]
Same here. Can't use the Training API :-(

**Comment by blandinw** [comment]
The POST /samples API queues up requests to be processed asynchronously when the system is under pressure. The system experienced slowness lately, hence POST /samples returning a 200 and app not being trained right away. We're implementing 2 things: a) massive speed ups of queue processing and b) training status API for you to know when the training actually will happen or happened.
