### ISSUE TITLE
Entity with an high number of keywords

### ISSUE THREAD

**Issue by MarcoMari** [wit-ai/wit#863]
Hi all,
I would like to understand what's the best approach for using Wit.ai in my situation.
I have a concept ("hotel room amenity") that can take several values ("TV", "coffee maker", ...). The number of values can easily go over 100.
In your experience, it's better to:
- create 1 entity, with 100+ keywords
- divide the single entity in 100+ simpler entities
- both approaches can be followed

Thank you in advance for any feedback!

**Comment by l5t** [comment]
Posting the answer here in case it can help others: 
I would suggest 1 entity with as many keywords as you need (as soon as it stays under 10,000). The main rationale is that these entities will be used in similar sentences so it’s better to only train one entity

**Comment by MarcoMari** [comment]
Answered on FB group:
" I would suggest 1 entity with as many keywords as you need (as soon as it stays under 10,000). The main rationale is that these entities will be used in similar sentences so it’s better to only train one entity"
