### ISSUE TITLE
Problem matching custom entities if sentence isn't built correctly

### ISSUE THREAD

**Issue by magnusburton** [wit-ai/wit#864]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
If I'm training text with multiple sentences and there aren't *spaces* [ ] between the dot and the next sentence Wit.ai has a problem parsing the last entity in the first sentence.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Let's say I have the following sentence;

> I'd like to have some ice cream.Preferably chocolate!

(Notice the lack of space between ice cream. and Preferably!)
And the custom entities `food` (as a keyword entity) and `flavor`. I'd want Wit.ai to match chocolate to the `flavor` entity and ice cream as a `food` item. The problem is that most of the time wit parses `food` as:

> ice cream.Preferably

**What is the expected behavior?**
If there's a space between the two, Wit.ai matches *ice cream* correctly. That's the expected behavior.

**What is the App ID where you are experiencing this issue (if applicable)?**
Lisa_SV_Disturbances (59f24f07-1046-45e4-a714-d41d78ceac4d)

**Comment by magnusburton** [comment]
See [this video](https://youtu.be/SfJJBt8Gh30).

**Comment by blandinw** [comment]
Thanks for your feedback! We're looking it.

**Comment by blandinw** [comment]
@magnusburton could you send us the problematic sentence (in Swedish) so that we can debug the actual issue you have (same app, same models, same input)?

**Comment by magnusburton** [comment]
@blandinw Thank you! Both of these sentences will display the issue:

> Trafiken är helt inställd mellan Centralen och Järva krog för buss 599 sedan kl 4:17 på grund av personalbrist.Detta beräknas pågå till cirka kl 6:00.

> Förseningar på som mest 9 minuter för buss 117 på grund av hög belastning.Förseningarna beräknas pågå till cirka kl 13:50.

**Comment by blandinw** [comment]
Thanks for the additional info @magnusburton 

This behavior is how our tokenizer is supposed to work unfortunately. When there's no space on _either_ side of the period, it can be hard to know what the user meant. A possible workaround would be to add spaces after punctuation on your side (`str.replace('.', '. ')`).

We're currently working on a new version of our free-text strategy, which should be smarter about this kind of things. I opened an internal ticket to keep this is mind as we build the new version.

I'll close the issue as wontfix, thanks again for the discussion.
