### ISSUE TITLE
wit/duration suddenly stopped working

### ISSUE THREAD

**Issue by magnusburton** [wit-ai/wit#865]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
Previously, wit/duration found (after some training) durations and detected the duration (`30 minuter` (30 minutes in Swedish) was detected by Wit as 30 minutes). See [this video](https://www.youtube.com/watch?v=yxf-LsXKSJQ).

**What is the expected behavior?**
Detecting duration correctly, as it did 1.5 week ago.

**What is the App ID where you are experiencing this issue (if applicable)?**
magnusburton/Lisa_SV_Disturbances

**Comment by blandinw** [comment]
Thanks for the report, looking into it now

**Comment by blandinw** [comment]
@magnusburton I fixed your app. 
This is a known issue (heinsenbug) that we're tracking down, where your language is reset to English for some reason. Did you by any chance update your app settings recently?
Thanks again for the report and apologies for the inconvenience.
