### ISSUE TITLE
Training API not working as Expected  (same as #862)

### ISSUE THREAD

**Issue by sachintah** [wit-ai/wit#866]
We are again facing same issue which I posted last week with issue number #862 .

The train APIs have stopped working again, please help. 

App is is 5a0a981b-0fc0-4c8b-ac2b-d03f7009b295

Regards
Sachin Tah

**Comment by MixalisV** [comment]
I am facing the same issue, posted data returns a success message "{ sent: true, n: 1 }". However it doesn't reflect on the interface.

**Comment by blandinw** [comment]
The POST /samples API queues up requests to be processed asynchronously when the system is under pressure. The system experienced slowness lately, hence POST /samples returning a 200 and app not being trained right away. We're implementing 2 things: a) massive speed ups of queue processing and b) training status API for you to know when the training actually will happen or happened.

**Comment by sachintah** [comment]
Wow this sounds great, this was exactly that we were expecting, thanks a ton. 

Would be great if you could let us know expected release date for this feature.

Thanks again for quick reply.

Sachin

**Comment by blandinw** [comment]
We don't have a definite release date for this feature.
You can join the Early Access Program to get access to the feature earlier and influence its development by sending an email to help@wit.ai.
