### ISSUE TITLE
Cannot import app from backup

### ISSUE THREAD

**Issue by maximFromThe6ix** [wit-ai/wit#867]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

bug

**What is the current behavior?**

I'm trying to upload backup data I got from another instance in order to start up a development version of my instance, but I get an error message that something went wrong. The app then gets created but with around 1% of the original data

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Try to create instance and import app data from backup.

**What is the expected behavior?**

It uploads properly and an instance with all the correct data is created.

**What is the App ID where you are experiencing this issue (if applicable)?**

App ID from which I am getting backup data: 594bfa3f-42d2-4d9d-9ec6-f6a41f60bfdc
App ID which gets created with lacking data: 5a1c64d6-7dad-4a4d-b045-28fe8ed457fd

**Comment by stopachka** [comment]
Hey @maximFromThe6ix -- I will look into this and let you know what I find.

In the meantime, you can try using the POST /samples API to push the samples async, to see if you can find the errors.

**Comment by stopachka** [comment]
Hey @maximFromThe6ix 

The main cause for this was turns.json -- there was an error with how we re-imported them. Simply setting the data array in there to an empty one, will make the import work.

As stories is deprecated within a couple of weeks, I don't think it makes sense to invest in fixing the  turns error. Let us know if you run into issues migrating over to plain NLP
