### ISSUE TITLE
Keyword matching matches first part of keyword that makes up larger keyword

### ISSUE THREAD

**Issue by maximFromThe6ix** [wit-ai/wit#868]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

bug

**What is the current behavior?**

Let's say I have an entity that has keywords/synonyms: M.D., N.C., M.D.N.C, amongst others, which are all mean different things. If I provide an input such as:

"I really like the M.D.N.C." the keywords retrieved are M.D. and N.C.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

I have keyword matching on and if you were to use the sentence I provided on my application you will find the same incorrect results.

**What is the expected behavior?**

The expected output of the sentence that I provided would be the extraction of M.D.N.C. as a keyword, not the 2 keywords that were actually extracted.

**What is the App ID where you are experiencing this issue (if applicable)?**

594bfa3f-42d2-4d9d-9ec6-f6a41f60bfdc

**Comment by stopachka** [comment]
Hey @maximFromThe6ix Testing your app, shows the correct entity is matched (jurisdiction, with the entity value that has the keyword M.D.N.C.

What are the entities that you are seeing on your end?

**Comment by maximFromThe6ix** [comment]
With this query:

"In M.D.N.C., is the color of the sky blue?"

I'm getting 2 entities, rather than just the 1

**Comment by maximFromThe6ix** [comment]
This is still happening, is there really no fix?

**Comment by yegeniy** [comment]
Hi @stopachka 

We have seen the same issue for months with our system. It's been easy enough to patch over in our backing code, but I would assume that the longest matching substring be chosen for the entity, instead of the smallest matching ones.

Anyways, in case there's a chance this will be resolved I have created a small application to showcase the bug.

App Id: `5a4c08da-41d2-4f1b-8528-6ff03ab3b4df`

![image](https://user-images.githubusercontent.com/292802/34502963-1375b536-efe4-11e7-9309-9fa7ad4e6dd1.png)
![image](https://user-images.githubusercontent.com/292802/34502967-19a2f8d8-efe4-11e7-9131-913f2747ee42.png)

The issue occurs with `free text & keywords` as well as just `keywords` as the lookup strategy.

**Comment by blandinw** [comment]
Thanks for your feedback, we're looking into it

**Comment by blandinw** [comment]
This is now fixed, thank you for your feedback and patience.

**Comment by yegeniy** [comment]
This is glorious! Confirmed as working, wonderfully.

```
{
  "_text": "al east",
  "entities": {
    "organization": [
      {
        "confidence": 1,
        "value": "American League",
        "type": "value",
        "_entity": "organization",
        "_body": "al",
        "_start": 0,
        "_end": 2
      },
      {
        "confidence": 1,
        "value": "East",
        "type": "value",
        "_entity": "organization",
        "_body": "east",
        "_start": 3,
        "_end": 7
      }
    ]
  },
  "msg_id": "localtesting.1518109316"
}
{
  "_text": "national league",
  "entities": {
    "organization": [
      {
        "confidence": 1,
        "value": "National League",
        "type": "value",
        "_entity": "organization",
        "_body": "national league",
        "_start": 0,
        "_end": 15
      }
    ]
  },
  "msg_id": "localtesting.1518109316"
}
{
  "_text": "all-stars game",
  "entities": {
    "organization": [
      {
        "confidence": 1,
        "value": "All-Star Game",
        "type": "value",
        "_entity": "organization",
        "_body": "all-stars game",
        "_start": 0,
        "_end": 14
      }
    ],
    "intent": [
      {
        "confidence": 0.73611579188875,
        "value": "gameinfo",
        "_entity": "intent"
      }
    ]
  },
  "msg_id": "localtesting.1518109316"
}
{
  "_text": "all-stars",
  "entities": {
    "organization": [
      {
        "confidence": 1,
        "value": "All-Star Game",
        "type": "value",
        "_entity": "organization",
        "_body": "all-stars",
        "_start": 0,
        "_end": 9
      }
    ]
  },
  "msg_id": "localtesting.1518109316"
}
```

Thank you again. I can delete so much code today :)

**Comment by stopachka** [comment]
Cheers @yegeniy!
