### ISSUE TITLE
Bad Request 400 using SpeechRecognition Python package

### ISSUE THREAD

**Issue by gogo199432** [wit-ai/wit#869]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
3 times out of 4 I get a 'Bad Request' answer when I try to recognize single words straight from a microphone. Here is the library I'm trying to use: https://github.com/Uberi/speech_recognition
Additionally recognition when it works is extremely slow, about 5 second of waiting.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Install the mentioned library above. 
Follow the provided example found here: https://github.com/Uberi/speech_recognition/blob/master/examples/microphone_recognition.py
**What is the expected behavior?**
Recognize words: play, pause, stop
**What is the App ID where you are experiencing this issue (if applicable)?**
5a1d8f73-0257-4ff6-be57-e4bcf7e7d68d
(Although I'm not using the ID itself, only the server access token)

**Comment by stopachka** [comment]
Hey @gogo199432 -- most likely this is because you are sending waves that do not have discernible text in them -- do you mind giving us a few example wavs?

**Comment by l5t** [comment]
We'll make a pass at speech reliability issues at some point, but this is not a priority as of today. Please reopen if you can consistently repro
