### ISSUE TITLE
entity name not shown in JSON when all referenced entities have roles

### ISSUE THREAD

**Issue by alexdown** [wit-ai/wit#87]
I create a simple intent that recognise two _number_ entities.
![screen shot 2014-03-18 at 2 06 19 pm](https://f.cloud.github.com/assets/2376150/2444864/b4be7214-ae63-11e3-8053-d3aa5c253ff8.png)

```
{
  "msg_id" : "cbca965d-aa86-43c1-984f-dacadb760a09",
  "msg_body" : "I am arriving at 3 and leaving at 6",
  "outcome" : {
    "intent" : "test_entity_role",
    "entities" : {
      "number" : [ {
        "end" : 18,
        "start" : 17,
        "value" : 3,
        "body" : "3"
      }, {
        "end" : 35,
        "start" : 34,
        "value" : 6,
        "body" : "6"
      } ]
    },
    "confidence" : 0.567
  }
}
```

If I then add a role to the entities:

![screen shot 2014-03-18 at 2 07 25 pm](https://f.cloud.github.com/assets/2376150/2444862/a21a248c-ae63-11e3-8dd5-ee62260cdaae.png)

![screen shot 2014-03-18 at 2 08 48 pm](https://f.cloud.github.com/assets/2376150/2444866/cbdf959a-ae63-11e3-8c63-82ec9f4f8e15.png)

The reference to the entity name (__number__) is missing from the JSON, only the roles are present.

```
{
  "msg_id" : "d3da5406-7904-4e4b-b088-25f959621f4b",
  "msg_body" : "I am arriving at 3 and leaving at 6",
  "outcome" : {
    "intent" : "test_entity_role",
    "entities" : {
      "from" : {
        "end" : 18,
        "start" : 17,
        "value" : 3,
        "body" : "3"
      },
      "to" : {
        "end" : 35,
        "start" : 34,
        "value" : 6,
        "body" : "6"
      }
    },
    "confidence" : 0.567
  }
}
```

If I happen to define different entities with the same role name, I won't be able to distinguish which role refers to which entity.

I think it would be better to prefix the entity name to the role in case the entity has a role attached, in the form ``entity:role``.

Example of a "desirable" result:

```
{
  "msg_id" : "d3da5406-7904-4e4b-b088-25f959621f4b",
  "msg_body" : "I am arriving at 3 and leaving at 6",
  "outcome" : {
    "intent" : "test_entity_role",
    "entities" : {
      "number:from" : {
        "end" : 18,
        "start" : 17,
        "value" : 3,
        "body" : "3"
      },
      "number:to" : {
        "end" : 35,
        "start" : 34,
        "value" : 6,
        "body" : "6"
      }
    },
    "confidence" : 0.567
  }
}
```

**Comment by rdefeo** [comment]
I understand the point about merging, however even just a simple attribute of role and entity type would give the best of both.

It this something you would consider?

**Comment by stopachka** [comment]
Hiya rdefeo, you get the role and entities by adding `verbose=true` to your search.

i.e 

curl \
 -H 'Authorization: Bearer 2N6VBOB3ORTPGOGTWLBQA2AFJKBHXGQ2' \
  'https://api.wit.ai/message?v=20150409&verbose=true&q=I%20want%20to%20fly%20from%20new%20york%20to%20san%20francisco'
{
  "stats" : {
    "total_time" : 27
  },
  "msg_id" : "aab16958-c35c-4764-8dcc-6b02d6e08116",
  "_text" : "I want to fly from new york to san francisco",
  "outcomes" : [ {
    "_text" : "I want to fly from new york to san francisco",
    "intent" : "travel_destinations",
    "entities" : {
      "location_arrival" : [ {
        "suggested" : true,
        "value" : "francisco",
        "type" : "value",
        "_entity" : "location",
        "_role" : "location_arrival",
        "_end" : 44,
        "_start" : 35,
        "_body" : "francisco"
      } ],
      "location_depart" : [ {
        "suggested" : true,
        "value" : "new",
        "type" : "value",
        "_entity" : "location",
        "_role" : "location_depart",
        "_end" : 22,
        "_start" : 19,
        "_body" : "new"
      } ]
    },
    "confidence" : 1.0
  } ]
}%

You can use `_entity` and `_role` in the results to differentiate. Does that help?
