### ISSUE TITLE
general site issues

### ISSUE THREAD

**Issue by individual11** [wit-ai/wit#871]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
*Bug*(s)

**What is the current behavior?**
The site is throwing timeout errors all over the place. When I try to train it, work in the inbox or download the bot info from settings.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

To not throw timeouts.

**What is the App ID where you are experiencing this issue (if applicable)?**

583273ad-575f-4ad3-a801-fe95d236ce57

**Comment by stopachka** [comment]
Hey @individual11 -- we had an infra issue that would have affected this. We should be back to normal now.
