### ISSUE TITLE
Could not validate this expression

### ISSUE THREAD

**Issue by camburley** [wit-ai/wit#872]
**report a *bug***

**What is the current behavior?**
Whenever I add any statement, I'm getting "Could not validate this expression" in UI. It's not saving any entity values or intents. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I type new expressions, i click 'validate'....after a few seconds I get flag in UI.

**What is the expected behavior?**
Adds new entity values 

**What is the App ID where you are experiencing this issue (if applicable)?**
5a10a4e8-e737-401e-a087-a9e890ace3fc

**Comment by stopachka** [comment]
Hey @camburley  -- we had an infra issue that would have affected this. We should be back to normal now.

**Comment by camburley** [comment]
thanks for your help 😀

**Comment by stopachka** [comment]
Cheers @camburley !
