### ISSUE TITLE
Could not validate issue/bug

### ISSUE THREAD

**Issue by pmm1** [wit-ai/wit#873]
**report a bug**

**What is the current behavior?**
Whenever I add any statement, I'm getting "Could not validate this expression" in UI. It's not saving any entity values or intents.

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
I type new expressions, i click 'validate'....after a few seconds I get flag in UI.

**What is the expected behavior?**
Adds new entity values

**What is the App ID where you are experiencing this issue (if applicable)?**
594990d7-27ea-4d01-9667-2b8d88b7a062

**Comment by stopachka** [comment]
Hey @pmm1 -- we had an infra issue that may have affected you. All should be back to normal now
