### ISSUE TITLE
Import into existing app

### ISSUE THREAD

**Issue by XY-Wang** [wit-ai/wit#874]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
feature

**What is the current behavior?**
I have an app in development and I want to keep a separate app in production. The development app will be trained with new intents/entities and when the app is stable and well-trained I want to move this app into the production app via export/import.
Right now import only works on a newly created app, which means that each time I move into production I'll have to create new app, kill the old one and then update and redeploy the production bot with the new app.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
NA

**What is the expected behavior?**
Import from .zip is possible into an existing app

**What is the App ID where you are experiencing this issue (if applicable)?**
NA

**Comment by stopachka** [comment]
This is a good idea @XY-Wang! Will keep this in mind for our work on Import / Export + Versioning

In the meantime, here's some ideas on what you could do:
- If you use Built-In NLP, you can change your token without deploying
- If you use something like Firebase to store your token, you can change it without deploying as well

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
