### ISSUE TITLE
[Master Issue] Training 

### ISSUE THREAD

**Issue by stopachka** [wit-ai/wit#879]
Training is in the process of migrating to more robust infra. In the meantime, there may be issues with failed schedules for training. We'll manage that, and other reports regarding training here, to make sure as we introduce the new infra, these are fixed.

**Comment by noumanbsc125** [comment]
my bot training status got stuck , can you please help me to restart it.
URl : https://wit.ai/moidev/MOI_Dev

**Comment by l5t** [comment]
Just restarted.

**Comment by magnusburton** [comment]
Would be appreciated if you could restart my app's training, thanks!

5a3682e4-1781-437e-a59b-25868cf6d299

**Comment by l5t** [comment]
Just restarted

**Comment by hglabska** [comment]
Could you possibly restart my app's training?

5a609d2d-55f5-49fe-908e-84a642528e6b

**Comment by l5t** [comment]
Restarted

**Comment by woprzech** [comment]
I also have a problem with adding new expressions to existing entities. Can you restart training? :)
5a3c0af6-e078-4bde-a7e6-dc3d05d101aa
