### ISSUE TITLE
Enhancement: clarification sentences

### ISSUE THREAD

**Issue by alexdown** [wit-ai/wit#88]
Let's consider the following scenario:
- the first sentence used to call the API is "how much is 500 USD in HKD"
- let's assume there is an intent __fx__ defined with two __amount_of_money__ entities mapped
- the Wit API returns a message with the intent, and the two amount_of_money entities for the source and target currency

Let's assume now the sentence is a bit different, "how much is 500 USD":
- considering there is an intent defined as above, Wit API returns the intent but only one __amount_of_money__ entity
- the client expects an intent with two entities, but the API returns only one
- the client may be intelligent enough to ask the user a clarification question, like "what is the target currency?"
- the user may simply reply, to this new question, "HKD"
- then the client have two sentences, the original
   "_how much is 500 USD_"
  and an additional
  "_HKD_"
  but he doesn't know how to combine them in a way that the Wit API will understand.

There should be a way to correlate two subsequent calls to the API, so that the engine knows that they are "correlated", or "belong to the same dialogue/discussion", and can parse them as a whole.

This may be achieved by reusing the ``msg_id`` returned by the Wit API in each message.
In the above example:

1. a first API call with sentence "how much is 500 USD" returns a ``msg_id``
- a second API call with sentence "HKD" includes the ``msg_id`` returned by 1) above
- Wit API now knows that message 2) is "correlated" with msg 1) (as referred by ``msg_id``) and treat them as a single unit for parsing
- Wit API then returns an intent with two entities, source and target currency: the _source_ was in message 1), the _target_ was in message 2)

**Comment by patapizza** [comment]
Hi @alexdown,

We released a beta version of our Bot Engine to help dealing with dialogue management.
Please see our blog post: https://wit.ai/blog/2016/04/12/bot-engine

Here's our quickstart: https://wit.ai/docs/quickstart
