### ISSUE TITLE
Cannot train wit/thanks intent

### ISSUE THREAD

**Issue by sajat-converge** [wit-ai/wit#882]
Hi,
I am trying to train wit with intent wit/thanks for conversation.
When i give i'm fine thanks..Wit understands this as wit/thanks.
But if i give "i'm fine" only, wit does not return the intent "wit/thanks"
If i manually add intent as "wit/thanks", it gives error as "Could not validate this expression"
Need help on this issue.

Thanking in advance.

**Comment by patapizza** [comment]
Hi @sajat-converge,

* Not sure if "i'm fine" is valid for `wit/thanks`. As an example, if one were to build a bot that would answer "You're welcome!" for any thankful intent, I'm not sure it would behave properly with "i'm fine".
* Do you still experience the issue when trying to validate an expression with `wit/thanks`? Feel free to reopen the issue.

**Comment by sajat-converge** [comment]
hi @patapizza ,

Thanks for the response. 
What i am trying to achieve is - our bot is going to ask, how are you? and the user will respond as "i'm fine thanks". We have trained this "i'm fine thanks" as wit/thanks...once we catch the intent "wit/thanks", the bot is going to answer "great to hear that..now, can i help with some questions?"...
Wit is returning "i'm fine..thanks" as "wit/thanks" intent...

What i  want to achieve is - "i'm fine thanks" and "i'm fine" should return the same intent so that our bot will be able to handle the next step for similar sentences.

For now, we created custom "thanks" intent and trained wit accordingly. Wit did not recognize "i'm fine" as "wit/thanks", but we cannon train "I'm fine" as "wit/thanks".
Can't we train our custom text for default wit intents?

Hope i was clear..

**Comment by patapizza** [comment]
@sajat-converge Thanks for the additional context.

Here it seems that `wit/thanks` doesn't fully cover your use case. I would suggest to complement it with a custom entity for things like `I'm fine`, `I'm good`, etc. that don't have any thankful mention. In your client implementation, you can look for `wit/thanks` and e.g. `feel_good` and answer `Great to hear that!` for both.

Hope this helps.
