### ISSUE TITLE
Wit/Location flopping on common address

### ISSUE THREAD

**Issue by justuseapen** [wit-ai/wit#883]
reporting a *bug*

**What is the current behavior?**

Trying to validate addresses that look like `212 cold spring lane` so that it returns a wit/location entity with "212 cold spring lane".

It's returning a location entity with the string: "spring lane"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Simply send a message with the string "212 cold spring lane" (or any number of variations involving two words, a common road/street suffix (like lane) and 3 or 4 digit house number.

**What is the expected behavior?**

I expect a wit/location entity to include the entire string: "212 cold spring lane"

**What is the App ID where you are experiencing this issue (if applicable)?**
5a1d9424-1a9b-4346-b726-9d42757b80ce

**Comment by patapizza** [comment]
Thanks for reporting @justuseapen.

Indeed, `wit/location` currently only gets the `spring lane` part of `212 cold spring lane`.
As a note, it does gets the full address for inputs `my address is 212 cold spring lane` and `let's go to 212 cold spring lane`.

**Comment by justuseapen** [comment]
Yes. So, I've trained on these terms providing the correct entity selection over 100 times at this point. Is there any better way?

**Comment by patapizza** [comment]
We'll need to look into the model. One thing you can do is validating different examples of addresses in different contexts (i.e. not always `212 cold spring lane`).

**Comment by jtliao** [comment]
Merging with #1615 for tracking
