### ISSUE TITLE
Problems with training HTTP API

### ISSUE THREAD

**Issue by rowanvanekeren** [wit-ai/wit#884]
I have massive problems with training with samples via HTTP API, please fix this!!!
Values appear in my expressions but when i type in the sentence no intent was found.

**Comment by rowanvanekeren** [comment]
btw i'm doing my graduation project with your api, im higly dependable

**Comment by patapizza** [comment]
Hi @rowanvanekeren,

Please use the provided template when submitting an issue. What is your app id?
There is some asynchronous work going on, the result is not immediate. Do you still experience the issue after a while?
If so, please provide as much information as possible in #876.

**Comment by rowanvanekeren** [comment]
hey i did some testing on app-id: 5a21524e-35e1-4ae9-b24c-2cd2092ee907
I know it's async but it still isnt working and i trained an intent hours ago. Like the intent new_haircut i added this to 'intent' with expression (in dutch) 'nieuw kapsel'. i also added other intents via the HTTP API the /samples and everything appears fine but no intent is found when i type 'nieuw kapsel' (new haircut) but it appears in at the intent expressions when i check the intent and it's value

**Comment by patapizza** [comment]
@rowanvanekeren There are many different values defined, with only a few examples. Can you try to limit the number of values, provide more examples for each of them, make sure those work, and then add more, and so on?
