### ISSUE TITLE
Wit responded with status: 400 (Bad Request)

### ISSUE THREAD

**Issue by raphaelgolubev** [wit-ai/wit#886]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
returns an error
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Download the voice message in mp3 format to the pythonanywhere server:
```
url = url.replace('.ogg', '.mp3')
    logo = urllib.request.urlopen(url).read()
    f = open("audio_message.mp3", "wb")
    f.write(logo)
    f.close()
```
2. Initialize:
```
client = Wit(<My server access token>)
```
3. Run the following code:
```
with open('audio_message.mp3', 'rb') as f:
            resp = client.speech(f, True, {'Content-Type': 'audio/mpeg3'})
            result = (str(resp['_text']))
```
An error occurs on this line: 
```
resp = client.speech(f, True, {'Content-Type': 'audio/mpeg3'}) 
```
**What is the expected behavior?**
It was expected that this code will convert the audio message into a text message. And the code does work, but only if it is checked locally on the computer
**What is the App ID where you are experiencing this issue (if applicable)?**
App ID of my application:
5a2d04f8-df66-4631-b9b6-1a784f99e60b

**Comment by patapizza** [comment]
Hi @raphaelgolubev,

Where does it not work? As it is working locally on the computer, this is likely not a Wit.ai issue. If it's related to the Python client, please open the issue [here](https://github.com/wit-ai/pywit/issues).
