### ISSUE TITLE
wit unstable when calling API from IBM serverless

### ISSUE THREAD

**Issue by ivgenyk** [wit-ai/wit#887]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
*bug*

**What is the current behavior?**
When running the wit calls from my computer in debug environment it always works fine and returns a response in 300-1500 msec. 
When using the IBM serverless action it works part of the times and part of the times returns timeout after 60000 msec.
I haven’t found any pattern to when it works and when it doesn’t.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Call wit API from serverless actions in IBM. 
The code I use (Node.js):

`sendMessageToWIT =function (userSays, witToken) {
 var options = {
        method: 'GET',
        url: 'https://api.wit.ai/message',
        timeout: 60000,        
        qs: { v: '20170402', q: userSays },
        headers:
        { authorization: `Bearer ${witToken}` }
    };
    console.log ("calling wit")
    return new Promise((resolve, reject) => {
        request(options, function (error, response, body) {
            console.log("**** wit response received")
            if (error) {
                console.log ('* wit parsing failed !!!!')                
                console.log (error)                
                 reject(error)
            } else {
                console.log ('* wit parsing done')
                resolve(JSON.parse(body));
            }
        })
    })
}
`
**What is the expected behavior?**
Response either good or bad in a reasonable time window (<60 sec)

**What is the App ID where you are experiencing this issue (if applicable)?**
58f78897-87a3-41f5-8d54-6c5150497ac4

**Comment by blandinw** [comment]
Your code looks correct and we don't do any special treatment for IBM serverless actions.
To debug this further and understand where the problem lies, we'd need to have low-level information about connection events (DNS resolution, TCP handshake, SSL handshake, etc.).

Do other endpoints/services work correctly? Can you reliably reach `https://api.wit.ai/ping`?

**Comment by ivgenyk** [comment]
I am trying right now to see if IBM serverless team will have some valuable input on this issue and if they can retrieve the logs for the low-level information.

**Comment by patapizza** [comment]
@ivgenyk Any update?

**Comment by ivgenyk** [comment]
IBM guys worked on this issue. It is resolved for now. Works properly.
