### ISSUE TITLE
[Built-in NLP] Bug: Facebook is dropping location entities

### ISSUE THREAD

**Issue by gonzo-oin** [wit-ai/wit#888]
When I use the Facebook integration, the location entity is not detected on same requests that works when I use the Wit API or the website.
 
I make screenshots that show request from Facebook on my local ngrok dashboard without the location entity and other screenshots that show wit.ai API and website works.
![ngrok](https://user-images.githubusercontent.com/1376242/34058364-0d2d7d60-e1db-11e7-87ab-707b25b4136b.png)
![wit.ai API](https://user-images.githubusercontent.com/1376242/34058367-133c1f40-e1db-11e7-90b9-8bc60e57239b.png)
![wit ai website](https://user-images.githubusercontent.com/1376242/34058373-17d9b242-e1db-11e7-8af7-2aa4c1ca9c97.png)

Any suggestions ?

**Comment by gonzo-oin** [comment]
I have also created a issue on Facebook, maybe the issue is on their side. 
https://developers.facebook.com/bugs/1806680956049597/

**Comment by stopachka** [comment]
Hey @gonzo-oin -- it looks like wit/location came in as an autosuggest entity, which means that this was not yet added into your app. Testing your app now, I can see that location returns for both now.

Could you confirm?

As an aside, it was a bug that you got back the location entity in your jsfiddle example. If you are able to repro this, with the autosuggest: true in the response, please send me your jsfiddle (stopachka [at] fb [dt] com)

**Comment by stopachka** [comment]
(closing for now -- please reopen if this is still an issue)
