### ISSUE TITLE
Metadata change in PUT request not reflected in API

### ISSUE THREAD

**Issue by prihoda** [wit-ai/wit#889]
When updating keyword entities using the PUT request, metadata field update is not reflected in API /message.

After issuing the PUT request, all values and expressions of the entity are successfully updated, they are visible in the GUI. Also, when I open the Edit metadata tooltip, I see the updated value. 

However, the /message API still returns the old metadata, until I manually edit and save the input field in the GUI.

App ID 59e9198d-acc6-4008-8c50-64c6882eac8a, e.g. entity 'tag'

**Comment by psquared2** [comment]
Bump - same here

App ID 5a5f65cf-78ea-4382-b2a9-ea0a85c456d0, e.g. entity "keywords"

**Comment by stopachka** [comment]
looking into this -- apologies for the bad experience. Will update with what I find here
