### ISSUE TITLE
Inbox content as API route

### ISSUE THREAD

**Issue by fbatschi** [wit-ai/wit#891]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
feature request

**What is the current behavior?**
There is no HTTP API route that gives you all the data that you get in the web GUI under "Inbox"

**What is the expected behavior?**
I want a route, that delivers the data as the Inbox does.

Inspecting the network requests, there is an https://api.wit.ai/inbox route which delivers the data for the Inbox in the GUI - but this can not be called with a Server Access Token to handle it.

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
