### ISSUE TITLE
thread_id param in GET /message not used?

### ISSUE THREAD

**Issue by pintux** [wit-ai/wit#893]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
maybe a bug

**What is the current behavior?**
calling a GET /message with thread_id param set doesn't result in having a correlated thread_id property in the response.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. call a GET /message with thread_id query param set;
2. analyze JSON response: thread_id is missing

**What is the expected behavior?**
JSON response expected to have a thread_id property set to the value sent in the request. 

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by l5t** [comment]
Thanks for reporting. We currently don't support returning the thread_id in the response as this is an optional id you can pass on your side. What will be your use case?

**Comment by pintux** [comment]
Just deciding how to correlate messages in a "conversational session" with a user. Thus I thought to use thread_id to correlate messages from a user and responses from Wit in the same "conversation"

**Comment by l5t** [comment]
Yes you can use thread_id exactly for that and it will group the messages in the Logs section.
