### ISSUE TITLE
contact entity needs some filtering

### ISSUE THREAD

**Issue by bmcclenahan** [wit-ai/wit#894]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
the built-in contact entity frequently returns grammatical elements like prepositions and articles (on, the) from the text

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Who's on the roster on December 31
returns who on and the as contact entity values

**What is the expected behavior?**
the contact entity should filter out values that are obvious grammatical elements

**What is the App ID where you are experiencing this issue (if applicable)?**
58aecb8b-e2a7-46ff-8f5d-3a04e81575ac

**Comment by patapizza** [comment]
Thanks for reporting @bmcclenahan, I'll improve the model soon.

**Comment by patapizza** [comment]
@bmcclenahan This is now fixed.

**Comment by bmcclenahan** [comment]
the contact entity is still a bit indiscriminate and greedy about what it claims in a sentence.
Who's on the service team tonight? returns Who's as a contact
Who is on the service team tonight? returns service team as a contact

contact is very important to my application, and it's just too variable. most times it's very accurate and trustworthy and then all of a sudden it it's just random and rubbish.

I'm having to cover these in code exceptions, and if I need to write many more, it's not going to be worth using wit - I may as well just do it all in code.

**Comment by blandinw** [comment]
cc @patapizza to have a look at feasibility
@bmcclenahan it would be helpful to have more erroneous predictions to find patterns

**Comment by patapizza** [comment]
@bmcclenahan I feel you. I'll look into improving `wit/contact` this week. It would help a lot if you can provide a bunch of false positives. Thanks!

**Comment by bmcclenahan** [comment]
I'll see what I can find
I have a feeling that I've retrained some of them and thus the trace of the error has gone
Bruce
________________________________

**Comment by bmcclenahan** [comment]
Some samples of contact being returned incorrectly

[
{
"entities":
{
"planitem":
[
{
"confidence":
1
"start":
16
"end":
20
"body":
"
plan
"
"value":
{
"value":
"
plan
"
}
"entity":
"
planitem
"
}
]
"contact":
[
{
"confidence":
0.9315
"start":
8
"end":
15
"body":
"
service
"
"value":
{
"value":
"
service
"
}
"entity":
"
contact
"
}
]
"intent":
[
{
"confidence":
0.99992361664161
"value":
{
"value":
"
service_query
"
}
"entity":
"
intent
"
}
]
}
"confidence":
null
"_text":
"
See the service plan
"
"intent":
"
default_intent
"
"intent_id":
"
default_intent_id
"
}
]

{
"entities":
{
"datetime":
[
{
"confidence":
0.961075
"start":
20
"end":
27
"body":
"
tonight
"
"value":
{
}
"entity":
"
datetime
"
}
]
"planitem":
[
{
"confidence":
0.99594153298319
"start":
11
"end":
15
"body":
"
plan
"
"value":
{
"value":
"
plan
"
}
"entity":
"
planitem
"
}
]
"contact":
[
{
"confidence":
0.93691
"start":
0
"end":
6
"body":
"
What’s
"
"value":
{
"value":
"
What’s
"
}
"entity":
"
contact
"
}
]
"intent":
[
{
"confidence":
0.99981033913868
"value":
{
"value":
"
service_query
"
}
"entity":
"
intent
"
}
]
}
"confidence":
null
"_text":
"
What’s the plan for tonight?
"
"intent":
"
default_intent
"
"intent_id":
"
default_intent_id
"
}
]


[
{
"entities":
{
"datetime":
[
{
"confidence":
0.9648375
"start":
15
"end":
25
"body":
"
on tonight
"
"value":
{
}
"entity":
"
datetime
"
}
]
"contact":
[
{
"confidence":
0.85268
"start":
0
"end":
5
"body":
"
Who’s
"
"value":
{
"value":
"
Who’s
"
}
"entity":
"
contact
"
}
]
"position":
[
{
"confidence":
0.75470433635482
"start":
6
"end":
14
"body":
"
rostered
"
"value":
{
"value":
"
roster
"
}
"entity":
"
position
"
}
]
"intent":
[
{
"confidence":
0.99999990521053
"value":
{
"value":
"
roster_query
"
}
"entity":
"
intent
"
}
]
}
"confidence":
null
"_text":
"
Who’s rostered on tonight?
"
"intent":
"
default_intent
"
"intent_id":
"
default_intent_id
"
}
]


[
{
"entities":
{
"datetime":
[
{
"confidence":
0.9651
"start":
15
"end":
23
"body":
"
tomorrow
"
"value":
{
"value":
"
2017-12-31T00:00:00.000-06:00
"
}
"entity":
"
datetime
"
}
]
"contact":
[
{
"confidence":
0.90841
"start":
0
"end":
5
"body":
"
Whose
"
"value":
{
"value":
"
Whose
"
}
"entity":
"
contact
"
}
]
"position":
[
{
"confidence":
0.98895446748051
"start":
9
"end":
14
"body":
"
sound
"
"value":
{
"value":
"
sound
"
}
"entity":
"
position
"
}
]
"intent":
[
{
"confidence":
0.98819787931465
"value":
{
"value":
"
roster_query
"
}
"entity":
"
intent
"
}
]
}
"confidence":
null
"_text":
"
Whose on sound tomorrow
"
"intent":
"
default_intent
"
"intent_id":
"
default_intent_id
"
}
]

**Comment by patapizza** [comment]
This is now fixed.

**Comment by bmcclenahan** [comment]
Thanks guys
________________________________
