### ISSUE TITLE
'Destroy app' should require password/verification

### ISSUE THREAD

**Issue by EnderCrypt** [wit-ai/wit#896]
Hello, i got an idea/feature

currently destroying a whole app takes 2 button presses by.. well, almost anyone that have access to your computer

![current behavior](https://image.prntscr.com/image/RnOa4SxjR_2boq2p445jSg.png)

i do think wit.ai should take the path of many other services/api's where the service requires the user to type in a password or in some other way verify that they are truly the owner of the app, not just 'be logged in', this would also ensure that there's ABSOLUTELY no way to accidentally delete an app

**Comment by patapizza** [comment]
Hi @EnderCrypt,

Thanks for the suggestion.

As developers log in through OAuth (using their Facebook or GitHub account), there is no password we could use. There are other ways we could do that (e.g. 2FA).

This feels more like a nice-to-have and we currently aren't able to prioritize this. Adding an internal note and closing.
