### ISSUE TITLE
How to use wit.ai bot to sql query databases to get answer for user's question?

### ISSUE THREAD

**Issue by chenprogrammer** [wit-ai/wit#900]
Hello, 
I have a question about wit.ai, I do not know if should post this question here.

I want to use wit.ai to build a college query chatbot. Students can ask question to this chatbot. The chatbot will use mysql to search three databases (created by the school) then return the information to users.

I only can find the demonstration without using databases. Can somebody show me how to do it?

Thank you!

**Comment by patapizza** [comment]
Hi @chenprogrammer,

Wit.ai can help in [categorizing the intent](https://wit.ai/docs/recipes#categorize-the-user-intent). One setup could be to have for each question/answer pair, have a different intent value. On the client side one could then match the intent value with the answer.

Hope this helps.
