### ISSUE TITLE
An issue of creating a new intent

### ISSUE THREAD

**Issue by chenprogrammer** [wit-ai/wit#901]
For example, I want to add an intent of "study"

When I type the "study" for intent, it supposed to show "study" in window, but instead it showed "Create new value "study" ".

Is it normal? It is different than demonstration.

**Comment by patapizza** [comment]
Hi @chenprogrammer,

Please use the provided template. What is your app id?

Did you already have a validated sample with the value "study"?

**Comment by patapizza** [comment]
@chenprogrammer Feel free to reopen if you still experience the issue (please provide more info).
