### ISSUE TITLE
Expose API for Validation of Expressions in an Entity

### ISSUE THREAD

**Issue by Hyperclaw79** [wit-ai/wit#904]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Feature
**What is the current behavior?**
No scope to perform the validation through API

**What is the expected behavior?**
An API method to validate all the expressions of an entity or by `message_id` or by range, etc.

_P.S._ Sorry about opening so many issues at once. 😅

**Comment by blandinw** [comment]
That's what POST /samples is for.
Closing for now, please comment/reopen if I missed something!
For keywords entities, you can also use POST and PUT /entities

**Comment by Hyperclaw79** [comment]
I was referring to the messages we validate via the inbox tab.
