### ISSUE TITLE
Can't export data

### ISSUE THREAD

**Issue by individual11** [wit-ai/wit#907]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
*bug*

**What is the current behavior?**
```
{
error: "Something went wrong. We've been notified.",
code: "wit"
}
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Just go to your settings and click on _Download .zip with your data._

**What is the expected behavior?**
To get the zip file for backup purposes.

**What is the App ID where you are experiencing this issue (if applicable)?**
583273ad-575f-4ad3-a801-fe95d236ce57

**Comment by blandinw** [comment]
@individual11 thank you for the feedback, we're looking into it.

**Comment by aforaleka** [comment]
@individual11 Thanks for reporting! The problem's been fixed and you should be able to export your app now.
