### ISSUE TITLE
after training intent expressions dissapear

### ISSUE THREAD

**Issue by rowanvanekeren** [wit-ai/wit#908]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

--BUG--

After training samples like: "i want a plane from new york to berlin" where "new york" connected with entity "flight_form" and berlin with entity "flight_to" the entire sentence disapears from the list when i want to get all intent expressions from the intent "flight_request"

i did this explanation in english but my test app is in Dutch:

intent (flight_request) = vliegtuig_aanvragen
flight_from = vliegen_vanaf
flight_to = vliegen_naar

Im using curl to get the wit intent content to my app

So why do expressions disapear after training with entities?

**What is the App ID where you are experiencing this issue (if applicable)?**
5a4f9b65-8a15-4194-9d69-084531222353

**Comment by patapizza** [comment]
Hi @rowanvanekeren,

Can you share the exact samples (in Dutch) that are missing?

**Comment by rowanvanekeren** [comment]
i deleted my app and started over. can you see the sentences in my wit account. because they are still there but the http api doesnt send them with the request. I reqognized that it only happens when an entity has lookups 'keywords'and 'freetext' is i only use 'keywords' they dont dissapear

**Comment by rowanvanekeren** [comment]
sorry i was not really clear. i made a new app with id: 5a5b9e46-50b5-41d6-8985-fae56ca23e57 with the same problems when training sentences with entities wit the lookup type keywords and freetext. the are trained but when i do a request to get all the expressions they dont get send along with the request

**Comment by patapizza** [comment]
This is the expressions I see for `flight_request`:

![](https://i.imgur.com/yFYNndF.png)

Which expressions are you missing? Are you trying from the UI or the API (if so, what request)?

Thanks.

**Comment by rowanvanekeren** [comment]
yeah it is there, but when you train them with entities "flight_from" and "flight_to". After you trained them they dont get send over http api anymore ( the expressions of flight_request )

**Comment by patapizza** [comment]
@rowanvanekeren Please be more explicit: what is the expression? What is the expected output (which entities)? What is the actual output?
