### ISSUE TITLE
Keywords automatically detecting correct keyword when entity is added

### ISSUE THREAD

**Issue by magnusburton** [wit-ai/wit#909]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Feature request/bug

**What is the current behavior?**
At the moment if I have the sentence

> I want to fly to New York

and it only detects `New York` as a location. When I add `fly` as entity `transport` (where transport is of type keywords and there's a keyword **airplane** with synonym **fly**) I manually have to go into the drop-down selector and pick the correct keyword.

I've only found this to happen while inside composite entities (see pic where the value of `buss` is a synonym for keyword `bus` in `transport` entity) but it's time-consuming to go through and select the correct keyword. If I do a mistake a new keyword is created and I have to go to the understanding tab and remove the new keyword etc.

![Example picture](https://i.imgur.com/prlPN1R.png)

**What is the expected behavior?**
Would be great if when an entity is added to a sentence it'd go through the keywords and their corresponding synonyms and find a match. If no match found, offer to create new value.

**Comment by stopachka** [comment]
Great point @magnusburton! Will add this on the roadmap
