### ISSUE TITLE
Swedish datetime parser fails in certain situations

### ISSUE THREAD

**Issue by magnusburton** [wit-ai/wit#910]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug report

**What is the current behavior?**
The Swedish DateTime parser fails when we have a date followed by time in the following format. In Swedish it's common to prepend the time part of the DateTime object by `kl.` or `kl` (see below).

`2018-02-28 kl 16:00`
`2017-06-19 kl 7:00` (in the am)
`2017-05-2 kl. 07:00`

(see the following picture)
![Example picture](https://i.imgur.com/6OGsjqx.png)

**What is the expected behavior?**
It works if we were to remove `kl.` and `kl` from the object:

`2018-02-28 16:00`
`2017-06-19 7:00` (in the am)
`2017-05-2 07:00`

it works..

**What is the App ID where you are experiencing this issue (if applicable)?**
/magnusburton/Lisa_Disturbances

**Comment by patapizza** [comment]
Thanks for reporting, will look at this tomorrow.

**Comment by patapizza** [comment]
@magnusburton This is now fixed.
