### ISSUE TITLE
datetime: next Monday [or other day] should return options

### ISSUE THREAD

**Issue by individual11** [wit-ai/wit#911]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
mostly a feature, but my customers think it's a bug ;-)

**What is the current behavior?**

When I pass in "next monday", the response will be the datetime for the _next_ Monday that occurs, with no optionals. If I pass in "monday", it returns the _next_ Monday with the previous and the following, so three options. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

Over 50% of my customers when using "next monday" actually mean "monday after next". I think it's just a colloquialism, but it would be great for the datetime to return 2 options; 1 for the next monday, and one for the monday after next, allowing me to confirm with my customer.

Let me know if this doesn't make sense, would be happy to discuss further.

**Comment by l5t** [comment]
good point. what do you think @patapizza?

**Comment by patapizza** [comment]
@individual11 This is a Duckling issue. Can you pitch in https://github.com/facebook/duckling/issues/44?

Thanks.
