### ISSUE TITLE
No classification in new app

### ISSUE THREAD

**Issue by ivgenyk** [wit-ai/wit#913]
*bug*

I created a new app using the UI, and trained it using the API on trait entities.
I can see all the data in the UI and it shows a green light saying "Status: Clean All your changes have been taken into account.". When trying to classify using API the answer is empty, using the UI is no better.

app ID: 5a54cf62-97cf-44ac-be9f-cc76dca76608

**Comment by patapizza** [comment]
@ivgenyk What is the input text that doesn't work? What is the expected response?

**Comment by ivgenyk** [comment]
Now when I test it (after a couple of days) I receive a valid response (very bad classification, but a valid response non the less). 
* Is there a reason why it didn't work for the first few hours?
* Do you know why it started to work now?

The testing expression - result:
The expression I used is: "What mortgage types do you have?"
The expected response is:   "entities": {
        "intent": [
            {
                "confidence": 0.8,
                "value": "FAQ Interest Rates"
            }]}

**Comment by stopachka** [comment]
Hey @ivgenyk, the issue was most likely related to https://github.com/wit-ai/wit/issues/879.

When you said "API for train entities", did you use `POST /samples?` or `POST https://api.wit.ai/entities/$ENTITY_ID/values`

Re: why it did not work then, but worked now
- Depending on the size of the dataset, it is possible that there was an issue where the training took a long time, but reported green in the meantime
  - if you can report in the master task, a time window of when the issue happened, as well as the answer to the question above, it would be helpful
   - We working on migrating to a new training infra, that will reduce this kind of error

For the very bad classification
- If you could give examples of what you expected during certain sentences, happy to take a look :)

**Comment by ivgenyk** [comment]
1. I used POST / samples. The database included ~400 samples for 23 classes. All classes are in the same entity (intent) and different values. The UI training indicator was green right away (it seems like a bug unless you train in less than a few minutes).
2. The training was performed several hours before my first message (2-5 hours).  Sometimes after "2018-01-11T11:05:51.006Z" . Unfortunately, I haven't saved the exact time.
3. One example of bad classification is:
sentence: What mortgage types do you have?
result: "entities": {
        "intent": [
            {
                "confidence": 0.28469981768863,
                "value": "FAQ Interest Rates"
            },
            {
                "confidence": 0.22604129748104,
                "value": "FAQ Mortgage Types"
            }]...
The correct result is: "FAQ Mortgage Types"
one of the training sentences:  what different mortgage programs do you have? - very similar to the query.

I also tried classifying with another API classifier and it returned the correct class with confidence over 0.8.

**Comment by patapizza** [comment]
@ivgenyk I'm confused. You first said that the correct response for `What mortgage types do you have?` is `FAQ Interest Rates` and now you're saying it is `FAQ Mortgage Types`. Which one is it?

The insights don't look too bad and trying another couple of inputs closer to the trained one:

![](https://i.imgur.com/xtKONaK.png)
![](https://i.imgur.com/5HZfJyD.png)
![](https://i.imgur.com/Yriy9AZ.png)

It looks like for the classifier, `What mortgage types do you have?` is not very similar to `what different mortgage programs do you have?`. Let's look into why.

There are a few sentences of the following form for `FAQ Interest Rates`:
`What are your *?`
`What * do you have?`
`Show me your *`

But none for `FAQ Mortgage Types`. And indeed, replacing `rates` by `mortgage types` doesn't give good results.

For `FAQ Mortgage Types`, it seems like the words `programs` and `different` are present in a few examples. As a result, the following inputs work slightly better:

![](https://i.imgur.com/NAP8MRL.png)
![](https://i.imgur.com/RUUOKXe.png)

So it seems like the dataset is a bit unbalanced. We'd like to provide better tooling to highlight that.

Have you tried validated a few examples in the forms above for `FAQ Mortgage Types` like `What are your mortgages types?`, `What mortgages types do you have?`, `Show me your mortgage types` to see if it helps?
Also curious which other API classifier have you tried that worked for this specific example (is it working for other example as well?).
