### ISSUE TITLE
What's the proper way of identifying multiple free text entities?

### ISSUE THREAD

**Issue by NicolasLevaique** [wit-ai/wit#914]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question: We're trying to build a widget to show some stats from a user sentence. A widget can have: 
- insights (ie the stats you want to show)
- timerange
- breakdowns (ie stats of all items grouped by attribute X)
- filters (ie stats only for items with the attribute X having the value A)

Our issue is that there are a lot of different filters possible and some of them need to be "free-text" entities (like names for example). Since they are all filters, they are more or less always used in the same context in a sentence - so they should be an entity. 

But at the same time, we need to be able to filter on attribute X having the value A or B. So we need to have an entity "attribute X" with possible values A, B or free-text. 

How should we proceed to be able to extract the proper filter (attribute X) and the filter's value (A, B or free-text)? Using multiple entities seems to be the only option but will it be possible to train the app enough?

How should we proceed? 

**What is the current behavior?**
We haven't trained our app too much (because we aren't sure how to get started) but it often mistakes distinct entities.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**
5a2d7e39-1eec-4871-b0a9-8bd27a018b46

**Comment by l5t** [comment]
Thanks for sharing the details. Can you provide a few examples of queries you would want to parse?

**Comment by NicolasLevaique** [comment]
It would be something along the lines of: 

"how many conversions do I have in France" where "conversions" is the insights and "France" is the filter (no timerange nor breakdown here)

"how many installs do I have on Android this week?" where "installs" is the insights, "Android" is the filter and "this week" is the timerange (no breakdown here)

"which campaigns are doing the most purchases this month on mobile?" where "campaigns" is a breakdown, "purchases" is the insights, "this month" the timerange and "mobile" is the filter

Thanks,
Nicolas

**Comment by patapizza** [comment]
Hi @NicolasLevaique,

One idea to try is to use `insights` and `breakdown` entities as `traits`. Each filter could be a different `free-text & keywords` entity (including built-ins like `wit/location` or `wit/contact`), and on your side, have a mapping of possible entity filters for the insights, then look into the ones detected. For timerange, use `wit/datetime`.

Would this work?
