### ISSUE TITLE
Adding messages to inbox

### ISSUE THREAD

**Issue by rodzzlessa24** [wit-ai/wit#916]
Currently I'm trying to add messages to my inbox so I can train them later on. However, no messages are actually being added to my inbox. I'm sending messages over the HTTP API and getting back a 200 OK everytime. Do messages take a while to propagate in the inbox or is this an issue? My app ID is: 5a55b393-7d15-4058-91bc-dc9936bc6f98
. Thank you!

**Comment by stopachka** [comment]
Hey @rodzzlessa24, looking at this app, I am able to see inbox items at this point in time. Could you confirm? If not, could you send me a full screenshot of what you see?

**Comment by rodzzlessa24** [comment]
I checked the app and there were only about 15 items in the inbox. I know I sent over 150. Is there a limit or filtering process of which api request make it to the inbox? I did a screen recording of a me running a simple program that talks to the wit api. It then prints the api's response to the console just to show that the request is working correctly. I then go back to my inbox and refresh but not items are in my inbox. https://drive.google.com/file/d/1FzUimAJsYphOhmnxIhZjEntWcNpXntQe/view?usp=sharing

**Comment by l5t** [comment]
Not sure if this will answer this, but note that if you validate already a sentence, it won't show up in the Inbox anymore. You can find them in the Logs section though

**Comment by patapizza** [comment]
@rodzzlessa24 I see the inbox is empty now. Do you still experience the issue? Can you try sending a **new** sentence and confirm you see it in the inbox?

Thanks.

**Comment by patapizza** [comment]
@rodzzlessa24 Feel free to reopen if you still experience the issue.

**Comment by kgarwal04** [comment]
Hi. I am still facing this issue. For instance, if I send 10 messages only 2 or 3 of them appear in inbox. The response code is 200 and the confidence level is also less than 1.00 for all the 10 messages. I was wondering, how much time should I wait for all the messages to appear in my inbox?

**Comment by patapizza** [comment]
Hi @kgarwal04, what is your app id? What are the messages you expect to see?
Just to be sure, validated messages don't show up in the Inbox.

**Comment by blandinw** [comment]
We do throttle what gets in your inbox. We do not guarantee all messages end up in the inbox. This is to avoid abuse. We will revisit our throttling thresholds in the near future.

**Comment by kgarwal04** [comment]
What is the current throttling threshold?

**Comment by blandinw** [comment]
The new threshold is maximum of 20 messages inboxed in a 10 minute window. We reserve the right to change this depending on system loads and individual app abuse, but we're considering increasing these numbers in the future.
