### ISSUE TITLE
Feature: Add ability to preview API output while training wit using sentences/examples on the web console

### ISSUE THREAD

**Issue by JibranKalia** [wit-ai/wit#917]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
feature
**What is the current behavior?**
Currently while training wit on the web console under the "Understanding" tab there is no option to view the JSON API output. That feature is however present in the "Inbox" tab.

**Comment by l5t** [comment]
Thanks for requesting this. It's on our roadmap and we hope to release it soon

**Comment by l5t** [comment]
We just released it ;-) 
![image](https://user-images.githubusercontent.com/6992759/35172930-78d99de2-fd1e-11e7-9f59-85d320b63efb.png)
