### ISSUE TITLE
What is the max number of items in each Wit entity?

### ISSUE THREAD

**Issue by khanhpv** [wit-ai/wit#919]
Hi,
I created an entity with over 1000 items. But, when query the exactly the item inputted, Wit does not understand it.
I want to know if a limitation existing on Wit entity.

Thank you

**Comment by l5t** [comment]
What type of entity (i assume keyword)? can you provide your app id and step to repro?

**Comment by khanhpv** [comment]
This is my app: https://wit.ai/khanhpv/botv20181/entities/mwg_ward
The entity type is freetext  & keyword.
Step: when I input "Hoài Châu, Hoài Nhơn, Bình Định", it doesn't detect "Hoài Châu" as inputted data, and displays "Create new value "Xã Hoài Châu"", although "Xã Hoài Châu" is an inputted data, and has "Hoài Châu" as Synonym.
The entity "mwg_ward" has over 11.000 entities.
![image](https://user-images.githubusercontent.com/3120540/34901602-10af7856-f83f-11e7-8a63-d38fd45a1ec3.png)

**Comment by stopachka** [comment]
Hey @khanhpv 

If I remember correctly, after 1000 entity vlaues, we no longer support keyword matching, and rely strictly on free-text. I'll look into this deeper and update you

**Comment by khanhpv** [comment]
@stopachka how's it going? Did you have any update?

**Comment by patapizza** [comment]
@khanhpv: There is no limit and `Hoài Châu` is correctly extracted with a value of `Xã Hoài Châu`.
The UI suggests to create a new value since `Hoài Châu` is not an exact synonym.
Actually this is what I see:

![](https://i.imgur.com/yYRJ98C.png)

**Comment by khanhpv** [comment]
I have rechecked and everything looks good. Thanks for your supports
