### ISSUE TITLE
Adding synonyms for a keyword using curl request

### ISSUE THREAD

**Issue by naman21** [wit-ai/wit#920]
I would like to ask how will we add multiple synonyms for a keyword using the wit HTTP curl requests. Please specify the code. 

Thanks.

**Comment by stopachka** [comment]
Hey @naman21 

You have two options:


1. POST /samples

```
curl -XPOST 'https://api.wit.ai/samples?v=20170307' \
  -H "Authorization: Bearer $TOKEN" \
  -H "Content-Type: application/json" \
  -d '[{
        "text": "I want to fly to san fran",
        "entities": [
          {
            "entity": "airport",
            "start": 17,
            "end": 28,
            "value": "sfo"
          }
        ]
      }]'
```

Because your value is different from what is in the sentence, now "san fran" (start: 17, end: 28)  will be a synonym of "sfo"
 
2.  POST https://api.wit.ai/entities/$ENTITY_ID/values/$ENTITY_VALUE/expressions


```
 curl -XPOST 'https://api.wit.ai/entities/airport/values/sfo/expressions?v=20170307' \
  -H 'Authorization: Bearer $TOKEN' \
  -H 'Content-Type: application/json' \
  -d '{"expression":"san fran"}'
```
