### ISSUE TITLE
Speech recognition error

### ISSUE THREAD

**Issue by sai28593** [wit-ai/wit#923]
**What is the current behavior?**
speech_recognition.RequestError: recognition connection failed: [Errno 11001] getaddrinfo failed

**What is the expected behavior?**
Text from api

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by l5t** [comment]
Do you experience this consistently? Can you share some details on how you call wit? it seems like an integration issue

**Comment by patapizza** [comment]
@sai28593 Feel free to reopen if you still experience the issue.
