### ISSUE TITLE
Extremely low recall/precision for user defined entities.

### ISSUE THREAD

**Issue by d-p-s** [wit-ai/wit#924]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**

I have trained my app programatically via POST /samples with a few hundred examples. For three of my user defined entities, (feature, type and loc) recall and precision are extremely low, < 0.2%. I previously trained another app using the same program and got good results, so I think something's not working as it should. Looking in the expressions for each of these entities, there are many labelled expressions from the samples I posted, so I'm pretty sure that my program is functioning as expected.

On a side note, when I view the logs nothing is there and the message says "No Logs Yet We haven't received an API request from you yet. Bring your app to life, go over to thesettingspage, and make a cURL request!". I'm not sure if the logs are supposed to show data submitted via POST / samples but I thought I'd mention it just in case.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

To reproduce I created a fresh app, and posted a few hundred samples with my program. Beyond that I'm not sure how to describe steps to reproduce - I could post the program but I doubt you want to read my code! Let me know if you want any further information.

**What is the expected behavior?**

The expected behaviour is that there would be quite a high level of precision and accuracy for these entities.

**What is the App ID where you are experiencing this issue (if applicable)?**

5a5d5010-bf8f-4fb0-befe-24d5903f8fc2

**Comment by patapizza** [comment]
Hi @d-p-s,

It seems like there was an off-by-one error in the `end` of these entities, for all posted samples. Can you try reimporting your app after fixing that to see if you get better insights?

Feel free to reopen the issue if that didn't help.

**Comment by d-p-s** [comment]
Jeez how embarrassing! That sorted it out. Thanks for your help!
