### ISSUE TITLE
Feature request: GET /entities/:entity_id/:entity_value should return corresponding samples

### ISSUE THREAD

**Issue by rowanvanekeren** [wit-ai/wit#927]
hey i want to know a better way of getting the list of expressions from an intent. now i get all the values in one request. but i just want one value with all it's expressions. is this possible?

**Comment by testfrancis22** [comment]
Not currently, you will have to use GET https://api.wit.ai/entities/$ENTITY_ID and filter by value of entities. Returns all the expressions validated for an entity. We currently limit to the first 1000 values (with the first 50 expressions). Can you share why you would need it?

https://wit.ai/docs/http/20170307#get--entities-:entity-id-link

**Comment by rowanvanekeren** [comment]
i made an conversational app with wit.ai so when i want to train an intent it goes like.
![image](https://user-images.githubusercontent.com/14889876/35040124-4cd057d0-fb80-11e7-872c-bf42b3fcca26.png)

and then if i want to train i goes like:

![image](https://user-images.githubusercontent.com/14889876/35040169-72f67d90-fb80-11e7-9594-73eb3277b090.png)


So it would be usefull if i can get the single intent value so i not have to get them al and loop through them.

(btw this is part of my graduation project, no commercial use)

**Comment by MathieuDuboy** [comment]
+1 ! It will be very useful to add this feature cause this is very long to query all the intent values and then filter by value :(

**Comment by hactar** [comment]
@rowanvanekeren What interface is that on your screen shots? Is that part of your grad project or some website/framework?

**Comment by rowanvanekeren** [comment]
hey @hactar i made this website as a grad project. But when people are interested i can make it public so they can make conversational chatbots. But need to do some language support...

**Comment by blandinw** [comment]
We're tracking this as a feature request. No ETA yet, we'll implement if there's a strong need for this. The workaround for now is to use the regular GET /entities/:entity_id API and filter on your side.

**Comment by jtliao** [comment]
This is now possible using https://medium.com/wit-ai/introducing-get-samples-a7ffbe189445
