### ISSUE TITLE
Could not validate this expression message is displayed.

### ISSUE THREAD

**Issue by osvald0** [wit-ai/wit#928]
HI, I'm trying to add examples to my app and when I press "Validate" button the platform displays the following message: "Could not validate this expression".

See screenshot for more information.

<img width="1662" alt="screen shot 2018-01-18 at 2 20 40 am" src="https://user-images.githubusercontent.com/20977158/35082096-c56b008e-fbf6-11e7-94c8-193b7b511a5a.png">

Thanks!

**Comment by l5t** [comment]
Tracking here https://github.com/wit-ai/wit/issues/929
