### ISSUE TITLE
`Could not validate this expression` during app's training.

### ISSUE THREAD

**Issue by Saurabh3333** [wit-ai/wit#929]
`Could not validate this expression` during app's training. But it is normally working when we manually select the intent rather than using the suggested intent before validating.

Thanks.

**Comment by zereth7** [comment]
Also experiencing this issue, console reports internal server errors and "sync failed". guessing something in the front-end deals with the automatically filled fields differently from the manual ones and that breaks it. 
if you have some of each they are also noticeably offset from each other (manual ones have the drop down shifted slightly to the right). not sure if that's part of the issue or a feature i didn't notice before.

**Comment by NicolaCastellaniTB** [comment]
{"body":"wit the hell?"} this is the response from server side, I think they have some issues on server side, waiting for the fix!

**Comment by AlexandreRgx** [comment]
Same issue. It's only working when you close the "intent field", then you have to add it again with your expected value.

**Comment by NicolasLevaique** [comment]
Same issue here!

**Comment by gregs007** [comment]
Same issue

**Comment by individual11** [comment]
Same issue here. Also unrelated, people need to add some avatars to their github IMHO.

App ID - 583273ad-575f-4ad3-a801-fe95d236ce57

**Comment by hweiler** [comment]
We've been experiencing the same issue today as well. It only seems to work if we remove the suggested values and manually add the intent and other values.

**Comment by l5t** [comment]
Thanks for reporting. We are investigating and will update you when fixed

**Comment by patapizza** [comment]
Fix on its way.

**Comment by patapizza** [comment]
This is now fixed. Sorry for the inconvenience!
