### ISSUE TITLE
Exclude "apostrophe s" (Example Asha's -> Asha) from wit/contact entity

### ISSUE THREAD

**Issue by nikskhubani** [wit-ai/wit#930]
Is there any better way to exclude "apostrophe s" (Example Asha's -> Asha) from Wit/contact entity detection. For example, if a user ask question like;

How is Asha's availability today? 

at present wit/contact is getting "Asha's" in the detected entity value. However we want it to ONLY return Asha and not Asha's.

Possible?

**Comment by patapizza** [comment]
@nikskhubani That's a good point. Let me see if we can fix this easily.

**Comment by patapizza** [comment]
@nikskhubani We'll need to improve the model at some point. Until then you can implement the workaround on your end.

**Comment by ashokpatsamatla** [comment]
@patapizza - Has there been any update on this? We have been getting the same issue with wit/contact not being able to identify names when used with apostrophe.

**Comment by patapizza** [comment]
Let's group the discussion in #853.
