### ISSUE TITLE
Validating inbox messages

### ISSUE THREAD

**Issue by alexeymkh** [wit-ai/wit#931]
Hello! Yesterday I transfered ownership of my app to another person.
After that validating of messages became broken in my Inbox and in new owner's inbox too.
We click "Validate", then message disappears, and after about 1 second it appears back on its place.

App id is 'konsierge'.

**Comment by gregs007** [comment]
I have the same issue.. Can't validate any messages or delete/archive

**Comment by hweiler** [comment]
We've been experiencing the same issue as well. Wit hasn't been able to validate any expressions from Understanding, so we've been using the same workaround we found there in the Inbox as well. If you remove any of the suggested values and manually add them back in it should work.

**Comment by l5t** [comment]
Tracking here https://github.com/wit-ai/wit/issues/929
