### ISSUE TITLE
Free Text and Keywords 

### ISSUE THREAD

**Issue by khwstech** [wit-ai/wit#932]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
I am entering text that I want WIT to ignore... however it is thinking its one of my free text traits and saying 'create new value... <text>'. I want it to ignore this text but theres no option

**Comment by patapizza** [comment]
@khwstech Please use the full template. What is your app id?

**Comment by khwstech** [comment]
Sorry about that.
App ID: 59945ded-a991-458b-9458-1ea934a685af

Text i enter: PK51 RYF
Returns output:
[
  {
    "confidence": null,
    "intent": "default_intent",
    "_text": "PK51 RYF",
    "entities": {
      "intent": [
        {
          "suggested": true,
          "confidence": 0.85140072327819,
          "value": "PK51 RYF",
          "type": "value"
        }
      ]
    }
  }
]

I would rather it not find anything.

**Comment by blandinw** [comment]
@khwstech you probably want to pick the `trait` strategy for your `intent` entity, and disable `free-text`. An intent is expressed from the whole sentence, it does not make sense to use something other than trait here (cf. https://wit.ai/docs/recipes#which-entity-should-i-use).

Please comment back if I missed something.

**Comment by khwstech** [comment]
We had an issue with making it as trait. Trait required us to put the same sentence in twice.. one without question mark and one with. IE: if we trained the text to be ... what is engine oil... then typed in what is engine oil? it failed

**Comment by l5t** [comment]
That really sounds like a bug as our entity detection should handle this use case obviously. Would you mind trying again and report if this doesn't work.

**Comment by rimitconsulting** [comment]
hello can you please restart my bot training it has scheduled to some specific time

**Comment by aforaleka** [comment]
hey @rimitconsulting, please let us know your app-id in the issue you opened so we can take a look.
