### ISSUE TITLE
Facing issue training wit.ai with some keywords entity overlap

### ISSUE THREAD

**Issue by NicolasLevaique** [wit-ai/wit#933]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

Bug

**What is the current behavior?**

I have 2 entities ad_entity (keyword entity matching "ad") and adaccount_entity (keyword entity matching "adaccount", "ad account" and "account").
 
No matter how much I train wit.ai, it always seems to understand "ad account" as an entity "ad_entity" and an entity "adaccount_entity" while I want it to be only one "adaccount_entity".

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Try the sentence "video views per ad account" for example

**What is the expected behavior?**

Should match "ad account" as the entity adaccount_entity but it'll most likely match "ad" as an ad_entity and "account" as an adaccount_entity

**What is the App ID where you are experiencing this issue (if applicable)?**

5a2d7e39-1eec-4871-b0a9-8bd27a018b46

**Comment by patapizza-test** [comment]
Hi @NicolasLevaique,

This looks like a similar issue with #881.

It seems like `ad` is used in multiple values for `breakdown` (e.g. `ad account` for `adaccount_entity`, `ad set` for `adset_entity`).
Can you help me understand why is it important to have the full body for `adaccount_entity`, vs. using `ad_entity` as a backup if no other value matches?

Thanks.

**Comment by patapizza** [comment]
Hi @NicolasLevaique,

This looks like a similar issue with #881.

It seems like ad is used in multiple values for breakdown (e.g. ad account for adaccount_entity, ad set for adset_entity).
Can you help me understand why is it important to have the full body for adaccount_entity, vs. using ad_entity as a backup if no other value matches?

Thanks.

**Comment by NicolasLevaique** [comment]
Hello @patapizza,

It's important because the results would be different if we have 1 adaccount_entity vs 1 adaccount_entity and 1 ad_entity.

In the first case, we would show a graph broken down by ad accounts, ie "insights per ad accounts". In the second scenario it would be a graph broken down by ad accounts and ads, ie "insights per ad account per ad" 

Thanks,
Nicolas

**Comment by patapizza** [comment]
Merging with #914.
