### ISSUE TITLE
How limited/featured is Wit API to train models outside of the Wit app dashboard

### ISSUE THREAD

**Issue by atanasov** [wit-ai/wit#934]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question or Bug

**What is the current behavior?**
Shortly I want to be able to train model and manage entities in my website admin, without need to go to Wit.ai dashboard website. I managed to add and edit Entities, but training with  /sample end-point - it always sets my entities to use TRAIT strategy, I want to use FreeText & Keywords. Is it possible?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Add new entity using API
POST https://api.wit.ai/entities?v=20170307 
{
	"id": "pizza",
	"doc": "types of pizza"
}
2. Update entity add keywords
PUT https://api.wit.ai/entities/pizza?v=20170307
{
	"values": [
		{
		"value": "cheese",
		"expressions":["cheese"]
		},
		{
		"value": "piperoni",
		"expressions":["piperoni"]
		},
		{
		"value": "vegi",
		"expressions":["vegi","vegs"]
		}
	]
}
3. Now I have to train my model and add some Expressions
POST https://api.wit.ai/samples?v=20170307
[{
	"text": "How much is the cheese pizza?",
	"entities": [
	    {
	    	"entity": "pizza",
	    	"value": "pizza"
	    }
	]
}]
4. After this call in the Wit dashboard I see pizza Entity with TRAIT strategy. 

**What is the expected behavior?**
I have working model created using stories. All entities are using FreeText & Keywords strategy and I want to keep using this strategy. Is it possible to do it with the API, to add edit Entities, keywords, and train with expressions but to set Entities to FreeText & Keywords.
The idea is to skip going to Wit dashboard at all and to manage all entities from a custom admin panel.
Any ideas, or workflow I can follow to achieve this?

**What is the App ID where you are experiencing this issue (if applicable)?**
This is the production app
58790948-81bb-46a1-82f3-3d80001e18a6

I am testing on this app - 
5a2fa874-5922-498f-a20a-138d128af680

**Comment by l5t** [comment]
When using /samples and you want to train a keyword or free-text entity, you need to specify the span (where your entity is in your sentence). Otherwise, you tell Wit that the pizza entity is for the whole sentence (so a trait entity)
Here is an example where the span is defined for tomorrow with the `start` and `end`

```
curl -XPOST 'https://api.wit.ai/samples?v=20170307' \
  -H "Authorization: Bearer $NEW_ACCESS_TOKEN" \
  -H "Content-Type: application/json" \
  -d '[{
        "text": "I want an appointment for tomorrow please",
        "entities": [
          {
            "entity": "intent",
            "value": "appt_make"
          },
          {
            "entity": "wit$datetime",
            "value": "tomorrow",
            "start": 26,
            "end": 34
          }
        ]
      }]'
```
