### ISSUE TITLE
streaming audio to the speech end point in C#

### ISSUE THREAD

**Issue by jliliamen** [wit-ai/wit#935]
This a question about streaming audio to the speech end point in C#. I don't know why I'm always getting a 400 bad request. I know that stream is correct because I test with the sound player.

```
private string ProcessSpeechStream(Stream stream)
  {
            BinaryReader filereader = new BinaryReader(stream);
            byte[] arr = filereader.ReadBytes((Int32)stream.Length);
            filereader.Close();


            HttpWebRequest request = (HttpWebRequest)WebRequest.Create("https://api.wit.ai/speech");
            request.SendChunked = true;
            request.Method = "POST";
            request.Headers["Authorization"] = "Bearer " + APIToken;
            request.ContentType  = "chunked"; 
            request.ContentLength = arr.Length;          
            var st = request.GetRequestStream();
            st.Write(arr, 0, arr.Length);
            st.Close();
            // Process the wit.ai response
            try
            {
                HttpWebResponse response = (HttpWebResponse)request.GetResponse();
                if (response.StatusCode == HttpStatusCode.OK)
                {
                    StreamReader response_stream = new StreamReader(response.GetResponseStream());
                    return response_stream.ReadToEnd();
                }
                else
                {
                    Logger.AILogger.Log("Error: " + response.StatusCode.ToString());
                    return string.Empty;

                }
            }
            catch (Exception ex)
            {
                Logger.AILogger.Log("Error: " + ex.Message, ex);
                return string.Empty;
            }
  }
```

**Comment by patapizza** [comment]
@jliliamen As the [docs](https://wit.ai/docs/http/latest#post--speech-link) says:

> We accept chunked data, which is a good way to reduce latency. In addition to the Content-type header, you must set a Transfer-encoding header to chunked

Also:

> 400 | missing body (code: body) or missing content-type (code: content-type) or unknown content-type (code: unknown-content-type) or speech recognition failed (code: speech-rec) or invalid parameters (code: invalid-params)

Have you tried setting the proper headers?

**Comment by jliliamen** [comment]
What's the proper content-type for streaming audio. The docs are not clear to me.

**Comment by patapizza** [comment]
@jliliamen You can use `play` from `sox` to get the audio infos. Make sure to include the `Transfer-encoding` header too.

**Comment by jliliamen** [comment]
@patapizza I was able to fix that by doing this:
  request.ContentType = "audio/mpeg3;encoding=unsigned-integer;bits=16;rate=11000;endian=little";
The stream to wit has some sort of high noise in the background. When I save the file, there is no noise background.

**Comment by jliliamen** [comment]
Julien, t'as pas une idée pourquoi j'ai bruit en background?

**Comment by patapizza** [comment]
@jliliamen We resample the audio to a common format, which might be the origin of the higher noise.

**Comment by blandinw** [comment]
@jliliamen thank you for the kind words, it's our pleasure to help
