### ISSUE TITLE
quick reply in NLP

### ISSUE THREAD

**Issue by bmcclenahan** [wit-ai/wit#936]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug/question

**What is the current behavior?**
quick reply messages are being passed to NLP and parsed

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
when I prompt the user with some quick reply options, the response message includes an nlp element, implying that the quick reply text has been passed to NLP for parsing. the text appears in the inbox of the Wit app confirming this.
This processing seems unnecessary, as the text of quick replies is typically tokens to be consumed by code in the messenger webhook, not needing to be parsed for intent. also, it results in non-language input to the Wit app model, and I'm concerned it might confuse it. the idea behind quick replies is to speed up the user experience, and having NLP applied must incur some delay which is undesirable
**What is the expected behavior?**
quick reply messages should not be directed to NLP
**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by patapizza** [comment]
@bmcclenahan Interesting, thanks for reporting.

**Comment by bmcclenahan** [comment]
I'm interested in the outcome of this, if you have time.

**Comment by stopachka** [comment]
merging into #953
