### ISSUE TITLE
wit/location failing when hyphen (-) is involved

### ISSUE THREAD

**Issue by magnusburton** [wit-ai/wit#937]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
> Mossvägen - Norra Bantorget kl 7:53 är inställd på grund av vagnfel.

Marks `Mossvägen - Norra Bantorget` as a _wit/location_ entity while in reality they should be split up into two separate entities (see below).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I've trained my app to treat `Mossvägen` as a _wit/location_ entity and `Norra Bantorget` as _wit/location:direction_. If I were to edit the sentence above to something like the following:
> Mossvägen till Norra Bantorget kl 7:53 är inställd på grund av vagnfel.

it'd work. I think this is caused by the hyphen.

This might be a similar issue to #864. If this is the case I apologize and am just wondering if this is part of your new free-text strategy:
> We're currently working on a new version of our free-text strategy, which should be smarter about this kind of things. I opened an internal ticket to keep this is mind as we build the new version.

**What is the App ID where you are experiencing this issue (if applicable)?**
5a4eadd2-ba12-42d6-a3e8-0f32511ced6f

**Comment by patapizza** [comment]
@magnusburton Thanks for reporting.

This is a tough one, as things like `Port - au - Prince` are valid `wit/location`. It seems like we'd need an actual location resolver to actually fix this, e.g. by resolving the full range and all chunks. Do you use any location resolver by any chance?

**Comment by magnusburton** [comment]
@patapizza I use a location resolver but only after I’ve processed the message through Wit. What I could do is split messages based on hyphens but that does seem like an unnecessary step.

What confuses me however is whether or not wit/location learns from my training (doesn’t seem like it now) or if it’s a more “free” parser. Having a hard time coming up with solutions to this issue.

**Comment by patapizza** [comment]
@magnusburton Yeah so the workaround for now would be to do that and let the resolver do the filtering. Today we provide entity extraction, not resolution. As a result for locations, we'd rather be too greedy than missing out some locations, as the issue can be mitigated on the client side using a resolver.

That being said, we're looking for improving `wit/location` and other entities; they do learn and validating more samples definitely helps.

**Comment by magnusburton** [comment]
@patapizza Thanks for your answer. I can consider this issue closed then as I'll be working on my location resolver to detect hyphens and do a split in my backend.
