### ISSUE TITLE
Identifying a generic message string

### ISSUE THREAD

**Issue by phpexpert10** [wit-ai/wit#938]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

*question* 

**What is the current behavior?**

User Says *Inform John that tomorrow is holiday so have fun*. I want to pick the string after 'that', *tomorrow is holiday so have fun* in separate entity. I tried with multiple training data by creating own custom entity and also tried with *message_body* entity but unable to identify the string. Basically I am not interested in Date *tomorrow* just want system to identify the Message. For eg user might say Tell John *I am not coming for meeting* so I just need this message so I can post it in message. 

What would be the better approach? Tried using message_body, message_subject, even agenda but got no success. Any suggestions please?

**Comment by blandinw** [comment]
If the provided entities do not work, you'll need to create your own `free-text` entity and provide enough training data (https://wit.ai/docs/recipes#which-entity-should-i-use)
