### ISSUE TITLE
Built-in entities too greedy

### ISSUE THREAD

**Issue by lukepeek** [wit-ai/wit#939]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

report a bug

**What is the current behavior?**

Regardless of what is taught, wit always thinks a sentence contains an age. Even though there is often nothing that relates to an age in the sentence (See the attached screenshots). This happens no matter how many times I train the app that saying ‘thankyou’ (or other entity) isn’t an age.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Screenshots attached of example phrases

**What is the expected behavior?**

age_of_person isn't detected in *every* sentence. Or at least not with such high confidence. e.g. 90% confidence that *cheese sandwiches* is an age?

**What is the App ID where you are experiencing this issue (if applicable)?**

5a182f0d-77e3-43f6-872c-b5547730d7e4

![screen shot 2018-01-22 at 13 41 15](https://user-images.githubusercontent.com/9349467/35273911-21ee268a-0032-11e8-8829-6bc9c5f73422.png)
![screen shot 2018-01-22 at 13 39 29](https://user-images.githubusercontent.com/9349467/35273913-221b5326-0032-11e8-9884-1dba3ca859f7.png)
![screen shot 2018-01-23 at 11 41 40](https://user-images.githubusercontent.com/9349467/35274054-95008820-0032-11e8-9843-c243b5bd0ada.png)
![screen shot 2018-01-23 at 11 42 00](https://user-images.githubusercontent.com/9349467/35274055-9515bd9e-0032-11e8-860f-bfcfa3cc9e54.png)

**Comment by patapizza** [comment]
Thanks for reporting @lukepeek - we'll need to improve the model.

**Comment by patapizza** [comment]
`wit/age_of_person` should behave more correctly now.

**Comment by DevinHillenius** [comment]
I see this issue is closed, I have however still have this issue with age_of_person, is it possibly introduced again somehow in the current version?

**Comment by jtliao** [comment]
We'll look into it, let's keep the discussion in the original thread you created.
