### ISSUE TITLE
Intents not detected and app stuck in training

### ISSUE THREAD

**Issue by devsagaacc** [wit-ai/wit#941]
I've created 90 trait/keyword intents through the HTTP API and added samples also through the API. I can see these intents and expressions through the console.
None of the created intents are being detected and the app is constantly in training status. It's been 12 hours now that this is the issue.
My appid is 5a689c72-23af-47e8-96e8-172f241f7a32

**Comment by l5t** [comment]
Just restarted. Sorry for the inconvenience.

**Comment by devsagaacc** [comment]
None of the intents are getting detected. I've entered the exact phrase I have in my expression and it doesn't work
![image](https://user-images.githubusercontent.com/26428067/35435204-11bc2f3c-028a-11e8-9d6a-
6a3144e4fed6.png)
![image](https://user-images.githubusercontent.com/26428067/35435215-1f950bba-028a-11e8-929b-6c32b7eed49c.png)

It's the same when calling from HTTP API.

**Comment by blandinw** [comment]
@devsagaacc we're looking into it cc @l5t for update

**Comment by blandinw** [comment]
@devsagaacc you have 84 trait entities, which is causing issues during training.
I'm working on a fix but your app will probably be working suboptimally.
Why not have one `intent` entity, with 84 values?

Will close once the fix is out.

**Comment by blandinw** [comment]
Fix is out
