### ISSUE TITLE
[wit][ui] breaks on certain expression

### ISSUE THREAD

**Issue by justuseapen** [wit-ai/wit#942]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

Bug Report

**What is the current behavior?**

When I enter an expression to train against the UI returns this:

![image](https://user-images.githubusercontent.com/4587141/35394793-a4b72604-01b6-11e8-8deb-80fd88be210f.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

I've been attempting to train on the phrase: `3114 remington avenue` and get the UI response above.

**What is the expected behavior?**
I'd expect to be given fields to set expected intents and entitities (as usual)

**What is the App ID where you are experiencing this issue (if applicable)?**
5a1d9424-1a9b-4346-b726-9d42757b80ce

P.S. This is for an app thats live on FB and getting more and more attention so it's a pretty [URGENT] situation.

**Comment by l5t** [comment]
I just checked and it seems to work now. Can you confirm?
![image](https://user-images.githubusercontent.com/6992759/35403733-8830d062-01b5-11e8-9d08-a6231297fdbe.png)

**Comment by l5t** [comment]
Actually there is indeed an issue with this query "3114 remington avenue" in our UI but if you click on the API output preview, you will see that the API returns the right entities
![image](https://user-images.githubusercontent.com/6992759/35403815-c9adef52-01b5-11e8-91eb-fb55cfd65509.png)

**Comment by justuseapen** [comment]
Those are _not_ the right entities. One of those values isn't even included in the query string. I need to train with the correct entitities: `intent:"get_water_bill", location: "3114 remington avenue"`

**Comment by l5t** [comment]
Wit cannot learn that "3114 remington avenue" is an get_water_bill trait entity. Wit can learn this when it has similar way to express this intent like "How do I get my water bill". "Where is my water bill" but Wit cannot infer with just an address that this is about get_water_bill

**Comment by justuseapen** [comment]
Ok...Can it learn that "3114 remington avenue" is a location?

**Comment by patapizza** [comment]
This is now fixed.

@justuseapen Yes it does:

```
$ curl \
 -H 'Authorization: Bearer xx' \
 'https://api.wit.ai/message?v=20180126&q=3114+remington+avenue'
{"_text":"3114 remington avenue","entities":{"location":[{"suggested":true,"confidence":0.93717666666667,"value":"3114 remington avenue","type":"value"}]},"msg_id":"xx"}
```
