### ISSUE TITLE
Trait value metadata lost after edition

### ISSUE THREAD

**Issue by guillefhc** [wit-ai/wit#943]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug

**What is the current behavior?**
The metadata of a trait value is lost when is edited whithout modifying it (clicking directly the save button ).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Use wit.ai frontend to edit trait value metada. 
After the edition window is openend, inmediatly click on save (without editing)
The operation deletes the medata.

![bug metadata lost on save](https://user-images.githubusercontent.com/5681065/35437968-02e6c5fc-0295-11e8-98df-f574609ee110.gif)

**What is the expected behavior?**
Save the same metadata that is already stored (or do nothing)

**What is the App ID where you are experiencing this issue (if applicable)?**
5a68a2f8-ff69-437b-babd-cff1aaddad8f

**Comment by l5t** [comment]
Thanks for reporting!
