### ISSUE TITLE
Generic pronouns to answer questions based on context

### ISSUE THREAD

**Issue by nathansamson** [wit-ai/wit#944]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

question

**What is the current behavior?**

Eg. I have an intent which recognizes sentences like "How do I drive to <location>" / "How do I reach <location>"
So what we do is just take the location and put it into google, which works.

But now we want our application to be context aware, and answer questions like "How do I drive there?" / "How do I reach it?"

Most of the time we just get it or there in the location entity (or an empty one). Obviously we could hardcode these generic words, but that would be defeating the point

**What is the expected behavior?**

We can easily create an entity "generic pronoun" (not sure about the term!) which will return to us if we need to do a context based lookup or not.
It seems we can't do this

**Comment by blandinw** [comment]
hi @nathansamson!

What you're referring to is called "anaphora resolution" (it, her, their, etc. are anaphors).
Wit does not support anaphora resolution out of the box at the moment.

However, you should be able to create an entity to recognize these anaphors using our keywords strategy (cf. https://wit.ai/docs/recipes#which-entity-should-i-use).

In the Understanding tab, click on this new entity and select "keywords" as a strategy.

Closing now, feel free to reopen/comment if we can help further!
