### ISSUE TITLE
Intents not detected

### ISSUE THREAD

**Issue by devsagaacc** [wit-ai/wit#945]
Previous issue #941 was closed but was not resolved so I have to open a new one.
None of the intents are getting detected. I've entered the exact phrase I have in my expression and it doesn't work
![image](https://user-images.githubusercontent.com/26428067/35440107-40cb47a4-029e-11e8-9e69-7d73504496c4.png)

![image](https://user-images.githubusercontent.com/26428067/35440084-2b8241fe-029e-11e8-8bd8-3caa9159e90f.png)

It's the same when calling from HTTP API.

**Comment by l5t** [comment]
I reopen the issue. Let's close this one and continue on this other issue #941
