### ISSUE TITLE
Training entities not working in Ukrainian

### ISSUE THREAD

**Issue by cvomcfly** [wit-ai/wit#946]
I have tried to train here flight status by route, between London and Kiev. I highlighted both cities with iataCode (origin/destination), but it didn't work out correctly in testing, and then I checked the preview API output...and no track of origin/destination...
![image](https://user-images.githubusercontent.com/33088084/35453788-c5241b70-02cb-11e8-8a54-055c7f0243c2.png)

While I did the same with another phrase (flight status from Kharkiv to Amsterdam), and it worked correctly (I have highlighted in the same way as before):
![image](https://user-images.githubusercontent.com/33088084/35453792-c9a66982-02cb-11e8-88bb-41d17147ac80.png)

If anyone could help me please. I have also tried to erase the phrase and training again from scratch but nothing different happened...

APP ID: 
59f05f84-7c54-4463-a779-970c490ff2eb

**Comment by cvomcfly** [comment]
Hi @patapizza thanks for checking this. I tried with more examples (without origin and destination), but not working either.. I attach screenshots here.
рейс з рига в чернівці вчасно (=flight status from Riga to Chernivtsi)
![image](https://user-images.githubusercontent.com/33088084/35564238-c8e3a2c6-05b9-11e8-8e3e-d947584d8d8a.png)

Without hyphen:
скажіть мені статус рейса по маршруту київ рига (flight status from Kiev to Riga)
![image](https://user-images.githubusercontent.com/33088084/35564257-db438a76-05b9-11e8-84be-48a66d84e065.png)

**Comment by stopachka** [comment]
Will summarize here, to make sure we get this correctly: 

Currently, despite valid examples, roles are not adequately detected in Ukfranian, for the lataCode entity.

The following trained examples should work, but do not:

```
рейс з рига в чернівці вчасно (=flight status from Riga to Chernivtsi)
expected: origin, destination
got: just iataCode

скажіть мені статус рейса по маршруту київ рига (flight status from Kiev to Riga)
expected: origin, destination
got: just iataCode
```

**Comment by stopachka** [comment]
Looking at `iataCode` 

it looks like you have the search strategy set as "keywords" -- if you do this, then the roles will not work, as they depend on the position in the sentence.

If you change it to "free text & keywords" it should behave differently
- (not editing your app myself, as you may have this in production. Let me know how it goes once you try that)
