### ISSUE TITLE
Roles not being applied inside composite entities after much training

### ISSUE THREAD

**Issue by magnusburton** [wit-ai/wit#947]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
If I have a sentence with a composite entity (which now works great btw) roles for `wit/location` are not being applied to similar sentences even after much training. Consider the following sentence:

> Hållplats Fiskarhagen är flyttad ca 200 meter bakåt för buss 708 mot Rönninge station från och med 2017-11-21 pga vägarbete. Detta planeras pågå till och med 2018-02-06.

`buss 708 mot Rönninge station` is my composite entity with entity `vehicle` for _buss_, `line` for _708_ and `wit/location:direction` for _Rönninge station_. `wit/location:direction` is applied correctly when outside a composite entity but inside one it fails.

**What is the App ID where you are experiencing this issue (if applicable)?**
5a4eadd2-ba12-42d6-a3e8-0f32511ced6f

**Comment by blandinw** [comment]
Update: the issue is more complex than initially thought. I hope to get a fix out next week.

**Comment by 91ns** [comment]
Is there an update on this issue?

I'm having the same problem 
5b3fac96-439d-4cbc-bc51-093895b9de28
