### ISSUE TITLE
Datetime enitie in Greek

### ISSUE THREAD

**Issue by doc1991** [wit-ai/wit#948]
Hello, 
We've been using wit.ai in Greek for some time now, and recently an issue appeared.
The newly-introduced datetime entities were not recognized, even if they 've been working for a month or so.
We ended up train a new app as a workaround.
Is it a known bug with the beta version of greek api or you never heard of it?
In this url of picture can see what happened
https://imgur.com/a/gSLL1
Thanks in advance

**Comment by patapizza** [comment]
Hi @doc1991,

Please use the template. What is your app id?
I can't repro. Also in your example `5 λεπτά` (5 minutes) is actually a `wit/duration`, not a `wit/datetime`.

Thanks.

**Comment by doc1991** [comment]
Hello again I post two picture one for duration and another for datetime. May be we doing something wrong. 
 [https://imgur.com/a/IkY7j](url) [https://imgur.com/a/5HITu](url)
Thanks

**Comment by patapizza** [comment]
@doc1991 Got it, I might have an idea on what's going on. I'll look into it tomorrow.

**Comment by blandinw** [comment]
duplicates #839
This is now fixed, apologies for the inconvenience.
