### ISSUE TITLE
Training expressions is not working

### ISSUE THREAD

**Issue by s-nour** [wit-ai/wit#949]
Hello, 
I've been trying to train expressions using this endpoint https://api.wit.ai/samples?v=20180130

The response is as follows: 
{
    "sent": true,
    "n": 12
}

However, the expressions are never trained.

**Comment by l5t** [comment]
Can you follow the issue template and provide your app id so it's easier to investigate... It would be great to get the full request. Also Training expressions via /samples can take some time so you may check again now

**Comment by l5t** [comment]
It seems that we have a backlog in the training queue. Closing and following the status on this #951
