### ISSUE TITLE
Shortcuts in console may not take precedence

### ISSUE THREAD

**Issue by Floby** [wit-ai/wit#95]
In the console, when trying out examples, the result is shown with shortcuts for Validation (Ctrl+V) and Cancellation (Ctrl+D). These two shortcuts have other meaning in the context of a browser like Chrome (Paste and Mark as Favourite) which sometimes take precedence.

This may be caused by the wrong DOM element having the focus (or the lack of DOM element having the focus at all).

**Comment by martinraison** [comment]
Apologies for the very late reply. I don't think those shortcuts are available anymore, so I will close this issues, but let me know if I'm wrong.
