### ISSUE TITLE
Entity expressions are not returned 

### ISSUE THREAD

**Issue by s-nour** [wit-ai/wit#950]
Please check the following: 
When requesting the entity expressions through API, they are always returned empty 
![image](https://user-images.githubusercontent.com/19264187/35554335-00c852b0-05a4-11e8-9481-d2ae13dd3cfb.png)

However, I can see them on Wit.ai 

![image](https://user-images.githubusercontent.com/19264187/35554357-1c5281f4-05a4-11e8-8e6b-a8826a3c3e81.png)

**Comment by l5t** [comment]
Can you share your app id?

**Comment by stopachka** [comment]
Hey  @s-nour 

Two issues:

re: errors where the "intent" entity gives you warnings
- It looks like "start" and "end" values are provided for some samples. Could you send me an example curl for them? 
  - For trait entities, they should not contain a start and end, as they consider the whole sentence

re: issues with GET /entity/:id

Here, the terminology is a bit confusing. 
- `expressions` in those case refer to `synonyms` for free-text and keyword entities. In this case, as this is a trait entity, there are no synonyms
- We are thinking through a  GET /samples api, that may help. If you need this urgently, let us know and we can give you a temporary solution

**Comment by mbukovy** [comment]
@stopachka 
Hello, I need this as well. We are trying to provide a convenient way of training and management, sort of a copy of Wit UI. I need to display all expressions of all values of an intent, but all I get is empty arrays. I use trait lookup as well, all the same as author.
Look at my app mbukovy/10-12-prvy, I need to see this expressions and be able to delete them as well (see the picture)

Is it possible or is it going to be implemented in the near future? Thank you!

![untitled](https://user-images.githubusercontent.com/27806309/35808680-e1de50c4-0a86-11e8-9255-fa6b7c966933.png)

**Comment by s-nour** [comment]
The main issue here is that we were previously able to obtain expressions of trait entity values, and we are still able to on apps created before January 28th. The expressions are returned as an empty array for apps created after the mentioned date.

**Comment by mbukovy** [comment]
Well, we're going to create apps dynamically through the API, so... :-)
But that's a very strange behavior, why is that?

I don't have an experience with Wit.ai before January 28th, so I just know, that I can't get the expressions I see in Wit UI.

**Comment by mbukovy** [comment]
@stopachka 
I've got the access to one older app and exactly as @s-nour states, it's working great. Exactly as I want.
Please, write here a status - is it going to be fixed, or implemented other way and when can we expect it?

Thank you!

**Comment by stopachka** [comment]
Very interesting 

@s-nour @mbukovy 
- could you give me an app id of one the apps, where this works?
 - (alongside the request you are making, without the access token) 

--- 

re: fully-featured samples api -- this is definitely a contender for an upcoming api update. Will let you know how it goes

**Comment by mbukovy** [comment]
@stopachka 
Interesting, now it doesn't work with an older app either. But I'm sure, it worked with this request
`GET https://api.wit.ai/entities/intent`
Now it returns empty arrays for expressions. I was able to see the expressions array and add/delete them with requests `POST entities/intent/values` and `DELETE /entities/intent/values/phone_problem/expressions/Oh my god my phone`

I was trying this _older app_ `5a2193c5-e96f-4f85-9c97-1b95d869551e`
and this _newer app_ `5a78465c-0604-4adf-a6e1-b5ae9bd9a1f5`

**Comment by josephlingzb** [comment]
i'm having this issue as well. will this be fixed soon?

**Comment by NourShalabi** [comment]
Here's the response returned for a previously working app from our logs:
Response:{
  "builtin" : false,
  "doc" : "User-defined entity",
  "exotic" : false,
  "id" : "59997b65-563c-4f25-8672-ccb2b2cf4297",
  "lang" : "en",
  "lookups" : [ "trait" ],
  "name" : "intent",
  "values" : [ {
    "value" : "Car Deals",
    "expressions" : [ "can you give me car deals", "do you have car deals", "i am looking for a car" ]
  }, {
    "value" : "Loans",
    "expressions" : [ "i need a car loan", "car loans" ]
  } ]
}
DateTime: 1/31/2018 1:10:44 PM

I can send you more samples from our logs if you'd like.

And this is the response for an app that still returns trait expressions: 

App ID: 5a16b0bf-bdd7-4a24-8fe1-f81fbce086fb
![wit2](https://user-images.githubusercontent.com/25252530/36027831-88a31838-0da5-11e8-8fe3-113a6082805f.JPG)

**Comment by josephlingzb** [comment]
@stopachka is there any way to get expressions of a trait using the API right now? This used to work until recently!

**Comment by patapizza** [comment]
Thanks for your patience, I'm working on a fix.

**Comment by patapizza** [comment]
This should now be fixed - can someone confirm?

**Comment by josephlingzb** [comment]
Just tested, this is now working. Thanks!

**Comment by mbukovy** [comment]
It's working, thank you!

**Comment by s-nour** [comment]
I can confirm it's working as well, thank you very much.
