### ISSUE TITLE
Bot is traning infinitely

### ISSUE THREAD

**Issue by guillefhc** [wit-ai/wit#951]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug report

**What is the current behavior?**
The bot is traning infinitely

**What is the App ID where you are experiencing this issue (if applicable)?**
5a37e52e-951e-41ba-9dca-eaba413e844a

**Comment by l5t** [comment]
Thanks for reporting, we are having a backlog in our training queue. Will update when back to normal

**Comment by l5t** [comment]
Seems to be working now. Please reopen if not
