### ISSUE TITLE
Postback, quickreplies in Built-In NLP

### ISSUE THREAD

**Issue by bmcclenahan** [wit-ai/wit#953]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug/question
**What is the current behavior?**
Postback items are appearing in my Wit App
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Since enabling NLP I notice that some postback text is appearing in the Inbox of my Wit App
**What is the expected behavior?**
I would not expect to see postback terms passed to the WIt App
**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by stopachka** [comment]
This is a good point. We are thinking about the consequences of filtering these messages out for NLP. For now it does seem unnecessary.

**Comment by bmcclenahan** [comment]
Yes, having postbacks appear in Inbox is creating unnecessary work for me - when I groom my inbox, it is cluttered with postback and quickreply messages that I have to identify and delete in case they disrupt the language model. I can think of no value in having these go to NLP - the software has already assigned a clear meaning to these message types.

Thank you
Bruce
________________________________

**Comment by stopachka** [comment]
Cheers @bmcclenahan .

In the meantime, to clear up the clutter, you could validate the expressions with a throwaway entity. This way they will no longer show up in the inbox. You are right though that this could risk changing the model in a bad direction.

I'll update here with the resolution that we'll take for quickreplies and postbacks

**Comment by bmcclenahan** [comment]
Thanks mate.
I think I'll put up with it, and wait for your resolution for quickreplies and postbacks
Cheers
________________________________

**Comment by stopachka** [comment]
Hey @bmcclenahan -- coming back to this, with an intent to ship the fix. 

Could you clarify what you mean by postbacks?
  - quickreplies would indeed arrive to the wit inbox, but I don't think postbacks would
     - what do you see when a postback is sent?

**Comment by bmcclenahan** [comment]
see >>>

________________________________
