### ISSUE TITLE
Chinese locale extracting entire utterance as an entity

### ISSUE THREAD

**Issue by XY-Wang** [wit-ai/wit#955]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
I'm trying to train a Chinese app utterances which includes an entity "iataCode" with roles "origin" and "destination". However the preview API output shows that the entire utterance is picked up as the "iataCode" entity instead of just the location. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Here are some screenshots:

![screen shot 2018-02-01 at 4 32 20 pm](https://user-images.githubusercontent.com/17497561/35691395-af51c20a-0778-11e8-9e12-a7d61be5440a.png)

![screen shot 2018-02-01 at 4 34 20 pm](https://user-images.githubusercontent.com/17497561/35691417-b84990d6-0778-11e8-9780-30cbec5f0459.png)

**What is the expected behavior?**

The highlighted text should be returned as entities with the correct role.

**What is the App ID where you are experiencing this issue (if applicable)?**
5a708229-a789-4975-80c3-c98a247d5c72

**Comment by patapizza** [comment]
Thanks for reporting @XY-Wang. We'll need to improve our models - in the meantime validating more examples would help!

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
