### ISSUE TITLE
about classification of training sets.

### ISSUE THREAD

**Issue by zhanpengli** [wit-ai/wit#956]
hi, When training wit.ai, some data are grouped into one intent, but I do not know how to subdivide the entities, and I just throw them all down in one entity, does this affect the matching of the intent?
 thanks a lot~~~

**Comment by zhanpengli** [comment]
![image](https://user-images.githubusercontent.com/32571006/35715677-f8337ac2-080e-11e8-9a3f-7bcce2364582.png)

**Comment by zhanpengli** [comment]
just like that

**Comment by stopachka** [comment]
hey @zhanpengli -- it depends on your use case. Feel free to add your app-id here, and I can take a look

**Comment by zhanpengli** [comment]
![image](https://user-images.githubusercontent.com/32571006/35906897-2e4f7f2c-0c27-11e8-8a42-b1537b737ad1.png)
ok,but i had changed the entity name ,that is the id : 
5a55e9f2-897a-4b42-b892-89f18a2f58ea

**Comment by zhanpengli** [comment]
@stopachka  and i also have one problem , what about the Query the amount of concurrency ? thanks

**Comment by zhanpengli** [comment]
hi，anybody can tell me wit.ai query concurrency？Our website traffic will be more than 50,000 a day，I need to know how many concurrency a wit.ai app can handle，thanks

**Comment by stopachka** [comment]
hey @zhanpengli -- if it is 1-2 qps, it should be good. If you will have more, please email us -- team@wit.ai, with what your expected qps is, and we will make sure to prepare for it

**Comment by stopachka** [comment]
@zhanpengli the only suggestion I would make on your app, is that the orderNumber entity, may be better done as a regex inside your app. (they seem pretty uniform, so it is unnecessary to train an ML model to detect them)

**Comment by zhanpengli** [comment]
hi @stopachka thanks for your enthusiastic answer, on the orderNum entity's proposal is exactly what I think, but my boss hopes to use wit.ai to try, anyway, is not a big problem. I will email you about the query concurrency for more detail , please remember to check email  , bests wishes  :)
