### ISSUE TITLE
Error when trying to export data from app.

### ISSUE THREAD

**Issue by JediRhymeTrix** [wit-ai/wit#957]
`{
  "error" : "Something went wrong. We've been notified.",
  "code" : "wit"
}`

 This is the response I get when I try to download the zip file containing my app's data.

Here's the App ID: 
5a6843bf-030d-41fc-b23c-13dbcedd54b7

**Comment by stopachka** [comment]
Hey @JediRhymeTrix -- tracked down the error. Looking into the underlying cause. Will update here when fix is shipped

**Comment by JediRhymeTrix** [comment]
Thanks. I hope it's a relatively quick fix.

**Comment by blandinw** [comment]
Fix has been deployed, you can now export your app.
Thank you for your feedback and patience!
