### ISSUE TITLE
Bot provides incorrect year for queries in January (query contains no year)

### ISSUE THREAD

**Issue by dananichev** [wit-ai/wit#959]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

Bug

**What is the current behavior?**

```
[
  {
    "confidence": null,
    "intent": "default_intent",
    "_text": "show january 20",
    "entities": {
      "datetime": [
        {
          "confidence": 0.96709,
          "values": [
            {
              "value": "2019-01-20T00:00:00.000+05:00",
              "grain": "day",
              "type": "value"
            },
            {
              "value": "2020-01-20T00:00:00.000+05:00",
              "grain": "day",
              "type": "value"
            },
            {
              "value": "2021-01-20T00:00:00.000+05:00",
              "grain": "day",
              "type": "value"
            }
          ],
          "value": "2019-01-20T00:00:00.000+05:00",
          "grain": "day",
          "type": "value"
        }
      ]
    }
  }
]
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

I have an ``wit/datetime`` entity described in my app. Recently it stopped working with dates in January.
Minimal demo:
* go to https://duckling.wit.ai/
* enter ``show january 20`` or ``January 20`` and click ``Try me!``

**What is the expected behavior?**

It should return current year.

**What is the App ID where you are experiencing this issue (if applicable)?**

``59fc2d1c-c58d-47b3-a399-69dc309ab94a``

**Comment by patapizza** [comment]
Hi @dananichev,

Duckling currently returns up to 3 future datetime values. It would only return past datetimes when the sentence context is explicit. This behavior could be overridden with https://github.com/facebook/duckling/issues/29.
