### ISSUE TITLE
Where is the explore page?

### ISSUE THREAD

**Issue by semsimsom** [wit-ai/wit#960]
In the docs i found out we can use public users intents.
As it says :
> "The explore page also shows a few useful open apps.
>  You can access the Explore page from the top menu in the Wit Console."

But it seems that https://wit.ai/explore is missing or remove :(
**Is there any way to use previous good intents and do not do it from scatch.** 
Thanks for this great tool.

**Comment by l5t** [comment]
Thanks for the kind words. The Explore page is no longer available, so the only way to reuse other intents/entities is to ask another developer to share their app with you (then exporting/API). This is not ideal but we plan to work on a new version to explore public entities this year. Stay tuned.

**Comment by patapizza** [comment]
Closing in favor of https://github.com/wit-ai/wit/issues/266.

**Comment by mrmokilok** [comment]
Hi, I was wondering this too and, after a furious Google-session, ended up here. In the reply, it says you were planning this for 2018. Are there any updates?
