### ISSUE TITLE
Wrongfully tagging non-locations as wit/location

### ISSUE THREAD

**Issue by magnusburton** [wit-ai/wit#961]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug report

**What is the current behavior?**
I have trained my bot on sentences that asks if there are any disruptions on a certain bus line, for example:

> Är det problem med linje **14**?

> Ser du några störningar på linje **72**?

> Hur fungerar linje **78**, **12**, **90**, **40X**, **58** nu ikväll?

I'm tagging the lines as entity `line` (free-text type) and chose not to use the built-in `wit/number` because certain "express"-lines or replacement lines may include a _X_ or _B_ in their names.

The issue is that for sentences with a single line (see the first two sentences above) it tags `linje 72` / `linje 14` as a `wit/location` entity. For the third and last sentence, it only tags the first line supplied as a `wit/location`. So in the case of this third sentence, the part `linje 14` would be tagged as `wit/location` and the following lines are recognized correctly as `line` entities.

**What is the expected behavior?**
I don't know if this is lack of training on my part but I've trained the entity on at least 100 examples so it shouldn't be an issue.

**What is the App ID where you are experiencing this issue (if applicable)?**
5808e3ed-1fca-446a-a4b7-0e04d7736779

**Comment by patapizza** [comment]
Hi @magnusburton, thanks for reporting. We're working on improving `wit/location`.
As a side note, you could use `wit/number` and a custom entity as back-up for `40X` line types.

**Comment by magnusburton** [comment]
@patapizza Thank you for your quick response. Seems like I made an error on my end by wrongly training `linje` as a `wit/location` once. This is the underlying reason why it kept suggesting `wit/location` for every new sentence trained.

This leads me to wonder if there's an effective way to find "mistrained" entities in your data?

**Comment by patapizza** [comment]
Is the issue resolve then?

That's a good point; we're planning on providing better dataset management tooling.
