### ISSUE TITLE
Wit api is returning 0 entities for trained  expressions

### ISSUE THREAD

**Issue by ckatta** [wit-ai/wit#964]
I’m not able to get entities for trained keywords. It is returning 0 entities for each request call.

Earlier we are able to see entity with confidence greater 0.9. now it seems nothing gets returned. Issue exists for last 20 hours.

I'm using node-wit for client app.

**My App Name:** "A2KeyWords"

```
const client = new Wit({accessToken: 'SYTVJD2ASVHQDGY7ACQIMTTA3DO2YVBG'});
client.message("Open URL", {}).then(function (data) {
console.log('Yay, got Wit.ai response: ' + JSON.stringify(data));
})
```

now my app is open, please use entity "Open URL", and see the debug console to view the differences between working and not working.

please find snapshots below

**working**
[https://ibb.co/jSFkox](https://ibb.co/jSFkox)

**not working**
[https://ibb.co/bCsWTx](https://ibb.co/bCsWTx)

**Comment by patapizza** [comment]
Hi @ckatta,

What is your app id?

**Comment by ckatta** [comment]
Hi @patapizza , app id is 

> 5a12a005-2170-49c3-b671-d9a7d85c14b8

**Comment by patapizza** [comment]
It seems like it's working now:

![](https://i.imgur.com/oKlTEb3.png)

BTW I see 102 trait entities that have very little validated samples. It would help to provide more examples to get better models. Also make sure that examples don't overlap with each other.

As an example, the `Click` entity has more validated samples and seem to work better:
![](https://i.imgur.com/za2wJXv.png)

Closing now, feel free to reopen if you still experience the issue.

**Comment by ckatta** [comment]
@patapizza, I am experiencing the same issue. Seems it is not working.

tried with node-wit.

**Comment by patapizza** [comment]
@ckatta Can you share a curl request that doesn't work?

**Comment by ckatta** [comment]
@patapizza, below are examples

**working**

curl -XGET 'https://api.wit.ai/message?v=20170307&q=switch to window' \
      -H 'Authorization: Bearer O7JZD6ARVXKN4NM43AFVYJROEY27YUIG'

https://api.wit.ai/message?v=20170307&q=switch to window

Authorization: Bearer O7JZD6ARVXKN4NM43AFVYJROEY27YUIG

**not working**

curl -XGET 'https://api.wit.ai/message?v=20170307&q=click on continue button' \
      -H 'Authorization: Bearer O7JZD6ARVXKN4NM43AFVYJROEY27YUIG'



https://api.wit.ai/message?v=20170307&q=click on continue button

Authorization: Bearer O7JZD6ARVXKN4NM43AFVYJROEY27YUIG

**APP ID:** 5a12a005-2170-49c3-b671-d9a7d85c14b8

**Comment by patapizza** [comment]
@ckatta Here's what I get on `click on continue button`:

```json
{
  "_text":"click on continue button",
  "entities":{
    "Click":[{"confidence":0.52079275500015,"value":"Click"}],
    "ClickandWait":[{"confidence":0.54347663016262,"value":"ClickandWait"}]
  }
}
```

Looking at your app, I see `click on continue button` for `Click` and `click on Continue button` for `ClickandWait`.
