### ISSUE TITLE
wit/url Not Capturing URL Fragment

### ISSUE THREAD

**Issue by kenpropel** [wit-ai/wit#965]
Bug report of not capturing full URL.

`wit/url` excludes URL **fragment** at the end. (What is a fragment? It's the optional `#header` at the end of some URLs. See [URI](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax).)

Example text sent to Wit app with `wit/url` as an entity:
`take a look at this url: https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax`
Response from Wit:
```json
{
  "_text": "take a look at this url: https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax",
  "entities": {
    "url": [
      {
        "confidence": 0.96785722222222,
        "domain": "en.wikipedia.org",
        "value": "https://en.wikipedia.org/wiki/Uniform_Resource_Identifier",
        "_entity": "url",
        "_body": "https://en.wikipedia.org/wiki/Uniform_Resource_Identifier",
        "_start": 25,
        "_end": 82
      }
    ],
  },
  "msg_id": "1234567890"
}
```

Expected to include fragment like so:
```json
{
  "value": "https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax",
  "_body": "https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax"
}
```

**Comment by l5t** [comment]
Thanks for reporting. This built-in entity is managed by Duckling our open source parser. Can you please open an issue here: https://github.com/facebook/duckling/issues
If you time, you can even contribute and do a pull request. Otherwise we will take care of it!
