### ISSUE TITLE
is have error when upload zip file to create an app

### ISSUE THREAD

**Issue by zhanpengli** [wit-ai/wit#967]
hi, This situation has happened twice,just like that:
![image](https://user-images.githubusercontent.com/32571006/36069209-0a755314-0f20-11e8-9b1e-412928230616.png)
and that is the right:
![image](https://user-images.githubusercontent.com/32571006/36069219-38b27cb6-0f20-11e8-9b41-b60bea396178.png)

**Comment by stopachka** [comment]
Hi @zhanpengli -- could you email me the zip of your app? (stopachka [at] fb [dot] com)

**Comment by zhanpengli** [comment]
ok @stopachka i will email you soon, thanks for help.

**Comment by stopachka** [comment]
Cheers @zhanpengli!

**Comment by stopachka** [comment]
I can repro the issue. Will look into it and let you know @zhanpengli

**Comment by zhanpengli** [comment]
Looking forward to your good news @stopachka

**Comment by stopachka** [comment]
Hey @zhangpengli 

The root cause of this is the `orderNum` entity. We are actively working on fixing the issue for entities that have > 10K values. 

In the meantime, I highly suggest removing the entity, and using regexes for orderNum, as that will perform much better then ML.

**Comment by zhanpengli** [comment]
@stopachka  ok, thank you very much, i already change the method
