### ISSUE TITLE
wit.ai returns "Something went wrong, we've been notified" in a Facebook messenger chatbot

### ISSUE THREAD

**Issue by simplicity-admin** [wit-ai/wit#968]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
report a bug

**What is the current behavior?**
The wit.ai nlp seems to always return "Something went wrong, we've been notified" on the first interaction with the chatbot. After that it seems to work fine. It's almost like the wit.ai goes to sleep and needs the first message to wake up. 

**If the current behaviour is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
The first message sent to our chat bot always returns the following 
      "nlp": {
             "errors": [
              {
                   "code": "unknown",
                   "message": "Something went wrong. We've been notified"
              }
              ]
       }

**What is the expected behavior?**
The expected behaviour is for the nlp to return one of the entities defined.

**What is the App ID where you are experiencing this issue (if applicable)?**
59d52bbc-2b53-47f7-a3bf-6d917f5fc3b2

**Comment by simplicity-admin** [comment]
hi guys
Still getting these errors. Any pointers would be much appreciated?
Cheers

**Comment by stopachka** [comment]
Hi @simplicity-admin , I am looking into this. will update here with what I find

**Comment by stopachka** [comment]
Hey @simplicity-admin 

- I am looking at your app's error log over the last week
  - So far I have seen about 4 error logs, that seem to have come from transient issues
    - Are you still experiencing this issue? 
      - If yes, can you go into how to repro this, or time windows of when it has happened for you?

**Comment by simplicity-admin** [comment]
Hi @stopachka 

Thank you for looking into this. To be honest what we had to do is to ping the wit.ai every 5 mins to make sure it stays "active". This has reduced the number of times this error happens dramatically. Hence the low count you so in the last week. But if you'd look into logs about few weeks back ( if available ) you'll see it used to happen a lot more regularly. I can see it has happened today in the morning ( 3 hours ago ). 

Below is the event sent from the Facebook backend to our webhook and you can see the wit.ai nlp response failed, doesn't tell us much other than that. 

    "body": {
        "object": "page",
        "entry": [
            {
                "id": "{hidden}",
                "time": {hidden},
                "messaging": [
                    {
                        "sender": {
                            "id": "{hidden}"
                        },
                        "recipient": {
                            "id": "{hidden}"
                        },
                        "timestamp": 1520539143432,
                        "message": {
                            "mid": "mid.$cAAOjFLtT95doOHdVCFiBzILdqy_F",
                            "seq": 97310,
                            "text": "Good morning",
                            "nlp": {
                                "errors": [
                                    {
                                        "code": "unknown",
                                        "message": "Something went wrong. We've been notified"
                                    }
                                ]
                            }
                        }
                    }
                ]
            }
        ]
    }

**Comment by stopachka** [comment]
Hey @simplicity-admin -- this has fallen through the cracks. I am assuming all is well and no longer an issue. If you have had further problems, we can re-open this and try to repro on a separate app. The problem is most likely related to the wit app itself, rather then built-in nlp
