### ISSUE TITLE
URGENT: is there a problem with training?

### ISSUE THREAD

**Issue by SoumyaChaudhuri** [wit-ai/wit#971]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
report a *bug*

**What is the current behavior?**
the most basic training example from https://wit.ai/docs/quickstart is not working

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
doing the demo steps 1, 2, 3, and 5 (skipping 4) yields
{
    "_text": "whats the temperature inside",
    "entities": {},
    "msg_id": "0PPpIFqj2rlZCCYqW"
}

**What is the expected behavior?**
{
  "msg_id" : "c34f010e-0f2e-478d-ad7f-d7dc5300e286",
  "_text" : "whats the temperature inside",
  "entities" : {
    "intent" : [ {
      "confidence" : 1.0,
      "value" : "temperature_get"
    } ]
  }
}

**What is the App ID where you are experiencing this issue (if applicable)?**
5a85aa93-a45d-4257-a3ec-5a1fe3d3d571

**Comment by patapizza** [comment]
Hi @SoumyaChaudhuri, I can't repro this.

![](https://i.imgur.com/KceJUhx.png)

Feel free to reopen if you still experience the issue.

**Comment by SoumyaChaudhuri** [comment]
Hi @patapizza , 

I'm definitely still having trouble retraining here.  It is very inconsistent.

I eliminated the "what is the temperature inside" intent and added one for "test".  It's been a few minutes, and I still am getting results for "temperature_get" but not for the word "test".

I tried both the training API (https://api.wit.ai/entities/INTENT?v=20180215 with body:
{
    "doc": "User-defined entity",
    "values": [
        {
            "value": "my.test",
            "expressions": [
                "test"
            ]
        }
    ]
}
, as well as using the UI.

I see my updated training data in the UI and using the API (https://api.wit.ai/entities/intent?v=20180215), but my queries are still giving me old results.

**Comment by SoumyaChaudhuri** [comment]
2 hours since trained.  Still not seeing the updated results.

**Comment by SoumyaChaudhuri** [comment]
I think we are experiencing the same issue as #971

**Comment by patapizza** [comment]
Thanks for the additional info, it should be fixed tomorrow.

**Comment by SoumyaChaudhuri** [comment]
It's working for me now.  Thanks for taking care of this so quickly.
