### ISSUE TITLE
Keyword issues/Wit understanding is trying to combine entities.

### ISSUE THREAD

**Issue by individual11** [wit-ai/wit#973]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
It's been recognizing correct entities for a while, then lately it's been trying to combine them for no reason as far as I can tell.

E.G. I trained it to understand "accident" and "insurance" as separate entities, but all of a sudden it keeps suggesting to combing them into "accident insurance". And the more I train it to *NOT* do that, the higher the confidence level it gets.

**What is the App ID where you are experiencing this issue (if applicable)?**

583273ad-575f-4ad3-a801-fe95d236ce57

**Comment by individual11** [comment]
Anyone? It's gradually getting worse combing more and more entities. I've had to switch to keywords only to keep it remotely consistent.

**Comment by blandinw** [comment]
@individual11 thank you for the feedback, I'm looking into it!

**Comment by blandinw** [comment]
The issue is that your `subject_matter` entity has a value `accident_insurance`, `accident` and `insurance`. So when the sentence "accident insurance" comes up, `accident_insurance` is returned, as opposed to 2 smaller entities `accident` and `insurance`.

I'm not sure this covers your whole question. Can you give more examples of actual results vs. expected results?

**Comment by monika1800** [comment]
No the issue hasnt been resolved yet. Please look into it. The consecutive entities are getting combined if two entities comes under the same label.

**Comment by stopachka** [comment]
Hey @monika1800 -- what do you mean they are combined? 

Could you give us an app id, an example sentence, what you expect, and what happened? When you say combined, do you mean strictly in the UI, or the api is returning some sort of combination, where it chooses one entity or another and gives one the value of both?

**Comment by monika1800** [comment]
Hi @stopachka,

The wit.ai engine was working fine before the last 2 weeks. Then suddenly it started combining the value of entities for the consecutive words which belongs to same entity.

For example, 
for the below sentence the UI and api used to return,
 "Show me my classified expenditure"
  entity        value
  action     classified
  action     expenditure

Now, it started combining the consecutive words under the same entitiy in a single value as shown below.
  "Show me my classified expenditure"
  entity        value
  action       Create new value "classified expenditure"

**Comment by patapizza** [comment]
@monika1800 Just to check, have you changed the search strategy for `action` from `keywords` to `free-text & keywords`?

**Comment by l5t** [comment]
@monika1800  I also think it would be better to use trait entity in your case

**Comment by monika1800** [comment]
Hi @patapizza @l5t ,
I have not changed the search strategy for action from keywords to free-text & keywords. Though, I would like to mention that this is not just happening with "action" label. It is happening with every consecutive terms under same label recognised by wit.

I tried using "keywords" only lookup strategy as well. But then it only works for the values under that label and it doesn't predict label for the terms which are not present as a value.
