### ISSUE TITLE
wit.ai is returning only one intent (as many trained, worked for 2 years)

### ISSUE THREAD

**Issue by giorgiomarzianidepaolis-was** [wit-ai/wit#974]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
BUG

**What is the current behavior?**
Whatever expression is submitted, the same intent has returned. 
Querying the API i see many expressions for all other intents. Using the webinterface, even if I train expressions, they will return same wrong value.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Write a sentence, see the result

**What is the expected behavior?**
returning the correct intent value

**What is the App ID where you are experiencing this issue (if applicable)?**
57e25ba9-ab3a-4928-b469-4c12d597dcbb

**Comment by etbuilder** [comment]
We are having the same issue too, nothing is trained or returned

**Comment by etbuilder** [comment]
I just tested today, so not sure?

**Comment by giorgiomarzianidepaolis-was** [comment]
my instance has about 2 years. I also tried to export and create a new one from backup. Nothing trait is returned.

**Comment by mminchev** [comment]
I am experiencing the same. Actually, in my case, it does not work only for newly trained intents. It just cannot learn them no matter how many examples I provide. The issue started today.

**Comment by giorgiomarzianidepaolis-was** [comment]
adding some useful info: in my specific case (57e25ba9-ab3a-4928-b469-4c12d597dcbb), all expressions are returing `off_assistenza` intent trait value.

**Comment by mminchev** [comment]
It seems to be fixed for me now.

**Comment by giorgiomarzianidepaolis-was** [comment]
Not for me, yet :/

**Comment by blandinw** [comment]
@etbuilder @mminchev what are your app ids?

**Comment by giorgiomarzianidepaolis-was** [comment]
mine is fixed, thanks @blandinw <3

**Comment by etbuilder** [comment]
@blandinw 5a6c8605-21b0-4d1e-a384-578c5d9ba327, I just trained another item to list another value, but still it shows the old value... the app started to work with the newly added data but after almost 20 hours.

**Comment by etbuilder** [comment]
@blandinw  Still ours is not working properly, we added a couple more but still they are not trained event with exact match.

**Comment by patapizza** [comment]
@etbuilder Do you still experience the issue? What is the new value you're looking for?

**Comment by etbuilder** [comment]
@patapizza its **back working now**, but for the last two days, the three dots shows then the green one appears indicating the training is complete but yet, the Last trained in insights does not change and its sometimes one day before.

**Comment by etbuilder** [comment]
@patapizza anything changed, was our app having an issue or the wit platform in general as this results in ambiguity for us. we don't know if what we are doing is right or wrong!

**Comment by patapizza** [comment]
@etbuilder The training dot is not always accurate - the training is done asynchronously and we prevent it from spinning for a while. We have plans to fix this, to better reflect when the training is actually done.

There seems to have been a transient issue in our backend.

**Comment by etbuilder** [comment]
Ok great thanks a lot.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
