### ISSUE TITLE
Huge Latency in Speech API

### ISSUE THREAD

**Issue by AustinRow1** [wit-ai/wit#976]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
When streaming raw audio, there is a at least a 4 second delay from the time the last audio chunk is sent and a response is returned from Wit.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Steps to Reproduce:
1. Stream raw audio to Wit with chunk size of 1024 and rate 8000.
2. Wait >4 seconds for response to come back.

See an example of how to do it [here](https://github.com/ilar/Wit.Ai-Chunked/blob/master/uploadPyAudio.py).

**What is the expected behavior?**
I've seen posts around the internet that suggest that the latency should be/was much lower than this. A delay of less than one second for receiving a response after the last audio chunk is sent would be ideal.

**What is the App ID where you are experiencing this issue (if applicable)?**
5a4fea00-6705-4cfa-a9de-ad3d98fbaea7

**Comment by stopachka** [comment]
Hey @AustinRow1 -- is this happening for you consistently, or do you notice it in spikes? The more info we have the better for this

**Comment by AustinRow1** [comment]
Hello, @stopachka . This is consistent behavior; I don't think that we have ever had it take less than four seconds for Wit to return a response after the last audio chunk is sent. That's the lower bound and sometimes it takes a couple seconds longer. 

I'm happy to give you any info you may need.

**Comment by patapizza** [comment]
Hi @AustinRow1, what is the average length of the audio samples?

Speech is not a priority for us at the moment. We do keep this in mind but can't provide an ETA on when things will improve. In the meantime, if the current state doesn't work well enough for you, we encourage you to try other solutions (e.g. iOS/Android native speech).

**Comment by AustinRow1** [comment]
@patapizza The audio samples are all ~5 seconds in length, give or take a couple seconds.

I understand, though it's a shame because Wit offers a very pleasant user experience from a developer standpoint.

**Comment by blandinw** [comment]
@AustinRow1 can you provide an example audio file causing slow requests for your app 5a4fea00-6705-4cfa-a9de-ad3d98fbaea7?

**Comment by blandinw** [comment]
Closing as stale, we've shipped some improvements since
