### ISSUE TITLE
queries don't appear in inbox when using client access token for auth

### ISSUE THREAD

**Issue by ryanmeador** [wit-ai/wit#98]
I can't find any documentation on the Client Access Token available in the Settings page of the console, so maybe this is intended.  When I was making queries using this token, everything worked as expected, except the query didn't appear in my inbox.  Using my regular Access Token, they do appear in the inbox.  What is this feature for?

**Comment by martinraison** [comment]
Apologies for the very late reply. We could do a better job at documenting the difference between client and server access token. I added this to our roadmap.

**Comment by l5t** [comment]
Closing. https://wit.ai/docs/http/20170307#cross_domain_link
