### ISSUE TITLE
Incorrect response for pre-defined entity "wit/amount_of_money"

### ISSUE THREAD

**Issue by nvkirankumar** [wit-ai/wit#980]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
report a Bug
**What is the current behavior?**
if we say "Pay Kiran1 10eur"
wit/amount_of_money is detecting that as 110EUR

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
(Scenario: when a name ends with a single digit number followed a 2digit amount of money, Then it is giving response as three digits currency [1st digit: the number with which it ended in the name and remaining two digits are same as given])

**What is the expected behavior?**
if we say "Pay Kiran1 10eur"
wit/amount_of_money is detecting that as 10EUR

**What is the App ID where you are experiencing this issue (if applicable)?**
AppId : 5a7305f4-73e4-4133-a119-e9523339bd90

![attach1](https://user-images.githubusercontent.com/17509278/36720154-2f122c24-1bcd-11e8-82b1-e0da56c15b5e.JPG)

**Comment by patapizza** [comment]
Hi @nvkirankumar,

Thanks for reporting.

`wit/amount_of_money` is powered by [Duckling](https://github.com/facebook/duckling). Please open an issue there.
