### ISSUE TITLE
Filter scope of search by parameter

### ISSUE THREAD

**Issue by makalaia** [wit-ai/wit#981]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question

**What is the current behavior?**
Hello all,

We're trying to build an app that could filter the scope of search by a parameter.

For example, in the case that different users accessing the api would have different access to different intents. So depending on a User-ID passed along the request, each user would have a different answer, based on the intents that the user has access to.

Does someone know if something like that is possible using wit?

Thanks in advance.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by patapizza** [comment]
Hi @makalaia,

It seems like this could be implemented on the client side. When reading the intent value from Wit's response, you can check if the user has access to this intent and gate the logic there.
You could also pass a value for `n` to filter out the intents that the user doesn't have access to, and use the remaining top one (make sure the confidence level is acceptable).

Hope this helps.
