### ISSUE TITLE
 How do we ensure that a user question matches a correct intention?

### ISSUE THREAD

**Issue by hhg01** [wit-ai/wit#982]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
This is a question.

We are carrying out a project that at the moment only works to give the climate and air quality.

Our intentions for the moment are getClima, getCalidadAire, getImecas. For these intentions, it only has a numeric value except for getCalidadAire, which also obtains recommendations on activities to be carried out.

We plan to make this project more complex and implement a getAuto function to know the traffic regulations and if our car was taken to any deposit.

Our question is:
if a user asks wit, can my car circulate due to air pollution?
This question should go to the intent of getCalidadAire, how do we ensure that it really goes to this intention and not to getAuto?

**Comment by patapizza** [comment]
Hi @hhg01,

Once you've validated at least 50 different samples, you will see the Insights section for the `intent` entity. This will give you an idea on how the model behaves and help you optimize the confidence threshold. More info on our [blog post](https://wit.ai/blog/2017/08/08/insights).

Hope this helps!

**Comment by hhg01** [comment]
OK thanks.

Another question if I declare a contamination entity directed to getCalidadAire and a car entity to getAuto when the user asks, can my car circulate due to air pollution? wit would not be confused in the intentions

**Comment by patapizza** [comment]
In the case where `getCalidadAire` and `getAuto` are traits, it might potentially return both entities with a confidence score. You can use that to decide whether there's one or two intents in the same input.
