### ISSUE TITLE
add support for small talks

### ISSUE THREAD

**Issue by brightening-eyes** [wit-ai/wit#983]
**What is the current behavior?**
wit doesnt have this feature
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
it should be possible to add small talks like hello with a responce etc (with an intent or something else) something like wit/smalltalk which can have a reply assigned to the given dialog
for example, user asks how old are you? and the reply can be "i am 14" and "why you want it?" which should be based on the trained data for replied messages, and mostly should be random
this makes it possible to train the apps easier and faster
**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by patapizza** [comment]
Hi @brightening-eyes,

Replies are part of dialog management. We've decided to fully focus on NLP by [sunsetting Stories](https://wit.ai/blog/2017/07/27/sunsetting-stories).
Small talk is a bit vague/broad on the scope. Today you can use `wit/greetings`, `wit/thanks` and `wit/bye` to detect those specific intents and build upon them.
We plan to provide [more entities](https://wit.ai/blog/2018/02/28/community-update-2018-02), both built-in and from the community, which should help to cover more of the small talk intents.

Hope this helps!
