### ISSUE TITLE
sdk for other languages should be developed for wit.ai?

### ISSUE THREAD

**Issue by brightening-eyes** [wit-ai/wit#984]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
*feature*
**What is the current behavior?**
the libwit (which is community maintained is limited), no interaction with contexts, not being aible to create and/or work with entities, etc
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
more features should be added (if possible, more sdks for other languages like C++ should be implemented), like working with contexts etc.
if you look at api.ai's C++ sdk, it can completely work with its interface
**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by patapizza** [comment]
Hi @brightening-eyes,

We don't have the bandwidth to provide and support SDKs in more languages. We picked Node.js, Python and Ruby as we thought those would be the most useful for the community.

That being said, our SDKs are a very thin wrapper around our HTTP API. It should be straightforward to build your own in the language of your choice.
