### ISSUE TITLE
In the training process encountered a bottleneck

### ISSUE THREAD

**Issue by zhanpengli** [wit-ai/wit#985]
I feel that the "logistic" intent in my app does not work very well. It can't recognize long sentences very well. I am not sure whether the problem is that the training sentences are not enough or that there is a problem with the entity classification. Can you give me some advice? 

app id: 5a825d08-557b-4622-bc77-ba05a5d7ec02

**Comment by patapizza** [comment]
@zhanpengli Can you share a few sentences that don't work (and what is expected)? Thanks.

**Comment by zhanpengli** [comment]
Thank you very much. I haven't found the right sentence yet.

**Comment by patapizza** [comment]
So it does work? Feel free to reopen once you find a few misbehaving examples.

**Comment by zhanpengli** [comment]
I'm not sure about this, because I recently changed my training and query mode, just for the website to go online more quickly, I will continue to observe this question....

**Comment by zhanpengli** [comment]
@patapizza thanks
