### ISSUE TITLE
I am not able to add synonyms to values in amenities entity in my wit app

### ISSUE THREAD

**Issue by buchikey** [wit-ai/wit#986]
I am not able to add synonyms to values in amenities entity in my wit app

App-Id:5a83d323-0b8a-4d78-b4b5-df6600b06762
App-name: tata_housing

**Comment by patapizza** [comment]
Thanks for reporting @buchikey, I'll look into it.

**Comment by aforaleka** [comment]
Hey @buchikey, thanks for reporting! I can't repro it, can you try again and let me know if it's working? Or is there a specific keyword that's experiencing the bug?

**Comment by aforaleka** [comment]
Feel free to reopen if you still experience the issue
