### ISSUE TITLE
How can I delete all intents programatically?

### ISSUE THREAD

**Issue by DavidCampaneroGarcia** [wit-ai/wit#988]
I just want to try with differents data sets, and program a function that allows me to reset the app.

I already can create new Traits and test the application.

But now if I want to try a different dataset I want to delete the Intents I created previously and add the new ones.

I don't want to delete the entire app and create a new one, cause I want to use the same Authentication Bearer everytime.

Is there any way to delete only the intents?

**Comment by l5t** [comment]
You can use https://wit.ai/docs/http/20170307#delete--entities-:entity-id-link

**Comment by DavidCampaneroGarcia** [comment]
But that would delete the entity "intent" isn't it? I want to delete the traits inside the entity "Intent" not intent itself.

**Comment by l5t** [comment]
Let me clarify, an intent = a trait entity. Each entity has value so in your case you want to remove the intent values? if so: https://wit.ai/docs/http/20170307#delete--entities-:entity-id-values-link

**Comment by patapizza** [comment]
@DavidCampaneroGarcia Indeed - to remove a single value, you can use [DELETE https://api.wit.ai/entities/$ENTITY_ID/values/$ENTITY_VALUE](https://wit.ai/docs/http/20170307#delete--entities-:entity-id-values-link).

**Comment by DavidCampaneroGarcia** [comment]
@l5t @patapizza  Oh I understand, I made it work know :)

I was Post them with this: [https://wit.ai/docs/http/20170307#post--samples-link] So i thought I would have to use something similar. You can close the thread now, thank you guys!
