### ISSUE TITLE
Change Lookup strategy through API

### ISSUE THREAD

**Issue by mohammad-melhem** [wit-ai/wit#989]
Hi all, I would like to request another feature that is available through the wit console but not through the API.

It's necessary since clients sometimes would like to define an entity that should be detected only as keywords but I have to do that manually for them.

Thanks all for your continuous great work and support.

**Comment by patapizza** [comment]
Hi @mohammad-melhem,

Thanks for pointing this out.

**Comment by mohammad-melhem** [comment]
hi @patapizza .. any update on this issue?

**Comment by stopachka** [comment]
Hey @mohammad-melhem 

The /entities api still secretly accepts lookups: rf the example in https://github.com/wit-
ai/wit/issues/798. Feel free to use this in the meantime

We need to think of a good ergonomic api for doing this. The reason we have not made this public yet is, some changes don't make sense. i.e moving from trait -> free-text, and the implications for what happens to the data are not clear. Let's focus the conversation in #798

**Comment by jtliao** [comment]
@mohammad-melhem , you can now set the lookups to free-text, keywords, or free-text & keywords through the API. 

See the docs for details: https://wit.ai/docs/http/20170307#put--entities-:entity-id-link

**Comment by mohammad-melhem** [comment]
Biiig Like!!! Thx ^_^
