### ISSUE TITLE
Setting up environments

### ISSUE THREAD

**Issue by tvvignesh** [wit-ai/wit#991]
Have been using wit for a quite some time now and while I love it, I have one feedback/feature request. 
Is there any way you could support multiple environments like development, production, etc. with different access tokens, with isolated training scope.

Right now, there is no way to do it and even if you create separate apps for each of the environments and  do all your stuff in say, development app, you cant push those changes to a production app and you have to end up retraining and redoing all stuff you did in development in production again.

**Comment by patapizza** [comment]
Hi @tvvignesh,

Indeed, that's on our roadmap: https://wit.ai/blog/2018/02/28/community-update-2018-02

**Comment by tvvignesh** [comment]
@patapizza Nice to hear that. I read that blog post but was not sure since it was not explicitly mentioned about different environments. Looking forward to it.

**Comment by FengyangZhang** [comment]
Hi @tvvignesh,

We just released wit app versioning today! Check out our blog post: https://medium.com/wit-ai/introducing-app-versioning-cc8566d3d4ff. Thanks for using wit!
