### ISSUE TITLE
how to get a high recall in my application?

### ISSUE THREAD

**Issue by hhg01** [wit-ai/wit#992]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

This is a question.

I'm making an application with ingenuity, I already have enough records and I can see the Insights section.

My question is, how can I assign or give more precision and retention to my application?

I have already changed some entities from my records, but my recovery of entities continues to decrease, in the same way that I can achieve high precision as well as recovery.

**Comment by l5t** [comment]
Have you checked https://wit.ai/docs/recipes#which-confidence-threshold-should-i-use? Not sure what you meant by recovery or retention

**Comment by hhg01** [comment]
Yes, already check that documentation.

The question is that in the level of confidence my presicion varies between 9 and 8, however my recall is always low, currently it is 0.54 and I do not know how to have a better value.

Or is it normal that in the graphic of confidence my recall lower its value?

**Comment by l5t** [comment]
Can you share your app ID so that we can have a look and which entity you're talking about

**Comment by hhg01** [comment]
My app ID is 5a982ffa-2ce3-4b82-bb3c-102a27157458

**Comment by l5t** [comment]
and you're talking about the intent or another entity?

**Comment by hhg01** [comment]
Yes, in my intentions I have access to Insights and what I can see there is that my recall is always in decline, I would like to know if there is any way to increase that percentage.

I have already added new fraces and changing entities a bit but the recall continues to go down

**Comment by l5t** [comment]
It might be because different intent values conflict, for example if you validated the same kind of expressions for different intent values

**Comment by l5t** [comment]
Closing, please reopen if you still have issues
