### ISSUE TITLE
What is the meaning of the question mark(?) in a paragraph?

### ISSUE THREAD

**Issue by tonytonypeng** [wit-ai/wit#993]
thanks~~~

**Comment by l5t** [comment]
Not sure what you're referring to. Can you elaborate?

**Comment by tonytonypeng** [comment]
ok, i mean Whether the "?" will affect the training effect. like "where is my order"   "where is my order?"

**Comment by l5t** [comment]
The more validated sample, the better Wit will work. So having both with and without the "?" will help. That being said, Wit is robust and should handle well if you only train with or without the ?
