### ISSUE TITLE
can not train expressions through api

### ISSUE THREAD

**Issue by zhanpengli** [wit-ai/wit#994]
when i train expressions through api the response code show "200", but when i check in my app, it show nothing ,can u help me, thanks

**Comment by DavidCampaneroGarcia** [comment]
I'm having the same problem. I think is not working well right now....

**Comment by l5t** [comment]
Can you try again? We had some training latency last night. If this still doesn't work please report your app id

**Comment by DavidCampaneroGarcia** [comment]
It works perfectly now. It seems it was the latency problems

**Comment by zhanpengli** [comment]
i need some help, i can't train my app through api again, thanks

**Comment by zhanpengli** [comment]
@l5t

**Comment by stopachka** [comment]
Hey @zhanpengli, could you provide your app-id, an example expression you trained you do not see?

**Comment by zhanpengli** [comment]
appid: 5abb2b6f-b592-41e3-a13b-a90626f03c83,
"expression":"gdsdasdfgaddf",
"entity":"other",
"value":"other"
@stopachka

**Comment by zhanpengli** [comment]
appid: 5abb2b6f-b592-41e3-a13b-a90626f03c83
"expression":"where is my kuaidi",
"entity":"logistics",
"value":"where_check"
The response to the API training is shown in the figure below:
![image](https://user-images.githubusercontent.com/32571006/38531316-d3c5cd1c-3ca1-11e8-9eea-894213713b4c.png)
Although the training showed success, it didn't sync up to my wit background.

**Comment by s-nour** [comment]
We are having the same issue on the following app since yesterday. 
5acb6329-9a20-41d5-8cb4-e9ba604be9c2

**Comment by patapizza** [comment]
@zhanpengli: It seems like it's working now:

![](https://i.imgur.com/JwhtHgx.png)

<img width="663" alt="screen shot 2018-04-13 at 5 30 06 pm" src="https://user-images.githubusercontent.com/1015208/38762390-5a5ae6be-3f40-11e8-805d-f5461a5c0d81.png">

@s-nour Can you share a couple of examples that don't work (and try to re-post them)? Thanks.

**Comment by zhanpengli** [comment]
yes, that's great, thanks

**Comment by anthonymfowler15** [comment]
It seems that this issue is happening again. Expressions posted via the API are not being persisted. 

App ID:
2303780949737600

**Comment by jtliao** [comment]
@anthonymfowler15 can you give an example of how you're using the API/which entity you're adding to?

also, in general it's recommended to create a new issue for easier trackability
