### ISSUE TITLE
How would I train wit to recognise bible verses in different forms?

### ISSUE THREAD

**Issue by samueljseay** [wit-ai/wit#995]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
This is a question

I want to reliably extract bible verses from conversation and I can imagine they would come in multiple forms. I considered a regex as you've mentioned in other issues like determining a license plate, but there are cases for this that I think would be non-uniform.

e.g.

```
Matthew chapter 1 verse 6
or Matthew 1:6
or Matthew 1v6
```
or potentially not even including a verse like: `Matthew 1`

I would obviously want to extract the book, chapter and verse

I could probably develop multiple regex for these cases, but I just wanted to get some advice first on whether this could be done and what the best approach would be.

Thanks so much for developing wit, its really great! :slightly_smiling_face:

**Comment by patapizza** [comment]
Hi @samueljseay,

It seems like a set of regexes would work.
Another idea to try is using composite entities, with a keyword entity for `Matthew`, and `wit/number` with different roles `chapter` and `verse`.
Let me know if that works!

This could also be implemented as a [custom dimension in Duckling](https://github.com/facebook/duckling/issues/29) (not ready).
