### ISSUE TITLE
How to deal with $1.45/kg ?

### ISSUE THREAD

**Issue by serraventura** [wit-ai/wit#996]
Do you want to request a feature, report a bug, or ask a question about wit?
question

> 5 kg of rice per $1.45/kg

where

rice = product (I guess a predefined list of products is the right thing to do here)
5 kg = quantity of the product (wit/volume ?)
$1.45/kg = price per kg (????)

What seems trick for me is $1.45/kg.

It could be 

$1.45/pounds
$1.45/unit
$1.45/grams
$1.45/liter
$1.45/ml

Maybe there's a way to mix wit/amount_of_money with wit/volume ?

Another I cannot figure out is the case for multiple products. Ex:

> we have available 5 kg of rice per $1.45/kg, 10 kg of beans per $2.48/kg etc...

I would need to get the related data.

5 kg and $1.45/kg = belongs to rice.
10 kg and $2.48/kg = belongs to beans.

**Comment by l5t** [comment]
I would use composite entities and the wit/quantity. As for the price per volume, I would probably create a custom entity, see below. With enough examples (20-30), Wit should be able to pick it up


![image](https://user-images.githubusercontent.com/6992759/37267472-b9f99156-257d-11e8-8b18-6ae78df995ad.png)

**Comment by serraventura** [comment]
I'm testing it. How did you change the quantity to 5000 grams. I can't find a option to change it

**Comment by l5t** [comment]
I did nothing. The wit/quantity is governed by [Duckling](https://github.com/facebook/duckling) our linguistic open source parser

**Comment by serraventura** [comment]
Wow! I think your idea is working. But still need to train more the app.

Thanks again!

**Comment by l5t** [comment]
Glad to hear.
