### ISSUE TITLE
wit/on_off entity is overlapping on_off entity in web UI

### ISSUE THREAD

**Issue by slhad** [wit-ai/wit#997]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a Bug

**What is the current behavior?**
Impossible to access "on_off" entity through UI, "wit/on_off" is shown instead

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Create a "free text & keywords" entity named "one_off"
2. Rename "one_off" entity to "on_off"
3. Access entity through UI
4. "wit/on_off" entity is shown, not "on_off" entity

**What is the expected behavior?**

Step 4 should show "on_off" entity

**What is the App ID where you are experiencing this issue (if applicable)?**

5aa03512-aacf-4be7-92dd-f2fd55729c85

**Comment by Istvan446** [comment]
H

**Comment by patapizza** [comment]
Hi @slhad, thanks for reporting.

This is low priority - I'll add a note. Please use another entity name in the meantime.
