### ISSUE TITLE
App isn't fully recognizing a new trait value for Intent

### ISSUE THREAD

**Issue by hweiler** [wit-ai/wit#998]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
I'd like to report a bug for renaming intent trait values.

**What is the current behavior?**
I changed the trait value for an intent, however, the app only partially updated the intent value for expressions that were previously trained. Some of the expressions are trained to the new trait value, but others still retain the previous trait value.

Under Understanding, the app also wants to create a new value for the old intent trait value rather than the updated trait value. I have to manually select the proper intent while training now.

I also want to add that I made this change over 16 hours ago, so the app has had time to process this new trait value.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Change the trait value for an intent
2. Export app data
3. Search for any expressions tied to the previous trait value

**What is the expected behavior?**
The Wit app will update the intent value for all expressions previously trained to the intent. The Understanding tab will not pick up the previous intent value and will instead offer the new intent value as a match.

**Comment by patapizza** [comment]
Hi @hweiler,

Thanks for reporting.
What is the app id? What were the previous and new values?

**Comment by etbuilder** [comment]
@patapizza  from our side, the wit.ai is not reflecting new changes directly sometimes it takes a day or two event thought the training sign goes from the dots to green

This happened when adding new entries, old data and old trained model works perfectly.

**Comment by etbuilder** [comment]
@patapizza  my app id 5a6c8605-21b0-4d1e-a384-578c5d9ba327, I just trained another item to list another value, but still it shows the old value... the app started to work with the newly added data but after almost 20 hours.

**Comment by patapizza** [comment]
@etbuilder Do you still see the old value (which one is it?)? Do you have an example that doesn't work?
