### ISSUE TITLE
Programmatic training not working

### ISSUE THREAD

**Issue by SoumyaChaudhuri** [wit-ai/wit#999]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
*bug*

**What is the current behavior?**
Programmatic training seems to not be working without going into the UI and manually training a new piece of data.  Looks like a repeat of #966 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. PUT training data to https://api.wit.ai/entities/INTENT?v=20180215
2. Test new training data via API call = no entities found
3. Train unrelated data in UI
4. Test same training data from (2) = trained entity found

**What is the expected behavior?**
entities should be found

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by patapizza** [comment]
Hi @SoumyaChaudhuri, thanks for reporting.

I fixed something on our end, do you still experience the issue?

**Comment by etbuilder** [comment]
@patapizza The issue happens with trait entities even if trained from console, or exporting and importing to a new app, nothing get trained/updated even if i send an exact match

**Comment by SoumyaChaudhuri** [comment]
It's working for me now.
